### ISSUE TITLE
Ensure that go.mod replacements are kept in sync with k3s

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1001]
K3s has a number of replacements in go.mod. Unfortunately module replacements paths and versions are not transitive, so we need to specify the same replacements in the RKE2 go.mod. When we update the k3s module version here in RKE2, we need to make sure that any replacements we share with K3s are also updated.

Failure to do so may result in build failures or unexpected behavior, depending on the nature of the module replacement.

A proposed script to do this can be found at
https://gist.github.com/brandond/1b3cb66ea012564f886e2e9982bdce42

**Comment by brandond** [comment]
Tagged for 1.19 but this was an issue with both the 1.18 and 1.19 branches.

**Comment by davidnuzik** [comment]
Closing this one. Changes to be tested as a part of patch test plan test cases as well as conformance we execute. This should be sufficient.
