### ISSUE TITLE
add rke2 config pre-check/sanity check for cluster-dns setting

### ISSUE THREAD

**Issue by Sicaine** [rancher/rke2#1003]
**Is your feature request related to a problem? Please describe.**

When configuring the service-cidr, rke2 allows to configure the cluster-dns ip address wrong which will appear as an issue after the cluster was created.

`
service-cidr: 192.168.0.0/18
cluster-dns: 192.168.0.10
`

**Describe the solution you'd like**

A validation step before initializing the cluster would prevent potential time consuming forth and back when this error is already caught before the cluster is created.

Perhaps even going a step further and supporting a 'config test' step like what nginx supports (-t tests the config file only).

I had similiar configuration issues with wrong flags i used (i still had a rke2-server config flag in my rke2-agent config file)

**Comment by brandond** [comment]
It would be a lot of work to duplicate the configuration validation that Kubernetes itself already does. For args like this that we ensure default to something valid, but are passed through directly to Kubernetes if specified by the user, it is assumed that if you're overriding our default you're overriding it with something that actually works.
