### ISSUE TITLE
RKE2 config.yaml file doesn't exist in /etc/rancher/rke2/

### ISSUE THREAD

**Issue by Skipper0707** [rancher/rke2#1004]
The title is pretty much self-explanatory, in the documents it has been written that by default, RKE2 will launch with the values present in the YAML file located at /etc/rancher/rke2/config, although, there's no such file in that directory.
Where can I find it?

**Comment by brandond** [comment]
It's a configuration file, you create it, and put in there the values you want? You can use the example as a starting point.
https://docs.rke2.io/install/install_options/install_options/#configuration-file

**Comment by Skipper0707** [comment]
Thank you for your guidance, sorry if my question was a bit basic, I'm just an intern.
