### ISSUE TITLE
Rename RBAC resources for K3s integrated cloud-controller-manager

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1009]
**Description:**

Following up on discussion https://github.com/rancher/rancher/issues/32604#issuecomment-841470680. RKE2 also uses too generic of rbac role names for this ClusterRole and ClusterRoleBinding (`cloud-controller-manager`) and should consider changing these. **This also affects k3s.**

**Expected behavior:**

It would be better to use the role name `<k3s|rke2>-cloud-controller-manager`

**Additional context / logs:**

This is not a huge bug, but can cause problems such as the linked issue when using out of tree cloud providers in case they try to use the same generic name.

This is for the pullthrough of code from https://github.com/k3s-io/k3s/issues/3308

**Comment by brandond** [comment]
Duplicate of https://github.com/k3s-io/k3s/issues/3308 which is where this will need to be fixed.

**Comment by rancher-max** [comment]
Oops, I checked the wrong repo for the existence of this. Let's keep this around for the rke2 pull-throughs. I'll update description

**Comment by rancher-max** [comment]
#### Validated in master, commitid: `02557e771787f8c5ad12a22057050f87b2ec5b2c`

- RBAC resources have been renamed and node continues to properly set the ProviderID (whether using built in or external cloud provider):
```
$ k get clusterroles | grep -i cloud-controller-manager
rke2-cloud-controller-manager                                          2021-06-11T23:47:00Z

$ k get clusterrolebindings | grep -i cloud-controller-manager
rke2-cloud-controller-manager                          ClusterRole/rke2-cloud-controller-manager                          2m22s

$ k describe node | grep -i providerid
ProviderID:                   rke2://ip-172-31-37-156

# And on a setup using AWS cloud provider:
$ k describe nodes | grep -i providerid
ProviderID:                   aws:///us-east-2c/i-09f21ad2ef5332634
```

- This should also resolve one of the workarounds noted for when using rancher vsphere cloud provider. Result 1 in the issue description here: https://github.com/rancher/rancher/issues/32604
