### ISSUE TITLE
kube-proxy helm chart incorrectly quotes bool values

### ISSUE THREAD

**Issue by scila1996** [rancher/rke2#1010]
Hi ! I was installed RKE2 and Rancher Server success. But i want to edit kube-proxy config for metallb. I was do following document

https://docs.rke2.io/helm/

this is my helm chart config and i was applied them

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    mode: "ipvs"
    ipvs:
      strictArp: true
```

But seem like no thing happened. How can i reinstall or make them changed

**Comment by brandond** [comment]
That looks like the correct manifest to customize the rke2-kube-proxy chart, so it should work. However, the values you're passing aren't correct. You can look at the chart values.yaml to see what can be set:
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-kube-proxy/rke2-kube-proxy/v1.20.6-build2021041901/values.yaml#L119

For example, the mode should be set as:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    proxy:
      mode: ipvs
    ipvs:
      strictArp: true
```

**Comment by scila1996** [comment]
> That looks like the correct manifest to customize the rke2-kube-proxy chart, so it should work. However, the mode value you're passing isn't correct; it's nested in the 'proxy' section. You can look at the chart values.yaml to see what can be set:
> https://github.com/rancher/rke2-charts/blob/main/charts/rke2-kube-proxy/rke2-kube-proxy/v1.20.6-build2021041901/values.yaml#L119
> 
> For example, the mode should be set as:
> 
> ```yaml
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: rke2-kube-proxy
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     proxy:
>       mode: ipvs
>     ipvs:
>       strictArp: true
> ```

I was edited follow you and run `kubectl apply -f rke2-kube-proxy.yaml`. But still nothing happened , ex. update kube-proxy configmaps or pod need to recreate ? :(

**Comment by brandond** [comment]
Did it apply cleanly? You should see a helm job pod created to apply the changes. Is there some other output you're expecting?

**Comment by scila1996** [comment]
yes ! i see that job was run to update I was run 

```
kubectl get configmaps -n kube-system kube-proxy -o yaml
```

But strictArp seem like still is null ?

```                                                                                                                                                
apiVersion: v1
data:
  config.conf: "apiVersion: kubeproxy.config.k8s.io/v1alpha1\nbindAddress: \"0.0.0.0\"\nclientConnection:\n
    \ acceptContentTypes: \n  burst: \n  contentType: \n  kubeconfig: \"/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig\"\n
    \ qps: 5 \nclusterCIDR: \"10.42.0.0/16\" \nconfigSyncPeriod: 15m0s\nconntrack:\n
    \ maxPerCore: 32768\n  min: 131072\n  tcpCloseWaitTimeout: \n  tcpEstablishedTimeout:
    \ndetectLocalMode: \nenableProfiling: \nhealthzBindAddress: \"0.0.0.0:10256\"\nhostnameOverride:
    \niptables:\n  masqueradeAll: \n  masqueradeBit: 14\n  \n  syncPeriod: 30s\nipvs:\n
    \ excludeCIDRs: \n  \n  scheduler: \n  strictARP: \n  syncPeriod: 30s\n  \n  \n
    \ \nkind: KubeProxyConfiguration\nmetricsBindAddress: \"127.0.0.1:10249\"\nmode:
    \"ipvs\"\nnodePortAddresses: null\noomScoreAdj: -999\nportRange: \nshowHiddenMetricsForVersion:
    \nudpIdleTimeout: \"250ms\"\nfeatureGates:\nwinkernel:\n  enableDSR: false\n  networkName:
    \"\"\n  sourceVip: \"\""
...
```

**Comment by brandond** [comment]
You appear to have got the capitalization wrong.
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-kube-proxy/rke2-kube-proxy/v1.20.6-build2021041901/templates/config.yaml#L37

**Comment by scila1996** [comment]
Thank you ! it's work ! problem by me !

**Comment by scila1996** [comment]
Hi @brandond  . I found issue occured when i reboot all master node.

I was set kube-proxy helm by RKE2 with

`strictARP: true`

And all Pod rke2-kube-proxy was CrashLoopBackOff. after that, i check log pod and see this error

```
F0521 03:18:40.235057       1 server.go:488] failed complete: failed to decode: v1alpha1.KubeProxyConfiguration.IPVS: v1alpha1.KubeProxyIPVSConfiguration.StrictARP: ReadBool: expect t or f, but found ", error found in #10 byte of ...|rictARP":"true","syn|..., bigger context ...|"excludeCIDRs":null,"scheduler":null,"strictARP":"true","syncPeriod":"30s"},"kind":"KubeProxyConfigu|...
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0003c0000, 0x180, 0x1d2)
        /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2a73fa0, 0xc000000003, 0x0, 0x0, 0xc000247110, 0x2991b66, 0x9, 0x1e8, 0x0)
        /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printf(0x2a73fa0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1ca2cf4, 0x13, 0xc000595d20, 0x1, ...)
        /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
        /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc0002742c0, 0xc00050d640, 0x0, 0x2)
        /go/src/github.com/kubernetes/kubernetes/cmd/kube-proxy/app/server.go:488 +0x136
github.com/spf13/cobra.(*Command).execute(0xc0002742c0, 0xc00003c190, 0x2, 0x2, 0xc0002742c0, 0xc00003c190)
        /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002742c0, 0xc00007e180, 0x2a73b60, 0x408685)
        /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        github.com/kubernetes/kubernetes/cmd/kube-proxy/proxy.go:48 +0x11d
```

in RKE2 template kube-proxy. Why you qoute value "true" ? please remove qoute function in helm chart template !

https://github.com/rancher/rke2-charts/blob/main/charts/rke2-kube-proxy/rke2-kube-proxy/v1.20.6-build2021041901/templates/config.yaml#L37

**Comment by brandond** [comment]
That does look problematic. I'm confused as to how this appeared to be working previously?

**Comment by scila1996** [comment]
> That does look problematic. I'm confused as to how this appeared to be working previously?

Before ! i was update helmchartconfig but not delete kube-proxy pod to reload or reboot node, yesterday, i was reboot a node and it crash kube-proxy on that node. Next, i delete kube-proxy pod to recreate on other node and crash too. But error is clearly, boolvalue can't be qouted 😢

**Comment by cjellick** [comment]
Needs moved to-test and @brandond needs to create backport issues for all the branches it is on.

**Comment by brandond** [comment]
Backport issues open and linked

**Comment by ShylajaDevadiga** [comment]
Reproduced the issue in v1.20.7+rke2r2  after node reboot kube-proxy CrashLoops with below error
```
$ kubectl logs  -n kube-system kube-proxy-b2s6h 
F0622 19:59:38.992835       1 server.go:488] failed complete: failed to decode: v1alpha1.KubeProxyConfiguration.IPVS: v1alpha1.KubeProxyIPVSConfiguration.StrictARP: ReadBool: expect t or f, but found ", error found in #10 byte of ...|rictARP":"true","syn|..., bigger context ...|"excludeCIDRs":null,"scheduler":null,"strictARP":"true","syncPeriod":"30s"},"kind":"KubeProxyConfigu|...
goroutine 1 [running]:
```
Validated fix using rc, v1.21.2-rc1+rke2r1, kube-proxy is in running state after roboot
```
$ kubectl get configmaps -n kube-system kube-proxy -o yaml
apiVersion: v1
data:
  config.conf: "apiVersion: kubeproxy.config.k8s.io/v1alpha1\nbindAddress: \"0.0.0.0\"\nclientConnection:\n
    \ acceptContentTypes: \n  burst: \n  contentType: \n  kubeconfig: \"/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig\"\n
    \ qps: 5 \nclusterCIDR: \"10.42.0.0/16\"\nconfigSyncPeriod: 15m0s\nconntrack:\n
    \ maxPerCore: 32768\n  min: 131072\n  tcpCloseWaitTimeout: \n  tcpEstablishedTimeout:
    \ndetectLocalMode: \nenableProfiling: \nhealthzBindAddress: \"0.0.0.0:10256\"\nhostnameOverride:
    \niptables:\n  masqueradeAll: \n  masqueradeBit: 14\n  \n  syncPeriod: 30s\nipvs:\n
    \ excludeCIDRs: \n  \n  scheduler: \n  strictARP: true\n  syncPeriod: 30s
```

**Comment by Wolskie** [comment]
Just deployed the following fresh:

```
/us/local/bin/rke2 --version
rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
```

`kube-proxy` prod crashlooping.

```
 kubectl get configmaps -n kube-system kube-proxy -o yaml
...
<snip>  strictARP: \"true\"\n <snip> 
```

**Comment by brandond** [comment]
How have you customized you rke2 kube-proxy configuration?

**Comment by Wolskie** [comment]
We have done so by creating the file `/var/lib/rancher/rke2/server/manifests/rke2-kube-proxy-config.yaml`  with the following contents:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    proxy:
      mode: "ipvs"
    ipvs:
      strictARP: true
```
