### ISSUE TITLE
--disable-api-server flag name is inconsistent with other apiserver flags

### ISSUE THREAD

**Issue by MonzElmasry** [rancher/rke2#1019]
The --disable-api-server CLI flag is inconsistent with other flags, where it is referred to as upstream does (apiserver). This should be corrected to --disable-apiserver, and the incorrect version kept around as a hidden deprecated flag.

This was flagged but not resolved in peer review https://github.com/k3s-io/k3s/pull/2900#discussion_r574169383

**Comment by ShylajaDevadiga** [comment]
Validated in rke2 version v1.21.1-alpha5+rke2r1
```
 $ cat /etc/rancher/rke2/config.yaml 
token: secret
disable-apiserver: true
disable-scheduler: true
disable-controller-manager: true

$ kubectl get nodes
NAME              STATUS   ROLES                  AGE     VERSION
ip-172-31-3-251   Ready    etcd                   3h39m   v1.21.1-alpha5+rke2r1
ip-172-31-5-82    Ready    control-plane,master   3h39m   v1.21.1-alpha5+rke2r1
```

Waiting on rc's to validate backports on earlier versions

**Comment by ShylajaDevadiga** [comment]
Validated on v1.20.7-rc1+rke2r1, v1.19.11-rc1+rke2r1, v1.18.19-rc1+rke2r1
