### ISSUE TITLE
Add ability to customize etcd extra_args

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1021]
Add ability to customize etcd extra_args

**Comment by mddamato** [comment]
Would like to see this

**Comment by Oats87** [comment]
With the merging of the PRs for: https://github.com/rancher/rke2/issues/1233 and https://github.com/rancher/rke2/issues/1525 you can now set custom arguments by setting extra environment variables for the etcd pod. This is not ideal, but is a workaround for now until I figure out how to get extra args to work for etcd
