### ISSUE TITLE
Investigate how 1.22 deleted APIs may affect us

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1026]
We should investigate how 1.22 deleted APIs may affect us. Seems like it could impact helm charts.
Additionally, there could be some impact to K3S as well.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22 seems like it should reveal what we need to be aware of; it will need review and we'll need to consider everywhere in K3s and RKE2 projects this could impact us.

We should investigate and prepare for this well before 1.22 releases. ([Date here](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.22#tldr)) but as of the time I'm writing this they plan to release August 4th.

Additional Charts: 
- rancher-sriov chart for SR-IOV networks management
- system-upgrade-controller

**Comment by davidnuzik** [comment]
Also note as of May 21st: The latest wrangler has been bumped to use v1 instead of v1beta1. So we should upgrade to v1 asap using latest wrangler, since v1beta1 crd will be removed starting from k8s v1.22.

**Comment by davidnuzik** [comment]
If/when we identify deleted APIs in 1.22 that will affect us, we should do our part and **update our internal "Kubernetes 1.22 Checklist" confluence page with our findings**.

**Comment by brandond** [comment]
Some assistance from @ibuildthecloud in getting things migrated over to newer versions of wrangler, or some primer on what all needs to be changed, would be appreciated. I took a shot at doing so myself a while back and it seems like mostly changing a lot of boilerplate controller setup code, but I don't have a good feel for how to approach it.

**Comment by davidnuzik** [comment]
Could have an impact on PSP as well.

**Comment by brandond** [comment]
We'll need to bump the metrics-server version to 0.5.0 for Kubernetes API updates - logs from 0.3.6 contain the following warning:
```
I0607 19:22:24.140911       1 round_trippers.go:438] POST https://10.43.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews 201 Created in 15 milliseconds
I0607 19:22:24.140934       1 round_trippers.go:444] Response Headers:
I0607 19:22:24.140941       1 round_trippers.go:447]     Cache-Control: no-cache, private
I0607 19:22:24.140946       1 round_trippers.go:447]     Content-Type: application/json
I0607 19:22:24.140951       1 round_trippers.go:447]     Warning: 299 - "authorization.k8s.io/v1beta1 SubjectAccessReview is deprecated in v1.19+, unavailable in v1.22+; use authorization.k8s.io/v1 SubjectAccessReview"
```
