### ISSUE TITLE
nginx in rke2 v1.20.6 fails intermittently with http code 502

### ISSUE THREAD

**Issue by grk-pancham** [rancher/rke2#1044]
RKE2 Version: 
rke2 version v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 
Linux  #1 SMP Thu Jan 21 16:15:07 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
6 nodes cluster with 3 master and 3 worker nodes

**Describe the bug:**
We are using nginx controller that gets installed with rke2. We get intermittent errors when we try to access the services via nginx. It returns http code 502 to client browser. This was working fine with open source rke v1.19.6. We also  upgraded nginx in rke2 to 0.35.0-rancher2 from 0.30.0-rancher1 but with no luck. It works fine if we skip the nginx and directly access the services using NodePort.

**Expected behavior:**
We should be able to access services via nginx reverse proxy without errors.

**Actual behavior:**
nginx in rke2 v1.20.6  intermittently returns http code 502 to client browser

**Comment by brandond** [comment]
> This was working fine with open source rke v1.19.6. 

Do you mean RKE, or RKE2? The two projects have very little in common, other than both belonging to Rancher

> nginx in rke2 v1.20.6 intermittently returns http code 502 to client browser

Can you provide logs from the nginx pods during the period in which they are returning 502 errors?

**Comment by grk-pancham** [comment]
We upgraded to RKE2 v1.20.6 from RKE. I do not see anything related to 502 issue in any of the 3 nginx controller logs.

**Comment by brandond** [comment]
How exactly did you upgrade from RKE1 to RKE2?

What *do* the logs show for this time period? Do the upstream pod logs show any attempted requests? It's hard to troubleshoot an issue without any logs showing an error.

**Comment by grk-pancham** [comment]
I know, that's exactly where i am lost too.

We used the tar method to install RKE2 and start the service. everything comes up correctly and is up and running. nginx logs should messages when we try to access any services via ngnix. but I do not see any messages in nginx logs when we get 502. 

Also this is intermittent issue but fairly reoccurring impact our build pipelines which fail to access services deployed in RKE2. I will try to repeat the process one more time and see if i see any log activity.

**Comment by brandond** [comment]
I'm confused though since you said you upgraded from RKE. Did you install RKE2 on top of an existing RKE installation? Or is this a new clean installation that you are migrating your workloads into?

**Comment by grk-pancham** [comment]
This is new clean installation of RKE2 on new servers and NOT an upgrade of existing RKE

**Comment by brandond** [comment]
Thanks, that helps.

Is there any additional context you can provide around the 502s? Errors from other pods or control-plane components, etc? I've not seen any other reports of errors caused by RKE2's deployment of the ingress.

**Comment by grk-pancham** [comment]
There are no errors in any of the pod services logs. Not sure what i missing. 

I also tried using http port instead of https port to access nginx in NodePort service but still no luck.
