### ISSUE TITLE
Allow configuring resource requests and limits for control-plane static pods

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1046]
**Is your feature request related to a problem? Please describe.**
Allow configuring resource requests and limits for control-plane static pods

**Describe the solution you'd like**

Allow setting requests and limits via two new flags: `control-plane-resource-requests` and `control-plane-resource-limits`. 

These would be structured much like the [kubelet system-reserved flag](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved). The bare `cpu`, `memory`, and `ephemeral-storage` keys are honored as a default for all components. Component-specific overrides can also be specified, in the form of `<NAME>-<RESOURCE>` for example `etcd-cpu`, `kube-apiserver-memory`, `kube-controller-manager-ephemeral-storage` et cetera.

We **should** include the `kube-` prefix on these, as this is the convention for the CLI pasthrough flags (`kube-apiserver-arg`, et al).

Example:  
* `--control-plane-resource-requests=[cpu=100m][,][memory=100Mi][,][ephemeral-storage=1Gi][,][etc-cpu=100m][,][etcd-memory=100Mi][,][etcd-ephemeral-storage=1Gi]`
* `--control-plane-resource-limits=[cpu=100m][,][memory=100Mi][,][ephemeral-storage=1Gi][,][kube-apiserver-cpu=100m][,][kube-apiserver-memory=100Mi][,][kube-apiserver-ephemeral-storage=1Gi]`

**Describe alternatives you've considered**
* Do nothing, continue to only use the embedded default CPU requests
* Allow the user to provide a 'template' static pod manifest for each component that we merge our desired configuration into, and document which fields in the manifest we overwrite or merge.    
    * This was decided against as being documentation-heavy, in addition to the fact that we currently blindly overwrite and/or delete the static pod manifests during cluster startup or reconfiguration.

**Additional context**
cc @nikkelma @Oats87

**Comment by Oats87** [comment]
Consolidating this issue to https://github.com/rancher/rke2/issues/1233
