### ISSUE TITLE
Pod communication not working on RHEL 8.4 on cloud providers

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#1053]
**Environmental Info:**
RKE2 Version: v1.20.7+rke2r1

Node(s) CPU architecture, OS, and Version: 
`Linux hostname 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
`Red Hat Enterprise Linux release 8.4 (Ootpa)`

Cluster Configuration: Single node.

**Describe the bug:**
Pod communication is not possible when running on a RHEL 8.4 host on AWS, regardless of selinux status.

**Steps To Reproduce:**
```
mkdir -p /etc/rancher/rke2/
systemctl stop firewalld
cat > /etc/rancher/rke2/config.yaml <<EOF
selinux: true
write-kubeconfig-mode: "0644"
EOF
curl -sfL https://get.rke2.io --output install.sh
chmod +x install.sh
INSTALL_RKE2_CHANNEL=stable ./install.sh
systemctl enable rke2-server.service --now
```

Wait for RKE2 server to start and pods to start, and try to `ping` any pod IP in the `10.42.x.x` range.

**Expected behavior:**
Pods can talk.

**Actual behavior:**
Pods don't talk.

**Additional context / logs:**
Looking at a `tcpdump` from within the container, you can see the corresponding ICMP request/reply, so the pod is definitely receiving the traffic. It seems to be getting lost heading back to the host network namespace.

This does not occur on VMs running in our test environment that are running RHEL 8.4

selinux status does not seem to affect the issue.

**Comment by Oats87** [comment]
Investigating this with @manuelbuil we found that we did not have issues on RHEL 8.3 AMI.

We also did not have any issues with our internal lab environment running 8.3 and 8.4.

We discovered a difference in the two AMIs, that there are new services (`nm-cloud-setup.service`, `nm-cloud-setup.timer`) that are enabled on the nodes. Disabling these i.e. `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` and rebooting the node restored connectivity on the node.

More work will need to be done to investigate why `nm-cloud-setup` is causing us issues when it is running.

**Comment by brandond** [comment]
It's Always NetworkManager.

**Comment by manuelbuil** [comment]
nm-cloud-setup creates a policy based route table more prioritized than the main routing table. That table only applies to packets with source-ip of the main interface ip and basically sets the default gateway to what the cloud provider announced as the gateway. For example. table 30400 in this case:
```
[ec2-user@ip-10-0-10-5 ~]$ ip rule
0:	from all lookup local
30400:	from 10.0.10.5 lookup 30400
32766:	from all lookup main
32767:	from all lookup default
```
That table is breaking the connectivity node<-->local_pod. As soon as that table is removed, the connectivity works again. This behaviour applies to the main interface, therefore, the current recommended configuration in rke2 for network manager https://docs.rke2.io/known_issues/#networkmanager does not fix this. According to the docs, the creation of that policy based route table is always done: https://www.mankier.com/8/nm-cloud-setup#Supported_Cloud_Providers.

I created an issue in the NetworkManager gitlab asking for a config to avoid this problem ==> https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/740. My suggestion is to wait for an answer. In the meantime, we need to do as Chris said `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` or remove that table (but if NetworkManager restarts, it'll be recreated)

**Comment by Oats87** [comment]
We should probably cross-file an issue over at https://github.com/flannel-io/flannel

**Comment by manuelbuil** [comment]
Reported it in calico as it seems more people are affected: https://github.com/projectcalico/calico/issues/4662

**Comment by manuelbuil** [comment]
I think can close this one. Calico guys are saying that it should be disabled.

- Docs updated saying nm-cloud-setup should be disabled
- Both rke2 and k3s systemd file updated. They will not run if nm-cloud-setup is enabled

**Comment by brandond** [comment]
QA should test the change that was made to the systemd unit.

**Comment by manuelbuil** [comment]
@brandond right! I don't know why I closed it directly :/

**Comment by rancher-max** [comment]
Validated on master branch commit `f23f5915ee3d3270bad235e26c8c54e8c3c0cf76` using the same steps as in https://github.com/rancher/rke2/issues/1670#issuecomment-904167578

**Comment by afvrns** [comment]
It looks like NetworkManager fixed the issue a few months after the problem was raised, specifically in [this merge request](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/974), release in NM 1.32.
