### ISSUE TITLE
[release-1.20] opa-gatekeeper on rke2 cluster disallows cluster members to join after reboot and stay in NotReady state

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1056]
Backport fix for #1054 to release-1.20 branch

**Comment by davidnuzik** [comment]
Assigned to @rancher-max and put in v1.20.7+rke2r2 milestone.

**Comment by rancher-max** [comment]
#### Validated in v1.20.7-rc1+rke2r2

Following the steps noted in the original issue, the node becomes Ready after reboot and is functional, as workloads are able to be deployed to it still.
