### ISSUE TITLE
[release-1.19] opa-gatekeeper on rke2 cluster disallows cluster members to join after reboot and stay in NotReady state

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1057]
Backport fix for #1054 to release-1.19 branch

**Comment by davidnuzik** [comment]
Created v1.19.12+rke2r2 and assigned to this milestone.

**Comment by rancher-max** [comment]
#### Validated in v1.19.12-rc1+rke2r1

- Node becomes Ready after reboot and is functional
- Workloads are able to be deployed to all nodes still after reboot
