### ISSUE TITLE
How to switch CNI from default calico to cilium

### ISSUE THREAD

**Issue by scila1996** [rancher/rke2#1072]
Hi all

I was deploy RKE2 Cluster and it's running. But i want switch CNI to cilium. How can i do ? just add "cni: cilium" to /etc/rancher/rke2/config.yaml or more step ?

**Comment by brandond** [comment]
You can try that, but in general CNI switches on an existing cluster are not well supported. In general you should decide what CNI you want to use before starting the cluster for the first time.
