### ISSUE TITLE
RKE2 fails when run in Docker on nodes with >8 cores

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1080]
Kube-proxy fails when run in Docker on nodes with >8 cores, as it tries to set a read-only module parameter based on a variable that is scaled by core count:
```console
[BASICS] I0528 16:51:45.880327       1 conntrack.go:83] Setting conntrack hashsize to 131072
[BASICS] F0528 16:51:45.880373       1 server.go:489] write /sys/module/nf_conntrack/parameters/hashsize: operation not supported
```

This is blocking @paraglade from upgrading our CI runners to anything with more cores than a `m5.2xlarge`.

We recently fixed an issue with K3s kube-proxy not being able to set sysctls when run in docker with https://github.com/k3s-io/k3s/pull/3337 - we basically had the supervisor take over setting sysctls, and disable them in the embedded kube-proxy.
We’re now hitting the same issue with RKE2, where our CI tests are failing on larger nodes because the sysctls scale with core count, and RKE2-in-docker can’t set the sysctls and crashes, same as K3s was doing. The K3s fix won’t work here, because we deploy kube-proxy as a helm chart, and the kube-proxy-args from the CLI (or set internally by the supervisor) are ignored. 

I have long wanted to [make kube-proxy a static pod](https://github.com/rancher/rke2/issues/751), same as everything else. This would fix multiple issues around behavior consistency and configurability, and would also address the current issue.. This would be a breaking change; I think 1.21 is a good time to do it.

Alternatives would be:
1. Pass through --kube-proxy-args from the server CLI into the kube-proxy helm chart. This is problematic, because kube-proxy has a number of tunables that really should be configurable on a per-node basis - what works for one node may not work for all.
2. Just hardcode the sysctl flags to 0 in the kube-proxy helm chart, knowing that we’re setting them in the supervisor. This is a viable workaround for the current issue, but doesn't make life any easier for users who expect `--kube-proxy-args` to work properly.

**Comment by brandond** [comment]
Chatted briefly with @ibuildthecloud about this on Slack:
> I don't see any particular downsides of running as a static pod.  Now's a good time to do that before its' in Rancher.
> I think I'd actually prefer it to be a static pod.

https://rancher.slack.com/archives/CRF4B1J8H/p1622239561344400?thread_ts=1622238445.339000&cid=CRF4B1J8H

**Comment by davidnuzik** [comment]
Blocking EIO team, to be worked on immediately after v1.21.1+rke2r1 release is done.

**Comment by cjellick** [comment]
@davidnuzik to follow up to get a good handle on criticality and see if we can bump out.

**Comment by davidnuzik** [comment]
This will be fixed by the kube-proxy static pod work that @phillipsj is working on. Brad mentioned it sounds like it may be done by the end of the week.

**Comment by davidnuzik** [comment]
@phillipsj on the basis that this should get fixed based on your kube-proxy static pod work, I'd like to assign this issue to you. When that work is complete, could you just move this issue's status to "To Test" so I can take over and work with devs/EIO team to give this another test in CI?

**Comment by davidnuzik** [comment]
I removed myself from assignment on this issue since I am no longer on the team. I believe Brad has a good understanding of this and can help and work with EIO to test this.

**Comment by cwayne18** [comment]
Is this still an issue @brandond
