### ISSUE TITLE
Support INSTALL_RKE2_EXEC as alias for INSTALL_RKE2_TYPE

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1082]
RKE2's installer is inconsistent in how it selects between server/agent, compared to K3s.

* RKE2 uses `INSTALL_RKE2_TYPE=server|agent` to select between the two install types.
* K3s uses `INSTALL_K3S_TYPE=notify|exec`; this controls the type of systemd unit generated, NOT the node type.
* K3s uses the first arg from `INSTALL_K3S_EXEC` to determine if server or agent is wanted, in addition to looking at whether K3S_URL is set.

For improved compatibility between the two scripts, it would be nice if the RKE2 installer supported `INSTALL_RKE2_EXEC` as an alias for `INSTALL_RKE2_TYPE`, so that `INSTALL_<X>_EXEC=server|agent` worked identically on both products. RKE2 should not support any values for this variable other than `server` or `agent`, as they will not be passed through into the systemd unit as they are on K3s.

Submitted for @ibuildthecloud 
![image](https://user-images.githubusercontent.com/370103/120050414-2170a580-bfd2-11eb-99b2-3d061c95047a.png)

**Comment by davidnuzik** [comment]
Now that's the right amount of flair!

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.21.1-rc2+rke2r1 on one master one agent setup.
Installed master node using
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.21.1-rc2+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -
```
Joined agent node using
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.21.1-rc2+rke2r1 INSTALL_RKE2_CHANNEL=testing INSTALL_RKE2_EXEC='agent' sh -
```
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE    VERSION
ip-172-31-15-118   Ready    <none>                      49m    v1.21.1-rc2+rke2r1
ip-172-31-15-127   Ready    control-plane,etcd,master   6h8m   v1.21.1-rc2+rke2r1
```
