### ISSUE TITLE
Integrated `cloud-controller-manager` causes unnecessary restarts of `rke2` service when leaderelection is lost

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#1085]
**REQUIRES BACKPORT to 1.20** 
See issue https://github.com/rancher/rke2/issues/1098

**Environmental Info:**
RKE2 Version: `v1.20.7+rke2r2`

Node(s) CPU architecture, OS, and Version: Irrelevant

Cluster Configuration: 3 servers

**Describe the bug:**
Under specific scenarios in which there may be a slow etcd/slow kube-apiserver and the integrated `cloud-controller-manager` loses leader election, it will cause the entire `rke2-server` process to panic along with it. This is unnecessarily disruptive, as this causes things like the `kubelet` to restart.

**Steps To Reproduce:**
Just, have a slow system and have the `cloud-controller-manager` lose leader election and observe that the `systemd` unit for `rke2-server` goes into a `Failed` state, and is subsequently restarted by `systemd`.

**Expected behavior:**
`cloud-controller-manager` should not be causing the entire `rke2-server` process to be restarted if it fails.

**Actual behavior:**
`cloud-controller-manager` drags the entire house down with it.

**Additional context / logs:**

I'm thinking we should either make it so that the `cloud-controller-manager` does not have the ability to cause the upstream `rke2` process to fail, or we should put the `cloud-controller-manager` into a static pod.

**Comment by brandond** [comment]
We should probably move this controller out to a static pod and stop running it in the supervisor process. Doing that would accommodate some long-overdue code cleanup on the k3s side to make it use the cloud controller manager code the way upstream intends.

**Comment by Oats87** [comment]
https://github.com/k3s-io/k3s/issues/2697

**Comment by cjellick** [comment]
We are actively working on this, but the code freeze for 1.21.2 is today, so we need to push to 1.21.3

**Comment by Oats87** [comment]
Relies on https://github.com/k3s-io/k3s/issues/2697 and https://github.com/k3s-io/k3s/pull/3525

**Comment by rancher-max** [comment]
#### Validated on master branch using commitid `41d9fc0b3bf4673edd36de76735ab8d1956b93a9`

- When cloud-controller-manager is enabled, the providerid is set. The uninitialized taint is temporarily set until the CNI pod becomes Running. Additionally, the following node annotations exist: `rke2.io/hostname`, `rke2.io/internal-ip`
- When it is disabled, it is correctly not setting providerid.
