### ISSUE TITLE
Update CIS Etcd User Creation Documentation for SLES Specific Installations

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1087]
A user in Slack identified an issue with documentation when install on SLES that depending on the configuration in `/etc/login.defs`, a group will not be created by default when a user is created. This deviates from the normal observed behavior of `useradd` in most distributions. 

We should update documentation to call out that on SLES, the "etcd" group may need to be created first and subsequently referenced in the `useradd` command that creates the "etcd" user.

**Comment by brandond** [comment]
I think you can just add `-U/--user-group` to useradd to ask for a user-named group, even if that's not the default behavior.

**Comment by briandowns** [comment]
Completed in #1089
