### ISSUE TITLE
Ingress controller pods stuck terminating after upgrade

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1093]
**Environmental Info:**
RKE2 Version: 

v1.20.6 upgraded to v1.21.1-rc2

Node(s) CPU architecture, OS, and Version: 
Validated this occurs regardless of OS. Confirmed on Centos8, SLES15SP2, and Ubuntu 20.04 LTS

Cluster Configuration:

My configuration was generally 3 server, 2 agents. The more nodes, the more likely this is to happen.

**Describe the bug:**

After upgrading to v1.21.1-rc2, which also upgrades the ingress-nginx-controller and changes it to a daemonset, some of the new pods created for that were stuck in Terminating state. The kubelet appears to be trying to mount a secret that no longer exists. Probably related to https://github.com/kubernetes/kubernetes/issues/70044 and https://github.com/rancher/rke2/issues/1092.

pod shows:

```
  Normal   Killing      35m                 kubelet                   Stopping container rke2-ingress-nginx-controller
  Warning  Unhealthy    35m (x2 over 35m)   kubelet                   Readiness probe failed: HTTP probe failed with statuscode: 500
  Warning  FailedMount  34s (x25 over 35m)  kubelet                   MountVolume.SetUp failed for volume "rke2-ingress-nginx-v3-token-d8bpb" : secret "rke2-ingress-nginx-v3-token-d8bpb" not found
```

Workaround - delete these stuck pods after upgrade:

`kubectl get pod -n kube-system | awk '/rke2-ingress-nginx-v3-controller.*Terminating/ {print $1}' | xargs kubectl delete pod -n kube-system --force`

**Steps To Reproduce:**

- Installed rke2 v1.20.6 
- Upgrade to v1.21.1-rc2 using rancher or SUC. This also seems to happen with curl upgrade as well, but I validated using SUC.

**Expected behavior:**

Pods should not be stuck terminating

**Comment by Oats87** [comment]
This was most likely caused by: https://github.com/kubernetes/kubernetes/issues/70044#issuecomment-853517954

I think a question we should also be asking is what happened to the original SA token?

**Comment by brandond** [comment]
As of 1.21, bound service account tokens are tied to the pod lifecycle, and are deleted when the pod is deleted. This means that the token can't be remounted if the kubelet tries to raise terminated pod from the dead.
Ref:  https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume

**Comment by Oats87** [comment]
Hmm, and considering this is happening on upgrade from 1.20 to 1.21, I wonder if the tokens are being deleted prematurely... maybe we need to keep that feature gate off for now?

**Comment by rancher-max** [comment]
It makes some sense. The flow as far as I can tell is:
1. Upgrade happens on one server node. This updates ingress-nginx-controller to be a daemonset, which then deploys on all nodes
2. Upgrade happens on next server node. This might kill the controller pod (and its associated service account token?) that was running on this node
etc.

**Comment by rancher-max** [comment]
#### Validated this is working using v1.21.1-rc3+rke2r1

- Using curl, SUC (manually), and SUC (through Rancher), upgrades, controller pods no longer get stuck in Terminating state
- Occassionally, the default-backend pod will get stuck in Terminating, which can be deleted using --force without any noticeable side effects
- Validated rke2-ingress-nginx is correctly using bumped image: `rancher/nginx-ingress-controller:nginx-0.46.0-rancher1`
