### ISSUE TITLE
Port 9345 necessary after all nodes are registered?

### ISSUE THREAD

**Issue by seimic** [rancher/rke2#1097]
Hi,

could someone tell me if the registration port 9345 for new cluster nodes is necessary after 
all cluster nodes joined the cluster? I'm using a load balancer that has both, external and 
internal ip. I would like to close this hole to make sure, nothing is able to join the cluster
or do some DoS stunts on it.
A connection can only become established with a valid token I know but I prefer the LB to
tell 'f...off' instead to let the connection pass the border.

Thanks,
Michael

**Comment by brandond** [comment]
Yes, you still need to have the supervisor port open on servers after nodes join the cluster.

**Comment by seimic** [comment]
Ahh OK, thanks :)
