### ISSUE TITLE
[1.20 backport] Integrated `cloud-controller-manager` causes unnecessary restarts of `rke2` service when leaderelection is lost

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1098]
_**Below is copied from parent issue, https://github.com/rancher/rke2/issues/1085**_

**Environmental Info:**
RKE2 Version: `v1.20.7+rke2r2`

Node(s) CPU architecture, OS, and Version: Irrelevant

Cluster Configuration: 3 servers

**Describe the bug:**
Under specific scenarios in which there may be a slow etcd/slow kube-apiserver and the integrated `cloud-controller-manager` loses leader election, it will cause the entire `rke2-server` process to panic along with it. This is unnecessarily disruptive, as this causes things like the `kubelet` to restart.

**Steps To Reproduce:**
Just, have a slow system and have the `cloud-controller-manager` lose leader election and observe that the `systemd` unit for `rke2-server` goes into a `Failed` state, and is subsequently restarted by `systemd`.

**Expected behavior:**
`cloud-controller-manager` should not be causing the entire `rke2-server` process to be restarted if it fails.

**Actual behavior:**
`cloud-controller-manager` drags the entire house down with it.

**Additional context / logs:**

I'm thinking we should either make it so that the `cloud-controller-manager` does not have the ability to cause the upstream `rke2` process to fail, or we should put the `cloud-controller-manager` into a static pod.

**Comment by cjellick** [comment]
@fapatel1 to follow up with @Oats87  - This has missed the deadline

**Comment by Oats87** [comment]
Relies on https://github.com/k3s-io/k3s/issues/3528 and https://github.com/k3s-io/k3s/pull/3531

**Comment by rancher-max** [comment]
#### Validated with v1.20.8-rc1+rke2r2

- When cloud-controller-manager is enabled, ProviderID is properly set. The expected node annotations exist: `rke2.io/hostname`, `rke2.io/internal-ip`
- When it is disabled, it not setting ProviderID as expected
