### ISSUE TITLE
Update Cilium to v1.9.8

### ISSUE THREAD

**Issue by mrostecki** [rancher/rke2#1099]
We would like to update Cilium to v1.9.8 in order to get latest bug fixes and features.

**Comment by rancher-max** [comment]
Validated this version is available on release-1.21 branch. Waiting for rc to do quick validation and additional confirmation of sonobuoy conformance checks and that networking checks continue to work.

**Comment by rancher-max** [comment]
#### Validated in v1.21.2-rc1+rke2r1

- Cilium version 1.9.8 is being used
- Networking checks continue to pass
- Conformance tests continue to pass
