### ISSUE TITLE
Ability to pass alternate encryption config

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#1105]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.1-rc2+rke2r1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single Node

**This needs testing:**
Using valid alternate encryption config should work

**To Test:**
- Create a encryption config file and pass it to kube-apiserver-arg through encryption-provider-config
- Validate that the secrets are created using the encryption specified in the config

**Expected behavior:**
Alternate valid encryption config should work

**Comment by ShylajaDevadiga** [comment]
Passing the encryption config below through kube-apiserver-arg, verified it works as expected.
```
$ cat /etc/rancher/rke2/secretsconfig
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: BiZm6VfQPotszRa+0uYI8g80O8sHQnnGfdrJayLS7as=
    - identity: {}
```
Encrypted secret
```
/registry/secrets/default/secret1
k8s:enc:aesgcm:v1:key1:06?pG?a՝?-?k?f????Ab?a?Xz?????C+Q??#?\??J????????Ř:R?????Komv???f??`X????i?L?j?W?
                                                                                                        8M%-d????M?8P??7?nǓL?6?0?c)'?f????A?:T?m?3???-<?x՛ɭ?n???????b?>f??jZW?????'??9'8???Tr?????C@C	%???-gI????{??h?
?{=?>
```

**Comment by brandond** [comment]
@ShylajaDevadiga can you try the configuration I posted?

**Comment by ShylajaDevadiga** [comment]
@brandond using your configuration above, validated secrets are not encrypted
Created secret from file with below content
```
touch file && echo "hello" > file
```
```
registry/secrets/default/test
k8s


v1Secret?
?
testdefault"*$9395b5bf-fb0d-480a-bfe8-57566c8c63872Ș??z?_
kubectl-createUpdatevȘ??FieldsV1:-
+{"f:data":{".":{},"f:file":{}},"f:type":{}}
filehello
Opaque"
```
