### ISSUE TITLE
Add Status Subcommand

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1107]
From original issue: https://github.com/rancher/rke2/issues/989

rke2 should also provide a rke2 status command that exposes component status. This could be retrieved from component readyz status, or simply kubelet + static pod container status (uptime and restarts)

**Comment by briandowns** [comment]
@ibuildthecloud @Oats87 @brandond Is this a feature we still need?

**Comment by caroline-suse-rancher** [comment]
Closing due to age and inactivity
