### ISSUE TITLE
Standardize logging format for RKE2 such that a timestamp is provided in log messages in a consistent manner

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#1110]
**Is your feature request related to a problem? Please describe.**
RKE2 currently logs to `stdout`/`stderr`. The issue with this, is that the timestamp that correlates with the journal entry is more of a `received at`. In addition, getting this timestamp data out of the journal message entries with `fluent-bit` has proven to be difficult. As per @paynejacob , 
>Systemd journal can consume logs in a few different ways, it is stored with the log message under the _TRANSPORT key.  in the case of rke2 and k3s the logs are using the stdout transport.  The stdout transport does not record the timestamp as accurately as other transport protocols such as journal.  When fluent-bit aggregates logs it does not receive the the timestamp fields with logs using the stdout transport.
>See Address Fields https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html

**Describe the solution you'd like**
We should 
1. Remove the `cloud-controller-manager` component from running under `rke2`, so that we don't have `klog` formatted logs mixed with our RKE2 logs. This is being handled by https://github.com/rancher/rke2/issues/1085
2. We should standardize the format of the logs RKE2 generates so that we can write a parser that accurately records timestamps along with log data.

There is an issue, in that we have `containerd` and (seemingly) `etcd` logs from snapshot operations that use `logrus` but in their own format. We don't directly control those.

**Comment by brandond** [comment]
We also get kubelet logs on stdout/stderr.

**Comment by briandowns** [comment]
etcd is using zap logger and allows for a config to be passed into the new client setup. We might be able to override defaults and get it in alignment with whatever standard we come up with.

**Comment by brandond** [comment]
Our current pattern for writing to a log file sees us reexecing with reopened stdout/stderr, which breaks systemd notifications. We should probably fix that while we're at it.
