### ISSUE TITLE
`--cloud-provider-name=vsphere` breaks use of in-tree vsphere cloud provider

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1114]
In https://github.com/rancher/rke2/issues/916 we chose to add some special logic that is enabled by setting `--cloud-provider-name=vsphere`, with the understanding that no-one was using the in-tree vsphere providers, in favor of the out-of-tree providers (via the helm chart).

This turned out not to be the case; we should use `--cloud-provider-name=rancher-vsphere` instead.

**Comment by cjellick** [comment]
Will get pulled in today

**Comment by rancher-max** [comment]
When testing this, we should make sure we consider migration path from in-tree to out-of-tree (rancher-vsphere). See https://github.com/rancher/docs/issues/3151#issuecomment-816044356 for details for RKE1.

**Comment by brandond** [comment]
My understanding is that the in-tree provider is officially deprecated, vmware is the first provider to make their out-of-tree provider the recommended option.

**Comment by rancher-max** [comment]
#### Validated in v1.21.2-rc1+rke2r1

- Out of tree `rancher-vsphere` works as expected
- In tree `vsphere` works now as it used to pre v1.20.6
- Upgrade from in tree to out of tree is successful. See https://github.com/rancher/rke2/issues/1115#issuecomment-863498048 for detailed steps
