### ISSUE TITLE
[release-1.20] Rename RBAC resources for K3s integrated cloud-controller-manager

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1118]
Backport "Rename RBAC resources for K3s integrated cloud-controller-manager" from #1009 to release-1.20.

These fixes will need to be backported to track with changes in k3s, which is getting updated in the release-1.20 branch to resolve other issues.

**Comment by rancher-max** [comment]
#### Validated in v1.20.8-rc1+rke2r1

- Resources are named in a fresh install and are the only cloud-controller resources present
- Upgrade is also successful. The old cloud-controller resources are not cleaned up, which is expected. Operators should clean these up manually if they were previously owned by rke2. If they are owned by an external cloud provider, then they are safe to leave:
```
$ k get clusterroles,clusterrolebindings | grep -i cloud-controller
clusterrole.rbac.authorization.k8s.io/cloud-controller-manager                                               2021-06-22T18:42:10Z
clusterrole.rbac.authorization.k8s.io/rke2-cloud-controller-manager                                          2021-06-22T20:27:31Z
clusterrolebinding.rbac.authorization.k8s.io/cloud-controller-manager                               ClusterRole/cloud-controller-manager                               5h10m
clusterrolebinding.rbac.authorization.k8s.io/rke2-cloud-controller-manager                          ClusterRole/rke2-cloud-controller-manager                          3h24m
```
