### ISSUE TITLE
Add manifest Support to runtime-image

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1127]
Add support for manifests for the `runtime-image`, opens the door for multi os/arch support.

**Testing**
Confirm the amd64/linux runtime image still pulls down deploying a linux cluster without any problems. we will add manifests + windows builds later which will be a separate issue/test.

**Comment by rosskirkpat** [comment]
https://github.com/rancher/rke2/pull/1311

**Comment by rancher-max** [comment]
Validated builds using master commit `e889d2e273bd88b8ed273207334f394fac0a6a11` continue to work on linux systems
