### ISSUE TITLE
RKE2 releases should not be tied to a specific Kubernetes version

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#1130]
Today, we are releasing RKE2 versions every time a new Kubernetes patch release comes out. This is a departure from the way we release RKE (https://github.com/rancher/rke)

This approach is unnecessarily noisy in my opinion, as it requires a full blown bottom-up RKE2 release, when in certain cases we do not actually change functionality within RKE2 itself. As RKE2 deploys all of the Kubernetes components (except for the `cloud-controller-manager`, which is no longer going to be the case once https://github.com/rancher/rke2/issues/1085 is completed). We use the `rke2-runtime` image and pull out the `kubelet`/`kubectl` binaries that we run onto filesystem in a "sane" directory, i.e. `/var/lib/rancher/rke2/data/v1.20.7-rke2r2-dbd2e65e6257`.

I am thinking we should move to an approach where upstream Kubernetes version metadata can be updated into RKE2 (and thus allowing RKE2 to deploy multiple K8s versions). RKE2 should be able to parse the metadata but also be shipped with the latest "snapshot" of metadata, very similar to the way we release RKE today, allowing for easy airgap installs.

It should be noted that today, it is possible to have an RKE2 version deploy any version of Kubernetes, by specifying custom images for the various components.

**Comment by Oats87** [comment]
https://github.com/rancher/rke2/issues/1104 would help with this

**Comment by katran001** [comment]
@Oats87 what is your feedback on this issue, can we close it? If not, what are next steps?

**Comment by caroline-suse-rancher** [comment]
@cwayne18 Should this idea still be under consideration?
