### ISSUE TITLE
Metrics are limited if external containerd is used

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#1139]
**Environmental Info:**
RKE2 Version: rke2 version v1.20.7+rke2r2 (ea6514775f816b0b4972f832de7d98eba8dff55c)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 
Linux hdg-worker-u1.priv.cerit-sc.cz 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 7 agents, one agent uses external containerd due to nvidia gpu operator

**Describe the bug:**
if using external containerd, /api/v1/nodes/NODE/proxy/metrics/cadvisor returns always container=""  for containers metrics.
E.g.: container_spec_cpu_period{container="",id="/kubepods/besteffort/pod2ad80de8-ebaf-4ec8-b332-29d7671ac701",image="",name="",namespace="kube-system",pod="kube-proxy-mkfz6"} 100000

I.e., container, image, and name is always empty. Not happening on different nodes.

**Comment by brandond** [comment]
How have you configured the external containerd endpoint?

**Comment by xhejtman** [comment]
rke2 config:
container-runtime-endpoint: unix:///run/containerd/containerd.sock

config.toml attached.
[config.toml.txt](https://github.com/rancher/rke2/files/6651845/config.toml.txt)

**Comment by brandond** [comment]
Try dropping the `unix://` prefix off it, see: https://github.com/k3s-io/k3s/pull/2836

Some things (kubelet) want it one way, others (cadvisor metrics) want it another.

**Comment by xhejtman** [comment]
Great, it works now, thanks. Can be closed.
