### ISSUE TITLE
rke2-runtime image can't be preloaded from image directory

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#114]
rke2 bootstrap code always tries to connect to a remote registry to pull the rke2-runtime image, which causes dev builds for rke2-runtime to be useless unless its pushed to a remote registry.

The code should be able to preload the image from the images/ directory

**Comment by davidnuzik** [comment]
This also has an impact on airgap (from @cjellick )

**Comment by brandond** [comment]
This is related to #233

**Comment by nikkelma** [comment]
Also related: #248

**Comment by nikkelma** [comment]
Can this be closed, or is there some other requirement different from #248 that's being tracked here?

**Comment by cjellick** [comment]
yep, this was effectively duped
