### ISSUE TITLE
kubectl timesout after RKE2 uninstall on secondary server

### ISSUE THREAD

**Issue by AndreiBarbuOz** [rancher/rke2#1140]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.20.7+rke2r2 (ea6514775f816b0b4972f832de7d98eba8dff55c)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 
Linux agent1 4.18.0-193.47.1.el8_2.x86_64 #1 SMP Thu Mar 4 03:03:32 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 servers

**Describe the bug:**
install RKE2 on VM1
join VM2 as server
run `kubectl get nodes` on VM1 outputs:
```
NAME      STATUS   ROLES                       AGE     VERSION
server1   Ready    control-plane,etcd,master   54s     v1.20.7+rke2r2
server0   Ready    control-plane,etcd,master   7m16s   v1.20.7+rke2r2
```
uninstall VM2
run `kubectl get nodes` on VM1 outputs:
```

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get services)
```

**Steps To Reproduce:**
- Installed RKE2 on VM1: 

config.yaml:
```
token: *****
selinux: false
kubelet-arg:
- "max-pods=500"
write-kubeconfig-mode: "0644"
etcd-snapshot-retention: 7
etcd-snapshot-schedule-cron: "*/15 * * * *"
tls-san:
- ip1
- fqdn
- kubernetes.default.svc
disable:
- rke2-ingress-nginx
kube-apiserver-arg:
- "feature-gates=TTLAfterFinished=true"
kube-controller-manager-arg:
- "node-cidr-mask-size=22"
- "pod-eviction-timeout=10s"
- "feature-gates=TTLAfterFinished=true"
disable-cloud-controller: true
```
- Installed RKE2 on VM2 using the same configuration
- Uninstalled RKE2 on VM2 using `/usr/bin/rke2-uninstall.sh`
- Ran kubectl get nodes on VM1 and timed out
- Installed RKE2 on VM2 again and it started working

**Expected behavior:**
If a VM is added by mistake and then removed from the cluster, the kubeapi should continue to function

**Actual behavior:**
kubectl commands timeout

**Additional context / logs:**

**Comment by brandond** [comment]
If you have a two-node etcd cluster and stop one node, the other node cannot function as it does not have quorum. Please read:
https://etcd.io/docs/v3.3/faq/#why-an-odd-number-of-cluster-members

**Comment by AndreiBarbuOz** [comment]
installed the second node as server by accident and didn't find docs regarding switching from server to agent. so I uninstalled it. found the etcd quorum documentation after opening the issue :/
