### ISSUE TITLE
[release 1.22] - Send systemd notifications for both server and agent

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1145]
Pull through fix for "Send systemd notifications for both server and agent " from k3s-io/k3s#3430 to release-1.22 (master)

**Comment by dereknola** [comment]
Validated on master commit `09bb5c27f29cf3dd831653543d274c948a225385`

Started rke2 server:
`systemctl start rke2-server`
Before commands returns, checked that kubelet is up:
```
root@node-cluster-init-buster64:/home/vagrant# netstat -tulpn | grep kubelet
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      11643/kubelet       
tcp6       0      0 :::10250                :::*                    LISTEN      11643/kubelet       
root@node-cluster-init-buster64:/home/vagrant# pgrep kubelet
11643

```
