### ISSUE TITLE
When etcd snapshots are disabled, the snapshot list configmap is still updated

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#1157]
RKE2 Version: 
rke2 version v1.21.1-dev+5f9b1aa6

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single node

**Describe the bug:**
While snapshot creation is disabled, we see a log message **ETCD snapshots are disabled** and also **Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap**
 
**Steps To Reproduce:**
1. Install rke2 with snapshots disabled
Config.yaml
```
etcd-disable-snapshots: true
etcd-snapshot-schedule-cron: "*/2 * * * *"
```
2. Logs contain both disabled message along with Saving snapshot message.
```
 journalctl -u rke2-server |grep snapshot
Jun 16 17:54:14 ip-172-31-34-252 rke2[1526]: time="2021-06-16T17:54:14Z" level=info msg="Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap"
Jun 16 21:45:58 ip-172-31-34-252 rke2[85241]: time="2021-06-16T21:45:58Z" level=info msg="ETCD snapshots are disabled"
Jun 16 21:47:59 ip-172-31-34-252 rke2[85241]: time="2021-06-16T21:47:59Z" level=info msg="Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap"
```

**Expected behavior:**
When etcd snapshots are disabled log we could only ETCD snapshots are disabled message

**Actual behavior:**
Both disable and saving messages are shown

**Comment by briandowns** [comment]
Changes have been made in K3s and will be pulled through when the RKE2 branches are updated.

**Comment by ShylajaDevadiga** [comment]
Valiidated in rke2 version v1.21.3-rc5+rke2r1
Logs dont show the Saving current etcd snapshot when snapshots are disabled
