### ISSUE TITLE
 bug: rke2/docs/install/quickstart.md link to known issues for networking results in 404

### ISSUE THREAD

**Issue by FruityWelsh** [rancher/rke2#1164]
**Describe the bug:**
 bug: rke2/docs/install/quickstart.md link to known issues for networking results in 404
 the link is https://docs.rke2.io/known_issues/#networkmanager but this 404s
 the link to known issues that works is https://docs.rke2.io/known_issues.html

**Comment by cjellick** [comment]
just a change to the docs site, so i think we can close

**Comment by cjellick** [comment]
Nah, QA can validate this I think.

**Comment by ShylajaDevadiga** [comment]
Validated https://docs.rke2.io/known_issues/ link works and there are no broken links on the main page.
