### ISSUE TITLE
Multi-OS Support for RKE2 runtime and binary builds (Adding Windows)

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1166]
Issue to track adding Windows (multi-OS) support to RKE2

1.21 backport issue: https://github.com/rancher/rke2/issues/1299
Manifest support for runtime images: https://github.com/rancher/rke2/issues/1127

**Comment by rosskirkpat** [comment]
cc: @sirredbeard @luthermonson @phillipsj

**Comment by rancher-max** [comment]
Closing in favor of https://github.com/rancher/rke2/issues/1289#issuecomment-926316897

**Comment by briandowns** [comment]
Validated on master.
