### ISSUE TITLE
[Backport 1.21] - Bump version multis chart

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1172]
The version of the multis chart needs to be bumped and included in the RKE2 1.21 release. Release notes should be updated to reflect this change as well.

**Comment by rancher-max** [comment]
Validated using commitid: `790186ffa54ab4c87a09d1835316e3aa55f59fb4` in release-1.21 branch. Multus works in Selinux enforcing system as the init container is now privileged.
