### ISSUE TITLE
golangci-lint has not been running during builds

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1173]
https://github.com/rancher/rke2/blob/master/scripts/validate#L1-L7

use of `-n`  requires quoted arguments. Since the args have been unquoted, all builds have been skipping validation (see below)

Without the argument quoted, validation will be skipped during every build:
```
./scripts/validate
+ '[' -n ']'
+ echo 'skipping validation. continuing...'
+ exit 0
skipping validation. continuing...
```

From a recent PR where the bug was fixed, the validate script runs and fails when golangci-lint runs:
```
./scripts/validate
+ '[' -n '' ']'
++ dirname ./scripts/validate
+ cd ./scripts/..
+ GO=go
+ echo Running validation
+ echo Running: go fmt
+ go fmt ./
Running validation
Running: go fmt
...
+ echo Running: go vet
+ go vet ./
Running: go vet
Running: golangci-lint
/go/bin/golangci-lint
+ echo Running: golangci-lint
+ command -v golangci-lint
+ golangci-lint run
pkg/controllers/cisnetworkpolicy/controller.go:25:6: func name will be used as cisnetworkpolicy.CISNetworkPolicyController by other packages, and that stutters; consider calling this Controller (golint)
func CISNetworkPolicyController(ctx context.Context, sc *server.Context) error {
     ^
make: *** [Makefile:64: validate] Error 1
```

**Comment by brandond** [comment]
@briandowns do you remember why this was done? It seems unrelated to the rest of the PR

https://github.com/rancher/rke2/commit/bdd34d3df64eaa05342453f3dcacba1e2d634b78#diff-4c0e1e708c59d9a06da4c01a46c2d30739fce6b57e17eff33b2930da8d294692L4

**Comment by briandowns** [comment]
That was awhile ago. I don't remember at this point.

**Comment by brandond** [comment]
Closing; QA does not need to validate CI fixes.
