### ISSUE TITLE
Test and Certify OpenSUSE (Leap) 15 SP3 [rke2]

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1176]
Test and Certify OpenSUSE (Leap) 15 SP3 on v1.21, v1.20, v1.19, v1.18 (with latest June patches or newer).
The precise versions mentioned here and the milestone are subject to change!

**Comment by rancher-max** [comment]
Validated v1.21, v1.20, and v1.19 per the support OS matrix.
