### ISSUE TITLE
Test and Certify Alma Linux 8.3 and 8.4 [rke2]

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1177]
on v1.21, v1.20, v1.19, v1.18 (with latest June patches or newer).
The precise versions mentioned here and the milestone are subject to change!

**Comment by b4ck3r** [comment]
Hello, 

Are there any plans to also certify Rocky Linux now that version 8.4 was officially released?

Thanks

**Comment by davidnuzik** [comment]
Just about to create an issue to track Rocky Linux :)

**Comment by b4ck3r** [comment]
Lovely, thank you!!!

**Comment by davidnuzik** [comment]
https://github.com/rancher/rke2/issues/1179

**Comment by davidnuzik** [comment]
@b4ck3r I updated the descriptions - we might not have the QA headcount to get all these done specifically by next releases in July FYI. If Rocky Linux is very very important to you you can give a thumbs up on that issue I referenced if you haven't yet. I can't promise it will make it in, however.

It's worth noting that I'd anticipate RKE2 will work just fine on Rocky Linux. That issue (#1179) is just to formally test it and approve it for use such as in production. If you plan to run non-test environments on Rocky Linux then -- yeah I'd wait until it formally passes QA in that issue.

**Comment by b4ck3r** [comment]
Thank you @davidnuzik

**Comment by davidnuzik** [comment]
Alma is moved to backlog for future consideration now. Rocky is still planned for by v1.21.3+rke2r1.

**Comment by caroline-suse-rancher** [comment]
No longer in the plans, closing

**Comment by ViktorOhlssonOP** [comment]
I see! 
However it says that it supports RHEL which Alma Linux is based upon so forgive me for my confusion but should it not be supported then perhaps?

**Comment by cwayne18** [comment]
"Support" in this case means constant testing and validation on patch releases and every new minor, which is a very heavy QA burden.  At this moment, we're not aware of any specific reason k3s *wouldn't* work on Alma linux, and if any issues are found we will do a best-effort investigation to get them fixed, but we're not going to take support calls or make any kind of guarantees at this time for Alma linux.
