### ISSUE TITLE
Feature request: Upgrade runc to v1.0.0

### ISSUE THREAD

**Issue by yasker** [rancher/rke2#1188]
**Is your feature request related to a problem? Please describe.**
There is a fix (https://github.com/opencontainers/runc/commit/bf7492ee5d022cd99a9dbe71c5c4f965041552e9 ) in the latest runc v1.0.0 release that's required for Hotplug with Live migration feature implementation in KubeVirt. More context can be found at the discussion https://groups.google.com/g/kubevirt-dev/c/0UbMD2R92mQ

Currently RKE2 ships with runc 1.0-rc95, which doesn't contain the fix.

**Describe the solution you'd like**
Upgrade runc to v1.0.0 in RKE2.

**Describe alternatives you've considered**
Workaround it internally in KubeVirt, which is unclear how at the moment, and not the preferred way from the community (see the conversation above) due to runc has already fixed the problem. 

**Additional context**
Hotplug with Live migration feature is required for Harvester v0.3 release and v1.0 GA.

**Comment by brandond** [comment]
@yasker which k3s releases do you need this in?

**Comment by yasker** [comment]
@brandond since we're switching to RKE2/RancherD for v0.3.0, update the latest RKE2 version should be good enough.

**Comment by brandond** [comment]
OK, so it'll need to be backported to the release-1.21 branch then.

**Comment by rancher-max** [comment]
Confirmed on master branch commit `09bb5c27f29cf3dd831653543d274c948a225385` actually using runc version 1.0.1

```
$ runc --version
runc version 1.0.1
commit: v1.0.1-0-g4144b638
spec: 1.0.2-dev
go: go1.16.4b7
libseccomp: 2.5.1
```
