### ISSUE TITLE
Second master/agent fails to join using env RKE2_URL

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#120]
**Environment**
rke2 version: v1.18.4-alpha15-rke2 (HEAD)
NodeOS: Ubuntu 20.04

**Describe the issue**
Joining second master or agent fails using env variables

**Steps to Reproduce**
1. Install rke2 using install script
```
INSTALL_RKE2_VERSION=v1.18.4-alpha15+rke2
```
2. Join second master
```
INSTALL_RKE2_VERSION=v1.18.4-alpha15+rke2 INSTALL_RKE2_EXEC='server' RKE2_TOKEN=<TOKEN> RKE2_URL='<NODE1_IP>:9345' ./install.sh
```
**Expected result**
Node should join the cluster

**Actual result**
Creates a new cluster

**Logs**
```
Jul 22 23:40:09 ip-172-31-14-175 rke2[218561]: time="2020-07-22T23:40:09Z" level=info msg="Waiting for kubelet to be ready on node ip-172-31-14-175: Get \"https://127.0.0.1:6443/api/v1/nodes/ip-172-31-14-175\": dial tcp 127.0.0.1:6443: c>
Jul 22 23:40:11 ip-172-31-14-175 rke2[218561]: {"level":"warn","ts":"2020-07-22T23:40:11.112Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-25e54114-b4a2-447d-a1f9-23d27>
Jul 22 23:40:11 ip-172-31-14-175 rke2[218561]: time="2020-07-22T23:40:11Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Jul 22 23:40:14 ip-172-31-14-175 rke2[218561]: time="2020-07-22T23:40:14Z" level=error msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&r>
Jul 22 23:40:16 ip-172-31-14-175 rke2[218561]: time="2020-07-22T23:40:16Z" level=info msg="Data store connection OK"
```

**Comment by davidnuzik** [comment]
Sorry, @ShylajaDevadiga is this not a duplciate of https://github.com/rancher/rke2/issues/53 which is being worked on?

**Comment by ShylajaDevadiga** [comment]
@davidnuzik This is a different issue. I will close the first one as validated.

**Comment by davidnuzik** [comment]
In case not clear the issue happens specifically when use this method (RKE2_URL) and token, etc as described above when joining the second master. Otherwise in INSTALL_RKE2_EXEC this will work.

**Comment by davidnuzik** [comment]
This is on hold until we have a plan for what we are doing with the install script (e.g. see https://github.com/rancher/rke2/issues/138 )
