### ISSUE TITLE
Provide a path to upgrade to Calico Enterprise

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1207]
The user deploying rke2 with open source Calico cni plugin should have a seamless path to migrate to Calico Enterprise.

The way to do this should be:

- Use Helm upgrade to move from the open source Tigera/Calico chart into the enterprise Tigera/Calico chart. We assume that by that, all the internals of Calico will be upgraded correctly
- Once the upgrade is successful, rke2 should stop managing Calico, i.e. do not upgrade the helm chart in an rke2 upgrade

Tasks:
- [ ] Verify the helm upgrade mechanism works when moving to Calico enterprise
- [x] Rke2 to stop managing the calico HelmChart

**Comment by manuelbuil** [comment]
The best way to make rke2 stop using the calico helm chart is by doing the following in all control-plane nodes:

`sudo mv /var/lib/rancher/rke2/server/manifests/rke2-calico.yaml /var/lib/rancher/rke2/server/manifests/rke2-calico.yaml.skip`

The controller ignores charts that have the suffix `.skip` and, for example, will not get touched when running an automated upgrade

**Comment by brandond** [comment]
Honestly you could probably just do `touch /var/lib/rancher/rke2/server/manifests/rke2-calico.yaml.skip`

**Comment by manuelbuil** [comment]
Waiting for calico enterprise images to verify the helm upgrade mechanism works when moving to Calico enterprise

**Comment by manuelbuil** [comment]
Tested and we get a lot of new pods with `ImagePullBackOff` errors because of `401 UNAUTHORIZED`, which seems to be normal

**Comment by manuelbuil** [comment]
We haven't received any bad feedback from Tigera or customers and there are customers already using it, so we can assume that it is working. Let's close it
