### ISSUE TITLE
Workloads in built-in helm charts should support arbitrary tolerations

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#1214]
This is *not* for the pre-defined role-based taints like etcd, control-plane, worker. We already support those.

Since users can specify arbitrary taints on nodes when creating a cluster, we should allow specification of arbitrary tolerations on our helm-based workloads

**Comment by katran001** [comment]
If we ever find time, we can come back to this ticket. In the meantime, I'm closing it.
