### ISSUE TITLE
Change pod log file location

### ISSUE THREAD

**Issue by grk-pancham** [rancher/rke2#1220]
RKE2 Version: v1.20.6.+rke2r1

Kubernetes pod logs are by default stored in /var/log/pods folder. We have requirement that the /var/log file system size is limited and cannot grow. As we deploy more pods, the log file system folder runs out of space and we cannot deploy any more pods. How do we configure the location so that all the pod logs are created in our custom folder ?

**Comment by Martin-Weiss** [comment]
Just some wild guessing - did not test that but maybe the "linux" way of things might help? ;-)...

- Maybe you could mount an other filesystem to /var/log/pods?

- Maybe you could replace the "pods" directory with a symbolic link pointing to an other place?

**Comment by grk-pancham** [comment]
Hi Martin, We cannot use any of these solutions since it is not allowed for us to alter this filesystem. Are you saying that there is no way to alter the pod logs location in RKE2 and it is currently sort of hard coded ?

**Comment by Martin-Weiss** [comment]
Unfortunately I do not have too deep insights so this is just a try to help with some wild guessing ;-).

I believe the path /var/log/pods is created by kubelet - so if the kubelet has an option to adjust the path we might need to set additional kubelet arguments in the rke2 configuration and for that I believe we have `--kubelet-arg value`.

**Comment by brandond** [comment]
Unfortunately, this is hardcoded in the kubelet: https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L61-L62
```go
	// The root directory for pod logs
	podLogsRootDirectory = "/var/log/pods"
```

**Comment by grk-pancham** [comment]
What is the log-dir command line parameter to kubelet for? Is this the log directory for kubelet logs and not the location for pod logs ?

**Comment by brandond** [comment]
correct
