### ISSUE TITLE
Cilium operator image can not be pulled

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#1224]
**Environmental Info:**
RKE2 Version: 1.20.8

**Describe the bug:**
For airgapped deployment we have to replicate the images required for the helm chart rke2-charts/rke2-cilium 1.9.808 but fetching the image rancher/mirrored-cilium-operator:v1.9.8 is not possible.

helm3 inspect values rke2-charts/rke2-cilium --version v1.9.8 shows these images:

rancher/mirrored-cilium-cilium:v1.9.8
rancher/mirrored-cilium-operator:v1.9.8
rancher/mirrored-cilium-startup-script:62bfbe88c17778aad7bef9fa57ff9e2d4a9ba0d8

**Steps To Reproduce:**
Get the list of images from helm chart
Try to pull them.

docker pull rancher/mirrored-cilium-operator:v1.9.8

`Error response from daemon: pull access denied for rancher/mirrored-cilium-operator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Expected behavior:**
The pull should work and not require a login.

**Actual behavior:**
The pull fails.

**Comment by mrostecki** [comment]
Please try pulling the `rancher/mirrored-cilium-operator-generic` image. That's the image which is used and I can confirm that even after a fresh rke2+cilium deployment

```
Containers:
  cilium-operator:
    Container ID:  containerd://fcd41ff2a835ccedb2ec9cb56aab0bff24693298ca0eea968534d6170dd65cb0
    Image:         rancher/mirrored-cilium-operator-generic:v1.9.8
    Image ID:      docker.io/rancher/mirrored-cilium-operator-generic@sha256:c7bdff24f03a80d390e7d4f6aed4ffdc45151c8a695701530f9e1ffc1978ddc5
    Port:          6942/TCP
    Host Port:     6942/TCP
    Command:
```

`helm3 inspect [...]` shows the wrong image name, I will try to figure out why and fix that.

**Comment by Martin-Weiss** [comment]
Yeah - pulling the generic one works.. so probably the helm chart values and templates might need to be adjusted a bit..

**Comment by cjellick** [comment]
@mrostecki - we should fix in main, 1.21, and 1.20, so you'll need to open up some backport issues. @brandond is a good resource on what to do there.

**Comment by brandond** [comment]
It's because the chart builds the image name via string templating - the image name you see has -aws, -azure, or -generic appended to it depending on how other values are configured.
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-cilium/rke2-cilium/1.9.808/charts/cilium/templates/cilium-operator-deployment.yaml#L138-L144
```yaml
{{- if .Values.eni }}
        image: {{ template "system_default_registry" . }}{{ .Values.operator.image.repository }}-aws:{{ .Values.operator.image.tag }}
{{- else if .Values.azure.enabled }}
        image: {{ template "system_default_registry" . }}{{ .Values.operator.image.repository }}-azure:{{ .Values.operator.image.tag }}
{{- else }}
        image: {{ template "system_default_registry" . }}{{ .Values.operator.image.repository }}-generic:{{ .Values.operator.image.tag }}
{{- end }}
```

**Comment by mrostecki** [comment]
Good catch @brandond. Will fix it upstream then.

**Comment by vadorovsky** [comment]
https://github.com/cilium/cilium/pull/16810

**Comment by vadorovsky** [comment]
Please not that the change in Cilium is quite invasive and maybe it would be a better idea to just not rely on `helm inspect` as the source of truth about image names.

**Comment by vadorovsky** [comment]
I closed the upstream PR. Making such a change in the Helm chart would require much more changes that I expected and would have an impact on upgrades. And on CI tests which test upgrades. Especially for upgrades, it's better to keep changes in Helm values as small as possible.

When talking about that PR, there was an idea about making Cilium configuration versioned as some kind of CRD and writing an operator, but I think that would be quite an overkill for such a small change.

**Comment by brandond** [comment]
@Martin-Weiss the takeaway here is:
> it is better idea to just not rely on helm inspect as the source of truth about image names.

**Comment by Martin-Weiss** [comment]
Hm - and what is the source about truth, then?
Seems this is the first one where the values.yaml is not the truth?

Am 28.07.2021 um 20:36 schrieb Brad Davidson ***@***.***>:

﻿

@Martin-Weiss<https://github.com/Martin-Weiss> the takeaway here is:

it is better idea to just not rely on helm inspect as the source of truth about image names.

**Comment by brandond** [comment]
> Hm - and what is the source about truth, then?

The image list text file.

**Comment by Martin-Weiss** [comment]
> 
> 
> > Hm - and what is the source about truth, then?
> 
> The image list text file.

Any idea why we do not deliver an adjusted helm chart with the explanation of the differences?
It is always difficult to understand if two places have different information..

Maybe we could add a comment to the helm charts values.yaml that explains that a different image is used in RKE2 deployments?

**Comment by brandond** [comment]
It's not different in rke2, that's how it is in the upstream chart, and they are unwilling to change it.

**Comment by Martin-Weiss** [comment]
> 
> 
> It's not different in rke2, that's how it is in the upstream chart, and they are unwilling to change it.

I am fine if this is left this way - but we should address this then by "proper documentation" in the values.yaml and maybe also in the readme of the chart..
