### ISSUE TITLE
kube-scheduler logging is empty

### ISSUE THREAD

**Issue by dbason** [rancher/rke2#1232]
**Environmental Info:**
RKE2 Version:  v1.20.8+rke2r1

Cluster Configuration: 
Tested with 1 server and various numbers of agents

**Describe the bug:**
Logging for the kube-scheduler only contains the leader election then nothing

**Steps To Reproduce:**
- Installed RKE2:  Used install script
- Check the logs using `kubectl logs -n kube-system <kube-scheduler-pod-name>` or by tailing the file on the server node

**Expected behavior:**
kube-scheduler info logging would be included

**Actual behavior:**
No kube-scheduler logs

**Additional context / logs:**
Explicitly setting the -v=2 flag for kube-scheduler generate the expected logs.  Setting -v=1 includes some additional logs about the startup flags, but not the info logs.

**Comment by brandond** [comment]
When looking at this earlier, I'm unable to find any signs that anything has changed in either RKE2 or upstream Kubernetes that would have affected this.

@dbason can you identify what release last included the log output you're expecting?

**Comment by dbason** [comment]
Sure, I can try and go back to find something.  As an aside though would the general expectation be that v=2 is the standard log level for kubernetes services?

**Comment by brandond** [comment]
No, the default verbosity level is 0:
https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#:~:text=v%20-%20verbosity

**Comment by Oats87** [comment]
As @brandond said, the `kube-scheduler` basically doesn't log anything by default. We should probably set it to be `-v=2` by default, as we do this in RKE1 today: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_service_options.go#L467

**Comment by dbason** [comment]
Yeah I think I was conflating our testing on RKE1 with this as I've been unable to replicate this on the previous few releases of RKE2.  I do think it's sort of weird that scheduling failures are just informational, and not warning:
```
I0630 23:08:01.835087       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="default/test-job-gfphk" err="0/1 nodes are available: 1 node(s) didn't match Pod's node affinity."
I0630 23:08:01.882722       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="default/test-job-kfmz2" err="0/1 nodes are available: 1 node(s) didn't match Pod's node affinity."
I0630 23:08:01.892104       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="default/test-job-kfmz2" err="0/1 nodes are available: 1 node(s) didn't match Pod's node affinity."
```
I would have expected that to be logged at the default level, but that's a question for upstream.

**Comment by brandond** [comment]
well this isn't really an error, it's just a state that the cluster finds itself in sometimes, depending on what's been requested vs what is available. Normally you would catch these sorts of things by watching v1.Event or (as a user) by doing `kubectl describe pod` and checking the status and/or events in the output.
