### ISSUE TITLE
Allow customizing of the static pod manifests for CPU, files, and directories

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#1233]
In order to keep feature parity with RKE1, we should support setting:

* Custom Environment Variables
* Custom bind-mounted directories from the host

More information on this capability can be found here: https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/

We should also allow customization of the CPU request, and, optionally, allow the user to set CPU limits on the static pod run components even though this is not ideal from a usability perspective, there could still be merit/reason to do so.

**Comment by brandond** [comment]
We have existing backlog issues for these under:
* #930
* #1046

**Comment by Oats87** [comment]
Thanks @brandond . Those are quite a bit more "nuanced" and specific. Wondering if we should independently track the functionality or just merge into one "super" issue, considering the code change to implement all of this is going to be in the same part of code.

**Comment by Oats87** [comment]
Consolidated https://github.com/rancher/rke2/issues/1046 to this issue

**Comment by rancher-max** [comment]
Confirmed these extra args are working on master branch commit `525479888074426ea6019474c33e184a947c197c` using the same steps as mentioned in https://github.com/rancher/rke2/issues/1525
