### ISSUE TITLE
Manual rke2-coredns manifest deployment not applied

### ISSUE THREAD

**Issue by sebastienmusso** [rancher/rke2#1235]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.2+rke2r1 and v1.20.8+rke2r1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04.2 LTS x86_64

Cluster Configuration:
Only one master in order to debug with some rke2 configuration items
config.yaml
```
kubelet-arg:
- "feature-gates=DynamicKubeletConfig=false"
debug: true
kube-apiserver-arg:
- "tls-min-version=VersionTLS12"
kube-scheduler-arg:
- "tls-min-version=VersionTLS12"
kube-controller-manager-arg:
- "tls-min-version=VersionTLS12"
disable:
- rke2-coredns
- rke2-canal
- rke2-ingress-nginx
- rke2-kube-proxy
- rke2-metrics-server
```

**Describe the bug:**
rke2-coredns custom manifest not deployed.
I need to set some specific values in rke2-coredns helm charts ("replicaCount: 2")
/var/lib/rancher/rke2/server/manifests/coredns.yaml is copied from default /var/lib/rancher/rke2/data/${rke2-version}/charts/rke2-coredns.yaml 

file is seen by rke2-server supervisor:
```
Jul 01 00:00:00 hostname rke2[pid]: time="2021-07-01T00:00:00Z" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/coredns.yml to set cluster configuration values"
```

but no coredns pods are deployed.

**Steps To Reproduce:**
disable rke2-coredns manifest in rke2 config file
get default rke2-coredns manifest and copy it into /var/lib/rancher/rke2/server/manifests/

**Expected behavior:**
deploy HelmChart object into the cluster

**Actual behavior:**
nothing appen

**Comment by brandond** [comment]
I see you've disabled canal as well, are you providing your own CNI too? What do you get from `kubectl get addon helmchart -A` ?

**Comment by sebastienmusso** [comment]
I made the same with canal, kube-proxy and metric-server.
ex
Get default rke2-canal charts in /var/lib/rancher/rke2/data/v1.20.7-rke2r2-dbd2e65e6257/charts/rke2-canal.yaml
et copy it into /var/lib/rancher/rke2/server/manifests/ with custom mtu and other stuff

coredns is the only one component impacted

**Comment by brandond** [comment]
I see the HelmChart, what about AddOn?

Do you see anything in the rke2 logs? If there's a typo in your custom manifest, the only place (at the moment) you'll see that reported is in the logs.

**Comment by brandond** [comment]
FWIW, the recommended way to customize these is via HelmChartConfig, it'such easier than disabling and copying the manifests.

https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by brandond** [comment]
Glad to hear it!
