### ISSUE TITLE
rke2-kube-proxy values.yaml have wrong example for strictARP variable (is strictArp instead of strictARP)

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#1237]
**Environmental Info:**
RKE2 Version: 1.20.8-rke2r1

**Describe the bug:**
helm inspect values -> see example and find "strictArp" where it should be "strictARP" as "strictARP" is used in the templates..

**Expected behavior:**
values.yaml should have strictARP instead of strictArp

**Actual behavior:**
values.yaml has strictArp

**Additional context / logs:**
--> this setting is required in case MetalLB is deployed..

**Comment by brandond** [comment]
Which chart are you referring to?

**Comment by Martin-Weiss** [comment]
> 
> 
> Which chart are you referring to?

Ahh - missed the most important thing - sorry ;-) rke2-kube-proxy

**Comment by brandond** [comment]
We are about to switch rke2-kube-proxy from a helm chart to a static pod, so this may not get fixed.

Ref: https://github.com/rancher/rke2/issues/1199

**Comment by Martin-Weiss** [comment]
> 
> 
> We are about to switch kube-proxy from a helm chart to a static pod, so this may not get fixed.
> 
> Ref: #1199

Thanks for the info. In case we use static pod I assume there will be a parameter we can set in config.yaml to enable strictARP and will be a migration strategy for upgrades?

**Comment by brandond** [comment]
Switching over to static pods will allow use of the k3s --kube-proxy-arg CLI flag on a per-node basis, similar to the other passthrough args like --kubelet-arg or --kube-apiserver-arg

**Comment by Martin-Weiss** [comment]
Sure - the question is just how the get this (and other customized settings) out of the configmap  / helm chart values into the CLI args during the upgrade..

**Comment by brandond** [comment]
For 1.21 and older branches we will likely continue to use the rke2-kube-proxy chart if a matching HelmChartConfig resource is detected, indicating local customization.

1.22 (or perhaps 1.23) will no longer package the helm chart or fall back to it; users that want to continue to deploy it that way will need to --disable-kube-proxy and provide their own chart.

This is all being worked on right now and the specific schedule for deprecation has not been decided upon.

**Comment by Martin-Weiss** [comment]
unstale
