### ISSUE TITLE
Create a PowerShell based installation script for RKE2 installation on Windows Nodes.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1240]
**Is your feature request related to a problem? Please describe.**

Windows nodes need an installation method similar to the existing installation approach.

**Describe the solution you'd like**

Add an install.ps1 script that allows the installation of RKE2 supporting many of the features of install.sh in a native PowerShell style.

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
This has been validated as the `install.ps1` installation script we use is from the master branch and is working correctly.
