### ISSUE TITLE
RKE2 installation fails in the absence of a default route

### ISSUE THREAD

**Issue by TFBW** [rancher/rke2#1242]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
go version go1.16.4b7

Node(s) CPU architecture, OS, and Version: 
Linux hcm06 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Experimental cluster running on VMs in an isolated subnet. VM host environment provides an HTTP proxy for all outside connectivity.

**Describe the bug:**
Installation of RKE2 does not complete if the host environment lacks a default route.

**Steps To Reproduce:**
Attempt to install RKE2 on a host with no default route, such as a VM attached to an isolated subnet. Due to the lack of IP connectivity outside the immediate network, this also requires the various HTTP proxy environment variables to be configured, and for a multi-homed host on the network to provide the proxy service,

**Expected behavior:**
At the very least, the absence of the default route should be detected, and the installation process should bail out with an appropriate error message. The use of the default route seems to be a heuristic for finding the "main" network interface, and there are other ways of doing this. For example, if you eliminate loopback interfaces and only one network interface remains, then that interface is reasonably considered the "main" one. Ultimately, there should be an explicit argument by which the interface is specified, and this heuristic should simply provide the default. A bail-out message could then mention the argument which is required to address the problem.

**Actual behavior:**
One of the scripted commands in the installation process fails due to a missing argument. The operator is left to ponder what the root cause of such an issue might be.

**Comment by brandond** [comment]
Kubernetes itself requires a default route on the host. It doesn't have to actually route anywhere, you can just black-hole it, but it's a basic requirement.

**Comment by TFBW** [comment]
Then an explicit failure message to that effect would be better than simply running off the rails.

**Comment by brandond** [comment]
There's an upstream issue for this, but it went stale and was closed because they do not consider it a common enough use case to handle:
https://github.com/kubernetes/kubernetes/issues/57534

TBH it's not something we see too often either. Feel free to put in a docs or installer PR.

**Comment by shreya-bhatnagar** [comment]
I am trying to do airgap installation of k3s. I did below steps:
  1.   copied [install.sh script](https://get.k3s.io/) to `/usr/local/bin/`
  2.   copied k3s binary (downloaded from [Assets](https://github.com/k3s-io/k3s/releases/tag/v1.22.3+k3s1)) to `/usr/local/bin`/
  3. ` cd /usr/local/bin/` 
  4.  `chmod 770 k3s` - giving executable rights to k3s binary
  5.  placed [airgap-images-amd64.tar](https://github.com/k3s-io/k3s/releases/download/v1.22.3%2Bk3s1/k3s-airgap-images-amd64.tar) image at `/var/lib/rancher/k3s/agent/images/` path
  6. ` INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh`  - ran install script
  7. Facing error in k3s service, I found its [an open issue for offline installation](https://github.com/k3s-io/k3s/issues/1103)
  8. `sudo ip route add default via 172.19.0.1` - as per [comment](https://github.com/k3s-io/k3s/issues/1144#issuecomment-559316077) : **_Though its not permanent solution, as comment says that after reboot the default config will go away. Plz let me know the permanent solution for this ._**
  9. The default `kube-system` pods came up  but pods are failing. 
 10. plz find attached `journalctl -u k3s` logs [journalctl_k3s_logs.txt](https://github.com/rancher/rke2/files/7510468/journalctl_k3s_logs.txt). Also `/var/log/k3s.log` **not** got created on this machine.
  
**Error I am getting now:**
Pods in Airgap/offline installation are not able to pull images.` kubectl describe pod coredns` gives error:
Warning  FailedCreatePodSandBox  17s (x2 over 39s)  kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: Try again

Can someone let me know how to resolve this ?
