### ISSUE TITLE
Certificate error not containing node-id on etcd join

### ISSUE THREAD

**Issue by quick691fr** [rancher/rke2#1248]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.18.20+rke2r1 (ad6f2bd5821f2ccea8dabc4b3a02ed54021bb24b)
go version go1.13.15b4

Node(s) CPU architecture, OS, and Version: 
Linux rancher-1.test.com 5.13.0-1.el8.elrepo.x86_64 #1 SMP Sun Jun 27 19:44:44 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 servers, each server has 2 network card, one named mgmt for management and external communication with clients, second one named hb for cluster internal communications. all network and routes correclty configured and hosts able to ping on each network. 

All DNS entries are correctly configured :

rancher.test.com : A 10.81.51.1
rancher.test.com : A 10.81.51.2
rancher-1.test.com : A 10.81.51.1
rancher-2.test.com : A 10.81.51.2

rancher.hb.test.com: A 10.81.41.1
rancher.hb.test.com: A 10.81.41.2
rancher-1.hb.test.com: A 10.81.41.1
rancher-2.hb.test.com: A 10.81.41.2

config.yaml on first node :
```
token: XXXXXXXXXXXXXXXXXXXX
tls-san:
  - rancher.test.com
  - rancher.hb.test.com
  - rancher-1.test.com
  - rancher-2.test.com
  - rancher-1.hb.test.com
  - rancher-2.hb.test.com
node-ip: 10.81.41.1
node-external-ip: 10.81.51.1
audit-policy-file: /etc/rancher/rke2/audit_log_policy.yml
```

config.yaml on second node :
```
server: https://rancher-1.hb.test.com:9345
token: XXXXXXXXXXXXXXXXXXXX
tls-san:
  - rancher.corp.test.com
  - rancher.hb.test.com
  - rancher-1.test.com
  - rancher-2.test.com
  - rancher-1.hb.test.com
  - rancher-2.hb.test.com
node-ip: 10.81.41.2
node-external-ip: 10.81.51.2
audit-policy-file: /etc/rancher/rke2/audit_log_policy.yml
```

**Describe the bug:**
Node 1 is starting correctly, Node 2 is stating certificate error on etcd join :

Jul  6 09:59:16 ip-10-81-52-86 rke2[5296]: {"level":"warn","ts":"2021-07-06T09:59:16.322Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-754a5064-78e1-4d63-b506-7e1c81f04f50/10.81.41.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 127.0.0.1, **10.81.51.1, 10.81.51.1**, 10.43.0.1, not **10.81.41.1**\""}

Is that normal to have 2 times external ip 10.81.51.1 in certificate and not the internal one 10.81.41.1 ?

**Steps To Reproduce:**
- Installed RKE2
- use config files as attached
- check the /var/log/message log file on node 2

**Expected behavior:**
Able to use node-ip for etcd and internal cluster communication and external-node-ip for public traffic or maybe I badly catched what is supposed to be node-ip and external-node-ip ?

**Actual behavior:**
Unable to create the cluster with node-ip and external-node-ip set.

**Additional context / logs:**
N/A

**Comment by brandond** [comment]
This appears to be similar to the configuration described in https://github.com/k3s-io/k3s/issues/3551. In particular, the way you're using node-external-ip to refer to an IP directly bound to an interface is not in line with its intended use, see: https://github.com/k3s-io/k3s/issues/3551#issuecomment-872039775

In general, we don't test on configurations where nodes have multiple interfaces that are intended to be used for different portions of cluster communication. You best bet would be to use one interface for all supervisor/control-plane communication, and bind the CNI to another dedicated interface if necessary.

**Comment by quick691fr** [comment]
@brandond Thanks for answer, do you have a tutorial in order to achieve :  bind the CNI to another dedicated interface if necessary. ?

**Comment by brandond** [comment]
That's generally CNI specific, and covered in their docs and/or helm chart values.
