### ISSUE TITLE
[1.21 backport] rke2-calico cni install does not honor global.systemDefaultRegistry

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1254]
Below is copied from parent issue, #1236 

Environmental Info:
RKE2 Version: v1.21.2+rke2r1
Install via rke2.linux-amd64.tar.gz

Node(s) CPU architecture, OS, and Version: 3.10.0-1160.21.1.el7.x86_64

Cluster Configuration: 3 servers, 6 agents

Describe the bug:
Calico CNI installation does not pull Calico images from custom system-default-registry. On servers, mirrored-calico-(kube-controllers|pod2daemon-flexvol|typha) images were incorrectly pulled from docker.io. On agents, mirrored-calico-(cni|pod2daemon-flexvol|node) were also pulled from docker.io. All other images on the nodes were correctly pulled from the custom system-default-registry.

Steps To Reproduce:

    Installed RKE2: via github.com/rancherfederal/rke2-ansible tarball_install with inventory/sample/group_vars/rke2_(agents|servers).yml updated with:

rke2_config:
  cni: calico
  system-default-registry: "<my_system_default_registry>"
...

Expected behavior:
Running ctr container ls | grep docker | wc -l on servers/agents returns 0

Actual behavior:
Running ctr container ls | grep docker | wc -l on servers/agents returns 3

Additional context / logs:

**Comment by rancher-max** [comment]
#### Validated in v1.21.2-rc4+rke2r2

This is now correctly honoring systemDefaultRegistry. 

The only potential issue I see is that our images.txt file in the artifacts only has the canal (default cni) images. Should we update this to have all cni images? I had to ensure the following were present in my registry:
```
rancher/mirrored-calico-node:v3.19.1
rancher/mirrored-calico-cni:v3.19.1
rancher/mirrored-calico-kube-controllers:v3.19.1
rancher/mirrored-calico-pod2daemon-flexvol:v3.19.1
rancher/mirrored-calico-typha:v3.19.1
rancher/mirrored-calico-operator:v1.17.4
```

**Comment by manuelbuil** [comment]
> #### Validated in v1.21.2-rc4+rke2r2
> 
> This is now correctly honoring systemDefaultRegistry.
> 
> The only potential issue I see is that our images.txt file in the artifacts only has the canal (default cni) images. Should we update this to have all cni images? I had to ensure the following were present in my registry:
> 
> ```
> rancher/mirrored-calico-node:v3.19.1
> rancher/mirrored-calico-cni:v3.19.1
> rancher/mirrored-calico-kube-controllers:v3.19.1
> rancher/mirrored-calico-pod2daemon-flexvol:v3.19.1
> rancher/mirrored-calico-typha:v3.19.1
> rancher/mirrored-calico-operator:v1.17.4
> ```

When using calico, you should download another set of images, as explained in https://docs.rke2.io/install/airgap/#tarball-method
