### ISSUE TITLE
 [release-1.21] INSTALL_RKE2_COMMIT installation method does not work

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1255]
Backport fix for "INSTALL_RKE2_COMMIT installation method does not work" to branch release-1.21:
* #1252

**Comment by manuelbuil** [comment]
Not needed. Problem fixed in the script that uploads the tarballs

**Comment by brandond** [comment]
#1260 fixed this on master, but has not been backported to 1.21 or earlier. Reopening, and will open issues for other branches.

**Comment by rancher-max** [comment]
This appears to be working on release-1.21 branch. Validated using latest commitid: `2ed0b0d1b6924af4414393cd1796c174a1ff5352`
