### ISSUE TITLE
[release-1.20] Registry endpoint URI scheme ignored when pulling runtime image 

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1265]
Backport fix to branch `release-1.20`:
*  #1246

**Comment by rancher-max** [comment]
Closing as this has been validated on the 1.21 line by the user who submitted the issue, and uses the same underlying wharfie fixes.

I validated that other responsibilities of wharfie such as tarball installs, private registry, airgap, etc. continues to work but have been unable to recreate the original issue for this. As such I believe this is safe to close.
