### ISSUE TITLE
[Docs] Document initial and experimental Windows agent support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1276]
Provide a simple one page document to rke2 docs for v1.21.3+rke2r1 initial and experimental windows agent support.

I propose we keep it quite simple to start. Create a page to be a child of the main Installation parent, it will mention Windows (Experimental) Install

It will provide a few steps to install a windows agent via install.ps1
It should briefly talk about $Version, $Channel, etc params.

It should provide a simple example using -Channel latest

Again - we need to be very careful/clear that this initial support was added in v1.21.3+rke2r1 and is experimental.

**Comment by davidnuzik** [comment]
Due by Friday 7/16/2021. @rosskirkpat @luthermonson @phillipsj 
Come to me with questions, keep it simple, yet explain key params and provide an example.
Suggest simple steps like at https://docs.rke2.io/install/quickstart/#agent-worker-node-installation and just explain the params briefly such as for channel and version. Provide one or two example install methods. Since there is no vanity url to grab this from, ensure you mention need to download install.ps1 to the windows host. Indicate which windows versions are supported for this experimental windows agent.

**Comment by rosskirkpat** [comment]
@davidnuzik Below are the current docs written for Windows on RKE2. I believe they meet your requirements. 

https://gist.githubusercontent.com/rosskirkpat/3e009973cf5cdd27c986c2ba4415063a/raw/69f2e7a7d7393377adf66834f1eba9606851a232/rke2-windows-docs.md

**Comment by davidnuzik** [comment]
Generally that gist LGTM. Config stuff might more appropriately belong in https://docs.rke2.io/install/install_options/install_options/ section where we talk about config files, etc. not sure.

Probably good starting point to get a PR in for the team to review :) 
Pretty sure it's mostly good to go - let's get eyes on it in a PR.

**Comment by brandond** [comment]
Closing; no testing needed for docs PR.
