### ISSUE TITLE
Automatic node naming feature parity with RKE

### ISSUE THREAD

**Issue by VelociPods** [rancher/rke2#1286]
**Is your feature request related to a problem? Please describe.**

Automatic node naming feature parity with RKE where environments have names and addresses pre-allocated.

**Describe the solution you'd like**

RKE seems to automatically set the node-name according to the cloud-provider. RKE2 does not and requires this to be set. Automatic node naming according to the cloud-provide to be added.

**Describe alternatives you've considered**

1) Resetting the hostname of the box before starting RKE2. Not possible due to hostname policy.
hostnamectl set-hostname "$(curl http://169.254.169.254/latest/meta-data/hostname)"

or

2) dynamically set the node-name each time the config is dropped. Not ideal.

export CLOUD_PROVIDER_NODE_NAME=$(curl http://169.254.169.254/latest/meta-data/hostname)
cat > /etc/rancher/rke2/config.yaml << EOF
cloud-provider-name: aws
node-name: ${CLOUD_PROVIDER_NODE_NAME}
EOF

**Additional context**

Example of RKE function wanted in RKE2

nodes:
- address: 172.31.15.22
port: "22"
role:
- controlplane
- worker
- etcd
user: ubuntu
services:
kube-api:
service_cluster_ip_range: 10.43.0.0/16
kube-controller:
cluster_cidr: 10.42.0.0/16
service_cluster_ip_range: 10.43.0.0/16
kubelet:
cluster_dns_server: 10.43.0.10
network:
plugin: canal
authentication:
strategy: x509
ssh_key_path: ~/.ssh/id_rsa
authorization:
mode: rbac
cloud_provider:
name: "aws"

This spins up automatically, setting the node-name to the AWS hostname required by the cloud-provider.

example:

ubuntu@test:~$ kubectl get nodes
NAME STATUS ROLES AGE VERSION
ip-172-31-15-22.us-gov-east-1.compute.internal Ready controlplane,etcd,worker 3m2s v1.20.6

**Comment by brandond** [comment]
> Resetting the hostname of the box before starting RKE2. Not possible due to hostname policy.

Can you say a bit more about this? Why are you unable to set the hostname to the cloud provider node name?

**Comment by tuckcodes** [comment]
> > Resetting the hostname of the box before starting RKE2. Not possible due to hostname policy.
> 
> Can you say a bit more about this? Why are you unable to set the hostname to the cloud provider node name?

Hostnames are pre-defined and assigned via a third party upon approval.
