### ISSUE TITLE
Windows and Calico support

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1289]
This is an issue to track supporting windows in rke2, issues to track for testing and backporting.

**Comment by rancher-max** [comment]
I'm going to use this as the main issue for validating windows on v1.22 in rke2. There are multiple other issues related to windows support in general that I'm going to close in favor of this.

**Comment by rancher-max** [comment]
Validated that windows installs are working in v1.22.2-rc1+rke2r1 when using calico as the cni. I am able to deploy workloads and services successfully.
