### ISSUE TITLE
Retest in rke2 some K3s fixes

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1292]
When finishing https://github.com/rancher/rke2/pull/1268 we pinned k3s to a new version which includes these k3s fixes. Adding an issue to track testing of these issues to confirm they are fixed in rke2 also.

https://github.com/k3s-io/k3s/pull/3537
https://github.com/k3s-io/k3s/pull/3527
https://github.com/k3s-io/k3s/pull/3586
https://github.com/k3s-io/k3s/pull/3475

**Comment by rancher-max** [comment]
I'm going to close this out as there are separate issues for each of these where relevant, and they have already been validated.
