### ISSUE TITLE
[1.21 backport] Retest in rke2 some K3s fixes

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1293]
When https://github.com/rancher/rke2/issues/1290 is closed it will contain a pin of k3s to a new version which includes these k3s fixes. Adding an issue to track testing of these issues to confirm they are fixed in rke2 also.

https://github.com/k3s-io/k3s/pull/3537
https://github.com/k3s-io/k3s/pull/3527
https://github.com/k3s-io/k3s/pull/3586
https://github.com/k3s-io/k3s/pull/3475

**Comment by ShylajaDevadiga** [comment]
Validated in rke2 version v1.21.3-rc7+rke2r1
