### ISSUE TITLE
[1.21 backport] Multi-OS Support for RKE2 runtime and binary builds (Adding Windows) 

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1299]
Opening to track the backport of #1212

**Comment by rancher-max** [comment]
I am able to run windows on v1.21.3 in a basic setup. The full scope of the test plan still needs to be executed, which includes airgap testing.

**Comment by rancher-max** [comment]
There have been two airgap issues to come from this: 
https://github.com/rancher/rke2/issues/1647 and https://github.com/rancher/rke2/issues/1648. I'm going to close this out as these are the remaining tasks and are tracked separately.
