### ISSUE TITLE
RPM Installer

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#13]
Based on recent discussions with the Rancher Federal team and Will, a full RPM installer is a must for MVP.

If a supplemental RPM is needed such as for SELinux policy this is okay. Best case one RPM does everything (is this possible?)

**Is waiting on internal eio issue rancher/rke2#36  to be completed.**

**Comment by leolb-aphp** [comment]
Distro packages in general make it very convenient for maintenance over time. I'm also very interested in this. I'm kind of disappointed that the Kubernetes eco-system does not use standard distro tools for installation and configuration of Kubernetes services and relies on custom tools, probably for a good reason but I'm wondering if it's possible to do without, by now. Lots of sysadmins have been relying on distro tools and packages for maintenance of their servers and it's been working relatively well for decades. Integrated, maintained, uniform.

The problem I see here is lack of ability to install packages in a distributed way as well as pushing configuration. Debian can do single-machine configuration with debconf, unsure about rpm-based distros.

Then we get into the realm of saltstack, ansible, chef, etc. which you can use to install RPMs/DEBs and push configurations, at least for the case of ansible, which looks OK but maybe not the best to provide a low friction experience.

What could be possible maybe is write a usage template of an ansible role or whatever which one can easily customize to their needs, in a way, kubespray is already this, but without support.

**Comment by davidnuzik** [comment]
Bumping out of alpha milestone into beta.

**Comment by ShylajaDevadiga** [comment]
Testing of this issue is covered #86. @Oats87 Please let me know if anything needs to be included for testing

**Comment by ShylajaDevadiga** [comment]
RPM multi master, multi agent  install is successful on CentOS 7.8 and RHEL 7.8. 
1. Create repo file
2. Create dir /etc/rancher/rke
3. Create config file with params to be passed to install
4. Install rke2-server package
5. Start the service 

Refer to docs for updated sample files.
For server
```
yum install rke2-server
```
For agent
```
yum install rke2-agent
```
All files installed by rpm are removed using 
```
yum remove rke2-server, rke2-common, rke2-selinux
```
