### ISSUE TITLE
All-in-One setup: how to run both server and agent on the same node 

### ISSUE THREAD

**Issue by Dimss** [rancher/rke2#1302]
With RKE1, there was an option to specify the node roles to make the node all-in-one K8s cluster. 
How same behavior can be archived with RKE2?

**Comment by mitchellmaler** [comment]
Check this out https://docs.rke2.io/install/ha/#2a-optional-consider-server-node-taints
By default the severs do not have taints set so can run normal workloads.

**Comment by Dimss** [comment]
Alright, thanks a lot!

**Comment by lee-b** [comment]
The link above is broken.  Can you please document this here, in the ticket, or with a permalink?

**Comment by brandond** [comment]
The answer is simple, rke2 servers include and agent by default. And as the comment in that previous message indicated, the servers also do not have taints. For any additional questions, please check the docs.
