### ISSUE TITLE
Update sysctl Values Only If Necessary

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#131]
The way the install script currently works is that it'll append creating duplicate entries.

**Comment by briandowns** [comment]
PR #135 resolves this issue.

To test:

Run installation in CIS mode. Check `/etc/sysctl.d/local.conf` to see if it has sysctl values. 

```
cat /etc/sysctl.d/local.conf
```

Then run the installation again in CIS mode. The `/etc/sysctl.d/local.conf` file should have the same contents. That can be verified running:

```
cat /etc/sysctl.d/local.conf
```

For further validation, delete `/etc/sysctl.d/local.conf` and run the installation again in CIS mode.

**Comment by davidnuzik** [comment]
We should put this on hold and not touch it until the refactor of the install.sh script happens.

**Comment by davidnuzik** [comment]
install.sh refactor is done and ready for testing from master.

**Comment by rancher-max** [comment]
The install.sh refactor has changed how this is done. It is now a manual step expected to be performed by the operator. Examples of values to set: `vm.panic_on_oom=0 kernel.panic=10 kernel.panic_on_oops=1 kernel.keys.root_maxbytes=25000000 vm.overcommit_memory=1`

Closing this issue as no longer relevant.
