### ISSUE TITLE
[release-1.19] INSTALL_RKE2_COMMIT installation method does not work

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1313]
Backport fix for "INSTALL_RKE2_COMMIT installation method does not work" to branch release-1.19:
* #1252

**Comment by rancher-max** [comment]
This is not working using release-v1.19 branch. Tried on both the latest commit: `9485245cbcb06611b596c6f0230331057657600d` and the commit associated with the merge: `f9146dcb2b86dc55e08db79d306fc5483ff7b047`. In both cases I see the same error:
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=9485245cbcb06611b596c6f0230331057657600d sh -
[INFO]  using commit 9485245cbcb06611b596c6f0230331057657600d as release
[INFO]  downloading airgap checksums at https://storage.googleapis.com/rke2-ci-builds/rke2-images.linux-amd64-9485245cbcb06611b596c6f0230331057657600d.tar.gz.sha256sum
curl: (22) The requested URL returned error: 404 
```

**Comment by brandond** [comment]
I'm not sure we ever backported this to the 1.19 branch to begin with; I'm OK with closing this as WONTFIX.

**Comment by rancher-max** [comment]
I think you're right and am okay with that as well. Closing
