### ISSUE TITLE
[release-1.20] Updating k3s to latest master commit

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#1319]
Issues linked to bumping k3s version to 

- https://github.com/k3s-io/k3s/issues/2348
- https://github.com/k3s-io/k3s/issues/3496
- https://github.com/k3s-io/k3s/issues/3438
- https://github.com/k3s-io/k3s/issues/3585
- https://github.com/k3s-io/k3s/issues/3600
- https://github.com/rancher/rke2/issues/1157
- https://github.com/rancherlabs/rancher-security/issues/501

**Comment by ShylajaDevadiga** [comment]
Closing validating as part of patch release.
