### ISSUE TITLE
[1.21 release] Move rancher/hardened-kubernetes build to rancher/image-build-kubernetes

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1321]
backport of https://github.com/rancher/rke2/issues/1294

**Comment by rancher-max** [comment]
Confirmed in v1.21.3-rc7+rke2r1 that kube-proxy static pods are correctly using the rancher/hardened-kubernetes image:
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/55997940/126691652-215ed207-7236-4332-a1af-e4e185524ac9.png">
