### ISSUE TITLE
[release-1.19] Updating k3s to latest release-1.19 commit

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#1324]
k3s issues linked to this update:

- https://github.com/k3s-io/k3s/issues/3170
- https://github.com/k3s-io/k3s/issues/3301
- https://github.com/rancher/k3d/issues/607
- https://github.com/k3s-io/k3s/issues/3543

**Comment by ShylajaDevadiga** [comment]
Closing Validated as part of patch release.
