### ISSUE TITLE
Using different containerd root 

### ISSUE THREAD

**Issue by Dimss** [rancher/rke2#1329]
I'd like to change the default containerd root. 
To do so, I followed this [docs](https://docs.rke2.io/advanced/#configuring-containerd), and I end up with generated `config.toml` file, that looks like that
```
root = "/datadrive/containerd-rke2"

[plugins.opt]
  path = "/var/lib/rancher/rke2/agent/containerd"
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "index.docker.io/rancher/pause:3.2"

[plugins.cri.containerd]
  disable_snapshot_annotations = true
  snapshotter = "overlayfs"

[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
``` 

After the restart of `rke2` the `/datadrive/containerd-rke2` was still empty. 
Then I noticed that containerd process was started with explicity set `--root` flag
```
containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml \
  -a /run/k3s/containerd/containerd.sock \
  --state /run/k3s/containerd \
  --root /var/lib/rancher/rke2/agent/containerd
```

And the question is, how I can change the `root` parameter for `containerd` process?

**Comment by brandond** [comment]
Does just setting --data-dir not accomplish what you're trying to do?

**Comment by Dimss** [comment]
it does, I should to look more carefully the `rke2 server -h` output. 
Thank you.
