### ISSUE TITLE
symlinks appear to be left behind after running rke2-uninstall shell script

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#133]
v1.18.4-alpha14+rke2 and v1.18.4-alpha22+rke2
ubuntu 20.04 amd64

This might not technically be a bug - perhaps an enhancement to improve rke2-uninstall.sh shell script. I wasn't quite sure how to categorize it.

If I install RKE2 like below, wait for everything to be fully ready, then execute rke2-uninstall.sh some symlinks are left behind in /usr/local/bin.

`curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha22+rke2 sh -`

```
root@ip-172-31-5-119:/usr/local/bin# ls -laht
total 43M
drwxr-xr-x  2 root root 4.0K Jul 28 02:04  .
lrwxrwxrwx  1 root root   34 Jul 28 01:53 '*' -> '/var/lib/rancher/rke2/data/*/bin/*'
lrwxrwxrwx  1 root root  100 Jul 28 01:33  runc -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/runc
lrwxrwxrwx  1 root root  103 Jul 28 01:33  kubelet -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/kubelet
lrwxrwxrwx  1 root root  119 Jul 28 01:33  containerd-shim-runc-v2 -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/containerd-shim-runc-v2
lrwxrwxrwx  1 root root  119 Jul 28 01:33  containerd-shim-runc-v1 -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/containerd-shim-runc-v1
lrwxrwxrwx  1 root root  111 Jul 28 01:33  containerd-shim -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/containerd-shim
lrwxrwxrwx  1 root root  106 Jul 28 01:33  containerd -> /var/lib/rancher/rke2/data/74bfb2ffe9b156f4c2c4320d556cce5f42b08b67a985164ef971122e42afdf94/bin/containerd
drwxr-xr-x 10 root root 4.0K Apr 23 08:12  ..
```

I would think these should be cleaned up probably.

Additionally (this may need a new issue) I'm curious if there are other areas for improvement in the rke2-uninstall.sh script. Perhaps cleaning up more stuff in /opt, /var/lib/rancher, /etc/rancher (But I think just like with k3s we want to leave token there?), etc.

**Comment by davidnuzik** [comment]
As per https://github.com/rancher/rke2/issues/138 the install script will not be available any longer. The RPM will be the recommended way to install RKE2. Later, we may create a DEB package as well (and perhaps repo). This is TBD and that issue should be referenced or used for any questions/comments.

**Comment by davidnuzik** [comment]
We decided to not remove the install script, as such -- reopening this issue to verify and ensure it's not still an issue by testing with the newly refactored install script in the release tarball.

**Comment by ShylajaDevadiga** [comment]
As of beta17, with the refactored install script we do not have symlinks in /usr/local/bin dir. But we have an issue with rke2 binary not being cleaned up after rke2-uninstall.sh is run. 
```
ls -laht
total 151M
-rwxr-xr-x  1 root root 151M Sep  4 22:53 rke2
```

Uninstall script related issues are tracked in https://github.com/rancher/rke2/issues/260. Closing this issue in favor of the tracking issue.
