### ISSUE TITLE
Unhide the --cluster-reset flag

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#139]
Based on a discussion with Darren, we should actually unhide the --cluster-reset flag as this is the only way to restore quorum. This may need documentation as well such as in README.md or in /docs directory.

So this issue has two parts. Unhide the flag in cli. Briefly document in GitHub in the project.

**Comment by briandowns** [comment]
The issue appears to be a dqlite build flag in k3s that is preventing the exposure of this flag. 

See files:

`pkg/cli/cmds/dqlite.go`
`pkg/cli/cmds/nocluster.go`

The variables in `pkg/cli/cmds/server.go` will need to be updated where `hideDqlite` is being used.

**Comment by ibuildthecloud** [comment]
Yep, remove any reference to dqlite.

**Comment by rancher-max** [comment]
Validated the flag is unhidden with current master builds. For the second part of this issue, we don't have any explicit documentation yet. Do we want to leave this open until we document or have an overarching documentation issue to cover this and some of the other things we are currently missing?

**Comment by davidnuzik** [comment]
@rancher-max I created https://github.com/rancher/rke2/issues/275 to track documentation efforts. You may close the issue.
