### ISSUE TITLE
Agent nodes fail to upgrade via SUC

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1405]
**Environmental Info:**
RKE2 Version: 

Initial Version: v1.19.12+rke2r1
Upgrade Version: v1.19.13-rc1+rke2r1

Node(s) CPU architecture, OS, and Version: 

Centos 8: `Linux ip-172-31-14-90.us-east-2.compute.internal 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 servers 1 agent

**Describe the bug:**

Agents wait for servers to upgrade before beginning their upgrade. During this time, an init container runs and waits to see that the server nodes have upgraded. Since the upgrade specifies v1.19.13-rc1+rke2r1, but the kubernetes version after upgrading shows `v1.19.13+rke2r2`, the init pod logs just continuously loop with:
```
[INFO]  Waiting for all master nodes to be upgraded to version 
+ continue
+ true
+ all_updated=true
+ kubectl get nodes '--selector=node-role.kubernetes.io/master' -o json
+ jq -r '.items[].status.nodeInfo.kubeletVersion'
+ sort -u
+ tr + -
+ MASTER_NODE_VERSION=v1.19.13-rke2r2
+ '[' -z v1.19.13-rke2r2 ]
+ '[' v1.19.13-rke2r2 '==' v1.19.13-rc1-rke2r1 ]
+ info 'Waiting for all master nodes to be upgraded to version '
+ echo '[INFO] ' 'Waiting for all master nodes to be upgraded to version '
+ sleep 5
[INFO]  Waiting for all master nodes to be upgraded to version 
```

**Steps To Reproduce:**

- Install rke2 initial version
- Upgrade using SUC to specified version

**Expected behavior:**

Upgrade succeeds on all server and agent nodes

**Actual behavior:**

Upgrade only succeeds on server nodes

**Additional context / logs:**

**Comment by brandond** [comment]
Fixed by: 
* rancher/rke2-upgrade#9

**Comment by rancher-max** [comment]
SUC has not been validated on 1.22 yet. There will be extensive upgrade testing done as soon as an RC is made available, so I'm going to close this in favor of whatever (if anything) that testing turns up.
