### ISSUE TITLE
RKE2 works on command line but not via Systemd

### ISSUE THREAD

**Issue by ride808** [rancher/rke2#1435]
**Environmental Info:**

RKE2 Version:  

$rke2 -v
```
rke2 version v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)
go version go1.15.8b5

```
$ yum list installed | grep -i rke
```
rke2-common.x86_64                1.20.6~rke2r1-0.el7        @rke2-v1.20
rke2-selinux.noarch               0.7-1.el7                  @rancher-rke2-common-latest
rke2-server.x86_64                1.20.6~rke2r1-0.el7        @rke2-v1.20
```

Node(s) CPU architecture, OS, and Version: 
$uname -a
` Linux dev2-rancher-node-1 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
$ sudo getenforceS
`Enforcing
`
Containerd is not installed on hosts and only leveraging the embedded within rke2
Cgroup2 not enabled in Kernel

Cluster Configuration:
3 server nodes, zero agents currently

**Describe the bug:**
When running rke2 from command line (ex.  sudo rke2 server) on a node, the node completely spins up with all kubernetes resources running.  However, with the yum install, and starting rke2-server.serivce through systemd, it does not get past the pulling of the rke2-runtime image and nothing gets popluated (binaries, etc) in /var/lib/rancher/rke2/data.
 
Systemd Output:
```
Jul 21 23:32:28 dev2-rancher-node-1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Jul 21 23:32:28 dev2-rancher-node-1 systemd[1]: Started Rancher Kubernetes Engine v2 (server).
Jul 21 23:32:28 dev2-rancher-node-1 rke2[6440]: time="2021-07-21T23:32:28Z" level=debug msg="No local image available for index.docker.io/rancher/rke2-runtime:v1.20.6-rke2r1: directory /var/lib/rancher/rke2/agent/images does not exist"
Jul 21 23:32:28 dev2-rancher-node-1 rke2[6440]: time="2021-07-21T23:32:28Z" level=debug msg="No local image available for myregistry.mydomain.com/rancher/rke2-runtime:v1.20.6-rke2r1: directory /var/lib/rancher/rke2/agent/images does not exist"
Jul 21 23:32:28 dev2-rancher-node-1 rke2[6440]: time="2021-07-21T23:32:28Z" level=info msg="Using registry config file at /etc/rancher/rke2/registries.yaml"
Jul 21 23:32:28 dev2-rancher-node-1 rke2[6440]: time="2021-07-21T23:32:28Z" level=info msg="Pulling runtime image myregistry.mydomain.com/rancher/rke2-runtime:v1.20.6-rke2r1"
Jul 21 23:35:04 dev2-rancher-node-1 rke2[6440]: time="2021-07-21T23:35:04Z" level=fatal msg="chmod /var/lib/rancher/rke2/data/v1.20.6-rke2r1-9ce6d7c5360b/bin: no such file or directory"
Jul 21 23:35:09 dev2-rancher-node-1 systemd[1]: rke2-server.service holdoff time over, scheduling restart.
Jul 21 23:35:09 dev2-rancher-node-1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
```

**Steps To Reproduce:**

1) Installed RKE2: 

   yum install -y rke2-server-1.20.6~rke2r1-0.el7

2)  Create config  /etc/rancher/rke2/config.yaml

```
profile: cis-1.5
selinux: true
kubelet-arg: feature-gates=DynamicKubeletConfig=false
kubelet-arg: image-pull-progress-deadline=30m
kubelet-arg: max-pods=150
kubelet-arg: enforce-node-allocatable='pods'
kubelet-arg: system-reserved='cpu=500m,memory=300Mi,ephemeral-storage=1Gi'
kubelet-arg: kube-reserved='cpu=500m,memory=300Mi,ephemeral-storage=1Gi'
kubelet-arg: eviction-hard='memory.available<1Gi,nodefs.available<10%'
node-label: ansible-provisioned-server=true
system-default-registry: myregistry.mydomain.com
tls-san: mydomain.com
etcd-snapshot-retention: 10
write-kubeconfig-mode: "0644"
kube-apiserver-arg: tls-min-version=VersionTLS12
kube-scheduler-arg: tls-min-version=VersionTLS12
kube-controller-manager-arg: tls-min-version=VersionTLS12
```
3) Create Registry Config  /etc/rancher/rke2/registries.yaml:

```
mirrors:
  "myregistry.mydomain.com":
    endpoint:
      - "https://myregistry.mydomain.com"
  docker.io:
    endpoint:
      - "https://myregistry.mydomain.com" 
```

4) sudo systemctl start rke2-server.service

**Expected behavior:**

Systemd service runs and brings node to ready state with pods/containers running with no different result than running the rke2 binary from the command line

**Actual behavior:**
sudo systemctl start rke2-server start   gets hung on pulling the rke2-runtime image where as running rke2 server runs to completion.

**Additional context / logs:**

**Comment by brandond** [comment]
Have you also installed the required selinx packages? Normally this would be handled for you by the install script.

**Comment by brandond** [comment]
Can you add `debug: true` to your config.yaml?

**Comment by ride808** [comment]
The debug flag didn't seem to produce any more logs at this stage in the process. Is there anything I should verify within systemd for as service to be able to start/use containers?  Also is there a way to verify the embedded containerd can pull the rke2-runtime image?  

```
Jul 22 13:18:55 dev2-rancher-node-1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Jul 22 13:18:55 dev2-rancher-node-1 systemd[1]: Started Rancher Kubernetes Engine v2 (server).
Jul 22 13:18:56 dev2-rancher-node-1 rke2[28554]: time="2021-07-22T13:18:56Z" level=debug msg="No local image available for index.docker.io/rancher/rke2-runtime:v1.20.6-rke2r1: directory /var/lib/rancher/rke2/agent/images does not exist"
Jul 22 13:18:56 dev2-rancher-node-1 rke2[28554]: time="2021-07-22T13:18:56Z" level=debug msg="No local image available for myregistry.mydomain.com/rancher/rke2-runtime:v1.20.6-rke2r1: directory /var/lib/rancher/rke2/agent/images does not exist"
Jul 22 13:18:56 dev2-rancher-node-1 rke2[28554]: time="2021-07-22T13:18:56Z" level=info msg="Using registry config file at /etc/rancher/rke2/registries.yaml"
Jul 22 13:18:56 dev2-rancher-node-1 rke2[28554]: time="2021-07-22T13:18:56Z" level=info msg="Pulling runtime image myregistry.mydomain.com/rancher/rke2-runtime:v1.20.6-rke2r1"
Jul 22 13:21:31 dev2-rancher-node-1 rke2[28554]: time="2021-07-22T13:21:31Z" level=fatal msg="chmod /var/lib/rancher/rke2/data/v1.20.6-rke2r1-9ce6d7c5360b/bin: no such file or directory"
Jul 22 13:21:36 dev2-rancher-node-1 systemd[1]: rke2-server.service holdoff time over, scheduling restart.
Jul 22 13:21:36 dev2-rancher-node-1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
```

**Comment by ride808** [comment]
I'm not sure why, but after giving the service sudo it worked without issue. Below is a task I had to add to my ansible to add using sudo to the ExecStart.  Any thoughts on why I'd need to do that?  The service is running as root (I confirmed that).

```
- name: Ensure rke2-server is run with sudo
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/rke2-server.service
    regexp: 'ExecStart=/usr/bin/rke2 server'
    line: ExecStart=/usr/bin/sudo /usr/bin/rke2 server
  become: yes
```

**Comment by brandond** [comment]
No, that doesn't make any sense to me. We've changed some things in this code path in the last few releases though - you might see if you can duplicate this with 1.20.8 (or 1.20.9 later today when it's released).

**Comment by cubic3d** [comment]
@ride808 You have duplicate `kubelet-arg` keys in your yaml config - this is not how yaml work. Probably that is the problem? Use a list instead:
```
kubelet-arg:
  - arg1
  - arg2
```

**Comment by ride808** [comment]
@cubic3d - good call.  I fixed the rke2 config and the systemd service comes up without issue when not using sudo.  Not sure why that helped in the first place but this is no longer an issue and a configuration/user error problem. Issue may be closed.
