### ISSUE TITLE
[Documentation] rke2 = rke + k3s ?

### ISSUE THREAD

**Issue by ElisaMeng** [rancher/rke2#144]
Interesting, how this is different from rke and k3s?

**Comment by briandowns** [comment]
At a high level:

k3s takes Kubernetes, makes some modifications, and results in a multicall binary with a lot of functionality on top of Kubernetes, at least on the surface. 

RKE2 uses upstream Kubernetes and associated runtime and, uses embedded etcd for it's data store. RKE2 has a focus on security so all Go code is compiled to comply with FIPS 140-2 guidance.

**Comment by ElisaMeng** [comment]
@briandowns  So embedded etcd + FIPS 140-2 are the main difference from rke?

**Comment by cjellick** [comment]
Hopefully the readme explains this a bit. I'll also get docs up that should explain this

**Comment by cjellick** [comment]
moved into GA milestone because I plan for this to be addressed in the documentation and I'll close it out once I'm happy with the docs
