### ISSUE TITLE
Restore from snapshot on new nodes is stuck during starting of the rke2 server

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#1447]
**Environmental Info:**
RKE2 Version: 
v1.21.3-rc7+rke2r1

**Node(s) CPU architecture, OS, and Version:**
NA

**Cluster Configuration:**
Single node or multi node

**Describe the bug:**

- Create a cluster with a single node or multi node
- Take a snapshot and store it in s3 bucket
- Bring up a new fresh node
- Restore from the snapshot
- Run installer and start rke2 server

**Resolution:**
Before starting rke2 server, run rke2-killall.sh

**Comment by rancher-max** [comment]
This has been validated as working on all of the latest releases
