### ISSUE TITLE
Both kube-proxy static pods and helm chart pods running after upgrade to v1.21.3+rke2r1

### ISSUE THREAD

**Issue by mstrent** [rancher/rke2#1458]
Upgrade was automatic via SUC. Coming from version v1.21.2+rke2r1. This issue is related to #1205.

I seem to have both the new static pods and the old Helm pods:
```
> kubectl get pods -n kube-system | grep kube-proxy
kube-proxy-8gmm8                                     1/1     Running   1          3d19h
kube-proxy-b4gkq                                     1/1     Running   1          3d19h
kube-proxy-hhpf5                                     1/1     Running   1          3d19h
kube-proxy-oly-rancher-51d                           1/1     Running   1          3d19h
kube-proxy-oly-rancher-52d                           1/1     Running   1          3d19h
kube-proxy-oly-rancher-53d                           1/1     Running   1          3d19h
```

This results in errors in the helm pods:
E0726 18:29:50.268072       1 server.go:627] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
E0726 18:29:50.360457       1 server.go:587] healthz server failed: failed to start proxier healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use

It seems the check to auto-disable when Helm chart config is present didn't work?
```
> kubectl get configmaps -n kube-system | grep kube-proxy
chart-content-rke2-kube-proxy             1      108d
chart-values-rke2-kube-proxy              1      108d
kube-proxy                                1      108d
```

**Comment by brandond** [comment]
Tracking this under #1455
