### ISSUE TITLE
Create cleanup scripts for windows.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1468]
Windows doesn't currently have scripts for stopping all running processes and uninstalling RKE2. These need to be created similar in functionality to rke2-uninstall.sh and rke2-killall.sh

**Comment by rosskirkpat** [comment]
https://github.com/rancher/rke2/pull/1488

**Comment by rancher-max** [comment]
Validated via https://github.com/rancher/rke2/issues/1497#issuecomment-893621222
