### ISSUE TITLE
[master] Default deployment of rke2-ingress-nginx has load balancer service enabled in RKE2 1.21.2

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1477]
Forwardport fix for "Default deployment of rke2-ingress-nginx has load balancer service enabled in RKE2 1.21.2" to branch master:
* #1446

**Comment by rancher-max** [comment]
Validated on master branch commit `472bd977569e4e2d5b04eb826816aca9c3af8ecb` using the same steps as mentioned in https://github.com/rancher/rke2/issues/1446#issuecomment-896166434
