### ISSUE TITLE
RPM - Provide example config file

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#148]
Per internal discussions, the RPM should deploy an example config file on the host.

I propose we do something similar to some other packages I have seen. For example, in the Debian space I notice that some packages like `Fail2Ban` will provide a default config file with ALL the options plugged into it (but commented out).

I think it would be great if we could do this too - the exception being if the LOE is too high or if this is not standard practice for RPMs.

**Comment by immanuelfodor** [comment]
A `something.conf` file and `something.conf.d` folder is also common, so the user can break down their config to multiple files (`10-something.conf`, `20-other.conf`) or one large file, and so the default can stay commented out on every line with one import to `something.conf.d` folder contents, so it can be updated without change to avoid conflicts or `something.conf.new` files after an update.

**Comment by dereknola** [comment]
Since this has been over 2 years since any "internal discussion" I think this should be brought up in a design meeting.

**Comment by caroline-suse-rancher** [comment]
Closing as this enhancement isn't in our near-term plans
