### ISSUE TITLE
Systemd does not get notified with READY state in etcd only nodes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#1483]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.21.3-rc1+rke2r1 (cd528693af8730fdcce6479870409f7ac4c57446.dirty)
go version go1.16.3

Node(s) CPU architecture, OS, and Version: 
Linux ip-172-31-14-237 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 node (etcd only node)

**Describe the bug:**
ETCD only node gets stuck with systemd since the recent changes of changing the notify for systemd in agent logic and not in server logic

**Steps To Reproduce:**
Install rke2 server with disabling api, controller, and scheduler
restart rke2

**Expected behavior:**
systemctl restart rke2-server restarts rke2 normally
 
**Actual behavior:**
systemctl restart command gets stuck

**Additional context / logs:**

**Comment by rancher-max** [comment]
This is fixed in v1.21.3-rc2+rke2r2. I am able to bring up individual role clusters in rancher:
![image](https://user-images.githubusercontent.com/55997940/128239829-8080bb23-eee6-4349-afed-931837441265.png)
