### ISSUE TITLE
Update the documentation for Windows

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1492]
Update the documentation for Windows:

Move `docs/install/uninstall.md` to `docs/install/linux_uninstall.md`
Update mkdocs.yml to reflect new changes
Fixes an issue with bad download links for `install.ps1`
Introduce docs for the new Windows uninstall script, which is currently under review in https://github.com/rancher/rke2/pull/1488

**Comment by dereknola** [comment]
Closing as it is a documentation only change
