### ISSUE TITLE
Rename flags.conf to config.yaml

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#150]
From https://github.com/rancher/rke2/issues/6 and from recommendation from Darren, rename the config file from flags.conf extension to config.yaml extension.

**Comment by rancher-max** [comment]
#### Validated with rke2 beta14

- Ensured flags.conf no longer functions
- Used a config.yaml file with a tls-san value and validated it is working as expected

**Still need to validate in k3s before closing this issue.**

**Comment by rancher-max** [comment]
Validated this is working in k3s as well by creating a `/etc/rancher/k3s/config.yaml` with contents of: `token: secret` and then validated that was used:
```
$ sudo cat /var/lib/rancher/k3s/server/node-token
K1098df0736c7a8fa8a7f308f71cb09ba5805bcfedacdc831ebaaafe4bcc75e0d4e::server:secret
```
