### ISSUE TITLE
Add tests for nightly builds

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#1502]
**Is your feature request related to a problem? Please describe.**
Ability to run nightly tests

**Describe the solution you'd like**
Initial commit to do basics testing across multiple OS on hardened cluster
Continue to add more tests and increase coverage for existing and new features

Linked PR https://github.com/rancher/rke2/pull/2044

**Comment by katran001** [comment]
Moving this to the next milestone since the team didn't have a chance to work on it for v1.22.5+rke2r1

**Comment by dereknola** [comment]
Both of these tests fulfill this issue.
https://github.com/rancher/rke2/pull/2424
https://github.com/rancher/rke2/pull/2464

**Comment by caroline-suse-rancher** [comment]
Nightly tests now run - closing
