### ISSUE TITLE
FIPS - Etcd secrets encryption

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#151]
We should look into what our options are for encrypting sensitive etcd information. For example Secrets, ConfigMaps, etc.

Further, if we implement this the fips documentation should be updated as well as a part of this effort.

**Comment by cjellick** [comment]
I think the question we now have to answer is whether or not the algorithm we use by default for encyrpting is a fips validated one. If it isnt, that might be ok and we just have to document how to switch to one that is.

**Comment by davidnuzik** [comment]
This is covered in https://docs.rke2.io/advanced/#secrets-encryption-config
Closing.
QA will be taking a holistic look at the docs so this is already covered and I glanced over and seems fine to me.
