### ISSUE TITLE
Adding annotations to PSPs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rke2#1512]
Based on the Rancher integration with it's own ability to manage PSP templates, Rancher is requesting that the PSPs have annotations that match the namespace annotation, so that these PSPs can be identified and deleted when a user selects a default PSP from Rancher.

We'd like to use the following annotations (which are the same ones in the namespace), but have them on the actual PSP as well. 

`psp.rke2.io/global-restricted` or  `psp.rke2.io/global-unrestricted`

**Comment by briandowns** [comment]
This has been resolved in master and the release-1.21 branches.

**Comment by deniseschannon** [comment]
The Rancher requirements have been met, so I'm not clear if this ticket still needs to be open?

**Comment by briandowns** [comment]
I think we need to keep ti open for QA to validate as part of their process for the 1.22 release.

**Comment by briandowns** [comment]
Validated on master.
