### ISSUE TITLE
[Release 1.21] RKE2 Can't Run Workloads with Default Msft Pause Image

### ISSUE THREAD

**Issue by luthermonson** [rancher/rke2#1522]
Booting rke2 without setting the pause image results in using the build tag compiled version which pointed to mcr.microsoft.com. The code to pull default images forces docker.io as a repo and tries to force pulling non-existing images if you do not override the pause image.

**Comment by rancher-max** [comment]
Validated on v1.21.3-rc3+rke2r2 the pause image is working correctly now.
