### ISSUE TITLE
RKE2 not starting up services on RHEL8 

### ISSUE THREAD

**Issue by jcrosel** [rancher/rke2#1539]
**Environmental Info:**
RKE2 Version: 
[myuser@vm1 ~]$ rke2 -v
rke2 version v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux vm1 4.18.0-147.51.2.el8_1.x86_64 #1 SMP Thu Jul 8 06:09:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 VM, Red Hat Enterprise Linux 8, latest patch level, 2 
vCPU, 8GB RAM

/etc/rancher/rke2/config.yaml:
debug: true
selinux: true

**Describe the bug:**
rke2-server does not seem to be able to start its components. 

**Steps To Reproduce:**

**Added some iptable entries**
sudo iptables -A INPUT -p tcp --dport 6443 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 2379 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 2380 -j ACCEPT

**Installed Docker**
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install docker-ce --nobest -y
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER

**Installed and started RKE2 server**
Run the installer: curl -sfL https://get.rke2.io | sh -
Enable the rke2-server service: systemctl enable rke2-server.service
Start the service: systemctl start rke2-server.service
 

**Expected behavior:**
RKE2 server to startup components like etcd, kube-apiserver

**Actual behavior:**
connection errors in log (see attached log file) for 2379 (etcd) and 6443 (kube-apiserver)

**Additional context / logs:**
[log-rke2 - Copy.txt](https://github.com/rancher/rke2/files/6938937/log-rke2.-.Copy.txt)

**Comment by brandond** [comment]
Why are you installing and starting Docker before RKE2? RKE2 uses its own embedded containerd; there is no need to install docker beforehand and in fact you are better off not.

It also looks like you've not installed the required selinux packages; normally the installer does this for you so I'm confused how this could happen:
`Aug 05 13:15:38 vm1 rke2[15268]: time="2021-08-05T13:15:38Z" level=warning msg="SELinux is enabled for rke2 but process is not running in context 'container_runtime_t', rke2-selinux policy may need to be applied"`

If removing docker and installing the selinux packages does not resolve the error, see if there's anything interesting  in the containerd log at `/var/lib/rancher/rke2/agent/containerd/containerd.log`.

**Comment by jcrosel** [comment]
@brandond thats good to know. I was just expecting it, as it was a requirement for rke (binary) and rke in rancher, as far as I know. 
I now completly started from scratch, these are the steps I did:
[rke2-server.log](https://github.com/rancher/rke2/files/6943593/rke2-server.log)

systemctl disable firewalld
vim /etc/NetworkManager/conf.d/rke2-canal.conf
systemctl reload NetworkManager
dnf upgrade -y
reboot
curl -sfL https://get.rke2.io | sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service

I found another possible issue:

**Comment by brandond** [comment]
etcd still isn't starting, can you check the containerd log file as requested above?

**Comment by jcrosel** [comment]
something seems to be off for CNI.
[containerd.log](https://github.com/rancher/rke2/files/6953037/containerd.log)

@brandond have you ever experienced something similar?

**Comment by brandond** [comment]
```console
time="2021-08-06T06:36:38.554910732Z" level=info msg="CreateContainer within sandbox \"214255c37689a276a424b37dffd2b03b9f7c641b68045f2180b2413dd5275d51\" for &ContainerMetadata{Name:kube-proxy,Attempt:0,} returns container id \"84b2f6932660193fa18d0a555b43e1b4444592ff7b6898aaf9e5c86f01cc05bd\""
time="2021-08-06T06:36:38.555421235Z" level=info msg="StartContainer for \"84b2f6932660193fa18d0a555b43e1b4444592ff7b6898aaf9e5c86f01cc05bd\""
time="2021-08-06T06:36:38.722580775Z" level=info msg="StartContainer for \"84b2f6932660193fa18d0a555b43e1b4444592ff7b6898aaf9e5c86f01cc05bd\" returns successfully"
time="2021-08-06T06:36:52.714149951Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:etcd-adbsg-fzag-k8s-vm1,Uid:985840a449fab27fbd1831f57843061a,Namespace:kube-system,Attempt:0,}"
time="2021-08-06T06:36:52.792435138Z" level=info msg="starting signal loop" namespace=k8s.io path=/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/e26f8170d80ada8ab2531a87962fec1edbfd7b708c416ff914d2c5e1d6cf662e pid=6507
time="2021-08-06T06:36:52.908778362Z" level=info msg="shim disconnected" id=e26f8170d80ada8ab2531a87962fec1edbfd7b708c416ff914d2c5e1d6cf662e
time="2021-08-06T06:36:52.908851662Z" level=error msg="copy shim log" error="read /proc/self/fd/28: file already closed"
time="2021-08-06T06:36:52.943644879Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-adbsg-fzag-k8s-vm1,Uid:985840a449fab27fbd1831f57843061a,Namespace:kube-system,Attempt:0,} failed, error" error="failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown"
```

I've only seen this one other time, in https://github.com/rancher/rke2/issues/851#issuecomment-814508133 - and this user was setting a custom-data dir and also using a standalone containerd, both of which complicate things on selinux-enabled hosts. Can you start over on a clean host that doesn't have system docker or containerd installed, and ensure that you're using the RPM install with all the required selinux packages?

**Comment by jcrosel** [comment]
I did start again from a clean RHEL 8.1 VM in Azure. 
I used the script in the quick start guide to install it. That uses rpm as well, right?

**Comment by ansilh** [comment]
Do we need to mention this in the support matrix or rke2 docs? 
Looks like we need RHEL 8.5 to get SELinux working in this case.

**Comment by mayank-reynencourt** [comment]
Hi all,

i'm also facing same issue while deploying rke2 using ansible on RHEL 8.2,

does anyone get some solution for that?

**Comment by belgaied2** [comment]
I am having the same issue on RedHat 8.4 on AWS, it looks like the error is:
```bash
sudo systemctl status rke2-server
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-03-03 15:36:37 UTC; 728ms ago
     Docs: https://github.com/rancher/rke2#readme
  Process: 17941 ExecStopPost=/bin/sh -c systemd-cgls /system.slice/rke2-server.service | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill (code=exited, status=0/SUCCESS)
  Process: 17938 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=1/FAILURE)
```
It looks like what is failing is the command before the execution of rke2:
```
[ec2-user@ip-172-31-44-245 ~]$ /bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
[ec2-user@ip-172-31-44-245 ~]$ echo $?
1
```
causing the service's executable to not run ?

On the same node, just running `rke2 server` results in a successful bootstrapping.

## Steps to reproduce:
- AWS EC2 instance using the AMI `ami-06ec8443c2a35b0ba` on `eu-central-1` , this instance is based on RHEL 8.4 with kernel `4.18.0-305.el8.x86_64` .
- All settings default: selinux is enforcing, firewalld is not enabled out-of-the-box
- Then try to install RKE2:
```bash
[ec2-user@ip-172-31-44-245 ~]$ curl -sfL https://get.rke2.io | sudo sh -
[ec2-user@ip-172-31-44-245 ~]$ sudo systemctl enable rke2-server
[ec2-user@ip-172-31-44-245 ~]$ sudo systemctl start rke2-server
```

Using this user-data should result in same behavior:
```yaml
#cloud-config
runcmd:
  - curl -sfL https://get.rke2.io | sudo sh -
  - sudo systemctl enable rke2-server
  - sudo systemctl start rke2-server
```

**Comment by ansilh** [comment]
@belgaied2 Not the same issue we discussed in the original thread. 

Looks like you need to make sure the known issues are addressed as per the rke2 doc.
https://docs.rke2.io/known_issues/#networkmanager
```
In some operating systems like RHEL 8.4, NetworkManager includes two extra services 
called nm-cloud-setup.service and nm-cloud-setup.timer. 

These services add a routing table that interfere with the CNI plugin's configuration. 
Unfortunately, there is no config that can avoid that as explained in the [issue](https://github.com/rancher/rke2/issues/1053). 
Therefore, if those services exist, they should be disabled and the node must be rebooted.
```

**Comment by belgaied2** [comment]
Thanks for the clarification!
