### ISSUE TITLE
[release-1.19] Empty label pods stuck in ContainerCreating

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1552]
Backport fix for **Empty label pods stuck in ContainerCreating** to branch **release-1.19**:
* #1530

This one got built with the wrong golang version as well.

**Comment by rancher-max** [comment]
Confirmed this is working in v1.19.13-rc1+rke2r2 and go version is correctly 1.15.x

```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+rke2r2", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-08-06T00:13:45Z", GoVersion:"go1.15.14b5", Compiler:"gc", Platform:"linux/amd64"}
```
