### ISSUE TITLE
Windows installation scripts fail for self-signed certficates.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1566]
**Environmental Info:**
RKE2 Version: 1.21.3

**Describe the bug:**

The built in powershell commandlets don't handle self-signed certs very well causing an error to exit the script during installation. 

**Steps To Reproduce:**

1. Use Rancher with a self-signed cert.
2 Install RKE2 using a Rancher custom cluster registration command and the install fails due to self-signed cert.

**Expected behavior:**

Install without issue.

**Actual behavior:**

Fails on first request due to self-signed certificate.

**Additional context / logs:**

https://github.com/rancher/rancher/issues/33625#issuecomment-893600992

**Comment by slickwarren** [comment]
on 2.6.0-rc5, I am able to register a windows worker using rancher + self-signed certs
