### ISSUE TITLE
Occassional address already in use error on multi-server node clusters

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1573]
**Environmental Info:**
RKE2 Version: 

v1.20.9
(both v1.20.9+rke2r1 and v1.20.9-rc1+rke2r2)

Node(s) CPU architecture, OS, and Version: 

Centos8.2, Ubuntu 20.04 LTS

Cluster Configuration:

3 servers, 1 agent

**Describe the bug:**

Intermittently one of the server nodes has the `kube-controller-manager` and/or `kube-scheduler` pod(s) stuck in CrashLoopBackoff. Logs from each, respectively, show:
```
failed to create listener: failed to listen on 127.0.0.1:10252: listen tcp 127.0.0.1:10252: bind: address already in use

failed to create listener: failed to listen on 127.0.0.1:10251: listen tcp 127.0.0.1:10251: bind: address already in use
```

**Steps To Reproduce:**

- Installed RKE2 with multiple servers

**Expected behavior:**

All servers should be up and running with all pods in a Running state with no restarts

**Actual behavior:**

_sometimes_ one of the servers has a pod or two stuck in a CrashLoopBackoff

**Additional context / logs:**

Rebooting the problematic node resolves the issue. Only restarting the service does not seem to do the trick.

I've only seen this on v1.20 line but that could just be randomness/luck.

**Comment by brandond** [comment]
Does this happen on upgrade, or clean install? Can you tell what's causing the port conflict?

Adding `--permit-address-sharing --permit-port-sharing` would probably fix this, as the conflict is probably coming from the port previous pod after upgrade being left in TIME_WAIT.

Probably a duplicate of https://github.com/rancher/rke2/issues/1074#issuecomment-850374337 which was confirmed as fixed by `--permit-port-sharing`

**Comment by rancher-max** [comment]
> Does this happen on upgrade, or clean install? Can you tell what's causing the port conflict?

This happens on a clean install for us. I haven't been able to tell yet what's causing the conflict.

**Comment by rancher-max** [comment]
It does look like a duplicate of that issue though and likely the same root cause.

**Comment by brandond** [comment]
RCA'd in https://github.com/rancher/rke2/issues/1074#issuecomment-850670271
> the scheduler is coming up just before the apiserver, and exits instead of waiting. When the pod gets restarted, the port is still in TIME_WAIT and cannot be reused.

**Comment by rancher-max** [comment]
Closing as a duplicate of the mentioned issue. We should add those arguments as defaults.
