### ISSUE TITLE
Windows Installation command isn't installing the correct version of RKE2, it installs the latest stable channel.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1577]
**Describe the bug:**

The windows RKE2 installer for Rancher isn't receiving the version of RKE2 to install. By default it will install the latest stable channel release if no version is provided.

**Steps To Reproduce:**

Create a new RKE2 custom cluster with a 1.21.4 RC version and add Windows node.

**Expected behavior:**

Running rke2.exe --version should report 1.21.3-rc4+rke2r2

**Actual behavior:**

The version report 1.21.3-rke2r1

**Additional context / logs:**

* https://github.com/rancher/rancher/issues/34094

**Comment by brandond** [comment]
The RKE2 PR for this issue has been merged and is ready to test; if there is another issue on the rancher side that is still in peer review that issue should be moved into Peer Review instead of this one.

**Comment by sirredbeard** [comment]
Backing this out in order to perform some additional ETE testing prior to QA handoff.

**Comment by rancher-max** [comment]
This was validated as part of v1.21. Closing as already done
