### ISSUE TITLE
Cluster is stuck in upgrading state when upgrading to v1.21.3-rc4+rke2r2

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1580]
* https://github.com/rancher/rancher/issues/34067
> Create an imported RKE2 cluster on rancher v2.5.9 on kubernetes v1.20.9-rc1+rke2r2
> Upgrade the rancher server version to v2.6.0-rc1
> Then upgrade the kubernetes version of the cluster to v1.21.3+rke2r1
>
>Upgrade the kubernetes version from to v1.21.3-rc4+rke2r2 the cluster is stuck in upgrading with the header Worker node [ip-172-31-3-86.us-east-2.compute.internal] being upgraded and won't recover from that state.
>
> v1.21.3-rc4+rke2r2 translates to v1.21.3+rke2r2, the actual issue is that the RCs are still using hardened-kubernetes v1.21.3+rke2r1 so you will not see a version change when upgrading.

We need to bump to v1.21.3+rke2r2 so that the target and running versions compare equal.

**Comment by rancher-max** [comment]
This was validated in the v1.21 line. 1.22 will have its own set of upgrade tests done WITHOUT rancher as it won't be supported there, so I'm going to close this out.
