### ISSUE TITLE
registry fault tolerance does not work for pulling runtime image

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#1584]
**Environmental Info:**
RKE2 Version: 1.20.7-rke2r2

Node(s) CPU architecture, OS, and Version: 
Intel x86_64, SLES 15 SP2

Cluster Configuration:
3 master, 14 worker, bare-metal, air-gapped

**Describe the bug:**
registries.yaml has three registries for fault tolerance but if the first one is not available - the runtime image is not pulled from secondary or tertiary registry.

registries.yaml looks similar to this:

```
mirrors:
  docker.io:
    endpoint:
      - "https://registry.customer.com/v2/"
      - "https://registry2.customer.com/v2/"
      - "https://registry3.customer.local:5000/v2/"
    rewrite:
      "^(?:library|)(.*)": "rke-prod/docker.io/$1"

``` 

Error in the log:

```
Aug 10 09:24:44 cluster-node-004 rke2[5678]: time="2021-08-10T09:24:44+02:00" level=error msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.20.7-rke2r2: no local image available for index.docker.io/rancher/rke2-runtime:v1.20.7-rke2r2: directory /var/lib/rancher/rke2/agent/images does not exist: image not found"
Aug 10 09:24:44 cluster-node-004 rke2[5678]: time="2021-08-10T09:24:44+02:00" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
Aug 10 09:24:44 cluster-node-004 rke2[5678]: time="2021-08-10T09:24:44+02:00" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.20.7-rke2r2"
Aug 10 09:24:44 cluster-node-004 rke2[5678]: time="2021-08-10T09:24:44+02:00" level=warning msg="Found more than one endpoint for index.docker.io; only the first entry will be used"
Aug 10 09:25:23 cluster-node-004 rke2[5678]: time="2021-08-10T09:25:23+02:00" level=fatal msg="failed to get runtime image index.docker.io/rancher/rke2-runtime:v1.20.7-rke2r2: GET https://registry.customer.com/v2/rke-prod/docker.io/rancher/rke2-runtime/manifests/v1.20.7-rke2r2: unexpected status code 502 Bad Gateway"
Aug 10 09:25:23 cluster-node-004 systemd[1]: rke2-agent.service: Main process exited, code=exited, status=1/FAILURE

```

**Steps To Reproduce:**
Configure multiple registry endpoints and stop the first registry in the list.

**Expected behavior:**
Secondary / Tertiary registry should be used to pull runtime image.

**Actual behavior:**
Secondary / Tertiary registry is not used if first one fails.

**Comment by brandond** [comment]
This is a known limitation; hence the warning. The library we're using doesn't currently support multiple endpoints.

**Comment by brandond** [comment]
Note that containerd will only fall back to other endpoints in case of a 404; this is fixed in 1.5 and newer but we do not ship 1.5 yet.
https://github.com/containerd/containerd/pull/5747/files

**Comment by Martin-Weiss** [comment]
> 
> 
> This is a known limitation; hence the warning. The library we're using doesn't currently support multiple endpoints.

Thanks for the quick feedback - any idea when this might be fixed and where to find a list of "known limitations"?

**Comment by brandond** [comment]
Not really; we could use some better documentation around registries.yaml, in particular the containerd patches we've added to support repo rewrite expressions.

Better handling for multiple endpoints is also being tracked internally as [SURE-2987](https://jira.suse.com/browse/SURE-2987).

**Comment by brandond** [comment]
It looks like that containerd patch to retry non-404s applies cleanly to our fork of 1.4. I might try including it in our next release. Fixing go-containerregistry to support multiple endpoints will require a fair bit more work, which is why we didn't do it as part of our initial implementation.

**Comment by Martin-Weiss** [comment]
> It looks like that containerd patch to retry non-404s applies cleanly to our fork of 1.4. I might try including it in our next release. Fixing go-containerregistry to support multiple endpoints will require a fair bit more work, which is why we didn't do it as part of our initial implementation.

One step after the other ;-) - but yes - would be great to get this in!

**Comment by Martin-Weiss** [comment]
Just heard that this should be fixed in RKE2 1.22.5 and 1.21.8 based on SURE-3227 and https://github.com/rancher/rke2/issues/2159 - is this true?

**Comment by brandond** [comment]
Correct, was fixed a while ago. I believe that issue was opened first, but I'm not sure why this one wasn't marked a duplicate of it.

**Comment by Martin-Weiss** [comment]
Closing based on last comment. Thanks for fixing!
