### ISSUE TITLE
[release-1.21] RKE2 Cluster running Calico seemingly losing UDP traffic when transiting through service IP to remotely located pod

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1586]
Same as this issue: https://github.com/rancher/rke2/issues/1541

**Comment by dereknola** [comment]
**Validated using v1.21.3-rc6+rke2r2**
Setup Rke2 server and agent using Calico as CNI
`dig @10.43.0.10 www.google.com` 
Succeeds with no issues on both server and agent nodes.
