### ISSUE TITLE
Pod Security Policy

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#159]
- RKE2 should have PSPs off by default. Policies should be set up for all our components (not global e.g. not touching Users, etc).

- If the user sets --profile=cis-1.5 we will use a different default in order to pass CIS tests / benchmark. (Instead of a psp with NO restrictions, deploy one that is restrictive and will pass CIS). If CIS mode enabled, turn on admission controller.

- The default PSP can be changed post-install and no further action will be taken by RKE2. Such as with a flag could disable and specify their own PSP.

The default should be replaceable and removable. Also, if a user would like to have the default re-deployed that should be doable as well. Reference / compare to: https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html

**Comment by briandowns** [comment]
This work has been performed in PR #199. 

Logic for loading the PSP's:

CIS:
- If the globalRestricted annotation does not exist, create PSP, role, binding.
- If the systemUnrestricted annotation does not exist, create the PSP, role, binding.
- If the globalUnrestricted annotation does not exist, check if PSP exists, and if so,
   delete it, the role, and the bindings.

non-CIS:
- If the globalUnrestricted annotation does not exist, then create PSP, role, binding.
- If the systemUnrestricted annotation does not exist, then create PSP, role, binding.
- If the globalRestricted annotation does not exist, then check if the PSP exists and
   if it doesn't, create it. Check if the associated role and bindings exist and
   if they do, delete them.

Testing this can be done by running `kubectl get psps`, `kubectl get roles`, `kubectl get clusterroles`, and `kubectl get clusterrolebindings` in conjunction with grep to identify what should and should exist depending on the operating mode.

**Comment by rancher-max** [comment]
#### Validated on beta11

- With non-CIS mode, everything looks correct to me. There are no `roles` resource types, but there are psps, clusterroles, and clusterrolebindings. Additionally, the clusterroles and clusterrolebindings are correctly pointing to the unrestricted psp. I believe this is the expected behavior. See below:
```
$ k get psp,roles,rolebindings,clusterroles,clusterrolebindings -o wide | grep psp

podsecuritypolicy.policy/global-restricted-psp     false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
podsecuritypolicy.policy/global-unrestricted-psp   true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
podsecuritypolicy.policy/system-unrestricted-psp   true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *

clusterrole.rbac.authorization.k8s.io/global-unrestricted-psp-clusterrole                                    2020-08-31T16:01:08Z
clusterrole.rbac.authorization.k8s.io/system-unrestricted-psp-role                                           2020-08-31T16:01:08Z

clusterrolebinding.rbac.authorization.k8s.io/global-unrestricted-psp-rolebinding                    ClusterRole/global-unrestricted-psp-clusterrole                    46m                                    system:authenticated                           
clusterrolebinding.rbac.authorization.k8s.io/system-node-default-psp-rolebinding                    ClusterRole/global-unrestricted-psp                                46m                                    system:nodes                                   
clusterrolebinding.rbac.authorization.k8s.io/system-unrestricted-node-psp-rolebinding               ClusterRole/system-unrestricted-psp-role                           46m                                    system:nodes                                   
```

**Minor Issue:**
- With CIS mode enabled, it appears to have the system-node-default clusterrolebinding pointing to the `global-unrestricted-psp` clusterrole, which doesn't exist. (I believe the correct behavior would either be for this rolebinding to point to a `global-restricted-psp` clusterrole OR to be deleted entirely?) See below:
```
$ k get psp,roles,rolebindings,clusterroles,clusterrolebindings -o wide | grep psp

podsecuritypolicy.policy/global-restricted-psp     false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
podsecuritypolicy.policy/global-unrestricted-psp   true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
podsecuritypolicy.policy/system-unrestricted-psp   true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *

clusterrole.rbac.authorization.k8s.io/global-unrestricted-psp-clusterrole                                    2020-08-31T16:01:08Z
clusterrole.rbac.authorization.k8s.io/system-unrestricted-psp-role                                           2020-08-31T16:01:08Z

clusterrolebinding.rbac.authorization.k8s.io/global-unrestricted-psp-rolebinding                    ClusterRole/global-unrestricted-psp-clusterrole                    46m                                    system:authenticated                           
clusterrolebinding.rbac.authorization.k8s.io/system-node-default-psp-rolebinding                    ClusterRole/global-unrestricted-psp                                46m                                    system:nodes                                   
clusterrolebinding.rbac.authorization.k8s.io/system-unrestricted-node-psp-rolebinding               ClusterRole/system-unrestricted-psp-role                           46m                                    system:nodes                                   

```

**Comment by rancher-max** [comment]
Mentioned issue is small enough that it should not block release in any way, so closing this in favor of https://github.com/rancher/rke2/issues/278
