### ISSUE TITLE
[release 1.21] bump calico to 3.19.2

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1593]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
On v1.21.3-rc5+rke2r2 in the windows node logs I see: `2021-08-13 00:20:50.063 [INFO][1096] startup/startup.go 103: Starting node ip-ac1f1938 with version v3.19.2` so this looks like it is using the correct version.
