### ISSUE TITLE
Calico encryption feature should be configurable during cluster provisioning

### ISSUE THREAD

**Issue by janeczku** [rancher/rke2#1608]
It should be possible for a user to easily enable the Wireguard encryption feature available in Calico during cluster provisioning using a HelmChartConfig.

https://docs.projectcalico.org/security/encrypt-cluster-pod-traffic

**Comment by brandond** [comment]
HelmChartConfig resources can be used set anything that can be changed via chart values. If this cannot be changed via chart values, that will need to be fixed upstream, not here.

**Comment by janeczku** [comment]
AFAIK, RKE2 ships a modified (patched) version of the upstream Calico helm chart. 
That patched version of the Helm chart may enable features that the upstream version does not.

**Comment by caroline-suse-rancher** [comment]
Closing this as complete per the merged PR
