### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by manelclos** [rancher/rke2#1609]
**Is your feature request related to a problem? Please describe.**
It would be great to have Alpine support in rke2, install script currently fails with:
```
sh: systemctl: not found
```

**Describe the solution you'd like**
Quick and easy install on Alpine, like K3s.

**Additional context**
Tried with Alpine 3.14.0.

**Comment by brandond** [comment]
RKE2 currently only supports systemd-based distributions. You could try installing systemd on alpine first, but that's not been tested.
