### ISSUE TITLE
--kube-proxy-arg option isn't being parsed correctly in conntrack

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1610]
**Environmental Info:**
RKE2 Version: 1.21.3-rk2r1

**Describe the bug:**
When passing the --kube-proxy-arg option to the agent I get the following error.

```
PS C:\> rke2.exe agent --kube-proxy-arg feature-gates=IPV6DualStack=false
time="2021-08-11T08:57:22-07:00" level=info msg="Starting rke2 agent v1.21.3-rc5+rke2r2 (fca5af9e52c5b0969c520a1a6320b3a5c93f8909)"
time="2021-08-11T08:57:22-07:00" level=info msg="Running load balancer 127.0.0.1:6444 -> [172.20.171.2:9345]"
time="2021-08-11T08:57:22-07:00" level=info msg="Running load balancer 127.0.0.1:6443 -> [172.20.171.2:6443]"
time="2021-08-11T08:57:22-07:00" level=fatal msg="failed to validate kube-proxy conntrack configuration: unknown flag: --featuregates"
```

**Steps To Reproduce:**

Create a cluster and try to pass custom kube proxy args.

**Expected behavior:**

Kube-proxy starts with the desired extra feature gates.

**Actual behavior:**

Errors

**Additional context / logs:**

**Comment by phillipsj** [comment]
Running it with qoutes resolved it. 
```
rke2.exe agent --kube-proxy-arg "feature-gates=IPV6DualStack=false"
```

**Comment by brandond** [comment]
Just out of curiosity, does it work as `rke2.exe agent --kube-proxy-arg feature-gates=IPV6DualStack=false` ?
