### ISSUE TITLE
Unable to provision nodes for custom Windows rke2 clusters

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1616]
Tracking issue to fix Rancher issue caused by Windows install scripts:
* rancher/rancher#34173

RKE2 install scripts are pulled from rke2 master into Rancher image at build time, so fix does not need to be backported.

**Comment by rancher-max** [comment]
This is blocked on the rancher side and is specifically related to rancher so is not any standalone validation I can do at this time.

**Comment by rancher-max** [comment]
This has now been validated from the rancher side and is working correctly.
