### ISSUE TITLE
Update embedded containerd to 1.4.9-k3s1

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1639]
* https://github.com/containerd/containerd/releases/tag/v1.4.9
* https://jira.suse.com/browse/SURE-2987
* https://github.com/containerd/containerd/pull/5747

**Comment by rancher-max** [comment]
Confirmed using `containerd://1.4.9-k3s1` on master branch commit `472bd977569e4e2d5b04eb826816aca9c3af8ecb`

During patch testing with an rc, I will validate that conformance and regression checks continue to pass.
