### ISSUE TITLE
Bump helm-controller to v0.10.5

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1643]
Haven't seen tiller crashes as much in RKE2, but this should address the same root issue:
* https://github.com/k3s-io/k3s/issues/3843

**Comment by dereknola** [comment]
Validated on master commit `09bb5c27f29cf3dd831653543d274c948a225385`
Deployed custom helmchartconfig and verified that helm controller bumped to `v0.10.6`
Klipper-helm version also verified as bumped to `rancher/klipper-helm:v0.6.4-build20210813`
