### ISSUE TITLE
Cannot install windows in airgap using tarball

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1647]
**Environmental Info:**
RKE2 Version: 

v1.21.3-rc5+rke2r2

Node(s) CPU architecture, OS, and Version: 

```
WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 7/24/2021 6:08:30 AM
WindowsProductId                                        : 00430-00000-00000-AA230
WindowsProductName                                      : Windows Server 2019 Datacenter
WindowsRegisteredOrganization                           : Amazon.com
WindowsRegisteredOwner                                  : EC2
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 1809
```

Cluster Configuration:

1 airgapped server node (using calico and strictaffinity), trying to add 1 windows agent but fails

**Describe the bug:**

Windows fails to install in an airgap environment when using the tarball. Error shown is:
```
time="2021-08-13T19:09:15Z" level=info msg="Checking local image archives in C:\\var\\lib\\rancher\\rke2\\agent\\images for index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2"
time="2021-08-13T19:09:16Z" level=info msg="Failed to find index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2 in C:\\var\\lib\\rancher\\rke2\\agent\\images\\rke2-windows-1809-amd64-images.tar.gz: tag rancher/rke2-runtime:v1.21.3-rc5-rke2r2 not found in tarball"
time="2021-08-13T19:09:16Z" level=error msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2: no local image available for index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2: not found in any file in C:\\var\\lib\\rancher\\rke2\\agent\\images: image not found"
time="2021-08-13T19:09:16Z" level=info msg="Checking local image archives in C:\\var\\lib\\rancher\\rke2\\agent\\images for index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2"
time="2021-08-13T19:09:18Z" level=info msg="Failed to find index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2 in C:\\var\\lib\\rancher\\rke2\\agent\\images\\rke2-windows-1809-amd64-images.tar.gz: tag rancher/rke2-runtime:v1.21.3-rc5-rke2r2 not found in tarball"
time="2021-08-13T19:09:18Z" level=error msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2: no local image available for index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r2: not found in any file in C:\\var\\lib\\rancher\\rke2\\agent\\images: image not found"
time="2021-08-13T19:09:18Z" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.21.3-rc5-rke2r
```

**Steps To Reproduce:**

- Install airgapped server node with calico as cni
- Setup the `rke2-windows-1809-amd64-images.tar.gz` tarball into `C:\var\lib\rancher\rke2\agent\images\` on windows airgapped node
- Setup config.yaml file with correct server and token
- Run `rke2 agent`

**Expected behavior:**

rke2 should install correctly

**Actual behavior:**

the runtime image cannot be found in the tarball

**Additional context / logs:**

It appeared that the contents of `sha256:d90ff39188e0bdf541792195be9ad90001f2c0237ba0adffcf84d757bdb49838` inside the tar has `"os":"linux"` but changing this to `"os":"windows"` and re-tarring and using that file instead does not solve the issue, resulting in the same error (although maybe this had something to do with my node already being "dirty"?).

**Comment by brandond** [comment]
I believe @luthermonson stated that airgap for windows was not going to be supported for a while yet. There are multiple issues with image platforms and tags not being correct.

**Comment by rancher-max** [comment]
Moving this to test as it seems like the "epic" to:
- https://github.com/rancher/rke2/issues/2671
- https://github.com/rancher/rke2/issues/2672
- https://github.com/rancher/rke2/issues/2673

**Comment by rancher-max** [comment]
### Validated in v1.21.11-rc6+rke2r1, v1.22.8-rc6+rke2r1, and v1.23.5-rc5+rke2r1

- Windows is able to be installed in an airgap environment now using tarball
- Confirmed that using the tar.gz or tar.zst are both successful with this approach
- Confirmed that airgap install is successful on both Windows 2022 and Windows 2019 servers.
- My steps were:
```
1. Start an airgapped server node running calico using tarball method
2. Join an airgapped linux agent node
3. Setup windows node to use the tarball:
  a. Copy the tarball file (either the .gz or .zst that corresponds to the windows server version) into `c:\var\lib\rancher\rke2\agent\images`
  b. Setup `c:\etc\rancher\rke2\config.yaml` to have the server and token information to join.
4. Run `rke2.exe agent`
```
