### ISSUE TITLE
rancher-logging: fluentbit containerd error

### ISSUE THREAD

**Issue by kphunter** [rancher/rke2#1649]
**Environmental Info:**
RKE2 Version: rke2 version v1.20.7+rke2r2 (ea6514775f816b0b4972f832de7d98eba8dff55c)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 
`Linux {name} 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
selinux: enforcing

Cluster Configuration:
3 servers, 2 agents
Centos 7.9.2009 w/ packages:
rke2-selinux: 0.7-1.el7
containerd: 1.2.14-1

**Describe the bug:**
Fluentbit pods (rancher-logging-fluentbit, rancher-logging-rke2-containers-fluentbit, and rancher-logging-rke2-journald-aggregator) fail when deploying Rancher Logging chart with {global:selinux:true} set:
```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown
```
<img width="1259" alt="Screen Shot 2021-08-14 at 6 57 59 AM" src="https://user-images.githubusercontent.com/5122386/129449590-993500c8-8f32-48f2-bd77-2918a01cefeb.png">

**Steps To Reproduce:**
- Installed RKE2 via [Rancherfederal ansible playbook](https://github.com/rancherfederal/rke2-ansible), vanilla defaults
- Deployed Rancher Logging chart via Cluster Explorer with `global:selinux:true`

**Expected behavior:**
Banzai Logging Operator chart deploy successfully

**Actual behavior:**
Fluentd statefulsets appear to deploy without errors, but fluentbit daemonsets fail with error. Rancher logging deployment is successful so flows and outputs can be configured, but any anticipated messages are never processed.

**Additional context / logs:**
This also appears to be an issue on a single cluster test node running v1.21.3+rke2r1.

**Comment by frjaraur** [comment]
In my case, fluentd does not work either due to "Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root (pod: "rancher-logging-fluentd-0_cattle-logging-system", container: fluentd)" errors.

Were you able to manage these errors?.

**Comment by kphunter** [comment]
I wasn't able to get it to work so I'm looking at elastic stack instead.
