### ISSUE TITLE
[backport 1.21] Cleanup how Calico processes are executed and terminated on Windows

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#1654]
The Windows agent calico processes where continuously restarting when it wasn't required. 

**Describe the solution you'd like**
Change how the process are starting and pass in a context that ensures process are cleaned up when kubelet is stopped.

**Comment by rancher-max** [comment]
#### Validated on v1.21.4-rc1+rke2r3

- Confirmed the calico process is no longer continuously restarting by checking the logs and no longer seeing the constant messages
- Confirmed that stopping the rke2 binary process does stop kubelet, kube-proxy, and containerd as well. This does not work for the rke2 service process, and there is another issue being opened to address that.
