### ISSUE TITLE
[master] Restoration fails on etcd only nodes due to invalid state of loadbalancers

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#1656]
**Environmental Info:**
RKE2 Version: v1.21.x

Cluster Configuration:
- 1 etcd only node server
- 1 controlplane node servers

**Describe the bug:**
upon restoring on an existing etcd only node, it tries to setup internal load balancer with existing configuration, and tries to connect to old supervisor servers, which may or may not exist and fails to restore wiht the following error:
```
msg=\"Waiting to retrieve agent configuration; server is not ready: Get \\\"https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt\\\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\""
``

**Comment by rancher-max** [comment]
Validated on master branch commitid `09bb5c27f29cf3dd831653543d274c948a225385` restoration is successful and loadbalancers are setup appropriately back to default of the node that is being reset.
