### ISSUE TITLE
Packaged components should not schedule on to Windows nodes

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1664]
In order to prevent packaged components from attempting to run on Windows worker nodes, all of the RKE2 helm charts need to be updated to include the following in the Pod spec:
```yaml
  nodeSelector:
    kubernetes.io/os: linux
```

**Comment by rancher-max** [comment]
Validated using master commit `09bb5c27f29cf3dd831653543d274c948a225385` - all resources deployed via a helm install have the appropriate linux node-selector. Note this does not apply to static pods such as cloud-controller, etcd, kube-proxy, etc.
