### ISSUE TITLE
Fix URL pruning when joining an etcd member

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1666]
Pull through **Fix URL pruning when joining an etcd member** from k3s to branch **master**:
* k3s-io/k3s#3832

**Comment by rancher-max** [comment]
Validated using master branch commit `09bb5c27f29cf3dd831653543d274c948a225385` with the same steps as mentioned in https://github.com/rancher/rke2/issues/1667#issuecomment-902928482
