### ISSUE TITLE
[release-1.21] CoreDNS Autoscaler

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1675]
Backport **CoreDNS Autoscaler** to branch **release-1.21**:
* #1023

**Comment by rancher-max** [comment]
#### Validated using release-1.21 branch commitid `f25c838c4cfb983192a168bcdc30422ef9749b59`

- coredns-autoscaler pod deployed by default
- no errors in logs
- updating the configmap to scale on every node, resetting the autoscale pod to use the updates, and joining a node correctly scales the coredns replicas

Will need to check this and NodeLocal DNS deploy correctly on hardened systems using cis profiles and selinux enforcing systems before closing.

**Comment by rancher-max** [comment]
Validated both this and node-local-dns deploy correctly on centos8 with cis profile 1.6 using v1.21.3-rc7+rke2r2
