### ISSUE TITLE
[Release-1.21] Add Harvester CMM and CSI integration

### ISSUE THREAD

**Issue by yaocw2020** [rancher/rke2#1680]
**Is your feature request related to a problem? Please describe.**
Both Harvester CCM & Guest CSI driver should install and configure by default when the user spins up a k8s cluster with the Harvester RKE2 node driver, therefore we will need to add the built-in Harvester cloud provider integration.

**Describe the solution you'd like**
- Add harvester-cloud-provider and harvester csi charts https://github.com/rancher/rke2-charts/pull/140
- Add harvester cloud provider kontainer driver metadata PR: https://github.com/rancher/kontainer-driver-metadata/pull/652
- Add harvester cloud provider and rke2 integration PR: https://github.com/rancher/rke2/pull/1679

https://github.com/rancher/rancher/issues/34438

**Comment by cjellick** [comment]
You need two issues: one for master and one for backporting. And you need a or to backport to the 1.21 branch

**Comment by dereknola** [comment]
Validated on `v1.21.5-rc2+rke2r1` release:
Running `rke2 server --cloud-provider-name harvester` produces the following:
```
root@node-cluster-init-buster64:/home/vagrant# kubectl get pods -A
NAMESPACE     NAME                                                    READY   STATUS              RESTARTS   AGE
kube-system   cloud-controller-manager-node-cluster-init-buster64     1/1     Running             1          3m12s
kube-system   etcd-node-cluster-init-buster64                         1/1     Running             1          61s
kube-system   harvester-cloud-provider-5bc9dcbb77-q45rb               0/1     ContainerCreating   0          38s
kube-system   harvester-cloud-provider-5bc9dcbb77-s5ckq               0/1     ContainerCreating   0          38s
kube-system   harvester-csi-driver-controllers-fcd95788c-89xrr        0/3     ContainerCreating   0          36s
kube-system   harvester-csi-driver-controllers-fcd95788c-p4xm9        0/3     ContainerCreating   0          36s
kube-system   harvester-csi-driver-controllers-fcd95788c-q6sk8        0/3     ContainerCreating   0          36s
kube-system   harvester-csi-driver-w294q                              0/2     ContainerCreating   0          36s
kube-system   helm-install-harvester-cloud-provider-vflqn             0/1     Completed           0          39s
kube-system   helm-install-harvester-csi-driver-njvq8                 0/1     Completed           0          39s
```
