### ISSUE TITLE
Make it clear that containerd's config.toml gets clobbered on startup

### ISSUE THREAD

**Issue by jroeber** [rancher/rke2#1681]
**Environmental Info:**
RKE2 Version: v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)

**Describe the bug:**
The containerd config at `/var/lib/rancher/rke2/agent/etc/containerd/config.toml` gets generated by RKE2 when the service starts. The file should have a comment in it to make it clear that manual changes will be lost on startup and that the [config.toml.tmpl](https://docs.rke2.io/advanced/#configuring-containerd) method should be used if a custom config is needed.

**Comment by dereknola** [comment]
This was pulled in to RKE2 as of https://github.com/rancher/rke2/commit/4c99712ba4c0e9c2bd029d237a577eb154759df5
