### ISSUE TITLE
RKE1 -> RKE2 Config Migration Tool

### ISSUE THREAD

**Issue by asummers** [rancher/rke2#1699]
**Is your feature request related to a problem? Please describe.**
A lot of the values in RKE1 configs have direct analogs in the RKE2 configs, and I'm spending a good amount of time transcribing to the new config format.

**Describe the solution you'd like**
Provide a tool to move over the ones that can mechanically take in an RKE1 config, translate what it can, and spit out anything it cannot as output. This would allow folks to much more easily try out RKE2 who have existing clusters, and give you much more direct feedback of issues from existing workloads.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by galal-hussein** [comment]
@asummers Thanks for opening the issue, but there is already an issue opened for this feature:

- https://github.com/rancher/rke2/issues/562

There is work that already has been done for this feature, you can find the code there:

https://github.com/rancher/migration-agent

**Comment by aslafy-z** [comment]
Nostale
