### ISSUE TITLE
Support kubelet configuration options via rke2 server arguments

### ISSUE THREAD

**Issue by dustinvanbuskirk** [rancher/rke2#1701]
Multiple components of Kubernetes support additional options through the CLI but kubelet did not make that list.

Prior in RKE you could edit the config.yaml of the cluster directly through the UI and could add extra volume mounts via that editing window.

https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-binds

This may be supported but I could not locate the documentation anywhere.

Can the rke2 server arguments support volume mounts for kubelet?

If not can a new argument be added to CLI to support?

**Comment by asummers** [comment]
https://docs.rke2.io/install/install_options/server_config/

```
--kube-apiserver-extra-mount
``` 

and friends (find for `-extra-mount`) are the analogs here, I think. Working through this problem myself currently.

**Comment by JannikZed** [comment]
I'm currently struggling with this as well! We have rancher 2.6 running and deployed a cluster with RKE2 - I'm not successful trying to set the --cloud-provider=external flag to the kubelet.

**Comment by brandond** [comment]
The --cloud-provider flag is already set to external by default, as RKE2 ships with an embedded external cloud provider by default.

**Comment by chrisludwig** [comment]
In my case it is the HCloud Cloud Controller Manager [HCloud Cloud Controller Manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager), which I would like to use with RKE2. Hence the need to set the `--cloud-provider=external` flag.

@brandond What are the possible downsides of replacing the embedded external cloud provider? At least I can see there is a RKE2 server configuration option (`--disable-cloud-controller`) to disable it.

**Comment by brandond** [comment]
If you disable the built-in cloud provider you must replace it with a different one, or any nodes added to the cluster will not have the externalIP/hostname addresses set properly, and will not have the `uninitialized` taint cleared.
