### ISSUE TITLE
TLS handshake error: certificate not yet valid

### ISSUE THREAD

**Issue by TFBW** [rancher/rke2#1702]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.3+rke2r2 (a81afac47bdf3f8548e5f0a90594672ebebdb9d9)
go version go1.16.6b7

Problem was also reproduced under RKE2 v1.20.9+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux hostname.redacted 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Mar 25 21:21:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Target 3 servers, but problem happens bootstrapping first server.

**Describe the bug:**
RKE2 start-up stalls due to a not-yet-valid TLS certificate on the RKE2 server port. Journal output shows repeated attempts to connect which fail due to an invalid TLS certificate (generated by RKE2), as in "certificate has expired or is not yet valid: current time 2021-08-24T12:23:20+10:00 is before 2021-08-24T10:21:49Z"

**Steps To Reproduce:**
- Install RKE2 RPMs.
- Write basic /etc/rancher/rke2/config.yaml file with two entries under "tls-san" (host name and cluster round-robin name).
- Enable rke2-server service.
- Reboot.

Note that the timezone of the server may be a significant factor. That is +1000 in my case.

**Expected behavior:**
RKE2 starts up and becomes ready.

**Actual behavior:**
RKE2 stalls until certificate becomes valid (takes about 8 hours in my case).

**Additional context / logs:**
```
time="2021-08-24T12:23:15+10:00" level=info msg="Connecting to proxy" url="wss://127.0.0.1:9345/v1-rke2/connect"
time="2021-08-24T12:23:15+10:00" level=error msg="Failed to connect to proxy" error="x509: certificate has expired or is not yet valid: current time 2021-08-24T12:23:15+10:00 is before 2021-08-24T10:21:49Z"
time="2021-08-24T12:23:15+10:00" level=error msg="Remotedialer proxy error" error="x509: certificate has expired or is not yet valid: current time 2021-08-24T12:23:15+10:00 is before 2021-08-24T10:21:49Z"
time="2021-08-24T12:23:15+10:00" level=info msg="Cluster-Http-Server 2021/08/24 12:23:15 http: TLS handshake error from 127.0.0.1:45656: remote error: tls: bad certificate"
time="2021-08-24T12:23:20+10:00" level=warning msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true\": dial tcp 127.0.0.1:6443: connect: connection refused"
```

Note that my host is in the +1000 timezone. It looks like the certificate is back-dated two hours from the time it is created, but there is a mismatch of timezones in the process (going from +1000 to UTC). If this guess as to the root cause of the bug is correct, the problem will only manifest in timezones greater than +0200.

Is there a way to manage certificates outside of RKE2? The documentation hints at it in places, but I can find no explicit instructions on how to do so.

**Comment by brandond** [comment]
Certificate expiration should be timezone aware; the code for this is all core golang code and not rke2 specific. Are you sure time is in sync across all of your nodes when you're bringing up rke2? Do you maybe need to wait for time sync to complete before starting rke2?

**Comment by TFBW** [comment]
The machines are VMs, and so get their clock from the host environment. It's unlikely that there is any clock drift. There may be some kind of clock update associated with setting the timezone during the boot process. I don't know where that occurs: it's all under the control of the RHEL7 systemd configuration, including whatever it is that the RKE2 RPMs do to insert themselves into that chain.

**Comment by brandond** [comment]
Is it possible that the clock is incorrectly set on the first boot? The issue is that the cert is being created when the system clock is set earlier than it is set after the reboot, so after the reboot, the cert is (as the error says) not yet valid:
`current time 2021-08-24T12:23:15+10:00 is before 2021-08-24T10:21:49Z"`

`2021-08-24T12:23:15+10:00` is `2021-08-24T02:23:15Z` which is clearly before `2021-08-24T10:21:49Z`

**Comment by mmikitka** [comment]
I am able to reproduce the `x509: certificate has expired or is not yet valid` error when either the `--profile=cis1.5` or `--profile=cis1.6` configuration flags are used. If the `--profile` flag is omitted, I do not see the error.

Here is a sample error message, emitted shortly after attempting to start rke2-server for the first time:
```
x509: certificate has expired or is not yet valid: current time 2022-02-27T03:36:46+02:00 is before 2022-02-27T03:32:19Z
```

A couple of things to note

1. Different timezones - +02:00 and +00:00 (UTC)
2. The certificate has a `notBefore` of ~2 hours in the future
3. Given 2, and the report from @TFBW , it looks like a localtime timestamp is interpreted as UTC.

Here is a summary of my testing.

The following scenarios **PASSED**

```
## curl -sfL https://get.rke2.io | sh -
Default config.yaml

$ /usr/bin/rke2 --version
rke2 version v1.22.7+rke2r1 (2bc7ff9bbd4109f7df3ae25a22b241d27b0370a9)
go version go1.16.10b7

## tarball - v1.22.7+rke2r1
Default config.yaml

$ rke2 --version
rke2 version v1.22.7+rke2r1 (2bc7ff9bbd4109f7df3ae25a22b241d27b0370a9)
go version go1.16.10b7

## tarball - v1.22.7+rke2r1
--cni=calico
```

The following scenarios **FAILED**

```
## tarball - v1.23.3+rke2r1
--cni=calico --profile=cis-1.6

$ bin/rke2 --version
rke2 version v1.23.3+rke2r1 (a885ca5e27263bb376f158f0234de1cb6be99d49)
go version go1.17.5b7

## tarball - v1.22.7+rke2r1
--cni=calico --profile=cis-1.6

$ rke2 --version
rke2 version v1.22.7+rke2r1 (2bc7ff9bbd4109f7df3ae25a22b241d27b0370a9)
go version go1.16.10b7

## tarball - v1.22.7+rke2r1
--profile=cis-1.5

$ rke2 --version
rke2 version v1.22.7+rke2r1 (2bc7ff9bbd4109f7df3ae25a22b241d27b0370a9)
go version go1.16.10b7

## tarball - v1.22.7+rke2r1
--profile=cis-1.5

$ rke2 --version
rke2 version v1.22.7+rke2r1 (2bc7ff9bbd4109f7df3ae25a22b241d27b0370a9)
go version go1.16.10b7
```

**Comment by brandond** [comment]
We're not doing our own cert timestamp checks, this is just core golang crypto libs. The statement is correct - 3:36+2:00 is before 3:36Z (UTC). What is the system TZ set to?

**Comment by mmikitka** [comment]
I got to root cause - the problem is on my side. The hardware clock was 2 hours in the future, and the first `ntpd` sync after reboot was usually happening *after* starting rke2-server for the first time.

For those diagnosing a similar problem, here is a trace of the configuration:

The hardware clock is 2 hours in the future
```
$ hwclock --show
Sat 05 Mar 2022 05:55:52 PM EET  -0.774025 seconds

$ date
Sat Mar  5 15:55:56 EET 2022
```

Sync the system time to the hardware clock:
```
$ hwclock --localtime --systohc

$ hwclock --show
Sat 05 Mar 2022 03:57:08 PM EET  -0.089755 seconds
```

Now the hardware clock is in sync.
