### ISSUE TITLE
[release-1.21] Switch upstream k3s branch from master to engine-1.21

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1710]
As per the note in [developer-docs/k3s.md](https://github.com/rancher/rke2/blob/master/developer-docs/k3s.md) we need to move the release-1.21 off of the K3s master branch. The time to do this is now, as k3s/master is now using Kubernetes 1.22 and we do not want to pull this in to stable branches of RKE2.

**Comment by dereknola** [comment]
Validated on `v1.21.5-rc2+rke2r1` source code that `go.mod` has been updated
```
...
github.com/rancher/k3s v1.21.5-engine0.0.20210921194018-2914de5297f0 
```
