### ISSUE TITLE
Support dual-stack in cni: calico

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1717]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to deploy calico using dual-stack automatically

**Describe the solution you'd like**

When configuring the initial cluster-cidr and service-cidr with ipv4 and ipv6 addresses, I'd like calico to reflect that and deploy a dual-stack networking infra 

**Describe alternatives you've considered**

It is possible to do this by manually modifying Calico's values.yaml but it is not ideal

**Additional context**

**Comment by manuelbuil** [comment]
In order to test this:
1 - Deploy rke2 with:
```
cni: calico
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:42:1::/112
```
2 - After the deployment is successful, verify that calico created two ippools. One with the ipv4 ip range and one with the ipv6 ip range

3 - Create a pod and verify that its interface has two ips, one from the ipv4 cidr and one from the ipv6 cidr

4 - Ping between pods on their ipv6 addresses

**Comment by rancher-max** [comment]
Validated this is working on master branch commit `09bb5c27f29cf3dd831653543d274c948a225385` following the steps mentioned.
Those steps are the "happy path" scenario, and we have had an internal discussion saying this is okay for this set of September releases and we will do a larger validation as part of the next release cycle, so for that reason I'm just going to bump this milestone out and leave the issue around.
