### ISSUE TITLE
Need a way to promote an agent node to server node 

### ISSUE THREAD

**Issue by cwayne18** [rancher/rke2#1721]
In harvester, we promote agent nodes to server nodes when the amount of total nodes are >= 3.
Currently, we are using the procedure to promote an agent node :

```
# on agent nodes
$ cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
cni: multus,canal
disable: rke2-ingress-nginx
cluster-cidr: 10.52.0.0/16
service-cidr: 10.53.0.0/16
cluster-dns: 10.53.0.10
EOF

systemctl disable --now rke2-agent
systemctl enable --now rke2-server
```

I'm not sure if the workaround is upgrade-proof yet. It would be great that Rancherd or Rancher can provide a way to promote an agent node.

Tracking https://github.com/rancher/rancherd/issues/5

**Comment by cjellick** [comment]
@cwayne18 @dereknola this needs to land in 1.21.5+rke2r1. So, we need a backport issue for that milestone

**Comment by rancher-max** [comment]
This code is present and validated as working for v1.21.5. The change was made to rancher/system-agent-installer which is used by rancher, and 1.22 will not yet be supported by rancher, so I'm going to close this one out.
