### ISSUE TITLE
Not Compatible with latest RHEL8

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [rancher/rke2#1722]
**Environmental Info:**
RKE2 Version: v1.19.7+rke2r1
Node(s) CPU architecture, OS, and Version: RHEL8 t3a.medium AWS instance (x86_64)
Cluster Configuration: 1 server node, 1 agent node (also tried 3 server nodes, still didn't work)

CoreDNS, Metrics Server, and NGINX Backend containers are stuck in a crash loop on RHEL8 deployments of RKE2. It appears that they are unable to access the kubernetes service IP. Logs show errors like this:

`Error: Kubernetes cluster unreachable: Get "https://10.43.0.1:443/version?timeout=32s": dial tcp 10.43.0.1:443: i/o timeout`

This was tested on RHEL8 v8.4 using the latest AWS AMI arn:aws-us-gov:ec2:us-gov-west-1::image/ami-0ac4e06a69870e5be (RHEL-8.4.0_HVM-20210504-x86_64-2-Hourly2-GP2) and [this terraform module](https://github.com/rancherfederal/rke2-aws-tf).

I have already documented this issue in that repo but I'm reposting here for better visibility: https://github.com/rancherfederal/rke2-aws-tf/issues/47

**Steps To Reproduce:**

1. Download the [rke2-aws-tf repo](https://github.com/rancherfederal/rke2-aws-tf)
2. `cd` into the quickstart or cloud-enabled folder
3. Make sure your AWS credentials are set to a govcloud account (i.e. set `AWS_PROFILE`)
4. `terraform init`
5. `terraform apply -auto-approve`
6. `export KUBECONFIG=$PWD/rke2.yaml`
7. `kubectl get pods -n kube-system` and observe the crashing pods

**Expected behavior:**
RKE2 deploys as normal, no pods on a crash loop

**Actual behavior:**
CoreDNS, Metrics Server, and NGINX Backend containers repeatedly crash.

**Additional context / logs:**
The same terraform example works perfectly using RHEL7, leading me to believe that this problem is confined to RHEL8

**Comment by BrandonALXEllisSS** [comment]
Just tried the latest release v1.21.4+rke2r2 on the latest RHEL8.4 AMI. Even worse than before, the rke2-server.service failed to start at all. These are the logs I've been able to gather from journalctl, but I'm not sure if there's somewhere else I should be looking:
```

[ec2-user@ip-172-31-19-152 log]$ systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-08-30 13:39:43 UTC; 4s ago
     Docs: https://github.com/rancher/rke2#readme
  Process: 18668 ExecStopPost=/bin/sh -c systemd-cgls /system.slice/rke2-server.service | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill (code=exited, status=0/SUCCESS)
  Process: 18665 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=1/FAILURE)
```
```
[ec2-user@ip-172-31-19-152 log]$ journalctl -xe
-- Subject: Unit rke2-server.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit rke2-server.service has begun starting up.
Aug 30 13:40:25 ip-172-31-19-152.us-gov-west-1.compute.internal sh[18743]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 30 13:40:25 ip-172-31-19-152.us-gov-west-1.compute.internal systemd[1]: rke2-server.service: Control process exited, code=exited status=1
Aug 30 13:40:25 ip-172-31-19-152.us-gov-west-1.compute.internal systemd[1]: rke2-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit rke2-server.service has entered the 'failed' state with result 'exit-code'.
Aug 30 13:40:25 ip-172-31-19-152.us-gov-west-1.compute.internal systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
-- Subject: Unit rke2-server.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit rke2-server.service has failed.
-- 
-- The result is failed.
```

**However**, I tried the exact same build on govcloud ami "ami-57ecd436" (i.e. RHEL-8.3.0_HVM-20201031-x86_64-0-Hourly2-GP2). Works with no issues at all.

I can try a few other builds and see if they act differently, but I'm becoming more certain that this is a problem specifically with RHEL8.4 compatibility. I see even there was another issue (https://github.com/rancher/rke2/issues/1539) that addressed this problem too not too long ago.

**Comment by brandond** [comment]
`  Process: 18665 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=1/FAILURE)`

This indicates that you need to disable the nm-cloud-setup.service, as documented here: https://docs.rke2.io/known_issues/#networkmanager

**Comment by chaospuppy** [comment]
Thank you posting this @BrandonALXEllisSS , we were facing the same issue with RHEL8.  The [workaround](https://docs.rke2.io/known_issues/#networkmanager) @brandond linked to resolved the problem for us.
