### ISSUE TITLE
[release-1.21] RKE2 apiserver cert is missing hostname SAN entries

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1740]
Backport fix for **RKE2 apiserver cert is missing hostname SAN entries** to branch **release-1.21**:
* #1739

**Comment by brandond** [comment]
Fixed by k3s pull-through in #1738

**Comment by dereknola** [comment]
Validated on release-1.21 branch commit `3331746ba88b0cc5210e60a9c98e9c81ecd5260e` using: 
`echo QUIT |openssl s_client -connect 172.17.0.2:6443 2>&1 | openssl x509 -noout -text | grep -A1 Alternative`
