### ISSUE TITLE
[release-1.20] RKE2 apiserver cert is missing hostname SAN entries

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1741]
Backport fix for **RKE2 apiserver cert is missing hostname SAN entries** to branch **release-1.20**:
* #1739

**Comment by brandond** [comment]
Fixed by k3s pull-through in #1745

**Comment by dereknola** [comment]
Validated on release-1.20 branch commit `e89a4f5d7ddf2bbfcfea4ee8b0c978ce0c366378` using: 
`echo QUIT |openssl s_client -connect 172.17.0.2:6443 2>&1 | openssl x509 -noout -text | grep -A1 Alternative`
