### ISSUE TITLE
Change release artifacts and refactor install.sh script

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#175]
Based on our design discussions and talks with Darren, we'd like to change how RKE2 release works (artifacts from release process) and how the install.sh script works.

There is a desire to **simplify the install.sh script**. We instead should just have a tarball artifact for RKE2 -- basically including the structure of RKE2 (/etc/rancher, /var/lib/rancher, etc) and deploy via the install script. Tarbal should contain full dir structure: systemctl files, uninstall, killall, binary.
The install script should just extract tarball or do yum repo and rpm and package installs.

The install script should do **CIS mitigation but it will not create the etcd user** any longer.

The unit file should also be separated out. The install script can deploy the **unit file** but it should be a separate release artifact.

The install script should be cleaned up/simplified so it's not making so many changes to the system. It should essentially be a simple means to install rke2 onto the machine with minimal modifications to the system - the exception being the light CIS mitigation (sans create etcd user). **kill-all and uninstall script** should be separate release artifacts and not a part of the install.sh script.

Install.sh should be it's own artifact.

**Comment by ShylajaDevadiga** [comment]
Need to pass --tls-san through flags or env variable to access cluster outside node. INSTALL_RKE2_EXEC variable is missing. Issue tracked in #258

**Comment by ShylajaDevadiga** [comment]
@dweomer install script does not have the INSTALL_RKE2_SKIP_DOWNLOAD variable. When we do installation using private registry in airgapped setup having INSTALL_RKE2_SKIP_DOWNLOAD=true would enable running install script.

**Comment by dweomer** [comment]
> @dweomer install script does not have the INSTALL_RKE2_SKIP_DOWNLOAD variable. When we do installation using private registry in airgapped setup having INSTALL_RKE2_SKIP_DOWNLOAD=true would enable running install script.

In the spirit of making the top-level install script less complicated, this functionality was indeed dropped. If you are installing for airgap scenario then I would assume you have the installer downloaded already (which is all the top-level install.sh is doing for you anyway) therefor you should be running the installer directly.

**Comment by ShylajaDevadiga** [comment]
Validated install.sh using beta16/beta17.
Simple install using refactored install script
```
sudo INSTALL_RKE2_VERSION=v1.18.4-beta17+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' ./install.sh
```
Passing CIS profile
```
sudo INSTALL_RKE2_VERSION=v1.18.4-beta17+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' RKE2_CIS_PROFILE='cis-1.5' ./install.sh
```
