### ISSUE TITLE
Processes should stop when stopping rke2 process on windows agent

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1755]
**Environmental Info:**
RKE2 Version: 

v1.21.4-rc1+rke2r3

Node(s) CPU architecture, OS, and Version: 

Windows 2019

Cluster Configuration:

1 server 1 windows agent

**Describe the bug:**

When running the rke2 agent as a service, and then performing `Stop-Process rke2`, I expect the kubelet, kube-proxy, and containerd processes to also stop, similar as when stopping the rke2 binary process.

**Steps To Reproduce:**

- Install rke2 on windows node
- Run the rke2 agent as a service
- Stop the rke2 process

**Expected behavior:**

rke2, kubelet, kube-proxy, and containerd processes should all stop

**Actual behavior:**

Only rke2 process is stopped

**Additional context / logs:**

**Comment by rancher-max** [comment]
When validating this, we should also bring up linux servers/agents and validate the running killall, uninstall, and cluster-reset all continue to function properly

**Comment by brandond** [comment]
As well as just basic service start/stop behavior.

**Comment by rancher-max** [comment]
This issue mentions the last step as: `Stop-Process rke2`, but this is actually not the correct behavior. In this case, we should do `Stop-Service rke2` (stopping the SERVICE, not the PROCESS), as this is what most Windows Admins will do anyway.

**Comment by mdrahman-suse** [comment]
Tested rke2 using v1.21.6-rc2+rke2r2 and I am not seeing any other services (kube-proxy, kubelet, containerd, etc) other than rke2 getting stopped when I perform `Stop-Service rke2`. Please advice @luthermonson @rosskirkpat 
CC: @rancher-max

**Comment by nickgerace** [comment]
Fleet `v0.3.8-rc2` (now on Rancher `v2.6-head`) contains the Wrangler module bump needed for this issue: https://github.com/rancher/fleet/pull/615

**Comment by mdrahman-suse** [comment]
After debugging with @luthermonson, we came to conclusion that there are some additional code changes requires for this to fully work and it is working better than before and satisfies the scope of this issue. New issue will be raised and tracked for the additional work. At the time of testing this ticket it was observed that `Stop-Service rke2` stops most of the services used by rke2, except for one or two like kubelet and kube-proxy. For now they are stopped manually via `Stop-Process -Name <service>`
