### ISSUE TITLE
CIS Control 1.1.12 fails in SLES server nodes

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1756]
**Environmental Info:**
_RKE2 Version:_ 
All.. but confirmed with v1.21.4+rke2r2 so this has probably always been the case and not a regression

_Node(s) CPU architecture, OS, and Version:_ 
SLES15 SP2
```
$ uname -a
Linux ip-172-31-3-190 5.3.18-24.37-default #1 SMP Wed Nov 4 09:38:41 UTC 2020 (c145e08) x86_64 x86_64 x86_64 GNU/Linux

$  cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

_Cluster Configuration:_
3 servers 1 agent, but probably happens with just 1 server

**Describe the bug:**

This control states: `Ensure that the etcd data directory ownership is set to etcd:etcd (Automated)`
The audit expectation is:
```
stat -c %U:%G /var/lib/rancher/rke2/server/db/etcd
etcd:etcd
```
However, in SLES15 SP2, using either cis profile, this is coming back as `etcd:users`

**Steps To Reproduce:**

- Install RKE2 in cis mode using either profile. For example: `profile: cis-1.6` in config.yaml

**Expected behavior:**

This control should pass when using both `profile: cis-1.5` and `profile: cis-1.6`

**Comment by caroline-suse-rancher** [comment]
Closing due to age and because 1.21 is EOL - @rancher-max let me know if I should reopen, please!
