### ISSUE TITLE
ngrok link in the windows airgap install documentation page

### ISSUE THREAD

**Issue by rgl** [rancher/rke2#1759]
The following line has a ngrok url instead of pointing to the correct documentation:

https://github.com/rancher/rke2/blame/5c59f2f163ea1a016d9f6aaeaae8eaa5dbcecdd4/docs/install/windows_airgap.md#L7

I believe this should somehow point to:

https://github.com/rancher/rke2/blob/5c59f2f163ea1a016d9f6aaeaae8eaa5dbcecdd4/docs/install/requirements.md#windows

**Comment by rosskirkpat** [comment]
Thanks for finding this! I have opened a PR with a fix and also bumped the versions in the airgap documentation. I'll close this out once the PR is merged.

**Comment by rosskirkpat** [comment]
https://github.com/rancher/rke2/pull/1768

**Comment by rosskirkpat** [comment]
Closing this issue as the docs fix has been merged. Thanks again @rgl !
