### ISSUE TITLE
Add conformance tests to CI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#177]
We need to add conformance tests to RKE2 ci - similar to what k3s is doing today.

**Comment by davidnuzik** [comment]
I've edited this issue. This issue is needed for GA - it now just covers adding conformance tests. I've separated out the CIS Scan aspect into this issue here which can come post-GA: https://github.com/rancher/rke2/issues/243

**Comment by cjellick** [comment]
if all the conformance tests dont currently pass, i would settle now for just ensuring that a cluster comes up successfully and the k8s api becomes available
