### ISSUE TITLE
[release-1.21] Imported images are not associated with rke2 lease

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1779]
Ensure that imported image lease-locking works correctly on **release-1.21**
* https://github.com/k3s-io/k3s/issues/3758

**Comment by brandond** [comment]
I believe we should be set; the lease-locking fixes are in the K3s engine-1.21 branch as used by rke2 release-1.20 and release-1.21:
https://github.com/k3s-io/k3s/blob/841793de01fd693669e167dee5263ddacc9cf098/pkg/agent/containerd/containerd.go

To test:
> There does not appear to be any way to verify that the image content is reference from the lease using ctr. I used boltbrowser to ensure that the lease references image content following this change - while rke2 is stopped, you can run boltbrowser -ro /var/lib/rancher/rke2/agent/containerd/io.containerd.metadata.v1.bolt/meta.db and browse to v1/k8s.io/leases/k3s/content.

**Comment by brandond** [comment]
FYI this can be easily worked around by running k3s with the `--init` flag (as in `docker run --init --rm -it --privileged rancher/k3s:v1.21.4-rke1`) but it might be nice if we included something in the image to handle this so that it wasn't necessary.

**Comment by rancher-max** [comment]
Using boltbrowser in an airgapped environment on v1.21.5-rc2+rke2r1, I am able to see all these leases successfully.
