### ISSUE TITLE
Air-gapped image rewrite fails if path begins with docker.io

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1784]
Fix **Air-gapped image rewrite fails if path begins with docker.io** on branch **master**:
* #1460

**Comment by rancher-max** [comment]
Validated on master branch using commitid `09bb5c27f29cf3dd831653543d274c948a225385` following the same steps as mentioned in https://github.com/rancher/rke2/issues/1460#issuecomment-925188981
