### ISSUE TITLE
Validate hostpath is a directory for extra volume mounts

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1793]
We require a directory to be given on the host when using extra mounts per https://docs.rke2.io/advanced/#extra-control-plane-component-volume-mounts. If a file is specified instead of a directory, the apiserver fails to start and there is not a graceful failure. The kubelet logs do show an error (see below) but it can be confusing to track down if you don't know what to look for:
`E0909 23:55:10.632727  3145 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/host-path/eac51eca33e6f4dd652ad476a1bb7f27-extra-mount-0 podName:eac51eca33e6f4dd652ad476a1bb7f27 nodeName:}" failed. No retries permitted until 2021-09-09 23:55:11.13267816 +0000 UTC m=+26.909590544 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"extra-mount-0\" (UniqueName: \"kubernetes.io/host-path/eac51eca33e6f4dd652ad476a1bb7f27-extra-mount-0\") pod \"kube-apiserver-ip-172-31-21-153\" (UID: \"eac51eca33e6f4dd652ad476a1bb7f27\") : hostPath type check failed: /home/ubuntu/otherfile.yaml is not a directory"`

We should support mounting at least files and sockets, in addition to directories. We should also support manual specification of the mount type, for cases where auto-detection is not sufficient

**Comment by doubleplush** [comment]
At present, [the example documentation for the `extra-mount` options](https://docs.rke2.io/advanced#ro-host-path-volume-mount) implies that files can be HostPath mounted:

```
# /etc/rancher/rke2/config.yaml
kube-apiserver-extra-mount: 
   - "/tmp/foo.yaml:/root/foo.yaml"
   - "/tmp/bar.txt:/etc/bar.txt:ro"
```

It would be very useful for our use-case if some additional configuration could be added to allow HostPath mounting of individual files rather than directories.

**Comment by brandond** [comment]
Although it is documented that way, I'm not sure why we would only allow directories. I guess the problem with allowing files is handling files that don't exist, such as log files. This recently bit us with the audit log path stuff, as file mounts default to RO while dirs are RW.

**Comment by JaneLiuL** [comment]
hi , file can not mount, you can only mount  sourcefolder:destfolder

**Comment by brandond** [comment]
files are possible, the just have to exist ahead of time. The current code does not handle nonexistent files properly.

**Comment by JaneLiuL** [comment]
we test, actually , file exisit in the hostpath, but when mount, since rke2 treate it as directory, so file will not exist in the container

**Comment by rwd5213** [comment]
I actually seem to be having the same problem. I am trying to mount the /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem to /etc/ssl/ca-bundle.pem in the controller pod using kube-controller-manager-extra-mount. It errors out saying `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` is not a directory

**Comment by brandond** [comment]
@rwd5213 why not just mount `/etc/pki/ca-trust/extracted/pem:/etc/ssl` instead of trying to mount the specific file?

**Comment by rwd5213** [comment]
@brandond the container is looking for /etc/ssl/certs/ca-certificates.crt so the file/folder would have to be renamed. Just mounting the folders like you suggested would end out with /etc/ssl/tls-ca-bundle.pem being in there. Not sure that would work

**Comment by brandond** [comment]
@rwd5213 If you're trying to load that into the golang OS CA bundle, that is not the only path you can use - there is actually a whole list that is checked. See the list at https://go.dev/src/crypto/x509/root_linux.go

**Comment by ShylajaDevadiga** [comment]
### Validated using latest commit id https://github.com/rancher/rke2/commit/95e13dc62fdbda33de2c709f1149b0c361d920b9 on master branch
**Environment Details
Infrastructure**
Cloud EC2 instance

**Node(s) CPU architecture, OS, and Version:**
```
cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
```
**Cluster Configuration:**
Single node

**Steps to reproduce:**

1. Copy config file
2. Install rke2
3. Exec into kube-apiserver pod and check the expected results

**Replication results:**
```
ec2-user@ip-172-31-14-2:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /home/ec2-user/filedoesnotexists:/tmp/example
  
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- ls -l /tmp
total 0
drwxr-xr-x 2 root root 6 Apr 17 23:50 example
ec2-user@ip-172-31-14-2:~> 
```
**Validation results:**
_Test that a socket can be mounted into a pod:_
```ec2-user@ip-172-31-14-2:~> file /run/systemd/journal/dev-log
/run/systemd/journal/dev-log: socket
ec2-user@ip-172-31-14-2:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /run/systemd/journal/dev-log:/dev/log 
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- ls -l /dev/log 
srw-rw-rw- 1 root root 0 Apr 17 17:27 /dev/log
ec2-user@ip-172-31-14-2:~> 
```


_Test that an already existing file can be mounted into a pod:_
```
ec2-user@ip-172-31-14-2:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /usr/share/zoneinfo/Etc/UTC:/etc/localtime
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- cat /etc/localtime
TZif2UTCTZif2UTC
UTC0
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- ls -l  /etc/localtime
lrwxrwxrwx 1 root root 27 Feb 26 06:44 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
ec2-user@ip-172-31-14-2:~> 
```
_Test that an already existing file can be mounted into a pod  in default rw mode:_

```
ec2-user@ip-172-31-14-2:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /home/ec2-user/f1:/tmp/f1
ec2-user@ip-172-31-14-2:~> cat f1
testfile
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- cat /tmp/f1  && echo "newfile" >>/tmp/f1 && cat /tmp/f1
testfile
newfile
```
_Test that an already existing file can be mounted into a pod  in ro mode:_

```
ec2-user@ip-172-31-14-75:~> cat f2
testfile

ec2-user@ip-172-31-14-75:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /home/ec2-user/f2:/tmp/f2:ro

> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-75 -- cat /tmp/f2  && echo "newfile" >>/tmp/f2 
testfile

> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-75 -- cat /tmp/f2
testfile

```

_Test that a nonexistent file can be mounted into a pod, and will be created on first use:_

```
ec2-user@ip-172-31-14-2:~> cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
token: <TOKEN>
kube-apiserver-extra-mount:
  - /tmp/foo.yaml:/root/foo.yaml:rw:FileOrCreate
  - /tmp/bar.txt:/etc/bar.txt:ro:FileOrCreate
ec2-user@ip-172-31-14-2:~> kubectl exec -n kube-system kube-apiserver-ip-172-31-14-2 -- ls -l /root/foo.yaml
-rw-r--r-- 1 root root 0 Apr 17 22:35 /root/foo.yaml
ec2-user@ip-172-31-14-2:~> 
```
