### ISSUE TITLE
RKE2 won't start with minimal requirements

### ISSUE THREAD

**Issue by remche** [rancher/rke2#1794]
**Environmental Info:**
RKE2 Version: 
v1.21.4+rke2r3

Node(s) CPU architecture, OS, and Version: 
Linux (all version)

Cluster Configuration:
1 server

**Describe the bug:**
RKE2 server wont start with the minimal requirements stated in [the documentation](https://docs.rke2.io/install/requirements/#linux_1).

The total CPU request for system pods is 1370 : 

```bash
kubectl get pods -n kube-system -o=jsonpath={'.items[*].spec.containers[*].resources.requests.cpu'}
200m 250m 200m 250m 100m 250m 100m 20m
```

**Steps To Reproduce:**
Run the server with only 1 CPU

**Comment by brandond** [comment]
@cjellick @cwayne18 We should probably raise the requirements on the docs page - do we need to check with anyone before doing this? Both the CPU and Memory requirements seem unrealistically low.

**Comment by mdrahman-suse** [comment]
@brandond For this specific issue, the tests were scoped to getting minimum requirements for server instance with nothing but an idle control-plane workload. We can test the 2GB/2CPU config with Rancher installed and observe the behavior.

**Comment by dereknola** [comment]
Hardware requirements have now been updated https://docs.rke2.io/install/requirements/#linuxwindows to 4/8GB
