### ISSUE TITLE
Correctly name the 9345 port in the requirements page

### ISSUE THREAD

**Issue by rgl** [rancher/rke2#1801]
The [requirements page](https://github.com/rancher/rke2/blame/5c59f2f163ea1a016d9f6aaeaae8eaa5dbcecdd4/docs/install/requirements.md#L76) names the following ports the same, but I think the 9345 should be called `Node Registration API`, `RKE2 Server API`, or even something more appropriate than `Kubernetes API`:

 Protocol | Port | Source | Description
|-----|-----|----------------|---|
| TCP | 9345 | RKE2 agent nodes | ~Kubernetes API~ Node Registration API or  RKE2 Server API |
| TCP | 6443 | RKE2 agent nodes | Kubernetes API |

**Comment by brandond** [comment]
Internally we refer to this as the supervisor port; it is the K3s/RKE2 Kubernetes provisioning API.
