### ISSUE TITLE
Windows service does not log the started services like kube-proxy anywhere

### ISSUE THREAD

**Issue by rgl** [rancher/rke2#1807]
**Environmental Info:**

RKE2 Version: 

```
rke2.exe version v1.21.4+rke2r3 (a6885e255371edb16ada271e6d75231773bf3153)
go version go1.16.6b7
```

Node(s) CPU architecture, OS, and Version: 

AMD64, Windows 2019 1809.

Cluster Configuration:

N/A

**Describe the bug:**

When the rke2 windows service is installed with `rke2 agent service --add`, we have no way to see the other processes logs like kube-proxy.

**Steps To Reproduce:**

Install the rke2 windows service with `rke2 agent service --add`.

**Expected behavior:**

Be able to read the rke2 started processes logs like the kube-proxy logs somewhere (e.g. in a file on disk).

**Actual behavior:**

Windows Event Logs only have the rke2 service logs.

**Additional context / logs:**

It seems the [current implementation just redirects the kube-proxy.exe stdout/stderr to the parent process (the windows service stdin/stdout)](https://github.com/rancher/rke2/blob/f377e3eedca2e9037b173981af6cccb5821b072b/pkg/pebinaryexecutor/pebinary.go#L211-L220). But on a windows service, the stdout/stderr descriptors do not really exist, as such, the logs are not written anywhere, hence this bug.

**Comment by phillipsj** [comment]
They are written to the event viewer logs under the rke2 application.

**Comment by rgl** [comment]
Indeed, I can see something being written to the rke2 event source, but, as described initially in this issue, it seems to be just the rke2 logs, not the logs of the started applications like kube-proxy.exe.

It also seems that something is not working correctly, as the general tab show `Incorrect function.` (although, the log details tab seems to contain the expected log line):

![image](https://user-images.githubusercontent.com/43356/210327053-7c8e794c-0b52-4232-845a-e8d849f8db0e.png)

**Comment by caroline-suse-rancher** [comment]
Closing, as this does not appear to be a bug within RKE2
