### ISSUE TITLE
[Feature request]: Support CoreDNS customizations

### ISSUE THREAD

**Issue by olljanat** [rancher/rke2#1808]
**Is your feature request related to a problem? Please describe.**
CoreDNS have nice plugin called for [rewrite](https://coredns.io/plugins/rewrite/) which allow on-the-fly DNS name rewrites. However currently only way modify CoreDNS configuration is use HelmChartConfig which IMO is very complex solution to simple problem.

**Describe the solution you'd like**
IMO best option would be use same solution than AKS is using by supporting custom config map with `.server` / `.override` sections: 
* https://docs.microsoft.com/en-us/azure/aks/coredns-custom#before-you-begin
* https://github.com/Azure/aks-engine/blob/6f730c853a604506df7772407069163752302c10/parts/k8s/addons/coredns.yaml#L80-L82

**Comment by brandond** [comment]
HelmChartConfig is the officially supported mechanism to customize packaged components. What other solution might you have in mind?

**Comment by olljanat** [comment]
Looks that someone have made PR about it recently https://github.com/coredns/helm/pull/44 so will close this one from here as follow that one.
