### ISSUE TITLE
How to deal with secondary masters and agents during restore from etcd snapshot?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#1814]
**Environmental Info:**
RKE2 Version: 1.20.*

Cluster Configuration:
3 master, 10 worker/agents

**Describe the bug:**
What needs to be done on the secondary master/agent/worker nodes during a restore of an etcd snapshot?

In the documentation we can just find what to do on one master - is this enough and don´t we have to touch anything on secondary masters / workers or do we have to do something on the other masters/workers, too?

Maybe we just need some more details in the documentation?

**Comment by brandond** [comment]
When you reset/restore on the 1st node, it will provide instructions on what to do on the other nodes.
https://github.com/k3s-io/k3s/blob/928b8531c38b5fd630dd0aa4360a8c5dc943e72c/pkg/etcd/etcd.go#L215
> Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes

**Comment by Martin-Weiss** [comment]
> 
> 
> When you reset/restore on the 1st node, it will provide instructions on what to do on the other nodes.
> https://github.com/k3s-io/k3s/blob/928b8531c38b5fd630dd0aa4360a8c5dc943e72c/pkg/etcd/etcd.go#L215
> 
> > Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes

Thanks for the fast reply.. however I still believe we need more input and an updated / enhanced description of the process here: https://docs.rke2.io/backup_restore/  ;-).

What does "rejoin the nodes" mean and how is that done? Are these RKE2 nodes or ETCD nodes?

So are the following two processes correct?:

Case A: Cluster consisting of 3 server/master, 4 worker/agents, snapshot restore with cluster still up and running

1. stop only first master and leave second and third and all workers running (systemctl stop rke2-server)
2. start first master it again with --cluster-reset and --cluster-reset-restore-path=<PATH-TO-SNAPSHOT> and the details for the snapshot source (s3, bucket,...)
   rke2 server \
  --cluster-reset \
  --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
3. restart second master without any config change (systemctl restart rke2-server)
4. restart fourth master without any  config change (systemctl restart rke2-server)
5. delete and re-join the "nodes" (ETCD or RKE2?)
--> what steps and details do I miss, here?

Case B: Cluster consisting of 3 server/master, 4 worker/agents, snapshot restore after cluster was lost completely
(all servers got deleted)

1. install first master with and with original config.yaml
  rke2 server \
  --cluster-reset \
  --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
2. install second master with original config.yaml and start it
3. install third master with original config.yaml and start it
4. install all workers with original config.yaml
--> what steps and details do I miss, here?

Thanks!!

**Comment by brandond** [comment]
> What does "rejoin the nodes" mean and how is that done? Are these RKE2 nodes or ETCD nodes?

Stop the rke2-server service, rename/delete the db directory, start rke2-server again (assuming your configuration still has the --server flag pointing at the first server)

**Comment by Martin-Weiss** [comment]
> 
> 
> > What does "rejoin the nodes" mean and how is that done? Are these RKE2 nodes or ETCD nodes?
> 
> Stop the rke2-server service, rename/delete the db directory, start rke2-server again (assuming your configuration still has the --server flag pointing at the first server)
> 

So for a snapshot restore process on a still running cluster is this process correct?

1. Stop all three masters before I start with the snapshot recovery (systemctl stop rke2-server)
2. Then on the first master
  rke2 server
  --cluster-reset
  --cluster-reset-restore-path=
3. on the second / third master rename/delete the db directory, start rke2-server again (assuming your configuration still has the --server flag pointing at the first server)
4.  On workers - do nothing

> When we talk about nodes we mean a RKE2/Kubernetes node. If we're talking about something that needs to be done at an etcd level we talk about members, as that is the language that etcd uses. You should not ever need to directly manipulate the etcd cluster; if you did need to do this we would include the etcdctl binary as we do crictl.

Understood.

**Comment by brandond** [comment]
> So for a snapshot restore process on a still running cluster is this process correct?
> 
> 1. Stop all three masters before I start with the snapshot recovery (systemctl stop rke2-server)
> 2. Then on the first master
>   rke2 server
>   --cluster-reset
>   --cluster-reset-restore-path=
> 3. on the second / third master rename/delete the db directory, start rke2-server again (assuming your configuration still has the --server flag pointing at the first server)
> 4.  On workers - do nothing

You got it!

**Comment by Martin-Weiss** [comment]
Do you think this could be added to https://docs.rke2.io/backup_restore/ ?

**Comment by Martin-Weiss** [comment]
Just had to realize that we still have containers (including etcd) still running after a systemctl stop rke2-server.
So is it enough to stop and then remove the db / run the --cluster-reset or should we better execute the rke2-killall.sh before executing the --cluster-reset / deletion of the db on secondary masters?

**Comment by Martin-Weiss** [comment]
And one more point - do we have to recover the "old" SSL certificates from /var/lib/rancher/rke2/server/tls, too?

**Comment by brandond** [comment]
The kubelet is started up in standalone mode to terminate the static pods as part of the restore process. You should not need to manually kill pods running on the node, unless your workload might be negatively affected by the rollback of cluster state associated with the restore.

**Comment by Martin-Weiss** [comment]
FYI - it seems in 1.20.8 we can not get the reset / restore working (ssl error in rke2-server for :9345) as part of a disaster recovery process (all Nodes lost completely). In 1.20.11 we can restore the backup created in 1.20.8 in case we stop all & do rm -rf /var/log/rancher/rke2/* before the cluster reset.
(we have config.yaml with cluster details and token in /etc/rancher/rke2 at this point in time)

So process with 1.20.11 is like this:
1. deploy new rke2 cluster with 3 master, 4 worker with same identity and config.yaml of old cluster including S3 details
2. systemctl stop rke2-server; systemctl stop rke2-agent; rke2-killall.sh on all nodes
3. rm -rf /var/lib/rancher/rke2/* on all nodes
4. On first master: rke2 server --cluster-reset --cluster-reset-restore-path=<S3 backup object to recover>
  --> wait until message "Etcd is running, restart without --cluster-reset flag now"
5. On first master systemctl stop rke2-server; rke2-killall.sh
6. On first master systemctl start rke2-server -> wait until kubectl get nodes shows the cluster nodes
7. On second master systemctl start rke2-server -> wait until kubectl get nodes shows the cluster nodes
8. On third master systemctl start rke2-server -> wait until kubectl get nodes shows the cluster nodes
9. On workers / agents -> systemctl start rke2-agent -> wait until all workers are up and running well

Do you agree that this is a valid process or do we oversee / miss something in this scenario?

**Comment by Martin-Weiss** [comment]
Just had to realize that this whole procedure and documentation is incomplete for the agents!

Basically if you want to re-join a re-installed agent as an existing node after the etcd restore - you have to delete the nodes password / the secret in the kube-system namespace.. as the /etc/rancher/node/password can not be recovered easily on a reinstalled node.

-> could we get this also added to the restore procedure, please?

**Comment by brandond** [comment]
I believe this is covered in https://docs.rke2.io/advanced/#how-agent-node-registration-works

> If the /etc/rancher/node directory of an agent is removed, the password file should be recreated for the agent prior to startup, or the entry removed from the server or Kubernetes cluster (depending on the RKE2 version).

How can we enhance this?

**Comment by Martin-Weiss** [comment]
> 
> 
> I believe this is covered in https://docs.rke2.io/advanced/#how-agent-node-registration-works
> 
> > If the /etc/rancher/node directory of an agent is removed, the password file should be recreated for the agent prior to startup, or the entry removed from the server or Kubernetes cluster (depending on the RKE2 version).
> 
> How can we enhance this?

IMO we need the disaster recovery procedure for agents added here: https://docs.rke2.io/backup_restore/ as someone who wants to do a recovery will not look into "advanced / how-agent-node-registration-works" ;-).

Maybe something like the following could be added to https://docs.rke2.io/backup_restore/ :

In case of a full disaster recovery (lost nodes / new nodes) - after the restore of ETCD on new nodes keep in mind that in etcd has node passwords stored in secrets that can not be recovered and are different of new nodes /etc/rancher/node/password. Due to this the nodes will not re-join to the same node object automatically and it is required to delete the secrets of the nodes that are re-installed "fresh".

Node recovery (new node):
- after restore of etcd on new masters delete the secret for the node you want to re-join
      `kubectl -n kube-system delete secret <node>.node-password.rke2`
- reinstall the new node with same name, IP and config in /etc/rancher/rke2/*
- install rke2 from tarball or via script and start the rke2-agent

Hint: an other option would be to delete the node object and then re-join but this might cause a loss of adjustments that have been done on the node objects after initial join (i.e. manually added labels)

**Comment by Martin-Weiss** [comment]
FYI - one more learning from today! In case of a restore of etcd during a full cluster recovery - on the first master where we restore the etcd backup we have to comment out the "server:" line in config.yaml as otherwise the restore will not happen!
-> could we get this added to the documentation, too?
