### ISSUE TITLE
Minor doc updates to "Istio SELinux Enforcing" section

### ISSUE THREAD

**Issue by jesseagonzalez** [rancher/rke2#1822]
**Describe the bug:**

Base on recent findings, wanted to propose making some minor updates to the `Istio SELinux Enforcing` section of document.

1. Istio `custom overlay` yaml seems to be rendering incorrectly.  Markdown page looks correct in github repo, but when visiting page on rendered `docs.rke2.io` site, the yaml is not properly formatted. See links below for examples:
    - WRONG: https://docs.rke2.io/known_issues/#istio-in-selinux-enforcing-system-fails-by-default
    ![image](https://user-images.githubusercontent.com/8986826/133420200-473ea9de-e821-493e-b5cd-248dd1ce4dae.png)
    - CORRECT: https://github.com/rancher/rke2/blob/master/docs/known_issues.md#istio-in-selinux-enforcing-system-fails-by-default
    ![image](https://user-images.githubusercontent.com/8986826/133420415-a03191e9-9741-426f-9b3d-d42a04d3ce55.png)

2. Within Istio `custom overlay` yaml, the cni image version (i.e., image: rancher/mirrored-istio-install-cni:1.9.3) should be aligned with the actual istio version deployed. (i.e., 1.10.4 being latest), otherwise, you'll see compatibility issues - such as the one below when latest istio version was applied as per docs in https://rancher.com/docs/rancher/v2.5/en/istio/configuration-reference/rke2/

```
...kubelet Error: failed to create containerd task: ... : stat /opt/local/bin/istio-cni-repair: no such file or directory: unknown
```

3. If the `custom overlay` yaml is used exactly as noted within the `docs.rke2.io` site - then the second step ("2. After the install is complete, there should be cni-node pods in a CrashLoopBackoff. Manually edit their daemonset to include securityContext.privileged: true on the install-cni container.") should not be required.

4. Not sure if this should be opened as separate issue, but on https://rancher.com/docs/rancher/v2.5/en/istio/configuration-reference/rke2/ site, the docs should be in-sync to avoid further confusion

**Comment by brandond** [comment]
A PR would be welcome!
