### ISSUE TITLE
node-role.kubernetes.io/master=:NoSchedule taint causes helm-install* jobs to stay in pending state

### ISSUE THREAD

**Issue by FruityWelsh** [rancher/rke2#1826]
**Environmental Info:**
RKE2 Version: 1.20

Node(s) CPU architecture, OS, and Version: 

Linux rke2-dev-0.tfe.dev 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Wed Feb 3 03:12:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master node
**Describe the bug:**

Helm install of core services fails to run on master node if `node-role.kubernetes.io/master=:NoSchedule` taint is set
**Steps To Reproduce:**

- Installed RKE2: 
- Set custom rke2-*-config.yamls
- tainted master node with cmd:
```
kubectl taint nodes \
                           -l node-role.kubernetes.io/master=true \
                           node-role.kubernetes.io/master=:NoSchedule \
                           --overwrite=true
```
**Expected behavior:**

Expected jobs to run and update core services
**Actual behavior:**

helm-install jobs stay in pending stay because they do not tolerate the master node toleration

**Comment by brandond** [comment]
As of 1.20, the master taint and role is deprecated in favor of control-plane. If you're going to taint your servers you should use control-plane instead. See:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint

**Comment by FruityWelsh** [comment]
issue seems to also apply to node-role.kubernetes.io/control-plane:NoSchedule

**Comment by brandond** [comment]
@FruityWelsh what version are you using?
https://github.com/k3s-io/helm-controller/blob/master/pkg/helm/controller.go#L293-L317

**Comment by FruityWelsh** [comment]
v1.20.8+rke2r1

**Comment by brandond** [comment]
That version of rke2 uses helm-controller v0.9.3 which should also include the correct tolerations:
https://github.com/k3s-io/helm-controller/blob/v0.9.3/pkg/helm/controller.go#L277

Note that these tolerations are only present on **bootstrap** charts that are critical for cluster operation. Other charts will remain pending until you provide untainted worker nodes.
