### ISSUE TITLE
rke2.yaml with server address lookpback (127.0.0.1) not LB

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#1831]
Below steps when buildings RKE2 cluster on RHEL 8 & F5 LB (rancher.example.com) with signed CA loaded.

```
mkdir -p /etc/rancher/rke2
cat << EOF >  /etc/rancher/rke2/config.yaml
token: pkls-secret
write-kubeconfig-mode: "0644"
tls-san:
  - rancher.example.com
EOF

curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.20 sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

Cluster build OK. When I look kubeconfig file (/etc/rancher/rke2/rke2.yaml) its a loopback (server: https://127.0.0.1:6443) not LB (rancher.example.com)

That OK, I am able to get cluster details. 

But if I change server address with LB (rancher.example.com) in  kubeconfig file (/etc/rancher/rke2/rke2.yaml) then getting following error ...

```Unable to connect to the server: x509: certificate signed by unknown authority```

**Comment by brandond** [comment]
Yes, the local admin kubeconfig on each server points at the local apiserver instance. On agents it points at a client loadbalancer that distributes connections between servers. The external LB address is only used when initially connecting to the cluster. This is covered in the RKE2 HA documentation.
