### ISSUE TITLE
Restart rancher-vsphere-cpi helm chart DaemonSet when credentialsSecret referenced in HelmChartConfig is updated

### ISSUE THREAD

**Issue by ron1** [rancher/rke2#1832]
**Environmental Info:**
RKE2 Version: 1.21.4+rke2r2

**Describe the bug:**
The rancher-vsphere-cpi helm chart DaemonSet rancher-vsphere-cpi-cloud-controller-manager is not automatically restarted when the credentialsSecret referenced in its RKE2 HelmChartConfig is updated.

A current workaround for this issue is to perform a rollout restart on the DaemonSet after the Secret/HelmChartConfig resource is updated.

**Steps To Reproduce:**
- Install RKE2 v1.21.4+rke2r2 with cloud-provider-name "rancher-vsphere". After installation, use kubectl to apply the following resources to the kube-system namespace:
- Secret rancher-vsphere-cpi-secret 
- HelmChartConfig rancher-vsphere-cpi with credentialsSecret.name="rancher-vsphere-cpi-secret" and credentialsSecret.generate="false"  
- HelmChartConfig rancher-vsphere-csi with configSecret.name="vsphere-config-secret" and configSecret.generate="true"

**Expected behavior:**
DaemonSet rancher-vsphere-cpi-cloud-controller-manager is automatically restarted with the updated secret
**Actual behavior:**
DaemonSet rancher-vsphere-cpi-cloud-controller-manager continues to run with a generated, invalid vsphere-cpi-creds Secret.

**Comment by brandond** [comment]
There's no linkage between the ConfigMap and the Pods/HelmChart/HelmChartConfig. Reloading Pods that mount a ConfigMap when the ConfigMap changes has long been a requested feature (see https://github.com/kubernetes/kubernetes/issues/22368) but at this point I'm not sure there's an easy fix on our side. Perhaps adding a https://github.com/jimmidyson/configmap-reload sidecar?

**Comment by caroline-suse-rancher** [comment]
Closing due to age
