### ISSUE TITLE
Support passing http_proxy envs to containerd

### ISSUE THREAD

**Issue by gitlawr** [rancher/rke2#1834]
**Is your feature request related to a problem? Please describe.**
* Similar to https://github.com/k3s-io/k3s/issues/3552
We would like to pull images via internal proxy

**Additional context**
* Dependency of https://github.com/harvester/harvester/issues/1218

**Comment by brandond** [comment]
Note that this is not quite so simple on RKE2, as RKE2 pulls the runtime image directly, before containerd is available.

If you don't have a proxy set for the main RKE2 process, this image pull will fail and RKE2 will not be able to start unless you've preloaded the runtime image via an airgap tarball.

Can you describe your use case a little better, and whether or not this would be a problem for you?

**Comment by gitlawr** [comment]
It is not a problem in our use case. Harvester packages and preloads all the runtime images. The configuration is useful when users want to run other workloads in the cluster.

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/commit/cbfe673c43e5ac369b50f39b8e4bde951192612a was on K3s master when we forked the engine-1.21 branch, so this should already be available in this month's RKE2 1.20 and 1.21 releases.

**Comment by guangbochen** [comment]
@brandond your above-pasted comments seem incorrect, just wondering would https://github.com/k3s-io/k3s/pull/4009 address the issue with the following env config.
```
[Service]
...
Environment="CONTAINERD_HTTP_PROXY=http://this.is.my.fake.proxy/"
Environment="CONTAINERD_HTTPS_PROXY=https://this.is.my.fake.proxy/"
...
```

**Comment by gitlawr** [comment]
Verified that passing the `CONTAINERD_*_PROXY` envs works.

**Comment by brandond** [comment]
@guangbochen what specifically is incorrect? It looks like @gitlawr was able to use the variable pass-through support.

**Comment by guangbochen** [comment]
Yep it works with the above env config, and sorry I mean the comment link https://github.com/k3s-io/k3s/commit/cbfe673c43e5ac369b50f39b8e4bde951192612a instead, thanks

**Comment by gtato** [comment]
@brandond Is there a way to configure the http proxy on windows before the rke2 agent starts? It doesn't seem to take into account the system proxy.

**Comment by brandond** [comment]
It should honor the proxy environment variables on Windows, same as it does on Linux. I would not expect it to honor the Windows system proxy settings.
