### ISSUE TITLE
Unable to find rke2-airgap-images tarball artifact

### ISSUE THREAD

**Issue by miket1** [rancher/rke2#1835]
The rke2 installation guide says:
RKE2 can be installed in an air-gapped environment with two different methods. You can either deploy via the rke2-airgap-images tarball release artifact, or by using a private registry.

However, when I go to the Assests for the latest release there is no tarball listed for rke2-airgap-images. Could you please help point me in the right direction? Thank you!

**Comment by brandond** [comment]
Did you see: https://docs.rke2.io/install/airgap/#tarball-method
