### ISSUE TITLE
 Readiness probe failed, when deployed istio service mesh in Rke2 based cluster 

### ISSUE THREAD

**Issue by ajeetas** [rancher/rke2#1846]
**Environmental Info:**
RKE2 Version: 
v1.20.10+rke2r1

[root@servernode1 ajeetas]# rke2 -v
rke2 version v1.20.10+rke2r1 (a4f6020ec8728f47c049bdd9c6504995cdb4928c)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
I[root@servernode1 ajeetas]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Cluster Configuration:

[root@servernode1 manifest]# kubectl get nodes -o wide
NAME                      STATUS   ROLES                       AGE     VERSION           INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                   KERNEL-VERSION           CONTAINER-RUNTIME
agentnode1.example.com    Ready    <none>                      4h30m   v1.20.10+rke2r1   10.106.102.172   <none>        Red Hat Enterprise Linux   3.10.0-1062.el7.x86_64   containerd://1.4.8-k3s1
servernode1.example.com   Ready    control-plane,etcd,master   30h     v1.20.10+rke2r1   10.106.102.171   <none>        Red Hat Enterprise Linux   3.10.0-1062.el7.x86_64   containerd://1.4.8-k3s1

**Reproduce steps**

https://istio.io/latest/docs/setup/install/istioctl/
follow the above guide to install istio service mesh and getting below logs;

[root@servernode1 manifest]# kubectl get pods -n istio-system  -o wide
NAME                                    READY   STATUS              RESTARTS   AGE   IP           NODE                      NOMINATED NODE   READINESS GATES
istio-ingressgateway-7cc49dcd99-hj8r6   0/1     ContainerCreating   0          60m   <none>       servernode1.example.com   <none>           <none>
istiod-db9f9f86-kmrdb                   0/1     CrashLoopBackOff    17         65m   10.42.2.13   agentnode1.example.com    <none>           <none>

**Log**

```
 kubectl describe pod istiod-db9f9f86-kmrdb -n istio-system
  Normal   Scheduled  11m                  default-scheduler  Successfully assigned istio-system/istiod-db9f9f86-kmrdb to agentnode1.example.com
  Warning  Unhealthy  10m (x4 over 11m)    kubelet            Readiness probe failed: Get "http://10.42.2.13:8080/ready": dial tcp 10.42.2.13:8080: connect: connection refused
  Normal   Pulled     9m42s (x5 over 11m)  kubelet            Container image "docker.io/istio/pilot:1.9.2" already present on machine
  Normal   Created    9m42s (x5 over 11m)  kubelet            Created container discovery
  Normal   Started    9m42s (x5 over 11m)  kubelet            Started container discovery
  Warning  BackOff    69s (x46 over 11m)   kubelet            Back-off restarting failed container
```

**Comment by brandond** [comment]
And what to the logs from that pod say?

**Comment by ajeetas** [comment]
[root@servernode1 manifest]# kubectl logs -f istiod-db9f9f86-kmrdb -n istio-system
Error from server: Get "https://10.106.102.172:10250/containerLogs/istio-system/istiod-db9f9f86-kmrdb/discovery?follow=true": dial tcp 10.106.102.172:10250: connect: no route to host

**Comment by brandond** [comment]
Hmm, the apiserver can't reach the node that pod is running on to read the logs? Is something wrong with your network?

**Comment by ajeetas** [comment]
root@servernode1 manifest]# kubectl get pods -A -o wide
NAMESPACE       NAME                                                 READY   STATUS              RESTARTS   AGE     IP               NODE                      NOMINATED NODE   READINESS GATES 
istio-system    istio-egressgateway-bd6d77495-jp594                  0/1     ContainerCreating   0          30m     <none>           agentnode1.example.com    <none>           <none>
istio-system    istio-ingressgateway-d46c4ff9b-tw2tw                 0/1     ContainerCreating   0          30m     <none>           agentnode1.example.com    <none>           <none>
istio-system    istiod-79ddd9dbf5-q267x                              0/1     CrashLoopBackOff    11         35m     10.42.2.15       agentnode1.example.com    <none>           <none>
kube-system     cloud-controller-manager-servernode1.example.com     1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     etcd-servernode1.example.com                         1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     helm-install-rke2-canal-76dng                        0/1     Completed           0          16h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     helm-install-rke2-ingress-nginx-thxgg                0/1     Completed           0          37h     10.42.0.2        servernode1.example.com   <none>           <none>
kube-system     helm-install-rke2-metrics-server-g2p5n               0/1     Completed           0          37h     10.42.0.3        servernode1.example.com   <none>           <none>
kube-system     httpbin-74fb669cc6-qdbcp                             1/1     Running             0          5h42m   10.42.0.15       servernode1.example.com   <none>           <none>
kube-system     kube-apiserver-servernode1.example.com               1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     kube-controller-manager-servernode1.example.com      1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     kube-proxy-agentnode1.example.com                    1/1     Running             0          11h     10.106.102.172   agentnode1.example.com    <none>           <none>
kube-system     kube-proxy-servernode1.example.com                   1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     kube-scheduler-servernode1.example.com               1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     rke2-canal-nrplj                                     1/2     Running             0          16h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     rke2-canal-sjdjm                                     1/2     Running             0          11h     10.106.102.172   agentnode1.example.com    <none>           <none>
kube-system     rke2-coredns-rke2-coredns-675b5596bc-jzk7l           1/1     Running             0          37h     10.42.0.4        servernode1.example.com   <none>           <none>
kube-system     rke2-ingress-nginx-controller-54946dd48f-4hc4x       1/1     Running             0          37h     10.106.102.171   servernode1.example.com   <none>           <none>
kube-system     rke2-ingress-nginx-default-backend-5795954f8-vkrwq   1/1     Running             0          37h     10.42.0.6        servernode1.example.com   <none>           <none>
kube-system     rke2-metrics-server-559dc47bd8-zphjr                 1/1     Running             0          37h     10.42.0.5        servernode1.example.com   <none>           <none>

**Comment by ajeetas** [comment]
other than istiod pods, application pod coming up properly.

**Comment by brandond** [comment]
That doesn't tell me anything about why the apiserver can't reach the kubelet on your node to view logs though.
