### ISSUE TITLE
Flannel - iface - different name on different nodes

### ISSUE THREAD

**Issue by chickeaterbanana** [rancher/rke2#1889]
**Environmental Info:**
RKE2 Version:
rke2 version v1.21.5+rke2r1 (881084666b8134df6c3086d4710d458c753f8c38)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux worker01 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux worker02 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux worker01 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
worker01, worker02 and worker03 are agent, etcd and server

**Describe the bug:**

https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/templates/config.yaml#L15
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/templates/daemonset.yaml#L215

My problem is following configuration:
worker01 private network interface is `enp35s0.4000`.
worker02 private network interface is `enp7s0.4000`.
worker03 private network interface is `enp35s0.4000`.

The default route of the nodes aren't assigned to these interfaces. I have to override the configuration of canal/flannel.

Its only one ConfigMap for all server. So the last server which configures the HelmChartConfig wins the battle for the correct config. If I restart one of the other server they would try to run the canal/flannel with the wrong interface.

**Steps To Reproduce:**

- Installed RKE2: 
Shell script downloaded from rke2.io.
Start 3 Server with different interface names and try to configure flannel explicit over helmchartconfig.

**Expected behavior:**

Possibility to configure each nodes interface name.

**Actual behavior:**

The flannel interface has to be named on all nodes the same.

**Comment by brandond** [comment]
@manuelbuil do you have any ideas on how we might handle per-node configuration?

**Comment by chickeaterbanana** [comment]
I've found a temporarily fix. I created virtual interfaces with the same name and modified the ConfigMap. This isn't so comfortable but gets the cluster rebootable.

**Comment by brandond** [comment]
You might also consider adding `net.ifnames=0 biosdevname=0` to your kernel command line, which would cause your interfaces to go back to the old `eth0` naming scheme instead of the new "predictable" scheme.

**Comment by manuelbuil** [comment]
The way to workaround this in flannel would be to define a list of interfaces with the `iface` variable. Flannel will check each value in order and will use the first match found. So you could use: --iface=enp35s0.4000,enp7s0.4000,enp35s0.4000 and flannel will choose the correct one for each worker (assuming they are only existing in one worker).

Another way would be to define the interface by the `iface-regex`, but that is a bit more complex to me, as I hate regex :)

**Comment by manuelbuil** [comment]
Hence, could you try using the helm value:
```
canal_iface: enp35s0.4000,enp7s0.4000,enp35s0.4000
```

**Comment by dweomer** [comment]
> You might also consider adding `net.ifnames=0 biosdevname=0` to your kernel command line, which would cause your interfaces to go back to the old `eth0` naming scheme instead of the new "predictable" scheme.

Came here to say exactly this!

**Comment by chickeaterbanana** [comment]
Thank you. I've found a suitable setup. For me the virtual interfaces are the most stable variant because of the explicit declaring of the name. `net.ifnames=0 biosdevname=0` and multiple choices in `canal_iface` didn't save me for misconfigurations if I add new hardware with interface namings I didn't expect.

**Comment by caroline-suse-rancher** [comment]
Closing as there appears to be a sufficient workaround
