### ISSUE TITLE
Windows install.ps1 airgap tarballs naming structure doesn't match published artifacts

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1890]
**Environmental Info:**
RKE2 Version: commit `9517e166151f202814d5a8856ab038ec53f43d4a`

**Describe the bug:**

Currently, there's an issue with the install.ps1 script as the [airgap tarball checksum](https://github.com/rancher/rke2/blob/master/install.ps1#L419-L426) naming structure will look for rke2-images.windows-amd64.tar.zst or  rke2-images.windows-amd64.tar.gz and we do not publish any artifacts with those names.

This will also cause testing specific commits to fail. Below is the tarball checksum file URL that the install script is looking for. This file does not exist and will have a separate issue filed for that.

`https://storage.googleapis.com/rke2-ci-builds/rke2-images.windows-amd649517e166151f202814d5a8856ab038ec53f43d4a.tar.zst.sha256sum`

There is a missing `-` between amd64 and the commit hash. See the linux example below:
`rke2-images.linux-amd64-00010ba327b51b19651caa93c6e4bfddf7832b64.tar.zst.sha256sum` 

source for the naming structure of tarballs is https://github.com/rancher/rke2/blob/master/scripts/build-upload#L57

We currently publish three different image tarballs for each windows OS: 1809, 2004, and 20H2.

![image](https://user-images.githubusercontent.com/55704795/135321547-b12996ab-fbbb-447a-bc84-66baeb48e454.png)

Ex. of what the filenames should look like once fixed
```
rke2-images.windows-amd64-9517e166151f202814d5a8856ab038ec53f43d4a.tar.zst.sha256sum
rke2-images.windows-amd64-9517e166151f202814d5a8856ab038ec53f43d4a.tar.zst.sha256sum
rke2-images.windows-amd64-9517e166151f202814d5a8856ab038ec53f43d4a.tar.zst.sha256sum
```

steps to fix these bugs:
1) We need to add a step in the install.ps1 script that will grab the build version from the host and then insert it into the URL
2) the missing dash needs added when looking for a tarball checksum
3) windows artifacts need to be published to https://storage.googleapis.com/rke2-ci-builds

**Comment by rosskirkpat** [comment]
I have addressed numbers 1 and 2 in https://github.com/rancher/rke2/pull/1872

**Comment by rancher-max** [comment]
This was validated using releases that are already out for 1 and 2 and commit `12e640bd` for the 3rd issue related to this. Artifacts are now correctly published and available, as can be seen at https://storage.googleapis.com/rke2-ci-builds. 

https://github.com/rancher/rke2/issues/2125 was created to address remaining issue with installing via commit.
