### ISSUE TITLE
Windows artifacts are not published to https://storage.googleapis.com/rke2-ci-builds

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1891]
Found while investigating https://github.com/rancher/rke2/issues/1890

Windows CI artifacts are not currently published to https://storage.googleapis.com/rke2-ci-builds

This blocks any and all testing of specific commits, including QA and dev-validate tasks. 

The build uploads are completed with the following [script](https://github.com/rancher/rke2/blob/master/scripts/build-upload) during CI.

This is due to the slightly different naming structure of Windows tarballs when they are [packaged](https://github.com/rancher/rke2/blob/master/scripts/package-windows-images#L10-L33) compared to Linux. When the build-upload script is [called](https://github.com/rancher/rke2/blob/master/scripts/dev-runtime-image#L19) for Windows, it is not taking into account the different naming structure.

L19 should instead look like:
`./scripts/build-upload dist/artifacts/${PROG}.windows-${ARCH}.tar.gz build/images/${PROG}-images.windows-${BUILD_VERSION}-${ARCH}.tar.zst ${COMMIT}`

We will have to evaluate how best to expose the Windows build version for use here.

**Comment by briandowns** [comment]
Issue resolved and confirmed by @rosskirkpat
