### ISSUE TITLE
Would like a way to redefine the unit for cpu so that in dev, 500m will means less cpu

### ISSUE THREAD

**Issue by SebTardif** [rancher/rke2#1893]
Hi,

I would like a way to redefine the unit for cpu, so that instead of updating dozen of applications limit/request for cpu, I can tell in dev to rke2 a new definition for the unit of cpu.

**Comment by brandond** [comment]
Are you trying to change the requests for all the components, or the unit itself?

**Comment by SebTardif** [comment]
I want to change the definition of the cpu unit so that it apply to all the components, the entire cluster.

**Comment by brandond** [comment]
That's not possible. 1 CPU is 1 CPU or 1000m CPU. Kubernetes does not allow fudging request units.

**Comment by dweomer** [comment]
@SebTardif it is possible that we are missing something (lost in translation maybe?). Please see [Managing Resources for Containers - Meaning of CPU](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu):

> Limits and requests for CPU resources are measured in cpu units. One cpu, in Kubernetes, is equivalent to 1 vCPU/Core for cloud providers and 1 hyperthread on bare-metal Intel processors.
> 
> Fractional requests are allowed. A Container with spec.containers[].resources.requests.cpu of 0.5 is guaranteed half as much CPU as one that asks for 1 CPU. The expression 0.1 is equivalent to the expression 100m, which can be read as "one hundred millicpu". Some people say "one hundred millicores", and this is understood to mean the same thing. A request with a decimal point, like 0.1, is converted to 100m by the API, and precision finer than 1m is not allowed. For this reason, the form 100m might be preferred.
> 
> CPU is always requested as an absolute quantity, never as a relative quantity; 0.1 is the same amount of CPU on a single-core, dual-core, or 48-core machine.

Or is it that you would like to change the CPU resource limit for every container in every pod in your cluster? There is probably a mutating webhook for that somewhere. Looks like OPA used to support ResourceQuotas via mutating webhook but my google is coming up 404s.

See also https://kubernetes.io/docs/concepts/policy/resource-quotas/

**Comment by SebTardif** [comment]
@dweomer If I cannot get the OS or Kubernetes to change the unit, I agree that something like a mutating webhook is my next best option.

My original use case is popular, in dev you may not want to use, so pay, for the same speed than in prod. Also, the API doesn't allow right now to have deterministic speed. The unit is relative to core not to the speed of a cpu. Even for a prod configuration, I may want to change the ratio if I move to a faster or slower core.
