### ISSUE TITLE
Missing packaging for cilium image bumps in v1.21.5

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1894]
This causes airgap install to fail with `Back-off pulling image "rancher/mirrored-cilium-cilium:v1.10.4@sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d"` since the image version present is: `v1.9.8`.

It looks like https://github.com/rancher/rke2/pull/1812 bumped the chart but not the images, so just a missing backport. 

I saw this using v1.21.5+rke2r1 with system-default-registry method, using `rke2-images-all.linux-amd64.txt` for my image file.

**Comment by cwayne18** [comment]
@dereknola we should plan on getting an R2 with this fix out this week, can you please lead this effort? cc @rancher-max

**Comment by rancher-max** [comment]
@cwayne18 In case we want to direct people to a workaround instead of an R2, it is just one step for people using a private registry (which should be most users in order to deploy workloads in the cluster post-install): 
1. Add the missing images to the registry manually

The more complicated bit is users using tarball install who may have a requirement not to have any system images in their private registries, in which case this would not work.

**Comment by rancher-max** [comment]
Validated the images are present in packaging on v1.21.5-rc1+rke2r2. Will perform a few different types of airgap installs before closing

**Comment by rancher-max** [comment]
This failed during an airgap install due to the init container looking for a specific digest that wasn't there:
```
  Warning  Failed   81s (x30 over 5h1m)      kubelet  (combined from similar events): Failed to pull image "rancher/mirrored-cilium-cilium:v1.10.4@sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/mirrored-cilium-cilium@sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d": failed to resolve reference "docker.io/rancher/mirrored-cilium-cilium@sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d": failed to do request: Head "https://registry-1.docker.io/v2/rancher/mirrored-cilium-cilium/manifests/sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d": dial tcp 54.161.109.204:443: i/o timeout
```

```
Init Containers:
   mount-cgroup:
    Image:      rancher/mirrored-cilium-cilium:v1.10.4@sha256:7d354052ccf2a7445101d78cebd14444c7c40129ce7889f2f04b89374dbf8a1d
```

**Comment by rancher-max** [comment]
Validated this is working in airgap installs on v1.21.5-rc3+rke2r2
