### ISSUE TITLE
Node stuck at deletion due to finalizer - cisnetworkpolicy-node

### ISSUE THREAD

**Issue by mattmattox** [rancher/rke2#1895]
**Environmental Info:**
RKE2 Version: v1.21.5+rke2r1

Node(s) CPU architecture, OS, and Version: AMD64 Ubuntu 20.04
Linux a1ubrke2mgmtp01 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 control-plane,etcd,master nodes with 5 worker.
Note: This cluster was hardened using the cis-1.5 profile.

**Describe the bug:**
Deletion of a node is stuck due to the presence of the finalizer `wrangler.cattle.io/cisnetworkpolicy-node`
Very similar to https://github.com/rancher/rke2/issues/1568

**Steps To Reproduce:**

- Installed RKE2 with the following config.
```
server: https://.....:9345
token: .....
profile: "cis-1.5"
tls-san:
  - ....
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
```
- Join worker node
- Delete worker node using `kubectl delete node`
- The following finalizer will be left behind.
```
  finalizers:
  - wrangler.cattle.io/cisnetworkpolicy-node
```
 
**Expected behavior:**
For the node to be deleted

**Actual behavior:**
The node will be left in the cluster in a `NotReady` status.

**Additional context / logs:**

**Comment by mattmattox** [comment]
Workaround:
`kubectl edit nodes NodeName`
Delete finalizer line.

**Comment by brandond** [comment]
Can you provide rke2-server logs from the remaining nodes in the cluster from around the time window in which you deleted this node?
