### ISSUE TITLE
Enhance RKE2 Documentation with full config.yaml examples

### ISSUE THREAD

**Issue by jtravee** [rancher/rke2#1901]
From Rancher/docs: https://github.com/rancher/docs/issues/3550

**Comment by brandond** [comment]
From https://github.com/rancher/docs/issues/3550#issuecomment-932489266:
>There is no difference between the CLI flags and config.yaml keys; the CLI flag help and comments are the exact same as the config.yaml help.
>
>There is no schema for the config file, it is just a map[string]interface{}. Internally the config YAML is ranged over, and keys/values merged into the flags provided via the CLI, at which point the standard CLI parser kicks in to actually operate on the flags.
