### ISSUE TITLE
HTTP 403 when accessing kube-controller-manager or kube-scheduler /metrics

### ISSUE THREAD

**Issue by susenguyen** [rancher/rke2#1903]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
go version go1.16.4b7

Node(s) CPU architecture, OS, and Version: 

Linux XXXXXX 5.3.18-24.52-default #1 SMP Tue Mar 2 13:15:25 UTC 2021 (c35b124) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 Masters
6 Workers

**Describe the bug:**

When trying to access the /metrics endpoint of the kube-controller-manager (on tcp/10257) or kube-scheduler (on tcp/10259, we get an HTTP 403 ("forbidden: User \"system:anonymous\" cannot get path \"/metrics\""). The same query against the kube-apiserver (tcp/6443) or kubelet (tcp/10250) is working fine and returning the metrics.

**Steps To Reproduce:**

- Installed RKE2 (private data redacted): 
tls-san: ['XXXXX']
data-dir: /var/lib/rancher/rke2
cluster-cidr: XXXXXXX
service-cidr: XXXXXXX
cluster-dns: XXXXXXX
cluster-domain: cluster.local
token: XXXXXX
write-kubeconfig: /root/.kube/config
write-kubeconfig-mode: 600
kube-apiserver-arg:
- enable-admission-plugins=NodeRestriction,PodSecurityPolicy,PodNodeSelector
- admission-control-config-file=/etc/rancher/rke2/admission-control.yaml
kube-scheduler-arg: ['bind-address=0.0.0.0', 'secure-port=10259']
kube-controller-manager-arg: ['bind-address=0.0.0.0', 'secure-port=10257']
etcd-expose-metrics: false
etcd-snapshot-schedule-cron: 0 */12 * * *
etcd-snapshot-retention: 5
etcd-snapshot-dir: /var/lib/rancher/rke2/db/snapshots
disable: rke2-ingress-nginx
node-name: XXXXXXX
node-taint: ['CriticalAddonsOnly=true:NoExecute']
node-label:
- XXXXXXX
- XXXXXXX
kubelet-arg:
- serialize-image-pulls=true
system-default-registry: XXXXXXX
profile: cis-1.5
audit-policy-file: /etc/rancher/rke2/audit-policy.yaml

**Clusterrole**
rke-2:~ # kubectl describe clusterrole cluster-prometheus
Name:                          cluster-prometheus
Labels:                        <none>
Annotations:                   PolicyRule:
  Resources                    Non-Resource URLs  Resource Names  Verbs
  endpoints                    []                 []              [get list watch]
  nodes/metrics                []                 []              [get list watch]
  nodes/proxy                  []                 []              [get list watch]
  nodes                        []                 []              [get list watch]
  pods                         []                 []              [get list watch]
  services                     []                 []              [get list watch]
  ingresses.extensions         []                 []              [get list watch]
  ingresses.networking.k8s.io  []                 []              [get list watch]
                               [/metrics]         []              [get]

**Clusterrolebinding**
rke-2:~ # kubectl describe clusterrolebindings.rbac.authorization.k8s.io cluster-prometheus
Name:         cluster-prometheus
Labels:       <none>
Annotations:  Role:
  Kind:       ClusterRole
  Name:       cluster-prometheus
Subjects:
  Kind            Name                Namespace
  ServiceAccount  cluster-prometheus  monitoring

**Test**
TOKEN is the cluster-prometheus service account's
SERVER is one of the 3 master nodes IP address or FQDN
PORT varies depending on the service we are testing:
- 10257 for kube-controller-manager
- 10259 for kube-scheduler
- 10250 for kubelet
- 6443 for kube-apiserver

curl -k -H "Authorization: bearer ${TOKEN}"  https://${SERVER}:${PORT}/metrics

**Expected behavior:**

The list of metrics for the given component

**Actual behavior:**

For kube-controller and kube-scheduler, we get the following:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
  },
  "code": 403
}

For the kube-apiserver and kubelet, we get the expected behavior.
**Additional context / logs:**

**Comment by brandond** [comment]
Your curl request shows that the request is being handled as anonymous. Are you sure you're passing the service account credentials properly?

**Comment by susenguyen** [comment]
Yes, I am using the token from the prometheus-cluster service account shown above.
And I get a proper response from the apiserver and kubelet using the exact same token.

**Comment by susenguyen** [comment]
We are not using the insecure port (tcp/10252) but the HTTPS-enabled port as per the config.yaml options:
   kube-controller-manager-arg: ['bind-address=0.0.0.0', 'secure-port=10257']

And the service is bound to 0.0.0.0 (all interfaces). I get the same result when curling https://localhost:10257/metrics.

**Comment by brandond** [comment]
Ah. If you're customizing the configuration to that extent you would probably also want to set `--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics` (add metrics to the default list) or alternately go through the work of setting up all the RBAC and CLI flags related to `--authentication-kubeconfig` so that the controllers are able to validate the tokens you're passing. We're going to do that for you on 1.22 but those changes probably will not be backported to older releases.

**Comment by brandond** [comment]
They can, as described above:
> Go through the work of setting up all the RBAC and CLI flags related to --authentication-kubeconfig so that the controllers are able to validate the tokens you're passing

1.22 will do this out of the box, but we're not (at the moment) planning on backporting these changes to 1.21 or earlier:
https://github.com/k3s-io/k3s/commit/dc556cbb727a86c5b11811cf5c0b3fb2780b3ae8#diff-e0ce1a7f3f76d7bfda0ffdae6e0226aa63b3009c4c4a770c321876aecad0a6c1
