### ISSUE TITLE
Automation to bulk-update and tag all these repos

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1904]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when... we need to manually update the base image versions every time a new golang version or hardneed-build-base image is released as explained in https://github.com/rancher/rke2/issues/1892

**Describe the solution you'd like**

An automated bot which creates the PRs automatically as part of our release process

**Describe alternatives you've considered**

Doing it manually and it sucks because we waste precious time

**Comment by briandowns** [comment]
This has been completed and now lives in the ECM Distro Tools.
