### ISSUE TITLE
How to increase pod capacity?

### ISSUE THREAD

**Issue by turowicz** [rancher/rke2#1914]
Currently the default is 110 pods maximum. How can I increase that? 

Apologies for the question but there is very little documentation on RKE2 configuration.

![image](https://user-images.githubusercontent.com/1055391/136024631-55994519-71bb-4d7d-9664-93e5b5963a12.png)

**Comment by brandond** [comment]
This isn't RKE2 specific, see: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

> -max-pods int32     Default: 110
>  Number of Pods that can run on this Kubelet.

Note that if you increase this you probably also need to change the [kube-controller-manager ](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)`--node-cidr-mask-size` to make more pod IP addresses available to each node.

You can pass through arguments to Kubernetes components via the RKE2 `--kubelet-arg`, `--kube-controller-manager-arg` flags: https://docs.rke2.io/install/install_options/server_config/

**Comment by turowicz** [comment]
Thanks @brandond

**Comment by turowicz** [comment]
@brandond can this be passed in the yaml config?

**Comment by turowicz** [comment]
```
kubelet-arg:
  - max-pods: 300
```
?

**Comment by turowicz** [comment]
Ok it goes like this:

```
kubelet-arg: "--max-pods=200"
```

**Comment by brandond** [comment]
You still need to increase the CIDR mask or you'll run out of pod addresses during churn. The default CIDR mask only has space for 253 pods, and you should allow some space for pods in creating/terminating state.

**Comment by turowicz** [comment]
for k3s 

```
kubelet-arg: "max-pods=200"
```
