### ISSUE TITLE
No pod CPU / Memory usage in Prometheus

### ISSUE THREAD

**Issue by turowicz** [rancher/rke2#1934]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.5+rke2r1 (881084666b8134df6c3086d4710d458c753f8c38)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux surveily-pilot-01 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node server.

**Describe the bug:**
No pod CPU / Memory usage in Prometheus after deploying with the following:
```
helm upgrade -i -n diagnostics --version 19.0.2 --create-namespace --wait --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheusOperator.admissionWebhooks.enabled=false --set prometheusOperator.admissionWebhooks.patch.enabled=false --set prometheusOperator.tlsProxy.enabled=false --set prometheusOperator.tls.enabled=false prometheus prometheus-community/kube-prometheus-stack
```

**Steps To Reproduce:**
- Installed RKE2
- Deployed Prometheus
- Don't see any metrics for pods

**Expected behavior:**
I expect to see CPU / Memory usage for pods in Prometheus

**Actual behavior:**
I don't see CPU / Memory usage for pods in Prometheus

**Additional context / logs:**
I like sandwitches.

**Comment by turowicz** [comment]
@brandond can you send me the link to the rancher monitoring chart?

**Comment by turowicz** [comment]
I prefer not having to go thorugh Rancher just to install monitoring chart

**Comment by turowicz** [comment]
@brandond aren't you interested in getting to the bottom of this? Seems like a basic feature is not working. We can do video call if you want so I can show you how to reproduce this.

**Comment by blaz-dev** [comment]
Have there been any updates to this? 

My test RKE2 cluster also fails to display any metrics in **Lens** IDE, it just says "Metrics not available at this moment". Meanwhile `kubectl top` seems to work fine so it can't be metrics-server at fault?
```
root@a1:~# kubectl top nodes
NAME   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
a1     213m         10%    2050Mi          51%
a2     176m         8%     1586Mi          40%
a3     180m         9%     1579Mi          40%
w1     42m          2%     778Mi           19%
```
Prometheus installed using helm and version 15.14.0 chart from `helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`

RKE2 version:
```
root@a1:~# rke2 --version
rke2 version v1.24.4+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
```
This is all there is to **prometheus-server** pod logs in test RKE2 cluster after fresh install of Prometheus:
```
ts=2022-10-03T10:36:15.611Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.36.2, branch=HEAD, revision=d7e7b8e04b5ecdc1dd153534ba376a622b72741b)"
ts=2022-10-03T10:36:15.611Z caller=main.go:540 level=info build_context="(go=go1.18.3, user=root@f051ce0d6050, date=20220620-13:21:35)"
ts=2022-10-03T10:36:15.612Z caller=main.go:541 level=info host_details="(Linux 4.15.0-193-generic #204-Ubuntu SMP Fri Aug 26 19:20:21 UTC 2022 x86_64 prometheus-server-85696cffd4-mnpw9 (none))"
ts=2022-10-03T10:36:15.612Z caller=main.go:542 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2022-10-03T10:36:15.612Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2022-10-03T10:36:15.624Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2022-10-03T10:36:15.626Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2022-10-03T10:36:15.631Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2022-10-03T10:36:15.652Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2022-10-03T10:36:15.656Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=6.263µs
ts=2022-10-03T10:36:15.658Z caller=main.go:996 level=info msg="TSDB started"
ts=2022-10-03T10:36:15.658Z caller=main.go:1177 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
ts=2022-10-03T10:36:15.665Z caller=kubernetes.go:325 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-10-03T10:36:15.665Z caller=kubernetes.go:325 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-10-03T10:36:15.666Z caller=kubernetes.go:325 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-10-03T10:36:15.666Z caller=kubernetes.go:325 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-10-03T10:36:15.666Z caller=main.go:1214 level=info msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml totalDuration=7.949437ms db_storage=1.273µs remote_storage=978ns web_handler=420ns query_engine=798ns scrape=254.42µs scrape_sd=1.428235ms notify=1.094µs notify_sd=2.209µs rules=266.079µs tracing=2.941µs
ts=2022-10-03T10:36:15.666Z caller=main.go:957 level=info msg="Server is ready to receive web requests."
ts=2022-10-03T10:36:15.667Z caller=manager.go:937 level=info component="rule manager" msg="Starting rule manager..."
```

Any hints on where to look in order to resolve this issue and get cluster metrics (CPU usage, memory usage, pod statistics etc.) displayed normally in **Lens** as they do in RKE and AWS EKS clusters would be most welcome.

**Comment by blaz-dev** [comment]
Replying to myself for anyone who hits this same issue - metrics are now showing correctly for my RKE2 cluster after installing the latest version of OpenLens (6.1.2).

My conclusion is it was old Lens version (5.4.something) that was to blame for metrics not showing up in v1.24.4+rke2r1 cluster while they worked correctly in RKE and EKS clusters running slightly older versions of Kubernetes.
