### ISSUE TITLE
Improve Windows uninstall script checks for running services

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1935]
for rke2:
https://github.com/rancher/system-agent-installer-rke2/blob/main/package/run.ps1#L87-L95

for wins:
https://github.com/phillipsj/wins/blob/feature/rancher-install-script/rancher-installer.ps1#L474-L490

**Comment by rancher-max** [comment]
See https://github.com/rancher/rke2/issues/1948#issuecomment-942813557 for validation as this is checking and working now as expected.
