### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by mattmattox** [rancher/rke2#1946]
**Is your feature request related to a problem? Please describe.**
When trying to join an ARM64 (Pi 4 8GB) to an RKE2 cluster you get the following error due to aarch64 not being a supported architecture. k3s supports ARM64 so it would be nice for RKE2 to also support ARM64 too.
`[ERROR]  unsupported architecture aarch64`

**Describe the solution you'd like**
Add an Experimental ARM64 builds for people that want to test.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by turowicz** [comment]
👍🏻

**Comment by mattmattox** [comment]
Please do not close this issue

**Comment by mattmattox** [comment]
Please do not close. ARM in the datacenter is becoming more common with things like AWS Graviton.

**Comment by briandowns** [comment]
This is on our roadmap still, with the limitation on the compiler side. Hopefully will have it sorted very soon actually.

**Comment by brandond** [comment]
Tracking in https://github.com/rancher/rke2/issues/817

**Comment by prichardsondev** [comment]
Still not working ubuntu 22 on RPI 4
root@raspberryk8-rancher:/etc/rancher/rke2# curl -sfL https://get.rancher.io | sh -
[ERROR]  unsupported architecture aarch64

**Comment by simonflood** [comment]
> Still not working ubuntu 22 on RPI 4 root@raspberryk8-rancher:/etc/rancher/rke2# curl -sfL https://get.rancher.io | sh - [ERROR] unsupported architecture aarch64

The above is the RancherD installation method which was an experimental feature available as part of Rancher v2.5.4 through v2.5.10 but is now deprecated and not available for recent releases
