### ISSUE TITLE
Update vSphere charts to 100.0.1

### ISSUE THREAD

**Issue by ron1** [rancher/rke2#1974]
Update vSphere cpi and csi charts to 100.0.1.

**Comment by brandond** [comment]
Are there any changes from the current version? We're currently waiting on upstream to get 1.22 support fixed (https://github.com/kubernetes/cloud-provider-vsphere/issues/504) which appears to have not moved forward in the last month and a half.

**Comment by ron1** [comment]
I am most interested in testing the upgrade from 100.0.0 to 100.0.1 as part of an rke2 upgrade. This can wait if vsphere cpi/csi 1.22 support is coming soon.
