### ISSUE TITLE
Unable to join server in a private network

### ISSUE THREAD

**Issue by giovannicandido** [rancher/rke2#1992]
**Environmental Info:**
RKE2 Version: rke2 version v1.21.5+rke2r2

Node(s) CPU architecture, OS, and Version: 

Linux  5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86
_64 x86_64 GNU/Linux
Cluster Configuration:

3 servers in HA mode

**Describe the bug:**

In a private network, secondary nodes are unable to connect to the first master.
The private network is made with wireguard VPN and I can ping all the nodes.
First node is up and can be see on kubectl get nodes.
Secondary nodes fall with the message in the logs:

```
ct 20 20:26:05 pterodactilo.srv.kugelbit.com rke2[5085]: {"level":"warn","ts":"2021-10-20T20:26:05.195-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = Dea
dlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Oct 20 20:26:05 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:05-04:00" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Oct 20 20:26:06 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:06-04:00" level=info msg="Cluster-Http-Server 2021/10/20 20:26:06 http: TLS handshake error from 127.0.0.1:52204: remote error: tls: bad certificate"
Oct 20 20:26:06 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:06-04:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Oct 20 20:26:06 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:06-04:00" level=warning msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true\":
dial tcp 127.0.0.1:6443: connect: connection refused"
Oct 20 20:26:10 pterodactilo.srv.kugelbit.com rke2[5085]: {"level":"warn","ts":"2021-10-20T20:26:10.509-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = Dea
dlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Oct 20 20:26:10 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:10-04:00" level=info msg="Failed to test data store connection: context deadline exceeded"
Oct 20 20:26:11 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:11-04:00" level=info msg="Cluster-Http-Server 2021/10/20 20:26:11 http: TLS handshake error from 127.0.0.1:52240: remote error: tls: bad certificate"
Oct 20 20:26:11 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:11-04:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Oct 20 20:26:11 pterodactilo.srv.kugelbit.com rke2[5085]: time="2021-10-20T20:26:11-04:00" level=warning msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true\":
dial tcp 127.0.0.1:6443: connect: connection refused"

```

Config on server:

```
token: xxxxxx
tls-san:
  - k8s1.internal.kugelbit.com
  - k8s1.external.kugelbit.com
  - triceratops.srv.kugelbit.com
  - pterodactyl.srv.kugelbit.com
  - tirannosaurus.srv.kugelbit.com
  - 10.8.0.1
  - 10.8.0.2
  - 10.8.0.3
advertise-address: 10.8.0.1
node-ip: 10.8.0.1
node-external-ip: 66.94.105.32
```

Config on client:

```
server: https://k8s1.internal.kugelbit.com:9345
token: xxxxxx
tls-san:
  - k8s1.internal.kugelbit.com
  - k8s1.external.kugelbit.com
  - triceratops.srv.kugelbit.com
  - pterodactyl.srv.kugelbit.com
  - tirannosaurus.srv.kugelbit.com
  - 10.8.0.1
  - 10.8.0.2
  - 10.8.0.3
advertise-address: 10.8.0.2
node-ip: 10.8.0.2
node-external-ip: 66.94.105.33

```

ufw is enabled in all nodes and only allow traffic from the internal vpn.

**Steps To Reproduce:**

- Installed RKE2: 

- Install rke2 with the config below and in server mode

**Expected behavior:**

The secondary nodes should join the cluster

**Actual behavior:**

the join is not made

**Additional context / logs:**

**Comment by brandond** [comment]
If you set `node-external-ip` on a servers, then ports 6443 and 9345 on that IP need to be accessible from all nodes in the cluster, including the node itself. This may require additional firewall rules and/or enabling hairpin/u-turn NAT on your firewall or NAT device.

**Comment by giovannicandido** [comment]
Hum.. strange I try several things, but when I open the port 6443 and 9345 in both server 1 and server 2 the join happen.
But I don't want to open that ports though the external interface, I want then to communicate in the private range, if the ip of the server change for any reason the cluster is broken.
I was think that the advertise ip address has the key to do that, but I'm wrong because I set that in both nodes.

**Comment by giovannicandido** [comment]
In other words it do not respect the "server:" config it keeps trying to connect through the external ip address.

I will keep testing

**Comment by giovannicandido** [comment]
Update: It only needs port 6443 open in all servers to join. 
I'm facing other problems with the VPN, kube-scheduler is not reaching the kubelet api in all servers with erros like;

```
Get "https://10.8.0.2:10250/containerLogs/kube-system/kube-scheduler-pterodactilo.srv.kugelbit.com/kube-scheduler": dial tcp 10.8.0.2:10250: connect: connection refused
```
Its also in pending state trying to lead elect:

```
 deprecated_insecure_serving.go:54] Serving healthz insecurely on 127.0.0.1:10251
I1021 21:51:39.550356       1 leaderelection.go:243] attempting to acquire leader lease kube-system/kube-scheduler..
```

This is causing instability on the servers with `kubectl get nodes` eventually showing nodes in the **NoReady** state.

`kubectl describe nodes` shows on some nodes 
 
```
Normal   Starting                 50m                kube-proxy  Starting kube-proxy. 
```

Probably something to do with the VPN itself, I'm not sure how kubelet implements its election, but maybe its trying a broadcast in the VPN and the VPN is not leting that packages flow. I will keep testing

Etcd seens is working fine, but I`m getting multiple warning messages (requests with more than 100ms) 

I will keep testing, deploying some apps to see and will also try another VPN solution that is on a layer 2 (wireguard is layer 3)
