### ISSUE TITLE
strict mode bug fix for install.ps1

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1995]
#### Proposed Changes ####

- fix missing declaration of `$suffix` in install.ps1
- remove the requirement to confirm that the user wants to stop processes/services when running rke2-uninstall.ps1
- simplify logic in rke2-uninstall.ps1
- address use case: if the container feature is not installed, we would previously call `Write-FatalLog` and then reference `$suffix` while it hasn't been set

This was not caught previously due to an unexpected test case where the script would exit prior to `$suffix` being set while `$suffix` is called in `Write-Fatallog` func

**Environmental Info:**
RKE2 Version: v1.21.5

**Comment by brandond** [comment]
Mobile mistap, sorry :(
