### ISSUE TITLE
[docs] Document tcp/5473 port requirement for Typha

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#1996]
while deploying rke2 through terraform, this error message was seen on a calico-node pod on a linux worker 

> 2021-10-21 03:50:19.991 [ERROR][62] felix/daemon.go 491: Failed to connect to Typha. Retrying... error=dial tcp 172.32.24.60:5473: i/o timeout

The networking setup was:
all nodes ran on the same VPC with a SG that only allowed traffic based on the latest port requirements from rke2 docs
linux cp/etcd on subnet a
linux worker on subnet b

the cp/etcd nodes did not report the tcp timeout.

Once I added a tcp/5473 rule to the security group, the calico-node pod error resolved.

port 5473 is not documented as a required port in the rke2 [networking docs](https://docs.rke2.io/install/requirements/#networking)

**Comment by jtravee** [comment]
@manuelbuil, could you review this and advise what the ports should be on each CNI that we support? I can then update in the inbound rules table- https://docs.rke2.io/install/requirements/#networking.

**Comment by manuelbuil** [comment]
Sorry for the delayed answer, I missed this :(. Here it goes:

For Cilium we need:
- 8472/udp (VXLAN)
- 4240/tcp (health-checks)
- ICMP 8/0 (health-cheks too)

For Calico:
- 179/tcp (if using BGP mode)
- 4789/udp (if using VXLAN mode)
- 5473/tcp (typha)

For Canal:
- 4789/udp (VXLAN mode)
- 51820/udp (Wireguard mode for ipv4)
- 51821/udp (Wireguard mode for ipv6 (dual-stack))
