### ISSUE TITLE
Unable to set flannel.backend = wireguard

### ISSUE THREAD

**Issue by flokli** [rancher/rke2#1997]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.21.5+rke2r2 (9e4acdc6018ae74c36523c99af25ab861f3884da)
go version go1.16.6b7
```

Node(s) CPU architecture, OS, and Version: 
```
Linux controlplane-0 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:
3 servers, 3 agents.

**Describe the bug:**
Coming from k3s, and using the `--flannel-backend wireguard` there, I wanted to configure the same in RKE2. I dropped the following file into `root@controlplane-0:~# cat /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml` (after looking into https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/values.yaml)

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
  spec:
    valuesContent: |-
      flannel:
        backend: wireguard
```

I see the helm chart getting installed. However, pods are crashlooping, and the CNI fails to initialize. If I look at the logs of the `rke2-canal-*` pods in the `kube-system` namespace, I see the following:

```
I1020 23:55:24.384737       1 main.go:518] Determining IP address of default interface
I1020 23:55:24.385595       1 main.go:531] Using interface with name eth0 and address 49.12.236.12
I1020 23:55:24.385631       1 main.go:548] Defaulting external address to interface address (49.12.236.12)
W1020 23:55:24.385666       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1020 23:55:24.423386       1 kube.go:119] Waiting 10m0s for node controller to sync
I1020 23:55:24.424181       1 kube.go:306] Starting kube subnet manager
I1020 23:55:25.424434       1 kube.go:126] Node controller sync successful
I1020 23:55:25.424613       1 main.go:246] Created subnet manager: Kubernetes Subnet Manager - controlplane-0
I1020 23:55:25.425121       1 main.go:249] Installing signal handlers
I1020 23:55:25.425853       1 main.go:390] Found network config - Backend type: wireguard
E1020 23:55:25.426106       1 main.go:283] Error fetching backend: unknown backend type: wireguard
I1020 23:55:25.426238       1 main.go:370] Stopping shutdownHandler...
```

So for some reason, wireguard backend support isn't compiled in?

**Steps To Reproduce:**
Install RKE, drop above manifest, observe the same error

**Expected behavior:**
I'd expect to be able to configure flannel with wireguard backend, or if that's not possible, this at least clearly documented somewhere.

**Comment by flokli** [comment]
> Oh right, our flannel support is just a shortcut for a predefined extension config using shell commands.
> 
> @flokli you might see if you can replicate this manually: https://github.com/k3s-io/k3s/blob/a18c2efb4c246cd6dbc37864efcabaadf0371345/pkg/agent/flannel/setup.go#L62

Probably not easily doable only via helm chart config at least.

> Yes, there is an old PR that adds it as backend but it seems nobody cared. I can take a look at it:
> [flannel-io/flannel#1230](https://github.com/flannel-io/flannel/pull/1230)

This one would also be nice, as it removes the need to manually install `wireguard-tools`, due to `wgctrl` using netlink under the hood (instead of shelling out to `wg` like the extension one).

**Comment by flokli** [comment]
Thanks!

**Comment by dgiebert** [comment]
Thank you for reviewing and merging the PR, is there a timeline when this will be integrated and can be used?

**Comment by manuelbuil** [comment]
> Thank you for reviewing and merging the PR, is there a timeline when this will be integrated and can be used?

We need flannel to create a new release first

**Comment by flokli** [comment]
unstale

**Comment by dgiebert** [comment]
The issue can be closed since it is documented and can be used.

https://docs.rke2.io/install/network_options#install-a-cni-plugin
