### ISSUE TITLE
Rancher Integration - PREVENT upgrades of rancherd from the rancher UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#201]
~Once `rancherd` cli is ready, we need to support upgrades of rancherd downstream clusters in ECM.~

~We believe that out of the gate, a rancherd cluster is likely to be recognized as an RKE2 cluster today - it should be recognized as a "Rancherd" cluster and support upgrades. We suspect this requires work similar to what was done to support RKE2 upgrades.~

We believe that out of the gate, a rancherd cluster is likely to be recognized as an RKE2 cluster today - it should be recognized as a "Rancherd" cluster and NOT be allowed to upgrade via the rancher UI. Upgrades will be manual

**Comment by MonzElmasry** [comment]
waiting on https://github.com/rancher/rancher/issues/29051

**Comment by davidnuzik** [comment]
https://github.com/rancher/rancher/issues/28651 appears to have been pushed out to Rancher 2.5.1

**Comment by ShylajaDevadiga** [comment]
Validated using rancher master build, commit id: 4ac3a87d74e987aa35896e0a91e757311b404309
Upgrade option is not available as expected.
Snippet from cluster API
```
"name": "local",
"nodeCount": 1,
"nodeVersion": 0,
"provider": "rke2",
"requested": {
"cpu": "0",
"memory": "0",
"pods": "0"
},

created": "2020-09-25T23:29:48Z",
"createdTS": 1601076588000,
"creatorId": "user-pk4s2",
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"desiredAuthImage": "",
"dockerRootDir": "/var/lib/docker",
"driver": "rancherd",
```
![image](https://user-images.githubusercontent.com/56045581/94326929-77c9a800-ff5c-11ea-8d00-294d699a985b.png)

![image](https://user-images.githubusercontent.com/56045581/94326935-844e0080-ff5c-11ea-9da9-450104bf9deb.png)

![image](https://user-images.githubusercontent.com/56045581/94327009-1c4bea00-ff5d-11ea-8123-260acbfcc3b5.png)
