### ISSUE TITLE
Update peer address when running cluster-reset 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#2015]
**Environmental Info:**
rke2 Version: master/v1.21/v1.20/v1.19

Cluster Configuration:
1 node cluster

**Describe the bug:**

When user changes the IP of the node and try cluster-reset to restore the state of the cluster, etcd complains with the following error:
```
INFO[0103] Failed to test data store connection: this server is a not a member of the etcd cluster. Found [ubuntu-focal-95aeb14b=https://10.0.0.100:2380], expect: ubuntu-focal-95aeb14b=10.0.0.101
```
**Steps To Reproduce:**
- Install rke2
- change the IP of the node
- restart rke2 and run cluster-reset

**Expected behavior:**
The cluster should run normally after cluster-reset

**Actual behavior:**
- the cluster hangs when the user run cluster-reset

**Comment by ShylajaDevadiga** [comment]
Validated following cni's  using v1.22.3-rc1+rke2r1, Cluster was functional after cluster-reset was run with ip change
```
cni: canal(default)
cni: calico
cni: multus,canal
cni: cilium
```
