### ISSUE TITLE
Need rancher-vsphere and harvester charts to work with 1.22

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2022]
From https://github.com/rancher/rke2/issues/1892, we still need to update vsphere and harvester as they will currently be broken on 1.22.
For rancher-vsphere, this is currently blocked by: https://github.com/rancher/rancher/issues/33848

**Comment by braunsonm** [comment]
Any update on this? The vSphere CSI has supported 1.22 for awhile now it seems.

**Comment by brandond** [comment]
This will likely happen in sync with Rancher 2.6.4

**Comment by caroline-suse-rancher** [comment]
Closing this issue since 1.22 is now EOL
