### ISSUE TITLE
 RKE2 does not ensure that certificates on disk match values from from cluster bootstrap data 

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2025]
Update K3s to fix **RKE2 does not ensure that certificates on disk match values from from cluster bootstrap data**:
* https://github.com/k3s-io/k3s/issues/4309

**Comment by rancher-max** [comment]
#### Validated on master branch commit `a471ffe97934428b19735349cb1eb25023a22f52`

All scenarios in test plan pass, which includes removing a file in tls directory, modifying a file, removing the entire directory, and bringing up all servers at the same time. Note that when removing the directory and removing multiple files from the directory, the `rke2-killall.sh` script should be run BEFORE restarting rke2-server process.
