### ISSUE TITLE
[release-1.21] K3s does not ensure that certificates on disk match values from from cluster bootstrap data

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2026]
Update K3s to fix **RKE2 does not ensure that certificates on disk match values from from cluster bootstrap data**:
* https://github.com/k3s-io/k3s/issues/4311
* https://github.com/rancher/rke2/issues/2025

**Comment by rancher-max** [comment]
#### Validated on release-1.21 branch commit `d2bf179842aed662b58089d5b738c3ab7df798f4`

All scenarios in test plan pass, which includes removing a file in tls directory, modifying a file, removing the entire directory, and bringing up all servers at the same time. Note that when removing the directory and removing multiple files from the directory, the `rke2-killall.sh` script should be run BEFORE restarting rke2-server process.
