### ISSUE TITLE
[release-1.20] RKE2 does not ensure that certificates on disk match values from from cluster bootstrap data

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2027]
Update K3s to fix **RKE2 does not ensure that certificates on disk match values from from cluster bootstrap data**:
* https://github.com/k3s-io/k3s/issues/4311
* https://github.com/rancher/rke2/issues/2025

**Comment by rancher-max** [comment]
#### Validated on release-1.20 branch commit `f15b23bbac04dc159db6548e2a1679a3fece75c8`

All scenarios in test plan pass, which includes removing a file in tls directory, modifying a file, removing the entire directory, and bringing up all servers at the same time. Note that when removing the directory and removing multiple files from the directory, the `rke2-killall.sh` script should be run BEFORE restarting rke2-server process.
