### ISSUE TITLE
 rke2 server service taking long time to start

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#2071]
- OS 

RHEL 8

- Tested RKE2 1.20 on same host ```No issue```

- Uninstall RKE2

```/usr/bin/rke2-uninstall.sh```

-  Install RKE2 1.21

```
curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.21 sh -
systemctl enable rke2-server.service
mkdir -p /etc/rancher/rke2
cp config-master.yaml /etc/rancher/rke2/config.yaml
systemctl start rke2-server.service
systemctl status rke2-server.service
 more /etc/rancher/rke2/config.yaml
token: rancher-secret
write-kubeconfig-mode: "0644"
node-label:
- "region=master"
# add ips/hostname of hosts and loadbalancer
tls-san:
  - "prancherin01"
  - "172.26.30.175"
```

Not sure what causing ... No issue with RKE2 1.20

**Comment by brandond** [comment]
Can you confirm that you've got up-to-date container-selinux and rke2-selinux packages installed on this host?

**Comment by cloudcafetech** [comment]
>Can you confirm that you've got up-to-date container-selinux and rke2-selinux packages installed on this host?

```
$yum list installed | grep container-selinux
container-selinux.noarch                      2:2.167.0-1.module+el8.4.0+12646+b6fd1bdf   

$yum list installed | grep rke2-selinux
rke2-selinux.noarch                           0.8-2.el8      
```

**Comment by brandond** [comment]
This sounds a lot like https://bugzilla.redhat.com/show_bug.cgi?id=1719067 - can you confirm that all the packages on your host are up to date?

**Comment by cloudcafetech** [comment]
> can you confirm that all the packages on your host are up to date?

Please help me how to check?
