### ISSUE TITLE
Store arbitrary metadata with etcd snapshots

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#2076]
**Is your feature request related to a problem? Please describe.**
Today, when RKE2 takes `etcd` snapshots, it does not include any metadata with these snapshots. It can be desirable to take etcd snapshots and keep metadata with the snapshots.

**Describe the solution you'd like**
When an etcd snapshot is taken, there should be a method to store additional metadata into the `rke2-etcd-snapshots` configmap along with the etcd snapshot name, so as to provide association. This metadata should be able to be sourced from a ConfigMap that exists within the cluster that the snapshot is being taken of.

**Describe alternatives you've considered**
Storing metadata directly from disk rather than from ConfigMap.

**Additional context**
This is required for the Rancher v2 Provisioning Framework parity enhancement with existing RKE(1) provisioning.

This will integrate https://github.com/k3s-io/k3s/issues/4380

**Comment by Oats87** [comment]
I did not end up merging the specific PR for bumping the K3s engine in RKE2; however, the K3s engine has been bumped since then to a version past the commit ID where I made the change in K3s for snapshot metadata and as such, this issue should be able to be closed as the functionality for etcd snapshot metadata should have made it into the RKE2 codebase for versions > 1.22

**Comment by katran001** [comment]
@rancher-max this is ready for testing for the next milestone.

**Comment by rancher-max** [comment]
#### Validated using v1.21.9+rke2r1, v1.22.6+rke2r1, and v1.23.3+rke2r1

Confirmed the metadata is being stored in all of these versions. Example configmap:
```
$ k get cm -n kube-system rke2-etcd-snapshots -o yaml
apiVersion: v1
data:
  local-on-demand-ip-172-31-16-240-1643669792: '{"name":"on-demand-ip-172-31-16-240-1643669792","location":"file:///var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-16-240-1643669792","nodeName":"ip-172-31-16-240","createdAt":"2022-01-31T22:56:33Z","size":3588128,"status":"successful","compressed":false}'
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-31T22:56:33Z"
  name: rke2-etcd-snapshots
  namespace: kube-system
  resourceVersion: "915"
  uid: f86d607f-f28e-4f3c-8448-4328c5b7f3db
```
