### ISSUE TITLE
Need network policies in default namespaces when in cis mode

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#208]
cis has a control that requires each namespace to have a network policy (control 5.3.2). We currently don't lay any policies down.

We should add logic to setup network policies for each of the built-in namespaces (default, kube-system, kube-node-lease) that locks the networking down to just that namespace.

**Comment by briandowns** [comment]
Instructions for verification can be found in the PR #254

**Comment by rancher-max** [comment]
#### Validated in `beta14`

- Default is to have a network policy whether CIS mode or not
- Network policies are present in the three mentioned namespaces:
```
$ kubetl get networkpolicy -A
NAMESPACE     NAME                     POD-SELECTOR   AGE
default       default-network-policy   <none>         56s
kube-public   default-network-policy   <none>         56s
kube-system   default-network-policy   <none>         56s
```
- The three mentioned namespaces have the correct annotation (note this is from a non-CIS setup as you can tell by the PSP's that are applied on the kube-system namespace, but other than that the data is the same for a CIS setup):
```
$ k describe namespace
Name:         default
Labels:       <none>
Annotations:  np.rke2.io: resolved
Status:       Active

No resource quota.

No LimitRange resource.


Name:         kube-node-lease
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.


Name:         kube-public
Labels:       <none>
Annotations:  np.rke2.io: resolved
Status:       Active

No resource quota.

No LimitRange resource.


Name:         kube-system
Labels:       <none>
Annotations:  np.rke2.io: resolved
              psp.rke2.io/global-restricted: resolved
              psp.rke2.io/global-unrestricted: resolved
              psp.rke2.io/system-unrestricted: resolved
Status:       Active

No resource quota.

No LimitRange resource.
```
- Intra-namespace traffic works as expected, and inter-namespace traffic is blocked as expected. Validated by deploying two simple nginx services and deployments in default namespace. Ensured they could reach each other by executing `curl <service clusterip>` while exec'ed into one of the pods. Ensured that exec'ing into a pod in the kube-system namespace could not access either of these endpoints. (This scenario is possible when these network policies are not present, so this means that the network policies are working as we would expect.)
