### ISSUE TITLE
Need doc update: Note regarding static image path usage

### ISSUE THREAD

**Issue by ansilh** [rancher/rke2#2087]
Putting many images under `/var/lib/rancher/rke2/agent/images` can cause the etcd to timeout during rke service startup and can cause node additions to fail.
We need to put a note in the documentation stating that the path is only intended for bootstrapping clusters and application containers should be using a local registry to download images

**Comment by brandond** [comment]
This issue has been fixed on recent releases of RKE2. It's still not a great idea to put too much stuff in there, as it WILL delay node startup until all the images are imported, but it will no longer cause etcd member addition to time out.

**Comment by ansilh** [comment]
Thanks, @brandond.
Is it worth noting this as part of best practice?
