### ISSUE TITLE
Etcd keeps old node in member list: Unhealthy cluster

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#2088]
**Environmental Info:**
RKE2 Version: v1.21.5+rke2r2

Node(s) CPU architecture, OS, and Version: Ubuntu 20.04

Cluster Configuration:
3 servers, 2 agents

**Describe the bug:**
I have had a significant amount of pain just trying to join and upgrade nodes in RKE2. When attempting to replace all server nodes, the final node failed to delete in Kubernetes properly resulting in me having to manually remove the etcd taint and delete it. Now the node that is supposed to replace it is unable to join etcd as it states there is the old node still in the cluster (does not exist).

This bug is coupled with the fact that joining nodes to clusters often needs a full `rke2-killall` and restart just to work about 50% of the time or the node will never become ready which further adds to frustration.

**Steps To Reproduce:**
- Have a running 1.21.4+rke2r3 cluster with 3 servers, 2 agents
- Delete a server, start up a new server with version 1.21.5+rke2r2
- Delete another server, startup a new server with version 1.21.5+rke2r2
- Delete the last server, startup a new server with version 1.21.5+rke2r2

By "delete a server" I mean, cordon, drain, and then delete the underlying VM. In my case vsphere's cloud provider automatically removes the node from the Kubernetes cluster.

On the very last step, the last server will not be deleted from `kubectl get nodes` and will be stuck in a `NotReady` state. The replacement node with the same IP cannot join the cluster due to `joining etcd cluster: etcdserver: Unhealthy cluster` because the old node still appears in the member list but is no longer alive.

You can manually remove the taint on the node that doesn't exist anymore and then `kubectl delete node ...` but the new VM still will not be able to join the cluster because that node still exists in the etcdcluster.

I don't think I'm doing anything too crazy here.

**Comment by brandond** [comment]
Can you share the RKE2 logs from all three servers at the time you attempt to delete the last original node from the cluster? I'm not aware of any outstanding issues with node deletion. There should not be anything special about this first node that prevents it from being deleted from the cluster.

> The replacement node with the same IP cannot join the cluster

Just to be clear, when you're deleting old nodes and joining new ones to the cluster, the "new" node has the same IPs as the old one that was just deleted?

**Comment by braunsonm** [comment]
After repeated attempts I found:
```
http: TLS handshake error from <joining ip>: remote error: tls: bad certificate
```
Being repeated in the logs of the other servers. Rebooting the joining node corrected the issue but why? The certificate is the same as the one that joined the server initially that worked fine and why would a reboot solve the problem?

> Just to be clear, when you're deleting old nodes and joining new ones to the cluster, the "new" node has the same IP as the "old" one that was just deleted?

Correct, in this instance we are just replacing the underlying OS template

**Comment by brandond** [comment]
OK so you're not really replacing old nodes with new nodes, you're stopping RKE2, replacing some bit of OS configuration, and then restarting RKE2? What all are you doing to stop and clean up RKE2 installations in between removing it from and readding it to the cluster?

**Comment by braunsonm** [comment]
> OK so you're not really replacing old nodes with new nodes, you're stopping RKE2, replacing some bit of OS configuration, and then restarting RKE2?

No. The entire VM **is deleted** including all data. The VM is recreated using a template and starts up with the same IP as the VM that was deleted. We follow an immutable infrastructure approach to upgrades including OS updates

**Comment by brandond** [comment]
Can you try again with the most recent release? The fact that restarting the node after attempting to join it allows it to join successfully makes me suspect something else is going on. Are you by any chance preloading images via airgap tarball?

**Comment by braunsonm** [comment]
No but we are using a private registry

**Comment by braunsonm** [comment]
This is hard to reproduce, I'll close this..

**Comment by albgus** [comment]
I am currently seeing the same issue. I thought that it was supposed to be possible to re-install nodes, but there is zero documentation available on this so perhaps it's not possible?

**Comment by brandond** [comment]
@labgus please open a new issue describing your system configuration, what you're doing, and what issue you're experiencing.
