### ISSUE TITLE
[Docs] Add documentation for HTTP proxy configuration

### ISSUE THREAD

**Issue by bashofmann** [rancher/rke2#2091]
**Is your feature request related to a problem? Please describe.**
The docs are missing a section on how and where to configure HTTP proxy settings for environments, where you only have connectivity through a proxy.

**Additional context**
Related issues:
* https://github.com/rancher/rke2/issues/517
* https://github.com/rancher/rke2/issues/1834

**Comment by gtato** [comment]
@bashofmann Hi, do you know how we can configure the http proxy for windows agents?

**Comment by bashofmann** [comment]
I assume, you have to also set these as environment variables when starting the `rke2.exe`. But I have no idea how to do this  on Windows.

**Comment by gtato** [comment]
Yup, I just did the following and it worked.
```
[Environment]::SetEnvironmentVariable("HTTP_PROXY", "http://ip:port", [EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("HTTPS_PROXY", "http://ip:port", [EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("NO_PROXY", "x,y,z", [EnvironmentVariableTarget]::Machine)

$env:HTTP_PROXY="http://ip:port"
$env:HTTPS_PROXY="http://ip:port"
$env:NO_PROXY="x,y,z"
```
