### ISSUE TITLE
Kube-system pods failing while Airgap installation of k3s.

### ISSUE THREAD

**Issue by shreya-bhatnagar** [rancher/rke2#2100]
I am trying to do airgap installation of k3s. I did below steps:
  1.   copied [install.sh script](https://get.k3s.io/) to `/usr/local/bin/`
  2.   copied k3s binary (downloaded from [Assets](https://github.com/k3s-io/k3s/releases/tag/v1.22.3+k3s1)) to `/usr/local/bin`/
  3. ` cd /usr/local/bin/` 
  4.  `chmod 770 k3s` - giving executable rights to k3s binary
  5.  placed [airgap-images-amd64.tar](https://github.com/k3s-io/k3s/releases/download/v1.22.3%2Bk3s1/k3s-airgap-images-amd64.tar) image at `/var/lib/rancher/k3s/agent/images/` path
  6. ` INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh`  - ran install script
  7. Facing error in k3s service, I found its [an open issue for offline installation](https://github.com/k3s-io/k3s/issues/1103)
  8. `sudo ip route add default via 172.19.0.1` - as per [comment](https://github.com/k3s-io/k3s/issues/1144#issuecomment-559316077) : **_Though its not permanent solution, as comment says that after reboot the default config will go away. Plz let me know the permanent solution for this ._**
  9. The default `kube-system` pods came up  but pods are failing. 
 10. plz find attached `journalctl -u k3s` logs [journalctl_k3s_logs.txt](https://github.com/rancher/rke2/files/7510468/journalctl_k3s_logs.txt). Also `/var/log/k3s.log` **not** got created on this machine.
  
**Error I am getting now:**
Pods in Airgap/offline installation are not able to pull images.` kubectl describe pod coredns` gives error:
Warning  FailedCreatePodSandBox  17s (x2 over 39s)  kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp: lookup registry-1.docker.io: Try again

Can someone let me know how to resolve this ?

_Originally posted by @shreya-bhatnagar in https://github.com/rancher/rke2/issues/1242#issuecomment-964836731_

**Comment by brandond** [comment]
Your logs indicate that you're running k3s v1.21.5+k3s2, but the images that the logs show being imported from airgap-images-amd64.tar on your node are for a 1.22 release. Please be sure that you're using the k3s binary and airgap images from the same release: https://github.com/k3s-io/k3s/releases/tag/v1.21.5%2Bk3s2

**Comment by brandond** [comment]
As noted on the other issue you commented on, the simplest fix may be to just add an init script on your node to run the `ip route add` command every time it starts.
