### ISSUE TITLE
etcd-snapshot loading config fails with "flag provided but not defined: -profile"

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#2103]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
N/A

**Describe the bug:**
Running the etcd-snapshot commands throw an error `flag provided but not defined: -profile`. 

**Steps To Reproduce:**
Have the profile set in the config file and run the etcd-snapshot which loads the default config.

**Expected behavior:**
Runs snapshot. 

**Actual behavior:**
Throw error saying flag profile is not defined.

**Comment by brandond** [comment]
cc @dereknola 

etcd-snapshot now loads the config file, but if there are other flags in the config file that aren't valid for the etcd-snapshot command it will barf on them.

**Comment by Oats87** [comment]
Ignoring unknown flags can be dangerous, as our current behavior of barfing on unknown flags allows for a user to get more immediate feedback that they have a misconfiguration. If we just ignore unknown flags a user can be misled especially as that is a departure from existing behavior.

**Comment by pitshou** [comment]
I have a customer who is hitting this. So, I am checking to see what they have inside of their config file

Incorrect Usage. flag provided but not defined: -node-label

**Comment by dnoland1** [comment]
Assume you can pass the `--config` and choose an alternative config.yaml to workaround this, right?

**Comment by mitchellmaler** [comment]
yes there are ways around this. Different config or just passing the args/flags directly to the command.

**Comment by mitchellmaler** [comment]
The expected result though is the server config with all the server flags can be used with the etcd-snapshot command.

**Comment by brandond** [comment]
I agree that ignoring flags could cause other issues @Oats87 but the current behavior makes the config file non-portable between commands. If you add flags specific to `rke2 server` those will cause `rke2 agent` or `rke2 etcd-snapshot` (and planned future subcommands) to fail. This probably needs a proper design discussion to hash out since there's no easy fix that will satisfy all concerns.

**Comment by dereknola** [comment]
Backport bot broken?

**Comment by chreniuc** [comment]
I've encountered the same problem when trying to generate an on-demand snapshot. I'm using: `rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)`.

The error shows up even when I run `help`:

```bash
rke2 etcd-snapshot help
```

```bash
FATA[0000] flag provided but not defined: -cluster-cidr 
```

The config file for the server contains:

```yml
cluster-cidr: 10.42.0.0/16
```

**Comment by brandond** [comment]
yes @chreniuc that's the same issue.

**Comment by VestigeJ** [comment]
### **_Issue validated_** 
RKE2 skipped over unknown flags inside of the config.yaml, etcd-snapshot correctly uploaded to an S3 bucket.

$ rke2 -v
```
rke2 version v1.21.7-rc2+rke2r1 (de8b499743b19a5a703f0bc26aea9c6fdabc3874)
go version go1.16.10b7
```

$ cat /etc/rancher/rke2/config.yaml

```
write-kubeconfig-mode: "0644"
tls-san:
  - "foot1.local"
node-label:
  - "key=valued"
  - "crisis=averted"
etcd-expose-metrics: true
etcd-snapshot-name: "vertabular"
etcd-snapshot-schedule-cron: "*/22****"
etcd-snapshot-retention: 7
etcd-snapshot-dir: /home/ubuntu/
etcd-s3: true
etcd-s3-bucket: "justin-validation-bucket"
etcd-s3-region: "us-north-9"
etcd-s3-endpoint: "s3.us-north-9.amazonaws.com"
etcd-s3-access-key: "***************"
etcd-s3-secret-key: "*************"
```

$  sudo /usr/local/bin/rke2 etcd-snapshot

```
WARN[0000] Unknown flag --write-kubeconfig-mode found in config.yaml, skipping 
WARN[0000] Unknown flag --tls-san found in config.yaml, skipping 
WARN[0000] Unknown flag --node-label found in config.yaml, skipping 
WARN[0000] Unknown flag --node-label found in config.yaml, skipping 
WARN[0000] Unknown flag --etcd-expose-metrics found in config.yaml, skipping 
WARN[0000] Unknown flag --etcd-snapshot-name found in config.yaml, skipping 
WARN[0000] Unknown flag --etcd-snapshot-schedule-cron found in config.yaml, skipping 
WARN[0000] Unknown flag --etcd-snapshot-retention found in config.yaml, skipping 
WARN[0000] Unknown flag --etcd-snapshot-dir found in config.yaml, skipping 
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
...
...
...
INFO[0000] Saving etcd snapshot on-demand-ip-15-5-55-55.us-north-9.compute.internal-5555 to S3 
INFO[0000] Checking if S3 bucket justin-validation-bucket exists 
INFO[0000] S3 bucket justin-validation-bucket exists    
INFO[0001] S3 upload complete for on-demand-ip-15-5-55-55.us-north-9.compute.internal-5555 
INFO[0001] Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap 
```

**Comment by VestigeJ** [comment]
Validated a fix across all RKE2 Release Candidates

https://github.com/rancher/rke2/issues/2130 [rke2 version v1.20.13-rc1+rke2r1]
https://github.com/rancher/rke2/issues/2129 [rke2 version v1.21.7-rc2+rke2r1]
https://github.com/rancher/rke2/issues/2191 [rke2 version v1.22.4-rc1+rke2r1]
