### ISSUE TITLE
Harvester - Kubectl Error - Waited for ... due to client-side throttling, not priority and fairness, request:.. 

### ISSUE THREAD

**Issue by gogbac** [rancher/rke2#2119]
**Environmental Info:**
RKE2 Version: harvester-v0.3.0-amd64.iso

Node(s) CPU architecture, OS, and Version: Dell PowerEdge XR11 (32Core, 128GB RAM, 2 x 1.5TB SSD)

Cluster Configuration: I was able to install only first node and Kubectl was showing those errors

**Describe the bug:**

UI is not responsive and kubectl gets error messages
 see Error messages examples:
![image](https://user-images.githubusercontent.com/51060150/141523629-3a78363e-f95b-4ac0-9e15-952aec32fef8.png)

**Steps To Reproduce:**

- Installed RKE2: harvester-v0.3.0-amd64.iso
[Testing Harvester 030 - SUSE Alliances - Installation Screenshots - Draft 3.pdf](https://github.com/rancher/rke2/files/7529912/Testing.Harvester.030.-.SUSE.Alliances.-.Installation.Screenshots.-.Draft.3.pdf)

**Expected behavior:**

- Ability to use Bond0 
- no Kubectl errors

**Actual behavior:**

- Kubectl error messages and UI performance makes it difficult to work

**Additional context / logs:**

[kubectl-debug.log](https://github.com/rancher/rke2/files/7529950/kubectl-debug.log)
[rke2-server.log](https://github.com/rancher/rke2/files/7529951/rke2-server.log)
[containerd.log](https://github.com/rancher/rke2/files/7529952/containerd.log)

**Comment by gogbac** [comment]
I have reinstalled the node1, using a single NIC and I got the same errors, see logs attached
[kubectl-debug_singleNIC.log](https://github.com/rancher/rke2/files/7530421/kubectl-debug_singleNIC.log)
[rke2-server_singleNIC.log](https://github.com/rancher/rke2/files/7530422/rke2-server_singleNIC.log)
[containerd_singleNIC.log](https://github.com/rancher/rke2/files/7530423/containerd_singleNIC.log)
,

**Comment by gogbac** [comment]
see more logs
[kubectl-debug_singleNIC_morelogs.log](https://github.com/rancher/rke2/files/7530494/kubectl-debug_singleNIC_morelogs.log)
 
![image](https://user-images.githubusercontent.com/51060150/141536238-ebcf63b8-df18-470b-b629-07fcf91d68be.png)

**Comment by brandond** [comment]
Based on the messages, it would appear that the client is throttling itself ("client-side throttling").  You might consider reading through https://kubernetes.io/docs/concepts/cluster-administration/flow-control/. As far as I can tell this is not an issue with RKE2.

**Comment by yasker** [comment]
I've encountered the same issue on my Dell PowerEdge R630. I would ask the Harvester team to take a look first.

**Comment by David-VTUK** [comment]
```
I1112 19:06:49.745731    7211 cached_discovery.go:130] failed to write cache to .kube/cache/discovery/127.0.0.1_6443/servergroups.json due to mkdir .kube: read-only file system
```
I've seen this before when the user I'm running `kubectl` as doesn't have access to ~/.kube/cache. For example:

```
ls -la .kube                                                                                                                                                  
total 4
drwxr-xr-x. 1 david david   42 Nov 30 15:00 .
drwx------. 1 david david  726 Dec  2 13:24 ..
drw-------. 1 root  root    26 Nov 30 13:37 cache
-rw-------. 1 david david  422 Dec  2 13:22 config
drwxr-x---. 1 david david 3094 Nov 30 15:01 http-cache
```
Results in:

```
 kubectl get po                                                                                                                            
I1202 13:23:30.574129   16091 request.go:668] Waited for 1.054408686s due to client-side throttling, not priority and fairness, request: GET:https://rancher.virtualthoughts.co.uk/k8s/clusters/c-m-kfhgmncw/apis/custom.metrics.k8s.io/v1beta1?timeout=32s
No resources found in default namespace.

```
Rectified with `chown david:david ~/.kube/cache` and `chmod` (if needed)

```
kubectl get po                                                                                                                             
No resources found in default namespace.
```

**Comment by guangbochen** [comment]
@gogbac can u please try the workaround of `chown $user:$user ~/.kube/cache` and please let us know if this can resolve the issue, thanks

**Comment by yasker** [comment]
@David-VTUK is right. It's a permission issue in Harvester.
<img width="1445" alt="Screen Shot 2021-12-07 at 3 48 30 PM" src="https://user-images.githubusercontent.com/3344618/145123507-a8a864d1-22b3-4aaa-988b-71dc50b3e949.png">

I will close this one and follow up the conversation in https://github.com/harvester/harvester/issues/1617

**Comment by fhanik** [comment]
```
chown -R $user:$user ~/.kube/*
```
not sure why some directories where owned by `root`, but this fixed it.

**Comment by JotaAraujo89** [comment]
I have the same problem using wsl (Ubuntu + OhMyZsh). I solved using bash in root mode. It's appears to be something around permission, but I don't know where.

![image](https://user-images.githubusercontent.com/80866426/177559926-f1c21fb1-b415-4854-a67b-5b6e7199d5f1.png)
