### ISSUE TITLE
[release-1.21] Support etcd extra-args

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#2137]
Backport of: https://github.com/rancher/rke2/issues/2135

**Is your feature request related to a problem? Please describe.**
RKE2 needs to support etcd extra-args

**Describe the solution you'd like**
Add `--etcd-arg` to RKE2

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by VestigeJ** [comment]
Validated with the following configs and outputs.
$ rke2 -v
```
rke2 version v1.21.6-dev+00a489a6 (00a489a60a11c0f83a108f0cce47ff8df3594867)
go version go1.16.6b7
```

_**INSTALL COMMAND**_
`$ sudo /usr/local/bin/rke2 server --debug --etcd-arg quota-backend-bytes=858993459 --etcd-arg "experimental-initial-corrupt-check=true" --etcd-arg "log-rotation-config-json={"maxsize": 100, "maxage": 0, "maxbackups": 0, "localtime": false, "compress": false}" --etcd-arg "log-outputs=[default]"`

$ sudo cat /var/lib/rancher/rke2/server/db/etcd/config
`cat: /var/lib/rancher/rke2/etcd/config: No such file or directory`

$ sudo /usr/local/bin/rke2 etcd-snapshot
```
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
...
...
...
INFO[0000] Saving etcd snapshot to /var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-26-80.us-north-9.compute.internal-1637798628 
{"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-26-80.us-north-9.compute.internal-1637798628.part"}
{"level":"info","ts":"2021-11-25T00:03:48.295Z","caller":"clientv3/maintenance.go:200","msg":"opened snapshot stream; downloading"}
{"level":"info","msg":"fetching snapshot","endpoint":"https://127.0.0.1:2379"}
{"level":"info","ts":"2021-11-25T00:03:48.404Z","caller":"clientv3/maintenance.go:208","msg":"completed snapshot read; closing"}
{"level":"info","msg":"fetched snapshot","endpoint":"https://127.0.0.1:2379","size":"6.4 MB","took":"134.748841ms"}
{"level":"info","msg":"saved","path":"/var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-26-80.us-north-9.compute.internal-1637798628"}
INFO[0000] Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap
```

$ sudo journalctl -xe | grep rke2
`Nov 24 23:59:47 ip-172-31-26-80.us-north-9.compute.internal sudo[40959]:   centos : TTY=pts/2 ; PWD=/home/centos ; USER=root ; COMMAND=/usr/local/bin/rke2 server --debug --etcd-arg quota-backend-bytes=858993459 --etcd-arg experimental-initial-corrupt-check=true --etcd-arg log-rotation-config-json={maxsize: 100, maxage: 0, maxbackups: 0, localtime: false, compress: false} --etcd-arg log-outputs=[default]
`

**Comment by ShylajaDevadiga** [comment]
Adding related issue for tracking purpose https://github.com/rancher/rke2/issues/2176
