### ISSUE TITLE
Changing token / agent-token required for security

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#2141]
**Is your feature request related to a problem? Please describe.**
During initial deployment we specify tokens / agent-tokens in config.yaml but for security reasons these tokens might need to be changed / updated on a regular basis similar to SSL certificates, encryption keys and passwords.

Is this supported / do we have a documented procedure on how it is supported to change tokens / agent-tokens?

**Comment by brandond** [comment]
We do not currently support changing the server token, as it is used both as a password to join the cluster, and as the passphrase for the bootstrap data. It should be possible to change the agent token though.

**Comment by brandond** [comment]
Not at the moment, no.

**Comment by jroeber** [comment]
I also want a way to change the server token. I accidentally committed the token to an automation repository, and it would be very nice to be able to rotate it at this point.

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id f8cb409287ac09608d3d2fbac364dddb05400a3e
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Configuration:*
3 server 1 agent

*Config.yaml:*
```
$ cat /etc/rancher/rke2/config.yaml 
write-kubeconfig-mode: "0644"
token: token1
node-external-ip: <IP>
```
 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml
2. Install rke2
3. As non-root user *rke2 token rotate --token token1 --new-token=token2*
4. Update config.yaml with new token
5. Restart rke2 service on all nodes
6. Reboot all nodes
7. Verify token is updated on every node, cluster is up and pods are in running state

After reboot cluster is up and running
**Validation results:**
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-10-199   Ready    control-plane,etcd,master   13m   v1.28.2+rke2r1
ip-172-31-15-142   Ready    <none>                      14m   v1.28.2+rke2r1
ip-172-31-3-159    Ready    control-plane,etcd,master   13m   v1.28.2+rke2r1
ip-172-31-8-100    Ready    control-plane,etcd,master   18m   v1.28.2+rke2r1

```
Validated as root user passing just the new-token and verified cluster comes up fine and all nodes are up
```
# rke2 token rotate --new-token=token2
```
