### ISSUE TITLE
Support node hard delete method of the RKE2 node

### ISSUE THREAD

**Issue by guangbochen** [rancher/rke2#2144]
**Environmental Info:**
RKE2 Version: v1.22.3+rke2r1

**Is your feature request related to a problem? Please describe.**
- delete one of the nodes from the cluster either via kubectl delete node or through the Rancher API
- reboot the deleted node and it will be added to the cluster again
- expecting a node hard delete methodology that it will not join the cluster again after node reboot

RKE2 related issue: https://github.com/rancher/rke2/issues/1959 may also get addressed via the node hard delete method.

Other related issues: 
https://github.com/rancher/rancher/issues/35258
https://github.com/harvester/harvester/issues/1497

**Comment by yasker** [comment]
Set to the same milestone as https://github.com/k3s-io/k3s/issues/4023

**Comment by yasker** [comment]
Keep it open to fix from RKE2 side, instead of using workaround on Harvester.

**Comment by brandond** [comment]
We don't currently have a method of deleting a node that prevents it from rejoining the server when the service is restarted. This is true of both K3s and RKE2.

I'm am not sure if this is something we need to offer as a feature, or if downstream projects like Harvester should find some way to orchestrate running `systemctl disable --now rke2-server` on the node to ensure that systemd no longer restarts the service, since it is ultimately the restarting of the service that causes the node to rejoin the cluster.

cc @dweomer @cjellick

**Comment by dweomer** [comment]
Is this more appropriately achieved via CCM implementaion?

**Comment by guangbochen** [comment]
I think the challenging part is with either with `systemctl disable --now rke2-server` or any other similar command(e.g we tried to remove the token via https://github.com/harvester/harvester/pull/1566) it will not 100% guarantee the node will get deleted on the controller side due to the finalizers and the node will become not ready when `kubelet` is lost.

**Comment by guangbochen** [comment]
quoted from https://github.com/harvester/harvester/issues/1497#issuecomment-1006488404: 
> Tried out systemctl disable rke2-server rke2-agent. The result is the same. Node became NotRready and Unreachable on master node, so the job cannot be scheduled onto that node. I guess it's the same problem described in #1497 (comment)

So I guess this is more appropriately achieved either via RKE2 or CCM implementation ?

**Comment by brandond** [comment]
I replied on that issue. Would you prefer to keep the discussion there, or here?

**Comment by katran001** [comment]
@guangbochen is still investigating this issue with @dweomer. Will update/close this issue until further notice.

**Comment by katran009** [comment]
@guangbochen can we close this?

**Comment by guangbochen** [comment]
Yes, we can close this one and track it on the Harvester side with https://github.com/harvester/harvester/issues/1497. It will require some low-level operation on the node server, but how to re-sync with the k8s API is still a challenging issue.
