### ISSUE TITLE
Compress etcd snapshots

### ISSUE THREAD

**Issue by chreniuc** [rancher/rke2#2151]
I've activated etcd snapshots and I'm saving them to S3(like it's specified in [these docs](https://docs.rke2.io/backup_restore/)). But I've noticed that those snapshots are not compressed. 

For example a snapshot is `20MB`, if I compress it with zip I reduce it to `4.1MB` and if I compress it with `7z`(or `tar.xz`) I get to `2.4MB`(almost 10 times less space used + bandwidth when uploading them to S3). We are backing up the etcd a few times a day and this would reduce our costs for our clusters.

Is there a way to activate compression for those snapshots? I couldn't find any info on this.

If not, are there any plans on adding this feature? Also restoring from a compressed snapshot.

**Comment by brandond** [comment]
@briandowns @Oats87 this sounds reasonable to me, what do you think?

**Comment by briandowns** [comment]
There hasn't been any chat around compression for snapshots so not too sure around timeframe if this feature were to be added but overall, seems reasonable.

**Comment by ShylajaDevadiga** [comment]
Validated on v1.23.2-rc1+rke2r1, backup and restore was successful on a compressed snapshot.
Before snapshot-compress
```
$ sudo ls -hl /var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-14-206.us-east-2.compute.internal-1643147887
-rw------- 1 root root 7.4M Jan 25 21:58 /var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-14-206.us-east-2.compute.internal-1643147887
```
After passing snapshot-compress
```
$ sudo ls -lh /var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-14-206.us-east-2.compute.internal-1643147841.zip
-rw-r--r-- 1 root root 1.4M Jan 25 21:57 /var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-14-206.us-east-2.compute.internal-1643147841.zip
```
