### ISSUE TITLE
rke2 pod to pod communication not working with different node

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#2152]
RKE Version v1.21.5+rke2r1
CNI Calico
OS RHEL 8.4

Based on observation, POD in same node its working fine but pod in differnet node not working (communication).

Any pointer ?

**Comment by manuelbuil** [comment]
Can you please show us your config?

**Comment by cloudcafetech** [comment]
```
{
  "agent-token": "vqcwjsmpfb9wxhjdd2dftvxmjpkh6dbg4zvshdb4t46xf24g6cbgnt",
  "cni": "calico",
  "disable": [
    "rke2-ingress-nginx"
  ],
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */12 * * *",
  "kube-apiserver-arg": [
    "authentication-token-webhook-config-file=/var/lib/rancher/rke2/kube-api-authn-webhook.yaml"
  ],
  "kubelet-arg": [
    "read-only-port=10255"
  ],
  "node-label": [
    "cattle.io/os=linux",
    "rke.cattle.io/machine=1f505e53-56c2-4436-8014-86455a535f33"
  ],
  "node-taint": [
    "node-role.kubernetes.io/control-plane:NoSchedule",
    "node-role.kubernetes.io/etcd:NoExecute"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "tls-san": [
    "k8s.example.com",
    "172.26.30.165"
  ],
  "token": "j7r9pxnfx46bbd7b2sxd2d56n6r8lcpdvlgq4hcj2k26kf9bzn28jp"
```

**Comment by manuelbuil** [comment]
Could you check three things:

1 - If you execute `ip a` in each of the nodes, do you see the interface `vxlan.calico`?
2 - Could you paste the output of `kubectl get pods -A -o wide`?
3 - If you are running the cluster in a public cloud (e.g. AWS), can you verify that UDP port 4789 is allowed in the security group of the instances?

**Comment by manuelbuil** [comment]
1 - How do you test pod-pod communication across nodes?

2 - When you are in a node, e.g. 172.25.32.191, and execute this `nc -uzv 172.25.32.197 4789` using the IP of another node, do you get `succeeded!` after ~5 seconds?

3 - When you are in a node, can you show me the output of `ip r` and `ip rule`?

**Comment by cloudcafetech** [comment]
> 1 - How do you test pod-pod communication across nodes?

We have setup of 3 Master  2 infra & 2 apps 
                 --------  ----------------
                  MASTER        WORKER

my ingress POD sitting in infra node and apps POD sitting in apps node. 
I am getting timeout in ingress pod logs of apps pod

If I schedule apps pod in infra node then no issue.

> 2 - When you are in a node, e.g. 172.25.32.191, and execute this nc -uzv 172.25.32.197 4789 using the IP of another node, do you get succeeded! after ~5 seconds?

```
[infra ~]# nc -uzv 172.25.32.196 4789
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 172.25.32.196:4789.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.

[infra ~]# nc -uzv 172.25.32.197 4789
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 172.25.32.197:4789.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.
```

>3 - When you are in a node, can you show me the output of ip r and ip rule?

```
[infra ~]# ip r
default via 172.25.32.1 dev eth0 proto static metric 100
10.42.18.0/24 via 10.42.18.0 dev vxlan.calico onlink
10.42.23.0/24 via 10.42.23.0 dev vxlan.calico onlink
10.42.89.35 dev cali049041c9a8a scope link
10.42.89.36 dev cali18cac350493 scope link
10.42.89.37 dev cali1252e745906 scope link
10.42.89.39 dev cali957a318a724 scope link
10.42.89.40 dev calid1bd4935c3d scope link
10.42.89.41 dev cali818d958bbd8 scope link
10.42.89.42 dev cali4a202a4a473 scope link
10.42.89.43 dev calie019bfa2886 scope link
10.42.89.44 dev calif90f62712bf scope link
10.42.148.0/24 via 10.42.148.0 dev vxlan.calico onlink
10.42.151.0/24 via 10.42.151.0 dev vxlan.calico onlink
10.42.187.0/24 via 10.42.187.0 dev vxlan.calico onlink
10.42.249.0/24 via 10.42.249.0 dev vxlan.calico onlink
10.148.173.128/27 dev eth1 proto kernel scope link src 10.148.173.140 metric 101
10.191.192.0/18 via 10.148.173.129 dev eth1 proto static metric 101
172.25.32.0/22 dev eth0 proto kernel scope link src 172.25.32.198 metric 100
[infra ~]#
[infra ~]#
[infra ~]# ip rule
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default
```

**Comment by manuelbuil** [comment]
Everything seems correct. Let's do one thing, assuming the following:
- debug POD is running on Node pk8wn01
- prometheus-0 or prometheus-msteams are running on pk8in01

Please provide me the output of:
- `sudo ip -details link show vxlan.calico` in pk8wn01
- `sudo ip -details link show vxlan.calico` in pk8in01

And then, I'd like you to execute the following:
- `sudo tcpdump -eni vxlan.calico icmp` in pk8wn01
- `sudo tcpdump -eni vxlan.calico icmp` in pk8in01

Once tcpdump is running on both nodes, please repeat the ping from debug POD to prometheus-0 or prometheus-msteams and show me the output of those commands after 2 or 3 seconds. If everything works correctly, you should see output on both commands

**Comment by cloudcafetech** [comment]
Sorry for late reply.

As I have to fix this issue, I switch to Canal CNI.

Will try to reproduce in different environment and update you.

Thanks.

**Comment by manuelbuil** [comment]
> Sorry for late reply.
> 
> As I have to fix this issue, I switch to Canal CNI.
> 
> Will try to reproduce in different environment and update you.
> 
> Thanks.

Does Canal work?

**Comment by cloudcafetech** [comment]
>Does Canal work?
Yes :)

**Comment by cloudcafetech** [comment]
Issue is related with calico, just wanted to know the cause.

**Comment by cloudcafetech** [comment]
Did not get a chance to replicate in new environment. Coming week planning to deploy same RHEL8, will update you.

**Comment by manuelbuil** [comment]
> Did not get a chance to replicate in new environment. Coming week planning to deploy same RHEL8, will update you.

awesome!

**Comment by jojoatt** [comment]
> Could you check three things:
> 
> 
> 
> 1 - If you execute `ip a` in each of the nodes, do you see the interface `vxlan.calico`?
> 
> 2 - Could you paste the output of `kubectl get pods -A -o wide`?
> 
> 3 - If you are running the cluster in a public cloud (e.g. AWS), can you verify that UDP port 4789 is allowed in the security group of the instances?

Hello, I'm installing a cluster on OpenStack via Kubeadm and the communication between pods on differents workers doesn't works. I don't understand why you talk about UDP port 4789 should be open, in k8s documentation, it's not specified that port.

Thank you in advance
