### ISSUE TITLE
Allow klipper-helm image version to be overridden

### ISSUE THREAD

**Issue by AshleyDumaine** [rancher/rke2#2160]
**Is your feature request related to a problem? Please describe.**
I need to use a custom version of `klipper-helm` (considered a core image since it is found in `rke2-images-core.linux-amd64.txt` for each release) to address a bug, but it doesn't seem possible to override the version being used by RKE2 unlike for other core images like `kube-apiserver`, `kube-scheduler`, `etcd`, and so on: https://github.com/rancher/rke2/blob/master/pkg/images/images.go#L15-L25

**Describe the solution you'd like**
I would like if all images found in `rke2-images-core.linux-amd64.txt` are able to be overridden via the RKE2 CLI / config by adding missing images such as `klipper-helm` to https://github.com/rancher/rke2/blob/master/pkg/images/images.go 

**Describe alternatives you've considered**
I've considered tagging my custom klipper-helm image as the upstream klipper-helm image desired by my target RKE2 version and adding that to my image registry to use instead of the unmodified upstream image. This is currently working, but it goes against best practices and is stopgap that is undesired as a long-term solution.

Thanks!

**Comment by philip06** [comment]
Bump. `rancher/klipper-helm:v0.8.4-build20240523` has too many security vulnerabilities and there is no way to upgrade it or refactor it out. This needs to be resolved in order to be usable in hardened environments.
