### ISSUE TITLE
Runtime image name in windows 1809 image tarball is incorrect

### ISSUE THREAD

**Issue by ckehoe** [rancher/rke2#2162]
**Environmental Info:**
RKE2 Version:

rke2.exe version v1.21.6+rke2r1 (b915fc9)
go version go1.16.6b7

I have also tried it with rke2 v1.22.3+rle2r1

Node(s) CPU architecture, OS, and Version:

64-bit, Microsoft Windows Server 2019 Standard, 10.0.17763

Cluster Configuration:

One centos 7.9 server, one centos 7.9 agent, and one Windows 2019 Server
Used calico as CNI and was able to join the centos 7.9 agent
Running on VSphere

**Describe the bug:**

When performing an air-gapped installation on a Windows RKE2 agent node the rke2.exe agent command fails due to not finding the image in the windows image tarball. RKE2 expects the image to be named rancher/rke2-runtime:v1.22.3-rke2r1 but the image name in the tarball is rancher/rke2-runtime:v1.22.3-rke2r1-windows-amd64. After not finding the image locally it will reach out to dockerhub which fails because of the air-gapped installation.

**Workaround**
This issue can be fixed by overriding the runtime-image name `rke2.exe agent --runtime-image=rancher/rke2-runtime:v1.22.3
-rke2r1-windows-amd64`

**Comment by rancher-max** [comment]
Moved this to Next Up as the PR was reverted

**Comment by rancher-max** [comment]
Validated windows airgap is functional in v1.23.6-rc2+rke2r1
