### ISSUE TITLE
[release-1.21] Update vsphere CSI/CPI charts to the latest charts

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rke2#2168]
**Is your feature request related to a problem? Please describe.**

vsphere CPI/CSI charts have been updated to correspond with k8s releases and the charts in the Rancher repo have been updated accordingly

**Describe the solution you'd like**

Here are the Rancher charts to use for k8s 1.21:

vSphere CPI: https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0%2Bup1.0.100

vSphere CSI:https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0%2Bup2.3.0

**Describe alternatives you've considered**

**Additional context**

Please update this is being requested to be updated in the RKE2 1.21 release for November as well as to update the versions in the KDM update for RKE2. 

Note: There is a small build hack that will need to be updated to be sure to build from the correct chart source until we officially correct this. 

Note: Rancher charts haven't been updated for k8s 1.22 as upstream doesn't have a proper fix, but minimally 1.22 should point to the same charts for upgrade purposes (between 1.21 to 1.22)

**Comment by rancher-max** [comment]
#### Validated on v1.21.7-rc3+rke2r1

- Both fresh install and upgrade are successful
- General vsphere cloud provider functionality continues to work

```
$ k describe nodes | grep -i providerid
ProviderID:                   vsphere://421a965f-24aa-ceda-469e-cb3d9ee3d262

$ helm ls -A
NAME               	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rancher-vsphere-cpi	kube-system	1       	2021-12-01 23:24:11.480948291 +0000 UTC	deployed	rancher-vsphere-cpi-100.1.0+up1.0.100       	1.0.1      
rancher-vsphere-csi	kube-system	1       	2021-12-01 23:24:11.908209622 +0000 UTC	deployed	rancher-vsphere-csi-100.1.0+up2.3.0         	2.3.0 
```
