### ISSUE TITLE
RKE2 Pods "nfs-client-provisioner-" is forbidden: PodSecurityPolicy: unable to admit pod: []:Deployment does not have minimum availability

### ISSUE THREAD

**Issue by aintbrokedontfix** [rancher/rke2#2174]
The following error appears when deploying the[ nfs-subdir-external-provisioner ](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner).

The RKE2 (v1.21.6+rke2r1) cluster is deployed with Default Pod Security Policy set to unrestricted, project network isolation is disabled, SELinux is disabled and no CIS profile is being enforced.

**Comment by brandond** [comment]
Can you fill out the issue template? This provides important information on your cluster version, configured, and nodes. It would also be helpful to provide the output of `kubectl get node - yaml` and the full logs of wherever you're seeing this error.
