### ISSUE TITLE
rke2 service needs to be restarted for etcd-arg params to be captured in rke2 logs

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#2176]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.3-dev+8fe46e71

Node(s) CPU architecture, OS, and Version: 
Any OS

Cluster Configuration:
Single node/Multi node

**Describe the bug:**
When etcd-arg is passed in the config, the params are not captured in rke2 logs unless rke2 service is restarted

**Steps To Reproduce:**
```
sudo cat /etc/rancher/rke2/config.yaml
etcd-arg:
  - "quota-backend-bytes=858993459"
  - "experimental-initial-corrupt-check=true"
EOF'

curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=8fe46e718e62b9f1416e5705d6214df709d15454 sh -s - server 
sudo systemctl enable rke2-server
sudo systemctl start rke2-server
```

**Expected behavior:**
rke2 logs should have an entry for the quota-size-bytes that is set in config

**Actual behavior:**
rke2 logs does not have an entry for the quota-size-bytes that is set until rke2 server is restarted.
etcd pod logs do have an entry

**Additional context / logs:**
```
$ kubectl logs  -n kube-system etcd-ip-172-31-27-134 |grep size |grep quota
{"level":"info","ts":"2021-11-29T16:34:13.770Z","caller":"embed/etcd.go:307","msg":"starting an etcd server","etcd-version":"3.5.0","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.16.7b7","go-os":"linux","go-arch":"amd64","max-cpu-set":2,"max-cpu-available":2,"member-initialized":false,"name":"ip-172-31-27-134-c58cbf44","data-dir":"/var/lib/rancher/rke2/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://172.31.27.134:2380"],"listen-peer-urls":["https://172.31.27.134:2380"],"advertise-client-urls":["https://172.31.27.134:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://172.31.27.134:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"ip-172-31-27-134-c58cbf44=https://172.31.27.134:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-size-bytes":858993459,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
```

**Comment by katran001** [comment]
Moving this to the next milestone since the team didn't have a chance to work on it for v1.22.5+rke2r1

**Comment by brandond** [comment]
> rke2 logs does not have an entry for the quota-size-bytes that is set until rke2 server is restarted.

Note that the config used by the embedded etcd that is temporarily started up when bootstrapping **does not** use the same config as the etcd static pod. It is expected that they will have slightly different config. On RKE2 at least, only the etcd pod logs should be checked.

**Comment by katran001** [comment]
Can we move this to the next milestone or close it?

**Comment by ShylajaDevadiga** [comment]
Closing issue as etcd pod logs contains the values passed etcd-arg as expected
rke2 version v1.22.11-rc1+rke2r1
```
kubectl logs  -n kube-system etcd-ip-172-31-16-28  |grep quota
...
"initial-cluster-token":"etcd-cluster","quota-size-bytes":858993459,
```
