### ISSUE TITLE
Upgrading RKE2 with system-upgrade-controller causes downtime in nginx-ingress

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#2184]
**Environmental Info:**
RKE2 Version:  1.20.8 - upgrade to 1.20.11

Node(s) CPU architecture, OS, and Version: 
Intel x86_64, SLES 15 SP2

Cluster Configuration:
3 servers, no agents, rancher local cluster and rancher downstream cluster

**Describe the bug:**
Changing the version in the Rancher UI from 1.20.8 to 1.20.12 -> system-upgrade-controller based upgrade starts.
During the upgrade we end up in this situation:
![grafik](https://user-images.githubusercontent.com/13362573/144057860-1c7e0c47-1494-4553-87e7-4c3173b2acb3.png)

**Steps To Reproduce:**
- Installed RKE2 1.20.8 with Rancher 2.5.9 - 3 server
- Installed RKE2 1.20.8 - 3 server
- Ingress as daemon set
- Import downstream cluster into Rancher
- Upgrade Rancher 2.5.9 to 2.5.11
- Upgrade local and downstream cluster via Rancher UI / edit / change version and do not select "drain"

--> realize after a few minutes that no ingress is possible anymore due to stuck in termination..

**Expected behavior:**
During each nodes upgrade the status of the pods is monitored and as long as a pod is in termination the rke2 service is not restarted.
In case the rke2 service is restarted the PODs in "termination" complete the termination.

**Actual behavior:**
See above - no new nginx-ingress pods get scheduled because the current ones are stuck in termination.

**Additional context / logs:**
We verified with crictl ps -a that the "terminating" pods were really not there, anymore.

Probably the rke2 service restart only should be done in case the termination of the pods is completed?

**Comment by brandond** [comment]
The pods stuck terminating is an upstream issue that we've been battling for a while:
https://github.com/kubernetes/kubernetes/issues/70044#issuecomment-853517954

**Comment by Martin-Weiss** [comment]
Seems that we have to fix/work around this bug in the rke2 upgrade process as long as the k8s issue exists as all upgrades can / will cause downtime as long as this issue exists.

I believe a workaround should be added to the way how Rancher uses the system-upgrade-controller / maybe also in the upgrade image by adding health checks.

I assume the upgrade procedure must stop automatically in case there are pods stuck in termination causing all replicas of a deployment/daemonset/statefulset to be gone and new ones are not scheduled due to this.
