### ISSUE TITLE
RKE2 deployment k8s component time zone problem

### ISSUE THREAD

**Issue by zuocg** [rancher/rke2#2192]
**Environmental Info:**
RKE2 Version:  v1.21.6+rke2r1

Describe the bug: Configure kube-apiserver-extra-mount parameters, service startup error

**Steps To Reproduce:**

- /etc/rancher/rke2/config.yaml:
kube-apiserver-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"
kube-scheduler-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"
kube-controller-manager-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"
kube-proxy-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"
etcd-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"
cloud-controller-manager-extra-mount:
    - "/etc/localtime:/etc/localtime:ro"          

Actual behavior: rke2-server service failed to initialize installation

Additional context / logs:
![image](https://user-images.githubusercontent.com/88480631/144168707-cd347583-1061-4599-881f-c1fa6e5fabf5.png)

**Comment by zuocg** [comment]
> **环境信息：** RKE2 版本：v1.21.6+rke2r1
> 
> bug描述：配置kube-apiserver-extra-mount参数，服务启动报错
> 
> **重现步骤：**
> 
> * /etc/rancher/rke2/config.yaml: 
>   kube-apiserver-extra-mount:
>   
>   * "/etc/localtime:/etc/localtime:ro" 
>     kube-scheduler-extra-mount:
>   * "/etc/localtime:/etc/localtime:ro" 
>     kube-controller-manager-extra-mount:
>   * "/etc/localtime:/etc/localtime:ro" 
>     kube-proxy-extra-mount:
>   * "/etc/localtime:/etc/localtime:ro" 
>     etcd-extra-mount:
>   * “/etc/localtime:/etc/localtime:ro” 
>     cloud-controller-manager-extra-mount:
>   * “/etc/localtime:/etc/localtime:ro”
> 
> 实际行为：rke2-server 服务未能初始化安装
> 
> 附加上下文/日志： ![图片](https://user-images.githubusercontent.com/88480631/144168707-cd347583-1061-4599-881f-c1fa6e5fabf5.png)

**Comment by zuocg** [comment]
Reset the mount etc directory and the container time zone bit CST
kube-apiserver-extra-mount: /etc:/etc:ro

**Comment by zuocg** [comment]
Why does setting the mount file cause the service to fail to start

**Comment by brandond** [comment]
If you're just trying to change the timezone, setting the TZ environment variable in the pods might be an easier way to do that.

**Comment by zuocg** [comment]
Tested, the time zone name changes, but the time is still UTC，K8s basic components cannot be modified by kubetctl edit
![image](https://user-images.githubusercontent.com/88480631/144776032-0ca9aaa7-1133-4d4a-9483-9803db066999.png)

**Comment by brandond** [comment]
No, they're static pods, you cannot edit them with kubectl. You must pass flags in via the rke2 CLI.

**Comment by zuocg** [comment]
Please tell me how to operate rke2 cli. Can I directly mount the /etc/localtime file in the config.yaml file

**Comment by brandond** [comment]
On recent releases, you should be able to use the following flags:
```
   --kube-apiserver-extra-env value              (components) kube-apiserver extra environment variables [$RKE2_KUBE_APISERVER_EXTRA_ENV]
   --kube-scheduler-extra-env value              (components) kube-scheduler extra environment variables [$RKE2_KUBE_SCHEDULER_EXTRA_ENV]
   --kube-controller-manager-extra-env value     (components) kube-controller-manager extra environment variables [$RKE2_KUBE_CONTROLLER_MANAGER_EXTRA_ENV]
   --kube-proxy-extra-env value                  (components) kube-proxy extra environment variables [$RKE2_KUBE_PROXY_EXTRA_ENV]
   --etcd-extra-env value                        (components) etcd extra environment variables [$RKE2_ETCD_EXTRA_ENV]
   --cloud-controller-manager-extra-env value    (components) cloud-controller-manager extra environment variables [$RKE2_CLOUD_CONTROLLER_MANAGER_EXTRA_ENV]
```

so, for example:
`rke2 server --kube-apiserver-extra-env=TZ=America/Los_Angeles`

**Comment by zuocg** [comment]
thk

**Comment by zuocg** [comment]
I configured it and found that it didn't take effect. The time zone and time are wrong
kube-apiserver-extra-env: "TZ=Asia/Shanghai"
kube-scheduler-extra-env: "TZ=Asia/Shanghai"
![image](https://user-images.githubusercontent.com/88480631/147524697-2bd49e98-f4cc-4230-b816-b0b72b99952b.png)

**Comment by zuocg** [comment]
![image](https://user-images.githubusercontent.com/88480631/147524827-8f2e171b-4efa-4002-a774-d65f859b10c4.png)

**Comment by zuocg** [comment]
Effective service：
- cloud-controller-manager
- etcd
Inactive services：
- kube-apiserver
- kube-controller-manager
- kube-proxy
- kube-scheduler
![image](https://user-images.githubusercontent.com/88480631/147525692-3c3d0b3f-614d-4873-8fba-19b9e9bd3949.png)

**Comment by chewdevs** [comment]
I have the same issue. the TZ env var is set but timezone is still UTC.

**Comment by jmolinavizcaino** [comment]
I have exactly the same problem 

The TZ env var is set but timezone is still UTC.

Do somebody find any solution to this problem?

**Comment by jmolinavizcaino** [comment]
Hi;

I have had the same issue ( the TZ env var is set but timezone is still UTC)  when define the extra environment variable
kube-apiserver-extra-env: "TZ=Europe/Madrid"

Finally I resolved the issue deleting the kube-apiserver-extra-env configuration and adding the  kube-apiserver-extra-mount configuration in the next way:

kube-apiserver-extra-mount: "/usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro"

I think is necessary to have the tzdata Linux package in all nodes

**Comment by brandond** [comment]
Yes, you can't use symbolic tz names without the tzdb available. You can still set it to an offset (`EST+5`) or offset with dst start/end times (`EST+5EDT,M4.1.0/2,M10.5.0/2). 
Ref: https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_431.html

We can look at including tzdb in our Kubernetes images.
