### ISSUE TITLE
Stress Testing RKE2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#22]
We should do some load/stress testing of RKE2 as there may be a performance impact due to implemented crypto. It would be a good idea to do the following:

- Test with upstream tests (similar to what Hussein has done in the past with K3s)
- Test with Rancher with many clusters (harsher test, similar to what Dan has done in the past)

While testing consider that we may have a performance impact compared to k3s tests we have done. We should test when we have an alpha available and try to complete this within a couple of weeks well before beta release.

**Comment by cjellick** [comment]
@galal-hussein - I'm pretty sure you are working on this based on our convo yesterday. I'm moving it over to working for you

**Comment by galal-hussein** [comment]
Stress tests have passed on the following clusters:

- 100 nodes, 50 pod per node
- 500 nodes, 50 pod per node
- 1000 nodes, 50 pod per node
- 1500 nodes, 50 pod per node

the tests involves running [clusterloader 2](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2), which runs load tests on each cluster and collect metrics, it makes sure that API SLO calls are satisfied for each cluster

**Comment by brandond** [comment]
@galal-hussein do you have the recorded metrics around anywhere? I'd be curious to take a look at the results.
