### ISSUE TITLE
antrea CNI integration

### ISSUE THREAD

**Issue by jayunit100** [rancher/rke2#2201]
**Is your feature request related to a problem? Please describe.**

Feature: a `--antrea` as the CNI option, we discussed this on https://www.youtube.com/watch?v=JzLmsOqfiq0 :) 

**Describe the solution you'd like**

To do exactly what @luthermonson did on the antrea live show :), with less steps

**Describe alternatives you've considered**

Manual cni installation w/ the no-cni option, which works.

**Comment by zilmarr** [comment]
Any updates on this?

**Comment by brandond** [comment]
We are not currently planning on bundling any additional CNIs.

**Comment by lchunleo** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Feature: a `--antrea` as the CNI option, we discussed this on https://www.youtube.com/watch?v=JzLmsOqfiq0 :)
> 
> **Describe the solution you'd like**
> 
> To do exactly what @luthermonson did on the antrea live show :), with less steps
> 
> **Describe alternatives you've considered**
> 
> Manual cni installation w/ the no-cni option, which works.

is it possible to share the steps in the manual cni installation for antrea?
