### ISSUE TITLE
Remove `hostNetwork: true` from default ingress-nginx configuration

### ISSUE THREAD

**Issue by ron1** [rancher/rke2#2206]
**Is your feature request related to a problem? Please describe.**

Remove `hostNetwork: true` from default ingress-nginx configuration and instead rely exclusively on hostPorts. Graduated CNCF project Linkerd service mesh does not work with the ingress-nginx `hostNetwork` property set. Now that issue https://github.com/kubernetes/kubernetes/issues/23920# is resolved, RKE2 should no longer need to set `hostNetwork: true` in its ingress-nginx configuration since hostPorts now behave as expected.

Furthermore, it is problematic that for Kubernetes v1.21 and up, the NGINX ingress controller configurations for RKE and RKE2 are no longer consistent W.R.T the hostNetwork property. Specifically, for k8s 1.21+, RKE no longer runs in hostNetwork: true but uses hostPorts for port 80 and port 443. This was done so the admission webhook can be configured to be accessed using ClusterIP so it can only be reached inside the cluster. I believe RKE2 shares the same admission webhook concern as RKE. It make sense for RKE and RKE2 to configure their NGINX ingress controllers consistently to simplify the upgrade from RKE to RKE2.

**Describe the solution you'd like**

Remove the `hostNetwork: true` line from the relevant helm chart values artifact [here](https://github.com/rancher/rke2-charts/blob/9aff0f37fd3553da303c6aae4233b6d0664eaa37/packages/rke2-ingress-nginx/generated-changes/patch/values.yaml.patch#L57).

**Describe alternatives you've considered**

**Additional context**

**Comment by melkypie** [comment]
Any updates on this?

Currently when having `hostNetwork: true` enabled for nginx-ingress-controller means you are unable to configure Calico network policies for ingress if the traffic goes through the nginx-ingress-controller as it bypasses any defined policies. See https://github.com/projectcalico/calico/issues/4291#issuecomment-997214807
