### ISSUE TITLE
Master node fails to register if on different subnet

### ISSUE THREAD

**Issue by NosIreland** [rancher/rke2#2215]
**Environmental Info:**
RKE2 Version: 
v1.21.6+rke2r1 

Node(s) CPU architecture, OS, and Version: 
Linux master2 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
6 nodes, 3xMasters, 3xWorkers

**Describe the bug:**
The nodes are divided between 2 subnets. There are no firewall in between subnets.
2 Master nodes are running in subnet 172.16.1.0 when trying to register additional master node in subnet 192.168.1.0 the mater would not register and would get stuck with 'Waiting for node to be registered in Kubernetes' message in Rancher 2.6.2
If I move the node to same subnet as the other 2 master nodes it would register fine.
Worker nodes register fine in both subnets. 

**Steps To Reproduce:**

In Rancher GUI under Cluster management select cluster('rke2')  and select Registration. 
Step 1.  select 'etcd' and 'Control Plane' only
Show advanced 
Step 2. provide node name 'master1' and private ip '192.168.1.31'
Step3. Select Insecure and copy the command
`curl --insecure -fL https://192.168.1.20:7443/system-agent-install.sh | sudo  sh -s - --server https://192.168.1.20:7443 --label 'cattle.io/os=linux' --token jkms55nvrz6mzdc8pkkx6t2l4db9dxjqsglfttnwfglhx85dlckdlb --ca-checksum 3e303910203c76016f27c8c7d7dccfa6aa655f037adb5586550e52be2ee535e4 --etcd --controlplane --worker --internal-address 192.168.1.31 --node-name master1`
paste the command in the node 
The cluster state changes to provisioning
New node appears under Machines but is stuck with  'Waiting for node to be registered in Kubernetes' message 

**Expected behavior:**
Master node is added to cluster

**Actual behavior:**
Master node is not added to cluster

**Additional context / logs:**
`journalctl -u rke2-server &> rke2-server.log ` output attached
[rke2-server.log](https://github.com/rancher/rke2/files/7654773/rke2-server.log)

**Comment by brandond** [comment]
```
Dec 04 21:26:03 master1 rke2[2544]: time="2021-12-04T21:26:03Z" level=info msg="Adding member master1-a52d09fd=https://192.168.1.31:2380 to etcd cluster [master2-423431cd=https://172.16.1.31:2380 master4-9a36449d=https://172.16.1.32:2380]"
Dec 04 21:26:03 master1 rke2[2544]: time="2021-12-04T21:26:03Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```

Can you also collect the pod logs, as requested on Slack? Etcd isn't starting up for some reason.

**Comment by NosIreland** [comment]
I have torn cluster apart as there was smth not right with it. It was sluggish, dashboard-shell would timeout unless the pod was running on worker node that is on the same subnet as masters. 
I suspect it must be something todo with the network. I will need to do more testing
We can park this for now.
