### ISSUE TITLE
coredns autoscaler is over requests

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#2223]
**Environmental Info:**
RKE2 Version: 1.21.6-rk2r1

Node(s) CPU architecture, OS, and Version: 
x86_64, Ubuntu 20.04

**Describe the bug:**
CPU Request usage is above requested for rke2-coredns-rke2-coredns-autoscaler and over 90% of Limit.
I saw some oom kills as well. So requests should be slightly increased. 

Or is it possible to setup own requests/limits?

**Comment by brandond** [comment]
Can you show the resource utilization for the deployment on your cluster?

**Comment by xhejtman** [comment]
```
kubectl top pod rke2-coredns-rke2-coredns-autoscaler-78bdc5d6c-4dgz9 -n kube-system 
NAME                                                   CPU(cores)   MEMORY(bytes)   
rke2-coredns-rke2-coredns-autoscaler-78bdc5d6c-4dgz9   21m          16Mi  
```

I can provide additional info if needed, just say command.

**Comment by manuelbuil** [comment]
It is possible to request your own request/limits. Those are configurable via the helm chart https://github.com/rancher/rke2-charts/blob/main/charts/rke2-coredns/rke2-coredns/1.16.401-build2021111901/values.yaml#L295-L302 by using HelmChartConfig https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig
