### ISSUE TITLE
rke2 does not install on AWS Amazon Linux 2 kernel 4.14 and 5.10

### ISSUE THREAD

**Issue by asloan7** [rancher/rke2#2227]
RKE2 Version:  v1.20.12+rke2r1

current latest 5.10 and 4.14
AMI ID: amzn2-ami-kernel-5.10-hvm-2.0.20211201.0-x86_64-gp2 (ami-0ed9277fb7eb570c9)
AMI ID: amzn2-ami-hvm-2.0.20211201.0-x86_64-gp2 (ami-061ac2e015473fbe2)

sudo -i
export RKE2_VERSION="v1.20.12+rke2r1"
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=$RKE2_VERSION RKE2_KUBECONFIG_MODE="644" INSTALL_RKE2_TYPE=server sh -
[INFO]  using 1.20 series from channel stable
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                       | 3.7 kB  00:00:00
rancher-rke2-1.20-stable                                                                         | 2.9 kB  00:00:00
rancher-rke2-common-stable                                                                       | 2.9 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package rke2-server.x86_64 0:1.20.12~rke2r1-0.el7 will be installed

also tried:
curl -sfL https://get.rke2.io | RKE2_KUBECONFIG_MODE="644" INSTALL_RKE2_TYPE=server sh -
[INFO]  using 1.22 series from channel stable
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
rancher-rke2-1.22-stable                                                                         | 2.9 kB  00:00:00
rancher-rke2-common-stable                                                                       | 2.9 kB  00:00:00
rancher-rke2-1.22-stable/primary_db                                                              | 3.2 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package rke2-server.x86_64 0:1.22.4~rke2r1-0.el7 will be installed

-----

--> Finished Dependency Resolution
Error: Package: rke2-selinux-0.9-1.el7.noarch (rancher-rke2-common-stable)
           Requires: container-selinux >= 2:2.107-3
Error: Package: rke2-selinux-0.9-1.el7.noarch (rancher-rke2-common-stable)
Requires: selinux-policy-base >= 3.13.1-252
Installed: selinux-policy-targeted-3.13.1-192.amzn2.6.7.noarch (@amzn2-core)
  selinux-policy-base = 3.13.1-192.amzn2.6.7
Available: selinux-policy-minimum-3.13.1-192.amzn2.6.7.noarch (amzn2-core)
  selinux-policy-base = 3.13.1-192.amzn2.6.7
...
Error: Package: rke2-selinux-0.9-1.el7.noarch (rancher-rke2-common-stable)
  Requires: container-selinux < 2:2.164.2

------

yum install container-selinux
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                       | 3.7 kB  00:00:00
No package container-selinux available.
Error: Nothing to do

yum update selinux-policy-base
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
No packages marked for update

--------

Is there something that I should know?

**Comment by brandond** [comment]
```
Error: Package: rke2-selinux-0.9-1.el7.noarch (rancher-rke2-common-stable)
Requires: container-selinux < 2:2.164.2
```

cc @dweomer

**Comment by dweomer** [comment]
hmm, el7 is weird. will look at the install script (it should be picking el8, i think)

**Comment by dweomer** [comment]
@asloan7 a work-around right now might be to install the `rke2-selinux-0.9-1.el8` rpm before invoking the the installer

**Comment by brandond** [comment]
Yeah, `amzn2` isn't really either EL7 or EL8 but the EL8 is probably closer. With `AL2022` coming down the pipe we should probably take another look at what is the most appropriate EL target for these.

**Comment by asloan7** [comment]
I'm following a bit of what is here https://docs.rke2.io/install/methods/#enterprise-linux-8 and 
yum install rke2-selinux-0.9-1.el8

But still getting 
Error: Package: rke2-selinux-0.9-1.el8.noarch (rancher-rke2-common-latest)
           Requires: container-selinux >= 2:2.167.0-1
Error: Package: rke2-selinux-0.9-1.el8.noarch (rancher-rke2-common-latest)
           Requires: selinux-policy-base >= 3.13.1-252

And don't know how to find them to install them manually

**Comment by brandond** [comment]
It looks like Amazon Linux 2 has upgraded container-selinux and selinux-policy-base past a version that we currently support. Amazon Linux isn't technically on our support matrix, but we can see what we can do.

**Comment by asloan7** [comment]
Do you have a link to a list of supported OS versions?
Maybe I could try an older AL2 AMI
---
For fun I just tried the AL2022,
curl -sfL https://get.rke2.io | RKE2_KUBECONFIG_MODE="644" INSTALL_RKE2_TYPE=server sh -
[INFO]  finding release for channel stable
[INFO]  using 1.22 series from channel stable
Rancher RKE2 Common (stable)                                                            9.7 kB/s | 2.9 kB     00:00
Rancher RKE2 1.22 (stable)                                                              3.9 kB/s | 1.9 kB     00:00
Error:
 Problem: package rke2-server-1.22.4~rke2r1-0.el7.x86_64 requires rke2-common = 1.22.4~rke2r1-0.el7, but none of the providers can be installed
  - package rke2-common-1.22.4~rke2r1-0.el7.x86_64 requires rke2-selinux >= 0.3-1, but none of the providers can be installed
  - conflicting requests
  - nothing provides container-selinux >= 2.107-3 needed by rke2-selinux-0.4-1.el7.noarch
  - nothing provides container-selinux >= 2.107-3 needed by rke2-selinux-0.6-1.el7.noarch
  - nothing provides container-selinux >= 2.107-3 needed by rke2-selinux-0.7-1.el7.noarch
  - nothing provides container-selinux >= 2.107-3 needed by rke2-selinux-0.8-2.el7.noarch
  - nothing provides container-selinux >= 2:2.107-3 needed by rke2-selinux-0.9-1.el7.noarch
  - nothing provides container-selinux < 2:2.164.2 needed by rke2-selinux-0.9-1.el7.noarch

**Comment by brandond** [comment]
See the OS list here: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-2/

**Comment by asloan7** [comment]
I see you have ubuntu above Centos/RHEL on the OS list, is it the preferred OS?

**Comment by caroline-suse-rancher** [comment]
Closing due to age

**Comment by stackednerds** [comment]
I am facing this issue right now on amazon linux 2(karoo)
anyone knows the fix ?
