### ISSUE TITLE
Wrong images in rke2-images-multus.linux-amd64.txt

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2236]
Fix **Wrong images in rke2-images-multus.linux-amd64.txt** on branch **master**
* #2229

**Comment by rancher-max** [comment]
Validated can successfully use multus during airgap install with v1.22.4-rc1+rke2r3 via private registry. Confirmed it is using `rancher/hardened-multus-cni:v3.7.1-build20211119`
