### ISSUE TITLE
SELinux - RHEL8 policy

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#225]
It's expected that a few tweaks will be necessary for RHEL8 selinux policy rpm.
We will probably want to have a separate branch so we can have a separate stream for rhel8 and newer (el8) and rhel7 (el7).
We'll also accordingly need el7 rpm for selinux policy  for rhel7 and el8 rpm for selinux policy for rhel8

**Comment by Oats87** [comment]
@dweomer Are you aware of the changes that are necessary to make the el8 policy happy?

**Comment by dweomer** [comment]
Addressed in rancher/rke2-selinux#7

**Comment by ShylajaDevadiga** [comment]
Validated on rke2 version v1.18.8-beta20+rke2
Node OS: RHEL 7.8, RHEL 8
Basic testing on CentOS
On SELinux Enforced system, while deploying local-path-provisioner,  dir needs context label to be set. #364
```
chcon -t container_file_t -R /opt/local-path-provisioner
```
