### ISSUE TITLE
[release-1.20] RKE2 Ignores multiple endpoint setting of private registry servers

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2253]
Backport fix for **RKE2 Ignores multiple endpoint setting of private registry servers** to branch **release-1.20**
* #2159

**Comment by rancher-max** [comment]
Performed the same tests mentioned in https://github.com/rancher/rke2/issues/2159#issuecomment-995274601 using v1.20.13-rc1+rke2r2 and all were successful.
