### ISSUE TITLE
Ship bundles that adhere to semver to make upgrades work without workarounds

### ISSUE THREAD

**Issue by gaktive** [rancher/rke2#2272]
UI received a ticket regarding upgrades not working within RKE2 versions: https://github.com/rancher/dashboard/issues/4776

As noted in the comments, the UI is dependent on semver logic to know the steps to upgrade. So when UI sees the RKE2 flow to upgrade from `v1.21.7+rke2r2` to `v1.21.7-rc2+rke2r3`, the hyphen `-` actually is a separator for versions, meaning that per helm, this is actually a downgrade as `v1.21.7` (without the `-rc2+rke2r3`) is lower than `v1.21.7+rke2r2`.

UI can consider a hack to make this upgrade logic work but our preference is to have the plus `+` data before the `-` (e.g, `1.21.7+rke2r3-rc2`). @deniseschannon did mention that the current versioning is tied to Kubernetes pre-releases but she would like to see this changed.

I'm leaving a milestone off here for now since UI works off of Rancher releases.

**Comment by brandond** [comment]
Our GA releases have a + in them: `v1.21.7+rke2r1` or v1.21.7+k3s1. Only RCs have a hyphen, which goes before the plus. If you are seeing `v1.21.7rke2r1` anywhere (without either a + or -) then there's a bug.

Putting the RC **before** the release (in a position where it actually looks like the Kubernetes version is an RC) was a decision handed down from above (@cjellick and @ibuildthecloud if I remember correctly).

**Comment by deniseschannon** [comment]
@brandond I think that was overall a typo, but these are the RKE2 releases that are published in KDM. I updated to add in the `+` in the typo.

@cjellick @cwayne18 We can discuss in our integration meeting.

**Comment by gaktive** [comment]
reopen

**Comment by gaktive** [comment]
For @Sahota1225, I'll create a corresponding `rancher/rancher` ticket to track.

**Comment by caroline-suse-rancher** [comment]
Closing as complete
