### ISSUE TITLE
On cis hardened cluster , RKE2 should refuse to start if the etcd user and group doesn't exist on the host

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#2288]
**Environmental Info:**
RKE2 Version: 
Any version
v1.20.14-rc2+rke2r1, v1.21.8-rc2+rke2r1, v1.22.5-rc1+k3s1

Node(s) CPU architecture, OS, and Version: 
SLES 15 SP2

Cluster Configuration:
3 server, 1 agent CIS enabled cluster
profile: cis-1.5
profile: cis-1.6

**Describe the bug:**
As per the docs, RKE2 should refuse to start if the etcd user and group doesn't exist on the host
```
ps -ef|grep "rke2 server"
root      2247     1  0 Dec20 ?        00:04:15 /usr/local/bin/rke2 server
```

**Steps To Reproduce:**
Install rke2 on SLES 15 in CIS enabled mode

**Expected behavior:**
RKE2 should refuse to start as per the docs.

**Actual behavior:**
RKE2 starts normally. When running CIS scan 1.1.12 fails, as the etcd user is created in users group as the cis requirement is not met.
Scan report:
```
1.1.12 | Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
```
```
stat -c %U:%G /var/lib/rancher/rke2/server/db/etcd
etcd:users
```
```
cat /etc/passwd |grep tail -1
etcd:x:475:100:etcd user:/home/etcd:/sbin/nologin

cat /etc/group |grep 100
users:x:100:
```
https://docs.rke2.io/security/cis_self_assessment16/#1112

**Comment by brandond** [comment]
Huh, we've only ever checked for the user, not the group. Despite both the check and our docs referencing the group being required.

**Comment by rancher-max** [comment]
Validated using v1.23.1-rc1+rke2r1 following the same steps as noted in the issue
