### ISSUE TITLE
Automate the Go Update Process for RKE2 and Dependent Image Build Processes

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#2305]
RKE2 uses custom images to build itself as well as it's dependent components. A nonexhaustive list is below. These image build processes need to be updated with the latest Go version in association with what the correlated upstream version is using. An automated process needs to be developed to ease the burden of the current manual update process.

* github.com/rancher/image-build-kubernetes
* github.com/rancher/image-build-flannel
* github.com/rancher/image-build-containerd
* github.com/rancher/image-build-base
* github.com/rancher/image-build-runc
* github.com/rancher/image-build-coredns
* github.com/rancher/image-build-calico
* github.com/rancher/image-build-ib-sriov-cni 
* github.com/rancher/image-build-sriov-cni 
* github.com/rancher/image-build-sriov-network-resources-injector 
* github.com/rancher/image-build-etcd
* github.com/rancher/image-build-k8s-metrics-server 
* github.com/rancher/image-build-dns-nodecache
* github.com/rancher/image-build-rke2-cloud-provider 
* github.com/rancher/image-build-cilium
* github.com/rancher/image-build-crictl

**Comment by nikolaishields** [comment]
After working on a prototype I discovered that there may be more image repositories that should be included in the list.
```
image-build-calico
image-build-base
image-build-etcd
image-build-containerd
image-build-k8s-metrics-server
image-build-kubernetes
image-build-runc
image-build-kube-proxy
image-build-coredns
image-build-ib-sriov-cni
image-build-sriov-cni
image-build-sriov-network-resources-injector
image-build-sriov-operator
image-build-sriov-network-device-plugin
image-build-multus
image-build-flannel
image-build-dns-nodecache
image-build-cni-plugins
image-build-rke2-cloud-provider
image-build-crictl
image-build-cilium
image-build-cilium-image-tools
image-build-coreos-flannel
image-build-skel
image-build-helm-controller
```

**Comment by brandond** [comment]
The authoritative list of build repos for RKE2 is at https://github.com/rancher/rke2/blob/master/developer-docs/image_sources.md - if you think you've found some that aren't on that page, please add them.

**Comment by nikolaishields** [comment]
Thanks @brandond, will do.

**Comment by briandowns** [comment]
This has been completed and is part of the ECM Distro Tools.
