### ISSUE TITLE
Rke2 cannot use insecure-registry

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rke2#2317]
version：rke2 version v1.22.5+rke2r1 (ce3e572376cbb1d8157f46e2ae29d7d7834067f1)

Harbor configuration using the port 80, not the TLS .rke2 configuration/etc/rancher/rke2 /registries.yaml is as follows:
```
mirrors:
  "172.16.1.208":
    endpoint:
      - "http://172.16.1.208"
configs:
  172.16.1.208:
    tls:
      insecure_skip_verify: true
```

Harbor address is 172.16.1.208

Rke2-server startup error：

```
Using private registry config file at /etc/rancher/rke2/registries.yaml"
Dec 30 14:55:08 rke-node4 rke2[14110]: time="2021-12-30T14:55:08Z" level=info msg="Pulling runtime image 172.16.1.208/rancher/rke2-runtime:v1.22.5-rke2r1"
Dec 30 14:55:08 rke-node4 rke2[14110]: time="2021-12-30T14:55:08Z" level=warning msg="Failed to get image from endpoint: Get \"https://172.16.1.208/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": dial tcp 172.16.1.208:443: connect: connection refused"
Dec 30 14:55:08 rke-node4 rke2[14110]: time="2021-12-30T14:55:08Z" level=warning msg="Failed to get image from endpoint: Get \"https://172.16.1.208/v2/\": dial tcp 172.16.1.208:443: connect: connection refused; Get \"https://172.16.1.208/v2/\": dial tcp 172.16.1.208:443: connect: connection refused"
Dec 30 14:55:08 rke-node4 rke2[14110]: time="2021-12-30T14:55:08Z" level=fatal msg="failed to get runtime image 172.16.1.208/rancher/rke2-runtime:v1.22.5-rke2r1: all endpoints failed: Get \"https://172.16.1.208/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": dial tcp 172.16.1.208:443: connect: connection refused; Get \"https://172.16.1.208/v2/\": dial tcp 172.16.1.208:443: connect: connection refused; Get \"https://172.16.1.208/v2/\": dial tcp 172.16.1.208:443: connect: connection refused"
```

**Comment by brandond** [comment]
It looks like the harbor registry is redirecting you to `https://172.16.1.208/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry` in order to obtain a token. Can you show the output of:

```bash
curl -vs http://172.16.1.208/v2/rancher/rke2-runtime/manifests/v1.22.5-rke2r1
```

**Comment by smallteeths** [comment]
I created an HTTP Harbor private registry for testing. When I tried to configure this Harbor private registry using Rancher to create RKE2, I obtained different results using two different configuration methods.

Configuration 1:
#cluster config
```
machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          system-default-registry: siye.io
    registries:
      configs:
        13.58.223.173:8080:
          insecureSkipVerify: true
      mirrors:
        siye.io:
          endpoint:
            - http://13.58.223.173:8080
```
#registries.yaml
```
{"configs":{"13.58.223.173:8080":{"auth":null,"tls":{"ca_file":"","cert_file":"","key_file":"","insecure_skip_verify":true}}},"mirrors":{"siye.io":{"endpoint":["http://13.58.223.173:8080"]}}}
```

The cluster creation was successful.

Configuration 2:
```
machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          system-default-registry: 13.58.223.173:8080
    registries:
      configs:
        13.58.223.173:8080:
          insecureSkipVerify: true
      mirrors:
        13.58.223.173:8080:
          endpoint:
            - http://13.58.223.173:8080
```
#registries.yaml
```
{"configs":{"13.58.223.173:8080":{"auth":null,"tls":{"ca_file":"","cert_file":"","key_file":"","insecure_skip_verify":true}}},"mirrors":{"13.58.223.173:8080":{"endpoint":["http://13.58.223.173:8080"]}}}
```

The cluster creation failed. 

To view the logs using journalctl -xef -u rancher-system-agent.service`

<img width="1780" alt="截屏2023-05-23 下午3 18 51" src="https://github.com/rancher/rke2/assets/27733391/ab961ecf-3860-4c3d-96c4-c978555cc763">

I don't quite understand why Configuration 2 didn't use the endpoint and defaulted to using HTTPS.

**Comment by iobelika** [comment]
I think for an HTTP without authentication private registry you should only use:

`mirrors:
  "172.16.1.208":
    endpoint:
      - "http://172.16.1.208"`

without anything else.
link: https://docs.rke2.io/install/containerd_registry_configuration

**Comment by smallteeths** [comment]
> I think for an HTTP without authentication private registry you should only use:
> 
> ```
> mirrors:
> "172.16.1.208":
>     endpoint:
>       - "http://172.16.1.208"
> ```
> 
> without anything else. link: https://docs.rke2.io/install/containerd_registry_configuration

Oh, thank you. I understand now.  TLS can't work with HTTP. So tls settings should be removed.
