### ISSUE TITLE
Feature Gate PodSecurity not handled correctly

### ISSUE THREAD

**Issue by majeinfo** [rancher/rke2#2318]
**Environmental Info:**
rke2 version v1.22.5-rc2+rke2r1 (6f2632aaae172dda758813c1dc3c8928ba36682f)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 
Linux ip-172-20-0-140 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 masters, 1 worker

**Describe the bug:**
I tried to active the PodSecurity admission controller, so I modified /etc/rancher/rke2/config.yaml file to add these lines:
kube-apiserver-arg:
  - --feature-gates=EphemeralContainers=true,JobTrackingWithFinalizers=true,PodSecurity=true

Once the apiserver is restarted (I rebooted the host), one can see that the wrong admission controller is enabled :

kube-apiserver --cloud-provider=aws --cloud-config= --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,rke2 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction,PodSecurityPolicy ....

**Steps To Reproduce:**
Update config.yaml as specified above and reboot the host

**Expected behavior:**
The admission controller name should be PodSecurity, not PodSecurityPolicy

**Actual behavior:**
PodSecurityPolicy loaded ! (I guess there is a wrong regexp or substring comparison somewhere...)

**Additional context / logs:**

**Comment by brandond** [comment]
You're adding things to the feature-gates flag but appear to be looking at the value of the enable-admission-plugins flag?

**Comment by majeinfo** [comment]
Quoting the official documentation :
"""
In v1.22, the PodSecurity feature gate is an Alpha feature and must be enabled in kube-apiserver in order to use the built-in admission plugin.

--feature-gates="...,PodSecurity=true"
"""

If I add this feature gate with rke2  v1.22.5-rc2+rke2r1, it activates the PodSecurityPolicy admission controller (as showed by "ps -edf | grep apiserver").
If I add this feature gate to the apiserver on a cluster built with kubeadm, it activates the PodSecurity controller.

**Comment by brandond** [comment]
Just to be more clear about what I was saying, adding things to the `--feature-gates` flag does not add anything to `--enable-admission-plugins`. Kubeadm may do that, but RKE2 does not. If you want to set both the `--feature-gates` and `--enable-admission-plugins` flags, you must do so yourself.
