### ISSUE TITLE
Need ability to disable packaged components (similar to k3s --disable)

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#232]
rke2 does not currently allow disabling any of the packaged components (exclusively HelmChart manifests, at the moment). The k3s `--disable` flag is currently hidden and uses a hardcoded value, since we're overloading it to disable the k3s packaged components.

We should:
1. Put the k3s manifests and static content inside a build flag so that we can disable them when compiling rke2
1. Stop using the `--disable` flag as an internal flag to k3s, and expose it to the CLI as a string slice (same as how it behaves in k3s).  We should not validate or otherwise restrict the values, as we should be able to add (and support disabling) bootstrap image content without modifying a static value list.
1. Check for matching file basenames [when extracting content from the bootstrap image](https://github.com/rancher/rke2/blob/master/pkg/bootstrap/stage.go#L87), and (if matched), skip extracting the file.
1. To make this identical to the k3s `--disable` flag we would also need to actively remove any matching files from the manifests directory, if found.

**Comment by cjellick** [comment]
I'm not going to close this, but I think we dont need this for GA because we have the .skip behavior, ie:
```
mkdir -p /var/lib/rancher/rke2/server/manifests/charts/; touch /var/lib/rancher/rke2/server/manifests/charts/rke2-canal-chart.yml.skip
```

That just needs clearly documented.

**Comment by cjellick** [comment]
@davidnuzik to open a documentation issue

**Comment by davidnuzik** [comment]
Created https://github.com/rancher/rke2/issues/257

**Comment by cjellick** [comment]
Moving into GA since @brandond has a fix in

**Comment by brandond** [comment]
The k3s PR takes care of 1. on the list; the remainder should be fairly easy to do as well since I've been poking about in the bootstrap code recently.

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.18.9-beta21+rke2

Updated config.yaml wtih disable: rke2-ingress-nginx

rke2-ingress-ngimx chart is not deployed
```
helm ls -n kube-system
NAME               	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
rke2-canal         	kube-system	1       	2020-09-29 22:50:24.194218136 +0000 UTC	deployed	rke2-canal-v3.13.3          	v3.13.3    
rke2-coredns       	kube-system	1       	2020-09-29 22:50:24.090076152 +0000 UTC	deployed	rke2-coredns-1.10.101       	1.6.9      
rke2-kube-proxy    	kube-system	1       	2020-09-29 22:50:24.087371431 +0000 UTC	deployed	rke2-kube-proxy-v1.18.9     	v1.18.9    
rke2-metrics-server	kube-system	1       	2020-09-29 22:50:58.468864421 +0000 UTC	deployed	rke2-metrics-server-2.11.100	0.3.6  

kubectl get pods -A
NAMESPACE     NAME                                         READY   STATUS      RESTARTS   AGE
kube-system   etcd-ip-172-31-12-23                         1/1     Running     0          49s
kube-system   helm-install-rke2-canal-f6s9d                0/1     Completed   0          89s
kube-system   helm-install-rke2-coredns-pmrwz              0/1     Completed   0          89s
kube-system   helm-install-rke2-kube-proxy-kmzk5           0/1     Completed   0          89s
kube-system   helm-install-rke2-metrics-server-x7dvh       0/1     Completed   0          89s
kube-system   kube-apiserver-ip-172-31-12-23               1/1     Running     0          32s
kube-system   kube-controller-manager-ip-172-31-12-23      1/1     Running     0          103s
kube-system   kube-proxy-2mr7z                             1/1     Running     0          70s
kube-system   kube-scheduler-ip-172-31-12-23               1/1     Running     0          103s
kube-system   rke2-canal-hbfs2                             2/2     Running     0          69s
kube-system   rke2-coredns-rke2-coredns-649896d599-vb9bj   1/1     Running     0          70s
kube-system   rke2-metrics-server-5d8c549c9f-2gmjh         1/1     Running     0          36s
```
