### ISSUE TITLE
Update calico to v3.21.2

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2321]
**Is your feature request related to a problem? Please describe.**

I would like to use the latest version of Calico

**Describe the solution you'd like**

I would like to use the latest version of Calico

**Describe alternatives you've considered**

Using older versions

**Additional context**

https://github.com/rancher/rke2-charts/pull/204

**Comment by rancher-max** [comment]
#### Validated using v1.23.1-rc1+rke2r2

- 2 daemonsets, `calico-node` and `calico-windows-upgrade`, using expected images: `docker.io/rancher/mirrored-calico-node:v3.21.2` and `docker.io/rancher/mirrored-calico-windows-upgrade:v3.21.2`
- 2 deployments,`calico-kube-controllers` and `calico-typha`, using expected images: `docker.io/rancher/mirrored-calico-kube-controllers:v3.21.2` and `docker.io/rancher/mirrored-calico-typha:v3.21.2`
- Network checks continue to work
