### ISSUE TITLE
Use of --agent-token prevents additional servers from joining the cluster

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2323]
When the initial server is started with --agent-token, and this agent-only token does not match the server --token value, additional servers cannot join the cluster. This is due to the joining server incorrectly using the agent username, but the server token, when validating that the local configuration matches the existing server.

This affects the most recent round of releases, all the way back to the 1.20 branch:
* v1.20.14+rke2r1
* v1.21.8+rke2r1
* v1.22.5+rke2r1
* v1.23.1+rke2r1

On the Rancher side we have a related issue:
* https://github.com/rancher/rancher/issues/36051

There is a related but separate issue with the recently added `secrets-encrypt` subcommands allowing use of agent credentials to modify server encryption configuration, but this does not affect node join.

**Comment by ekarlso** [comment]
Is there any workaround for this?

**Comment by brandond** [comment]
Set the agent token to the same value as the token, or downgrade.

**Comment by rancher-max** [comment]
#### Validated in v1.20.14-rc1+rke2r2, v1.21.8-rc1+rke2r2, v1.22.5-rc1+rke2r2, and v1.23.1-rc1+rke2r1

- Can still use only `token` (don't need to pass agent-token)
- servers are required to have both the same token and agent-token values, and when supplying those they join successfully
```
# example config.yaml, server1
token: test
agent-token: secret
```
```
# example config.yaml, server2
token: test
agent-token: secret
server: https://server1ip:9345
```
- Validated can provision multi-server clusters in rancher (v1.21 and v1.22 only). Configuration: 3 nodes all roles, 2 nodes etcd only, 1 node cp only, 1 node worker only
