### ISSUE TITLE
how to change pod/service CIDR on an already deployed cluster

### ISSUE THREAD

**Issue by slavonicsniper** [rancher/rke2#2326]
**Is your feature request related to a problem? Please describe.**
I tried to change the pod/service CIDR range on an already deployed cluster. After restarting the rke2-server, the range is changed but the whole cluster is broken as the pods with the old range were not recreated. Is it possible to do that via rke2?

**Describe the solution you'd like**
Be able to change the pod/service CIDR range on an already deployed cluster.

**Describe alternatives you've considered**
Manually deleting the pods so new pods with the new CIDR range are created but that does not work because cluster is already broken.

**Additional context**

**Comment by brandond** [comment]
Changing CIDRs on an existing cluster is not well supported; you should decide on what CIDRs you will use before starting the cluster the first time. Addresses and blocks out of the CIDR ranges are allocated by Kubernetes as nodes and services are deployed, and there is no logic to automatically re-allocate them if the ranges change.
