### ISSUE TITLE
Add CI testing for Windows workloads

### ISSUE THREAD

**Issue by cwayne18** [rancher/rke2#2337]
We've missed a couple windows-related bugs with specific configurations in the past, so I think it's time to invest some cycles in adding more robust CI for Windows. Lots of times we can break Windows making what we'd consider un-related changes, so I don't think its tenable to just ask QA to test Windows while making windows-specific changes.

**Comment by katran001** [comment]
Since this wasn't a part of the OS testing in the immediate roadmap for E2E tests, Derek will prioritize this action item in the next sprint planning. Most likely within 2-3 weeks. Moving this to the next milestone

**Comment by dereknola** [comment]
Closing this a complete, E2E testing is now being run.
