### ISSUE TITLE
Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input seen in kubelet.log

### ISSUE THREAD

**Issue by superseb** [rancher/rke2#234]
* Install rke2 on Ubuntu 18.04 using https://github.com/rancher/rke2/blob/b24f1e24dfa891d31560e1779ecf973b8b2200e5/install.sh and command 

```
INSTALL_RKE2_VERSION=v1.18.4-beta8+rke2 ./install.sh
```

* Check contents of `/var/lib/rancher/rke2/agent/logs/kubelet.log` after all pods are launched
* See these lines every X seconds
```
E0826 14:16:26.736905    9820 driver-call.go:266] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
W0826 14:16:26.736918    9820 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
E0826 14:16:26.736941    9820 plugins.go:729] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input
```

There seems to be something broken around flexvol-driver container.

* No command specified to launch for the init container? https://github.com/rancher/rke2-charts/blob/master/packages/rke2-canal/charts/templates/daemonset.yaml#L88
* Compiled binary not in expected place? https://github.com/rancher/image-build-calico/blob/master/Dockerfile#L49

**Comment by davidnuzik** [comment]
In for GA, but not a blocker. This is a nice-to-have.

**Comment by brandond** [comment]
I had done a bit of research on this before it was reassigned. I don't think it's an error, but it is irritating.

The kubelet probes all built-in volume plugins at startup to see which ones are available. That is done in [plugins.go](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/volume/plugins.go#L731). The flexvolume plugin lists all the subdirectories in the volume plugin path, and tries to run the plugin binary with a single argument of `init`. This is done in [flexvolume/probe.go](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/volume/flexvolume/probe.go#L102)

The problem here is that we have an empty plugin directory getting created at `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/`. Because it exists, it is checked, but we get an error because the `uds` binary does not exist. I'll see if I can figure out where this directory is coming from.

**Comment by brandond** [comment]
Oh, this is coming from Canal. It mounts a HostPath volume of type DirectoryOrCreate, but creating that directory without a corresponding binary causes the error described above.

```yaml
    - hostPath:
        path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
        type: DirectoryOrCreate
      name: flexvol-driver-host
```

**Comment by brandond** [comment]
rke2 has a unified calico image, while upstream uses separate image for each component. Our image's entrypoint is just a shell, so the initcontainer isn't installing them image. We need to have the flexvol-driver container run `/usr/local/bin/flexvol.sh` to drop the uds binary.

**Comment by brandond** [comment]
Testing with modified chart, kubelet.log shows:

```
I0918 16:19:31.421696   15523 plugins.go:644] Loaded volume plugin "flexvolume-nodeagent/uds"
```

**Comment by rancher-max** [comment]
I still see this behavior on `v1.18.9-beta21+rke2`. Log shows many errors of:
```
E0930 14:55:08.862291    5131 plugins.go:731] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input
E0930 14:55:08.862509    5131 driver-call.go:266] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
W0930 14:55:08.862516    5131 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
```

Performed install using the following commands:
```
curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh -o install.sh && \
chmod +x install.sh

sudo INSTALL_RKE2_VERSION=v1.18.9-beta21+rke2 INSTALL_RKE2_METHOD='tar' ./install.sh

sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
```

**Comment by brandond** [comment]
@rancher-max I am NOT seeing this on my side. Can you share the output from this command your test node?
`KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/bin/kubectl describe pods -n kube-system rke2-canal- | grep -A 22 flexvol-driver:`

**Comment by rancher-max** [comment]
```
$ KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/bin/kubectl describe pods -n kube-system rke2-canal- | grep -A 22 flexvol-driver:
  flexvol-driver:
    Container ID:  containerd://63430ad5617c559a1cad6e890f9ec05b07f2d4d8e4fd52e64e51ee65d8416f5d
    Image:         rancher/hardened-calico:v3.13.3
    Image ID:      docker.io/rancher/hardened-calico@sha256:6d2cd61a338bff0868a42ad9e35808f8f695481133f1619dd1720025fc81db60
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/flexvol.sh
      -s
      /usr/local/bin/flexvol
      -i
      flexvoldriver
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 30 Sep 2020 14:55:08 +0000
      Finished:     Wed, 30 Sep 2020 14:55:08 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from canal-token-g2697 (ro)
```

**Comment by brandond** [comment]
OK, so it is getting run with the correct arguments, and the file is being created, despite the kubelet saying it doesn't exist.
```
fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory
```

Can you confirm that this message is from the current run? Another fun thing is that this path doesn't cleaned up by rke2-uninstall.sh so you have to delete it manually to test.

**Comment by brandond** [comment]
@cjellick I am tempted to just remove this whole bit. As per the Calico documentation, this unix datagram socket (uds) is only necessary if you're using istio. The UDS is the bridge between dikastes inside the container, and felix on the node. Since we're not doing full isito and injecting the envoy+dikastes sidecars into the pod, this socket (and the flexvol driver) are unncessary.

![arch.png](https://github.com/projectcalico/app-policy/raw/master/docs/arch.png)

**Comment by davidnuzik** [comment]
FYI: Istio needs to work on any supported downstream cluster in Rancher (K3s, RKE2, etc).
@rancher-max is a good resource to help with testing on Rancher.

cc: @galal-hussein

**Comment by galal-hussein** [comment]
@rancher-max so I believe that pr https://github.com/rancher/rke2-charts/pull/20 solved the issue, however you may see the error at first but it will stop after the flex vol driver initialize and drop the binary, I will move the issue to to-test and open another one for Istio to make sure its working on k3s/rke2

**Comment by rancher-max** [comment]
When building rke2 from master I still see many logs of the Flexvolume error. Eventually the log stops, but the functionality looks exactly the same in master build `v1.18.10-dev+13f4ce97` as in latest release: `v1.18.10+rke2r1`. Also looks the same as in the version this was previously found in, `v1.18.9-beta21+rke2`

When I inspect `daemonset.apps/rke2-canal` in all of these versions, I see the command present that was added in the mentioned PR:
```
flexvol-driver:
    Image:      rancher/hardened-calico:v3.13.3
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/flexvol.sh
      -s
      /usr/local/bin/flexvol
      -i
      flexvoldriver
    Environment:  <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
```

@galal-hussein Is this expected? Install when not building from master was done with `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.18.10+rke2r1 INSTALL_RKE2_METHOD='tar' sh -`

**Comment by brandond** [comment]
Yes, you'll get the error until the init container runs to drop the binary. If we're going to keep this around I will probably fix the image so that it doesn't create the plugin directory so far in advance of the binary being dropped.

**Comment by rancher-max** [comment]
Since it's expected I will close this out. @brandond I can open a new issue for fixing the image if you'd like?
