### ISSUE TITLE
etcd-snapshot subcommand does not out debug logs even when `--debug` flag is provided

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#2343]
**Environmental Info:**
RKE2 Version: 

Master Branch

Node(s) CPU architecture, OS, and Version: 

Single node 

**Describe the bug:**

With a running rke2 server, calling `rke2 etcd-snapshot --debug` does not correctly output debug logs.

**Steps To Reproduce:**

- Installed RKE2: 
- Run any cluster
- Attempt to save a snapshot with the `--debug` flag set in either CLI or config.yaml

**Expected behavior:**

All rke2 subcommands that support debug flag should output debug logs

**Actual behavior:**

Only server and agent output debug logs with the flag set.
etcd-snapshot and others do not.

**Additional context / logs:**

Discovered while looking into https://github.com/rancher/rke2/issues/2341

**Comment by rancher-max** [comment]
Validated using v1.23.2-rc2+rke2r1 that passing the `--debug` flag to the etcd-snapshot subcommand shows debug logs now. See command and snippet from the end of the output:

```
$ sudo rke2 etcd-snapshot --debug
...
INFO[0000] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
DEBU[0000] core.Factory is initialized                  
DEBU[0000] Attempting to reconcile etcd snapshot data for configmap generation 0 
DEBU[0000] Updating snapshot ConfigMap (rke2-etcd-snapshots) with 1 entries 
INFO[0000] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete
```
