### ISSUE TITLE
[release-1.22] Update packaged containerd and etcd

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2348]
* containerd 1.5.9 - fix (previously patched in our fork) for CVE: GHSA-mvff-h3cj-wj9c
* etcd 3.5.1 - fix for https://github.com/etcd-io/etcd/issues/13196

Requires K3s pull-through as well:
* https://github.com/k3s-io/k3s/issues/4941

**Comment by rancher-max** [comment]
#### Validated on v1.22.6-rc1+rke2r1

- etcd pod uses expected image: `index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112`
- container-runtime on the nodes is using the correct version: `containerd://1.5.9-k3s1`
- sonobuoy checks continue to pass and checks around etcd (cluster reset and restore) continue to pass
