### ISSUE TITLE
Pod Security Standards?

### ISSUE THREAD

**Issue by liyimeng** [rancher/rke2#2387]
From k8s 1.22, Pod Security Standards is introduced to replace Pod Security Policies,  see https://kubernetes.io/docs/concepts/security/pod-security-standards/

Has rke2 v1.22, v1.23 adapt this change?

**Comment by brandond** [comment]
Anything available in upstream Kubernetes is available in RKE2. The CIS Benchmark for Kubernetes hasn't picked up on Pod Security Standards yet, so there's not anything built into our RKE2-specific hardening, which relies on the benchmark for guidance.

**Comment by liyimeng** [comment]
@brandond Thanks for clarification!

**Comment by liyimeng** [comment]
@brandond PSA seem might clean to use https://kubernetes.io/docs/tutorials/security/cluster-level-pss/ 
Is it possible for me to disable PSP and use PSA for now?

**Comment by brandond** [comment]
You could, but it wouldn't pass a CIS validation since CIS standard still asks for PSPs.

**Comment by liyimeng** [comment]
@brandond I got that. I expect rke2 will adapt PSA soon since PSP is to remove in a year.  Am I right? :) 
Anyway I just wanna play around and study, not have it in the any production environment yet.  However, I could not find any doc to disable psp according text here https://github.com/rancher/rke2/blob/master/docs/install/install_options/server_config.md 

Do you know how to do it?

**Comment by brandond** [comment]
We will follow upstream's deprecation timeline for removal of PSPs. When the CIS Benchmark for Kubernetes updates to reference PSAs then we will probably offer a --profile value that uses PSAs instead.

**Comment by sylvainOL** [comment]
Hello,
CIS benchmark with Pod Security Standards is out since april with an update mid may. 
Do you know when RKE2 will support this profile?
Since I have several components with specific PSP, it would be great to have time to migrate before 1.25 :)

thanks

**Comment by dsmithbauer** [comment]
Bump. Any update on this?

**Comment by brandond** [comment]
https://docs.rke2.io/security/cis_self_assessment123/
