### ISSUE TITLE
with-node-id not working as expected

### ISSUE THREAD

**Issue by powellchristoph** [rancher/rke2#2390]
**Environmental Info:**
RKE2 Version: 
v1.22.4+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux test-worker-002 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers 2 workers

**Describe the bug:**
Attempting to leverage the [documented](https://docs.rke2.io/advanced/#how-agent-node-registration-works) `--with-node-id` flag within the yaml config file.

**Steps To Reproduce:**
- Installed RKE2: Update yaml config file with
`with-node-id: True`

**Expected behavior:**
A unique node ID can be appended to the hostname.

**Actual behavior:**
The agent skips the flag.

**Additional context / logs:**
```
Jan 24 22:59:31 test-worker-002 rke2[1521]: time="2022-01-24T22:59:31Z" level=warning msg="Unknown flag --with-node-id found in config.yaml, skipping\n"
```

**Comment by brandond** [comment]
This was probably unintentionally carried over when initially creating basic RKE2 documentation from the K3s docs. RKE2 has never supported the --with-node-id flag.

**Comment by brandond** [comment]
Docs change only; no test needed.
