### ISSUE TITLE
From-scratch base images

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#240]
UBI7 is not desirable for domestic federal use cases in the long term. There is an interest to have from-scratch images.

**Comment by davidnuzik** [comment]
Updated title and summary. from-scratch is what we will go with.

**Comment by Oats87** [comment]
After discussion, we are going to remain on UBI 7 for the foreseeable future. We can entertain the idea of moving to UBI8 if necessary.

**Comment by cjellick** [comment]
So now we need to decide between UBI 7, UBI 8, scratch, and SLE BCI

**Comment by caroline-suse-rancher** [comment]
We are now 100% SLE BCI - closing
