### ISSUE TITLE
Cannot restore backups from other clusters

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#2410]
**Environmental Info:**
RKE2 Version:  1.21.5rke2r2

Node(s) CPU architecture, OS, and Version: Ubuntu 20.04 AMD64

**Describe the bug:**
If you need to restore a backup into a new cluster, the backup will fail due to the node token differing. This is a major problem as if you suffer a catastrophic failure and need to restore on new hosts, you cannot.

**Steps To Reproduce:**
1. Create an RKE2 cluster
2. Back it up
3. Delete it
4. Create another RKE2 cluster
5. Try to restore it with the previous backup

**Expected behavior:**
The restore completes

**Actual behavior:**
When attempting to restore RKE2 into another cluster, the process fails with "bootstrap data is already found and encrypted with a different token".

**Additional context / logs:**
Tested this using Rancher 2.6.4

**Comment by briandowns** [comment]
Hi @braunsonm , we encrypt the boostrap data with the token to protect it from leaks since it contains the CAs for the cluster. You'll need the token that was used with that cluster initially to get the cluster up and running again from a snapshot restore.

**Comment by braunsonm** [comment]
Hey @briandowns 
The problem is this doesn't seem possible to provide in rancher? If you create the new cluster with Rancher it doesn't try any other node tokens. 

Also is there a CLI flag to provide the token if you don't deploy with Rancher?

**Comment by briandowns** [comment]
The former should probably be brought up in an issue in the rancher repo. 

As for the latter, there's a flag on the `server` command to provide the token.

```sh
$ rke2 server -h | grep token
   --token value, -t value                       (cluster) Shared secret used to join a server or agent to a cluster [$RKE2_TOKEN]
```

This can also be provided in a config file.

**Comment by braunsonm** [comment]
Ah okay great I didn't realize it could be used during restore too. Might be worth a mention in the docs? The CLI output as you put only mentions during joining of nodes.

I'll leave that up to you though and I've raised an issue with Rancher about the restore feature they have.
