### ISSUE TITLE
[DOCS] Adding kubectl details to Quick Start Guide

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/rke2#2420]
**Expected behavior:**
https://docs.rke2.io/install/quickstart/
Does not contain a follow-up on how to interact with the installed system or how to verify further nodes have joined the cluster.

Perhaps adding /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/.../rke2.yaml get nodes
would highlight how to execute commands.

Additionally, it would be of immense help to advise how to add kubectl to the path and rke2.yaml to ~/.kube/config

**Actual behavior:**
https://docs.rke2.io/install/quickstart/
Points to be binaries path and the kubeconfig path but is not clear on using the --kubeconfig flag or how to get started with the cluster.

**Comment by Martin-Weiss** [comment]
This is how I do it (on SLES):

```
ln -s /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl
/usr/local/bin/kubectl completion bash > /usr/share/bash-completion/completions/kubectl
chmod 644 /usr/share/bash-completion/completions/kubectl
```

And then in any session:

```
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
kubectl..
```

Obviously this requires the user to have read access to /etc/rancher/rke2/rke2.yaml
