### ISSUE TITLE
Add CIS scan to CI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#243]
We should consider adding cis scan to CI. Before taking this on we should think on this and determine what the pros/cons of this are. Is there a reason we would not want to do this?

**Comment by cjellick** [comment]
I think this could be part of QA's validation automation. We'll discuss in a design session. We had initially agreed to assign to @bmdepesa, but I think i'm going to hold off on that.

**Comment by caroline-suse-rancher** [comment]
@rancher-max do you know if this has been implemented yet?

**Comment by rancher-max** [comment]
I don't think it has yet

**Comment by caroline-suse-rancher** [comment]
Closing as CIS scanning shouldn't really be a part of CI, and we already do CIS scans as a part of each patch validation
