### ISSUE TITLE
[Release 1.22] Upgrade calico

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2431]
**Environmental Info:**
RKE2 Version: 1.22

**Describe the bug:**

According to calico's documentation, calico v3.20 was not tested on k8s 1.22 [1]. Therefore, we should move to at least calico v3.21 to comply with the upstream recommendation, even though we haven't detected any issue.

[1] - https://projectcalico.docs.tigera.io/archive/v3.20/getting-started/kubernetes/requirements

**Comment by rancher-max** [comment]
#### Validated using v1.22.7-rc2+rke2r1

- All calico resources are using `v3.21.4`
- Networking checks continue to function correctly
