### ISSUE TITLE
[Question/Feature] Replace master nodes

### ISSUE THREAD

**Issue by albgus** [rancher/rke2#2441]
**Is your feature request related to a problem? Please describe.**
I am trying to re-install the master nodes of a RKE2 cluster. The idea is to be able to replace the nodes one by one until all the nodes are deployed on an updated image. To achieve this I would need to be able to remove the existing node first, before re-joining it to the cluster.

I'm not sure if this is possible or not. I can't find any mention of how to remove nodes in the docs, however I found a reference in this GitHub issue: https://github.com/rancher/rke2/issues/1959 which indicates that it should be possible to run `kubectl delete node master01`, this does not appear to have worked.

After stopping the old node and running `kubectl delete <old-node-name>`, the remaining etcd nodes are attempting to contact it:

```
{"level":"warn","ts":"2022-02-08T11:04:11.083Z","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"10.130.10.190:54318","server-name":"","error":"read tcp 10.130.10.234:2379->10.130.10.190:54318: read: connection reset by peer"}
{"level":"warn","ts":"2022-02-08T11:04:12.780Z","caller":"rafthttp/probing_status.go:70","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"a70cf5ef44c4a1a4","rtt":"1.111939ms","error":"dial tcp 10.130.10.190:2380: connect: connection refused"}
{"level":"warn","ts":"2022-02-08T11:04:12.780Z","caller":"rafthttp/probing_status.go:70","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"a70cf5ef44c4a1a4","rtt":"6.235689ms","error":"dial tcp 10.130.10.190:2380: connect: connection refused"}
{"level":"warn","ts":"2022-02-08T11:04:17.780Z","caller":"rafthttp/probing_status.go:70","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"a70cf5ef44c4a1a4","rtt":"6.235689ms","error":"dial tcp 10.130.10.190:2380: connect: connection refused"}
{"level":"warn","ts":"2022-02-08T11:04:17.780Z","caller":"rafthttp/probing_status.go:70","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"a70cf5ef44c4a1a4","rtt":"1.111939ms","error":"dial tcp 10.130.10.190:2380: connect: connection refused"}
```

Re-joining the new node doesn't work either, as there is already a node with the same name: `Feb  8 11:09:14 staging-master-3 rke2[13684]: time="2022-02-08T11:09:14Z" level=fatal msg="ETCD join failed: duplicate node name found, please use a unique name for this node"`

**Describe the solution you'd like**
There should be some way to remove master nodes from an RKE2 cluster. Running `kubectl delete node <old-master>` to remove the node from the cluster would be great. Alternatively if the `rke2-uninstall.sh` script would unjoin the node, or any documented procedure really.

**Describe alternatives you've considered**
I guess manually messing with the etcd Pods could work, but it's pretty cumbersome and tbh the RKE2 project should include documentation of that is the case.

**Comment by brandond** [comment]
Deleting the old node from the Kubernetes cluster via `kubectl delete node` should also remove it from the etcd cluster. You should confirm that the node is actually deleted (does not show up in `kubectl get node`) before attempting to rejoin it to the cluster.

The suggested order of operations would be:
1. `systemctl stop rke2-server` (on the node)
2. `rke2-killall.sh` (on the node)
3. `kubectl delete node` NODENAME (on another node)
4. `kubectl get node` (on another node; confirm that the deleted node is gone)

If the node appears to be stuck deleting (does not ever disappear from the list after deletion), please attach rke2-server logs from the remaining servers.

**Comment by kdalporto** [comment]
@brandond As a similar type issue as described above, if you wanted to add fault tolerance through AWS and Autoscaling Groups to a multi-master node setup (like in [this issue](https://github.com/rancherfederal/rke2-aws-tf/issues/40) for this repo: [rke2-aws-tf](https://github.com/rancherfederal/rke2-aws-tf) ), it doesn't seem that rke2 lends itself well to that type of capability and seems like a similar capability to what was described above albeit a different style of deployment. 

Is there any official guidance that you've heard of for regard the management of master-nodes in an Autoscaling Group?

**Comment by albgus** [comment]
Could this be triggered because I ran `rke2-uninstall.sh` on the node I wanted to remove, without running `systemctl stop rke2-server` first? I assumed that this would stop and remove all components, but I suppose that it may not be doing a graceful stop of the rke2-server..

Anyway, I was able to recover the cluster for now using etcdctl to manually remove the node from etcd. (inspired by this https://github.com/rancher/rke2/issues/55)

```
kubectl -n kube-system exec -it etcd-staging-kube-master-1.fqdn.com -- bash

etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member remove <node-id from previous cmd>
```

After this I was at least able to join a node with the same hostname and IP back into the cluster.

**Comment by brandond** [comment]
You should be able to delete the node from the Kubernetes cluster and have it also removed from etcd, even if it's been terminated unexpectedly.

You definitely need some integration with the autoscaling functionality, since you can get into a state where you lose quorum if too many nodes are replaced at the wrong time. K3s with a sqlite backend might be a better fit for autoscaling, since the servers themselves are stateless. Etcd nodes are stateful with a quorum requirement, and are hard to orchestrate without an operator or something carefully coordinating replacement.

If you do get stuck in a quorum-loss scenario, you can also use --cluster-reset to knock the etcd cluster back down to a single node without loosing any datastore data. Taking etcd snapshots to an external medium is also recommended.

**Comment by albgus** [comment]
I think something had completely broken down in this cluster in regards to node management. I now have a node that I can't delete, `kubectl delete node` simply hangs. I guess this has something to do with the `wrangler.cattle.io/managed-etcd-controller` not working, which makes sense as it didn't do anything with the other nodes.

Is there any logs for the managed-etcd-controller anywhere? Something to use to try and figure out what is going on?

**Comment by brandond** [comment]
Yeah, they're in the rke2-server logs. Is it possible for you to attach the logs from the other servers covering the time period in which the node was initially deleted?

**Comment by kdalporto** [comment]
@brandond I came across the Cluster Autoscaler a few days ago, which sounds like it could fix the issues around the use of autoscaling groups. Have you heard of its use to try and solve this issue?
https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cluster-autoscaler/amazon/
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws
