### ISSUE TITLE
traefik-proxy during rke2 deployment

### ISSUE THREAD

**Issue by dcgtri** [rancher/rke2#2454]
**Is your feature request related to a problem? Please describe.**
This is not a "problem" per se, but nice to have. It will at-least achieve a cleaner and faster cluster deployment 

**Describe the solution you'd like**
Need a way to deploy RKE2 cluster (on Linux at-least) with traefik-proxy. Yes, there is a helm chart to do this post cluster creation, but would be nice feature to have if it can be done during deployment (like k3s).

**Describe alternatives you've considered**
Yes, there is an option to use K3s, but due to our environment, we are more committed to hardened distribution RKE2. 

**Additional context**

**Comment by brandond** [comment]
You can drop manifests, including HelmChart manifests, in the /var/lib/rancher/RKE2/server/manifests directory on RKE2, same as you can with K3s: https://docs.rke2.io/advanced/#auto-deploying-manifests
