### ISSUE TITLE
secrets-encrypt not able to connect to API not bound to 127.0.0.1

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2476]
Same issue as in https://github.com/k3s-io/k3s/issues/5006

**Comment by dereknola** [comment]
Closing issue, it was incorrectly created (my bad). The issue does not exist in RKE2 as the `--server` flag is available to the `secrets-encrypt` command. https://github.com/dereknola/rke2/commit/096b6b01b2bff161addb55d31d97d46fde77b1ee#diff-c273ee16eff7989e14c7c55aa4571c3ac0edc94a9af158626fd6c0bd6831f20fR11
