### ISSUE TITLE
Airgap install fails due to attempting to fetch image from docker.io

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#248]
Version:
rke2 -v
rke2 version v1.18.4-beta11+rke2 (b459d18894e4f2a625e309f686cd95aa1cccf304)

Describe the issue:
rke2 is trying to fetch images from docker.io instead of from tarball.

Steps to reproduce:
1. Placed the rke2 binary under /usr/local/bin dir
2. Unzipped  rke2-images.linux-amd64.tar.gz and placed the tar file under /var/lib/rancher/rke2/agent/images dir
3. rke2 server --debug

Console output:
```
rke2 server  --debug
WARN[0000] not running in CIS 1.5 mode                  
FATA[0154] Get "https://index.docker.io/v2/": dial tcp 54.236.224.26:443: i/o timeout 
```

**Comment by nikkelma** [comment]
Looks like the airgap image bundle is created without arch suffixes [1] (e.g. `docker.io/rancher/rke2-runtime:v1.18.4-beta13-rke2`) but `preloadBootstrapImage` [2] looks for a tag with the arch suffix (e.g. `docker.io/rancher/rke2-runtime:v1.18.4-beta13-rke2-amd64`). Was able to get past this specific error by removing the suffix in `preloadBootstrapImage` but unsure if that's a long-term solution for multi-arch.

[1] https://github.com/rancher/rke2/blob/ca5f9bacfac555317852ce0f2b908791cf9c5978/scripts/build-images#L11-L23
[2] https://github.com/rancher/rke2/blob/ca5f9bacfac555317852ce0f2b908791cf9c5978/pkg/bootstrap/stage.go#L222-L234

**Comment by joshrwolf** [comment]
Seeing the same error with the latest beta14 release on our fully airgapped mock C2S environment:

```
[root@ip-10-0-101-252 centos]# rke2 server
WARN[0000] not running in CIS 1.5 mode
FATA[0000] Get "https://index.docker.io/v2/": EOF
```

Steps to reproduce:

0. Be airgapped
1. rke2 beta14 binary in `/usr/bin/rke2` (from `yum install` method)
2. Released airgap images placed in `/var/lib/rancher/rke2/agent/images` directory
3. `rke2 server --debug` (or install script)

**Comment by joshrwolf** [comment]
False alarm, `gunzip`ing the images and placing the `.tar` directly in `/var/lib/rancher/rke2/agent/images/` gets past the error.

Would it be good to add that documentation somewhere that the images .tgz needs to be unzipped first?  Since `k3s` releases uncompressed `.tar` files, I can see consumers (myself included) of the `rke2` images to blindly assume the same.

**Comment by cjellick** [comment]
yep! thanks for the quick feeback

**Comment by davidnuzik** [comment]
I will make sure this gets documented. Once we have the whole airgap story sorted.

**Comment by brandond** [comment]
Compressed image support is already available in k3s, but I believe rke2 needs some extra work to plug this in.

**Comment by ShylajaDevadiga** [comment]
Validated on beta16, Ubuntu 20.04
```
sudo rke2 -v
rke2 version v1.18.4-beta16+rke2 (9c11691024ae4c812af40a4573f0323ea7537201)
```
1. Created cluster with one master one agent node, both airgapped.
2. Copied images tar file to images for in master as well as into agent node
```
root@ip-172-31-41-10:~# ls /var/lib/rancher/rke2/agent/images/
rke2-images.linux-amd64.tar

root@ip-172-31-39-169:~# ls /var/lib/rancher/rke2/agent/images/
rke2-images.linux-amd64.tar
```
3. Started server with 
```
sudo rke2 server --debug
```
4. Created config.yaml in agent node
```
/etc/rancher/rke2/config.yaml 
server: https://172.31.41.10:9345
token: TOKEN
```
5. Started agent with
```
sudo rke2 agent --debug
```
Cluster is up with two nodes
```
sudo /var/lib/rancher/rke2/data/*/bin/kubectl get nodes -A --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAME               STATUS   ROLES         AGE     VERSION
ip-172-31-39-169   Ready    <none>        10m     v1.18.4-beta16+rke2
ip-172-31-41-10    Ready    etcd,master   3h14m   v1.18.4-beta16+rke2

sudo /var/lib/rancher/rke2/data/*/bin/kubectl get pods -A --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAMESPACE     NAME                                                  READY   STATUS      RESTARTS   AGE
kube-system   etcd-ip-172-31-41-10                                  1/1     Running     0          3h13m
kube-system   helm-install-rke2-canal-ljv78                         0/1     Completed   0          3h14m
kube-system   helm-install-rke2-coredns-65wsc                       0/1     Completed   0          3h14m
kube-system   helm-install-rke2-ingress-nginx-p5dp5                 0/1     Completed   0          3h14m
kube-system   helm-install-rke2-kube-proxy-sg65v                    0/1     Completed   0          3h14m
kube-system   helm-install-rke2-metrics-server-g74w4                0/1     Completed   0          3h14m
kube-system   kube-apiserver-ip-172-31-41-10                        1/1     Running     0          3h13m
kube-system   kube-controller-manager-ip-172-31-41-10               1/1     Running     0          3h13m
kube-system   kube-proxy-6mfrc                                      1/1     Running     0          3h9m
kube-system   kube-proxy-z8ms4                                      1/1     Running     0          10m
kube-system   kube-scheduler-ip-172-31-41-10                        1/1     Running     0          3h13m
kube-system   rke2-canal-4h9tk                                      2/2     Running     0          3h9m
kube-system   rke2-canal-zmlsj                                      2/2     Running     0          10m
kube-system   rke2-coredns-rke2-coredns-7979fc655-ldzhq             1/1     Running     0          3h9m
kube-system   rke2-ingress-nginx-controller-d78b898d5-4m9nw         1/1     Running     0          3h8m
kube-system   rke2-ingress-nginx-default-backend-5787b8798f-p9pkq   1/1     Running     0          3h8m
kube-system   rke2-metrics-server-8c48bb8f7-6cdg7                   1/1     Running     0          3h8m
```

**Comment by ShylajaDevadiga** [comment]
Validated on CentOS Linux release 7.8.2003 
With SELinux in disabled mode, created a two node cluster with one master one agent node in airgapped setup.
Commands used is same as in Ubuntu 20.04 testing.
Closing this issue as resolved.
