### ISSUE TITLE
nginx ingress tcp-services

### ISSUE THREAD

**Issue by erSitzt** [rancher/rke2#2481]
Hi,

with my old RKE clusters in Rancher 2.4.11 the nginx-ingress was always running with the option `--tcp-services-configmap` which pointed to a config map in POD_NAMESPACE with the name tcp-services (or udp-services for udp)

With RKE2 this seems not to be the case ? Is this intentional or did the behavior change ?
I found that i can use `extraArgs` to enable this manually again, but what is the correct way to customize the nginx ingress in a running cluster ?

**Comment by brandond** [comment]
You need to configure TCP and UDP services via the Helm chart:
https://github.com/rancher/rke2-charts/blob/b75a4cb870ed18ea8f9abd08b97dfa455a491116/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.0.306/values.yaml#L836-L846

The best way to do this is to configure the helm chart via a HelmChartConfig manifest:
https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by Fabyao** [comment]
@brandond Thanks for the details. I am trying to enable TCP 22 for a gitlab instance. After saving the HelmChartConfig. I am getting the following errors from the ingress deamonset re-deploy:
<details>
  <summary>Error Logs</summary>
  
I0222 21:31:13.975776 7 nginx.go:379] "Stopping admission controller"
I0222 21:31:13.976617 7 nginx.go:387] "Stopping NGINX process"
E0222 21:31:13.977275 7 nginx.go:318] "Error listening for TLS connections" err="http: Server closed"
2022/02/22 21:31:13 [warn] 80#80: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:143
nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:143
2022/02/22 21:31:13 [warn] 80#80: the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:144
nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:144
2022/02/22 21:31:13 [warn] 80#80: the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /etc/nginx/nginx.conf:145
nginx: [warn] the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /etc/nginx/nginx.conf:145
2022/02/22 21:31:13 [notice] 80#80: signal process started
2022/02/22 21:31:11 [emerg] 31#31: still could not bind()
W0222 21:31:14.398965 7 controller.go:198] Dynamic reconfiguration failed: Post "http://127.0.0.1:10246/configuration/backends": read tcp 127.0.0.1:58168->127.0.0.1:10246: read: connection reset by peer
E0222 21:31:14.399019 7 controller.go:202] Unexpected failure reconfiguring NGINX:
Post "http://127.0.0.1:10246/configuration/backends": read tcp 127.0.0.1:58168->127.0.0.1:10246: read: connection reset by peer
E0222 21:31:14.399056 7 queue.go:130] "requeuing" err="Post \"http://127.0.0.1:10246/configuration/backends\": read tcp 127.0.0.1:58168->127.0.0.1:10246: read: connection reset by peer" key="kube-system/rke2-ingress-nginx-controller-admission"
I0222 21:31:15.024878 7 nginx.go:400] "NGINX process has stopped"
I0222 21:31:15.024934 7 main.go:175] "Handled quit, awaiting Pod deletion"
I0222 21:31:25.027244 7 main.go:178] "Exiting" code=0
</details>
<details>
  <summary>My HelmChartConfig</summary>

```apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    tcp: 
       22: "dummy-namespace/dummy-service-name:22"
```
</details>

@erSitzt Did you experience the same issue? Any pointers would be greatly appreciated.

**Comment by brandond** [comment]
The nginx ingress is deployed in HostPort mode by default on RKE2; I suspect that 22 is probably used by the ssh service on your nodes?

https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.0.306/values.yaml#L76-L88

**Comment by Fabyao** [comment]
Correct. Port 22 is used by the SSH service on my node. I am not sure why its an issue? In my helmChartConfig above, I have provided the service name to use on port 22.

**Comment by brandond** [comment]
Use of HostNetwork means that the ingress service is running in the same network namespace as processes on the host operating system. This means that you can't have the Ingress process listen on port 22 (and forward requests to your service) if you already have OpenSSH on port 22. In general, only a single process can bind to a particular port.

**Comment by brandond** [comment]
It sounds like Gitlab has a recommended deployment configuration for the Nginx Ingress. We ship the upstream Helm chart without any modifications (other than some tweaks to the default values) so it should be possible to deploy it in alignment with their guide.

**Comment by Fabyao** [comment]
@brandond thanks for your help. I have decided to use port 2222 instead of 22 for external traffic. With this I amended my HelmChartConfig accordingly and this time no port collision.

For now its better than using the NodePort.

**Comment by gauravkarki** [comment]
I am having the same issue as @Fabyao. I am running bitbucket in a container and trying to expose TCP port (7999). I followed the instruction provided but I can not connect to the TCP port.
Any help/advise is greatly appreciated.
### Environment: rke2 v1.24.7 on RHEL8.6
### Service
#kubectl -n source-management get svc bitbucket -o yaml         
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitbucket
  name: bitbucket
  namespace: source-management
spec:
  ports:
  - name: http
    port: 7990
    protocol: TCP
    targetPort: 7990
  - name: ssh
    port: 7999
    protocol: TCP
    targetPort: 7999
  selector:
    app: bitbucket
    pod: bitbucket
  type: ClusterIP
```
### Ingress
#kubectl -n source-management get ingress bitbucket -o yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: bitbucket
    description: ingress-for-bitbucket
  name: bitbucket
  namespace: source-management
spec:
  rules:
  - host: bitbucket.<domain.com>
    http:
      paths:
      - backend:
          service:
            name: bitbucket
            port:
              number: 7990
        path: /
        pathType: Prefix
      - backend:
          service:
            name: bitbucket
            port:
              number: 7999
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bitbucket.<domain.com>
    secretName: wildcard-cert
status:
  loadBalancer: ## I am not using any LoadBalancer. These Ingress IPs are the IPs of worker Nodes
    ingress:
    - ip: 10.100.x.x
    - ip: 10.100.x.x
    - ip: 10.100.x.x
# kubectl -n source-management get ingress
NAME             CLASS    HOSTS                                     ADDRESS          PORTS     AGE
bitbucket        <none>   bitbucket.<domain.com>   10.100.x.x,10.100.x.x,10.100.x.x   80, 443   21d   <-- TCP port 7999 is not listed in the ingress
```
### HelmChartConfigs
#kubectl get helmchartconfigs.helm.cattle.io -n kube-system rke2-ingress-nginx -o yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      extraArgs:
        tcp-services-configmap: "kube-system/rke2-ingress-tcp-service"
    tcp:
       7999: "source-management/bitbucket:7999"
```
### RKE2 nixing ingress controller Daemonsets
#kubectl -n kube-system describe daemonsets.apps rke2-ingress-nginx-controller | grep tcp-services-configmap
`      --tcp-services-configmap=kube-system/rke2-ingress-tcp-service`

#kubectl -n kube-system describe pod rke2-ingress-nginx-controller-f6tz2 | grep tcp-services-configmap
`      --tcp-services-configmap=kube-system/rke2-ingress-tcp-service`
### ConfigMap
#kubectl -n kube-system get cm rke2-ingress-tcp-service -o yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-ingress-tcp-service
  namespace: kube-system
data:
  "7999": source-management/bitbucket:7999
```
### Connection Test
#telnet 10.100.x.x 443 <-- Connection to 443 is successful.
Trying 10.100.x.x...
Connected to 10.100.x.x.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

#telnet 10.100.x.x 7999 <-- Connection to TCP port using Ingress IP is not successful.
Trying 10.100.x.x...
telnet: connect to address 10.100.x.x: Connection refused

#telnet  10.43.1x.x 7999 <-- However connection to TCP port using the ClusterIP of the service is successful. 
Trying 10.43.x.x...
Connected to 10.43.x.x.
Escape character is '^]'.
SSH-2.0-APACHE-SSHD-2.8.0
^]
telnet> quit
Connection closed.

**Comment by erSitzt** [comment]
@gauravkarki you are mixing up stuff here i think...
you're trying to use an http ingress rule to move traffic to your ssh, which is a tcp service. this does not work.
If you use the tcp-services configmap, the nginx itself will start to listen on that port and you need to use the nodes ip to connect to the port number you specified first in the configmap.
The ports may differ, you dont have to use 7999.

The initial problem in this issue was that nginx was not using the tcp-services configmap by default... maybe thats your root issue here...
