### ISSUE TITLE
Can't get metrics from kube-proxy with prometheus and duplicated kube-proxy deploy on configure

### ISSUE THREAD

**Issue by lfdominguez** [rancher/rke2#2491]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux node02.domain.com 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
The default deployment of rke2 with the kube-proxy component only listen the metrics endpoint at 127.0.0.1, so prometheus can't scrape the metrics endpoint. So using the HelmChartConfig method to try to change the metrics endpoint, now rke2 deployed 2 sets of kube-proxy, but don't solve the problem

**Steps To Reproduce:**
- Installed RKE2
- Installed prometheus monitoring stack
- See error on prometheus targets
- Create a file at `/var/lib/rancher/rke2/server/manifests/rke2-kube-proxy-config.yaml`
- Write a `HelmChartConfig` to the file with `valuesContent` as `metricsBindAddress: 0.0.0.0:10249`
- Restart rke2-server
- See 2 sets of kube-proxy deployed

**Expected behavior:**
One set of kube-proxy with metrics endpoint listen on 0.0.0.0

**Actual behavior:**
Two sets of kube-proxy with metrics endpoint listen on 127.0.0.1 (the other sets not listen)

**Additional context / logs:**
Reading the documentation i see that i can modify the helm deployed configuration, so i write the file like this

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    metricsBindAddress: 0.0.0.0:10249
```

but when i restarted rke2 i get this for pods lists

```
kube-proxy-node02.domain.com                  1/1     Running     0          10m
kube-proxy-node03.domain.com                  1/1     Running     0          10m
kube-proxy-node03.domain.com                  1/1     Running     0          10m
kube-proxy-ktrmm                              1/1     Running     0          16m
kube-proxy-slzxf                              1/1     Running     0          16m
kube-proxy-wggjz                              1/1     Running     0          16m
```

the kube-proxy with hostnames appended are the default ones get on first rke2 installation, and `Controlled By: Node/*`. The other set of kube-proxy was deployed on rke2-server restarted with the new config and are controlled by a daemonset.
I tried to remove the first one, but rke2 recreate it....

**Comment by brandond** [comment]
The kube-proxy helm chart is deprecated. You should use the --kube-proxy-arg CLI flag / config file key to add additional configuration to kube-proxy. If you must use the helm chart for some reason, disable the kube-proxy static pod with --disable-kube-proxy.

**Comment by lfdominguez** [comment]
Hi, thanks for response, i configure this on `/etc/rancher/rke2/config.yaml`:
```
kube-proxy-arg: "--metrics-bind-address 0.0.0.0:10249"
```
But rke2-server not start because:
```
msg="failed to validate kube-proxy conntrack configuration: unknown flag: --metrics-bind-address 0.0.0.0:10249"
```

**Comment by lfdominguez** [comment]
Found the issue with `config.yaml`, the working config is:
```yaml
kube-proxy-arg: "metrics-bind-address=0.0.0.0:10249"
```
