### ISSUE TITLE
Support installing local RPMs if enabled

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#2501]
Today, if a user specifies `INSTALL_RKE2_ARTIFACT_PATH`, there is an implicit assumption that the user is installing using a local tar ball. This functionality was added for the purposes of allowing the system-agent to install RKE2 using local artifacts (rather than downloading the tarball from the internet). 

This is an enhancement request to add local RPM support, to allow the install script to install RPMs for RKE2 that are located in the `ARTIFACT_PATH` if the system deems it should install RPMs. This will allow the system-agent to stage RPM files for installing RKE2 into the artifact path and end up with an RPM-based installation. 

Notably, if a local artifact path is used, the corresponding rancher repo files should not be created, and the RPMs should be installed using `yum localinstall` or the `dnf` equivalent. 

The installation method on a host should be "sticky", i.e. a tar installation should remain tar (and be managed like tar), and an RPM installation should be RPM.

Example would be a user who installs using an older system-agent-installer-rke2 version that force-installs tarball on CentOS 7/8 or RHEL 7/8, then upgrades to a newer version of the `system-agent-installer-rke2` that supports local RPMs -- the user should remain on the tar ball install.

This will also allow bringing selinux into the picture in an automated fashion using the RPM.

https://github.com/rancher/rancher/issues/36482

**Comment by ron1** [comment]
Issue is still relevant.
