### ISSUE TITLE
Helm install of rancher-vsphere-csi/rancher-vsphere-csi-100.1.0+up2.3.0 fails with "chart requires kubeVersion: 1.19 - 1.21" when upgraded to v1.22.5+rke2r2

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#2505]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.5+rke2r2 (b61d4b3cb989b0380aae97fceb9a3e45a35ee2b9)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, multiple agents

**Describe the bug:**
Upgraded from 1.21 to v1.22.5+rke2r2 and the rancher-vsphere-csi helm chart install is failing with the error
`UPGRADE FAILED: chart requires kubeVersion: 1.19 - 1.21 which is incompatible with Kubernetes v1.22.5+rke2r2`

Looking in the log it seems to be running the install for chart rancher-vsphere-csi/rancher-vsphere-csi-100.1.0+up2.3.0

**Steps To Reproduce:**
1. Install rke2 1.21 with rancher-vsphere-csi
2. Upgrade rke2 to v1.22.5+rke2r2
3. Helm install of rancher-vsphere-csi fails

**Expected behavior:**
rancher-vsphere-csi is installed or upgrades to a supported chart version 

**Actual behavior:**
rancher-vsphere-csi fails to run helm install

**Additional context / logs:**
Looks like installed version is rancher-vsphere-csi/rancher-vsphere-csi-100.1.0+up2.3.0

**Comment by mitchellmaler** [comment]
Related issue from rancher/rancher https://github.com/rancher/rancher/issues/35953

**Comment by brandond** [comment]
Yes, the rancher vsphere CSI/CPI charts aren't supported on 1.22 or 1.23 yet. This was being tracked at https://github.com/rancher/charts/pull/1685 but it appears that it has been shuffled around and I'm not sure what the current status is. 

cc @samkulkarni20 @PennyScissors
