### ISSUE TITLE
Suggestion to rename airgap tar file to include airgap keyword in it

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#253]
Version:
rke2 beta11

Currently airgap tar file does not have airgap keyword in it. Would be good to have to differentiate with other tar files. It was ranamed/updated in beta6.

Current zipped tar file name for airgap:

rke2-images.linux-amd64.tar.gz

**Comment by dweomer** [comment]
`rke2-images` seems pretty clear to me.

**Comment by cjellick** [comment]
I am fine with it as-is. The image list has uses/implications beyond airgap. I'm going to close this issue.

**Comment by davidnuzik** [comment]
Should we change this in rancher/k3s too then?

**Comment by cjellick** [comment]
I'm fine with the inconsistency.
