### ISSUE TITLE
Update containerd to v1.5.10

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#2537]
To address:
* https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7

**Comment by rancher-max** [comment]
This appears to have the correct expected version and general checks continue to succeed using v1.23.4-rc2+rke2r2. Containerd version is: `containerd://1.5.10-k3s1`. I will leave this issue open to validate the following:
```
v1.21.11+rke2r1 : containerd://1.4.13-k3s1
v1.22.8+rke2r1 : containerd://1.5.10-k3s1
```

**Comment by rancher-max** [comment]
### Validated in all versions

**v1.21.11-rc4+rke2r1**
- Linux: containerd://1.5.7
- Windows: containerd://1.4.13-k3s1
I believe the mismatch here is expected and OK as this is a functional setup

**v1.22.8-rc4+rke2r1**
- Linux: containerd://1.5.10-k3s1
- Windows: containerd://1.5.10

**v1.23.5-rc3+rke2r1**
- Linux: containerd://1.5.10-k3s1
- Windows: containerd://1.5.10
