### ISSUE TITLE
Update containerd to 1.6 to fix bug pulling windows images

### ISSUE THREAD

**Issue by franznemeth** [rancher/rke2#2541]
**Environmental Info:**
RKE2 Version: rke2.exe version v1.21.9+rke2r1 (e48f07f7b208c0e43c537fca006cd5b6ce31b13b)

Node(s) CPU architecture, OS, and Version: 
Master:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a 
Linux <removed> 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Worker:
```
PS C:\> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
PS C:\> Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
WindowsProductName           WindowsVersion OsHardwareAbstractionLayer
------------------           -------------- --------------------------
Windows Server 2019 Standard 1809           10.0.17763.2061
```

Cluster Configuration:
The cluster was provisioned via rancher (2.6.3) as a custom cluster with on-premises nodes.
Architecture: 
3 controlplane & etcd nodes 
2 linux worker nodes (for cluster services)
2 windows worker nodes

**Describe the bug:**
We try to run a pod on windows using an image which has visual studio installed. The visual studio installation comes with filenames that contain unicode characters. This makes it impossible to pull those images with the containerd version provided through rke2.

The bug lies with the containerd version and is fixed in 1.6 as described here: https://github.com/containerd/containerd/issues/6612 and fixed here https://github.com/containerd/containerd/pull/6588

Please upgrade the containerd version shipped with rke2 to 1.6

**Steps To Reproduce:**

- Installed RKE2 via the Rancher Registration Command on controlplane and worker nodes
- Created pod on windows node using an image as described here: https://github.com/containerd/containerd/issues/6612
- Pull fails and the pod is in ImagePullBackOff

**Expected behavior:**
containerd provided by rke2 is able to pull the image and start the pod

**Actual behavior:**
Pulling the image fails on windows nodes

**Additional context / logs:**
Error message from `kubectl describe pods`
```
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  Failed   56m                   kubelet  Failed to pull image "<removed>": rpc error: code = Unknown desc = failed to pull and unpack image "<removed>": failed to extract layer sha256:<removed>: open \\?\C:\Windows\TEMP\hcs775739432\Files\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TextMate\Starterkit\Extensions\cmake\Snippets\File(Glob …).tmSnippet: The filename, directory name, or volume label syntax is incorrect.: unknown
```

**Comment by rosskirkpat** [comment]
@franznemeth Thank you for filing this issue, we are actively looking into it

**Comment by newbenji** [comment]
Maybe upgrade both linux and windows to containerd 1.6.x 
there is for once a inotify leak thats solved in 1.6.x when used with cgroupv2 ... which flatcar hits.

**Comment by rosskirkpat** [comment]
@newbenji @franznemeth The containerd version for linux and windows has been bumped to 1.6.x in the master branch, which will be v1.24.x of RKE2. We should have the first rke2 release of 1.24 out within the next month.

Please note, however, that it will not be back-ported to v1.23 or earlier of RKE2.

**Comment by franznemeth** [comment]
Thanks for taking care. For us its completely fine to upgrade to a newer version. I will close this issue.
