### ISSUE TITLE
Windows Install via `-Commit` fails

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#2543]
**Environmental Info:**
RKE2 Version: 

v1.22.7+rke2r1

Node(s) CPU architecture, OS, and Version: 

Windows Server

Cluster Configuration:

1 server, 1 linux agent, 1 windows agent
**Describe the bug:**

Windows agent fails to startup due to missing tar images.
```
Failed to load runtime 
image index.docker.io/rancher/rke2-runtime:v1.22.7-dev-90d94ddb from tarball: no 
local image available for 
index.docker.io/rancher/rke2-runtime:v1.22.7-dev-90d94ddb: directory 
C:\var\lib\rancher\rke2\agent\images does not exist: image not found<
```

**Steps To Reproduce:**

`./install.ps1 -Commit 90d94ddbd8601c4b1bc15460811239e1c99ba1b3`

**Expected behavior:**

Install.ps1 should place the image.tar under /var/lib/rancher/rke2/agent/images

**Actual behavior:**

No /var/lib/rancher/rke2/agent/images directory is ever created

**Additional context / logs:**

**Comment by rosskirkpat** [comment]
```powershell
./install.ps1 -Commit 058823838da854109d8159911bbcd5f2d5030ad3
[INFO] Windows feature: 'Containers' is installed. Installation will proceed.
Using stable channel of rke2 for installation
[INFO] using commit 058823838da854109d8159911bbcd5f2d5030ad3 as release
[INFO] Version: commit 058823838da854109d8159911bbcd5f2d5030ad3
Storage URL: https://storage.googleapis.com/rke2-ci-builds
Github URL: https://github.com/rancher/rke2
Binary Checksums: C:\Users\Administrator\AppData\Local\Temp\rke2-install\rke2.checksums
Image Checksums: C:\Users\Administrator\AppData\Local\Temp\rke2-install\rke2-images.checksums
downloading image checksum for commit: 058823838da854109d8159911bbcd5f2d5030ad3 at https://storage.googleapis.com/rke2-ci-builds/rke2-images.windows-amd64-058823838da854109d8159911bbcd5f2d5030ad3.tar.zst.sha256sum
[INFO] downloading airgap tarball with commit 058823838da854109d8159911bbcd5f2d5030ad3 from https://storage.googleapis.com/rke2-ci-builds/rke2-images.windows-amd64-058823838da854109d8159911bbcd5f2d5030ad3.tar.zst
downloading binary checksum for commit: 058823838da854109d8159911bbcd5f2d5030ad3 at https://storage.googleapis.com/rke2-ci-builds/rke2.windows-amd64-058823838da854109d8159911bbcd5f2d5030ad3.tar.gz.sha256sum
downloading binary tarball for commit: 058823838da854109d8159911bbcd5f2d5030ad3 at https://storage.googleapis.com/rke2-ci-builds/rke2.windows-amd64-058823838da854109d8159911bbcd5f2d5030ad3.tar.gz
[INFO] verifying tarball
[INFO] unpacking tarball file to C:/usr/local
[INFO] install complete; you may want to run:  $env:PATH+=";C:/usr/local\bin;C:\var\lib\rancher\rke2\bin"
```

@dereknola The current master install.ps1 script is working as expected for me on a 2019 Windows VM. Can you verify that you are running powershell as administrator? Not running as administrator would block creation of directories on `C:\usr\local`

**Comment by dereknola** [comment]
Attaching existing issue https://github.com/rancher/rke2/issues/2125 to this PR.

**Comment by rosskirkpat** [comment]
My previous comment was based on an incorrect understanding of the issue. @dereknola's fix addresses it.

**Comment by rosskirkpat** [comment]
Update:

There is a lower level issue blocking the `-Commit` functionality. We are actively investigating it.

The above change I requested to unpack the tar.zst image tarball was meant to be a stop gap but it revealed other issues and I am advocating to scrap that approach. The original changes from @dereknola is validated as working when it comes to properly preparing the image tarball for rke2 to extract. However, rke2 agent on Windows is not working beyond that point and we are working to isolate where it is failing.

**Comment by dereknola** [comment]
Closing this issue in fair of https://github.com/rancher/rke2/issues/2571
