### ISSUE TITLE
Restarting after secrets-encrypt causes rke2-server to exit continuously

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#2562]
**Environmental Info:**
RKE2 Version: 

`v1.21.10+rke2r1`

Node(s) CPU architecture, OS, and Version: 

`Linux jhyde-rke2-test-cp-479ed483-szfpk 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

2 controlplane, 1 etcd/worker

**Describe the bug:**

Cannot rotate encryption keys on a control plane node that is not also an etcd node. 

**Steps To Reproduce:**

- Installed RKE2: Rancher provisioned rke2 downstream
- SSH into any control plane node
- Run `rke2 secrets-encrypt prepare`
  - The command appears to succeed (when running `rke2 secrets-encrypt status`, but returns a `400 Bad Request Error secrets-encrypt-xxxxx`
- The `rke2-server` logs show a warning with the following message: `secrets-encrypt-xxxxx: etcdclient: no available endpoints`

**Expected behavior:**

`systemctl restart rke2-server` should function the same way as when the control plane node also has the etcd role.

**Actual behavior:**

Running `systemctl restart rke2-server` causes the server to enter into a restart loop, with the following message: `/var/lib/rancher/rke2/server/cred/encryption-state.json, /var/lib/rancher/rke2/server/cred/encryption-config.json newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore.`

**Additional context / logs:**

I have included a short screen capture to demonstrate the issue:
https://user-images.githubusercontent.com/33796120/157129075-5045765f-6414-4108-906e-111c6829fc0f.mp4

This works fine when the control plane nodes are also etcd nodes, including a single node cluster.

**Comment by dereknola** [comment]
Can confirm that secrets-encryption relies on etcd bootstrapping to propagate necessary changes to other nodes.

**Comment by brandond** [comment]
etcd-only servers shoudn't participate in encryption config rotation, but they should do the right thing if the apiserver is enabled later.

I'm not sure what to do about secrets rotation on control-plane only nodes without a local etcd datastore; I guess one requirement in this scenario would be that there is a node with etcd on it that remains available while the control-plane nodes are restarted to effect the configuration change.

**Comment by snasovich** [comment]
Related k3s issue: https://github.com/k3s-io/k3s/issues/5225
