### ISSUE TITLE
node-name not set from meta-data endpoint if cloud-provider-name is set to aws

### ISSUE THREAD

**Issue by thedadams** [rancher/rke2#2567]
**Environmental Info:**
RKE2 Version: v1.22.7+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux auston-rke2-cloudprovdering-pool1-e028ea72-sm5d5 5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 1 agent

**Describe the bug:**
Based on the code, I would expect that if a `node-name` is not set and `cloud-provider-name` is set to `aws`, then code in [this](https://github.com/rancher/rke2/blob/9947db5011b8e6bb3e3dbd574f077ec3096457ee/pkg/rke2/rke2_linux.go#L64) if-statement would run and set the `node-name` to the value it gets from the meta-data endpoint.

However, the `node-name` is being set to the output of the `hostname` command and none of the debug logs seem to be printed (that would indicate an error occurred).

**Steps To Reproduce:**
Rancher is putting a file at `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` with the contents:
```json
{
  "debug": true,
  "advertise-address": "<redacted>",
  "agent-token": "<redacted>",
  "cloud-provider-name": "aws",
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-ip": [
    "<redacted>"
  ],
  "node-label": [
    "rke.cattle.io/machine=c838f2b4-f218-4a83-8e42-86d433e93043"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "tls-san": [
    "<redacted>"
  ],
  "token": "<redacted>"
}
```

**Expected behavior:**
I expect the `node-name` to be set from the meta-data endpoint.

**Actual behavior:**
The `node-name` is set to the output of the `hostname` command.

**Comment by briandowns** [comment]
Currently huddling on the issue...

**Comment by Auston-Ivison-Suse** [comment]
This issue was created because of a user error. 

I apologize. 

Here is a comment describing some of the validation steps: https://github.com/rancher/rancher/issues/35618#issuecomment-1062192841

**Comment by briandowns** [comment]
No worries at all. Would rather get an issue submitted and subsequently close it than have a bug go unknown. Thank you very much!
