### ISSUE TITLE
[Documentation] Explain the .skip behavior for /manifests/ charts

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#257]
We may add `--disable` flag functionality to RKE2 in the future and this is tracked in https://github.com/rancher/rke2/issues/232

In the meantime, and before we GA RKE2, we need to document the .skip functionality for charts which can be leveraged in place of the `--disable` functionality. This should be documented in the RKE2 project.

**Comment by brandond** [comment]
We should probably document it in k3s as well. It's secret functionality at the moment. I forgot about it until I was re-reading the code.

**Comment by brandond** [comment]
We ended up landing --disable support as a GA feature. IMHO this is preferred to the undocumented .skip feature. If we document it then we have to keep supporting it, wheras it's a bit of an internal implementation detail at the moment.

**Comment by davidnuzik** [comment]
Closing. Not needed since we got `--disable` support added in. This was meant to be a stop-gap if it didn't get in.
