### ISSUE TITLE
Containerd versions need to be tracked between Windows and Linux for rke2

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#2577]
To prevent situations where the linux containerd version is higher than windows, we should have automation in place to catch it similar to what we have in https://github.com/rancher/rke2/blob/v1.22.7%2Brke2r1/scripts/validate-release#L55-L66.

**Comment by rosskirkpat** [comment]
@rancher-max FYI I have marked this as `Waiting for RC` as I believe the only way to verify the validation is _truly_ working is if an RC/release is cut.

**Comment by rancher-max** [comment]
Validated in all versions. See https://github.com/rancher/rke2/issues/2537#issuecomment-1079441495. I confirmed that 1.21 is expected to be different
