### ISSUE TITLE
Fossa build step outdated

### ISSUE THREAD

**Issue by paraglade** [rancher/rke2#2581]
EIO has an optimized Fossa drone plugin which will replace this step: https://github.com/rancher/rke2/blob/master/.drone.yml#L39
with this:
https://github.com/rancherlabs/drone-plugin-fossa#basic

we collaborated with Fossa devs and according to them it is not necessary to do the `test` command which will dramatically cut down on the time it takes to run this step.

in addition the `install.sh` referenced in the current `build.yaml` is outdated and not longer maintained; using the fossa drone plugin delivers an updated ready to run fossa app.

**Comment by briandowns** [comment]
Thank you for taking a look and identifying this as an optimization @paraglade !
