### ISSUE TITLE
RKE2 - the Label `node-role.kubernetes.io/etcd` is missing from an ETCD node  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke2#2583]
**Rancher Server Setup**
- Rancher version: v2.6-head 3df76e4
- Installation option (Docker install/Helm Chart): Docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): DO

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

The label `node-role.kubernetes.io/etcd` is missing from an ETCD node, which causes the Dashboard UI to mark it as a worker node. 

**To Reproduce**
 
-  create an RKE2 cluster. In my case,  the cluster has 2 control plane, 3 etcd, and 1 worker node 

**Result**
the label `node-role.kubernetes.io/etcd` is missing from one of the ETCD nodes 

<img width="1280" alt="Screen Shot 2022-03-09 at 1 16 50 PM" src="https://user-images.githubusercontent.com/6218999/157528594-554425f9-5bc4-45b0-bda9-004177100325.png">

**Expected Result**

the label `node-role.kubernetes.io/etcd` should be set on the node 

**Screenshots**

Dashboard UI marks the etcd node as a worker node:
<img width="1010" alt="Screen Shot 2022-03-09 at 1 18 19 PM" src="https://user-images.githubusercontent.com/6218999/157528786-5e5bd4b6-5cc2-4b34-bd1c-ed3c1de551f5.png">

**Additional context**

It also causes issue for the job `apply-system-agent-upgrader-on-<cluster-name>` where its pod are assigned to the etcd node which misses the label, and here is the error in the pod's logs:
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/install.sh
+ '[' -n rke2-jiaqi-rke2-etcd-21352816-4fgwf ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/node.yaml
+ kubectl get node rke2-jiaqi-rke2-etcd-21352816-4fgwf -o yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/rancher-system-agent'
+ '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
+ chroot /host /var/lib/rancher/agent/tmp/tmp.VhUoF7daLs/install.sh
[FATAL] You must select at least one role.
```

**Comment by brandond** [comment]
All three of the etcd servers are still spewing an error about the apiserver not being reachable, despite everything mostly working OK. This seems to have prevented the first etcd server from properly setting the node annotations; restarting the rke2-server service allowed it to do so successfully, but the messages continue:

```
Mar  9 23:46:44 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:46:44Z" level=info msg="Waiting for API server to become available"
Mar  9 23:47:14 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:47:14Z" level=info msg="Waiting for API server to become available"
Mar  9 23:47:44 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:47:44Z" level=info msg="Waiting for API server to become available"
Mar  9 23:48:14 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:48:14Z" level=info msg="Waiting for API server to become available"
Mar  9 23:48:44 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:48:44Z" level=info msg="Waiting for API server to become available"
Mar  9 23:49:14 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:49:14Z" level=info msg="Waiting for API server to become available"
Mar  9 23:49:44 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:49:44Z" level=info msg="Waiting for API server to become available"
Mar  9 23:50:14 rke2-jiaqi-rke2-etcd-21352816-4fgwf rke2[1737]: time="2022-03-09T23:50:14Z" level=info msg="Waiting for API server to become available"
(END)
```

**Comment by brandond** [comment]
I believe that the changes in https://github.com/k3s-io/k3s/pull/5143/files should resolve this, once backported to the correct branch and pulled in to RKE2.

**Comment by rancher-max** [comment]
If I'm not mistaken, this is already in v1.21.11+rke2r1 so should be validated in that already released version

**Comment by brandond** [comment]
Correct; I neglected to update the state despite the PR being merged.

**Comment by VestigeJ** [comment]
**Valid with v1.21.11+rke2r1 NOTE only without CloudProvider set to "NONE"**

$ rancher -v 
```
v2.6-head 6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1
```

$ rke2 -v 
```
$ rke2 -v
rke2 version v1.21.11+rke2r1 (2998c71ea2db8418d55ec63014e3b916a76666e9)
go version go1.16.14b7
```

Every 12.0s: kubectl get nodes                                                                                                                               
```
tryingtogainafloor-contplanna-8646511e-pf9gx: Tue Apr 19 19:16:19 2022

NAME                                           STATUS   ROLES                  AGE     VERSION
tryingtogainafloor-contplanna-8646511e-ktrzm   Ready    control-plane,master   4m53s   v1.21.11+rke2r1
tryingtogainafloor-contplanna-8646511e-pf9gx   Ready    control-plane,master   18m     v1.21.11+rke2r1
tryingtogainafloor-etcetc-f09777f3-54jd2       Ready    etcd                   17m     v1.21.11+rke2r1
tryingtogainafloor-etcetc-f09777f3-p6bm2       Ready    etcd                   18m     v1.21.11+rke2r1
tryingtogainafloor-etcetc-f09777f3-vlzn2       Ready    etcd                   17m     v1.21.11+rke2r1
tryingtogainafloor-worksorxz-205524bf-49srt    Ready    worker                 5m54s   v1.21.11+rke2r1
tryingtogainafloor-worksorxz-205524bf-vptjp    Ready    worker                 5m54s   v1.21.11+rke2r1
```


![Screen Shot 2022-04-19 at 12 26 17 PM](https://user-images.githubusercontent.com/8961630/164080514-b6fde60e-6adc-4684-9baa-077cfb98e93b.png)
