### ISSUE TITLE
Cannot edit ingress

### ISSUE THREAD

**Issue by crowne** [rancher/rke2#2596]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.21.9+rke2r1 (e48f07f7b208c0e43c537fca006cd5b6ce31b13b)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 

Linux k8stest-pool-2c055718-jzzml 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

6 full nodes all roles

**Describe the bug:**

I have a nexus repository manager running on an rke2 cluster, I need to add some additional hosts and routes to the ingress.
The currently configured ingress is working properly and I can use the app in a web-browser https://nexus.domain1.net/
I need to add hosts nexus-dh.domain1.net and nexus-dg.domain1.net
If I edit the config of the current ingress, even without changing anything and try to save it I get the following error :

Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": x509: certificate is valid for *.domain1.net, domain1.net, not rke2-ingress-nginx-controller-admission.kube-system.svc

**Steps To Reproduce:**

- Installed RKE2: on vSphere cluster
- added repository https://sonatype.github.io/helm3-charts/
- installed nexus-repository-manager
- nsupdate add host nexus.domain1.net -> ip of deployment
- app is working ok
- log into add add docker repositories, (dockerhub-proxy, docker-hosted:8082, docker-group:8083), configure http ports as ingress handles reverse proxy + tls termination
- On rancher-ui go to services and add ports 8082 + 8083
- On rancher-ui go to ingress try to add host routes
- fails
- try to save ingress without any changes.
- fails

**Expected behavior:**

If I edit and save a working ingress without changing anything then I don't expect any errors.

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
> Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "[https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s](https://rke2-ingress-nginx-controller-admission.kube-system.svc/networking/v1/ingresses?timeout=10s)": x509: certificate is valid for *.domain1.net, domain1.net, not rke2-ingress-nginx-controller-admission.kube-system.svc

Did you do something to the ingress-nginx webhook configuration, or are you injecting HTTP proxy environment variables into your RKE2 configuration? Do you perhaps have a wildcard record in your DNS server that is redirecting traffic when it should not? Something in your environment is causing the apiserver to reach something that has a wildard certificate for `*.domain1.net` instead of the in-cluster webhook endpoint.

**Comment by brandond** [comment]
> The tls certificate is a wildcard.

The ingress controller validation webhook uses a self-signed certificate that is specifically trusted by the apiserver; it would not be using a wildcard certificate from a public CA. The fact that you were seeing the wildcard cert pop up here indicates that something is directing the traffic outside the cluster.
