### ISSUE TITLE
masquerade NAT rules remain after uninstall

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#2599]
Environmental Info:
RKE2 Version: v1.23.4+rke2r2

Describe the bug:
rke2-uninstall.sh does not clean up the masquerade rules

Node(s) CPU architecture, OS, and Version:
NA, Tested on Ubuntu

Cluster Configuration:
Single node or multi node configuration

Steps To Reproduce:
- Install rke2 with default settings
- Run rke2-uninstall.sh
- Check iptables using

$ sudo iptables-save |grep -i masq
```
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
-A POSTROUTING -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
-A POSTROUTING ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully
```
Expected behavior:
All rules applied during installation should be removed at uninstall

Actual behavior:
Some rules remain

Backporting

[*] Needs backporting to older releases

**Comment by rancher-max** [comment]
Reopening because this does not work when doing an upgrade from v1.23.4+rke2r2 to v1.23.5-rc4+rke2r1. Checked using SLES 15 SP3.

**Comment by manuelbuil** [comment]
> Reopening because this does not work when doing an upgrade from v1.23.4+rke2r2 to v1.23.5-rc4+rke2r1. Checked using SLES 15 SP3.

Yes, this is expected. Flannel is not capable of detecting the old iptables rules because they are missing the new arg "--comment" which allows us to identify those rules and delete them. I don't think there is a good workaround to avoid this :(

**Comment by brandond** [comment]
This should only be an issue following upgrades, correct? If you reboot or otherwise clear out the iptables rules and let flannel put them back, the uninstall script should clean them up once they have the correct comments on them.

**Comment by rancher-max** [comment]
> This should only be an issue following upgrades, correct? If you reboot or otherwise clear out the iptables rules and let flannel put them back, the uninstall script should clean them up once they have the correct comments on them.

Yep that's correct!

**Comment by manuelbuil** [comment]
I agreed wtih @rancher-max to add a comment in the clean-up script informing people that they might need to remove those rules if they are coming from an upgrade

**Comment by ShylajaDevadiga** [comment]
Validated masquerade NAT rules are removed using v1.23.6-rc3+rke2r1 install and upgrade
and user friendly comment is displayed during uninstall/killall process
```
+ echo If this cluster was upgraded from an older release of the Canal CNI, you may need to manually remove some flannel iptables rules:
If this cluster was upgraded from an older release of the Canal CNI, you may need to manually remove some flannel iptables rules:
+ echo -e \texport cluster_cidr=YOUR-CLUSTER-CIDR
-e 	export cluster_cidr=YOUR-CLUSTER-CIDR
+ echo -e \tiptables -D POSTROUTING -s $cluster_cidr -j MASQUERADE --random-fully
-e 	iptables -D POSTROUTING -s $cluster_cidr -j MASQUERADE --random-fully
+ echo -e \tiptables -D POSTROUTING ! -s $cluster_cidr -d  -j MASQUERADE --random-fully
-e 	iptables -D POSTROUTING ! -s $cluster_cidr -d  -j MASQUERADE --random-fully
```
