### ISSUE TITLE
At build time scan for non-fips algorithms (or panic)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#26]
FIPS-140 does not permit some algorithms from being used. For example, MD5 may not be allowed.

We should determine a solution that allows us to either parse and scan thru go code and alert on an invalid algorithm or perhaps we just want to halt the build process and panic when an invalid algorithm is detected.

May just involve updating our shim or something to this effect? (As we cannot touch GoBoring library).

**Comment by caroline-suse-rancher** [comment]
Closing this due to age
