### ISSUE TITLE
When using bind-address i have error: Remotedialer proxy error" error="dial tcp 192.168.0.6:9345: connect: connection refused"

### ISSUE THREAD

**Issue by WMP** [rancher/rke2#2606]
**Environmental Info:**
RKE2 Version: v1.22.7-rke2r1

Cluster Configuration:
3 servers

**Describe the bug:**
In servers  i have connected 2 interfaces: 192.168.0.0/24 and 17.19.5.0/24. 192.168.0.0 is external interface with routing to internet, and anyone from my network can connect to this network. 172.19.5.0/24 is network only to connect kubernetes nodes. So in 172.19.5.0 i have only 3 IP: 172.19.5.1 172.19.5.2 172.19.5.3 . I want to rke2 server listen on 172.19.5.1:9345 172.19.5.2:9345 172.19.5.3:9345 . 

**Steps To Reproduce:**

- Installed RKE2 and start server  with config:
```
#CLUSTER INIT
token: kub3rn3te8-token
tls-san:
  - "kubernetes.lan"
cluster-domain: "kubernetes.lan"
cni: "calico"

#Node
node-external-ip: 192.168.0.6
bind-address:     172.19.5.1
node-ip:          172.19.5.1
```

Server 2 Config:
```
#CLUSTER INIT
server: "https://172.19.5.1:9345"
token: kub3rn3te8-token
tls-san:
  - "kubernetes.lan"
cluster-domain: "kubernetes.lan"
cni: "calico"

#Node
node-external-ip: 192.168.0.7
bind-address:     172.19.5.2
node-ip:          172.19.5.2
```
Server 3 Config:
```
#CLUSTER INIT
server: "https://172.19.5.1:9345"
token: kub3rn3te8-token
tls-san:
  - "kubernetes.lan"
cluster-domain: "kubernetes.lan"
cni: "calico"

#Node
node-external-ip: 192.168.0.8
bind-address:     172.19.5.3
node-ip:          172.19.5.3
```

**Expected behavior:**
I except to rke2 connect to 172.19.5.1:9345 

**Actual behavior:**
Systemd unit cannot finish starting.

**Additional context / logs:**
``` 
mar 15 12:59:00 kub05n01 rke2[35579]: time="2022-03-15T12:59:00+01:00" level=info msg="Connecting to proxy" url="wss://192.168.0.6:9345/v1-rke2/connect"
mar 15 12:59:00 kub05n01 rke2[35579]: time="2022-03-15T12:59:00+01:00" level=error msg="Failed to connect to proxy" error="dial tcp 1192.168.0.6:9345: connect: connection refused"
mar 15 12:59:00 kub05n01 rke2[35579]: time="2022-03-15T12:59:00+01:00" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.0.6:9345: connect: connection refused"
```

**Comment by brandond** [comment]
--node-external-ip is meant for use in environments that provide a publicly routable (external) IP address that is NATed to a private LAN address. It is not meant to distinguish between multiple addresses bound to interfaces on the host itself.

If the node advertises its external IP as 192.168.0.8, then other nodes will attempt to connect to it at that address. You cannot both set that as the external IP, and bind to a different address that specifically isn't reachable via that address.

**Comment by WMP** [comment]
Thanks, in RKE1 i use address: 192.168.0.8 and internal_address: 172.19.5.3, and then rke1  can connect to 192.168.0.8. In rke2 i dont need 192.168.0.8 in configuration.
