### ISSUE TITLE
RKE2 and k3s SELINUX policies conflict and prevent install

### ISSUE THREAD

**Issue by bgulla** [rancher/rke2#263]
While spinning up fresh VMs is what all the cool kids do, some bare-metal enthusiasts don't have the luxury of fresh environments. When trying to install rke2/k3s on a machine that once installed it's counterpart, it is unable to install the competing SELINUX policy. I assume that these policies are similar in execution, we should add a check to ensure that another rancher SELINUX policy is not blocking upon yum install.

```bash

[root@localhost k3ama]# rpm -i https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
warning: /var/tmp/rpm-tmp.GEoTd7: Header V4 RSA/SHA1 Signature, key ID e257814a: NOKEY
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/lib/cni(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/run/k3s(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/log/pods(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/run/flannel(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/log/containers(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/lib/kubelet/pods(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Invalid argument
libsemanage.semanage_validate_and_compile_fcontexts: setfiles returned error code 1.
semodule:  Failed!

```

**Comment by dweomer** [comment]
@bgulla centos7 or ...?

**Comment by dweomer** [comment]
There are a couple of ways to tackle this that I can think of:
- remove the duplication from the k3s-selinux policy in rke2-selinux and have rke2-selinux depend on k3s-selinux
- completely duplicate k3s-selinux policy within rke2-selinux policy and flag the rpm as providing k3s-selinux

**Comment by ShylajaDevadiga** [comment]
Validated policies conflict and prevent install.
1. Install k3s/rke2
2. Install rke2/k3s
3. Install fails with below message
```
Error: rke2-selinux conflicts with k3s-selinux-0.3~rc1-0.el7.noarch
Error: k3s-selinux conflicts with rke2-selinux-0.4-1.el7.noarch
```
