### ISSUE TITLE
kubectl unavailable in PATH with beta11

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#267]
Version: beta11 /beta13
rke2 version v1.18.4-beta13+rke2

Issue:
kubectl not available in PATH

```
find / -name kubectl
/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/3f4f2ba3319380c30690939d3caf2d84c3bb299f6f06f6ccadaf8906c61afcf5/rootfs/usr/local/bin/kubectl
/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/7/fs/usr/local/bin/kubectl
/var/lib/rancher/rke2/data/b13f05d06aed40b9317221a1a1ef9dacc37566e0d7618fc814b30ec642508ca5/bin/kubectl
```

**Comment by dweomer** [comment]
@davidnuzik @cjellick is this a requirement? A working RKE2 installation will setup a `/var/lib/rancher/rke2/bin/` symlink to `/var/lib/rancher/rke2/data/<content hash>/bin/` but no effort is made to put it on the `$PATH`.

**Comment by cjellick** [comment]
not a high priority requirement, but I think we should do the same thing that k3s does, which is put it on the path. I'm open to reasons why it would be a bad idea to do so for k3s. 
Regardless, this is a low-priority issue and could slip past GA if need be.

If we did it, where would we put it on the path? In the install.sh? Somehow in the rpm or something-install tar?

**Comment by briandowns** [comment]
This was a function of the install script and used to do so.

**Comment by cjellick** [comment]
yeah, maybe in the spirit of "the install script should do less", maybe we _shouldnt_ do this for rke2. Is that your thinking @dweomer ?

**Comment by dweomer** [comment]
> yeah, maybe in the spirit of "the install script should do less", maybe we _shouldnt_ do this for rke2. Is that your thinking @dweomer ?

Probably the install script _should_ setup the symlink. It is possible that I completely missed this as a requirement but I don't remember seeing included as an exception to the simplification which is why it was left off.

**Comment by davidnuzik** [comment]
It may not have been a requirement before. But I think it's a nice-to-have.

**Comment by cjellick** [comment]
you didnt miss it. it was never discussed explicitly

**Comment by dweomer** [comment]
I think this is a documentation issue now, that should be addressed by #322

**Comment by davidnuzik** [comment]
@ShylajaDevadiga as low priority task, review the docs created such as from https://github.com/rancher/rke2/pull/322
If these are satisfactory then please close this issue when you have the time.

**Comment by ShylajaDevadiga** [comment]
@davidnuzik Couple of updates/issues seen while validating. For ubuntu (non-rpm) nodes  with as 'tar' as the default installation method used, installation unpacks tarball into /usr/local/share and we need to enable the service. This needs to be documented.

OS: Ubuntu 20.04
```
sudo curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh --output install.sh
sudo INSTALL_RKE2_METHOD=tar INSTALL_RKE2_VERSION=v1.18.8-beta19+rke2 sh ./install.sh
```
Enable service
```
sudo systemctl enable /usr/local/share/rke2/rke2.service
```
**As the option provided in docs using rpm as a method in rpm based nodes, rke2 service works as expected**
OS: RHEL 7.8
```
sudo curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh --output install.sh
sudo INSTALL_RKE2_VERSION=v1.18.8-beta19+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='rpm' sh ./install.sh
```
**As the option provided in docs using tar as a method in rpm based nodes, rke2 service fails to start**

```
$ curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh --output install.sh
$ sudo INSTALL_RKE2_METHOD=tar sh ./install.sh
[INFO]  finding release for channel testing
[INFO]  using v1.18.8-beta19+rke2 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.18.8-beta19+rke2/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.18.8-beta19+rke2/rke2.linux-amd64.tar.gz
[INFO]  verifying installer
[INFO]  unpacking tarball file

```
Service status
```
sudo systemctl status  rke2
● rke2.service - Rancher Kubernetes Engine v2
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
     Docs: https://github.com/rancher/rke2#readme

Sep 21 07:49:35 ip-172-31-9-158.us-east-2.compute.internal systemd[1]: [/usr/local/share/rke2/rke2.service:25] Executable path is not absolute, ignoring: rke2 server
Sep 21 07:49:35 ip-172-31-9-158.us-east-2.compute.internal systemd[1]: rke2.service lacks both ExecStart= and ExecStop= setting. Refusing.
Sep 21 07:49:35 ip-172-31-9-158.us-east-2.compute.internal systemd[1]: [/usr/local/share/rke2/rke2.service:25] Executable path is not absolute, ignoring: rke2 server
Sep 21 07:49:35 ip-172-31-9-158.us-east-2.compute.internal systemd[1]: rke2.service lacks both ExecStart= and ExecStop= setting. Refusing.
````

**Comment by davidnuzik** [comment]
@ShylajaDevadiga could you please open a new GH issue to track the docs changes you'd like to see? Please put in GA milestone and assign to me.

**Comment by ShylajaDevadiga** [comment]
@davidnuzik Please ignore the above comment. Docs have them correct. Closing as validated
