### ISSUE TITLE
[release-1.22]  hardcode linker flag for windows runtime image

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rke2#2672]
https://github.com/rancher/rke2/pull/2669

**Comment by rancher-max** [comment]
### Validated in v1.22.8-rc6+rke2r1

- Windows is able to be installed in an airgap environment now using either private registry or tarball
- Confirmed that using the tar.gz or tar.zst are both successful with the tarball airgap approach
- Confirmed that airgap install is successful on both Windows 2022 and Windows 2019 servers.
- My high-level steps were:
```
1. Start an airgapped server node running calico (either using tarball or private registry)
2. Join an airgapped linux agent node
3. Setup windows node for airgap (by copying the tarball file into c:\var\lib\rancher\rke2\agent\images or setting up the private registry and trusting the cert via, for example: `Import-Certificate -FilePath "C:\Users\Administrator\ca.pem" -CertStoreLocation cert:\CurrentUser\Root`). Also setup `c:\etc\rancher\rke2\config.yaml` to have the server and token information to join.
4. Run `rke2.exe agent`
```
