### ISSUE TITLE
Add `-o / --output` flag to `secrets-encrypt status` and support JSON

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#2680]
**Is your feature request related to a problem? Please describe.**

k3s has support for json output in `secrets-encrypt status` https://github.com/k3s-io/k3s/issues/5138. When parsing `secrets-encrypt status` for encryption key rotation in rancher, parsing json would be preferred.

**Describe the solution you'd like**

Add `secrets-encrypt status -o/--output`. 

**Describe alternatives you've considered**

This isn't critical since currently it's possible to parse `secrets-encrypt status`, but would make it easier on the rancher side due to support for json parsing.

**Additional context**

I've implemented this change as it is fairly straightforward, and will be opening a PR shortly.

**Comment by brandond** [comment]
Thanks @jakefhyde I believe we'd intended to pull this through to RKE2 after adding it to K3s. Which Rancher release is this needed for?

**Comment by jakefhyde** [comment]
@brandond This will be needed for the v2.6.5 release.

**Comment by rancher-max** [comment]
#### Validated using master branch commitid `32da631c2e61b023b8afeabd5d9b17df0abe1346`

Status shows json output correctly. Here is how it looks on each of the stages:
- Initial (before doing anything)
```
$ sudo rke2 secrets-encrypt status -o json
{
	"stage": "start",
	"activekey": "aescbckey",
	"enable": true,
	"hashmatch": true
}
```
- After prepare
```
{
	"stage": "prepare",
	"activekey": "aescbckey",
	"enable": true,
	"hashmatch": true,
	"inactivekeys": [
		"aescbckey-2022-04-20T20:29:56Z"
	]
}
```
- After rotate
```
{
	"stage": "rotate",
	"activekey": "aescbckey-2022-04-20T20:29:56Z",
	"enable": true,
	"hashmatch": true,
	"inactivekeys": [
		"aescbckey"
	]
}
```
- reencrypt (active)
```
{
	"stage": "reencrypt_active",
	"activekey": "aescbckey-2022-04-20T20:29:56Z",
	"enable": true,
	"hashmatch": true,
	"inactivekeys": [
		"aescbckey"
	]
}
```
- reencrypt (finished)
```
{
	"stage": "reencrypt_finished",
	"activekey": "aescbckey-2022-04-20T20:29:56Z",
	"enable": true,
	"hashmatch": true
}
```
- Example for before hashes match:
```
{
	"stage": "prepare",
	"activekey": "aescbckey-2022-04-20T20:29:56Z",
	"enable": true,
	"hasherror": "hash does not match between ip-172-31-33-244 and ip-172-31-37-48",
	"inactivekeys": [
		"aescbckey-2022-04-20T21:12:31Z"
	]
}
```
