### ISSUE TITLE
Certificate rotation issue client.key: no such file or directory 

### ISSUE THREAD

**Issue by Thiritin** [rancher/rke2#2683]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.23.5-rc3+rke2r1 (8f3ff0c9b68d32890597f9815cc6b8b111e86ebc)
go version go1.17.5b7
```

```
INFO[0000] Starting rke2 v1.23.5-rc3+rke2r1 (8f3ff0c9b68d32890597f9815cc6b8b111e86ebc) 
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Starting temporary etcd to reconcile with datastore 
FATA[0000] Failed to reconcile with temporary etcd: open /var/lib/rancher/rke2/server/tls/etcd/client.key: no such file or directory 
```

Node(s) CPU architecture, OS, and Version: 
`Linux node01 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
2 Servers (On the way to setup the 3rd.)

**Describe the bug:**
After installing a new cluster on the latest version and imemdiately running certificate rotate will cause the following error.

```
INFO[0000] Starting rke2 v1.23.5-rc3+rke2r1 (8f3ff0c9b68d32890597f9815cc6b8b111e86ebc) 
INFO[0000] Managed etcd cluster bootstrap already complete and initialized 
INFO[0000] Starting temporary etcd to reconcile with datastore 
FATA[0000] Failed to reconcile with temporary etcd: open /var/lib/rancher/rke2/server/tls/etcd/client.key: no such file or directory 
```

**Steps To Reproduce:**

- Installed RKE2: 
- Used the configuration at the bottom.
Here is the install script to replicate

```bash
#! /usr/bin/bash
mkdir -p /etc/rancher/rke2/
cp /root/config /etc/rancher/rke2/config.yaml # Use the config file at the end
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.23.5-rc3+rke2r1 sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
sleep 60
rke2 certificate rotate
```

**Expected behavior:**
Certificate Rotation adds in client certificates for etcd

**Actual behavior:**
Certificate Rotation does not put client certificates into the etcd directory.

**Additional context / logs:**
```
profile: cis-1.6
write-kubeconfig-mode: "0644"
tls-san:
  - kubectl.becker-sotware.de
  - 10.0.5.1
disable:
  - rke2-ingress-nginx
  - rke2-metrics-server
protect-kernel-defaults: true
```

**Comment by galal-hussein** [comment]
@Thiritin Thanks for openning the issue, this problem is most probably a timing issue due to the fact that you didnt give it enough time for rke2 to actually start and pull the images and start the services, I would suggest that in your script that you check if node is ready and you can use kubectl properly, then try to do certificate rotate

**Comment by Thiritin** [comment]
Hey @galal-hussein,

I just ran the rotate command on my production system. Same issue.

`````
rke2 certificate rotate
service rke2-server restart
Mär 29 08:35:44 node01 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
root@node01:~# journalctl -u rke2-server.service 
Mär 28 00:49:08 node01 rke2[1696]: time="2022-03-28T00:49:08Z" level=info msg="Starting rke2 v1.23.4+rke2r2 (288ec372a6db018b71ce20112fe863072361a2a4)"
Mär 28 00:49:08 node01 rke2[1696]: time="2022-03-28T00:49:08Z" level=fatal msg="starting kubernetes: preparing server: failed to get CA certs: Get \"https://10.0.5>Mär 28 00:49:08 node01 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
````

**Comment by galal-hussein** [comment]
@Thiritin It seems that you have a misconfiguration in your cluster, this server is trying to connect to an invalid address: 
```
Get \"https://10.0.5>Mär 28 00:49:08 node01
```
can you share your config.yaml

**Comment by rancher-max** [comment]
Thank you @Thiritin for finding this issue! We ended up being able to reproduce it, so we got the fix in and validated it on all of the latest RCs:
v1.21.11-rc6+rke2r1, v1.22.8-rc6+rke2r1, and v1.23.5-rc5+rke2r1.

This was a regression that should've only been present in the pre-release RCs and not in any actual release.
