### ISSUE TITLE
Kubelet in NotReady state with beta13

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#269]
Version:
```
rke2 -v
rke2 version v1.18.4-beta13+rke2
```
NodeOS and Arch:
Ubuntu 20.04, amd 64

Describe the issue:
Installation fails with node being in NotReady state.
Logs attached
Node info:
```
 Ready            False   Mon, 31 Aug 2020 16:05:42 +0000   Mon, 31 Aug 2020 16:05:40 +0000   KubeletNotReady              [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized, CSINode is not yet initialized]
```
System log:
```
Aug 31 16:05:44 ip-172-31-32-217 systemd[1]: Started Rancher Kubernetes Engine v2.
Aug 31 16:05:44 ip-172-31-32-217 rke2[2680]: time="2020-08-31T16:05:44Z" level=info msg="Setting PSP: global-unrestricted-psp"
Aug 31 16:05:44 ip-172-31-32-217 rke2[2680]: time="2020-08-31T16:05:44Z" level=fatal msg="networkpolicies.networking.k8s.io \"default-network->
Aug 31 16:05:44 ip-172-31-32-217 systemd[1]: rke2.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 16:05:44 ip-172-31-32-217 systemd[1]: rke2.service: Failed with result 'exit-code'.

```
Command used:
```
INSTALL_RKE2_VERSION=v1.18.4-beta13+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' ./install.sh
```
[rke2.log](https://github.com/rancher/rke2/files/5151150/rke2.log)

**Comment by cjellick** [comment]
@briandowns these are the three issues that @ShylajaDevadiga has associated with directory creation:
#244
#259
#269

Can you work on these as a group and ensure theyre all working?

**Comment by briandowns** [comment]
On it. Thanks for aggregating the issues here.

**Comment by briandowns** [comment]
Work performed in PR #274

**Comment by briandowns** [comment]
Should be resolved with beta14 which I'll be cutting momentarily.

**Comment by rancher-max** [comment]
Validated this is resolved in beta14

**Comment by gellban** [comment]
**Is there a solution for rke2 version v1.21.5+rke2r2?**
Info:
Installed rke2 under proxy
$ rke2 -v
rke2 version v1.21.5+rke2r2 (9e4acdc6018ae74c36523c99af25ab861f3884da)
go version go1.16.6b7
$  kubectl describe node
....
  KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
.....

**Comment by gellban** [comment]
Is there a solution for rke2 version v1.21.5+rke2r2?
Info:
Installed rke2 under proxy
Air-Gap Install
sudo su

open inbound rules as in https://docs.rke2.io/install/requirements/
sudo bash ./ports.sh

sudo su
mkdir /root/rke2-artifacts && cd /root/rke2-artifacts/
sudo apt install curl

sudo curl --proxy proxyIP:port -OLs https://github.com/rancher/rke2/releases/download/v1.21.5%2Brke2r2/rke2-images.linux-amd64.tar.zst
sudo curl -OLs https://github.com/rancher/rke2/releases/download/v1.21.5%2Brke2r2/rke2.linux-amd64.tar.gz --proxy proxyIP:port
sudo curl -OLs https://github.com/rancher/rke2/releases/download/v1.21.5%2Brke2r2/sha256sum-amd64.txt --proxy proxyIP:port
sudo curl -sfL https://get.rke2.io/ --output install.sh --proxy proxyIP:port

sudo INSTALL_RKE2_ARTIFACT_PATH=/root/rke2-artifacts sh install.sh

sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service

sudo journalctl -u rke2-server -f

$ rke2 -v
rke2 version v1.21.5+rke2r2 (https://github.com/rancher/rke2/commit/9e4acdc6018ae74c36523c99af25ab861f3884da)
go version go1.16.6b7
$ kubectl describe node
....
KubeletNotReady container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
.....
