### ISSUE TITLE
Agent nodes require a control-plane node to join cluster instead of either that OR etcd-only node

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2697]
If giving the IP of an etcd-only node, the agent will fail to join the cluster with constant looping logs like:
```
Mar 28 19:52:32 ip-172-31-39-31 k3s[1558]: time="2022-03-28T19:52:32Z" level=info msg="Connecting to proxy" url="wss://172.31.32.154:6443/v1-k3s/connect"
Mar 28 19:52:32 ip-172-31-39-31 k3s[1558]: time="2022-03-28T19:52:32Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

This gets confusing because in a setup of just 1 etcd-only node, 1 cp-only node, and 1 agent, one must setup the etcd-only node first, then join the cp-only node using the etcd-only node's IP, then join the agent using now the cp-only node's ip. Joining other etcd-only, cp-only, or all-role nodes (default server node) does not have this limitation.

**Comment by rancher-max** [comment]
See comments from https://github.com/k3s-io/k3s/issues/5348 as this is an upstream k3s issue.

**Comment by VestigeJ** [comment]
**Validated with COMMIT=32da631c2e61b023b8afeabd5d9b17df0abe1346**

$ rke2 -v
```
rke2 version v1.23.5-dev+32da631c (32da631c2e61b023b8afeabd5d9b17df0abe1346)
go version go1.17.5b7
```

$ kubectl get nodes 
```
NAME                                          STATUS   ROLES                  AGE     VERSION
ip-172-31-21-237.us-east-2.compute.internal   Ready    <none>                 115s    v1.23.5+rke2r1
ip-172-31-25-104.us-east-2.compute.internal   Ready    control-plane,master   2m13s   v1.23.5+rke2r1
ip-172-31-29-70.us-east-2.compute.internal    Ready    etcd                   2m4s    v1.23.5+rke2r1
```

----------------------------------------------------------------------------------------
 etcd only
$ sudo cat /etc/rancher/rke2/config.yaml 
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
disable-apiserver: true
disable-scheduler: true
disable-controller-manager: true
```

control-plane, master: targeting etcd node to join cluster simultaneously as the agent
$ sudo cat /etc/rancher/rke2/config.yaml 
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
server: https://18.117.223.246:9345
disable-etcd: true
```

agent: targeting etcd node to join cluster simultaneously as the agent
$ show.figs
```
rke2 config: server: https://18.117.223.246:9345
token: coolclouds
```
