### ISSUE TITLE
Migrate images from ranchertest to rancher docker hub repo

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#27]
We need to migrate from ranchertest over to our rancher docker hub repo.

**Comment by briandowns** [comment]
EIO ticket tracking first portion of the process. https://github.com/rancherlabs/eio/issues/173 

After this is complete, I'll use the associated image tooling to update the repos, retag the releases, and push to the new image repos.

**Comment by briandowns** [comment]
This is complete and can be verified by checking each repo for a pushed image and tag. The repo list can be found in the eio ticket link above.

**Comment by rancher-max** [comment]
Leaving this one open until issue with crictl is fixed in EIO issue.

**Comment by briandowns** [comment]
crictl isn't needed and is just a nice to have. It's not impactful on this.

**Comment by rancher-max** [comment]
All necessary images are pushed and available in the rancher docker org
