### ISSUE TITLE
Support Azure Blob for backups (minio gateway mode being removed)

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#2709]
**Is your feature request related to a problem? Please describe.**

Currently only s3 is supported for etcd backups. This has been easily done by using existing s3 providers or running a minio gateway in front of something like azure blob to send the backups too. Minio is now removing their gateway feature in June which removes any possibility of backing up rke2 to azure by using minio gateway in front of azure blob storage.

https://github.com/minio/minio/issues/14331

**Describe the solution you'd like**
Support Azure Blob storage as an option for backing up rke2.

**Describe alternatives you've considered**

Run an older version of minio that still supports the gateway mode in front of blob. This will become insecure and never receive updates which makes it not an optimal option.

**Additional context**

**Comment by briandowns** [comment]
Thanks for adding this issue. I'll get this through to the folks that matter and we will figure out where this lands in the priority list.

**Comment by mitchellmaler** [comment]
@briandowns @brandond Do you know if there is any alternative to S3 for backing up RKE2 to an external destination? We are looking at moving away from Min.io now that there are no more supported updates for the gateway. 

The only other idea I have is writing a cronjob using rclone copying the etcd snapshots manually.
