### ISSUE TITLE
API resource csistoragecapacities is still refering storage.k8s.io/v1beta1 in a  v1.22.7+rke2r2 installation

### ISSUE THREAD

**Issue by mcguppy** [rancher/rke2#2712]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.7+rke2r2 (45a0df00aa42108f5a6b5c48ee221c1bed03a745)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 
Linux fmtdev02-worker-911c2312-4pqcb 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 Server
3 agents

**Describe the bug:**
After installing a new RKE2 cluster by rancher and performing a `kubectl api-resources` I get the following entry for csistoragecapacities:

`csistoragecapacities                           storage.k8s.io/v1beta1                 true         CSIStorageCapacity`

In [https://kubernetes.io/docs/reference/using-api/deprecation-guide/](url) I read the following: _The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22._

Like this, when running the primer check of the Kasten IO backup software, I am getting:
`CSI Capabilities Check:
  Cluster isn't CSI capable`

**Steps To Reproduce:**

- Installed RKE2: From rancher webgui, I created a new cluster on VMWare vSphere. When doing it by selecting v.1.21.10+rke2r2, all is okay but getting the warnings by running the Kasten K10 primer: 'W0308 13:41:14.312606       8 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver'

When installing  v.1.22.7+rke2r2, I am getting the message, the cluster isn't CSI capable. I really think this is because of the API resource `csistoragecapacities`, which is refering the not any more available ` storage.k8s.io/v1beta1`

**Expected behavior:**
'csistoragecapacities' is using 'storage.k8s.io/v1'

**Actual behavior:**
'csistoragecapacities' is using 'storage.k8s.io/v1beta1'

**Additional context / logs:**
Find attached the whole output of 'kubectl api-resources'
[api-resources_of_v1_22_7_rke2r2.txt](https://github.com/rancher/rke2/files/8408306/api-resources_of_v1_22_7_rke2r2.txt)

**Comment by brandond** [comment]
> After installing a new RKE2 cluster by rancher and performing a kubectl api-resources I get the following entry for csistoragecapacities:
> `csistoragecapacities storage.k8s.io/v1beta1 true CSIStorageCapacity`
> In https://kubernetes.io/docs/reference/using-api/deprecation-guide/ I read the following: 
>> The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.


This all sounds correct. The deprecation guide doesn't say anything about deprecating the `CSIStorageCapacity` CRD?

**Comment by mcguppy** [comment]
Thanks for your answer. I have to check then, why Kasten K10 Primer is telling me, my cluster isn't CSI capabele. The only different in the setup is using  v.1.22.7+rke2r2 instead of v.1.21.10+rke2r2. 
I really thought, this storage.k8s.io/v1beta1 API version was completely removed from v1.22.x.
