### ISSUE TITLE
Update to the latest versions of the Rancher vSphere Charts

### ISSUE THREAD

**Issue by phillipsj** [rancher/rke2#2713]
Rancher vSphere charts, both CPI and CSI have been updated. In the update process, both charts have been made into "super" charts that will detect the Kubernetes version and deploy the correct versions for both. 

The PR for RKE2 charts is here: https://github.com/rancher/rke2-charts/pull/238

Once that PR is merged, which I don't have permissions to do, the charts will need to be updated in RKE2. Those changes can be safely backported to all supported versions 1.21 or newer. The versions of the charts are below:

CSI:  2.5.1-rancher101
CPI:  1.2.101

Related Issues:
* https://github.com/rancher/rancher/issues/37005
* https://github.com/rancher/rancher/issues/37004

**Comment by phillipsj** [comment]
@cwayne18 @katran001 just so we don't lose track. /cc @sirredbeard

**Comment by phillipsj** [comment]
@rancher-max this has been merged and backported.

**Comment by rancher-max** [comment]
Purposely leaving milestone blank here as this issue is relevant and should be tested for all 3 of the upcoming releases so is relevant for: v1.23.6+rke2r1, v1.22.9+rke2r1, and v1.21.12+rke2r1

**Comment by rancher-max** [comment]
#### Validated using master branch commitid `32ab1c9e2eebb17448e851eb2ac31c4fcd662aad`

- Fresh install is successful - providerid is set and charts show they are using expected versions when viewed with `helm ls -A`
  - Image versions for components:
  ```
  daemonset.apps/rancher-vsphere-cpi-cloud-controller-manager   1         1         1       1            1           kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true   4m      rancher-vsphere-cpi-cloud-controller-manager            rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.22.6                                                                                                                 name=rancher-vsphere-cpi-cloud-controller-manager
  daemonset.apps/vsphere-csi-node                               1         1         1       1            1           <none>                                                              3m59s   node-driver-registrar,vsphere-csi-node,liveness-probe   rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.5.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0   app=vsphere-csi-node
  deployment.apps/vsphere-csi-controller                 3/3     3            3           3m59s   csi-attacher,vsphere-csi-controller,liveness-probe,vsphere-syncer,csi-provisioner   rancher/mirrored-sig-storage-csi-attacher:v3.4.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0,rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v2.5.1,rancher/mirrored-sig-storage-csi-provisioner:v3.1.0   app=vsphere-csi-controller
  ```
- General cloud provider functionality works -- am able to deploy a volume and pod and see the volume created and the pod attached in the vsphere environment
- Upgrade from v1.23.5+rke2r1 to master commit `32ab1c9e2eebb17448e851eb2ac31c4fcd662aad` is successful and the vsphere charts are updated and continue to funtion as expected

#### Validated using release-1.22 branch commitid `69e4058725dfde63818aae57689b32537ad1a0c2`
- Fresh install is successful - providerid is set and charts show they are using expected versions when viewed with `helm ls -A`
  - Image versions for components: 
  ```
  kube-system   daemonset.apps/vsphere-csi-node                               1         1         1       1            1           <none>                                                              4m50s   node-driver-registrar,vsphere-csi-node,liveness-probe   rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.5.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0   app=vsphere-csi-node
  kube-system   daemonset.apps/rancher-vsphere-cpi-cloud-controller-manager   1         1         1       1            1           kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true   4m50s   rancher-vsphere-cpi-cloud-controller-manager            rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.22.6                                                                                                                 name=rancher-vsphere-cpi-cloud-controller-manager
  kube-system   deployment.apps/vsphere-csi-controller                 3/3     3            3           4m50s   csi-attacher,vsphere-csi-controller,liveness-probe,vsphere-syncer,csi-provisioner   rancher/mirrored-sig-storage-csi-attacher:v3.4.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0,rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v2.5.1,rancher/mirrored-sig-storage-csi-provisioner:v3.1.0   app=vsphere-csi-controller
  ```
- General cloud provider functionality works -- am able to deploy a volume and pod and see the volume created and the pod attached in the vsphere environment
- Upgrade from v1.22.8+rke2r1 to release-1.22 commit `69e4058725dfde63818aae57689b32537ad1a0c2` is successful and the vsphere charts are updated and continue to funtion as expected

#### Validated using release-1.21 branch commitid `f5cf6ab45a591b10bc5f937f349e1cbda0671ac1`

- Fresh install is successful - providerid is set and charts show they are using expected versions when viewed with `helm ls -A`
  - Image versions for components: 
  ```
  daemonset.apps/rancher-vsphere-cpi-cloud-controller-manager   1         1         1       1            1           kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true   8m36s   rancher-vsphere-cpi-cloud-controller-manager            rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.21.3                                                                                                                 name=rancher-vsphere-cpi-cloud-controller-manager
  daemonset.apps/vsphere-csi-node                               1         1         1       1            1           <none>                                                              8m36s   node-driver-registrar,vsphere-csi-node,liveness-probe   rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.5.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0   app=vsphere-csi-node
  deployment.apps/vsphere-csi-controller                 3/3     3            3           8m36s   csi-attacher,vsphere-csi-controller,liveness-probe,vsphere-syncer,csi-provisioner   rancher/mirrored-sig-storage-csi-attacher:v3.4.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1,rancher/mirrored-sig-storage-livenessprobe:v2.6.0,rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v2.5.1,rancher/mirrored-sig-storage-csi-provisioner:v3.1.0   app=vsphere-csi-controller
  ```
- General cloud provider functionality works -- am able to deploy a volume and pod and see the volume created and the pod attached in the vsphere environment
- Upgrade from v1.21.11+rke2r1 to release-1.21 commit `f5cf6ab45a591b10bc5f937f349e1cbda0671ac1` is successful and the vsphere charts are updated and continue to funtion as expected

**Comment by rancher-max** [comment]
@phillipsj I realize I probably shouldn't have just closed this without confirming, but let me know if those component version look wrong and if so we can reopen and work to resolve that.

**Comment by phillipsj** [comment]
@rancher-max LGTM! Thanks for getting that tested so quickly.
