### ISSUE TITLE
Quick start guide: kubectl connection refused

### ISSUE THREAD

**Issue by dpearceMN** [rancher/rke2#2714]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.7+rke2r2 (45a0df00aa42108f5a6b5c48ee221c1bed03a745)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 
Linux rke2server1 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
One server

**Describe the bug:**
Followed the quick start guide. Ran this command and got this error message:
# /var/lib/rancher/rke2/bin/kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Steps To Reproduce:**
- Installed RKE2: 
- Ran "kubectl get nodes"

**Expected behavior:**
A listing of the server node.

**Actual behavior:**
Error message: The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Additional context / logs:**
# /var/lib/rancher/rke2/bin/kubectl config view
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null

**Comment by dpearceMN** [comment]
Found this in the README.md file. It is not in the quick start instructions.
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin

Should be added to https://docs.rke2.io/install/quickstart/

**Comment by brandond** [comment]
It is called out on that page:
> * Additional utilities will be installed at /var/lib/rancher/rke2/bin/. They include: kubectl, crictl, and ctr. Note that these are not on your path by default.
> * A [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) file will be written to /etc/rancher/rke2/rke2.yaml.
