### ISSUE TITLE
Helm Controller : Debug and trace helmcharts (CRD) deployment

### ISSUE THREAD

**Issue by khalid-lemghari** [rancher/rke2#2715]
Hello,

Is there a feature to debug a helmchart deployment or trace that ?

Before to copy the helmchart to **/var/lib/rancher/rke2/server/manifests/**, I try to apply it using : **kubectl apply -f gitlab-runner.yml**. But sometimes I got nothing  in return to know where the errors.

Best regards,

**Comment by brandond** [comment]
You can check the Helm job pod logs to view the logs from the chart install/upgrade process.

**Comment by khalid-lemghari** [comment]
Hello @brandond,

So no other way to check that like **kubectl get events** or **kubectl describre helmchart**. It must to connect to masters and collects rke2-server logs.

Thank you so much @brandond

**Comment by brandond** [comment]
If the HelmChart manifest is so broken that the controller can't figure out how to create a Job, then yes you would need to check the error logs in the rke2-server output. For failures to actually install the Helm chart specified by the manifest, you could check the job pod logs.
