### ISSUE TITLE
trailing / on /v2/ path in /etc/rancher/rke2/registries.yaml endpoint address no longer works

### ISSUE THREAD

**Issue by katran001** [rancher/rke2#2717]
Issue description:
Upon upgrade from v1.20.6+rke2r1 to v1.20.15+rke2r1, in an air-gapped environment with a private registry using the /etc/rancher/rke2/registries.yaml, RKE2 fails to start where the docker.io mirror endpoint specifies the v2 path with a trailing / i.e. /v2/

Business impact:
If a user has a trailing slash on the docker.io mirror endpoint address in their /etc/rancher/rke2/registries.yaml file and they upgrade to an affected RKE2 version, RKE2 will not start

Troubleshooting steps:
N/A

Repro steps:

Create a private registry with authentication and populate with the images for v1.20.6+rke2r1 and v1.20.15+rke2r1
Provision RKE2 instances with v1.20.6+rke2r1 and v1.20.15+rke2r1, in each configuration test the effect of using a /etc/rancher/rke2/registries.yaml file of the format below to use the private registry, setting the path in the endpoint to /v2/ , /v2 and removing the path altogether.
In v1.20.6+rke2r1 all three paths work, i.e. https://aseymour-registry.do.support.rancher.space:5000/, https://aseymour-registry.do.support.rancher.space:5000/v2 and https://aseymour-registry.do.support.rancher.space:5000/v2/
In v1.20.15+rke2r1 this works without the path or a trailing slash, i.e. https://aseymour-registry.do.support.rancher.space:5000/ and https://aseymour-registry.do.support.rancher.space:5000/v2 but not with the trailing slash, i.e. https://aseymour-registry.do.support.rancher.space:5000/v2/
The error logged where the trailing slash is present is of the following format: Feb 09 09:42:57 rancher3 rke2[109269]: time="2022-02-09T09:42:57+01:00" level=warning msg="Failed to get image from endpoint: GET https://aseymour-registry.do.support.rancher.space:5000/v2/rke-test/docker.io/rancher/rke2-runtime/manifests/v1.20.15-rke2r1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:rke-test/docker.io/rancher/rke2-runtime Type:repository]]"
 

mirrors:
  docker.io:
    endpoint:
      - "https://aseymour-registry.do.support.rancher.space:5000/v2/"
    rewrite:
      "^(?:library|)(.*)": "rke-test/docker.io/$1"
configs:
  "aseymour-registry.do.support.rancher.space:5000":
    auth:
      username: rke-cluster-test
      password: _Ey4sYq1wAyBUSfjcsQY
    tls:
      ca_file: /etc/rancher/rke2/ca.crt 
 

 

Workaround:
Is workaround available and implemented? Yes
What is the workaround: exclude path from endpoint address or remove trailing slash (i.e. /v2 not /v2/)

Actual behavior:
Trailing slash on endpoint address with path specified, e.g. https://registry.example.com:5000/v2/ continues to work as it did in previous RKE2 versions

Expected behavior:
Trailing slash on endpoint address with path specified, e.g. https://registry.example.com:5000/v2/ does not work

Files, logs, traces:
N/A

Additional notes:

Comparing https://github.com/rancher/rke2/blob/v1.20.6%2Brke2r1/pkg/bootstrap/bootstrap.go and https://github.com/rancher/rke2/commits/v1.20.15%2Brke2r1/pkg/bootstrap/bootstrap.go I belive the issue may originate in the switch to wharfie, and in the function here https://github.com/rancher/wharfie/blob/v0.5.1/pkg/registries/endpoint.go#L41 
https://github.com/rancher/wharfie/blob/v0.5.1/pkg/registries/endpoint.go#L41

**Comment by katran001** [comment]
Tracking internally as SURE-4299

**Comment by rancher-max** [comment]
Should validate this using release artifacts once we have RCs on **all** of v1.21.12, v1.22.9, and v1.23.6.

This might get messy with upgrading from something as old as v1.20.6 to v1.23.6 but I'm going to try it anyway.

**Comment by rancher-max** [comment]
I was able to see the successful result using v1.20.6+rke2r1 and the failure using v1.21.11+rke2r1 and v1.20.15+rke2r1. My steps were:
1. Create cluster with private registry without the `/v2/` in the endpoint, using specified version with 1 server 1 agent
2. Uninstall the agent and delete the node from the cluster
3. Update registries.yaml on the agent to append `/v2/` to the endpoint
4. Rerun the agent

I will perform these same steps on all RCs when available.

**Comment by rancher-max** [comment]
Validated in all of v1.23.6-rc2+rke2r1, v1.22.9-rc2+rke2r1, and v1.21.12-rc2+rke2r1 following the same steps as above and saw success.
