### ISSUE TITLE
Unable to resolve DNS

### ISSUE THREAD

**Issue by rollathi** [rancher/rke2#2720]
**OS:**
Debian 11 (5.10.0-12-amd64)

**RKE2:**
rke2 version v1.22.7+rke2r2 (45a0df00aa42108f5a6b5c48ee221c1bed03a745)
go version go1.16.10b7

**Cluster:**
1 master, 5 workers

**Installation:**
https://docs.rke2.io/install/quickstart/

**Error:**
Unable to resolve DNS

**Pod:**
rke2-coredns-rke2-coredns-5679c85bbb-tttvm (`Warning: Back-off restarting failed container`)
**Namespace:**
kube-system

**Logs:**
```log
[ERROR] plugin/errors: 2 <name.domain>. A: read udp 10.42.0.3:56189->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 <name.domain>. AAAA: read udp 10.42.0.3:45751->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 <name.domain>. A: read udp 10.42.0.3:48669->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 <name.domain>. AAAA: read udp 10.42.0.3:46008->8.8.8.8:53: i/o timeout
...
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:45487->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:43913->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:49292->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:45794->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:45469->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:34692->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:36560->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:41170->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:40762->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1451436619335120735.1781604709331512472. HINFO: read udp 10.42.0.3:36323->8.8.8.8:53: i/o timeout
```

**Comment by WolfspiritM** [comment]
Did you update from a previous rke2 version?
Are you using calico by any chance?
I had an issue after the upgrade where calico didn't update and/or install correctly.

It took me ages to debug that and it started with DNS issues but also services from one node not being able to talk with services on another node. The calico namespace was stuck in the deleted state and I had to remove the rancher webhook to actually got it deleted. After recreation it seems to have been set up the wrong way.
What worked for me is doing a:
```kubectl -n calico-system edit FelixConfiguration default```
and making sure to add ```vxlanEnabled: true``` to the specs.
The update/reinstall somehow removed that entry.
On another cluster it didn't remove the calico namespace and the resource at all somehow and there it worked fine.

**Comment by rollathi** [comment]
Thanks for your answer but I don't use calico.
In fact, it's a brand new cluster so for now, I have classic debian 11 via netinstall on which I followed the documentation to install rke2.
The only configuration done is the one provided by the doc, ie on the workers I modified `/etc/rancher/rke2/config.yaml` adding my server and its token.
