### ISSUE TITLE
disable-kube-proxy should remove kube-proxy pod manifest

### ISSUE THREAD

**Issue by WMP** [rancher/rke2#2728]
**Environmental Info:**
RKE2 Version: v1.22.7+rke2r1 

**Describe the bug:**
Options to disable  kube-proxy should remove pod manifest from /var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml if exists.

**Steps To Reproduce:**
1. Deploy cluster without options `disable-kube-proxy: true` and `disable: - rke2-kube-proxy`
2. Add options to disable kube-proxy
3. Restart rke2

**Expected behavior:**
I want to not have kube-proxy, but it still exists in `ps aufx` or `iptables-save | grep KUBE-SVC`

**Actual behavior:**
Kube-proxy is still enable.

**Comment by brandond** [comment]
Hmm, we don't have any logic in core RKE2 to clean up iptables rules, other than those in the uninstaller. Cleaning up the static pod manifest is reasonable, but we might need to advise rebooting, uninstalling/reinstalling, or manually clearing iptables rules after disabling kube-proxy on a running host, just to get those rules purged.

**Comment by EugenMayer** [comment]
Just if anybody run's into the same issue. To uninstall the kube-proxy properly, you will need to remove the manifest manually

```
sudo rm /var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml
sudo systemctl restart rke2-agent
```

You will still need to set `disable-kube-proxy: true` so it will not be re-added on the next rke2 upgrade, but you will have to uninstall it once manually

**Comment by EugenMayer** [comment]
@brandond i understand then hot-fixing iptables is not something you would invest in, those would be fixed after a simple reboot anyway.

But is there any chance we could care about that manifest? Siince this will force the actualy kube-proxy to be re-deployed again and again.

**Comment by brandond** [comment]
The PR linked above will remove the manifest when kube-proxy is disabled.

**Comment by rancher-max** [comment]
#### Validated using master branch commitid `32da631c2e61b023b8afeabd5d9b17df0abe1346`

Steps:
1. Ran rke2-server process with config.yaml like:
```
write-kubeconfig-mode: 644
```
2. Ensured the kube-proxy static pod manifest was present and was running in the cluster:
3. Updated config.yaml to disable kube-proxy static pod:
```
write-kubeconfig-mode: 644
disable-kube-proxy: true
```
4. Restarted rke2-server process
5. Ensured kube-proxy static pod manifest was no longer present and kube-proxy pod was not running in the cluster:
```
$ sudo ls /var/lib/rancher/rke2/agent/pod-manifests/
cloud-controller-manager.yaml  etcd.yaml  kube-apiserver.yaml  kube-controller-manager.yaml  kube-scheduler.yaml


NAME                   STATUS   ROLES                       AGE   VERSION          INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-172-31-43-97   Ready    control-plane,etcd,master   21m   v1.23.5+rke2r1   172.31.43.97   <none>        Ubuntu 20.04.3 LTS   5.11.0-1022-aws   containerd://1.5.11-k3s1

NAMESPACE     NAME                                                        READY   STATUS      RESTARTS        AGE     IP             NODE              NOMINATED NODE   READINESS GATES
kube-system   pod/cloud-controller-manager-ip-172-31-43-97                1/1     Running     0               3m35s   172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/etcd-ip-172-31-43-97                                    1/1     Running     0               3m47s   172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/helm-install-rke2-canal-qbkgf                           0/1     Completed   0               20m     172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-bc59w                         0/1     Completed   0               20m     172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-2c7ml                   0/1     Completed   0               20m     10.42.0.4      ip-172-31-43-97   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-xtg4m                  0/1     Completed   0               20m     10.42.0.5      ip-172-31-43-97   <none>           <none>
kube-system   pod/kube-apiserver-ip-172-31-43-97                          1/1     Running     0               20m     172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/kube-controller-manager-ip-172-31-43-97                 1/1     Running     0               3m35s   172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/kube-scheduler-ip-172-31-43-97                          1/1     Running     0               3m35s   172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/rke2-canal-jmg2x                                        2/2     Running     0               20m     172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-547d5499cb-4cwf7              1/1     Running     1 (4m38s ago)   20m     10.42.0.11     ip-172-31-43-97   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-65c9bb465d-kqjcs   1/1     Running     1 (4m39s ago)   20m     10.42.0.10     ip-172-31-43-97   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-xnw2j                     1/1     Running     0               20m     172.31.43.97   ip-172-31-43-97   <none>           <none>
kube-system   pod/rke2-metrics-server-6564db4569-ctdf7                    1/1     Running     1 (4m39s ago)   20m     10.42.0.9      ip-172-31-43-97   <none>           <none>
```

**Comment by pschichtel** [comment]
@rancher-max @brandond I just faced this issue again I think: I disabled kube-proxy after initial deployment (`v1.31.3+rke2r1`) and the kube-proxy manifests and pods remained until I manually removed it from all nodes. Upon manifest removal, the pods instantly went to Error and disappeared.

Should I file a new issue for this?

**Comment by brandond** [comment]
I suspect you've not done it in the correct order. Kube-proxy needs to be disabled on the server, and then all nodes restarted. I am not aware of any current defects that would cause it to not be cleaned up if disabled properly.

**Comment by Velociraptor85** [comment]
Same for me with _v1.31.7+rke2r1_ on rancher-manager _v2.11.3_ manually deleting the mentioned file fixed it for me. Thanks.
