### ISSUE TITLE
Server Nodes randomly fail becoming Not Ready

### ISSUE THREAD

**Issue by linus365** [rancher/rke2#2733]
**Environmental Info:**
RKE2 Version: 
```
~ » rke2 --version                                                                                                                                              
rke2 version v1.23.5+rke2r1 (e94a55acebfb58595e26e17b2e280d97dc15965e)
go version go1.17.5b7
```

Node(s) CPU architecture, OS, and Version: 
```
Linux node-01 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux node-02 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux node-03 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
3 netcup root servers set up as rke2 server nodes.

**Describe the bug:**
All three nodes sometimes randomly fail and become not ready since i upgraded to 1.23.5+rke2r1.
I usually only have to restart the rke2-server service on the node and it comes back up. But this causes downtime on my loads.
The logs from the node right before the failure can be found below in the logs section.

**Steps To Reproduce:**
- Installed RKE2: i only used tls-san and node-label flags besides the server and token values

**Expected behavior:**
Cluster should be stable and nodes should not fail without a proper reason

**Actual behavior:**
Nodes randomly become not ready

# Logs

### rke2-server
[node-01_rke2-server.log](https://github.com/rancher/rke2/files/8450613/node-01_rke2-server.log)

### kube-system
[node-01_kube-system.log](https://github.com/rancher/rke2/files/8450641/node-01_kube-system.log)

### rke2-server
[node-02_rke2-server.log](https://github.com/rancher/rke2/files/8454957/node-02_rke2-server.log)

### kube-system
[node-02_kube-system.log](https://github.com/rancher/rke2/files/8454927/node-02_kube-system.log)

### rke2-server
[node-03_rke2-server.log](https://github.com/rancher/rke2/files/8454958/node-03_rke2-server.log)

### kube-system
[node-03_kube-system.log](https://github.com/rancher/rke2/files/8454930/node-03_kube-system.log)

**Comment by brandond** [comment]
Your log lines are both truncated AND redacted so I can't quite tell exactly what's going on. Can you attach the rke2-server logs from journald, as well as the output of `head -n -1 /var/log/pods/kube-system_*/*/*.log`, from all three nodes?

**Comment by linus365** [comment]
@brandond 
I now also added the kube-system logs for the node which failed. 
I added it in form of a file, since it's so much content.

**Comment by linus365** [comment]
Hey, it happened again. 
I did not have this issue before on 1.22.
It's new with 1.23.5. 
Do you have an idea what it could be? @brandond

**Comment by linus365** [comment]
@brandond 
Hey, will you take a look at this as well? It continuously happens and only since i updated to 1.23.5.
So I am pretty sure that it is a new issue with that version.

**Comment by brandond** [comment]
All I see is this repeating:
```
pr 07 12:14:39 node-01 rke2[1609849]: time="2022-04-07T12:14:39+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:40 node-01 rke2[1609849]: time="2022-04-07T12:14:40+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:41 node-01 rke2[1609849]: time="2022-04-07T12:14:41+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:42 node-01 rke2[1609849]: time="2022-04-07T12:14:42+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:43 node-01 rke2[1609849]: time="2022-04-07T12:14:43+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:44 node-01 rke2[1609849]: time="2022-04-07T12:14:44+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:45 node-01 rke2[1609849]: time="2022-04-07T12:14:45+02:00" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
Apr 07 12:14:45 node-01 rke2[1609849]: time="2022-04-07T12:14:45+02:00" level=info msg="Shutting down k3s.cattle.io/v1, Kind=Addon workers"
Apr 07 12:14:45 node-01 rke2[1609849]: time="2022-04-07T12:14:45+02:00" level=fatal msg="context canceled"
Apr 07 12:14:45 node-01 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 12:14:45 node-01 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Apr 07 12:14:45 node-01 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
```

This suggests that containerd is failing to start up the CRI plugin for some reason. What does the log at `/var/lib/rancher/rke2/agent/containerd/containerd.log` say?

**Comment by linus365** [comment]
Hey brandond, thanks for your suggestion. I sadly don't have those logs anymore. But the nodes have stabilized without any action from my side. If this happens again I will check the containerd logs. Thanks :)
