### ISSUE TITLE
RKE2 1.23 ignoring HelmChartConfig for cilium configuration

### ISSUE THREAD

**Issue by susenguyen** [rancher/rke2#2738]
**Environmental Info:**
RKE2 Version: 1.23.5

rke2 version v1.23.5+rke2r1 (e94a55acebfb58595e26e17b2e280d97dc15965e)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 

Linux rke-32 5.3.18-24.96-default #1 SMP Mon Nov 22 08:33:36 UTC 2021 (9a413cc) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 masters

**Describe the bug:**

We are trying to configure cilium, more specifically the port the prometheus exporter is served on with the following HelmChartConfig:

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      prometheus:
        enabled: true
        port: 6943

The exact same config reconfigures the cilium-config ConfigMap on RKE2 1.21.8 with prometheus-serve-addr set to 6943.
On RKE2 1.23.5, prometheus-serve-addr is unchanged from its default value of 9090.

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Please see the **Important Note** at the top of the release notes: https://github.com/rancher/rke2/releases/tag/v1.23.5%2Brke2r1

**Comment by susenguyen** [comment]
Sorry, we completely missed those notes...
The new syntax is working fine. Thanks!
