### ISSUE TITLE
RKE2- VIP cluster not responding when only 1 master is available

### ISSUE THREAD

**Issue by Mohammed-Idrees** [rancher/rke2#2753]
Hi Team,

|Node-IP|Role|OS|
|:------|:------|:------|
|192.x.x.101| Control-Plane|RHEL 8|
|192.x.x.102|Control-Plane|RHEL 8|
|192.x.x.103|Control-Plane|RHEL 8|
|192.x.x.107|Worker|RHEL 8|
|192.x.x.108|Worker|RHEL 8|
|192.x.x.109|Worker|RHEL 8|
|192.x.x.105|VIP||

# Use-Cases #

|No of Masters Ready/Running|Expected|Actual|
|:------|:------|:------|
|3 Masters|Ingress Created with VIP IP and ping to VIP should work|VIP is working|
|2 Masters|Ingress Created with VIP IP and ping to VIP should work|VIP is working|
|1 Master|Ingress Created with VIP IP and ping to VIP should work| VIP is not working, Kubectl is not responding|

I have Created a RKE2 HA Cluster with **kube-vip** and cluster is working fine only when atleast 2 master are in Running, but I want to test a use case where only 1 master is available the VIP should be able to ping and any ingress created with VIP address should work.

In my case when 2 masters are down I'm facing an issue with kube-vip-ds pod, when i check the logs using crictl command I'm getting the below error can someone suggest to me how to reslove this issue.

<pre><code>
E0412 12:32:20.733320  1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: etcdserver: request timed out
E0412 12:32:20.733715  1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: etcdserver: request timed out
E0412 12:32:25.812202  1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
E0412 12:32:25.830219  1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
E0412 12:33:27.204128  1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: the server was unable to return a response in the time allotted, but may still be processing the request (get leases.coordination.k8s.io plndr-cp-lock)
E0412 12:33:27.504957  1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: the server was unable to return a response in the time allotted, but may still be processing the request (get leases.coordination.k8s.io plndr-svcs-lock)
E0412 12:34:29.346104  1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: the server was unable to return a response in the time allotted, but may still be processing the request (get leases.coordination.k8s.io plndr-cp-lock)
E0412 12:34:29.354454  1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: the server was unable to return a response in the time allotted, but may still be processing the request (get leases.coordination.k8s.io plndr-svcs-lock)
</code></pre>

Thanks.

**Comment by brandond** [comment]
If you take 2/3 of the servers down, the control-plane is non-functional. You must ensure that the etcd cluster retains quorum in order for control-plane functionality to be available. It sounds like your VIP node requires access to the control-plane in order to route traffic to the workers. Have you considered running the VIP on the workers themselves, instead of making it a single point of failure on a dedicated node?
