### ISSUE TITLE
Bump Harvester Cloud Provider 0.1.11

### ISSUE THREAD

**Issue by rebeccazzzz** [rancher/rke2#2765]
There’s already a PR for this: https://github.com/rancher/rke2/pull/2754

The latest version of Harvester Cloud Provider contains a couple of bug fixes needed for Harvester 1.0.2.

We also want to backport this to RKE2 v1.21.x (PR https://github.com/rancher/rke2/pull/2766), v1.22.x (PR https://github.com/rancher/rke2/pull/2767) and v1.23.x (PR https://github.com/rancher/rke2/pull/2754).

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher v2.6.4 with the KDM April RC release URL with the following RKE2 version:
https://raw.githubusercontent.com/nikolaishields/kontainer-driver-metadata/april_release_rke2/data/data.json

* v1.23.6-rc3+rke2r1
* v1.22.9-rc3+rke2r1

### Result
* Harvester Cloud Provider have been bumped to v0.1.1100 on RKE2 `v1.23.6-rc3+rke2r1`
  ![image](https://user-images.githubusercontent.com/29251855/164967759-6d9bcb1c-0d73-45b7-8133-ccc11ec00bef.png)

* Harvester Cloud Provider have been bumped to v0.1.1100 on RKE2 `v1.22.9-rc3+rke2r1`
  ![image](https://user-images.githubusercontent.com/29251855/164970037-35d4dbf4-2ecf-48e8-bf0a-e95dbfb21d94.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: ` master-03ee6213-head` (04/18)
* Rancher version: v2.6.4

### Verify Steps
1. Open  Global Settings → rke-metadata-config 
2. Update the URL with the April RC release URL
https://raw.githubusercontent.com/nikolaishields/kontainer-driver-metadata/april_release_rke2/data/data.json
3. Re-login Rancher UI
4. Provision a RKE2 cluster in Harvester with `v1.23.6-rc3+rke2r1`
5. Provision a RKE2 cluster in Harvester with `v1.22.9-rc3+rke2r1`
6. Open Cluster management
7. Open Apps -> Installed Apps
8. Check the version of Harvester CSI driver and Cloud provider
