### ISSUE TITLE
Validate Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2780]
https://ubuntu.com/about/release-cycle -- We should validate this in rke2 when this is available.

**Comment by rancher-max** [comment]
This has been validated in all branches and we have been using it as our primary OS when testing issues lately.

**Comment by crumohr** [comment]
The documentation does not mention 22.04, which information is correct @rancher-max ?

https://docs.rke2.io/install/requirements/#operating-systems

**Comment by rancher-max** [comment]
We validated 22.04 works, so the information here. The docs just haven't been updated to reflect that there yet, but it shows it here: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-9/#anchor-h4-item1
