### ISSUE TITLE
Documentation on how to load air-gap images into registry

### ISSUE THREAD

**Issue by aetherith** [rancher/rke2#2788]
**Is your feature request related to a problem? Please describe.**

I am trying to load the contents of the airgap installation tarball into a Docker registry behind the airgap so all of my containerization platforms utilize the same tools to interact with their resources. I cannot seem to get either `podman` or `skopeo` to recognize the type of archive it is sufficiently to upload the images contained within.

**Describe the solution you'd like**

Some basic documentation on how one might load the airgap tarball into a Docker Registry when already inside the airgap. Examples using `skopeo` would be extra nice. Even a short script that would transform the archive into a format which `library/registry:2` will read and serve out correctly would be great.

**Describe alternatives you've considered**

None, if there's not an easy way to load it into the registry it will be annoying but not a dealbreaker.

**Comment by brandond** [comment]
You might join in on the discussion at https://github.com/rancher/rke2/issues/2732
