### ISSUE TITLE
DNS round robin server join works inconsistently

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#2789]
**Environmental Info:**
RKE2 Version: 1.22.7-rke2r2

Node(s) CPU architecture, OS, and Version: Ubuntu 20.04

Cluster Configuration:
3 servers
2 agents

**Describe the bug:**
Using DNS round robin for the server join URL is an officially supported method according to the RKE2 docs. However this does not work very well in practice. It seems like however the join logic is written, it will stick to a single IP that was resolved for a long time, resulting in needing to reboot the VM in order to get it to try to join again. Otherwise you will see an etcd error that there are no healthy endpoints.

**Steps To Reproduce:**
1. Use DNS round robin to define your server node IPs
2. Deploy RKE2 a few times
3. Everytime you deploy a node, you have a 33% chance of it sticking to the wrong IP and never joining until the VM is rebooted

**Expected behavior:**
Round robin should try all the IPs on the A-record

**Actual behavior:**
The join logic sticks to one IP

**Comment by brandond** [comment]
What is the TTL on your round-robin DNS record? Neither rke2 nor the golang resolver will do any caching internally, but it is likely that your host is running a local resolver (systemd-resolved or the like) that is caching the DNS lookup for at least as long as the TTL on the record.

**Comment by braunsonm** [comment]
The TTL is 1 hour, is the recommended practice to set this as low as possible? From what I understand the lowest possible setting for a TTL is 30 seconds.

**Comment by brandond** [comment]
If you set the TTL to an hour then the client is allowed to cache that result and use it for up to an hour, so the behavior you're describing is to be expected given your TTL. You can set the TTL as low as you like, something around 5 seconds might be appropriate for what you're doing.

**Comment by braunsonm** [comment]
Who is the client? As I said, `systemd-resolved` caches all 3 server IPs returned by the DNS for that A-Record. This is fine to store for 1 hour since my server IPs do not change. So is RKE2 wrongly caching a single IP?

**Comment by braunsonm** [comment]
> As I said above we don't specifically cache anything, nor do we try all endpoints if the lookup returns multiple. We simply use the golang http client to make a request to the provided server URL That in turn handles the DNS lookup by using the first address returned.

This is disappointing. Have you thought about changing this behaviour? It is unclear to me how the internals of the golang http client work when there are multiple DNS results. I'm not sure setting a TTL would even help here if it is just returning the first result.

**Comment by brandond** [comment]
Some managed DNS services may enforce a higher lower limit on the TTL value to reduce load on their servers. Theoretically you can even set it to 0.

**Comment by braunsonm** [comment]
Thanks @brandond for clearing that up. I'll play around with some settings!
