### ISSUE TITLE
Ability to pass version as param to install script while using rpm install for testing

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#279]
Version
rke2 -v
rke2 version v1.18.4-beta11+rke2 (b459d18894e4f2a625e309f686cd95aa1cccf304)

Describe the issue:
While the latest version is beta13, INSTALL_RKE2_CHANNEL-"testing" selects latest version as the version to install as set in https://github.com/rancher/rke2/blob/master/channels.yaml.

We could have an option to pass version and have default set to latest version

**Comment by davidnuzik** [comment]
The concept is having an option similar to INSTALL_K3S_VERSION much like in rancher/k3s install.sh which allows QA to select specific releases to install/test with.

**Comment by davidnuzik** [comment]
If we can get this to work with a specific RPM version, the install script at least needs to error out.

**Comment by davidnuzik** [comment]
Note, the documentation at present also mentions INSTALL_RKE2_VERSION, however this does not work currently.
https://docs.rke2.io/install/install_options/install_options/#configuring-the-installation-script

**Comment by davidnuzik** [comment]
IIRC, there is or was also an issue with RPM s3 bucket we used - was deleting older RPMS - we can't have that -- if we're going to support specifying INSTALL_RKE2_VERSION the user should be able to specify any prior version (within reason). For example, a year or so from now a user specifies a very old RKE2 version - this should work on RHEL-like systems.

**Comment by davidnuzik** [comment]
We think it logical to do this first before the COMMITID feature. (Tracked via https://github.com/rancher/rke2/issues/62)
