### ISSUE TITLE
v1.22.9-rc2+rke2r1 and v1.23.6-rc2+rke2r1 fail to fully come up when installing via RPM

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2808]
**Environmental Info:**
RKE2 Version: 

v1.22.9-rc2+rke2r1
v1.23.6-rc2+rke2r1
NOT v1.21

Node(s) CPU architecture, OS, and Version: 

RHEL 8.5 and Rocky 8.4
```
$ uname -a
Linux ip-172-31-38-71.us-east-2.compute.internal 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Thu Jun 17 07:52:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

Cluster Configuration:

1 server

**Describe the bug:**

`pod/helm-install-rke2-canal` and `pod/helm-install-rke2-coredns` are both stuck in CrashLoopBackoff with the same error:
```
+ helm_v3 install --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 --set-string global.systemDefaultRegistry= rke2-coredns /tmp/rke2-coredns.tgz
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
```

**Steps To Reproduce:**

- Install rke2 using RPMs: `curl -sfL https://get.rke2.io/ | sudo INSTALL_RKE2_VERSION=v1.23.6-rc2+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -`
- Start the service: `sudo systemctl enable rke2-server.service --now`

**Expected behavior:**

All pods should be up and running

**Actual behavior:**

Coredns and the CNI both don't install due to the helm install error. I have confirmed this happens with both calico and canal (and haven't tried cilium).

**Additional context / logs:**

It seems this only happens when doing an RPM install, and not when installing via tar via the commit: `INSTALL_RKE2_COMMIT=7a3800793a34100dbceab5d6b749488320d4dcaf`

**Comment by brandond** [comment]
Confirmed that this is due to container-selinux pulling the k3s/rke2 containerd contexts back out. Now that they are removed, we need to update rke2-selinux and k3s-selinux to reclaim ownership of the paths removed in:
* https://github.com/containers/container-selinux/pull/162

In the mean time, the issue can be worked around with:
```bash
yum install container-selinux-2:2.167.0-1.module+el8.5.0+710+4c471e88 'dnf-command(versionlock)' -y
yum versionlock container-selinux
```

**Comment by dweomer** [comment]
> Confirmed that this is due to container-selinux pulling the k3s/rke2 containerd contexts back out. Now that they are removed, we need to update rke2-selinux and k3s-selinux to reclaim ownership of the paths removed in:
> 
> * [remove k3s fcontexts containers/container-selinux#162](https://github.com/containers/container-selinux/pull/162)
> 
> In the mean time, the issue can be worked around with:
> 
> ```shell
> yum install container-selinux-2:2.167.0-1.module+el8.5.0+710+4c471e88 'dnf-command(versionlock)' -y
> yum versionlock container-selinux
> ```

Ah, k3s policy should be fine. Did we miss rke2?

**Comment by brandond** [comment]
Apparently K3s is also having issues with container-selinux v2.172.1 or newer, so there is apparently still something to be resolved on that side as well. I do find it suspicious that rolling back the policy fixes the issue; there appears to be some combination of containerd 1.5.11 (with the reduced default linux capabilities) and the new selinux policy that causes problems. I suspect that perhaps the excessive privilege was papering over some previously-unnoticed gap in policy.

**Comment by dweomer** [comment]
> I suspect that perhaps the excessive privilege was papering over some previously-unnoticed gap in policy.

Usually this is exactly right and probably so here as well.

**Comment by rancher-max** [comment]
#### Validated using v1.23.6-rc4+rke2r1

Install is successful and regression tests pass
