### ISSUE TITLE
*.cluster.x-k8s.io resources not resolving in 1.22

### ISSUE THREAD

**Issue by aendi123** [rancher/rke2#2815]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.8+rke2r1 (bd020f4f0c54f8dcd99fc26a7ea503367741c99d)
go version go1.16.14b7

Node(s) CPU architecture, OS, and Version: 
AlmaLinux 8.5 Kernel 4.18.0-348.20.1.el8_5.x86_64

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
```
$ kubectl api-resources | grep cluster.x-k8s.io
clusters                                   cl                                                        cluster.x-k8s.io/v1alpha4                   true         Cluster
machinedeployments                         md                                                        cluster.x-k8s.io/v1alpha4                   true         MachineDeployment
machinehealthchecks                        mhc,mhcs                                                  cluster.x-k8s.io/v1alpha4                   true         MachineHealthCheck
machines                                   ma                                                        cluster.x-k8s.io/v1alpha4                   true         Machine
machinesets                                ms                                                        cluster.x-k8s.io/v1alpha4                   true         MachineSet

$ kubectl get cl,md,mhc,ma,ms
Error from server (InternalError): Internal error occurred: error resolving resource
Error from server (InternalError): Internal error occurred: error resolving resource
Error from server (InternalError): Internal error occurred: error resolving resource
Error from server (InternalError): Internal error occurred: error resolving resource
Error from server (InternalError): Internal error occurred: error resolving resource
```

![image](https://user-images.githubusercontent.com/40163655/164983255-07d024b2-a025-48a4-bfea-b753b7c061d3.png)

I installed an RKE2 v1.21 cluster some time ago and recently upgraded to v1.22. Since then ArgoCD 2.3.3 isn't usable anymore, because it tries to get *.cluster.x-k8s.io resources and gets the error `error resolving resource`. This prevents the sync of applications.

**Steps To Reproduce:**
- Installed RKE2 v1.21
- ArgoCD worked normally
- Upgraded to RKE2 v1.22
- ArgoCD doesn't work anymore

**Comment by brandond** [comment]
These are Cluster API custom resources that don't come with core Kubernetes or RKE2. What did you install that included the Custom Resource Definitions for Cluster API? Does it need to be upgraded to be compatible with Kubernetes 1.22?

**Comment by aendi123** [comment]
Alright, thanks. I have multiple applications in ArgoCD and none of them work anymore. Some are really dead simple with a deployment, service and ingress and give me the resolving error. It seems like ArgoCD requires all the *.cluster.x-k8s.io resources regardless of the applications to work correctly.

**Comment by brandond** [comment]
Yeah, you're probably going to have to figure out where those came from. They've never been something that's shipped with core Kubernetes or RKE2.

**Comment by aendi123** [comment]
Solved by adding an exclusion for *.cluster.x-k8s.io in ArgoCD
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion
