### ISSUE TITLE
[Documentation] How to create user with x509 certificate (persistent between restarts in the control plane)

### ISSUE THREAD

**Issue by luis13byte** [rancher/rke2#2816]
**Is your feature request related to a problem? Please describe it.**
I have observed a behavior in RKE2 (I use v1.22.8+rke2r1).

I manage to successfully create users with signed certificates with the Kubernetes Certificate Signing workflow. With the modified kubeconfig (/etc/rancher/rke2/rke2.yaml) and using the user, I get access to the Kubernetes API, but this file is cleaned in each reboot of my control plane, it remains only with the default configuration. It is not only that the kubeconfig is deleted, because I have copies of it, but the user created is also deleted.

**Describe the solution you would like**
A brief explanation of correct way to manage this kind of users in RKE2, with service accounts I have no problems, but this restart is annoying, because I should create my users in each restart of the control plane.

**Comment by brandond** [comment]
> With the modified kubeconfig (/etc/rancher/rke2/rke2.yaml) and using the user, I get access to the Kubernetes API, but this file is cleaned in each reboot of my control plane.

Don't modify the admin kubeconfig. You should instead create your modified kubeconfig in $HOME/.kube/, or another location that's not going to be rewritten by RKE2 on startup.

**Comment by luis13byte** [comment]
The problem is not only the kubeconfig of the server, from another machine with the kubectl client I try to connect to the same user and I succeed but after a restart of RKE2 the control plane deletes these created users.

**Comment by brandond** [comment]
If something is getting deleted out of the Kubernetes datastore it is probably because you are (as you did with the kubeconfig file) modifying something whose configuration is managed by the control plane. Can you document the steps you used to create these users?

Note that there is no real concept of a User in Kubernetes RBAC. The CN on the cert defines the username; the O defines the groups. Those groups are mapped to roles and the roles in turn have access to resources. The user itself only exists as a field on the client certificate.

**Comment by luis13byte** [comment]
It was my mistake, I had not specified the duration of validity of the certificates I was interested in. Now my request specifies that they are valid for 1 year (specified in seconds).

~~~
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: luis13byte
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZVzVuWld4aE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTByczhJTHRHdTYxakx2dHhWTTJSVlRWMDNHWlJTWWw0dWluVWo4RElaWjBOCnR2MUZtRVFSd3VoaUZsOFEzcWl0Qm0wMUFSMkNJVXBGd2ZzSjZ4MXF3ckJzVkhZbGlBNVhwRVpZM3ExcGswSDQKM3Z3aGJlK1o2MVNrVHF5SVBYUUwrTWM5T1Nsbm0xb0R2N0NtSkZNMUlMRVI3QTVGZnZKOEdFRjJ6dHBoaUlFMwpub1dtdHNZb3JuT2wzc2lHQ2ZGZzR4Zmd4eW8ybmlneFNVekl1bXNnVm9PM2ttT0x1RVF6cXpkakJ3TFJXbWlECklmMXBMWnoyalVnald4UkhCM1gyWnVVV1d1T09PZnpXM01LaE8ybHEvZi9DdS8wYk83c0x0MCt3U2ZMSU91TFcKcW90blZtRmxMMytqTy82WDNDKzBERHk5aUtwbXJjVDBnWGZLemE1dHJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR05WdmVIOGR4ZzNvK21VeVRkbmFjVmQ1N24zSkExdnZEU1JWREkyQTZ1eXN3ZFp1L1BVCkkwZXpZWFV0RVNnSk1IRmQycVVNMjNuNVJsSXJ3R0xuUXFISUh5VStWWHhsdnZsRnpNOVpEWllSTmU3QlJvYXgKQVlEdUI5STZXT3FYbkFvczFqRmxNUG5NbFpqdU5kSGxpT1BjTU1oNndLaTZzZFhpVStHYTJ2RUVLY01jSVUyRgpvU2djUWdMYTk0aEpacGk3ZnNMdm1OQUxoT045UHdNMGM1dVJVejV4T0dGMUtCbWRSeEgvbUNOS2JKYjFRQm1HCkkwYitEUEdaTktXTU0xMzhIQXdoV0tkNjVoVHdYOWl4V3ZHMkh4TG1WQzg0L1BHT0tWQW9FNkpsYWFHdTlQVmkKdjlOSjVaZlZrcXdCd0hKbzZXdk9xVlA3SVFjZmg3d0drWm89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31557600  # one year
  usages:
  - client auth
EOF
~~~
