### ISSUE TITLE
etcd node marked as worker node in rancher cluster explorer 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rke2#2828]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head a6d2050

**Information about the Cluster**
- Kubernetes version: `v1.22.8+rke2r1`
- Cluster Type (Local/Downstream): `custom cluster  1 worker, 1 etcd, 1 cp RKE2`

**Describe the bug**

- Create a custom cluster from rancher server with cis-profile 1.6 enabled with 1 etcd, 1 cp and 1 worker node
- Register the nodes in the custom cluster

**Result**
From the rancher explorer UI >> etcd node is marked as `worker` node as the label `node-role.kubernetes.io/etcd` is missing

apply-system-agent-upgrader-on-<cluster-name> fails with the error logs :
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/install.sh
+ '[' -n ip-172-31-9-75 ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/node.yaml
+ kubectl get node ip-172-31-9-75 -o yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/rancher-system-agent'
+ '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
+ chroot /host /var/lib/rancher/agent/tmp/tmp.D45ePJ9BBd/install.sh
[FATAL] You must select at least one role.
```

**Expected Result**
Expected etcd node marked as etcd and not worker node

**Additional context**
Similar issue: https://github.com/rancher/rke2/issues/2583#
server logs from the etcd node : [etcd_serverlogs.txt](https://github.com/rancher/rke2/files/8566242/etcd_serverlogs.txt)

Output from `kubectl get node -o yaml` [node.txt](https://github.com/rancher/rke2/files/8566243/node.txt)

**Comment by brandond** [comment]
Can you attach logs from the rke2-server service on the affected node? All I see here is rancher system agent logs.

**Comment by anupama2501** [comment]
rke2server logs:
[etcd_serverrke2.txt](https://github.com/rancher/rke2/files/8567254/etcd_serverrke2.txt)

**Comment by brandond** [comment]
Hmm, I don't see much going on here. It looks like the node was started up on v1.22.8+rke2r1, and then almost immediately upgraded to v1.22.9-rc4+rke2r1. On the second startup, I do see the labels being set:

```
Apr 26 20:22:03 ip-172-31-9-75 rke2[7876]: time="2022-04-26T20:22:03Z" level=info msg="Successfully set etcd role label and annotations on node ip-172-31-9-75"
```

**Comment by caroline-suse-rancher** [comment]
Closing due to age
