### ISSUE TITLE
rke2 server panic and restart continously

### ISSUE THREAD

**Issue by umeshauv** [rancher/rke2#2829]
**Environmental Info:**
RKE2 Version:  v1.21.9+rke2r1

rke2 --version
rke2 version v1.21.9+rke2r1 (e48f07f7b208c0e43c537fca006cd5b6ce31b13b)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 

Linux 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 20:59:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

5 Node cluster,  2 servers (Control Plane, Etcd), 3 Agents (1 All, 2 workers)

**Describe the bug:**
On one the the servers, rke2-server is restarting continuously with following message
Apr 26 14:37:01  rke2[709662]: {"level":"info","ts":"2022-04-26T14:37:01.763-0500","caller":"rafthttp/stream.go:459","msg":"stopped stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"7f374354cb5384d4","remote-peer-id":"476327f58fa4d90a"}
Apr 26 14:37:01  rke2[709662]: {"level":"info","ts":"2022-04-26T14:37:01.763-0500","caller":"rafthttp/peer.go:340","msg":"stopped remote peer","remote-peer-id":"476327f58fa4d90a"}
Apr 26 14:37:01  rke2[709662]: {"level":"info","ts":"2022-04-26T14:37:01.763-0500","caller":"rafthttp/transport.go:369","msg":"removed remote peer","local-member-id":"7f374354cb5384d4","removed-remote-peer-id":"476327f58fa4d90a"}
Apr 26 14:37:01  rke2[709662]: panic: removed all voters
Apr 26 14:37:01  rke2[709662]: goroutine 230 [running]:
Apr 26 14:37:01  rke2[709662]: go.etcd.io/etcd/raft.(*raft).applyConfChange(0xc000774140, 0x0, 0xc004db2720, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Apr 26 14:37:01  rke2[709662]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/raft.go:1514 +0x225
Apr 26 14:37:01  rke2[709662]: go.etcd.io/etcd/raft.(*node).run(0xc000a6e000)
Apr 26 14:37:01  rke2[709662]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/node.go:356 +0x845
Apr 26 14:37:01  rke2[709662]: created by go.etcd.io/etcd/raft.RestartNode
Apr 26 14:37:01  rke2[709662]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/node.go:240 +0x330
Apr 26 14:37:01  systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 26 14:37:01  systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Apr 26 14:37:01  systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
Apr 26 14:37:06  systemd[1]: rke2-server.service: Service RestartSec=5s expired, scheduling restart.

**Comment by brandond** [comment]
> 2 servers (Control Plane, Etcd)

2 etcd nodes is an invalid configuration. Etcd quorum requires an odd number of nodes.

https://etcd.io/docs/v3.5/faq/#why-an-odd-number-of-cluster-members

**Comment by umeshauv** [comment]
> 

I have 3 etcd servers in the cluster.   My understanding is that node with role All runs etcd as well.

**Comment by umeshauv** [comment]
I have not run cluster-reset on this node or changed it's hostname/ip-address.  Please find the logs you requested for.
[kubectl_nodes.txt](https://github.com/rancher/rke2/files/8577502/kubectl_nodes.txt)
[node2_yaml.txt](https://github.com/rancher/rke2/files/8577507/node2_yaml.txt)
[server.log](https://github.com/rancher/rke2/files/8577508/server.log)
.

**Comment by brandond** [comment]
Hmm, for some reason etcd does not recognize the local cluster member and is trying to remove it from the cluster.
```
Apr 27 14:51:13 k8s-rke-node01 rke2[999303]: {"level":"info","ts":"2022-04-27T14:51:13.763-0500","caller":"membership/cluster.go:422","msg":"removed member","cluster-id":"71ce1bbadd6f30d8","local-member-id":"7f374354cb5384d4","removed-remote-peer-id":"7f374354cb5384d4","removed-remote-peer-urls":["https://10.100.1.205:2380"]}
```

Can you try upgrading this node to v1.21.12+rke2r1? There have been some changes to the etcd startup code path that may resolve this.
