### ISSUE TITLE
Second control plane node stuck while upgrading from v1.21.12+rke2r1 to v1.22.8+rke2r1

### ISSUE THREAD

**Issue by thedadams** [rancher/rke2#2834]
**Environmental Info:**
RKE2 Version: v1.22.8+rke2r1

Cluster Configuration:

3 etcd-only, 2 cp, 2 worker nodes

**Describe the bug:**
While upgrading from v1.21.12+rke2r1 to v1.22.8+rke2r1, the etcd-only nodes are upgraded one at a time. Then the control plane nodes are upgraded one at a time. The second control plane node gets stuck upgrading.

**Steps To Reproduce:**
1. In Rancher, setup a cluster with the above node types on version v1.21.12+rke2r1. Wait for the cluster to become active.
2. Upgrade the version to v1.22.8+rke2r1
3. The three etcd-only nodes will upgrade successfully, one at a time.
4. The first control plane node will update. The second one will get stuck.

**Additional context / logs:**
Running `rke2-killall.sh` on the stuck control plane node and then `systemctl restart rke2-server` does un-stick the upgrade. The worker nodes upgrade successfully afterwards.

I have attached the pods logs for the [apiserver](https://github.com/rancher/rke2/files/8595501/apiserverlogs.txt) and the RKE2 [logs](https://github.com/rancher/rke2/files/8595504/log.txt) for the stuck control plane node.

**Comment by VestigeJ** [comment]
Is the behavior any different between manual upgrading of the cp node? I’m assuming this was hit when using the system upgrade controller?

**Comment by brandond** [comment]
It was done with rancher-system-agent via v2prov, not via SUC. I would expect to hit the same thing whenever following the same node-group-staged upgrade process that the agent is using.

**Comment by ShylajaDevadiga** [comment]
Validated as part of patch validation on v1.23.6-rc1+rke2r2 using 3 etcd, 2 cp, 2 worker node using rancher provisioning. Upgrade was successful and basic upgrade tests have passed
