### ISSUE TITLE
Customization of rke2-calico configuration gets stuck

### ISSUE THREAD

**Issue by luis13byte** [rancher/rke2#2838]
**Environmental Info:**
RKE2 Version: rke2 version v1.22.8+rke2r1

**Cluster Configuration:**
Test environment of 1 server and 1 agent.

**Describe the bug:**
When I try to upgrade the configuration of chart rke2-calico with the method specified in the official documentation it gets stuck, as far as I have been able to observe it leaves the namespace calico-system in "Terminating" status, I am not sure but I think that the upgrade pretends to clean removing the previous version of the helm (deleting namespace), but it does not complete this step correctly.

I have tried to force the deletion of the namespace with: 
~~~
 (                                                      
NAMESPACE=calico-system
kubectl proxy &
kubectl get namespace $NAMESPACE -o json |jq '.spec = {"finalizers":[]}' >temp.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
)
~~~

And then restart the server (and agent), but even if it has specified "cni: calico" it doesn't recreate the namespace.

**Steps To Reproduce:**
1. Execute this script:
~~~
#!/bin/bash
mkdir -p /etc/rancher/rke2/
curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.22.8+rke2r1 sh -

cat << EOF > /etc/rancher/rke2/config.yaml
server: https://161.97.171.52:9345
token-file: K1008eae49ae189e5e65ecdbbbf6b7de6c299dd3ad05b12d4fec4fad8ad34096fa6::server:ab10d78488b39e0e60f625d02c976baa
cni: calico
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
node-name: controlplane1
EOF

systemctl enable rke2-server.service && systemctl start rke2-server.service
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
~~~
2. Customize Calico (apply manifest):
~~~
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        mtu: 1480
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 10.42.0.0/16
          blockSize: 24
~~~

**Expected behavior:**
Get the Calico configuration updated.

**Comment by brandond** [comment]
CNIs can be touchy. Is there some reason that you're not just placing the HelmChartConfig manifest in /var/lib/rancher/rke2/server/manifests so that it's picked up when the cluster is originally being brought up, instead of trying to change the configuration after the fact?
