### ISSUE TITLE
rke2-killall.sh does not clear all processes

### ISSUE THREAD

**Issue by LukeMauldin** [rancher/rke2#2845]
**Environmental Info:**
rke2 version v1.22.7+rke2r2 (45a0df00aa42108f5a6b5c48ee221c1bed03a745)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 
Linux usgvtzkubetst04 5.3.18-150300.59.49-default #1 SMP Mon Feb 7 14:40:20 UTC 2022 (77d9d02/lp-384d8aa) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 control servers and 2 workers

**Describe the bug:**
On a worker node, run the `rke2-killall.sh` script.  Expected for all rke2 related processes and mounts to be cleared so that server could reboot or shutdown but on reboot/shutdown server hangs indefinitely.  Must be manually power cycled.  Was following instructions from https://github.com/k3s-io/k3s/discussions/4319 and https://github.com/rancher/rke2/issues/2411#issuecomment-1055775531 to fix rke2 related shutdown issues.

**Steps To Reproduce:**
rke2 was installed on nodes via rancher v2.6.4.

**Expected behavior:**
Server to reboot or power off after `rke2-killall.sh` script was executed.

**Actual behavior:**
Server hangs at the very end of power off cycle.  Multiple other VMs on system running same kernel version and not running rke2 reboot or shutdown correctly.

**Comment by brandond** [comment]
This is a duplicate of the issue discussed at https://github.com/rancher/rke2/issues/2411#issuecomment-1055775531

**Comment by LukeMauldin** [comment]
I did some more research and it seems like in my case a mount of `/dev/rbd0` is preventing the unmount and reboot from occurring.  I think that rke2-killall.sh should be modified to also unmount /dev/rbd* devices.
In my case, I am using rke2 with integrated ceph-csi for dynamically provisioned storage and that is what is creating the /dev/rbd mount points.  Those are not being properly unmounted by rke2-killall.sh so the server reboot/shutdowns hang.
