### ISSUE TITLE
rke2-upgrade image not being pushed

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#286]
Latest image is from `beta1`. Probably a CI issue? 

https://hub.docker.com/r/rancher/rke2-upgrade/tags

**Comment by MonzElmasry** [comment]
CI script was fixed via : https://github.com/rancher/rke2-upgrade/pull/3
beta15, beta16 and beta17 were manually pushed, no ci problems, will double check when beta18 is out.

**Comment by rancher-max** [comment]
Validated this has been pushed properly with the tag of beta18: https://hub.docker.com/layers/rancher/rke2-upgrade/v1.18.8-beta18-rke2/images/sha256-25548adf5cd949fe114a8128476d93f285e631f926f513e7bc41ccd4dc579033?context=explore
