### ISSUE TITLE
Node containerd/top node metrics stop working after running for a while and node memory rises

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#2863]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.8+rke2r1 (bd020f4f0c54f8dcd99fc26a7ea503367741c99d)
go version go1.16.14b7

containerd github.com/k3s-io/containerd v1.5.10-k3s1 18edb4854b2a31f56f06a8e5363ef5b91b5840b5

Node(s) CPU architecture, OS, and Version: 
Linux stg-tenant-01-w01-29-vvs8l 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 121 agents

**Describe the bug:**
A running node will stop reporting container (crictl stats) and node metrics (kubectl top node) after running for a while along with its memory going up. Restarting rke2-agent drops the memory substantially along with allowing metrics to start working again.

**Steps To Reproduce:**
1. Install rke2-agent on the node with the above version. 
2. Allow it to run for a while which then the below occurs

nodes that show unknown also won't allow crictl stats to return and show higher memory than average
```
$ kubectl top node | grep unknown
stg-tenant-01-w03-19-73dtl            <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w02-06-w0s27         <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w01-29-vvs8l            <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w01-21-m5w4s         <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w03-22-50cnm         <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w03-21-d7vhm          <unknown>                           <unknown>               <unknown>               <unknown>               
stg-tenant-01-w03-06-5hanh          <unknown>                           <unknown>               <unknown>               <unknown> 
```

This command just hangs and does not return
```
$ ssh stg-tenant-01-w02-06-w0s27
[stg-ham-tenant-01-w02-06-w0s27 ~]$ sudo crictl -r unix:///run/k3s/containerd/containerd.sock stats 
```

Memory usage is higher and when the agent is restarted memory drops and stats work
```
[stg-tenant-01-w02-06-w0s27 ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:             15          10           0           0           5           5
Swap:             0           0           0
[stg-tenant-01-w02-06-w0s27 ~]$ sudo systemctl restart rke2-agent
[stg-tenant-01-w02-06-w0s27 ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:             15           6           4           0           5           9
Swap:             0           0           0
```

crictl stats now work after restarting the agent (this is on the same node above that service was restarted)
```
CONTAINER           CPU %               MEM                 DISK                INODES
021521dfddfae       0.46                103.7MB             208.9kB             26
05804c82fb2a4       0.01                20.34MB             90.11kB             16
09b8dab1641c7       0.12                38.79MB             114.7kB             17
0e8d08258a70c       0.13                45.83MB             114.7kB             17
130b812201fd2       0.12                39.74MB             114.7kB             17
1e89f6c5deab3       0.17                109.1MB             114.7kB             17
2c85aa93186d8       46.19               53.21MB             73.73kB             13
2d572a79ddcb5       0.02                5.485MB             155.6kB             22
2d58ee8b2f563       0.24                44.95MB             114.7kB             17
2f5287c8542cb       0.63                37.49MB             114.7kB             17
300f9e9ffdcc5       0.21                40.15MB             114.7kB             17
305eaf19a385a       0.00                15.72MB             98.3kB              18
...truncated
```

**Expected behavior:**
container and node stats never break and node memory doesn't increase too much due to stats usage.

**Actual behavior:**
Containerd and node stats stop flowing and memory raises. If not caught ahead of time sometimes it will use too much memory and cause node instability. 

**Additional context / logs:**

**Comment by brandond** [comment]
Have you reported this issue to containerd?

**Comment by mitchellmaler** [comment]
Sure I can log the same issue there.

**Comment by mitchellmaler** [comment]
@brandond actually looks like someone has logged a similar issue 
https://github.com/containerd/containerd/issues/6362

**Comment by brandond** [comment]
You might also look at the containerd log file when the status results are timing out, see if there's anything interesting in there?

**Comment by mitchellmaler** [comment]
We are only seeing this on our cluster running v1.22 that has containerd v1.5.10-k3s1. A few other clusters running v1.21.6 with containerd v1.4.11-k3s1 don't seem to have the issue.
