### ISSUE TITLE
Validate Oracle Linux 8.6

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2897]
We have previously validated up to oracle linux 8.3, but 8.5 is available and should be validated. In addition, there have been enough changes in rke2 since those validations have been performed that it's possible something has broken. Furthermore, the OS is different enough that our RHEL 8.5 validations shouldn't apply here and we should handle this separately.

**Comment by cocampbe** [comment]
@rancher-max I am really curious how much different OL 8.5 would be from RHEL 8.5, or even CentOS and Rocky? Oracle has always claimed 100% binary compatibility with RHEL. The only difference I am aware of is the UEK. They do provide a RH compatible kernel.

**Comment by rancher-max** [comment]
This has been validated in all of v1.22.11+rke2r1, v1.23.8+rke2r1, and v1.24.2+rke2r1. Upgrades were performed to the most recently released versions (1.22.12, 1.23.9, and 1.24.3).
