### ISSUE TITLE
[Release 1.23] Update calico 3.23.0

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#2907]
Backport for #2895

**Comment by rbrtbnfgl** [comment]
Are you sure that on update the image version is updated?
I found out that they modified the helm chart on 3.23.0 and it introduced some issues on update.
I mentioned it here  #2932

**Comment by rancher-max** [comment]
I mistyped that! You're right, the image versions did not update, but the helm version updated as expected.

**Comment by VestigeJ** [comment]
See the following links - I'll be closing this issue this has been tested but will be again with the latest release candidate on v1.24.

 https://github.com/rancher/rke2/issues/2953  - version v1.23.6-dev+dce8b399
https://github.com/rancher/rke2/issues/2949   - version v1.24.0-dev+eac4887d (eac4887d4d9593e23764df7fd37454833637b9e6)
