### ISSUE TITLE
RKE2 YUM/RPM  - Selinux not working - What am i missing?

### ISSUE THREAD

**Issue by riaanp78** [rancher/rke2#2917]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.23.6+rke2r2 (40d712e5081ac87e30e8f328f738130acf2c31f8)
go version go1.17.5b7
CentOS Stream release 8

Node(s) CPU architecture, OS, and Version: 
Linux k8-master01.local.lab 4.18.0-365.el8.x86_64 #1 SMP Thu Feb 10 16:11:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 masters
5 worker nodes

**Describe the bug:**
Following this as guidance:
https://docs.rke2.io/security/hardening_guide/

I have been trying to use RKE2 with a CIS profile enabled and with SELinux enabled.  I am am using the **YUM/RPM** method since I am aware the TAR method does not work with SELinux (saw a comment on a another issue thread). 

**Steps To Reproduce:**
Using version: **v1.23.6+rke2r2**

yum install rke2-server -y
systemctl start rke2-server

I am using the bare minimum configuration to test with SELinux  

This is my config.xml

```
write-kubeconfig-mode: "0644"
tls-san:
  - clusterlab.local
selinux: true
profile: cis-1.5
debug: true
```

Tried with CIS 1.6 as well

```
write-kubeconfig-mode: "0644"
tls-san:
  - clusterlab.local
selinux: true
profile: cis-1.6
debug: true
```

What am i doing wrong /  what is missing? The OS's are clean installs. Is there a specific version I should be using?

**Expected behavior:**
RKE2 just starts up with SELINUX enabled

**Actual behavior:**
SELinux prevents RKE2 from starting 

**Additional context / logs:**
From /var/lib/rancher/rke2/agent/containerd/containerd.log

```
6fb5dfe8c63230cccfa0d48b0b/init.pid: no such file or directory\"\n"
time="2022-05-16T09:07:59.498574354+02:00" level=error msg="copy shim log" error="read /proc/self/fd/21: file already closed"
time="2022-05-16T09:07:59.509908360+02:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-k8-master01.local.lab,Uid:16a8d783de051b86612a42859e7d6253,Namespace:kube-system,Attempt:0,} failed, error" error="failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown"
```

**Comment by riaanp78** [comment]
Hello Hussei, I already have that package installed:

***@***.*** ~]# rpm -qa | grep rke2
rke2-common-1.23.6~rke2r2-0.el8.x86_64
rke2-selinux-0.8-2.el7.noarch
rke2-server-1.23.6~rke2r2-0.el8.x86_64

These are the 3 packages I installed.

These are also the other selinux packages I have installed

***@***.*** ~]# rpm -qa | grep selinux
selinux-policy-3.14.3-89.el8.noarch
container-selinux-2.170.0-1.module_el8.6.0+954+963caf36.noarch
python3-libselinux-2.9-5.el8.x86_64
rpm-plugin-selinux-4.14.3-21.el8.x86_64
selinux-policy-targeted-3.14.3-89.el8.noarch
libselinux-2.9-5.el8.x86_64
libselinux-utils-2.9-5.el8.x86_64
rke2-selinux-0.8-2.el7.noarch


Is there anything else I might have missed that you can think of?

**Comment by brandond** [comment]
You might read through the thread at https://github.com/rancher/rke2/issues/1539#issuecomment-938905544 and see if any of the discussion there is helpful.

Also, I notice that you have an out-of-date version of the rke2-selinux package, and for el7 instead of el8. How did you come to get that version installed?

**Comment by riaanp78** [comment]
Brad the rescue! I did not even spot that. I fixed the yum config, i have
an ansible script to generate the YUM repo config to build the cluster.
That was a typo on my part.

After I removed the wrong RPM and re-install it works perfectly fine now.
So no bug or issue. Apologies for wasting your time.

**Comment by riaanp78** [comment]
a wrong package was installed using 3rd party provision methods that caused the wrong selinux library to be installed, this in turn caused RKE2 not to start up. After fixing the typo everything worked as expected.
