### ISSUE TITLE
Bringing up third node on cluster with tls-san sometimes fails

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#292]
**Description:**
If I am working quickly in creating nodes, registering them with target groups in AWS for tls-san, and bringing up the rke2 cluster, then sometimes the third server node fails to join to the cluster and the cluster seems to have other issues (for example when registering it with rancher).

**Steps to reproduce:**
1. Create 3 nodes in aws
2. Immediately register them with existing target groups with ports 6443 and 9345. These should connect to an LB which is connected to a Route53 fqdn.
3. Bring up the first node with config.yaml as:
```yaml
tls-san: 
  - <your.fqdn.here>
```
4. Retrieve the token and bring up the second node as soon as you see the node in ready state and pods all running. Config.yaml as:
```yaml
tls-san: 
  - <your.fqdn.here>
token: <token>
server: https://<Node 1 Public IP>:9345
```
5. As soon as that node is reporting ready and pods are running, bring up third node exactly the same as second node. 
6. Notice third node fails to come up and logs with `journalctl -eu rke2 -f` show the `datastore context exceeded` repeated and is never `Data store connection OK`

**Additional Details:**
- This is tricky to reproduce. I notice it happens more often when I work very quickly and do things AS SOON AS they are up/available.

**Comment by briandowns** [comment]
@rancher-max What command(s) are you running to determine things are up and it's time to add the third node?

**Comment by rancher-max** [comment]
I just run `watch kubectl get nodes,pods -A` and validate after adding each node that all of the nodes are reporting `Ready` and all of the pods are running with no restarts. For the first node, there are obviously many more pods that need to be running, but for the second (and any subsequent node) it is just making the sure the node itself is Ready and the canal pod is showing 2/2 and Running.

**Comment by rancher-max** [comment]
I tried to recreate this multiple different times using `v1.18.8-beta19+rke2` and so far have been unable to. I think for now we should take this out of the current milestone and keep an eye on if it ever happens again, and if it does then try to capture more repeatable steps at that point. It's also very possible that the etcd changes that are in this beta have fixed the issue entirely.

**Comment by cjellick** [comment]
@davidnuzik should this be moved out per max's comment? not sure why its still in and in next up

**Comment by rancher-max** [comment]
I was able to recreate this today using `v1.18.8-beta20+rke2`. This time, it happened without using tls-san at all. Steps were:
1. Bring up first node (success):
```
# config.yaml
write-kubeconfig-mode: 644
token: "secret"
etcd-snapshot-retention: 20
etcd-snapshot-schedule-cron: "*/2 * * * *"
```
2. Bring up second node (success):
```
# config.yaml
write-kubeconfig-mode: 644
token: "secret"
server: "https://<Node 1 Public IP>:9345"
etcd-snapshot-retention: 20
etcd-snapshot-schedule-cron: "*/2 * * * *"
```
3. Attempt to bring up third node:
```
# config.yaml
write-kubeconfig-mode: 644
token: "secret"
server: "https://<Node 1 Public IP>:9345"
etcd-snapshot-retention: 20
etcd-snapshot-schedule-cron: "*/2 * * * *"
```

Ran the same steps when bringing up all nodes:
```
# Create config yaml with contents mentioned above:
sudo mkdir -p /etc/rancher/rke2 && \
sudo vi /etc/rancher/rke2/config.yaml

# Download install script
curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh -o install.sh && \
chmod +x install.sh

# Run rke2-server
sudo INSTALL_RKE2_VERSION=v1.18.8-beta20+rke2 INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE='server' ./install.sh
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
```

**Comment by brandond** [comment]
So the original 3rd node did get added to the etcd cluster as a learner, but it's not in the k8s cluster. Do you have any logs from the 3rd node?

The 3rd node being in the cluster as a learner breaks adding a 4th node, since you can only have one learner at a time.

**Comment by rancher-max** [comment]
Better log file that the one listed above:
[rke2temp.log](https://github.com/rancher/rke2/files/5257345/rke2temp.log)

**Comment by brandond** [comment]
It looks like it is getting stuck trying to take a snapshot while still a learner:
```
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: time="2020-09-21T17:32:00Z" level=info msg="Snapshot retention check"
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: time="2020-09-21T17:32:00Z" level=info msg="Taking etcd snapshot at 2020-09-21 17:32:00.000232649 +0000 UTC m=+89.644771911"
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: {"level":"info","msg":"created temporary db file","path":"/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-1600709520.part"}
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: {"level":"info","ts":"2020-09-21T17:32:00.004Z","caller":"clientv3/maintenance.go:200","msg":"opened snapshot stream; downloading"}
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: {"level":"info","msg":"fetching snapshot","endpoint":"https://127.0.0.1:2379"}
Sep 21 17:32:00 ip-172-31-6-39 rke2[2202]: {"level":"warn","ts":"2020-09-21T17:32:00.030Z","caller":"clientv3/retry_interceptor.go:202","msg":"retrying RecvMsg","error":"rpc error: code = Unavailable desc = etcdserver: rpc not supported for learner"}
```
That last line just repeats forever.

We probably need to fix this so that we don't attempt to take snapshots on learners.

**Comment by brandond** [comment]
The infinite loop appears to be coming from the etcd client api, which sets up the snapshot rpc call for infinite retries with no backoff:
https://github.com/etcd-io/etcd/blob/release-3.4/clientv3/maintenance.go#L195

**Comment by brandond** [comment]
So we have two issues here:
1. Etcd snapshot is attempted even if the local node is still a learner, which then goes into infinite retry due to etcd client bug.
1. Nodes that fail startup after joining the etcd cluster, but before joining the k8s cluster, do not ever get cleaned up and will prevent subsequent nodes from joining the cluster. They will need to be manually removed from the cluster with etcdctl, until we can figure out a good way to handle this.

**Comment by brandond** [comment]
I have split issue 2 above off from this one, as I think the fix in https://github.com/rancher/k3s/pull/2295 will make it harder to reproduce. It's still a bug and should be fixed at some point though.

**Comment by rancher-max** [comment]
#### Validated using `v1.18.9-beta21+rke2`

- When a snapshot attempts to happen while the node is an etcd learner, it no longer blocks the node from promoting and coming up successfully.
- General etcd snapshot functionality still working
