### ISSUE TITLE
Installing via install script causes cluster to continuously retry running rke2.service after quorum loss

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#293]
**Description:**
Installing a 3-node cluster via the install script, then bringing down two of the nodes, causes the cluster to lose quorum. The remaining node will have the rke2.service system process stop, but it will continuously try to restart it. This causes issues with restoring the cluster from a backup.

**Steps to reproduce:**
1. Create 3-server-node cluster using install script. Set etcd snapshot time t
`sudo INSTALL_RKE2_VERSION=v1.18.4-beta16+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' ./install.sh`
2. Shut down two of the nodes -- this will cause the cluster to lose quorum.
3. On the first node, notice the constant retries with: `journalctl -eu rke2 -f`

**Additional Details:**
- If trying to restore a backup by setting the config.yaml to have `cluster-reset` and `cluster-reset-restore-path`, there are failures when comparing what looks like a node hash:
`Found [ip-172-31-46-108-a991844d=https://172.31.46.108:2380  ip-172-31-34-41-1b350532=https://172.31.34.41:2380  ip-172-31-35-143-55158b42=https://172.31.35.143:2380], expect: ip-172-31-34-41-2c0a2e58=172.31.34.41`

- Attempted on rke2 version `beta16`

**Comment by galal-hussein** [comment]
@cjellick @rancher-max I think there is a misunderstanding here, after I tried to reproduced this, rke2 worked as expected, it basically restored the snapshot  and entered a loop of fatal errors stating that:
```
ime="2020-09-14T23:35:16Z" level=info msg="etcd already restored from a snapshot. Restart without --snapshot-restore-path flag. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes"
```
which means that the user just needs to remove these flags and restart rke2 with the db, the only thing that maybe misleading is the message sent to the user of removing --snapshot-restore-path which it should be remove --cluster-reset-restore-path, but that can be fixed easily

**Comment by davidnuzik** [comment]
Do we think docs need to more carefully cal out the process? FYI we have a PR for them here if would like to take a peek and have any suggestions: http://github.com/rancher/docs/pull/2684

**Comment by cjellick** [comment]
@galal-hussein please put in a fix for the the flag mislabelling and reference this issue

**Comment by cjellick** [comment]
@galal-hussein please review the docs PR to clear up the confusion around the process.

**Comment by rancher-max** [comment]
There is an issue regarding the mislabeling in the k3s repo: https://github.com/rancher/k3s/issues/2244 

I think @galal-hussein is right that the install script here is not the issue, but I still run into part of the issue in https://github.com/rancher/rke2/issues/320. Namely, this section:
```
However, at this time, the cluster acted like it was accessible:

$ kubectl get nodes
NAME               STATUS     ROLES         AGE    VERSION
ip-172-31-18-246   NotReady   etcd,master   106m   v1.18.8-beta19+rke2
ip-172-31-23-63    Ready      etcd,master   52m    v1.18.8-beta19+rke2
ip-172-31-28-148   Ready      etcd,master   78m    v1.18.8-beta19+rke2

The NotReady node here is the one that is still running, and the other two are stopped.

The other interesting thing is it DOES appear to have restored the snapshot, because the original few workloads I deployed are present and the other ones I deployed after this snapshot was taken are not. However, The cluster is generally not functional. Deploying and deleting more workloads fails.
```

This has now been seen when using the install script directly for ALL commands (initial node starts, cluster-reset/restore, rerun node1), using the binary for ALL commands, and when using the install script for the initial node start and then just doing `sudo systemctl restart rke2.service` after editing the config.yaml file for the reset/restore and rerun node1.


For reference, in k3s, using the install script for all the commands feels like the simplest way and works as expected, so this is strictly related to rke2. 

**We may be able to close this issue though as it doesn't look like the install script is the problem.**

**Comment by galal-hussein** [comment]
I would like this to be retested also after the restart of components fix https://github.com/rancher/rke2/pull/338

**Comment by rancher-max** [comment]
#### Validated using `beta20`

There is no issue with the install script anymore. The steps would be to update the config.yaml to have cluster-reset and cluster-reset-restore-path and then run `sudo systemctl restart rke2-server.service`, then update the config to not have those values and run the same command.

**Comment by oliverchan** [comment]
Hi
With the setup of 3 master nodes and 2 worker nodes together with pod service running on  worker node ( I setup 1 nginx to run on the worker as I tainted all the masters). Now , when I bring down 2 masters nodes, it behaved as expected as I cant perform kubectl on the remaining masters, however I can access the pod service, and able to recv response. is it normal?

**Comment by brandond** [comment]
@oliverchan please read https://etcd.io/docs/v3.3/faq/#what-is-failure-tolerance

**Comment by oliverchan** [comment]
@brandond Thanks for the prompt reply. I understand the concept behind etcd, and I'm able to see the exact behavior of the cluster not working when I brought down 2 masters nodes.
However, I'm not able to get my head around for the following:-
1. The pod service can still be accessed, even though the cluster has loss it quorum . Shouldn't the pod service be down as well? 
2. I have setup an external LB, infront of the cluster. And I can access the pod service when I redirect to the specific server via the real IP and port. 
Appreciate your response. thanks

**Comment by brandond** [comment]
I'm not sure what you mean by the pod service. The apiserver, controller-manager, and scheduler will not function without etcd. The kubelet itself continues to function when the apiserver is down.

**Comment by oliverchan** [comment]
" The kubelet itself continues to function when the apiserver is down. Workload pods, services, and other things within the cluster also continue to function as last configured by the control plane. This is all standard Kubernetes behavior."

Thanks. I think your response answer my qn - ie:- all workload pods and services deploy in the worker nodes will continue to function as normal, when the masters are down.
