### ISSUE TITLE
Calico fails to update to v3.23.0 from older version

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#2932]
**Environmental Info:**
RKE2 Version: v1.23.6+rke2r2

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

RKE2 with Calico as CNI with a version older then 3.23.0

**Describe the bug:**

When updating RKE2 with the newer Calico version (3.23.0) on the new chart of the tigera-operator the `tigera-operator` namespace is not created.
 From the chart README:
```
Prior to release v3.23, the Calico helm chart itself deployed the `tigera-operator` namespace and required that the helm release was
installed in the `default` namespace. Newer releases properly defer creation of the `tigera-operator` namespace to the user and allow installation
of the chart into the `tigera-operator` namespace.
```
After the update the `tigera-operator` pod is created on the `kube-system` namespace and not on the `tigera-operator` one; it fails to start and the `calico-node` daemonset is not updated and it remains with the older version.

**Steps To Reproduce:**

- Installed RKE2: v1.23.6+rke2r2
- Update RKE2 to a newer commit (df16d112ed5981650b5cca15385026635d0531bc)
- Calico version is v3.22.1 and not v3.23.0

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by manuelbuil** [comment]
This is the PR that changed this behaviour https://github.com/projectcalico/calico/commit/629fc030f786ca144b9f3a1529a4dbda03be390a

**Comment by brandond** [comment]
The migration steps listed in their documentation are effectively unsupportable. Automating this as part of cluster upgrades is going to be quite unpleasant.

https://projectcalico.docs.tigera.io/maintenance/kubernetes-upgrade#upgrade-from-calico-versions-prior-to-v3230

**Comment by rbrtbnfgl** [comment]
We can force our chart to create `tigera-operator` namespace and to run the pod on that namespace.

**Comment by rancher-max** [comment]
@VestigeJ Can this be closed based on the validations from https://github.com/rancher/rke2/issues/2949#issuecomment-1133335495?

**Comment by VestigeJ** [comment]
@rancher-max I believe so yes
