### ISSUE TITLE
Cannot join nodes back after cluster-reset when not restoring from snapshot

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2991]
Forwardport for: https://github.com/rancher/rke2/issues/2857

**Comment by brandond** [comment]
This appears to be an issue with etcd, but we've been unable to reproduce it in a simple configuration such that upstream can diagnose and fix it. I would like QA to validate that it is still an issue with newer releases of etcd (such as the version shipped with 1.26), and if so we can put another spike of work into coming up with a simple reproducer for upstream.

**Comment by brandond** [comment]
Yes, this seems to be fairly easy to reproduce using embedded etcd. I need to be able to provide the etcd maintainers with a set of steps to reproduce on vanilla etcd in order for them to look at it.

**Comment by VestigeJ** [comment]
As of RKE2 v1.27.4+rke2r1 I'm no longer seeing this behavior and am electing to close this issue as stale and no longer relevant.
