### ISSUE TITLE
Test image pull secrets

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#30]
Based on 6/10/20 call with Rancher Federal team, there was some concern that image pull secrets do not work with containerd. We believe this is not the case but proposed to have QA briefly check this area to verify.

**Comment by ShylajaDevadiga** [comment]
Pulling private image using secrets was successful. 
Created a secret of type docker-registry.
Created a pod to access the private image.
Pod was able to successfully pull the private image using secrets.
Deleted imagePullSecrets: entry and verified pod failed to pull the private image with pull access denied msg.
