### ISSUE TITLE
RKE2 does not start on boot on Leap 15.3

### ISSUE THREAD

**Issue by tibold** [rancher/rke2#3001]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.23.6+rke2r2 (40d712e5081ac87e30e8f328f738130acf2c31f8)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 
```
Linux worker-001 5.3.18-59.5-default #1 SMP Wed Jun 2 08:21:36 UTC 2021 (eaf040d) x86_64 x86_64 x86_64 GNU/Linux
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Describe the bug:**
The default installation through rancher using custom existing nodes add the service and env files for systemd under `/usr/local/systemd/system`.
However, when using btrfs and default configuration this will cause rke2 to not boot, because `/usr/local` is not yet mounted when systemd reads it's configuration.

The recommended workaround as for as I understand is to place these service files into `/etc/systemd/system` which is already the case for the `rancher-system-agent.service`.

**Steps To Reproduce:**
- Install RKE2 using Rancher and custom nodes
- Once the cluster is healthy, reboot any node

**Expected behavior:**
The node comes back and re-integrated into the cluster

**Actual behavior:**
The rke2-agent or rke2-server service never start

**Additional context / logs:**
If systemd debug logs are enabled:
```
May 29 08:59:44 worker-001 systemd[1]: Pulling in rke2-agent.service/start from multi-user.target/start
May 29 08:59:44 worker-001 systemd[1]: rke2-agent.service: Cannot add dependency job, ignoring: Unit rke2-agent.service not found.
```

**Comment by marton-kiss** [comment]
workaround:
cp /usr/local/lib/systemd/system/rke2-*.service /etc/systemd/system/
sed -i '/After=[network-online.target/a](http://network-online.target/a) After=usr-local.mount' /etc/systemd/system/rke2-server.service
sed -i '/After=[network-online.target/a](http://network-online.target/a) After=usr-local.mount' /etc/systemd/system/rke2-agent.service
systemctl daemon-reload

The intall script somehow fails the check the /usr/local mount point and don't copy the binaries to the /opt. It works well with standard install ( curl | bash -), but fails with deploy from rancher.

**Comment by tibold** [comment]
The binaries are correctly placed under /opt and the mount point is correctly detected during install. I don't have the log files for that anymore though.

Only the systemd service definition (4 files) are left under /usr/local.

The workaround I used is slightly different:

# Fix Rancher Services

mv /usr/local/lib/systemd/system/rke2* /etc/systemd/system/

systemctl is-enabled rke2-server.service && systemctl reenable rke2-server.service

systemctl is-enabled rke2-agent.service && systemctl reenable rke2-agent.service

- It is not enough to move the .service files, they have 2 .env files as well
- Once moved the service must be reenabled so the links are fixed to point to the new location of the service files
- Since the binaries are correctly placed, there was no need to wait for the mounting /usr/local

**Comment by brandond** [comment]
I believe this should go into rancher/rancher, since it sounds like an issue with the v2 provisioning via rancher-system-agent.

**Comment by tibold** [comment]
Maybe.
I honestly wasn't sure what rancher is doing. ^_^

Can it be moved or do I need to re-report it?

**Comment by brandond** [comment]
cc @Oats87 @cbron

**Comment by brandond** [comment]
Which version of Rancher are you using?

**Comment by tibold** [comment]
> @tibold what version of Rancher are you using?

V2.6.5

I think this is the latest stable release. I'm happy to update if there is an update though.

**Comment by abonillabeeche** [comment]
@brandond this is biting another one of our customers. Would you know who can we ask to prioritize this issue?

**Comment by bvankampen** [comment]
@brandond I'm having the same problem with a customer running SLES 15.4

**Comment by Martin-Weiss** [comment]
I have the same problem when using Rancher to deploy RKE2 on SLES OS (JEOS image) - and the problem seems to be that systemd does not find the services files in /usr/local.
My workaround is to add the services files to /etc.. via cloud-init..

**Comment by cwayne18** [comment]
Since this is a rancher v2prov issue, I'm going to close this out and we can follow the issue at https://github.com/rancher/rancher/issues/38106

To be very clear I'm not saying this isn't an issue or that we won't fix it, but rather it should be tracked in the proper repo.

**Comment by cwayne18** [comment]
Turns out I was wrong and this is an issue in the system-agent-installer-rke2, reopening although it should be fixed imminently.

**Comment by est-suse** [comment]
Validated the new files are created under  /etc/systemd/system 

```
sudo ls /etc/systemd/system
afterburn-sshkeys.target.requires  dbus-org.freedesktop.nm-dispatcher.service  multi-user.target.requires   network.service		  rke2-agent.service	syslog.service
basic.target.wants		   default.target.wants			       multi-user.target.wants	    rancher-system-agent.env	  rke2-server.service	timers.target.wants
bootmsg.service			   getty.target.wants			       network-online.target.wants  rancher-system-agent.service  sysinit.target.wants

```

Not under /usr/local/lib/systemd/system

```
 sudo ls /usr/local/lib/systemd/system
ls: cannot access '/usr/local/lib/systemd/system': No such file or directory
```

**Comment by Martin-Weiss** [comment]
Will this fix „repair“ existing deployments during upgrade of RKE2 via Rancher?
