### ISSUE TITLE
sig-network conformance tests related to session affinity fail with cilium CNI

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#3003]
**Environmental Info:**
RKE2 Version: 

Confirmed with v1.24.1-rc1+rke2r1, v1.22.8+rke2r1, and v1.23.6+rke2r2

Node(s) CPU architecture, OS, and Version: 

SLES15 SP3 (but probably all)

Cluster Configuration:

3 servers, 1 agent

**Describe the bug:**

When running certified-conformance tests with cilium as the cni, session affinity tests fail:
```
   Failed tests:
 [sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]
 [sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]
 [sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance]
 [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
```

**Steps To Reproduce:**

- Installed RKE2 using cilium cni
- Run conformance tests: `sonobuoy run --kubernetes-version=v1.24.1 --mode=certified-conformance`
  - For a minimal reproduction, just run one of the failing ones: `sonobuoy run --kubernetes-version=v1.24.1 --e2e-focus="Services should have session affinity work for service with type clusterIP"`

**Expected behavior:**

All conformance tests should pass

**Actual behavior:**

Some tests fail

**Additional context / logs:**

Note that if ingress is not disabled when running rke2, the ingress test will also fail but this is known and expected.

**Comment by manuelbuil** [comment]
This is identified by upstream Cilium and has a fix in Draft ==> https://github.com/cilium/cilium/pull/16179

**Comment by manuelbuil** [comment]
> @manuelbuil looks like the fix merged! Would we consider this issue "fixed" as well?

I would say yes!
