### ISSUE TITLE
`rke2-server.service` fails to activate during `systemctl restart` following `rke2 secrets-encrypt reencrypt`

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#3004]
**Environmental Info:**
RKE2 Version: v1.23.6+rke2r2

Cluster Configuration:

1 server (rancher provisioned, but reproducible standalone)

**Describe the bug:**

In a single node cluster, `rke2-server.service` is stuck activating during `systemctl restart rke2-server.service` following `rke2 secrets-encrypt reencrypt` command.

**Steps To Reproduce:**

- Installed RKE2: Rancher provisioned, but also reproducible standalone
- Create a script that does the following:
  - Run `rke2 secrets-encrypt prepare`
  - Scrape `rke2 secrets-encrypt status` to verify that the current stage is `prepare`
  - Restart the node using `systemctl restart rke2-server.service`
  - Run `rke2 secrets-encrypt rotate`
  - Scrape `rke2 secrets-encrypt status` to verify that the current stage is `rotate`
  - Restart the node using `systemctl restart rke2-server.service`
  - Run `rke2 secrets-encrypt reencrypt`
  - Scrape `rke2 secrets-encrypt status` to verify that the current stage is `reencrypt_request`, `reencrypt_active`, or `reencrypt_finished`
  - Continue scraping status until the current stage is `reencrypt_finished`
  - Restart the node using `systemctl restart rke2-server.service`

**Expected behavior:**

`rke2-server.service` successfully restarts following `rke2 secrets-encrypt reencrypt`

**Actual behavior:**

`rke2-server.service` is stuck in `Activating` state, and the `kube-apiserver` pod will eventually restart, however it produces no logs after the restart and the `Waiting for API server to become available` message never goes away.

**Additional context / logs:**

### `journalctl -u rke2-server.service`
```
May 31 17:56:09 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:09Z" level=info msg="Waiting for API server to become available"
May 31 17:56:09 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:09Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
May 31 17:56:14 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:14Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
May 31 17:56:16 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:16Z" level=info msg="Waiting for API server to become available"
May 31 17:56:19 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:19Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
May 31 17:56:24 jhyde-do-pfipa-pool0-77085e31-lwq7z rke2[20284]: time="2022-05-31T17:56:24Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```
### `kubectl get pods -n kube-system`
```
NAME                                                           READY   STATUS             RESTARTS        AGE
cloud-controller-manager-jhyde-do-pfipa-pool0-77085e31-lwq7z   1/1     Running            6 (9m57s ago)   15m
etcd-jhyde-do-pfipa-pool0-77085e31-lwq7z                       1/1     Running            3 (10m ago)     15m
helm-install-rke2-calico-4gdxx                                 0/1     Completed          2               16m
helm-install-rke2-calico-crd-d5hx5                             0/1     Completed          0               16m
helm-install-rke2-coredns-nvc4h                                0/1     Completed          0               16m
helm-install-rke2-ingress-nginx-mtdct                          0/1     Completed          0               16m
helm-install-rke2-metrics-server-hrnb2                         0/1     Completed          0               16m
kube-apiserver-jhyde-do-pfipa-pool0-77085e31-lwq7z             1/1     Running            0               15m
kube-controller-manager-jhyde-do-pfipa-pool0-77085e31-lwq7z    1/1     Running            5 (9m56s ago)   15m
kube-proxy-jhyde-do-pfipa-pool0-77085e31-lwq7z                 1/1     Running            3 (10m ago)     16m
kube-scheduler-jhyde-do-pfipa-pool0-77085e31-lwq7z             1/1     Running            3 (10m ago)     15m
rke2-coredns-rke2-coredns-547d5499cb-lqmhv                     1/1     Running            3 (10m ago)     15m
rke2-coredns-rke2-coredns-autoscaler-65c9bb465d-ghrjc          1/1     Running            3 (10m ago)     15m
rke2-ingress-nginx-controller-ghp5j                            0/1     CrashLoopBackOff   8 (81s ago)     14m
rke2-metrics-server-6564db4569-f99ss                           1/1     Running            3 (10m ago)     15m
```
### `kubectl logs -n kube-system kube-apiserver-jhyde-do-pfipa-pool0-77085e31-lwq7z`

[kube-apiserver-jhyde-do-pfipa-pool0-77085e31-lwq7z.log](https://github.com/rancher/rke2/files/8809781/kube-apiserver-jhyde-do-pfipa-pool0-77085e31-lwq7z.log)

**Comment by brandond** [comment]
There is a delay between the rke2-server service (and kubelet) restarting, and the kubelet in term applying changes to the static pod manifests. If you hammer it with a request to reencrypt secrets immediately after restarting the service, the kube-apiserver static pod probably hasn't been restarted to apply the new configuration yet. The reencrypt status check just ensures that all the secrets have been re-written; it doesn't actually check the running apiserver to see that it's been restarted with the new configuration prior to taking action, so it's totally possible that it just reencrypted everything with the old config.

Have you tried adding a ~2-3 minute delays after rke2-server process restarts to allow time for the static pods to have their configuration updated and in turn be restarted by the kubelet?

**Comment by brandond** [comment]
https://github.com/rancher/rke2/issues/897 may be considered a root cause for this - we don't actually wait for the new static pod manifests to be applied before moving on during the startup sequence. We just drop the static pod manifest, and wait for the kubelet to eventually apply it. If the configuration change is a critical one, startup may appear complete, when the configuration change has not yet actually been applied.

I've seen cases where RKE2 actually crashes a couple seconds after being restarted to apply a configuration change. This is caused by the etcd or apiserver static pod being restarted, which causes the rke2 embedded controllers to crash. The service is automatically restarted and then stays up, which hides the problem to a certain extend.
