### ISSUE TITLE
networkpolicy is not working in ubuntu

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#302]
Rke2 version: 
rke2 version v1.18.4-beta17+rke2

OS version:
Ubuntu 20.04

Issue:
NetworkPolicy does not work on ubuntu. 

Steps to reproduce:
1. Create a networkpolicy to deny all traffic
2. Create two pods.
3. Fetch the pods IP
4. Exec into pod and ping ip of another pod.
5. Ping works. It should not have, as network policy rule is deny-all

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: deny-all
 namespace: default
spec:
 podSelector: {}
 policyTypes:
 - Ingress

kubectl get po -o wide
NAME             READY   STATUS    RESTARTS   AGE    IP           NODE               NOMINATED NODE   READINESS GATES
busybox1         1/1     Running   0          6s     10.42.0.23   ip-172-31-10-194   <none>           <none>
busybox2         1/1     Running   0          5s     10.42.0.24   ip-172-31-10-194   <none>           <none>

kubectl exec -ti busybox2 -- ping -c3   10.42.0.23 
PING 10.42.0.23 (10.42.0.23): 56 data bytes
64 bytes from 10.42.0.23: seq=0 ttl=63 time=0.140 ms
64 bytes from 10.42.0.23: seq=1 ttl=63 time=0.088 ms
```
Additional info:
Issue not seen in RHEL7.8, following the same steps
```
kubectl exec -ti busybox2 -- ping -c3 10.42.3.85 
PING 10.42.3.85 (10.42.3.85): 56 data bytes
```

**Comment by Oats87** [comment]
This actually looks like desired behavior from the `Ubuntu` side of things -- intra-namespace traffic should be allowed. I am starting to think that the CentOS 7/RHEL 7.8 system are the ones that are not acting properly.

**Comment by ShylajaDevadiga** [comment]
@briandowns @Oats87 I am not seeing this issue now.  Seem to be resolved with #299 
```
rke2 -v
rke2 version v1.18.4-dev+babe152f (babe152fe5fe6f2a20dd31cf86049626dba1cce5)
```
Applying deny-all policy, works as expected.
```
kubectl exec -ti busybox2 -- ping -c3 10.42.1.2
PING 10.42.1.2 (10.42.1.2): 56 data bytes
```

**Comment by briandowns** [comment]
Thanks for the heads up on this @ShylajaDevadiga .

**Comment by ShylajaDevadiga** [comment]
Closing issue as validated.
