### ISSUE TITLE
Unable to connect to the CoreDNS nameserver IP

### ISSUE THREAD

**Issue by leon-andria** [rancher/rke2#3020]
**Environmental Info:**
RKE2 Version: v1.23.6+rke2r2

Node(s) CPU architecture, OS, and Version: 
5.13.0-1025-azure #29~20.04.1-Ubuntu

Cluster Configuration:
"3 servers, 4 agents"

**Describe the bug:**
To save compute on Azure, we start/stop VMs.
With the scheduler job, we start first the servers and 30 min later, the agents.
Some pods require to connect to Internet but can't resolve the host. Somehow, there is a DNS issue to resolve the host and this is randomly.
The resolv.conf file as the nameserver 10.43.0.10 but this IP can't be reachable.
nslookup google.com 10.43.0.10 ends to a timeout.
However, nslookup google.com 8.8.8.8 works pretty well as expected.
When nslookup google.com 10.43.0.10 works, it happen only the first time, the second call will fail and this behavior happen to any new host.
We are thinking it's a problem of CoreDNS but putting logs on it didn't bring too much help.
If anyone has tips to where to start or any guidances are welcome.

**Comment by manuelbuil** [comment]
Thanks for reporting this. Could you check if doing the `nslookup` using the IP of the coredns pod works? In other words, instead of `nslookup google.com 10.43.0.10` use `nslookup google.com $corednsIP`
