### ISSUE TITLE
Create release Channel for 1.24

### ISSUE THREAD

**Issue by alb-dev** [rancher/rke2#3048]
**Is your feature request related to a problem? Please describe.**
Create a release channel for 1.24 so that it can be used as a reference in other sotware products. 

**Describe the solution you'd like**
Create a release channel like the following "https://update.rke2.io/v1-release/channels/v1.23" for 1.24

**Describe alternatives you've considered**

**Additional context**
This would be greate for the updates (system upgrade controller) so that minor release can be installed automatically

**Comment by rancher-max** [comment]
Validated v1.24 channel is now present:
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_CHANNEL=v1.24 sh -
[INFO]  finding release for channel v1.24
[INFO]  using v1.24.1+rke2r2 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.24.1+rke2r2/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.24.1+rke2r2/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
```
