### ISSUE TITLE
[Release 1.23] kube-ipvs0 not removed when cleaning up

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#3049]
Backport: https://github.com/rancher/rke2/issues/3017

**Comment by mdrahman-suse** [comment]
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux i5.4.0-1009-aws #9-Ubuntu x86_64 GNU/Linux
"Ubuntu 20.04 LTS"
```
  
*Cluster Configuration:*

```
1 server all roles
```
  
*Config.yaml:*

```
write-kubeconfig-mode: 644
kube-proxy-arg: "proxy-mode=ipvs"
```
  
## Replication Steps

  
- Copy config.yaml file to `/etc/rancher/rke2`
- Execute `ip a` command and ensure that `kube-ipvs0` interface is NOT observed
- Then execute
```
$ sudo modprobe ip_vs_rr && sudo modprobe ip_vs_wrr && sudo modprobe ip_vs_sh
```
- Install RKE2:

```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.23.7+rke2r2 sh -
```
- Start RKE2:
```
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
```
- Execute `ip a` command and ensure that `kube-ipvs0` interface is observed
- Then execute `sudo rke2-uninstall.sh` to uninstall rke2
**Results:**

- Execute `ip a` command and `kube-ipvs0` interface is still visible 
 
## Validation Steps

  
- Copy config.yaml file to `/etc/rancher/rke2`
- Execute `ip a` command and ensure that `kube-ipvs0` interface is NOT observed
- Then execute
```
$ sudo modprobe ip_vs_rr && sudo modprobe ip_vs_wrr && sudo modprobe ip_vs_sh
```
- Install RKE2:

```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=bc865ee5801cf5666b4d98dce1ff82901a0cc9b8 sh -
```
- Start RKE2:
```
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
```
- Execute `ip a` command and ensure that `kube-ipvs0` interface is observed
- Then execute `sudo rke2-uninstall.sh` to uninstall rke2
  
**Results:**

- Execute `ip a` command and `kube-ipvs0` interface is NOT observed 
  
**Additional context / logs:**
```
```
