### ISSUE TITLE
Static pod manifest customization

### ISSUE THREAD

**Issue by QtSYnT** [rancher/rke2#3104]
**Is your feature request related to a problem? Please describe.**

RKE2 provides limited ability to configure the generated static pod manifest files for control plane components. Some items like liveness probes are unable to be configured due to this abstraction.

**Describe the solution you'd like**

A generic way to override values in the generated manifests would be ideal or alternatively a way to supply an existing manifest file to be used instead.

**Describe alternatives you've considered**

There are limited workarounds that can be applied like for example disabling certain control plane components and then supplying the manifest ourselves but this isn't possible for all components.

**Additional context**

N/A

**Comment by brandond** [comment]
Are there any specific bits of the probes you'd like to see changed? Generic customization of manifest fields is unlikely to land without a specific use case, but if there's something in particular you're wanting to change we may be able to accommodate that more quickly.

**Comment by QtSYnT** [comment]
A good start would be the ability to manipulate the timing/threshold values for the existing probes. Next level up from that would be a way to define probes that don't already exist and their respective values.

I'm open to "hacky" solutions that can achieve this so if even some unsupported pathways exists for it or could be opened up that would be great.

**Comment by brandond** [comment]
Can you describe what you think we're missing from the current control-plane component static pod health checks? I believe that most of ours mirror the kubeadm defaults pretty closely.

**Comment by QtSYnT** [comment]
I'd like to see a way to define startup/liveness probes for static pods to facilitate monitoring. So for example right now the api server and kube proxy don't have any probes defined.

**Comment by brandond** [comment]
See what you think of that PR. If all you want is to add health checks to those two static pods, that should do it.

**Comment by QtSYnT** [comment]
Sorry about the delay on this I needed to verify a few more things before I got back to you. So it's great that the liveness probes now exist for all static pods but the following are missing if we're using kubeadm as a reference.

The following are missing startup probes:

- etcd
- kube-apiserver
- kube-controller-manager
- kube-scheduler
- kube-proxy

The kube-apiserver is also missing the readiness probe.

The startup probe is critical in accurately reporting the "Ready" status of the pod. When it's not defined the only time the pod will report a "Not Ready" status is a split second when restarting from the liveness probe and then again once the pod goes on CrashLoopBackOff. That's the functionality observed in RKE2 while in contrast kubeadm installs will retain a "Not Ready" status until the probe succeeds unlike RKE2/k3s.

Then the second part of this request would be to expose the failureThreshold, intialDelaySeconds, periodSeconds, and timeoutSeconds values as configuration flags in RKE2. It would be acceptable to have them configurable per probe type in aggregate but really any method to tune these to specific requirements would be appreciated.

**Comment by brandond** [comment]
Can you provide some example of how you're consuming the pod status output? Other than it being more technically correct to have these, I don't see how their presence or absence affects the correct operation of the system.

**Comment by QtSYnT** [comment]
Our own monitoring tools use the ready status among other things to detect isolated failures for control plane pods. This information is pulled from the Kubernetes API by the monitoring tool and will alert on failures. This works great with Kubeadm but with RKE2, control plane pods happily report that they are working fine when in fact they are not responding. If we're talking just isolated to RKE2 then sure the pods are restarting correctly when failed however this is obstructing external monitoring. We're open to another solution for pulling accurate control plan pod status if an alternative exists.

As for the probe values we just simply need to fail/recover faster for our usage.

**Comment by brandond** [comment]
I've just added a PR to add the missing probes, but since kubeadm hardcodes the thresholds and does not provide any easy way to tune them, I'm liable to do the same for RKE2:
https://github.com/kubernetes/kubernetes/blob/v1.24.0/cmd/kubeadm/app/util/staticpod/utils.go#L245-L269

**Comment by QtSYnT** [comment]
Thanks for the PR. 

As for the hard coded probe values the difference between RKE2 and Kubeadm in this case is that once a node is installed the static pod manifests can be modified to reflect whatever is desired. In contrast RKE2 will overwrite any changes on each startup blocking this workaround. Ideally if a flag could be passed to RKE2 to tell it to not overwrite these files if they already exist that would solve this issue for us.

**Comment by brandond** [comment]
Hmm. I've updated the PR to include the ability to override the defaults, although it's not pretty. See what you think.

**Comment by QtSYnT** [comment]
Fantastic this is exactly what we needed and closes out this feature request. Thanks for this.

**Comment by brandond** [comment]
Reopening for QA to test.

**Comment by MichaelTrip** [comment]
+1 for this issue. i need to change certain bind addresses on for example the kube-controller-manager because prometheus scrapes the node IP. Would love it if we could customize these files.

**Comment by brandond** [comment]
@MichaelTrip please check the server configuration docs, you can already do that with` --kube-controller-manager-arg` and the like. This is specifically for configuring the static pod probes.

**Comment by MichaelTrip** [comment]
> @MichaelTrip please check the server configuration docs, you can already do that with `--kube-controller-manager-arg` and the like. This is specifically for configuring the static pod probes; nothing to do with the actual component arguments or Prometheus scrape config.

Hi,

Yeah I already found it. Sorry for the post and thank you for pointing me in the right direction:)

**Comment by ShylajaDevadiga** [comment]
### Validated on v1.24.4-rc1+rke2r1 
  
## Environment Details

  
*Infrastructure*
- [X ] Cloud
  
*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04
  
*Cluster Configuration:*
Single node cluster
  
*Config.yaml:*
```
control-plane-probe-configuration:
  - kube-apiserver-readiness-period-seconds=13
```
  
## Testing Steps
1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2

**Validation Results:**
- rke2 version used for validation:
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.24.4-rc1+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -
```
```
ubuntu@ip-172-31-5-110:~$ kubectl get pods -n kube-system kube-apiserver-ip-172-31-5-110 -o yaml|grep readiness -A 15
    readinessProbe:
      exec:
        command:
        - kubectl
        - get
        - --server=https://localhost:6443/
        - --client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt
        - --client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key
        - --certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt
        - --raw=/readyz
      failureThreshold: 3
      periodSeconds: 13
```
control-plane-probe-configuration don’t work properly if you enter them as a list in config.yaml, only the last value is used
For example `etcd-startup-initial-delay-seconds` parameter is replaced by  `kube-apiserver-readiness-period-seconds`
```
control-plane-probe-configuration:
  - etcd-startup-initial-delay-seconds=42
  - kube-apiserver-readiness-period-seconds=13
 ```
```
$ kubectl get node -o yaml|grep startup
      rke2.io/node-args: '["server","--control-plane-probe-configuration","etcd-startup-initial-delay-seconds=42","--control-plane-probe-configuration","kube-apiserver-readiness-period-seconds=13"]'
ubuntu@ip-172-31-5-110:~$ kubectl describe pod -n kube-system etcd-ip-172-31-5-110  |grep -i startup
    Startup:   http-get http://localhost:2381/health%3Fserializable=true delay=10s timeout=5s period=10s #success=1 #failure=24
```
 Issue to track: https://github.com/rancher/rke2/issues/3256
