### ISSUE TITLE
Ability to specifically enable containerd systemd cgroup without custom config.toml.tmpl file

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#3106]
**Is your feature request related to a problem? Please describe.**
Currently, the cgroups default to cgroupfs but we would like to use systemd without a custom containerd config template

**Describe the solution you'd like**
RKE2 flag to enable systemd cgroup for containerd `SystemdCgroup = true`

**Describe alternatives you've considered**
None other than providing our own template file

**Comment by frank-at-suse** [comment]
What's the content of `/var/lib/rancher/rke2/agent/etc/containerd/config.toml`?

**Comment by olljanat** [comment]
Which vetsion you are using?

As far I understand this one should handle that automatically https://github.com/k3s-io/k3s/pull/5462

**Comment by brandond** [comment]
Yes, as per the above linked PR, K3s will automatically use the systemd cgroup driver on a supported version of systemd. Can you confirm that you're on a recent release of both K3s and systemd?
