### ISSUE TITLE
Support for RHEL 8.6

### ISSUE THREAD

**Issue by snasovich** [rancher/rke2#3112]
As of 5/28/22 per https://docs.rke2.io/install/requirements/#linux the highest RHEL version RKE2 was validated on is RHEL 8.5.
It's possible there are issues with running standalone RKE2 on RHEL 8.6, most specifically https://github.com/rancher/rancher/issues/37997.

Please verify/fix support for RHEL 8.6.

**Comment by est-suse** [comment]
Os has been validated.

https://confluence.suse.com/pages/viewpage.action?pageId=1025344090
