### ISSUE TITLE
Upgrade from RKE2 Version v1.22.9+rke2r2 to v1.23.7+rke2r2 fails with "critical configuration value mismatch" do to missing EgressSelectorMode

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#3121]
**Environmental Info:**
RKE2 Version: v1.23.7+rke2r2

rke2 version v1.23.7+rke2r2 (d0c2bd7f1dbd30f5b7bbc2e3c899d2efde979c25)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: Centos 7

3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 servers, many agents

**Describe the bug:**
Trying to upgrade a node from 1.22 to 1.23 but failing with "critical configuration value mismatch". I deleted the VM and k8s node, and then created a new one with the same config (nothing changed as before) but with the new rke2 version installed. All our server nodes get the same config.yaml template with just a few server-specific templated values such as node name and labels. As part of this update, this was not changed at all.

**Steps To Reproduce:**
1. Bring up VM
2. cloud-init sets config.yaml, registries.yaml, and a custom audit-policy.yaml file
3. starts rke2-server systemd service
4. fails due to critical config 

I compared the config between the new server and the already running servers and all are the same except for a different node-labels set which I don't think is a CriticalConfig arg. 

```
INFO[0000] Starting rke2 v1.23.7+rke2r2 (d0c2bd7f1dbd30f5b7bbc2e3c899d2efde979c25)
INFO[0000] Managed etcd cluster not yet initialized
DEBU[0000] This is the server CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc0012bc5d0)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc0012bc600), DisableCCM:true, DisableHelmController:false, DisableNPC:true, DisableServiceLB:false, FlannelBackend:"none", FlannelIPv6Masq:false, EgressSelectorMode:"", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc0012bc630), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc0012bc660)}}
DEBU[0000] This is the local CriticalControlArgs: config.CriticalControlArgs{ClusterDNSs:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}}, ClusterIPRanges:[]*net.IPNet{(*net.IPNet)(0xc001289a10)}, ClusterDNS:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x2b, 0x0, 0xa}, ClusterDomain:"cluster.local", ClusterIPRange:(*net.IPNet)(0xc001289a10), DisableCCM:true, DisableHelmController:false, DisableNPC:true, DisableServiceLB:false, FlannelBackend:"none", FlannelIPv6Masq:false, EgressSelectorMode:"disabled", NoCoreDNS:false, ServiceIPRange:(*net.IPNet)(0xc001289a40), ServiceIPRanges:[]*net.IPNet{(*net.IPNet)(0xc001289a40)}}
FATA[0000] starting kubernetes: preparing server: failed to validate server configuration: critical configuration value mismatch
```

**Expected behavior:**
Server starts

**Actual behavior:**
Fails to start up

**Additional context / logs:**

**Comment by mitchellmaler** [comment]
Looks to me the EgressSelectorMode: "" and EgressSelectorMode: disabled is what is causing it but that is no set in the config at all

**Comment by mitchellmaler** [comment]
Looks like the latest 1.22.10 version sets this to disabled by default 
https://github.com/rancher/rke2/pull/3037
Will update to that version first then try the 1.23 update again

**Comment by mitchellmaler** [comment]
That did not work. 1.22.10 throws the same error over the EgressSelectorMode mismatch. I am unsure how to proceed since the older server nodes do not have that configuration.

**Comment by brandond** [comment]
Thanks for reporting this!

Just to confirm, you're attempting to upgrade the cluster by deleting a server from the cluster, and then replacing it with a new server running the new version?

I know it's not an ideal fix, but are you able to alter the configuration on the existing nodes to change the setting prior to adding the new nodes?

**Comment by mitchellmaler** [comment]
That is correct. We just delete the old nodes/vm and rebuild them, we have been doing that for a while now for general os patches, stop any drife, and rke2 upgrades. 

I can set the config but running `rke2 server --help` on the server nodes I do not even see an option for egress-selector-mode. Will it let me set a non-existing configuration?

Here is a copy of a config that we place on each server node. The main differences between each one is the name and labels. Everything else is the same.

```yaml
# /etc/rancher/rke2/config.yaml
node-name: THIS_SPECIFIC_VM_NAME
profile: cis-1.6
selinux: true
server: https://10.182.214.8:9345
tls-san:
  - 10.182.214.8
  - asc-stg-ham-tenant-01.ascendlearning.com
token: OBMITTED
write-kubeconfig-mode: "0644"
resolv-conf: /run/NetworkManager/no-stub-resolv.conf
cloud-provider-name: rancher-vsphere
audit-policy-file: /etc/rancher/rke2/audit-policy.yaml
control-plane-resource-limits:
  - kube-apiserver-memory=24576.0Mi
control-plane-resource-requests:
  - kube-apiserver-memory=10Gi
kube-apiserver-arg:
  - audit-log-format=json
  - audit-log-maxage=5
  - audit-log-maxbackup=5
  - audit-log-maxsize=256
  - audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log
kube-controller-manager-arg:
  - bind-address=0.0.0.0
kube-scheduler-arg:
  - bind-address=0.0.0.0
kube-proxy-arg:
  - metrics-bind-address=0.0.0.0:10249
cni: calico
node-taint:
  - CriticalAddonsOnly=true:NoExecute
node-label:
  - node-pool=asc-stg-ham-tenant-01-cp
  - node-name=asc-stg-ham-tenant-01-cp-01
# disable nginx ingress controller by default
disable: rke2-ingress-nginx

kubelet-arg:
  - system-reserved=cpu=200m,memory=500Mi,ephemeral-storage=1Gi,pid=100
  - kube-reserved=cpu=500m,memory=300Mi,ephemeral-storage=1Gi
  - eviction-hard=imagefs.available<15%,nodefs.available<10%,memory.available<500Mi,nodefs.inodesFree<5%

etcd-s3: true
etcd-s3-endpoint: "OBMITTED"
etcd-s3-skip-ssl-verify: false
etcd-s3-access-key: "OBMITTED"
etcd-s3-secret-key: "OBMITTED"
etcd-s3-bucket: "kubernetes-backups-asc-stg-ham-tenant-01"
```

**Comment by mitchellmaler** [comment]
Do you think the critical configuration check can ignore new/non-existing configurations like this since it is null on the servers but defaults to disabled on the newer versions when not provided in the config?

**Comment by brandond** [comment]
Yes, that's what we should have done. Apparently this is a gap in our current upgrade testing.

**Comment by rancher-max** [comment]
This has been validated in all of the releases, v1.24.2+rke2r1, v1.23.8+rke2r1, and v1.22.11+rke2r1

**Comment by vikstlu** [comment]
Run into this upgrading from v1.23.10 to v1.23.14. Is there a work-around for it or should I go in small steps from .10->.11->...?

**Comment by brandond** [comment]
> Run into this upgrading from v1.23.10 to v1.23.14. 

I'm not aware of it having regressed on v1.23.14. Can you provide more information on what you're seeing?

**Comment by vikstlu** [comment]
I added "EgressSelectorMode: disabled" to the rke2 server config and then the node came up. Added this to my ansible code's auto-generate config.yml (we are always creating new nodes instead of updating). After that i could switch out the two other rke2-server nodes without problems

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vikstlu** [comment]
The previous version was: v1.23.10+rke2r1
The new version: v1.23.14+rke2r1

The server config.yml looks like this from ansible templating:
server: https://xx.xx.xx.xx:9345
token: ****
disable: rke2-ingress-nginx
egress-selector-mode: disabled
node-label:
- [HIDDEN]/purpose=server
node-taint:
- CriticalAddonsOnly=true:NoExecute
tls-san:
- yy.yy.yy

The “egress-selector-mode: disabled” line was missing when it didn’t work.

We are using centos 7 virtual machines on vmware, and installing from tar utilizing ansible roles from here: https://github.com/rancherfederal/rke2-ansible for the actual rke2 installation part.

/Lucas

**Comment by brandond** [comment]
Ah, this was probably caused by https://github.com/rancher/rke2/pull/3529 - there was a short period of time where the default was `disabled`, rather than simply unset, as the fix linked above handles. I agree that this transition was handled poorly.
