### ISSUE TITLE
I am installing RKE2, but I get an error  "curl: (22) The requested URL returned error: 403"

### ISSUE THREAD

**Issue by drylio** [rancher/rke2#3125]
We have a proxy server (squid) with internet access. We want to install RKE2 on a linux ubuntu machine, but we get an error as if we don't have access to github:

root@kubernetes:/usr/bin# curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
[INFO] finding release for channel stable
[INFO] using v1.23.7+rke2r2 as release
[INFO] downloading checksums at https://github.com/rancher/rke2/releases/download/v1.23.7+rke2r2/sha256sum-amd64.txt
curl: (22) The requested URL returned error: 403

Translated with www.DeepL.com/Translator (free version)

**Comment by brandond** [comment]
Sounds like your proxy is allowing access to get.rke2.io, but blocking access to the github release downloads.
