### ISSUE TITLE
Traffic gets transferred over the public IPs

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [rancher/rke2#3126]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.9+rke2r1 (fc31bcb127d7dd85bcd6eae892a3549c1a901720)
go version go1.16.14b7

Node(s) CPU architecture, OS, and Version: 

Linux 5.4.0-109-generic # 123-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers

**Describe the bug:**
We noticed that most of the cluster's traffic goes over the pubic IPs which is costly and has high latency and not the private IPs which is free and has low latency and we already specified the private and public IPs in `/etc/rancher/rke2/config.yaml` file when we built the cluster!

The CNI plugin that gets used is Canal(the default) and here is a sample of the configurations that are used when building the cluster:

```yml
tls-san:
  - rke2.example.com
  - 172....
  - 192....
  - 139....
  - 192....
  - 139....
  - 192....
node-ip: "192...."
node-external-ip: "172...."
```

The private IPs are the ones that start with 192 and the others are public.

We have `eth0` interface that both the private and public IPs are assigned to it and here is a sample of the routing table:

```
default via 172.... dev eth0 proto static
10.... dev cali... scope link
...
172..../24 dev eth0 proto kernel scope link src 172....
192..../17 dev eth0 proto kernel scope link src 192.....
```

**Steps To Reproduce:**

- Installed RKE2: 

```shell
curl -sfL https://get.rke2.io | sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

**Expected behavior:**
We expected the traffic to goes over the private IPs

**Actual behavior:**
Traffic gets transferred over the public IPs

**Comment by MohammedAl-Mahdawi** [comment]
This is what we expected, we expected some traffic to go over the public IPs, for example, to generate certificates and so on and this is why we advertise it in the first place.

The reality is MOST of the traffic goes over the public IPs, the pod-to-pod traffic, the pod-to-service traffic, and so on.

We now pay thousands of extra dollars per month just because of this!

Let me give you one of the cases and please tell me if it makes sense or not.

We have multiple apps that use Redis for many functions like session and cache and with hundreds of thousands of users, all this goes over the public IPs which is high latency and costly while the private ones exist and it is Redis we use it to get high speed then we slow it down because of this!

Please can you suggest to us what is the best thing to do now in order to resolve this?

It is a big production cluster.

Also, I highly recommend that you talk about this in the documentation and make it very clear. I think most of the people expected what we expected but they didn't notice this because of their workloads or so.

**Comment by brandond** [comment]
It's hard to make blanket recommendations since there are so many possible deployment scenarios. What works well for some may not work at all (or work optimally) for others. We usually aim for what will work by default for the most users.

Are you using the default CNI (canal)? How is your external IP actually presented? Do you have a single interface with a private IP, and an external IP NATed to that private IP... or do you have one private interface and one public interface?

**Comment by MohammedAl-Mahdawi** [comment]
We are using Linode and the plan is Dedicated CPU, the other information exists in the bug report.

Thank you!

**Comment by brandond** [comment]
Yes, that is correct. It looks like using the `--public-ip=` flag is probably what you need to do, but I don't believe theres a good way to do that on a per-node basis via the canal daemonset. It may be that canal is not a good choice for your requirements, and you'll need to look at using a different CNI.

**Comment by MohammedAl-Mahdawi** [comment]
We tested this solution on the test cluster and it worked with no side effects or issues. It's been more than ten days since we applied it to our production cluster. Also, there are no side effects or issues.

All the inter-node traffic now uses private IPs.

@brandond Thank you for your help!
