### ISSUE TITLE
rancher-mirror.rancher.cn requires ICP in china

### ISSUE THREAD

**Issue by nzkyyds** [rancher/rke2#3136]
![image](https://user-images.githubusercontent.com/9328617/177692428-7305014c-a3f8-4b3f-ab5f-d7c4242fcd0f.png)

**Comment by niusmallnan** [comment]
@nzkyyds please discuss this case here. https://forums.rancher.cn/

`rancher-mirror.rancher.cn` is not an official service and will not be guaranteed by SLA.
