### ISSUE TITLE
Bump Harvester Cloud Provider 0.1.13

### ISSUE THREAD

**Issue by chrisho** [rancher/rke2#3142]
There’s already a PR for this: https://github.com/rancher/rke2/pull/3138

We also want to backport this to RKE2 v1.21.x (PR https://github.com/rancher/rke2/pull/3141), v1.22.x (PR https://github.com/rancher/rke2/pull/3140) and v1.23.x (PR https://github.com/rancher/rke2/pull/3139).

**Comment by VestigeJ** [comment]
Moved to Rancher to validate when Caleb is back from PTO

**Comment by rancher-max** [comment]
Marked as release blocker based on the linked rancher issue. This issue title probably should change to:
> Bump Harvester Cloud Provider 0.1.14

**Comment by guangbochen** [comment]
Hi @rancher-max & @slickwarren  the version bump PR is already merged so we should be fine to close this one, in regards to the issue https://github.com/rancher/rancher/issues/38336 it was resolved by https://github.com/rancher/dashboard/pull/6450 as a UI related bug, feel free to re-validate it again if u have time, thanks.

**Comment by rancher-max** [comment]
Oh right. I saw your message about that 🙈 Thank you for confirming. I will close this one out and let those issues take care of validating that. Thank you @guangbochen!
