### ISSUE TITLE
nginx ingress tcp-services frequent disconnects

### ISSUE THREAD

**Issue by erSitzt** [rancher/rke2#3144]
Hi,

I'm using a `tcp-services` ConfigMap for the Nginx-Ingress to allow external access to a RabbitMQ in my cluster on port 5672.
I get disconnects every 15-30 minutes for alle clients that go through the nginx-ingress.
Local services in the cluster connecting directly to RabbitMQ stay connected, remote services (external to the cluster ) using a second instance of RabbitMQ ( to test this issue ) using NodePort stay connected too.

The cluster is an imported RKE2 cluster
Rancher: 2.6.6
Provider: RKE2
Kubernetes Version: v1.21.5

The nginx-ingress is the default DaemonSet that was deployed during install

Name :  `rke2-ingress-nginx-controller` 
Image :  `rancher/nginx-ingress-controller:nginx-0.47.0-hardened1`

I have the same setup with nginx-ingress and `tcp-services` in an older Rancher 2.4.11 where this is not issue.
Image : `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`

The RabbitMQ connection is using heartbeat with values between 10s - 60s, all of them get disconnected at the same time, regardless of when they initially connected to rabbitmq.

The nginx-ingress only logs these two lines:

```
Mon, Jul 11 2022 3:23:40 pm | [10.9.3.1] [11/Jul/2022:13:23:40 +0000] TCP 200 15629 22633 1332.029
Mon, Jul 11 2022 3:23:40 pm | [10.9.3.1] [11/Jul/2022:13:23:40 +0000] TCP 200 1240 834 1329.967
```

At the same time all services that connect through the nginx-ingress log the disconnects.
This happens from services in multiple clusters and services started on a local workstation simultaneously
<img width="310" alt="image" src="https://user-images.githubusercontent.com/1625376/178278230-b50954ae-cd9c-442f-8d48-98b2282a78f6.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1625376/178278293-499d3613-b01e-4a1d-9a37-fc3ddc2660e4.png">

**Comment by erSitzt** [comment]
Yeah the simultaneous  disconnects made me think of a problem with a firewall or the loadbalancer in front of the cluster or an error in our services, but i tried all variations and only when going through the nginx-ingress the clients loose the connection.
The same service connecting directly to the nodeport ( same networks/firewall,with and without the loadbalancer ) runs fine for days now...

**Comment by erSitzt** [comment]
So there might be a correlation between backend reloads of nginx-ingress and my disconnects...

Disconnects seem to be happening approx. 4 minutes after a backend reload due to configuration change ( not sure what kind of change, as there is/was no one changing anything at the time )

So i did a grep on the nginx.conf for `240`
```
bash-4.4$ cat nginx.conf | grep 240
worker_shutdown_timeout 240s ;
```
And thats something i read in an issue before...

**Comment by erSitzt** [comment]
And here we go full circle...

https://github.com/rancher/fleet/issues/523#issuecomment-1156566723

My kong related resource still has a name too long for fleet to handle correctly, so it gets redeployed all the time... causing backend reloads and disconnects for my services... :(

**Comment by brandond** [comment]
Sounds like a known issue with fleet then; we should probably close this out as it is not related to RKE2.

**Comment by erSitzt** [comment]
Yeah, I'll close it
