### ISSUE TITLE
"Kubelet exited: exit status 1" when attempting to start service "rke2-server" with options "kube-apiserver-arg" and "kubelet-arg"

### ISSUE THREAD

**Issue by a880c05562b4f31a55f2975840ffb789** [rancher/rke2#3145]
**Environmental Info:**
RKE2 Version: 

    # rke2 --version
    rke2 version v1.22.9+rke2r2 (d7c26a45b92cf3f76c063e93f8c6448fde7b2456) go version go1.16.14b7

Node(s) CPU architecture, OS, and Version: 

    # uname -a
    Linux <HOSTNAME> 3.10.0-1160.62.1.el7.x86_64 #1 SMP Wed Mar 23 09:04:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

One (1) server, two (2) agents

**Describe the bug:**

I am attempting to install the AWS EBS CSI driver in a RKE2 cluster:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md

As part of the install process, I am attempting to pass additional arguments to the kubelet or kube-apiserver processes. 
 However, when attempting to start service rke2-server with file "config.yaml" containing these additional arguments:

    # cat config.yaml.working 
    # /etc/rancher/rke2/config.yaml
    disable:
     - rke2-ingress-nginx
    kube-apiserver-arg+:
      - feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true
    kubelet-arg+:
      - allow-privileged=true
      - feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true

kubelet fails to start.  A 'journalctl -u rke2-server' records what appears to be the output when 'rke2 server --help' is run, so this appears to be a configuration error.  I'm attempting to follow the documentation and various examples, some of them in response to issues reported to this project, but it's not clear what the problem is.

**Steps To Reproduce:**

- Installed RKE2: 

We essentially used the quick start instructions, but have been learning as we have continued working with RKE2 so have been catching up on various prerequisites and "better practices" like changes to configure NetworkManager to ignore calico/flannel related network interfaces.

**Expected behavior:**

I expected the cluster to start with the options above passed as arguments to kubelet or the kube-apiserver processes themselves.

**Actual behavior:**

The cluster does not start, specifically kubelet on the server does not start.

**Additional context / logs:**

I don't know what additional context might be useful.

**Comment by brandond** [comment]
As per https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ `--allow-privileged=true` does not appear to be a valid Kubelet argument. Where'd you get that from?

**Comment by brandond** [comment]
I suspect that the documentation on that page is woefully out of date, and some of the FeatureGates have also been removed and are no longer valid.

**Comment by a880c05562b4f31a55f2975840ffb789** [comment]
Hello @brandond,

All of the feature gates were GA at Kubernetes v1.22.9, so I removed them from file config.yaml.  That is the only thing that is probably of interest to the project.  However, in the interest of others gaining some benefit from our experience:

Briefly, there were any of several problems here:
1. Existing AWS EBS CSI driver install documentation is, as you noted, dated.  Several of the feature gates have been GA since Kubernetes v1.15, which reached EOL over a year ago.
1. When working in AWS GovCloud certain ARN identifiers are different than those given in the example policy.
1. No policy needs to be created when using a Kubernetes secret with an IAM user.  See existing AWS-managed policy "AmazonEBSCSIDriverPolicy", which is virtually identical to the example policy.
1. We are working with encrypted volumes, so had to add an additional policy to deal with KMS.
1. When using a Kubernetes secret with an IAM user, the secret containing the access key and secret access key for the IAM user must be named literally "aws-secret".  There does not appear to be a way to specify an alternate secret, which is a bit limiting.  The AWS EBS CSI driver has to be re-installed after re-creating the secret.

Thanks for your help.

**Comment by ShubhamDesai17** [comment]
Hello @brandond ,
when I use 
```
kubelet-arg:
  - "anonymous-auth=false"
```

I get ` level=error msg="Kubelet exited: exit status 1"`
is this also deprecated?, could you help to resolve

**Comment by brandond** [comment]
Look at kubelet.log to see why it's exiting.
