### ISSUE TITLE
Image pull error for CNI images in airgap installation - install.sh bug

### ISSUE THREAD

**Issue by miguelgmedina** [rancher/rke2#3147]
**Environmental Info:**
RKE2 Version: v1.23.7+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux master-01 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

Cluster Configuration:
1 master
4 workers
airgap environment
CNI: multus,calico

**Describe the bug:**

When bootstraping RKE2 airgap cluster with CNI plugins other than default (in my case, multus and calico), the CNI images are not  loaded by install.sh script. RKE server starts but it cannot start the CNI, so the cluster doesn't get into a Ready state.

**Steps To Reproduce:**

Please, notice I also downloaded zst files with CNI images
```
mkdir /root/rke2-artifacts && cd /root/rke2-artifacts/
curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.7%2Brke2r2/rke2-images-calico.linux-amd64.tar.zst
curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.7%2Brke2r2/rke2-images-multus.linux-amd64.tar.zst
curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.7%2Brke2r2/rke2-images.linux-amd64.tar.zst
curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.7%2Brke2r2/rke2.linux-amd64.tar.gz
curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.7%2Brke2r2/sha256sum-amd64.txt
curl -sfL https://get.rke2.io --output install.sh
```
Create the `/etc/rancher/rke2/config.yaml` file:
```
server: https://192.168.30.21:9345
token: XXXXXXXXXXXXXXXXX
cni: ['multus', 'calico']
tls-san:
  - cluster.local
  - 192.168.30.21
snapshotter: overlayfs
node-name: master-01
```
Run the installer:
```
INSTALL_RKE2_ARTIFACT_PATH=/root/rke2-artifacts sh install.sh
```
Start the RKE2 server systemctl service:
```
systemctl start rke2-server.service
```

**Expected behavior:**

All pods in kube-system namespace running, nodes in Ready state. 
**Actual behavior:**

Multus and calico images missing, not loaded localy in containerd. ImagePullBackOff. 

**Additional context / logs:**
Analyzing install.sh script, I find the functions that stage the main rke2-images.linux-amd64.tar.zst but not the CNI ones (rke2-images-calico.linux-amd64.tar.zst and rke2-images-multus.linux-amd64.tar.zst):
```
# stage_local_airgap_tarball stages the local checksum hash for validation.
stage_local_airgap_tarball() {
    if [ -f "${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.zst" ]; then
        info "staging zst airgap image tarball from ${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.zst"
        cp -f "${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.zst" "${TMP_AIRGAP_TARBALL}"
        AIRGAP_TARBALL_FORMAT=zst
    elif [ -f "${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.gz" ]; then
        info "staging gzip airgap image tarball from ${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.gz"
        cp -f "${INSTALL_RKE2_ARTIFACT_PATH}/rke2-images.${SUFFIX}.tar.gz" "${TMP_AIRGAP_TARBALL}"
        AIRGAP_TARBALL_FORMAT=gz
    fi
}
```
${SUFFIX} in my case is `linux-amd64`. So there is not staging of these images in that local airgap tarball. Calico and Multus tar.zst are ignored.

BR, Miguel :)

**Comment by brandond** [comment]
Yes, that is expected behavior. The install script only installs the core artifacts. If you want to drop tarballs for additional components (or for your own images) you should create the images dir and place the tarballs there yourself.

**Comment by miguelgmedina** [comment]
> Yes, that is expected behavior. The install script only installs the core artifacts. If you want to drop tarballs for additional components (or for your own images) you should create the images dir and place the tarballs there yourself.

Many thanks Brandond. I followed your advice and manually (well, with ansible) copy the tarballs for CNIs (Calico and Multus) before bootstrapping the cluster. Now, CNIs pods start and cluster is in Ready state. 

Well, just to finish, I have not found anything in RKE2 docs about this procedure. Maybe in Airgap installation instructions a comment about deploying CNIs other than the default Canal one.

Thanks again

**Comment by brandond** [comment]
I'm pretty sure it's covered here: https://docs.rke2.io/install/airgap/#tarball-method - the docs haven't been updated since we added multus, but it does note that you must provide additional image tarballs for canal and cilium.
