### ISSUE TITLE
ctr: content digest sha256:... : not found

### ISSUE THREAD

**Issue by trangxoan** [rancher/rke2#3153]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.23.8+rke2r1 (f2f1ecd720f566e2cc8a700073d6d82ba9e2ca52)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 

Linux svim-53-118 4.19.20-041920-lowlatency #201902061341 SMP PREEMPT Wed Feb 6 18:47:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers (1 master node, 2 node)

**Describe the bug:**

root@xx-xx-xx:~/rke2-artifacts# ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
ctr: content digest sha256:0a77ffd6a8416dc185403903fbc3b77145253fd200cc9b68b251f564bc2c9b9e: not found

I have been successful many times before, but the last time I reinstalled this error

**Steps To Reproduce:**

- Installed RKE2: 
$ vi /etc/environment
add path :/var/lib/rancher/rke2/bin
$ mkdir -p /etc/rancher/rke2/
$ vi /etc/rancher/rke2/config.yaml
   write-kubeconfig-mode: "0644"
   write-kubeconfig: "/root/.kube/config"
   cni: "calico"
   tls-san:
     - xx.xx.xx.xx #common IP

$ mkdir /root/rke2-artifacts && cd /root/rke2-artifacts/
$ INSTALL_RKE2_ARTIFACT_PATH=/root/rke2-artifacts sh install.sh
The dependent packages I downloaded here
$ curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.8%2Brke2r1/rke2-images.linux-amd64.tar.zst
$ curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.8%2Brke2r1/rke2.linux-amd64.tar.gz
$ curl -OLs https://github.com/rancher/rke2/releases/download/v1.23.8%2Brke2r1/sha256sum-amd64.txt
$ curl -sfL https://get.rke2.io --output install.sh

$ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
//image-rke2.tar include list image of --namespace k8s.io (export from when install service online)
service rke2-server start

**Expected behavior:**

root@xx-xx-xx:~/rke2-artifacts# ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
done

**Actual behavior:**

root@xx-xx-xx:~/rke2-artifacts# ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
ctr: content digest sha256:0a77ffd6a8416dc185403903fbc3b77145253fd200cc9b68b251f564bc2c9b9e: not found 

**Additional context / logs:**

I have been successful many times before (start succes rke2 service and deploy success app)
but the last time I reinstalled this error

**Comment by brandond** [comment]
```
$ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
//image-rke2.tar include list image of --namespace k8s.io (export from when install service online)
service rke2-server start
```

I'm confused by how you would import things into the rke2 containerd before rke2 is running. If the rke2 service is stopped, so is containerd.

```
root@xx-xx-xx:~/rke2-artifacts# ctr -a /var/run/k3s/containerd/containerd.sock --namespace k8s.io images import image-rke2.tar
ctr: content digest sha256:0a77ffd6a8416dc185403903fbc3b77145253fd200cc9b68b251f564bc2c9b9e: not found
```

What is `image-rke2.tar`? Why are you exporting and manually re-importing all the images via an uncompressed tarball? If you want to preloadload additional images into rke2 at startup, just place the (compressed or uncompressed) tarball in `/var/lib/rancher/rke2/agent/images` and they will be automatically imported after containerd is started, but before the kubelet.
