### ISSUE TITLE
Validate SLES 15 SP4

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#3157]
Verification: Follow New OS Validation page
(https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html)

**Comment by mdrahman-suse** [comment]
SLES15 SP4 has been validated using the versions below
```
Rancher Version: 2.6.7-rc5
RKE2 Versions: v1.24.2+rke2r1, v1.23.8+rke2r1, and v1.22.11+rke2r1
Upgrade Versions: v1.24.3+rke2r1, v1.23.9+rke2r1, and v1.22.12+rke2r1
```

**Comment by Richardswe** [comment]
I upgraded the nodes from OpenSuse Leap 15.3 to 15.4. After that the kube-scheduler,kube-controller-manager and cloud-controller-manager restarts 1-2 times a day. And I'm on rke2 v1.23.7 . Seems to be leader issues between the components. Any suggestions? I'm grateful for replies :)
