### ISSUE TITLE
Initial Logging Output Update

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#317]
The logging needs to be updated and this ticket serves as a placeholder for a first pass until additional design and possible infrastructure is added.

**Comment by davidnuzik** [comment]
This change makes some modifications to logging methods and fixes some spelling. The potential impact on rke2 should be very low. We do not have explicit things to test to close this out - ensure RKE2 comes up as expected - take a peek at journalctl logs - ensure no obvious/unusual issues are seen with a look at the systemd logs.

**Comment by cjellick** [comment]
The PR brian put in was only for k3s. we need to pull that through to rke2 before this could be tested there. Perhaps @MonzElmasry could do that?

**Comment by briandowns** [comment]
I have a branch pushed which just needs to have k3s bumped.=20

> On Sep 21, 2020, at 15:12, Craig Jellick <notifications@zube.io> wrote:
>=20
> =EF=BB=BF
>=20
>  Craig Jellick commented on a Card
>=20
>  #2627 (rancher/rke2 #317) Initial Logging Output Update
>=20
> The PR brian put in was only for k3s. we need to pull that through to rke2=
 before this could be tested there. Perhaps @MonzElmasry could do that?
>=20
> rancher/k3s+rke2/Active Workspace
>=20
> You are receiving this notification because you are subscribed to this ite=
m.=20
> You can change your notification settings at https://zube.io/rancher/k3srk=
e2/w/active-workspace/edit.
>=20

**Comment by ShylajaDevadiga** [comment]
Validated using master build on 
k3s version v1.19.2+k3s-b56e52ee
rke2 version v1.18.9-dev+5762b886
