### ISSUE TITLE
Add rke2 containerd or import sub commands

### ISSUE THREAD

**Issue by guangbochen** [rancher/rke2#3171]
**Is your feature request related to a problem? Please describe.**
We would like to add rke2 sub-commands like `rke2 import` or `rke2 containerd` so that we can use them to manage some pre-requisite works before the rke2 is started, e.g, preloading some images to the node. 

**Describe the solution you'd like**
- use `rke2 import` to specify the path and import the images accordingly, if not specified default to rke2 image path `/var/lib/rancher/rke2/agent/images/`.
- use `rke2 containerd`  to bootstrap the containerd only so users can integrate with cri and crictl command.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by dereknola** [comment]
Thank you for the request, but at this time, the RKE2 team will not be moving forward with this feature. We don't see enough need from customers. 

If you wish to configure containerd and images before hand, it may be best to run `containerd` separate from RKE2, and then use the `--container-runtime-endpoint` flag to disable the embedded CRI and use that instead.
