### ISSUE TITLE
Documentation: need to add the information that node-ip settings are only used during initial join

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#3173]
**Environmental Info:**
RKE2 Version: v1.21.10+rke2r2 
Worker node with two IP addresses

**Describe the bug:**
Changing a IP address of a node that "detected" the wrong IP during joining is not possible after the join with adding the parameter node-ip.

Just learned that this parameter is only relevant during initial join:
"You would need to delete the node and rejoin it. Setting the IPs is only done by the cloud provider during initial join."

**Steps To Reproduce:**
Join an agent with two IP addresses and then they to change the node IP with adding the setting to config.yaml.
Restart the agent
Realize that the IP for the node did not change

**Expected behavior:**
Changing the node-ip setting should also change the node-ip used.
In case this is a wrong expectation - it should be documented for the parameter "node-ip".

**Actual behavior:**
Node IP does not change and the requirement to "remove node and re-add node" is not documented for this change.

**Comment by brandond** [comment]
This is core Kubernetes behavior - the cloud provider only sets node IPs when the node is first joined. Once the addresses have been set and the uninitialized taint is cleared no further address updates are performed.

**Comment by Martin-Weiss** [comment]
Here https://docs.rke2.io/install/install_options/server_config/ I find just this:

  --node-ip value, -i value                     (agent/networking) IPv4/IPv6 addresses to advertise for node
  --node-external-ip value                    (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
 
For me it is not clear that with RKE2 the internal cloud provider is used and due to that it can not be changed after joining.

So could we add some information to the documentation that this can not be changed after node is joined?

**Comment by Martin-Weiss** [comment]
Sure - but I assume most RKE2 users do not know the details of RKE2 internal registration process and might not even find the URL in the kubernetes architecture documentation and understand it as "it is not possible for node-ip and with RKE2".

So could we add some information to the RKE2 documentation that this (node-ip) can not be changed after node is joined? I really belive we need more detailed descriptions on the documentation for the parameters available in RKE2.

**Comment by brandond** [comment]
We could perhaps link to those upstream docs from somewhere, but we tend to not cover in our documentation things that are standard upstream Kubernetes behavior - such as labels, annotations, and IPs not changing after the initial registration.

**Comment by Martin-Weiss** [comment]
I believe RKE2 should have this information in its own docs for RKE2 "users".
Especially the information which parameters of RKE2 config can be changed after deploymend and which not should be documented..
