### ISSUE TITLE
[BUG] Possible memory leak in RKE2 cluster node?

### ISSUE THREAD

**Issue by crazyelectron-io** [rancher/rke2#3174]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.23.7+rke2r2 (d0c2bd7f1dbd30f5b7bbc2e3c899d2efde979c25)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 
Installed RKE2 cluster with 3 etcd/control nodes and 4 worker nodes on a bare metal Harvester cluster of 3 physical nodes (i9-10900, 128MB, 1TB NVMe, 4x 8TB SSD each. Based on Debian 11.3 cloud image (amd64).

**Describe the bug:**
After installation of a 7 node RKE2 cluster and let it run without anything installed on it for a day the memory consumption of one etc/control-plane node went to 82%, while the other 2 stayed at about 60%.

**Steps To Reproduce:**
Install Harvester 1.0.2 on a server (I used 3 nodes) and import it in the Rancher UI.
Install a RKE2 cluster through the Rancher UI with all optional parameters default.
Wait a day or so.

**Comment by brandond** [comment]
> i9-10900, 128MB, 1TB NVMe, 4x 8TB SSD each

Do you mean 128GB? Or is this the processor cache size, and you've not specified the amount of main memory?

> without anything installed on it for a day the memory consumption of one etc/control-plane node went to 82%, while the other 2 stayed at about 60%.

The memory consumption of what? Which process or processes are consuming memory? Can you show `ps` or `top` output?

**Comment by crazyelectron-io** [comment]
> Do you mean 128GB?

Yes, sorry my bad.

> Can you show `ps` or `top` output?

```
    579 root      20   0  767600  69812  21032 S   7.0   1.8  30:22.43 containerd
   1019 root      20   0 1394864 536348  36184 S   2.7  13.7  45:48.44 kube-apiserver
    598 root      20   0  830928  82124  27140 S   1.7   2.1  16:23.65 kubelet
   1009 root      20   0   10.9g 127572  24192 S   1.7   3.2  26:51.47 etcd
   2028 root      20   0 1673260  67632  40932 S   0.7   1.7   9:18.94 calico-node
   6337 root      20   0  827124  91908  25136 S   0.7   2.3   9:22.25 kube-controller
   7203 root      20   0  955268 226492  56220 S   0.7   5.8   7:29.52 agent
    542 root      20   0 1014208  98472  18892 S   0.3   2.5   5:01.67 rke2
   1354 systemd+  20   0 1419552  43196  12744 S   0.3   1.1   1:08.22 calico-typha
   6381 debian    20   0 1283404  64028  15548 S   0.3   1.6   2:19.10 operator
  48593 root      20   0  885520 130820  50712 S   0.3   3.3   4:19.04 agent
      1 root      20   0  166064  10520   6764 S   0.0   0.3   0:53.21 systemd
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kthreadd
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri
      8 root       0 -20       0      0      0 I   0.0   0.0   0:04.70 kworker/0:1H-kblockd
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq
     10 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tasks_rude_
     11 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tasks_trace
     12 root      20   0       0      0      0 S   0.0   0.0   0:06.60 ksoftirqd/0
     13 root      20   0       0      0      0 I   0.0   0.0   0:16.89 rcu_sched
     14 root      rt   0       0      0      0 S   0.0   0.0   0:00.18 migration/0
     16 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/0
     17 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/1
     18 root      rt   0       0      0      0 S   0.0   0.0   0:00.26 migration/1
     19 root      20   0       0      0      0 S   0.0   0.0   0:12.43 ksoftirqd/1
     21 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/1:0H-events_highpri
     24 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kdevtmpfs
     25 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 netns
     26 root      20   0       0      0      0 S   0.0   0.0   0:00.01 kauditd
```
> It is normal that one of the nodes will have higher resource utilization than the others, as many of the core Kubernetes components are lease-locked and only one node at a time performs that work.

I can understand that. It's just that I have had nodes crashing or becoming cordoned a few times (mostky with K3s) for no apparent reason (usually before I installed anything beyond Longhorn), so I feared it might be related to that. But so far, it seems stable at a slightly lower 79%, which indicates what you stated.

Will close this issue.

**Comment by brandond** [comment]
Those figures all seem quite reasonable. etcd mmaps a big chunk so it its virtual memory figures look high but the actual resources used are low, just 120mb. All in all I don't think I see more than 1GB of memory in use by processes here. Are you sure you're not looking at the kernel  buffer and filesystem caches figures when evaluating total system memory utilization?
