### ISSUE TITLE
Add Support for RHEL 9

### ISSUE THREAD

**Issue by wangzheyuan** [rancher/rke2#3180]
RHEL 9 and Rocky Linux 9 has released, it's time to add support for RHEL 9 and Rocky Linux 9.

**Comment by ported-pw** [comment]
Please make this happen!
**For a reaI use case:** I currently cannot run [DragonflyDB](https://dragonflydb.io/) on RKE2 since no distribution supported by RKE2 has Kernel 5.10+.

**Comment by brandond** [comment]
It should already work fine, it just hasn't been tested by QA yet.

**Comment by ported-pw** [comment]
It might work, but I've had trouble installing on RHEL 9, I think with some signing key error. Will try again and post the full error.

**Comment by brandond** [comment]
* Its possible that https://github.com/k3s-io/k3s/issues/5588 is needed for `rke2-selinux` as well.

**Comment by ported-pw** [comment]
Yes, pretty sure that this is the issue I was having.

**Comment by ported-pw** [comment]
Made a separate issue for the bug

**Comment by caroline-suse-rancher** [comment]
Closing due to the new issue making this one a duplicate; tracking for RHEL 9 validation will be here https://github.com/rancher/rke2/issues/3860
