### ISSUE TITLE
Update Cilium to  1.12.0

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#3181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Update Cilium to the latest version

**Describe alternatives you've considered**

**Additional context**

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit 06bd13522885197e27f1f8cedf0ee8ceb2b73669
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-33-176 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
```
  
*Cluster Configuration:*

```
Single node
```
  
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summer
cni: cilium
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2 `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=06bd13522885197e27f1f8cedf0ee8ceb2b73669 sh -`
3. Ensure the cluster and pods are up
 
**Validation Results:**
- rke2 commit used for validation:

```
$ rke2 -v
rke2 version v1.24.3-dev+06bd1352 (06bd13522885197e27f1f8cedf0ee8ceb2b73669)
go version go1.18.1b7
```
 

```
$ kubectl describe -n kube-system deployment.apps/cilium-operator | grep -i image
    Image:      rancher/mirrored-cilium-operator-generic:v1.12.0

$ kubectl describe ds cilium -n kube-system | grep -i image
    Image:      rancher/mirrored-cilium-cilium:v1.12.0
    Image:      rancher/mirrored-cilium-cilium:v1.12.0
    Image:      rancher/mirrored-cilium-cilium:v1.12.0
    Image:      rancher/mirrored-cilium-cilium:v1.12.0
    Image:      rancher/mirrored-cilium-cilium:v1.12.0
    Image:       rancher/mirrored-cilium-cilium:v1.12.0

$ kubectl describe daemonset.apps/cilium-node-init -n kube-system | grep -i image
    Image:      rancher/mirrored-cilium-startup-script:d69851597ea019af980891a4628fb36b7880ec26
```
- Also validated and confirmed networking checks pass (ingress, clusterip svc, nodeport)
