### ISSUE TITLE
Please explain, if server damaged ?

### ISSUE THREAD

**Issue by esakarya** [rancher/rke2#3184]
This is a great app, first of all thank you.
I'm setting up a cluster with RKE2. As far as I understand, RKE2 only configures nodes as servers and agents.

Referring to the page below;
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/production/recommended-architecture/

What happens if the server node is damaged? What do we need to do ?

**Comment by Martin-Weiss** [comment]
Delete the failed node and re-install / re-join. As long as there are enough servers that should not have an impact on the running cluster. (3 masters/servers can accept 1 master/server to fail)

**Comment by esakarya** [comment]
soo if master ip changed ? what we need do at agents ?
also i tried add agent from different datacenter, pods cant create what we can do for that ?

**Comment by esakarya** [comment]
I setup 3 node, and install one server another both agent. and i see all nodes are ready.
after i complete delete server node. and i re install it.
i save old token to /etc/rancher/rke2/config.yaml

and i install server with.  curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -

now i am checking node with  kubectl  get node
i can see only server node, another agent nodes missing, what i miss ?

**Comment by esakarya** [comment]
Your documentation on the Error/Recovery issues is really poor. I can only access documents related to installations about rancher. For the purpose of Kubernetes, there is no documentation about disaster scenarios.

I set up a cluster for the second time and re-installed the server node. it is in no way included in the old clustar.

It's time to take a look at the different engines. kubespray etc..
