### ISSUE TITLE
[BUG] `rke2-server.service` fails to activate during `systemctl restart` following `rke2 secrets-encrypt reencrypt`when there are a large # of secrets

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#3186]
**Environmental Info:**
RKE2 Version: v1.24.2+rke2r1

Cluster Configuration:

1 etcd+controlplane+worker

**Describe the bug:**

When a cluster has too many secrets (~10k), the `rke2-server.service` fails to become activate during encryption key rotation post reencrypt. This bug exhibits the same behavior as https://github.com/rancher/rke2/issues/3004.

**Steps To Reproduce:**

- Installed RKE2: Rancher provisioned, but also reproducible standalone
- Create a script that does the following:
  1. Create 10000 secrets
      `kubectl create namespace test-encryption-key-rotation && for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done`
  2. Run `rke2 secrets-encrypt prepare`
  3. Scrape `rke2 secrets-encrypt status` to verify that the current stage is `prepare`
  4. Restart the node using `systemctl restart rke2-server`
  5. Run `rke2 secrets-encrypt rotate`
  6. Scrape `rke2 secrets-encrypt status` to verify that the current stage is `rotate`
  7. Restart the node using `systemctl restart rke2-server`
  8. Run `rke2 secrets-encrypt reencrypt`
  6. Scrape `rke2 secrets-encrypt status` to verify that the current stage is `reencrypt_finished`
  9. Restart the node using `systemctl restart rke2-server`

**Expected behavior:**

`rke2-server.service` successfully restarts following `rke2 secrets-encrypt reencrypt`

**Actual behavior:**

`rke2-server.service is stuck in Activating state`

**Additional context / logs:**

Attached are the kube-apiserver static pod logs during encryption key rotation

[kube-apiserver-logs.tar.gz](https://github.com/rancher/rancher/files/9192361/kube-apiserver-logs.tar.gz)

Note: This is a root cause of https://github.com/rancher/rancher/issues/38283

**Comment by brandond** [comment]
> Create 10000 secrets

The example only appears to create 1000 secrets, and is probably more efficient if you just do something like: `for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done`

Your remaining steps appear to be missing a couple checks. You should always check the status before restarting the service. For example, there is no check to confirm that the `reencrypt` has completed before the service is restarted the final time. Failure to do so will leave the secrets re-encryption only partially complete.

**Comment by jakefhyde** [comment]
> > Create 10000 secrets
> 
> The example only appears to create 1000 secrets, and is probably more efficient if you just do something like: `for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done`
> 
> Your remaining steps appear to be missing a couple checks. You should always check the `status` output before restarting the service. For example, there is no check to confirm that the `reencrypt` has completed before the service is restarted the final time. Failure to do so will leave the secrets re-encryption only partially complete.
> 
> This would explain the error in the logs, which suggests that the apiserver no longer has the key available to decrypt secrets:
> `2022-07-26T18:12:01.224320272Z stderr F W0726 18:12:01.218599       1 reflector.go:324] storage/cacher.go:/secrets: failed to list *core.Secret: unable to transform key "/registry/secrets/cattle-system/tls-rancher": no matching key was found for the provided AES transformer`

Let me clarify, we are waiting for the status to be what we expect before restarting. Also we are testing with both 1k and 10k secrets: 1k works fine but I must've copied the wrong script when creating the issue, updating now.

**Comment by dereknola** [comment]
Running 10K secrets, I see some interesting behavior where the re-encryption seems to stop around 8500K secrets (based of the progress logs), but all secrets remain accessible and the rotation process completes just fine. So this oddity looks like a separate issue and does affect the functionality of the cluster.

**Comment by jakefhyde** [comment]
@dereknola I think the cluster configuration may be important here. I haven't tested with everyone of our expected cluster permutations, but I can do so today. So far I've only seen this on a single node cluster and a 3 etcd 2 control plane 3 worker.

**Comment by dereknola** [comment]
I just tested this on RKE2, single node, with https://github.com/k3s-io/k3s/commit/1c17f05b8ee669ad309ad344dc443b0ae919328a pulled in and did not hit any errors with 10K secrets rotation.

**Comment by dereknola** [comment]
Note for QA: 
This was reproducible on a single node for RKE2, no need to spin up rancher or multinode cluster.
Steps
- Start single node RKE2
- Create 10K secrets `kubectl create namespace test-encryption-key-rotation && for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done` 
- Run thru the standard secrets encryption rotation steps (described above or in the docs)
- Watch the logs
When testing the old version for failure, failures are seen around the ~8K mark. 

Validation for K3s has already happened. https://github.com/k3s-io/k3s/issues/5933

**Comment by bguzman-3pillar** [comment]
### Validated on RC `v1.25.0-rc4+rke2r1`
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
  
*Cluster Configuration:*

```
1 server
```
  
## Testing Steps

1. Start single node RKE2
2. Create 10K secrets `kubectl create namespace test-encryption-key-rotation && for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done`
3. Run thru the standard secrets encryption rotation steps (described above or in the docs)
4. Watch the logs
 When testing the old version for failure, failures are seen around the ~8K mark.
  
**Replication Results:**
- rke2 version used for replication: `v1.24.3+rke2r1`

```
sudo rke2 secrets-encrypt status                                                                                                                                                      ip-172-31-46-121: Tue Sep 13 21:54:10 2022

Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-09-13T21:11:52Z
 * 
```

- Finished/stuck before 8K
```
Sep 13 21:44:46 ip-172-31-46-121 rke2[63445]: time="2022-09-13T21:44:46Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"ip-172-31-46-121\", UID:\"ip-172-31-46-121\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'SecretsProgress' reencrypted 7980 secrets"
Sep 13 21:44:48 ip-172-31-46-121 rke2[63445]: time="2022-09-13T21:44:48Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"ip-172-31-46-121\", UID:\"ip-172-31-46-121\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'SecretsProgress' reencrypted 7990 secrets"
```
 

```
```
 
**Validation Results:**
- rke2 version used for validation: `v1.25.0-rc4+rke2r1`

```
# sudo rke2 secrets-encrypt status
Encryption Status: Enabled
Current Rotation Stage: reencrypt_finished
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey-2022-09-13T20:38:08Z
 * 




# sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt get --prefix /registry/secrets/test-encryption-key-rotation/test9999 |hexdump -C |more
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 74 65 73 74 2d 65  6e 63 72 79 70 74 69 6f  |s/test-encryptio|
00000020  6e 2d 6b 65 79 2d 72 6f  74 61 74 69 6f 6e 2f 74  |n-key-rotation/t|
00000030  65 73 74 39 39 39 39 0a  6b 38 73 3a 65 6e 63 3a  |est9999.k8s:enc:|
00000040  61 65 73 63 62 63 3a 76  31 3a 61 65 73 63 62 63  |aescbc:v1:aescbc|
00000050  6b 65 79 2d 32 30 32 32  2d 30 39 2d 31 33 54 32  |key-2022-09-13T2|
00000060  30 3a 33 38 3a 30 38 5a  3a 2d 3f b5 46 6c 06 19  |0:38:08Z:-?.Fl..|
00000070  70 fe 7b de 11 a8 a6 7c  bd b2 d5 95 0c 04 ba d0  |p.{....|........|
00000080  0a 92 c6 21 40 da 00 df  be 21 b4 ed 07 e1 e5 0f  |...!@....!......|
00000090  b0 a1 d2 2d bd bc 9d 2d  5c 6a 48 10 9e 99 e3 b5  |...-...-\jH.....|
000000a0  85 1f ae 3d 2a 52 85 2c  b0 c2 2f 41 e0 6b 33 51  |...=*R.,../A.k3Q|
000000b0  eb d5 97 7b 70 80 b1 7e  29 38 52 8b 26 c8 55 e7  |...{p..~)8R.&.U.|
000000c0  25 fb 56 36 dc d1 c3 be  f5 76 52 c9 13 c8 cc 64  |%.V6.....vR....d|
000000d0  42 eb 01 ae 7a a6 4d 62  16 dc 03 1e 09 ad b3 30  |B...z.Mb.......0|
000000e0  6e 3e ae 95 27 c0 63 7f  0b 96 fb ba 44 da 2b 35  |n>..'.c.....D.+5|
000000f0  42 5d 56 55 8a c6 97 c9  0e 5f d1 b1 98 db c8 46  |B]VU....._.....F|
00000100  59 7d 09 70 aa 7f 42 eb  06 5b 6a 69 01 09 0c d1  |Y}.p..B..[ji....|
00000110  a8 df 0b 56 fa c2 1a 7d  8e cb 92 45 dd a0 86 66  |...V...}...E...f|
00000120  d9 fa e0 11 5e 1b f6 b2  2f c2 9b 8a 76 4c 18 18  |....^.../...vL..|
00000130  03 1c 26 c5 a6 62 ca f5  30 73 c3 39 e6 5f df 5f  |..&..b..0s.9._._|
00000140  9b 87 a7 b6 24 0a 2d 4e  5b 04 bf 5c a6 b0 21 4d  |....$.-N[..\..!M|
00000150  76 d9 a5 29 ff 43 16 df  7b e7 f6 1d f5 fa e2 86  |v..).C..{.......|
00000160  c5 bc 55 e7 32 78 45 63  f2 28 71 ae 5a ca 6d 85  |..U.2xEc.(q.Z.m.|
00000170  a1 f1 0f cd 14 d8 b7 0e  ee 0a                    |..........|
0000017a
```
- Checking logs: all secrets got reencrypted
```
$ sudo journalctl -u rke2-server | grep "reencrypted"
Sep 13 21:18:46 ip-172-31-36-215 rke2[175405]: time="2022-09-13T21:18:46Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"ip-172-31-36-215\", UID:\"ip-172-31-36-215\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'SecretsProgress' reencrypted 10280 secrets"
```
