### ISSUE TITLE
Add Feature Gates

### ISSUE THREAD

**Issue by jonathon2nd** [rancher/rke2#3193]
**Is your feature request related to a problem? Please describe.**

Unable to add feature gates in Rancher created RKE2 clusters, like RKE

**Describe the solution you'd like**

Some way to add feature gates through UI or API

**Describe alternatives you've considered**

Kinda need for RKE2

**Additional context**

I have looked though https://docs.rke2.io/ and have found nothing.

https://rancher-users.slack.com/archives/C01PHNP149L/p1659037158151269?thread_ts=1659005780.732539&cid=C01PHNP149L

>I am also attempting to figure out how to enable feature gate on RKE2.
I have looked at
https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke2-config-reference/
which leads to
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
--feature-gates <A list of 'key=true/false' pairs>
...
(DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See [kubelet-config-file](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for more information.)
I have tried a few ways to add, but all the ways I would add to rke do not seem to be there. I used to be able to add via API.
Wanting to add to test out [linstor-csi](https://github.com/piraeusdatastore/linstor-csi)
You will need to enable the following feature gates on both the kube-apiserver and all kubelets for this plugin to be operational: CSINodeInfo=true, CSIDriverRegistry=true,VolumeSnapshotDataSource=true. Please ensure that your version of Kubernetes is recent enough to enable these gates.
Other Doc: https://linbit.com/blog/linstor-csi-plugin-for-kubernetes/
Any know how to enable feature flags on RKE2 though Rancher?

**Comment by brandond** [comment]
https://docs.rke2.io/install/install_options/server_config/ 
```
   --kube-apiserver-arg value                    (flags) Customized flag for kube-apiserver process
   --kube-controller-manager-arg value           (flags) Customized flag for kube-controller-manager process
   --kube-scheduler-arg value                    (flags) Customized flag for kube-scheduler process
```

`--kube-apiserver-arg=FeatureGates=MyGate=true`
