### ISSUE TITLE
rke2 server --cluster-reset with --cluster-reset-restore-path fails with "open /var/lib/rancher/rke2/force-restart: is a directory"

### ISSUE THREAD

**Issue by roderickgreen** [rancher/rke2#3196]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.23.9+rke2r1 (2d206eba8d0180351408dbed544c852b6b4fdd42)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 

Linux  5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 control plane, 2 worker

**Describe the bug:**

rke2 server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-<snapshot> fails with
WARN[0000] not running in CIS mode
FATA[0000] open /var/lib/rancher/rke2/force-restart: is a directory

**Steps To Reproduce:**

- Installed RKE2: curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.23 INSTALL_RKE2_TYPE=server sh -
attempt to restore a periodic snapshot with the above command

**Expected behavior:**

restore should complete successfully

**Actual behavior:**

restore fails with above error 

**Additional context / logs:**

if i'm understanding this correctly, the call here should be to filebase.Dir, not filepath.Base, yeah?  https://github.com/rancher/rke2/blob/master/pkg/rke2/rke2.go#L166. i'm not tooled up for go dev so i can't test / put up a PR.

**Comment by brandond** [comment]
yes, that's probably the wrong call there entirely; it appears that the intent is to ensure that the data-dir exists. I don't think this would cause the problem you're seeing unless your working directory happens to be `/var/lib/rancher/rke2/` while running the restore; otherwise it'll just create a `force-restart` directory in whatever directory you happen to be in... which isn't great either.

**Comment by roderickgreen** [comment]
oh you're right. changing out of `/var/lib/rancher/rke2/` gets me up and running. i was wondering how this could have gone unnoticed for so long but that makes sense. thanks!

**Comment by bguzman-3pillar** [comment]
### Validated on <branch> with <commit> / <version>
```
rke2 -v
rke2 version v1.24.4-rc1+rke2r1 (48205d8a01cfb3084d2a430bd01a005451abc9cf)
go version go1.18.1b7

```
  
## Environment Details

  
*Infrastructure*
- [ x ] Cloud
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
```
  
*Cluster Configuration:*

```
3 servers, 2 agents
```
   
## Testing Steps
1. Pre condition: HA cluster up and ready
2. On main server node deploy some workloads before create the snapshot.
3. Take snapshot to s3: `sudo rke2 etcd-snapshot --s3 --s3-bucket=<YOUR_BUCKET> --s3-folder=rke2snap --s3-region=us-east-2 --s3-access-key=YOURKEY --s3-secret-key="YOURSECRET"`
4. Deploy more workloads
5. Stop all nodes in cluster (by stopping the instances entirely) — MAKE SURE TO GRAB TOKEN BEFORE DOING THIS at `/var/lib/rancher/rke2/server/node-token`
6. Create just one fresh VM
7. Restore s3 snapshot to that fresh VM:
`$ curl -sfL https://get.rke2.io/ | sudo INSTALL_RKE2_VERSION=$VERSION sh -`
`$ sudo rke2 server --cluster-reset --etcd-s3 \
  --cluster-reset-restore-path=on-demand-ip-YOUR_IPINFO \
  --etcd-s3-bucket=YOUR_BUCKET_NAME --etcd-s3-folder=rke2snap --etcd-s3-region=us-east-2 \
  --etcd-s3-access-key=YOURKEY --etcd-s3-secret-key="YOURSECRET" \
  --token=TOKEN`
8. Ensure the initial workloads from step 2 are present in the cluster, and the workloads from step 4 are not
  

 
**Validation Results:**
- RKE2 cluster was successfully restored!
- For all that are `NotReady` status we can just delete and join new nodes. It worked perfectly.
- All workloads deployed worked correctly after restore step.


```
$ kubectl get node -A 
NAME                                          STATUS     ROLES                       AGE   VERSION
ip-172-31-0-209.us-east-2.compute.internal    NotReady   <none>                      66m   v1.24.4+rke2r1
ip-172-31-0-238.us-east-2.compute.internal    NotReady   control-plane,etcd,master   69m   v1.24.4+rke2r1
ip-172-31-13-102.us-east-2.compute.internal   NotReady   <none>                      67m   v1.24.4+rke2r1
ip-172-31-45-151                              Ready      control-plane,etcd,master   15m   v1.24.4+rke2r1
ip-172-31-5-183.us-east-2.compute.internal    NotReady   control-plane,etcd,master   71m   v1.24.4+rke2r1
ip-172-31-8-188.us-east-2.compute.internal    NotReady   control-plane,etcd,master   68m   v1.24.4+rke2r1
```
```
$ kubectl get node -A 
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-45-151   Ready    control-plane,etcd,master   19m   v1.24.4+rke2r1
```
