### ISSUE TITLE
ETCD S3 Snapshots fail when AWS instance uses IMDSv2

### ISSUE THREAD

**Issue by kgtw** [rancher/rke2#3198]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.22.10+rke2r2 (45c39feae55ea479ba5cdcb82aa1e7079e033c23)
go version go1.16.14b7

Node(s) CPU architecture, OS, and Version: 

Linux ip-172-29-202-214 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers, 3 agents

**Describe the bug:**

ETCD snapshots cannot be backed up to AWS S3 when the underlying instance is using IMDSv2 

**Steps To Reproduce:**

- Installed RKE2: 
- Configure controlplane/server instances with IMDSv2 
- Attempt to create a manual snapshot to s3

**Expected behavior:**

S3 Snapshots to be uploaded.

**Actual behavior:**

```
rke2 etcd-snapshot ls
INFO[0000] Checking if S3 bucket my-s3-bucket exists
FATA[0000] 401 Unauthorized
```

**Additional context / logs:**

- minio-go fixed this in https://github.com/minio/minio-go/pull/1489 released in `v7.0.11`
- k3s currently uses minio-go `v7.0.7`

**Comment by rancher-max** [comment]
### Validated on v1.24.4+rke2r1
  
## Environment Details

  
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a && cat /etc/os-release
Linux ip-172-31-46-216 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
  
*Cluster Configuration:*

1 server
  
*Config.yaml:*

N/A
  
*Additional files*

N/A
  
## Testing Steps

Same as in the issue:
1. Install rke2
2. Attempt to take a snapshot using `sudo rke2 etcd-snapshot --s3 --s3-bucket=maxrtest --s3-folder=myfolder --s3-region=us-east-2`
  
**Replication Results:**
- rke2 version used for replication: `v1.22.10+rke2r2`
 

- I did not see the issue exactly the same as in the report, but I do see a 401 unauthorized on the IMDSv2 instance:
```
...
INFO[0000] Checking if S3 bucket maxrtest exists        
WARN[0000] Unable to initialize S3 client: 401 Unauthorized 
INFO[0000] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
INFO[0000] Checking if S3 bucket maxrtest exists        
ERRO[0000] error retrieving S3 snapshots for reconciliation: 401 Unauthorized 
INFO[0000] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete 
```
- On an AWS instance that is using IMDSv1, I see the following, which is what I'm therefore looking for when doing the validation
```
INFO[0000] Checking if S3 bucket maxrtest exists        
WARN[0000] Unable to initialize S3 client: 404 Not Found 
INFO[0000] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
INFO[0000] Checking if S3 bucket maxrtest exists        
ERRO[0000] error retrieving S3 snapshots for reconciliation: 404 Not Found 
INFO[0000] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete 
```
 
**Validation Results:**
- rke2 version used for validation: `v1.24.4+rke2r1`
 
- On an AWS instance that is using IMDSv2, I correctly see the following:
```
INFO[0000] Checking if S3 bucket maxrtest exists        
WARN[0000] Unable to initialize S3 client: 404 Not Found 
INFO[0000] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
INFO[0000] Checking if S3 bucket maxrtest exists        
ERRO[0000] error retrieving S3 snapshots for reconciliation: 404 Not Found 
INFO[0001] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete  
```
