### ISSUE TITLE
Token CA hash does not match the Cluster CA certificate hash for Quick Start Guide..

### ISSUE THREAD

**Issue by jordan-lumley** [rancher/rke2#3214]
**Environmental Info:**
RKE2 Version: rke2 version v1.23.9+rke2r1 (2d206eba8d0180351408dbed544c852b6b4fdd42)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 3 vm nodes under a proxmox controller. 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Linux pos01.prd 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 server and 2 worker nodes

**Describe the bug:**
Following the quickstart guide step by step and keep running into CA cert errors. I have spent 4 days destroying the VM's and starting back from scratch time and time again. Sometimes worker node 1 will join but 2 will fail with these errors. At the time of writing this ticket, worker node 1 is getting the error but node 2 joined successfully.

**Steps To Reproduce:**
Just following the quick start guide.

- Installed RKE2: 

**Expected behavior:**
The nodes to join successfully.

**Actual behavior:**
```
-- Logs begin at Thu 2022-08-04 16:33:11 UTC, end at Thu 2022-08-04 18:46:35 UTC. --
Aug 04 18:15:41 pos02.prd systemd[1]: Starting Rancher Kubernetes Engine v2 (agent)...
Aug 04 18:15:41 pos02.prd sh[48430]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 04 18:15:41 pos02.prd sh[48431]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Aug 04 18:15:41 pos02.prd rke2[48435]: time="2022-08-04T18:15:41Z" level=warning msg="not running in CIS mode"
Aug 04 18:15:41 pos02.prd rke2[48435]: time="2022-08-04T18:15:41Z" level=info msg="Starting rke2 agent v1.23.9+rke2r1 (2d206eba8d018>
Aug 04 18:15:41 pos02.prd rke2[48435]: time="2022-08-04T18:15:41Z" level=info msg="Running load balancer rke2-agent-load-balancer 12>
Aug 04 18:15:41 pos02.prd rke2[48435]: time="2022-08-04T18:15:41Z" level=error msg="token CA hash does not match the Cluster CA cert>
Aug 04 18:15:43 pos02.prd rke2[48435]: time="2022-08-04T18:15:43Z" level=error msg="token CA hash does not match the Cluster CA cert>
Aug 04 18:15:45 pos02.prd rke2[48435]: time="2022-08-04T18:15:45Z" level=error msg="token CA hash does not match the Cluster CA cert>
Aug 04 18:15:47 pos02.prd rke2[48435]: time="2022-08-04T18:15:47Z" level=error msg="token CA hash does not match the Cluster CA cert>
Aug 04 18:15:49 pos02.prd rke2[48435]: time="2022-08-04T18:15:49Z" level=error msg="token CA hash does not match the Cluster CA cert>
Aug 04 18:15:51 pos02.prd rke2[48435]: time="2022-08-04T18:15:51Z" level=error msg="token CA hash does not match the Cluster CA
```

**Additional context / logs:**
The logs above are from the output from the beginning of journactl from the 1st worker node ONLY. The full error message is: 
```Aug 04 18:47:11 pos02.prd rke2[48435]: time="2022-08-04T18:47:11Z" level=error msg="token CA hash does not match the Cluster CA certificate hash: 537e7956a582a6ac14a6e0c5eb7961030efd8c9590550b5b580230e213237868 != 5dc21fa3143eea7ca48f468cdfb5c36553b8b0e184c7fbb9db9d1777d66bfed1"```

**Comment by brandond** [comment]
What is the `--server` URL set to on the agents? Did you put a SSL-terminating load-balancer in front of your server, or does the URL point directly at the server node?

**Comment by jordan-lumley** [comment]
> What is the `--server` URL set to on the agents? Did you put a SSL-terminating load-balancer in front of your server, or does the URL point directly at the server node?

config yaml:
```
server: https://192.168.100.39:9345 
token: K10537e7956a582a6ac14a6e0c5eb7961030efd8c9590550b5b580230e213237868::server:57b288f04abf15074b85b2fdf5c17403
```

**Comment by jordan-lumley** [comment]
And also to note, over the entirety of the week and the multiple attempts, either node #2 will fail to join or #3 will fail to join with errors such as this one. Node #3 joined perfectly fine in this case this time.

**Comment by jordan-lumley** [comment]
Not sure if this will help but here is the output of curl -kv https://192.168.100.39:9345 (server node) 

From worker 1(failing to join): 
```
*   Trying 192.168.100.39:9345...
* TCP_NODELAY set
* Connected to 192.168.100.39 (192.168.100.39) port 9345 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=rke2; CN=rke2
*  start date: Mar  4 15:48:59 2022 GMT
*  expire date: Mar  4 15:48:59 2023 GMT
*  issuer: CN=rke2-server-ca@1646408939
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: 192.168.100.39:9345
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 04 Aug 2022 19:08:50 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 192.168.100.39 left intact
```


From worker node 2(successful join): 
```
*   Trying 192.168.100.39:9345...
* TCP_NODELAY set
* Connected to 192.168.100.39 (192.168.100.39) port 9345 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=rke2; CN=rke2
*  start date: Aug  4 18:01:20 2022 GMT
*  expire date: Aug  4 18:01:20 2023 GMT
*  issuer: CN=rke2-server-ca@1659636080
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x557fe121dd80)
> GET / HTTP/2
> Host: 192.168.100.39:9345
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Thu, 04 Aug 2022 19:08:46 GMT
< 
404 page not found
* Connection #0 to host 192.168.100.39 left intact
```

**Comment by brandond** [comment]
Do you have the **exact same** token on both agents?

What do you get from `curl -ks https://192.168.100.39:9345/cacerts | sha256sum` on both agents? The sha256sum should match the bit immediately following `K10` in the token value: `537e7956a582a6ac14a6e0c5eb7961030efd8c9590550b5b580230e213237868`

**Comment by jordan-lumley** [comment]
I used the same config.yaml between both worker nodes. But the result of the curl command you had asked me to run is different. 

Screenshots: 
Worker 1
![image](https://user-images.githubusercontent.com/57803850/182935054-1ae0a2f5-5642-47ee-b362-ebfa744642ce.png)

Worker 2
![image](https://user-images.githubusercontent.com/57803850/182935159-eae4d375-dd72-4ef9-876e-b6c774d96a92.png)

How is that possible?

**Comment by brandond** [comment]
Are these VMs or something? Are you sure 192.168.10.39 reaches the same host from both nodes?

**Comment by jordan-lumley** [comment]
These are VM's, yes. What way would you like me to check to verify that they're hitting the same host? Willing to try whatever you need to me to try in order to troubleshoot. We have a proxy that faces external to handling basic web traffic but this is just a local <-> to local connection so the proxy is avoided at this point.

**Comment by brandond** [comment]
That's a bit beyond what I can help you troubleshoot, but you might try just the basics:
What is the **complete** output of `curl -vks https://172.17.0.2:9345/cacerts` - is there a bit in there about `* Uses proxy env variable HTTPS_PROXY ==`  ?
* If you ssh to that IP from the agents, do you end up on the same host?

**Comment by jordan-lumley** [comment]
I destroyed the 1st worker node and going to try and rebuild the VM real quick. I'll report back in 5-10 minutes.

**Comment by jordan-lumley** [comment]
So, surpsingly enough, after the double digits worth of times I deleted proxmox VM's and restarted the process over again, this time it worked. However, the proxy wont stay open :( why meeeee lol

![image](https://user-images.githubusercontent.com/57803850/182941403-9a950199-9c65-4f2e-bc0b-a32ba1b6c237.png)

Server: 
![image](https://user-images.githubusercontent.com/57803850/182941440-32faac5d-b930-4f65-8bbc-5fe74e599a36.png)

Worker 1: 
![image](https://user-images.githubusercontent.com/57803850/182941616-6d193c11-c791-41b5-a12d-1cbce94ce02d.png)

**Comment by jordan-lumley** [comment]
![image](https://user-images.githubusercontent.com/57803850/182944108-cc7d1b54-6369-4780-a6ae-1285bbd80364.png)

**Comment by jordan-lumley** [comment]
Should I open a separate issue for this next issue im running into?

**Comment by brandond** [comment]
no, it looks like another aspect of the same thing. Is something going on with the network between the VMs?

**Comment by dsyorkd** [comment]
@jordan-lumley did you figure this out? I'm seeing much the same, but the only difference I can tell, is that whenever I use node-ip in the server config, pods like coredns and nginx aren't able to ever complete, leaving out node-ip, and my cluster starts but using the wrong adapter/ip for communication.

**Comment by CagiHub** [comment]
This one helped me:
ssh into the machine and run command:
`systemctl restart rke2-agent.service`

**Comment by jostmart** [comment]
I think there is a clarification problem in the documentation. If you add token to your initial servers /etc/rancher/rke2/config.yaml, that token is not picked up by RKE. In fact, another token will be generated and added to /var/lib/rancher/rke2/server/node-token.

172.20.10.100 loadbalancer pointing towards 172.20.10.15

Example from my initial master:

```
cat /var/lib/rancher/rke2/server/node-token
K10c7d825d6fece904bc2755bd226b99f829cd12a23c7884dd095a6a02f7a03d953::server:7ccd56357e2b6663b846a7493a7124c2

curl -ks https://172.20.10.100:9345/cacerts | sha256sum
c7d825d6fece904bc2755bd226b99f829cd12a23c7884dd095a6a02f7a03d953  -

curl -ks https://172.20.10.15:9345/cacerts | sha256sum
c7d825d6fece904bc2755bd226b99f829cd12a23c7884dd095a6a02f7a03d953  -

cat /etc/rancher/rke2/config.yaml
tls-san:
  - 172.20.10.100
```


And this is from my second master:
```
cat /etc/rancher/rke2/config.yaml
server: https://172.20.10.100:9345
token: K10c7d825d6fece904bc2755bd226b99f829cd12a23c7884dd095a6a02f7a03d953::server:7ccd56357e2b6663b846a7493a7124c2
tls-san:
  - 172.20.10.100
```

When using curl, to compare cacerts like above you need to remember that even an error output will be piped to sha256sum. Example below look like a faulty token, but its in fact an empty reply from a non existing service:

```
curl -ks https://172.20.10.16:9345/cacerts | sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
```

**Comment by jostmart** [comment]
This error still exist in: rke2_version: v1.25.3+rke2r1 on RPM based OS

**Comment by brandond** [comment]
> why the token from the configuration file are not picked up by the initial server?

You can't change the token after the fact. I can't really follow the sequence that you described above, but if you have a short token set in the config file at the initial startup of the cluster, that token will be honored.

Note that it only makes sense to set the short token on the first server, not a full `K10` format token. Since the first server to start up generates new CA certificates, and the long token includes a hash of the CA certificates, there is no way that a predefined `K10` token's embedded hash is ever going to match the actual hash of the certificates.

**Comment by jostmart** [comment]
So after changing into a passphrase instead of token, for the token parameter, things work. Thanks for the clarification about the difference between a K10 format token, and passphrase for the token parameter!

**Comment by caroline-suse-rancher** [comment]
Closing as this does not appear to be a bug with rke2
