### ISSUE TITLE
Failing to initialize cluster when providing container-runtime-endpoint

### ISSUE THREAD

**Issue by QtSYnT** [rancher/rke2#3219]
**Environmental Info:**
RKE2 Version: 
v1.23.9+rke2r1
v1.23.8+rke2r1

Node(s) CPU architecture, OS, and Version: 
4.18.0-372.13.1.el8_6.x86_64
4.18.0-147.5.1.el8_1.x86_64

Cluster Configuration:
Single node clusters

**Describe the bug:**

When `container-runtime-endpoint` is specified to use CRI-O as the CRI, RKE2's ready endpoint will continually fail while logs show failures to connect to containerd. A temporary "fix" for this issue is to symlink the CRI-O socket to `/run/k3s/containerd/containerd.sock`. Unsure if I'm missing something else that needs to be configured in RKE2.

**Steps To Reproduce:**
1. Install CRI-O
2. Install RKE2 with the automated script provided in the quick start
3. Configure RKE2 with `container-runtime-endpoint` for CRI-O

```
cni: multus,canal
disable: rke2-ingress-nginx,rke2-metrics-server
disable-cloud-controller: true
kubelet-arg:
- "cgroup-driver=systemd"
container-runtime-endpoint: "/var/run/crio/crio.sock"
```

**Expected behavior:**

RKE2 should fully use the configured CRI socket and not the embedded one. 

**Actual behavior:**

Kubelet is configured to use the correct CRI and will start up along with some of the control plan static pods. Startup will halt however at the RKE2 ready check. See logs:

**Additional context / logs:**

```
Aug 08 19:05:32 crio-test rke2[3663]: time="2022-08-08T19:05:32Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:05:37 crio-test rke2[3663]: time="2022-08-08T19:05:37Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:05:42 crio-test rke2[3663]: time="2022-08-08T19:05:42Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:05:47 crio-test rke2[3663]: time="2022-08-08T19:05:47Z" level=info msg="Waiting for cri connection: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""
Aug 08 19:05:47 crio-test rke2[3663]: time="2022-08-08T19:05:47Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:05:52 crio-test rke2[3663]: time="2022-08-08T19:05:52Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:05:57 crio-test rke2[3663]: time="2022-08-08T19:05:57Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Aug 08 19:06:02 crio-test rke2[3663]: time="2022-08-08T19:06:02Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```

**Comment by QtSYnT** [comment]
Looks to me like this bug was introduced in #3058 with the addition of checkStaticManifests which is using the const containerdSock variable.

**Comment by brandond** [comment]
cc @dereknola - can you take a look at this?

**Comment by bguzman-3pillar** [comment]
### Validated on branch with RC v1.24.4-rc2+rke2r1
```
$ rke2 -v
rke2 version v1.24.4-rc2+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
```
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
```
  
*Cluster Configuration:*

```
1 server
```
  
*Config.yaml:*

```
$ cat config.yaml 
write-kubeconfig-mode: 644
token: summer
cni: multus,canal
disable: rke2-ingress-nginx,rke2-metrics-server
disable-cloud-controller: true
kubelet-arg:
- "cgroup-driver=systemd"
container-runtime-endpoint: "/var/run/crio/crio.sock"
```

## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.24.4-rc2+rke2r1 sh -
```
3. Start rke2 service: `sudo systemctl enable crio.service --now`
  
**Validation Results:** 
- Error doesn't show anymore
