### ISSUE TITLE
[Release-1.23] - Cannot run rancher on hardened system

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#3224]
Backport fix for Cannot run rancher on hardened system

* #3195

**Comment by rancher-max** [comment]
### Validated on release-1.23 branch commit `4b350b64c945446c3affdb06012e3ea7e8521f66`

- Rancher UI is accessible again
- There is now a new network policy applied in hardened mode:
```
$ k get netpol -A
...
kube-system                 default-network-ingress-policy   app.kubernetes.io/name=rke2-ingress-nginx   73m
...
```
