### ISSUE TITLE
Installer ignores patch number when upgrading RPM install

### ISSUE THREAD

**Issue by sidju** [rancher/rke2#3226]
**Environmental Info:**
RKE2 Version: 1.23.8+rke2r1 and 1.23.9+rke2r1

Node(s) CPU architecture, OS, and Version: 
Irrelevant

Cluster Configuration:

1 server, 2 agents

**Describe the bug:**

When upgrading agents to 1.23.8 with the command
`curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.23.8+rke2r1 sudo sh -`
the version 1.23.9 was installed.

**Steps To Reproduce:**

- Installed RKE2: 1.21.7 using the install script (RPM install chosen due to nodes being RHEL)
- Ran `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.23.8+rke2r1 sudo sh -` on the agents
- The version configured in the environment variable isn't followed

**Expected behavior:**
Either that the version configured is installed OR a warning and request to confirm that the patch configured may not be respected.

**Actual behavior:**
On the agents a different version than configured was installed (on the server it seemed to be respected).

**Additional context / logs:**

**Comment by brandond** [comment]
> Installed RKE2: 1.21.7 using the install script (RPM install chosen due to nodes being RHEL)
> Ran `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.23.8+rke2r1 sudo sh -` on the agents

I'm not sure what you're reporting here - are you installing 1.21.7, or 1.23.8? There is no difference in package install logic between server and agent; the version should be (and is, as far as I can tell) respected for both.

**Comment by sidju** [comment]
I initially installed RKE2 1.21.7. When I was upgrading my cluster to 1.23.8 one of the agents upgraded to 1.23.9 instead despite me specifying 1.23.8.
(I believe the 1.23.9 version was published as RPM to the repos used by the installer just as I was upgrading, if that makes a difference)

**Comment by brandond** [comment]
> When I was upgrading my cluster to 1.23.8 one of the agents upgraded to 1.23.9 instead despite me specifying 1.23.8.

Are you upgrading nodes by manually re-running the install script? Can you provide logs showing this behavior?

The installed package version is explicitly set from the version provided in the INSTALL_RKE2_VERSION variable at https://github.com/rancher/rke2/blob/f8f9e453f139abe69b8e33530cac963cdef4afc4/install.sh#L535-L540

```console
brandond@dev01:~$ echo v1.23.8+rke2r1 | sed -E -e "s/[\+-]/~/g" | sed -E -e "s/v(.*)/\1/"
1.23.8~rke2r1
```

The only way I can see what you're describing happening is if you ran a `yum update` after installing the package. If you don't want to update RKE2 via yum, you should use the `yum versionlock` plugin to lock it.

**Comment by sidju** [comment]
I cannot reproduce the issue now, so nevermind I guess.
