### ISSUE TITLE
Debian packages, please (resubmitted)?

### ISSUE THREAD

**Issue by harridu** [rancher/rke2#3230]
I wonder if it would be possible to provide Debian packages for RKE2 as well? This could help to keep the system up-to-date using the default maintenance tools. Not to mention that a lot of additional platforms would benefit from this improvement.

**Comment by hwittenborn** [comment]
Just asking out of curiosity, but would there be any interest in using [makedeb](https://makedeb.org) to create the Debian packages? It's a project I lead, but I think it could greatly reduce the maintenance cost of maintaining the package over traditional Debian packaging.

Any thoughts?

**Comment by harridu** [comment]
I understand that Debian-based distributions are not top of the priority list, esp since Rancher has been bought by RPM-based Suse. Installing tar.gz files bypassing the package manager is a no-go. By not providing Debian packages you scare away a lot of potential users. 

That means less popularity and less revenue.

**Comment by harridu** [comment]
I am creating a private rke2 package on my own now.
