### ISSUE TITLE
Windows Agent is ignoring registries.yaml

### ISSUE THREAD

**Issue by GauthamJayaraman** [rancher/rke2#3239]
**Environmental Info:**
![image](https://user-images.githubusercontent.com/45933097/185137701-37897939-b44d-481d-8862-bdf577362679.png)

RKE2 Version - v1.23.9
Server -  RHEL 8.6
Agent - RHEL, Windows Server 2019

**Describe the bug:**
Windows Agent seems to ignore the registries.yaml file. This file is made available on Windows agent on location c:\etc\rancher\rke2\

```yaml
configs:
   "netinfra.carbon.internal":
      tls:
        insecure_skip_verify: true
```

**Steps To Reproduce:**

Create registries.yaml on the Windows Agent on c:\etc\rancher\rke2\. Configure to skip certificate verification for a private registry. Try to deploy a pod with container images coming from private registry. The pod deployment fails with **ErrorImagePull.**

**Expected behavior:**
The pod deployment should be successful for Windows node. The certificate check should not be done once configured on registries.yaml.

**Actual behavior:**
The pod deployment fails with **ErrorImagePull.**

**Additional context / logs:**
Workaround is to manually import the certificate on windows agent. This issue is not seen with Linux agent.

**Comment by GauthamJayaraman** [comment]
For windows node, the C:\var\lib\rancher\rke2\agent\etc\containerd\config.toml looks like this

  [plugins."io.containerd.grpc.v1.cri".registry.configs**.tls**."netinfra.carbon.internal"]
        insecure_skip_verify = true

where as on Linux systems  /var/lib/rancher/rke2/agent/etc/containerd/config.toml

[plugins.cri.registry.configs."netinfra.carbon.internal".**tls**]
     insecure_skip_verify = true

**Comment by brandond** [comment]
That appears to be intentional, as per the template at https://github.com/k3s-io/k3s/blob/master/pkg/agent/templates/templates_windows.go#L116-L146. I believe there may be an upstream issue with containerd not properly honoring the registry TLS configuration on Windows though?
