### ISSUE TITLE
k3s ClusterRoleBinding missing from RKE2 RBAC

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#324]
rancher/rke2#323 removed the packaged components from k3s, which includes the k3s rolebindings.yaml. Two of the three roles in there are k3s specific (clusterrole.rbac.authorization.k8s.io/system:k3s-controller and clusterrolebinding.rbac.authorization.k8s.io/system:k3s-controller) but the third (clusterrolebinding.rbac.authorization.k8s.io/kube-apiserver-kubelet-admin) is needed to allow the kubelet to function properly. Without it the tunnel endpoint controller does not work and we get errors like:

```
ERRO[0278] Unable to watch for tunnel endpoints: unknown (get endpoints)
```

**Comment by rancher-max** [comment]
@brandond I still occasionally see the mentioned error as a warning:
```
INFO[0059] etcd data store connection OK                
INFO[0059] Waiting for API server to become available   
WARN[0063] Unable to watch for tunnel endpoints: unknown (get endpoints) 
INFO[0064] labels have been set successfully on node: ip-172-31-12-53 
```
It only happens once and always in this same spot, and doesn't cause any errors. Is this expected? Potentially a timing issue with the fix here?

**Comment by brandond** [comment]
You will see `WARN[0063] Unable to watch for tunnel endpoints:` with various reasons after it repeated until after etcd is up, apiserver is up, and rbac is loaded. From the other lines in your log it looks like the apiserver has not yet started.

We probably need to figure out how to get this to wait until later to start so that it's not spamming errors all the time.

**Comment by rancher-max** [comment]
In that case this issue itself is fixed. There are no blocking errors, the kubelet appears to be functioning properly. Down the road we can figure out how to reduce the warning spam. As a note, I do not see the warnings when performing actions on the cluster and checking kubelet logs.
Also, ensured the clusterrolebinding is present: `clusterrolebinding.rbac.authorization.k8s.io/kube-apiserver-kubelet-admin                           ClusterRole/system:kubelet-api-admin`

Validated using `v1.18.9-beta21+rke2`
