### ISSUE TITLE
Quick start failure not connect to docker containerd repo

### ISSUE THREAD

**Issue by DeBr4nd** [rancher/rke2#3244]
HI i've thi issue when i run `sudo rke2 server --debug`.
Here the --debug [logs](https://www.cscinformatica.it/wp-content/uploads/2022/08/log.txt) 

PS Docker is running (and working) installed an Sudoers, Using CentOS8.

**Comment by brandond** [comment]
It appears that your host is unable to pull down critical system components from docker hub. If this host does not have access do docker hub, please follow the airgap installation instructions.

```
WARN[0030] Failed to get image from endpoint: Get "https://auth.docker.io/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=registry.docker.io": dial tcp: i/o timeout
FATA[0030] failed to get runtime image index.docker.io/rancher/rke2-runtime:v1.23.9-rke2r1: all endpoints failed: Get "https://auth.docker.io/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=registry.docker.io": dial tcp: i/o timeout
```

**Comment by DeBr4nd** [comment]
the host have internet access, si i will try your suggestion. tnx

**Comment by DeBr4nd** [comment]
ok my vm is connected to internet and the firewall is deactivated, but nothing is changed.

**Comment by brandond** [comment]
This error:
```
Get "https://auth.docker.io/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=registry.docker.io": dial tcp: i/o timeout` 
```
is what you need to be troubleshooting. Why can't your node connect to Docker Hub?

**Comment by DeBr4nd** [comment]
ok tnx i will investigate
