### ISSUE TITLE
Why does the apisever deployed by rke not support --enable-bootstrap-token-auth=true by default？

### ISSUE THREAD

**Issue by arrowfeng** [rancher/rke2#3245]
**Environmental Info:**
RKE2 Version: 

rke version v1.3.13
Node(s) CPU architecture, OS, and Version: 

Linux iZbp1aak6om0brzooe87c4Z 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 servers.
**Describe the bug:**

When I added a new node in the bootstrap method, an error was reported, and the investigation found that the apiserver did not enable bootstrap-token-auth.

**Comment by brandond** [comment]
We don't use bootstrap tokens to add nodes, nor do we support adding non-rke2 nodes the the cluster. If you can get that working then that's great, but it's not something we test or support.
