### ISSUE TITLE
Add a flag to skip systemctl deamon restart in install script

### ISSUE THREAD

**Issue by dramich** [rancher/rke2#3247]
**Is your feature request related to a problem? Please describe.**
Currently the install script assumes that systemctl is available when doing a tar install, so when using the script to build images and the system init hasn't been ran the install script fails.
**Describe the solution you'd like**
Add a flag to skip the reload

**Comment by mdrahman-suse** [comment]
### Validated on RC v1.25.0-rc5+rke2r1
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-42-243 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
```
  
*Cluster Configuration:*

```
Single node
```
  
*Config.yaml:*

```
write-kubeconfig-mode: 644
cni: calico
token: summerheat
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2 as root: 
  - Replication: `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.24.4+rke2r1 sh -`
  - Validation: `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.25.0-rc5+rke2r1 INSTALL_RKE2_SKIP_RELOAD=true sh -`
3. Check logs: `journalctl --system --no-pager -n 20 | grep Reloading`
  
**Replication Results:**
- rke2 version used for replication:

```
rke2 version v1.24.4+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
```
 

- Logs shows
```
$ journalctl --system --no-pager -n 20 | grep Reloading
Sep 14 23:03:52 ip-172-31-42-243 systemd[1]: Reloading.
Sep 14 23:03:52 ip-172-31-42-243 systemd[1]: Reloading.
Sep 14 23:03:52 ip-172-31-42-243 systemd[1]: Reloading.
Sep 14 23:04:13 ip-172-31-42-243 systemd[1]: Reloading.
```
 
**Validation Results:**
- rke2 version used for validation:

```
rke2 version v1.25.0-rc5+rke2r1 (e0608f3fad96143de5af9ed14dac20ed45574d04)
go version go1.19 X:boringcrypto
```
 

- Logs shows
```
# journalctl --system --no-pager -n 20 | grep Reloading
# 
```
