### ISSUE TITLE
Update images to use BCI

### ISSUE THREAD

**Issue by brooksn** [rancher/rke2#3260]
All chart images and images containing runtime components that are now based on UBI should be based on SUSE BCI.

### Image conversion
<details>
  <summary>Test build checklist</summary>
  
[Expanded list of images](https://gist.github.com/brooksn/8066acf781f4c39225676b80e77a8cf7)

The following images should be built for amd64 and s390x, and pushed to https://hub.docker.com/u/bcibase:

- [x] hardened-kubernetes
- [x] hardened-coredns
- [x] hardened-cluster-autoscaler
- [x] rke2-cloud-provider
- [x] hardened-sriov-network-device-plugin
- [x] hardened-flannel
- [x] hardened-sriov-network-resources-injector
- [x] hardened-etcd
- [x] hardened-sriov-network-webhook
- [x] hardened-sriov-network-config-daemon
- [x] hardened-crictl
- [x] hardened-dns-node-cache
- [x] hardened-sriov-cni
- [x] hardened-sriov-network-operator
- [x] hardened-k8s-metrics-server
- [x] hardened-runc
- [x] hardened-containerd
- [x] hardened-cni-plugins
- [x] hardened-whereabouts
- [x] hardened-ib-sriov-cni
- [x] hardened-calico
- [x] nginx-ingress-controller
- [x] hardened-multus-cni

</details>

#### Image build pull requests

- https://github.com/rancher/image-build-calico/pull/32
- https://github.com/rancher/image-build-cni-plugins/pull/13
- https://github.com/rancher/image-build-containerd/pull/23
- https://github.com/rancher/image-build-coredns/pull/17
- https://github.com/rancher/image-build-crictl/pull/11
- https://github.com/rancher/image-build-dns-nodecache/pull/9
- https://github.com/rancher/image-build-etcd/pull/12
- https://github.com/rancher/image-build-flannel/pull/24
- https://github.com/rancher/image-build-ib-sriov-cni/pull/9
- https://github.com/rancher/image-build-k8s-metrics-server/pull/16
- https://github.com/rancher/image-build-kubernetes/pull/34
- https://github.com/rancher/image-build-multus/pull/15
- https://github.com/rancher/image-build-rke2-cloud-provider/pull/15
- https://github.com/rancher/image-build-runc/pull/12
- https://github.com/rancher/image-build-sriov-cni/pull/10
- https://github.com/rancher/image-build-sriov-network-device-plugin/pull/12
- https://github.com/rancher/image-build-sriov-network-resources-injector/pull/12
- https://github.com/rancher/image-build-sriov-operator/pull/17
- https://github.com/rancher/ingress-nginx/pull/112
- https://github.com/rancher/image-build-whereabouts/pull/4

### Testing

[Test plan](https://confluence.suse.com/display/RKE2/SLE+BCI+Image+Swap+Test+Plan)
- [x] v1.23.12+rke2r1
- [x] v1.24.6+rke2r1
- [x] v1.25.2+rke2r1

<details>
  <summary>registries.yaml</summary>

```yaml
mirrors:
  docker.io:
    rewrite:
      "^rancher/hardened-etcd(.*)": "bcibase/hardened-etcd$1"
      "^rancher/hardened-kubernetes(.*)": "bcibase/hardened-kubernetes$1"
      "^rancher/nginx-ingress-controller(.*)": "bcibase/nginx-ingress-controller$1"
      "^rancher/nginx-ingress-controller-chroot(.*)": "bcibase/nginx-ingress-controller-chroot$1"
      "^rancher/hardened-calico(.*)": "bcibase/hardened-calico$1"
      "^rancher/hardened-sriov-network-resources-injector(.*)": "bcibase/hardened-sriov-network-resources-injector$1"
      "^rancher/hardened-k8s-metrics-server(.*)": "bcibase/hardened-k8s-metrics-server$1"
      "^rancher/hardened-sriov-network-webhook(.*)": "bcibase/hardened-sriov-network-webhook$1"
      "^rancher/hardened-sriov-network-operator(.*)": "bcibase/hardened-sriov-network-operator$1"
      "^rancher/hardened-sriov-network-device-plugin(.*)": "bcibase/hardened-sriov-network-device-plugin$1"
      "^rancher/hardened-flannel(.*)": "bcibase/hardened-flannel$1"
      "^rancher/hardened-crictl(.*)": "bcibase/hardened-crictl$1"
      "^rancher/hardened-ib-sriov-cni(.*)": "bcibase/hardened-ib-sriov-cni$1"
      "^rancher/hardened-runc(.*)": "bcibase/hardened-runc$1"
      "^rancher/rke2-cloud-provider(.*)": "bcibase/rke2-cloud-provider$1"
      "^rancher/hardened-cni-plugins(.*)": "bcibase/hardened-cni-plugins$1"
      "^rancher/hardened-dns-node-cache(.*)": "bcibase/hardened-dns-node-cache$1"
      "^rancher/hardened-containerd(.*)": "bcibase/hardened-containerd$1"
      "^rancher/hardened-cluster-autoscaler(.*)": "bcibase/hardened-cluster-autoscaler$1"
      "^rancher/hardened-coredns(.*)": "bcibase/hardened-coredns$1"
      "^rancher/hardened-multus-cni(.*)": "bcibase/hardened-multus-cni$1"
      "^rancher/hardened-whereabouts(.*)": "bcibase/hardened-whereabouts$1"
      "^rancher/hardened-sriov-cni(.*)": "bcibase/hardened-sriov-cni$1"
      "^rancher/hardened-sriov-network-config-daemon(.*)": "bcibase/hardened-sriov-network-config-daemon$1"
```
</details>

## Updating RKE2

#3407
#3408
#3409

**Comment by dereknola** [comment]
Looks like some of the builds can't find the image, such as https://github.com/rancher/image-build-calico/pull/31

**Comment by rancher-max** [comment]
I validated the multus bumps here using release-1.25 branch commitids, so I am going to close this issue. The other images have previously been validated in all branches. We still need to complete https://github.com/rancher/rke2/issues/3564 in a separate effort, but as far as I am concerned, this issue is complete.
