### ISSUE TITLE
Static Pod Annotation and Label Customizations

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#3266]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add annotations and/or labels to the static pod manifests that are created by the server and agent.

**Describe the solution you'd like**
Server and Agent flag/config option to add extra annotations and labels to the generated static pod manifests

**Describe alternatives you've considered**
None, since the server and agent overwrite them each time it is restarted.

**Additional context**
The main reason we are looking at doing this is to add annotations to enable auto discovery of pods from our monitoring agent.

**Comment by brandond** [comment]
Do you need to add arbitrary labels and annotations to individual static pods, or would you want them added to **all** static pods? Is this the only solution that will allow your monitoring tool to monitor the static pods?

**Comment by mitchellmaler** [comment]
@brandond Each static pod would need different values, such telling it the etcd pod should use the etcd integration and kube-proxy should use the kube-proxy integration.

Currently, it installs an agent on each node and then uses autodisovery to figure out what is running on that node. I might be able to cut up the deployment so that way I enable the different integrations on their respective nodes but if I were able to set different annotations on each static pod manifests it would make it easier.

**Comment by brandond** [comment]
That sounds somewhat complicated; don't the pods already contain sufficient fields (such as the name) to uniquely identify which component they're hosting such that your agent could match the appropriate integration?

**Comment by mitchellmaler** [comment]
I am using DataDog and here is the documentation around the etcd integration for example.
https://docs.datadoghq.com/integrations/etcd/?tab=containerized
It says in a containerized environment to use the auto discovery, which is just providing annotations to the pods. 
https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2

The other control-plane components follow a similar manner.

I do agree if it was able to autodiscover based on the standard labels/annotations that would be nice.

I think manually enabling it _should_ work, and I have sent a request to them asking the best way forward if I am unable to modify the static pod manifests.

**Comment by brandond** [comment]
I would vote against adding the ability to inject arbitrary labels and annotations into the static pod config. We already added a bunch of extra fields to allow for configuring static pod resources, and this would further bloat things for minimal gain. I believe the datadog configuration should be able to be modified to understand the existing metadata on the static pods.

**Comment by caroline-suse-rancher** [comment]
Closing for now - can reopen if we choose to pursue this
