### ISSUE TITLE
Support CIS Kubernetes 1.20/1.23 Benchmarks

### ISSUE THREAD

**Issue by bdun1013** [rancher/rke2#3268]
**Is your feature request related to a problem? Please describe.**

The CIS Kubernetes 1.6 benchmark is meant for Kubernetes 1.16 - 1.18. There is a CIS Kubernetes 1.20 benchmark for 1.19 - 2.20 and a CIS Kubernetes 1.23 benchmark for 1.23+.

It looks like cis-1.23 scans are available in the [rancher-cis-benchmark v2.1.0 Helm Chart](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.1.0/templates/benchmark-cis-1.23.yaml), which uses [v1.0.9 of the Rancher cis-operator](https://github.com/rancher/cis-operator/tree/v1.0.9). 

[cis-1.23 scans were successfully run using Rancher v2.6.7 on RKE2 clusters](https://github.com/rancher/cis-operator/issues/153#issuecomment-1194007760), but the ability to harden your RKE2 cluster in accordance to the 1.20 and 1.23 benchmarks is not clear.

**Describe the solution you'd like**

It would be nice if there was support for the `cis-1.20` and `cis-1.23` values, in addition to the already supported `cis-1.5` and `cis-1.6` values, for the `--profile` flag of the [rke2 server](https://docs.rke2.io/install/install_options/server_config/) and [rke2 agent](https://docs.rke2.io/install/install_options/linux_agent_config/) commands.

**Describe alternatives you've considered**

Just use the `cis-1.6` profile for passing CIS Kubernetes 1.23 benchmark scans.

**Additional context**

I'm not intimately familiar with how the hardening works, but it looks like [Pod Security Policies (PSPs) are created](https://github.com/rancher/rke2/blob/master/pkg/rke2/psp_templates.go). PSPs were deprecated in Kubernetes 1.21 and [were just removed in Kubernetes 1.25](https://kubernetes.io/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/#podsecuritypolicy-removal). This may be an issue for the eventual initial RKE2 1.25 release.

**Comment by dasMulli** [comment]
Looks like #3282 added cis-v1.23 (/cc @galal-hussein)
