### ISSUE TITLE
Update Calico to 3.23.3

### ISSUE THREAD

**Issue by ruslanloman** [rancher/rke2#3285]
Hi everyone!

**Is your feature request related to a problem? Please describe.**

There is a bug with ip_autodetection mode "k8s-internal-ip" in calico 3.23.1 https://github.com/projectcalico/calico/issues/6142 and it was fixed in 3.23.2 version https://github.com/projectcalico/calico/pull/6228

**Describe the solution you'd like**

Update calico to v3.23.3

**Describe alternatives you've considered**

**Additional context**

I've created appropriate PR into rke2-charts repo https://github.com/rancher/rke2-charts/pull/283

**Comment by mdrahman-suse** [comment]
https://github.com/rancher/rke2/issues/3337
