### ISSUE TITLE
Discovered bug in cilium preflight charts

### ISSUE THREAD

**Issue by mallardduck** [rancher/rke2#3288]
**Environmental Info:**
RKE2 Version: n/a
Node(s) CPU architecture, OS, and Version:  n/a
Cluster Configuration: n/a

**Describe the bug:**
Within the daemonset for the cilium preflight charts, currently there is an additional `| quote` in the image source.
This is causing the helm charts/templates to fail parsing.

See here:
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-cilium/rke2-cilium/1.11.502/templates/cilium-preflight/daemonset.yaml#L38

**Steps To Reproduce:**
Attempt to run the deployment with `preflight.enabled=true`.

**Expected behavior:**
The helm operation should complete and the templates render as expected.

**Actual behavior:**
Getting an error in helm about failure to parse Yaml/JSON.

**Additional context / logs:**
```
Error: YAML parse error on rke2-cilium/templates/cilium-preflight/daemonset.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 18: did not find expected key
YAML parse error on rke2-cilium/templates/cilium-preflight/daemonset.yaml
```

This bug was fixed in this PR on the `rke2-charts`: https://github.com/rancher/rke2-charts/pull/284

**Comment by est-suse** [comment]
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted

*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-1-52 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Cluster Configuration:
3 servers - 1 agent
<img width="799" alt="image" src="https://user-images.githubusercontent.com/106194120/189971060-6b65038c-9a97-40d8-a057-11fc86ad8654.png">
