### ISSUE TITLE
Clean install RKE2 containers stuck on containercreating

### ISSUE THREAD

**Issue by Syntax3rror404** [rancher/rke2#3290]
**Environmental Info:**
RKE2 Version: 
v1.24.4+rke2r1 also tested with v1.23.10+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux rancher 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

singlenode to control downstream clusters with default config

**Describe the bug:**

cert-manager pods stuck on containercreating) on v1.23.10+rke2r1
v1.23.10+rke2r1 stuck on nginx-ingress controller install

**Steps To Reproduce:**

- Installed RKE2 with: curl -sfL https://get.rke2.io | sh -
- start rke2 service with: systemctl enable rke2-server.service
- install cert-manager (error starting here with v1.24.4+rke2r1  cert-manager pods stuck on containercreating) on v1.23.10+rke2r1 no probs
- install rancher with helm (not possible with v1.24.4+rke2r1 because cert-manager missing, v1.23.10+rke2r1 nginx-ingress pod also stuck at containercreating)

**Expected behavior:**

nginx-ingress and cert-manger do not stuck at containercreating like on 1.22 rke2

**Actual behavior:**

v1.24.4+rke2r1 stuck on certmanager install 
v1.23.10+rke2r1 stuck on nginx-ingress controller install
v1.22.x working

**Additional context / logs:**

`Error from server (BadRequest): container "rke2-ingress-nginx-controller" in pod "rke2-ingress-nginx-controller-d677p" is waiting to start: ContainerCreating`

**Comment by brandond** [comment]
Can you attach the RKE2 journald logs, as well as the containerd log at `/var/lib/rancher/rke2/agent/containerd/containerd.log`?

**Comment by Syntax3rror404** [comment]
`/var/lib/rancher/rke2/agent/containerd/containerd.log` says iptables is missing. Now it works! Thank you :)
