### ISSUE TITLE
Helm chart for push proxy (support for Rancher monitoring v2)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#33]

**Comment by cjellick** [comment]
This came out of our discussion for "monitoring V2", which (Arvind) @aiyengar2 is working on. When we pick this up, reach out to him.

It refers to this proejct:
https://github.com/prometheus-community/PushProx

This is how we will get metrics data out of etcd and into Prometheus. Arvid is going to write the chart that can deploy pushProx for RKE1, but we'll need to fork that chart and adapt it for rke2.

**Comment by rancher-max** [comment]
Overall monitoring is okay. See https://github.com/rancher/rke2/issues/277 for remaining issue that came from this

**Comment by rancher-max** [comment]
Closing in favor of the above mentioned issue.
