### ISSUE TITLE
[release-1.23] Bump runc version

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3306]
Backport to `release-1.23`:
* #3304

**Comment by bguzman-3pillar** [comment]
### Validated on `v1.23.11-rc1+rke2r1`
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
  
*Cluster Configuration:*

```
1 server
```
  
## Testing Steps

1. Install RKE2 `sudo curl -sfL https://get.rke2.io/ | sudo INSTALL_RKE2_VERSION=v1.23.11-rc1+rke2r1 sh -`
2. Check the runc version using this command `runc --version`
   
**Validation Results:**

- runc version `1.1.4` is showed!
```
$ runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.16.10b7
libseccomp: 2.5.1


$ kubectl get node -A -o wide
NAME               STATUS   ROLES                       AGE     VERSION           INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-42-169   Ready    control-plane,etcd,master   3m39s   v1.23.11+rke2r1   172.31.42.169   <none>        Ubuntu 22.04 LTS   5.15.0-1011-aws   containerd://1.5.13-k3s1
```
