### ISSUE TITLE
Can't join the server (HA control plane)

### ISSUE THREAD

**Issue by xokaido** [rancher/rke2#3309]
Hello,
We're getting `TLS handshake error from 127.0.0.1:35906: remote error: tls: bad certificate`

Our configuration is like this:

Server 1:
```
token: secrettoken
tls-san:
        - K8S-SERVER-0
        - K8S-SERVER-1
        - K8S-SERVER-2
        - 10.18.3.10
        - 10.18.3.11
        - 10.18.3.12
        - 127.0.0.1
        - localhost
node-ip: 10.18.3.10
write-kubeconfig-mode: "0644"
```

And Server 2:

```
server: https://10.18.3.10:9345
token: secrettoken
tls-san:
        - K8S-SERVER-0
        - K8S-SERVER-1
        - K8S-SERVER-2
        - 10.18.3.10
        - 10.18.3.11
        - 10.18.3.12
        - 127.0.0.1
        - localhost
node-ip: 10.18.3.11
write-kubeconfig-mode: "0644"
```

The first server runs fine without any issues but the second server throws this error:
( `rke2 server --debug` )

```
INFO[0180] Waiting for API server to become available
INFO[0180] Waiting for API server to become available
INFO[0181] Cluster-Http-Server 2022/09/02 08:30:38 http: TLS handshake error from 127.0.0.1:35900: remote error: tls: bad certificate
DEBU[0181] Wrote ping
INFO[0181] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
INFO[0186] Cluster-Http-Server 2022/09/02 08:30:43 http: TLS handshake error from 127.0.0.1:35906: remote error: tls: bad certificate
DEBU[0186] Wrote ping
INFO[0186] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
```

Can anyone point us to the right direction?
Thanks in advance.

**Comment by brandond** [comment]
Can you attach the complete journald logs from the `rke2-server` unit, as well as anything you find in `/var/log/pods`?

**Comment by xokaido** [comment]
@brandond  Actually, from the logs it was saying we need to remove some files. I removed all those files and now we're getting different error, which is related to the CA authority: https://clbin.com/s1pCJ

**Comment by brandond** [comment]
The logs for the second server indicate that it was initially started up without the `server` value configured, and started a second single-node cluster:
```
Sep 01 15:50:31 K8S-SERVER-1 rke2[4052]: time="2022-09-01T15:50:31Z" level=info msg="Managed etcd cluster initializing"
Sep 01 15:50:32 K8S-SERVER-1 rke2[4052]: time="2022-09-01T15:50:32Z" level=info msg="Starting etcd for new cluster"
```

Given that, it would make sense that you've got errors after restarting with --server set to join an existing cluster. I would recommend starting over on this node - uninstall RKE2, delete the node from the cluster, and ensure that it is properly configured before starting the service next time.

**Comment by xokaido** [comment]
@brandond Thank you, the fresh installation doesn't have any problems.
