### ISSUE TITLE
Etcd Arg configuration does not take effect

### ISSUE THREAD

**Issue by zuocg** [rancher/rke2#3314]
**Environmental Info:**
RKE2 Version: v1.24.4+rke2r1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

When etcd arg is passed in config, the parameters will not be captured in the rke2 log, and restarting the rke2 service will not take effect
cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
etcd-arg: "quota-backend-bytes=4294967296"
kube-apiserver-extra-env: "TZ=Asia/Shanghai"
kube-scheduler-extra-env: "TZ=Asia/Shanghai"
kube-controller-manager-extra-env: "TZ=Asia/Shanghai"
kube-proxy-extra-env: "TZ=Asia/Shanghai"
etcd-extra-env: "TZ=Asia/Shanghai"
etcd-extra-mount: "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"

systemctl restart rke2-server

**Expected behavior:**

The etcd container yaml file should see the new parameters added to etcd

**Actual behavior:**

The etcd container yaml file should see the new parameters added to etcd, but the actual yaml file does not see the new parameters
**Additional context / logs:**

9月 05 14:54:05 k8s-etcd-1 rke2[1906]: {"level":"info","ts":"2022-09-05T14:54:05.021+0800","caller":"etcdserver/quota.go:94","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}

**Comment by brandond** [comment]
> `k8s-etcd-1 rke2[1906]: {"level":"info","ts":"2022-09-05T14:54:05.021+0800","caller":"etcdserver/quota.go:94","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}`

You're looking at the logs from the embedded etcd instance that's started up temporarily to extract the bootstrap data. For the actual etcd that is run to host the cluster datastore, look at the etcd pod logs.

> the actual yaml file does not see the new parameters

I don't believe that's true. Can you show the etcd static pod content?

**Comment by zuocg** [comment]
![image](https://user-images.githubusercontent.com/88480631/188417625-2d25036e-addb-4d3b-9be7-dd0c60ebcea8.png)

**Comment by brandond** [comment]
Your  `TZ=Asia/Shanghai` environment variable is there, and I believe you'll see that the mount is listed further towards the bottom of the file. What did you see that made you think it wasn't taking effect?
