### ISSUE TITLE
RKE2 Cluster reset failure with error in kubelet_volumes.go:225

### ISSUE THREAD

**Issue by shan100github** [rancher/rke2#3315]
**Environmental Info:**
RKE2 Version: 
v1.21.5+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux svmaster 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Baremetal environment
1-Server
6-Agents

**Describe the bug:**
Currently, the cluster is in 10.x.x.x/24 physical network. And the physical network is moved to 172.x.x.x/24, In order to bring back the cluster, performed the below operation.
- stopped all rke2-server and rke2-agent services in all nodes.
- execute rke2-kill.sh in server node
- `rke2 server --cluster-reset`

Fails to perform cluster-reset due to many errors like`kubelet_volumes.go:225] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"1b2f7d9c-627f-4a2c-a601-e50d8bbd1cce\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/1b2f7d9c-627f-4a2c-a601-e50d8bbd1cce/volumes/kubernetes.io~configmap/istiod-ca-cert: directory not empty" numErrs=19`

It might be related to https://github.com/kubernetes/kubernetes/issues/105536

**Expected behavior:**
All pods in `/var/lib/kubelet/pods/` should have been cleaned up and cluster reset completes successfully.

**Actual behavior:**
Cluster reset failure

**Additional context / logs:**

[cluster-reset-failure-server.log](https://github.com/rancher/rke2/files/9491767/cluster-reset-failure-server.log)

**Comment by brandond** [comment]
Closing this out in favor of tracking this via the upstream Kubernetes issue https://github.com/kubernetes/kubernetes/issues/105536.

Note that this seems to be triggered by mounting external storage (NFS, EBS, Longhorn) volumes into the cluster, which the kubelet cannot unmount and clean up properly. Manually unmounting the volumes and cleaning up the filesystem seems to be required.

**Comment by kkmaslowski** [comment]
@brandond I have the same problem. I don't see any mounted volumes. Should I manually remove contents of /var/lib/kubelet/pods/*/volumes/ directories? Or delete all pods in /var/lib/kubelet/pods/*?

```
E1109 09:55:18.831421   13909 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"9ef02bc6-3568-40d0-911b-c955c518809b\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/9ef02bc6-3568-40d0-911b-c955c518809b/volumes/kubernetes.io~configmap/flannel-cfg: directory not empty" numErrs=9
E1109 09:55:20.832242   13909 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"9ef02bc6-3568-40d0-911b-c955c518809b\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/9ef02bc6-3568-40d0-911b-c955c518809b/volumes/kubernetes.io~configmap/flannel-cfg: directory not empty" numErrs=9
E1109 09:55:22.832931   13909 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"9ef02bc6-3568-40d0-911b-c955c518809b\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/9ef02bc6-3568-40d0-911b-c955c518809b/volumes/kubernetes.io~configmap/flannel-cfg: directory not empty" numErrs=9
E1109 09:55:24.831108   13909 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"9ef02bc6-3568-40d0-911b-c955c518809b\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/9ef02bc6-3568-40d0-911b-c955c518809b/volumes/kubernetes.io~configmap/flannel-cfg: directory not empty" numErrs=9
E1109 09:55:26.832267   13909 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"9ef02bc6-3568-40d0-911b-c955c518809b\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/9ef02bc6-3568-40d0-911b-c955c518809b/volumes/kubernetes.io~configmap/flannel-cfg: directory not empty" numErrs=9
```

**Comment by brandond** [comment]
Yes, as described in the upstream issue, you will need to manually clean up the contents of the directories that it complains about wanting to `rmdir` before the kubelet will be able to continue.
