### ISSUE TITLE
want to use '--cloud-controller-manager-image' option

### ISSUE THREAD

**Issue by oingooing** [rancher/rke2#3335]
### Versions
**rancher** :  v2.6.7
**cluster** : v1.24.4+rke2r1

---

hi, i want to use '--cloud-controller-manager-image' option.
there are image override options in server configuration reference [here](https://docs.rke2.io/install/install_options/server_config/#rke2-server-cli-help),

but '--cloud-controller-manager-image' option is not exist there and also does not work.

i need to change cloud controller manager image and version because rebuild by adding only the loadbalancer function to rke2 ccm.

is it possible to add feature or is there any other way to override cloud controller manager image?

thank you.

**Comment by brandond** [comment]
> but '--cloud-controller-manager-image' option is not exist there and also does not work.

You are correct, there is code to configure it, but not to override the image. That was an oversight.

> i need to change cloud controller manager image and version because rebuild by adding only the loadbalancer function to rke2 ccm.

Can you explain more about what you've done to enable the loadbalancer functionality in your rebuilt RKE2 CCM? The K3s/RKE2 stub cloud controller only has code to set addresses and clear the unintialized taint; I'm curious what you added to enable LoadBalancer functionality. Do you have a PR open for this change? We have some long-term plans to integrate ServiceLB/KlipperLB into the cloud controller, but haven't yet prioritized that work.

**Comment by oingooing** [comment]
hi. we have private cloud solution and it has own loadbalancer services. (does not have instance solution only loadbalancer)
i want to create "LoadBalancer Type Service" in rke2 cluster, so i implemented own ccm. (--cloud-provider=oing)

i found the problem that we can use only one ccm in k8s.
already exist rke2 ccm in cluster, so my ccm didn't register in k8s provider.

fortunately, rke2 cloud controller manager implemented only Instances interface. [here](https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/instances.go)
I copied that code and merged my cloud provider code. rebuild used [image-build-rke2-cloud-provider](https://github.com/rancher/image-build-rke2-cloud-provider)

i do not have PR open, because this is all I need.

if i can use '--cloud-controller-manager-image' option, It is perfect.

**Additional Question**

> The K3s/RKE2 stub cloud controller only has code to set addresses and clear the unintialized taint; 

i can disable rke2 cloud controller manager when create cluster. is it ok to create cluster? i can't predict its impact.

thank you for answer.

**Comment by brandond** [comment]
Yes, if you want to deploy another cloud provider, you are intended to use the `--disable-cloud-controller` option, and manage your own cloud controller deployment (as is usually done for AWS, GKE, Azure, and so on). It was not our intent to allow swapping out different cloud providers by changing the image for the built-in CCM.

**Comment by oingooing** [comment]
ok, i understand your intend.
I will close this issue.
thank you for answer.
