### ISSUE TITLE
[process][feature] assert control plane components are statically built artifacts

### ISSUE THREAD

**Issue by dweomer** [rancher/rke2#335]
Review the control-plane components and apply build-time assertions:
- `ldd` gets you "not a dynamic executable"
- `go tool nm` gets you `*_Cfunc__goboringcrypto_*` symbols where appropriate, prior to stripping. see https://kupczynski.info/2019/12/15/fips-golang.html#build-process

If the component is built from a separate repository the assertion(s) should be made there at build-time:
- [x] etcd :arrow_right: https://github.com/rancher/image-build-etcd/pull/2
  - etcdctl
- [x] metrics-server :arrow_right: https://github.com/rancher/image-build-k8s-metrics-server/pull/1
- [x] coredns :arrow_right: https://github.com/rancher/image-build-coredns/pull/2
- [x] kube-proxy :arrow_right: https://github.com/rancher/image-build-kube-proxy/pull/4
- [x] calico :arrow_right: https://github.com/rancher/image-build-calico/pull/3
- [x] flannel :arrow_right: https://github.com/rancher/image-build-flannel/pull/4
- [x] crictl :arrow_right: https://github.com/rancher/image-build-crictl/pull/1
- [x] containerd :arrow_right: https://github.com/rancher/image-build-containerd/pull/4
  - ctr
  - containerd
  - containerd-shim
  - containerd-shim-runc-v1
  - containerd-shim-runc-v2
- [x] runc :arrow_right: https://github.com/rancher/image-build-runc/pull/1
- [x] kubernetes :arrow_right: https://github.com/rancher/rke2/pull/352
  - kubelet
  - kubectl
  - kube-apiserver
  - kube-scheduler
  - kube-controller-manager
- [x] rke2 :arrow_right: https://github.com/rancher/rke2/pull/352

**Comment by davidnuzik** [comment]
QA Smoke test, ensure we didn't break anything obvious. Can do some automation checks as you see fit.

**Comment by rancher-max** [comment]
Validated using `v1.18.9-beta21+rke2` not seeing any regressions through smoke tests and automation.
