### ISSUE TITLE
Documentation should reflect changes in CIS Profile Flags with RKE 1.25

### ISSUE THREAD

**Issue by brownz11** [rancher/rke2#3353]
It looks for RKE 1.25 the accepted values for profile have been updated from ["cis-1.5","cis-1.6"] to ["cis-1.23"] (specifically in commit https://github.com/rancher/rke2/commit/68e5e0cccf170c61bda3c4a5356d3b59f490ab61)

The documentation for RKE2 should be updated to reflect the new acceptable values in RKE 1.25, it may also be beneficial to include a blurb to this effect in release notes.

**Comment by brandond** [comment]
cc @galal-hussein @cwayne18 - I agree that this is something we probably should have called out in the release notes (and docs) as a breaking change. Can we get that updated?

**Comment by galal-hussein** [comment]
@brownz11 Thanks for opening the issue, I edited the release notes to reflect that change https://github.com/rancher/rke2/releases/tag/v1.25.0%2Brke2r1 and I am working on updating the documentation which will include the changes to the profile flag and also the new edits to the cis benchmarks
