### ISSUE TITLE
Canal CNI fails and leaks pod IPs when iptables not installed on nodes

### ISSUE THREAD

**Issue by zanewgray** [rancher/rke2#3361]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.25.0+rke2r1 (46eaa13645d504c851173a9e59783d21bde1b01d)
go version go1.19 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Node 1: Linux rancher-mngt-01 5.4.0-1074-kvm #79-Ubuntu SMP Mon Aug 15 18:41:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Node 2: Linux rancher-mngt-02 5.4.0-1074-kvm #79-Ubuntu SMP Mon Aug 15 18:41:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Node 3: Linux rancher-mngt-03 5.4.0-1074-kvm #79-Ubuntu SMP Mon Aug 15 18:41:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 node RKE2 cluster running on Ubuntu cloud Focal Fossa (patched) on a Harvester 1.0.3 virtualization environment.  Underlying hardware is Dell PowerEdge R740XD (3 each).

**Describe the bug:**
On a fresh RKE2 HA cluster, the rke2-nginx-ingress-controller hangs at a status of "ContainerCreating".  Checking the logs, the nginx pods initially show an error: 

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1f7cb22eaaf84e37e9706c43b6483460b6d5da3786456ac53cfc821b0914cc3d": plugin type="portmap" failed (add): failed to open iptables: exec: "iptables": executable file not found in $PATH"

The nginx pod will then recreate, but the pod IP address does not appear to be released from the /var/lib/cni/networks/k8s-pod-network directory.  Eventually, all 255 available IPs will be consumed, as the Canal CNI does not appear to release them, and the nginx pods are never successfully deployed due to the "'iptables': executable file not found in $PATH" issue.

**Steps To Reproduce:**
1. Deploy three copies of the latest nightly build of Focal Fossa (Ubuntu 20.02) cloud image to a VM environment.  In my case, I deployed onto harvester using the following cloud-config:

#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
password: mypassword
chpasswd: { expire: False }
ssh_pwauth: True

2. Install apt-utils on each VM using "sudo apt install apt-utils"
3. Install nano on each VM using "sudo apt install nano"
4. Set the root password on each VM using "sudo passwd root"
5. Modify each VM's NetworkManager settings (see the issues section of the official RKE docs):
sudo mkdir -p /etc/NetworkManager/conf.d/
sudo touch /etc/NetworkManager/conf.d/rke2-canal.conf
sudo nano /etc/NetworkManager/conf.d/rke2-canal.conf
! add the following to the rke2-canal.conf

[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:flannel*
 
! save the yaml

6. Modify Wicked network settings on each VM (see the issues section of the official RKE docs):
sudo touch /etc/sysctl.d/90-rke2.conf
!
sudo nano /etc/sysctl.d/90-rke2.conf
! add the following to the 90-rke2.conf file

net.ipv4.conf.all.forwarding=1

! save the yaml

7. Patch each VM and reboot:
sudo apt update
sudo apt upgrade
sudo reboot

8. Modify hosts file entries to point to the first RKE2 node.  NOTE: I am using DNS round robin to load balance to the three nodes, and this is required temporarily to get these 

sudo nano /etc/hosts
(add whatever IP and name is appropriate for the first RKE2 node)

9.  su to root and run the RKE2 install script:

su root
curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=stable INSTALL_RKE2_VERSION="v1.25.0+rke2r1" sh -

(NOTE: I attempted with both 1.24 and the 1.25 version with the same results)

10.  Configure the token and TLS names on the first RKE node (as root):

mkdir -p /etc/rancher/rke2/
touch /etc/rancher/rke2/config.yaml
!
nano /etc/rancher/rke2/config.yaml
! add the following to the config.yaml

write-kubeconfig-mode: "0644"
token: <mytoken>
tls-san:
  - <load balanced cluster dns name>
  - <local VM dns name>
  - <local VM IP>
 
! save the yaml

11.  Configure the token and TLS for the other two nodes:

mkdir -p /etc/rancher/rke2/
touch /etc/rancher/rke2/config.yaml
!
nano /etc/rancher/rke2/config.yaml
! add the following to the config.yaml

write-kubeconfig-mode: "0644"
server: https://<load balanced dns name>:9345
token: <mytoken>
tls-san:
  - <load balanced cluster dns name>
  - <local VM dns name>
  - <local VM IP>
 
! save the yaml

12.  Start the RKE2 service on all three nodes:

systemctl enable rke2-server.service
systemctl start rke2-server.service

13.  Go get some coffee (you earned it!) and wait awhile.

14.  Export the kube config on each node so you can use kubectl:

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin

15.  On the first, run "kubectl get pods --all-namespaces" and note the status of the rke2-nginx-ingress-controller pods:

NAMESPACE     NAME                                                   READY   STATUS              RESTARTS        AGE
kube-system   cloud-controller-manager-rancher-mngt-01               1/1     Running             3 (8m14s ago)   14m
kube-system   cloud-controller-manager-rancher-mngt-02               1/1     Running             2 (7m2s ago)    12m
kube-system   cloud-controller-manager-rancher-mngt-03               1/1     Running             0               11m
kube-system   etcd-rancher-mngt-01                                   1/1     Running             0               13m
kube-system   etcd-rancher-mngt-02                                   1/1     Running             0               12m
kube-system   etcd-rancher-mngt-03                                   1/1     Running             0               12m
kube-system   helm-install-rke2-canal-87gg4                          0/1     Completed           0               13m
kube-system   helm-install-rke2-coredns-j7lww                        0/1     Completed           0               13m
kube-system   helm-install-rke2-ingress-nginx-gtq5m                  0/1     Completed           0               13m
kube-system   helm-install-rke2-metrics-server-5v6ws                 0/1     Completed           0               13m
kube-system   kube-apiserver-rancher-mngt-01                         1/1     Running             0               14m
kube-system   kube-apiserver-rancher-mngt-02                         1/1     Running             0               12m
kube-system   kube-apiserver-rancher-mngt-03                         1/1     Running             0               12m
kube-system   kube-controller-manager-rancher-mngt-01                1/1     Running             2 (10m ago)     13m
kube-system   kube-controller-manager-rancher-mngt-02                1/1     Running             2 (8m26s ago)   12m
kube-system   kube-controller-manager-rancher-mngt-03                1/1     Running             0               11m
kube-system   kube-proxy-rancher-mngt-01                             1/1     Running             0               14m
kube-system   kube-proxy-rancher-mngt-02                             1/1     Running             0               12m
kube-system   kube-proxy-rancher-mngt-03                             1/1     Running             0               11m
kube-system   kube-scheduler-rancher-mngt-01                         1/1     Running             2 (10m ago)     13m
kube-system   kube-scheduler-rancher-mngt-02                         1/1     Running             2 (8m20s ago)   12m
kube-system   kube-scheduler-rancher-mngt-03                         1/1     Running             0               11m
kube-system   rke2-canal-7qhgq                                       2/2     Running             0               11m
kube-system   rke2-canal-blrwh                                       2/2     Running             0               11m
kube-system   rke2-canal-sd2s2                                       2/2     Running             0               11m
kube-system   rke2-coredns-rke2-coredns-75b444678c-2fknz             1/1     Running             0               11m
kube-system   rke2-coredns-rke2-coredns-75b444678c-pbkdk             1/1     Running             0               6m56s
kube-system   rke2-coredns-rke2-coredns-autoscaler-bf4dcf6d6-xjkpz   1/1     Running             0               11m
kube-system   rke2-ingress-nginx-controller-knkvl                    0/1     ContainerCreating   0               5m12s
kube-system   rke2-ingress-nginx-controller-lmt8l                    0/1     ContainerCreating   0               5m12s
kube-system   rke2-ingress-nginx-controller-njlh7                    0/1     ContainerCreating   0               5m12s
kube-system   rke2-metrics-server-597c4c8c8b-d5s6g                   1/1     Running             0               6m42s

16.  Check the events of the rke2-ingress-nginx-controller pod (I exported the kubeconfig to Lens to find this error in the events):

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1f7cb22eaaf84e37e9706c43b6483460b6d5da3786456ac53cfc821b0914cc3d": plugin type="portmap" failed (add): failed to open iptables: exec: "iptables": executable file not found in $PATH

17.  Check the "/var/lib/cni/networks/k8s-pod-network" directory.  Repeat this, and watch the directory slowly fill on all three VMs until the IP block is exhausted.

ls /var/lib/cni/networks/k8s-pod-network

18.  Once all IPs have been exhausted, re-check the events of the rke2-ingress-nginx-controller pods (I exported the kubeconfig to Lens to find this error in the events).  Note that the errors now include:

failed to allocate for range 0: no IP addresses available in range set

19.  The ingress controller will never complete the installation.

**Expected behavior:**
The rke2-nginx-ingress-controller pods should complete their installation and the cluster should be operational.

**Actual behavior:**
The rke2-nginx-ingress-controller pods are hung at a status of "ContainerCreating"

**Additional context / logs:**

**Comment by brandond** [comment]
It does not depend on firewalld. Firewalld is in fact not supported alongside RKE2; we require that it be disabled.

The canal CNI's portmap plugin is, however, dependent on your host having the `iptables` package installed, in either legacy or NFT mode:
`plugin type="portmap" failed (add): failed to open iptables: exec: "iptables": executable file not found in $PATH`

**Comment by brandond** [comment]
cc @cwayne18 because he loves Ubuntu stuff.

**Comment by brandond** [comment]
Also cc @manuelbuil and @rbrtbnfgl in case something has changed on the canal side - this seems to be popping up more frequently, and I don't think it's due to vendors dropping packages. I suspect maybe this requirement is new?

**Comment by lapawa** [comment]
My rke2 installation failed with the same issue on bare metal network installed Debian 11. Adding package iptables while installing fixed it.  
d-i pkgsel/include string openssh-server curl iptables

**Comment by rbrtbnfgl** [comment]
If you are using debian from debian 11 they decided to use nftables instead of iptables by default. I think that all the other OS debian based will use the same approach.

**Comment by brandond** [comment]
Nftables should work, as long as the iptables-nft package is installed, right? It just needs an iptables binary, it doesn't matter if it's legacy or nftables.

**Comment by rbrtbnfgl** [comment]
As I understand nftables replaced iptables entirely on the newer debian versions without iptables-nft.

**Comment by manuelbuil** [comment]
Both Canal and Calico CNI plugins rely on portmap to apply the hostPort functionality. For example in Calico: https://github.com/projectcalico/calico/blob/master/charts/calico/templates/calico-config.yaml#L95-L99

Portmap relies on "github.com/coreos/go-iptables/iptables" https://github.com/containernetworking/plugins/blob/main/plugins/meta/portmap/portmap.go#L26 to implement the hostPort stuff. That library requires iptables userspace binary to be installed (the README explains why it prefers it to nft: https://github.com/coreos/go-iptables/blob/main/README.md).

Therefore, if you use canal or calico and deploy a pod that requires hostPort (e.g. nginx), then iptables userspace binary is a requirement. Cilium is implementing the hostPort functionality using BPF instead, so you don't need iptables to be installed

**Comment by manuelbuil** [comment]
> As I understand nftables replaced iptables entirely on the newer debian versions without iptables-nft.

I installed Debian 11 in Azure and it did not have iptables nor nft
