### ISSUE TITLE
Failed to deploy apiserver pod first restart after `rke2-killall.sh`

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#3364]
**Environmental Info:**
RKE2 Version: v1.24.4+rke2r1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

3 Node all roles

**Describe the bug:**

When using the killall script during encryption key rotation, the first `systemctl restart rke2-server` fails because the apiserver pod is not restarted. Subsequent restarts rectify this, but this is causing issues with rancher integration because it is unknown from the rancher perspective why the `systemctl restart` is taking so long, so there is no option other than to wait for the 30 minute timeout. 

```
Sep 15 17:19:06 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:06Z" level=info msg="Latest etcd manifest deployed"
Sep 15 17:19:06 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:06Z" level=info msg="kube-apiserver pod not found, retrying"
Sep 15 17:19:08 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:08Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 15 17:19:13 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:13Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 15 17:19:18 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:18Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
//...
Sep 15 17:19:26 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:26Z" level=info msg="kube-apiserver pod not found, retrying"
Sep 15 17:19:26 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs rke2[6925]: time="2022-09-15T17:19:26Z" level=fatal msg="Failed waiting for manifests to deploy: timed out waiting for the condition"
Sep 15 17:19:26 auto-jhyde-do-jpykp-pool0-90c1b715-9kwxs systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
```

**Steps To Reproduce:**

- Installed RKE2: Rancher provisioned v1.24.4 
- Begin encryption key rotation sequence
- Elect leader
- Run the following commands on the leader
	- `rke2 secrets-encrypt prepare`
	- `rke2 secrets-encrypt status`
		- run the above command until the expected encryption key rotation stage is returned
- For each node, run the following commands
	- `systemctl is-active rke2-server`
		- Verify output of above command, if not true, wait 10 seconds then try again
	- `rke2-killall.sh`
	- `systemctl restart rke2-server`
	- `rke2 secrets-encrypt status`
		- Run above command until it succeeds
	- Verify that the other nodes have the same encryption key rotation status as the leader.

**Expected behavior:**

After restarting the `rke2-server.service` post `rke2-killall.sh`, the apiserver pod should be deployed and not block the server.

**Actual behavior:**

The apiserver static pod manifest is not deployed, and the `rke2-server.service` has to time out during the `systemctl restart rke2-server` to get it to deploy.

**Additional context / logs:**

So far, this has been narrowed down to the `rke2-killall.sh` script, however we desire the functionality of the killall script during out encryption key rotation process due to how sensitive of an operation it is in an effort to minimize cluster activity during the process.

This issue also likely affects k3s, however v1.24.4+rke2r1 is just the version I found it on.

**Comment by brandond** [comment]
Can you attach logs from rke2-server, kubelet, and containerd showing why the apiserver pod isn't being deployed? You haven't shared enough info here to make a determination, but I suspect you may be running in to https://github.com/rancher/rke2/issues/3315.

**Comment by jakefhyde** [comment]
> I'm confused - you opened this issue against RKE2, and K3s doesn't uses static pods to run components so I'm not sure how K3s could be affected. What are you trying to say here?

Copied the same sentence from a k3s issue I was opening and forgot to flip the versions, updated

**Comment by jakefhyde** [comment]
Closing this issue as rancher has migrated away from using the killall script.
