### ISSUE TITLE
RKE2 windows container create failed

### ISSUE THREAD

**Issue by bangzhuzhu** [rancher/rke2#3368]
**Environmental Info:**
RKE2 Version: 

linux：
rke2 version v1.24.4+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
windows：
rke2 version v1.24.4+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
Node(s) CPU architecture, OS, and Version: 

linux 
linuxVm7 5.15.0-1019-azure #24~20.04.1-Ubuntu SMP Tue Aug 23 15:52:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

windows server 2022
Cluster Configuration:

1 linux server 1 agent 
**Describe the bug:**

The test deploy is failed and coreDNS is pending.
![image](https://user-images.githubusercontent.com/111118214/191428462-a206c43d-a372-41b8-931b-d99f2ab43204.png)

**Steps To Reproduce:**

Linux: 
1.curl -sfL https://get.rke2.io/ | sh -
2.mkdir -p /etc/rancher/rke2/
3.echo "cni: calico" > /etc/rancher/rke2/config.yaml
4.systemctl enable rke2-server.service
5.systemctl start rke2-server.service

windows:
1. ...some prep as doc
2.  ./install.ps1
3. rke2 agent

linux:
1. kubectl create deployment win --image=mcr.microsoft.com/windows/nanoserver:ltsc2022
2. kubectl create deployment hello --image=hello-world

then 
1. kubectl create deployment hello --image=hello-world (result show above)
2. kubectl get event 
![image](https://user-images.githubusercontent.com/111118214/191429707-744ff94d-876c-499f-b995-5206d06974d3.png)

windows:
ctr container ls:
![image](https://user-images.githubusercontent.com/111118214/191429956-56dadd47-86a3-484a-b6e1-2a333afa326f.png)

**Expected behavior:**

container should be created.
**Actual behavior:**

container can not create

**Additional context / logs:**

**Comment by bangzhuzhu** [comment]
from log : C:\var\lib\rancher\rke2\agent\logs
![image](https://user-images.githubusercontent.com/111118214/191436409-edf61170-1928-4f7b-9f52-34220ec98bad.png)
it's loop to add and remove.

**Comment by bangzhuzhu** [comment]
![image](https://user-images.githubusercontent.com/111118214/191644325-929fa6b7-1b07-468e-84f5-8fb509f4ab66.png)

**Comment by brandond** [comment]
It just looks to me like the pod is crashlooping. What do the pod logs say?

**Comment by bangzhuzhu** [comment]
@brandond nothing if my command is right
![image](https://user-images.githubusercontent.com/111118214/191646039-bdd92990-3406-4865-a9f3-7fccfdfb2d60.png)
