### ISSUE TITLE
Wrong package Vsphere in RKE2 assets

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3377]
**Environmental Info:**

RKE2 Version: 1.24.4+rke2r1
Node(s) CPU architecture, OS, and Version: 3.10.0-1160.71.1.el7.x86_64

**Describe the bug:**
In AirGap Mode,
package vsphere-linux-amd64 is packaged with   docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.0

But RKE2  1.24.4+rke2r1 version are looking for docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1

```
Normal   Pulling           3m46s (x2 over 4m1s)  kubelet  Pulling image "rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1"
  Warning  Failed            3m45s (x2 over 4m1s)  kubelet  Error: ErrImagePull
  Warning  Failed            3m45s                 kubelet  Failed to pull image "rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1": rpc error: code = Unknown desc = failed to pull and unpack image "[docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1]
```

**Steps To Reproduce:**
Download airgap package from https://github.com/rancher/rke2/releases/tag/v1.24.4%2Brke2r1
Do an airgap RKE2 installation  and  set   cloud-provider-name=rancher-vsphere in conffig.yaml

**Expected behavior:**
Provide Vsphere package containing  : docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.5.1

**Comment by brandond** [comment]
Appears that this was broken in https://github.com/rancher/rke2/pull/2755 - the chart version was bumped, but not the images.

**Comment by brandond** [comment]
This will be fixed by https://github.com/rancher/rke2/pull/3356

**Comment by seb-835** [comment]
Thanks @brandond , 
today, in air gap mode, which latest version of rke2 i can use with the correct vsphere package ?

**Comment by brandond** [comment]
v1.23.5. Honestly you're probably better off just using `docker save` to put the correct image in a tarball until we get an update release out.

**Comment by brandond** [comment]
Yes, this issue was reported after we entered code freeze for this month's patch releases. The PR linked above will be merged for our next release cycle.

**Comment by seb-835** [comment]
@brandond 
i see another issue, even if you add the correct vsphere airgap package, it will not be enough.

The DaemonSet  vsphere-csi-node   and Deployment vsphere-csi-deployment  set  by the helmChart 
have some images with  imagePullPolicy set to Always . 

So Kube always try to pull image from registry, and not using the one on node.

**Comment by brandond** [comment]
> The DaemonSet vsphere-csi-node and Deployment vsphere-csi-deployment set by the helmChart
have some images with imagePullPolicy set to Always .

I fixed that as well.

**Comment by seb-835** [comment]
Is it possible to bump version 2.5.3 and 2.6.1  , interesting bug fix when not using default vmware-system-csi namespace.

https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.5/rn/vmware-vsphere-container-storage-plugin-25-release-notes/index.html

**Comment by brandond** [comment]
It is unlikely that will make it into this release cycle, but I will ask the team responsible for maintaining our vsphere charts.

**Comment by brandond** [comment]
We could patch the chart to create that namespace, but I'd prefer to get it updated to the fixed image so that we don't have to deal with the fallout of changing the namespace later on. The vsphere charts team is aware of the ask, if we can't get the update in this week I'll probably revert the PR and just fix the tags for the currently packaged versions.

**Comment by VestigeJ** [comment]
Validated using latest v1.24.7-rc1+rke2r1

$ rke2 -v
```
rke2 version v1.24.7-rc1+rke2r1 (a9d978dbdb5a1f707296df28df7e7eb31c7dd6c2)
go version go1.18.1b7
```

$ wget https://github.com/rancher/rke2/releases/download/v1.24.7-rc1%2Brke2r1/rke2-images-vsphere.linux-amd64.tar.gz

$ sudo mkdir -p /var/lib/rancher/rke2/agent/images/
$ sudo cp rke2-images-vsphere.linux-amd64.tar.gz /var/lib/rancher/rke2/agent/images/

$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh

$ sudo systemctl enable rke2-server --now

# wait for cluster to reach "Ready" state

$ get.images
```
docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver    v2.6.1                         801463495918e       265MB
```
