### ISSUE TITLE
Kubelet configuration option can be set via commandline argument but not in config file

### ISSUE THREAD

**Issue by moio** [rancher/rke2#3378]
**Environmental Info:**
RKE2 Version:

rke2 version v1.23.10+rke2r1 (2616002259455211fb8af2e2eb8f996593c18b86)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 

Linux ip-172-16-1-60.ec2.internal 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

7-node t3.xlarge AWS cluster, 50 GiB EBS gp3 root volume.
3 server nodes and 4 agent nodes.

**Describe the bug:**

Adding kubelet extra arguments via the configuration file seems to be ignored, eg. in `/etc/rancher/rke2/config.yaml`:

```yaml
kubelet-arg: "max-pods=250"
```

Setting kubelet arguments from the command line works as expected. Eg, with `systemd`:

```shell
mkdir -p /etc/systemd/system/rke2-server.service.d/
cat >/etc/systemd/system/rke2-server.service.d/override.conf <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/rke2 server --kubelet-arg=max-pods=250
EOF

systemctl daemon-reload
systemctl restart rke2-server
```

**Steps To Reproduce:**
- edit `/etc/rancher/rke2/config.yaml` to add
```yaml
kubelet-arg: "max-pods=250"
```
- restart rke2-server
- see kubelet commandline arguments from `ps aux`

**Expected behavior:**
`--max-pods=250` is in `ps aux` output.

**Actual behavior:**
`--max-pods=250` is **not** in `ps aux` output.

**Comment by brandond** [comment]
I can't reproduce this if I edit the systemd unit directly. Are you sure your systemd override file is actually being used?

**Comment by brandond** [comment]
I can't reproduce this, kubelet args and all other flags are successfully loaded from the config file when rke2 is restarted.
