### ISSUE TITLE
Support Calico CNI configuration customization in Windows

### ISSUE THREAD

**Issue by olljanat** [rancher/rke2#3380]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use more complex configurations like Calico with BGP and without NAT and with multiple IP pools on RKE2 + Windows + Calico combination.

That is because:
* VXLAN mode is hardcoded https://github.com/rancher/rke2/blob/562228ec09f4c8b7c4a5f6fd1538e9d7f1340417/pkg/windows/calico.go#L164
* Single IP pool mode is hardcoded https://github.com/rancher/rke2/blob/c2aa2dc5671cee04d9d99e358b00f08c63fbe1dd/pkg/windows/templates.go#L14
* Encapsulation is hardcoded https://github.com/rancher/rke2/blob/c2aa2dc5671cee04d9d99e358b00f08c63fbe1dd/pkg/windows/templates.go#L61
* Outgoing NAT is harcoded https://github.com/rancher/rke2/blob/c2aa2dc5671cee04d9d99e358b00f08c63fbe1dd/pkg/windows/templates.go#L47-L54

In additionally it looks to be that even if `C:\var\lib\rancher\rke2\agent\etc\cni\10-calico.conf` file exist it will get replaces by RKE2.

**Describe the solution you'd like**
In minimum it should be possible to create custom `C:\var\lib\rancher\rke2\agent\etc\cni\10-calico.conf` before starting RKE2.

**Describe alternatives you've considered**
Alternatively each setting can be parameterized separately.

**Additional context**

**Comment by manuelbuil** [comment]
Calico supports a very limited amount of options for Windows. Have you tried modifying those parameters and still have a working cluster? If I remember correctly, those values were the only ones working some months ago

**Comment by brandond** [comment]
In particular, see https://projectcalico.docs.tigera.io/getting-started/windows-calico/kubernetes/standard which says:
> Windows can support only a single type of IP pool so it is important that you use only a single VXLAN IP pool in this mode.
> Windows supports only VXLAN on port 4789 and VSID >=4096. Calico’s default (on Linux and Windows) is to use port 4789 and VSID 4096.

I think you'll find that many of the things you might want to configure cannot actually be changed on Windows.

**Comment by olljanat** [comment]
> Calico supports a very limited amount of options for Windows.

Yes, however those looks to be quite well documented to https://projectcalico.docs.tigera.io/getting-started/windows-calico/limitations

> Have you tried modifying those parameters

How I can do that with RKE2? As far I can see it's start overwrites CNI config and Calico does not read changes when it is running.

>  and still have a working cluster?

I actually ended up opposite problem when tried to add Windows workloads to existing BGP only cluster. Windows does not have any connectivity at all, not even gateway responses to ping. Documentation looks to be saying quite clearly that BGP need to be disabled before VXLAN can be used with Windows and that I cannot do without breaking all other use cases.

> I seem to recall that there was some problem with BGP mode such that VXLAN was the only working option.

Now when I'm looking it in more details. There looks to be quite a lot of extra requirement to enable BGP mode in Windows. If you look https://projectcalico.docs.tigera.io/getting-started/windows-calico/quickstart#install (and switch to "Kubernetes BGP" tab), there is that "RemoteAccess" service which need to be installed and configured.

On top of that there must be second `calico-node.exe` process running with `-confd` and it needs quite a lot of configuration which are here https://github.com/projectcalico/calico/tree/master/confd/windows-packaging

> I think you'll find that many of the things you might want to configure cannot actually be changed on Windows.

Yes, I know and that why I have been trying to avoid Windows workloads so far but now we have use case in table where it would be useful.

**Comment by brandond** [comment]
> I have been trying to avoid Windows workloads so far but now we have use case in table where it would be useful.

I would probably try to make your cluster configuration align with our current Windows support requirements, as opposed to trying to get BGP working on Windows. We spent a fair time testing the different options before settling on the current configuration as something we could support.

**Comment by olljanat** [comment]
Actually BGP in Windows with RKE2 and even peering with ToR switches looks to be working fine when I installed second copy of Calico in parallel with PowerShell script mentioned in this section https://projectcalico.docs.tigera.io/getting-started/windows-calico/quickstart#install-calico-for-windows-manually and disabled other parts of it except CalicoConfd service.

Only limitation which I noticed was that there really looks to be only one IP pool limit in Windows, even if `windows_use_single_network` is set to `false` all pods gets IPs from first pool.

> I would probably try to make your cluster configuration align with our current requirements for enabling Windows nodes, as opposed to trying to get BGP working on Windows.

I'm not convinced that VXLAN is good idea on Windows either. I have seen a way too much issues with them with Linux + Windows hybrid Docker Swarms and most of the it is that HNS part which caused problems. That why pure IP traffic without any overlay feels better option. But sure that is very special config which most of the users don't want to use.

Another reason why we use it is that it makes integration with other workloads easier.

> We spent a fair time testing the different options before settling on the current configuration as something we could support.

I believe that. How about option to just disable Calico configuration and start by RKE2 agent in Windows? That would allow users to use those scripts provided by Calico project it selves which can be then easily included to server template creation.

**Comment by brandond** [comment]
@manuelbuil @dereknola do you know if we do the right thing when the server has `cni: none`? Letting people bring their own on Windows, even if it's not supported, seems like a reasonable ask.

**Comment by manuelbuil** [comment]
> @manuelbuil @dereknola do you know if we do the right thing when the server has `cni: none`? Letting people bring their own on Windows, even if it's not supported, seems like a reasonable ask.

I think we do but if I understand correctly the desired feature is:
* Start rke2 servers on Linux using Calico as the backend (with a specific config)
* If the config does not match our current hardcoded config for windows, allow users to define `cni: none` but only in that particular Windows node. Then, users will deploy Calico on the Windows agents using the upstream scripts and connecting to the server

@olljanat , right?

**Comment by olljanat** [comment]
@manuelbuil yes. currently `cni: none` can be only configured for server but should be supported by Windows agent too.

**Comment by brandond** [comment]
The `cni` setting is a cluster-wide value that can only be set on servers, and must be the same on all of them. It doesn't make sense for some nodes to have one CNI while others have a different one.

I think what we need at the moment is for Windows agents to understand `cni: none` and not fail if there is no CNI chart deployed (as they currently do), but rather just wait for the user to install their own CNI using whatever powershell scripts or whatnot the CNI project requires.

**Comment by olljanat** [comment]
> It doesn't make sense for some nodes to have one CNI while others have a different one.

It does make sense from that point of view that `cni` value in server controls which Helm chart is deployed.
Windows CNI deployment instead of does not use Helm at all.

However Calico already have tech preview support for [Install Calico for Windows using HostProcess containers](https://projectcalico.docs.tigera.io/getting-started/windows-calico/quickstart#install-calico-for-windows-using-hostprocess-containers) and some day it most probably will be included as option to their Helm chart.

So big question here is that does RKE2 then switch deploying Calico to Windows as HostProcess containers? If it does then my original request that user should be able configure those settings should works just fine while using `cni: calico` (like we do because there is enough configuration options available in Linux deployment).

**Comment by brandond** [comment]
Yes, that is on the roadmap for us to support, when it is out of preview.
