### ISSUE TITLE
SELinux Trouble  with RKE2 tarball Airgap  installation

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3381]
**Environmental Info:**
RKE2 Version: 1.24.4+rke2r1
Node(s) CPU architecture, OS, and Version: 3.10.0-1160.71.1.el7.x86_64

**Describe the bug:**
As soon as i set **selinux** in mode **permissive**, 
Only the kube-proxy restart,
Other :  etcd; api-server, scheduler, ... ...never goes up, so node is notReady.

**Additional context / logs:**
the config.yaml have : 

```
secret-encryption: true
selinux: true
profile: cis-1.6
```

**Expected behavior:**
Node to be available in **Selinux permissive** with all kube components running.

I may have made a mistake, or forget settings, could you help ?

**Comment by brandond** [comment]
> As soon as i set selinux in mode permissive, only the kube-proxy restart

What mode was selinux in when you initially started RKE2? Was selinux enabled in the rke2 configuration when you initially started it?

**Comment by seb-835** [comment]
Hi @brandond ,
i just redo an installation (in tarball airgap mode)  on a fresh new server, with selinux set to permissive.

The containers does not pop up, in the logs of rke2-server i see : 

SELinux is enabled for rke2 but process is not running in context 'container_runtime_t', rke2-selinux policy may need to be applied.

I attach rke2-server and containerd logs. 

[rke2-server.log](https://github.com/rancher/rke2/files/9654432/rke2-server.log)
[containerd.log](https://github.com/rancher/rke2/files/9654433/containerd.log)

Thanks for help, sure i may have missed to do something.

**Comment by Martin-Weiss** [comment]
@seb-835 - which OS are you using / RHEL7 or CentOS7? Maybe this is also related to https://github.com/rancher/rke2/issues/1865?

**Comment by seb-835** [comment]
@Martin-Weiss   RedHat Entreprise 7.9
look like the same issue, but i was not able to find any rke2  selinux policy file on the host.

**Comment by Martin-Weiss** [comment]
In case you do the RPM install instead of the tarball install - the installer also fetches the rke2-selinux policy RPM..
So if you can switch from tarball to RPM based install it should work on RHEL 7.9 - at least it has been working for me on CentOS 7.9. The problem seems to exist with the tarball install, only.

**Comment by seb-835** [comment]
thanks @Martin-Weiss 

you put me to the right way.
i download the rpm  rke2-selinux :   rpm from  https://github.com/rancher/rke2-selinux/releases
i download the rpm  :   container-selinux  , 
yum install both ...and  got it works...
so for tarball install  ,   you need those 2 packages  added  to make it run in selinux mode.

**Comment by Martin-Weiss** [comment]
@seb-835  - so for your setup you are using the two RPMs rke2-selinux and container-selinux but the tarball of RKE2 1.24.4+rke2r1 and it works without any additional selinux policy change? Did you reboot after the deployment to see if all comes up well?

**Comment by seb-835** [comment]
@Martin-Weiss 
yes, that's what i do,  rke2 tarball + 2 rpm package : rke2-selinux and container-selinux 
no additional selinux policy add or change,
and after rebooting some nodes to test  :  the  cluster is still up  with all its nodes running.

**Comment by Martin-Weiss** [comment]
@seb-835  - thanks - then there must be some other difference when comparing RHEL 7 to CentOS 7.9 with my issue https://github.com/rancher/rke2/issues/1865 ..

**Comment by seb-835** [comment]
@Martin-Weiss Do you have cloud-provider enable in your env ?

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss Do you have cloud-provider enable in your env ?

I have been testing with Harvester - so yes.
