### ISSUE TITLE
Add support for the gpu-operator

### ISSUE THREAD

**Issue by tonygilkerson** [rancher/rke2#3385]
**Is your feature request related to a problem? Please describe.**

I am unable to use the [gpu-operator](https://nvidia.github.io/gpu-operator) due to how RKE2 handles the containerd `config.toml` file.

The gpu-operator will create `nvidia-container-toolkit-daemonset` (aka toolkit).  This toolkit tries to edit the CONTAINERD_CONFIG file, which in my case should be `/var/lib/rancher/rke2/agent/etc/containerd/config.toml`.  However, with RKE2 I can not edit this file directly because if I do it is stomped on at startup.  RKE2 will look for `config.toml.tmpl` and use it to generate `config.toml`.  If I point the toolkit at `config.toml.tmpl` it will give the following error because it does not understand the template expressions. 

```sh
nvidia-container-toolkit-ctr time="2022-09-26T15:50:01Z" level=fatal msg="Error: unable to load config: (6, 21): unexpected token type in inline table: keys cannot contain { character"
``` 

**Describe the solution you'd like**

I would like the ability to deploy the gpu-operator in my RKE2 cluster with no errors.  If I have to set a flag or some environment variable to indicate my situation that is ok by me.

**Describe alternatives you've considered**

We considered generating the `config.toml.tmpl` with concrete values using a tool like Ansible, this way it would contain no template expressions.  Then we might be able to point the toolkit at the `config.toml.tmpl`.    

**Additional context**

**Comment by brandond** [comment]
You shouldn't need to use the operator at all. The docs need to be updated to cover this, but see the instructions at https://github.com/k3s-io/k3s/issues/4391#issuecomment-1233314825 which should also work for RKE2.

**Comment by xhejtman** [comment]
Actually, you can use gpu-operator with rke2. The way is exactly as you say via config.toml.tmpl. You just need version 1 not version 2.

Put something like this into the `config.toml.tmpl`:
```
[plugins.opt]
  path = "/var/lib/rancher/rke2/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "index.docker.io/rancher/pause:3.6"

[plugins.cri.containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
  


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.containerd.runtimes.runc.options]
        SystemdCgroup = false
```

**Comment by caroline-suse-rancher** [comment]
Closing due to age

**Comment by yingding** [comment]
@brandond 
I am also facing issue with RKE2 v1.24 cluster to get gpu-operator working, especially missing the doc for configuring containerd.

Does the doc for k3s 
https://docs.k3s.io/advanced#configuring-containerd
also work for RKE2 ? 
Really appreciate your help to point me to the right direction.

**Comment by brandond** [comment]
yes, those docs also work for RKE2, assuming you correct the paths.
