### ISSUE TITLE
Cluster fails to come up after `rke2 cluster-reset` on etcd-only node due to leftover etcd container

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3387]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.24.4+rke2r1 (749c87a7da6482dec999df44f25578486158b21d)
go version go1.18.1b7
```

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
One control-plane only, one etcd only

**Describe the bug:**
After running `rke2 server --cluster-reset` and starting the rke2-server process, etcd does not come up.

**Steps To Reproduce:**
* Install and start RKE2 on both nodes as described
* Stop rke2-server on both nodes
* Run `rke2 server --cluster-reset` on the etcd-only node
* Start rke2-server on both nodes
* Note that the cluster fails to come up, and appears to be waiting on etcd. 
* If you look at `crictl ps` there are two etcd containers - the original one from before the cluster-reset which appears to be hung, and another new one that is crashlooping with the following error: `"error":"listen tcp 127.0.0.1:2380: bind: address already in use"`
  ```console
  systemd-node-01:/ # CONTAINER_RUNTIME_ENDPOINT=unix:///var/run/k3s/containerd/containerd.sock /var/lib/rancher/rke2/bin/crictl ps -a
  CONTAINER           IMAGE               CREATED             STATE               NAME                            ATTEMPT             POD ID              POD
  eef793ba98dc3       f0af64efd7e38       4 minutes ago       Exited              etcd                            6                   cc4d50d4c7d2c       etcd-systemd-node-01
  fb18c85fd3d90       f0af64efd7e38       12 minutes ago      Running             etcd                            0                   3babcaa3dacca       etcd-systemd-node-01
  55542188e8447       888570eb9d038       13 minutes ago      Exited              rke2-ingress-nginx-controller   0                   d8fb030215e74       rke2-ingress-nginx-controller-kpl8v
  bc51a29d7f436       491a6519673bd       14 minutes ago      Exited              coredns                         0                   967da38a739b1       rke2-coredns-rke2-coredns-76cb76d66-rkn99
  ```
  
You can use `crictl rm -f` to delete the older of the two etcd containers, after which the cluster will come up successfully.

**Expected behavior:**
old etcd static pod is cleaned up properly

**Actual behavior:**
old etcd static pod is not removed

**Additional context / logs:**
I suspect that this is a kubelet bug, as it should not be trying to start a new container for the etcd static pod while the old one remains running.

**Comment by brandond** [comment]
Confirmed that this also happens on `v1.24.2+rke2r1` so it's at least something that hasn't regressed recently.

**Comment by brandond** [comment]
Tracking upstream issue at https://github.com/kubernetes/kubernetes/issues/112814

**Comment by est-suse** [comment]
### Validated on <branch> with <commit> / <version> ## Environment Details *Infrastructure*- [ ] Cloud- [ ] Hosted
--
