### ISSUE TITLE
[Release 1.23] Update calico in windows env

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#3393]
Backport: https://github.com/rancher/rke2/issues/3391

**Comment by est-suse** [comment]
Validated on Commit ID 5b5988cc8d1683e6bfa44ce1426c207bba20f289

Node(s) CPU architecture, OS, and Version:
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```

Cluster Configuration:
```
1 linux server, 1 windows agent
```

Config.yaml:
```
cni: calico
token: secret
write-kubeconfig-mode: 644
cluster-init: true
```

Testing Steps:
1. sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
2. sudo curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=5b5988cc8d1683e6bfa44ce1426c207bba20f289 sh -
3. Join Windows agent node

Validation Results:

![image](https://user-images.githubusercontent.com/106194120/195252761-3469d059-491e-42ca-aee5-7f7e1639c35f.png)

kubectl get all -A -o wide | grep -i -e "v3.24.1"

![image](https://user-images.githubusercontent.com/106194120/195252821-86baa0f7-2af6-4bd8-b974-a8d8821ff7e7.png)

Validate version in Windows Agent:

![image](https://user-images.githubusercontent.com/106194120/195252926-a62debf1-d23b-4c7b-87a4-d06ab56e8c46.png)
