### ISSUE TITLE
Integrate Helm charts for addons to rke2 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#34]
As per discussion with @ibuildthecloud:

rke2 will integrate helm charts as CRs manifests in the manifest directory, however since rke2 is using different supervisor port the helm controller will not be able to download the charts, so the following changes will be added:

- helm controller will have an added spec to the crd called `chartContent`
- rke2 build process will download the tgz charts and add it to the yaml manifest as helmChart CRs
- helm controller will create configmap as the chartContent
- klipper helm job will mount this configmap as a chart tgz and it will decode it

**Comment by ShylajaDevadiga** [comment]
With rke2 version v0.0.1-alpha.4,  verified charts are installed on startup.
