### ISSUE TITLE
[release-1.24] Update metrics-server to v0.6.1

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3401]
Backport to release-1.24:
*  #3400

**Comment by est-suse** [comment]
Validated on RKE2_VERSION=v1.24.7-rc2+rke2r1

Node(s) CPU architecture, OS, and Version:
```
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

```
Cluster Configuration:
```
1 server
```

Testing Steps

Install RKE2
sudo curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.24.7-rc2+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -
Make sure everything is up and running kubectl get node,all -A -o wide
Describe the metrics-server pod and look for the v0.6.1 is correctly showed!



![image](https://user-images.githubusercontent.com/106194120/196770820-d8c4165c-6b25-4c11-bdaf-cc072e6e3a0f.png)


![image](https://user-images.githubusercontent.com/106194120/196770234-2bec1686-5463-45be-b941-0f095e03ef8e.png)
