### ISSUE TITLE
Incorrect Documentation - Upgrades

### ISSUE THREAD

**Issue by monotok** [rancher/rke2#3422]
I think this part of the documentation needs to be updated. 

https://docs.rke2.io/upgrade/manual_upgrade

Specifically this bit "Currently, the latest channel is the only available channel. Once we have more releases and need to distinguish between the most recent release and the most stable release, we will add a stable channel and set it as the default."

Within this https://update.rke2.io/v1-release/channels I see there is a stable channel.

I only noticed because I installed RKE2 and it was v1.24.6+rke2r1 while I noticed on the github there was v1.25.2+rke2r1.

Thanks!

**Comment by brandond** [comment]
Thanks for the reminder! Docs have been updated.
