### ISSUE TITLE
rke2 dual-stack cluster worker nodes fails to register

### ISSUE THREAD

**Issue by ElZakariyae** [rancher/rke2#3423]
**Environmental Info:**
RKE2 Version: 

v1.24.4+rke2r1

Node(s) CPU architecture, OS, and Version: 

5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
6cpu/32ram

Cluster Configuration:

3 nodes as etcd/control-plan
8 nodes as worker

**Describe the bug:**

We have setup an rke2 dual-stack cluster and we were able to register 3 nodes as etcd/control-plan and one node as worker/control-plan but if fails if we try to register nodes as worker only.

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

register worker nodes as we usually do with rke1.
**Actual behavior:**

worker nodes fails to register.
**Additional context / logs:**

msg="failed to get CA certs at https://127.0.0.1:6444/cacerts: Get https://127.0.0.1:6444/cacerts: EOF"

**Comment by brandond** [comment]
Are you installing RKE2 and joining the cluster members manually, or are you provisioning the cluster from Rancher? Your use of the word "worker" makes me suspect that you're using Rancher. In that case I believe you're running into https://github.com/rancher/rancher/issues/39039

If you're not using Rancher, please attach the complete rke2-server and rke2-agent logs from the affected nodes. Just quoting an error message isn't sufficient to troubleshoot this issue.

**Comment by brandond** [comment]
Closing as Rancher issue.
