### ISSUE TITLE
default ClusterInformation.calicoVersion is not updated due to wrong build time injection of VERSION?

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#3424]
**Environmental Info:**
RKE2 Version: rke2 version v1.21.11+rke2r1 (2998c71ea2db8418d55ec63014e3b916a76666e9)
go version go1.16.14b7

Node(s) CPU architecture, OS, and Version:  Linux k8s-build001-master001.asdf.com 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 18:09:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 masters 10 workers. 

**Describe the bug:**

canal is missing the VERSION variable at build time so our cluster still has old ClusterInformation.calicoVersion:
```
$ kubectl get clusterinformations.crd.projectcalico.org --all-namespaces default -o yaml
apiVersion: crd.projectcalico.org/v1
kind: ClusterInformation
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"9060badc-8dce-4cb3-8fae-672a2e160ca8","creationTimestamp":"2021-01-29T07:36:12Z"}'
  creationTimestamp: "2021-01-29T07:36:12Z"
  generation: 1
  name: default
  resourceVersion: "699"
  uid: 105d183c-7b6f-4b63-b684-24c7000a1fd5
spec:
  calicoVersion: v3.13.3
  clusterGUID: cc97e050360a4b94b6e33b448655279d
  clusterType: k8s,canal,kdd
  datastoreReady: true
```

The problem is that VERSION seems to be missing to be set when the binary is built? The VERSION variable is used here to update calicoVersion in clusterinformations: https://github.com/projectcalico/calico/blob/v3.21.4/node/pkg/lifecycle/startup/startup.go#L1120

Its prooven by logs from here https://github.com/projectcalico/calico/blob/v3.21.4/node/pkg/lifecycle/startup/startup.go#L99 
which for us gives: 
```
rke2-canal-p287s calico-node 2022-10-05 12:14:04.271 [INFO][10] startup/startup.go 99: Starting node k8s-build001-worker006.sto1.asdf.com with version
```

As you can see the version is empty string. 
We should have ClusterInformation.calicoVersion 3.21.4 in our cluster but we still have the old one 3.13.3 since VERSION at build time is empty string and therefore does not update ClusterInformation correctly when starting up. 

I think the problem is this line which does not point to the correct place in 3.21.4? https://github.com/rancher/image-build-calico/blob/v3.21.4-build20220208/Dockerfile#L101 

correct path should be: `github.com/projectcalico/calico/node/pkg/lifecycle/startup.VERSION=${TAG}`

This was also reported in https://github.com/rancher/rancher/issues/35562 and could be solved as above.

**Comment by est-suse** [comment]
*Infrastructure*
- [X] Cloud
- [ ] Hosted


*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-1-186 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

*Cluster Configuration:*

```
3 servers-1 agent
```
