### ISSUE TITLE
Ingress Airgap Tarball is missing  nginx-ingress-controller-defaultbackend image.

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3428]
**Environmental Info:**

RKE2 Version: 1.24.4+rke2r1

**Describe the bug**
In AirGap Mode, the ingress tarball is missing image : nginx-ingress-controller-defaultbackend  if we want to enabled defaultBackend feature.

**Comment by brandond** [comment]
This is intentional. We dropped the defaultbackend image when switching to the newer chart that no longer requires a separate pod just to serve 404s for unhandled requests.

https://github.com/rancher/rke2/pull/969

**Comment by seb-835** [comment]
Oh :( 
The backend have the feature to serve a /healthz  helpfull for external lb.

**Comment by brandond** [comment]
You don't need the default backend for that either, what are you seeing that makes you think you do? All the stuff that used to be handled by the defaultbackend is now just served directly by the ingress controller, by default.

```console
root@rke2-server-1:/# curl -vks --http1.1 https://localhost:443/healthz
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Oct  6 18:21:28 2022 GMT
*  expire date: Oct  6 18:21:28 2023 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /healthz HTTP/1.1
> Host: localhost
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 06 Oct 2022 18:25:05 GMT
< Content-Type: text/html
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

**Comment by seb-835** [comment]
My bad, was having a 404 on the healthz, but error comme from a bad rewrite rule.
Thanks for all the help you bring @brandond , so appreciate.
