### ISSUE TITLE
[Release 1.24] Fix Canal chart to fix token renewal

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#3429]
Backport for #3425

**Comment by linuxpham** [comment]
How install this patch ?

**Comment by brandond** [comment]
Milestones track things to be fixed in upcoming releases. Kubernetes and RKE2 v1.24.7 won't be out until later this month. You can also see that the linked PR hasn't been merged yet.

**Comment by linuxpham** [comment]
At the moment, my K8S cluster can not mount PVC because this issue. Are there any way to fix temporary ? @rbrtbnfgl @brandond

**Comment by fastlorenzo** [comment]
@linuxpham you can use this: https://github.com/rancher/rke2/issues/3425#issuecomment-1271891935

**Comment by rancher-max** [comment]
### Validated on release-1.24 commitid `cf6466ea22d742121d3f0bf911dddaa5a5414ea1`
  
## Environment Details

  
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

Validated both rhel 8.6 and ubuntu 22.04 LTS
  
*Cluster Configuration:*

```
3 servers
1 agent
```
  
*Config.yaml:*

```
cni: canal
profile: cis-1.6
```
  
*Additional files*

N/A
  
## Testing Steps

1. Install RKE2 using `cni: canal` and join any additional nodes
2. Deploy a pod `kubectl run nginx1 --image=nginx`
3. Wait 24 hours, then deploy another pod: `kubectl run nginx2 --image=nginx`
  
**Replication Results:**
- rke2 version used for replication: `v1.24.6+rke2r1`
 
- Pod attempted to create after 24 hours is stuck in container creating with the following Error Event:
```
  Warning  FailedCreatePodSandBox  61s (x60 over 14m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9054f8781e49aa60e583a45f0b1351f09c13039aa76445e7b07ecdb1fb43e721": plugin type="calico" failed (add): error getting ClusterInformation: connection is unauthorized: Unauthorized
```
 
**Validation Results:**
- rke2 version used for validation: commit `cf6466ea22d742121d3f0bf911dddaa5a5414ea1`
 
- pods are all created successfully:
```
$ k get pods
NAME     READY   STATUS    RESTARTS   AGE
nginx1   1/1     Running   0          24h
nginx2   1/1     Running   0          3h26m
nginx3   1/1     Running   0          16m
```
