### ISSUE TITLE
Add pod-security-admission-config-file flag to the doc

### ISSUE THREAD

**Issue by PhanLe1010** [rancher/rke2#3440]
We added the new flag `pod-security-admission-config-file` [here](https://github.com/rancher/rke2/blob/ffba111f8f3d9933d9e1f08caa29944352ab4739/pkg/rke2/rke2_linux.go#L119-L125), so maybe considering adding it to [the doc](https://github.com/rancher/rke2/blob/master/docs/install/install_options/server_config.md)?

Context: I was working on testing some Pod Security Admission and tried to modify the default behavior. Looking through the doc doesn't seems to find a way to set it until I read [the PR](https://github.com/rancher/rke2/pull/3282/files#diff-0cdb72b73bef2169e6b872613aefd8949abef5f6b9dceae387ba9a1222487c90).

**Comment by dereknola** [comment]
It exists in the docs https://docs.rke2.io/security/pod_security_standards#pod-security-standards, we were transitioning the Rke2 docs to a new website, so there was about a month where the old docs still existed but were not getting updated.

**Comment by sureshgoli25** [comment]
I did roundtrip to here to know that, it is not yet covered in here https://docs.rke2.io/reference/server_config but available :)

**Comment by caroline-suse-rancher** [comment]
Closing because the documentation is available in an appropriate location
