### ISSUE TITLE
RKE2-server restarts 

### ISSUE THREAD

**Issue by Richardswe** [rancher/rke2#3441]
Cluster info: 3 servers, 2 agent
OS: OpenSuse Leap 15.4
RKE2-version: v.1.23.7.r2r2
Issue: After doing a drain on 1 master node at a time and upgrading the OS, restart the node and then uncordon the node. The cluster seems unstable, resulting in 2 rke2-servers restarting one time per day. cloud-controller-manager, kube-controller-manager and kube-scheduler pods restarts one time per day. 

Seems like the cluster is not HA anymore but maybe 1-2 nodes not 3. 
Shall i remove 2 master nodes and join in two new ones?

**Comment by brandond** [comment]
You haven't attached any logs or other information on what's causing things to restart, so it's hard for me to recommend for or against any particular course of action.

**Comment by Richardswe** [comment]
yes sorry @brandond I'm not so used to github yet, I ended up doing a cluster-reset with a snapshot and rebooting the nodes. Now it works again. Next time i make sure to attach the logs :)
