### ISSUE TITLE
Proxy Setting and HelmChart Deployment ?

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3443]
Hi Team,

Is it possible to assign specific proxy setting when using inbuild HelmChart CRD to deploy apps in the kubernetes cluster ?
We only want to use this proxy when pulling the charts from  server.

Thanks for your help.

**Comment by brandond** [comment]
> We only want to use this proxy when pulling the charts from server.

it is not currently possible to configure a HTTP proxy for the Helm job pod.

**Comment by thehonker** [comment]
Hate to necro but has the status of this changed at all?
