### ISSUE TITLE
containerd: operation not permitted

### ISSUE THREAD

**Issue by jeremy-london** [rancher/rke2#3454]
**Environmental Info:**
rke2 version v1.25.2+rke2r1 (851733a1cefcbe182094eece241b9b75fe6aca5e)
go version go1.19 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Rocky Linux 9 with DISA STIG
https://docs.rockylinux.org/es/books/disa_stig/disa_stig_part1/

```
$ getenforce
Enforcing
```

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"
```

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
After all this config the rke2-server.service fails with the following errors:

```
journalctl -u rke2-server -f
```

```
Oct 12 06:09:10 localhost.localdomain rke2[14827]: time="2022-10-12T06:09:10-04:00" level=info msg="Running containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/containerd"

Oct 12 06:09:10 localhost.localdomain rke2[14827]: containerd: fork/exec /var/lib/rancher/rke2/data/v1.21.5-rke2r2-92b1ca9704d2/bin/containerd: operation not permitted
```

**Steps To Reproduce:**

Following the Airgap deployment docs: https://docs.rke2.io/install/airgap/#rke2-installsh-script-install

`/etc/rancher/rke2/config.yaml`

```
secrets-encryption: "true"
profile: "cis-1.23"
selinux: "true"
write-kubeconfig-mode: "0644"
tls-san:
  - "[<REDACTED_MY-IP_ADDRESS>]"
```

- Installed RKE2: Not yet 😭 

**Expected behavior:**
RKE2 server to start

**Actual behavior:**
Failed to start service due to errors mentioned above

Quick attempt:
`/var/lib` has `chmod 777 -R` on it but still no luck

**Comment by brandond** [comment]
Have you by any chance mounted any of the paths above /var/lib/rancher/rke2 noexec or taken any other actions that would prevent running binaries in subdirectories of that path?

**Comment by clemenko** [comment]
Trying changing the `profile: "cis-1.23"` to `profile: "cis-1.6"` to start. We are seeing a similar error with another cluster. What were the STIG steps you applied to the host?

**Comment by brandond** [comment]
@clemenko 1.25 only supports cis-1.23. The only differences between the two profiles are the switch from PSP to PSS; which is all within Kubernetes and would not prevent the container runtime from being executed.

**Comment by clemenko** [comment]
@brandond where is that documented????

**Comment by brandond** [comment]
https://github.com/rancher/rke2/pull/3360 - I'm not sure why this isn't merged yet.

**Comment by clemenko** [comment]
> * [Update documentation with PSP removal #3360](https://github.com/rancher/rke2/pull/3360) - I'm not sure why this isn't merged yet.

undocumented features help no one! AND FYI. I have a cluster with 1.25 and the cis-1.6 working. SO....

**Comment by brandond** [comment]
It is also covered in the release notes for all the 1.25 releases...

https://github.com/rancher/rke2/releases/tag/v1.25.0%2Brke2r1
> RKE2 now supports version 1.23 of the CIS Benchmark for Kubernetes. The legacy CIS 1.5 and 1.6 profiles (profile: cis-1.5 and profile: cis-1.6) have been removed as they do not apply to Kubernetes 1.25. Servers using one of the legacy profiles must be updated to specify the cis-1.23 profile when upgrading to RKE2 1.25, or RKE2 will fail to start.

> I have a cluster with 1.25 and the cis-1.6 working. SO....

Are you sure?

**Comment by clemenko** [comment]
Sorry you are right, i have 1.24.

**Comment by brandond** [comment]
Yeah so none of this affects you at all then.

**Comment by clemenko** [comment]
I have a customer with an identical error on 1.23.4. so trying to figure it all out.

**Comment by brandond** [comment]
Yeah, that just furthers my suspicion that this is due to OS-level hardening and not anything in RKE2.

**Comment by clemenko** [comment]
@jeremy-london Is this on bare metal or in a VM?

**Comment by asteriskie** [comment]
Depending on the linux version, you may be encountering a restriction with fapolicyd.   
systemctl status fapolicyd
if it's running and you want to remain secure, it will likely be necessary to write some rules for this.

**Comment by brandond** [comment]
If you are using fapolicyd, then you might look at https://github.com/rancher/rke2/pull/3416

**Comment by jeremy-london** [comment]
Apologies for the delay on this -- I am running on bare metal with a STIG applied Rocky Linux 8 (RHEL 8.6 STIG actually)

A bit of change over the last month -- but the same issues

Node(s) CPU architecture, OS, and Version:
Rocky Linux 8 with DISA STIG
https://docs.rockylinux.org/es/books/disa_stig/disa_stig_part1/

I have updated the fapolicyd and was able to get the containerd error past.. but now stuck with this

1. Im getting a warning about the SELinux.. i assumed that the RPM install of rke2-common or rke2-server would have set that up.. any idea how to set this up?
```
WARN[0001] SELinux is enabled for rke2 but process is not running in context 'container_runtime_t', rke2-selinux policy may need to be applied
```

2. New errors now that containerd is running
```
INFO[0058] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
INFO[0060] Waiting for etcd server to become available
INFO[0060] Waiting for API server to become available
INFO[0063] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
{"level":"warn","ts":"2022-11-14T16:13:16.783-0500","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00041ba40/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
INFO[0065] Failed to test data store connection: context deadline exceeded
INFO[0068] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
INFO[0073] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
INFO[0078] Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error
```
... and so on -- seems `etcd` , `kube-proxy` and the kube API dont come up..

**Comment by clemenko** [comment]
What does the `/etc/rancher/rke2/config.yaml` look like? You should reapply the rke2-selinux rpm.

**Comment by brandond** [comment]
```
INFO[0060] Waiting for etcd server to become available
INFO[0060] Waiting for API server to become available
```

You should check the kubelet and containerd logs, as well as the etcd static pod logs. Can you run the following command on all three nodes and attach the resulting tarballs?
```bash
tar -czvf $(hostname).tgz /var/lib/rancher/rke2/agent/logs/kubelet.log /var/lib/rancher/rke2/agent/containerd/containerd.log /var/log/pods/kube-system_etcd-*/*/* /var/log/pods/kube-system_kube-apiserver-*/*/*
```

**Comment by jeremy-london** [comment]
Here are the contents of `/etc/rancher/rke2/config.yaml`

```
secrets-encryption: "true"
profile: "cis-1.23"
selinux: "true"
write-kubeconfig-mode: "0644"
tls-san:
  - "192.168.100.22"
```

I started going through the logs and found `/var/log/pods/kube-system_etcd-*/*/*` had this output
```
2022-11-16T15:36:03.191821934-05:00 stderr F {"level":"warn","ts":"2022-11-16T20:36:03.191Z","caller":"etcdmain/etcd.go:75","msg":"failed to verify flags","error":"open /var/lib/rancher/rke2/server/db/etcd/config: permission denied"}
```

The rest of the logs did not show much -- other then connection refused while attempting to spin up and reach other ports/API in the RKE2 stack

```
/var/lib/rancher/rke2/bin/crictl ps -a

CONTAINER      STATE    POD
c210a3d6462f7  Running  cloud-controller-manager-rke2-server
01d2ab335ae5a  Running  kube-apiserver-rke2-server
ba1cd2ff85795  Exited   etcd-rke2-server
82b93030afb93  Exited   kube-controller-manager-rke2-server
b4f028b2be45a  Exited   cloud-controller-manager-rke2-server
4f8b414504393  Exited   kube-apiserver-rke2-server
24c447bc4dd51  Exited   etcd-rke2-server
0d7929aac9e13  Running  kube-scheduler-rke2-server
```
>I confirmed `crictl logs -f etcd` was showing the same error as the /var/logs/pods was showing
--- 
I have followed the guide for setting up the `etcd` user to support CIS hardening

```
 ls -al /var/lib/rancher/rke2/server/db/etcd/
 
drwxrw-rw-. 2 etcd etcd   32 Nov 10 18:04 .
drwxrw-rw-. 3 root root   18 Nov 10 18:04 ..
-rw-rw-rw-. 1 etcd etcd 1128 Nov 16 15:44 config
-rw-rw-rw-. 1 etcd etcd   20 Nov 10 18:04 name
```

I checked the manifest for etcd
`/var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml`

```
...
securityContext:
    runAsGroup: 983
    runAsUser: 987
    seLinuxOptions:
      type: rke2_service_db_t
...
```

`/etc/passwd` 
```
etcd:x:987:983:etcd user:/home/etcd:/sbin/nologin
```
      
I have the following setup as well 
```
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
```

**Comment by clemenko** [comment]
@jeremy-london do you have time next week to get on a call to walk through all this?

**Comment by brandond** [comment]
@clemenko if you're on this I'll let you take over, but I suspect that it might be necessary to check that the most recent version of rke2-selinux is installed, and that contexts have been reapplied to all the affected paths. I have also seen additional stig-based hardening break things in unpredictable ways.

**Comment by clemenko** [comment]
That is what I am thinking too. Or even still the fapolicyd.

**Comment by brandond** [comment]
@jeremy-london @clemenko can someone provide follow up on the resolution for the next person that runs into this?

**Comment by asteriskie** [comment]
run: restorecon -rv <directory with the rke2 binary>
should help restore the contexts expected to run the service with selinux.   Would think the rpm's would do this...maybe they do now.
