### ISSUE TITLE
vSphere CSI chart does not allow enabling topology support

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3468]
For  role and zone topology to work, we have to uncomment   Line 209 and 210

https://github.com/rancher/vsphere-charts/blob/bc2dd9eae26a3c0608822bfa64e833893db1a0e1/charts/rancher-vsphere-csi/templates/controller/deployment.yaml#L209
https://github.com/rancher/vsphere-charts/blob/bc2dd9eae26a3c0608822bfa64e833893db1a0e1/charts/rancher-vsphere-csi/templates/controller/deployment.yaml#L210

 to have :

```
            - "--feature-gates=Topology=true"
            - "--strict-topology"
```

_Originally posted by @seb-835 in https://github.com/rancher/rke2/issues/3398#issuecomment-1281415536_

**Comment by nickvth** [comment]
https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-162E7582-723B-4A0F-A937-3ACE82EAFD31.html

**Comment by caroline-suse-rancher** [comment]
@brandond is this still relevant with the recent version bumps?

**Comment by brandond** [comment]
Yes. We should probably create an issue in the rancher/vsphere-charts repo (if there isn't one already) and make sure it gets prioritized for that team. Once the chart is updated there we can pull it in to RKE2.

**Comment by caroline-suse-rancher** [comment]
Closing as fixed per https://github.com/rancher/vsphere-charts/pull/42
