### ISSUE TITLE
Error getting ClusterInformation: connection is unauthorized: Unauthorized"

### ISSUE THREAD

**Issue by bernardgut** [rancher/rke2#3473]
So I created a single node rke2 cluster using the quick start guide to play around with. The config.yaml file is 
```
tls-san:                                                                         
  - <mydomain>.com
```

After about 48 hours (and every 48 hours after that) the scheduler fails completely and is not able to instanciate/delete pods, returning consistantly something along the line of :

`plugin type=\"calico\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized"`

The only way to fix this is to do 

```
systemctl stop rke2-server
rke2 certificate rotate
systemctl start rke2-server
```

this is starting to annoy me. Pods are stuck in "terminating" and the only way to cleanup is to restart the node. Anyone experienced something similar ? Is this supposed to be normal ? Do you  have to rotate certificates every 24-48h or the cluster node will go down ? 

Thanks

**Comment by manuelbuil** [comment]
If you are deploying with Canal as your CNI, you must be hitting this bug which is fixed in the next rke2 release happening this week https://github.com/rancher/rke2/issues/3425

**Comment by brandond** [comment]
Closing in favor of #3425
