### ISSUE TITLE
PSP removal plan for Kubernetes Clusters versions prior to 1.25

### ISSUE THREAD

**Issue by freecaykes** [rancher/rke2#3476]
**Is your feature request related to a problem? Please describe.**

From the [CIS hardening guide docs](https://docs.rke2.io/security/hardening_guide) seems like on Kubernetes Clusters 1.25+ CIS hardening will start using PSS.  Just wanted to inquire if the PSS will be back ported for RKE2 CIS hardened clusters with version prior to Kubernmetes 1.25 in the future and any timeline you  might have around this.  

**Describe the solution you'd like**

PSS deployed for Kubernetes 1.25+ to be backported to earlier release versions 1.21+

**Describe alternatives you've considered**

Deploying specific PSPs for some of our deployments to use when running in CIS hardened clusters.  Wanted to avoid this as PSPs are deprecated in Kubernetes 1.21+.

**Additional context**

**Comment by brandond** [comment]
We are not currently planning on it. We're treating 1.25 as a hard cutover point from PSP to PSS. While I admit we could have been more proactive about offering a migration period during the PSP deprecation period, we decided that it would be too much work to support switching back and forth between PSP and PSS based secure profiles.
