### ISSUE TITLE
Unable to access agent logs when ports on the agent node are not open

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#3481]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.25.3-rc2+rke2r1

Node(s) CPU architecture, OS, and Version: N/A
SLES 15 sp4

Cluster Configuration:
Two node: 1 server 1 agent
Port 20250 not open on security group

**Describe the bug:**
Unable to access kubectl logs and kubectl exec for pod on agent node work properly with egress-selector-mode not disabled

**Steps To Reproduce:**
As described in the original issue
1.  Run k3s 1-server/1-agent with --kubelet-arg=port=20250 and port 20250 not open on firewall or security group between nodes; note that kubectl logs and kubectl exec for pod on agent node work properly
2. On the server node **egress-selector-mode: agent** (not disabled)

**Expected behavior:**
With egress-selector-mode enabled kubectl logs and kubectl exec for pods on agent node work properly

**Actual behavior:**
Unable to access agent pod logs

**Additional context / logs:**
From the journalctl logs, egress-selector-mode is in disabled mode
```
Oct 20 00:58:53 ip-172-31-17-71 rke2[129219]: time="2022-10-20T00:58:53Z" level=info msg="Tunnel server egress proxy mode: disabled"
```

**Comment by brandond** [comment]
* Need to revert https://github.com/rancher/rke2/pull/3035 now that the bugs have been ironed out.

**Comment by ShylajaDevadiga** [comment]
### Validated using rke2 version v1.25.4-rc1+rke2r1
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04

*Cluster Configuration:*
Two node cluster, One server, One agent

  *Server Config.yaml:*
```
cat /etc/rancher/rke2/config,yaml
token: <TOKEN>
kubelet-arg:
  - port=65535
egress-selector-mode: agent
```
*Agent Config.yaml:*
```
cat /etc/rancher/rke2/config,yaml
token: <TOKEN>
kubelet-arg:
  - port=65535
server: https://SERVERIP:9345
```

 ## Steps to validate the fix
1. Copy config.yaml
2. Install rke2 with port 65535 not open on firewall or security group between nodes
3. Successfully being able to exec into any pod running on the agent node and access logs of the agent pod

**To validate:**
```
$ kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-35-56   Ready    control-plane,etcd,master   38m   v1.25.4+rke2r1
ip-172-31-40-31   Ready    <none>                      34m   v1.25.4+rke2r1

$ kubectl get pods -o wide
NAME                                         READY   STATUS    RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
nginx-nodeport-deployment-6546875bf8-j57lp   1/1     Running   0          14m   10.42.1.4    ip-172-31-40-31   <none>           <none>
nginx-nodeport-deployment-6546875bf8-xh8k8   1/1     Running   0          14m   10.42.0.10   ip-172-31-35-56   <none>           <none>

$ kubectl exec nginx-nodeport-deployment-6546875bf8-j57lp -- ls -la
total 92
drwxr-xr-x   1 root root 4096 Nov 11 20:15 .
drwxr-xr-x   1 root root 4096 Nov 11 20:15 ..
drwxr-xr-x   1 root root 4096 Dec  3  2021 bin
drwxr-xr-x   2 root root 4096 Oct  3  2021 boot
...

$ kubectl logs nginx-nodeport-deployment-6546875bf8-j57lp
2022/11/11 20:15:55 [notice] 1#1: using the "epoll" event method
2022/11/11 20:15:55 [notice] 1#1: nginx/1.21.4
2022/11/11 20:15:55 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2022/11/11 20:15:55 [notice] 1#1: OS: Linux 5.15.0-1019-aws
2022/11/11 20:15:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/11/11 20:15:55 [notice] 1#1: start worker processes
2022/11/11 20:15:55 [notice] 1#1: start worker process 10
2022/11/11 20:15:55 [notice] 1#1: start worker process 11

```

**Comment by ShylajaDevadiga** [comment]
Validated on rke2 version v1.24.8-rc1+rke2r1
Validated on rke2 version v1.23.14-rc1+rke2r1
