### ISSUE TITLE
Default ingress not working out of the box when installed with Cilium

### ISSUE THREAD

**Issue by mightymouse2045** [rancher/rke2#3490]
**Environmental Info:**
RKE2 Version: 
Multiple versions including:
rke2 version v1.24.7+rke2r1 (5fd5150f752a663efa16ac3ae2aac5d6bba6c364)
go version go1.18.1b7

and 

rke2 version v1.24.6+rke2r1 (473cc354adecd235f00f0d80828611b0556b83e5)
go version go1.18.1b7

Node(s) CPU architecture, OS, and Version:  Tried with:
Linux test-server 5.15.0-1021-generic #28-Ubuntu SMP Fri Oct 14 15:46:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux test1 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server any number of servers and agents has the issue

**Describe the bug:**
Install RKE2 server with cni cliium in /etc/rancher/rke2/config.yaml and default ingress does not work

**Steps To Reproduce:**
- Installed RKE2: 
curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -

/etc/rancher/rke2/config.yaml:
```yaml
write-kubeconfig-mode: "0644"
tls-san:
  - "1.2.3.4" (IP of the server)
  - "test.com"
cluster-domain: "test.com"
service-cidr: "172.80.0.0/16"
cluster-dns: "172.80.0.10"
service-node-port-range: "30010-32000"
cni: "cilium"
```

systemctl enable rke2-server
systemctl start rke2-server

**Expected behavior:**
default ingress works, 404 on curl http://127.0.0.1

**Actual behavior:**
curl http://127.0.0.1 connection refused

**Additional context / logs:**
I have installed without cilium as the cni and the deault ingress works. I have tried installing cilium through the UI and by changing the config file and adding in the cni of cilium after doing an initial install of RKE2 without cilium. It works at first but on reboot it reverts to connection refused.

If there are any other steps required to get cilium working out of the box then these should be documented somewhere, I can only find references from old versions.

**Comment by mightymouse2045** [comment]
Hi Brandon,

I have managed to resolve this by creating a manifest file:
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: "strict"

 and adding the following to the /etc/rancher/rke2/config.yaml:
disable-kube-proxy: "true" 

Once this is redeployed then the default ingress works as expected

**Comment by mightymouse2045** [comment]
> I'm not aware of any issues with cilium. Can you provide the output of `kubectl get node -o wide` and `kubectl get pod -A -o wide`?

This is the output from the above on a broken system, ie deploying it as per the approach in the Steps To Reproduce: above.

```
curl http://127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused

kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml get node -o wide
NAME          STATUS   ROLES                       AGE    VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
test-server   Ready    control-plane,etcd,master   3m9s   v1.24.7+rke2r1   10.10.0.71    <none>        Ubuntu 22.04.1 LTS   5.15.0-1021-gcp   containerd://1.6.8-k3s1

kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml get pod -A -o wide
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
kube-system   cilium-operator-6dc58756c8-jldrk                        1/1     Running     0          3m18s   10.10.0.71    test-server   <none>           <none>
kube-system   cilium-operator-6dc58756c8-n8wzz                        0/1     Pending     0          3m18s   <none>        <none>        <none>           <none>
kube-system   cilium-snlz2                                            1/1     Running     0          3m18s   10.10.0.71    test-server   <none>           <none>
kube-system   cloud-controller-manager-test-server                    1/1     Running     12         3m20s   10.10.0.71    test-server   <none>           <none>
kube-system   etcd-test-server                                        1/1     Running     10         3m30s   10.10.0.71    test-server   <none>           <none>
kube-system   helm-install-rke2-cilium-ljk6d                          0/1     Completed   0          3m59s   10.10.0.71    test-server   <none>           <none>
kube-system   helm-install-rke2-coredns-zr4hg                         0/1     Completed   0          3m59s   10.10.0.71    test-server   <none>           <none>
kube-system   helm-install-rke2-ingress-nginx-8mvl5                   0/1     Completed   0          3m59s   10.42.0.239   test-server   <none>           <none>
kube-system   helm-install-rke2-metrics-server-5f5t5                  0/1     Completed   0          3m59s   10.42.0.87    test-server   <none>           <none>
kube-system   kube-apiserver-test-server                              1/1     Running     10         3m1s    10.10.0.71    test-server   <none>           <none>
kube-system   kube-controller-manager-test-server                     1/1     Running     12         3m25s   10.10.0.71    test-server   <none>           <none>
kube-system   kube-proxy-test-server                                  1/1     Running     0          3m19s   10.10.0.71    test-server   <none>           <none>
kube-system   kube-scheduler-test-server                              1/1     Running     10         3m29s   10.10.0.71    test-server   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-54b786c9cb-v5dwh              1/1     Running     0          3m19s   10.42.0.44    test-server   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-768bfc5985-f6cw4   1/1     Running     0          3m19s   10.42.0.68    test-server   <none>           <none>
kube-system   rke2-ingress-nginx-controller-j4kd9                     1/1     Running     0          2m13s   10.42.0.250   test-server   <none>           <none>
kube-system   rke2-metrics-server-67697454f8-6v4vc                    1/1     Running     0          2m32s   10.42.0.131   test-server   <none>           <none>
```

**Comment by brandond** [comment]
What version of Ubuntu is this on? Do your hosts have the iptables or xtables-nft package installed?

**Comment by mightymouse2045** [comment]
Ubuntu 22.04.1 LTS

Yes iptables is installed

**Comment by brandond** [comment]
cc @manuelbuil - I'm not aware of any problems with kube-proxy and cilium, are you?

**Comment by mightymouse2045** [comment]
I am happy to run it without the kubeproxy seeing as that is one of the primary reasons to use it and it is working once I deployed a manifest file etc so happy if we want to close this out

**Comment by brandond** [comment]
The default configuration should work though. There no reason not to use kube-proxy unless you want ebpf.

**Comment by Martin-Weiss** [comment]
> The default configuration should work though. There no reason not to use kube-proxy unless you want ebpf.

JFYI - we have to disable kube-proxy for using the egress gateway functionality included in Cilium.

**Comment by brandond** [comment]
Yes, but we deploy ingress-nginx as a hostport daemonset, which should have nothing to do with egress gateway, or kube-proxy either since kube-proxy handles routing to services. So something is definitely odd here.

**Comment by manuelbuil** [comment]
> cc @manuelbuil - I'm not aware of any problems with kube-proxy and cilium, are you?

I am not. Cilium should work in the default case (i.e. with kube-proxy). Let me try to reproduce this

**Comment by manuelbuil** [comment]
@mightymouse2045 So far I was not able to reproduce it. I have one question: you wrote: `default ingress works, 404 on curl http://127.0.0.1`. What do you mean by `default ingress`? In a default rke2 deployment, ingress is listening on port 443 and using a ClusterIP, therefore, `http://127.0.0.1` does not point to anything. Unless you have changed the ingress configuration, you should pick up the clusterIP from: `kubectl get service -n kube-system rke2-ingress-nginx-controller-admission` and then do: `curl https://$CLUSTERIP`

**Comment by mightymouse2045** [comment]
> @mightymouse2045 So far I was not able to reproduce it. Could you try one thing? In a default rke2 deployment, ingress is listening on port 443 and using a ClusterIP. Could you pick up the clusterIP from: `kubectl get service -n kube-system rke2-ingress-nginx-controller-admission` and then do: `curl https://$CLUSTERIP`? Let's see if this is a hostPort problem or a kube-proxy problem

Yeah that is for the rke2-ingress-nginx-controller-admission, but I am talking about the default ingress controller for workloads.

The default message I am used to seeing for the default ingress is this or similar:

```
curl http://127.0.0.1
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by manuelbuil** [comment]
I was misunderstanding the issue and I could finally reproduce it. The rke2 nginx-controller is listening on two hostPorts (80 and 443), which means that all traffic coming to the node on tcp ports 80 and 443 will be sent to the nginx-controller pod. 

Cilium, by default, only enables `hostPort` for eBPF-based kube-proxy replacement as explained here: https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-portmap/#k8s-install-portmap. To enable that functionality when using the regular kube-proxy, you should set `cni.chainingMode=portmap`. BTW, portmap is a well known CNI plugin that takes care of the hostPort functionality using iptables.

The best way to change that config is, before deploying, create the directory `/var/lib/rancher/rke2/server/manifests/` and then place there a file `rke2-cilium-config.yaml` with the following content:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cni:
      chainingMode: portmap 
```
After that, your `curl http://127.0.0.1` will work. You can check that everything is ok by looking at `sudo iptables-save | grep -n HOST`, the output rules are what allow hostPort to work. If there are no rules, something went wrong and hostPort will not work.

**Comment by brandond** [comment]
@manuelbuil is that something we should set in the default chart config? If hostports are broken out of the box at the moment, that's not optimal.

**Comment by mightymouse2045** [comment]
> I was misunderstanding the issue and I could finally reproduce it. The rke2 nginx-controller is listening on two hostPorts (80 and 443), which means that all traffic coming to the node on tcp ports 80 and 443 will be sent to the nginx-controller pod.
> 
> Cilium, by default, only enables `hostPort` for eBPF-based kube-proxy replacement as explained here: https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-portmap/#k8s-install-portmap. To enable that functionality when using the regular kube-proxy, you should set `cni.chainingMode=portmap`. BTW, portmap is a well known CNI plugin that takes care of the hostPort functionality using iptables.
> 
> The best way to change that config is, before deploying, create the directory `/var/lib/rancher/rke2/server/manifests/` and then place there a file `rke2-cilium-config.yaml` with the following content:
> 
> ```
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: rke2-cilium
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     cni:
>       chainingMode: portmap 
> ```
> 
> After that, your `curl http://127.0.0.1` will work. You can check that everything is ok by looking at `sudo iptables-save | grep -n HOST`, the output rules are what allow hostPort to work. If there are no rules, something went wrong and hostPort will not work.

Yeah cool thanks - at the moment however my cluster network is now broken with 2 of the pods complaining:

[ContainersNotInitialized] containers with incomplete status: [mount-cgroup apply-sysctl-overwrites mount-bpf-fs clean-cilium-state]

I don't know how to recover them from that state, I've tried rebooting the nodes and deleting the pods but to no avail

**Comment by manuelbuil** [comment]
> > I was misunderstanding the issue and I could finally reproduce it. The rke2 nginx-controller is listening on two hostPorts (80 and 443), which means that all traffic coming to the node on tcp ports 80 and 443 will be sent to the nginx-controller pod.
> > Cilium, by default, only enables `hostPort` for eBPF-based kube-proxy replacement as explained here: https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-portmap/#k8s-install-portmap. To enable that functionality when using the regular kube-proxy, you should set `cni.chainingMode=portmap`. BTW, portmap is a well known CNI plugin that takes care of the hostPort functionality using iptables.
> > The best way to change that config is, before deploying, create the directory `/var/lib/rancher/rke2/server/manifests/` and then place there a file `rke2-cilium-config.yaml` with the following content:
> > ```
> > apiVersion: helm.cattle.io/v1
> > kind: HelmChartConfig
> > metadata:
> >   name: rke2-cilium
> >   namespace: kube-system
> > spec:
> >   valuesContent: |-
> >     cni:
> >       chainingMode: portmap 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, your `curl http://127.0.0.1` will work. You can check that everything is ok by looking at `sudo iptables-save | grep -n HOST`, the output rules are what allow hostPort to work. If there are no rules, something went wrong and hostPort will not work.
> 
> Yeah cool thanks - at the moment however my cluster network is now broken with 2 of the pods complaining:
> 
> [ContainersNotInitialized] containers with incomplete status: [mount-cgroup apply-sysctl-overwrites mount-bpf-fs clean-cilium-state]
> 
> I don't know how to recover them from that state, I've tried rebooting the nodes and deleting the pods but to no avail

Can you check the logs of the init containers and see if there is anything interesting?

**Comment by manuelbuil** [comment]
> @manuelbuil is that something we should set in the default chart config? If hostports are broken by default at the moment, that's not optimal.

yep. Although it may break Cilium deployments using the kube-proxy-less solution. I need to test this out first. Cilium has multiple features that make sense when deploying kube-proxy but break the kube-proxyless. And the opposite is also true. I wonder if we should have two Cilium backends: cilium and cilium-kube-proxy-less with the only difference being the default values (and removing kube-proxy in the case of the latter)

**Comment by mightymouse2045** [comment]
> > > I was misunderstanding the issue and I could finally reproduce it. The rke2 nginx-controller is listening on two hostPorts (80 and 443), which means that all traffic coming to the node on tcp ports 80 and 443 will be sent to the nginx-controller pod.
> > > Cilium, by default, only enables `hostPort` for eBPF-based kube-proxy replacement as explained here: https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-portmap/#k8s-install-portmap. To enable that functionality when using the regular kube-proxy, you should set `cni.chainingMode=portmap`. BTW, portmap is a well known CNI plugin that takes care of the hostPort functionality using iptables.
> > > The best way to change that config is, before deploying, create the directory `/var/lib/rancher/rke2/server/manifests/` and then place there a file `rke2-cilium-config.yaml` with the following content:
> > > ```
> > > apiVersion: helm.cattle.io/v1
> > > kind: HelmChartConfig
> > > metadata:
> > >   name: rke2-cilium
> > >   namespace: kube-system
> > > spec:
> > >   valuesContent: |-
> > >     cni:
> > >       chainingMode: portmap 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After that, your `curl http://127.0.0.1` will work. You can check that everything is ok by looking at `sudo iptables-save | grep -n HOST`, the output rules are what allow hostPort to work. If there are no rules, something went wrong and hostPort will not work.
> > 
> > 
> > Yeah cool thanks - at the moment however my cluster network is now broken with 2 of the pods complaining:
> > [ContainersNotInitialized] containers with incomplete status: [mount-cgroup apply-sysctl-overwrites mount-bpf-fs clean-cilium-state]
> > I don't know how to recover them from that state, I've tried rebooting the nodes and deleting the pods but to no avail
> 
> Can you check the logs of the init containers and see if there is anything interesting?

This was due to this bug on one of my servers running Debian - by removing SYS_MODULE and setting the privileged=true in the right place I was able to get this working.

[This resolved the nsenter mount permission denied error I was getting](https://pullanswer.com/questions/cilium-agents-fail-to-start-due-to-mount-permissions-with-cilium-v1-12-0-likely-upstream-issue)

**Comment by mightymouse2045** [comment]
> > @manuelbuil is that something we should set in the default chart config? If hostports are broken by default at the moment, that's not optimal.
> 
> yep. Although it may break Cilium deployments using the kube-proxy-less solution. I need to test this out first. Cilium has multiple features that make sense when deploying kube-proxy but break the kube-proxyless. And the opposite is also true. I wonder if we should have two Cilium backends: cilium and cilium-kube-proxy-less with the only difference being the default values (and removing kube-proxy in the case of the latter)

I believe I am now suffering from this issue at the moment. 

My /etc/rancher/rke2/config.yaml file includes this:

```
cni:
  - cilium
disable-kube-proxy: "true"
```
However I still have kube proxy deployed and I don't know why it's still there given the above it should remove the kube proy from the cluster automatically. 

I'm also not seeing changes to the cilium manifest take effect, for example if I change the IP for k8sServiceHost in /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml

k8sServiceHost: 1.2.3.4

It is not getting deployed with that IP it still has the old one in there.

Likely two completely separate issues - but how can I clean out any previous config that was supplied by a manifest and ensure the /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml is being used?

**Comment by manuelbuil** [comment]
I tried this morning and I can confirm that when deploying with kube-proxy-less options, the ` cni,chainingMode: portmap` is not creating any conflicts. Therefore, I'll enable it as default to avoid this issue. I'll update cilium to 1.12.3 in the process

**Comment by manuelbuil** [comment]
> > > @manuelbuil is that something we should set in the default chart config? If hostports are broken by default at the moment, that's not optimal.
> > 
> > 
> > yep. Although it may break Cilium deployments using the kube-proxy-less solution. I need to test this out first. Cilium has multiple features that make sense when deploying kube-proxy but break the kube-proxyless. And the opposite is also true. I wonder if we should have two Cilium backends: cilium and cilium-kube-proxy-less with the only difference being the default values (and removing kube-proxy in the case of the latter)
> 
> I believe I am now suffering from this issue at the moment.
> 
> My /etc/rancher/rke2/config.yaml file includes this:
> 
> ```
> cni:
>   - cilium
> disable-kube-proxy: "true"
> ```
> 
> However I still have kube proxy deployed and I don't know why it's still there given the above it should remove the kube proy from the cluster automatically.
> 
> I'm also not seeing changes to the cilium manifest take effect, for example if I change the IP for k8sServiceHost in /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
> 
> k8sServiceHost: 1.2.3.4
> 
> It is not getting deployed with that IP it still has the old one in there.
> 
> Likely two completely separate issues - but how can I clean out any previous config that was supplied by a manifest and ensure the /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml is being used?

I have just tried and it worked for me. Can you paste here the exact content of `rke2-cilium-config.yaml` and `config.yaml` please?

**Comment by Martin-Weiss** [comment]
Just a side note - for k8sServiceHost I am using 127.0.0.1..

**Comment by mightymouse2045** [comment]
> Just a side note - for k8sServiceHost I am using 127.0.0.1..

Is this the correct value to use?

**Comment by mightymouse2045** [comment]
rke2-cilium-config.yaml:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: strict
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
    operator:
      replicas: 1
    encryption:
      enabled: false
      type: wireguard
    l7Proxy: false
    hubble:
      enabled: true
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      relay:
        enabled: true
    prometheus:
      enabled: true
      port: 9090
```

config.yaml:
```
write-kubeconfig-mode: "0644"
tls-san:
  - "some.domain.com"
  - "10.x.x.x"
cluster-domain: "some.domain.com"
service-cidr: "172.80.0.0/16"
cluster-dns: "172.80.0.10"
service-node-port-range: "0-65500"
cni:
  - cilium
disable-kube-proxy: "true"
```

**Comment by mightymouse2045** [comment]
Sorry I noted that I have a failed helm update for cilium with this error:

`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Secret "cilium-ca" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rke2-cilium"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"`

**Comment by brandond** [comment]
Had you previously created that secret by hand, or attempted to manually install or upgrade cilium?

**Comment by mightymouse2045** [comment]
@brandond 

So the process I went through was one of panic.

- Firstly I had the issue after moving to cilium where the ingress wasn't working properly, so as I said I got things working via nodeport 80 on the required container.
- I played in my test environment and got it working using the proxy replacement method as I said.
- I proceeded to deploy the 'fix' to prod, but it was also maintenance night so proceeded to update the server OS's
- However due to the previously mentioned bug on the 2 debian servers in the cluster (yes I haven't consolidated the OS's on all the nodes yet) I had a broken prod system after deploying the 'fix'
- In my haste to rectify (I couldn't roll back the system patches), I thought I'd roll back to a non cilium cluster, so returned the system to using canal (updating the config to remove the cni and kube proxy lines and restarting the server)
- This didn't work cleanly and everything was still broken
- I returned the cluster to cilium cni, with the broken cilium nodes until I found the bug posted above. Once I deployed that everything started working again however the system is in the state with the kube proxy still running and the helm upgrade in a failed state

This is output of get pods
```
kubectl get pods -n kube-system
NAME                                                    READY   STATUS      RESTARTS        AGE
cilium-gjflx                                            1/1     Running     1 (35h ago)     38h
cilium-operator-7f784fbf8d-zgcxv                        1/1     Running     1 (39h ago)     45h
cilium-ptrnd                                            1/1     Running     0               38h
cilium-vlkfp                                            1/1     Running     0               38h
cilium-w2ntt                                            1/1     Running     0               38h
cloud-controller-manager-105app                     1/1     Running     2 (39h ago)     46h
csi-smb-controller-78b7b4b576-98bzh                     3/3     Running     3 (39h ago)     2d3h
csi-smb-node-4246n                                      3/3     Running     0               38h
csi-smb-node-kg48p                                      3/3     Running     17 (35h ago)    5d15h
csi-smb-node-xbbvp                                      3/3     Running     12 (39h ago)    5d14h
csi-smb-node-znnr6                                      3/3     Running     3 (39h ago)     11d
etcd-105app                                         1/1     Running     1 (39h ago)     2d10h
helm-delete-rke2-canal-ltz9j                            0/1     Completed   0               46h
helm-install-rke2-cilium-gh6wl                          0/1     Error       7 (5m19s ago)   11m
helm-install-rke2-ingress-nginx-42nhf                   0/1     Completed   0               2d4h
helm-install-rke2-metrics-server-ksq8m                  0/1     Completed   0               2d4h
kube-apiserver-105app                               1/1     Running     1 (39h ago)     2d10h
kube-controller-manager-105app                      1/1     Running     2 (39h ago)     46h
kube-proxy-102app                                   1/1     Running     4 (35h ago)     2d6h
kube-proxy-103app                                   1/1     Running     2 (39h ago)     2d6h
kube-proxy-104app                                   1/1     Running     1 (43h ago)     38h
kube-scheduler-105app                               1/1     Running     1 (39h ago)     46h
rke2-coredns-rke2-coredns-7c95fbfb68-6997z              1/1     Running     1 (39h ago)     2d4h
rke2-coredns-rke2-coredns-7c95fbfb68-xsgf5              1/1     Running     1 (39h ago)     2d6h
rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-d872n   1/1     Running     1 (39h ago)     2d4h
rke2-ingress-nginx-controller-2bq2s                     1/1     Running     10 (39h ago)    2d4h
rke2-ingress-nginx-controller-59wr8                     1/1     Running     0               38h
rke2-ingress-nginx-controller-7crgr                     1/1     Running     1 (39h ago)     44h
rke2-ingress-nginx-controller-hlrr6                     1/1     Running     1 (35h ago)     38h
rke2-metrics-server-6979d95f95-p5976                    1/1     Running     1 (39h ago)     2d4h
```

**Comment by brandond** [comment]
> In my haste to rectify (I couldn't roll back the system patches), I thought I'd roll back to a non cilium cluster, so returned the system to using canal (updating the config to remove the cni and kube proxy lines and restarting the server)

Switching CNIs on an existing cluster isn't supported, and having done so on this cluster is likely to continue to cause you problems. We don't currently protect against it, but perhaps we should.

**Comment by mightymouse2045** [comment]
ah ok - is there anyway I can resolve this - I have the weekend to resolve this uninterrupted and can also take down the cluster if required. For example can I delete the offending secret and restart the helm install pod?

**Comment by mightymouse2045** [comment]
backup cluster, delete it and the agents, run up new cluster and restore from backup?

**Comment by brandond** [comment]
You can try adding the missing helm labels to the secret, but I'm not sure what else you might run into. Restoring from a backup or otherwise rebuilding the cluster is a good option if you can't easily move forward with getting the helm chart installed again.

**Comment by mightymouse2045** [comment]
> You can try adding the missing helm labels to the secret, but I'm not sure what else you might run into. Restoring from a backup or otherwise rebuilding the cluster is a good option if you can't easily move forward with getting the helm chart installed again.

Yeah ok I'll give that a go, can you tell me how I can update the secret because I've never done that before?

**Comment by mightymouse2045** [comment]
umm I see what I've done wrong - hangon

**Comment by mightymouse2045** [comment]
> You can try adding the missing helm labels to the secret, but I'm not sure what else you might run into. Restoring from a backup or otherwise rebuilding the cluster is a good option if you can't easily move forward with getting the helm chart installed again.

Ok so I have updated the annotations etc, this was missing on the secret for cilium and hubble and also on the hubble service. Once I updated those it is working as expected and updates to the cilium-config manifest are deploying.

However - I get an error that kubeproxy is using the healthz port now because I have this set 
    `kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"` so I have set it to the following to get around that error:
    `kubeProxyReplacementHealthzBindAddr: ""`

Despite having `disable-kube-proxy: "true"` in the config.yaml the kube proxy is still running

What does the above setting do in the background and how can I troubleshoot why that is not removing the kube proxy as expected? If I delete them manually they come back automatically,

output from get pods:
```

NAME                                                    READY   STATUS      RESTARTS       AGE
cilium-7cf5z                                            1/1     Running     8 (10m ago)    24m
cilium-hgp97                                            1/1     Running     0              24m
cilium-operator-6f6df47f8f-9km29                        1/1     Running     0              24m
cilium-v6cfp                                            1/1     Running     7 (12m ago)    24m
cilium-zmpn2                                            1/1     Running     7 (12m ago)    24m
cloud-controller-manager-105app                     1/1     Running     2 (42h ago)    2d
csi-smb-controller-78b7b4b576-98bzh                     3/3     Running     3 (42h ago)    2d6h
csi-smb-node-4246n                                      3/3     Running     0              40h
csi-smb-node-kg48p                                      3/3     Running     17 (37h ago)   5d17h
csi-smb-node-xbbvp                                      3/3     Running     12 (42h ago)   5d17h
csi-smb-node-znnr6                                      3/3     Running     3 (42h ago)    11d
etcd-105app                                         1/1     Running     1 (42h ago)    2d13h
helm-delete-rke2-canal-ltz9j                            0/1     Completed   0              2d
helm-install-rke2-cilium-xggzj                          0/1     Completed   0              7m48s
helm-install-rke2-ingress-nginx-42nhf                   0/1     Completed   0              2d7h
helm-install-rke2-metrics-server-ksq8m                  0/1     Completed   0              2d7h
hubble-relay-84b4ddb556-xflgv                           1/1     Running     0              7m47s
kube-apiserver-105app                               1/1     Running     1 (42h ago)    2d13h
kube-controller-manager-105app                      1/1     Running     2 (42h ago)    2d
kube-proxy-102app                                   1/1     Running     4 (37h ago)    2d9h
kube-proxy-103app                                   1/1     Running     2 (42h ago)    2d9h
kube-proxy-104app                                   1/1     Running     1 (45h ago)    40h
kube-scheduler-105app                               1/1     Running     1 (42h ago)    2d
rke2-coredns-rke2-coredns-7c95fbfb68-6997z              1/1     Running     1 (42h ago)    2d6h
rke2-coredns-rke2-coredns-7c95fbfb68-xsgf5              1/1     Running     1 (42h ago)    2d8h
rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-d872n   1/1     Running     1 (42h ago)    2d7h
rke2-ingress-nginx-controller-2bq2s                     1/1     Running     10 (42h ago)   2d7h
rke2-ingress-nginx-controller-59wr8                     1/1     Running     0              40h
rke2-ingress-nginx-controller-7crgr                     1/1     Running     1 (42h ago)    47h
rke2-ingress-nginx-controller-hlrr6                     1/1     Running     1 (37h ago)    40h
rke2-metrics-server-6979d95f95-p5976                    1/1     Running     1 (42h ago)    2d7h
```

**Comment by brandond** [comment]
Do you by any chance have a HelmChartConfig for rke2-kube-proxy present?

**Comment by mightymouse2045** [comment]
> Do you by any chance have a HelmChartConfig for rke2-kube-proxy present?
> 
> If not, note that you need to set the `disable-kube-proxy` option on all the servers, and the restart all the nodes in the cluster in order to make that change.

No only these are present:
rke2-cilium-config.yaml   rke2-cilium.yaml          rke2-coredns.yaml         rke2-ingress-nginx.yaml   rke2-metrics-server.yaml

I have removed the option and readded it and will restart the server and all nodes and see if that works

**Comment by mightymouse2045** [comment]
> Do you by any chance have a HelmChartConfig for rke2-kube-proxy present?
> 
> If not, note that you need to set the `disable-kube-proxy` option on all the servers, and the restart all the nodes in the cluster in order to make that change.

No the impact is it removes the kubeproxy from the server but not the agents. So the server has no kube proxy running but all the agents do

**Comment by Martin-Weiss** [comment]
> > Just a side note - for k8sServiceHost I am using 127.0.0.1..
> 
> 
> 
> Is this the correct value to use?

As long as the operator runs on the masters in the cluster this should work. Otherwise the load balancer VIP for :6443 could be used. Using the IP of a one master node would not be very fault tolerant I assume ;-).

**Comment by mightymouse2045** [comment]
> > > Just a side note - for k8sServiceHost I am using 127.0.0.1..
> > 
> > 
> > Is this the correct value to use?
> 
> As long as the operator runs on the masters in the cluster this should work. Otherwise the load balancer VIP for :6443 could be used. Using the IP of a one master node would not be very fault tolerant I assume ;-).
My operator is running on one of the worker nodes - should it only deploy to the masters? Sounds like I should set it to the lb VIP instead.

**Comment by Martin-Weiss** [comment]
> > > > Just a side note - for k8sServiceHost I am using 127.0.0.1..
> > > 
> > > 
> > > Is this the correct value to use?
> > 
> > 
> > As long as the operator runs on the masters in the cluster this should work. Otherwise the load balancer VIP for :6443 could be used. Using the IP of a one master node would not be very fault tolerant I assume ;-).
> > My operator is running on one of the worker nodes - should it only deploy to the masters? Sounds like I should set it to the lb VIP instead.

Strange - my expecation would have been that the operator throws an error in case it can not reach the kubernetes API on 127.0.0.1:6443 on a worker.. don´t you see an error in the cilium operator logs?

**Comment by mightymouse2045** [comment]
> > > > > Just a side note - for k8sServiceHost I am using 127.0.0.1..
> > > > 
> > > > 
> > > > Is this the correct value to use?
> > > 
> > > 
> > > As long as the operator runs on the masters in the cluster this should work. Otherwise the load balancer VIP for :6443 could be used. Using the IP of a one master node would not be very fault tolerant I assume ;-).
> > > My operator is running on one of the worker nodes - should it only deploy to the masters? Sounds like I should set it to the lb VIP instead.
> 
> Strange - my expecation would have been that the operator throws an error in case it can not reach the kubernetes API on 127.0.0.1:6443 on a worker.. don´t you see an error in the cilium operator logs?

From the logs for cilium operator running on the worker node:
`
level=info msg="Starting apiserver on address 127.0.0.1:9234" subsys=cilium-operator-api
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s

`

**Comment by Martin-Weiss** [comment]
Interesting - did not expect that it can reach 127.0.0.1:6443 in case it is not running on a master node.. but as long as it works this way it seems to be fine..

**Comment by mightymouse2045** [comment]
> Interesting - did not expect that it can reach 127.0.0.1:6443 in case it is not running on a master node.. but as long as it works this way it seems to be fine..

cool

**Comment by brandond** [comment]
> did not expect that it can reach 127.0.0.1:6443

On agents or other nodes not running the apiserver, this is provided by the agent's loadbalancer tunnel.

**Comment by mightymouse2045** [comment]
rebuilt cluster and everything working now

**Comment by manuelbuil** [comment]
Let me reopen to track the initial issue of hostPort not working. PRs are created and are under test

**Comment by rancher-max** [comment]
#### Validated using `v1.25.4-rc2+rke2r1`

- See expected result from default ingress:
```
$ curl http://127.0.0.1
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
- General ingress functionality is working
- Standard nodeport/clusterip tests continue to function
