### ISSUE TITLE
sudo systemctl start rke2-server.service fails 

### ISSUE THREAD

**Issue by amitagh** [rancher/rke2#3498]
Getting below errors while installing rke2 due to this probably installation gets stuck waiting for either etcd or kube-proxy or other pods:
sudo systemctl start rke2-server.service
Job for rke2-server.service failed because the control process exited with error code.
See "systemctl status rke2-server.service" and "journalctl -xe" for details.
make: *** [Makefile:249: /home/a/aether-in-a-box//build/milestones/k8s-ready] Error 1

Below are the logs i see in /var/lib/rancher/rke2/agent/containerd/containerd.log
```
time="2022-10-28T02:08:44.626250910-07:00" level=info msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\""
time="2022-10-28T02:08:48.608337405-07:00" level=error msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\" failed" error="failed to pull and unpack image \"docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\": failed to copy: httpReadSeeker: failed open: failed to authorize: failed to fetch anonymous token: Get \"https://auth.docker.io/token?scope=repository%3Arancher%2Fhardened-etcd%3Apull&service=registry.docker.io\": read tcp 192.168.1.66:40218->52.1.184.176:443: read: connection reset by peer"
time="2022-10-28T02:09:02.426115969-07:00" level=info msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\""
time="2022-10-28T02:09:05.271365524-07:00" level=error msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\" failed" error="failed to pull and unpack image \"docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\": failed to copy: httpReadSeeker: failed open: failed to do request: Get \"https://registry-1.docker.io/v2/rancher/hardened-etcd/manifests/sha256:5ce7ea0dd355d9d5f6b9d6d4c1e3453a438bf608792f2f5733e8355eafdb8da8\": read tcp 192.168.1.66:56000->34.194.164.123:443: read: connection reset by peer"
time="2022-10-28T02:09:35.425405706-07:00" level=info msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\""
time="2022-10-28T02:09:38.550069898-07:00" level=error msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\" failed" error="failed to pull and unpack image \"docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\": failed to copy: httpReadSeeker: failed open: failed to do request: Get \"https://registry-1.docker.io/v2/rancher/hardened-etcd/manifests/sha256:5ce7ea0dd355d9d5f6b9d6d4c1e3453a438bf608792f2f5733e8355eafdb8da8\": read tcp 192.168.1.66:33008->18.215.138.58:443: read: connection reset by peer"
time="2022-10-28T02:10:24.425533210-07:00" level=info msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\""
time="2022-10-28T02:10:28.280987949-07:00" level=error msg="PullImage \"index.docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\" failed" error="failed to pull and unpack image \"docker.io/rancher/hardened-etcd:v3.5.1-k3s1-build20220112\": failed to copy: httpReadSeeker: failed open: failed to authorize: failed to fetch anonymous token: Get \"https://auth.docker.io/token?scope=repository%3Arancher%2Fhardened-etcd%3Apull&service=registry.docker.io\": read tcp 192.168.1.66:48846->52.1.184.176:443: read: connection reset by peer"
```

**Comment by Martin-Weiss** [comment]
Seems that downloading the fails due to some problems with 52.1.184.176:443 - do you have configured a proxy for internet access can you curl https://auth.docker.io/ ?

**Comment by amitagh** [comment]
> Seems that downloading the fails due to some problems with 52.1.184.176:443 - do you have configured a proxy for internet access can you curl https://auth.docker.io/ ?

curl https://auth.docker.io/
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to auth.docker.io:443

**Comment by amitagh** [comment]
RKE is being installed in a VM on my windows laptop. VM is on VMWare player with Ubuntu 20.0.4 OS with NIC as Bridged.

**Comment by amitagh** [comment]
> > > Seems that downloading the fails due to some problems with 52.1.184.176:443 - do you have configured a proxy for internet access can you curl https://auth.docker.io/ ?
> > 
> > 
> > curl https://auth.docker.io/ curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to auth.docker.io:443
> 
> This is what I get:
> 
> ```
> curl https://auth.docker.io/
> 404 page not found
> ```
> 
> So it seems you have some sort of a network problem..

In the same VM if i open it in browser i do get 404 error. But on the terminal i get the error i pasted earlier.

**Comment by amitagh** [comment]
On second time 

> > > > Seems that downloading the fails due to some problems with 52.1.184.176:443 - do you have configured a proxy for internet access can you curl https://auth.docker.io/ ?
> > > 
> > > 
> > > curl https://auth.docker.io/ curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to auth.docker.io:443
> > 
> > 
> > This is what I get:
> > ```
> > curl https://auth.docker.io/
> > 404 page not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it seems you have some sort of a network problem..
> 
> In the same VM if i open it in browser i do get 404 error. But on the terminal i get the error i pasted earlier.

Curl on second time gives 404 error now:
a@ubuntu:~/aether-in-a-box$ curl https://auth.docker.io/
404 page not found

**Comment by Martin-Weiss** [comment]
Strange - still looks like a network problem - now like a network stability problem.. but if the 404 page not found works, now - try to restart rke2-server and see..

**Comment by amitagh** [comment]
> Strange - still looks like a network problem - now like a network stability problem.. but if the 404 page not found works, now - try to restart rke2-server and see..

Did clean install multiple times. get the same issue again and again. It was working couple of days back. But since yesterday getting the issue everytime.

**Comment by brandond** [comment]
> curl https://auth.docker.io/
> curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to auth.docker.io:443

This is a problem with the networking on your device. Until this curl test works, rke2 and containerd will not work either.

Possibly there is a firewall or proxy server on your network that is blocking this access? Are you on a corporate network or in some other location where your access to public resources is restricted?

**Comment by brandond** [comment]
This is clearly an issue with your device or network; unfortunately we're unable to assist with troubleshooting your connection to Docker Hub.
