### ISSUE TITLE
CNI plugin binaries are not removed when `rke2-uninstall.sh`

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#3499]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

CNI plugin binaries are usually stored in /opt/cni/bin. We are not removing that directory as part of `rke2-uninstall.sh`. As a consequence, if we first deploy with canal and then with e.g. cilium, we don't know if those binaries were deployed by cilium or canal

**Steps To Reproduce:**

1 - Install rke2
2 - Check `ls /opt/cni/bin`
3 - rke2-uninstall.sh
4 - Check `ls /opt/cni/bin`, binaries are still there

**Expected behavior:**

No /opt/cni/bin after `rke2-uninstall.sh`

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
#### Validated using `master` branch commitid `2754ceaae826f50436de10c53ab56786ca649f44`

**Steps:**
1. Install rke2: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=2754ceaae826f50436de10c53ab56786ca649f44 sh -`
2. Update `/etc/rancher/rke2/config.yaml` to use chosen CNI. See following four files for what I did:
```
# 1
cni: canal

# 2
cni: multus,cilium

# 3
cni: calico

# 4
cni: cilium
```
3. After everything is up and running, check cni dir for files: `sudo ls -la /opt/cni/bin`
4. Uninstall rke2: `sudo rke2-uninstall.sh`
5. After uninstall completes, check cni dir and confirm it is empty or doesn't exist: `sudo ls -la /opt/cni/bin`

**Results:**
- Expectations were met using each CNI. For example, see below for results with `canal`:
```
# After install:
$ sudo ls -la /opt/cni/bin
total 197092
drwxr-xr-x 2 root root     4096 Nov  4 18:00 .
drwxr-xr-x 3 root root     4096 Nov  4 18:00 ..
-rwxr-xr-x 1 root root  4791048 Nov  4 18:00 bandwidth
-rwxr-xr-x 1 root root  5087400 Nov  4 18:00 bridge
-rwsr-xr-x 1 root root 43076608 Nov  4 18:00 calico
-rwsr-xr-x 1 root root 43076608 Nov  4 18:00 calico-ipam
-rwxr-xr-x 1 root root  9045992 Nov  4 18:00 dhcp
-rwxr-xr-x 1 root root  5214280 Nov  4 18:00 firewall
-rwxr-xr-x 1 root root  2302744 Nov  4 18:00 flannel
-rwxr-xr-x 1 root root  4782984 Nov  4 18:00 host-device
-rwxr-xr-x 1 root root  4331432 Nov  4 18:00 host-local
-rwsr-xr-x 1 root root 43076608 Nov  4 18:00 install
-rwxr-xr-x 1 root root  4881192 Nov  4 18:00 ipvlan
-rwxr-xr-x 1 root root  2471776 Nov  4 18:00 loopback
-rwxr-xr-x 1 root root  4930472 Nov  4 18:00 macvlan
-rwxr-xr-x 1 root root  4766440 Nov  4 18:00 portmap
-rwxr-xr-x 1 root root  5038312 Nov  4 18:00 ptp
-rwxr-xr-x 1 root root  2627552 Nov  4 18:00 sbr
-rwxr-xr-x 1 root root  2158624 Nov  4 18:00 static
-rwxr-xr-x 1 root root  2582464 Nov  4 18:00 tuning
-rwxr-xr-x 1 root root  4877096 Nov  4 18:00 vlan
-rwxr-xr-x 1 root root  2652000 Nov  4 18:00 vrf

# After uninstall:
$ sudo ls -la /opt/cni/bin
ls: cannot access '/opt/cni/bin': No such file or directory
```
