### ISSUE TITLE
Cannot install rke2-cilium via rancher (unknown object type "nil" in ConfigMap.data.ipv6-native-routing-cidr)

### ISSUE THREAD

**Issue by Ajtak** [rancher/rke2#3501]
Cannot install cilium, because after install from rancher ui I'm getting next error.

How to solve this?

```
helm install --namespace=cattle-system --timeout=10m0s --values=/home/shell/helm/values-rke2-cilium-1.12.102.yaml --version=1.12.102 --wait=true cilium /home/shell/helm/rke2-cilium-1.12.102.tgz¨

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.ipv6-native-routing-cidr
```

**Comment by brandond** [comment]
cc @manuelbuil

**Comment by brandond** [comment]
@Ajtak which release of rke2 are you trying to install, and from which release of Rancher?

**Comment by rbrtbnfgl** [comment]
Did you specify any values for cilium config from rancher? That config should be enabled if you specify `ipv6NativeRoutingCIDR` or IPv4 is disabled.

**Comment by Ajtak** [comment]
Last Stable version of Rancher UI And rke2. No, i dont specify any options, i use ONLY ipv4.

**Comment by brandond** [comment]
The command you're running doesn't look correct. Are you trying to MANUALLY install the rke2-cilum chart on an existing cluster? That's not supported. You should pick the correct CNI when provisioning the cluster from Rancher. When you do so, RKE2 will install and configure the chart automatically; the logs will look something like this:

```console
root@rke2-server-1:/# kubectl logs -n kube-system   helm-install-rke2-cilium-2rv8z | grep 'helm_v3 install'
+ helm_v3 install --set-string global.cattle.systemDefaultRegistry= --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 --set-string global.systemDefaultRegistry= rke2-cilium /tmp/rke2-cilium.tgz
```

**Comment by Ajtak** [comment]
Exists some tutorials, how to deploy Cilium into new / existing cluster? I'm not found anything.

Thanks

**Comment by rbrtbnfgl** [comment]
I don't know how to do it with rancher. On RKE2 the config file should be on `/etc/rancher/rke2/config.yaml` and the `cni` value configures the used CNI.

**Comment by brandond** [comment]
In Rancher, pick cilium as the CNI from the drop-down list when provisioning the cluster.

If you're installing rke2 by hand, set `cni: cilium` in the config file, and see the docs at https://docs.rke2.io/install/network_options/
