### ISSUE TITLE
Kubernetes system static pods have the wrong priorityClassName (etcd, apiserver, etc.)

### ISSUE THREAD

**Issue by crtvmn** [rancher/rke2#3509]
Static pods (ETCD, kube-apiserver, kube-scheduler, etc.) have the wrong priorityClassName (https://github.com/rancher/rke2/blob/master/pkg/staticpod/staticpod.go#L213)

Indeed, it must be `system-node-critical` instead of `system-cluster-critical` because static pods can not be moved to another node as described in the `system-cluster-critical` priorityClassName.

```
$ kubectl get priorityclasses.scheduling.k8s.io system-cluster-critical -o yaml
apiVersion: scheduling.k8s.io/v1
description: Used for system critical pods that must run in the cluster, but can be
  moved to another node if necessary.
kind: PriorityClass
metadata:
  creationTimestamp: "2022-10-28T15:31:22Z"
  generation: 1
  name: system-cluster-critical
  resourceVersion: "86"
  uid: 8ab79243-94a6-4c3f-b204-89a575bddb8e
preemptionPolicy: PreemptLowerPriority
value: 2000000000
```

```
T0227148@597a5763948e:/$ kubectl get priorityclasses.scheduling.k8s.io system-node-critical -o yaml
apiVersion: scheduling.k8s.io/v1
description: Used for system critical pods that must not be moved from their current
  node.
kind: PriorityClass
metadata:
  creationTimestamp: "2022-10-28T15:31:22Z"
  generation: 1
  name: system-node-critical
  resourceVersion: "85"
  uid: 51558a87-ce55-457c-817b-aa413def6aff
preemptionPolicy: PreemptLowerPriority
value: 2000001000
```

**Comment by brandond** [comment]
While this might be technically correct, I don't believe it makes an actual difference in terms of pod eviction. Static pods are ALWAYS exempt from eviction. You can refer to https://github.com/kubernetes/kubernetes/blob/42df02029d6dd6387f27f64bd823571f8f48df69/pkg/kubelet/types/pod_update.go#L158-L170

**Comment by crtvmn** [comment]
Of course, you’re right, it’s not a critical or a major bug. I just gave it for information. It works the same way.
I just did a diff with another Kubernetes cluster and I saw this diff.

**Comment by caroline-suse-rancher** [comment]
Closing due to age
