### ISSUE TITLE
Need a way to enable CIS mode when installing rke2 via install script

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#351]
**Description:**
Currently, CIS mode is enabled from a "Global Option" level in the rke2 binary via the `--profile` flag. This is not valid for the config.yaml, so there is no easy way to enable CIS mode when installing rke2 via the install script. The only known workaround would be to either run the binary instead, or directly edit `/usr/local/lib/systemd/system/rke2-server.env`

We should either allow global flags, such as `debug` and `profile` to be used in the config.yaml, or make rke2 aware of the `RKE2_CIS_PROFILE` environment variable. Note if we do not do this with the environment variable, then we should remove mention of this environment variable in the help text as well.

**Comment by cjellick** [comment]
@brandond can you please figure out why the profile flag (and any other non-functional global rke2 flags) are not working?

**Comment by davidnuzik** [comment]
_Some more information for context:_
The `--profile` flag doesn't do any mitigation, it only checks that the kernel params are set. No "flag" exists to enable "CIS mode". Previously we would perform CIS mitigation via the `INSTALL_RKE2_CIS_MODE=true` install environment variable. This no longer works after the refactor (it was taken out to simplify things).

So, in order for us to do CIS mitigation we must have a new flag or some script to perform this. **Or**, if this is no longer our goal then we need clarification and confirmation that the user will be expected to mitigate as per our documentation.

FYI here was the original issue where we tested cis mitigation and `--profile` flag: https://github.com/rancher/rke2/issues/61

**Comment by davidnuzik** [comment]
@cjellick QA approached me to indicate concern on this ^^ Can we get confirmation that it was intentional to remove the capability to enable "CIS mode". This "mode" was how we programmatically did some CIS mitigation for the user. This is no longer possible.

Would like confirmation that the user must follow docs and do their own mitigation thus QA too would be expected to do this before passing the `--profile=cis-1.5` flag and value.

Also confused on purpose of https://github.com/rancher/rke2/blob/master/bundle/share/rke2/rke2-cis-sysctl.conf

cc: @dweomer

**Comment by cjellick** [comment]
Just to be clear: this bug is for the fact that you cannot set the profile flag in the config.yaml. It has nothing to do with the functionality of profile once it is turned on.

The profile flag NEVER did mitigation and it still doesn't. The user must follow docs for mitigation, but the docs are currently incomplete. I am working on fixing the CIS docs up now.

**Comment by brandond** [comment]
I think I might know why this is happening. It may be resolved by some stuff that I had to fix to get --disable working right. I'll check.

**Comment by rancher-max** [comment]
There is a fatal error that happens when using the profile flag, whether installing via rke2 binary or install script and config file that prevents the server from running.
```
# sudo rke2 server --write-kubeconfig-mode 644 --profile=cis-1.5 2>&1 &
[1] 16350
root@ip-172-31-17-69:~# FATA[0000] invalid kernel parameter value kernel.panic=-1 - expected 10
invalid kernel parameter value kernel.panic_on_oops=0 - expected 1
invalid kernel parameter value vm.overcommit_memory=0 - expected 1 
```

**Comment by brandond** [comment]
Yes @rancher-max that is the expected behavior if the host is not configured in compliance with the CIS benchmark. We don't fix it for you, but tell you what the current and expected values are.

**Comment by cjellick** [comment]
+1, expected. ...We are writing a hardening doc that instructs you how to do this.

**Comment by davidnuzik** [comment]
Moving back To Test. If you object, please explain here or ping me.

**Comment by rancher-max** [comment]
#### Validated on beta23

- Can enable CIS mode in rke2 via profile flag in config.yaml or with `rke2 server --profile=cis-1.5`
- CIS mode comes up successfully when using this flag and initial check of expected values are correct

Steps to enable must include setting up etcd user and kernel params. If using the install script, this becomes simplified:
```
$ curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh -o install.sh && chmod +x install.sh
$ sudo INSTALL_RKE2_VERSION=v1.18.9-beta23+rke2 INSTALL_RKE2_METHOD='tar' ./install.sh
$ sudo useradd -r -c "etcd user" -s /sbin/nologin -M etcd
$ sudo sysctl -p /usr/local/share/rke2/rke2-cis-sysctl.conf

# Setup profile flag in config.yaml, then run:
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
```

**Comment by brandond** [comment]
Note for anyone reading this in the future - just running `sysctl -p` will not persist across reboots, you should do:

```sh
sudo cp /usr/local/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/
sudo sysctl --system
``
