### ISSUE TITLE
After upgrading to 1.24.7, multus pod is in error state which blocks other pods from getting terminated

### ISSUE THREAD

**Issue by krp2** [rancher/rke2#3520]
**Environmental Info:**
RKE2 Version: 
v1.24.7+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux sles-roi-m1 5.3.18-59.27-default #1 SMP Tue Oct 5 10:00:40 UTC 2021 (7df2404) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers 1 Agent

**Describe the bug:**
When cluster was upgraded from rke2 - 1.23.1 to 1.24.7, On worker node multus pod is unable to start. And because of this, other pods on this node are stuck in terminating state.
Please note that this is an intermittent issue and not observed always.

Error on describing multus pod:
`  Warning  Failed     53m (x11 over 55m)   kubelet            Error: failed to create containerd container: failed to stat parent: stat /var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/546/fs: no such file or directory`

Error on terminating pods:
`  Warning  FailedKillPod  104s (x300 over 66m)  kubelet  error killing pod: failed to "KillPodSandbox" for "0339d6f1-89f5-4419-b363-9bdcf6c8dbd9" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"51ab8569895f2f6181c17bbab018ffbc79e864399cea15902f1ca94db02ce2aa\": plugin type=\"multus\" name=\"multus-cni-network\" failed (delete): Multus: [powerflex/postgresql-ha-pgpool-6b65ccf865-nkbbg]: error getting pod: Unauthorized"`

**Steps To Reproduce:**

- Installed RKE2 version 1.23.1 on 3 masters, 1 agent
- Upgraded to 1.24.7

**Expected behavior:**

All pods should be up and running

**Actual behavior:**

Multus pod on one of the node is in error state and it is blocking other pods from getting terminated.

**Additional context / logs:**

Logs of the node where multus was in error state
[sles-roi-w1-2022-11-03_10_42_36.tar.gz](https://github.com/rancher/rke2/files/9936159/sles-roi-w1-2022-11-03_10_42_36.tar.gz)

**Comment by brandond** [comment]
> `container: failed to stat parent: stat /var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/546/fs: no such file or directory`

Did anything else happen to this node before or after the upgrade? This feels some sort of corruption of the filesystem or containerd state. Have you tried deleting the pod with kubectl, or the container with crictl, so that it can be recreated?

**Comment by krp2** [comment]
@brandond No I dont see anything unusual being done before or after upgrade.
We did retry deleting multus pod but it goes back to same error state. For some reason , it is looking for this file path and it does not exist on the node.

**Comment by brandond** [comment]
The `io.containerd.snapshotter.v1.overlayfs/snapshots` directory contains unpacked image layers. The fact that this directory is missing suggests that one or more of the layers for the multus image has disappeared out from underneath containerd. There is no good way to get containerd to scan and fix the snapshotter's layer store; it may be necessary to drain the pods from this node, stop rke2, and delete the `snapshots` directory so that containerd can re-pull and rebuild the layers to a known-good state.
