### ISSUE TITLE
Windows picking wrong interface for calico-vxlan

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#3533]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Windows deployment does not care about the node-ip configured in kubernetes and thus picks the interface without any requirement. As a consequence, in nodes with multiple interfaces, it is possible that it picks the wrong interface. In that case, inter-node communication will not work

**Steps To Reproduce:**

- Installed RKE2: 

1 - Deploy rke2 on windows. The windows agent must have more than 1 interface.
2 - In the windows deployment, list the hns-networks ==> Get-HnsNetwork
3 - Both External and Calico networks should have "ManagementIP = node-ip". This is not always happening
4 - When this is not happening, try to send traffic to a windows pod or from windows try to contact a linux pod. It will not work.

**Expected behavior:**

Internode (linux-windows) traffic works

**Actual behavior:**

Internode (linux-windows) traffic does not work

**Additional context / logs:**

**Comment by VestigeJ** [comment]
$ rke2 -v
```
rke2 version v1.25.5-rc4+rke2r1 (b64a0227652004cc8ff147d6c873e210753c5414)
go version go1.19.3 X:boringcrypto
```

$ kgn -o wide
```
NAME               STATUS   ROLES                       AGE   VERSION          INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION    CONTAINER-RUNTIME
ip-12-31-25-137   Ready    control-plane,etcd,master   18m   v1.25.5+rke2r1   12.31.25.137    <none>        Ubuntu 22.04.1 LTS             5.15.0-1019-aws   containerd://1.6.12-k3s1
win-ugrr8pkd7qt    Ready    <none>                      12m   v1.25.5          12.16.135.206   <none>        Windows Server 2022 Standard   10.0.20348.288    containerd://1.6.12
```

PS C:\Users\Administrator> ipconfig
```
Windows IP Configuration


Ethernet adapter vEthernet (baseline):

   Connection-specific DNS Suffix  . : world.wideweb.com
   Link-local IPv6 Address . . . . . : fe80::iced:co83:d018:a84d%14
```

PS C:\Users\Administrator> Get-HnsNetwork
```
ManagementIP           : 12.16.135.206
MaxConcurrentEndpoints : 0
Name                   : External
NetworkAdapterName     : baseline
Policies               : {}
State                  : 1
```
