### ISSUE TITLE
Refactor RPM build to be based off of the tarball

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#355]
Now that we have a simple tarball for installation on non-rpm based systems, we want to refactor the rpm to simply be based off of that tarball. Will keep things nice and consistent.

This is related to https://github.com/rancher/rke2/issues/295

**Comment by dweomer** [comment]
Addressed by https://github.com/rancher/rke2-packaging/pull/9

**Comment by davidnuzik** [comment]
@dweomer could you help us out a bit with how this should be validated by QA? We see in the PR:
```
Source various artifacts from the RKE2 tarball:

bin/rke2 executable
lib/systemd/system/rke2-{server,agent}.service units
share/rke2/rke2-cis-sysctl.conf
```

Think it's good enough to be checking that post-install the artifacts are indeed on disk at these locations? Good enough?

**Comment by dweomer** [comment]
For the purposes of validating this the two main focuses should be the installed binaries and service units from tarball and rpm.
In a centos container run the install script both ways, once for rpm and once for tarball, then:
- the output of `/usr/local/bin/rke2 --version` and `/usr/bin/rke2 --version` should be identical
- the sha256sum of `/usr/local/bin/rke2` and `/usr/bin/rke2` should be identical
- the service unit files `/lib/systemd/system/rke2-{server,agent}.service` to their `/usr/local/lib/systemd/system/rke2-{server,agent}.service` counterparts except for the executable location in the `ExecStart=` line

**Comment by ShylajaDevadiga** [comment]
Seeing difference in sha256sum between tarball and rpm install binary on same version of rke2
Tarball install on Ubuntu
```
rke2 -v
rke2 version v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5)

shasum -a 256 /usr/local/bin/rke2
d68798d38b315ab1bcd98ff3d3ea55a82042a98762a6892e7fd4f2e4e520c422  /usr/local/bin/rke2
```
RPM install on Centos
```
rke2 -v
rke2 version v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5)

shasum -a 256 /usr/bin/rke2
c26f0557cf87b9bd94141851277924905eb128555ba4551b90d533b4d328469e  /usr/bin/rke2
```
diff between the service unit file is identical except for env and executable location
```
14c14
< EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env
---
> EnvironmentFile=-/usr/local/lib/systemd/system/rke2-server.env
26c26
< ExecStart=/usr/bin/rke2 server
---
> ExecStart=/usr/local/bin/rke2 server
```

**Comment by dweomer** [comment]
Looks like rpmbuild makes an attempt to strip the binary so we will have to forgo the checksum comparison. We should probably open a different issue to address this in rke2-packaging (run rpmbuild in such a way so as to avoid attempting to strip the packaged binaries). For now, so long as the output from `/usr/local/bin/rke2 --version` and `/usr/bin/rke2 --version` are identical this should be good enough.

**Comment by ShylajaDevadiga** [comment]
Sounds good @dweomer Created new issue to track packaging binaries #496
Closing as validated.
