### ISSUE TITLE
[release-1.23] RKE2 truncates manifests that contain a HelmChart resource as the first document

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3551]
Backport to `release-1.23`:
*  #3469

**Comment by caroline-suse-rancher** [comment]
@brandond did this backport make it into Nov patches, or will it be for Dec?

**Comment by brandond** [comment]
Did not make it into November. Up next for December.

**Comment by rancher-max** [comment]
Validated as part of https://github.com/rancher/rke2/issues/3698
