### ISSUE TITLE
RKE2 aarch64 support

### ISSUE THREAD

**Issue by rajivml** [rancher/rke2#3552]
HI,

Am trying to set up dev environment on Mac M1 machine using UTM + Rocky Linux + RKE2  and we need RHEL for testing as our installer is RHEL specific and when I run RKE2 installer I got the error that "aarch64 is not supported"

So, can Rancher add this support please, looks like the upstream dependency is also resolved now https://github.com/golang/go/issues/39760#issuecomment-1308185760

**Comment by brandond** [comment]
Tracking in https://github.com/rancher/rke2/issues/817
