### ISSUE TITLE
Bundled ingress-nginx out of date

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#3558]
**Environmental Info:**
RKE2 Version: 1.25.3+rke2r1

Node(s) CPU architecture, OS, and Version: Ubuntu 22.04

Cluster Configuration: 3 servers, 2 agents

**Describe the bug:**

The bundled ingress-nginx chart is severly out of date. From what I understand these should not be updated out of band of RKE2 as you bundle your own version of the chart.

These should be updated as the current version is running a build from April. I counted 6 CVE's which have not been patched based on the release notes for ingress-nginx

**Additional context / logs:**

Is there anyway to upgrade this chart before RKE2 does? It would be nice to be able to update these easier than RKE2 releases.

**Comment by brandond** [comment]
> The bundled ingress-nginx chart is severly out of date. From what I understand these should not be updated out of band of RKE2 as you bundle your own version of the chart.
>
>These should be updated as the current version is running a build from April. I

Can you show specifically what you're looking at? Recent releases of rke2 ship rke2-ingress-nginx with [`nginx-1.2.1-hardened9`](https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.1.005/values.yaml#L25) which was built [one month ago](https://github.com/rancher/ingress-nginx/releases/tag/nginx-1.2.1-hardened9) today.

**Comment by braunsonm** [comment]
Interesting I was looking at this: https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-ingress-nginx/package.yaml

Which references the version from April as the base helm chart. Feel free to close if this is not in fact accurate

**Comment by brandond** [comment]
That is the upstream chart that our chart is based on. You can see from the other files in that directory that we are customizing it and providing our own (hardened) build of the controller.

**Comment by braunsonm** [comment]
Actually @brandond I'd like to reopen this. 1.2.1 is still really far behind the ingress-nginx copies and it's missing a ton of features...

Specifically, it is missing the ability to match CN's with TLS client authentication.

**Comment by brandond** [comment]
We do periodically bump the version, but we do tend to lag a bit behind since we have some custom patches to harden the ingress controller that aren't always particularly easy to rebase.
