### ISSUE TITLE
Windows agent fails on startup if `--profile` flag used

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3566]
**Environmental Info:**
RKE2 Version: 
n/a

Node(s) CPU architecture, OS, and Version: 
windows

Cluster Configuration:
any windows agent

**Describe the bug:**
with `profile: cis-1.6` in the config.yaml, run:
```console
PS C:\Users\Administrator> C:\\usr\\local\\bin\\rke2.exe agent --config /etc/rancher/rke2/config.yaml
time="2022-11-02T12:51:43+01:00" level=fatal msg="open /proc/sys/kernel/panic: The system cannot find the path specified."
```

**Steps To Reproduce:**
See above

**Expected behavior:**
windows agents don't fail on linux-specific paths

**Actual behavior:**
fails

**Additional context / logs:**
I don't think the CIS benchmark even covers Windows agents, so we should probably just skip it entirely on Windows.

**Comment by mdrahman-suse** [comment]
### Validated on branch master with commit 8f52bbbb4760922bd7851ff33d2880811c109547
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux ip-172-31-39-82 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

Windows 2019
```
  
*Cluster Configuration:*

```
1 server, 1 Win agent
```
  
*Config.yaml:*

```
# server
write-kubeconfig-mode: 644
token: summer
cni: calico
profile: 'cis-1.23'

# win agent
server: https://<server-IP>:9345
token: summer
node-external-ip: <agent-IP>
profile: 'cis-1.23'
```
  
## Testing Steps

1. Copy config.yaml on server
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
 - For replication: 
   - server: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.25.4+rke2r1 sh -`
   - agent: `./install.ps1 -Version v1.25.4+rke2r1`
 - For validation:
   - server: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=8f52bbbb4760922bd7851ff33d2880811c109547 sh -`
   - agent: ./install.ps1 -Commit 8f52bbbb4760922bd7851ff33d2880811c109547
3.
  
**Replication Results:**
- rke2 version used for replication:

- agent
```
rke2 -v
rke2.exe version v1.25.4+rke2r1 (b1992225c5b448bcf3b4818b473dc57e3cfb5f9b)
go version go1.19
```
 

- Observed an error while adding rke2 service on the agent node
```
rke2 --debug agent
time="2022-12-04T03:39:20Z" level=fatal msg="open /proc/sys/vm/panic_on_oom: The system cannot find the path specified."
```
 
**Validation Results:**
- rke2 version used for validation:

- agent
```
rke2 -v
rke2.exe version v1.25.4-dev+8f52bbbb (8f52bbbb4760922bd7851ff33d2880811c109547)
go version go1.19.3
```
 

- No errors observed
```
C:\usr\local\bin\rke2.exe --debug agent
time="2022-12-04T05:26:57Z" level=info msg="Starting rke2 agent v1.25.4-dev+8f52bbbb (8f52bbbb4760922bd7851ff33d2880811c109547)"
```
NOTE: agent was not able to join as hardened mode is not supported with Windows
