### ISSUE TITLE
Support for ContainerD BTRFS Plug-in

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#3569]
**Is your feature request related to a problem? Please describe.**

When deploying RKE2 on top of SLES with BTRFS for /var/lib/rancher it would be possible to use the overlay functionality BTRFS has included via containerd.

**Describe the solution you'd like**

Could we get the BTRFS plug-in added to the containerd delivery we have included in RKE2 - maybe with an auto-detection if the file-system „below“ /var/lib/rancher… and then auto-select / auto-enable / auto-use the BTRFS plug-in of containerd?

**Describe alternatives you've considered**
Using the non-BTRFS-optimized overlay driver in containerd.

**Comment by Martin-Weiss** [comment]
Seems I have overseen this:

`--snapshotter value                           (agent/runtime) Override default containerd snapshotter (default: "overlayfs")`

-> setting this to btrfs should do the trick, already..

**Comment by Martin-Weiss** [comment]
Just as reference - at least in RKE2 1.24.4 it seems we have this issue when using the btrfs snapshotter: https://github.com/containerd/containerd/issues/4217

**Comment by brandond** [comment]
Yeah, my understanding is that the btrfs snapshotter is not that great.
