### ISSUE TITLE
RKE2 conformance

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#357]
Run conformance against RKE2 and submit to upstream conformance repo to register it as an officially conformant distro.

Use RKE2's product name "RKE Government" in the PR (rather than "RKE2").

**Comment by davidnuzik** [comment]
Once this is approved and merged in upstream, we should update the v1.18.9 release notes.

**Comment by ShylajaDevadiga** [comment]
PR is merged. RKE Government now officially certified K8s distribution.
