### ISSUE TITLE
Allow override of policy.json to enable custom image signature requirements.

### ISSUE THREAD

**Issue by andrewcorr** [rancher/rke2#3590]
**Is your feature request related to a problem? Please describe.**

We would like to be able to verify the signature of all images being used in our cluster including the rke2 core images.
**Describe the solution you'd like**

It would be nice if we could create a custom policy.json file block any unsigned images being used. We are using a private registry but we would like only signed images to be used. When we scan images for vulnerabilities, if the vulnerabilities have been documented and allowed we sign the image, so no images which have not been scanned should be pulled.
**Describe alternatives you've considered**

Use an admission controller to check image signatures on admission to cluster but this does not deal with the rke2-hardened-etcd/kubernetes/coredns images.  
**Additional context**

**Comment by brandond** [comment]
I'm not sure what policy.json you're referring to. Can you be more specific in terms of what you're trying to override?

**Comment by andrewcorr** [comment]
The policy.json is the file which controls how containerd pulls images, the default config is below, taken from one of our rke2 clusters running 1.23.13
cat /var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1510/fs/etc/containers/policy.json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports":
        {
            "docker-daemon":
                {
                    "": [{"type":"insecureAcceptAnything"}]
                }
        }
}

**Comment by andrewcorr** [comment]
I think this is used by the k3s/rke2 bootstrap process. It is a config file for crio. Looking through the k3s code it looks like k3s uses crio to pull images.

**Comment by andrewcorr** [comment]
Just looking at the k3s code, it looks like your bootstrap process just pulls the images using containerd via the cri plugin, this  will not allow us to do image verification, looks like we will need to approach this from a different angle.

**Comment by andrewcorr** [comment]
maybe this is the solution... containerd/containerd#6691

**Comment by brandond** [comment]
Yes, that's not something rke2 manages. As you noted it appears to be part of containerd; is it perhaps something you could configure via containerd's config.toml? I will also note that rke2 does a very limited bit of image pre-pulling using CRI to containerd; most of it is just managed by the kubelet as part of pod lifecycle. Either way, it sounds like you need to figure out how to configure containerd to do what you want.

**Comment by andrewcorr** [comment]
Exactly, will do
