### ISSUE TITLE
Add inter-node test for windows e2e

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#3593]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

As described in https://github.com/rancher/rke2/issues/3533, there was a bug in the windows env which broke connectivity linux-windows. This is now fixed but we should have noticed in advanced. Unfortunately, we did not have any test verifying this connectivity. This PR adds this test

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

There is a test that verifies is linux pods can contact windows pods (and the other way around)

**Actual behavior:**

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
This is just adding tests in the repo. No QA validation is needed
