### ISSUE TITLE
make rke2-server and rke2-agent conflict at the systemd unit level

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#360]
Tarball installation already does this. You should be able to install rke2-server and rke2-agent rpms next each other but should not be able to run them both.

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.18.9-beta21+rke2
```
ps -ef |grep "rke2 server"

root     17865     1  9 06:14 ?        00:00:08 /usr/bin/rke2 server

yum install rke2-agent-1.18.9~beta21-2.el7.x86_64

sudo systemctl enable rke2-agent
sudo systemctl start rke2-agent

ps -ef |grep "rke2 agent"
root     22024     1  0 06:19 ?        00:00:00 /usr/bin/rke2 agent

ps -ef |grep "rke2 server" |grep -v grep

Logs:
```
journalctl -u rke2-server

Sep 29 06:19:11 ip-172-31-17-217.us-east-2.compute.internal systemd[1]: rke2-server.service: main process exited, code=exited, status=1/FAILURE
Sep 29 06:19:11 ip-172-31-17-217.us-east-2.compute.internal systemd[1]: Stopped Rancher Kubernetes Engine v2 Server.
Sep 29 06:19:11 ip-172-31-17-217.us-east-2.compute.internal systemd[1]: Unit rke2-server.service entered failed state.
Sep 29 06:19:11 ip-172-31-17-217.us-east-2.compute.internal systemd[1]: rke2-server.service failed

journalctl -u rke2-agent -f

Sep 29 06:27:03 ip-172-31-17-217.us-east-2.compute.internal rke2[22024]: time="2020-09-29T06:27:03Z" level=error msg="failed to get CA certs at https://127.0.0.1:41610/cacerts: Get https://127.0.0.1:41610/cacerts: read tcp 127.0.0.1:55166->127.0.0.1:41610: read: connection reset by peer"
Sep 29 06:27:05 ip-172-31-17-217.us-east-2.compute.internal rke2[22024]: time="2020-09-29T06:27:05Z" level=error msg="failed to get CA certs at https://127.0.0.1:41610/cacerts: Get https://127.0.0.1:41610/cacerts: read tcp 127.0.0.1:55178->127.0.0.1:41610: read: connection reset by peer"

```
Starting server again, agent is disabled, Node is back in Ready state
```
sudo systemctl start rke2-server
ps -ef |grep "rke2 server"
root     11986     1 23 17:29 ?        00:00:00 /usr/bin/rke2 server
kubectl get nodes
NAME                                         STATUS   ROLES         AGE     VERSION
ip-172-31-35-86.us-east-2.compute.internal   Ready    etcd,master   3m45s   v1.18.9-beta21+rke2

ps -ef |grep "rke2 agent" |grep -v grep
[root@ip-172-31-35-86 ~]# 
```
