### ISSUE TITLE
ETCD S3 Backup File Name/Prefix Override

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#3610]
**Is your feature request related to a problem? Please describe.**
When we deploy nodes, we generate a unique suffix for its name. For upgrades and changes we rebuild the nodes which in turn generates a new suffix on its name. The issue we are running into is the etcd backup process saves the files using the node name and also uses that for the pruning process. Since our node names often change, all old backups are not deleted automatically.

**Describe the solution you'd like**
Allow us to provide a backup prefix/name override that way even if the node name changes, the backup names are kept the same. Basically we would set this to the node name without the suffix. 

**Describe alternatives you've considered**
Build some custom process to delete the backups outside rke2.

**Additional context**

none

**Comment by mitchellmaler** [comment]
Updated name to include s3. This is around the automated s3 backup process in rke2.

**Comment by brandond** [comment]
Lets track this in https://github.com/rancher/rke2/issues/3714 - I believe the underlying issue is the same.
