### ISSUE TITLE
[rke2-charts] split branches

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#363]
We need to move to the new schema of managing branches:

main and main-source
- main contains the helm artifacts
- main-source contains the helm charts for dev

**Comment by cjellick** [comment]
this is to bring the consistence with rancher charts,
- main branch contains only assets(helm chart tarball), index.yaml and charts(real helm chart content after applying patches)
- main-source contains only source content, which has package.yaml or the helm chart content that developer iterates. Any future PR should be put against this branch. The generated artifacts will be push to main branch and also be served there.

So, testing shoiuld include verifying that you can actually see what the cahrt looks like on the "main" branch and just a simple regresssion test that rke2 still launches all the charts as expected

**Comment by rancher-max** [comment]
- Validated seeing the chart on the main branch
- Regression of rke2 in both airgap and non-airgap setups contains all charts as expected and manifests directory is setup correctly
