### ISSUE TITLE
[Test] Automate restarting rke2 service 

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#3641]
Manual steps:
1. Install RKE2 HA cluster as we usually do.
2. Deploy a workload -- ensure it is running successfully
3. Once everything is up and ready, run this:
  ```
  # Server Nodes:
  sudo systemctl restart rke2-server
  
  # Agent Nodes:
  sudo systemctl restart rke2-agent
  ```
4. While they are restarting, the cluster is not accessible for some minutes, then it should come back up and all nodes and pods should be running and working again
5. Ensure previously deployed workload is running successfully
6. Also ensure the previously deployed workload does not get restarted after agent restart
7. Deploy some new workloads (Pods, deployments, ingress, daemonset, replicas, etc) -- ensure they are running successfully

**Comment by est-suse** [comment]
Code has been  deployed.
