### ISSUE TITLE
--data-dir flag is ignored

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#367]
Starting rke2 with the --data-dir option does not alter the data directory. It always uses the default value of /var/lib/rancher/rke2.

**Comment by ShylajaDevadiga** [comment]
rke2 version v1.18.9+rke2r1

While using /mnt dir as the param for data-dir all content of data dir is relocated to new /mnt dir, except for crictl file in the agent dir
```
ls -R  /var/lib/rancher/rke2/
/var/lib/rancher/rke2/:
agent

/var/lib/rancher/rke2/agent:
etc

/var/lib/rancher/rke2/agent/etc:
crictl.yaml

ls /mnt
agent  bin  data  server
```

**Comment by brandond** [comment]
This appears to be coming from here:

https://github.com/rancher/k3s/commit/58aae57e120f4bef011c6e29986d2a5f41d60503#diff-e86b77690979bd28019f01c993abec39R44

**Comment by ShylajaDevadiga** [comment]
Created a new issue to track this #474
Closing as validated as the data-dir relocation works as expected.
```
/mnt/bin/kubectl get nodes
NAME              STATUS   ROLES         AGE     VERSION
ip-172-31-23-79   Ready    <none>        2m14s   v1.18.9+rke2r1
ip-172-31-30-69   Ready    etcd,master   41m     v1.18.9+rke2r1
```
