### ISSUE TITLE
upgrading_kubernetes doc has wrong extension

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#368]
The file at [docs/upgrading_kubernetes.nd](../blob/master/docs/upgrading_kubernetes.nd) has a typo in the extension, which prevents GitHub from rendering it as markdown.

**Comment by briandowns** [comment]
@davidnuzik  It would appear that this issue assigned to me has been resolved. Just FYI for something else to be assigned to take it's place. This should have been closed when it was resolved.

**Comment by brandond** [comment]
My apologies - I thought I'd linked this from the PR where I was fixing it.
