### ISSUE TITLE
When SUC upgrade is applied the cluster left orphaned replicasets

### ISSUE THREAD

**Issue by bguzman-3pillar** [rancher/rke2#3682]
**Environmental Info:**
RKE2 Version: 1.23, 1.24, 1.25, 1.26

Cluster Configuration: 3 servers, 1 agent

**Describe the bug:**

**Steps To Reproduce:**

- Installed RKE2: `v1.24.8+rke2r1` and upgrade to newest version
- Create plan.yaml 
- Run `kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.9.1/system-upgrade-controller.yaml`
- Apply plan.yaml

**Expected behavior:**

Cluster upgrade without any problem and remove all the previous version replicasets

**Actual behavior:**

Left orphaned replicasets there
```
$ kubectl get rs -A
NAMESPACE        NAME                                              DESIRED   CURRENT   READY   AGE
default          nginx-nodeport-deployment-c6c7fcb5                4         4         4       3h31m
kube-system      rke2-coredns-rke2-coredns-58fd75f64b              2         2         2       3h58m
kube-system      rke2-coredns-rke2-coredns-autoscaler-768bfc5985   1         1         1       3h58m
kube-system      rke2-metrics-server-67697454f8                    0         0         0       3h57m
kube-system      rke2-metrics-server-74f878b999                    1         1         1       3h24m
system-upgrade   system-upgrade-controller-b8f6445c6               1         1         1       3h27m
```

**Additional context / logs:**

**Comment by brandond** [comment]
Probably up for debate if we want to address this or not. On the K3s side we are making an attempt to package everything with `revisionHistoryLimit: 0` but on this side it's going to require a bunch of additional chart patching for purely cosmetic benefit.

**Comment by brandond** [comment]
I think there are too many moving pieces here to try to modifying everything to have `revisionHistoryLimit: 0`, since it's not the default for deployments. The old replicasets don't consume any significant resources. If a customer is irritated by this and wants to escalate it through PM we can take it up as a feature request.
