### ISSUE TITLE
pod is assigned ipv6 even though not config dual stack

### ISSUE THREAD

**Issue by nvthuong1996** [rancher/rke2#3716]
pod is assigned ipv6 even though not config dual stack
how can i disable ipv6 of pod ?

<img width="744" alt="image" src="https://user-images.githubusercontent.com/24992586/208223044-8bdb3139-e439-44b8-bc7d-c5e62ecab2d3.png">

**Environmental Info:**
RKE2 Version: 
rke2 version v1.24.8+rke2r1 (b061438ce1f04518d980aac842b62f92095d793d)
go version go1.18.1b7

**Comment by brandond** [comment]
That's just a link-local address, auto-assigned by the kernel on interface creation, not a global address assigned by the cluster. If you don't want your interfaces to have ipv6 link-local addresses assigned, you should disable ipv6 on the host.
