### ISSUE TITLE
Unable to enable weak ciphers for ingress-nginx

### ISSUE THREAD

**Issue by mikeyzm** [rancher/rke2#3720]
**Environmental Info:**
RKE2 Version: 
v1.24.7+rke2r1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**
Unable to enable weak ciphers for ingress-nginx such as `DES-CBC3-SHA`. The configuration does not take effect.

**Steps To Reproduce:**
- Installed RKE2
- Set the SSL ciphers from https://github.com/kubernetes/ingress-nginx/blob/1930b1467d93238bbcd96daac8e3863a91e58747/docs/user-guide/tls.md#legacy-tls

**Expected behavior:**
Can connect using `DES-CBC3-SHA`

**Actual behavior:**
Can't connect using `DES-CBC3-SHA`

**Additional context / logs:**
Downgrade `rke2-nginx-ingress` image version to `nginx-1.2.1-hardened7` worked for me.

**Comment by brandond** [comment]
Do the pod logs include any hints as to why this might be the case? I suspect that perhaps these legacy ciphers are no longer available in our hardened build of nginx.

**Comment by pirouet** [comment]
Excluding any "enterprise weirdness" due to older applications, is the question not why would you enable weak ciphers

https://ciphersuite.info/cs/TLS_RSA_WITH_3DES_EDE_CBC_SHA/
