### ISSUE TITLE
Compute Ressources: Kube-Reserved & System-Reserved

### ISSUE THREAD

**Issue by sass1997** [rancher/rke2#3722]
### Discussed in https://github.com/rancher/rke2/discussions/3718

<div type='discussions-op-text'>

<sup>Originally posted by **sass1997** December 19, 2022</sup>
I would like to see some recommandations about the configuration of kube-reserved and system-reserved of the Kubelet. I found some references from providers like AWS, Azure & Google how they configure the kube-reserved according to the vm-size. https://learnk8s.io/allocatable-resources

Also I'm not sure which c-groups for kube-reserved and system-reserved must be referenced. According to this design recommandation from Kubernetes. https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md#recommended-cgroups-setup. If I want to follow this design document I would need to start the kubelet/containerd process in a seperate c group. This is acutally not forseen in the current installation, as far as I saw.

Happy for every Input</div>

**Comment by brandond** [comment]
Closing in favor of the discussion.
