### ISSUE TITLE
Can not mount volume ReadWriteMany when SELinux enabled with Longhorn

### ISSUE THREAD

**Issue by rolnick** [rancher/rke2#3724]
**Environmental Info:**
RKE2 Version: rke2 version v1.23.6+rke2r1

Node(s) CPU architecture, OS, and Version: 
CentOS Linux release 7.9.2009 (Core)
Linux somename 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 2 servers, 2 agents.

**Describe the bug:**
I am in process of hardening kubernetes cluster with SELinux enabled. In most cases everything works fine.
Unfortunately when I was trying to start Statefulset with volume: ```accessModes: - ReadWriteMany```, I got an error:
```Error: failed to generate container "ad4c1d879d3bafd3c2a408ff840173a03b0f9b8756f8077ebda698a6b4fd5c10" spec: failed to generate spec: relabel "/var/lib/kubelet/pods/273ccdbf-bd23-4ba6-8cd8-ad6443e35b09/volumes/kubernetes.io~csi/pvc-07143c13-b920-4412-b906-cc42cc4329ca/mount" with "system_u:object_r:svirt_sandbox_file_t:s0:c148,c553" failed: lsetxattr /var/lib/kubelet/pods/273ccdbf-bd23-4ba6-8cd8-ad6443e35b09/volumes/kubernetes.io~csi/pvc-07143c13-b920-4412-b906-cc42cc4329ca/mount: operation not supported```

I am using Longhorn as storage class. What is more funny, when I switched to ```ReadWriteOnce``` everything worked fine.
In ```/var/log/audit/audit.log``` I do not see anything related to ```relabel```

**Steps To Reproduce:**
Install RKE2 with:
```yaml
profile: cis-1.6
selinux: true
```

Enable SELinux:
```conf
SELINUX=enforcing
SELINUXTYPE=targeted
```
Packages with SELinux:
```bash
container-selinux.noarch        2:2.119.2-1.911c772.el7_8  @centos7.9-extras 
libselinux.x86_64               2.5-15.el7                 @centos7.9-base   
libselinux-python.x86_64        2.5-15.el7                 @centos7.9-base   
libselinux-utils.x86_64         2.5-15.el7                 @centos7.9-base   
rke2-selinux.noarch             0.11-1.el7                 @/rke2-selinux-0.11-1.el7.noarch
selinux-policy.noarch           3.13.1-268.el7_9.2         @centos7.9-updates
selinux-policy-targeted.noarch  3.13.1-268.el7_9.2         @centos7.9-update
```
- Installed RKE2: rke2 version v1.23.6+rke2r1

**Expected behavior:**
Volume should be attached to pod.

**Actual behavior:**
Can not start pod, because of error.

**Additional context / logs:**

**Comment by brandond** [comment]
This sounds like a longhorn issue, not rke2. The error message suggests that the longhorn nfs share doesn't support xattrs. Any particular reason you opened an issue here?

**Comment by rolnick** [comment]
Just trying to figure out, where the problem is. Indeed NFS Ganesha does not have full support for xattrs.
Thank you.
