### ISSUE TITLE
Canal pods not starting when cluster-cidr 192.168.0.0/16 is used

### ISSUE THREAD

**Issue by timmaay21** [rancher/rke2#3726]
**Environmental Info:**
RKE2 Version:  v1.24.9+rke2r1 (1e1469d26dcddd9f712216b299b6a6c1c8e916ca)

Node(s) CPU architecture, OS, and Version: 
CentOS 7.9 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
(on VMware ESX)

Cluster Configuration:
3 servers, but bug can appear during the install of 1st or 2nd server

**Describe the bug:**
If cluster is built using "--cluster-cidr=192.168.0.0/16" or anything in the 192.168.0.0/16 range, Canal pods will show a status of "Error" upon starting and will enter a crash-restart loop. I believe this is due to a conflict with Calico's default internal IPv4 pool of 192.168.0.0/16 but I'm not sure.

**Steps To Reproduce:**
1) Set cluster-cidr in config.yaml to 192.168.0.0/16
2) Install RKE2 as per the instructions (curl -sfL https://get.rke2.io | sh -)
3) systemctl start rke2-server
4) watch kubectl get pods -A
5) if it doesn't happen on the first node, setup second node with config.yaml set to same cluster-cidr, "server" set to https://firstnode.domain:9345, and "token" set to the node-token of first node

**Expected behavior:**
I would expect 192.168.0.0/16 to be a valid cluster-cidr, or it should be documented that it won't work with Canal

**Actual behavior:**
Canal pods enter crash/restart loop

**Additional context / logs:**
I'm not seeing any obvious errors from the logs of the Canal pod, but I can attach if needed

**Comment by rbrtbnfgl** [comment]
It should work.
Are you sure that there aren't any overlap with the host network?

**Comment by timmaay21** [comment]
There shouldn't be...internally we use 10.0.0.0/8 so that was my reason for trying to use a different private range. :)

**Comment by rbrtbnfgl** [comment]
Ok.
If you could provide the logs of the Canal pod containers we can check if there are any errors.
I tried a similar setup with two servers and the cluster started without any issue.

**Comment by timmaay21** [comment]
[canal_log.txt](https://github.com/rancher/rke2/files/10320549/canal_log.txt)

**Comment by rbrtbnfgl** [comment]
Calico container seems to not have any issues. Probably flannel container fails.
`kubectl -n kube-system logs rke2-canal-xth5t kube-flannel` This should shows flannel logs.
