### ISSUE TITLE
cant delete etcd pod manifest file

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#373]
I could only repro this with the etcd pod manifest. I ran into it while testing the cis profile and how it impacts the etcd pod.

1. Create an rke2 cluster (single node)
2. create the etcd user (see readme on how to do that)
2. Once its up, turn on cis profile:
```
cat /usr/local/lib/systemd/system/rke2-server.env
RKE2_CIS_PROFILE="cis-1.5"
```
3. This should cause the etcd pod manifest to be modifed to include a securityContext section that specifies a user and grou pid (uid and gid), but that didn't work. The seecurityContext section never showed (separate bug).
4. At this point, I thought if i deleted the etcd pod manifest, rke2 would recreate it (it should). I did this to see if on recreate it would have securityContex. Instead, after restarting I got this error:
```
Sep 26 20:28:31 craig-rke2 rke2[1893264]: time="2020-09-26T20:28:31Z" level=fatal msg="starting kubernetes: preparing server: start cluster and https: open /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml: no such file or directory"
```

That shouldn't happen. rke2 should be able to lay down this file without a previous version exsting.

I tried to repro with the kube-apiserver manifest and it did not repro...the file was succesfully recreated upon restart.

**Comment by brandond** [comment]
Right now we skip extracting content (both bin and charts) if the bin directory for a particular release already exists. We should probably change this to only skip the bins, since the manifests will need to be recreated to properly support changing --disable flags, as well as your use case of manually deleted files.

**Comment by ShylajaDevadiga** [comment]
Validated in rke2 version v1.18.12-rc1+rke2r1, 
- securityContext section is present, specifying the user and group
- etcd data dir is owned by etcd:etcd
- deleted etcd pod manifest file, validated it was recreated with securityContext intact

```
$ cat /usr/local/lib/systemd/system/rke2-server.env
RKE2_CIS_PROFILE="cis-1.5"
$ cat /etc/passwd |grep etcd
etcd:x:997:997:etcd user:/home/etcd:/sbin/nologin
$ cat /etc/group |grep etcd
etcd:x:997:
$ kubectl get nodes
NAME             STATUS   ROLES         AGE   VERSION
ip-172-31-0-32   Ready    etcd,master   18m   v1.18.12-rc1+rke2r1
$ kubectl get pods -A
NAMESPACE     NAME                                                  READY   STATUS      RESTARTS   AGE
kube-system   etcd-ip-172-31-0-32                                   1/1     Running     1          2m26s
kube-system   helm-install-rke2-canal-dbldx                         0/1     Completed   0          14m

securityContext:
    runAsGroup: 997
    runAsUser: 997

sudo ls -ld  /var/lib/rancher/rke2/server/db/etcd
drwx------ 3 etcd etcd 4096 Nov 16 23:20 /var/lib/rancher/rke2/server/db/etcd
```
After deleting pod manifest, pod was recreated with securityContext section
```
 kubectl get pods -n kube-system etcd-ip-172-31-0-32 -o yaml |grep -A 2 security
  securityContext:
    runAsGroup: 997
    runAsUser: 997
kubectl get pods -A
NAMESPACE     NAME                                                  READY   STATUS      RESTARTS   AGE
kube-system   etcd-ip-172-31-0-32                                   1/1     Running     0          21s
kube-system   helm-install-rke2-canal-dbldx                         0/1     Completed   0          29m
kube-system   helm-install-rke2-coredns-g95vh                       0/1     Completed   0          29m

```
