### ISSUE TITLE
Setting profile=cis-1.5 does not trigger expected etcd changes

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#374]
If running in etcd mode, the following are expected to happen:
- the etcd process is ran as the etcd user & group. The process running as etcd:etcd should be triggered by a securityContext section in the etcd static pod yaml (/var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml) where uid and gid are specified.
- the etcd data dir is owned by etcd:etcd

This isnt happening.

version: beta20
on an ubuntu 20.04 box

Steps to repro:
1. Create an rke2 cluster (single node)
2. create the etcd user (see readme on how to do that)
2. Once its up, turn on cis profile:
```
cat /usr/local/lib/systemd/system/rke2-server.env
RKE2_CIS_PROFILE="cis-1.5"
```

**Comment by cjellick** [comment]
found during this time: https://github.com/rancher/rke2/issues/373

**Comment by cjellick** [comment]
This was blocking some of my CIS assertions and documentation, so I had to investigae. I believe I have a fix.

**Comment by cjellick** [comment]
Fix is merged, but im holding onto the issue until i can do a beta and test it out.

**Comment by cjellick** [comment]
Turning on CIS via the profile does a number of things, like turning on PSPs, network policy, and affecting how etcd is ran. I was testing etcd related stuff when I ran into this and didn't have time to fully investigate if PSP and net policy were affected, but for etcd, here are the things you should observe:
The etcd data dir is owned by the etcd user and group:
```
stat -c %U:%G /var/lib/rancher/rke2/server/db/etcd
etcd:etcd
```

The etcd process is ran as the etcd user:
```
etcd     2494105 2494029  3 Sep27 ?        00:35:15 etcd --config-file=/var/lib/rancher/rke2/server/db/etcd/config
```
and relatedly, the etcd pod manifest has a security context specified which points at the etcd user:
```
 grep -i securitycontext -A3  /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
  securityContext:
    runAsGroup: 996
    runAsUser: 996
```
that 996 corresponds to the etcd user I had made earlier:
```
grep etcd /etc/passwd
etcd:x:996:996::/var/lib/rancher/rke2/server/db:/bin/false
```

**Comment by rancher-max** [comment]
#### Validated on beta23

- All of the above is working correctly and is the same behavior I see
- Validated etcd pod is running as etcd user (in my case 997):
```
$ k -n kube-system exec -it etcd-ip-172-31-29-22  -- whoami
whoami: cannot find name for user ID 997
```
