### ISSUE TITLE
Windows nodes update error

### ISSUE THREAD

**Issue by ArwynFr** [rancher/rke2#3748]
**Environmental Info:**
RKE2 Version:  
```
rke2.exe version v1.22.17+rke2r1 (630063444231b0625b0c1345b2271d7420e08d15)
go version go1.16.14b7
```

Node(s) CPU architecture, OS, and Version: Windows Server 2019 Datacenter 10.0.17763.3770

Cluster Configuration: 1 linux server, 1 windows agent

**Describe the bug:**
After joining the Windows node to the cluster, system-update-controller tries to update the node (although it should not) and uses image `rancher/rke2-upgrade:v1.22.17-rke2r1` which only has `linux/*` implementations and fails.

**Steps To Reproduce:**

- Installed RKE2:
```
.\install.ps1 -Version v1.22.17+rke2r1
rke2 agent
```

**Expected behavior:**
```
$ kubctl describe node ***-dev-win
Kubelet Version: v1.22.17+rke2r1
```
No update Plan created or update using a windows image.

**Actual behavior:**
```
$ kubctl describe node ***-dev-win
Kubelet Version: v1.22.17
```
Update plan created and update fails because it uses a linux image.

**Additional context / logs:**

```
ErrImagePull (rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rke2-upgrade:v1.22.17-rke2r1": no match for platform in manifest: not found)
```

**Comment by brandond** [comment]
RKE2 doesn't come with system-upgrade-controller. Where is the system-upgrade-controller plan coming from? Did you import the cluster into Rancher, or did you deploy the SUC manually? If the plan is coming from Rancher, then this issue belongs in rancher/rancher.

**Comment by ArwynFr** [comment]
Yes, I'm using rancher, but I thought the SUC was from rke2.
I'll create a new issue in rancher/rancher regarding SUC.

However I think it is rke2 that handles node version.
Is it expeted behavior that the Windows node reports running `v1.22.17` instead of `v1.22.17+rke2r1` ?

**Comment by brandond** [comment]
I'm honestly not sure if we support importing clusters with Windows nodes, or if they must be provisioned through Rancher. I'll close this out and let the Rancher team follow up on the other issue.

**Comment by brandond** [comment]
The Window kubelet version doesn't contain the +rke2r1 suffix because we don't build Kubernetes for windows, we just use vanilla upstream binaries.
