### ISSUE TITLE
RKE2 relase channel stable points to older release

### ISSUE THREAD

**Issue by kagehisa** [rancher/rke2#3759]
**Describe the bug:**

Previous RKE2 updates with the RKE2 release channel stable pointed to `v1.24.9+rke2r1` On Friday the release that stable points to was "updated" to `v1.24.8+rke2r1`. I stopped the updates on our clusters for now since this looks like a mistake.
Was there a reason for the downgrade? 

**Expected behavior:**

Steadily increasing versions, no hopping between old and new releases. At least at the stable channel.

**Comment by brandond** [comment]
See the warning at the top of https://github.com/rancher/rke2/releases/tag/v1.24.9%2Brke2r1
