### ISSUE TITLE
[k3s-upgrade] k3s binary missing container_runtime_exec_t context type after upgrade on selinux systems

### ISSUE THREAD

**Issue by dweomer** [rancher/rke2#379]
**Environmental Info:**
K3s Version: 
- v1.18.x
- v1.19.x

Node(s) CPU architecture, OS, and Version: 
- CentOS 7, _any_ architecture

Cluster Configuration:
- _any_

**Describe the bug:**
After upgrading k3s via `rancher/k3s-upgrade` the type portion of the context label for `/usr/local/bin/k3s` reverts to `bin_t` or something other than `container_runtime_exec_t`. When the k3s process is restarted by the supervisor process (typically systemd) it will then cascade via domain/file transitions incorrect labels that will cause new/recreated pods to fail to operate correctly.

**Steps To Reproduce:**
- Installed K3s (single node example, but easier to see in multi-node when upgrade incurs eviction):
  - `curl -fsSL https://get.k3s.io | sh` with the following environment already exported:
    - `INSTALL_K3S_CHANNEL=stable`
    - `K3S_KUBECONFIG_MODE=0644`
    - `K3S_SELINUX=true`
    - `K3S_TOKEN=centos/7`
- Install SUC:
  - `curl -fsSL https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml | kubectl apply -f-`
- Install the example k3s-upgrade plans:
  - `curl -fsSL https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/examples/k3s-upgrade.yaml | kubectl apply -f-`
- Start the upgrade(s):
  - `kubectl label node --all k3s-upgrade=true`

**Expected behavior:**
Post-reboot, new/recreated pods start correctly.

**Actual behavior:**
Post-reboot, new/created pods in CrashLoopBackOff. Pods that were in place prior to the upgrade remain unaffected because they were started with the correct labels/transitions from the previous k3s/containerd process.

**Additional context / logs:**
- https://github.com/rancher/k3s/issues/2248#issuecomment-693603587

**Comment by ShylajaDevadiga** [comment]
Validated correct context labels are set before and after install on both rke2 and k3s with SELinux Enforcing mode
rke2 version v1.18.9-beta21+rke2
Red Hat Enterprise Linux Server release 7.8 (Maipo)

Before
```
kubectl get nodes
NAME                                          STATUS   ROLES         AGE     VERSION
ip-172-31-16-222.us-east-2.compute.internal   Ready    etcd,master   9m52s   v1.18.9-beta21+rke2
ip-172-31-25-212.us-east-2.compute.internal   Ready    <none>        57s     v1.18.9-beta21+rke2

 ps -eZ | grep -E 'rke2|containerd|shim'
system_u:system_r:container_runtime_t:s0 17330 ? 00:00:12 rke2
system_u:system_r:container_runtime_t:s0 17343 ? 00:00:47 containerd
system_u:system_r:container_runtime_t:s0 17544 ? 00:00:00 containerd-shim
```

After
```
kubectl get nodes
NAME                                          STATUS   ROLES         AGE   VERSION
ip-172-31-16-222.us-east-2.compute.internal   Ready    etcd,master   19m   v1.18.9-beta22+rke2
ip-172-31-25-212.us-east-2.compute.internal   Ready    <none>        10m   v1.18.9-beta22+rke2

system_u:system_r:container_runtime_t:s0 26644 ? 00:00:09 rke2
system_u:system_r:container_runtime_t:s0 26696 ? 00:00:09 containerd
system_u:system_r:container_runtime_t:s0 26968 ? 00:00:00 containerd-shim
```

K3S Upgrade from v1.18.9+k3s1 to v1.19.1+k3s1
Using dev repo
Before
```
kubectl get nodes
NAME                                          STATUS     ROLES    AGE     VERSION
ip-172-31-30-151.us-east-2.compute.internal   Ready      master   3m33s   v1.18.9+k3s1
ip-172-31-17-56.us-east-2.compute.internal    Ready   <none>   13s      v1.18.9+k3s1

cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml |grep selinux
  enable_selinux = true

[root@ip-172-31-30-151 ~]# ps -eZ | grep -E 'k3s|containerd|shim'
system_u:system_r:container_runtime_t:s0 11178 ? 00:00:24 k3s-server
system_u:system_r:container_runtime_t:s0 11193 ? 00:00:05 containerd
system_u:system_r:container_runtime_t:s0 11588 ? 00:00:00 containerd-shim
```
After
```
kubectl get nodes
NAME                                          STATUS   ROLES    AGE   VERSION
ip-172-31-30-151.us-east-2.compute.internal   Ready    master   33m   v1.19.1+k3s1
ip-172-31-17-56.us-east-2.compute.internal    Ready    <none>   29m   v1.19.1+k3s1

cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml |grep selinux
  enable_selinux = true

system_u:system_r:container_runtime_t:s0 13916 ? 00:01:38 k3s-server
system_u:system_r:container_runtime_t:s0 13926 ? 00:00:06 containerd
system_u:system_r:container_runtime_t:s0 14810 ? 00:00:01 containerd-shim
```
