### ISSUE TITLE
[rpm] RKE2 server and agent RPM's should require the corresponding RPM released versions of the RPM

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#380]
Right now, RKE2 server and agent depend on `rke2-common` for an `rpm_version` that matches the `rke2-server` or `rke2-agent` RPM they are trying to install. This is incorrect, and the `server` and `agent` rpm's should rely on a corresponding common RPM that also matches the RPM release.

**Comment by Oats87** [comment]
This can be tested with two of the "same" version of RPMs, but with different RPM releases.

i.e. install
`rke2-server` and `rke2-common` `1.18.9~beta21+rke2.1` from `rpm-testing.rancher.io`, then try to install `rke2-server` `1.18.9~beta21+rke2.2` which should then require you to update `rke2-common` to `1.18.9~beta21+rke2.2`

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version rke2 version v1.18.9-beta21+rke2
Installed rke2-common release 1, while installing rke2-server release 2, corresponding rke2-common release was updated.
```
yum install rke2-common-1.18.9~beta21-1.el7.x86_64

yum install rke2-server-1.18.9~beta21-2.el7.x86_64
Loaded plugins: amazon-id, product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package rke2-server.x86_64 0:1.18.9~beta21-2.el7 will be installed
--> Processing Dependency: rke2-common = 1.18.9~beta21-2.el7 for package: rke2-server-1.18.9~beta21-2.el7.x86_64

```
