### ISSUE TITLE
Inconsistent node joins on vSphere

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#3800]
**Environmental Info:**
RKE2 Version: 1.23.6+rke2r2

Node(s) CPU architecture, OS, and Version: Ubuntu 20.04

Cluster Configuration:
3 servers, 2 agents

**Describe the bug:**
We've been having a problem that we've been troubleshooting since using RKE2. Basically it is very inconsistent whether a node will join the cluster or if it will get stuck in a loop with the error that the node cannot be found by the kubelet. This can always be resolved by rebooting the node but would like to avoid that. I thought that it was related to this issue: https://github.com/kubernetes-retired/contrib/issues/2761 

So I've been trying to set `node-ip` in the kubelet to troubleshoot. I've been following the advice from @brandond here: https://github.com/rancher/rke2/issues/3108#issuecomment-1167761927

Since we are using the vsphere cloud provider we cannot use the top level `node-ip` as it is overwriten by the provider. So we are setting `kubelet-arg+: ["node-ip=1.1.1.1"]`

Still the issue remains, nodes will inconsistently join the cluster. See the error below about what the kubelet says. A restart usually resolves the issue.

**Steps To Reproduce:**
- Deploy on vsphere with the following configuration:
```
cloud-provider-name: rancher-vsphere
kubelet-arg+:
  - "node-ip=1.1.1.1"
token: <YOUR TOKEN>
server: <YOUR SERVER>
```
(I've tried with `kubelet-arg+` and `kubelet-arg` to the same effect)
- Recreate the same node a couple of times with the same name+IP
- Notice that sometimes the node hangs and repeats the error below in the kubelet log

**Expected behavior:**
The node joins correctly

**Actual behavior:**
The `kubelet` log shows:

```
"Eviction manager: failed to get summary stats"
"Failed to get node when trying to set owner ref to the node lease" err="nodes EXAMPLE not found"
"Error updating node status, will retry"
"Unable to update node status"
```

Restarting the RKE2 Agent process usually fixes the problem.

**Comment by braunsonm** [comment]
This seems to me at least to be some kind of timing issue that is happening with the networking and the cloud provider.. sometimes a sleep before starting rke2-agent will improve your chances of it coming online. But this shouldn't be required and it would be nice if RKE2 Agent would properly handle this restart or if there was a setting I could tweak to prevent this all together.

**Comment by brandond** [comment]
Can you attach the **complete** rke2-agent logs from systemd on an affected node, along with the contents of /var/log/pods on that node, and vsphere cloud controller pod logs from the same timeframe?

**Comment by braunsonm** [comment]
Understandable. However it's a bit difficult for me to provide in my work environment, especially considering `/var/log/pods/` **does** start to run some pods that are scheduled as daemonsets before being unable to join and the kubelet error message repeats. Unfortunately I wasn't able to see the logs of these pods before they were destroyed, kubelet cleans them up within a minute of them starting up.

It seems this is what happens:
1. The node starts up, and starts the rke2-agent process
2. It very briefly joins the cluster (can see it on the local cluster in the Rancher UI for a split second)
3. `/var/log/pods/` creates some folders for daemonset pods
4. The `/var/log/pods` folder is cleared and replaced with a single `kube-statem_kube-proxy` folder
5. Startup of the kube-system_kube-proxy folder seems normal with the exception of `Can't determine this node's IP, assuming 127.0.0.1`, but starts up nonetheless
6. kubelet repeats the message posted in the original issue.

During this process kubelet does not restart, but does show messages that the CNI is not ready yet which is understandable. This does seem to show that the node starts to sync and get scheduled pods because I see my own workloads start to get scheduled before it disconnects and gets stuck repeating the message in kubelet's logs

```
eviction_manager.go:254] "Evicition manager: failed to get summary stats" err="failed to get node info: node HOSTNAME not found"
nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes HOSTNAME not found" node="HOSTNAME"
kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node HOSTNAME: nodes HOSTNAME not found"
kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node HOSTNAME: nodes HOSTNAME not found"
kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node HOSTNAME: nodes HOSTNAME not found"
kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node HOSTNAME: nodes HOSTNAME not found"
kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node HOSTNAME: nodes HOSTNAME not found"
kubelet_node_status.go:447] "Unable to update node status" err="update node status exceeds retry count"
```

Is there anything specific that I might be able to provide you?

**Comment by braunsonm** [comment]
When a reboot of the node is done, the next time rke2-agent starts, the kube-proxy reports:
```
node.go:163] Successfully retrieved node IP: xyz
```

So it does seem to go back to what I said before about some kind of race condition with networking. However at this point networking is started up and operating, especially since the `rke2-agent` service `Wants=network-online.target` in systemd

**Comment by brandond** [comment]
> Is there anything specific that I might be able to provide you?

Yes, the stuff I asked for - the complete rke2-agent logs from systemd on the affected node, along with the kubelet log, the contents of /var/log/pods on that node (whatever you've got when it is stuck, along with whatever you can grab of the larger set for the daemonset), and the vsphere cloud controller pod logs from the same timeframe.  The containerd log file might also be interesting but I suspect this is all on the kubelet or cloud-controller side.

**Comment by brandond** [comment]
If you don't want to share the logs here for some reason, feel free to put them on dropbox/drive/whatever and send me an e-mail or find me on Rancher Users slack.

**Comment by brandond** [comment]
We're planning to update the CPI image versions for 1.22 and 1.23 as part of this month's releases.

cc @dereknola
