### ISSUE TITLE
Upgraded from 1.23.10+rke2r1 to 1.24.9+rke2r2 which resulted in the CNI uninstalling itself

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#3805]
**Environmental Info:**
RKE2 Version: 1.24.9+rke2r2

Node(s) CPU architecture, OS, and Version: N/A

Cluster Configuration:
3 servers, many agents

**Describe the bug:**
We upgraded from 1.23.10+rke2r1 to 1.24.9+rke2r2 which resulted in the calico release being uninstalled. We didn't change any configuration. My current hunch is there was a race condition in the helm job where one of the older version server nodes restarted when the api/etcd connection was lost. Ran the old cni helm job, which decided to uninstall due to version issues.

**Steps To Reproduce:**
I am unsure how to reproduce. 

**Expected behavior:**
CNI never uninstalls, even if there is a version mismatch (server node wants a lower version than what is installed.)

**Actual behavior:**
Some reason CNI was uninstalled. Calico System namespace was removed, and the Installation resource was missing.

**Additional context / logs:**
Even after restarting the rke2-server it didn't apply a new Installation file. I had to pull one from another cluster that way we can get CNI re-installed. Along with rebooting each node.

**Comment by brandond** [comment]
The helm install job will be retried until it completes, so the CNI chart will be updated eventually once you finish upgrading all the nodes, assuming you finish upgrading them all. If you leave some of them on an older version, and restart them partway through the upgrade process, yes that would likely cause problems.

**Comment by brandond** [comment]
One server going down for an upgrade should not cause the other server to fail and restart. Even if that does happen for some reason, the chart will get reconciled when the affected server is upgraded and also receives the new chart. Although things may be disrupted temporarily, with time it should resolve. Can you identify from the logs the specific sequence of events?

We're aware that the current handling of chart upgrades can occasionally have some rough edges, but I have never seen it get stuck in an unresolvable state.

**Comment by mitchellmaler** [comment]
Do you know what would cause the rke2-calico release to be removed without changing any of the cni config in the config yaml file? Would a rke2-server instance that was restarted be able to do this when running the manifests, or should it not be possible? Is there a way to disable helm downgrades or uninstalls of critical components once they are in place, that way we can stop this from happening again?

I am unable to find the logs that point to it being uninstalled.

**Comment by brandond** [comment]
A Helm job is triggered whenever the Job generated by rendering the HelmChart+HelmChartConfig changes. This could be a change to values, chart repo, version, etc. The script executed in the Job will attempt to install or upgrade the chart, depending on whether it is currently installed or not. If the upgrade fails, it will uninstall and reinstall the chart. Since the Helm jobs for bootstrap charts (including the CNI) run with host network, and talk to the local apiserver, this should be fine.
