### ISSUE TITLE
Docs for airgapped install - not really airgapped because of SELinux RPM deps

### ISSUE THREAD

**Issue by netikras** [rancher/rke2#3817]
Currently, air-gapped installation instructions explain that if I'm running SELinux, I must install a set of additional RPM packages. Most of the packages are standard RHEL packages and are likely to be mirrored in the local repository (inside the company network, verified and approved by security chaps), while the rke2-specific ones come from a separate repository. This is not a valid option for an air-gapped system, that's only accessible via LAN/intranet and has no way to reach the internet.

What can you offer in a case like this? How do I get those RPMs installed on an offline system? Is there a way to pre-fetch those RPMs in advance so I could scp them into the server and install them manually? If so - where from? This is undocumented.

The system in question is a RockyLinux 9 setup. Even with a hacky access to RKE2 repo for rhel8 I can only install rke2-selinux, but not rke2-common because of some GPG error, so I'm not even sure how to go around that in a semi-airgapped system, let alone a completely air-gapped one.

```
[root@localhost ~]# yum install rke2-common
Last metadata expiration check: 0:09:54 ago on Fri Jan 20 17:03:14 2023.
Dependencies resolved.
===========================================================================================================
 Package             Architecture   Version                         Repository                        Size
===========================================================================================================
Installing:
 rke2-common         x86_64         1.18.20~rke2r1-0.el8            rancher-rke2-1-18-latest          34 M

Transaction Summary
===========================================================================================================
Install  1 Package

Total size: 34 M
Installed size: 154 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm: Already downloaded                                 
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Problem opening package rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
[root@localhost ~]# 
[root@localhost ~]# find / -name rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm
/var/cache/dnf/rancher-rke2-1-18-latest-32cda30a2173fd04/packages/rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm
[root@localhost ~]# rpm -Uv /var/cache/dnf/rancher-rke2-1-18-latest-32cda30a2173fd04/packages/rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm
warning: Signature not supported. Hash algorithm SHA1 not available.
error: /var/cache/dnf/rancher-rke2-1-18-latest-32cda30a2173fd04/packages/rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID e257814a: BAD
error: /var/cache/dnf/rancher-rke2-1-18-latest-32cda30a2173fd04/packages/rke2-common-1.18.20~rke2r1-0.el8.x86_64.rpm cannot be installed
```

**Comment by brandond** [comment]
Please install a more recent release of RKE2. The 1.18 release series is ancient and has been end-of-life for approximately 18 months. Current supported release versions have packages that use SHA256 GPG signatures which will install without error.

**Comment by netikras** [comment]
@brandond How do I do that? I'm merely following the docs on a fresh install and this is what I'm getting.

**Comment by brandond** [comment]
Ah I see. The docs could probably make it more clear that 1.18 is an example repo stanza. Replace `1.18` with the Kubernetes minor version you'd like to use - `1.23` through `1.26`.

As for the question about how to get the RPMs - how do you install and update the base operating system packages on your host? If you don't have tooling to maintain an airgapped yum repo, you can find the packages themselves at:
* https://github.com/rancher/rke2-packaging/releases
* https://github.com/rancher/rke2-selinux/releases

You will need to figure out how to download and install the rke2-selinux dependencies from your base operating system repos as well.

**Comment by netikras** [comment]
@brandond YESS!! These links are the missing parts I was looking for!

I'm installing OS packages from a pre-approved set of repositories inside the company network. rke2 repo (as well as hundreds of others) is not mirrored there. That's why I'm looking for the means to install rke dependencies in offline mode.

Is it possible to make the docs:
- reflect the repo version clarification given by you (the v1.8 incident) and its relation to the Kubernetes version
- reflect those 2 links to */releases/ as an alternative for truly offline install

?
