### ISSUE TITLE
Recommend may_detach_mounts sysctl added to install instructions for RHEL 7

### ISSUE THREAD

**Issue by bordenit** [rancher/rke2#3829]
The may_detach_mounts sysctl still seems to be needed with RHEL 7. I had this issue in the past with kubespray as well where the cluster. https://github.com/kubernetes-sigs/kubespray/issues/8622

Recommending updates to knowledge articles if using RHEL 7 to avoid containers getting stuck in terminating unless there is an alternative. This is potentially something that docker and crio do, but for some reason containerd install does not add this sysctl.

**Comment by brandond** [comment]
I've not seen any reports of containers getting stuck terminating on recent releases of Kubernetes. Can you provide more information on what you're experiencing?

**Comment by bordenit** [comment]
On new v1.24.9 install containers were stuck in terminating for 3 days, through the weekend. Added the may_detach_mounts sysctl we used for previous kubespray clusters and the pods resolved themselves, as they also did with Kubespray. Just saying it's still a containerd thing for RHEL 7 on our 8 clusters. https://github.com/containerd/containerd/issues/3667#issuecomment-652901331

**Comment by brandond** [comment]
Hmm. We test every release on EL7 as a supported platform and haven't run into this as something that needs to be resolved. Under what circumstances were you seeing the pods get stuck?

**Comment by brandond** [comment]
x-ref: https://bugzilla.redhat.com/show_bug.cgi?id=1441737 - this appears to be EL7 specific; I suspect that since we test EL7 on AWS the kernel we're using doesn't have or need this sysctl to be set.

**Comment by bordenit** [comment]
Yes, it's only a RHEL 7, CentOS specific issue with containerd. It's not something you will notice first day, maybe not even first week, but eventually if not set you'll log in and see a few to a few hundred pods stuck in terminating. We never seemed to have a problem with Docker as the Docker installer set it.

**Comment by brandond** [comment]
Well not just EL7 but EL7 running the stock EL7 kernel. If you're running on a cloud provider with one of their custom kernels, the sysctl is even available.

**Comment by bordenit** [comment]
@brandond Yeah, that's strange. We build from the AWS RHEL 7.9 AMI as the starting point in GovCloud. I assume it's the same RHEL 7.9 as everything else available in AWS. It's a problem that is probably going to go away when everyone migrates to new OS over the next year, so feel free to close this request if desired.


If anyone else reads this, if you have RHEL 7.9, and you start seeing your pods get stuck in terminating and start to fill your terminal with multiple pods with the same name in terminating, then add the may_detach_mounts sysctl and plan to update to RHEL 8 (or something else).
