### ISSUE TITLE
Bump RKE2 KDM version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#383]
Update the RKE2 release version accordingly in KDM channels-rke2.yaml for RKE2 release.
Since we will ship as v1.18.9+rke2 this will be the new value needed [on line 2 of this file](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/channels-rke2.yaml#L2).

**Comment by davidnuzik** [comment]
To be tested after RKE2 GA release which is planned for 10/4 but before Rancher GA release.
Endpoint: https://update.rke2.io/v1-release/channels

Once it's time I will assign the issue over to QA. For now I hold onto it since there is nothing yet to test until the right time.

**Comment by davidnuzik** [comment]
Endpoint looks good. I forgot we need Rancher release (well, we should ideally just wait and check; we could use our own data.json but I think we shoudl wait) to check in Rancher.

So for checking in Rancher we'll wait until we have the rancher release out and just double-check and ensure all looks good there.

**Comment by ShylajaDevadiga** [comment]
Validated. 
```
rke2": {
  "releases": [
   {
    "maxChannelServerVersion": "v2.5.99",
    "minChannelServerVersion": "v2.5.0-rc1",
    "version": "v1.18.9+rke2r1"
   }
  ]
```
