### ISSUE TITLE
Keys and Certificate Files Need to be Generated with Tighter Permissions for CIS

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#385]
Certificate and keys are generated with file permissions of `644` and should be generated with `600`.

How to reproduce: 

```sh
stat -c %n\ %a /var/lib/rancher/rke2/server/tls/*.key
```

Side note, this was marked as skipped in the security-scan pr for RKE2. That's been remediated.

**Comment by cjellick** [comment]
Relevant controls:
- 1.1.20 Ensure that the Kubernetes PKI certificate file permissions are set to 644 or more restrictive
- 1.1.21 Ensure that the Kubernetes PKI key file permissions are set to 600

So, .crt files can remain 644 but .key files need to be 600.

We should do this regardless of whether we are in "cis mode" or not.

**Comment by briandowns** [comment]
This issue was entered in error. Closing.
