### ISSUE TITLE
rke2 blows up on hostname change

### ISSUE THREAD

**Issue by KyleSanderson** [rancher/rke2#3857]
**Environmental Info:**
RKE2 Version: 1.22

Node(s) CPU architecture, OS, and Version: amd64

Cluster Configuration: Single Node

**Describe the bug:**

If you change the hostname, it creates new deployments and never removes the old ones. Compounding on the problem is there's dead finalizers on these workloads, and force deleting the old ones effectively brick the cluster.

**Steps To Reproduce:**

- Installed RKE2: 
- had a sandwich while the binaries were being pulled.
- enabled the systemd unit and changed service-node-port-range through the provided yml.
- started rke2
- had a single CPU, so the deployment stalled on Canal and did nothing for an hour
- had another sandwich and rebooted the host with 2 CPUs
- deployment finished, saw the hostname was localhost
- set the hostname from my DHCP and DNS server to bigbilly
- rebooted the host
- duplicates of every pod were present with both new and old name
- tried to fix cluster using native k8s tools, did not go well

**Expected behavior:**

Bigbilly was able to connect with bigsally as a worker node.

**Actual behavior:**

Bigbilly had to be completely reinstalled (which deleted the config yaml directory which wasn't impressive), and seems a bit healthier now.

**Additional context / logs:**

Chicken on a nice rye.

**Comment by brandond** [comment]
Yes, don't do that. Kubernetes generally expects that nodes will not change their names or addresses once they've joined the cluster.  If you change the server IP, you'll probably need to reset the etcd cluster membership. If you change the hostname, you'll need to delete the node with the original name from the cluster.

**Comment by KyleSanderson** [comment]
> Yes, don't do that. Kubernetes generally expects that nodes will not change their names or addresses once they've joined the cluster. If you change the server IP, you'll probably need to reset the etcd cluster membership. If you change the hostname, you'll need to delete the node with the original name from the cluster.

I understand that, but with k8s you can just reissue the certificates on SNI change and adjust etcd accordingly to recover. With rke2 the core product handles this situation worse than upstream with the completely duplicated deployments, and leaves an end user with little recourse to recover.

So while an "enterprise" user won't encounter this frequently, an end user trying the product will suffer when an address or hostname changes, and thus think the product is not anywhere near stable (and worse, leave with the impression it's broken). rke2 from an outside (/my) perspective is batteries included.

**Comment by brandond** [comment]
When you changed the hostname you created a new node. The node by the old name will eventually transition to NotReady, but there is no good safe way for us to know that the old node is never coming back, so it is on you to delete it yourself.

**Comment by bendemott** [comment]
Spent like 4 hours trying to recover an RKE2 cluster, then found this post.
DHCP issued the servers hostname - but rke2 installed before that could happen. Joy.

**Comment by brandond** [comment]
Please demonstrate how any other distro handles node hostname changes better.
