### ISSUE TITLE
Validate rhel9 on rke2

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#3860]
Validate rke2 on rhel 9 on selinux enabled mode on rke2 version v1.26

**Comment by bguzman-3pillar** [comment]
Test validated until now and passed successfully:
Rhel9 `ami-0560d5a32eec08262`

1. Fresh Installation and run Sonobuoy Conformance tests
2. Upgrade Traditional with workloads
3. Certificate Rotation - Full Flow
4. Secrets Encryption - Full Flow
