### ISSUE TITLE
rke2 is using 200% CPU

### ISSUE THREAD

**Issue by KyleSanderson** [rancher/rke2#3870]
**Environmental Info:**
RKE2 Version: v1.24.10+rke2r1

Node(s) CPU architecture, OS, and Version: amd64, plow

Cluster Configuration: Single node

**Describe the bug:**
 Excessive CPU usage for fun.

**Steps To Reproduce:**

- Installed RKE2.

**Expected behavior:** Not using 2 full cores.

**Actual behavior:** Uses atleast 200%.

**Additional context / logs:**

INFO[25023] Applying local snapshot retention policy: retention: 5, snapshotPrefix: etcd-snapshot-rke2, directory: /var/lib/rancher/rke2/server/db/snapshots 
INFO[25023] Removing local snapshot /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-rke2-1675468800 
INFO[25023] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
INFO[25023] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete 
INFO[36029] Updating TLS secret for kube-system/rke2-serving (count: 10): map[listener.cattle.io/cn-10.100.200.10:10.100.200.10 listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-__1-f16284:::1 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc:kubernetes.default.svc listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rke2:rke2 listener.cattle.io/fingerprint:SHA1=B483BFA44A3C8FF13DAF6A62A2F4D2C514DD1499] 
I0206 15:03:31.766137      20 event.go:294] "Event occurred" object="kube-system/rke2-multus" fieldPath="" kind="HelmChart" apiVersion="helm.cattle.io/v1" type="Normal" reason="ApplyJob" message="Applying HelmChart using Job kube-system/helm-install-rke2-multus"
I0206 15:03:31.767596      20 event.go:294] "Event occurred" object="kube-system/rke2-coredns" fieldPath="" kind="HelmChart" apiVersion="helm.cattle.io/v1" type="Normal" reason="ApplyJob" message="Applying HelmChart using Job kube-system/helm-install-rke2-coredns"
I0206 15:03:31.767626      20 event.go:294] "Event occurred" object="kube-system/rke2-metrics-server" fieldPath="" kind="HelmChart" apiVersion="helm.cattle.io/v1" type="Normal" reason="ApplyJob" message="Applying HelmChart using Job kube-system/helm-install-rke2-metrics-server"
WARN[53741] Proxy error: read failed: read tcp 127.0.0.1:9345->127.0.0.1:54286: read: connection reset by peer 
INFO[68223] Saving etcd snapshot to /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-rke2-1675728000 
INF snapshot/v3_snapshot.go:65 > ts=2023-02-07T00:00:00.039Z msg=created temporary db file path=/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-rke2-1675728000.part
INF v3@v3.5.4-k3s1/maintenance.go:211 > ts=2023-02-07T00:00:00.050Z logger=client msg=opened snapshot stream; downloading
INF snapshot/v3_snapshot.go:73 > ts=2023-02-07T00:00:00.052Z msg=fetching snapshot endpoint=https://127.0.0.1:2379
INF v3@v3.5.4-k3s1/maintenance.go:219 > ts=2023-02-07T00:00:00.515Z logger=client msg=completed snapshot read; closing
INF snapshot/v3_snapshot.go:88 > ts=2023-02-07T00:00:00.546Z msg=fetched snapshot endpoint=https://127.0.0.1:2379 size=7.8 MB took=now
INF snapshot/v3_snapshot.go:97 > ts=2023-02-07T00:00:00.546Z msg=saved path=/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-rke2-1675728000
INFO[68223] Applying local snapshot retention policy: retention: 5, snapshotPrefix: etcd-snapshot-rke2, directory: /var/lib/rancher/rke2/server/db/snapshots 
INFO[68223] Removing local snapshot /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-rke2-1675512000 
INFO[68223] Reconciling etcd snapshot data in rke2-etcd-snapshots ConfigMap 
INFO[68223] Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete

**Comment by brandond** [comment]
Can you show which specific process is using 2 core? Perhaps the output of `ps -auxfww`, `top`, `systemd-cgtop` or anything else that actually shows the CPU usage you're reporting?
