### ISSUE TITLE
Airgap documentation asks for image download twice (redundant)

### ISSUE THREAD

**Issue by horihel** [rancher/rke2#3871]
**Environmental Info:**
RKE2 Version: no version (documentation issue)

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**
Both in Tarball and Private-Registry mode, the documentation lets us prepare all necessary images. *-core* and *-canal* for example in the first two chapters. After this, all necessary images are deployed in the system.

Later (in https://docs.rke2.io/install/airgap#rke2-installsh-script-install), the documentation asks to download the legacy full archive for the install script to consume. This is redundant in all cases I can imagine, as either the legacy image or "core" and "addon" images have already been deployed earlier.

I think the image download in the last chapter can be safely removed, which saves about 1GB of download for most users. I might be wrong though.

**Additional context / logs:**

Ideally get.rke2.io could be amended to download a staging directory and consume the staged content (it can already consume a legacy image). If you think this would be a welcome addition, I might be able to contribute. Kindly point me to the repo that contains the install script then.

**Comment by brandond** [comment]
I'm not sure I understand which bit asks you to download things twice. That page covers multiple different ways to airgap; either using a private registry or by placing the tarballs on the nodes for direct import into the image store. You're not expected to do both.

**Comment by horihel** [comment]
you're asked to do one of them and after that you're asked to install rke2, either by installing the binary manually, or using install.sh
and _there_ it asks you do download the image again.

**Comment by brandond** [comment]
Are you referring to the example at the bottom that shows you how INSTALL_RKE2_ARTIFACT_PATH can be used?  That's just an example that brings everything together, you don't have to do EVERYTHING shown on that page.

**Comment by brandond** [comment]
The install script is right here in this repo if you want to look at it:
https://github.com/rancher/rke2/blob/master/install.sh

I believe it will already do most of what you want with regards to consuming staged content.

**Comment by horihel** [comment]
Then I definitely misunderstood this section. Sorry for that. 
Keep in mind that people might refer to this - especially when step 1 explicitely states to download the images.
Though downloading the additional images doesn't hurt in any form.

wrt the install script: it does. I'd consider adding support for the newer images and using the download bits to get the needed files instead of downloading them manually.

**Comment by brandond** [comment]
The install script doesn't know which CNIs or out of tree cloud providers you might use, which is why it only downloads the binaries, and leaves the airgap images to the user.

**Comment by horihel** [comment]
unfortunately many of my users want airgap (without proxy) ;)
i'll leave it at that. If i find a non-intrusive way to add support for the new images to install.sh, i'll file a PR.
Thank you for the clarification.
