### ISSUE TITLE
When running with CIS profile on an agent node, etcd user is required and shouldn't be

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#388]
etcd user should only be required when we are on a sever node, because those are the nodes that launch etcd.

Steps to repro:
1. Launch an agent node. 
2. Turn on the cis profile. Right now I am doing this via env vars:
```
cat /etc/sysconfig/rke2-agent
HOME=/root
RKE2_SELINUX=true
RKE2_CIS_PROFILE="cis-1.5"
```
(This was a cent system)
3. check logs: `journalctl -u rke2-agent -f`

Actuall result:
System errors out with:
```
Sep 29 13:58:30 craig-cent8-rke2 rke2[2360359]: time="2020-09-29T13:58:30Z" level=fatal msg="user: unknown user etcd\n"
Sep 29 13:58:30 craig-cent8-rke2 systemd[1]: rke2-agent.service: Main process exited, code=exited, status=1/FAILURE
Sep 29 13:58:30 craig-cent8-rke2 systemd[1]: rke2-agent.service: Failed with result 'exit-code'.
```

Expected result:
System should not be checking for etcd user on agent nodes.

**Comment by rancher-max** [comment]
#### Validated on beta23

Do not need etcd user on agents anymore. The only required step for agents when using `profile: cis-1.5` is to ensure the node has kernel params set properly.
