### ISSUE TITLE
1.24.10+rke2r1 using dockerd instead of containerd

### ISSUE THREAD

**Issue by joeburke30** [rancher/rke2#3889]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.24.10+rke2r1 (1ccdce2571291649b9414af1f269f645c3fe4002)
go version go1.19.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux myhostname #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

Cluster Configuration:
1 server 

**Describe the bug:**
trying to use cri-dockerd instead of containerd.   

cri-dockerd installed (followed Mirantis) and running at /run/cri-dockerd.sock        version: cri-dockerd 0.3.1 (7e528b98)
docker-ce and components running   Docker version 23.0.0, build d7573ab

all of the following attmepts failed -- etcd does not start

rke2 --debug server --container-runtime-endpoint /run/cri-dockerd.sock  
rke2 --debug server --container-runtime-endpoint unix:///run/cri-dockerd.sock  
rke2 --debug server --kubelet-arg "cri-socket=/run/cri-dockerd.sock container-runtime-endpoint=/run/cri-dockerd.sock" --container-runtime-endpoint /run/cri-dockerd.sock

**Steps To Reproduce:**

1. Fresh install of Debian 11
2. install docker 
- docker-buildx-plugin_0.10.2-1~debian.11~bullseye_amd64.deb
- docker-ce-cli_23.0.0-1~debian.11~bullseye_amd64.deb
- docker-ce-rootless-extras_23.0.0-1~debian.11~bullseye_amd64.deb
- docker-ce_23.0.0-1~debian.11~bullseye_amd64.deb

3. Followed: https://www.mirantis.com/blog/how-to-install-cri-dockerd-and-migrate-nodes-from-dockershim/
- loaded cri-dockerd-0.3.1.amd64.tgz

4. installed RKE2 using airgapped method.
5. downloaded
- rke2-images-all.linux-amd64.txt
- rke2-images.linux-amd64.tar.gz
- rke2-images.linux-amd64.txt
- rke2.linux-amd64.tar.gz
- sha256sum-amd64.txt

6. config.yaml

#container-runtime-endpoint: "unix:///run/cri-dockerd.sock"
write-kubeconfig-mode: 644
#profile: "cis-1.23"
token: mysupersecrettoken
tls-san:
  - "192.168.yy.xxx"

System
- Installed RKE2: 
INSTALL_RKE2_ARTIFACT_PATH=/opt/rke2_files/boot
INSTALL_RKE2_METHOD=tar
INSTALL_RKE2_TAR_PREFIX=/opt/rke2
INSTALL_RKE2_TYPE=server
INSTALL_RKE2_VERSION=v1.24.10+rke2r1
KUBECONFIG=/etc/rancher/rke2/rke2.yaml

Ran rke2-install script
log:
[INFO]  staging local checksums from /opt/rke2_files/boot/sha256sum-amd64.txt
[INFO]  staging gzip airgap image tarball from /opt/rke2_files/boot/rke2-images.linux-amd64.tar.gz
[INFO]  staging tarball from /opt/rke2_files/boot/rke2.linux-amd64.tar.gz
[INFO]  verifying airgap tarball
grep: /tmp/rke2-install.v3fU88Xz7x/rke2-images.checksums: No such file or directory
[INFO]  decompressing airgap tarball to /var/lib/rancher/rke2/agent/images
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /opt/rke2
[INFO]  updating tarball contents to reflect install path
[INFO]  moving systemd units to /etc/systemd/system
[INFO]  install complete; you may want to run:  export PATH=$PATH:/opt/rke2/bin

**Expected behavior:**
with --container-runtime-endpoint pointing to /run/cri-dockerd.sock    rke2 and kubernetes will start.

**Actual behavior:**
without any --container-runtime-endpoint  value -- containerd starts and is used --- kube and rke2 work as expected.
But, with --container-runtime-endpoint having a value. etcd does not start.

**Additional context / logs:**
happy to provide, please recommend.

**Comment by brandond** [comment]
> all of the following attmepts failed -- etcd does not start

Can you post logs as to **why** it doesn't start? What are the errors you see in the rke2, kubelet, or cri-dockerd logs? Can you confirm that you've configure the kubelet to use correct cgroup driver for whatever mode you've put dockerd in? If you're bringing your own container runtime, it is on you to configure both the runtime and the kubelet correctly, since RKE2 cannot manage them in coordination.

**Comment by HILLJAY1019** [comment]
Is there any follow-up, can rke2 and docker share containerd？
