### ISSUE TITLE
Support for Rancher Logging v2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#39]
Make sure static pods go into the default logging v2 and also the supervisor process log.
Basically we need to ensure all logs can get into Rancher log v2.

**Comment by rancher-max** [comment]
#### Validated in rancher v2.5.0-alpha1 using rke2 beta11.

- 3 server nodes, 3 agent nodes
- After enabling logging v2, all server and agent nodes had logs at the path: `/var/log/containers/*rke*.log`
- Logs visible on both frontend and backend
- Logging v2 app deploys successfully and overall appears functional
