### ISSUE TITLE
Error Installing on CentOS 8.6

### ISSUE THREAD

**Issue by ccravens** [rancher/rke2#3903]
**Environmental Info:**
RKE2 Version: 
I tested several releases from 1.23.6 - 1.26.0 with the same result

Node(s) CPU architecture, OS, and Version: 
```bash
$ sudo uname -r
4.18.0-448.el8.x86_64
$ sudo uname -a
Linux ip-192-168-32-10.us-east-1.compute.internal 4.18.0-448.el8.x86_64 #1 SMP Wed Jan 18 15:02:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ sudo rpm -q centos-stream-release
centos-stream-release-8.6-1.el8.noarch
```

Cluster Configuration:
N/A - Can't Install

**Describe the bug:**
Looks like the semodule errors when installing on latest of CentOS 8:
```bash
Rancher RKE2 Common (stable)                                                                                               12 kB/s | 2.4 kB     00:00    
Importing GPG key 0xE257814A:
 Userid     : "Rancher (CI) <ci@rancher.com>"
 Fingerprint: C8CF F216 4551 26E9 B9C9 18BE 925E A29A E257 814A
 From       : https://rpm.rancher.io/public.key
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                  1/1 
  Running scriptlet: container-selinux-2:2.195.1-1.module_el8.8.0+1254+78119b6e.noarch                                                                1/4 
  Installing       : container-selinux-2:2.195.1-1.module_el8.8.0+1254+78119b6e.noarch                                                                1/4 
  Running scriptlet: container-selinux-2:2.195.1-1.module_el8.8.0+1254+78119b6e.noarch                                                                1/4 
  Running scriptlet: rke2-selinux-0.11-1.el8.noarch                                                                                                   2/4 
  Installing       : rke2-selinux-0.11-1.el8.noarch                                                                                                   2/4 
  Running scriptlet: rke2-selinux-0.11-1.el8.noarch                                                                                                   2/4 
Conflicting name type transition rules
Binary policy creation failed at /var/lib/selinux/targeted/tmp/modules/400/rke2/cil:324
Failed to generate binary
semodule:  Failed!
```

**Steps To Reproduce:**
Install RKE2 on `CentOS-Stream-8-x86_64-20230125-dvd1.iso` via:
`curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION="v{{ rke2_version }}+{{ rke2_rc }}" sudo -E sh -`

**Expected behavior:**
Expect RKE2 installation to be successful

**Actual behavior:**
SELinux modules fail to compile during installation

**Additional context / logs:**
Submitted this issue: https://github.com/rancher/rke2-selinux/issues/33
But not sure if those issues are monitored or responded to.

**Comment by brandond** [comment]
* Same issue as https://github.com/k3s-io/k3s-selinux/issues/36
cc @galal-hussein

**Comment by brandond** [comment]
Note that we don't technically support Stream as it is a rolling release distro and probe to this sort of breakage. Ref: https://docs.rke2.io/install/requirements#linux

**Comment by ccravens** [comment]
Thank you @brandond! I have moved over to RHEL 8 to stay consistent with the supported OS.

Given that this issue may likely show up in a future RHEL release, would you like me to keep this issue open as an item that needs to be addressed or close it?

**Comment by caroline-suse-rancher** [comment]
I'm going to close this issue for now as we can reference it or reopen in the future if needed.
