### ISSUE TITLE
Statefulset pod stucks in status terminating while the node is down

### ISSUE THREAD

**Issue by hitwjj** [rancher/rke2#3913]
**Environmental Info:**
RKE2 Version: v1.20.14+rke2r1

Node(s) CPU architecture, OS, and Version: 

rhel8 with VM running on ESXi
Cluster Configuration:

3 servers, 6 agents
**Describe the bug:**

with a RKE2 cluster, if I powered off one of the worker nodes, the Pods of Statefulset running on this node become Terminating forever(4 hours so far) and not changed to Terminated status, and the pod is not reschedulled to other healthy nodes.
The pod of deployment also stuck in Terminating status however, a new pod is schedulled to other healthy nodes.
**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

the pod on a powered off node should be terminated in 5 minutes and schedulled to other healthy nodes
**Actual behavior:**

the pod on a powered off node stuck in Terminating status
**Additional context / logs:**

**Comment by brandond** [comment]
This is core Kubernetes behavior, not anything specific to RKE2. NotReady nodes cannot be reasoned about. Kubernetes doesn't know if it's actually still running your StatefulSet pods but disconnected from the apiserver by a network outage, or rebooting, or outside in a dumpster. It will not replace the StatefulsSet pods until the node comes back online and tells Kubernetes that the pods have been deleted, or you delete the node from the cluster yourself.
