### ISSUE TITLE
Unrelated folder created on TAR mode installation on Linux system

### ISSUE THREAD

**Issue by rahendatri** [rancher/rke2#3918]
**Environmental Info:**
RKE2 Version: 

v1.24.10+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux localhost.localdomain 5.14.0-115.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun 20 11:03:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

Regardless the fact that it's on Linux system, RKE2 installation in TAR mode creates a folder named 'rke2-windows'

**Steps To Reproduce:**

```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_METHOD=tar sh -
```

- Installed RKE2: v1.24.10+rke2r1

**Expected behavior:**

```
[user@localhost ~]$ ll /usr/local/share/rke2-windows/
ls: cannot access '/usr/local/share/rke2-windows/': No such file or directory

```

**Actual behavior:**

```
[user@localhost ~]$ ll /usr/local/share/rke2-windows/
total 0

```

**Additional context / logs:**

**Comment by dereknola** [comment]
This is an issue with how we package the rpm, https://github.com/rancher/rke2/blob/master/scripts/package-bundle#L24, we grab everything under `share` which includes an empty `rke2-windows` folder.

**Comment by est-suse** [comment]
Node(s) CPU architecture, OS, and version:
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```

Cluster Configuration:
```
NAME              STATUS   ROLES                       AGE    VERSION
ip-172-31-39-86   Ready    control-plane,etcd,master   116s   v1.26.3+rke2r1

```

config.yaml
```
write-kubeconfig-mode: 644
debug: true
token: VOIDSTARLABS
cni: cilium
```

Testing Steps:
```
sudo mkdir -p /etc/rancher/rke2/ && sudo cp config.yaml /etc/rancher/rke2/config.yaml
Install rke2: sudo curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.26.3-rc1+rke2r1 sh-

```
Results:

$ ll /usr/local/share/rke2-windows/
```
ls: cannot access '/usr/local/share/rke2-windows/': No such file or directory
```
