### ISSUE TITLE
Install Rke2 on EC2 install invallid option --y

### ISSUE THREAD

**Issue by haidangbk** [rancher/rke2#3929]
![image](https://user-images.githubusercontent.com/46040940/220242689-8b6a7eaf-daeb-4bc1-8359-d37c4f28296e.png)

**Comment by haidangbk** [comment]
> ![image](https://user-images.githubusercontent.com/46040940/220242689-8b6a7eaf-daeb-4bc1-8359-d37c4f28296e.png)

help me

**Comment by brandond** [comment]
Please fill out the issue template, it asks for critical information. For example, what Linux distribution are you attempting to install on?

**Comment by haidangbk** [comment]
> Please fill out the issue template, it asks for critical information. For example, what Linux distribution are you attempting to install on?

I'm using amazon-linux-2

**Comment by brandond** [comment]
We don't technically support Amazon Linux. The failure is coming from https://github.com/rancher/rke2/blob/master/install.sh#L454 as we do not detect the package manager for that distro. Please use a distro from the list in the docs: https://docs.rke2.io/install/requirements#linux

**Comment by STARRY-S** [comment]
Try adding the `INSTALL_RKE2_METHOD=tar` environment variable.
https://docs.rke2.io/install/configuration#configuring-the-linux-installation-script
