### ISSUE TITLE
Incorrect EnvironmentFile in rke2-server systemd unit

### ISSUE THREAD

**Issue by mlschuler** [rancher/rke2#3930]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.24.9+rke2r2 (2f4571a879954e1ea8d4560023eaf57c567df737)
go version go1.18.7b7

Node(s) CPU architecture, OS, and Version: 
Linux node1 5.14.21-150400.24.46-default #1 SMP PREEMPT_DYNAMIC Thu Feb 9 08:38:18 UTC 2023 (2d95137) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Setup Control Node from Rancher GUI, Create new OnPrem Cluster behind http proxy

**Describe the bug:**
Systemd Unit File of rke2-server is incorrect
EnvironmentFile=-/opt/rke2/lib/systemd/system/%N

would be correct, but instead
EnvironmentFile=-/opt/rke2/lib/systemd/system/%N.env
is deployed which is wrong

**Steps To Reproduce:**

- Installed RKE2: 
http_proxy="http://g02depxmche000.g02.fujitsu.local:81" https_proxy="http://g02depxmche000.g02.fujitsu.local:81" no_proxy=".xsnet,localhost,127.0.0.1,192.168.29.40" curl --insecure -fL https://bbtrz247.xsnet/system-agent-install.sh | sudo http_proxy="http://g02depxmche000.g02.fujitsu.local:81" https_proxy="http://g02depxmche000.g02.fujitsu.local:81" no_proxy=".xsnet,localhost,127.0.0.1,192.168.29.40" sh -s - --server https://bbtrz247.xsnet --label 'cattle.io/os=linux' --token r7n9bw2r5nrcd28v26j9t4lsbr97qqb8jcf8jzxrn82hnk879ccwkx --ca-checksum 196742906bb88c33141611ebf164a523545f9714d46f6be54d8fabe92a5260f4 --etcd --controlplane

After that there is no HTTP Proxy in rke2-server, since the Unit File is incorrect

**Expected behavior:**
rke2-server must be able to access the Internet via HTTP Proxy

**Actual behavior:**
rek2-server has no access to the Internet

**Additional context / logs:**

with provided EnvironmentFile the following status is shown -> no access to the Internet

node1:~ # systemctl status rke2-server
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
     Active: activating (start) since Tue 2023-02-21 08:18:48 CET; 27s ago
       Docs: https://github.com/rancher/rke2#readme
    Process: 1891 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 1895 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 1897 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 1898 (rke2)
      Tasks: 8
     CGroup: /system.slice/rke2-server.service
             └─ 1898 "/opt/rke2/bin/rke2 server"

Feb 21 08:18:50 node1 rke2[1898]: time="2023-02-21T08:18:50+01:00" level=info msg="Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2"
Feb 21 08:18:50 node1 rke2[1898]: time="2023-02-21T08:18:50+01:00" level=warning msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2: not found in any file in /var/lib/rancher/rke2/agent/images: image not found"
Feb 21 08:18:50 node1 rke2[1898]: time="2023-02-21T08:18:50+01:00" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
Feb 21 08:18:50 node1 rke2[1898]: time="2023-02-21T08:18:50+01:00" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2"
Feb 21 08:18:54 node1 rke2[1898]: time="2023-02-21T08:18:54+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Feb 21 08:18:59 node1 rke2[1898]: time="2023-02-21T08:18:59+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Feb 21 08:19:04 node1 rke2[1898]: time="2023-02-21T08:19:04+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Feb 21 08:19:09 node1 rke2[1898]: time="2023-02-21T08:19:09+01:00" level=info msg="Waiting for cri connection: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""
Feb 21 08:19:09 node1 rke2[1898]: time="2023-02-21T08:19:09+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Feb 21 08:19:14 node1 rke2[1898]: time="2023-02-21T08:19:14+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"

**Comment by brandond** [comment]
> Systemd Unit File of rke2-server is incorrect
> `EnvironmentFile=-/opt/rke2/lib/systemd/system/%N`
> 
> would be correct, but instead
> `EnvironmentFile=-/opt/rke2/lib/systemd/system/%N.env`
> is deployed which is wrong

I'm not sure what you mean by this being "wrong"? `rke2-agent.env` or `rke2-server.env` is what we have always used for the RKE2 systemd units. The location of that file is moved from `/var/lib/systemd/system` to  `/opt/rke2/lib/systemd/system` if `/var/lib` is on a separate mount point. There are two other files also loaded from`/etc/default` and `/etc/sysconfig`, without the .env suffix. Is this difference perhaps what you're considering wrong? If so that is not correct; the behavior is intentional.

**Comment by brandond** [comment]
Also, note that the `system-agent-install.sh` (and `install.sh` from the RKE2 repo) do not persist variables or configuration into the RKE2 env files for you. If you're coming from K3s, this may be a source of confusion, as the K3s install script does do that for you.

**Comment by mlschuler** [comment]
what I mean is the following

node1:~ # ls /opt/rke2/lib/systemd/system
rke2-agent.env  rke2-server.env  rke2-server.service
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.env
HOME=/root
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.service
EnvironmentFile=-/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env

The proxy settings are in /var/lib/rancher/rke2/system-agent-installer/rke2-sa.env

**Comment by mlschuler** [comment]
Note that I did not install RKE2 using https://get.rke2.io but I used Creare a New Cluster from the Rancher GUI and configured my proxy settings in the Rancher GUI.

So do you recommend to manually copy  the procy settings  from /var/lib/rancher/rke2/system-agent-installer/rke2-sa.en to /etc/default/rke2-server?

Why is this not done automatically ?

**Comment by mlschuler** [comment]
OK. The following works, i.e. ,manually create /etc/default/rke2-server.

But, in my opinion, this is a workaround. This could be done in the system-agent-install.sh script as well !

See below:

node1:~ # http_proxy="http://g02depxmche000.g02.fujitsu.local:81" https_proxy="http://g02depxmche000.g02.fujitsu.local:81" no_proxy=".xsnet,127.0.0.1,localhost,192.168.29.41" curl --insecure -fL https://bbtrz247.xsnet/system-agent-install.sh | sudo http_proxy="http://g02depxmche000.g02.fujitsu.local:81" https_proxy="http://g02depxmche000.g02.fujitsu.local:81" no_proxy=".xsnet,127.0.0.1,localhost,192.168.29.41" sh -s - --server https://bbtrz247.xsnet --label 'cattle.io/os=linux' --token 656884kp72kbvdqzmgpdf4g9s7ssmht8t7hcsflvv6wqrt9f6m7tjw --ca-checksum 196742906bb88c33141611ebf164a523545f9714d46f6be54d8fabe92a5260f4 --etcd --controlplane
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29792    0 29792    0     0   175k      0 --:--:-- --:--:-- --:--:--  176k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[WARN]  /usr/local is read-only or a mount point; installing to /opt/rancher-system-agent
[INFO]  Determined CA is necessary to connect to Rancher
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://bbtrz247.xsnet/cacerts is an x509 certificate
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://bbtrz247.xsnet/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://bbtrz247.xsnet/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
[INFO]  Successfully downloaded Rancher connection information
[INFO]  systemd: Creating service file
[INFO]  Creating environment file /etc/systemd/system/rancher-system-agent.env
[INFO]  Enabling rancher-system-agent.service
Created symlink /etc/systemd/system/multi-user.target.wants/rancher-system-agent.service → /etc/systemd/system/rancher-system-agent.service.
[INFO]  Starting/restarting rancher-system-agent.service

node1:~ # systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
     Active: activating (start) since Wed 2023-02-22 09:15:57 CET; 3s ago
...

node1:~ # cp /var/lib/rancher/rke2/system-agent-installer/rke2-sa.env /etc/default/rke2-server
node1:~ # systemctl restart rke2-server.service

node1:~ # systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2023-02-22 09:19:12 CET; 8s ago

**Comment by ravarga** [comment]
In my opinion writing files manually defeats the purpose of Rancher. When a downstream cluster is deployed from within the Rancher UI there should be a propagation of user-defined environment variables like in this example proxy settings. While the documentation is valid for manually deployed clusters, automated clusters, especially when deployed on a large scale may require some additional external automation. 

Is it possible to enhance this so that variables are automatically propagated during downstream cluster deployment?

**Comment by brandond** [comment]
>```
> node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.service
> EnvironmentFile=-/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env
> ```

Is that **all** that's in that file? Can you show the complete contents of the `rke2-server.service` file, as well as the contents of any EnvironmentFiles that it references?

This is all technically part of Rancher's provisioning system - rancher-system-agent and system-agent-installer - and not RKE2. Can you confirm that you put the HTTP_PROXY and other environment variables in the "Agent Environment Vars" section of the cluster config? I believe those are supposed to be passed through to RKE2 as well, through the addition of the system-agent-installer EnvironmentFile.

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/370103/220571975-30d0fb64-f122-4f42-a7da-411c9100f9d9.png">

**Comment by brandond** [comment]
You might also see if using the uppercase versions of those env vars works any differently - the all-uppercase version is more common, and may be handled differently by the agent.

**Comment by mlschuler** [comment]
here you are. I have removed the hostname of the proxy for reasons of security.

I have configiured these values in the Rancher GUI "Agent Environent Vars" and will run a new test using capital letters now.

As I said /etc/default/rke2-server has been manually populated by myself.

node1:~ # cat /etc/systemd/system/rke2-server.service
[Unit]
Description=Rancher Kubernetes Engine v2 (server)
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target
Conflicts=rke2-agent.service

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/opt/rke2/lib/systemd/system/%N.env
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/opt/rke2/bin/rke2 server
ExecStopPost=-/bin/sh -c "systemd-cgls /system.slice/%n | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill"

node1:~ # cat /etc/default/rke2-server
https_proxy=http://<proxy>:81
http_proxy=http://<proxy>:81
no_proxy=.xsnet,127.0.0.1,localhost,192.168.29.41
node1:~ # cat /etc/sysconfig/rke2-server
cat: /etc/sysconfig/rke2-server: No such file or directory
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.env
HOME=/root
node1:~ #

**Comment by mlschuler** [comment]
This was the complete contents of the file /opt/rke2/lib/systemd/system/rke2-server.service

**Comment by mlschuler** [comment]
No improvement using capital letters of the environment variables.

node1:~ # HTTP_PROXY="http://g02depxmche000.g02.fujitsu.local:81" HTTPS_PROXY="http://g02depxmche000.g02.fujitsu.local:81" NO_PROXY=".xsnet,localhost,127.0.0.1,192.168.29.40" curl --insecure -fL https://bbtrz247.xsnet/system-agent-install.sh | sudo HTTP_PROXY="http://g02depxmche000.g02.fujitsu.local:81" HTTPS_PROXY="http://g02depxmche000.g02.fujitsu.local:81" NO_PROXY=".xsnet,localhost,127.0.0.1,192.168.29.40" sh -s - --server https://bbtrz247.xsnet --label 'cattle.io/os=linux' --token 9nwrm9rfzngmwktflkc4q6wc4zk9864hlgjpzppwpjsp9ntsv6ssb8 --ca-checksum 196742906bb88c33141611ebf164a523545f9714d46f6be54d8fabe92a5260f4 --etcd --controlplane
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29792    0 29792    0     0   954k      0 --:--:-- --:--:-- --:--:--  969k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[WARN]  /usr/local is read-only or a mount point; installing to /opt/rancher-system-agent
[INFO]  Determined CA is necessary to connect to Rancher
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://bbtrz247.xsnet/cacerts is an x509 certificate
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://bbtrz247.xsnet/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://bbtrz247.xsnet/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
[INFO]  Successfully downloaded Rancher connection information
[INFO]  systemd: Creating service file
[INFO]  Creating environment file /etc/systemd/system/rancher-system-agent.env
[INFO]  Enabling rancher-system-agent.service
Created symlink /etc/systemd/system/multi-user.target.wants/rancher-system-agent.service → /etc/systemd/system/rancher-system-agent.service.
[INFO]  Starting/restarting rancher-system-agent.service
node1:~ # systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
     Active: activating (start) since Wed 2023-02-22 11:41:38 CET; 10s ago
       Docs: https://github.com/rancher/rke2#readme
    Process: 1857 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 1861 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 1863 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 1864 (rke2)
      Tasks: 8
     CGroup: /system.slice/rke2-server.service
             └─ 1864 "/opt/rke2/bin/rke2 server"

Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Set sysctl 'net/ipv4/conf/all/forwarding' to 1"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Set sysctl 'net/netfilter/nf_conntrack_max' to 131072"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=warning msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2: not found in any file in /var/lib/rancher/rke2/agent/images: image not found"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=warning msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2: not found in any file in /var/lib/rancher/rke2/agent/images: image not found"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
Feb 22 11:41:39 node1 rke2[1864]: time="2023-02-22T11:41:39+01:00" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.24.9-rke2r2"
Feb 22 11:41:43 node1 rke2[1864]: time="2023-02-22T11:41:43+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Feb 22 11:41:48 node1 rke2[1864]: time="2023-02-22T11:41:48+01:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
node1:~ # cat /etc/systemd/system/rke2-server.service
[Unit]
Description=Rancher Kubernetes Engine v2 (server)
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target
Conflicts=rke2-agent.service

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/opt/rke2/lib/systemd/system/%N.env
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/opt/rke2/bin/rke2 server
ExecStopPost=-/bin/sh -c "systemd-cgls /system.slice/%n | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill"
node1:~ # cat /etc/default/rke2-server
cat: /etc/default/rke2-server: No such file or directory
node1:~ # /etc/sysconfig/rke2-server
-bash: /etc/sysconfig/rke2-server: No such file or directory
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.env
HOME=/root
node1:~ # ls /opt/rke2/lib/systemd/system
rke2-agent.env  rke2-server.env  rke2-server.service
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-agent.env
HOME=/root
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.service
EnvironmentFile=-/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env
node1:~ # cat /var/lib/rancher/rke2/system-agent-installer/rke2-sa.env
HTTP_PROXY=http://proxy:81
NO_PROXY=.xsnet,localhost,127.0.0.1,192.168.29.40
HTTPS_PROXY=http://proxy:81
node1:~ #

**Comment by brandond** [comment]
OK, I think there might be a bug in the system-agent-installer. From your logs:
```console
node1:~ # cat /etc/systemd/system/rke2-server.service
[Unit]
...
node1:~ # cat /opt/rke2/lib/systemd/system/rke2-server.service
EnvironmentFile=-/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env
```

That additional `EnvironmentFile` line is meant to be appended to /etc/systemd/system/rke2-server.service but it is instead going into /opt/rke2/lib/systemd/system/rke2-server.service, which isn't used by systemd.

**Comment by brandond** [comment]
I believe I have a fix for this, but it will not be retroactive to previous releases.

**Comment by brandond** [comment]
For QA: PR has been merged to system-agent-installer-rke2; you should be able to test with of the February RCs.
