### ISSUE TITLE
waiting for cluster agent to connect

### ISSUE THREAD

**Issue by wuwo1952368901** [rancher/rke2#3931]
rancher version: 2.7.0
RKE2 Version:  v1.24.9+rke2r2
The cluster has three master nodes enabled. When the machine with catle-cluster-agent is reboot, the restarted node cannot recover normally, and the prompt: waiting for cluster agent to connect
The reboot machine needs to execute "iptables - F" to recover

**Comment by caroline-suse-rancher** [comment]
Hi @wuwo1952368901, it looks like your issue is with Rancher specifically, can you create a new issue in that repo? https://github.com/rancher/rancher/issues/new/choose
