### ISSUE TITLE
rke2 ~100% cpu utilization with no workload

### ISSUE THREAD

**Issue by apiszcz** [rancher/rke2#3934]
rke2 version v1.24.9+rke2r2 (2f4571a879954e1ea8d4560023eaf57c567df737)
go version go1.18.7b7

m@m01:~$ uname -a
Linux m01 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

100% CPU utilization, node does not register, reconciling status in Rancher

I expect this to drop to < 5% soon (< 1 minute) after connecting with rancher if the node is not in use.

PID 4620 shown below is rke2

```
top - 04:25:30 up 38 min,  2 users,  load average: 1.17, 1.40, 1.26
Tasks: 125 total,   2 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.0 us,  1.8 sy,  0.0 ni, 72.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7957.0 total,   5982.2 free,    508.3 used,   1466.6 buff/cache
MiB Swap:    975.0 total,    975.0 free,      0.0 used.   7192.3 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   4620 root      20   0  944960 149284  89808 S  99.3   1.8   6:22.38 /usr/local/bin+
   4636 root      20   0  778012  73704  42000 S   9.3   0.9   0:16.20 containerd -c +
   4649 root      20   0  821020  97228  60612 S   1.3   1.2   0:06.89 kubelet --volu+
   1244 root      20   0   10.7g  71300  34568 S   0.7   0.9   0:14.79 etcd --config-+
      1 root      20   0  164976  10352   7792 S   0.0   0.1   0:02.95 /sbin/init
```

**Comment by brandond** [comment]
The terminal output is trimmed. Can you show the full binary path to confirm that this is the rke2 process? What do the logs show when it's at 100%? Can you `kill -ABRT` that process, and collect the resulting stack trace?

When posting logs, please attach files to your comment instead of posting them in the text.
