### ISSUE TITLE
Support "windows-bgp" mode in Calico for Windows

### ISSUE THREAD

**Issue by milkmanrox** [rancher/rke2#3945]
**Is your feature request related to a problem? Please describe.**
Currently the rke2 executable sets Calico in vxlan mode by default (as per https://github.com/rancher/rke2/issues/3380)
Even with "cni: none" set, once a Calico manifest is deployed to the cluster, the deployed Windows nodes still deploy calico with the hardcoded vxlan mode, preventing any ability to manually deploy Calico on the node with the required settings.

**Describe the solution you'd like**
Support the ability to either change the CNI config.yaml from vxlan to windows-bgp, or allow for BGP to be enabled in the installation file at cluster creation

**Describe alternatives you've considered**
There's no way to currently prevent rke2 from deploying Calico so no alternatives seem to have worked from what I've tried.

**Additional context**
The reason for requiring windows-bgp mode is to support load balancing of pods directly from an external load balancer. There's no easy way to add an external non k8s node to participate in vxlan with Calico unlike flannel.

**Comment by est-suse** [comment]
```
WARNING: Waiting for service 'Routing and Remote Access (RemoteAccess)' to stop...
PS C:\Users\Administrator> Get-BgpRouteInformation -Type all

DestinationNetwork NextHop      LearnedFromPeer   State LocalPref MED
------------------ -------      ---------------   ----- --------- ---
10.42.232.192/26   172.31.23.87 Mesh_172_31_23_87 Best  100


DestinationNetwork NextHop      LearnedFromPeer   State LocalPref MED
------------------ -------      ---------------   ----- --------- ---
10.42.232.192/26   172.31.23.87 Mesh_172_31_23_87 Best  100
```
