### ISSUE TITLE
rke2-server fails to start after the restart

### ISSUE THREAD

**Issue by yingyue520** [rancher/rke2#3948]
Hello, excuse me.
I deployed a rke2 cluster, but when my computer rebooted, I used
systemctl restart rke2-server cannot be started.
An error occurs when using the Kubectl get instruction
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port? The connection to the server 127.0.0.1:6443 was refused - Did you specify the right host or port?
I by netstat PNLT | grep found port 6443 hasn't been listening.
I want to get help.
My version is  v1.24.10+rke2r1

**Comment by yingyue520** [comment]
[root@rke-server ~]# kubectl get nodes
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
[root@rke-server ~]# systemctl restart rke2-server
Job for rke2-server.service failed because the control process exited with error code. See "systemctl status rke2-server.service" and "journalctl -xe" for details.
[root@rke-server ~]# systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 二 2023-02-28 22:43:12 CST; 1s ago
     Docs: https://github.com/rancher/rke2#readme
  Process: 14837 ExecStopPost=/bin/sh -c systemd-cgls /system.slice/%n | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill (code=exited, status=0/SUCCESS)
  Process: 14825 ExecStart=/usr/bin/rke2 server (code=exited, status=2)
  Process: 14821 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 14819 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 14815 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
 Main PID: 14825 (code=exited, status=2)

2月 28 22:43:12 rke-server systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
2月 28 22:43:12 rke-server systemd[1]: Unit rke2-server.service entered failed state.
2月 28 22:43:12 rke-server systemd[1]: rke2-server.service failed.

**Comment by yingyue520** [comment]
This is My journal.
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/daemons/executor/etcd.go:30 +0x10e
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/etcd.(*ETCD).StartEmbeddedTemporary(0xc0003ba190, {0x7569550, 0xc0009482c0})
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/etcd/etcd.go:862 +0x55b
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/cluster.(*Cluster).reconcileEtcd(0xc000b7f260, {0x7569550, 0xc000948240})
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/cluster/bootstrap.go:523 +0x2e5
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/cluster.(*Cluster).Bootstrap(0xc000b7f260, {0x7569550, 0xc000948240}, 0x0)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/cluster/bootstrap.go:63 +0x1e5
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/daemons/control.prepare({0x7569550, 0xc000948240}, 0xc000e4b908)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/daemons/control/server.go:265 +0x245
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/daemons/control.Server({0x7569550?, 0xc000948240}, 0xc000e4b908)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/daemons/control/server.go:34 +0xff
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/server.StartServer({0x7569550?, 0xc000948240}, 0xc000e4b900, 0x1?)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/server/server.go:58 +0x93
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/cli/server.run(0xc000ec5600, 0xa963d80, {0x0, 0x0, 0x9?}, {0xc00106c870, 0x0, 0x0?})
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/cli/server/server.go:460 +0x2b11
2月 28 23:20:48 rke-server rke2[1662]: github.com/k3s-io/k3s/pkg/cli/server.RunWithControllers(...)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/k3s-io/k3s@v1.24.10-0.20230114061559-739be58a8b45/pkg/cli/server/server.go:46
2月 28 23:20:48 rke-server rke2[1662]: github.com/rancher/rke2/pkg/rke2.Server(_, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {0x0, ...}, ...}, ...})
2月 28 23:20:48 rke-server rke2[1662]: /source/pkg/rke2/rke2.go:123 +0x545
2月 28 23:20:48 rke-server rke2[1662]: github.com/rancher/rke2/pkg/cli/cmds.ServerRun(0xc000ec5600?)
2月 28 23:20:48 rke-server rke2[1662]: /source/pkg/cli/cmds/server.go:162 +0xa5
2月 28 23:20:48 rke-server rke2[1662]: github.com/urfave/cli.HandleAction({0x588b6a0?, 0x6ba7b48?}, 0x6?)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 +0x50
2月 28 23:20:48 rke-server rke2[1662]: github.com/urfave/cli.Command.Run({{0x68ae865, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x68fcbed, 0x15}, {0xc000dbe948, ...}, ...}, ...)
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173 +0x65b
2月 28 23:20:48 rke-server rke2[1662]: github.com/urfave/cli.(*App).Run(0xc00072d180, {0xc000839880, 0x4, 0x4})
2月 28 23:20:48 rke-server rke2[1662]: /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277 +0x8a7
2月 28 23:20:48 rke-server rke2[1662]: main.main()
2月 28 23:20:48 rke-server rke2[1662]: /source/main.go:22 +0xb9e
2月 28 23:20:48 rke-server systemd[1]: rke2-server.service: main process exited, code=exited, status=2/INVALIDARGUMENT
2月 28 23:20:48 rke-server systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
-- Subject: Unit rke2-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rke2-server.service has failed.
-- 
-- The result is failed.
2月 28 23:20:48 rke-server systemd[1]: Unit rke2-server.service entered failed state.
2月 28 23:20:48 rke-server systemd[1]: rke2-server.service failed.

**Comment by brandond** [comment]
Can you attach (not paste) the whole service log? There's not enough there to figure out what's going on.

**Comment by MrWuzhuoyue** [comment]
Thank you very much. I have found the problem.
After my machine restarted, the host name changed. Cause to crash

**Comment by yingyue520** [comment]
> Thank you very much. I have found the problem. After my machine restarted, the host name changed. Cause to crash
