### ISSUE TITLE
HA not working

### ISSUE THREAD

**Issue by Paulrke2** [rancher/rke2#3949]
**Environmental Info:**
RKE2 Version: v1.26.1+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux myhost01.example.com 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 master/control plane nodes, 4 workers/agents

**Describe the bug:**

rebooting any of the three masters prevents the other masters from running ANY kubectl command until all three masters are up. Relevant info in /var/log/messages is:

```
Feb 21 14:11:36 kubehost-02 rke2[1434]: time="2023-02-21T14:11:36-05:00" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 192.168.222.178:9345: connect: connection refused"
Feb 21 14:11:36 kubehost-02 rke2[1434]: time="2023-02-21T14:11:36-05:00" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.222.178:9345: connect: connection refused"
Feb 21 14:11:41 kubehost-02 rke2[1434]: time="2023-02-21T14:11:41-05:00" level=info msg="Connecting to proxy" url="wss://192.168.222.178:9345/v1-rke2/connect"
Feb 21 14:11:41 kubehost-02 rke2[1434]: time="2023-02-21T14:11:41-05:00" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 192.168.222.178:9345: connect: connection refused"
Feb 21 14:11:41 kubehost-02 rke2[1434]: time="2023-02-21T14:11:41-05:00" level=error msg="Remotedialer proxy error" error="dial tcp 192.168.222.178:9345: connect: connection refused"
Feb 21 14:11:46 kubehost-02 rke2[1434]: time="2023-02-21T14:11:46-05:00" level=info msg="Connecting to proxy" url="wss://192.168.222.178:9345/v1-rke2/connect"
```

kubeconfig is using localhost:
.kube/config:
    server: https://127.0.0.1:6443

/etc/rancher/rke2/config.yaml
                server: https://my-cluster.example.com:9345

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

kubectl should continue to function when any of the master nodes are rebooted

**Actual behavior:**

kubectl hangs until all three nodes are up

**Additional context / logs:**

**Comment by brandond** [comment]
That's not something I've encountered. Can you show the output of `kubectl get nodes -o wide` from one of the nodes when all the servers are up, as well as the output of running that same command on each of the servers when one of them is down?

**Comment by Paulrke2** [comment]
Thanks for the quick response. 
Here's the output of kubectl get nodes -o wide from one of the nodes when all the servers are up:


```
NAME                              STATUS   ROLES                       AGE     VERSION          INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                               KERNEL-VERSION                 CONTAINER-RUNTIME


master-01.example.com     Ready    control-plane,etcd,master   20d     v1.26.1+rke2r1   192.168.222.177   <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
master-02.example.com     Ready    control-plane,etcd,master   18d     v1.26.1+rke2r1   192.168.222.176   <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
master-03.example.com     Ready    control-plane,etcd,master   18d     v1.26.1+rke2r1   192.168.222.178   <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
worker-dc1-01.example.com    Ready    <none>                      18d     v1.26.1+rke2r1   172.22.155.82    <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
worker-dc1-02.example.com    Ready    <none>                      3h22m   v1.26.1+rke2r1   172.22.51.215    <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
worker-dc2-01.example.com   Ready    <none>                      18d     v1.26.1+rke2r1   172.13.59.26     <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
worker-dc2-02.example.com   Ready    <none>                      3h19m   v1.26.1+rke2r1   172.13.51.184    <none>        Red Hat Enterprise Linux 8.7 (Ootpa)   4.18.0-425.10.1.el8_7.x86_64   containerd://1.6.15-k3s1
```

When any one of the master nodes is down, kubectl just hangs - and during that time I see the above messages relating to RemoteDialer & proxy  in /var/log/messages. The ip in those messages corresponds to the master that is down/being rebooted - I have tried rebooting all three masters one at a time and they all behave the same way.

**Comment by brandond** [comment]
What is `https://my-cluster.example.com:9345/` that you are using as the server endpoint - is it an external load-balancer, DNS alias that points to one or more of the servers, or something else? Do you have this `server` address configured on all of the server nodes, or just some of them? Are you using the rke2 admin kubeconfig at /etc/rancher/rke2/rke2.yaml, or are you constructing your own somehow?

What you're describing doesn't make any sense to me, as the apiserver binds to port 6443 and runs with host network, so as long as the apiserver static pod is running, and has a connection to etcd, you should be fine. Have you checked the apiserver and etcd logs in /var/log/pods to make sure there's not something else weird going on when you take down one of the nodes? It almost sounds like your etcd cluster is actually only running with 2/3 nodes active for some reason. Here's my cluster with one of the three nodes stopped:

```console
root@rke2-server-1:/# kubectl get node
NAME            STATUS     ROLES                       AGE     VERSION
rke2-server-1   Ready      control-plane,etcd,master   5m5s    v1.26.0+rke2r1
rke2-server-2   Ready      control-plane,etcd,master   4m40s   v1.26.0+rke2r1
rke2-server-3   NotReady   control-plane,etcd,master   3m4s    v1.26.0+rke2r1
```

**Comment by brandond** [comment]
Are all of the etcd pods actually running? Check the restart count to see if it is abnormally high, and check the logs from the etcd pods on all the nodes to confirm that they aren't printing any errors.
