### ISSUE TITLE
please elaborate resource constraints for RKE2 in the documentation

### ISSUE THREAD

**Issue by harridu** [rancher/rke2#3957]
AFAICS the documentation doesn't mention resource requests and limits for RKE2's namespaces (kube-system, cattle-system, cattle-fleet-system, calico-system, etc) in the documentation. Setting reasonable values might be crucial for stability and reliability. Apparently RKE2 does not set default requests and limits for most system pods. 

Would you mind to elaborate this in the documentation?

**Comment by caroline-suse-rancher** [comment]
@harridu This might be more so what you're looking for if you're using Rancher - https://ranchermanager.docs.rancher.com/v2.5/how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/override-default-limit-in-namespaces Let me know if that helps.
