### ISSUE TITLE
No endpoints available for service "rke2-ingress-nginx-controller-admission" when trying to use with Rancher

### ISSUE THREAD

**Issue by curtisy1** [rancher/rke2#3958]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.24.10+rke2r1 (1ccdce2571291649b9414af1f269f645c3fe4002)
go version go1.19.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux Ubuntu-2204-jammy-amd64-base 5.15.0-60-generic # 66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server, 3 agents

**Describe the bug:**

Trying to set up Rancher together with RKE2 does not work for me anymore. This happens on a clean install from a Hetzner dedicated root server, where I can 100% reproduce this behaviour (clean install meaning there's no other dependencies installed except for the Ubuntu minimal stuff).

EDIT: I should probably mention that it works just fine with k3s and traefik, so this seems to be rke2 related.

**Steps To Reproduce:**

[Here's a gist](https://gist.github.com/curtisy1/3405b63c88fe99c80da38e610b036048) of the setup script I'm currently using. I'm sure it could be improved, but it used to work just fine before.
It basically boils down to:
- install rke2
- install helm
- install cert-manager for ssl
- install rancher via helm

**Expected behavior:**

I get a nice and shiny Rancher UI I can use. Be it using my own subdomain or a sample DNS entry using sslip.io

**Actual behavior:**

The install fails at the last step.

**Additional context / logs:**

INSTALLATION FAILED: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "rke2-ingress-nginx-controller-admission"

**Comment by brandond** [comment]
Have you looked at the pod status or error logs to see why there are no endpoints? Its hard to help without knowing what is actually going on with the pods.

**Comment by curtisy1** [comment]
Gotcha! So far, I haven't looked at the logs but I'll try to reproduce again and get some logs later today on my personal machine when I'm home since I'm happy it's working fine now with k3s (never change a running system).

**Comment by brandond** [comment]
The logs look fine but for some reason there are no endpoints for the webhook service. Can you get the output of `kubectl get pod -A -o wide` and `kubectl get service -A -o wide` ?

**Comment by curtisy1** [comment]
Sure thing! Here's the outputs of `kubectl get pod -A -o wide`

```
NAMESPACE      NAME                                                    READY   STATUS      RESTARTS   AGE    IP               NODE                NOMINATED NODE   READINESS GATES
cert-manager   cert-manager-85945b75d4-z568w                           1/1     Running     0          99s    10.42.0.4        ubuntu-4gb-fsn1-1   <none>           <none>
cert-manager   cert-manager-cainjector-7f694c4c58-4ftsq                1/1     Running     0          99s    10.42.0.7        ubuntu-4gb-fsn1-1   <none>           <none>
cert-manager   cert-manager-webhook-7cd8c769bb-ddtjs                   1/1     Running     0          99s    10.42.0.6        ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    cloud-controller-manager-ubuntu-4gb-fsn1-1              1/1     Running     0          112s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    etcd-ubuntu-4gb-fsn1-1                                  1/1     Running     0          111s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    helm-install-rke2-canal-9q4rk                           0/1     Completed   0          100s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    helm-install-rke2-coredns-bb6qv                         0/1     Completed   0          100s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    helm-install-rke2-ingress-nginx-m2jmk                   0/1     Completed   0          100s   10.42.0.3        ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    helm-install-rke2-metrics-server-jwwbx                  0/1     Completed   0          100s   10.42.0.8        ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    kube-apiserver-ubuntu-4gb-fsn1-1                        1/1     Running     0          112s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    kube-controller-manager-ubuntu-4gb-fsn1-1               1/1     Running     0          105s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    kube-proxy-ubuntu-4gb-fsn1-1                            1/1     Running     0          108s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    kube-scheduler-ubuntu-4gb-fsn1-1                        1/1     Running     0          105s   123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    rke2-canal-65fhj                                        2/2     Running     0          89s    123.201.116.44   ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    rke2-coredns-rke2-coredns-58fd75f64b-4ftgk              1/1     Running     0          90s    10.42.0.5        ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    rke2-coredns-rke2-coredns-autoscaler-768bfc5985-p9q6d   1/1     Running     0          90s    10.42.0.9        ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    rke2-ingress-nginx-controller-fx5vc                     1/1     Running     0          48s    10.42.0.12       ubuntu-4gb-fsn1-1   <none>           <none>
kube-system    rke2-metrics-server-74f878b999-w92rj                    1/1     Running     0          58s    10.42.0.10       ubuntu-4gb-fsn1-1   <none>           <none>
```

And the output of `kubectl get service -A -o wide`, respectively
```
NAMESPACE       NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE     SELECTOR
cattle-system   rancher                                   ClusterIP   10.43.125.234   <none>        80/TCP,443/TCP   75s     app=rancher
cert-manager    cert-manager                              ClusterIP   10.43.232.23    <none>        9402/TCP         2m22s   app.kubernetes.io/component=controller,app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=cert-manager
cert-manager    cert-manager-webhook                      ClusterIP   10.43.27.97     <none>        443/TCP          2m22s   app.kubernetes.io/component=webhook,app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=webhook
default         kubernetes                                ClusterIP   10.43.0.1       <none>        443/TCP          2m31s   <none>
kube-system     rke2-coredns-rke2-coredns                 ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP    2m5s    app.kubernetes.io/instance=rke2-coredns,app.kubernetes.io/name=rke2-coredns,k8s-app=kube-dns
kube-system     rke2-ingress-nginx-controller-admission   ClusterIP   10.43.208.50    <none>        443/TCP          83s     app.kubernetes.io/component=controller,app.kubernetes.io/instance=rke2-ingress-nginx,app.kubernetes.io/name=rke2-ingress-nginx
kube-system     rke2-metrics-server                       ClusterIP   10.43.76.197    <none>        443/TCP          93s     app=rke2-metrics-server,release=rke2-metrics-server
```

**Comment by brandond** [comment]
Are you perhaps just trying to install Rancher before all the components are done starting up? Everything looks fine now. If you try to install Rancher before nginx is done starting, yeah you'll get errors because the webhook has been added but nginx isn't ready yet.

**Comment by curtisy1** [comment]
That... seems to be it. At least if I manually wait for a few seconds I can install without any errors. Thanks for clearing that up!

I'm guessing what's still confusing me is how this used to work without any wait on my end before but since I can't pinpoint the release I used anymore and it might very well have been a due to overall machine slowness at the time, I'll close this as solved since this clears up my confusion.

Thanks again for helping me out with this!

**Comment by e-minguez** [comment]
Just in case, if you want to ensure the nginx controller has been already deployed you can use:

```
while ! kubectl rollout status daemonset -n kube-system rke2-ingress-nginx-controller --timeout=60s; do sleep 2 ; done
```

**Comment by ShubhamDesai17** [comment]
I get this issue while deploying any ingress resources
I am using rke2-cluster with 1 master and 2 worker

Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded

**Comment by andrew-morris-rgs** [comment]
Just incase anyone else runs into this I found this works pretty well:
```
kubectl wait --for=create ingressClass --all
INGRESS_INSTANCE=$(kubectl -n kube-system get ingressClass -o yaml | yq '.items[0].metadata.labels."app.kubernetes.io/instance"')
kubectl wait --for=condition=ready pod -l "app.kubernetes.io/instance"="${INGRESS_INSTANCE}" -n kube-system
```
I think I prefer just putting Rancher into a HelmChart manifest in the rke2 manifest dir so far. That also handles it very well, but this covered the gotchas I had rapidly deploying Rancher on freshly created rke2 cluster.
