### ISSUE TITLE
clustermesh-apiserver-client-certs will be lost

### ISSUE THREAD

**Issue by wuwo1952368901** [rancher/rke2#3963]
rke2:  v1.24.10+rke2r1
rancher:2.7.0
CNI:  cilium

When using cilium and enabling useAPIServer, clustermesh-apiserver-client-certs will be lost.

**Comment by brandond** [comment]
Can you be more descriptive about what specifically you're seeing? The information you've provided isn't sufficient for us to reproduce anything.

**Comment by wuwo1952368901** [comment]
![image](https://user-images.githubusercontent.com/18156943/223943613-eacc8603-b090-4eba-acc1-9f29bbe4dc09.png)
When creating a cluster, useAPIServer is enabled. When the cluster is created successfully, you will see that clustermesh-apiserver-client-certs is missing.
![image](https://user-images.githubusercontent.com/18156943/223944014-2f67ed3a-8a9c-4b86-b366-e35b943d2ce6.png)

**Comment by brandond** [comment]
You said that they were lost. Usually that would indicate that they were there at some point but then went away. Were these certs present at some point in the past, or has this never worked properly for you?
