### ISSUE TITLE
[New OS Validation] RHEL 9.1

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#3994]
Confirm this OS is functional using v1.26

**Comment by est-suse** [comment]
Validated on RKE2: 1.26.3. 1.25.8, 1.24.12
AMI-08079ea9aa44b5de6

- Fresh Installation and sonobuoy execution
- Upgrade SUC RKE2 native with workloads
- Install RKE2 as local management cluster for Rancher
- cluster-reset  (Perform on one of the server nodes after bringing two of them down)
- Perform snapshot and restore to a new node
