### ISSUE TITLE
Full core being used on NIC add.

### ISSUE THREAD

**Issue by KyleSanderson** [rancher/rke2#3998]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.24.10+rke2r1 (1ccdce2571291649b9414af1f269f645c3fe4002)
go version go1.19.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
5.19.0-35-generic #36~22.04.1-Ubuntu 

Cluster Configuration:

**Describe the bug:**
Enabled a NIC. etcd busyloops forever.

```
Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=info msg="Defragmenting etcd database"
Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Foun>
Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=info msg="Connecting to proxy" url="wss://10.100.200.2:9345/v1-rke2/connect"
Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 10.100.200.2:9345: connec>
Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=error msg="Remotedialer proxy error" error="dial tcp 10.100.200.2:9345: connect: connection refused"
Mar 13 23:37:25 fileserver rke2[2314]: time="2023-03-13T23:37:25-07:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://10.24.96.50:9345/v
```

**Steps To Reproduce:**

- Installed RKE2: 
- Add a NIC
- have your distro use far too much cpu.

**Expected behavior:**
- Not fully crash a box.

**Actual behavior:**
- Busyloop.

**Additional context / logs:**

**Comment by brandond** [comment]
Can you attach the **complete** rke2 logs from journald? The snippet you included is truncated, and appears to contain just a couple lines of messages during cluster startup - it does NOT show enough to discern why RKE2 restarted when you added the interface (if that is indeed what happened).

I will note that a bit of the message here suggests that the node's primary IP address changed when you added the interface, which isn't supported. The node's primary IP must remain static for the duration of its membership in the cluster.
> `Mar 13 23:37:24 fileserver rke2[2314]: time="2023-03-13T23:37:24-07:00" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Foun>`

**Comment by KyleSanderson** [comment]
The machine was restarted once the NIC was added.

**Comment by brandond** [comment]
Can you share any of the requested information, or confirm whether or not the node's IP address changed after adding the nic?

**Comment by KyleSanderson** [comment]
The node continues to be on the original IP address (per -o wide), it's just this etcd loop that kills the node.

**Comment by brandond** [comment]
You haven't provided any untruncated logs so I can't really help you figure out what's going on. The bit of the logs you HAVE shared shows that the node doesn't consider itself to be part of the etcd cluster; the usual cause of this is that the auto-detected node address has changed for some reason.

**Comment by KyleSanderson** [comment]
I ended up rebuilding the cluster, after I did a certificate regeneration it bricked.
