### ISSUE TITLE
Manually configured audit logging does not mount correct log directory

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4026]
* *From https://github.com/rancher/rke2/issues/1183#issuecomment-1241299430*

The default audit-log-path is always set to `DATA_DIR/server/logs/audit.log`, and the directory for that file is mounted into the apiserver static pod. This is done even if the server's `--audit-policy-file` flag is not set and no audit-log-path flag will be passed to the apiserver.

Ref:
* https://github.com/rancher/rke2/blob/5d1dc149953661f8910c107a76d7ebc7de8ae40f/pkg/podexecutor/staticpod.go#L245
* https://github.com/rancher/rke2/blob/5d1dc149953661f8910c107a76d7ebc7de8ae40f/pkg/podexecutor/staticpod.go#L256-L268
* https://github.com/rancher/rke2/blob/5d1dc149953661f8910c107a76d7ebc7de8ae40f/pkg/podexecutor/staticpod.go#L299

Unfortunately, if the user overrides the audit-log-path with `kube-apiserver-args`, we only mount the default audit log directory, and the audit logs don't get written to the host filesystem. It is up to the user to know to manually add a `kube-apiserver-extra-mount` for the selected log directory. We don't cover this in the docs, so most users won't figure this out on their own.

We should honor the user's selected audit-log-path, and ensure that it is mounted into the static pod, instead of always mounting the default.

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit be54040d8e8591cb2e6b2705df6308830f33de00
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Linux 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```
  
*Cluster Configuration:*

```
1 server
```
  
*Config.yaml:*

```
write-kubeconfig-mode: 644
token: summer
node-name: server
audit-policy-file: /etc/rancher/rke2/audit.yaml
kube-apiserver-arg: audit-log-path=/var/log/audit/rke2.log
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
3. Start RKE2 service
4. Ensure the log file exists on the directory defined by the user in confg.yaml
  
**Replication Results:**
- rke2 version used for replication:

```
rke2 version v1.26.3+rke2r1 (81b04f085bd73d7a285f63087489600fb011a7a4)
go version go1.19.7 X:boringcrypto
```
 

- No audit folder created in `/var/log` and `DATA_DIR/server/logs` dir is empty
```
$ sudo ls -la /var/log/audit
ls: cannot access '/var/log/audit': No such file or directory

$ sudo ls -la /var/lib/rancher/rke2/server/logs
total 8
drwxr-xr-x 2 root root 4096 Apr 11 23:46 .
drwx------ 8 root root 4096 Apr 11 23:46 ..

```
 
**Validation Results:**
- rke2 commit used for validation:

```
rke2 version v1.26.3+dev.be54040d (be54040d8e8591cb2e6b2705df6308830f33de00)
go version go1.19.7 X:boringcrypto
```
 

- Audit folder is created in `/var/log` along with the defined file and NO logs folder got created in `DATA_DIR/server` dir
```
$ sudo ls -la /var/log/audit
total 8
drwxr-xr-x  2 root root   4096 Apr 12 00:05 .
drwxrwxr-x 14 root syslog 4096 Apr 12 00:05 ..
-rw-------  1 root root      0 Apr 12 00:05 rke2.log

$ sudo ls -la /var/lib/rancher/rke2/server/logs
ls: cannot access '/var/lib/rancher/rke2/server/logs': No such file or directory
```

**Additional observation:**
- No logs folder got created in `DATA_DIR/server`
- Upon uninstalling rke2, the log file still remains in `var/log/audit` folder
Are these expected? @brandond

**Comment by rancher-max** [comment]
We confirmed internally:
1. that’s expected, as rke2 was asked to put the logs in /var/log/audit instead
2. if you put the logs in a custom path, the uninstaller won’t be aware of that; it only handles default path.
