### ISSUE TITLE
Calico operator installs old ippools.crd.projectcalico.org

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#4032]
**Environmental Info:**
RKE2 Version: 1.26.2 rke2r1

Bundled calico operator installs older crd `ippools.crd.projectcalico.org` that does not contain `disableBGPExport` filed and making it impossible to use it in calico configuration. 

https://docs.tigera.io/calico/3.24/reference/resources/ippool 

it is available since version 3.21.0

**Comment by xhejtman** [comment]
`allowedUses` field is also missing.

**Comment by brandond** [comment]
I am assuming you're using calico (`cni: calico`), and are not referring to the calico embedded in canal? Can you confirm?

cc @rbrtbnfgl @thomasferrandiz

**Comment by xhejtman** [comment]
Yes, I use `cni: calico`, sorry not mention it.

**Comment by xhejtman** [comment]
the problem is also in older versions, esp. 1.24.10 (tested).

**Comment by brandond** [comment]
In that case the operator is not responsible for creating the CRDs; we are instead bundling them in a standalone helm chart:
https://github.com/rancher/rke2-charts/tree/main/charts/rke2-calico/rke2-calico-crd/v3.25.001/templates/calico

It does look like we're missing some updates from upstream:
https://github.com/projectcalico/calico/tree/master/manifests/ocp

**Comment by xhejtman** [comment]
It would be nice if it could be updated also in 1.24 releases.

**Comment by rbrtbnfgl** [comment]
I am probably missing something. We are creating the chart based from the one shipped by calico. The crd should be downloaded from source.

**Comment by brandond** [comment]
I wonder if the upstream chart has fallen behind then. I can confirm that the fields @xhejtman mentioned are present in the CRDs in the main calico repo.

**Comment by rbrtbnfgl** [comment]
The crd that we are using is the right one from sources we are manually removing those values during the patching process.
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-calico/generated-changes/patch/crds/calico/crd.projectcalico.org_ippools.yaml.patch
I have no idea of the reason maybe @manuelbuil should know.

**Comment by ShylajaDevadiga** [comment]
### Validated on master branch using commit id 0df15121bbb764ce64fcb6ef9976c255e69d50b9
Calico chart is updated and the parameter **disableBGPExport** is present in ippools.crd.projectcalico.org crd
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
SLES 15 SP4

*Cluster Configuration:*
Multi node cluster

  *Config.yaml:*
```
cat /etc/rancher/k3s/config,yaml
cni: calico
```
 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml
2. Install rke2
3. Check chart version
4. Check if parameter is present in the above mentioned ippools.crd.projectcalico.org crd

**Results from reproducing the issue:**
```
sudo cat /var/lib/rancher/rke2/server/manifests/rke2-calico.yaml|more
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-calico/rke2-calico-v3.25.001.tgz
  name: rke2-calico

>kubectl get crd ippools.crd.projectcalico.org -o yaml|grep disableBGPExport;echo $?
1

```

**Results after validating the fix:**
```
sudo cat /var/lib/rancher/rke2/server/manifests/rke2-calico.yaml|more
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-calico/rke2-calico-v3.25.002.tgz
  name: rke2-calico

> kubectl get crd ippools.crd.projectcalico.org -o yaml|grep disableBGPExport;echo $?
              disableBGPExport:
0
```
