### ISSUE TITLE
Create stable channel and promote GA to stable

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#404]
Create a stable channel for RKE2 and once we have signoff from Craig or Dave then update GA release to stable.

Update install.sh to pull from stable channel by default instead of latest

**Comment by davidnuzik** [comment]
Once we do this, install options docs may need an update in the environment variables section as it initially indicates the install script defaults to the latest channel.

**Comment by davidnuzik** [comment]
Bumping out to our planned early November release. We should be nearly ready to declare our next release as stable. We want to iron out some things with etcd (rancher/k3s). Our November release should get some more testing focus on etcd and when we release we'll later mark it as stable.

**Comment by immanuelfodor** [comment]
Wow, does this mean RKE2 is considered stable and it can replace RKE1? Where are we now on the timeline in this section of the docs? https://docs.rke2.io/#why-two-names

**Comment by davidnuzik** [comment]
Hello! In short, no. Stable is a channel we use to designate what has not only been QA tested but has "baked" in the community for a while. Releases in the stable channel should be suitable for use in production environments.

RKE2 does not yet have feature parity with RKE1 ([rancher/rke](https://github.com/rancher/rke))
However, this is something that we are striving to get to (as close as possible) and you might find that we are closer in feature parity with RKE1 by as early as end of Q1 next year. And we plan to have an upgrade/migration path as early as end of Q1 as well next year.

This said, [RKE2 is a certified kubernetes distribution](https://landscape.cncf.io/selected=rke-government) and is ready for use as a kubernetes cluster in production environments today. Today, you can import an RKE2 cluster into Rancher. Later, you should be able to provision an RKE2 cluster in Rancher.

**Comment by immanuelfodor** [comment]
Thank you for the explanation, David, very enlightening! :) 
- Do you track the feature parity somewhere, like a checkbox list to easily compare the current differences and follow later on how RKE2 advances over time? 
- Is there an issue or something that I can subscribe to get notification when the upgrade/migration path is available or is in progress?
