### ISSUE TITLE
[release-1.24] Bump harvester csi driver to v0.1.16

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4040]
Backport for #4038 

PR: #4006

**Comment by VestigeJ** [comment]
Waiting for harvester team to validate...

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.7-head` and `v2.6-head` with Harvester `v1.1.2-rc3`. Close this issue.

### Result
After update Kubernetes version of the RKE2 guest cluster from `v1.24.10` to `v1.24.12-rc1`

1. RKE2 guest cluster can include csi-driver v0.1.16 chart installation
  ![image](https://user-images.githubusercontent.com/29251855/226628358-14fc8a01-9f6a-4228-820b-de362f6f826f.png)
2. In guest cluster, default storage class set to Harvester
3. Can create PVC with Harvester storage class
4. Can attach PV to deployment
5. The created PV on Rancher can display on Harvester volume page 

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: v1.1.2-rc3
* Rancher version: `v2.7-head` (a841a91), `v2.6-head` (a2423b1) 
* K8s version: `v1.24.12-rc1`

### Verify Steps
1. In Harvester setting, set the version number from `v1.1.2-rc3` to `v1.1.2` (for Rancher v2.6-head)
2. Import Harvester to Rancher 
3. Provision the RKE2 cluster with K8s version v1.24.10
4. Check the csi-driver version on guest cluster application page
5. Update the YAML of the guest cluster 
6. Change the kubernetes version to `v1.24.12-rc1+rke2r1`
7. Wait the update complete
8. Check the csi-driver version on guest cluster application page
9. Create an nginx deployment and set Harvester as the PVC
10. Check the PVC and PV state on Rancher and Harvester UI
