### ISSUE TITLE
Validate SRIOV

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#4041]
Need to validate SRIOV so we can remove the experimental flag

**Comment by rancher-max** [comment]
This is available to test now, but we should wait until after March releases to validate it.

**Comment by ShylajaDevadiga** [comment]
### Validated using rke2 version v1.26.4-rc1+rke2r1 per our SR-IOV CNI Test Plan
Validated configurations

**SR-IOV specific checks pass using host-local**
- cni: multus,canal
- cni: multus,calico
- cni: multus,cilium

**SR-IOV specific checks pass using whereabouts**
- cni: multus,canal
- cni: multus,calico
- cni: multus,cilium
