### ISSUE TITLE
CoreDNS resolves FQDN to IPv6 even if the host system does not support IPv6 (on purpose).

### ISSUE THREAD

**Issue by peter-englmaier** [rancher/rke2#4050]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.23.16+rke2r1 (0124f3b3a88575a77ae75778eb82ef87a7302fc7)
go version go1.19.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux k2-master1 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
(all nodes identical)

Cluster Configuration:

3 master, 3 worker, all allow PODs to be scheduled (our DEV Cluster)

**Describe the bug:**

The cluster nodes are all IPv4 only, but inside pods `getent hosts domain.tld` responds with IPv6 address, even if IPv4 address exists. The host system behaves differently and only reports IPv4 (because IPv6 is turned off). This causes problems with nginx reverse proxy in certain cases.

**Solution:**

Actually, this may not be a bug at all, but some folks need to run IPv4 only clusters while having a DNS resolver which also serves IPv6 (our DNS might be the real cause) because the rest of the network is dual-stack. Nevertheless, the coredns should not resolve IPv6 when the node doesn't support it. I fixed this by changing the configmap rke2-coredns-rke2-coredns in namespace kube-system to include a rewrite statement as follows:

```
data:
  Corefile: ".:53 {\n   rewrite type AAAA A \n    errors \n    health  {\n        lameduck
    5s\n    }\n    ready \n    kubernetes   cluster.local  cluster.local in-addr.arpa
    ip6.arpa {\n        pods insecure\n        fallthrough in-addr.arpa ip6.arpa\n
    \       ttl 30\n    }\n    prometheus   0.0.0.0:9153\n    forward   . 192.168.150.28\n
    \   cache   30\n    loop \n    reload \n    loadbalance \n}"
```
The IP address 192.168.150.28 is on of our internel DNS servers. The line `rewrite type AAAA A` basically rewrites requests for IPv6 (type AAAA) into IPv4 (type A).

This solved the problem for us. 

Please add this to the documentation, as it might be helpful for others. Thanks!

**Comment by Martin-Weiss** [comment]
I have seen a similar problem with some PODs that have been trying to use ::1 for loopback instead of 127.0.0.1, because the DNS server replied with 127.0.0.1 and ::1 on "getent hosts localhost". Due to that the services in some pods failed to bind to ::1 and did not start as the nodes in the cluster have IPv6 disabled and ::1 does not exist..

So probably related to this issue, here?

**Comment by brandond** [comment]
This is not something that the DNS server should be responsible for handling. If the client application isn't going to use ipv6, it should not look up AAAA records. The DNS server isn't responsible for knowing what addresses families the cluster or client supports.
