### ISSUE TITLE
Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input / Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by tadas-equinix** [rancher/rke2#4059]
Error Message from /var/log/syslog
Mar 27 19:21:33 master01 kubelet[61781]: E0327 19:21:33.028607   61781 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
Mar 27 19:21:33 master01 kubelet[61781]: W0327 19:21:33.028619   61781 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: executable file not found in $PATH, output: ""

root@master01:/var/log# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
root@master01:/var/log# 

How do I fix this issue .  .

**Comment by caroline-suse-rancher** [comment]
Hi @tadas-equinix can you please fill out a bug report and provide some more info so we can better help you? Should be available from the "New Issue" button above.
