### ISSUE TITLE
Move from `rancher/pause` to `rancher/mirrored-pause`

### ISSUE THREAD

**Issue by superseb** [rancher/rke2#4061]
This was changed in https://github.com/k3s-io/k3s/issues/3750 for k3s and should be done for rke2 as well.

**Comment by brandond** [comment]
I think @briandowns did some of this for 1.27 as part of the arm64 work, but we should probably backport it to other branches as well.

**Comment by briandowns** [comment]
This was in fact done for arm64 work. I can backport next sprint.

**Comment by brandond** [comment]
still needs backporting
