### ISSUE TITLE
Where/How to install SELINUX policies for RKE2 with offline install

### ISSUE THREAD

**Issue by bordenit** [rancher/rke2#4065]
**Environmental Info:**
RKE2 Version: 
1.24.10

Node(s) CPU architecture, OS, and Version: 
AWS, RHEL7.9, m5.large controller and m5.xlarge worker

Cluster Configuration:
5 workers, 5 controllers

**Describe the bug:**
SELINUX policies are not getting applied when using offline installation in an offline environment. The offline installation instructions offer a single cryptic statement related to the offline install as if there might be something different required, but it does not list details on what different thing needs to be done. container-selinux and rke2-selinux are both installed; however, SELINUX is blocking everything from trying to start up. We used sealert -a /var/log/audit/audit.log and used audit to allow to remove some blocks, but new blocks occur after every single app we try to add to the cluster. How can I at least install all the SELINUX policies manually if needed so that we do not need to continue to use sealert -a /var/log/audit/audit.log to continuously unblock things.

**Steps To Reproduce:**
Install RKE2 with offline tar file option in selinux option enabled in config.yml. Run rpm -qa to ensure rke2-selinux and container-selinux are installed. rke2-server does not start. Install setroubleshoot and run sudo sealert -a /var/log/audit/audit.log and notice that several blocks are occuring in SELINUX which is failing to allow rke2-selinux to start. Manually add all those policies using ausearch and audit to allow will eventually allow rke2-selinux to start, but every app added after also needs to be manually unblocked in SELINUX.

- Installed RKE2: 

**Expected behavior:**
The SELINUX policies would get applied the same in offline environment since rke2-selinux and container-selinux are both installed. I assume these 2 rpms do something to auto-apply policies?

**Actual behavior:**
We are ending up auditing to allow every single thing as it tries to start up.

**Additional context / logs:**

**Comment by bordenit** [comment]
This may be related to https://github.com/rancher/rke2/issues/3386 

But, I don't think I can install it any differently in our isolated environment than I have with the available install.sh environment variables it seems fairly limited for the offline installation options. I would need to manually modify the install.sh script. It would be nice if it had INSTALL_RKE2_RPM_REPO option and INSTALL_RKE2_IMAGE_REPO option so if already have our own offline repositories to host the rpms and images we could use those with no modifications to install.sh.

**Comment by brandond** [comment]
If you need to install the RPMs directly, without mirroring the repos, you can find the packages at:
* https://github.com/rancher/rke2-packaging/releases
* https://github.com/rancher/rke2-selinux/releases

**Comment by bordenit** [comment]
Thanks. The easy install instructions make it seem like you need that install.sh script, but just the rpm's worked. Closing issue.
