### ISSUE TITLE
[release-1.24] Bump coredns to v1.10.1

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4075]
* #4073 Backport

**Comment by fmoral2** [comment]
helm list --all-namespaces | grep rke2-coredns
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
rke2-coredns       	kube-system	1       	2023-04-10 18:23:29.282815345 +0000 UTC	deployed	rke2-coredns-1.19.402                       	1.9.3

**Comment by brandond** [comment]
@fmoral2 please check the image used by the coredns container as well, just to confirm that it's 1.10.1

**Comment by fmoral2** [comment]
@brandond  sorry i had upload that comment not on purpose
