### ISSUE TITLE
Add support for SLE Micro 5.4

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#4098]
This should include v1.25, v1.26, and v1.27

**Comment by mdrahman-suse** [comment]
## Validated SLE Micro 5.4 with versions v1.25.9, v1.26.4, and v1.27.1

Executed below tests
- Fresh installation of HA cluster
- Sonobuoy tests
- SUC upgrade
- Rancher install locally, create new cluster, import existing cluster
- Cluster Reset/Restore
