### ISSUE TITLE
Cannot properly configure audit-logging in the API Server pod

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#410]
Per CIS requirements, we need to add the `--audit-policy-file` argument to the kube-apiserver. This argument needs to point at a file containing a valid Policy resource:
```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules: []
```

We may want to provide a default file with no rules (as shown above) that the user can customize.

In order to pass this file through to the apiserver static pod, we will need to add it to the host path mounts. We will likely need to do the same for the audit log file. Suggested paths and audit options from the hardening guide are:

```
--kube-apiserver-arg=audit-policy-file=/etc/rancher/rke2/audit/policy.yaml
--kube-apiserver-arg=audit-log-path=/var/log/rke2/audit.log
--kube-apiserver-arg=audit-log-maxage=31
--kube-apiserver-arg=audit-log-maxbackup=100
--kube-apiserver-arg=audit-log-maxsize=100
```

**Comment by cjellick** [comment]
We need to mount in a directory from the host that will have the audit policy file and we need to be able to get the audit log files off the host.

**Comment by dweomer** [comment]
> We need to mount in a directory from the host that will have the audit policy file and we need to be able to get the audit log files off the host.

Should we be opinionated here and force/assume those locations?

**Comment by briandowns** [comment]
> > We need to mount in a directory from the host that will have the audit policy file and we need to be able to get the audit log files off the host.
> 
> Should we be opinionated here and force/assume those locations?

I think it'd probably be safe with `/var/lib/rancher` as the assumed root.

**Comment by galal-hussein** [comment]
I am going to add a flag for the policy file the same way we do for the registries.yaml file, the default place will be in the same config file /etc/rancher/rke2/policy.yaml file and will be an empty policy by default, as for the log file I will assume datadir/server/logs/audit.log the same way we do for kubelet logs under agent dir, and the rest will be hardcoded and can be overriden with extra args

**Comment by brandond** [comment]
It needs to be a valid policy file, but the example above (with no rules) should work. Maybe don't overwrite it if it already exists so that users can customize it?

**Comment by rancher-max** [comment]
#### Validated using `v1.18.10-alpha1+rke2r1`

- There continues to be no audit logging by default when NOT in CIS mode
- When in CIS mode, this now passes the CIS Scored check (3.2.1 Ensure that a minimal audit policy is created (Scored)). This can be validated using `/bin/ps -ef | grep kube-apiserver | grep audit-policy-file`. Verified no regressions to CIS with the other audit parameters of: `audit-log-path`, `audit-log-maxage`, `audit-log-maxbackup`, and `audit-log-maxsize`
- The default audit-policy-file provides a level of `None` to all requests. Users have the ability to pass their own audit file with different levels. For example, to log all requests at the metadata level:
```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
```
and then provide the path to that file in config.yaml, i.e: 
```yaml
audit-policy-file: "/home/ubuntu/auditpol.yaml"
```
- When providing policies with different rules, ensured the logs are appropriately written to `$datadir/server/logs/audit.log`
