### ISSUE TITLE
how can i set Calico ENV "CALICO_IPV4POOL_BLOCK_SIZE" in windows node?

### ISSUE THREAD

**Issue by oingooing** [rancher/rke2#4140]
**Is your feature request related to a problem? Please describe.**

hi
i want to use Calico Env Option that CALICO_IPV4POOL_BLOCK_SIZE. (default : 26)
i know that kube-proxy currently only supports a single IP block per host in windows. (https://docs.tigera.io/calico/3.24/getting-started/kubernetes/windows-calico/limitations#calico-vxlan-networking-limitations)

As an alternative, try increasing the ip block size. (/20)

i cannot find calico env configuration in rke2 config file. 
how can i set calico env? persists even when the node is restarted.

thanks.

**Describe the solution you'd like**

It would be nice if rke2 didn't overwrite the settings on node restart
or
possible input with rke2 settings

**Additional context**

**Rancher Version** : v2.6.9
**K8s Version** : v1.24.10+rke2r1
**Calico Version** : 3.24.5
**Windows Node OS** : Windows Server 2019 STD

**Comment by brandond** [comment]
You should set it the same as you would any other Windows environment variable, in the Environment Variables editor, accessible via the Advanced tab of the Windows System control panel.

![image](https://user-images.githubusercontent.com/370103/234386365-8ca930a4-f4c3-4bbb-b6b8-85afba46cf6b.png)
