### ISSUE TITLE
Validate SLES 15 SP5 on RKE2 1.26

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4141]
Jira Ticket: https://jira.suse.com/browse/SURE-6142

Snapshot of SLES 15 SP5 should now be available.

**Comment by VestigeJ** [comment]
Just checked for the AMI to be present in the AWS Catalog and it's still not published.

**Comment by rancher-max** [comment]
This has been validated using an AMI in AWS that was upgraded from SP4 to SP5 public RC
