### ISSUE TITLE
Multus fails to connect to cilium.sock after host reboot.

### ISSUE THREAD

**Issue by Winor** [rancher/rke2#4146]
#### What I did:
Deploy ```rke2 (v1.25.7+rke2r1)``` using ```rancher manager (v2.7.2)``` with ```Cilium``` + ```Multus``` CNI on an ```VM``` running ```Fedora CoreOS``` (v 37.20230401.3.0). SELinux is enabled if that matters.
#### What I except:
When the host reboots, I expect all the pods with ``k8s.v1.cni.cncf.io/networks`` to start with the configured network interfaces available in the pod
#### What I get:
The pods start, but without the configured network interfaces.
#### Logs:
I tried setting 
```
logFile: /var/log/multus.log
logLevel: debug
```
Via helm, but that made no difference, so I manually edited the DeamonSet to add ```--multus-log-level=debug``` and ```--multus-log-file=/var/log/multus.log``` switches in the command arguments. After I did that, the log showed up on ```/var/log/multus.log``` as expected. I rebooted the host and in the log file I saw

```

2023-04-27T12:30:16Z [error] delegateDel: error invoking ConflistDel - "portmap": conflistDel: error in getting result from DelNetworkList: unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get "http:///var/run/cilium/cilium.sock/v1/config": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?

```
In the pod:
```
2023-04-27T12:30:00+00:00 Generating Multus configuration file using files in /host/etc/cni/net.d...
2023-04-27T12:30:00+00:00 Using MASTER_PLUGIN: 05-cilium.conflist
2023-04-27T12:30:01+00:00 Nested capabilities string: "capabilities": {"portMappings": true},
2023-04-27T12:30:01+00:00 Using /host/etc/cni/net.d/05-cilium.conflist as a source to generate the Multus configuration
2023-04-27T12:30:01+00:00 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true}, "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.1", "name": "portmap", "plugins": [ { "name": "cilium", "type": "cilium-cni", "enable-debug": false, "log-file": "/var/run/cilium/cilium-cni.log" }, { "type": "portmap", "capabilities": {"portMappings": true} } ] } ] }
2023-04-27T12:30:01+00:00 Entering sleep (success)...
```
Unless you enable debug mode and check the logs, there is no indication that something went wrong with Multus. That can be quite problematic in production.
It won't try to reconnect unless I restart the ```rke2-multus-ds```, but even then I have to manually restart the pods that use ``k8s.v1.cni.cncf.io/networks`` annotations to get the network interfaces to show up in the pod.
Is there any solution or something I can try?
Thanks!

**Comment by brandond** [comment]
This looks like a bug with Multus. It should probably retry internally, or exit so that the pod can be restarted.

cc @manuelbuil @rbrtbnfgl @thomasferrandiz

**Comment by Winor** [comment]
After some digging in the Multus repository, I found this [issue](https://github.com/k8snetworkplumbingwg/multus-cni/issues/972#issuecomment-1371462498). I am pretty sure that this is the issue I am facing, since I'm able to reproduce it. Now, what is the best practice way to change  [exclusive: true](https://github.com/cilium/cilium/blob/1085ae269e7181ed8dc0140b4ed26bf6fa15c0c9/install/kubernetes/cilium/values.yaml#L500) ? Looks like changing the helm values via Rancher's Add-On Config UI make no deference.

**Comment by brandond** [comment]
We have our own chart, but it doesn't appear to have an equivalent.
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-multus/rke2-multus/v3.9.3-build2023010902/values.yaml

**Comment by thomasferrandiz** [comment]
You should be able to set `exclusive: true` in the `rke2-cilium` since it is present in the `values.yaml` file: https://github.com/rancher/rke2-charts/blob/main/charts/rke2-cilium/rke2-cilium/1.12.401/values.yaml#L370

**Comment by brandond** [comment]
Ahh indeed, I was on mobile and didn't notice that the link was to the cilium chart, not multus 🙃
