### ISSUE TITLE
Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4168]
The github.com/ghodss/yaml package is no longer being actively maintained. sigs.k8s.io/yaml is a permanent fork of github.com/ghodss/yaml, which is actively maintained by Kubernetes SIG and widely used in K8s projects.

We should switch to the upstream-maintained package.

**Comment by rancher-max** [comment]
Not much to validate here outside of standard regression checks, so closing and any issues that might come from that will be opened separately.
