### ISSUE TITLE
Bump Harvester Cloud Provider 0.2.0

### ISSUE THREAD

**Issue by rebeccazzzz** [rancher/rke2#4184]
Harvester Cloud Provider 0.2.0 will contain issues needed for Harvester 1.2.0.

Related issue: https://github.com/harvester/harvester/issues/2134

**Comment by irishgordo** [comment]
@rancher-max from the Harvester side this looks good :smile: :+1: 
was able to successfully provision with proper cloud provider - run nginx deployment - scale

#### Test scope w/ Harvester v1.2.0-rc2
|                   | v1.26.6-rc4+rke2r1 | v1.25.11-rc4+rke2r1 | v1.24.15-rc4+rke2r1 |
|-------------------|:-----------:|:-----------:|:------------:|
| Rancher v2.7.5-rc5 |    PASS     |    PASS       |     PASS         |

![Screenshot from 2023-06-21 15-29-01](https://github.com/rancher/rke2/assets/5370752/d5d97bd1-97af-4dac-a1fd-6b77b2d3058a)
![Screenshot from 2023-06-21 15-29-42](https://github.com/rancher/rke2/assets/5370752/66fbb0ae-5b39-4409-aa5d-9b5cdf7c824a)
![Screenshot from 2023-06-21 15-30-13](https://github.com/rancher/rke2/assets/5370752/067e2f5f-dd66-49e0-a493-e59825d08988)
![Screenshot from 2023-06-21 14-59-58](https://github.com/rancher/rke2/assets/5370752/5e9787af-5e76-496c-ab1f-cd68908f90da)
![Screenshot from 2023-06-21 14-58-06](https://github.com/rancher/rke2/assets/5370752/c9b533fe-3c98-4108-b2bd-1c0a6c6b275d)
![Screenshot from 2023-06-21 13-14-53](https://github.com/rancher/rke2/assets/5370752/fe7f892d-1f80-4756-a41b-c5d91210f43a)
![Screenshot from 2023-06-21 12-59-54](https://github.com/rancher/rke2/assets/5370752/719a5884-d547-418f-abe8-26652a67657d)
![Screenshot from 2023-06-21 12-56-49](https://github.com/rancher/rke2/assets/5370752/cb53d1e8-b898-4c5d-b7b6-386931215afe)

**Comment by rancher-max** [comment]
Thank you so much!
