### ISSUE TITLE
kubelet-arg does not accept evictionHard settings

### ISSUE THREAD

**Issue by NosIreland** [rancher/rke2#4200]
**Environmental Info:**
RKE2 Version: v1.24.9+rke2r2 

Node(s) CPU architecture, OS, and Version:   5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 masters, 4 agents

**Describe the bug:**
Trying to change `evictionHard` confguration:
Created file on agent `/opt/kube-config.yaml`
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
evictionHard:
  nodefs.available: "3%"
  imagefs.available: "3%"
  nodefs.inodesFree: "3%"
```

modified `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` and added
```
  "kubelet-arg": [
    "config=/opt/kube-config.yaml"
  ],
```
restarted rke2 service.
In the logs can see that `/opt/kube-config.yaml` file is loaded `--config=/opt/kube-config.yaml`

`May 10 18:42:57 dev-worker-2 rke2[3670240]: time="2023-05-10T18:42:57+02:00" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --alsologtostderr=false --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --config=/opt/kube-config.yaml --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=dev-worker-2 --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --log-file=/var/lib/rancher/rke2/agent/logs/kubelet.log --log-file-max-size=50 --logtostderr=false --node-ip=10.0.0.52 --node-labels=cattle.io/os=linux,rke.cattle.io/machine=15ae2182-a6ca-4a69-8d5f-ef20ceffb931,topology.kubernetes.io/region=fsn1,topology.kubernetes.io/zone=fsn1-dc18,traveltime/optimized-for=ram --pod-infra-container-image=index.docker.io/rancher/pause:3.6 --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --stderrthreshold=FATAL --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key"`

But it still listing default settings:
`--eviction-hard=imagefs.available<5%,nodefs.available<5%`

Also In the logs I see this:
`May 10 18:42:57 dev-worker-2 rke2[3670648]: Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.`

So looks like it does not accept my config for some reason

**Steps To Reproduce:**
See above

**Comment by brandond** [comment]
If you specify a kubelet configuration file, all other args are ignored - including those set internally by RKE2. If you want to use a kubelet configuration file, you must also convert all of the args to configuration file values.

This is being tracked on the K3s side in https://github.com/k3s-io/k3s/issues/2116.

**Comment by NosIreland** [comment]
Thank you. I had this but instead of `kubelet-arg:` had `kubelet-args:` and could not figure out why it was not working.

**Comment by NosIreland** [comment]
After some futher testing I see that the` kubelet-arg:` is not preserved after node reboot. Is there a way to keep config after reboot?

**Comment by sibzz** [comment]
@brandond Hi, Im interested in your last comment. I knew i could do this on a per node basis by  modifying the config.yaml but how do I do this using Rancher?

**Comment by brandond** [comment]
Put it in the kubelet args for the cluster in the Rancher UI?
