### ISSUE TITLE
Remove cluster-init flag in rke2

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#426]
Version:
rke2 version v1.18.9-rc1+rke2

Issue:
We dont use cluster-init flag in rke2.

```
rke2 server --help|grep init
   --cluster-init                       (experimental/cluster) Initialize a new cluster [$RKE2_CLUSTER_INIT]
```

**Comment by davidnuzik** [comment]
We will mention the issue in release notes and fix after our GA release.

**Comment by rancher-max** [comment]
#### Validated in a build off current master: `rke2 version v1.18.10-dev+13f4ce97 (13f4ce97832eee244b9b2b6ff9ff9bd6920bb556)`

- Does not show up in server or agent flags anymore using `rke2 server --help`
- Cannot use the flag when running. Retrieve following error: `FATA[0000] flag provided but not defined: -cluster-init `
