### ISSUE TITLE
[BUG] `rke2-snapshot-controller` and `rke2-snapshot-validation` pod errors out on RKE2 windows node driver cluster 

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rke2#4264]
**Rancher Server Setup**
- Rancher version: v2.7-head(f929174)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.26.4+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- In RKE2 Windows node driver cluster, `rke2-snapshot-controller` and `rke2-snapshot-validation` pods get stuck into `Containercreating` state, as it is getting scheduled on a windows worker node and shows below error in recent events :
```
(combined from similar events): MountVolume.SetUp failed for volume "kube-api-access-rjxqh" : chown c:\var\lib\kubelet\pods\03c0c7f2-d9f8-430d-a083-bf97e26d3f99\volumes\kubernetes.io~projected\kube-api-access-rjxqh\..2023_05_19_12_45_07.225458724\token: not supported by windows
```
![pods](https://github.com/rancher/rancher/assets/36376154/20b7bd56-6499-4ab7-a8ff-ddcfab60612d)

- **Note :** As a workaround, if we provision a cluster with 1-cp, 1-etcd, 1-w(linux) and after it comes into Active state, then add a Machine Pool for windows worker node. All pods would be Active, but in this case also if we delete these two pods they will error out, if get scheduled on a windows worker node.

**To Reproduce**

- On vSphere env 7, provision a RKE2, vSphere node driver cluster with 1-cp, 1-e, 1-w(linux), 1-w(windows)
- Explore cluster, once it comes into Active state -> `rke2-snapshot-controller` and `rke2-snapshot-validation` would be stuck into Containercreating state.

**Result**
- `rke2-snapshot-controller` and `rke2-snapshot-validation` pods getting scheduled on a windows worker node and erring out.

**Expected Result**

- All pods should be up and running.

**Comment by mitulshah-suse** [comment]
Will this be fixed in 1.26.4 as well? 
@brandond @snasovich

**Comment by brandond** [comment]
No. Fixes go in new patch releases. There will not be a rerelease of 1.26.4.

**Comment by rancher-max** [comment]
### Validated using v1.27.2-rc2+rke2r1 in Rancher v2.7-head commit `fbca7c3`

I was able to reproduce this using v1.26.4+rke2r1 following the steps as mentioned in the original issue description:
<img width="1424" alt="image" src="https://github.com/rancher/rke2/assets/55997940/eee15bc8-7409-49a6-a61c-e851d97e8355">

Using the latest RC for rke2 and the same steps, I saw these coming up successfully:
<img width="1432" alt="image" src="https://github.com/rancher/rke2/assets/55997940/c90e0df9-2a22-4ecb-aad5-81923332ddd6">

Also confirmed all chart versions:
```
rancher-vsphere-cpi:1.5.100 
rancher-vsphere-csi:3.0.1-rancher100 
rke2-snapshot-controller:1.7.202
rke2-snapshot-controller-crd:1.7.202 
rke2-snapshot-validation-webhook:1.7.101 
```
