### ISSUE TITLE
apiserver pod dns can not resolve cluster internal dns

### ISSUE THREAD

**Issue by JaneLiuL** [rancher/rke2#4282]
when we create cluster via rke2, and /etc/rancher/rke2/config.yaml as below, we found that the apiserver can resolve the outside dns like baidu or gooogle.
but the question is , apiserver pod can not resolve the cluster internal dns like service, for example curl kubernetes.default, it can not be resolve.
Then we check the kubernetes document, i double confirm that the apiserver static pod.spec.dnsPolicy=ClusterFirst.
and apiserver pod is hostNetwork=true, if you check this link:  https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
you can found that hostnetwork=true pod need to set `dnsPolicy=ClusterFirstWithHostNet`
since rke2 can not provide any possible to change the pod.spec.dnsPolicy for apiserver. i raise this issue as bug.

```yaml
tls-scan:
 - xxx
resolv-conf: /etc/resolv.conf
```

**Comment by brandond** [comment]
> but the question is , apiserver pod can not resolve the cluster internal dns like service, for example curl kubernetes.default, it can not be resolve.

Why would you want it to do that? The apiserver is not designed to be run within the cluster or to use the cluster DNS service for lookups. For things like webhook endpoints that may operate within the cluster, the apiserver bypasses cluster DNS lookups and queries the service endpoint IPs directly.

**Comment by heitzflorian** [comment]
> > but the question is , apiserver pod can not resolve the cluster internal dns like service, for example curl kubernetes.default, it can not be resolve.
> 
> Why would you want it to do that? The apiserver is not designed to be run within the cluster or to use the cluster DNS service for lookups. For things like webhook endpoints that may operate within the cluster, the apiserver bypasses cluster DNS lookups and queries the service endpoint IPs directly, if you use a [service reference](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#service-reference) in the webhook configuration. It functions similarly when using `kubectl proxy` to tunnel connections to services.

Hi @brandond,

sorry for the topic digging up and i don't know if it's the right place to ask, but if you have some additional details regarding the 'service reference' you are mentioning to put in webhook configuration, i'm interested to know a little bit more about it.

To add a little more context, i'm trying to configure Falco with the k8saudit plugin activated in a Rancher context, which imply audit-logs to be configured and being sent by kubernetes kube-apiserver pod to falco pods. 

As kube-apiserver use the `hostNetwork:true` setting and falco is (by default) deployed as a daemonSet do not (`hostNetwork:false`), you may have several way to make both communicates. Falco documentation mainly detail how to do it using a webhook service (don't mistake with MutatingWebhook or AdmissionWebhook terms), so i'm curious on how to do it with the alternative  'service reference' you are mentioning.

In a nutshell:
* In kubernetes vanilla, if using webhook service with something else than 127.0.0.1/localhost, nodePort or hostNetwork IP, it don't work out of the box unless you set `dnsPolicy: ClusterFirstWithHostNet `at the kube-apiserver component level so it tries resolving the service name using internal DNS before trying external one (defined in /etc/resolv.conf for instance)
* In rancher it also don't work out of the box, but it seems there is no way to set `dnsPolicy: ClusterFirstWithHostNet` at the kube-apiserver component level as fleet will reconcile the kube-apiserver settings.

Please let me know if we should discuss that topic elsewhere: i'll do and edit/remove this comment.

Thanks in advance for your reply.

Documentation references: 
* https://falco.org/docs/concepts/event-sources/plugins/kubernetes-audit/#enabling-kubernetes-audit-logs
* https://falco.org/docs/getting-started/learning-environments/#falco-with-multiple-sources
* https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
* https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/

**Comment by brandond** [comment]
Did you click on the link in the text you quoted? The docs on that page show you specifically and with examples, how to refer to a service within the cluster as the backend for a webhook. Note that this is for validating/mutating webhooks, NOT for audit webhooks.

Audit webhooks take only a basic kubeconfig, with a reference to a server URL that is reachable by the apiserver pod. Best practice would see you host it OUTSIDE the cluster, so that audit logging is not dependent on the integrity of the cluster being audited. If you want to violate best practices and host the audit log collection webhook within the cluster, you'll need to find some way to expose that service so that it is reachable from the host network on the control-plane nodes.

**Comment by heitzflorian** [comment]
> Did you click on the link in the text you quoted? The docs on that page show you specifically and with examples, how to refer to a service within the cluster as the backend for a webhook. Note that this is for validating/mutating webhooks, NOT for audit webhooks.
> 
> Audit webhooks take only a basic kubeconfig, with a reference to a server URL that is reachable by the apiserver pod. Best practice would see you host it OUTSIDE the cluster, so that audit logging is not dependent on the integrity of the cluster being audited. If you want to violate best practices and host the audit log collection webhook within the cluster, you'll need to find some way to expose that service so that it is reachable from the host network on the control-plane nodes.

Indeed, i clicked on the link, but it was refering to admission controllers details so my concern was to double check applicability for audit webhooks and you did a clear and precise reply on that point: the service reference is not applicable for audit webhooks.

I'll have to study alternatives (nodePort service, hostNetwork or whatever) to host the log collection webhook within the cluster and evaluate their pros and cons for each.

Many thanks for your quick reply clarifying the situation for audit webhooks.

**Comment by brandond** [comment]
It's really meant to be used to send things outside the cluster, to an externally managed service. If you're logging within the cluster, best practice would be to just log to files, and then deploy a daemonset to read them from disk.

I think you're going to end up building a fragile, overcomplicated stack if you go down your current path.
