### ISSUE TITLE
rke2-server systemd unit restarts unnecessarily revert file and directory permissions

### ISSUE THREAD

**Issue by brsolomon-deloitte** [rancher/rke2#4284]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.25.9+rke2r1 (842d05e64bcbf78552f1db0b32700b8faea403a0)
go version go1.19.8 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

```
$ uname -a
Linux redacted 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ umask && umask -S
0022
u=rwx,g=rx,o=rx
```

Cluster Configuration:

1 server, 1 agent, stock Ubuntu 22.04 AWS EC2

**Describe the bug:**

Restarts of the `rke2-server.service` unnecessarily adds back world-read and world-execute file permissions on various files and directories under `/var/lib/rancher/rke2`. This in turn violates the [Rancher Government Solutions RKE2 STIG - Ver 1, Rel 2](https://public.cyber.mil/stigs/downloads/).

**Steps To Reproduce:**

As root / uid 0:

```bash
apt-get update -y
apt-get install -y --no-install-recommends apparmor
curl -fsSL https://get.rke2.io | sh -
mkdir -p /etc/rancher/rke2/
cat << EOF > /etc/rancher/rke2/config.yaml
debug: true
write-kubeconfig-mode: "0640"
EOF
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

**Expected behavior:**

Service restarts should not unnecessarily change file and directory modes.

**Actual behavior:**

As root on rke2 server:

```shell
$ ls -ld /var/lib/rancher/rke2/server/manifests
drwxr-xr-x 2 root root 4096 May 23 15:06 /var/lib/rancher/rke2/server/manifests
$ chmod 0750 /var/lib/rancher/rke2/server/manifests
$ ls -ld /var/lib/rancher/rke2/server/manifests
drwxr-x--- 2 root root 4096 May 23 15:06 /var/lib/rancher/rke2/server/manifests
$ systemctl restart rke2-server.service
$ ls -ld /var/lib/rancher/rke2/server/manifests
drwxr-xr-x 2 root root 4096 May 23 15:15 /var/lib/rancher/rke2/server/manifests # < back to original 0755
```

**Additional context / logs:**

None.

**Comment by brandond** [comment]
This is because we use the CopyDir function from `containerd/continuity/fs` to copy over the extracted manifests. This function copies the permissions of the source directory, which in this case are 0755 due to what I think is just the default umask when the charts dir is created in the Dockerfile.

**Comment by bguzman-3pillar** [comment]
### Validated on `v1.27.3-rc4+rke2r1`
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
  
*Cluster Configuration:*

```
1 server
```
  
  
## Testing Steps

1. Install rke2 `v1.27`
2. Change the permission of /var/lib/rancher/rke2/server/manifests to 0750
3. Restart rke2-server.service
4. Validate if the permission of /var/lib/rancher/rke2/server/manifests still is to 0750

 
**Validation Results:**
- rke2 version used for validation:

```
ubuntu@ip-172-31-22-87:~$ sudo chmod 0750 /var/lib/rancher/rke2/server/manifests
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ sudo ls -ld /var/lib/rancher/rke2/server/manifests
drwxr-x--- 2 root root 4096 Jun 26 17:43 /var/lib/rancher/rke2/server/manifests
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ sudo systemctl restart rke2-server.service
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ 
ubuntu@ip-172-31-22-87:~$ sudo ls -ld /var/lib/rancher/rke2/server/manifests
drwxr-x--- 2 root root 4096 Jun 26 17:46 /var/lib/rancher/rke2/server/manifests
```
