### ISSUE TITLE
Ability to confirm snapshots are turned off

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#430]
Version:
rke2 version v1.18.9-rc1+rke2

Issue:
While the snapshot was enabled initially and then disabled for any reason, we should have a way to find snapshots are disabled.
Logs or any file do not seem to have info on snapshot being disabled explicitly

Config.yaml
```
etcd-disable-snapshots: true
etcd-snapshot-schedule-cron: "*/2 * * * *"
```
When the snapshots are disabled it does not create snapshots as expected, but its good to have it in logs when explicitly disabled

**Comment by briandowns** [comment]
This has been achieved in k3s via PR https://github.com/k3s-io/k3s/pull/3405 and needs to be pulled into RKE2.

**Comment by davidnuzik** [comment]
Applied v1.21.1+rke2r1 milestone.

**Comment by brandond** [comment]
Added a backport issue; linked this issue and the backport issue into the PRs landing later today.

**Comment by ShylajaDevadiga** [comment]
Validating using commit id, verified a message is shown when snapshot is disabled. 
```
$ rke2 version v1.21.1-dev+5f9b1aa6
$ journalctl -u rke2-server |grep snapshot
Jun 16 17:54:14 ip-172-31-34-252 rke2[1526]: time="2021-06-16T17:54:14Z" level=info msg="Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap"
Jun 16 21:45:58 ip-172-31-34-252 rke2[85241]: time="2021-06-16T21:45:58Z" level=info msg="ETCD snapshots are disabled"
Jun 16 21:47:59 ip-172-31-34-252 rke2[85241]: time="2021-06-16T21:47:59Z" level=info msg="Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap"
```
With that when etcd snapshots are disabled we may not want Saving current etcd message to be included as it is conflicting with disable message.  Issue for tracking #https://github.com/rancher/rke2/issues/1157

**Comment by ShylajaDevadiga** [comment]
Validated using rc
```
ubuntu@ip-172-31-43-128:~$ rke2 -v
rke2 version v1.21.2-rc1+rke2r1

ubuntu@ip-172-31-43-128:~$ journalctl -u rke2-server -f|grep snapshot
Jun 22 16:52:56 ip-172-31-43-128 rke2[11362]: time="2021-06-22T16:52:56Z" level=info msg="ETCD snapshots are disabled"
```
