### ISSUE TITLE
cilium hubble err

### ISSUE THREAD

**Issue by jiaxingli** [rancher/rke2#4307]
Configure cilium and enable hubble. some err happen below.
![image](https://github.com/rancher/rke2/assets/15809720/bc0ea8da-97ee-4057-bb59-4241fb539867)
![image](https://github.com/rancher/rke2/assets/15809720/6f02e86c-a00d-41a1-9011-c5ef63a24f79)

**Comment by manuelbuil** [comment]
Can you tell us what config you used to deploy rke2 and how did you deploy hubble?

**Comment by jiaxingli** [comment]
1. I choose rancher rke2 to install k8s, and select cilium cni plug-in as shown in Figure 
 
![image](https://github.com/rancher/rke2/assets/15809720/bc4f7c87-d857-4ee5-9805-7ba2df20af2d)

2. add cilium official helm source after k8s installation and change the k8s cluster add-on config yaml, attached is yaml file content
[cilium.txt](https://github.com/rancher/rke2/files/11619675/cilium.txt)

**Comment by brandond** [comment]
Why are you replacing the bundled cilium helm chart with the one from upstream? Are you unable to configure the required features using the bundled chart?
