### ISSUE TITLE
RKE2 cannot authenticate to insecure registry when pulling runtime image

### ISSUE THREAD

**Issue by JacieChao** [rancher/rke2#4308]
**Environmental Info:**
RKE2 Version: v1.25.7+rke2r1

Node(s) CPU architecture, OS, and Version: Ubuntu 22.04 x86_64

Cluster Configuration: 1 server

**Describe the bug:**

Harbor configuration using the port 80 or other port e.g. 8080, not the TLS. When setting the mirror registry hostname the same as endpoint, rke2 server cannot startup and print error logs with https requests.

For example, with port 80 insecure registry /etc/rancher/rke2 /registries.yaml is as follows:
```
mirrors:
  3.26.98.114:
    endpoint:
      - "http://3.26.98.114"
```

With port 8080 insecure registry /etc/rancher/rke2 /registries.yaml is as follows:
```
mirrors:
  3.26.98.114:8080:
    endpoint:
      - "http://3.26.98.114:8080"
```

The configurations above work fine with containerd.

**Steps To Reproduce:**

1. Save install script for RKE2
```
curl -sfL https://get.rke2.io --output install.sh
chmod +x install.sh
```
2. Set RKE2 configuration(/etc/rancher/rke2/config.yaml):
```
write-kubeconfig-mode: "0644"
system-default-registry: "3.26.98.114:8080"
```
3. Set containerd private registry configuration(/etc/rancher/rke2/registries.yaml)
```
mirrors:
  3.26.98.114:8080:
    endpoint:
      - "http://3.26.98.114:8080"
```
4. Execute install script with `INSTALL_RKE2_VERSION=v1.25.7+rke2r1 ./install.sh`
5. Enable rke2 server with `systemctl start rke2-server`

**Expected behavior:**

The rke2 server start successfully.

**Actual behavior:**

The rke2 server failed to start and use the default HTTPS scheme to pulling image.

**Additional context / logs:**

```
May 31 05:54:33 ip-172-31-20-66 rke2[1580]: time="2023-05-31T05:54:33Z" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
May 31 05:54:33 ip-172-31-20-66 rke2[1580]: time="2023-05-31T05:54:33Z" level=info msg="Pulling runtime image 3.26.98.114:8080/rancher/rke2-runtime:v1.25.7-rke2r1"
May 31 05:54:33 ip-172-31-20-66 rke2[1580]: time="2023-05-31T05:54:33Z" level=warning msg="Failed to get image from endpoint: Get \"https://3.26.98.114:8080/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": http: server gave HTTP response to HTTPS client"
May 31 05:54:33 ip-172-31-20-66 rke2[1580]: time="2023-05-31T05:54:33Z" level=warning msg="Failed to get image from endpoint: Get \"https://3.26.98.114:8080/v2/\": http: server gave HTTP response to HTTPS client"
May 31 05:54:33 ip-172-31-20-66 rke2[1580]: time="2023-05-31T05:54:33Z" level=fatal msg="failed to get runtime image 3.26.98.114:8080/rancher/rke2-runtime:v1.25.7-rke2r1: all endpoints failed: Get \"https://3.26.98.114:8080/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": http: server gave HTTP response to HTTPS client; Get \"https://3.26.98.114:8080/v2/\": http: server gave HTTP response to HTTPS client"
May 31 05:54:33 ip-172-31-20-66 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
```

### Workaround for current version

The RKE2 server can start successful with the following configuration:
- rke2 config(/etc/rancher/rke2/config.yaml)
```
write-kubeconfig-mode: "0644"
system-default-registry: "3.26.98.114"
```
- private registry config(/etc/rancher/rke2/registries.yaml)
```
mirrors:
  3.26.98.114:
    endpoint:
      - "http://3.26.98.114:8080"
```

For insecure registry for port 80, the config like the above is not work. Need to config registry hostname with port 80.
- rke2 config(/etc/rancher/rke2/config.yaml)
```
write-kubeconfig-mode: "0644"
system-default-registry: "3.26.98.114:80"
```
- private registry config(/etc/rancher/rke2/registries.yaml)
```
mirrors:
  3.26.98.114:80:
    endpoint:
      - "http://3.26.98.114"
```

### More information

According to my investigation, when we try to get an image by `/v2` [here](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/ping.go#L84) by HTTPS scheme, the request will RoundTrip to [endpoint](https://github.com/rancher/wharfie/blob/main/pkg/registries/endpoint.go#L48) and redirect the request to the real endpoint that configs in `registries.yaml` using HTTP scheme. 
According to my configuration above, the `/v2` request returns `http.StatusUnauthorized` [pingResp](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/ping.go#L109) and get corrent `realm` and `services` parameters to help get bearer token [here](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/transport.go#L77). 
The [bearerTransport](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/bearer.go#L293) will try to get bearer token with the `realm` url. The [transport schemer RoundTrip](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/schemer.go#L40) checks the host, when we set the registry hostname the same with endpoint, the scheme will redirect to HTTPS [here](https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/v1/remote/transport/schemer.go#L41) and the [endpoint RoundTrip](https://github.com/rancher/wharfie/blob/main/pkg/registries/endpoint.go#L48)  skip the redirect the request endpoint if the url path is not `/v2` which cause the error log with `Get \"https://3.26.98.114:8080/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": http: server gave HTTP response to HTTPS client; Get \"https://3.26.98.114:8080/v2/\": http: server gave HTTP response to HTTPS client"`.

As the same result with the workaround above, when the mirror registry hostname is different from the endpoint, the transport schemer won't change the request scheme which will not redirect to get the token by HTTPS scheme.

**Comment by brandond** [comment]
There is additional code being used here that you may have missed. go-containerregistry doesn't support mirrors or multiple endpoints, so that's something we've added ourself, to mirror containerd's endpoint support when using go-containerregistry to pull and unpack image. You can find the code for that at:

https://github.com/rancher/wharfie/tree/main/pkg/registries

**Comment by brandond** [comment]
I'm also confused, as under `Steps To Reproduce` you describe using port 8080, but the rest of the issue describes that the problem is when using port 80? Which is it?

**Comment by brandond** [comment]
Hmm, so in this case, harbor is redirecting to another prefix on the same endpoint for authentication, but we're not handling that rewrite. I don't think we expected that users would commonly want to submit credentials in plaintext, which is what this configuration would require... but I guess we could attempt to handle that better.

**Comment by brandond** [comment]
Just for my notes, the test cases we should match from containerd are at: https://github.com/containerd/containerd/blob/main/remotes/docker/resolver_test.go

**Comment by ShylajaDevadiga** [comment]
### Validated on rke2 version v1.27.3-rc2+rke2r1 
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Configuration:*
Single node

  *Config.yaml:*
```
$ cat /etc/rancher/k3s/config,yaml
write-kubeconfig-mode: "0644"
system-default-registry: "172.31.9.128:5000"
toekn: <TOEKN>
```
*registries.yaml:*
```
$ cat /etc/rancher/rke2/registries.yaml 
mirrors:
  172.31.9.128:5000:
    endpoint:
      - "http://172.31.9.128:5000"
```
 ## Steps to reproduce the issue  and validate the fix
1. Copy config.yaml to /etc/rancher/rke2
3. Copy registries.yaml to /etc/rancher/rke2 setting mirror registry hostname the same as endpoint
4. Install rke2

**Results from reproducing the issue:**
**rke2 version v1.27.2+rke2r1**
```
Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=info msg="Pulling runtime image 172.31.5.131:5000/rancher/rke2-runtime:v1.27.2-rke2r1"
Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=warning msg="Failed to get image from endpoint: GET http://172.31.5.131:5000/v2/rancher/rke2-runtime/manifests/v1.27.2-rke2r1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.27.2-rke2r1]"
Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=warning msg="Failed to get image from endpoint: Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client"
Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=fatal msg="failed to get runtime image 172.31.5.131:5000/rancher/rke2-runtime:v1.27.2-rke2r1: all endpoints failed: GET http://172.31.5.131:5000/v2/rancher/rke2-runtime/manifests/v1.27.2-rke2r1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.27.2-rke2r1]; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client"
Jun 21 09:20:38 ip-172-31-5-131 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
```

**Results from validation:**
```
ubuntu@ip-172-31-9-128:~$ rke2 -v
rke2 version v1.27.3-rc2+rke2r1 (02f58981a09e61f578c306c4e417aa336bf170eb)
go version go1.20.5 X:boringcrypto

ubuntu@ip-172-31-9-128:~$ kubectl get nodes
NAME              STATUS   ROLES                       AGE    VERSION
ip-172-31-9-128   Ready    control-plane,etcd,master   8m4s   v1.27.3+rke2r1

ubuntu@ip-172-31-9-128:~$ kubectl get pods -A
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cloud-controller-manager-ip-172-31-9-128                1/1     Running     0          8m5s
kube-system   etcd-ip-172-31-9-128                                    1/1     Running     0          7m24s
kube-system   helm-install-rke2-canal-w4f2b                           0/1     Completed   0          7m50s
kube-system   helm-install-rke2-coredns-728pw                         0/1     Completed   0          7m50s
kube-system   helm-install-rke2-ingress-nginx-4v7pg                   0/1     Completed   0          7m50s
kube-system   helm-install-rke2-metrics-server-gz45z                  0/1     Completed   0          7m50s
kube-system   helm-install-rke2-snapshot-controller-crd-h4bnb         0/1     Completed   0          7m50s
kube-system   helm-install-rke2-snapshot-controller-q66z6             0/1     Completed   1          7m50s
kube-system   helm-install-rke2-snapshot-validation-webhook-s6vsh     0/1     Completed   0          7m50s
kube-system   kube-apiserver-ip-172-31-9-128                          1/1     Running     0          8m5s
kube-system   kube-controller-manager-ip-172-31-9-128                 1/1     Running     0          8m5s
kube-system   kube-proxy-ip-172-31-9-128                              1/1     Running     0          8m1s
kube-system   kube-scheduler-ip-172-31-9-128                          1/1     Running     0          8m5s
kube-system   rke2-canal-tjxg6                                        2/2     Running     0          7m43s
kube-system   rke2-coredns-rke2-coredns-5bbb44696c-4trrg              1/1     Running     0          7m43s
kube-system   rke2-coredns-rke2-coredns-autoscaler-659c5fdf55-d4gpg   1/1     Running     0          7m43s
kube-system   rke2-ingress-nginx-controller-25ghg                     1/1     Running     0          6m55s
kube-system   rke2-metrics-server-6dc7f897d4-p947q                    1/1     Running     0          7m8s
kube-system   rke2-snapshot-controller-68f7b95874-rtqjv               1/1     Running     0          7m3s
kube-system   rke2-snapshot-validation-webhook-5cccb4656b-txx5j       1/1     Running     0          7m4s
ubuntu@ip-172-31-9-128:~$ 

```

**Comment by frankieci** [comment]
#> ### Validated on rke2 version v1.27.3-rc2+rke2r1
> ## Environment Details
> _Infrastructure_ Cloud EC2 instance
> 
> _Node(s) CPU architecture, OS, and Version:_ Ubuntu 22.04
> 
> _Cluster Configuration:_ Single node
> 
> _Config.yaml:_
> 
> ```
> $ cat /etc/rancher/k3s/config,yaml
> write-kubeconfig-mode: "0644"
> system-default-registry: "172.31.9.128:5000"
> toekn: <TOEKN>
> ```
> 
> _registries.yaml:_
> 
> ```
> $ cat /etc/rancher/rke2/registries.yaml 
> mirrors:
>   172.31.9.128:5000:
>     endpoint:
>       - "http://172.31.9.128:5000"
> ```
> 
> ## Steps to reproduce the issue and validate the fix
> 1. Copy config.yaml to /etc/rancher/rke2
> 2. Copy registries.yaml to /etc/rancher/rke2 setting mirror registry hostname the same as endpoint
> 3. Install rke2
> 
> **Results from reproducing the issue:** **rke2 version v1.27.2+rke2r1**
> 
> ```
> Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
> Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=info msg="Pulling runtime image 172.31.5.131:5000/rancher/rke2-runtime:v1.27.2-rke2r1"
> Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=warning msg="Failed to get image from endpoint: GET http://172.31.5.131:5000/v2/rancher/rke2-runtime/manifests/v1.27.2-rke2r1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.27.2-rke2r1]"
> Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=warning msg="Failed to get image from endpoint: Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client"
> Jun 21 09:20:38 ip-172-31-5-131 rke2[51773]: time="2023-06-21T09:20:38Z" level=fatal msg="failed to get runtime image 172.31.5.131:5000/rancher/rke2-runtime:v1.27.2-rke2r1: all endpoints failed: GET http://172.31.5.131:5000/v2/rancher/rke2-runtime/manifests/v1.27.2-rke2r1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.27.2-rke2r1]; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client; Get \"https://172.31.5.131:5000/v2/\": http: server gave HTTP response to HTTPS client"
> Jun 21 09:20:38 ip-172-31-5-131 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
> ```
> 
> **Results from validation:**
> 
> ```
> ubuntu@ip-172-31-9-128:~$ rke2 -v
> rke2 version v1.27.3-rc2+rke2r1 (02f58981a09e61f578c306c4e417aa336bf170eb)
> go version go1.20.5 X:boringcrypto
> 
> ubuntu@ip-172-31-9-128:~$ kubectl get nodes
> NAME              STATUS   ROLES                       AGE    VERSION
> ip-172-31-9-128   Ready    control-plane,etcd,master   8m4s   v1.27.3+rke2r1
> 
> ubuntu@ip-172-31-9-128:~$ kubectl get pods -A
> NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
> kube-system   cloud-controller-manager-ip-172-31-9-128                1/1     Running     0          8m5s
> kube-system   etcd-ip-172-31-9-128                                    1/1     Running     0          7m24s
> kube-system   helm-install-rke2-canal-w4f2b                           0/1     Completed   0          7m50s
> kube-system   helm-install-rke2-coredns-728pw                         0/1     Completed   0          7m50s
> kube-system   helm-install-rke2-ingress-nginx-4v7pg                   0/1     Completed   0          7m50s
> kube-system   helm-install-rke2-metrics-server-gz45z                  0/1     Completed   0          7m50s
> kube-system   helm-install-rke2-snapshot-controller-crd-h4bnb         0/1     Completed   0          7m50s
> kube-system   helm-install-rke2-snapshot-controller-q66z6             0/1     Completed   1          7m50s
> kube-system   helm-install-rke2-snapshot-validation-webhook-s6vsh     0/1     Completed   0          7m50s
> kube-system   kube-apiserver-ip-172-31-9-128                          1/1     Running     0          8m5s
> kube-system   kube-controller-manager-ip-172-31-9-128                 1/1     Running     0          8m5s
> kube-system   kube-proxy-ip-172-31-9-128                              1/1     Running     0          8m1s
> kube-system   kube-scheduler-ip-172-31-9-128                          1/1     Running     0          8m5s
> kube-system   rke2-canal-tjxg6                                        2/2     Running     0          7m43s
> kube-system   rke2-coredns-rke2-coredns-5bbb44696c-4trrg              1/1     Running     0          7m43s
> kube-system   rke2-coredns-rke2-coredns-autoscaler-659c5fdf55-d4gpg   1/1     Running     0          7m43s
> kube-system   rke2-ingress-nginx-controller-25ghg                     1/1     Running     0          6m55s
> kube-system   rke2-metrics-server-6dc7f897d4-p947q                    1/1     Running     0          7m8s
> kube-system   rke2-snapshot-controller-68f7b95874-rtqjv               1/1     Running     0          7m3s
> kube-system   rke2-snapshot-validation-webhook-5cccb4656b-txx5j       1/1     Running     0          7m4s
> ubuntu@ip-172-31-9-128:~$ 
> ```
> 
> **Results from reproducing using harbor**
> 
> ```
> Jun 22 15:54:46 ip-172-31-2-72 rke2[641876]: time="2023-06-22T15:54:46Z" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
> Jun 22 15:54:46 ip-172-31-2-72 rke2[641876]: time="2023-06-22T15:54:46Z" level=info msg="Pulling runtime image harbor.example1.com:5000/rancher/rke2-runtime:v1.27.2-rke2r1"
> Jun 22 15:54:46 ip-172-31-2-72 rke2[641876]: time="2023-06-22T15:54:46Z" level=warning msg="Failed to get image from endpoint: Get \"https://harbor.example1.com:5000/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": http: server gave HTTP response to HTTPS client"
> Jun 22 15:54:46 ip-172-31-2-72 rke2[641876]: time="2023-06-22T15:54:46Z" level=warning msg="Failed to get image from endpoint: Get \"https://harbor.example1.com:5000/v2/\": http: server gave HTTP response to HTTPS client"
> Jun 22 15:54:46 ip-172-31-2-72 rke2[641876]: time="2023-06-22T15:54:46Z" level=fatal msg="failed to get runtime image harbor.example1.com:5000/rancher/rke2-runtime:v1.27.2-rke2r1: all endpoints failed: Get \"https://harbor.example1.com:5000/service/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=harbor-registry\": http: server gave HTTP response to HTTPS client; Get \"https://harbor.example1.com:5000/v2/\": http: server gave HTTP response to HTTPS client"
> Jun 22 15:54:46 ip-172-31-2-72 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
> ```
> 
> **Results from validating using harbor**
> 
> ```
> $ cat registries.yaml 
> mirrors:
>   harbor.examplereg1.com:5000:
>     endpoint:
>       - "http://harbor.examplereg1.com:5000"
> configs:
>   harbor.examplereg1.com:5000:
>     auth:
>       username: admin
>       password: <REDACTED>
> ```
> 
> ```
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.27.3-rc4-rke2r1"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=warning msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.27.3-rc4-rke2r1 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.27.3-rc4-rke2r1: not found in any file in /var/lib/rancher/rke2/agent/images: image not found"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Checking local image archives in /var/lib/rancher/rke2/agent/images for harbor.examplereg1.com:5000/rancher/rke2-runtime:v1.27.3-rc4-rke2r1"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=warning msg="Failed to load runtime image harbor.examplereg1.com:5000/rancher/rke2-runtime:v1.27.3-rc4-rke2r1 from tarball: no local image available for harbor.examplereg1.com:5000/rancher/rke2-runtime:v1.27.3-rc4-rke2r1: not found in any file in /var/lib/rancher/rke2/agent/images: image not found"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Using private registry config file at /etc/rancher/rke2/registries.yaml"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Pulling runtime image harbor.examplereg1.com:5000/rancher/rke2-runtime:v1.27.3-rc4-rke2r1"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Creating directory /var/lib/rancher/rke2/data/v1.27.3-rc4-rke2r1-c9f087930f61/bin"
> Jun 26 19:46:08 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:08Z" level=info msg="Extracting file bin/containerd to /var/lib/rancher/rke2/data/v1.27.3-rc4-rke2r1-c9f087930f61/bin/containerd"
> Jun 26 19:46:09 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:09Z" level=info msg="Extracting file bin/containerd-shim to /var/lib/rancher/rke2/data/v1.27.3-rc4-rke2r1-c9f087930f61/bin/containerd-shim"
> Jun 26 19:46:09 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:09Z" level=info msg="Extracting file bin/containerd-shim-runc-v1 to /var/lib/rancher/rke2/data/v1.27.3-rc4-rke2r1-c9f087930f61/bin/containerd-shim-runc-v1"
> Jun 26 19:46:09 ip-172-31-0-224 rke2[48356]: time="2023-06-26T19:46:09Z" level=info msg="Extracting file bin/containerd-shim-runc-v2 to /var/lib/rancher/rke2/data/v1.27.3-rc4-rke2r1-c9f087930f61/bin/containerd-shim-runc-v2"
> ```
> 
> ```
> NAME              STATUS   ROLES                       AGE   VERSION
> ip-172-31-0-224   Ready    control-plane,etcd,master   20m   v1.27.3+rke2r1
> ubuntu@ip-172-31-0-224:~$ kubectl get pods -A
> NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
> kube-system   cloud-controller-manager-ip-172-31-0-224                1/1     Running     0          20m
> kube-system   etcd-ip-172-31-0-224                                    1/1     Running     0          19m
> kube-system   helm-install-rke2-canal-mjg5c                           0/1     Completed   0          20m
> kube-system   helm-install-rke2-coredns-9hw4r                         0/1     Completed   0          20m
> kube-system   helm-install-rke2-ingress-nginx-w9b58                   0/1     Completed   0          20m
> kube-system   helm-install-rke2-metrics-server-bwcdc                  0/1     Completed   0          20m
> kube-system   helm-install-rke2-snapshot-controller-crd-v8dbw         0/1     Completed   0          20m
> kube-system   helm-install-rke2-snapshot-controller-ff879             0/1     Completed   0          20m
> kube-system   helm-install-rke2-snapshot-validation-webhook-cn6t4     0/1     Completed   0          20m
> kube-system   kube-apiserver-ip-172-31-0-224                          1/1     Running     0          20m
> kube-system   kube-controller-manager-ip-172-31-0-224                 1/1     Running     0          20m
> kube-system   kube-proxy-ip-172-31-0-224                              1/1     Running     0          20m
> kube-system   kube-scheduler-ip-172-31-0-224                          1/1     Running     0          20m
> kube-system   rke2-canal-wjcvh                                        2/2     Running     0          19m
> kube-system   rke2-coredns-rke2-coredns-8467cb5549-l6zkw              1/1     Running     0          19m
> kube-system   rke2-coredns-rke2-coredns-autoscaler-7b6f45898f-m9xz8   1/1     Running     0          19m
> kube-system   rke2-ingress-nginx-controller-nwj8v                     1/1     Running     0          19m
> kube-system   rke2-metrics-server-5bfb65bcf8-vdth7                    1/1     Running     0          19m
> kube-system   rke2-snapshot-controller-685c4659d8-qk885               1/1     Running     0          19m
> kube-system   rke2-snapshot-validation-webhook-fbf8754dd-smnhn        1/1     Running     0          19m
> ubuntu@ip-172-31-0-224:~$ 
> ```

**Comment by frankieci** [comment]
@ShylajaDevadiga how to resolve it?

$rke2 -v
rke2 version v1.32.2+rke2r1 (8a5c3a23c25cc9b423a303be5f4f1c0e8b885726)
go version go1.23.6 X:boringcrypto

$cat /etc/rancher/rke2/config.yaml 

write-kubeconfig-mode: "0644"
tls-san:
  - master01
  - worker02
node-name: sse-24
node-ip: "10.10.2.3"
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
node-label:
  - "node=Master"

cni: "canal"
disable:
  - "rke2-ingress-nginx"
  - "rke2-metrics-server"
disable-cloud-controller: true

etcd-snapshot-retention: "6"

debug: true
# data-dir: /data/rancher/rke2

system-default-registry: "demo.registry.cn:5000"
private-registry: /etc/rancher/rke2/registries.yaml

kubelet-arg:
  - "system-reserved=cpu=1000m,memory=1Gi"
  - "kube-reserved=cpu=200m,memory=1Gi"

kube-apiserver-extra-env:
  - "feature-gates='RemoveSelfLink=false'"

$ cat /etc/rancher/rke2/registries.yaml
mirrors:
  "demo.registry.cn:5000":
    endpoint:
      - "http://demo.registry.cn:5000"

configs:
  "demo.registry.cn:5000":
    auth:
      username: admin # this is the registry username
      password: xxxxxx # this is the registry password


**When use ctr command `ctr image pull`, result such as:**

ctr images pull demo.registry.cn:5000/rancher/rke2-runtime:v1.32.2-rke2r1
WARN[0000] DEPRECATION: The `configs` property of `[plugins."io.containerd.grpc.v1.cri".registry]` is deprecated since containerd v1.5 and will be removed in containerd v2.1.Use `config_path` instead. 
ctr: rpc error: code = Unknown desc = failed to resolve image: failed to do request: Head "https://demo.registry.cn:5000/v2/rancher/rke2-runtime/manifests/v1.32.2-rke2r1": http: server gave HTTP response to HTTPS client
