### ISSUE TITLE
Support for Wasm/WASI

### ISSUE THREAD

**Issue by Sporesirius** [rancher/rke2#4318]
**Is your feature request related to a problem? Please describe.**
Ability to run WebAssembly.

**Describe the solution you'd like**
First-party support for running WebAssembly workloads.

**Comment by ron1** [comment]
Hi @brandond, is there additional work required in rke2 to resolve this issue? Or does rke2 automatically inherit the wasm support that was recently added to k3s?

**Comment by brandond** [comment]
Yes, RKE2 has the same support for alternative container runtimes that k3s has.
