### ISSUE TITLE
Update coredns chart version to allow prometheus metrics

### ISSUE THREAD

**Issue by daniel-palmer-gu** [rancher/rke2#4321]
**Is your feature request related to a problem? Please describe.**

The rke2-coredns chart is based off of upstream version 1.19.4 as seen [here](https://github.com/rancher/rke2-charts/blob/3834c470d7e75049ca7bf58188a6c5dec8398783/packages/rke2-coredns/package.yaml#L1)

With the current chart version, it isn't possible to configure a container port on the pod to allow prometheus to talk to the metrics endpoint until version 1.19.7. Specific [commit](https://github.com/coredns/helm/commit/717b9112bb1ccfd334fef5e85fc0ef32c7b8da70) enabling premetheus compatibility

**Describe the solution you'd like**

Upgrade rke2-coredns' upstream chart version to at least 1.19.7

**Describe alternatives you've considered**

Unfortunately there isn't an alternative unless I want to deploy the chart myself on the new version. See this ticket [here](https://github.com/coredns/helm/issues/46) for more details on why it isn't possible with the current chart version

**Additional context**

I hope this is the appropriate place for this request. It didn't look like I could create an issue in the [rke2-charts](https://github.com/rancher/rke2-charts) repo

**Comment by mdrahman-suse** [comment]
## Validated on RC
- With Version
```console
rke2 version v1.27.3-rc2+rke2r1 (02f58981a09e61f578c306c4e417aa336bf170eb)
```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
PRETTY_NAME="Ubuntu 22.04.2 LTS"

*Cluster Configuration:*
Single node

*Config.yaml:*
```console
write-kubeconfig-mode: "0644"
token: summer
```


## Steps to Validate the fix:
1. Install rke2 version: `v1.27.3-rc2+rke2r1`
2. Install helm
3. Check coredns deployment and service
4. Validate coredns chart version is >= than 1.19.7
5. Perform same checks on upgrade from v1.27.2+rke2r1

<details>
<summary> Validation details </summary>

- Observed the version is updated on new installs and upgrade
```console
$ kubectl get svc  -n kube-system | grep coredns
rke2-coredns-rke2-coredns                 ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP                15m

$ kubectl get deployments -n kube-system | grep coredns
rke2-coredns-rke2-coredns              1/1     1            1           15m
rke2-coredns-rke2-coredns-autoscaler   1/1     1            1           15m

$ helm list -n kube-system | grep rke2-coredns
rke2-coredns                    	kube-system	2       	2023-06-20 22:46:51.875948968 +0000 UTC	deployed	rke2-coredns-1.24.004                       	1.10.1
```

</details>
