### ISSUE TITLE
Update canal chart

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4338]
**Is your feature request related to a problem? Please describe.**

Update canal chart with the new flannel image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-   rke2 version v1.27.2+dev.c07beb26 (c07beb26feae9d8b1c43ffdf90de609f3ae93a6b)
```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu

*Cluster Configuration:*
1 node

*Config.yaml:*
```
token: secret
selinux: true

```



## Steps to Validate the fix:
1. Install rke2 in latest commit
2. Check the version of rke2 and flannel








<details>


    #### Issue Validation: ####

    CMD: rke2 --version

    RESULT:
    rke2 version v1.27.2+dev.c07beb26 (c07beb26feae9d8b1c43ffdf90de609f3ae93a6b)
    go version go1.20.4 X:boringcrypto



    Assertion:
    v1.26

    Matched with:
    rke2 version v1.27.2+dev.c07beb26 (c07beb26feae9d8b1c43ffdf90de609f3ae93a6b)
    go version go1.20.4 X:boringcrypto





    CMD: kubectl describe pod rke2-canal- -n kube-system  --kubeconfig=/tmp/franmoralrke2local_kubeconfig  | grep Image

    RESULT:
    Image:         rancher/hardened-calico:v3.25.1-build20230512
    Image ID:
    Image:         rancher/hardened-calico:v3.25.1-build20230512
    Image ID:
    Image:         rancher/hardened-calico:v3.25.1-build20230512
    Image ID:
    Image:         rancher/hardened-flannel:v0.22.0-build20230609
    Image ID:


    Assertion:
    flannel:v0.22.0

    Matched with:
    Image ID:
    Image:         rancher/hardened-flannel:v0.22.0-build20230609

    ```
