### ISSUE TITLE
Add ability to customize cert expiration

### ISSUE THREAD

**Issue by QtSYnT** [rancher/rke2#4363]
**Is your feature request related to a problem? Please describe.**

We have some requirements that make it so that the current 1 year cert lifetime is not sufficient for our use case. 

**Describe the solution you'd like**

Add configuration to decrease or increase the TTL for generated certs.

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
Note that this is intentionally NOT DOCUMENTED and NOT SUPPORTED, but this month's releases will include a change to allow overriding the certificate durations via an environment variable. Ref:
* https://github.com/rancher/rke2/pull/4324

**Comment by QtSYnT** [comment]
Fantastic, thanks!
