### ISSUE TITLE
kube-proxt ipvs mode&calico vxlan

### ISSUE THREAD

**Issue by kinbod** [rancher/rke2#4382]
**Environmental Info:**
RKE2 Version:  v1.25.7-rke2r1

Node(s) CPU architecture, OS, and Version:  4.18

Cluster Configuration:

**Describe the bug:**

I can ping service externalIP in cluster, but out of cluster.
When I use a non-rke2 cluster it works well. I want know if it is a bug?

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by kinbod** [comment]
> How did you configure RKE2? Are you using a custom configuration with Calico?

No more custom. just like below

machineGlobalConfig:
  kube-proxy-arg:
    - proxy-mode=ipvs
    - ipvs-strict-arp=true

**Comment by rbrtbnfgl** [comment]
So you can't ping the IPs? If you try to contact the server through the configured port does it work?

**Comment by kinbod** [comment]
> And you can't ping the IPs? If you try to contact the server through the configured port does it work?

I have tried it, not works. and service could not access. Do you meet the same problem?
