### ISSUE TITLE
Windows nodes stuck in "Waiting for Node Ref" - no interface has the ip

### ISSUE THREAD

**Issue by tonyrsmith** [rancher/rke2#4393]
**Environmental Info:**
RKE2 Version: 
rke2.exe version v1.24.10+rke2r1 (1ccdce2571291649b9414af1f269f645c3fe4002)
go version go1.19.5

Node(s) CPU architecture, OS, and Version: 
AMD64, Windows Server 2019 LTSC
AMD64, Ubuntu 20.04

Cluster Configuration:

1 control plane + etcd
3 Linux agents
3 Windows agents

**Describe the bug:**
All Windows nodes are stuck in "Waiting for Node Ref"

Running RKE2 manually ```c:\usr\local\bin\rke2.exe agent --token TOKEN --server "https://10.x.y.119:9345"``` returns the following error.

```
time="2023-06-21T01:29:40-07:00" level=debug msg="hcsshim::HNSNetwork::Delete id=C9352A63-C6C3-456A-A4E5-6B4DF299E4F4"
time="2023-06-21T01:29:40-07:00" level=debug msg="[DELETE]=>[/networks/C9352A63-C6C3-456A-A4E5-6B4DF299E4F4] Request : "
time="2023-06-21T01:29:40-07:00" level=debug msg="hcsshim::HNSNetwork::Delete id=BE34AB9D-B7A8-4965-88C4-2F80F9A7A630"
time="2023-06-21T01:29:40-07:00" level=debug msg="[DELETE]=>[/networks/BE34AB9D-B7A8-4965-88C4-2F80F9A7A630] Request : "
time="2023-06-21T01:29:42-07:00" level=debug msg="evaluating if the interface: Ethernet0 with addresses [], contains ip: 10.x.y.116"
time="2023-06-21T01:29:42-07:00" level=debug msg="evaluating if the interface: Loopback Pseudo-Interface 1 with addresses [::1/128 127.0.0.1/8], contains ip: 10.x.y.116"
time="2023-06-21T01:29:42-07:00" level=fatal msg="no interface has the ip: 10.x.y.116"
```

This looks similar to https://github.com/rancher/rke2/issues/3925

Running ipconfig returns

```
PS C:\usr\local\bin> ipconfig

Windows IP Configuration
Ethernet adapter vEthernet (Ethernet0):

   Connection-specific DNS Suffix  . : xxxxxxxx
   IPv4 Address. . . . . . . . . . . : 10.x.y.116
   Subnet Mask . . . . . . . . . . . : 255.255.255.128
   Default Gateway . . . . . . . . . : 10.x.y.1
```

**Steps To Reproduce:**
Registered Windows node using the following (redacted) command line provided by Rancher UI.

```
curl.exe --insecure -fL https://rancher.xxxxxxxx:8443/wins-agent-install.ps1 -o install.ps1; Set-ExecutionPolicy Bypass -Scope Process -Force; ./install.ps1 -Server https://rancher.xxxxxxxx:8443 -Label 'cattle.io/os=windows' -Token TOKEN -Worker -CaChecksum CACHECKSUM
```

**Expected behavior:**
Windows node to successfully register with Rancher

**Actual behavior:**
Windows node to stuck in "Waiting for Node Ref"
Linux nodes are registered correctly

**Comment by rbrtbnfgl** [comment]
Hi @tonyrsmith did you follow all the steps suggested here https://docs.rke2.io/install/quickstart ?
Did you run as an Administrator the shell where you are executing the commands?

**Comment by tonyrsmith** [comment]
Hi @rbrtbnfgl, no I was running the command line from the Rancher UI as I described in "Steps To Reproduce".

**Comment by rbrtbnfgl** [comment]
If you run this
`curl.exe --insecure -fL https://rancher.xxxxxxxx:8443/wins-agent-install.ps1 -o install.ps1; Set-ExecutionPolicy Bypass -Scope Process -Force; ./install.ps1 -Server https://rancher.xxxxxxxx:8443 -Label 'cattle.io/os=windows' -Token TOKEN -Worker -CaChecksum CACHECKSUM` You shouldn't start RKE2 agent that command should register and start the service.

**Comment by tonyrsmith** [comment]
@rbrtbnfgl Exactly.  I was running RKE2 manually so I could diagnose why its not working, which returned `"no interface has the ip: 10.x.y.116"`.  Hence this bug report.

**Comment by tonyrsmith** [comment]
@rbrtbnfgl Anyway, I appreciate your time looking into this :-)

**Comment by rbrtbnfgl** [comment]
If you check the Event on windows related to the service started using the rancher command what did you get?

**Comment by tonyrsmith** [comment]
|Event|Description|
| --- | --- |
|Information|Connecting to proxy url=wss://10.x.y.119:9345/v1-rke2/connect|
|Error|Failed to connect to proxy. Empty dialer response error=dial tcp 10.x.y.119:9345: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.|
|Error|Remotedialer proxy error. error=dial tcp 10.x.y.119:9345: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.|

`10.x.y.119` is the IP address of the the Control Plane/etcd node.
`10.x.y.116` is the IP address of the Windows worker node.

However, when I test the connectivity between `10.x.y.116` and `10.x.y.119` port `9345` is open.

```powershell
PS C:\> Test-NetConnection -Computer 10.x.y.119 -Port 9345

ComputerName     : 10.x.y.119
RemoteAddress    : 10.x.y.119
RemotePort       : 9345
InterfaceAlias   : vEthernet (Ethernet0)
SourceAddress    : 10.x.y.116
TcpTestSucceeded : True
```

**Comment by rbrtbnfgl** [comment]
could you check the content of `c:/var/lib/rancher/k3s/agent/etc/k3s-agent-load-balancer.json` it should contain the IP of the proxy that should be the one from the controller.

**Comment by tonyrsmith** [comment]
Rancher itself is hosted as Docker container running on a Linux VM and uses volume mounting for the data directory, so the path is slightly different.  Nevertheless, I found:

```
cat data/k3s/agent/etc/k3s-agent-load-balancer.json
{
  "ServerURL": "https://127.0.0.1:6443",
  "ServerAddresses": [
    "127.0.0.1:6443"
  ],
  "Listener": null
}
```

But it looks very generic.  And its worth noting that the Linux worker nodes have registered correctly with Rancher.

**Comment by rbrtbnfgl** [comment]
Not on rancher the file should be present also on the windows node

**Comment by tonyrsmith** [comment]
Ahh... apologies, but I saw `k3s` and assumed you meant the Rancher cluster itself.

Anyway, on Windows for `rke2` I found the following:

```
C:\var\lib\rancher\rke2\agent\etc>type rke2-agent-load-balancer.json
{
  "ServerURL": "https://10.x.y.119:9345",
  "ServerAddresses": [
    "10.x.y.119:9345"
  ],
  "Listener": null
}
```

FYI `10.x.y.119` is the IP address of the the Control Plane/etcd node.

**Comment by rbrtbnfgl** [comment]
this should be the right config. The node with the IP 10.x.y.119 has a firewall to block the traffic to 9345 or there is a firewall on the network that connects the nodes?

**Comment by tonyrsmith** [comment]
As I previously stated: when I test the connectivity between `10.x.y.116` and `10.x.y.119` port `9345` is open.

```powershell
PS C:\> Test-NetConnection -Computer 10.x.y.119 -Port 9345

ComputerName     : 10.x.y.119
RemoteAddress    : 10.x.y.119
RemotePort       : 9345
InterfaceAlias   : vEthernet (Ethernet0)
SourceAddress    : 10.x.y.116
TcpTestSucceeded : True
```

**Comment by rbrtbnfgl** [comment]
Are the 3 linux worker working properly? Could you check if there is enough free memory and CPU on the control plane? It could be that the TCP connection works properly but the API sever is slow to respond.

**Comment by tonyrsmith** [comment]
The 3 Linux workers are running fine.

The control plane/etc node has the following hardware:

| Hardware | Size | In use |
| --- | --- | ---| 
| CPU | 4 | 1% load |
| Memory | 8 GB | 1.6 GB |
| Disk | 200 GB | 7% |

So I don't think the control plane node is under stress.


As I said in the original bug report, I think the problem might be similar to https://github.com/rancher/rke2/issues/3925, which was closed but not resolved.

**Comment by tonyrsmith** [comment]
@rbrtbnfgl Sorry for the lag, I've been working on other things.  At the time when I ran RKE2 manually via command line I had already stopped the RKE2 service in Windows services.

Anyway, thanks for your help.

**Comment by ShylajaDevadiga** [comment]
Validated with latest rc v1.27.5-rc2+rke2r1, cluster with windows and linux agents joined the server successfully
1 control plane + etcd
3 Linux agents
3 Windows agents

```
$ kubectl get nodes
NAME                                          STATUS   ROLES                       AGE    VERSION
ip-172-31-11-192.us-east-2.compute.internal   Ready    <none>                      153m   v1.27.5+rke2r1
ip-172-31-14-122.us-east-2.compute.internal   Ready    control-plane,etcd,master   157m   v1.27.5+rke2r1
ip-172-31-7-27.us-east-2.compute.internal     Ready    <none>                      153m   v1.27.5+rke2r1
ip-172-31-9-182.us-east-2.compute.internal    Ready    <none>                      153m   v1.27.5+rke2r1
ip-ac1f030a                                   Ready    <none>                      149m   v1.27.5
ip-ac1f0a86                                   Ready    <none>                      149m   v1.27.5
ip-ac1f0ab8                                   Ready    <none>                      149m   v1.27.5
```
Closing issue as resolved. Please feel free to re-open if you see the issue. It would also with calico process that is started in a loop, so if it fails, it will start again and should work.
