### ISSUE TITLE
RKE2 opens firewall on public interface after upgrade 1.22 --> 1.25

### ISSUE THREAD

**Issue by samikroon** [rancher/rke2#4394]
**Environmental Info:**
RKE2 Version:  1.25

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

5 agent nodes, dedicated servers running Ubuntu 20.04 and one server node which is a VM in our Proxmox

**Describe the bug:**

We have our setup with our own iptable rules which are being applied by a systemd process, and which blocks external traffic to our public interface. We setup RKE2 with both:

node-ip: <private address in 172.16.0.0/12 range>
node-external-ip: <private address in 172.16.0.0/12 range>

We use NGINX as an ingress, before upgrading from 1.22 to 1.25 this worked fine and incoming traffic on our ingresses was only possible from our private network. After the upgrade, RKE2 now seems to open the firewall on the public interface as well.

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

Firewall does not open port 80, 443, 8443 on our public interface.

**Actual behavior:**

Firewall does open port 80, 443, 8443 on our public interface.

**Additional context / logs:**

**Comment by samikroon** [comment]
With `ss -lntp` I can see that it is nginx/nginx-ingress which binds on `0.0.0.0` instead of the private IP, how can I change this? I already tried adding `bind-address: 172.16.0.0/12`  to the configmap of the nginx ingress controller, but that does not work either

**Comment by brandond** [comment]
> After the upgrade, RKE2 now seems to open the firewall on the public interface as well.

Can you show specifically what you mean by "open the firewall"? What iptables rules are you looking at to make this determination?

**Comment by samikroon** [comment]
The iptable rules that we apply ourselves:
```
        iptables -w -P INPUT DROP -m comment --comment "Drop incoming traffic by default" -w
        iptables -w -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Accept related or established traffic"
        iptables -w -A INPUT -i lo -j ACCEPT -m comment --comment "Accept all traffic on localhost"
        iptables -w -A INPUT -s 172.16.0.0/12 -j ACCEPT -m comment --comment "Accept all traffic on private vrack"
        iptables -w -A INPUT -p icmp -j ACCEPT
        iptables -w -A INPUT -p icmp --icmp-type 8 -d 0/0 -m state --state ESTABLISHED,RELATED -j ACCEPT
```

This would work fine in RKE2 1.22 where traffic would be blocked from the public interface. But since upgrading, I can reach the NGINX ingress over the public interface. I'm not entirely sure which iptable rules are causing it, or if iptable rules are causing it, but as the iptable rules should block non public network traffic, my gues would be that the issue lays there. If I look at the INPUT rules in iptables,
```
Chain INPUT (policy DROP 1 packets, 40 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     864K 1412M cali-INPUT  all  --  any    any     anywhere             anywhere             /* cali:Cz_u1IQiXIMmKD4c */
2     334K 1234M KUBE-PROXY-FIREWALL  all  --  any    any     anywhere             anywhere             ctstate NEW /* kubernetes load balancer firewall */
3     600K 1367M KUBE-NODEPORTS  all  --  any    any     anywhere             anywhere             /* kubernetes health check service ports */
4     334K 1234M KUBE-EXTERNAL-SERVICES  all  --  any    any     anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
5     306K  154M ACCEPT     all  --  any    any     anywhere             anywhere             state RELATED,ESTABLISHED /* Accept related or established traffic */
6    12849  775K ACCEPT     all  --  lo     any     anywhere             anywhere             /* Accept all traffic on localhost */
8     377K 1421M ACCEPT     all  --  any    any     172.16.0.0/12        anywhere             /* Accept all traffic on private vrack */
9     5170  167K ACCEPT     icmp --  any    any     anywhere             anywhere
10       0     0 ACCEPT     icmp --  any    any     anywhere             anywhere             icmp echo-request state RELATED,ESTABLISHED
```

Then my guess would be that it goes through one of the kubernetes created chains to still reach the NGINX ingress. My knowledge on iptables is quite basic so I might be totally wrong. Any suggestions on where to look are much appreciated.

I do see one difference compared to the old version, in the old version, this INPUT rule wasn't created:
```
2     334K 1234M KUBE-PROXY-FIREWALL  all  --  any    any     anywhere             anywhere             ctstate NEW /* kubernetes load balancer firewall */
```

**Comment by brandond** [comment]
Is there some reason you're trying to do this with manual firewall rules on the node instead of using Kubernetes network policy? Kubernetes and CNIs do not have any API contract around order or behavior of their managed rules, so you're going to have to evaluate and adapt to changes between component versions if you want to try to maintain a set of unmanaged rules.

**Comment by samikroon** [comment]
Not a specific reason, thank you for pointing out network policies are the way to go, I'll have a look into it tomorrow. I'll close the issue for now 🙂

**Comment by brandond** [comment]
FWIW, the KUBE-PROXY-FIREWALL rule you found was added in 1.25, from https://github.com/kubernetes/kubernetes/pull/110289.

**Comment by samikroon** [comment]
The network policies are indeed the solution, couldn't wait and tried it out. Thanks again for pointing me in the right direction!

**Comment by CrazyPilot** [comment]
What if I just want to block a set of IPs entirely on the node? 
`iptables -I INPUT -s <IP> -j DROP` blocks everything except ingresses, so attacker still can access website from this IP
