### ISSUE TITLE
Rancher Integration: Recognize RKE2 cluster on import

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#44]
Much like with K3s, add support for recognizing an imported RKE2 cluster.

**Comment by MonzElmasry** [comment]
Done, as part of https://github.com/rancher/rke2/issues/43

**Comment by davidnuzik** [comment]
Should be working (proven in demo). Just needs one more quick sanity check. Single-node is fine.

**Comment by rancher-max** [comment]
After a very short time when the rke2 cluster is imported, Rancher shows "RKE2" in the clusters view in the UI. Basic checks still work.
