### ISSUE TITLE
When specifying a profile, audit-log-path is not longer passed as an argument.

### ISSUE THREAD

**Issue by cl-rf** [rancher/rke2#4415]
**Environmental Info:**
RKE2 Version: 
v1.25.10+rke2r1, v1.26.5+rke2r1, v1.27.2+rke2r1

Node(s) CPU architecture, OS, and Version: 
RHEL 7,8,9

Cluster Configuration:
1 node

**Describe the bug:**
If the profile is set in the config.yaml, the audit-log-path is not longer set.

**Steps To Reproduce:**
- Installed RKE2: 

` ~]# echo "profile: cis-1.23" > /etc/rancher/rke2/config.yaml`

**Expected behavior:**
The audit-log-path is set per the profile flag.

`root     24317  6.0  4.8 1255964 391944 ?      Ssl  14:13   2:55  \_ kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log --audit-policy-file=/etc/rancher/rke2/audi -policy.yaml --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100`

**Actual behavior:**
The audit-log-path is no longer set

`root      181256 20.9  5.8 1255624 464056 ?      Ssl  17:18   0:34  \_ kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-policy-file=/etc/rancher/rke2/audit-policy.yaml --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 `

**Additional context / logs:**
The other audit arguments are passed. It is just the path that is no longer there.

**Comment by est-suse** [comment]
### Validated on <branch-name> branch with commit <commit-id> / version <version>
 ```
Master Branch: b808f56d271663c3bc050afe93a59fde61e10ab8
rke2 version v1.27.3+dev.b808f56d (b808f56d271663c3bc050afe93a59fde61e10ab8)
go version go1.20.5 X:boringcrypto

```
## Environment Details

 
*Infrastructure*
- [X] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
token: secret
write-kubeconfig-mode: 644
profile: cis-1.23
debug: true
```
 
*Additional files*

```
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install rke2
3.Check the pod for kube-apiserver:


 
 
**Replication Results:**
- rke2 version used for replication:

```
Replicate on Version 1.27.3:

kubectl get pod -o yaml -n kube-system kube-apiserver-ip-172-31-23-202

    - --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml
    - --audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --allow-privileged=true
    - --anonymous-auth=false
```
 

 
**Validation Results:**
- k3s version used for validation:

```


```
 

```
Validated with commit ID b808f56d271663c3bc050afe93a59fde61e10ab8:

kubectl get pod -o yaml -n kube-system kube-apiserver-ip-172-31-31-102

  containers:
  - args:
    - --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml
    - --audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log
```
