### ISSUE TITLE
K3S Error Adding Node

### ISSUE THREAD

**Issue by textgroove-steven** [rancher/rke2#4418]
**Environmental Info:**
RKE2 Version: K3S v1.23.17+k3s1	

Node(s) CPU architecture, OS, and Version: 
Ubuntu 22.04

Cluster Configuration:
4 Total servers, 3 All, 1 Worker

**Describe the bug:**
When adding a worker node, it does not join. I took a look through the logs and I am seeing the following error `Incorrect Usage: flag provided but not defined: -system-default-registry`. Not sure how to fix this/proceed.

**Steps To Reproduce:**
- Added node using the generated registration command

**Expected behavior:**
Expected worker node to join the cluster

**Actual behavior:**
Node is not joining with the error `configuring worker node(s) custom-0727771e1c0e: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for agent to check in and apply initial plan`

**Additional context / logs:**
It keeps trying to boot in a loop with the error `Incorrect Usage: flag provided but not defined: -system-default-registry`

**Comment by brandond** [comment]
I'm confused, you opened an issue in the RKE2 repo for a problem with K3s? Did you mean to open this issue at https://github.com/k3s-io/k3s?

**Comment by textgroove-steven** [comment]
@brandond

No, I did not mean to open it there. I opened it here because I used rancher to configure the cluster. K3S became officially supported along with RKE2, however, I could not find a k3s branch within any of the rancher repositories so I figured I would open it here, then get it moved to the proper rancher team. Does rancher/suse manage k3s?
