### ISSUE TITLE
Outdated FelixConfiguration CRD with Canal CNI

### ISSUE THREAD

**Issue by moray95** [rancher/rke2#4453]
**Environmental Info:**
RKE2 Version: 

```
$ rke2 -v
rke2 version v1.25.8+rke2r1 (a8edcda62ba13bb226f1dc8a429f2e37c0e81df0)
go version go1.19.7 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

```
$ uname -a
Linux master-0 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration: 3 servers, 4 agents

**Describe the bug:**

When using the default Canal CNI plugin, the `FelixConfiguration` CRD deployed by RKE2 does not have the option `workloadSourceSpoofing`. 

This option has been added in Calico 3.23.0 (PR [here](https://github.com/projectcalico/calico/pull/5742), release notes [here](https://docs.tigera.io/archive/v3.23/release-notes/#v3230)). RKE2 seems to deploy Calico v3.25.0 based on the output of `helm ls` and container image version. The CRD provided by the RKE2 helm chart [here](https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/templates/crds/felixconfigurations.crd.yaml) does not contain `workloadSourceSpoofing`, while [the official Calico CRD manifests](https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/canal.yaml) has it.

**Steps To Reproduce:**

Install RKE2 with the default Canal CNI plugin. Find the attributes present for the FelixConfiguration CRD with `kubectl explain FelixConfiguration.spec`.

**Expected behavior:**

The output should contain the `workloadSourceSpoofing` option.

**Actual behavior:**
The output does not contain the `workloadSourceSpoofing` option.

**Additional context / logs:**

We have stumbled upon this issue while trying to install Istio Ambient mesh, following [their steps](https://github.com/istio/istio/tree/master/cni/pkg/ebpf) for Calico CNI.

**Comment by rbrtbnfgl** [comment]
Hi I'm not sure that this will work even with the update of the CRD chart on Canal. Canal is using Flannel for the pod networking and Calico to setup the network policies. If you want to use a more complex setup related to Calico I suggest you to directly use Calico as CNI.

**Comment by moray95** [comment]
Hello @rbrtbnfgl , we were able to achieve the desired outcome by setting the environment variable `FELIX_WORKLOADSOURCESPOOFING` on the Canal DaemonSet's Calico container as a work-around.

**Comment by rbrtbnfgl** [comment]
Ok so it'll work on Canal. I'll try to automate the CRD update with the Calico version on the Canal Chart.

**Comment by bguzman-3pillar** [comment]
### Validated on commit 33caf61cf1fc71cca522eaeac1d3541b5f3c417c
```
---------------------
Command:
 rke2 -v
---------------------
Result:
rke2 version v1.27.3+dev.33caf61c (33caf61cf1fc71cca522eaeac1d3541b5f3c417c)
go version go1.20.5 X:boringcrypto
---------------------
```
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Ubuntu
```
  
*Cluster Configuration:*

```
1 server
```
  
*Config.yaml:*

```
cni: canal
```
  
*Additional files*

```
# Install
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
3. Install helm
4. Check for the `workloadSourceSpoofing` to be present on `FelixConfiguration.spec`
5. Check the canal version `v3.25.1-build2023051203`

 
**Validation Results:**
- rke2 version used for validation:

```
---------------------
Command:
kubectl explain FelixConfiguration.spec  --kubeconfig=/tmp/bgrke2-127_kubeconfig  | grep workload

---------------------
Result:
     drop IPIP encapsulated traffic from workloads [Default: false]
     drop VXLAN encapsulated traffic from workloads [Default: false]
     network. This needs to match the interfaces that Calico workload traffic
     workload interfaces (usually named cali...).
     remote workloads. If set to "Tunnel" then both request and response traffic
     mode for workloads and services. [Default: true - bypass Linux conntrack]
     Calico workload traffic flows over as well as any interfaces that handle
     large enough to hold an entry for each device (host + workloads) on a host.
     large enough to hold one entry per workload and a handful of entries per
     a workload endpoint to the host itself (after the traffic hits the endpoint
     egress policy). By default Calico blocks traffic from workload endpoints to
     packets to the "INPUT" chain once it has completed processing workload
     workloads after processing workload endpoint egress policy. [Default: Drop]
     workloads or if CPU is constrained. For a list of active subcomponents, see
     InterfacePrefix is the interface name prefix that identifies workload
     these ranges to separate host and workload traffic. [Default: 30000:32767].
     match workload interfaces (usually named cali...).
     WorkloadIPs: use workload endpoints to construct routes. - CalicoIPAM: the
   workloadSourceSpoofing       <string>
---------------------
```

```
---------------------
Command:
 helm ls -A  --kubeconfig=/tmp/bgrke2-127_kubeconfig | grep rke2-canal
---------------------
Result:
rke2-canal                              kube-system     1               2023-07-13 21:28:05.345198862 +0000 UTC deployed        rke2-canal-v3.25.1-build2023051203              v3.25.1    
---------------------
```
