### ISSUE TITLE
RKE2 agent wont join with server is not ready

### ISSUE THREAD

**Issue by joelcomp1** [rancher/rke2#4478]
**Environmental Info:**
RKE2 Version: 
1.27.2

Node(s) CPU architecture, OS, and Version: 
Linux npsv05.muos.lab 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
8 nodes,  3 control plane / workers, then 5 stand alone workers

**Describe the bug:**
I have 8 nodes, 7 are working without issue, when I try to join the last node (as a worker) it fails in journalctl with:

Jul 17 21:56:08 npsv05.muos.lab sudo[143466]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul 17 21:56:08 npsv05.muos.lab sudo[143466]: pam_unix(sudo:session): session opened for user root by jmillage(uid=0)
Jul 17 21:56:09 npsv05.muos.lab rke2[143408]: time="2023-07-17T21:56:09-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or content>
Jul 17 21:56:10 npsv05.muos.lab rke2[143408]: time="2023-07-17T21:56:10-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or content>
Jul 17 21:56:12 npsv05.muos.lab sudo[143466]: pam_unix(sudo:session): session closed for user root
Jul 17 21:56:12 npsv05.muos.lab rke2[143408]: time="2023-07-17T21:56:12-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or content>
Jul 17 21:56:47 npsv05.muos.lab rke2[143408]: time="2023-07-17T21:56:47-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or content>
Jul 17 21:57:02 npsv05.muos.lab rke2[143408]: time="2023-07-17T21:57:02-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: failed to get CA certs: Get \"https://127.0.0.1:6444/>
Jul 17 21:57:06 npsv05.muos.lab sudo[143494]: jmillage : TTY=pts/1 ; PWD=/home/jmillage ; USER=root ; COMMAND=/bin/journalctl

**Steps To Reproduce:**
restart the rke2-agent service, it will never go to running

**Expected behavior:**
Node should join

**Actual behavior:**
node never joins

**Additional context / logs:**
I have tried uninstalling / re-installing RKE2 bash script, i have tried rebooting. I can't think of anything else. It's like it think's its already in the cluster but its not in the node list

**Comment by manuelbuil** [comment]
`Node password rejected, duplicate hostname or content>` is it possible that the node connected once and you uninstalled rke2 in the node without doing `kubectl delete node ....`? In that case, you should manually remove the secret that represents the password for that node

**Comment by joelcomp1** [comment]
Yes I think that is entirely possible.   Is that secret on the node that I am having issues with or on the control plane node I am trying to join? I assumed if it was on the node I was having issues with that running /usr/bin/rke2-uninstall.sh would have removed it

**Comment by manuelbuil** [comment]
I don't have an rke2 cluster with me right now but if you do `kubectl get secrets -A` you should see a secret that has the name of the node and IIRC, the string "password". Just remove that secret and then try adding the worker node again

**Comment by joelcomp1** [comment]
Awesome you are a life saver, there is a secret for each node in kube-system namespace, had no idea, thank you so much!
