### ISSUE TITLE
Add calico-bgp test for windows

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4486]
**Is your feature request related to a problem? Please describe.**

rke2-windows can now use calico-bgp with this new PR https://github.com/rancher/rke2/pull/4164

We should replicate the [mixedos e2e test](https://github.com/rancher/rke2/tree/master/tests/e2e/mixedos) but using calico-bgp and verify that traffic between linux and windows works. 

Warning! Some iptables magic would need to be applied to avoid packets being dropped 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
Thank you for the updates to the tests! 🎉
