### ISSUE TITLE
Provide support for multi-arch SRIOV images

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4489]
**Is your feature request related to a problem? Please describe.**

SRIOV images now support arm64 but drone was not updated to push multi-arch images. As a consequence, the sriov image will use amd64 or arm64 depending on which image is pushed the last.

Example: https://github.com/rancher/image-build-sriov-operator and https://hub.docker.com/r/rancher/hardened-sriov-network-operator/tags

This is happening in all sriov images:
* https://github.com/rancher/image-build-sriov-network-resources-injector
* https://github.com/rancher/image-build-sriov-network-device-plugin
* https://github.com/rancher/image-build-sriov-operator
* https://github.com/rancher/image-build-ib-sriov-cni
* https://github.com/rancher/image-build-sriov-cni

**Describe the solution you'd like**

I would like all sriov images to be multi-arch (amd64 and arm64). For example like multus: https://hub.docker.com/r/rancher/hardened-multus-cni/tags

**Describe alternatives you've considered**

**Additional context**

**Comment by manuelbuil** [comment]
The update of those images will be done as part of https://github.com/rancher/rke2/issues/4654

**Comment by ShylajaDevadiga** [comment]
Unable to test arm64 SRIOV image support as we do not have the necessary hardware. Will cover amd64 as part validating https://github.com/rancher/rke2/issues/4654
