### ISSUE TITLE
update nfd to v0.14.1

### ISSUE THREAD

**Issue by thomasferrandiz** [rancher/rke2#4499]
https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.13.3

**Comment by mgfritch** [comment]
nfd `v0.13.3` does not work with with k8s 1.28, let's target an update to nfd `v0.14.0` instead.

**Comment by ShylajaDevadiga** [comment]
Validated as part of https://github.com/rancher/rke2/issues/4654#issuecomment-1758831827
