### ISSUE TITLE
kubeVersion constrait not flexible for eks-distro or another distro

### ISSUE THREAD

**Issue by kubilaykaptanoglu** [rancher/rke2#4514]
When I try install rke2 with eks-distro. I have to install all component manually(canal,coredns,metrics-server etc.) I think, this constrait should be removed on charts.

Example for canal initialize: 
> k logs -f helm-install-rke2-canal-zxbht -n kube-system
Error: INSTALLATION FAILED: chart requires kubeVersion: >= v1.26.6 which is incompatible with Kubernetes v1.26.6-eks-3316523. 

Because when we use a distro with rke2 our kubernetes version contains different letters.

**Comment by brandond** [comment]
This is due to how helm's semver comparisons work. According to semver, the `v1.26.6-eks-3316523` version returned by EKS is a release candidate for 1.26.6, and therefore does not meet the 1.26.6 minimum version requirement. See: https://semver.org/#spec-item-9
