### ISSUE TITLE
Update canal version

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4515]
**Is your feature request related to a problem? Please describe.**

Canal is currently using old versions:
* Calico v3.25.1 (instead of v3.26.x)
* Flannel v0.22.0 (instead of v0.22.1)

We should upgrade

**Describe the solution you'd like**

Use newer versions

**Describe alternatives you've considered**

**Additional context**

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  rke2 version v1.27.4+dev.875fb76d (875fb76d65140495d3339aa9a188c1a019f9738c)

```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04
Windows 2019

*Cluster Configuration:*
1 node cluster 

*Config yaml:*
```console
write-kubeconfig-mode: 644
```



## Steps to validate the fix
1. Install rke2 with commit ID
2. Get the version of flannel and calico
3. Check the nodes and pods


## **Validation Results:**
<details>

```
~$ rke2 -v

rke2 version v1.27.4+dev.875fb76d (875fb76d65140495d3339aa9a188c1a019f9738c)


$ kubectl -n kube-system get pods -l k8s-app=canal -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq -c
      3 docker.io/rancher/hardened-calico:v3.26.1-build20230802
      1 docker.io/rancher/hardened-flannel:v0.22.1-build20230802
      3 rancher/hardened-calico:v3.26.1-build20230802
      1 rancher/hardened-flannel:v0.22.1-build20230802


```
