### ISSUE TITLE
metrics unable to handle the request with cilium and cis-1.23

### ISSUE THREAD

**Issue by soulwhisper** [rancher/rke2#4517]
**Description:**
When installing cilium on a recent enough vSphere version (v6 or v7) and VMXNet driver, cilium connectivity breaks because of hardware segmentation offload.

**Error Example:**
 `failed calling webhook` 
 `failing or missing response` 

**Solution:**
```
sudo ethtool -K ens192 tx-udp_tnl-segmentation off
sudo ethtool -K ens192 tx-udp_tnl-csum-segmentation off
```

Notice, **you need to run above commands every time the VM reboot**. A systemd example below:
```
[Unit]
Description=Disables UDP offload
After=NetworkManager-wait-online.service
RefuseManualStart=true
RefuseManualStop=true

[Service]
Type=oneshot
ExecStart=/usr/sbin/ethtool -K ens192 tx-udp_tnl-segmentation off
ExecStart=/usr/sbin/ethtool -K ens192 tx-udp_tnl-csum-segmentation off
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
```

For more info, check [this issue](https://github.com/cilium/cilium/issues/21801).

**Comment by soulwhisper** [comment]
anyway, it is hard to find what you do with flannel when cis is enabled, the solution should be a helmconfig according to what you did before.

**Comment by brandond** [comment]
You'd need to check the metrics-server pod logs to see why it is unable to scrape node metrics. It may be necessary to edit the deployment to increase the verbosity and figure out why.

**Comment by soulwhisper** [comment]
besides this one, when I try to install rancher on a fresh install rke2 with above config, it reports
`
Error: 2 errors occurred:
        * Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded
        * Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
`

**Comment by soulwhisper** [comment]
I also tried [overlay-test](https://ranchermanager.docs.rancher.com/zh/troubleshooting/other-troubleshooting-tips/networking), it shows that pod-to-pod communication is blocked.

**Comment by soulwhisper** [comment]
with `cilium connectivity test`, it shows "connectivity test failed: timeout reached waiting for lookup for localhost from pod cilium-test/client-c4bfddc44-lxb8g to server on pod cilium-test/echo-other-node-646976b7dd-4962w to succeed (last error: context deadline exceeded)", should lead to same root cause ---- I need a specific policy for cilium to work.

**Comment by soulwhisper** [comment]
`kubectl -n kube-system exec ds/cilium -- cilium status --verbose` reports no error, except all endpoints shows as "unreachable"

**Comment by soulwhisper** [comment]
Milstone: cilium unreachable / metrics bug can be fixed with method in [this issue](https://github.com/cilium/cilium/issues/21801). tested.

**Comment by brandond** [comment]
> `failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"`

This suggests that there are no pods running to host the cert-manager-webhook service. Can you confirm that cert-manager has been deployed successfully?

**Comment by soulwhisper** [comment]
> > `failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"`
> 
> This suggests that there are no pods running to host the cert-manager-webhook service. Can you confirm that cert-manager has been deployed successfully?

This lead to the same root cause that pod-to-pod communication is blocked. I install rancher as test again with CIS disabled, now I get the welcome word.

**Comment by soulwhisper** [comment]
@brandond bug solved, solution added, issus closed.
