### ISSUE TITLE
rke2-uninstall.sh uninstall consent.

### ISSUE THREAD

**Issue by busyboy77** [rancher/rke2#4522]
Cam you please add a 

* option in the `rke2-uninstall.sh` script that confirms the end-user with a consent this is going to remove all the data?
* force or override the above question to be used in scripts like `--confirm-deletion`

**Comment by brandond** [comment]
Duplicate of https://github.com/rancher/rke2/issues/3928 - see https://github.com/rancher/rke2/issues/3928#issuecomment-1437484236
