### ISSUE TITLE
Control plane pods do not come back up after restarting node

### ISSUE THREAD

**Issue by GwynHannay** [rancher/rke2#4526]
### **Environmental Info:**
**RKE2 Version:** 
rke2 version v1.26.6+rke2r1 (59620dfabfb8d60ef9f6d7da98faad3958dc6609)
go version go1.19.10 X:boringcrypto

**Node(s) CPU architecture, OS, and Version:** 
Linux homesys 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Cluster Configuration:**
Single node RKE2 on a VM created in VMWare ESXi

### **Describe the bug:**
Control plane pods do not start properly again after restarting the node. State:
- cloud-controller-manager: stuck on Createcontainererror, presumably because of missing permissions for the API Server configmaps? (_Fatal error running RKE2 Cloud Provider: unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "rke2-cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"_)
- etcd: running but not ready
- kube-apiserver: running but not ready
- kube-controller-manager: running but not ready
- kube-proxy: running but not ready
- kube-scheduler: running but not ready

### **Steps To Reproduce:**
**Installing RKE2**: 
These are my notes for how I install RKE2:

> #### Setup VM
> - Install Ubuntu from ISO
>     - Update to new installer
>     - Deselect "create disk as LVM group"
>     - Select to enable SSH, import SSH identity from GitHub
> - Set timezone: `sudo timedatectl set-timezone Australia/Perth`
> - Disable swap (`swapoff -a`, then edit '/etc/fstab')
> - Set _fs.inotify.max_user_instances=512_ in '/etc/sysctl.d/99-sysctl.conf' and run `sudo service procps force-reload`
> - Update all packages and autoremove
> - Create NFS mounts and add user for NFS mount
> - Create RKE2 config file (`sudo mkdir -p /etc/rancher/rke2` then `sudo touch /etc/rancher/rke2/config.yaml`), and copy contents:
```
control-plane-resource-requests:
  - cloud-controller-manager-cpu=5m
  - etcd-cpu=50m
  - kube-apiserver-cpu=150m
  - kube-controller-manager-cpu=20m
  - kube-proxy-cpu=1m
  - kube-scheduler-cpu=5m`
```
> #### Commands
```
# Install RKE2
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.26.6+rke2r1 sh -
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
sudo systemctl status rke2-server.service

# Use kubectl
mkdir .kube
sudo cp /etc/rancher/rke2/rke2.yaml .kube/config
sudo chown -R homesys:homesys .kube/
sudo nano /etc/profile
# Add this to bottom of file, then log out and back in
export PATH="/var/lib/rancher/rke2/bin:$PATH"

# Install Helm
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Install Cert-Manager, External-DNS, and Rancher charts
helm repo add jetstack https://charts.jetstack.io
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo update

# Install Cert-Manager
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.crds.yaml
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.12.2
```
> - Create and apply YAML files from repo:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      allowSnippetAnnotations: true
      publishService:
        enabled: true
      service:
        enabled: true
      resources:
        requests:
          cpu: "10m"
```
> - Create CloudFlare API key in cert-manager
> - Create "infra" namespace
> - Add CloudFlare API key in infra
> - Create and apply [cluster issuer](https://github.com/GwynHannay/homeserver/blob/main/rke2/cert-manager/cluster_issuer.yaml)
> - Create Rancher values file [rancher_values.yaml](https://github.com/GwynHannay/homeserver/blob/main/rke2/rancher.yaml)
> - Run commands:
```
# Install External-DNS
helm install external-dns bitnami/external-dns --namespace infra --set provider=cloudflare --set cloudflare.secretName=provider --set cloudflare.proxied=false --set replicaCount=1

# Install Rancher
helm install rancher rancher-latest/rancher --create-namespace --namespace cattle-system -f tmpyamls/rancher_values.yaml
```
> - Log into Rancher UI when it's up and running, then create all secrets necessary.
> - Install prerequisites script for Longhorn: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/prerequisite/longhorn-iscsi-installation.yaml`
> - Set up GitHub Repo in Fleet

This is the repo of all the stuff I run, which I kind of rolled out bit by bit: https://github.com/GwynHannay/homeserver/tree/main

**Restart node**
- Drain node: `kubectl drain --ignore-daemonsets --delete-emptydir-data --force homesys` (Longhorn won't evict, but I wait until it looks like everything else has drained, then Ctrl + C)
- Reboot VM
- Uncordon node: `kubectl uncordon homesys`
- Delete pods for MetalLB Speaker and rke2-nginx-ingress-controller so they recreate
- After troubleshooting for a while, restart RKE2 `sudo systemctl restart rke2-server.service`
- Control plane pods still in state mentioned above

### **Expected behavior:**
- For control plane pods to come back up

### **Actual behavior:**
- Control plane pods are either not ready or cannot create containers:
    - cloud-controller-manager: stuck on Createcontainererror, presumably because of missing permissions for the API Server configmaps? (_Fatal error running RKE2 Cloud Provider: unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "rke2-cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"_)
    - etcd: running but not ready
    - kube-apiserver: running but not ready
    - kube-controller-manager: running but not ready
    - kube-proxy: running but not ready
    - kube-scheduler: running but not ready

### **Additional context / logs:**
- I've tried troubleshooting this myself a fair bit, and it first happened when I was following advice on changing control plane requests in issue #4323
- In that instance, I just deleted my VM and started the installation process from the beginning of my notes above.
- The cloud-controller-manager says that user "rke2-cloud-controller-manager" can't access the configmap for the API server, and suggests creating a role binding for it, but there is no service account with that name
- I'm a bit lost on what to look for

**Comment by brandond** [comment]
Why are you reducing all the requests? Are you trying to squeeze all the components into a node that does not meet the CPU and memory requirements for a server node? Do you experience these same issues if you allocate additional resources and use a VM with more cores and memory?

**Comment by GwynHannay** [comment]
Because those components don't use anywhere _near_ that amount of CPU in their day-to-day operation - I'm running a single node RKE2 on an Intel Core i5 (4 cores) with 32GB that's sitting in my server rack. Allowing the control plane to request far more CPU than it uses just prevents me from being able to schedule other apps.

Or does the control plane require all that CPU, but only when being restarted? :-/

**Comment by brandond** [comment]
The fact that they're running but not ready suggests that they're not actually functional with the resources that you're giving them, although the core underlying resource constraint may be something else (disk IO, for example). If you don't deploy any workload, and leave the control-plane resource requests set the the defaults, does everything come up and ready?

**Comment by GwynHannay** [comment]
Okay, so I went ahead and uninstalled RKE2 via the rke2-uninstall.sh script, then did the following:

- Installed RKE2 with no config options:
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.26.6+rke2r1 sh -
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
```
- Once everything was running: `kubectl drain --ignore-daemonsets --delete-emptydir-data --force homesys`
- Rebooted the machine once everything was safely drained, then `kubectl uncordon homesys`
- Waited a while for things to come back and they didn't, so I restarted RKE2: `sudo systemctl restart rke2-server.service`

The outcome - with nothing else deployed and using default resource requests - is the same:
![Screenshot 2023-08-01 at 13 40 14](https://github.com/rancher/rke2/assets/8345824/a79f316d-e3a9-419c-94e2-6732908aca4e)

Looking at the events, I think this is the same thing I faced last time and ended up just deleting my VM and starting from scratch. My understanding from the research I did that day is that there's some issues with the race condition for everything coming up at once and the underlying container runtime.

![Screenshot 2023-08-01 at 13 43 19](https://github.com/rancher/rke2/assets/8345824/e0b8294c-2d13-4438-9f26-eb27144b1644)

> Error: failed to reserve container name "cloud-controller-manager_cloud-controller-manager-homesys_kube-system_1a84611ed06607ed8a51e65d936a6ff0_2": name "cloud-controller-manager_cloud-controller-manager-homesys_kube-system_1a84611ed06607ed8a51e65d936a6ff0_2" is reserved for "cd87a109aeb6b7f4c4423e63c01e0ff42be9a9c87f228f7d1ddd1f7bbd51d5d7"

**Comment by brandond** [comment]
I don't think I've ever seen the pod restart time listed as `<invalid>`. There is definitely something odd going on with your node, but not something I've seen before. If you can figure out how to reproduce any of this on demand, I'd love to know what is causing it.

What is the goal of cordoning, draining, and rebooting the node? Are you just trying to see what happens?

**Comment by GwynHannay** [comment]
Seeing `<invalid>` after rebooting a node has been pretty consistent for me, even when I was using k3s. I did wonder if there are issues with timezone somewhere, because I tend to set my timezone whenever I see an option to do so, and it has resulted in some of my logs sometimes adding another 8 hours.

The use case for draining and rebooting the node is when Ubuntu prompts me to do so after updating the packages. It's pretty common for me to do this since I try to keep everything up to date, but I'd also hate to go through this every time there's a power outage or if I have to unplug and move my machine or anything.

This issue is as far as I got when digging into it last month before deciding to delete the VM and start from scratch: https://github.com/containerd/containerd/issues/4604

**Comment by brandond** [comment]
Is your system time going backwards when you restart the node, or something like that?

**Comment by GwynHannay** [comment]
Not as far as I know, but I haven't done any specific digging as of yet. I'll be doing another rebuild at some point in the next few days or weeks to better separate my storage drive from the one running Kubernetes, so I can do some experiments then and see if I can spot the timezone weirdness.

I wonder, is it generally just bad practice to set your server OS timezone to anything other than UTC? I don't usually see others doing it but it always bugged me having to mentally convert logs to my timezone, haha.
