### ISSUE TITLE
Check calico or felix related env variables in windows

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4580]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently, calico-node or felix do not check on OS level env variables when executing their processes, something that makes it hard to change the default config

**Describe alternatives you've considered**

**Additional context**

**Comment by rbrtbnfgl** [comment]
The Calico services on Windows aren't getting the OS env they need to be manually configured on the code.
We are generating the env with https://github.com/rancher/rke2/blob/master/pkg/windows/calico.go#L470
The env from the OS should be manually copied using `os.Getenv` https://github.com/rancher/rke2/blob/master/pkg/windows/calico.go#L398

**Comment by manuelbuil** [comment]
> The Calico services on Windows aren't getting the OS env they need to be manually configured on the code. We are generating the env with https://github.com/rancher/rke2/blob/master/pkg/windows/calico.go#L470 The env from the OS should be manually copied using `os.Getenv` https://github.com/rancher/rke2/blob/master/pkg/windows/calico.go#L398

Yes! I have a PR on the works ;)

**Comment by est-suse** [comment]
For Visibility.

The C:\var\log/felix is not being created, check with the commit ID: https://github.com/rancher/rke2/commit/70c3aee2bb1f46b8a19540e13e857786ecd4606c

The result of Get-HNSNetwork is nor showing calico as a network:


ActivityId             : C6B0351B-A290-4F80-827F-EFAA302F624D
AdditionalParams       :
CurrentEndpointCount   : 0
Extensions             : {@{Id=E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A; IsEnabled=False; Name=Microsoft Windows Filtering
                         Platform}, @{Id=E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017; IsEnabled=False; Name=Microsoft Azure
                         VFP Switch Extension}, @{Id=EA24CD6C-D17A-4348-9190-09F0D5BE83DD; IsEnabled=True;
                         Name=Microsoft NDIS Capture}}
Flags                  : 0
Health                 : @{AddressNotificationMissedCount=0; AddressNotificationSequenceNumber=0;
                         InterfaceNotificationMissedCount=0; InterfaceNotificationSequenceNumber=0; LastErrorCode=0;
                         LastUpdateTime=133370975609612046; RouteNotificationMissedCount=0;
                         RouteNotificationSequenceNumber=0}
ID                     : 926EFCED-6D9E-4B1C-B592-00D0C7900CEF
IPv6                   : False
LayeredOn              : C8ED85A5-51B2-42A3-BD3E-1A55D540771C
MacPools               : {@{EndMacAddress=00-15-5D-FF-5F-FF; StartMacAddress=00-15-5D-FF-50-00}}
MaxConcurrentEndpoints : 0
Name                   : nat
NatName                : ICSEFD2DDE5-4FDD-47D7-9187-13C004F22EB8
Policies               : {}
Resources              : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; Health=;
                         ID=C6B0351B-A290-4F80-827F-EFAA302F624D; PortOperationTime=0; State=1; SwitchOperationTime=0;
                         VfpOperationTime=0; parentId=E5562E80-6618-482A-B00E-CB56070E028B}
State                  : 1
Subnets                : {@{AdditionalParams=; AddressPrefix=172.30.128.0/20; GatewayAddress=172.30.128.1; Health=;
                         ID=F404D3EB-68A2-4F04-B560-CB2F08D04623; Policies=System.Object[]; State=0}}
TotalEndpoints         : 0
Type                   : nat
Version                : 38654705669

ActivityId             : 371F0876-AE5C-44A9-93E4-D7FBD56747C2
AdditionalParams       :
CurrentEndpointCount   : 0
DNSServerCompartment   : 3
DrMacAddress           : 00-15-5D-D3-EB-1F
Extensions             : {@{Id=E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A; IsEnabled=False; Name=Microsoft Windows Filtering
                         Platform}, @{Id=E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017; IsEnabled=True; Name=Microsoft Azure
                         VFP Switch Extension}, @{Id=EA24CD6C-D17A-4348-9190-09F0D5BE83DD; IsEnabled=True;
                         Name=Microsoft NDIS Capture}}
Flags                  : 0
Health                 : @{LastErrorCode=0; LastUpdateTime=133371053797007946}
ID                     : A2F52629-6E15-40BD-90C6-541DD593D1A8
IPv6                   : False
LayeredOn              : 0FE14CDD-6626-4D62-9F40-66EB11FCD67A
MacPools               : {@{EndMacAddress=00-15-5D-7E-5F-FF; StartMacAddress=00-15-5D-7E-50-00}}
ManagementIP           : 172.31.7.77
MaxConcurrentEndpoints : 0
Name                   : External
NetworkAdapterName     : Ethernet 2
Policies               : {}
Resources              : @{AdditionalParams=; AllocationOrder=1; Allocators=System.Object[]; Health=;
                         ID=371F0876-AE5C-44A9-93E4-D7FBD56747C2; PortOperationTime=0; State=1; SwitchOperationTime=0;
                         VfpOperationTime=0; parentId=D5A5C34A-D3C8-4D7D-915B-C7973991CEFD}
State                  : 1
Subnets                : {@{AdditionalParams=; AddressPrefix=192.168.255.0/30; GatewayAddress=192.168.255.1; Health=;
                         ID=8496FCB5-2B3E-45C1-81F8-11F0F5188B77; ObjectType=5; Policies=System.Object[]; State=0}}
TotalEndpoints         : 0
Type                   : Overlay
Version                : 38654705669
Manuel is currently working on a solution

**Comment by est-suse** [comment]
Validated on master branch with commit 3ab96dd0016a637f48672b011822de5a35c96045


Environment Details
Infrastructure

 Cloud
 Hosted
Node(s) CPU architecture, OS, and Version:
```
Ubuntu 22.04 as Linux server and agent
Windows 2019 (1809) as Windows agent node
```

Cluster Configuration:
```
NAME                                         STATUS   ROLES                       AGE   VERSION
ip-172-31-1-182.us-east-2.compute.internal   Ready    control-plane,etcd,master   18h   v1.27.4+rke2r1
ip-172-31-3-150.us-east-2.compute.internal   Ready    control-plane,etcd,master   18h   v1.27.4+rke2r1
ip-172-31-3-228.us-east-2.compute.internal   Ready    <none>                      18h   v1.27.4+rke2r1
ip-172-31-6-253.us-east-2.compute.internal   Ready    control-plane,etcd,master   18h   v1.27.4+rke2r1
ip-ac1f055f                                  Ready    <none>                      58s   v1.27.4
```
Config.yaml:
```
write-kubeconfig-mode: "0644"
cni: calico
```

Testing Steps
```
Copy config.yaml
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
Install RKE2 on server node
Join agent node and Windows agent node
Add the system variable: [System.Environment]::SetEnvironmentVariable('FELIX_DATASTORETYPE','etcdv3', 'Machine')
```

Validate the logs are shwoing the OS varaibale: 
```

 Get-EventLog -LogName Application -Source 'rke2'  -Newest 200 | select-object -Property TimeWritten,ReplacementStrings | Format-Table -Wrap

8/23/2023 3:59:31 PM  {Felix Envs: [KUBE_NETWORK=Calico.* KUBECONFIG=c:\var\lib\rancher\rke2\agent\calico.kubeconfig NODENAME=ip-ac1f055f CALICO_K8S_NODE_REF=ip-ac1f055f IP=172.31.5.95 USE_POD_CIDR=false FELIX_FELIXHOSTNAME=ip-ac1f055f FELIX_VXLANVNI=4096 FELIX_DATASTORETYPE=kubernetes FELIX_DATASTORETYPE=etcdv3]}
```

from var/logs/felix:
```
2023-08-23 15:59:31.505 [INFO][5912] felix/config_params.go 612: Parsing value for DatastoreType: etcdv3 (from environment variable)
2023-08-23 15:59:31.505 [INFO][5912] felix/config_params.go 648: Parsed value for DatastoreType: etcdv3 (from environment variable)
```
