### ISSUE TITLE
Add port 2381 to RKE2 documentation

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rke2#4602]
Port 2381 is used on a default RKE2 install, but it's not listed in the port requirements for RKE2:

https://docs.rke2.io/install/requirements

Could we get this added?

**Comment by manuelbuil** [comment]
+1, it is the healthport for etcd pod ==> https://github.com/rancher/rke2/blob/master/pkg/podexecutor/staticpod.go#L533

**Comment by brandond** [comment]
moving out of the milestone since docs are not part of the release.
