### ISSUE TITLE
system_default_registry is not propagated to all cilium containers causing Air-gapped installations to fail

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rke2#4603]
**Environmental Info:**
RKE2 Version: 
v1.25.11+rke2r1

**Describe the bug:**
Patched cilium chart [1.13.2](https://github.com/rancher/rke2-charts/tree/30474a81db4ce683d96532696c3dc6f0b18c4dfd/packages/rke2-cilium) used in 1.25.11 rke2 is missing system_default_registry patch for couple init containers:
`name: config`: https://github.com/cilium/cilium/blob/v1.13.2/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L408
`name: install-cni-binaries`: https://github.com/cilium/cilium/blob/v1.13.2/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L673

**Steps To Reproduce:**
Install RKE2 with cilium CNI in Air gapped environment with default system registry set.
**Expected behavior:**
All cilium containers get correct default system registry

**Actual behavior:**
2 init containers didn't use system default registry

**Additional context / logs:**
none

**Comment by riuvshyn** [comment]
Oh I just noticed it was fixed with upgrading to 1.14 cilium https://github.com/rancher/rke2-charts/commit/97bdb7eb6e8a37e2b1bb20e61b8815d40a2e11af#diff-93d48583c8aa1bd680259f56e6f8cc4b836b7ad2eaa9495cfae2ea1143d23743

When can we expect cilium 1.14 to be available for 1.25.x rke2?

**Comment by brandond** [comment]
This will be included in the next round of patch releases.
