### ISSUE TITLE
Few files not well formatted

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4604]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

The code includes a few files that are not well formatted

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by est-suse** [comment]
After talking to @manuelbuil , The issue is to format a couple of files. performed an installation as a smoke testing.

Validated on master branch: commit id: 000ce7f68fe2f79074d10353a20e9b4f9f3685d9
