### ISSUE TITLE
ETCD snapshot retaining failed s3 backups

### ISSUE THREAD

**Issue by felipe-colussi** [rancher/rke2#4632]
**Environmental Info:**

rke2 version v1.26.7+rke2r1 (374bdaf23d963e7d16bcaa820e95f792b1d3c661)
go version go1.20.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux felipe-test-do-dont-delete-pool1-a8718f76-vffrc 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single node cluster, but this happens in a multi node cluster too.

**Describe the bug:**

I'm not sure if this is a bug or the intended behavior. 

The configmap `rke2-etcd-snapshots` never remove up to X errors from it.  Seems that it has a default behavior of keeping: 
x - Local Snapshots.
x - Succesfull s3 snapshots.
x - Failed snapshots. 

**Steps To Reproduce:**

* install RKE2 (can be done through rancher too)
* Configure ETCD snapshots  to be backed-up on a S3 bucket with X retention. 
* Force some errors. (can be a wrong URL) 
* Fix the error and wait.
* After this up to X errors will always exists on the configMap 

**Expected behavior:**

I'm not sure if this is a bug or the expected behavior. 

After fixing a bug and having successes wile backingup the snapshots on S3 I expected the failed backups to be removed from the config-map.

**Actual behavior:**
they stay there forever. 

**Additional context / logs:**
```
Name:         rke2-etcd-snapshots
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
local-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692180004:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692180004","location":"file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692180004","metadata":"METADATA-","nodeName":"felipe-test-do-dont-delete-pool1-a8718f76-vffrc","createdAt":"2023-08-16T10:00:04Z","size":10375200,"status":"successful","compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692106202:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692106202","metadata":"=","message":"METADATA","nodeName":"s3","createdAt":"2023-08-15T13:30:02Z","status":"failed","s3Config":{"endpoint":"s3.us-east-2.amazonaws.comm","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692108003:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692108003","metadata":"METAD","message":"SGVhZCAiaHR0cHM6Ly9zMy51cy1lYXN0LTIuYW1hem9uYXdzLmNvbW0vZmVsaXBlLXRlc3QtcmVzdG9yZS1yYW5jaGVyLyI6IGRpYWwgdGNwOiBsb29rdXAgczMudXMtZWFzdC0yLmFtYXpvbmF3cy5jb21tIG9uIDEyNy4wLjAuNTM6NTM6IG5vIHN1Y2ggaG9zdA==","nodeName":"s3","createdAt":"2023-08-15T14:00:03Z","status":"failed","s3Config":{"endpoint":"s3.us-east-2.amazonaws.comm","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692180004:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692180004","metadata":"METAD","nodeName":"s3","size":10375200,"status":"successful","s3Config":{"endpoint":"s3.us-east-2.amazonaws.com","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692187203:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692187203","metadata":"METAD","nodeName":"s3","size":10375200,"status":"successful","s3Config":{"endpoint":"s3.us-east-2.amazonaws.com","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}
local-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692183603:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692183603","location":"file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692183603","metadata":"METAD","nodeName":"felipe-test-do-dont-delete-pool1-a8718f76-vffrc","createdAt":"2023-08-16T11:00:03Z","size":10375200,"status":"successful","compressed":false}
local-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692187203:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692187203","location":"file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692187203","metadata":"METAD","nodeName":"felipe-test-do-dont-delete-pool1-a8718f76-vffrc","createdAt":"2023-08-16T12:00:03Z","size":10375200,"status":"successful","compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692107101:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692107101","metadata":"METAD=","message":"SGVhZCAiaHR0cHM6Ly9zMy51cy1lYXN0LTIuYW1hem9uYXdzLmNvbW0vZmVsaXBlLXRlc3QtcmVzdG9yZS1yYW5jaGVyLyI6IGRpYWwgdGNwOiBsb29rdXAgczMudXMtZWFzdC0yLmFtYXpvbmF3cy5jb21tIG9uIDEyNy4wLjAuNTM6NTM6IG5vIHN1Y2ggaG9zdA==","nodeName":"s3","createdAt":"2023-08-15T13:45:01Z","status":"failed","s3Config":{"endpoint":"s3.us-east-2.amazonaws.comm","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}
s3-etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692183603:
----
{"name":"etcd-snapshot-felipe-test-do-dont-delete-pool1-a8718f76-vffrc-1692183603","metadata":"METAD","nodeName":"s3","size":10375200,"status":"successful","s3Config":{"endpoint":"s3.us-east-2.amazonaws.com","bucket":"felipe-test-restore-rancher","region":"us-east-2","folder":"rainbow-cluster"},"compressed":false}

BinaryData


```

**Comment by brandond** [comment]
Yes, it records that the snapshots failed so that the failure information can be populated up into other tools that want to know whether or not snapshots are working.

**Comment by vwbusguy** [comment]
Here's how I figured out how to clear them if you want them gone (at your own risk).

Against the Rancher cluster, run `kubectl get ETCDSnapshot -A -ojson | jq -r '.items[] | select(.snapshotFile.status // "" | test("failed")).snapshotFile.name'` .  

Take this list and use it to clear keys from the rke2-etcd-snapshots or k3s-etcd-snapshots configmap in the kube-system namespace in the cluster where the snapshots failed.

Then, once you've removed all the snapshotFile key references from the configMap on the downstream cluster, go back to the Rancher local cluster and you can now delete the failed snapshot objects with: `kubectl delete -n fleet-default ETCDSnapshot $(kubectl get ETCDSnapshot -A -ojson | jq -r '.items[] | select(.snapshotFile.status // "" | test("failed")).metadata.name')` .  Alternatively, these can be deleted manually with `kubectl delete -n fleet-default ETCDSnapshot` by copying the metadata.name from the Snapshot in the web UI.

If you attempt to delete these from the local rancher cluster without deleting them from the configMap first, they'll get instantly recreated.
