### ISSUE TITLE
Agents cannot join after upgrade: Node password rejected

### ISSUE THREAD

**Issue by uchalasani** [rancher/rke2#4659]
I upgraded RKE2 from v1.23.9 to v1.25.9 after taking a back up.
After upgrade of the 3 Server nodes, I deleted Agent node secrets, and Agent nodes from the cluster.
Then removed old RKE2 from the Agent nodes, and re-installed new RKE2 v1.25.9 on Agent nodes.
When I restarted Agents using ```sudo systemctl start rke2-agent``` I am seeing the following `journalctl` logs.
Linux <rancher-node> 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
ug 17 09:17:40 <Rancher-agent-node> rke2[1386]: time="2023-08-17T09:17:40-04:00" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"
```

**Comment by uchalasani** [comment]
Looks like this is related to [https://github.com/rancher/rke2/issues/616](url)

**Comment by brandond** [comment]
Can you show confirmation with `kubectl get` that the nodes and node secrets do not exist any longer, and that you don't have any duplicate hostnames in the cluster? Do you see any error or warning messages on the server that you're joining the agents to? I'm not aware of any currently unresolved issues that would cause this message to occur.
