### ISSUE TITLE
Cannot start rke2-service

### ISSUE THREAD

**Issue by astridmonthe** [rancher/rke2#4666]
Hello,

When running systemctl start rke2-server. I get the following issue on RHEL7.

 level=fatal msg="failed to get runtime image index.docker.io/rancher/rke2-runtime:v1.25.12-rke2r1: all endpoints failed: Get \"https://index.docker.io/v2/\": read tcp 10.28.129.84:55774->44.205.64.79:443: read: connection reset by peer"

Can anyone please help?

Those are the commands I used to install rke2-server:

curl -sfL https://get.rke2.io -o install-rke.sh

INSTALL_RKE2_CHANNEL=latest

INSTALL_RKE2_CHANNEL_URL=https://github.com/rancher/rke2/releases 

chmod +x ./install-rke.sh 
./install-rke.sh

**Comment by manuelbuil** [comment]
it seems like a problem of your node when trying to connect to docker, or?

**Comment by brandond** [comment]
> `Get "[https://index.docker.io/v2/\](https://index.docker.io/v2/%5C)": read tcp 10.28.129.84:55774->44.205.64.79:443: read: connection reset by peer`

As @manuelbuil noted, check this node's connection to Docker Hub. Did you need to open up firewall rules, or configure a proxy?
