### ISSUE TITLE
about rke2 etcd backup and restore

### ISSUE THREAD

**Issue by withlin** [rancher/rke2#4679]
**Environmental Info:**
RKE2 Version: `v.126.4+rke2r1`

Node(s) CPU architecture, OS, and Version: `Linux ip xx.xx.xx.xxx  4.18.0-488.15.1.el8_8.x86_64`

Cluster Configuration: `1 server 1 agent`

**Describe the bug:**

### command
```
systemctl stop rke2-server

rke2 server\
   --cluster-reset \
   --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
```
### rke2 server Log
```
WARN[0082] Failed to get apisever address from etcd from etcd: context dedline. exceeded
INFO[0083] Removing kube-proxy static pod manifest: kube-porxy has been disbaled
INFO[0083]  Wating to retrieve kube-proxy configuration; server is not ready: http://127.0.0.1:6443/v1-rke2/readyz 500 Internal Server Error
INFO[0087] Failed to test data store connection: context dedline exceeded
INFO[0087] Tunnel server egress proxy wating for runtime  core to become availble...........
```
### /var/logs/pod/etcd
```
{"level":"info","ts":"2023-05-17T08:07:29.022Z","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["etcd","--config-file=/var/lib/rancher/rke2/server/db/etcd/config"]}
{"level":"warn","ts":"2023-05-17T08:07:29.022Z","caller":"etcdmain/etcd.go:75","msg":"failed to verify flags","error":"open /var/lib/rancher/rke2/server/db/etcd/config: permission denied"}
```
and then excute: `systemctl start  rke2-server`, but failed.

if i excute: command+ C [macOs type], and then `rke2 server` logs follow:
```
INFO[0157] ETCD server is now running
INFO[0157] rke2 is up and running
INFO[0157] Saving cluster boottrap data to datastore
INFO[0157] Watching for delete of IP xxxxx. Node Object
ERROR[0157] spc: failed to wait for node deletion: timed out waiting for the condition
FATA[0157] serviceAccount: namespace kube-system client rate limiter Wait returned an error: context canceled
```
and i was excuting: `systemctl start rke2-server`, which it can start successfuly.

**Comment by withlin** [comment]
@brandond cc

**Comment by brandond** [comment]
> `INFO[0083] Removing kube-proxy static pod manifest: kube-porxy has been disbaled`

Whats's going on with these log messages, are these straight logs from RKE2 or are you typing these errors from memory?

> `open /var/lib/rancher/rke2/server/db/etcd/config: permission denied`

Is this on a hardened node? Are you using selinux, and if so, do you have the correct packages installed?

**Comment by elaijuh** [comment]
it's on a hardended node with cis-profile: 1.23 and selinux enabled.

we have container_selinux and rke2_selinux installed

```
# sesearch --allow --source rke2_service_db_t --target container_var_lib_t --class file
allow container_domain container_var_lib_t:file entrypoint;
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow rke2_service_db_t container_var_lib_t:file { append create getattr ioctl link lock map open read rename setattr unlink write };

# ls -Z /var/lib/rancher/rke2/server/db/etcd/config
unconfined_u:object_r:container_var_lib_t:s0 /var/lib/rancher/rke2/server/db/etcd/config
```
then we run these command with sudo
```
systemctl stop rke2-server
rke2 server --selinux=true --cluster-reset  --cluster-reset-restore-path=/var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-x-x-x-x.xxx-xxx
```
then see this error
```
2023-08-25T06:46:34.867303876Z stderr F {"level":"warn","ts":"2023-08-25T06:46:34.867Z","caller":"etcdmain/etcd.go:75","msg":"failed to verify flags","error":"open /var/lib/rancher/rke2/server/db/etcd/config: permission denied"}
```

**Comment by brandond** [comment]
When you say "hardened node", what exactly do you mean? his sounds a lot like the directory permissions / umask issue from https://github.com/rancher/rke2/issues/4313. Have you perhaps changed the umask in your shell, and the etcd db directory permissions are being excessively locked down when you run the cluster reset? T

**Comment by withlin** [comment]
@brandond Thanks a lot, it works fine.
