### ISSUE TITLE
Error when executing containerd in Windows is not logged

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#4693]
**Environmental Info:**
RKE2 Version: Any

Node(s) CPU architecture, OS, and Version: 

Windows

Cluster Configuration:

Any

**Describe the bug:**

If containerd fails to start for whatever reason, the log is not reported

**Steps To Reproduce:**

- Installed RKE2: 
Deploy rke2 with a wrong PATH so that it can't find containerd. rke2 service keeps restarting and it is impossible to know why. By inspecting the logs, you can guess that it is more or less when containerd must start:
```
8/28/2023 10:20:52 AM Starting rke2 agent v1.27.4+dev.3ab96dd0-dirty (3ab96dd0016a637f48672b011822de5a35c96045.dirty) 
8/28/2023 10:20:52 AM Stackdump - waiting signal at Global\stackdump-6104
8/28/2023 10:20:21 AM Running containerd -c C:\var\lib\rancher\rke2\agent\etc\containerd\config.toml
8/28/2023 10:20:21 AM Logging containerd to C:\var\lib\rancher\rke2\agent\containerd\containerd.log
```

**Expected behavior:**

An error is printed in the logs to understand why things are failing

**Actual behavior:**

No error is printed. You get desperate because you have no idea what is going on

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
Unable to replicate the issue and in turn validate the change. As the change is minimal, so we decided to run basic validations on rke2 with Windows agent using commits.
- Performed basic validation using commit 302b2915ff5013cb3f566c455cfdefe54a0e8882
- Validated the cluster is up and running with
```
rke2 -v
rke2 version v1.28.2+dev.302b2915 (302b2915ff5013cb3f566c455cfdefe54a0e8882)
go version go1.20.8 X:boringcrypto
```
