### ISSUE TITLE
During System cluster reset, node is stuck on sudo systemctl start rke2-server for a 45 min

### ISSUE THREAD

**Issue by est-suse** [rancher/rke2#4707]
**Environmental Info:**
RKE2 Version: 

```
Versions:  v1.24.17-rc2+rke2r1, v1.25.13-rc2+rke2r1, v1.26.8-rc2+rke2r1, v1.27.5-rc2+rke2r1

```
Node(s) CPU architecture, OS, and Version: 

```
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

Cluster Configuration:

```
3 servers - 1 agent
```

**Describe the bug:**

```
during the performing of a “Cluster reset” test, the second server is stuck on  during "sudo systemctl start rke2-server" for around 30-45 min
```

**Steps To Reproduce:**

```

1. Create an HA cluster, make sure it's up and ready
2. Deploy some workloads.
3. Stop two server nodes by using "sudo rke2-killall.sh"
4. Make sure the cluster is not accessible now
5. Shut down the rke2 server on that remaining node by running "sudo systemctl stop rke2-server"
6. Now run "sudo rke2 server --cluster-reset"
7. After the command completes, restart the rke2 server process: "sudo systemctl start rke2-server"
8. Check to get it working again and after a while the other nodes will not be ready. Usually have to wait a few minutes for this to occur.
9. Remove the db directories from other servers by running "sudo rm -rf /var/lib/rancher/rke2/server/db"
10. Restart the rke2-server process on the other servers by running "sudo systemctl start rke2-server"

```

The cluster is stuck on sudo systemctl start rke2-server

![image](https://github.com/rancher/rke2/assets/106194120/6a479332-c161-4816-8448-4aeff136fec1)

The server is not a learner: 

```
+------------------+---------+-----------------------------------------------------+---------------------------+---------------------------+------------+
|        ID        | STATUS  |                        NAME                         |        PEER ADDRS         |       CLIENT ADDRS        | IS LEARNER |
+------------------+---------+-----------------------------------------------------+---------------------------+---------------------------+------------+
| 9d4ae55fa38d545d | started |   ip-172-31-2-6.us-east-2.compute.internal-02d5d92c |   https://172.31.2.6:2380 |   https://172.31.2.6:2379 |      false |
| ce003f7dd9d0f843 | started | ip-172-31-11-14.us-east-2.compute.internal-cdcf9086 | https://172.31.11.14:2380 | https://172.31.11.14:2379 |      false |
```

**Expected behavior:**

```
Should take less time to finish the sudo systemctl start rke2-server, checking the previous version is taking no more than 5
to complete the start
```
**The following logs are present**

```
Aug 29 02:09:11 ip-172-31-8-28 rke2[1940]: {"level":"info","ts":"2023-08-29T02:09:11.567Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
Aug 29 02:09:11 ip-172-31-8-28 rke2[1940]: {"level":"warn","ts":"2023-08-29T02:09:11.568Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a8c8c0/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Aug 29 02:09:20 ip-172-31-8-28 rke2[1940]: {"level":"warn","ts":"2023-08-29T02:09:20.305Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a8c1c0/172.31.2.251:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: too many learner members in cluster"}

Aug 29 16:35:11 ip-172-31-8-28 rke2[5634]: {"level":"info","ts":"2023-08-29T16:35:11.442Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
```

**Comment by brandond** [comment]
Please attach the complete logs (rke2-server journald log, and contents of /var/log/pods) from all three server nodes.

**Comment by est-suse** [comment]
[logs_start.txt](https://github.com/rancher/rke2/files/12478361/logs_start.txt)

**Comment by est-suse** [comment]
[s1_logs_var.tgz](https://github.com/rancher/rke2/files/12478706/s1_logs_var.tgz)
[s2_logs_var.tgz](https://github.com/rancher/rke2/files/12478707/s2_logs_var.tgz)
[s3_logs_var.tgz](https://github.com/rancher/rke2/files/12478708/s3_logs_var.tgz)
[serv2.txt](https://github.com/rancher/rke2/files/12478709/serv2.txt)
[server1.txt](https://github.com/rancher/rke2/files/12478710/server1.txt)
[server3.txt](https://github.com/rancher/rke2/files/12478711/server3.txt)

**Comment by brandond** [comment]
This seems to be fallout from https://github.com/rancher/rke2/pull/4508 - depending on the exact sequence of events, a couple things can happen:
* On the server that is reset, etcd is still running following the cluster-reset, and is restarted by static pod sync to remove the force-new-cluster option from the config. This interrupts the just-started apiserver, and various rke2 embedded controller operations (such as registering CRDs) fail after a few seconds. The main RKE2 process fails and is restarted.
  * We could probably fix this by running static pod cleanup again at the end of the cluster-reset process, so that etcd doesn't have to be restarted and reconfigured midway through the next start?
* On a server that is starting to rejoin following a cluster-reset, the apiserver manifest isn't rewritten until after etcd starts and joins the cluster. The kubelet will start the apiserver using the old manifest, sync once, and then static pod sync terminates it so that it can be restarted with the new config (intended to ensure that the apiserver doesn't have caches from before the cluster was reset). Unfortunately the kubelet never restarts it because it is now stuck trying to sync mirror pods to the now-unavailable apiserver. Static pod sync times out after many minutes. The main RKE2 process fails and is restarted.
  * We could probably fix this by unconditionally removing the apiserver static pod manifest during rke2 startup, so that the kubelet doesn't start it before it's been written with the current config.

**Comment by est-suse** [comment]
For Visibility: 

I am noticing the fix for the issue [rke2/issues/4707](https://github.com/rancher/rke2/issues/4707) after execute the  ‘sudo rke2-killall.sh’ on both secondary servers and execute the cluster reset and ‘start rke2-server’ on the main server, the status of both secondary servers remain as ‘Ready’ even if when they are not. Despite of this If I complete the remove of the DB and start both of the server, the cluster will come up correctly it
After  running the commands one more  (cluster reset and  killall), the servers will be ‘Not Ready’, this is happening on Hardened Cluster, for Non-Hardened I am not facing this issue

**Comment by brandond** [comment]
I'm not quite understanding the sequence here.

You're saying that on a hardened cluster, if you run through the complex cluster-reset process twice, some of the nodes will not come up the second time?

Please pull the rke2 and pod logs from all the nodes in the affected cluster.

**Comment by est-suse** [comment]
Sorry for the confusion, for a Hardened Cluster, following these steps:

```
1. Create an HA cluster, make sure it's up and ready
2. Deploy some workloads.
3. Stop two server nodes by using "sudo rke2-killall.sh"
4. Make sure the cluster is not accessible now
5. Shut down the rke2 server on that remaining node by running "sudo systemctl stop rke2-server"
6. Now run "sudo rke2 server --cluster-reset"
7. After the command completes, restart the rke2 server process: "sudo systemctl start rke2-server"
8. Check to get it working again and after a while the other nodes will not be ready. Usually have to wait a few minutes for this to occur.
9. Remove the db directories from other servers by running "sudo rm -rf /var/lib/rancher/rke2/server/db"
10. Restart the rke2-server process on the other servers by running "sudo systemctl start rke2-server"
``` 

For the step 7, I am expecyting to see the cluster 2 and 3 as a 'Not Ready' but they are 'Ready'  but I cannot access any of them (Server 2 and Server 3).

from main server after Step # 7:
```
NAME                                          STATUS   ROLES                       AGE     VERSION
ip-172-31-10-121.us-east-2.compute.internal   Ready    control-plane,etcd,master   5h32m   v1.26.8+rke2r1
ip-172-31-10-136.us-east-2.compute.internal   Ready    control-plane,etcd,master   5h35m   v1.26.8+rke2r1
ip-172-31-12-162.us-east-2.compute.internal   Ready    <none>                      5h29m   v1.26.8+rke2r1
ip-172-31-4-115.us-east-2.compute.internal    Ready    control-plane,etcd,master   5h32m   v1.26.8+rke2r1
```

from etcdctl 
```
 
ec2-user@ip-172-31-10-136:~> sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list -w table
+------------------+---------+------------------------------------------------------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |                         NAME                         |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+------------------------------------------------------+----------------------------+----------------------------+------------+
| 532b0ca7c5bcd59e | started | ip-172-31-10-136.us-east-2.compute.internal-f8d35e0f | https://172.31.10.136:2380 | https://172.31.10.136:2379 |      false |
+------------------+---------+------------------------------------------------------+----------------------------+----------------------------+------------+
```
```

**Comment by est-suse** [comment]
[s1.txt](https://github.com/rancher/rke2/files/12518507/s1.txt)
[s2.txt](https://github.com/rancher/rke2/files/12518508/s2.txt)
[s3.txt](https://github.com/rancher/rke2/files/12518510/s3.txt)

**Comment by brandond** [comment]
> For the step 7, I am expecyting to see the cluster 2 and 3 as a 'Not Ready' but they are 'Ready' but I cannot access any of them (Server 2 and Server 3).

How long are you waiting? The nodes should be marked as NotReady by the controller-manager on Server 1 after a couple minutes. If this isn't happening, it suggests that the controller-manager isn't working correctly for some reason. The logs do show that the kube-controller-manager is exiting because the apiserver isn't up yet; it should be restarted automatically after a minute or two.

If the kube-controller-manager pod isn't restarted after a few minutes, and the nodes don't ever go NotReady, please grab the kubelet.log off Server 1.

**Comment by est-suse** [comment]
Hi Brad, 

After 26 min, they are shown as 'Ready'.

```
NAME                                         STATUS   ROLES                       AGE   VERSION
ip-172-31-15-14.us-east-2.compute.internal   Ready    control-plane,etcd,master   24m   v1.26.8+rke2r1
ip-172-31-2-221.us-east-2.compute.internal   Ready    <none>                      23m   v1.26.8+rke2r1
ip-172-31-4-0.us-east-2.compute.internal     Ready    control-plane,etcd,master   27m   v1.26.8+rke2r1
ip-172-31-4-179.us-east-2.compute.internal   Ready    control-plane,etcd,master   23m   v1.26.8+rke2r1

```



On 1.27 after 1 min, they are changing to 'Not Ready':

```
ec2-user@ip-172-31-10-13:~> kubectl get nodes -w
NAME                                          STATUS   ROLES                       AGE   VERSION
ip-172-31-10-13.us-east-2.compute.internal    Ready    control-plane,etcd,master   29m   v1.27.5+rke2r1
ip-172-31-14-214.us-east-2.compute.internal   Ready    control-plane,etcd,master   25m   v1.27.5+rke2r1
ip-172-31-3-21.us-east-2.compute.internal     Ready    <none>                      25m   v1.27.5+rke2r1
ip-172-31-8-73.us-east-2.compute.internal     Ready    control-plane,etcd,master   26m   v1.27.5+rke2r1
ip-172-31-3-21.us-east-2.compute.internal     Ready    <none>                      25m   v1.27.5+rke2r1
^Cec2-user@ip-172-31-10-13:~> kubectl get nodes -w
NAME                                          STATUS   ROLES                       AGE   VERSION
ip-172-31-10-13.us-east-2.compute.internal    Ready    control-plane,etcd,master   30m   v1.27.5+rke2r1
ip-172-31-14-214.us-east-2.compute.internal   Ready    control-plane,etcd,master   26m   v1.27.5+rke2r1
ip-172-31-3-21.us-east-2.compute.internal     Ready    <none>                      25m   v1.27.5+rke2r1
ip-172-31-8-73.us-east-2.compute.internal     Ready    control-plane,etcd,master   26m   v1.27.5+rke2r1
ip-172-31-8-73.us-east-2.compute.internal     NotReady   control-plane,etcd,master   27m   v1.27.5+rke2r1
ip-172-31-14-214.us-east-2.compute.internal   NotReady   control-plane,etcd,master   26m   v1.27.5+rke2r1
ip-172-31-14-214.us-east-2.compute.internal   NotReady   control-plane,etcd,master   26m   v1.27.5+rke2r1
ip-172-31-8-73.us-east-2.compute.internal     NotReady   control-plane,etcd,master   27m   v1.27.5+rke2r1
```

**Comment by est-suse** [comment]
[s3_kubelet.log](https://github.com/rancher/rke2/files/12528401/s3_kubelet.log)
[s2_kubelet.log](https://github.com/rancher/rke2/files/12528402/s2_kubelet.log)
[s1_kubelet.log](https://github.com/rancher/rke2/files/12528403/s1_kubelet.log)

```
crictl ps -a
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
WARN[0000] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
E0905 21:19:13.747095   18796 remote_runtime.go:390] "ListContainers with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory\"" filter="&ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},}"
FATA[0000] listing containers: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory"
ec2-user@ip-172-31-10-136:~>
```

**Comment by brandond** [comment]
You need to be root, and export the correct environment variable in order to use crictl. See the examples at https://docs.rke2.io/reference/cli_tools?_highlight=crictl#containerd

**Comment by est-suse** [comment]
After the retested on a node with 4 cores instead of 2, the issue is not longer happening. The steps are performed correctly.
