### ISSUE TITLE
RKE2 didn't load non-rke2 image tarball

### ISSUE THREAD

**Issue by zhenlohuang** [rancher/rke2#4710]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.27.4+rke2r1 (3aaa57a9608206d95eeb9ce3f79c0ec2ea912b20)
go version go1.20.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux yjy-yjy-dev-testing-dev-e6oy6y 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
"1 servers"

**Describe the bug:**
I put a non-rke2 image tarball(e.g. registry.tar) to /var/lib/rancher/rke2/agent/images/, however the image tarball was not loaded.  I am not sure if it is expected or not. In my option, the image tarball should be load  because the user could add other helm charts to /var/lib/rancher/rke2/server/manifests.

**Steps To Reproduce:**
- Installed RKE2:  following quick started and installed a single node cluster.
- put image tarball: copying image tarball to /var/lib/rancher/rke2/agent/images/

**Expected behavior:**
the image tarball was loaded by rke2.

**Actual behavior:**
RKE2 didn't load the image tarball

**Additional context / logs:**
No.

**Comment by brandond** [comment]
You neglected to mention how you created the image tarball. Are you sure it's in a format that can be imported? It should be an archive as create by `docker save`, with optional compression.
