### ISSUE TITLE
Unable to complete quickstart

### ISSUE THREAD

**Issue by cortopy** [rancher/rke2#475]
I was just evaluating rke2 using the quickstart. The way in which the script sets up the server is very impressive and quick.

I've issued all the commands in the readme for the server:

```
curl -sfL https://get.rke2.io | sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
# Wait a bit
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
kubectl get nodes
```

However, I'm unable to run the agent too following https://docs.rke2.io/install/quickstart/#agent-worker-node-installation. These are the logs:

```
Oct 07 23:36:12 rke systemd[1]: Starting Rancher Kubernetes Engine v2 (agent)...
Oct 07 23:36:12 rke systemd[1]: Started Rancher Kubernetes Engine v2 (agent).
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=warning msg="not running in CIS 1.5 mode"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Runtime image \"index.docker.io/rancher/rke2-runtime:v1.18.9-rke2r1\" bin dir already exists at \"/var/lib/rancher/rke2/data/v1.18.9-rke2r1-c6ad0280a551/bin\"; skipping extract"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Starting rke2 agent v1.18.9+rke2r1 (67ded31a6924dac8d0c497b7b1c180a28d8a31af)"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Module overlay was already loaded"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Module nf_conntrack was already loaded"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Module br_netfilter was already loaded"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=info msg="Running load balancer 127.0.0.1:44201 -> [1.2.3.4:9345]"
Oct 07 23:36:13 rke rke2[8337]: time="2020-10-07T23:36:13+02:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:44201/cacerts: read tcp 127.0.0.1:37272->127.0.0.1:44201: read: connection reset by peer"
Oct 07 23:36:15 rke rke2[8337]: time="2020-10-07T23:36:15+02:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:44201/cacerts: read tcp 127.0.0.1:37284->127.0.0.1:44201: read: connection reset by peer"
```

I've swapped the real IP for 1.2.3.4 in that snippet

It seems as if the script sets up a load balancer which in turn can't resolve the CA of the certificate used by the server

the config for the agent is:

```
server: https://1.2.3.4:9345
token: <token>

```

**Comment by cjellick** [comment]
This is an agent node? Does the server come up properly and is it accessible on port 9345 fom the agent node?

**Comment by cortopy** [comment]
I don't know if this is possible, but I'm evaluating RKE2 using just one node (etcd,controlplane and worker all in one). If I understood correctly, the server is etcd/controlplane and the agent is worker, so I'm trying to run both in the same machine.

Port is available to the agent daemon (tried with external and localhost IP)

**Comment by ron1** [comment]
I believe the intent is to run server or agent on a host, not both. I think the rpm installer enforces this requirement.

**Comment by briandowns** [comment]
@cortopy The server will run the worker process as well.

**Comment by cortopy** [comment]
ah that makes sense then. Thank you!
