### ISSUE TITLE
Can't install RKE2 on ARM64

### ISSUE THREAD

**Issue by tardich** [rancher/rke2#4754]
**Environmental Info:**
RKE2 Version: v1.26.8+rke2r1 but tested with other versions as well

Node(s) CPU architecture, OS, and Version: 

Linux rke2-pi1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:

**Describe the bug:**

Try to install RKE2 on Raspberry Pi4 with 

curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.8+rke2r1 sh -

Returns:

[INFO]  using v1.26.8+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.26.8+rke2r1/sha256sum-arm64.txt
curl: (22) The requested URL returned error: 404

**Steps To Reproduce:**
Using steps above

**Expected behavior:**

SHould be able to get checksum files and move further in the installation process

**Actual behavior:**
Does not get checksum so not installing

**Additional context / logs:**

**Comment by brandond** [comment]
arm64 support is experimental, and only available for 1.27+.

**Comment by tardich** [comment]
Ahhhh!   Good to know. Maybe this should be clearly documented somewhere (or I didn't see it, which leads to the same issue, not visible enough).

It now works!  Thanks a lot fot the tip!
