### ISSUE TITLE
multus not starting on rke2-arm64

### ISSUE THREAD

**Issue by tardich** [rancher/rke2#4764]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.27.5+rke2r1 (1de995339f133cc0ec5003854e8ff1f32ca4a9c0)
go version go1.20.7 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux rke2-pi1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:
1 master node so far

**Describe the bug:**
After deploying rke2 (server) on my raspberry pi 4, multus ds did not create any pods. I was able to find out that the DaemonSet is specifying kubernetes.io/arch=amd64 as node selector

**Steps To Reproduce:**
1) Include, in /etc/rancher/rke2/rke2.yaml, multus as a required cni, as:

```
cni:
  - multus,canal
```

Then proceed with normal rke2 installation on the node

**Expected behavior:**
multus pod should be starting (from helm-install-rke2-multus job) in kube-system

**Actual behavior:**
multus pod does not start due to node selector misconfiguration

**Additional context / logs:**
My config.yaml file:

```
tls-san:
  - kubernetes.04.int.servinfo.stba
  - kubernetes.default.svc.cluster.04.int.servinfo.stba
cluster-cidr:
  - 10.46.0.0/16
service-cidr:
  - 10.47.0.0/16
cluster-domain:
  - cluster.04.int.servinfo.stba
disable:
  - rke2-ingress-nginx
cni:
  - multus,canal
kubelet-arg:
  - --cpu-cfs-quota=false
```

**Comment by brandond** [comment]
Arm64 support is experimental, and not all components support it yet.

cc @manuelbuil @briandowns

**Comment by brandond** [comment]
Will defer to @briandowns on whether to leave this open, or just track it as part of ongoing arm64 work.

**Comment by manuelbuil** [comment]
We are already building multus image with arm64 support, so even if it is experimental, you should be able to try.

You will need to change the multus chart values because amd64 is the default: https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-multus/charts/values.yaml#L81.

To do so, please apply a HelmChartConfig with the new value. Here is an example: https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig

**Comment by manuelbuil** [comment]
@tardich did you have the chance to try the HelmChartConfig?

**Comment by manuelbuil** [comment]
Let's open it again if the issue still exists
