### ISSUE TITLE
Allow Users to Customize Audit Log Related Options 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke2#4767]
RKE1 allows users to configure some audit-log-related options on the `kube-apiserver` ([RKE1 Docs](https://rke.docs.rancher.com/config-options/audit-log))
We would like to see the same functionalities on RKE2. 

Currently RKE2 sets hard-coded values when the `profile` flag is set.

**Comment by brandond** [comment]
RKE2 sets hardcoded values, but arguments set by RKE2 can always be overridden by arbitrary `kube-apiserver-args`. Is there something in particular you're trying to set, and not seeing it take effect? Can you provide an example of setting audit configuration that's not doing what you expect?

**Comment by jiaqiluo** [comment]
@brandond, The approach of setting `kube-apiserver-arg` works. 

The goal of the feature request is to make RKE2 feature-wide parity with RKE1 where some of those flags can be set directly in RKE1's config file under `.spec.service.kube-api.auditlog.configuration.audit-log-xxx`.  The priority is low AFAIK.

**Comment by brandond** [comment]
I don't think we are interested in adding dedicated top-level `rke2 server` or `rke2 agent` CLI flags that are just naively passed through to embedded component configuration; if there's something that needs to be set, it should be done directly via the appropriate component's extra-arg or placed in the appropriate user-provided configuration file in the case of audit config.

**Comment by jiaqiluo** [comment]
OK, it makes sense to me.

**Comment by brandond** [comment]
Feel free to open a RFE in Jira if this needs to be discussed with Product Management.
