### ISSUE TITLE
How to display external IP with "kubectl get nodes -o wide" cmd in rke2.

### ISSUE THREAD

**Issue by DungT9x** [rancher/rke2#4787]
**Environmental Info:**
RKE2 Version: v1.26.4

Node(s) CPU architecture, OS, and Version:  22.04, 4cpu, 8gb

Cluster Configuration: 1 Master and 1 Worker

**Describe the bug:**

Don't display external IP in "kubectl get nodes -o wide" cmd.

**Steps To Reproduce:**

- Installed RKE2: 
- Edit config.yaml

```
server: https://192.168.0.61:9345/
data-dir: /var/lib/rancher/rke2
tls-san:
  - cluster.local
  - 192.168.0.61
  - 14.225.53.251
node-external-ip: IP PUBLIC
node-ip: 192.168.0.61
```
- Restart rke2-server

**Expected behavior:**

Display external IP with "kubectl get nodes -o wide" cmd 

**Actual behavior:**

**Additional context / logs:**

- ps aux | grep kubelet

```
kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log --audit-policy-file=/etc/rancher/rke2/audit-policy.yaml --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --advertise-address=x.x.x.x (IP PUBLIC) --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,rke2 --authorization-mode=Node,RBAC --bind-address=0.0.0.0
```
- Rke2 status
```
Sep 25 09:20:32 master-01 rke2[2587886]: time="2023-09-25T09:20:32+07:00" level=info msg="Connecting to proxy" url="wss://x.x.x.x (IP PUBLIC):9345/v1-rke2/connect"
Sep 25 09:20:32 master-01 rke2[2587886]: time="2023-09-25T09:20:32+07:00" level=error msg="Failed to connect to proxy. Empty dialer response" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 192.168.0.194, 192.168.0.61, ::1, not x.x.x.x (IP PUBLIC)"
Sep 25 09:20:32 master-01 rke2[2587886]: time="2023-09-25T09:20:32+07:00" level=error msg="Remotedialer proxy error" error="x509: certificate is valid for 10.43.0.1, 127.0.0.1, 192.168.0.194, 192.168.0.61, ::1, not x.x.x.x (IP PUBLIC)"
```

**Comment by Martin-Weiss** [comment]
Did you try to add your public ip to tls-san?

**Comment by DungT9x** [comment]
> Did you try to add your public ip to tls-san?

I've been added public ip to tls-san but the same issue.

**Comment by Martin-Weiss** [comment]
And you restarted RKE2 after adding tls-san: to the config.yaml?

**Comment by DungT9x** [comment]
> And you restarted RKE2 after adding tls-san: to the config.yaml?

Yes. I've been deleted and re-install system.

**Comment by brandond** [comment]
Is the external IP actually associated with the node via NAT, or is it hosted on an external load-balancer with a certificate you provisioned manually?

**Comment by DungT9x** [comment]
> Is the external IP actually associated with the node, either bound to an interface or mapped via NAT, or is it hosted on an external load-balancer with a certificate you provisioned manually?

1. Yes, this external IP is associated with my node.

> If you set the address as the external IP, it should be present on the cert, which makes me suspect that the cert is not managed by rke2.

2. I've been re-installed and checked my system. I don't see to any log about cert.

3. I tested 1.26.8 version with same config so the external IP column is displayed to Public IP as expect.

Tks you.

**Comment by brandond** [comment]
> RKE2 Version: v1.26.4

> I tested 1.26.8 version with same config and the external IP column is displayed to Public IP as expect.

Sounds like the issue is resolved then? I'm confused why you opened an issue about something that's already fixed on newer releases.

**Comment by DungT9x** [comment]
> > RKE2 Version: v1.26.4
> 
> > I tested 1.26.8 version with same config and the external IP column is displayed to Public IP as expect.
> 
> Sounds like the issue is resolved then? I'm confused why you opened an issue about something that's already fixed on newer releases.

No, I just want to confirm with you that only the versions in the following [link](https://github.com/rancher/rke2/issues/752) are still normal, the rest do not support external IP, right? Let me plan the version upgrades for all my systems.

**Comment by brandond** [comment]
That is a really old issue - like, 2 and a half years old. We hadn't looked at it in a long time, and just recently validated that it is no longer reproducible We're not sure exactly when it started working, but it should work properly on any recent release.
