### ISSUE TITLE
Build improvements

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#480]
@cnuber has identified a number of build improvements/changes that would ease his integration.

In short, he needs to rebuild all of RKE2 inside a controlled and isolated environment. The biggest restriction (as I understand it) is that any artifact pulled from outside the isolated environment needs to go through a whitelisting procedure (basically, he puts them in a yaml file).

So, things like git cloning kubernetes/kubernetes are bad, but downloading the source tarball of kubernetes is good/easy.

I'm going to have Chris outline his desired changes here. For each one, we should evaluate if 1) it is possible 2) if it has a very big negative impact to our build process.

If the change is possible and it doesnt have a big negative impact, we shoud implement the change so that there is a higher degree of fidelity between our native builds and Chris's.

If we determine that the change isn't possible or it DOES have a large negative impact, we must communicate that clearly to Chris. Preferably in slack (to potentially talk through work arounds) and here (for a more official record of the decision).

**Comment by cjellick** [comment]
@galal-hussein I've assigned you to this effort, but I'd like you to talk through the changes with @dweomer since he did a lot of refactoring to the build.

**Comment by cjellick** [comment]
@davidnuzik tagging you so that you can track this. This falls into our "respond to RFed feedback" bucket of work.

**Comment by davidnuzik** [comment]
@cnuber I believe we are waiting on a list of feature requests for the build process. Could you follow up at your earliest availability?

**Comment by brandond** [comment]
I have handed a script off to the RFed folks: https://gist.github.com/brandond/1ee1838af67d682eff508d624613f79b

This script will grab artifacts from the current release, and `flatten` the airgap images out into a tarball containing just dockerfiles and 'from scratch' root filesystems that will effectively recreate the images from the ground up. These artifacts can be checked into a Docker build pipline, and will give images that should function the same as the originals in an environment where simply `docker load`ing images is disallowed.

The RFed folks will be responsible for running this script to produce the tarball, and importing this tarball into the target environment for consumption by the build pipeline.
