### ISSUE TITLE
Skip check for helm v2 in rke2 charts

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#481]
when rke2 helm charts pods start they start in hostNetwork: true, and it causes a problem when they run in parallel because they all want to start tiller on the same port, we should skip helm v2 in rke2 if the bootstrap flag is passed to the chart

**Comment by davidnuzik** [comment]
@galal-hussein is this still in review? Where is PR? We already released v1.18.12+rke2r1 so this was already in that release but not tested?

**Comment by davidnuzik** [comment]
I'm going to assume this just slipped. It wasn't slated with a milestone. @rancher-max can you give this a test in v1.18.12+rke2r1 release?

**Comment by rancher-max** [comment]
helm controller is not updated yet in rke2 or k3s repos, so this actually isn't present in v1.18.12+rke2r1. @davidnuzik I'm assigning this to you for now as it's not ready for test quite yet and just waiting on the repo updates from the shift to k3s-io github org.

**Comment by rancher-max** [comment]
As this is now present in v1.19.5+rke2, I am able to validate the changes are working as expected.

- Passing `helmVersion: v2` and `bootstrap: true` together in a manifest file produces an expected error in the helm-install pod (and therefore also a CrashLoopBackoff series of retries):
`Error: bootstrap flag can't be set with helm version 2 charts, please remove the bootstrap flag and update the chart`
- Confirmed that removing either the bootstrap flag or the helmVersion flag allows the chart to install correctly.
- Having neither value present allows install
- Able to install multiple v2 charts using helm v2 without bootstrap flag
