### ISSUE TITLE
Documentation inconsistency?

### ISSUE THREAD

**Issue by aceeric** [rancher/rke2#4824]
RKE2 Version:  current documentation online

Please see: 
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
... which says:
>  UDP | 8472 | Canal/Flannel VXLAN overlay networking

and: https://docs.rke2.io/install/requirements
... which says:
>  UDP | 4789 | All RKE2 nodes | All RKE2 nodes | Calico CNI with VXLAN

Note - after installing RKE2 _v1.28.2+rke2r1_ then `netstat -tulpn` shows:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
```

**Comment by brandond** [comment]
cc @manuelbuil

**Comment by manuelbuil** [comment]
It's the same port 8472 in both docs. @aceeric you are checking the Calico CNI with VXLAN row, you should check Canal CNI with VXLAN row
