### ISSUE TITLE
cilium 1.14.0 Gateway API Service Annotation race condition

### ISSUE THREAD

**Issue by zs-ko** [rancher/rke2#4832]
**Environmental Info:**
RKE2 Version: 1.27.6

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

Cilium has resolved a race condition for services created by the Gateway api controller. 
https://github.com/cilium/cilium/pull/27251

**Steps To Reproduce:**

- Installed RKE2
- Add cloud provider controller for loadblanacer provision that modifies annotations on the service
- add cilium with gateway api enabled
- observe race conditions by both controller
- tested on hetzner cloud

**Expected behavior:**

no race conditions

**Actual behavior:**

**Additional context / logs:**

upgrade cilium to 1.14.2 to resolve controller issue

**Comment by brandond** [comment]
> upgrade cilium to 1.14.2 to resolve controller issue

This is already being tracked. See https://github.com/rancher/rke2-charts/pull/374 - I believe @dereknola has a PR in progress to pull that update in here.

**Comment by dereknola** [comment]
Yeah I should a PR in by EOD. So look for that in the October releases.
