### ISSUE TITLE
Bump to latest v1.19.x

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#485]
We will want to bump to latest v1.19.x and release on or around 12/9 (subject to change).
We originally considered a +rke2r2 release of v1.19.4; however, after speaking with the team it sounds like we can update kubernetes fairly quickly at least for the RKE2 project. As such, we'll pull in v1.19.5 slated for 12/9.

**Comment by dweomer** [comment]
Due to poor branching with my PRs, this change has been satisfied by #599

**Comment by davidnuzik** [comment]
Closing. As for testing, will track via https://github.com/rancher/rke2/issues/610 main issue.
