### ISSUE TITLE
Add cilium as a CNI plugin option

### ISSUE THREAD

**Issue by ereslibre** [rancher/rke2#490]
Allow users to choose the CNI plugin when setting up the rke2 server.

Since rke2 is not following k3s' approach of using the `--flannel-{backend,iface,conf}` and `--no-flannel` CLI arguments an open question is how to expose the CNI plugin selection to users.

rke2 will apply all charts present in the rke2-runtime container image. As we see it, there are three main alternatives to allow choosing the CNI plugin:

* Follow the current procedure of applying everything listed on the rke2-runtime container image under `/charts`, and add some selector for the charts to be applied.
  * Despite being very flexible, this approach is error prone, since it delegates a consistent selection completely to the user, so its UX is not optimal.
  * Examples: `rke2 server --chart-selector=*,-canal`, `rke2 server --chart-selector=coredns,ingress-nginx,kube-proxy,metrics-server,cilium`.
  * Examples of inconsistent selections: `rke2 server --chart-selector=canal,cilium`.

* Add a specific configuration to be able to choose a CNI plugin.
  * There is a number of config options in k3s that have an impact on the CNI plugin selection already: `--no-flannel` (deprecated), and `--flannel-backend=none` that does not install any CNI plugin.
  * If it's fine to deviate from k3s on the approach, a flag can be added exclusively to rke2, or added to k3s and inherited if that's preferred.
  * Example: `rke2 server --cni-plugin=cilium`.

* Depend solely on the runtime container image: produce different runtime container images with different charts under `/charts` -- depending on which image you choose, you will get e.g. canal or cilium set up.
  * This has the drawback of combinatorial explosion if more options are added in the future along the CNI plugin.
  * Can be achieved with subdirectories under `/charts` on the same image as well, acting like presets -- allowing the user to choose a preset from the CLI. Despite on the same container image, there is still combinatorial explosion at the default preset level.

The second option has a good balance between valid options, easiness of selection and maintanability. The most straightforward implementation of this option would be to refactor the `rke2-runtime` container image, so it has both CNI plugin charts and the rest of charts in different folders (e.g. `/charts` and `/charts/cni-plugins`). The logic on applying `/charts` is unchanged (listing files under that directory and applying them), whereas the `--cni-plugin=` argument involves looking at `/charts/cni-plugins/rke2-{cni-plugin}.yaml` and applying the one that matches (if any).

Please, let us know if there is a preferred approach for managing this, or if you had something in mind on how to implement this feature.

/cc @manuelbuil

**Comment by davidnuzik** [comment]
@rancher-max to test with v1.20.6+rke2r1 and then lightly test in v1.21.0+rke2r1 (its RC).

**Comment by rancher-max** [comment]
This is validated on v1.20.6+rke2r1 according to our test plan. Pending one issue: https://github.com/rancher/rke2/issues/931

**Comment by rancher-max** [comment]
Issue has been resolved. Cilium is working completely now in v1.20.6+rke2r1 and in v1.21.0-alpha2+rke2r1
