### ISSUE TITLE
kubelet affected by CONTAINERD_* environment, ignoring NO_PROXY

### ISSUE THREAD

**Issue by andreas-p** [rancher/rke2#4924]
**Environmental Info:**
RKE2 Version: v1.27.6+rke2r1   
Linux 6.1.0-12-amd64 Debian12  
first node, fresh air-gapped install from tarballs 

The environment is configured in /etc/default/rke-server for containerd to have all its traffic redirected via a proxy:
```
CONTAINERD_HTTP_PROXY=http://registry-proxy:3128
CONTAINERD_HTTPS_PROXY=http://registry-proxy:3128
CONTAINERD_NO_PROXY=.my-domain
```

According to https://docs.rke2.io/advanced#configuring-an-http-proxy, this should configure containerd only. Since containerd will access images via FQDN only, local networks were omitted from CONTAINERD_NO_PROXY.

**Describe the bug:**

After rke-server is started successfully and kubectl reports the node ready, many pods are still in state ContainerCreating. Examining rke2-coredns-rke2-coredns-5f5d6b54c7-nc49d, kubectl describe shows 
```
kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "57fbff22dd766fa2738e98333bafcbbf95fb08f5442d35f794ce37419cd39ca1": plugin type="calico" failed (add): error getting ClusterInformation: Get "https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": tls: failed to verify certificate: x509: certificate is valid for 192.168.17.101, 127.0.0.1, ::1, not 10.43.0.1
```

So apparently kubelet is not accessing the kubernetes service at 10.43.0.1, but the registry-proxy at 192.168.17.101.

`cat /proc/<pid-of-kubelet>/environ` looks as expected, including `NO_PROXY=.svc,.cluster.local,10.42.0.0/16,10.43.0.0/16` .

**Steps To Reproduce:**
- Start rke2 with CONTAINERD settings as above, esp no local networks in CONTAINERD_NO_PROXY.

**Expected behavior:**
kubelet should work unaffected.

**Actual behavior:**

In contrast to the documentation at https://docs.rke2.io/advanced#configuring-an-http-proxy, kubelet will use CONTAINERD_* settings, and ignores the NO_PROXY setting.

**Workaround:**
https://docs.rke2.io/advanced#configuring-an-http-proxy suggests to set `CONTAINERD_NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16` as example. This turns out to be a workaround for the unexpected behavior.

**Comment by brandond** [comment]
>`x509: certificate is valid for 192.168.17.101, 127.0.0.1, ::1, not 10.43.0.1`
>
> apparently kubelet is not accessing the kubernetes service at 10.43.0.1, but the registry-proxy at 192.168.17.111.

I'm not sure how you made that connection? The address in the error is not the same as the IP addresses that you say your registry is using.


> cat /proc/<pid-of-kubelet>/environ looks as expected, including NO_PROXY=.svc,.cluster.local,10.42.0.0/16,10.43.0.0/16 .

RKE2 always adds the cluster CIDRs and domain to the NO_PROXY environment variable. This is working as designed.

Nothing you've shown indicates that anything else is using the configured proxy.  

Also, the recommended way to set up registry caches is via registries.yaml as covered in the docs. You may find that things don't work quite right when attempting to use your registry as a HTTP forward proxy.

**Comment by andreas-p** [comment]
Fixed typo: 192.168.17.101 is the proxy. This IP isn't configured anywhere, kubelet can only get that certificate when accessing the proxy, which it shouldn't do.

**Comment by brandond** [comment]
Not all CNIs call out to the network to retrieve and store information, calico just happens to be one that does. Flannel for example is pretty much self-contained within config files local to the node.

**Comment by andreas-p** [comment]
I wonder if automatically adding cluster internal ip ranges to CONTAINERD_NO_PROXY, just as performed on NO_PROXY, would be a good idea.
