### ISSUE TITLE
Etcd restore does not work as expected while extra-args is passed to controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#4930]
**Environmental Info:**
RKE2 Version: 
v1.26.8+rke2r1

Node(s) CPU architecture, OS, and Version: 
NA, Ubuntu 22.04

Cluster Configuration:
Split server, All roles

**Describe the bug:**
While restoring from snapshot on a split role or all roles cluster, the joining nodes are stuck at NotReady state. They take ~15min to join the cluster.

**Config used:**

```
$ cat /etc/rancher/rke2/config.yaml

write-kubeconfig-mode: "0644"
cni: calico
kube-controller-manager-arg:
 - cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager
 - secure-port=10257
kube-controller-manager-extra-mount:
 - /var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager
kube-scheduler-arg:
 - cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler
 - secure-port=10259
kube-scheduler-extra-mount:
 - /var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler
```

**Steps To Reproduce:**
1. Create the cluster with the above config
2. Take a snapshot
3. Run rke2-killall.sh on all nodes
4. Restore from snapshot taken earlier
5. Start rke2 service
6. Wait for node to be Ready and other nodes to be in NotReady state
7. Start rke2 service on the other nodes
8. Wait for the Nodes to be Ready. Notice node are stuck at NotReady for atleast 15 min before joining the cluster

**Expected behavior:**
Nodes should join back at reasonable time like 2-4 min

**Actual behavior:**
Nodes took longer to join back

**Additional context / logs:**
This behavior is seen only when we pass extra args. Cluster restores correctly while extra args are not passed.

**Workaround:**
Before restoring from snapshot
On all server nodes run:
```
sudo rke2-killall.sh 
sudo rm -rf /var/lib/rancher/rke2/server/manifests/rke2-*.yaml
sudo rm -rf  /var/lib/rancher/rke2/server/db/etcd/tombstone
sudo touch /var/lib/rancher/rke2/server/db/etcd/tombstone
sudo rm -rf  /var/lib/rancher/rke2/agent/pod-manifests
```
On agent nodes:
```
sudo rke2-killall.sh 
sudo rm -rf  /var/lib/rancher/rke2/agent/pod-manifests
```

**Comment by brandond** [comment]
Specifically, the issue seems to be triggered by the extra volumes for `/var/lib/rancher/rke2/server/tls/kube-scheduler`. If the kubelet is in the process of mounting these paths at the same time the mirror pod is discovered by the apiserver, seems to break the kubelet's tracking of mount points for the pod, and it thinks it is forever stuck with umounted volumes.

**Comment by ShylajaDevadiga** [comment]
## Validated on rke2 version v1.28.3-rc4+rke2r1 
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Config:*
3 server nodes

Initial setup Nodes are are Ready state
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-13-115   Ready    control-plane,etcd,master   21m   v1.28.3+rke2r1
ip-172-31-14-81    Ready    control-plane,etcd,master   15m   v1.28.3+rke2r1
ip-172-31-7-176    Ready    control-plane,etcd,master   15m   v1.28.3+rke2r1
```
Nodes are in NotReady after restoring on first nodes
```
$ kubectl get nodes
NAME               STATUS     ROLES                       AGE   VERSION
ip-172-31-13-115   Ready      control-plane,etcd,master   22m   v1.28.3+rke2r1
ip-172-31-14-81    NotReady   control-plane,etcd,master   16m   v1.28.3+rke2r1
ip-172-31-7-176    NotReady   control-plane,etcd,master   16m   v1.28.3+rke2r1
```
Nodes joined the cluster successfully within 2-3 min
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-13-115   Ready    control-plane,etcd,master   25m   v1.28.3+rke2r1
ip-172-31-14-81    Ready    control-plane,etcd,master   19m   v1.28.3+rke2r1
ip-172-31-7-176    Ready    control-plane,etcd,master   19m   v1.28.3+rke2r1
```
