### ISSUE TITLE
[BUG] Core DNS HelmChartConfig does not patch

### ISSUE THREAD

**Issue by aceeric** [rancher/rke2#4940]
### Information about the Cluster
- Kubernetes version: RKE2 v1.25.11+rke2r1
- Cluster Type: Local

### User Information
- What is the role of the user logged in?: Admin/Cluster Owner

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? Rancher Federal Ansible Installer: https://github.com/rancherfederal/rke2-ansible

### Describe the bug
It does not appear to be possible to *patch* an additional CoreDNS Plugin using the documented `HelmChartConfig`.

### To Reproduce
1. Place the following file in `/var/lib/rancher/rke2/server/manifests/rke2_manifests/rke2-coredns-config.yaml` with the intent of **adding** a plugin to the out-of-the-box plugins:
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    servers:
    - plugins:
      - name: hosts
        configBlock: |-
          fallthrough
```
2. Install RKE2

### Actual Result
`kubectl -n kube-system describe cm rke2-coredns-rke2-coredns` shows:
```
apiVersion: v1
data:
  Corefile: |-
    .{
        hosts  {
            fallthrough
        }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: rke2-coredns
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-08-02T18:41:44Z"
  labels:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rke2-coredns
    helm.sh/chart: rke2-coredns-1.24.002
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: rke2-coredns-rke2-coredns
  namespace: kube-system
  resourceVersion: "1187"
  uid: 70578fc3-7c88-4a46-abaa-2e67b079c523
```
### Expected Result
Additional plugin *merged* into the out-of-the-box RKE2 CoreDNS `Corefile` CM

### Additional context
Is there a way to declaratively _patch_ in an additional plugin into the default Core DNS config without fully re-specifying the out of the box config? My concern with fully re-specifying is - once I do that my duplicated/modified manifest could drift with future RKE2 releases. So each time I upgrade RKE2 I need to re-evaluate that `HelmChartConfig` to ensure that the parts I copied from RKE2 are still the same...

**Comment by brandond** [comment]
I moved this from rancher/charts, as the chart and chart controller in question have nothing to do with Rancher, or charts from the Rancher charts repo.

The rke2-coredns chart comes from here:
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-coredns/rke2-coredns/1.24.007/values.yaml

Note that `servers` in the values file is an array. According to https://github.com/helm/helm/issues/6569 it is NOT POSSIBLE to append items to an array when merging values. If you want to add an item to a default list, you must include the original list items, and add your new value at the desired position.
