### ISSUE TITLE
rke2 etcd-snapshot save logs wrong s3 bucket/folder path

### ISSUE THREAD

**Issue by aganesh-suse** [rancher/rke2#4941]
**Environmental Info:**
RKE2 Version: 

rke2 -v
rke2 version v1.28.3-rc2+rke2r1 (0d0d0e4879fdf95254461e3a49224f75d7b2dc3d)
go version go1.20.10 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Ubuntu 22.04 

Cluster Configuration:

3 server/1 agent 
**Describe the bug:**

This is really a nit bug. 
$ sudo rke2 etcd-snapshot save 
.
.
INFO[0005] Uploading snapshot to s3://s3_bucket//var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-x-x-x-x-1697836368
INFO[0007] Uploaded snapshot metadata s3://s3_bucket//var/lib/rancher/rke2/server/db/.metadata/on-demand-ip-x-x-x-x-1697836368
.
.

It is logging the s3_bucket/<local folder name> as the s3 url... instead of s3_bucket/<s3_folder> path. 
It saves to the right place though.

**Comment by mdrahman-suse** [comment]
## Validated using v1.29.1-rc2+rke2r1

Followed steps mentioned here: https://github.com/rancher/rke2/issues/4941#issue-1955022968

## Testing

1. Install rke2
2. Enable and start rke2-server.service
3. Ensure cluster is up and running
4. Perform etcd-snapshot save
```
sudo rke2 etcd-snapshot save \
--s3 \
--s3-bucket="<bucket>" \
--s3-folder="<folder>" \
--s3-access-key="<access-key>" \
--s3-secret-key="<secret-key>" \
--s3-region="<region>"
```

## Replication result:

```
rke2 version v1.29.0+rke2r1 (4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709)
go version go1.21.5 X:boringcrypto
```
- Observed console output
```
...
INFO[0000] Saving etcd snapshot <snapshot-name> to S3
INFO[0000] Uploading snapshot to s3://<bucket>//var/lib/rancher/rke2/server/db/snapshots/<snapshot-name>
INFO[0000] Uploaded snapshot metadata s3://<bucket>/<folder>/.metadata/<snapshot-name>
INFO[0000] S3 upload complete for <snapshot-name>
...
```

## Validation result:
```
rke2 version v1.29.1-rc2+rke2r1 (a4986a5a5840f1a259e66c61553a9abd58ef9624)
go version go1.21.6 X:boringcrypto
```
- Observed console output
```
...
INFO[0000] Saving etcd snapshot <snapshot-name> to S3
INFO[0000] Uploading snapshot to s3://<bucket>/<folder>/<snapshot-name>
INFO[0000] Uploaded snapshot metadata s3://<bucket>/<folder>/.metadata/<snapshot-name>
INFO[0000] S3 upload complete for <snapshot-name>
```
Also validated on upgrades and compressed format

**Comment by mdrahman-suse** [comment]
## Validated the backports on
- v1.28.6-rc2+rke2r1
- v1.27.10-rc2+rke2r1
- v1.26.13-rc2+rke2r1
