### ISSUE TITLE
[Documentation] Update README.md to mention security issue reporting process

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#495]
Similar to https://github.com/rancher/k3s/pull/2395
There should be an update to README.md explaining the process for reporting any security issues.

**Comment by matttrach** [comment]
I believe this is already done.

**Comment by briandowns** [comment]
Can you include a link please?

**Comment by matttrach** [comment]
Sure, this is the k3s issue: https://github.com/k3s-io/k3s/pull/2395/files
and the same content already exists in the README.md and SECURITY.md files in the repo:
- https://github.com/rancher/rke2/blob/master/README.md#security
- https://github.com/rancher/rke2/blob/master/SECURITY.md#reporting-a-vulnerability

**Comment by briandowns** [comment]
Thank you.
