### ISSUE TITLE
rke2 issues on hosts with very large routing tables

### ISSUE THREAD

**Issue by ickymettle** [rancher/rke2#4983]
In our environment we've run into a bit of and issue with rke2. The issue is a little bit specific to our environment and i'm not sure how we might be able to move forward.

We're prototyping a new bare metal cluster and have been evaluating moving to rancher for cluster management. In our environment the target hosts carry full BGP routing tables (over 1.5M entries). At present rke2 is unable to even display its help output.

Digging into the issue, at startup an inordinate amount of time is spent reading the routing table entries via netlink:

```
SIGQUIT: quit
PC=0x404dce m=0 sigcode=0

goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0xc000c73900?, 0x0?, 0xc0009ff158?, 0x454396?, 0x500?, 0x32633c0?, 0x485d01?)
	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36 fp=0xc0009ff0e8 sp=0xc0009ff060 pc=0x48ba16
syscall.recvfrom(0xc000c73900?, {0xc00093e000?, 0x4843f9?, 0xc000c70c80?}, 0x3?, 0x2?, 0x1?)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1531 +0x58 fp=0xc0009ff150 sp=0xc0009ff0e8 pc=0x48b3d8
syscall.Recvfrom(0xc00093e000?, {0xc00093e000?, 0x1000?, 0x1000?}, 0x0?)
	/usr/local/go/src/syscall/syscall_unix.go:317 +0x6d fp=0xc0009ff218 sp=0xc0009ff150 pc=0x4869cd
syscall.NetlinkRIB(0xc00131f390?, 0x41018a?)
	/usr/local/go/src/syscall/netlink_linux.go:79 +0x405 fp=0xc0009ff328 sp=0xc0009ff218 pc=0x483de5
go.etcd.io/etcd/pkg/v3/netutil.getDefaultRoutes()
	/go/pkg/mod/github.com/k3s-io/etcd/pkg/v3@v3.5.9-k3s1/netutil/routes_linux.go:96 +0x32 fp=0xc0009ff3d8 sp=0xc0009ff328 pc=0x2283f72
go.etcd.io/etcd/pkg/v3/netutil.GetDefaultHost()
	/go/pkg/mod/github.com/k3s-io/etcd/pkg/v3@v3.5.9-k3s1/netutil/routes_linux.go:38 +0x2b fp=0xc0009ff4c0 sp=0xc0009ff3d8 pc=0x2283c2b
go.etcd.io/etcd/server/v3/embed.init.0()
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/embed/config.go:136 +0x17 fp=0xc0009ff4d0 sp=0xc0009ff4c0 pc=0x248c897
runtime.doInit(0x56df720)
	/usr/local/go/src/runtime/proc.go:6525 +0x126 fp=0xc0009ff600 sp=0xc0009ff4d0 pc=0x44b766
runtime.doInit(0x56c90c0)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ff730 sp=0xc0009ff600 pc=0x44b6b1
runtime.doInit(0x56bde40)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ff860 sp=0xc0009ff730 pc=0x44b6b1
runtime.doInit(0x56971e0)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ff990 sp=0xc0009ff860 pc=0x44b6b1
runtime.doInit(0x56d55c0)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ffac0 sp=0xc0009ff990 pc=0x44b6b1
runtime.doInit(0x56d0640)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ffbf0 sp=0xc0009ffac0 pc=0x44b6b1
runtime.doInit(0x56d92c0)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ffd20 sp=0xc0009ffbf0 pc=0x44b6b1
runtime.doInit(0x56c8640)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009ffe50 sp=0xc0009ffd20 pc=0x44b6b1
runtime.doInit(0x569c360)
	/usr/local/go/src/runtime/proc.go:6502 +0x71 fp=0xc0009fff80 sp=0xc0009ffe50 pc=0x44b6b1
runtime.main()
	/usr/local/go/src/runtime/proc.go:233 +0x1c6 fp=0xc0009fffe0 sp=0xc0009fff80 pc=0x43dfe6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0009fffe8 sp=0xc0009fffe0 pc=0x4731c1
```

The underlying cause appears to be an init function in [etcd/server/embed.go](https://github.com/k3s-io/etcd/blob/v3.5.9-k3s1/server/embed/config.go#L135-L137) which: 
* calls etcd's [netutils.GetDefaultHost()](https://github.com/k3s-io/etcd/blob/master/pkg/netutil/routes_linux.go#L36)
* which subsequently calls [getDefaultRoutes()](https://github.com/k3s-io/etcd/blob/master/pkg/netutil/routes_linux.go#L94) which issues a netlink `RTM_GETROUTE` message to fetch all the routes, iterates over them and attempts to determine first IP address for the machine.

Given this is called via an init function there doesn't seem to be an easy way to bypass this behaviour. I don't think rke2 uses etcd at all and this is a side effect of the k3s-io dependency where all the init() functions across the module will be called.

Any suggestions for paths forward would be appreciated. We're exploring some other options internally but wanted to get this logged. As mentioned we're probably a little bit unique in our environment - I couldn't find any other past reports of similar issues.

Thanks!
Marcus

**Comment by brandond** [comment]
We do actually us the embedded etcd from k3s; it is used to extract data from the etcd database files prior to startup of the full containerized etcd that is managed by the static pod by way of the kubelet.

Even if that was not present, I suspect that the same init function would prevent the etcd static pod from starting up, as it runs with host network and will also be exposed to your very large route tables.

Why do you find it necessary to push your full BGP routing tables down into every node? You can't offload this to top-of-rack switches or something else even one hop removed from the nodes?

**Comment by ickymettle** [comment]
Thanks for the reply and detail on your etcd usage. Confirms my other concern that we'd run into this regardless given it's etcd specific more so than rancher. So we'll need to think about how we might solve this in other creative ways.

>Why do you find it necessary to push your full BGP routing tables down into every node? You can't offload this to top-of-rack switches or something else even one hop removed from the nodes?

It's a pretty deliberate architectural design decision in our environment. It works fabulously for our primary use case (we're a large CDN), but does make integrating with some other tech a bit more challenging.

**Comment by ickymettle** [comment]
We've managed to resolve this internally. As you've mentioned this is expected behaviour and a bit of an "us" problem :) Thanks for taking the time to comment.

**Comment by brandond** [comment]
If you can share any info on how you solved it, I'd love to hear more! Plus it might help the next person who has a similar problem.
