### ISSUE TITLE
scan the base build image for vulnerabilities before compiling binaries and copying to Scratch image

### ISSUE THREAD

**Issue by cnuber** [rancher/rke2#499]
The rke2 image build process results in a FROM scratch image.  As such, scanners like trivy/clair/etc do not run against the image.

Scanning the base build image as part of the image build process before the binaries are compiled and copied over to the final Scratch image would allow for proactive identification and remediation of any known vulnerabilities in the libraries included in the compiled binary.

**Comment by briandowns** [comment]
We are scanning the base image prior to RKE2 build. https://github.com/rancher/rke2/blob/7e5ffec7434767e1e0ab4a333ee77dfd63a2308e/Dockerfile#L61-L70
