### ISSUE TITLE
kubelet-arg does not accept CPU manager settings

### ISSUE THREAD

**Issue by ninjab3s** [rancher/rke2#4992]
**Environmental Info:**
RKE2 Version: 
v1.24.17+rke2r1

Node(s) CPU architecture, OS, and Version: 
Single node cluster, Intel(R) Xeon(R) Gold 6338N CPU @ 2.20GHz, Ubuntu 2204

Cluster Configuration:
1 agent, 1 server

**Describe the bug:**
I want to apply kublet args to activate the CPU management. Unfortunately, I get prompted with the following error message in the kubelet journal log:
`Error: failed to parse kubelet flag: unknown flag: --cpu-manager`

I have tried what I have found in these threads:
https://github.com/rancher/rke2/discussions/3034
https://github.com/rancher/rke2/issues/2118

**Steps To Reproduce:**

Edit /etc/rancher/rke2/config.yaml and add the following content:

```
kubelet-arg:
- "cpu-manager=true"
- "cpu-manager-policy=static"
- "cpu-manager-policy-options=full-pcpus-only=true"
- "cpu-manager-reconcile-period=0s"
- "reserved-cpus=0,1,2,3"
```

**Expected behavior:**
CPU manager settings get applied.

**Actual behavior:**
The kublet fails to start with the following error:
`Error: failed to parse kubelet flag: unknown flag: --cpu-manager`

**Comment by brandond** [comment]
As the error suggests, there is no such flag. You can find a list of valid flags in the upstream docs at https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
