### ISSUE TITLE
How helmchart disable openapi validation?

### ISSUE THREAD

**Issue by liyang516** [rancher/rke2#4994]
I use helmchart deploy hwameistor, chart version is 0.12.3。
when I upgrade this chart to version 0.13.0 ，helmchart pod is Error，logs is blow

```shell
# kubectl logs -n kube-system helm-install-hwameistor-operator--1-z49p2 
...
...
+ helm_v3 install --namespace hwameistor --repo http://chartmuseum.chartmuseum.svc.cluster.local:8080 --version v0.13.1 --set-string localDiskManager.kubeletRootDir=/var/lib/kubelet --set-string localStorage.kubeletRootDir=/var/lib/kubelet hwameistor-operator hwameistor-operator --values /config/values-01_HelmChart.yaml
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Cluster.spec.localStorage.member): unknown field "juicesyncImage" in io.hwameistor.v1alpha1.Cluster.spec.localStorage.member
``` 

It seems that the clusters.hwameistor.io(crd) changed，so k8s validating error .
If I use helm command upgrade，I could use **helm upgrade --disable-openapi-validation**  to disable validation，but use helmchart how to resolve it？

**Comment by brandond** [comment]
There is not currently any way to do this. I suspect you'll need to update the chart to have the correct object schema before you'll be able to upgrade.
