### ISSUE TITLE
Ingress proxy cannot access containers on remote hosts

### ISSUE THREAD

**Issue by thomas-workaccount** [rancher/rke2#4997]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.26.10+rke2r1 (9b01c8e4e9f781a2654075f43cb59b922fed1713)
go version go1.20.10 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux ip-10-0-0-231 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
rke2-ingress-nginx-controller pods are running on all 3 nodes and currently the proxy can access the app container running on the same machine. Look at the related log entries for working and not working cases:

10.0.1.156 - - [08/Nov/2023:15:59:54 +0000] "GET / HTTP/1.1" 200 6 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 809 0.001 [apps-first-80] [] 10.42.0.24:3000 6 0.000 200 17b299a13663c34b95588796bb1f1a5e -- This container is on the same machine where the proxy runs.

2023/11/08 15:59:54 [error] 796#796: *4709728 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.1.156, server: HOSTNAME, request: "GET / HTTP/1.1", upstream: "http://10.42.2.8:3000/", host: "HOSTNAME" -- In this case the container runs on another machine.

**Steps To Reproduce:**
- Run some test app
- Create an Ingress  and service to get to the app via Ingress proxy
- Add cluster nodes to the LB using which the app is accessed externally.

**Expected behavior:**
The app must be accessible regardless of where the app containers run.

**Actual behavior:**
Gets 504 gateway error when the container is not running on the host where the ingress proxy pod is running.

**Additional context / logs:**

**Comment by brandond** [comment]
It sounds like CNI traffic between nodes is being dropped. If you're sure that you've opened all the correct ports (see https://docs.rke2.io/install/requirements#inbound-network-rules), you might check out the thread at https://github.com/rancher/rke2/issues/4993#issuecomment-1799661561 and see if disabling hardware offload resolves your issue.

**Comment by thomas-workaccount** [comment]
@brandond Thanks for pointing the right direction. The inbound access rule on port 8472 for UDP was missing and the issue could be resolved by adding it. I ran "ethtool --offload flannel.1 rx off tx off" also on all the nodes, but that is not needed I think. Will verify this in another cluster and report if I would find anything different.
