### ISSUE TITLE
Kube-proxy cannot specify -v argument

### ISSUE THREAD

**Issue by kgtw** [rancher/rke2#4998]
**Environmental Info:**
RKE2 Version: 

v1.27.6+rke2r1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

3 servers, 6 agents

**Describe the bug:**

When configuring `kube-proxy-arg` with `v=3` the `rke2-server` service fails to start.

```
level=fatal msg="failed to validate kube-proxy conntrack configuration: unknown flag: --v"
rke2-server.service: Main process exited, code=exited, status=1/FAILURE
rke2-server.service: Failed with result 'exit-code'.
```

**Steps To Reproduce:**

- Installed RKE2: 

- Configure kube-proxy arguments:
```
kube-proxy-arg:
- v=3
```

**Expected behavior:**

kube-proxy component to be configured with relevant verbosity via the `-v` argument flag.

**Actual behavior:**

`rke2-server.service` crashes because of a fatal error, preventing any new server or agents to bootstrap and connect to the cluster.

**Additional context / logs:**

**Comment by brandond** [comment]
Will need to be fixed on the k3s side; apparently the arg parser from `kubeproxy.NewProxyCommand` no longer recognizes the `--v` flag.

Ref: https://github.com/k3s-io/k3s/blob/f5920d7864ce17062f98ca5a345b078a10b64a12/pkg/agent/run.go#L181-L185

**Comment by VestigeJ** [comment]
So I tried and failed to reproduce this on v1.29.0+rke2r1 but was able to re-use the above mentioned version to catch it. 



##Environment Details
Reproduced using VERSION=v1.27.6+rke2r1
Validated using VERSION=v1.29.1-rc2+rke2r1

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"

*Cluster Configuration:*

```
NAME              STATUS   ROLES                       AGE     VERSION
ip-12-13-12-13    Ready    control-plane,etcd,master   5m51s   v1.29.1+rke2r1
```

*Config.yaml:*

```
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
protect-kernel-defaults: true
cluster-init: true
kube-proxy-arg:
- v=3
```

<details><summmary><h4>Reproduction</h4></summary>



```
$ curl https://get.rke2.io --output install-"rke2".sh
$ sudo chmod +x install-"rke2".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ VERSION=v1.27.6+rke2r1
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh
$ go_rke2 //sudo systemctl enable rke2-server --now
$ sudo journalctl -u rke2-server | grep -i "unknown"
//uninstall / cleanup journalctl logs
$ VERSION=v1.29.1-rc2+rke2r1
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh
$ go_rke2 //sudo systemctl enable rke2-server --now
$ set_kubefig //export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
$ kgn //kubectl get nodes
$ kgp -A //kubectl get pods -A
$ sudo journalctl -u rke2-server | grep -i "v=3"
```

</details>

**Results:**

$ sudo journalctl -u rke2-server | grep -i "unknown"
```
 level=fatal msg="failed to validate kube-proxy conntrack configuration: unknown flag: --v"
```

$ sudo journalctl -u rke2-server | grep -i "v=3"
```
 level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s --conntrack-tcp-timeout-established=0s --healthz-bind-address=127.0.0.1 --hostname-override=ip-12-13-12-13 --kubeconfig=/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig --proxy-mode=iptables --v=3"
```


Validated
