### ISSUE TITLE
Openstack cloud provider

### ISSUE THREAD

**Issue by Born2Bake** [rancher/rke2#501]
Hi,

Is openstack cloud provider supported by rke2?

I am trying to add https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md via rke2 server --cloud-provider-name & --cloud-provider-config and cluster provisioning is stuck at api implementation.

Thank you

**Comment by cjellick** [comment]
We don't test it and over the years we have seen a lot of problems in RKE1 with it. RKE2 is very much vanilla kubernetes, so it "should work."

**Comment by cjellick** [comment]
going to close, but i'll still get notified if you have a follow up.
