### ISSUE TITLE
Failed bootstrapping of node leads to certificate mismatches

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#5048]
**Environmental Info:**
RKE2 Version: v1.27.7+rke2r1

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
3 servers

**Describe the bug:**
There is weirdness that can occur when quickly bootstrapping RKE2 nodes into place. We saw the initial node not persist its dynamic listener secret, leading to subsequent nodes being able to persist their data onto the node. This led to failures down the line as the SAN list was not complete within the dynamic listener secret on the init node.

**Steps To Reproduce:**
This is difficult to reproduce, but was seen in a scenario where `node-A` (init node) bootstrapped, `node-B` was joined via `--server` and `--token` to it right after `node-A` was "ready". In an unrelated operation, `node-B` was restarted and was unable to restart as `node-A` was serving using a certificate that only had `node-B`'s IP in it.

**Expected behavior:**
RKE2 does not do this 

**Actual behavior:**
RKE2 is stuck crashing. It is probably possible to manually recover the cluster, but as this issue was found in the Rancher provisioning tests as a flake, it is not possible to see if manual recovery was possible.

**Additional context / logs:**
[logs_rancher_rancher_34445_4_2.log-parsed.zip](https://github.com/rancher/rke2/files/13385994/logs_rancher_rancher_34445_4_2.log-parsed.zip)

**Comment by mdrahman-suse** [comment]
Unable to replicate the issue with standalone rke2 (also this version is not supported in Rancher, yet), tried with the 1.28.3+rke2r2 version on different OS (Ubuntu, RHEL) with various setups (HA, split roles, etc). Closing it for now and will keep an eye out if this issue resurfaces and will check as part of patch validation for any regression.

Validated the dynamic listener version bump in go.mod for RC v1.28.4-rc1+rke2r1, which is tagged using commit 2c842468
https://github.com/rancher/rke2/blob/2c84246818190995417c5888dec972ea00e1e345/go.mod#L305
From release v1.28.3+rke2r2 (commit cf6c1ae3):
https://github.com/rancher/rke2/blob/cf6c1ae3f199c2e838ba19125cbd2d522c8765d3/go.mod#L305
@Oats87 Please let us know if this issue appears again
