### ISSUE TITLE
How to disable snapshot controller install in rke2-v1.28.3

### ISSUE THREAD

**Issue by liyang516** [rancher/rke2#5061]
I want to disable snapshot controller installed in rke2,  Is there any solution？

**Comment by brandond** [comment]
you can use --disable to turn off any packaged component. So for this you would want `--disable=rke2-snapshot-controller,rke2-snapshot-controller-crd,rke2-snapshot-validation-webhook`

**Comment by sojjan1337** [comment]
For disabling it in rancher gui directly:

spec:
  rkeConfig:
    machineGlobalConfig:
      disable:
        - rke2-snapshot-controller
        - rke2-snapshot-controller-crd
        - rke2-snapshot-validation-webhook
