### ISSUE TITLE
Rancher RKE2  installation script will failed if run on arm64 server because sha256sum-arm64.txt file is missing in version 1.26.10 repo

### ISSUE THREAD

**Issue by DSNYCYANG** [rancher/rke2#5067]
**Environmental Info:**
RKE2 Version: 
v1.26.10 (default version now)

Node(s) CPU architecture, OS, and Version: 
Oracle Cloud arm64 server, ubuntu 22.04.3

Cluster Configuration:
first node

**Describe the bug:**
install script will stop and report can't fine sha256sum-arm64.txt file

**Steps To Reproduce:**
just run curl -sfL https://get.rke2.io | sh -

**Expected behavior:**
install script should run successfully

**Actual behavior:**
install script failed with error can't fine sha256sum-arm64.txt file

**Additional context / logs:**
I can confirm  sha256sum-arm64.txt file is not in github [v1.26.10+rke2r2] Assets list (https://github.com/rancher/rke2/releases/tag/v1.26.10%2Brke2r2)

**Comment by brandond** [comment]
arm64 support is still experimental; we are only publishing arm64 support for 1.27 and newer - there will be no artifacts for older minors.
