### ISSUE TITLE
support for more than 253 pods per node by default

### ISSUE THREAD

**Issue by harridu** [rancher/rke2#5076]
**Is your feature request related to a problem? Please describe.**

If you look at today's hardware with 32 cores + HT and 2 real CPUs per node, and the typical load at run time as returned by kubectl top, the default of 110 pods per node doesn't appear to be reasonable. The upper limit in cluster.yaml seems to be 253, restricted by the internal default /24 network. This is too small. I would like to use 1000 pods per node to increase utilization on modern hardware.

**Describe the solution you'd like**

RKE2 could use /16 IPv4 subnets (or IPv6-only) on internal networks per default.

**Comment by brandond** [comment]
We are not planning on raising the default for rke2 above what the upstream Kubelet defaults to. It is easy enough to change is users have hardware that they believe can support it. We are certainly not going to raise it by a factor if 10.

**Comment by harridu** [comment]
I understand that you rely on upstream here, but hopefully you agree that the current restriction conflicts with the microservices paradigm?
