### ISSUE TITLE
Kubectl incorrect information 

### ISSUE THREAD

**Issue by hpeaj** [rancher/rke2#5077]
Installed Latest version of RKE2 using https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher 
curl -sfL https://get.rke2.io | sh -

```console
elk103:~ # kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
NAME     STATUS   ROLES                       AGE   VERSION
elk103   Ready    **control-plane,etcd,master**   49m   v1.26.10+rke2r2
elk105   Ready    **control-plane,etcd,master**   31m   v1.26.10+rke2r2
elk106   Ready    **control-plane,etcd,master**   27m   v1.26.10+rke2r2
elk103:~ #
```

isnt the should that last role say **worker** or **node**?
control-plane and master together are confusing. 
is this display issue or has the worker node role has been configured  confused? 

```console
elk103:~ # kubectl describe node elk103
Name:               elk103
Roles:              control-plane,etcd,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=rke2
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=elk103
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/etcd=true
                    node-role.kubernetes.io/master=true
```

**Comment by brandond** [comment]
> isnt the should that last role say worker or node?

All of these are nodes. RKE2 doesn't use the "worker" role. Servers are master/control-plane and/or etcd. Agents do not have a role. You're welcome to add a your own roles to the RKE2 config if it would make you feel better to have them on agents:
```yaml
node-role:
  - "node-role.kubernetes.io/worker=true"
```

> control-plane and master together are confusing.

The two roles are equivalent. We will eventually drop the legacy master role, but have retained it for purposes of backwards compatibility.

**Comment by maxisam** [comment]
i do think it is confusing without worker role. I understand RKE2 doesn't need it but it is convention to have it. I thought something was wrong.

**Comment by brandond** [comment]
RKE1 did a lot of things that RKE2 does not. Don't expect that rke2 has any of the same design decisions.
