### ISSUE TITLE
Taint server nodes by default (with easy toggle)

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#508]
Right now, RKE2 does not taint server nodes by default. This is **not** in alignment with other distributions suchas as kubeadm and RKE1.

This behavior of not-tainting was inherited from k3s, where not-tainting server nodes is the desired default bc small clusters made up entirely of all-in-one nodes is the assumed default usecase.

RKE2 should align with RKE1 and taint server nodes by default.

There should also be an easy parameter for toggling this behavior (rather than having to directly manipulate the taints). Something like: `--taint-server-nodes=false`.

I suspect https://github.com/rancher/rke2/issues/505 is related because I'm guessing that the user wants is to be able to ensure workloads only land on worker nodes.

**Comment by davidnuzik** [comment]
Added to near top of backlog for further triaging

**Comment by brandond** [comment]
I don't think this is desired. A three-node server-only cluster is a common deployment pattern. If users want to taint the servers and deploy dedicate agent nodes that is easy enough to do.

**Comment by caroline-suse-rancher** [comment]
Closing for now - can reopen if we reprioritize in the future.

**Comment by ss-dsutherland** [comment]
I think this should be reopened.  The documentation should be clear about which taints to use and how to apply them(which it doesn't).  Most k8s distros you can just taint noschedule for node-role.kubernetes.io/master but in the case of rke2 that will break the cluster.  I tried using also the following (as its what rke1 uses) but it also breaks the cluster:

      - node-role.kubernetes.io/etcd=:NoExecute
      - node-role.kubernetes.io/controlplane=:NoSchedule

thoughts?
