### ISSUE TITLE
Loadbalancer occasionally timesout

### ISSUE THREAD

**Issue by AdamJSoftware** [rancher/rke2#5085]
**Environmental Info:**
RKE2 Version: v2.7.6

Node(s) CPU architecture, OS, and Version: 
Linux apps2-pool1-070c2e68-qbsw9 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux * 3

Cluster Configuration:
3 servers

**Describe the bug:**
This only happens on one of my clusters. My others don't have this issue. When I create a loadbalancer, about 1/3 of my requests timeout, and the other ones are quite slow. This cluster also frequently displays fsnotify: too many open files when trying to read logs which leads me to believe that it is an issue with too many open files but that can also be a red hearing. I also remember having issues creating a horizontal pod scaler but I don't know if that's related to this. I am routing all the LB traffic to traefik BTW.

**Comment by brandond** [comment]
RKE2 doesn't ship with a load-balancer controller or Traefik, so these would both be components that you deployed yourself? I'm not sure how we can help with things that we don't provide.

**Comment by AdamJSoftware** [comment]
My bad. I have some further development anyways. I was at RKE2 version  v1.26.4 but then I upgraded to version  v1.26.10+rke2r2 and I noticed that the timeouts significantly diminished, there are still some requests that occasionally timeouts but significantly less.

**Comment by brandond** [comment]
Closing, please feel free to reopen if there is anything RKE2-specific we can address.
