### ISSUE TITLE
v1.18.12+rke2r1 Release

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#509]
**Summary:**
Task covering release work. v1.18.11+rke2r1 is slated for ~11/2/20~ 11/11/20 release, although this could change.
Code Freeze: 11/6/2020

**List of required releases:**
_To release as soon as able for QA:_
v1.18.11-rc1+rke2r1

_To release once have approval from QA:_
v1.18.11+rke2r1

**Prep work (up to 7 days prior to release day):**
- [x] EIO and QA team notified of the incoming releases - send calendar invite
- [x] PM and QA: Review changes and understand testing efforts
- [x] Menna: Prep PR for rancher/kontainer-driver-metadata (bump version(s)) [pr](https://github.com/rancher/kontainer-driver-metadata/pull/406)
- [x] Rancher2 team notified of the release (create rancher/rancher issue and put in milestone. They will need to update rancher2 Dockerfile, etc) https://github.com/rancher/rancher/issues/29825
- [x] PM Draft Releases (fill in release notes, mark as pre-release, fill in title, set target release branch, leave tag version blank, save as draft)
- [x] QA: Validate and close out all issues in the release milestone.

**Release work:**
- [x] PM: Merge PR for rancher/kontainer-driver-metadata into the dev branches
- [x] Chris: Tag and release any necessary RCs for QA to test KDM
- [x] Chris: Tag and release the patch(es) when have QA and PM approval

**Post-Release work:**
- [x] Chris: Uncheck "Pre-release" once drone is complete and all release artifacts are there
- [x] PM: Create an issue to mark the latest release as stable (this is done typically at least 7 days post release) https://github.com/rancher/rke2/issues/404
- ~Rancher PM: (handled separately) Merge in rancher/kontainter-driver-metadata change to release branch (so new patch versions show up as upgrade options in Rancher UI). _We plan to release KDM 11/13, Friday._~ Due to complications with K3s releases an emergency KDM release happened. You can expect to see RKE2 updated in KDM by 2.5.3 Rancher release.
- [x] PM: Close the milestone in GitHub.

**Comment by davidnuzik** [comment]
Moved to working state since the prep work is in flight.

**Comment by Oats87** [comment]
We are going to be releasing `v1.18.12+rke2r1` as the `v1.18.11` upstream K8s release was a dud.

**Comment by Oats87** [comment]
https://github.com/rancher/image-build-containerd/releases/tag/v1.3.7-k3s1 Containerd `v1.3.7-k3s1` is here
