### ISSUE TITLE
Error while running kubectl  while using install script method of installation.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#51]
Version:
Rke2 v0.0.1-alpha.4

Describe the issue:
1. kubectl errors with below message instead of command not found
rke2 kubectl get nodes --kubeconfig=/etc/rancher/rke2/rke2.yaml
WARN[0000] not running in CIS 1.5 mode                  
No help topic for 'kubectl'
```
2. After installing kubectl, default path of kubeconfig need to be passed explicitly.
```
kubectl get nodes --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAME               STATUS   ROLES         AGE    VERSION
ip-172-31-13-222   Ready    etcd,master   9m9s   v1.18.4
```

**Comment by briandowns** [comment]
The install script doesn't run that removal code. That code is part of an uninstall script that gets created. That code would look for a symlink and remove it if it exists when the user explicitly calls the rke2-uninstall.sh script.

**Comment by briandowns** [comment]
#52 resolves the primary issue here with `kubectl` execution. Since there's no wrapper in rke2 for other binaries like in k3s, the kubeconfig will need to be set as an env var or on the cli like you have above.

**Comment by ShylajaDevadiga** [comment]
Verified the fix. 
```
kubectl get nodes --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAME               STATUS   ROLES         AGE     VERSION
ip-172-31-13-22   Ready    etcd,master   2m28s   v1.18.4
```
