### ISSUE TITLE
Update docs to mention the need to run install as root

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#510]
RKE2 requires you run the install as root. Compared to K3s install.sh there is no "auto-escalation" with sudo.
Due to this, we should tweak the RKE2 docs to make it clear that installation commands need to be ran as root.

Further, what about running kubectl? Anything else?
We should ensure the docs are friendly and call out anywhere a sudo command (or otherwise running as root) is required.

**Comment by jossemargt-3pillar** [comment]
Addressed on #2434
