### ISSUE TITLE
Validate RHEL 9.3

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#5100]
**RKE2 Versions to be Validated**

v1.26.11+rke2r1
v1.27.8+rke2r1
v1.28.4+rke2r1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

config.yaml inclusions:
```
selinux: true
```

**Comment by aganesh-suse** [comment]
RHEL 9.3 testing. 

Verified tests: 

1.     Install and run sonobuoy conformance tests on a hardened cluster - 0.57.1 version used - PASS
2.     Validate SUC upgrade - PASS
3.     Install Rancher Manager - v2.8.0 used for testing.  - PASS
4.     Validate snapshot restore via cluster-reset-restore-path. PASS.

Versions tested: 
```
v1.26.11+rke2r1
v1.27.8+rke2r1
v1.28.4+rke2r1
```
