### ISSUE TITLE
Upgrading Cluster can leave rke2 SELinux Module unloaded

### ISSUE THREAD

**Issue by brownz11** [rancher/rke2#5128]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.26.10+rke2r2 (21e3a8c82da71473f2b846065dcab197a9b2c9d8)
go version go1.20.10 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
x64, RHEL 8
SELinux enforcing and enabled in the RKE2 config

Cluster Configuration:
3 MasterWorkers (Rancher local cluster)

**Describe the bug:**
During the install process the installer checks if a new version of rke2-selinux and container-selinux are available, if so it unloads the rke2 SELinux module. However, under certain circumstances while new versions are available, they may not be installed and the module stays unloaded (because the install is supposed to re-load it back in). This can cause issues similar to https://github.com/rancher/rke2-selinux/issues/58 where the filesystem starts to get mislabeled as new images are pulled, and eventually containerd will be unable to start containers (typically after a reboot)

**Steps To Reproduce:**
0) Add in the RKE2 yum repos
1) Install container-selinux-2:2.221.0-1.module+el8.9.0+19685+019f3589
2) Install rke2-selinux-0.14-1.el8
3) Install RKE2 v1.26.10+rke2r2 (via the get.rke2.io script, ie `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.10+rke2r2 sh -`)
4) Note that the installer unloaded the rke2 module, but didn't install a new version of rke2-selinux

A more in-depth reproduction is possible with version locking, but takes more work:
1) Simulate an "old" node in need of updates
1.1) Install yum version lock `yum install python3-dnf-plugin-versionlock`
1.2) version lock container-selinux and rke2-selinux
```
echo "rke2-selinux-0:0.14-1.el8.*" >> /etc/yum/pluginconf.d/versionlock.list
echo "container-selinux-2:2.221.0-1.module+el8.9.0+19685+019f3589.*" >> /etc/yum/pluginconf.d/versionlock.list   
```
1.3) install RKE2 v1.26.10+rke2r2 `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.10+rke2r2 sh -` remembering to populate config.yaml, add etcd user, etc
1.4) validate the node works (start rke2, query the api)
1.5) clear version locks
```
echo "" > /etc/yum/pluginconf.d/versionlock.list
```
2) upgrade to RKE2 v1.26.11+rke2r1 `curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.11+rke2r1 sh -`
2.1) Note that the installer unloaded the rke2 module, but didn't install a new version of rke2-selinux

**Expected behavior:**
The rke2 selinux module should be loaded after the script finishes.

**Actual behavior:**
The rke2 selinux module is not loaded after the script finishes.

**Work Around:**
Reinstall the rke2-selinux module, it'll rerun the module load up. If the file labels have been damaged though, probably need to follow  https://github.com/rancher/rke2-selinux/issues/58#issuecomment-1760000562

**Additional context / logs:**
I'm pretty certain this isn't specific to the RKE2 version, just any time there's a new rke2-selinux and container-selinux AND the rke2-common version doesn't depend on that newer rke2-selinux package (so it never gets re-installed/upgraded)

**Comment by brownz11** [comment]
Example run from an upgrade

```
# curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.11+rke2r1 sh -
[INFO]  using 1.26 series from channel stable
libsemanage.semanage_direct_remove_key: Removing last rke2 module (no other rke2 module exists at another priority).
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:39 ago on Mon 11 Dec 2023 01:33:55 PM CST.
Dependencies resolved.
=============================================================================================================================================================================================================================================
 Package                                              Architecture                                    Version                                                        Repository                                                         Size
=============================================================================================================================================================================================================================================
Upgrading:
 rke2-common                                          x86_64                                          1.26.11~rke2r1-0.el8                                           rancher-rke2-1.26-stable                                           20 M
 rke2-server                                          x86_64                                          1.26.11~rke2r1-0.el8                                           rancher-rke2-1.26-stable                                          8.8 k

Transaction Summary
=============================================================================================================================================================================================================================================
Upgrade  2 Packages

<...SNIP...>
```

You can see the semanage output of unloading the module, but no rke2-selinux upgrade/reinstall.

This is expected as rke2-common doesn't depend on a newer rke2-selinux
```
package: rke2-common-1.26.11~rke2r1-0.el8.x86_64
  dependency: /bin/sh
   provider: bash-4.4.20-4.el8_6.x86_64
  dependency: iptables
   provider: iptables-1.8.5-10.el8_9.i686
   provider: iptables-1.8.5-10.el8_9.x86_64
  dependency: rke2-selinux >= 0.12-0
   provider: rke2-selinux-0.17-1.el8.noarch
```

The get.rke2.io script does, however, identify the availability upgrades
```
# yum -q --refresh list rke2-selinux --upgrades | tail -n 1 | awk '{print $2}'
0.17-1.el8
# yum -q --refresh list container-selinux --upgrades | tail -n 1 | awk '{print $2}'
2:2.221.0-1.module+el8.9.0+20326+387084d0
```

And install "selinux" packages
```
# yum list installed | grep selinux
container-selinux.noarch                      2:2.221.0-1.module+el8.9.0+19685+019f3589   @rhel-8-for-x86_64-appstream-rpms
libselinux.x86_64                             2.9-8.el8                                   @rhel-8-for-x86_64-baseos-rpms
libselinux-utils.x86_64                       2.9-8.el8                                   @rhel-8-for-x86_64-baseos-rpms
python3-libselinux.x86_64                     2.9-8.el8                                   @rhel-8-for-x86_64-baseos-rpms
rke2-selinux.noarch                           0.14-1.el8                                  @rancher-rke2-common-stable
rpm-plugin-selinux.x86_64                     4.14.3-26.el8                               @rhel-8-for-x86_64-baseos-rpms
selinux-policy.noarch                         3.14.3-128.el8                              @rhel-8-for-x86_64-baseos-rpms
selinux-policy-targeted.noarch                3.14.3-128.el8                              @rhel-8-for-x86_64-baseos-rpms
```

**Comment by brownz11** [comment]
https://github.com/rancher/rke2/blob/71ac57d72319315c8c11c557b801f4cb604f6efe/install.sh#L564

Unloads the module.

Then rke2-selinux loads it as part of it's post install script.

https://github.com/rancher/rke2-selinux/blob/f6d5407dbe2dc45a71e2fbcd7d50514ea3f4621d/policy/centos8/rke2-selinux.spec#L65

**Comment by brandond** [comment]
Ah fair. I forgot we'd added that for EL9 in https://github.com/rancher/rke2/pull/4303.

That should only kick in if both container-selinux and rke2-selinux have upgrades available though, which is to specifically fix an issue where there were conflicts between container-selinux and rke2-selinux.

@galal-hussein do you have any thoughts on how to handle this better?

**Comment by brownz11** [comment]
The docs for upgrading RKE2 explicitly mention just rerunning the instal lscript.

https://docs.rke2.io/upgrade/manual_upgrade

**Comment by brandond** [comment]
I mean sure, you can, but you can also just use the package manager...

**Comment by brownz11** [comment]
I imagine even upgrading via my package manager I'll now get bit by the issue worked around in https://github.com/rancher/rke2/pull/4303 container-selinux may still try to update while the rke2 module is loaded

This is also still a potential issue across minor version updates, I haven't validated, but I don't see why it would fix it.

**Comment by brandond** [comment]
Yeah, we expect that the module will get reloaded by the upgrade of the two selinux packages. I'm curious why that's not happening. Perhaps we just need to add an explicit upgrade step, if we've unloaded the module expecting an upgrade.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ rke2 version v1.29.1-rc2+rke2r1 (a4986a5a5840f1a259e66c61553a9abd58ef9624)



```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"


*Cluster Configuration:*
1 server node 


 

 
## Steps to validate the fix
1. Create a lock version for rke2-selinux
2. Install an older version of container-selinux
3. Install rke2
4. Upgrade rke2
4. Validate rke2-selinux module is loaded after upgrade
 

 
 
## **Reproduction Issue:**
<details>

```
 
- Cant repro
```
 

 


## **Validation Results:**
<details>

```
$ yum install python3-dnf-plugin-versionlock

$ echo "rke2-selinux-0:0.14-1.el8.*" >> /etc/yum/pluginconf.d/versionlock.list
 
$ curl -O https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/container-selinux-2.219.0-1.module_el8+487+8e42a277.noarch.rpm
 
$ sudo dnf install container-selinux-2.219.0-1.module_el8+487+8e42a277.noarch.rpm

$ curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.26.10+rke2r2 sh -

$ curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.29.1-rc2+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -
 
$ rke2 -v
rke2 version v1.29.1-rc2+rke2r1 (a4986a5a5840f1a259e66c61553a9abd58ef9624)
go version go1.21.6 X:boringcrypto

$ rpm -q rke2-selinux
rke2-selinux-0.14-1.el8.noarch


]$ sudo semodule -l | grep rke2
rke2


 
$ rpm -q container-selinux
container-selinux-2.219.0-1.module_el8+487+8e42a277.noarch

$ yum -q --refresh list container-selinux --upgrades | tail -n 1 | awk '{print $2}'
2:2.221.0-1.module+el8.9.0+1580+e76741f0


$ sudo  yum list container-selinux --showduplicates
Last metadata expiration check: 0:45:48 ago on Mon 29 Jan 2024 05:28:50 PM EST.
Installed Packages
container-selinux.noarch                                                                                         2:2.219.0-1.module_el8+487+8e42a277                                                                                              @@commandline
Available Packages
container-selinux.noarch                                                                                         2:2.221.0-1.module+el8.9.0+1580+e76741f0   


```
