### ISSUE TITLE
Installer does not default to RPM for SLES

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/rke2#5132]
**Describe the bug:**
The installer does not default to RPMs with SLES, only with SLE Micro. For other RPM distros, the installer will default to RPM.

**Steps To Reproduce:**
Install RKE2 via

`curl -sfL https://get.rke2.io | sh -`

**Expected behavior:**
Add the repos to SLES as it does for SLE Micro

**Actual behavior:**
Tar ball install is used.

**Additional context / logs:**
```test-vm:~ # curl -sfL https://get.rke2.io | sh -
[INFO]  finding release for channel stable
[INFO]  using v1.26.11+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.26.11+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.26.11+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local

test-vm:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

**Comment by brandond** [comment]
As @Martin-Weiss said in https://github.com/rancher/rke2/issues/3386#issuecomment-1260416222:
>  this is still broken for SLES as the RPM for SLES requires selinux but we do not provide a supported selinux policy RPM for SLES as part of the RKE2 delivery via RPMs.

Until SLE provides selinux policies, we will not support RPM installs on SLE systems. IMO, the SLES claim to support selinux is disingenuous, as actually using it will void your support terms. SLES does not provide any policies, and does not support use of third party policies - so you can install it, but as soon as you configure any policies you are in an unsupported configuration.

See: https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-selinux.html
> SLES offers all binaries and libraries you need to use SELinux on your server.
> A policy is not included, and you must build your own. Third-party policies are not supported.

**Comment by abonillabeeche** [comment]
> SLES offers all binaries and libraries you need to use SELinux on your server.
> A policy is not included, and you must build your own. Third-party policies are not supported.

This means the 3rd party policy isn't supported, not that the entire system would fall out of support.

Why can't we install the RPM without using SELinux, since it is not enabled by default... ?

**Comment by brandond** [comment]
The rke2-common RPM depends on rke2-selinux, which in turn depends on container-selinux. We do not offer an RPM that does not have a selinux dependency.

**Comment by Martin-Weiss** [comment]
It still would be nice to deliver an RPM without the SElinux dependency for SLES..  (maybe it would be possible to change the forced dependenncy to an optinal dependency in the RPM with "suggests" or "recommends" insead of "requires")
