### ISSUE TITLE
 rke2-images-cilium.linux-amd64.* missing and Airgap Tarball is failing

### ISSUE THREAD

**Issue by eifelmicha** [rancher/rke2#5136]
**Environmental Info:**
RKE2 Version: v1.28.4+rke2r1

Node(s) CPU architecture, OS, and Version: Linux k8s-master-1 6.1.0-15-arm64 #1 SMP Debian 6.1.66-1 (2023-12-09) aarch64 GNU/Linux

Cluster Configuration: 3 Server with Cilium CNI

**Describe the bug:**
I would like to prefetch files in Packer to do an Tarball Installation of RKE2 and reduce startup times. According to: https://docs.rke2.io/install/airgap#tarball-method i have to download `rke2-images-core` and `rke2-images-cilium `, because of  `--cni=cilium`
However  rke2-images-cilium.linux-**amd64**.tar.zst  does exist, while  rke2-images-cilium.linux-**arm64**.tar.zst  does not.

**Steps To Reproduce:**
- Scripted Curl to download files, the `+` is escaped before:
```
ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then ARCH=arm64; fi
curl -OLs https://github.com/rancher/rke2/releases/download/$RKE2_VERSION/rke2-images-core.linux-$ARCH.tar.zst
curl -OLs https://github.com/rancher/rke2/releases/download/$RKE2_VERSION/rke2-images-cilium.linux-$ARCH.tar.zst
curl -OLs https://github.com/rancher/rke2/releases/download/$RKE2_VERSION/sha256sum-$ARCH.txt
```

**Expected behavior:**
Successful download

**Actual behavior:**
`CHECKSUM_CILIUM_EXPECTED=$(grep "rke2-images-cilium.linux-$ARCH.tar.zst" "sha256sum-$ARCH.txt" | awk '{print $1}');` failed, because no file and checksum is present.

**Additional context / logs:**

- https://docs.rke2.io/install/airgap#tarball-method

**Comment by brandond** [comment]
I believe that up until recently, some or all of the cilium images did not support arm64, so we disabled packaging it for that architecture.

https://github.com/rancher/rke2/blob/c1494f5de1d2f6ae26cbb7d8ec365344dc1209d8/scripts/build-images#L36-L37

@manuelbuil @thomasferrandiz can we revisit this, and see if we can package cilium airgap images for arm64?

**Comment by brandond** [comment]
Also related: https://github.com/rancher/rke2/issues/5135#issuecomment-1855389188

**Comment by mgfritch** [comment]
> I believe that up until recently, some or all of the cilium images did not support arm64, so we disabled packaging it for that architecture.

I removed the `cilium-etcd-operator` since it still has no arm64 builds, but that makes sense it was marked as deprecated in 2020 and the github repo was finally archived last year...

**Comment by manuelbuil** [comment]
> > I believe that up until recently, some or all of the cilium images did not support arm64, so we disabled packaging it for that architecture.
> 
> I removed the `cilium-etcd-operator` since it still has no arm64 builds, but that makes sense since it was marked as deprecated in 2020 and the github repo was finally archived last year...

Thanks Mike! You should change the status of the issue to working and set the milestone to the next release :)
