### ISSUE TITLE
in offline installed cluster, nslookup failed to resolve k8s service inside the same namespace.

### ISSUE THREAD

**Issue by sonicning** [rancher/rke2#5137]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.28.3+rke2r2 (cf6c1ae3f199c2e838ba19125cbd2d522c8765d3)
go version go1.20.10 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux master01 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

 single server 10.1.1.123 in a total offline network without routers, just switch
 
```
[root@offline-cluster ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="static"
DEFROUTE="yes"
IPADDR=10.1.1.123
NETMASK=255.255.255.0
GATEWAY=10.1.1.123   ###used itself as gateway, using iptables
###DNS1=10.112.32.70
IPV4_FAILURE_FATAL="no"
###IPV6INIT="yes"
###IPV6_AUTOCONF="yes"
###IPV6_DEFROUTE="yes"
###IPV6_FAILURE_FATAL="no"
###IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="eth0"
UUID="UUIDXXXXXX"
DEVICE="eth0"
ONBOOT="yes"
```
```
[root@offline-server ~]# ip route
default via 10.1.1.123 dev eth0 proto static metric 100
10.1.1.0/24 dev eth0 proto kernel scope link src 10.1.1.123 metric 100
```

**Describe the bug:**

![bad_cluster_first_installed](https://github.com/rancher/rke2/assets/6220120/f9c2cb06-d535-4cd4-9c8b-100d26e8d538)
the error above was solved by adding `nameserver 10.1.1.123` in /etc/resolv.conf on the single node 10.1.1.123
![bad_cluster_main_error1](https://github.com/rancher/rke2/assets/6220120/a846c9d5-33e5-4bd8-9824-e7ca9b98d01e)
![bad_cluster_nslookup](https://github.com/rancher/rke2/assets/6220120/8435d062-29bf-482a-996a-7d15cd2bb297)

**Steps To Reproduce:**

- Installed RKE2: 
```
systemctl stop firewalld; systemctl disable firewalld;
systemctl stop dnsmasq; systemctl disable dnsmasq;
systemctl stop ntpd; systemctl disable ntpd;
systemctl stop postfix; systemctl disable postfix;
iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat && iptables -P FORWARD ACCEPT;
swapoff -a; sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab;
setenforce 0; sed -i '/SELINUX/s/enforcing/disabled/' /etc/selinux/config;

cd  /data/rke2-artifacts/ && INSTALL_RKE2_ARTIFACT_PATH=/data/rke2-artifacts sh  install.sh

systemctl enable rke2-server.service
systemctl start rke2-server.service
```

1. I have installed a good single node rke2-server with exactly the same offline installation steps, the only diffrence would be the working default gateway and dns in the network
2. links I checked https://github.com/kubernetes/kubernetes/issues/66924
3. links I checked https://github.com/coredns/coredns/issues/2026
4. links I checked https://docs.rke2.io/zh/known_issues

**Expected behavior:**

in a good single node cluster with good network 
![good_cluster_nslookup_2023-12-14_21-13-16](https://github.com/rancher/rke2/assets/6220120/cc6fb33b-6530-415d-89e9-ff73cdf69a8e)

**Actual behavior:**

![bad_cluster_nslookup](https://github.com/rancher/rke2/assets/6220120/0545db53-e42f-4d73-a3c3-6455e5cb576b)

**Additional context / logs:**

bad_cluster_canal_logs
![bad_cluster_canal_logs](https://github.com/rancher/rke2/assets/6220120/5e1179e9-fa34-443f-97ed-f183fed21525)
bad_cluster_coredns_logs
![bad_cluster_coredns_logs](https://github.com/rancher/rke2/assets/6220120/b12bbde3-bddd-4b55-b71f-5b9123dbb936)
bad_cluster_corefile
![bad_cluster_corefile](https://github.com/rancher/rke2/assets/6220120/51cbf332-f7a5-4b2d-aef0-f188d9774924)
bad_cluster_ip_forward
![bad_cluster_ip_forward](https://github.com/rancher/rke2/assets/6220120/57f93261-28bf-4549-8d91-d4e410528a5d)
bad_cluster_kubeproxy_logs
![bad_cluster_kubeproxy_logs](https://github.com/rancher/rke2/assets/6220120/6e02a83d-70e9-4c7e-a5fb-dbc0e6c79b69)
bad_cluster_resolv
![bad_cluster_resolv](https://github.com/rancher/rke2/assets/6220120/670e012a-9ef7-4286-a8b0-87e1a5a6968c)

**Comment by brandond** [comment]
coredns will not function without an upstream resolver. You do need to provide an upstream host in resolv.conf on the node, even if it does not exist and will timeout - or better yet is just a stub that responds with NXDOMAIN to all requests.

**Comment by sonicning** [comment]
Thanks, I configured bind-chroot on the host server and used it as nameserver in the cluster.

BTW, it is highly suggested to use `ipvs` instead of `iptables`, I came through a lot of network issues in this offline cluster with out hardware routers using default configurations of iptables.
I upgraded the kernel and added the following in the `/etc/rancher/rke2/config.yaml` config file
```
kube-proxy-arg:
- "proxy-mode=ipvs"
```
it all works now
