### ISSUE TITLE
We do not have our own CIS-type benchmark for RKE2 specific files

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#514]
In our [CIS self-assessment Guide](https://github.com/rancher/rke2/blob/master/docs/security/cis_self_assessment.md) we declare what we Pass and don't pass for the Kubernetes CIS Benchmark. However, we do not have our own benchmark addressing rke2 specific files. This is something we should care about, especially for the `rke2-server.service` and `rke2-agent.service` files which are in charge of the rke2 supervisor processes that control kubelet among other things. 

These files should have ownership of `root:root` and permissions that are `644` or more restrictive.

**Comment by cjellick** [comment]
I'm pushing this out a bit. Even though the initial dev work is done, I don't want this landing in QA's queue as it is non-critical

**Comment by caroline-suse-rancher** [comment]
Closing as this is resolved; will open new issues for CIS-related tickets
