### ISSUE TITLE
Not able to modify API server Static POD

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#5142]
I am setting DEX (OIDC), Oauth2Proxy, Kubernetes Dashboard with RKE2 (v1.26)

As part of above setup I have to add following lines in ```/var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml``` file.

```
    - --oidc-issuer-url=https://auth.<LB>.nip.io/
    - --oidc-client-id=oidc-auth-client
    - --oidc-ca-file=/var/lib/rancher/rke2/server/tls/dex-ca.crt
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
```

But after modify **kube-apiserver.yaml** file, seems its revert back.

Please suggest how can I achieve this, do I need to modify any other file ?

Just same things are working with my kubeadm setup :)

**Comment by brandond** [comment]
Don't do that. The static pod manifest is managed by RKE2. If you need to append arguments to the apiserver, use the `kube-apiserver-arg` value in your config.yaml.

**Comment by cloudcafetech** [comment]
Thanks @brandond , will check 👍

**Comment by heroes1412** [comment]
> Don't do that. The static pod manifest is managed by RKE2. If you need to append arguments to the apiserver, use the `kube-apiserver-arg` value in your config.yaml.
> 
> ```yaml
> token: my-token
> kube-apiserver-arg:
>   - --arg1=foo
>   - --arg2=bar
> ```

after appending args to config.yaml, what next bro? restart all control panel nodes?

**Comment by brandond** [comment]
yes?

**Comment by heroes1412** [comment]
i just try to append this to config.yaml

kube-apiserver-arg:
- --service-node-port-range="80-32767"

so /etc/rancher/rke2/config.yaml looks like:
`cni:
- calico
disable:
- rke2-ingress-nginx
- rke2-snapshot-validation-webhook
- rke2-snapshot-controller
- rke2-snapshot-controller-crd
node-taint:
- node-role.kubernetes.io/control-plane=true:NoSchedule
kube-apiserver-arg:
- --service-node-port-range="80-32767"`


and then: systemctl restart rke2-server.service
kube-apiserver wont start :)

**Comment by brandond** [comment]
try just
```yaml
 kube-apiserver-arg:
 - service-node-port-range=80-32767
```
