### ISSUE TITLE
Update cilium to 1.14.500

### ISSUE THREAD

**Issue by mgfritch** [rancher/rke2#5155]

**Comment by caroline-suse-rancher** [comment]
Hey @mgfritch are you actively working on this?

**Comment by drustan** [comment]
Hey, just a heads-up. I ran into a super annoying bug in version 1.14.400 : https://github.com/cilium/cilium/issues/29238. Can't wait for 1.14.500 or 1.14.600 to roll out and hopefully fix this!

**Comment by mgfritch** [comment]
closed in favor of https://github.com/rancher/rke2/issues/5354
