### ISSUE TITLE
set http_proxy for containerd to pull images

### ISSUE THREAD

**Issue by kingyzf** [rancher/rke2#517]
I need set http_proxy for containerd to pull images, I set http_proxy and no_proxy envirenment variable to rke2 server, but there's side effect , some other process use the proxy too.I just wan't set proxy for  containerd

**Comment by kennychen101** [comment]
We are behind corp proxy, and I have no luck so far to configure containerd to pull images from the internet. Does containerd support http_proxy at all?

**Comment by kingyzf** [comment]
> We are behind corp proxy, and I have no luck so far to configure containerd to pull images from the internet. Does containerd support http_proxy at all?

yes, by setting http_proxy env for containerd systemd service (if you use standalone containerd),but in rke2 , containerd is started by rke2 ,if I set env for rke2, all processes will use the env

**Comment by nemethk** [comment]
Check:
`cat /usr/lib/systemd/system/rke2-server.service`

```
[Unit]
Description=Rancher Kubernetes Engine v2 (server)
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target
Conflicts=rke2-agent.service

[Install]
WantedBy=multi-user.target

[Service]
EnvironmentFile=-/etc/default/rke2-server
EnvironmentFile=-/etc/sysconfig/rke2-server
EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/bin/rke2 server
```

Under 'service' there is
`EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env`

Create this file
`/usr/lib/systemd/system/rke2-server.env`

with following content:
```
HTTP_PROXY=http://ip:port
HTTPS_PROXY=http://ip:port
NO_PROXY=localhost,127.0.0.1
```

**Comment by kingyzf** [comment]
> Check:
> `cat /usr/lib/systemd/system/rke2-server.service`
> 
> ```
> [Unit]
> Description=Rancher Kubernetes Engine v2 (server)
> Documentation=https://github.com/rancher/rke2#readme
> Wants=network-online.target
> After=network-online.target
> Conflicts=rke2-agent.service
> 
> [Install]
> WantedBy=multi-user.target
> 
> [Service]
> EnvironmentFile=-/etc/default/rke2-server
> EnvironmentFile=-/etc/sysconfig/rke2-server
> EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env
> KillMode=process
> Delegate=yes
> LimitNOFILE=1048576
> LimitNPROC=infinity
> LimitCORE=infinity
> TasksMax=infinity
> TimeoutStartSec=0
> Restart=always
> RestartSec=5s
> ExecStartPre=-/sbin/modprobe br_netfilter
> ExecStartPre=-/sbin/modprobe overlay
> ExecStart=/usr/bin/rke2 server
> ```
> 
> Under 'service' there is
> `EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env`
> 
> Create this file
> `/usr/lib/systemd/system/rke2-server.env`
> 
> with following content:
> 
> ```
> HTTP_PROXY=http://ip:port
> HTTPS_PROXY=http://ip:port
> NO_PROXY=localhost,127.0.0.1
> ```

I only want to set HTTP_PROXY for containerd，not for rke2.because  when I set to rke2 , it has side effects

**Comment by nemethk** [comment]
> > Check:
> > `cat /usr/lib/systemd/system/rke2-server.service`
> > ```
> > [Unit]
> > Description=Rancher Kubernetes Engine v2 (server)
> > Documentation=https://github.com/rancher/rke2#readme
> > Wants=network-online.target
> > After=network-online.target
> > Conflicts=rke2-agent.service
> > 
> > [Install]
> > WantedBy=multi-user.target
> > 
> > [Service]
> > EnvironmentFile=-/etc/default/rke2-server
> > EnvironmentFile=-/etc/sysconfig/rke2-server
> > EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env
> > KillMode=process
> > Delegate=yes
> > LimitNOFILE=1048576
> > LimitNPROC=infinity
> > LimitCORE=infinity
> > TasksMax=infinity
> > TimeoutStartSec=0
> > Restart=always
> > RestartSec=5s
> > ExecStartPre=-/sbin/modprobe br_netfilter
> > ExecStartPre=-/sbin/modprobe overlay
> > ExecStart=/usr/bin/rke2 server
> > ```
> > 
> > 
> > Under 'service' there is
> > `EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env`
> > Create this file
> > `/usr/lib/systemd/system/rke2-server.env`
> > with following content:
> > ```
> > HTTP_PROXY=http://ip:port
> > HTTPS_PROXY=http://ip:port
> > NO_PROXY=localhost,127.0.0.1
> > ```
> 
> I only want to set HTTP_PROXY for containerd，not for rke2.because when I set to rke2 , it has side effects

Maybe this note could help: https://github.com/containerd/containerd/issues/1990#issuecomment-403414959

**Comment by kingyzf** [comment]
> > > Check:
> > > `cat /usr/lib/systemd/system/rke2-server.service`
> > > ```
> > > [Unit]
> > > Description=Rancher Kubernetes Engine v2 (server)
> > > Documentation=https://github.com/rancher/rke2#readme
> > > Wants=network-online.target
> > > After=network-online.target
> > > Conflicts=rke2-agent.service
> > > 
> > > [Install]
> > > WantedBy=multi-user.target
> > > 
> > > [Service]
> > > EnvironmentFile=-/etc/default/rke2-server
> > > EnvironmentFile=-/etc/sysconfig/rke2-server
> > > EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env
> > > KillMode=process
> > > Delegate=yes
> > > LimitNOFILE=1048576
> > > LimitNPROC=infinity
> > > LimitCORE=infinity
> > > TasksMax=infinity
> > > TimeoutStartSec=0
> > > Restart=always
> > > RestartSec=5s
> > > ExecStartPre=-/sbin/modprobe br_netfilter
> > > ExecStartPre=-/sbin/modprobe overlay
> > > ExecStart=/usr/bin/rke2 server
> > > ```
> > > 
> > > 
> > > Under 'service' there is
> > > `EnvironmentFile=-/usr/lib/systemd/system/rke2-server.env`
> > > Create this file
> > > `/usr/lib/systemd/system/rke2-server.env`
> > > with following content:
> > > ```
> > > HTTP_PROXY=http://ip:port
> > > HTTPS_PROXY=http://ip:port
> > > NO_PROXY=localhost,127.0.0.1
> > > ```
> > 
> > 
> > I only want to set HTTP_PROXY for containerd，not for rke2.because when I set to rke2 , it has side effects
> 
> Maybe this note could help: [containerd/containerd#1990 (comment)](https://github.com/containerd/containerd/issues/1990#issuecomment-403414959)

thanks,but that containerd is an standalone service,in rke2 it's not ;
of course,I can use a standalone containerd, I just wonder if rke2 can support setting HTTP_PROXY for packaged containerd

**Comment by brandond** [comment]
> thanks,but that containerd is an standalone service,in rke2 it's not ;
> of course,I can use a standalone containerd, I just wonder if rke2 can support setting HTTP_PROXY for packaged containerd

I had a PR floating around at one point that allowed for doing that, but I think it ended up not being needed. Would you consider opening an issue for this feature?

**Comment by bingo4933** [comment]
hello @nemethk
thanks for your help, however my `rke2-server.service` looks like difference to your comment which is 
```
# cat /usr/lib/systemd/system/rke2-server.service
[Unit]
Description=Rancher Kubernetes Engine v2 (server)
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target
Conflicts=rke2-agent.service

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/usr/lib/systemd/system/%N.env
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/bin/rke2 server
ExecStopPost=-/bin/sh -c "systemd-cgls /system.slice/%n | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill"
```

it shows `/usr/lib/systemd/system/%N.env` 
what's the `%N` mean?

what file name should I create?

**Comment by brandond** [comment]
%N is expanded to the unit name, rke2-server or rke2-agent.

**Comment by bingo4933** [comment]
so, in my case, I need to create file at location `/usr/lib/systemd/system/rke2-server.env`

is this correct?

**Comment by brandond** [comment]
That is one of the three options, yes.

**Comment by bingo4933** [comment]
brandond,
it worked, thanks a lot for help.
