### ISSUE TITLE
Server certificate not being generated with hostname (Was: Quickstart Documentation (rke2-agent install) not working)

### ISSUE THREAD

**Issue by jagipson** [rancher/rke2#518]
Starting with a minimal CentOS 8.2 install, I followed the Quick Start Instructions.
My server is named "blueberry". After running the _Server Node Installation_ section on blueberry, I get this on blueberry which tells me the server node is working:

> [root@blueberry server]# cat ~/kubectlgetpodsserver 
> NAMESPACE     NAME                                                  READY   STATUS      RESTARTS   AGE
> kube-system   etcd-blueberry                                        1/1     Running     5          3h16m
> kube-system   helm-install-rke2-canal-p8rs5                         0/1     Completed   0          3h16m
> kube-system   helm-install-rke2-coredns-mskzh                       0/1     Completed   0          3h16m
> kube-system   helm-install-rke2-ingress-nginx-kgg5x                 0/1     Completed   0          3h16m
> kube-system   helm-install-rke2-kube-proxy-5fwhx                    0/1     Completed   0          3h16m
> kube-system   helm-install-rke2-metrics-server-djwz8                0/1     Completed   0          3h16m
> kube-system   kube-apiserver-blueberry                              1/1     Running     4          3h15m
> kube-system   kube-controller-manager-blueberry                     1/1     Running     3          3h16m
> kube-system   kube-proxy-565rx                                      1/1     Running     3          3h15m
> kube-system   kube-scheduler-blueberry                              1/1     Running     3          3h16m
> kube-system   rke2-canal-48gkg                                      2/2     Running     6          3h15m
> kube-system   rke2-coredns-rke2-coredns-649896d599-rbhfz            1/1     Running     3          3h15m
> kube-system   rke2-ingress-nginx-controller-d4989f458-vcmnj         1/1     Running     5          3h15m
> kube-system   rke2-ingress-nginx-default-backend-65f75d6664-nl7r4   1/1     Running     3          3h15m
> kube-system   rke2-metrics-server-5d8c549c9f-qj7gt                  1/1     Running     3          3h15m

When I run the _Agent (Worker) Node Installation_ on my agent (named pear), everything appears to be fine until I run `journalctl -u rke2-agent -f`, which appears to be doing things up until I see repeating lines like this:

> Nov 04 15:56:17 pear systemd[1]: Starting Rancher Kubernetes Engine v2 (agent)...
> Nov 04 15:56:17 pear systemd[1]: Started Rancher Kubernetes Engine v2 (agent).
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=warning msg="not running in CIS > 1.5 mode"
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Runtime image \\"index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1\" bin dir already exists at \"/var/lib/rancher/rke2/data/v1.18.10-rke2r1-05727ee6de6c/bin\"; skipping extract"

> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Starting rke2 agent v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5)"
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Module overlay was already loaded"
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Module nf_conntrack was already loaded"
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Module br_netfilter was already loaded"
> Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Running load balancer 127.0.0.1:42005 -> [blueberry:9345]"
> Nov 04 15:56:38 pear rke2[1754]: time="2020-11-04T15:56:38-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:42005/cacerts: read tcp 127.0.0.1:59946->127.0.0.1:42005: read: connection reset by peer"
> Nov 04 15:57:00 pear rke2[1754]: time="2020-11-04T15:57:00-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:42005/cacerts: read tcp 127.0.0.1:59950->127.0.0.1:42005: read: connection reset by peer"
> Nov 04 15:57:22 pear rke2[1754]: time="2020-11-04T15:57:22-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:42005/cacerts: read tcp 127.0.0.1:59954->127.0.0.1:42005: read: connection reset by peer"
> Nov 04 15:57:44 pear rke2[1754]: time="2020-11-04T15:57:44-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:42005/cacerts: read tcp 127.0.0.1:59958->127.0.0.1:42005: read: connection reset by peer"
> Nov 04 15:58:06 pear rke2[1754]: time="2020-11-04T15:58:06-05:00" level=error msg="CA cert validation failed: Get https://127.0.0.1:42005/cacerts: read tcp 127.0.0.1:59966->127.0.0.1:42005: read: connection reset by peer"

This goes on indefinitely.
Testing I run curl:

> [root@pear ~]# curl https://127.0.0.1:42005/cacerts
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

And once again with insecure option

> [root@pear ~]# curl --insecure https://127.0.0.1:42005/cacerts
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:42005 

The agent node does not appear to be initializing.  Any help would be greatly appreciated.

**Comment by jagipson** [comment]
It does eventually work with insecure:

> [root@pear ~]# curl --insecure https://127.0.0.1:42005/cacerts
> -----BEGIN CERTIFICATE-----
> MIIBWjCCAQCgAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
> ......
> NjRfz6WggIK2Cae54Xw=
> -----END CERTIFICATE----

-

**Comment by briandowns** [comment]
Did you have a previous installation on `pear`? It looks like the bin dir and certs might already exist for a previous installation.

**Comment by jagipson** [comment]
Thank you for your reply.

I had started the rke2-agent.service and then stopped it and ran  rke2 agent --debug for clues (there were none) and then restarted rke2-agent.service to generate logs.

I do have another machine (strawberry) which has not had anything installed on, and I can use it and record transcripts, if that helps.  Before I do, are there any commands to run/information to gather? And when I do, is there anything special outside of the instructions for the agent install that I should do along the way?

**Comment by briandowns** [comment]
On the new node, just make sure that `/var/lib/rancher` hasn't been created yet. That way we can know that the installation is succeeding and we should have a clean startup, as well as not see messages like:

```
Nov 04 15:56:18 pear rke2[1754]: time="2020-11-04T15:56:18-05:00" level=info msg="Runtime image \"index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" bin dir already exists at "/var/lib/rancher/rke2/data/v1.18.10-rke2r1-05727ee6de6c/bin"; skipping extract"
```

**Comment by jagipson** [comment]
Last login: Wed Nov  4 12:11:24 2020 from 192.168.122.1

> [root@strawberry ~]# systemctl disable --now firewalld
> Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
> Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
> [root@strawberry ~]# setenforce 0
> [root@strawberry ~]# stat /var/lib/rancher
> stat: cannot stat '/var/lib/rancher': No such file or directory
> curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

> Rancher RKE2 Common (latest)                    1.4 kB/s | 1.0 kB     00:00    
> Rancher RKE2 1.18 (latest)                      2.7 kB/s | 2.0 kB     00:00    
> Dependencies resolved.
> ================================================================================
>  Package       Arch    Version                Repository                   Size
> ================================================================================
> Installing:
>  rke2-agent    x86_64  1.18.10~rke2r1-0.el8   rancher-rke2-1-18-latest    8.7 k
> Installing dependencies:
>  rke2-common   x86_64  1.18.10~rke2r1-0.el8   rancher-rke2-1-18-latest     33 M
>  rke2-selinux  noarch  0.3-1.el7_8            rancher-rke2-common-latest   15 k
> 
> Transaction Summary
> ================================================================================
> Install  3 Packages
> 
> Total download size: 33 M
> Installed size: 153 M
> Downloading Packages:
> (1/3): rke2-agent-1.18.10~rke2r1-0.el8.x86_64.r  24 kB/s | 8.7 kB     00:00    
> (2/3): rke2-selinux-0.3-1.el7_8.noarch.rpm       39 kB/s |  15 kB     00:00    
> (3/3): rke2-common-1.18.10~rke2r1-0.el8.x86_64. 7.7 MB/s |  33 MB     00:04    
> --------------------------------------------------------------------------------
> Total                                           7.7 MB/s |  33 MB     00:04     
> warning: /var/cache/dnf/rancher-rke2-common-latest-f14facca04d2cc0e/packages/rke2-selinux-0.3-1.el7_8.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID e257814a: NOKEY
> Rancher RKE2 Common (latest)                    7.3 kB/s | 2.4 kB     00:00    
> Importing GPG key 0xE257814A:
>  Userid     : "Rancher (CI) <ci@rancher.com>"
>  Fingerprint: C8CF F216 4551 26E9 B9C9 18BE 925E A29A E257 814A
>  From       : https://rpm.rancher.io/public.key
> Key imported successfully
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                        1/1 
>   Installing       : rke2-selinux-0.3-1.el7_8.noarch                        1/3 
>   Running scriptlet: rke2-selinux-0.3-1.el7_8.noarch                        1/3 
>   Installing       : rke2-common-1.18.10~rke2r1-0.el8.x86_64                2/3 
>   Installing       : rke2-agent-1.18.10~rke2r1-0.el8.x86_64                 3/3 
>   Running scriptlet: rke2-agent-1.18.10~rke2r1-0.el8.x86_64                 3/3 
>   Verifying        : rke2-selinux-0.3-1.el7_8.noarch                        1/3 
>   Verifying        : rke2-agent-1.18.10~rke2r1-0.el8.x86_64                 2/3 
>   Verifying        : rke2-common-1.18.10~rke2r1-0.el8.x86_64                3/3 
> Installed products updated.
> 
> Installed:
>   rke2-agent-1.18.10~rke2r1-0.el8.x86_64                                        
>   rke2-common-1.18.10~rke2r1-0.el8.x86_64                                       
>   rke2-selinux-0.3-1.el7_8.noarch                                               
> 
> Complete!
> [root@strawberry ~]# systemctl enable rke2-agent.service
> Created symlink /etc/systemd/system/multi-user.target.wants/rke2-agent.service → /usr/lib/systemd/system/rke2-agent.service.

> [root@strawberry ~]# mkdir -p /etc/rancher/rke2/
> [root@strawberry ~]# vim /etc/rancher/rke2/config.yaml
File created:

> [root@strawberry ~]# cat /etc/rancher/rke2/config.yaml 
> server: https://blueberry:9345
> token: K10381ff581cf6c.....e828305d18e98e4d::server:48b86e5b73.....359835
> [root@strawberry ~]# systemctl start rke2-agent.service
> [root@strawberry ~]# journalctl -u rke2-agent -f

[root@strawberry ~]# journalctl -u rke2-agent -f

> -- Logs begin at Wed 2020-11-04 12:11:10 EST. --
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Updated HelmChart \"/var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml\" to apply --system-default-registry modifications"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Updated HelmChart \"/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml\" to apply --system-default-registry modifications"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Updated HelmChart \"/var/lib/rancher/rke2/server/manifests/rke2-kube-proxy.yaml\" to apply --system-default-registry modifications"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Updated HelmChart \"/var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml\" to apply --system-default-registry modifications"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Starting rke2 agent v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5)"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Module overlay was already loaded"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Module nf_conntrack was already loaded"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Module br_netfilter was already loaded"
> Nov 04 16:31:35 strawberry rke2[1708]: time="2020-11-04T16:31:35-05:00" level=info msg="Running load balancer 127.0.0.1:38803 -> [blueberry:9345]"
> Nov 04 16:31:55 strawberry rke2[1708]: time="2020-11-04T16:31:55-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34122->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:32:17 strawberry rke2[1708]: time="2020-11-04T16:32:17-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34126->127.0.0.1:38803: read: connection reset by peer"

> Nov 04 16:32:39 strawberry rke2[1708]: time="2020-11-04T16:32:39-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34130->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:33:01 strawberry rke2[1708]: time="2020-11-04T16:33:01-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34134->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:33:23 strawberry rke2[1708]: time="2020-11-04T16:33:23-05:00" level=error msg="failed to get CA certs: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34138->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:33:45 strawberry rke2[1708]: time="2020-11-04T16:33:45-05:00" level=error msg="CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34146->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:34:07 strawberry rke2[1708]: time="2020-11-04T16:34:07-05:00" level=error msg="CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34150->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:34:39 strawberry rke2[1708]: time="2020-11-04T16:34:39-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34160->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:35:04 strawberry rke2[1708]: time="2020-11-04T16:35:04-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34164->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:35:29 strawberry rke2[1708]: time="2020-11-04T16:35:29-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34168->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:35:54 strawberry rke2[1708]: time="2020-11-04T16:35:54-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34172->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:36:19 strawberry rke2[1708]: time="2020-11-04T16:36:19-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34176->127.0.0.1:38803: read: connection reset by peer"
> Nov 04 16:36:44 strawberry rke2[1708]: time="2020-11-04T16:36:44-05:00" level=error msg="Failed to retrieve agent config: CA cert validation failed: Get https://127.0.0.1:38803/cacerts: read tcp 127.0.0.1:34180->127.0.0.1:38803: read: connection reset by peer"
>

**Comment by jagipson** [comment]
Additionally, after deleting the /var/ items, and retrying on strawberry:
```
[root@strawberry log]# /usr/bin/rke2 agent --debug --config /etc/rancher/rke2/config.yaml --selinux 
WARN[0000] not running in CIS 1.5 mode                  
DEBU[0000] No local image available for "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1": dir "/var/lib/rancher/rke2/agent/images" does not exist 
INFO[0000] Pulling runtime image "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" 
2020-11-05 08:57:58.848552 I | Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2020-11-05 08:57:58.848635 I | No matching credentials were found, falling back on anonymous
INFO[0001] Extracting "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" "/bin/" to "/var/lib/rancher/rke2/data/v1.18.10-rke2r1-05727ee6de6c/bin" 
INFO[0001] Extracting file "bin/kubectl"                
INFO[0003] Extracting file "bin/kubelet"                
INFO[0006] Extracting file "bin/containerd"             
INFO[0008] Extracting file "bin/containerd-shim"        
INFO[0008] Extracting file "bin/containerd-shim-runc-v1" 
INFO[0008] Extracting file "bin/containerd-shim-runc-v2" 
INFO[0009] Extracting file "bin/ctr"                    
INFO[0009] Extracting file "bin/crictl"                 
INFO[0010] Extracting file "bin/runc"                   
INFO[0011] Extracting file "bin/socat"                  
INFO[0011] Done extracting "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" 
INFO[0011] Extracting "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" "/charts/" to "/var/lib/rancher/rke2/server/manifests" 
INFO[0011] Extracting file "charts/rke2-canal.yaml"     
INFO[0011] Extracting file "charts/rke2-coredns.yaml"   
INFO[0011] Extracting file "charts/rke2-ingress-nginx.yaml" 
INFO[0011] Extracting file "charts/rke2-kube-proxy.yaml" 
INFO[0011] Extracting file "charts/rke2-metrics-server.yaml" 
INFO[0020] Done extracting "index.docker.io/rancher/rke2-runtime:v1.18.10-rke2r1" 
INFO[0020] Updated HelmChart "/var/lib/rancher/rke2/server/manifests/rke2-canal.yaml" to apply --system-default-registry modifications 
DEBU[0052] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0052] Incoming conn 127.0.0.1:48430, error dialing load balancer servers: context deadline exceeded 
DEBU[0062] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0062] Incoming conn 127.0.0.1:48432, error dialing load balancer servers: context deadline exceeded 
ERRO[0062] failed to get CA certs: Get https://127.0.0.1:41127/cacerts: read tcp 127.0.0.1:48432->127.0.0.1:41127: read: connection reset by peer 
DEBU[0074] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0074] Incoming conn 127.0.0.1:48434, error dialing load balancer servers: context deadline exceeded 
DEBU[0084] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0084] Incoming conn 127.0.0.1:48436, error dialing load balancer servers: context deadline exceeded 
ERRO[0084] failed to get CA certs: Get https://127.0.0.1:41127/cacerts: read tcp 127.0.0.1:48436->127.0.0.1:41127: read: connection reset by peer 
DEBU[0096] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0096] Incoming conn 127.0.0.1:48438, error dialing load balancer servers: context deadline exceeded 
DEBU[0106] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0106] Incoming conn 127.0.0.1:48440, error dialing load balancer servers: context deadline exceeded 
ERRO[0106] failed to get CA certs: Get https://127.0.0.1:41127/cacerts: read tcp 127.0.0.1:48440->127.0.0.1:41127: read: connection reset by peer 
DEBU[0118] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0118] Incoming conn 127.0.0.1:48442, error dialing load balancer servers: context deadline exceeded 
```
And repeats thus.
INFO[0020] Updated HelmChart "/var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml" to apply --system-default-registry modifications 
INFO[0020] Updated HelmChart "/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml" to apply --system-default-registry modifications 
INFO[0020] Updated HelmChart "/var/lib/rancher/rke2/server/manifests/rke2-kube-proxy.yaml" to apply --system-default-registry modifications 
INFO[0020] Updated HelmChart "/var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml" to apply --system-default-registry modifications 
INFO[0020] Starting rke2 agent v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5) 
INFO[0020] Module overlay was already loaded            
INFO[0020] Module nf_conntrack was already loaded       
INFO[0020] Module br_netfilter was already loaded       
INFO[0020] Running load balancer 127.0.0.1:41127 -> [blueberry:9345] 
DEBU[0030] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0030] Incoming conn 127.0.0.1:48426, error dialing load balancer servers: context deadline exceeded 
DEBU[0040] Dial error from load balancer: dial tcp: i/o timeout 
DEBU[0040] Incoming conn 127.0.0.1:48428, error dialing load balancer servers: context deadline exceeded 
ERRO[0040] failed to get CA certs: Get https://127.0.0.1:41127/cacerts: read tcp 127.0.0.1:48428->127.0.0.1:41127: read: connection reset by peer

**Comment by jagipson** [comment]
### PROGRESS:
I think a possibility is that the certificate on the control-plane node does *not* have the hostname "blueberry" in the certificate and this (might?) be the problem?

Over on blueberry...
```
[root@blueberry tls]# kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml get secret -o yaml rke2-serving -n kube-system 
apiVersion: v1
data:
  tls.crt: [TLS Cert redacted]
  tls.key: [TLS Key redacted]
kind: Secret
metadata:
  annotations:
    listener.cattle.io/cn-10.43.0.1: 10.43.0.1
    listener.cattle.io/cn-127.0.0.1: 127.0.0.1
    listener.cattle.io/cn-192.168.122.8: 192.168.122.8
    listener.cattle.io/cn-kubernetes: kubernetes
    listener.cattle.io/cn-kubernetes.default: kubernetes.default
    listener.cattle.io/cn-kubernetes.default.svc.cluster.local: kubernetes.default.svc.cluster.local
    listener.cattle.io/cn-localhost: localhost
    listener.cattle.io/fingerprint: SHA1=85AFB7555AD40377FB413017EDBCFE2BF32AEB84
  creationTimestamp: "2020-11-04T17:22:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:tls.crt: {}
        f:tls.key: {}
      f:metadata:
        f:annotations:
          .: {}
          f:listener.cattle.io/cn-10.43.0.1: {}
          f:listener.cattle.io/cn-127.0.0.1: {}
          f:listener.cattle.io/cn-192.168.122.8: {}
          f:listener.cattle.io/cn-kubernetes: {}
          f:listener.cattle.io/cn-kubernetes.default: {}
          f:listener.cattle.io/cn-kubernetes.default.svc.cluster.local: {}
          f:listener.cattle.io/cn-localhost: {}
          f:listener.cattle.io/fingerprint: {}
      f:type: {}
    manager: rke2
    operation: Update
    time: "2020-11-04T17:22:11Z"
  name: rke2-serving
  namespace: kube-system
  resourceVersion: "173"
  selfLink: /api/v1/namespaces/kube-system/secrets/rke2-serving
  uid: 686d9c4c-e67b-468d-99ca-ca1a2bb1a250
type: kubernetes.io/tls
```
So I took the certificate data and...
```
[root@blueberry tls]# echo '[TLS Cert redacted]' | base64 --decode | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2513013959480367789 (0x22e004e1b26cdaad)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = rke2-server-ca@1604510397
        Validity
            Not Before: Nov  4 17:19:57 2020 GMT
            Not After : Nov  4 17:19:57 2021 GMT
        Subject: O = rke2, CN = rke2
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:4a:ac:9b:4b:a7:d1:63:d6:f3:9a:0e:e8:b4:29:
                    2f:e2:33:cf:e3:2a:ab:f7:31:8d:37:bc:d2:66:ea:
                    27:9d:c2:c8:79:87:32:e7:0b:54:c0:d7:24:f7:e9:
                    d3:c8:a2:e5:c0:40:d0:0d:0e:06:56:d3:67:06:d8:
                    e4:9b:f0:a3:2b
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:192.168.122.8
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:d9:82:ae:96:e9:c5:88:fc:af:17:0d:aa:19:
         1e:b8:81:67:e0:fe:20:f9:e7:37:d0:9e:41:f2:2b:8e:8b:05:
         cd:02:20:58:1f:e3:92:9a:6f:bc:91:a6:19:37:8b:17:a6:77:
         6f:62:ce:94:ba:48:db:db:33:c9:4c:a0:bd:a3:ae:79:82
```
We see "localhost" instead of "blueberry" in the DNS record in the cert above.  With this knowledge in-hand, on the agent (strawberry) I replaced the hostname (blueberry) in the `server:` entry with the IP address.
Config.yaml WAS:
```server: https://blueberry:9345
token: K10381f.........98e4d::server:48b86....9835
```
and NOW is 
```
server: https://192.168.122.8:9345
token: K10381f.........98e4d::server:48b86....9835
```
After this edit, the agent might be running... I see the following in the process tree:
```
        ├─containerd-shim─┬─flanneld───6*[{flanneld}]
        │                 ├─pause
        │                 ├─runsvdir───runsv───calico-node───10*[{calico-node}]
        │                 └─14*[{containerd-shim}]
        ├─containerd-shim─┬─kube-proxy───7*[{kube-proxy}]
        │                 ├─pause
        │                 └─13*[{containerd-shim}]
```
However:
```
[root@strawberry tmp]# export KUBECONFIG=/etc/rancher/rke2/config.yaml
[root@strawberry tmp]# /var/lib/rancher/rke2/bin/kubectl get pods --all-namespaces
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
I still can't seem to attach.

_**Possibly Related:**_
https://github.com/rancher/k3s/issues/1633
https://github.com/rancher/k3s/issues/1395
https://github.com/rancher/k3s/issues/2369

**Comment by manuelbuil** [comment]
I was experiencing exactly the same. In my case, the problem was that my network manager restarted and removed a required route in the routing table. The consequence was that from the worker I was not able to reach the server. However, the logs were only showing `msg="failed to get CA certs: Get \"https://127.0.0.1:32849/cacerts\": read tcp 127.0.0.1:41882->127.0.0.1:32849: read: connection reset by peer"`. Once I added that missing rule, everything went back to normal
