### ISSUE TITLE
Release channel for v1.29 missing

### ISSUE THREAD

**Issue by peter-englmaier** [rancher/rke2#5192]
**Describe the bug:**
[v1.29.0+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.29.0%2Brke2r1) has been release two weeks ago, but the channel URL https://update.rke2.io/v1-release/channels/v1.29 still returns 404.
Is this on purpose because .0 releases are not recommended, or has it been forgotten?

**Comment by brandond** [comment]
We released it over the holidays, and most of the team was out. We're back this week and are picking up where we left off.

**Comment by peter-englmaier** [comment]
@brandond : Thanks !
I see, that the problem has been fixed! I wish you and your team a happy New Year!

**Comment by brandond** [comment]
1.29 is not stable yet, you'll need to use INSTALL_RKE2_CHANNEL=latest to get RPMs from the latest non-stable channel.
