### ISSUE TITLE
bind-address configuration in /etc/rancher/rke2/config.yaml not affecting kube-apiserver listening address

### ISSUE THREAD

**Issue by kingsd041** [rancher/rke2#5196]
**Environmental Info:**
RKE2 Version: v1.29.0+rke2r1

Node(s) CPU architecture, OS, and Version: 

ubuntu 22.04

Cluster Configuration:

1 server

**Describe the bug:**

I have configured the `bind-address` parameter in the /etc/rancher/rke2/config.yaml file to specify a specific IP address for kube-apiserver to bind to. However, it seems that kube-apiserver continues to listen on 0.0.0.0, ignoring the specified bind address.

**Steps To Reproduce:**

1. Edit the /etc/rancher/rke2/config.yaml file. Set the `bind-address` parameter to a specific IP address.
```
root@rke2-2:~# cat /etc/rancher/rke2/config.yaml
system-default-registry: registry.cn-hangzhou.aliyuncs.com
bind-address: 192.168.205.81
```
2. start RKE2

**Expected behavior:**

I expect kube-apiserver to bind to the IP address specified in the `bind-address` configuration.

**Actual behavior:**

Kube-apiserver still listens on 0.0.0.0, regardless of the `bind-address` configuration.

![image](https://github.com/rancher/rke2/assets/19684717/32117cdb-c3a9-4f81-a6eb-8bd6083f2674)

**Additional context / logs:**

**Comment by brandond** [comment]
That arg configures the supervisor API bind address, not the apiserver bind address. If you want to override the apiserver bind address, you should set the correct apiserver arg:

```yaml
apiserver-arg:
  - bind-address=192.168.205.81
```
