### ISSUE TITLE
Cannot implement Lua plugin

### ISSUE THREAD

**Issue by hustluh** [rancher/rke2#5235]
**Environmental Info:**
RKE2 Version: rke2 version v1.26.11+rke2r1 (7ee1cfc93db32d05f3270711b24c429515019e8a)

Node(s) CPU architecture, OS, and Version: Linux serverName 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Thu Aug 31 10:29:22 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 server, 1 agent

**Describe the bug:**

I am attempting to test Lua plugin functionality with our RKE2 instance as we utilize Lua scripts in a high-side environment utilizing standard NGINX/nginx.conf files.

**Steps To Reproduce:**

- Installed RKE2: 
- Ran the following command: `kubectl edit pod -n kube-system rke2-ingress-nginx-controller` (with the additional randomized value at the end)
-  Attempted to add volumeMount /etc/nginx/lua/plugins/hello_world/ with name hello-world, as well as volumes name: hello-world, configMap:, name: hello-world-plugin (following the answer here https://stackoverflow.com/questions/76835282/ingress-nginx-set-host-header-dynamically-depending-on-path)
**Expected behavior:**

File allows the write to occur, then I could perform a rollout restart to have the new plugin recognized and tested for verification purposes.
**Actual behavior:**

Receive error:
```# pods "rke2-ingress-nginx-controller-jjj9h" was not valid:
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
#   core.PodSpec{
#       Volumes: []core.Volume{
#               {Name: "webhook-cert", VolumeSource: {Secret: &{SecretName: "rke2-ingress-nginx-admission", DefaultMode: &420}}},
#               {Name: "kube-api-access-l9lh5", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: "token"}}, {ConfigMap: &{LocalObjectReference: {Name: "kube-root-ca.crt"}, Items: {{Key: "ca.crt", Path: "ca.crt"}}}}, {DownwardAPI: &{Items: {{Path: "namespace", FieldRef: &{APIVersion: "v1", FieldPath: "metadata.namespace"}}}}}}, DefaultMode: &420}}},
# +             {
# +                     Name: "hello-world",
# +                     VolumeSource: core.VolumeSource{
# +                             ConfigMap: &core.ConfigMapVolumeSource{LocalObjectReference: core.LocalObjectReference{...}, DefaultMode: &420},
# +                     },
# +             },
#       },
#       InitContainers: nil,
#       Containers: []core.Container{
#               {
#                       ... // 7 identical fields
#                       Env:       {{Name: "POD_NAME", ValueFrom: &{FieldRef: &{APIVersion: "v1", FieldPath: "metadata.name"}}}, {Name: "POD_NAMESPACE", ValueFrom: &{FieldRef: &{APIVersion: "v1", FieldPath: "metadata.namespace"}}}, {Name: "LD_PRELOAD", Value: "/usr/local/lib/libmimalloc.so"}},
#                       Resources: {Requests: {s"cpu": {i: {...}, s: "100m", Format: "DecimalSI"}, s"memory": {i: {...}, s: "90Mi", Format: "BinarySI"}}},
#                       VolumeMounts: []core.VolumeMount{
#                               {Name: "webhook-cert", ReadOnly: true, MountPath: "/usr/local/certificates/"},
#                               {Name: "kube-api-access-l9lh5", ReadOnly: true, MountPath: "/var/run/secrets/kubernetes.io/serviceaccount"},
# +                             {Name: "hello-world", MountPath: "/etc/nginx/lua/plugins/hello_world"},
#                       },
#                       VolumeDevices: nil,
#                       LivenessProbe: &{ProbeHandler: {HTTPGet: &{Path: "/healthz", Port: {IntVal: 10254}, Scheme: "HTTP"}}, InitialDelaySeconds: 10, TimeoutSeconds: 1, PeriodSeconds: 10, ...},
#                       ... // 10 identical fields
#               },
#       },
#       EphemeralContainers: nil,
#       RestartPolicy:       "Always",
#       ... // 28 identical fields
#   }
```

**Additional context / logs:**

Reviewing additional questions online, it seems that with the nginx-ingress controller being a pod vs a deployment, the issue occurs.

**Comment by brandond** [comment]
1. You can't edit running pods. The error message you're getting is very clear about that.
2. You COULD edit the deployment, but I wouldn't recommend doing that, as it is managed by the helm chart.
3. Check the rke2-ingress helm [chart values](https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.8.200/values.yaml), and see if you can enable what you need via [HelmChartConfig](https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig).

**Comment by hustluh** [comment]
I edited the helm chart per your advice and I see the mount has taken (`/etc/nginx/lua/plugins/hello_world`); however, after restarting the pod/cluster, I see the attempt to load the plugin and it states it cannot find that path's main.lua, which it exists. With it showing the path, wouldn't that mean it is pulling it from the container's root file system? If so, why would it spit out that it can't find it?

**Comment by brandond** [comment]
I would probably recommend building your own images with the plugins you want, instead of trying to distribute the plugin files to the hosts and then mounting those files into the pods via volumes. This is not really about RKE2 though...

**Comment by hustluh** [comment]
Yeah, that's a secondary option.. but following their (Kubernetes) guide, it mentioned mounting it would be just fine.. and I was assuming (we all know how that goes) that the mount would come from within the container for RKE2's ingress nginx controller, since it was found there already.. or is me putting in that mount from the helm chart registering from the host's root file system instead?

WRT not being about RKE2, I agree to a point. Full disclosure, I opened a ticket with the Kubernetes ingress-nginx folks too and they counter pointed to reach back out to you all as the version is not supported or created by them (1.9.3 hardened I believe was the call out). I tried relaying this in chat, but it seems I'm shadow banned from messaging.

**Comment by brandond** [comment]
I would point you at this section of the chart values:
https://github.com/rancher/rke2-charts/blob/3eb1abdab79351674b7486aa2de9b728cbbc4eaf/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.8.200/values.yaml#L548-L573

**Comment by hustluh** [comment]
Thanks. I manipulated that to:

```
# -- Additional volumeMounts to the controller main container.
  extraVolumeMounts:
      - name: hello-world
        mountPath: /etc/nginx/lua/plugins/hello_world

  # -- Additional volumes to the controller pod.
  extraVolumes:
    - name: hello-world
```

This allowed the mount to show up in the output of `kubectl describe pod -n kube-system rke2-ingress-nginx-controller`:

```
    Mounts:
      /etc/nginx/lua/plugins/hello_world from hello-world (rw)
      /usr/local/certificates/ from webhook-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dmrbk (ro)
```

Reviewing the logs for the ingress nginx controller, grepping for `plugin` returned:

```
[root@redacted 4.8.200]# kubectl logs -n kube-system rke2-ingress-nginx-controller-tqm99 | grep plugin
2024/01/10 20:46:58 [error] 23#23: [lua] plugins.lua:19: load_plugin(): error loading plugin "plugins.hello_world.main": module 'plugins.hello_world.main' not found:
	no field package.preload['plugins.hello_world.main']
	no file '/etc/nginx/lua/plugins/hello_world/main.lua'
	no file '../lua-resty-core/lib/plugins/hello_world/main.lua'
	no file '../lua-resty-lrucache/lib/plugins/hello_world/main.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/plugins/hello_world/main.lua'
	no file '/usr/local/share/lua/5.1/plugins/hello_world/main.lua'
	no file '/usr/local/lib/lua/plugins/hello_world/main.lua'
	no file './plugins/hello_world/main.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/plugins/hello_world/main.lua'
	no file '/usr/local/share/lua/5.1/plugins/hello_world/main.lua'
	no file '/usr/local/share/lua/5.1/plugins/hello_world/main/init.lua'
	no file '/usr/local/lib/lua/plugins/hello_world/main/plugins/hello_world/main.so'
	no file '/usr/local/lib/lua/plugins/hello_world/main.so'
	no file './plugins/hello_world/main.so'
	no file '/usr/local/lib/lua/5.1/plugins/hello_world/main.so'
	no file '/usr/local/lib/lua/plugins/plugins.so'
	no file '/usr/local/lib/lua/plugins.so'
	no file './plugins.so'
	no file '/usr/local/lib/lua/5.1/plugins.so'
```
