### ISSUE TITLE
Bump sriov image build verions

### ISSUE THREAD

**Issue by mgfritch** [rancher/rke2#5236]
The following arm64 image builds are failing:
* `hardened-sriov-network-config-daemon`
* `hardened-sriov-network-webhook`

arm64 builds are created via https://github.com/rancher/image-build-sriov-operator/pull/26, but were missed during the image build bump https://github.com/rancher/rke2/pull/4865

**Comment by VestigeJ** [comment]
https://hub.docker.com/search?q=rancher%2Fhardened-sriov

https://github.com/rancher/charts/blob/e239090645e5128c5fc2926e2f5396b9516f02c3/charts/sriov/103.0.0%2Bup0.1.0/Chart.yaml#L29
