### ISSUE TITLE
In windows, kube-proxy does not log the error and calico logs are in the wrong path

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5247]
**Environmental Info:**
RKE2 Version: 

Any

Node(s) CPU architecture, OS, and Version: 

One Windows agent

Cluster Configuration:

1 windows agent

**Describe the bug:**

If something goes wrong in kube-proxy.exe process, by checking the windows system logs, you will see the following output:
```
kube-proxy exited: exit status 1
```
which is useless to understand what is going on.

The problem is that these lines don't apparently work well in windows:
https://github.com/rancher/rke2/blob/master/pkg/pebinaryexecutor/pebinary.go#L225C8-L226
and they don't provide anything in the logging windows system

Then, calico logs are under /var/log/. It makes more sense that they are under `C:\var\lib\rancher\rke2\agent\logs`

**Steps To Reproduce:**

- Installed RKE2: 

I don't exactly know how to produce a `kube-proxy.exe` error with the current rke2 binary. This is how it happened to me:

1 - Add on extra arg here https://github.com/rancher/rke2/blob/master/pkg/pebinaryexecutor/pebinary.go#L225C8-L226. An arg which is wrong. For example:
```
	extraArgs := map[string]string{
		"network-name": p.CNIConfig.CNICfg.OverlayNetName,
		"bind-address": p.CNIConfig.CNICfg.IP,
                "log-file": "C://var//log//dummy.log"
	}
```
2 - Build rke2.exe `make build-windows-binary`
3 - Execute rke2.exe in the node-agent as a service `C:\usr\local\bin\rke2.exe agent service --add` and `Start-Service -Name rke2`
4 - By checking the windows logs, you'll see `kube-proxy exited: exit status 1` and have no idea what is going on

Check that calico logs and kube-proxy logs are in `C:\var\lib\rancher\rke2\agent\logs`
```
PS C:\Users\Administrator> ls C:\var\lib\rancher\rke2\agent\logs

    Directory: C:\var\lib\rancher\rke2\agent\logs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/12/2024  2:39 AM           8402 calico-node.log
-a---           1/12/2024  2:39 AM          76379 felix.log
-a---           1/12/2024  2:39 AM              0 kube-proxy.log
-a---           1/12/2024  2:21 AM       51485306 kubelet.log
```

**Expected behavior:**

To know what is going on so that you can fix it

**Actual behavior:**

You just know that there is an error

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
### Validated with version v1.29-rc2+rke2r1
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
Ubuntu 22.04, Windows 2022
```
  
*Cluster Configuration:*

```
1 server, 1 agent (optional), 1 windows agent
```

## Testing Steps

1. Install RKE2 and join linux (optional) and windows agent
2. Check the logs are present in Windows agent under `C:\var\lib\rancher\rke2\agent\logs`
  
**Replication Results:**
- rke2 version used for replication:

```
PS C:\Users\Administrator> C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.29.0+rke2r1 (4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709)
go version go1.21.5
```
 

```
PS C:\Users\Administrator> ls C:\var\lib\rancher\rke2\agent\logs\


    Directory: C:\var\lib\rancher\rke2\agent\logs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/22/2024   4:53 PM              0 kubelet.log


PS C:\Users\Administrator>
```
 
**Validation Results:**
- rke2 version used for validation:

```
PS C:\Users\Administrator> C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.29.1-rc2+rke2r1 (a4986a5a5840f1a259e66c61553a9abd58ef9624)
go version go1.21.6
```
 

```
PS C:\Users\Administrator> ls C:\var\lib\rancher\rke2\agent\logs\


    Directory: C:\var\lib\rancher\rke2\agent\logs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/22/2024   6:41 PM           3036 calico-node.log
-a----         1/22/2024   6:41 PM              0 felix.log
-a----         1/22/2024   6:41 PM              0 kube-proxy.log
-a----         1/22/2024   6:41 PM              0 kubelet.log


PS C:\Users\Administrator>
```
