### ISSUE TITLE
crictl/ctr not usable because of wrong default socket configuration

### ISSUE THREAD

**Issue by megabreit** [rancher/rke2#5250]
**Environmental Info:**
RKE2 Version: 
v1.26.11+rke2r1 (but any earlier version (e.g.1.25, 1.24...) is the same)

Node(s) CPU architecture, OS, and Version: 
Linux node 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04 but probably any other OS is the same

Cluster Configuration:
any

**Describe the bug:**
crictl and ctr from the rke2 installation don't work in a default installation because their default socket config is wrong.
```
# crictl ps
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
WARN[0000] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
E0111 19:07:44.842990 2289747 remote_runtime.go:390] "ListContainers with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory\"" filter="&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},}"
FATA[0000] listing containers: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory" 
```
```
# ctr -n k8s.io images ls
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///run/containerd/containerd.sock: timeout"
```
This can be worked around at runtime with:
```
# crictl config --set runtime-endpoint=unix:///run/k3s/containerd/containerd.sock
# crictl ps
```
or with an additional option like
```
# ctr --address /run/k3s/containerd/containerd.sock -n k8s.io images ls
```
The workarounds are unfortunately not persistent across reboots.
This extremely lowers the debug experience in case it's needed to go down that deep.

**Steps To Reproduce:**
any RKE2 installation
``` 
# export PATH=$PATH:/var/lib/rancher/rke2/bin
# crictl ps
# ctr images ls
```

**Expected behavior:**
crictl and ctr should use the containerd socket /run/k3s/containerd/containerd.sock correctly by default

**Actual behavior:**
crictl and ctr are not usable, see problem description

**Comment by brandond** [comment]
Yes, we have a nonstandard CRI socket path. This is covered in a few places in the docs:
https://docs.rke2.io/search?q=container_runtime_endpoint

**Comment by megabreit** [comment]
@brandond Call me old-fashioned, but I think if you deliver some commands with RKE2 I'm expecting them to all work in the default configuration. I also don't see why *you* should not fix this once but let *lots of people* find out about this in cases they need to debug a broken RKE2 installation. This is very user-unfriendly.
I created a case for this, so yes, it's important to me.

**Comment by brandond** [comment]
We ship vanilla Kubernetes components, including kubectl and crictl. You need to set the CRI socket path for `crictl` for the some reason you need to set the KUBECONFIG path when using `kubectl` - because RKE2 does not use the default paths expected by these tools, and we do not believe in modifying the user's environment for them to override the defaults.

**Comment by megabreit** [comment]
Persistent symlinking will not work, because /run is usually tmpfs. But RKE2 could create one at startup.
There are also standard locations in any Linux distro to place environment variables (like /etc/environment) which could easily modified correctly by the RKE2 installation procedure.
It's not that there were no easy ways to setup things correctly by RKE2.
