### ISSUE TITLE
Should not rewrite HelmChart manifests using HelmChart type

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#527]
As per @ibuildthecloud:

>  https://github.com/rancher/rke2/blob/master/pkg/bootstrap/bootstrap.go#L365  We probably dont' want to read/write this file using a struct.  While the typed nature is nice, the downside is if HelmChart has a new field in the struct we don't know about, they we will drop it.  So it's better to just treat this is an unstructured object.

Discussed using the unstructured type from https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured instead

**Comment by brandond** [comment]
While we're here we should probably handle manifests with multiple documents as well. Failure to do so is the cause of https://github.com/rancher/rancher/issues/30012#issuecomment-741228968 - the first document is a namespace, so we don't handle helmChart portion. If the HelmChart had happened to be first, we would have dropped the namespace when rewriting and broke it in a different way.

**Comment by ShylajaDevadiga** [comment]
Closing this issue in favor of validation covered in https://github.com/rancher/rke2/issues/3469
