### ISSUE TITLE
Refactor windows CNI code to simplify the support of new CNI plugins

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5275]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/rancher/rke2/issues/5215, we need to abstract how pebinary talks to the CNI plugin. Right now, as Calico is the only CNI plugin, there is a lot of Calico specific stuff

**Describe the solution you'd like**

* An interface that each CNI plugin can honor
* A common config struct
 Both objects could be used by pebinary without having to know details on the CNI plugin

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
A few issues around this are similar. The code went through a few iterations and required some changes tracked by this, but I'm going to close this one in favor of the Calico and Flannel Windows issues directly.
