### ISSUE TITLE
Bump containerd to 1.4.x for cgroups v2 capable systems

### ISSUE THREAD

**Issue by kphunter** [rancher/rke2#530]
When trying to install and run rke2 on CentOS 7.8, a significant hurdle is updating the system bootloader to accommodate legacy cgroups.

The [known issues](https://github.com/rancher/rke2/blob/master/docs/known_issues.md#control-groups-v2) documentation page could more clearly specify how to modify grub, but resolution for this issue would be to update the version of `containerd` baked into the systemd binary: https://github.com/rancher/rke2/blob/6f91705c4940762504470e2db784d37118da7142/Dockerfile#L131.

**Comment by rancher-max** [comment]
#### Validated using v1.19.5-rc1+rke2r1

- Containerd version is 1.4.3 as expected:
```
$ sudo /var/lib/rancher/rke2/bin/containerd -v
containerd github.com/rancher/containerd v1.4.3-k3s2 441c8be2f38dbb1b0676818391aa93d3ad46ecb6
```
- Validated I am able to install rke2 on a fedora system 
- Able to join both server and worker nodes and deploy some workloads

**Comment by arlllk** [comment]
Currently the documentation continues to say that rke2 uses containerd 1.3, and based on the check of the version I think the documentation should be updated to reflect the update

https://docs.rke2.io/known_issues/
