### ISSUE TITLE
resolv.conf set to 8.8.8.8 by default on api server, not straight forward to change.

### ISSUE THREAD

**Issue by mattwillsher** [rancher/rke2#5309]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.29.0+rke2r1 (4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709)
go version go1.21.5 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 
```
Linux rke2-server-1 5.14.0-362.13.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 21 07:12:43 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server (VM, 4 cores, 4GB RAM), 1 agent (8 core, 96GB RAM)

**Describe the bug:**
When setting up OIDC integration use a DNS zone, logs showed resolution happening against 8.8.8.8:53 only, not the internal resolvers configured on the server host.  This results in failed resolution, and information leakage in clear text.

**Steps To Reproduce:**
- Installed RKE2: 
- Configure, e.g. OIDC to use a private DNS name resolvable via the host machines resolvers but not on the public Internet.
- Check `/var/log/containers/kube-apiserver-*` for E0119 errors (see log line below).

**Expected behavior:**
containerd uses the host resolvers by default, with an rke2 configuration option to set them independent of the host.

**Actual behavior:**
container uses resolver 8.8.8.8 only.

**Additional context / logs:**
```
2024-01-19T07:21:50.590940429Z stderr F E0119 07:21:50.590639       1 oidc.go:304] oidc authenticator: initializing plugin: Get "https://REDACTED/.well-known/openid-configuration": dial tcp: lookup REDACTED on 8.8.8.8:53: no such host
```

**Comment by mattwillsher** [comment]
Also affects coredns pod, helm-install/delete. 
Source of the 8.8.8.8 is kubelet, getting it from `/var/lib/rancher/rke2/agent/etc/resolv.conf`
This location is configurable via the `--resolv-conf` agent argument, or `resolv-conf` in `/etc/rancher/rke2/config.yaml`. Setting it and restarting rke2-server does not change the value in the api container, nor does deletion the pod via kubectl. 
In the end I rebooted the server node, which worked and the resolv.conf in the pods now contains the host resolvers.

**Comment by brandond** [comment]
> Expected behavior:
> containerd uses the host resolvers by default

This is about RKE2 and the kubelet, not containerd.

RKE2 does attempt to to use the system resolvers by default. It checks `/etc/resolv.conf` and `/run/systemd/resolve/resolv.conf`. If neither of these contain an ipv4 unicast upstream resolver (ie they contain no upstream, or point at a loopback address a la resolved) then RKE2 will generate a stub resolv.conf that uses 8.8.8.8.

You should ensure that your host resolv.conf points at a valid upstream resolver, or create a rke2-specific resolv.conf and use the `resov-conf` option to point RKE2 at this file.

**Comment by mattwillsher** [comment]
resolv.conf does point to a valid upstream ipv4 unicase DNS servers
```
# Generated by NetworkManager
search REDACTED
nameserver 192.168.1.1
nameserver fd01:870:d352:1111::1
nameserver fe80::618:d6ff:fea0:1234%ens3
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver fe80::618:d6ff:fea0:aeb%ens3
````
I fixed the issue I saw by setting `--resolve-conf` to `/etc/resolv.conf`

**Comment by brandond** [comment]
All three of your ipv6 upstreams point at nonroutable ULA addresses, and are why it was not considered suitable for use by k3s. You should not have these in the resolv.conf use by k3s. If your pods attempt to use these, they will experience DNS timeouts, as these are only reachable from the host network namespace.

**Comment by snowman386** [comment]
> The second two IPv6 upstreams are [link-local address](https://en.wikipedia.org/wiki/Link-local_address#IPv6), and is why this file was not considered suitable for use by k3s. You should not have these in the resolv.conf used by k3s. If your pods attempt to use these, they will experience DNS timeouts, as these are only reachable from the host network namespace.

I just ran into this issue in AWS. Apparently RKE2 doesn't like the AWS resolver IP 169.254.169.253 so /etc/resolv.conf is rejected. Seems like there should be an exception for such a prominent IP.

**Comment by brandond** [comment]
@snowman386 there is an exception for the GCP resolver at 169.254.169.254. See https://github.com/k3s-io/k3s/pull/12692

If AWS has decided to use another, DIFFERENT link-local address that is one octet off, that is unfortunate. Are you sure this is actually reachable from pod networks? Normally it would not be, as it is a link-local address that cannot be routed to.

I would recommend using the vpc+2 resolver address, as this is guaranteed to be a routable address:
> https://docs.aws.amazon.com/vpc/latest/userguide/AmazonDNS-concepts.html
> The Route 53 Resolver is located at 169.254.169.253 (IPv4), fd00:ec2::253 (IPv6), and at the primary private IPV4 CIDR range provisioned to your VPC plus two. For example, if you have a VPC with an IPv4 CIDR of 10.0.0.0/16 and an IPv6 CIDR of 2001:db8::/32, you can reach the Route 53 Resolver at 169.254.169.253 (IPv4), fd00:ec2::253 (IPv6), or 10.0.0.2 (IPv4).

**Comment by snowman386** [comment]
> [@snowman386](https://github.com/snowman386) there is an exception for the GCP resolver at 169.254.169.254. See [k3s-io/k3s#12692](https://github.com/k3s-io/k3s/pull/12692)
> 
> If AWS has decided to use another, DIFFERENT link-local address that is one octet off, that is unfortunate. Are you sure this is actually reachable from pod networks? Normally it would not be, as it is a link-local address that cannot be routed to.
> 
> I would recommend using the vpc+2 resolver address, as this is guaranteed to be a routable address:
> 
> > https://docs.aws.amazon.com/vpc/latest/userguide/AmazonDNS-concepts.html
> > The Route 53 Resolver is located at 169.254.169.253 (IPv4), fd00:ec2::253 (IPv6), and at the primary private IPV4 CIDR range provisioned to your VPC plus two. For example, if you have a VPC with an IPv4 CIDR of 10.0.0.0/16 and an IPv6 CIDR of 2001:db8::/32, you can reach the Route 53 Resolver at 169.254.169.253 (IPv4), fd00:ec2::253 (IPv6), or 10.0.0.2 (IPv4).

Of course AWS and GCP are 1 bit different! I did test it with custom DNS resolver endpoints which worked. I can also set the DHCP options on the vpc to use the +2 address. That works too.  This is a vendor AMI with rke2 bundled so I don't have a lot of control over it. Just trying to figure out the best workaround.

Thanks

**Comment by snowman386** [comment]
I was able to get back into it today. This is the version of rke2 in the vendor's AMI
`rke2 version v1.34.8`
I was able to test dns resolution from coredns and a busybox pod to 169.254.169.253 and it resolved.  Would it be beneficial to open an issue to get the AWS IP added as an exception and probably the Azure one if not already in there?

**Comment by brandond** [comment]
Yeah, I suppose we could.

I wish folks would agree on addresses to use for this, rather than each of them picking random IPs from reserved ranges to treat specially.
