### ISSUE TITLE
etcdvoter after upgrade from 1.25.14 rke2r1 to 1.26.12

### ISSUE THREAD

**Issue by therus000** [rancher/rke2#5314]
etcdvoter after upgrade from 1.25.14 rke2r1 to 1.26.12
i tried to update my cluster from 3 nodes (controlplan). 
everything update norm until i updated the firs node
i got status on everynode etcdvoter
the version that i update from 1.25.14 rke2r1
the version that i updated to 1.26.12

**Comment by brandond** [comment]
Yes, we added a status condition for etcd. It will be true if the node is a voting member of the cluster. If not, the reason and message will describe why.

**Comment by therus000** [comment]
is that mean that is this status normal?

![etcdvoter](https://github.com/rancher/rke2/assets/48754322/73856442-e900-487c-8144-e41db282ca5e)

**Comment by brandond** [comment]
Yes.
