### ISSUE TITLE
Facing issue regarding calico-node pod

### ISSUE THREAD

**Issue by Samanthaterralogic** [rancher/rke2#5316]
Hi, i am facing the issue the calico-node pod is not running. It is getting crashed. Not able to deploy any pods,due to this error.
How can i fix this error ?
<img width="960" alt="Screenshot 2024-01-24 151832" src="https://github.com/rancher/rke2/assets/140379812/5a34a7cf-fe35-4420-b3a2-a8eff01ac3cf">

<img width="960" alt="Screenshot 2024-01-24 151851" src="https://github.com/rancher/rke2/assets/140379812/c8a133f8-c974-4faf-bdd0-3b89f879a482">

**Comment by Samanthaterralogic** [comment]
@
![Uploading Screenshot 2024-01-24 180201.png…]()

**Comment by thomasferrandiz** [comment]
I can't see the screenshot in your last comment.
Can you post it as text, it will be a lot easier to read.

Also please note that 1.23 has been unsupported for a long time. 
Only 1.26+ versions are currently supported.

**Comment by Samanthaterralogic** [comment]
Sorry for the inconveince regarding screenshot. Below is the config.yaml file - 
-------
tls-san:
  - "master1.192.168.199.104.nip.io"
node-label:
  - "nodetype=master"
node-ip: "192.168.199.104,2001:abc:0:224:250:56ff:fe9b:5cfb"
cluster-cidr: "10.42.0.0/16,2001:cafe:42:0::/56"
service-cidr: "10.43.0.0/16,2001:cafe:42:1::/112"
cluster-dns: "10.43.0.10"
cluster-domain: "master1.192.168.199.104.nip.io"
cni:
  - calico
disable:
  - rke2-canal
  - rke2-kube-proxy

--------

I am working on centos 7,once i will check with 1.26 version and see if i am facing same issue. When i tried 1.29 version on ubuntu 22.04 i faced issue with calico node pod crashing,the error was regarding the BIRD. 
Error in ubuntu - "Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused W0724 00:54:46.157624 73 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Back-off restarting failed container"

So thats why i started to check on centos 7.

**Comment by Samanthaterralogic** [comment]
> I can't see the screenshot in your last comment. Can you post it as text, it will be a lot easier to read.
> 
> Also please note that 1.23 has been unsupported for a long time. Only 1.26+ versions are currently supported.

I tried for rke2 version 1.26.12. Still facing same issue.

**Comment by brandond** [comment]
Is your node really named `localhost`? I wonder if that is confusing things. Many bits of Kubernetes require an interface with a valid IP address and a default route, even if it is just a dummy interface.

**Comment by Samanthaterralogic** [comment]
Actually, i have downloaded minimal version of centos 7 on my virtual box. The local host name was automatically created,it is the hostname of my VM. I have configured static ip for the VM.

**Comment by thomasferrandiz** [comment]
I just noticed that in both of your screenshots the pod `calico-kube-controllers` is still in `ContainerCreating` state which would explain why `calico-node` keeps crashing since `calico-kube-controllers`.

Can you show the output of `kubectl describe` for this pod?
Also does your VM meet the minimum requirements to run the rke2 control plane?
You need at least 4GB of RAM as per https://docs.rke2.io/install/requirements#vm-sizing-guide
