### ISSUE TITLE
rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64  images cannot be used on windows platform

### ISSUE THREAD

**Issue by alec-lu** [rancher/rke2#5320]
**Environmental Info:**
RKE2 Version: v1.26.12-rke2r1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:3 servers(linux), 2 agents(windows)

**Describe the bug:**
rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64   images 
<img width="795" alt="rke2-win01" src="https://github.com/rancher/rke2/assets/36758795/f76eab0a-a2f6-44b4-9845-cccd8e5638ef">
![rke2-win02](https://github.com/rancher/rke2/assets/36758795/b62bb882-c297-4ba8-b0d5-0d8266c0936b)
cannot be used on windows platform

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by manuelbuil** [comment]
It works for me:
```
1/25/2024 2:08:34 AM Starting rke2 agent v1.26.12+rke2r1 (10683d5a09610873f643ada416b97eb01859108d)
1/25/2024 2:08:34 AM Running load balancer rke2-agent-load-balancer 127.0.0.1:6444 -> [10.85.9.172:9345] [default: 10.85.9.172:9345]
1/25/2024 2:08:34 AM Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation.
1/25/2024 2:08:35 AM Adding server to load balancer rke2-api-server-agent-load-balancer: 10.85.9.172:6443
1/25/2024 2:08:35 AM Running load balancer rke2-api-server-agent-load-balancer 127.0.0.1:6443 -> [10.85.9.172:6443] [default: 10.85.9.172:6443]
1/25/2024 2:08:36 AM Host resolv.conf includes loopback or multicast nameservers - kubelet will use autogenerated resolv.conf with nameserver 8.8.8.8
1/25/2024 2:08:36 AM Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64:
                     directory C:\var\lib\rancher\rke2\agent\images does not exist: image not found
1/25/2024 2:08:36 AM Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64:
                     directory C:\var\lib\rancher\rke2\agent\images does not exist: image not found
1/25/2024 2:08:36 AM Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.26.12-rke2r1-windows-amd64
```

The error you are getting points at a networking problem when connecting to dockerhub:
```
i/o timeout
```

**Comment by brandond** [comment]
The rke2-runtime image is not executed in the container runtime; it is just used to hold various binaries and manifests that are extracted out to disk during node bootstrapping. You are not meant to run it with docker; rke2  extracts it from the airgap tarball or pulls it from docker hub as necessary.

In your case, since you don't appear to have access to docker hub, or a local registry mirror, I would recommend downloading the windows airgap tarball from the release page, and placing it in the images directory on your windows node.
