### ISSUE TITLE
 https://raw.githubusercontent.com/rancher/rke2/release-1.28/install.ps1 seems to install 1.26.12

### ISSUE THREAD

**Issue by aleyval** [rancher/rke2#5323]
**Environmental Info:**
RKE2 Version: 
`rke2.exe version v1.26.12+rke2r1 (10683d5a09610873f643ada416b97eb01859108d)`
`go version go1.20.12`

**OS, and Version**
Windows Server 2022

**Describe the bug:**
I installed rke2 agent on my worker node to add it to my Linux cluster. I got the install script from the release-1.28, but it seems it installed rke2 in v1.26.

**Steps To Reproduce:**
Here are the commands I used :
`137 Invoke-WebRequest -Uri https://raw.githubusercontent.com/rancher/rke2/release-1.28/install.ps1 -Outfile install.ps1`
`138 New-Item -Type Directory c:/etc/rancher/rke2 -Force`
`139 Set-Content -Path c:/etc/rancher/rke2/config.yaml -Value @"`
`	server: https://<server>:9345`
`	token: <token from server node>`
`	"@`
`143 $env:PATH+=";c:\var\lib\rancher\rke2\bin;c:\usr\local\bin"`
`144 [Environment]::SetEnvironmentVariable(`
`   	"Path",`
`   	[Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";c:\var\lib\rancher\rke2\bin;c:\usr\local\bin",`
`    	[EnvironmentVariableTarget]::Machine)`
`145 ./install.ps1`
`147 rke2.exe agent service --add`
`148 Start-Service rke2`

In the end, the rke2 -v returns v1.26.12+rke2r1, and the kubectl get nodes on the master nodes returns the same : 
`NAME                 STATUS   ROLES                                 AGE   VERSION`
`node1                 Ready    control-plane,etcd,master   52m   v1.28.5+rke2r1`
`node_windows   Ready    <none>                                59s   v1.26.12`

**Expected behavior:**
I'd like to be able  to install RKE2 agent in v1.28 to have a homogeneity of versions throughout my cluster

**Comment by manuelbuil** [comment]
By default, it gets installed the version in the stable channel, which is `v1.26.12`.

Try instead: `.\install.ps1 -Version v1.28.2+rke2r1`

**Comment by aleyval** [comment]
Thanks for your help, this worked as expected !
