### ISSUE TITLE
Using installer script in Ubuntu 22.04 on Rasperry Pi 4 causes a 404 error on checksum download.

### ISSUE THREAD

**Issue by willkara** [rancher/rke2#5331]
**Environmental Info:**

**RKE2 Version:** 
N/A

**Node(s) CPU architecture, OS, and Version:** 
Ubuntu 22.04
Raspberry Pi 4

**Cluster Configuration:**
N/A

**Describe the bug:**
Running the installer script causes a 404 error when trying to download checksums for `https://github.com/rancher/rke2/releases/download/v1.26.12+rke2r1/sha256sum-arm64.txt`.

Taking a look at that respective release page shows that there isn't a checksum file generate for `arm64`

**Steps To Reproduce:**
Run installer script in above given architecture and RPi version

**Expected behavior:**
Checksums to download properly and file to exist.

**Actual behavior:**

```
willkara@pleiades-1:~$ curl -sfL https://get.rke2.io | sudo sh -
[INFO]  finding release for channel stable
[INFO]  using v1.26.12+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.26.12+rke2r1/sha256sum-arm64.txt
curl: (22) The requested URL returned error: 404
```

**Comment by skanakal** [comment]
its available from 1.27 and newer versions... see this, Add arm64 support https://github.com/rancher/rke2/pull/4335 
use the flag INSTALL_RKE2_VERSION to set the version...

https://github.com/rancher/rke2/releases/tag/v1.27.3%2Brke2r1
