### ISSUE TITLE
Disable cilium `node.cilium.io/agent-not-ready taint` taint by default

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#5333]
RKE2 tracking issue for:
* https://github.com/k3s-io/helm-controller/issues/151#issuecomment-1912853587

**Comment by rancher-max** [comment]
### Validated on v1.29.2-rc3+rke2r1
  
## Environment Details  
*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04 LTS
  
*Cluster Configuration:*

1 server
  
*/etc/rancher/rke2/config.yaml:*

```
write-kubeconfig-mode: 644
cni: cilium
```
  
## Testing Steps

1. Install helm into VM: `curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash`
2. After starting rke2 and everything up and running, retrieve helm charts and ensure `rke2-cilium` is used: `helm ls -A`
3.  Get value for this chart setting: `helm -n kube-system get all rke2-cilium | grep -i taint`
  
**Replication Results:**
- rke2 version used for replication: v1.29.1+rke2r1
- Cilium version:
```
$ helm ls -A
NAME                            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rke2-cilium                     	kube-system	1       	2024-02-28 22:41:39.647703721 +0000 UTC	deployed	rke2-cilium-1.14.400                        	1.14.4     
...
```
- See that `setNodeTaints` here is actually set to `null` which, ends up using the default. Therefore, `set-cilium-node-taints` is `true`
```
$ helm -n kube-system get all rke2-cilium | grep -i taint
agentNotReadyTaintKey: node.cilium.io/agent-not-ready
  removeNodeTaints: true
  setNodeTaints: null
  remove-cilium-node-taints: "true"
  set-cilium-node-taints: "true"
  agent-not-ready-taint-key: "node.cilium.io/agent-not-ready"
  # To remove node taints
```
 
**Validation Results:**
- rke2 version used for validation: v1.29.2-rc3+rke2r1
- Cilium version:
```
$ helm -n kube-system ls
NAME                            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rke2-cilium                     	kube-system	1       	2024-02-28 18:37:06.810344089 +0000 UTC	deployed	rke2-cilium-1.15.100                        	1.15.1     
...
```
- Now, `setNodeTaints` is explicitly `false` and there is no value for `set-cilium-node-taints`. Other values remain the same.

```
$ helm -n kube-system get all rke2-cilium | grep -i taint
agentNotReadyTaintKey: node.cilium.io/agent-not-ready
  removeNodeTaints: true
  setNodeTaints: false
  remove-cilium-node-taints: "true"
  agent-not-ready-taint-key: "node.cilium.io/agent-not-ready"
  # To remove node taints
```
