### ISSUE TITLE
Some files and directories are created with looser permissions than RKE2's STIG requires

### ISSUE THREAD

**Issue by sfackler** [rancher/rke2#5334]
**Environmental Info:**
RKE2 Version:

```
rke2 version v1.26.12+rke2r1 (10683d5a09610873f643ada416b97eb01859108d)
go version go1.20.12 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 4.18.0-477.27.1.el8_8.x86_64

Cluster Configuration: 1 server

**Describe the bug:**
After installing RKE2 with a config that otherwise complies with the current revision (V1R4) of RKE2's STIG, it creates a few files and directories with incorrect permissions. This is kind of annoying to deal with, since it requires remediation after the installation and startup process (and I think after every upgrade for the binaries).

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**
RKE2 should permission the files and directories it creates in a manner that respects the STIG's requirements (or be able to be configured in such a way). I don't know what the implications would be of changing these permissions on all RKE2 installs, but adding an `--enforce-stig-permissions` flag to the rke2 binary would work for me.

**Actual behavior:**
* The binaries in the directory symlinked from `/var/lib/rancher/rke2/bin` have 0755 permissions rather than the required 0750.
* The `manifests` and `logs` directories in `/var/lib/rancher/rke2/server` have 0755 permissions rather than the required 0750.
* The `v1.26.12-rke2r1-3a06874196a9` directory in `/var/lib/rancher/rke2/data` has 0755 permissions, which may or may not be correct - the STIG says all files in that directory must have 0640 permissions but there are no files in there 🙃.

**Comment by brandond** [comment]
We are not currently planning on moving beyond what is provided by the CIS profile flags by integrating STIG hardening into RKE2. I would probably suggest you work with the RGS folks that maintain the RKE2 STIG and see if they have tools that can assist you in enabling the configuration you're looking for.

https://ranchergovernment.com/

cc @bgulla
