### ISSUE TITLE
[1.19] Bump go version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#534]
We should bump to 1.15.5 or newer.

**Comment by dweomer** [comment]
We did not bump golang yet because we are still on 1.18 which its on go 1.13.x. This belongs in a 1.19 miltstone @davidnuzik

**Comment by dweomer** [comment]
Due to poor branching with my PRs, this change has been satisfied by #599

**Comment by davidnuzik** [comment]
@ShylajaDevadiga no specific test to run here. Conformance pass is suitable to close this issue.

**Comment by rancher-max** [comment]
```
$ rke2 --version
rke2 version v1.19.5-rc1+rke2r1 (a148adbedfbd90c7a8f31313e49134a01848d1b9)
go version go1.15.5b5
```

Pending conformance test success then will close.

**Comment by ShylajaDevadiga** [comment]
Conformance test have passed on CIS Enabled, SELinux Enabled Cluster
CentOS 7.8
CentOS 8.2
