### ISSUE TITLE
Fix validate-charts script

### ISSUE THREAD

**Issue by thomasferrandiz** [rancher/rke2#5371]
There are several minor issues with the current `validate-charts` script:
- k8s version check for version-dependent charts (like vsphere charts) is incorrect
- rke2-coredns template is not rendered properly
- the temp yaml file used by `helm template` was not cleaned-up
- busybox image was not tested when checking for missing airgap images and globalSystemRegistry usage

**Comment by thomasferrandiz** [comment]
Note: multus is updated in https://github.com/rancher/rke2/pull/5379 so I guess there is no need to validate it for this PR in addition

**Comment by rancher-max** [comment]
Closing as there was a [separate issue](https://github.com/rancher/rke2/issues/5378) for multus validation.
