### ISSUE TITLE
[feature] fixed registration address... - kube-vip

### ISSUE THREAD

**Issue by schmitch** [rancher/rke2#540]
for ha it would be great to have a simple built-in mechanism like https://github.com/plunder-app/kube-vip that runs on the server nodes. basicaly I think that would be good for deployments that are smaller than say 50 nodes.

**Comment by mscbpi** [comment]
Just for my information, how is this handled in RKE1 (multiple master without any LB?)

**Comment by mscbpi** [comment]
I think I found the doc [there](https://rancher.com/learning-paths/building-a-highly-available-kubernetes-cluster/)

**Comment by immanuelfodor** [comment]
Huge +1 for the feature idea, though I think it should be another solution that is not mentioned in the above linked docs. Kube API server HA would be really great to achieve without an external load balancer, and it's achievable on the nodes themselves. 

For example, I'm using the CARP protocol with this project to have a simple floating IP across nodes that always points to an up and running node: https://github.com/immanuelfodor/kube-karp This is similar to kube-vip but easier and quicker to setup if you just want the virtual IP and don't need the rest kube-vip offers (DDNS, BGP, etc).
