### ISSUE TITLE
Bump harvester-csi-driver to 0.1.7

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#5430]
harvester-csi-driver's Helm chart has been bumped to 0.1.7 in rancher/rke-charts, we should update here

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  rke2 version v1.29.1+dev.f964aedd (f964aedd6108af661addca2d87ebef14dfaf5218)
 

```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
NAME="Oracle Linux Server"
VERSION="8.9"
ID="ol"
ID_LIKE="fedora"


*Cluster Configuration:*
1 node servers 



## Steps to validate the fix
1. Install  rke2 
2. Install helm
3. Validate harvester csi driver chart versions
 
 
 

## **Validation Results:**
<details> 


```
 
$ rke2 -v

rke2 version v1.29.1+dev.f964aedd (f964aedd6108af661addca2d87ebef14dfaf5218)
go version go1.21.6 X:boringcrypto


~$ helm list -n kube-system | grep harv


WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
harvester-csi-driver            	kube-system	1       	2024-02-16 14:58:46.845376294 +0000 UTC	deployed	harvester-csi-driver-0.1.1700               	v0.1.6
 


```
