### ISSUE TITLE
[E2E] Add Test Case For Process Cleanup when stopping the RKE2 Windows Service

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rke2#5435]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher/rke2/pull/5419 implements logic to ensure that Windows processes are cleaned up alongside the RKE2 service. This change was verified manually but ideally it should be covered in the e2e test suite 

Describe the solution you'd like

Add new E2E test

**Comment by manuelbuil** [comment]
This is a great idea! Right now, this gets wrong so many times. Lately, what I have seen the most is that for some reason containerd/snapshot directory can't be deleted and that makes the script "rke2-uninstall.ps1" fail and leave all the stuff in /var/lib/rancher/rke2
