### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by kaosmonk** [rancher/rke2#546]
Hi guys,

I have a rke2 based cluster that is working fine - 3 control plane nodes, 3 workers. I have used `rancher-latest/rancher` helm chart to get the Rancher server running on rke2 that got installed like:

```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=${URL} \
  --set tls=external
```
I have ALB in front with http and https listeners (used for ssl offload), where http listener redirects to https one and https points to a target group (goes only via http port 80) as ingress seems to be running on a single worker node and that instance shows to be healthy and listens on port 80.

But I am constantly getting `too many redirects` if I try to visit that `URL` and ingress logs shows 302s. Any ideas as to what might be the problem as I am not finding anything to be wrong with the setup nor I am seeing any options that I could use to adjust the behaviour?

If any ideas please share. Ask for any additional piece of information that I will gladly share.

PS please let me know if not appropriate place to ask this question.

**Comment by kaosmonk** [comment]
For the ref
```
# rke2 --version
v1.18.12+rke2r1
```

**Comment by vikassach** [comment]
Hi @kaosmonk did you manage to find a fix for this issue ? getting same issue with `rancher-stable/rancher` and same config as mentioned above.

**Comment by brandond** [comment]
Can you try with a more recent version of RKE2? Previously releases shipped the ingress as a deployment instead of a daemonset by default, which may not be the behavior most users are expecting.

**Comment by thebetterjort** [comment]
I'm running into this issue with rancher stable. I can hit my root domain, but when I try and hit subdomain we get too many redirects. Seems to happen with our nginx 1.14 load balancer, but all apps are deployed are working, its just rancher that gets too many redirects.

**Comment by brandond** [comment]
@thebetterjort I would recommend searching for info or opening an issue in the rancher/rancher repo; RKE2 is a different beast entirely.
