### ISSUE TITLE
RKE2 and Containerd won't start with linux IMA kernel enabled.

### ISSUE THREAD

**Issue by witzd** [rancher/rke2#5469]
I have been trying to get RKE2 running on some servers, after installing RHEL 8.1. The server can start without any problem. But when I switch the OS to IMA label on. nothing seems to work, the server also goes on a loop and keep restarting since the service cannot start. it is a airgap environment, so I do not have too much logs available. 

It also seems that containerd can see the images under /agent/images/ but it cannot untar that file to start the server. 

it throws an error saying the images were not imported. Unfortunately I need to run the servers with IMA enabled. and the rke2 servers and agent will most likely be configured after this is done.

**Comment by witzd** [comment]
@brandond https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/kernel_administration_guide/enhancing_security_with_the_kernel_integrity_subsystem

**Comment by witzd** [comment]
level=error msg="containerd exited: fork/exec /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd: exec format error"

**Comment by brandond** [comment]
Sounds like it's blocking RKE2 from running. RKE2 extracts out most of the core runtime binaries when started, so anything that block execution of unknown files is going to break RKE2.

We can leave this open as a placeholder issue, but we do not have support for this security module on our roadmap.

**Comment by dweomer** [comment]
@witzd have you signed any executables as per the following?
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/kernel_administration_guide/enhancing_security_with_the_kernel_integrity_subsystem#sect-collecting_file_hashes_with_ima

If so, please specify what files you have enabled via the evm/ima subsystem. Please also fill out the appropriate issue template, e.g. https://raw.githubusercontent.com/rancher/rke2/master/.github/ISSUE_TEMPLATE/bug_report.md
