### ISSUE TITLE
CIS 1.5 Control 5.1.5 Remediation

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#549]
Currently, RKE2 can be secured manually by updating the default service account to conform to the CIS 1.5 control 5.1.5 however it'd be preferred to have RKE2 do this automatically if the `--profile=cis-1.5` argument is provided.

**Comment by rancher-max** [comment]
Validated in a simple test on master branch with commit `525479888074426ea6019474c33e184a947c197c` using both cis-1.5 and cis-1.6 profiles that this control is now passing. As this has already been validated on previous released backport branches, I do not believe I need to do any more validations around this here.

However, during testing with an rc when available, I will run rancher scans on a hardened cluster to ensure they all pass in 1.22.
