### ISSUE TITLE
Server configuration file overwritten each time on service startup.

### ISSUE THREAD

**Issue by wilkerd1** [rancher/rke2#553]
When starting the RKE2 server service the values in /etc/rancher/rke2/rke2.yaml are overwritten. I configured it after installation instead of starting the process via the CLI. Setting the server element in the config file to the IP of my server gets clobbered with 127.0.0.1. 

I am also seeing a ton of notifications regarding the use of 127.0.0.1 in the logs - for several components: e.g. kube scheduler, kube controller manager, kublet, etc. 

This leads me to believe it's related to my main configuration file getting clobbered at service startup. How do I go about making the configuration adjustment so it sticks? I'm following the start guide to the letter. Also having similar kinds of issues on my agent node as well.

**Comment by nemethk** [comment]
The similar problem with **kube-controller-manager**...
I add `--pod-eviction-timeout=30s` to the `/var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml` but after `systemctl restart rke2-server.service` all modifications are restored to the default values.

**Comment by brandond** [comment]
1. rke2.yaml is the server-generated admin kubeconfig. If you want to modify it, you can copy it to ~/.kube/config and then make your changes.
2. The static pod manifests are not meant to be modified. If you need to alter the args, use the --kube-controller-manager-arg flag that exists for this purpose.

**Comment by nemethk** [comment]
@brandond Thanks! Does not work, pods were evicted only after 5 minutes.

RKE2 is started on each master as:
`rke2 server --kube-controller-manager-arg="pod-eviction-timeout=10s"`

Checking the `kube-controller-manager`:
```
:~$ kubectl get pod -n kube-system kube-controller-manager-rke2-m3 -o yaml | grep evic
    - --pod-eviction-timeout=10s
```
When status of a node become "Not Ready", pods from that node are evicted only after 5 minutes.

**Comment by nemethk** [comment]
Starting RKE2 service as:
`rke2 server --kube-controller-manager-arg="pod-eviction-timeout=10s" --kube-controller-manager-arg="terminated-pod-gc-threshold=100"`

Checking the `kube-controller-manager`:
```
:~$ kubectl get pod -n kube-system kube-controller-manager-rke2-m3 -o yaml
...
spec:
  containers:
  - command:
    - kube-controller-manager
...
    - --pod-eviction-timeout=10s
...
    - --terminated-pod-gc-threshold=100
...
    - --terminated-pod-gc-threshold=1000 
```

**Comment by nemethk** [comment]
> @brandond Thanks! Does not work, pods were evicted only after 5 minutes.
> 
> RKE2 is started on each master as:
> `rke2 server --kube-controller-manager-arg="pod-eviction-timeout=10s"`
> 
> Checking the `kube-controller-manager`:
> 
> ```
> :~$ kubectl get pod -n kube-system kube-controller-manager-rke2-m3 -o yaml | grep evic
>     - --pod-eviction-timeout=10s
> ```
> 
> When status of a node become "Not Ready", pods from that node are evicted only after 5 minutes.

If it is not RKE2 fault then it's look like the same issue as: https://github.com/kubernetes/kubernetes/issues/55713

**Comment by brandond** [comment]
It looks like RKE2 is passing the setting to the controller manager, so if it's not doing what you want then yeah it's an upstream issue.

**Comment by adeepsri** [comment]
@brandond I see this ticket https://github.com/kubernetes/kubernetes/issues/55713 is closed on 25th June 2021. can you please tell us with which release of RKE2 we can get this fix

**Comment by brandond** [comment]
See the comment at https://github.com/kubernetes/kubernetes/issues/55713#issuecomment-844035331 - the corresponding RKE2 releases would contain the fix.
