### ISSUE TITLE
Indicate GoBoring version when user invokes --version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#555]
When a user invokes `--version` we should indicate the version of GoBoring in use.

**Comment by davidnuzik** [comment]
FYI: This is a nice-to-have for v1.19.5+rke2r1 release, and I imagine the LOE is low. If it needs to slip until next release this is acceptable.

**Comment by dweomer** [comment]
We should emit the golang version, which, in the case of GoBoring, will be something like 1.15.5b instead of 1.15.5.

**Comment by ShylajaDevadiga** [comment]
Validated version of GoBoring is displayed along with rke2 version.
```
rke2 --version
rke2 version v1.19.5-rc1+rke2r1 (a148adbedfbd90c7a8f31313e49134a01848d1b9)
go version go1.15.5b5

```

**Comment by davidnuzik** [comment]
Just to reiterate, the version of GoBoring is printed out. An end user would ensure they see the `b` in the version as Jacob indicated in a comment above here https://github.com/rancher/rke2/issues/555#issuecomment-737502915
