### ISSUE TITLE
Containers from old version of RKE2 persist even after upgrade and multiple restarts of rke2-agent/server

### ISSUE THREAD

**Issue by sibzz** [rancher/rke2#5576]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.26.13+rke2r1 (637e8a38334f603b60650b30547252a5c461fa0d)
go version go1.20.13 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux redacted 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

- 3 Control Plane Nodes
- 3 Worker nodes

**Describe the bug:**

- I follow the upgrade process using the installation script as specified in: #https://docs.rke2.io/upgrade/manual_upgrade#upgrade-rke2-using-the-installation-script 
- Restart the rke2-agent/server using systemd.
- restart works fine and kubectl shows that the cluster is upgraded. however if i do a systemctl status rke2-agent i see this output:
```shell
● rke2-agent.service - Rancher Kubernetes Engine v2 (agent)
     Loaded: loaded (/usr/local/lib/systemd/system/rke2-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-03-07 19:24:53 UTC; 6min ago
       Docs: https://github.com/rancher/rke2#readme
    Process: 2012852 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 2012855 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 2012857 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 2012858 (rke2)
      Tasks: 87
     Memory: 3.3G
     CGroup: /system.slice/rke2-agent.service
             ├─   1531 /var/lib/rancher/rke2/data/v1.24.7-rke2r1-bd84af53feb9/bin/containerd-shim-runc-v2 -namespace k8s.io -id 344b1e6d488>
             ├─   1559 /var/lib/rancher/rke2/data/v1.24.7-rke2r1-bd84af53feb9/bin/containerd-shim-runc-v2 -namespace k8s.io -id 003f7d269af>
             ├─1949222 /var/lib/rancher/rke2/data/v1.24.7-rke2r1-bd84af53feb9/bin/containerd-shim-runc-v2 -namespace k8s.io -id 7639284389d>
             ├─1952227 /var/lib/rancher/rke2/data/v1.24.7-rke2r1-bd84af53feb9/bin/containerd-shim-runc-v2 -namespace k8s.io -id 53b5f5bd46d>
             ├─2012858 /usr/local/bin/rke2 agent
             ├─2012874 containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state >
             └─2012952 kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins --file-check-frequency=5s --sync-frequency=30s --address=>
``` 
Right now the node is cordoned off. If I uncordon it, new containers spin up from the new data dir ```v1.26.13-rke2r1-348d76d5e67c```

i can make these go away by performing a cordon --> upgrade --> rke2-killall.sh --> startup rke2

**Steps To Reproduce:**
- Installed RKE2: 
RKE2 is installed using the shell installation script as specified in #https://docs.rke2.io/install/quickstart

Reproduce the issue:
- upgrade the rke2 instance. in my case i went from 1.24.7 to 1.25.16 to 1.26.13 and then to 1.27.11
- 
**Expected behavior:**

after upgrade and restarting rke2 all containers should be started from the upgraded directory.

**Actual behavior:**
Some containers linger on after the upgrade even though kubectl indicates that the upgrade is a success.

**Additional context / logs:**
also noticeable is that the persisting containers belong to the original version from which the upgrade process was started. the in between versions do not persist which is as per expectation.

**Comment by brandond** [comment]
Note that the only thing actually left over from the previous version of rke2 is the runc stub that is used to manage the container across restarts of the containerd process.

Containers are intentionally left running when RKE2 is restarted, including when RKE2 is restarted for an upgrade. Containers started prior to the upgrade, whose configuration is not affected by the upgrade, will continue to run until some external change requires them to be stopped and/or restarted.

If you want to see all pods restarted during the upgrade, you can do one or more of:
* drain the node prior to upgrading
* run the rke2-killall.sh script after upgrading, and restart the service
* restart the node after upgrading.

**Comment by sibzz** [comment]
thanks for the clarification. I understand i can safely ignore any container that keeps running after the upgrade.
