### ISSUE TITLE
RKE2 error- Waiting for API server to become available Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server

### ISSUE THREAD

**Issue by Balakumaran-07** [rancher/rke2#5654]
**Environmental Info:**
RKE2 Version: 
 v1.27.12

Node(s) CPU architecture, OS, and Version: 
 ubuntu 22.04

Cluster Configuration:
 2 Servers 1 HA 

**Describe the bug:**
 K8 cluster is not accessible due to API server and ETCD database is connecting facing an error. I have attached the logs screenshot. 

**Steps To Reproduce:**
  The k8 cluster should be accesssible.
![Screenshot from 2024-03-29 20-21-18](https://github.com/rancher/rke2/assets/77376584/802236d7-432f-464f-ab83-c56ac0d7b778)
![image](https://github.com/rancher/rke2/assets/77376584/da694f70-f283-4b6d-9e01-413f3ffdad13)
 
- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Screenshots from `systemctl status` are not logs. Please attach the actual output of `journalctl -u rke2-server` and the contents of `/var/log/pods`. 

> Cluster Configuration:
> 2 Servers 1 HA

Note that a two-server cluster does not provide HA. You need an odd number of servers running etcd to provide quorum. In a two-server cluster, an outage on either node will prevent the other node from working.

**Comment by Balakumaran-07** [comment]
journalctl -u rke2-server- Logs of the rke2 on the day of error 
[rke2_log.txt](https://github.com/rancher/rke2/files/14819073/rke2_log.txt)

Contents of /var/log.pods/
[pods.txt](https://github.com/rancher/rke2/files/14818983/pods.txt)

**Comment by brandond** [comment]
I would need to see the actual etcd pod logs (`/var/log/pods/kube-system_etcd-rke2-master02/*`), not just a list of what directories exist under /var/log/pods.

The rke2-server logs you shared suggests that the other two servers were shut down or restarted and were unreachable for several minutes:
```
Mar 23 01:14:51 rke2-master02 rke2[3135089]: time="2024-03-23T01:14:50+05:30" level=warning msg="Proxy error: read failed: tunnel disconnect"
Mar 23 01:14:53 rke2-master02 rke2[3135089]: time="2024-03-23T01:14:50+05:30" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Mar 23 01:15:14 rke2-master02 rke2[3135089]: time="2024-03-23T01:15:14+05:30" level=error msg="Failed to check local etcd status for learner management: failed to dial endpoint https://127.0.0.1:2379 with maintenance client: context deadline exceeded"
Mar 23 01:15:17 rke2-master02 rke2[3135089]: time="2024-03-23T01:15:17+05:30" level=info msg="Stopped tunnel to 46.250.239.68:9345"
Mar 23 01:15:18 rke2-master02 rke2[3135089]: time="2024-03-23T01:15:17+05:30" level=info msg="Proxy done" err="context canceled" url="wss://46.250.239.68:9345/v1-rke2/connect"
Mar 23 01:15:21 rke2-master02 rke2[3135089]: time="2024-03-23T01:15:21+05:30" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Mar 23 01:15:26 rke2-master02 rke2[3135089]: time="2024-03-23T01:15:25+05:30" level=warning msg="Proxy error: read failed: read tcp 46.250.239.68:60534->10.42.1.239:10250: read: connection reset by peer"
Mar 23 01:16:20 rke2-master02 rke2[3135089]: time="2024-03-23T01:16:19+05:30" level=info msg="Stopped tunnel to 46.250.239.68:9345"

Mar 23 01:17:56 rke2-master02 rke2[3135089]: time="2024-03-23T01:17:56+05:30" level=info msg="Handling backend connection request [rke2-master02]"
Mar 23 01:17:57 rke2-master02 rke2[3135089]: time="2024-03-23T01:17:57+05:30" level=info msg="Handling backend connection request [rke2-master01]"
```
