### ISSUE TITLE
Unable to restore cluster from snapshot, Failed to validate golang version

### ISSUE THREAD

**Issue by Mikrz** [rancher/rke2#5655]
**Environmental Info:**
RKE2 Version: 

rke2 version dev (HEAD)
go version go1.21.7

Node(s) CPU architecture, OS, and Version: 

Linux host.name.local 6.7.9-1-default #1 SMP PREEMPT_DYNAMIC Thu Mar  7 06:07:11 UTC 2024 (6049de6) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers, though can't get the first to work

**Describe the bug:**

Attempting a `--cluster-reset` using the `--cluster-reset-restore-path` fails with the following error:
```
FATA[0020] Failed to validate golang version: kubernetes golang build version not set - see 'golang: upstream version' in https://github.com/kubernetes/kubernetes/blob/dev/build/dependencies.yaml
```

**Steps To Reproduce:**

- Installed RKE2 using `stable` or `latest` release
- Attempt restoration from etcd snapshot using `rke2 server --cluster-reset --cluster-reset-restore-path=./path/to/snapshots`
- Get error shown above

**Expected behavior:**

No FATAL errors, and successful snapshot restoration.

**Actual behavior:**

Snapshot restoration fails, and the cluster appears to be fully reset as if brand-new.

**Additional context / logs:**

The error seems to stem from [this line](https://github.com/rancher/rke2/blob/c5abf84257c0c92f9b33330b8529d8a8350ea522/Dockerfile#L1) as the listed path in the error no longer exists on the upstream Kubernetes repo, leading to [this line](https://github.com/rancher/rke2/blob/c5abf84257c0c92f9b33330b8529d8a8350ea522/scripts/version.sh#L71) to fail to evaluate. This appears to have been added 4 years ago, so this is likely due to a change on the upstream Kubernetes repo's apparent removal of the `dev` branch.

**Comment by brandond** [comment]
> rke2 version dev (HEAD)
> go version go1.21.7
> FATA[0020] Failed to validate golang version: kubernetes golang build version not set - see 'golang: upstream version' in https://github.com/kubernetes/kubernetes/blob/dev/build/dependencies.yaml

This message indicates you're not building RKE2 correctly, ref: https://github.com/k3s-io/k3s/pull/9054

If compiling your own builds of RKE2, please make sure you're using the build scrips in a properly configured environment.

**Comment by Mikrz** [comment]
@brandond I am not building rke2 myself, I was using the install script as specified in the quick start documentation, the one found at https://get.rke2.io

I found the message you listed, which is why I went looking in the build configurations in this repo, and found the linked lines referencing an nonexistent `dev` tag/branch on the upstream kubernetes repo. If you follow the link int he error, it provides a 404, and if you follow the `DEPENDENCIES_URL` link with the appropriate `KUBERNETES_VERSION` filled in (dev, based on the Dockerfile), it also 404's. This is almost certainly *not* intended.

**Comment by brandond** [comment]
Can you confirm the output of `rke2 --version` and `which rke2`, as well as the output you see when running the install script? No released version of rke2 should ever identify as `dev`.

**Comment by Mikrz** [comment]
Perhaps this is related to how install is done for MicroOS? I checked on my other nodes and they are successfully installing non-dev versions. They also produce slightly different output, as the other two use DNF for installation, one being AlmaLinux 9 and the other is Fedora Server 39.

```
archon:~ # curl -sfL https://get.rke2.io | sh -
[WARN]  /usr/local is read-only or a mount point; installing to /opt/rke2
[INFO]  finding release for channel stable
[INFO]  using v1.27.12+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.27.12+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.27.12+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /opt/rke2
[INFO]  updating tarball contents to reflect install path
[INFO]  moving systemd units to /etc/systemd/system
[INFO]  install complete; you may want to run:  export PATH=$PATH:/opt/rke2/bin
archon:~ # which rke2
/usr/bin/rke2
archon:~ # rke2 --version
rke2 version dev (HEAD)
go version go1.21.7
```

Here is some example output from the Fedora system:
```
❯ curl -sfL https://get.rke2.io | sh -
[INFO]  finding release for channel stable
[INFO]  using 1.27 series from channel stable
Error: No matching Packages to list
Last metadata expiration check: 0:00:01 ago on Sun 31 Mar 2024 05:28:44 PM.
Dependencies resolved.
========================================================================================== Package         Arch       Version                    Repository                    Size
==========================================================================================Downgrading:
 rke2-common     x86_64     1.27.12~rke2r1-0.el7       rancher-rke2-1.27-stable      25 M
 rke2-server     x86_64     1.27.12~rke2r1-0.el7       rancher-rke2-1.27-stable     4.5 k

Transaction Summary
==========================================================================================Downgrade  2 Packages

Total download size: 25 M
Downloading Packages:
(1/2): rke2-server-1.27.12~rke2r1-0.el7.x86_64.rpm         14 kB/s | 4.5 kB     00:00
(2/2): rke2-common-1.27.12~rke2r1-0.el7.x86_64.rpm         10 MB/s |  25 MB     00:02
------------------------------------------------------------------------------------------Total                                                      10 MB/s |  25 MB     00:02     Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                  1/1   Downgrading      : rke2-common-1.27.12~rke2r1-0.el7.x86_64                          1/4   Downgrading      : rke2-server-1.27.12~rke2r1-0.el7.x86_64                          2/4   Running scriptlet: rke2-server-1.27.12~rke2r1-0.el7.x86_64                          2/4   Running scriptlet: rke2-server-1.29.3~rke2r1-0.el7.x86_64                           3/4   Cleanup          : rke2-server-1.29.3~rke2r1-0.el7.x86_64                           3/4   Running scriptlet: rke2-server-1.29.3~rke2r1-0.el7.x86_64                           3/4   Running scriptlet: rke2-common-1.29.3~rke2r1-0.el7.x86_64                           4/4   Cleanup          : rke2-common-1.29.3~rke2r1-0.el7.x86_64                           4/4   Running scriptlet: rke2-common-1.29.3~rke2r1-0.el7.x86_64                           4/4   Verifying        : rke2-common-1.27.12~rke2r1-0.el7.x86_64                          1/4   Verifying        : rke2-common-1.29.3~rke2r1-0.el7.x86_64                           2/4   Verifying        : rke2-server-1.27.12~rke2r1-0.el7.x86_64                          3/4   Verifying        : rke2-server-1.29.3~rke2r1-0.el7.x86_64                           4/4 
Downgraded:
  rke2-common-1.27.12~rke2r1-0.el7.x86_64     rke2-server-1.27.12~rke2r1-0.el7.x86_64

Complete!
❯ which rke2                                                                              /usr/bin/rke2
❯ rke2 --version                                                                          rke2 version v1.27.12+rke2r1 (25b27b4e4709a2ac4c550609ad730a9e172d110a)
go version go1.21.8 X:boringcrypto
```

**Comment by Mikrz** [comment]
I just noticed the path is different than what the installer is using, so I'm going to try to determine where the usr located rke2 came from. I know I didn't install a custom built version of my own though.

**Comment by Mikrz** [comment]
I just noticed the path is different than what the installer is using, so I'm going to try to determine where the usr located rke2 came from. I know I didn't install a custom built version of my own though.

Edit: so it seems the rke2 release available through zypper is the culprit. It must've been installed during previous experimentation, though I'm not sure why *that one* would be built wrong.

**Comment by brandond** [comment]
> Edit: so it seems the rke2 release available through zypper is the culprit. It must've been installed during previous experimentation, though I'm not sure why that one would be built wrong.

Yes, that's likely the cause of your problem. We're aware that other teams have tried to distribute their own modified builds of RKE2; the added check that you're seeing fail is an attempt to ensure that these builds observe at least SOME of the correct packaging processes. I assume that removing the zypper package and modifying your $PATH as suggested by the install script resolved your issue?

**Comment by Mikrz** [comment]
Yes, it appears to have resolved this issue. Thank you for your quick responses. I'll see if it's worth putting in a report for wherever the broken package came from for the repo, to ideally avoid you having any other reports of this issue.
