### ISSUE TITLE
Flannel-windows uses an old way to call host-local

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5662]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

We are calling host-local with v0.2.0 which is pretty old. Besides, we were creating a different host-local network (vxlan0) instead of using the flannel one for Windows (flannel.4096) 

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

The directory `/var/lib/network/cni/` only contains one directory

**Actual behavior:**

The directory `/var/lib/network/cni/` contains two directories

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
# Validation on master branch with commit 9a8df95e

Followed the steps mentioned here: https://github.com/rancher/rke2/issues/5662#issue-2220973885

## Replication
```
rke2 -v
rke2 version v1.29.3+rke2r1 (1c82f7ed292c4ac172692bb82b13d20733909804)
go version go1.21.8 X:boringcrypto
```
- In Windows agent
```
PS C:\Users\Administrator> ls C:\var\lib\cni\networks\


    Directory: C:\var\lib\cni\networks


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/12/2024   3:26 AM                vxlan0
```
- Logs
```
{Reserved VIP for kube-proxy: xx.xx.1.2}
...
{Reserving an IP on flannel HNS network for kube-proxy source vip}
```

## Validation
```
rke2 -v
rke2 version v1.29.3+dev.9a8df95e (9a8df95e4d520a5b969a695211163c69c0da3d9e)
go version go1.21.8 X:boringcrypto
```
- In Windows agent
```
PS C:\Users\Administrator> ls C:\var\lib\cni\networks\


    Directory: C:\var\lib\cni\networks


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/12/2024   3:43 AM                flannel.4096
```
- Logs
```
{Reserved VIP for kube-proxy: xx.xx.1.2}
...
{Reserving an IP on flannel HNS network for kube-proxy source vip}
```
