### ISSUE TITLE
Calico-node crashing on RKE2 1.28.8 running on ARM64

### ISSUE THREAD

**Issue by bvankampen** [rancher/rke2#5663]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.8+rke2r1 (42cab2f61939504cb17073e47deaea0b29fe2c1b)
go version go1.21.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux pi-5 6.6.17-v8-16k+ #1735 SMP PREEMPT Wed Feb 21 14:45:17 GMT 2024 aarch64 GNU/Linux

Cluster Configuration:
Single Node

**Describe the bug:**
Calico-node pod crashes, log entry
```
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)
calico-node: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
Calico node failed to start
```

**Steps To Reproduce:**
Install RKE2 v1.28.8 on a ARM64 node.

**Additional context / logs:**
Probably upstream issue https://github.com/projectcalico/calico/issues/8407 fixed in ` v3.27.3` RKE2 is using `docker.io/rancher/mirrored-calico-node:v3.27.2`

**Comment by manuelbuil** [comment]
Yes, the issue you link seems like the most likely cause. We must update to Calico `v3.27.3`

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  rke2 version v1.28.8+dev.0b0069ad (0b0069adc8d228e6ef9b2f14b5e2af5426028f12)



```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu   
ARM

*Cluster Configuration:*
-1 node 
 
 
## Steps to validate the fix
1. start rke2 with calico cni
2. get logs from calico node
3. Validate that has no error
 


 
 
## **Reproduction Issue:**
<details>

``` 
 
 
 
 
```

 
## **Validation Results:**
<details>


``` 
 $ k logs calico-node-bnkh7 -n calico-system | grep "failed to start"
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)


$ k get pods -A
NAMESPACE         NAME                                                                  READY   STATUS             RESTARTS         AGE
calico-system     calico-kube-controllers-5f6cc89c65-hnwxq                              1/1     Running            0                30m
calico-system     calico-node-bnkh7                                                     1/1     Running            0                30m
calico-system     calico-node-df5f9                                                     1/1     Running            0                28m
calico-system     calico-typha-5c6bb69956-t5bbh                                         1/1     Running            0                30m

$ k get nodes 
NAME                                         STATUS   ROLES                       AGE   VERSION
ip-1 .us-east-2.compute.internal   Ready    control-plane,etcd,master   32m   v1.28.8+rke2r1
ip-1 .us-east-2.compute.internal   Ready    <none>                      29m   v1.28.8+rke2r1


```
