### ISSUE TITLE
Support for etcd-only nodes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#567]
In order to improve our integration with Rancher we want to support etcd-only nodes with RKE2.
We also want to do this for K3s (https://github.com/k3s-io/k3s/issues/2635)

**Comment by ShylajaDevadiga** [comment]
Related issue to remove static pods https://github.com/rancher/rke2/issues/886

**Comment by ShylajaDevadiga** [comment]
Validated in rke2 v1.21.0-dev+e8b3547b as per test plan 

1. Cluster Config
- Node1 - etcd only
- Node2 - all roles except no etcd
- Node3 - all roles
2. Join node4 with all roles
3. Remove etcd roles from node4
4. Add back etcd role to node4
5. disable api server on node4
6. disable-controller-manager on node4
7. reboot etcd-only node
8. reboot all nodes
9. Join worker node to the cluster
