### ISSUE TITLE
RKE2 error- Waiting for API server to become available Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server

### ISSUE THREAD

**Issue by yoges24** [rancher/rke2#5681]
**Environmental Info:**
RKE2 Version: 
 v1.27.11

Node(s) CPU architecture, OS, and Version: 
 Ubuntu 22.04

Cluster Configuration:
 1 HA(LB) with 3 Master Nodes

**Describe the bug:**
 Can't access the k8s cluster
I initially set up a Kubernetes (k8s) cluster using three nodes: one for high availability load balancing (HA LB) and two for master nodes. However, I encountered an issue where the API server was not becoming available. When checking the status using systemctl status rke2-server.service, I discovered that the problem originated from the first master node. I had taken the token from this master node, and as a result, the second master node was stuck in a ‘loaded activating’ state.

To troubleshoot, I uninstalled the RKE2 server on the first master node and then reinstalled it, resulting in a newly created server. However, communication between the first and second master nodes remains problematic. I’ve also created a /etc/rancher/rke2/config.yaml file on both master nodes, but the issue persists. Even after adding a new node to the k8s cluster for high availability, the problem remains unresolved. I would appreciate your assistance in resolving this issue.
**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**
 I have deployed some application on the server. I can't access the application using kubectl but its running background. 

**Actual behavior:**
 The k8 cluster must be accessible without any data loss.

**Additional context / logs:**

[rke2.zip](https://github.com/rancher/rke2/files/14892642/rke2.zip)

**Comment by pamanseau** [comment]
I have the same issue after upgrading to RANCHER 2.8.3 and installing a new cluster RKE2 1.27 or 1.28.
When installing with the `curl -sfL https://get.rke2.io | sh -` it's working.

IMO, it's a bug in the `system-agent-install.sh` from RANCHER 2.83.

**Comment by pamanseau** [comment]
I opened an issue on the [Rancher Github issue #45035](https://github.com/rancher/rancher/issues/45035)

**Comment by brandond** [comment]
This is a configuration error on your part, see https://github.com/rancher/rancher/issues/45035#issuecomment-2045887324
