### ISSUE TITLE
Update to newer ingress-nginx 1.9.6

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#5684]
**Is your feature request related to a problem? Please describe.**

Our ingress-nginx version is now 6 months old. 1.9.6 came out in Feburary and 1.10.0 is now out. 

**Describe the solution you'd like**

We should move to 1.9.6.

**Describe alternatives you've considered**

We are not ready to move to 1.10.0 which update the internal nginx engine to v1.25, and reworked the build system substantially. 
**Additional context**

**Comment by endawkins** [comment]
### Validated on master using commit 95e13dc | version 1.29

```
Cluster nodes:
 ip-[redacted].us-east-2.compute.internal   Ready   control-plane,etcd,master   68s   v1.29.3+rke2r1   [redacted]   [redacted]   SUSE Linux Enterprise Server 15 SP4   5.14.21-150400.22-default   containerd://1.7.11-k3s2
```

```
Command:
  kubectl get node -o yaml  --kubeconfig=/tmp/elwoodrke2val129_kubeconfig  | grep 'nginx-ingress-controller' -A1
 ---------------------
 Assertion:
 1.9.6
 ----------------------
 Matched with result:
 - docker.io/rancher/nginx-ingress-controller@sha256:[redacted]
       - docker.io/rancher/nginx-ingress-controller:nginx-1.9.6-hardened1
       sizeBytes: 325093593
```
