### ISSUE TITLE
RKE2-windows flannel not retrying

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5702]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

When the Windows node has only one interface and we set up rke2-flannel, we will lose connectivity to the node for some seconds. It varies between 5 to 25 seconds. That's how windows works when binding an hns overlay network to a physical interface. In some environments, if it takes too long, flanneld exits with an error because it can't contact kube-api anymore

JIRA: SURE-8128

**Steps To Reproduce:**

- Installed RKE2:
Not always reproducible. Deploy rke2 on a windows agent with only one interface and check the rke2 logs, you will see:
`Flanneld has an error:`
And we never retry.
If you can't reproduce it, just verify that flanneld is using v0.25.1:

```
C:\var\lib\rancher\rke2\bin\flanneld.exe --version
v0.25.1
```

**Expected behavior:**

As we do with Calico, we retry again because it could be fine that flanneld must be restarted

**Actual behavior:**

We never retry and flanned dies forever. The workaround is restarting the rke2 service even though the rest of components work correctly

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
## Validation on master branch with commit 95e13dc6

Unable to replicate the issue, validated the flannel version in Windows node

### Validation
```
PS C:\Users\Administrator> C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.29.3+dev.95e13dc6 (95e13dc62fdbda33de2c709f1149b0c361d920b9)
go version go1.21.8

PS C:\Users\Administrator> C:\var\lib\rancher\rke2\bin\flanneld.exe --version
v0.25.1
```

## Validation on release-1.28 branch with commit 04086ee5

Unable to replicate the issue, validated the flannel version in Windows node
### Validation
```
PS > C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.28.8+dev.04086ee5 (04086ee5e83a876f6576418c7fa4ff9ea5e1caf7)
go version go1.21.8

PS > C:\var\lib\rancher\rke2\bin\flanneld.exe --version
v0.25.1
```

## Validation on release-1.27 branch with commit 191329a6

Unable to replicate the issue, validated the flannel version in Windows node
### Validation
```
PS > C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.27.12+dev.191329a6 (191329a6e3faac429ec145523e8d84c1b3be81fe)
go version go1.21.8

PS > C:\var\lib\rancher\rke2\bin\flanneld.exe --version
v0.25.1
```
