### ISSUE TITLE
RKE2-windows failing to reserve a vip for kube-proxy when restarting rke2

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5704]
**Environmental Info:**
RKE2 Version: 

Use cni flannel

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

One windows node

**Describe the bug:**

If we deploy rke2 with Flannel CNI, it reserves an IP for kube-proxy, which is consumed by kube-proxy using the flag `source-vip`. If we stop the rke2 service in Windows and, without deleting anything, start it again, rke2 is unable to detect that an IP was already reserved for kube-proxy and it fails when trying to reserve a new one with the error:
```
4/11/2024 3:18:04 PM Failed to execute host-local.exe
4/11/2024 3:18:04 PM This is the output: {
                         "code": 999,
                         "msg": "failed to allocate for range 0: 10.42.3.2 has been allocated to dummy, duplicate allocation is not allowed"
                     }
```

**Steps To Reproduce:**

- Installed RKE2: 
1 - Deploy rke2 with flannel on windows. 
2 - Wait for the rke2 logs to state `Running RKE2 kube-proxy` and verify it has an IP after the flag `--source-vip`
3 - `Stop-Service rke2`
4 - `Start-Service rke2`
5 - Check the logs. You'll see the above error and `--source-vip` will be empty

**Expected behavior:**

We check if there was an already reserved source-vip and then use that one

**Actual behavior:**

The code tries to reserve a new IP but it detects that there is already one with the same data

**Additional context / logs:**

**Comment by mdrahman-suse** [comment]
# Validation on master branch with commit 95e13dc6

## Environment
```
1 Linux server and 1 Windows server
```
Followed the steps mentioned here: https://github.com/rancher/rke2/issues/5704#issue-2237996688

## Replication
```
C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.29.3+rke2r1 (1c82f7ed292c4ac172692bb82b13d20733909804)
go version go1.21.8
```
- Logs before `Stop-Service rke2`
```
...
{Running RKE2 kube-proxy [--bind-address=xxx.xx.xx.39 --enable-dsr=true --feature-gates=WinDSR=true --network-name=flannel.4096 --source-vip=xx.xx.x.2 --cluster-cidr=xx.xx.x.x/xx
...
{Reserved VIP for kube-proxy: xx.xx.x.2}
...
```
- Logs after `Stop-Service rke2` and `Start-Service rke2`
```
...
{Running RKE2 kube-proxy [--bind-address=xxx.xx.xx.39 --enable-dsr=true --feature-gates=WinDSR=true --network-name=flannel.4096 --source-vip= --cluster-cidr=xx.xx.x.x/xx
...
{Reserved VIP for kube-proxy: }
{Failed to reserve VIP for kube-proxy: exit status 1}
{This is the output: {
    "code": 999,
    "msg": "failed to allocate for range 0: 10.42.1.2 has been allocated to dummy, duplicate allocation is not allowed"
}}
{Failed to execute host-local.exe, error=exit status 1}
```

## Validation
```
C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.29.3+dev.95e13dc6 (95e13dc62fdbda33de2c709f1149b0c361d920b9)
go version go1.21.8
```
- Log before `Stop-Service`
```
...
{Running RKE2 kube-proxy [--bind-address=xxx.xx.xx.39 --enable-dsr=true --feature-gates=WinDSR=true --network-name=flannel.4096 --source-vip=xx.xx.x.2 --cluster-cidr=xx.xx.x.x/xx
...
{Reserved VIP for kube-proxy: xx.xx.x.2}
...
```
- Log after `Stop-Service` and `Start-Service`
```
...
{Running RKE2 kube-proxy [--bind-address=xxx.xx.xx.39 --enable-dsr=true --feature-gates=WinDSR=true --network-name=flannel.4096 --source-vip=xx.xx.x.2 --cluster-cidr=xx.xx.x.x/xx
...
{Reserved VIP for kube-proxy: xx.xx.x.2}
```
