### ISSUE TITLE
Support configurable taints and tolerations

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#572]
- piped through to helm charts
- must be pass through rancher cluster config
- does it affect static pods at all?﻿

This topic may require more design discussion, as necessary.
This is also needed in K3s (see https://github.com/k3s-io/k3s/issues/2637)

**Comment by galal-hussein** [comment]
linking the adding tolerations issue to this one https://github.com/rancher/rke2/issues/1061

**Comment by davidnuzik** [comment]
I'm going to close this issue as https://github.com/rancher/rke2/issues/1061 captures what we needed here. Confirmed that issue covers what product management needed.
