### ISSUE TITLE
[Release-1.28] - RKE2-windows failing to reserve a vip for kube-proxy when restarting rke2

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5736]
Backport fix for RKE2-windows failing to reserve a vip for kube-proxy when restarting rke2

* #5704

**Comment by mdrahman-suse** [comment]
# Validation on release 1.28 branch with commit 04086ee5

Followed the steps mentioned here: https://github.com/rancher/rke2/issues/5704#issuecomment-2060287983
Observed the same issue on replication with v1.28.8+rke2r1

## Validation
```
C:\usr\local\bin\rke2.exe -v
rke2.exe version v1.28.8+dev.04086ee5 (04086ee5e83a876f6576418c7fa4ff9ea5e1caf7)
go version go1.21.8

```
- Event log before and after `Restart-Service`
```
...
{Running RKE2 kube-proxy [--bind-address=xxx.xx.xx.39 --enable-dsr=true --feature-gates=WinDSR=true --network-name=flannel.4096 --source-vip=xx.xx.x.2 --cluster-cidr=xx.xx.xx.x/xx
...
{Reserved VIP for kube-proxy: xx.xx.x.2}
```
