### ISSUE TITLE
Vsphere-csi updates to 3.1.2-rancher300

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#5765]
update rke2 to pull through the new rke2-charts updates https://github.com/rancher/rke2-charts/pull/441, the update will fix the version for csi chart to 3.1.2-rancher3 and adds a new snapshotter image

**Comment by rancher-max** [comment]
Performed same validations as in https://github.com/rancher/rke2/issues/5768#issuecomment-2059728779 and https://github.com/rancher/rke2/issues/5768#issuecomment-2067015500, with the same results, but using `master` branch commitid `b6a72c9061853ae4642353cc5b8b05058b9acdad`
