### ISSUE TITLE
[Release-1.28] - Vsphere-csi updates to 3.1.2-rancher300

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#5767]
Backport fix for Vsphere-csi updates to 3.1.2-rancher300

* #5765

**Comment by rancher-max** [comment]
Performed same validations as in https://github.com/rancher/rke2/issues/5768#issuecomment-2059728779 and https://github.com/rancher/rke2/issues/5768#issuecomment-2067015500, with the same results, but using `release-1.28` branch commitid `6504442cfff900b23c43fdd8464c925213302893`
