### ISSUE TITLE
Can't create server annotation anymore v1.28

### ISSUE THREAD

**Issue by pstefka** [rancher/rke2#5776]
Seems the issue has been already fixed in upstream https://github.com/kubernetes/ingress-nginx/issues/10543 

Solution in the linked post is to update nginx chart to 4.9, which is already available in the rke2 charts repo

Will the fix be backported to RKE2 v1.28 ?

**Environmental Info:**
RKE2 Version: v1.28.8+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux svc-rancher-stable-infra-util-control-plane-etcd-4f5b7d31-ftjlk 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 22.04

Cluster Configuration:
rke2-ingress-nginx 4.8.200 = nginx 1.9.3

**Describe the bug:**
Can't create server snippets although snippets are enabled in the rke2 ingress nginx helm chart

**Steps To Reproduce:**
Create an ingress with nginx.ingress.kubernetes.io/server-snippet  or nginx.ingress.kubernetes.io/configuration-snippet annotation

**Expected behavior:**
Snippets are accepted and work

**Actual behavior:**
Ingress is rejected with an error message:

"validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/server-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator

**Additional context / logs:**

**Comment by brandond** [comment]
Snippet annotations are intentionally disabled in the default chart values. If you want to re-enable them, you may do so using a HelmChartConfig resource as documented at https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig

https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.8.200/values.yaml#L76-L80

**Comment by pstefka** [comment]
@brandond the problem is (as written in the bug report) that although the snippet annotations are enabled using the appropriate helm chart values, their usage end in an error. This  problem has been introduced in Nginx 1.9, meaning chart version 4.8.200 is affected. Upgrading to chart version 4.9.1 should help with the fix.. the question is how

**Comment by brandond** [comment]
I don't see anything in that issue that indicates there was a bug that was fixed regarding annotations not being enabled even if set in the config. The only note there is confirming what I said, which is that snippet annotations are disabled by default. The actual problem in that issue was user error - they were setting `controller.config.allowSnippetAnnotations` instead of `controller.allowSnippetAnnotations`

**Comment by pstefka** [comment]
You are correct on the linked bugreport, there was a misunderstanding on our side.

But as already mentioned we explicitly enabled the snippet annotations (as mentioned in the bugreport).

However one thing I've failed to mention is that we use Rancher to provision RKE2, and with Rancher 2.8.3 and RKE2 v1.28.8 it seems on one occasion, Rancher didn't correctly set the HelmChartConfig manifest for rke2-ingress-nginx in /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml. The file didn't contain a rke2-ingress-nginx HelmChartConfig at all, only the rke2-cilium one. Luckily this was a fresh install, so we reinstalled it and the new downstream does contain the HelmChartConfig and everything works correctly. We didn't see any problem on the Rancher side, so we don't know why it wasn't working previously.

Thank you for you time @brandond !

**Comment by laralar** [comment]
Hello.

I am also using rancher to provision RKE2, I am very new to the whole K8s, and it is not clear for me how to enable the snippets using when using rancher.  I am just trying to deploy nextcloud on it. and it seems there should be enabled. 

So.. I see the option to edit as yaml, is that where I should put the options for enabling the snippets?

thanks
