### ISSUE TITLE
[1.30] Moved to fatal error for old `cis-1.23` profile flag.

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#5780]
**Is your feature request related to a problem? Please describe.**

In line with our deprecation of the old `cis-1.23` flag in favor of the generic `cis` flag, we need to move from just a warning to a fatal error for the `profile: cis-1.23`

**Describe the solution you'd like**

A clear fatal error explaining what went wrong with the `cis-1.23` and to use the new `cis` value.

**Describe alternatives you've considered**

**Additional context**

**Comment by aganesh-suse** [comment]
### Verified with version: v1.30.0-rc1+rke2r1

## Environment Details
Cloud instance
OS: SLES 15 SP5

*Config.yaml:*

```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
profile: "cis-1.23"
```
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION='v1.30.0-rc1+rke2r1' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Follow https://docs.rke2.io/security/hardening_guide 
```
$ sudo useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
$ sudo cp -f /usr/local/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/60-rke2-cis.conf 
$ cat /etc/sysctl.d/60-rke2-cis.conf 
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
$ sudo systemctl restart systemd-sysctl 
```
4. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent

Verified that journal logs contained errors:
``` 
 time="2024-05-07T20:54:32Z" level=fatal msg="cis-1.23 profile is deprecated. Please use 'cis' instead."
```
