### ISSUE TITLE
Expose RKE2 metrics via supervisor port

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#5786]
In K3s, we are able to expose custom metrics via the kubelet's metrics registerer and gatherer, which can be easily scraped via `kubectl`: 
> `kubectl get --raw /api/v1/nodes/NODENAME/proxy/metrics`

Since RKE2 doesn't embed the Kubernetes components in the supervisor process like K3s does, custom metrics (such as those for spegel and cert expiration) are not currently exposed.

We should wire up the `/metrics` endpoint on the supervisor port. The agent's supervisor doesn't currently listen on this port unless Spegel is enabled, so we will probably need to refactor that a bit and add an agent flag to start that listener to expose metrics even if Spegel isn't enabled.

* This is required to publish the spegel image metrics for https://github.com/rancher/rke2/issues/5298
* This is required to publish the cert expiration metrics for https://github.com/rancher/rke2/issues/5620
* This is required to publish etcd snapshot metrics for https://github.com/rancher/rke2/issues/3110

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit 3aaa16c9b17da45e9f3475ba5011ed90a49a2e42
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
  
*Config.yaml:*

Server Node Configs:
```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
enable-pprof: true
supervisor-metrics: true
```

Agent node configs: 
```
token: xxxx
node-external-ip: 1.1.1.2
server: https://<server ip>:9345
enable-pprof: true
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='3aaa16c9b17da45e9f3475ba5011ed90a49a2e42' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Verify Cluster Status: 
```
kubectl get nodes -o wide
kubectl get pods -A
```
5. Verify with server and agent IPs for the curl urls on a server node: 
```
curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:9345/metrics
curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:9345/debug/pprof
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.30.1+dev.3aaa16c9 (3aaa16c9b17da45e9f3475ba5011ed90a49a2e42)
go version go1.22.2 X:boringcrypto
```
 

```
$ sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<agent_node_ip>:9345/debug/pprof/ 
*   Trying <agent_node_ip>:9345...
* connect to <agent_node_ip> port 9345 failed: Connection refused
* Failed to connect to <agent_node_ip> port 9345 after 0 ms: Connection refused
* Closing connection 0


$ sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<agent_node_ip>:9345/metrics 
*   Trying <agent_node_ip>:9345...
* connect to <agent_node_ip> port 9345 failed: Connection refused
* Failed to connect to <agent_node_ip> port 9345 after 0 ms: Connection refused
* Closing connection 0
```

The same works for querying all server nodes (Not providing output due to large size):
```
sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<server_node_ip>:9345/debug/pprof/ 

sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<server_node_ip>:9345/metrics 
```

**Comment by brandond** [comment]
There is a bug on the k3s code, the agents are listening on the apiserver port (6443), instead of the supervisor port (9345).

We'll have to bump this out and fix it in July.

**Comment by brandond** [comment]
Actually, this is breaking the embedded registry mirror on agents too... so it'll need to be fixed this release.

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit 7e788b736cc690d2ce520c17e34cefdfe7bbe2ce
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
  
*Config.yaml:*

Server Node Configs:
```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
enable-pprof: true
supervisor-metrics: true
```

Agent node configs: 
```
token: xxxx
node-external-ip: 1.1.1.2
server: https://<server ip>:9345
enable-pprof: true
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='7e788b736cc690d2ce520c17e34cefdfe7bbe2ce' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Verify Cluster Status: 
```
kubectl get nodes -o wide
kubectl get pods -A
```
5. Verify with server and agent IPs for the curl urls on a server node: 
```
curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:6443/metrics
curl -vks --cert /var/lib/rancher/k3s/server/tls/client-admin.crt --key /var/lib/rancher/k3s/server/tls/client-admin.key https://<server|agent ip>:6443/debug/pprof
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.30.2-rc3+rke2r1 (7e788b736cc690d2ce520c17e34cefdfe7bbe2ce)
go version go1.22.4 X:boringcrypto
```

Verified that querying all server/agent nodes works (Not providing output due to large size):
```
sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<server_node_ip>:9345/debug/pprof/ 

sudo curl -vks --cert /var/lib/rancher/rke2/server/tls/client-admin.crt --key /var/lib/rancher/rke2/server/tls/client-admin.key https://<server_node_ip>:9345/metrics 
```
