### ISSUE TITLE
rke2 upgrade rollback after reboot

### ISSUE THREAD

**Issue by codot-fr** [rancher/rke2#5793]
**Environmental Info:**
rke2 version v1.26.11+rke2r1 (7ee1cfc93db32d05f3270711b24c429515019e8a)
go version go1.20.11 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux k8s-orange-ctrl-f197b549-5znm2 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 3 agents

**Describe the bug:**
After performing the upgrade to the latest stable release using `curl -sL https://get.rke2.io | INSTALL_RKE2_CHANNEL=stable sh`, rke2 version report as rke2 version v1.27.12+rke2r1 (25b27b4e4709a2ac4c550609ad730a9e172d110a) /go version go1.21.8 X:boringcrypto.

Then I reboot and it shows as v1.26.11 again.

**Comment by brandond** [comment]
This is not something RKE2 would be doing for itself. Are you perhaps running RKE2 on a host with an immutable or transactional filesystem that is not getting committed before restarting?

**Comment by codot-fr** [comment]
Hello Brandon. I agree, it's weird. I would even happen without reboot, just after an rke2-server service restard.

I would even seen a discrepancy between the kube version in kubectl get nodes and the rke2 --version...

Anyway, the nodes are broken after many troubleshooting tries so I can't investigate the issue anymore.

Thanks.
