### ISSUE TITLE
flannel-v6.4096 interface is not deleted when running rke2-killall.sh

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5794]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

cni: flannel

**Describe the bug:**

After deploying rke2 with `cni: flannel` in a dual-stack environment, two interfaces get created `flannel.4096` and  `flannel-v6.4096`. When we execute `rke2-killall.sh`, the former gets removed but not the latter.

**Steps To Reproduce:**

- Installed RKE2: 
After deploying rke2 with `cni: flannel` in a dual-stack environment, two interfaces get created `flannel.4096` and  `flannel-v6.4096`. When we execute `rke2-killall.sh`, the former gets removed but not the latter.

**Expected behavior:**

Both interfaces get removed

**Actual behavior:**

**Additional context / logs:**

**Comment by rancher-max** [comment]
I am going to close this without explicit testing to save time for 1.30 validations. This is a small change to the killall script which is not affecting the product directly, plus we know based on the other tests around it previously that the changes made here are consistent with what has worked in the past. This is only a very minimal risk, so should be okay.
