### ISSUE TITLE
Service restarts take ~6m40s when using Kine/sqlite 

### ISSUE THREAD

**Issue by sdemura** [rancher/rke2#5807]
**Environmental Info:**
RKE2 Version: 1.29.4-rc1+rke2r1

Node(s) CPU architecture, OS, and Version: 

ubuntu 22.04, x85

Cluster Configuration:

Single node

**Describe the bug:**

I know I'm jumping the gun here, but I noticed that 1.29.4-rc1+rke2r1 landed and I'm very excited to see Kine support being added. I understand that the initial target for Kine support in RKE2 is for external HA database (postgres/mysql), but I am really looking forward to single node with kine/etcd. I understand that 'generally' the recommendation is to use k3s, but for our case we need some RKE2-only features, but want the ability to use kine/sqlite. I also understand the kine feature is not stable, but on recommendation from Rancher slack I'm opening a pro-active ticket.

In any event, I've been able to succesfully deploy RKE2 using Kine/sqlite by adding the config `datastore-endpoint: sqlite:///var/lib/rancher/rke2/server/db/rke2-sqlite.db`. The initial setup/install works as expected, but I've noticed an issue with restarting rke2-server service. If I run `systemctl restart rke2-server` it takes a long time. I've tried this multiple times, and each time the service restart takes around ~6m40s. The logs are chock full of:
```
Apr 19 03:34:27 jammy-01 rke2[1735185]: time="2024-04-19T03:34:27Z" level=info msg="Pod for kube-apiserver is synced"
Apr 19 03:34:31 jammy-01 rke2[1735185]: time="2024-04-19T03:34:31Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```

when this happens.
However, if I issue a systemctl restart rke2-server and follow up with a kill -9 $(pidof kube-apiserver) the service restarts very shortly after. It seems as if there's some internal timer to restart kube-apiserver after ~6m40s?. I've also noticed that if I let systemctl restart rke2-server do it's thing, after ~6m40s the pid of kube-apiserver indeed does change.
example:
```
sean@jammy-01:~$ pidof kube-apiserver
1733097
sean@jammy-01:~$ time sudo systemctl restart rke2-server && pidof kube-apiserver

real    6m39.124s
user    0m0.003s
sys     0m0.001s
1741042
```

issuing a restart and killing kube-apiserver shortly after.
```
sean@jammy-01:~$ cat kill.sh
#!/bin/bash

sleep 10
sudo kill -9 $(pidof kube-apiserver)
sean@jammy-01:~$ ./kill.sh &
[1] 1759136
sean@jammy-01:~$ time sudo systemctl restart rke2-server
[1]+  Done                    ./kill.sh

real    0m21.220s
user    0m0.006s
sys     0m0.005s
```

**Steps To Reproduce:**

- Installed RKE2 with option `datastore-endpoint: sqlite:///var/lib/rancher/rke2/server/db/rke2-sqlite.db`
- Issue `systemctl restart rke2-server`

**Expected behavior:**

- Expect rke2-server service to have restarted reasonably quickly.

**Actual behavior:**

- Restarts take 6m40s

**Additional context / logs:**

**Comment by brandond** [comment]
cc @vitorsavian

**Comment by sdemura** [comment]
FWIW, looks like a HUP works just as well as SIGKILL

**Comment by VestigeJ** [comment]
Presently A delay of ~7 minutes is observed from a systemctl restart of the service - ready to validate backports when they merge



##Environment Details
Reproduced using VERSION=v1.30.1+rke2r1
Validated using COMMIT=3c4642bd1ebef5b2deb6f701f6d76b0d78698184

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"

*Cluster Configuration:*
```
NAME             STATUS   ROLES                  AGE     VERSION
ip-1-1-1-1       Ready    control-plane,master   4h57m   v1.30.1+rke2r1
```

*Config.yaml:*

```
node-external-ip: 1.1.1.1
token: YOUR_TOKEN_HERE
write-kubeconfig-mode: 644
debug: true
embedded-registry: true
datastore-endpoint: sqlite:///var/lib/rancher/rke2/server/db/rke2-sqlite.db
```

<details><summmary><h4>steps</h4></summary>



```
$ curl https://get.rke2.io --output install-"rke2".sh
$ sudo chmod +x install-"rke2".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo mkdir -p /var/lib/rancher/rke2/server/db/
$ sudo touch /var/lib/rancher/rke2/server/db/rke2-sqlite.db
$ VERSION=v1.30.1+rke2r1
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh
$ go_rke2
$ set_kubefig
$ w2 kg no,po,svc -A
$ date;sudo systemctl restart rke2-server; date
--- log time here ---
$ kgn
$ COMMIT=3c4642bd1ebef5b2deb6f701f6d76b0d78698184
$ sudo INSTALL_RKE2_COMMIT=$COMMIT INSTALL_RKE2_EXEC=server ./install-rke2.sh
$ sudo systemctl restart rke2-server
$ date;sudo systemctl restart rke2-server; date;
```

**Results:**

$ date;sudo systemctl restart rke2-server
Tue 28 May 2024 10:01:11 PM UTC
----- elapsed time -----
$ date
Tue 28 May 2024 10:08:01 PM UTC

$ kgn
```
NAME             STATUS   ROLES                  AGE     VERSION
ip-1-1-1-1       Ready    control-plane,master   4h12m   v1.30.1+rke2r1
```

New behavior 

$ date;sudo systemctl restart rke2-server; date;
```
Tue 28 May 2024 10:48:59 PM UTC
Tue 28 May 2024 10:49:21 PM UTC
```

</details>
