### ISSUE TITLE
During execution of rke2-uninstall.sh, fapolicyd is activated even if it is disabled in systemd

### ISSUE THREAD

**Issue by burlyunixguy** [rancher/rke2#5809]
https://github.com/rancher/rke2/blame/1c82f7ed292c4ac172692bb82b13d20733909804/bundle/bin/rke2-uninstall.sh#L102

Can we can check the systemd status  prior to restarting fapolicyd?  The 'systemd restart fapolicyd' will will start fapolicyd even if it is disabled.  

`systemctl -q is-active && systemctl restart fapolicyd`   should do the job.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  rke2 version v1.30.1 (c727b365ea6cb0d8b70fdcaac648d79950b9591b)

```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
rhel    
AMD
 

*Cluster Configuration:*
-1 node server 
 
 

## Steps to validate the fix
1. Install  rke2
2. Install and enable fapolicyd
3. Run uninstall script
4. Validate that fapolicyd is disabled
 

 


 
 
## **Reproduction Issue:**
<details>

``` 
 rke2 version v1.30.1 (c727b365ea6cb0d8b70fdcaac648d79950b9591b)

$ sudo systemctl enable fapolicyd
$ sudo systemctl start fapolicyd
$ sudo systemctl stop fapolicyd
$ sudo systemctl status fapolicyd
 - dead

$ sudo /usr/local/bin/rke2-uninstall.sh

~$ sudo systemctl is-active  fapolicyd
active


```

 
## **Validation Results:**
<details>


``` 
   rke2 version v1.30.1 (c727b365ea6cb0d8b70fdcaac648d79950b9591b )

$ sudo systemctl enable fapolicyd
$ sudo systemctl start fapolicyd
$ sudo systemctl stop fapolicyd
$ sudo systemctl status fapolicyd
 - dead

$ sudo /usr/local/bin/rke2-uninstall.sh

~$ sudo systemctl is-active  fapolicyd
inactive
 

 ```
