### ISSUE TITLE
Official support for Amazon Linux 2

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rke2#5810]
**Is your feature request related to a problem? Please describe.**
Numerous customers have requested official support for Amazon Linux 2. 

**Describe the solution you'd like**
RKE2 works in Amazon Linux 2 fine, you just need to add '2023' to '/etc/os-release' and install things normally 

**Additional context**
https://gist.github.com/zackbradys/88096b6c5b8a77ff30386ea065068cf8

**Comment by zackbradys** [comment]
Additionally, the `install.sh` could be modified to automatically detect and better support AL2 (and AL2023).

**Comment by caroline-suse-rancher** [comment]
After speaking with product about this, we intend to pursue validation of Amazon Linux 2 in a coming release.

**Comment by zackbradys** [comment]
Great news! Thank you for working to support this @caroline-suse-rancher

For those looking for work around steps... https://gist.github.com/zackbradys/88096b6c5b8a77ff30386ea065068cf8

**Comment by aganesh-suse** [comment]
Related issues for history: 
https://github.com/rancher/rke2/issues/6354
https://github.com/rancher/rke2/issues/6521

**Comment by ShylajaDevadiga** [comment]
Versions and Validations to be covered for AL2

**Versions to be Validated**

v1.31.0+rke2r1
v1.30.4+rke2r1
v1.29.8+rke2r1
v1.28.13+rke2r1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Comment by aganesh-suse** [comment]
Pre-requisite step on Amazon Linux 2 setup to get selinux packages/policies setup: 
```
sudo amazon-linux-extras enable selinux-ng; sudo yum install selinux-policy-targeted -y
```

**Comment by brandond** [comment]
sounds like docs fodder!

**Comment by aganesh-suse** [comment]
After setting up with pre-requisite steps mentioned here: https://github.com/rancher/rke2/issues/5810#issuecomment-2332593009
Verified the tests on versions mentioned here: https://github.com/rancher/rke2/issues/5810#issuecomment-2332579324

Uninstall was still not working: https://github.com/rancher/rke2/issues/6521

**Comment by ShylajaDevadiga** [comment]
Closing as completed as uninstall issue mentioned above is fixed and validated. 
Issue to track documentation for pre-requisites https://github.com/rancher/rke2/issues/6979
