### ISSUE TITLE
[Release-1.28] - Unable to provision downstream cluster in Rancher

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#5820]
Backport fix for Unable to provision downstream cluster in Rancher

* #5819

**Comment by mdrahman-suse** [comment]
# Validation on RC v1.28.9-rc3+rke2r1

Followed similar setup and steps to validate the issue as mentioned here: https://github.com/rancher/rke2/issues/5819#issuecomment-2077420251

- Validated split-roles cluster with Rancher v2.8.3 and v1.28.9-rc3+rke2r1
