### ISSUE TITLE
[Release-1.27] - Unable to provision downstream cluster in Rancher

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#5821]
Backport fix for Unable to provision downstream cluster in Rancher

* #5819

**Comment by mdrahman-suse** [comment]
# Validation on RC v1.27.13-rc3+rke2r1

Followed similar setup and steps to validate the issue as mentioned here: https://github.com/rancher/rke2/issues/5819#issuecomment-2077420251

- Validated split-roles cluster provisioning on Rancher v2.7.12 with v1.27.13-rc3+rke2r1
- Validated split-roles cluster provisioning on Rancher v2.8.3 with v1.27.13-rc3+rke2r1
