### ISSUE TITLE
While using cni: flannel directory /etc/cni/net.d has no selinux context or policy

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#5839]
**Environmental Info:**
RKE2 Version: 
$ rke2 -v
rke2 version v1.29.3+rke2r1

Node(s) CPU architecture, OS, and Version: 
Red Hat Enterprise Linux 9.3

Cluster Configuration:
3 server 1 agent 

**Describe the bug:**
While using cni: flannel directory /etc/cni/net.d selinux context or policy is missing

**Steps To Reproduce:**
1. Install rke2 with cni: flannel on any rpm based OS

**Expected behavior:**
```
$ sudo ls -Z /etc/cni/net.d
system_u:object_r:etc_t:s0 10-canal.conflist  system_u:object_r:etc_t:s0 calico-kubeconfig
```
**Actual behavior:**
```
[ec2-user@ip-172-31-0-9 ~]$ sudo ls -Z /etc/cni/net.d
[ec2-user@ip-172-31-0-9 ~]$ 

```

**Comment by galal-hussein** [comment]
To add more context about the issue, calico/canal charts starts the init container that places the cni plugin as a privileged container which runs with context `spc_t` that has access to almost everything, however flannel starts the init container with no privileges which results in the error:
```
type=PROCTITLE msg=audit(1714071707.254:1615): proctitle=6370002D66002F6574632F6B7562652D666C616E6E656C2F636E692D636F6E662E6A736F6E002F6574632F636E692F6E65742E642F31302D666C616E6E656C2E636F6E666C697374
type=SYSCALL msg=audit(1714071707.254:1615): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7ffcbeb8cbaf a2=c1 a3=1a4 items=0 ppid=43442 pid=64262 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cp" exe="/usr/bin/cp" subj=system_u:system_r:container_t:s0:c386,c486 key=(null)
type=AVC msg=audit(1714071707.254:1615): avc:  denied  { write } for  pid=64262 comm="cp" name="net.d" dev="xvda4" ino=161756878 scontext=system_u:system_r:container_t:s0:c386,c486 tcontext=system_u:object_r:etc_t:s0 tclass=dir permissive=0
```

**Comment by galal-hussein** [comment]
The issue can be tested using the testing channel [v0.18.testing.2](https://github.com/rancher/rke2-selinux/releases/tag/v0.18.testing.2)

**Comment by ShylajaDevadiga** [comment]
Completed in the scope of validating https://github.com/rancher/rke2/issues/5843
