### ISSUE TITLE
Add Ubuntu 24.04 Support to RKE2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#5854]
**RKE2 Versions to be Validated**

TBD

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

Internal reference: SURE-8314

**Comment by nicewrld** [comment]
Also looking for this support so we can upgrade.

**Comment by rancher-max** [comment]
Validated with April releases:
v1.29.4+rke2r1
v1.28.9+rke2r1
v1.27.13+rke2r1
