### ISSUE TITLE
How to upgrade a cluster created by RKE1 to RKE2

### ISSUE THREAD

**Issue by myselfghost** [rancher/rke2#586]
I have a cluster created by RKE1 ,How to upgrade the cluster to RKE2?

**Comment by c3y1huang** [comment]
Currently there is no support to upgrade from RKE1 to RKE2. However, it seems like it's already on the radar. You can track in https://github.com/rancher/rke2/issues/562.

**Comment by immanuelfodor** [comment]
Unstale

**Comment by immanuelfodor** [comment]
Unstale

**Comment by brandond** [comment]
As mentioned above, this is being tracked in https://github.com/rancher/rke2/issues/562.
