### ISSUE TITLE
Container pods cannot connect to internet without hitting Egress Self-signed cert

### ISSUE THREAD

**Issue by nfaction** [rancher/rke2#5883]
**Environmental Info:**
RKE2 Version: 
```
$ rke2 -v
rke2 version v1.27.11+rke2r1 (6665618680112568f79b1f5992aecf4655e3cf8b)
go version go1.21.7 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 
`Linux k8s1 5.15.0-1057-kvm #62-Ubuntu SMP Mon Apr 15 18:41:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
```
NAME   VERSION
k8s1   v1.27.11+rke2r1 - server
k8s2   v1.27.11+rke2r1 - agent
k8s3   v1.27.11+rke2r1 - agent
```

Installed latest MetalLB and am using BGP + Layer 3 routing, which works as expected.

**Describe the bug:**
All container pods running within the cluster are unable to connect to outside websites like Github.com or anything with TLS enabled. For example within a `netshoot` pod:

```shell
curl https://github.com
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Similarly, if you load up a browser in a pod, and inspect the certificate, you'll see a `Kubernetes Ingress Controller Fake Certificate`. 

I tried to set a default certificate for all non-ingress defined routes using `default-ssl-certificate` on the `rke2-ingress-nginx-controller`, and it does in fact swap it out with the certificate I provided, but since it's a normal TLS cert, it does not route like a CA would.

As a potential workaround, I tried using `tinyproxy` and set all the parameters (https://docs.rke2.io/advanced?_highlight=proxy#configuring-an-http-proxy) on all the nodes.

Short of having to install a CA on every single pod that I need to connect to the internet, I don't have an idea how to fix.

I initially found this when trying to create a new App in the default ArgoCD install within this cluster. It was unable to connect to `github`. Here's the error:

```
FATA[0000] rpc error: code = InvalidArgument desc = application spec for guestbook is invalid: InvalidSpecError: repository not accessible: repositories not accessible: &Repository{Repo: "https://github.com/argoproj/argocd-example-apps.git", Type: "", Name: "", Project: ""}: repo client error while testing repository: rpc error: code = Unknown desc = error testing repository connectivity: Get "https://github.com/argoproj/argocd-example-apps.git/info/refs?service=git-upload-pack": tls: failed to verify certificate: x509: certificate is valid for ingress.local, not github.com 
```

As one can see, it's not liking the `ingress.local`

I've also checked that I'm running in `priviledged` mode https://docs.rke2.io/security/pod_security_standards and verified that it's unrestricted

**Steps To Reproduce:**

- Installed RKE2: 
- Also happens with K3s
- Install ArgoCD, fails to add app

**Expected behavior:**

There should be an option to allow pods to egress to the internet with a valid CA certificate chain, otherwise any pod running will not be able to interact with most modern internet connections. I expect there to be a way to route around the nginx-ingress any bypass it for egress, or have a way to install a CA or cert at the ingress to fix this.

**Actual behavior:**
Pods cannot connect to any site on the internet with modern TLS

**Additional context / logs:**
All listed in description.

**Comment by manuelbuil** [comment]
Normally, pods in RKE2 don't use any egress component to connect to internet server, how are you configuring the egress part?

**Comment by brandond** [comment]
It sounds like you have a wildcard DNS entry somewhere in the search list that is being used by pods, that points back at the ingress addres. When you try to hit `github.com`, the wildcard points at `github.com.<YOURDOMAIN>` instead, and you get an invalid cert error because the ingress isn't valid for that domain.

I would probably avoid using wildcard records in domains that are in your search list.

**Comment by nfaction** [comment]
@brandond That was indeed the issue. Nice catch! Is there any way to configure a wildcard domain that would work? I've read up on External-DNS, but with my home network I don't have the common cloud-based DNS services. I'm not sure how I would configure CoreDNS with it without running another instance. I've noticed that PiHole may have an option for this. Any suggestions?

**Comment by brandond** [comment]
> Is there any way to configure a wildcard domain that would work?

Don't put the wildcard record in a scope that is included in your cluster's search domain.

**Comment by manuelbuil** [comment]
I'm curious about one thing: unless manually adding an DNS entry, how can `github.com.<YOURDOMAIN>` point at the ingress svc address?

**Comment by nfaction** [comment]
So if I were to define a domain with a wildcard that was NOT configured in the cluster's search it would work?

**Comment by brandond** [comment]
Correct.
