### ISSUE TITLE
Support Adding Auto-Deploying manifests during installation

### ISSUE THREAD

**Issue by flokli** [rancher/rke2#590]
https://docs.rke2.io/advanced/#auto-deploying-manifests mentions:

> Any file found in /var/lib/rancher/rke2/server/manifests will automatically be deployed to Kubernetes in a manner similar to kubectl apply.

This only works after RKE2 has been started up already. If I do this before, it'll remove all files in there, and add some files on its own.

I setup RKE2 clusters with cloud-init, add `cloud-provider=external` to `kubelet-arg` and wanted to provide some manifests for a custom CCM, but there seems no way to do this in a non-racy fashion.

**Comment by flokli** [comment]
@brandond has this been fixed in the meantime?

**Comment by brandond** [comment]
I'm not aware of any issue with this functionality. We do not delete files from `/var/lib/rancher/rke2/server/manifests` unless the corresponding addon is present in the `--disable` list.

**Comment by flokli** [comment]
Indeed, this doesn't seem to be an issue (anymore?):

```
root@rke-experiment:~# mkdir -p /var/lib/rancher/rke2/server/manifests
root@rke-experiment:~# cat > /var/lib/rancher/rke2/server/manifests/example-foo.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true   
root@rke-experiment:~# curl -sfL https://get.rke2.io | sh -
[INFO]  finding release for channel stable
[INFO]  using v1.21.3+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.21.3+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.21.3+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
root@rke-experiment:~# systemctl start rke2-server.service 
root@rke-experiment:~# KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/bin/kubectl get configmaps
NAME               DATA   AGE
game-demo          4      35s
kube-root-ca.crt   1      22s
```
