### ISSUE TITLE
Ingress Controller in RKE2 Cluster Not Passing Real Client IP to Pods

### ISSUE THREAD

**Issue by mhrznamn068** [rancher/rke2#5917]
The RKE2 Nginx Ingress Controller in the RKE2 cluster is unable to receive the real client IP in pods.

Does the RKE2 Nginx Ingress Controller support similar configurations to those that can be done in Nginx, such as the following?

```
set_real_ip_from 0.0.0.0/0;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

location / {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by brandond** [comment]
I would probably check with the upstream project: https://github.com/kubernetes/ingress-nginx/issues/9749

**Comment by mhrznamn068** [comment]
@brandond, it seems like I'm encountering a different issue compared to the one you mentioned earlier.

My current challenge revolves around configuring the RKE2 Ingress controller to accurately receive the real IP address from an external load balancer operating above my Kubernetes cluster.

In this scenario, I'm exploring the options available through the ConfigMap resources of the Nginx Ingress Controller. Specifically, I'm looking into utilizing the `set-real-ip-from` and `real-ip-header` directives within the configmap resources.

For more detailed information on these configuration options and how they can be applied, you can refer to the Nginx Ingress Controller documentation provided in the link below:

[NGINX Ingress Controller Configuration Documentation
](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#:~:text=set%2Dreal%2Dip,real%2Dip%2Dheader)

**Comment by mhrznamn068** [comment]
Resolved using use-forwarded-headers: "true"

https://docs.rke2.io/networking/networking_services#:~:text=use%2Dforwarded%2Dheaders%3A%20%22true%22

**Comment by sungureanu** [comment]
@mhrznamn068 
Hi,
I have a RKE2 1.30.x cluster, using ingress-nginx controller, having metalllb to provide LB IPs, and I'm struggle to see real IP on ingress pod logs.
What I see on ingress pod logs, as a source, is the ipaddress of  kube-proxy and not the client real IP. 
I did what you suggested, adding those 2 lines on manifest config, but in nginx pods, x_forwarded_for is empty:
"http_x_forwarded_for": "-"
Have you done something else?

Thank you!
