### ISSUE TITLE
Test / Verify against SLES

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#592]
We would like to expand the K3s OS support matrix and include [SUSE Linux Enterprise Server 15 SP2](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/)

**Comment by davidnuzik** [comment]
Prioritize 1.19.x first then 1.18.

**Comment by davidnuzik** [comment]
Bonus: Briefly smoke test on openSUSE Leap (latest).

**Comment by rancher-max** [comment]
Blocked by https://github.com/k3s-io/k3s/issues/2778. Will try with workaround to see if the support matrix checks can be validated with that.

**Comment by ShylajaDevadiga** [comment]
Validated SLES15SP2 as per New OS Validation matrix on c-beta1+rke2r2 v1.20.2-beta1+rke2r1 with the apparmor fix.
1. Conformance test passed.
2. Import to rancher was successful and functionality test passed.
3. Upgrade using SUC was successful and upgrade test passed.
4. Validated rke2 v1.19.7-beta1+rke2r2 as local management cluster. k8s v1.20 is not supported at this point in rancher.

**Comment by rancher-max** [comment]
This has been fully validated on the latest rc's for 1.18 and 1.19 and is in our support matrix moving forward.

**Comment by Martin-Weiss** [comment]
> 
> 
> Validated SLES15SP2 as per New OS Validation matrix on c-beta1+rke2r2 v1.20.2-beta1+rke2r1 with the apparmor fix.
> 
>     1. Conformance test passed.
> 
>     2. Import to rancher was successful and functionality test passed.
> 
>     3. Upgrade using SUC was successful and upgrade test passed.
> 
>     4. Validated rke2 v1.19.7-beta1+rke2r2 as local management cluster. k8s v1.20 is not supported at this point in rancher.

Cool - this is really great news! Have there been any special configurations used?

I am testing with SLES15SP2 and RKE2 and PODS (i.e. helm-jobs and busybox in kube-system namespace) in the cluster network can not reach coredns.. still trying to find out what is going wrong..

**Comment by peter-englmaier** [comment]
@Martin-Weiss 
I have no problems reaching coredns. My system is SLES15SP2 with 3 Masters, no Workers. 
Have you disabled firewalld? Are all pods running?
```
$ kubectl get pods -A|grep -E 'canal|coredns'
kube-system        helm-install-rke2-canal-wjh54                        0/1     Completed   0          3h15m
kube-system        helm-install-rke2-coredns-kgp9k                      0/1     Completed   0          3h15m
kube-system        rke2-canal-dkf2q                                     2/2     Running     2          3h15m
kube-system        rke2-canal-n9v94                                     2/2     Running     2          3h14m
kube-system        rke2-canal-shjgh                                     2/2     Running     2          3h15m
kube-system        rke2-coredns-rke2-coredns-9d9bf756f-v9kwc            1/1     Running     1          3h15m
```

However, I have problems using private repository. Credentials seem not to be sent to registry. Otherwise, it works as expected.

**Comment by Martin-Weiss** [comment]
Thanks a lot! We could narrow down the problem on my side - basically the busybox image does have a problem talking to core-dns. When using suse, ubuntu or alpine this problem is not there so I have a workaround at least..

This is basically what is not working for me:
kubectl -n kube-system exec -it busybox --command bash
-> then do "nslookup <any name>"

**Comment by brandond** [comment]
uclibc-based busybox has some odd behavior around name resolution compared to standard images. Something to keep in mind when using it to test DNS.

**Comment by Martin-Weiss** [comment]
> 
> 
> uclibc-based busybox has some odd behavior around name resolution compared to standard images. Something to keep in mind when using it to test DNS.

It seems we have been running into https://github.com/docker-library/busybox/issues/48 - so probably we might have to adjust the guide at https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-if-domain-names-are-resolving with either not using busybox or add a warning "not to use a newer version of busybox than 1.28"..
