### ISSUE TITLE
cannot perform Air-Gap Install with Tarball Method

### ISSUE THREAD

**Issue by heroes1412** [rancher/rke2#5922]
**Environmental Info:**
RKE2 Version: [v1.30.0+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.30.0%2Brke2r1)

Node(s) CPU architecture, OS, and Version: 
Linux cp1 5.15.0-205.149.5.1.el9uek.x86_64 #2 SMP Fri Apr 5 11:29:36 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux
Oracle Linux 9 

**Steps To Reproduce:**
- selinux was disabled
ip link add dummy0 type dummy
ip link set dummy0 up
ip addr add 203.0.113.254/31 dev dummy0
ip route add default via 203.0.113.255 dev dummy0 metric 1000
- already copied rke2-images.linux-amd64.tar.gz to /var/lib/rancher/rke2/agent/images/
- Installed RKE2 by: INSTALL_RKE2_TYPE="server" ./install_rke2.sh

**Expected behavior:**
- can install RKE2 server node in offline enviroment

**Actual behavior:**
[root@localhost tmp]# INSTALL_RKE2_TYPE="server" ./install_rke2.sh
[INFO]  finding release for channel stable
curl: (28) Failed to connect to update.rke2.io port 443: Connection timed out
[INFO]  using stable series from channel stable
Rancher RKE2 Common (stable)                                                                             0.0  B/s |   0  B     06:00
Errors during downloading metadata for repository 'rancher-rke2-common-stable':
  - Curl error (28): Timeout was reached for https://rpm.rancher.io/rke2/stable/common/centos/9/noarch/repodata/repomd.xml [Failed to connect to rpm.rancher.io port 443: Connection timed out]
Error: Failed to download metadata for repo 'rancher-rke2-common-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@localhost tmp]#

**Comment by brandond** [comment]
See the docs - specifically https://docs.rke2.io/install/airgap#rke2-installsh-script-install where it says `install.sh may be used in an offline mode by setting the INSTALL_RKE2_ARTIFACT_PATH variable to a path containing pre-downloaded artifacts` - it does not appear that you've set that variable.

**Comment by heroes1412** [comment]
thanks, it works. i thought that i only need all zst|gz file into /var/lib/rancher/rke2/agent/images/
install script will detect and run in offline mode :D
