### ISSUE TITLE
cattle.io 此域名可供出售！

### ISSUE THREAD

**Issue by nzkyyds** [rancher/rke2#5926]
# exec shell
1. curl -sfL https://rancher-mirror.rancher.cn/rke2/install.sh | INSTALL_RKE2_MIRROR=cn sh -
2. systemctl enable rke2-server.service
3. systemctl start rke2-server.service
4. journalctl -u rke2-server -f

# got error
error syncing 'kube-system/rke2-snapshot-controller': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-snapshot-controller\" not found, requeuing

# visit helmcharts.helm.cattle.io
![image](https://github.com/rancher/rke2/assets/9328617/25e12b6b-7340-48b6-a240-9896fc96f4db)

**Comment by nzkyyds** [comment]
// exec shell

1. curl -sfL https://rancher-mirror.rancher.cn/rke2/install.sh | INSTALL_RKE2_MIRROR=cn sh -
2. systemctl enable rke2-server.service
3. systemctl start rke2-server.service
4. journalctl -u rke2-server -f

**Comment by brandond** [comment]
1. `error syncing 'kube-system/rke2-snapshot-controller': handler helm-controller-chart-registration: helmcharts.helm.cattle.io "rke2-snapshot-controller" not found, requeuing` This is a normal message to see during startup when caches are being initialized
2. That is a custom resource group, not a website. It is not expected that there would be a website available at that address.
