### ISSUE TITLE
Support Traefik as ingress for RKE2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#5928]
Some users would like the option to use Traefik as ingress. We do offer this on k3s, but it is now being asked for on RKE2. This would be an addition to our current supported ingress of nginx. 

Related Jira ticket is SURE-8403

**Comment by manuelbuil** [comment]
It would be good to understand the reasons why somebody might choose one over the other to add it in the docs

**Comment by mdrahman-suse** [comment]
# Validated on RC v1.30.3-rc5+rke2r1

## Testing
Scenarios with flag `ingress-controller: traefik` / `ingress-controller: traefik,ingress-nginx`
- HA cluster 
- New cluster
- Upgrade cluster 
- Air-gapped cluster
- CIS enabled cluster 
- Rancher deployed on cluster 
- Dual-stack cluster
- Cluster with Windows as agent

Issues found: 
- Airgap: https://github.com/rancher/rke2/issues/6438
- CIS enabled: https://github.com/rancher/rke2/issues/6449

**Comment by AaronDewes** [comment]
I could not find the `ingress-controller` setting in the documentation, apart from the [ADR](https://github.com/rancher/rke2/blob/5b8d8ceeee6af2fec66afc0e9eeb0f7ded236bda/docs/adrs/008-traefik-ingress.md?plain=1#L16). Will this setting be added to the documentation with available options?

**Comment by ceejatec** [comment]
@AaronDewes and anyone else who wanders this way: the way to enable this feature is to add the line

    ingress-controller: traefik

to `/etc/rancher/rke2/config.yaml` when first installing RKE2. There may be other ways as well, but I can confirm this works with RKE2 1.31.5+rke2r1. The cluster comes up with traefik configured as an ingress class, and no nginx-related pods or resources.

**Comment by AaronDewes** [comment]
Thanks for mentioning it.

I understood it in general, but at the time when I wrote this comment, the only official information was this GitHub issue, while I would expect to see it featured in the official docs. Not sure if it's still not mentioned, but I guess I could try to create a docs PR myself if it isn't.

**Comment by brandond** [comment]
Yeah, we do need to add this to the docs.

**Comment by cupracer** [comment]
Hi, I'm trying to use this new `ingress-controller` option via Terraform as shown here (shortened version):

```
resource "rancher2_cluster_v2" "create_cluster" {
  name               = "dummy"
  kubernetes_version = "v1.31.7+rke2r1"

  rke_config {
    machine_global_config = <<EOF
ingress-controller: traefik
EOF
  }
}
```

Unfortunately this new option isn't existing in the resulting cluster in the generated `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml`, so the cluster uses the default `rke2-ingress-nginx`. When adding that option manually:
```
# /etc/rancher/rke2/config.yaml
ingress-controller: traefik
```
and restarting rke2-server.service afterwards, `rke2-ingress-nginx` is being removed and `rke2-traefik` is being installed as expected.

I'm wondering which component needs to be extended here to honor the new option. Is it the **Rancher system-agent**? I could go ahead and create a new issue for that, but I'd need a hint to address it in the right project. Any idea? Thanks.

**Comment by brandond** [comment]
Rancher provisioning doesn't currently support selecting the ingress controller. This will need to be addressed on the Rancher side.

**Comment by cupracer** [comment]
Thanks a lot for the quick reply. I just created https://github.com/rancher/rancher/issues/49615 for that.
