### ISSUE TITLE
[Release-1.29] Bump Harvester cloud provider v0.2.4

### ISSUE THREAD

**Issue by Vicente-Cheng** [rancher/rke2#5990]
Bump Harvester cloud provider v0.2.4

PR: https://github.com/rancher/rke2/pull/5981

cc @khushboo-rancher, @bk201, @w13915984028, @innobead

**Comment by VestigeJ** [comment]
Validated and recorded here - 
 https://github.com/rancher/rke2/issues/6008#issuecomment-2161518323
