### ISSUE TITLE
[Release-1.27] Bump harvester-cloud-provider v0.2.4

### ISSUE THREAD

**Issue by Vicente-Cheng** [rancher/rke2#5992]
Bump harvester-cloud-provider v0.2.4

PR: https://github.com/rancher/rke2/pull/5983

cc @khushboo-rancher, @bk201, @w13915984028, @innobead

**Comment by VestigeJ** [comment]
Validated and recorded here - 
 https://github.com/rancher/rke2/issues/6008#issuecomment-2161518323
