### ISSUE TITLE
Config file support for RKE2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#6]
**Work should start on k3s first, then port this into RKE2**. https://github.com/rancher/k3s/issues/1505

Add support for flat config file which specifies flags to run binary with. _**Please reference the K3s issue for details. This issue is for tracking the work to port this over to RKE2**_

**Comment by davidnuzik** [comment]
Fixed in https://github.com/rancher/rke2/issues/66

**Comment by davidnuzik** [comment]
@ShylajaDevadiga for this issue, https://github.com/rancher/rke2/pull/121 may help (as far as what to test). See the docs in that PR

**Comment by ShylajaDevadiga** [comment]
Validated flags specified in conf file is being used during install
1. Default location /etc/rancher/rke2/flags.conf

```
cat /etc/rancher/rke2/flags.conf
node-label:
  - "foo=bar"
  - "something=amazing"

kubectl describe node |grep some
                    something=amazing

```
2. User defined location passed through --config /tmp/myconfig 
```
cat /tmp/myconfig 
write-kubeconfig-mode: "0644"
node-label:
  - "foo=bar"

ls -l /etc/rancher/rke2/rke2.yaml 
-rw-r--r-- 1 root root 2797 Jul 23 21:40 /etc/rancher/rke2/rke2.yaml

kubectl describe node |grep foo
                    foo=bar
```

3. Default location /etc/rancher/rke2/flags.conf with cli args, cli args overrides conf file args
```
INSTALL_RKE2_VERSION=v1.18.4-alpha19+rke2  ./install.sh  --node-label=foo2=bar2

cat /etc/rancher/rke2/rke2.conf 
write-kubeconfig-mode: "0644"
node-label:
  - "foo1=bar1"

kubectl describe node |grep foo
                    foo2=bar2
                    rke2.io/node-args: ["server","--node-label","foo2=bar2"]

ls -l /etc/rancher/rke2/rke2.yaml 
-rw------- 1 root root 2801 Jul 23 21:55 /etc/rancher/rke2/rke2.yaml

```
