### ISSUE TITLE
Test INSTALL_RKE2_CIS_MODE Functionality in Install Script

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#60]
Functionality introduced in PR needs to be tested and verified. https://github.com/rancher/rke2/pull/58

Verify the etcd user has been created:

```sh
grep etcd /etc/passwd
```

Verify kernel parameters have been updated, run the commands below:

```sh
sysctl vm.panic_on_oom
sysctl kernel.panic
sysctl kernel.panic_on_oops
sysctl kernel.keys.root_maxbytes
```

Expected values:

vm.panic_on_oom=0
sysctl kernel.panic=10
sysctl kernel.panic_on_oops=1
sysctl kernel.keys.root_maxbytes=25000000

**Comment by ShylajaDevadiga** [comment]
Verified using rke2 version v0.0.1-alpha.6 on a one node cluster
1. etcd user is created
```
cat /etc/passwd |grep etcd
etcd:x:997:997:ETCD Service User:/var/lib/rancher/rke2:/usr/sbin/nologin
```
2. kernel parameters have been updated and persist across reboots.
```
root@ip-172-31-8-139:~# sysctl vm.panic_on_oom
vm.panic_on_oom = 0
root@ip-172-31-8-139:~# sysctl kernel.panic
kernel.panic = 10
root@ip-172-31-8-139:~# sysctl kernel.panic_on_oops
kernel.panic_on_oops = 1
root@ip-172-31-8-139:~# sysctl kernel.keys.root_maxbytes
kernel.keys.root_maxbytes = 25000000
```

**Comment by davidnuzik** [comment]
Briefly reopening for a moment just to test something in zube / with zubebot.
