### ISSUE TITLE
Improve messaging/blocking of firewalld

### ISSUE THREAD

**Issue by bgulla** [rancher/rke2#600]
As a user/operator of RKE2, I commonly install RKE2 on systems running RHEL/CentOS. By default these operating systems have the systemd service for `firewalld` enabled. As mentioned in our docs, the way that kubernetes/rke2 manages ephemeral ports disallows the ability to run out-of-the-box `firewalld` on an RKE2 host. We have seen this commonly lead to problems for our users that install RKE2 without knowing to disable `firewalld`.

Thoughts:
  - Can we better publicly document why `firewalld` is not tenable for RKE2 installations?
  - Can we check at RKE2 runtime if `firewalld` is running and FATAL rke2?
     - if not, can we include a `preflight-check.sh` script for RKE2 similar to k3s?
  - Many security shops get weird if you tell them to disable `firewalld`, is there any configuration/firewalld policy that would allow the process to run in a mode permissive enough for rke2?

**Comment by nikkelma** [comment]
If there is no known stable `firewalld` configuration, a suggestion for an alternate on-host firewall solution would be required for the on-prem use cases, unless another on-prem architecture (not requiring in-host firewall) would be recommended instead.

**Comment by frjaraur** [comment]
Why we can just add flannel.1 interface to trusted zone for Canal (Flannel VXLan) just to avoid firewalld conflicts on forwarding?. I didn´t have any other issue after this change.

**Comment by kphunter** [comment]
> If there is no known stable `firewalld` configuration, a suggestion for an alternate on-host firewall solution would be required for on-prem use cases, unless another on-prem architecture (not requiring on-host firewall) would be recommended instead.

Is there a recommendation about alternatives to `firewalld` these days? I'm struggling to justify turning it off after having been burned by a malicious actor. I think what's causing the confusion is the blanket statement "[firewalld should be disabled on systems running RKE2](https://docs.rke2.io/known_issues/#firewalld-conflicts-with-default-networking)", which appears to be at odds with the [firewall port recommendations in the Rancher docs](https://rancher.com/docs/rancher/v2.6/en/installation/requirements/ports/#ports-for-rancher-server-nodes-on-rke2). Does the `firewalld` restriction only apply to RKE2 deployments using Canal? What's the recommended way to secure nodes?

**Comment by frjaraur** [comment]
I manage various RKE2 with firewalld running protecting hosts network (even with multiple interfaces). It is just needed some time reviewing what ports are required to work, and of course, whenever you add new applications using host network, you need to change ports configuration again.

**Comment by Martin-Weiss** [comment]
If I remember right - one of the "challenges" with firewalld has been, that a restart of the network / firewalld can cause a reset / disruption of iptables rules that have been created "dyamically" with the kubernetes CNI, because there has not been a direct integration of firewalld and the CNIs available.. not sure if this is still true.

**Comment by frjaraur** [comment]
To be honest, I haven't noticed, but it is not usual to modify firewalld tables outside of kubernetes in my case. I use a rule to allow communications between nodes hence publishing new node ports is not required for inter-kubernetes applications.

**Comment by kphunter** [comment]
> To be honest, I haven't noticed, but it is not usual to modify firewalld tables outside of kubernetes in my case. I use a rule to allow communications between nodes hence publishing new node ports is not required for inter-kubernetes applications.

That's the direction I was thinking-of: a restrictive (sane) default for the public zone but allowing essentially all traffic between nodes via `firewall-cmd --add-source...` for a separate (active) zone...

**Comment by cade-thomas** [comment]
Whats the word on this these days?  Putting some example calico/cilium resources to secure afterwards in the docs would probably help people.
