### ISSUE TITLE
rke2-killall.sh script fails to kill containers when run on narrow terminal

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6024]
The `ps` command truncates output to terminal width. If the terminal window is small, or when run via automation where the COLUMNS var is set to a low value, the truncated command output will fail to match the `rke2/data/[^/]*/bin/containerd-shim` pattern that the killall script searches for, and the killall script will fail to terminate container processes.

To reproduce this, run the killall script on a very narrow terminal, or export `COLUMNS=40` and then run the killall script. Note that it fails to kill all the running containers.

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$ rke2 version v1.30.1+rke2r1  (254060695d70ad1c2f65b0138ceb4b2f7c4236e5 )
 
```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
rhel    
AMD
 

*Cluster Configuration:*
-1 node server 
 
 

## Steps to validate the fix
1. Install  rke2 
2. export COLUMNS=40 to simulate a narrow terminal
3. Run killall script
4. Validate that will not kill all the processes
5. Run killall script again
6. Validate that will kill all the processes
 

 


 
 
## **Reproduction Issue:**
<details>

``` 
 rke2 version v1.30.1 (c727b365ea6cb0d8b70fdcaac648d79950b9591b)

getshims() {
     COLUMNS=40  ps -e -o pid= -o args= | sed -e 's/^ *//; s/\s\s*/\t/;' | grep -w 'rke2/data/[^/]*/bin/containerd-shim' | cut -f1
}

$ sudo  /usr/local/bin/rke2-killall.sh


 AFTER script some processes are still running  -------

 ps -e -o pid= -o args= | sed -e 's/^ *//; s/\s\s*/\t/;' | grep -w 'rke2/data/[^/]*/bin/containerd-shim' | cut -f1
102983
103085
103335
103672
103701
103763
103936
103983
104014
104148
104151
104198
104634
104645
104657
104881
105405
105984


```

 
## **Validation Results:**
<details>


``` 
 
 
$ sudo  /usr/local/bin/rke2-killall.sh
+ killtree 102248 102507 102668 102673 102703 103365 104968 118133 118297 118395 118471 118540 118577 119185 119337 119409 119883 119971



$  ps -e -o pid= -o args= | sed -e 's/^ *//; s/\s\s*/\t/;' | grep -w 'rke2/data/[^/]*/bin/containerd-shim' | cut -f1
<EMPTY>

 ```
