### ISSUE TITLE
[Question] what source code version does rke2 use to build rancher/hardened-cluster-autoscaler:v1.8.6-build20230609

### ISSUE THREAD

**Issue by went2** [rancher/rke2#6040]
Hi, I'm working on replacing some RKE2 built-in images with ones  built from source code.

I ran into a problem while trying to create an image of rancher/hardened-cluster-autoscaler:**v1.8.6-build20230406**. The [source code repository](https://github.com/rancher/image-build-cluster-proportional-autoscaler) starts at tag v1.8.10 and doesn't have a tag for v1.8.6.

Could you let me know where I can find the source code for the v1.8.6-build20230406 version of the autoscaler? Any help would be really appreciated. Thanks!

**Comment by manuelbuil** [comment]
We started building that image a few months ago when the upstream code was using v1.8.10. That's why there is no tag for older releases
