### ISSUE TITLE
rpm download server not progressing

### ISSUE THREAD

**Issue by jdewinne** [rancher/rke2#6051]
**Environmental Info:**
RKE2 Version: 

1.29.3

Node(s) CPU architecture, OS, and Version: 

x86_64

Cluster Configuration:

Single node

**Describe the bug:**

rpm server down?

**Steps To Reproduce:**

- Installed RKE2: 
Run `curl -sfL https://get.rke2.io` to install which will hang on downloading the rpm
```
[    7.250253] cloud-init[1204]: + curl -sfL https://get.rke2.io
[    7.253709] cloud-init[1204]: + sh -s -
[    7.684725] cloud-init[1204]: [INFO]  using 1.29 series from channel stable
[   25.099228] cloud-init[1204]: Last metadata expiration check: 0:00:01 ago on Wed May 29 16:05:55 2024.
[   25.394311] cloud-init[1204]: Dependencies resolved.
[   25.395403] cloud-init[1204]: ================================================================================
[   25.397110] cloud-init[1204]:  Package       Arch     Version                Repository                  Size
[   25.398738] cloud-init[1204]: ================================================================================
[   25.401032] cloud-init[1204]: Upgrading:
[   25.401904] cloud-init[1204]:  rke2-common   x86_64   1.29.3~rke2r1-0.el8    rancher-rke2-1.29-stable    26 M
[   25.403630] cloud-init[1204]:  rke2-server   x86_64   1.29.3~rke2r1-0.el8    rancher-rke2-1.29-stable   8.8 k
[   25.405341] cloud-init[1204]: Transaction Summary
[   25.406275] cloud-init[1204]: ================================================================================
[   25.407967] cloud-init[1204]: Upgrade  2 Packages
[   25.409025] cloud-init[1204]: Total download size: 26 M
[   25.410056] cloud-init[1204]: Downloading Packages:
[   25.892422] cloud-init[1204]: (1/2): rke2-server-1.29.3~rke2r1-0.el8.x86_64.r  18 kB/s | 8.8 kB     00:00
```

**Expected behavior:**

Download the rpm and install

**Actual behavior:**

Not downloading rpm

**Additional context / logs:**

**Comment by brandond** [comment]
I can't reproduce this, either locally or on an EC2 instance. Is there something on your node or network that might be blocking your access to the S3 bucket hosting the packages? You're obviously able to pull down the repo metadata, I don't know why you would be able download that but not the rpm itself.

**Comment by jdewinne** [comment]
It is working again. As the rpm's are hosted on s3, this can also have been an AWS issue (regional). Their status page doesn't show anything about it however.
