### ISSUE TITLE
Test and Verify Etcd Runs as Etcd User

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#61]
The functionality introduced in PR: https://github.com/rancher/rke2/pull/56 needs to be validated. This work is in conjunction to the install script for adding CIS mode.

This can be done by:

```sh
./rke2 --profile=cis-1.5 server
```

If it runs, it thinks it succeeded.

To get the etcd process, run the command below.

```sh
ps aux | grep etcd
```

Check the pod manifest for a security context section that has the etcd user id and group id. Those id's can be references from the output from `cat /etc/passwd | grep etcd`. To see the manifest:

```sh
cat /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
```

**Comment by ShylajaDevadiga** [comment]
rke2 version v0.0.1-alpha.7
Seeing error while running the binary with --profile flag
```
./rke2 --profile=cis-1.5 server 
FATA[0000] user: unknown user etcd
kernel.panic=-1 - expected 10
kernel.panic_on_oops=0 - expected 1 
```

**Comment by briandowns** [comment]
Was the install script ran in CIS mode? This would be expcted if it wasn't.

**Comment by ShylajaDevadiga** [comment]
I guess I missed the purpose of --profile=cis-1.5 flag as expected criteria is set when INSTALL_RKE2_CIS_MODE=true

Tested with below parameters:

Scenario 1: Without setting  INSTALL_RKE2_CIS_MODE, running binary with --profile fails as expected criteria is not met.
```
# INSTALL_RKE2_VERSION=v0.0.1-alpha.7 ./install.sh
# ps -ef |grep rke2
root        2107       1  0 03:11 ?        00:00:15 /usr/local/bin/rke2 server 

# systemctl stop rke2

# rke2 -v
rke2 version v0.0.1-alpha.7 (HEAD)

# rke2 --profile=cis-1.5 server 2>&1 &
FATA[0000] user: unknown user etcd 
```
Scenario 2: With setting  INSTALL_RKE2_CIS_MODE, running binary with --profile after stopping rke2
```
# INSTALL_RKE2_VERSION=v0.0.1-alpha.7 INSTALL_RKE2_CIS_MODE=true  ./install.sh
    
# systemctl stop rke2

# rke2 --profile=cis-1.5 server 2>&1 &

# ps -ef |grep "etcd --config"
etcd      681955  681894  1 03:56 ?        00:00:09 etcd --config-file=/var/lib/rancher/rke2/server/db/etcd/config

# cat /etc/passwd |grep etcd
etcd:x:997:997:ETCD Service User:/var/lib/rancher/rke2:/usr/sbin/nologin

# cat /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml |grep 997
    runAsGroup: 997
    runAsUser: 997
```
Scenario 3:
```
# INSTALL_RKE2_VERSION=v0.0.1-alpha.7 INSTALL_RKE2_CIS_MODE=true  ./install.sh

# ps -ef |grep "etcd --config"
etcd        2344    2281  1 04:14 ?        00:00:15 etcd --config-file=/var/lib/rancher/rke2/server/db/etcd/config

# cat /etc/passwd |grep etcd
etcd:x:997:997:ETCD Service User:/var/lib/rancher/rke2:/usr/sbin/nologin

# cat /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml |grep 997
    runAsGroup: 997
    runAsUser: 997
```

**Comment by ShylajaDevadiga** [comment]
@briandowns Could you please confirm the  --profile=cis-1.5 flag is for checking the criteria is met?

**Comment by briandowns** [comment]
Yes, the `--profile` flag with the value of "cis-1.5" will check for the "etcd" user as well as a number of kernel parameters being set to specific values.

**Comment by ShylajaDevadiga** [comment]
Thanks @briandowns
