### ISSUE TITLE
v1.19.5+rke2r1 Release (our first time bumping to 1.19.x)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#610]
Release Captain = Hussein

**Summary:**
Task covering release work. v1.19.5+rke2r1
Dev Complete: 12/14/2020

**List of required releases:**
_To release as soon as able for QA:_
- [x] v1.19.5-rc1+rke2r1

_To release once have approval from QA:_
- [x] v1.19.5+rke2r1

**Prep work (up to 7 days prior to release day):**
- [x] EIO and QA team notified of the incoming releases - send calendar invite
- [x] QA: Review changes and understand testing efforts
- [x] Menna: Prep PR for rancher/kontainer-driver-metadata (bump version(s)). PREPARE, but PLEASE DO NOT MERGE. KDM release should be planend for on or around 12/22. Because rke2 v1.19.5 won't be stable yet we should NOT get this into the relaese branches just yet. You can prepare the PR if you wish but make sure it is clear it should not get merged in yet until post late december KDM release!
- [x] Rancher2 team notified of the release (create rancher/rancher issue and put in milestone. They will need to update rancher2 Dockerfile, etc) https://github.com/rancher/rancher/issues/30492
- [x] PM Draft Releases (fill in release notes, mark as pre-release, fill in title, set target release branch, leave tag version blank, save as draft)
- [x] QA: Validate and close out all issues in the release milestone.

**Release work:**
- [x] Release Captain*: Merge PR for rancher/kontainer-driver-metadata into the dev branches (This task is typically done by PM but will be on PTO)
- [x] Release Captain: Tag and release any necessary RCs for QA to test KDM
- [x] Release Captain: Tag and release the patch(es) when have QA and PM approval

**Post-Release work:**
- [x] Release Captain: Uncheck "Pre-release" once drone is complete and all release artifacts are there
- [x] PM: Create an issue to mark the latest release as stable (this is done typically at least 7 days post release, and rke2-packaging needs to be kicked off for stable before we mark as stable in channel.yaml) https://github.com/rancher/rke2/issues/609
- ~Rancher PM: (handled separately) Merge in rancher/kontainter-driver-metadata change to release branch (so new patch versions show up as upgrade options in Rancher UI). _We plan to release KDM late December on or around 12/22. Since this is so close to our release date we'll get this picked up in the NEXT KDM release._
- [x] PM: Close the milestone in GitHub.

**Comment by cjellick** [comment]
> Menna: Prep PR for rancher/kontainer-driver-metadata (bump version(s)). PREPARE, but PLEASE DO NOT MERGE. KDM release should be planend for on or around 12/22. Because rke2 v1.19.5 won't be stable yet we should NOT get this into the relaese branches just yet. You can prepare the PR if you wish but make sure it is clear it should not get merged in yet until post late december KDM release!

Dates on this are out-of-date. The new set of dates are basically 1/4. We are not going to promote anything to stable until 1/4 or later, so no prs for kdm+rke2/k3s should get merged until then.

**Comment by davidnuzik** [comment]
KDM should be all set now. Merged PRs into the necessary dev branches for release tomorrow.

**Comment by davidnuzik** [comment]
Closing as this was released over the holiday break. Testing is a pass and the release is also marked as stable now.

**Comment by tallaxes** [comment]
1.19 `stable` RPMs don't seem to be available; install script gets 404 on e.g. https://rpm.rancher.io/rke2/stable/1.19/centos/7/x86_64/repodata/repomd.xml (`latest` are there ...) Am I missing something? Or is there a step missing in the checklist above? (Something about tags in rke2-packaging repo?)

**Comment by Oats87** [comment]
@tallaxes We have now cut the corresponding `v1.19.5+rke2r1` RPM into the `stable` repository.
