### ISSUE TITLE
Doc: Fix disable docs ingress service name

### ISSUE THREAD

**Issue by aaron-grewell** [rancher/rke2#611]
In the [server configuration](https://docs.rke2.io/install/install_options/server_config/) docs under `--disable` the ingress service name is listed as `rke2-ingress` which is incorrect. The actual name is `rke2-ingress-nginx` as described in [Issue 232](https://github.com/rancher/rke2/issues/232).

**Comment by rancher-max** [comment]
The doc has been updated and is live. Thank you for calling this out!
