### ISSUE TITLE
Bump flannel to v0.25.3

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#6117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Use the newer flannel v0.25.3

**Describe alternatives you've considered**

**Additional context**

**Comment by mdrahman-suse** [comment]
@manuelbuil I am seeing the version is still v0.25.3 when using the latest commit: 3aaa16c9b17da45e9f3475ba5011ed90a49a2e42 which should have the version v0.25.4
```
$ kubectl get nodes -A
server1   Ready   control-plane,etcd,master   2m35s   v1.30.1+rke2r1

$ kubectl get node -o yaml   | grep 'hardened-flannel' -A1
docker.io/rancher/hardened-flannel@sha256:dc9056741d7e75baddd66f4d3b30b97ddaaf975e0d80ac02435ea7fe7f5f472d
  - docker.io/rancher/hardened-flannel:v0.25.3-build20240605
     sizeBytes: 83563673
```

**Comment by mdrahman-suse** [comment]
I actually see it when using `cni: flannel`

```
$ kubectl get node -o yaml   | grep 'hardened-flannel' -A1
docker.io/rancher/hardened-flannel@sha256:dc9056741d7e75baddd66f4d3b30b97ddaaf975e0d80ac02435ea7fe7f5f472d
 - docker.io/rancher/hardened-flannel:v0.25.3-build20240605
    sizeBytes: 83563673
```
So is the expectation to see the updated version when it is enabled?

**Comment by manuelbuil** [comment]
Yes, you should see `v0.25.4` version and image should be `v0.25.4-build20240610`. Let me try to reproduce it

**Comment by manuelbuil** [comment]
Even with the commit you tried:
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=3aaa16c9b17da45e9f3475ba5011ed90a49a2e42 sh -
```
I get:
```
      - docker.io/rancher/hardened-flannel@sha256:d1fa60b5dd98c9f8b27e97dca6d9980fea08c93c5170a122d14e09b5210570fa
      - docker.io/rancher/hardened-flannel:v0.25.4-build20240610
      sizeBytes: 83562985
```

**Comment by manuelbuil** [comment]
Perhaps you were trying with `cni: canal`? Note that canal also uses flannel and we haven't moved that one to `0.25.4` as we were already on code freeze and the fixed bug only appears in Windows

**Comment by mdrahman-suse** [comment]
> Perhaps you were trying with `cni: canal`? Note that canal also uses flannel and we haven't moved that one to `0.25.4` as we were already on code freeze and the fixed bug only appears in Windows (canal is not supported on Windows)

It was using the default cni (canal), hence I was seeing the old version, tks!

**Comment by mdrahman-suse** [comment]
# Validation with RC v1.30.2-rc3+rke2r1

## Environment and config
```
Ubuntu 22.04, Single Server

## config.yaml
cni: flannel
```

## Testing
- Install rke2 with the config
- Ensure cluster is up
- Validate the flannel version

```
12:24:00  rke2 version v1.30.2-rc3+rke2r1 (7e788b736cc690d2ce520c17e34cefdfe7bbe2ce)
12:24:00  go version go1.22.4 X:boringcrypto
12:24:04  
12:24:04  Command:
12:24:04  kubectl get node -o yaml  | grep 'hardened-flannel' -A1
12:24:04  ---------------------
12:24:04  Assertion:
12:24:04  v0.25.4
12:24:04  ----------------------
12:24:04  Matched with result:
12:24:04  - docker.io/rancher/hardened-flannel@sha256:d1fa60b5dd98c9f8b27e97dca6d9980fea08c93c5170a122d14e09b5210570fa
12:24:04        - docker.io/rancher/hardened-flannel:v0.25.4-build20240610
12:24:04        sizeBytes: 83562985
```
