### ISSUE TITLE
WireGuard Support for Canal

### ISSUE THREAD

**Issue by devopstales** [rancher/rke2#612]
Wireguard support for canal would be awesome! This is exactly what k3s is doing, (See: https://github.com/rancher/k3s/blob/master/pkg/agent/flannel/setup.go#L62). So why not use the same thing in rke2?

**Comment by arianvp** [comment]
This could also be solved by allowing `calico` as the network plugin. It has native wireguard support and supports VXLAN as well so supports all the usecases Canal would support.

**Comment by cjellick** [comment]
Calico is now supported as a CNI
