### ISSUE TITLE
Update airgap docs to specify dependencies required for Selinux systems and Cent/Rhel 8

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#614]
Following are dependencies when doing an rpm install:
```
Installing:
 rke2-server                 
Installing dependencies:
 container-selinux           
 iptables                    
 libnetfilter_conntrack      
 libnfnetlink                
 libnftnl                    
 policycoreutils-python-utils
 rke2-common                 
 rke2-selinux 
```
We should update docs [here](https://docs.rke2.io/install/airgap/) to either specify this or update the "RPM Documentation" link in there to go somewhere that specifies this. That link should be updated regardless to go somewhere useful.

As an aside: this is also important for rancherd in NON AIRGAP on cent 8 as it installs using tarball method.

**Comment by cjellick** [comment]
Keeping open as a docs issue.
