### ISSUE TITLE
Removing node doesn't remove node password

### ISSUE THREAD

**Issue by joshrwolf** [rancher/rke2#616]
For clusters cycling nodes frequently (such as group(s) of spot instances), there is an eventual problem when a new node with a non unique hostname/ip starts and is unable to join the cluster due to an existing entry in `/var/lib/rancher/rke2/server/cred/node-passwd`.

Was able to "fix" it by removing the relevant entries from _all_ of the server node's `/var/lib/rancher/rke2/server/cred/node-passwd`.

This appears to be a known issue being worked on in k3s, with the elated issue [here](https://github.com/k3s-io/k3s/issues/802), but opening this issue to ensure it's tracked and a fix is ported to rke2.

**Comment by davidnuzik** [comment]
As per our recent discussion -- not needed in 1.19 line. This is planned for 1.20 now.

**Comment by ShylajaDevadiga** [comment]
Validated on rke2 version v1.20.4-rc2+rke2r1

Steps followed.
- Create a cluster with two nodes (master and agent)
- Deleted the node agent using kubectl delete node
- Uninstall rke2 and Shutdown the agent node
- Changed the hostname of a new node to the hostname of deleted node
- Joined the node to the cluster successfully

Note the hostname of the agent node is different from the ip address of the node as part of validation
```
kubectl get nodes -o wide
NAME                                          STATUS   ROLES                       AGE   VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
ip-172-31-26-108.us-east-2.compute.internal   Ready    control-plane,etcd,master   80m   v1.20.4-rc2+rke2r1   172.31.26.108   <none>        CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.4.3-k3s3
ip-172-31-28-142.us-east-2.compute.internal   Ready    <none>                      94s   v1.20.4-rc2+rke2r1   172.31.20.156   <none>        CentOS Linux 8 (Core)   4.18.0-193.6.3.el8_2.x86_64   containerd://1.4.3-k3s3
```
