### ISSUE TITLE
Don't dump the full SQL payload when SlowSQLThreshold is exceeded

### ISSUE THREAD

**Issue by bwerthmann** [rancher/rke2#6176]
**Is your feature request related to a problem? Please describe.**

kine (sqlight) is spamming my logs with slow query logs.

**Describe the solution you'd like**

Expose Kine's `SlowSQLThreshold` via rke2 config.

```
var (
	// SlowSQLThreshold is a duration which SQL executed longer than will be logged.
	// This can be directly modified to override the default value when kine is used as a library.
	SlowSQLThreshold = time.Second
)
```
https://github.com/k3s-io/kine/blob/be5e94c41466558eecf415bd3af31ccb23b3ae39/pkg/metrics/metrics.go#L36-L38

**Describe alternatives you've considered**

Filtering the logs after the fact.

**Additional context**

The issue is more so that the slow query logs dump the payloads (and possibly secrets?) into the rke2 log. Disabling slow query logging seemed like the fastest path to resolution.

This single log message, fully expanded, is 28 KB.
```
time="2024-06-10T22:10:44Z" level=info msg="Slow SQL (started: 2024-06-10 22:10:26.800869648 +0000 GMT m=+362.420845090) (total time: 17.882925587s): INSERT INTO kine(name, created, deleted, create_revision, prev_revision, lease, value, old_value) values(?, ?, ?, ?, ?, ?, ?, ?) : [[/registry/pods/namespace/podxyz-547ccf5fff-cmh6d 0 0 3889 4048 0 [ <encoded data>
<1000 chars of encoded data>
< +279 lines like ^^>
<more encoded data>]]]"
```

We're getting hundreds or thousands of these a day from an single RKE2 system. And we have many RKE2 systems. Our short-term solution is to filter these payloads in our logging agent so don't make it to our logging aggregator.

**Comment by brandond** [comment]
We're not currently planning on making this directly configurable. If you are seeing warnings from this on a regular basis, then datastore performance is poor and there are likely to be other downstream problems if latency continues to increase.

What sort of system (disks/cpu/memory) are you running this on where the sqlite queries regularly take longer than 1 second to execute?

**Comment by bwerthmann** [comment]
I've updated the `Additional context` section, PTAL. The primary issue is that the slow query logs are dumping the sql payload into the logs, which may or may not contain secrets, the single example log message I added is 28 KB and we're getting a lot of SlowQuery logs per day. If there was a way to disable dumping of the Slow Query payload into the logs that'd also work for us.

> What sort of system (disks/cpu/memory) are you running this on where the sqlite queries regularly take longer than 1 second to execute?

We have queries that take over a minute to run in the worst case. We did not see this before when we ran k3s.

We deploy to a number of hardware platforms as well as cloud and on-prem virtual envs. We moved off `etcd` because we know we have to deal with our and our customers "slow disk", and it was a major pain point for us. In this case the system is one of our mid-range hardware platforms with 44 cores, 192 GB of ram. `sqlight` file is on a 4 HDD + mdadm raid10 + LUKS , which is shared with a number of other consumers, rke2 can run on 14 of the 44 cores which are shared with a number of other consumers.

**Comment by bwerthmann** [comment]
> Yeah... having that in the logs is certainly not ideal. I can take a look at eliding the parameters from the logged sql query. We should probably only dump that out when logging at trace level.

Agreed.

> 
> I think that the slow SQL messages are still important from a situational awareness perspective. If you switched from etcd to sqlite due to poor shared disk performance, and sqlite isn't keeping up either... that's not great.

Agreed.

**Comment by brandond** [comment]
https://github.com/k3s-io/kine/issues/305

**Comment by mdrahman-suse** [comment]
Validated on the release RCs (rc4), closing this master ticket
