### ISSUE TITLE
 build image from system-upgrade-controller source code with tag v0.13.1, back-off restar

### ISSUE THREAD

**Issue by hchyue** [rancher/rke2#6184]
**Version**

v0.13.1
**Platform/Architecture**
arm64

**Describe the bug**

checkout source code with tag v0.13.1, run "make" build image.
fail to run pod with the image:
<img width="1312" alt="image" src="https://github.com/rancher/system-upgrade-controller/assets/69490488/700f78b5-fe8a-45ae-a055-9d6edeaddec6">

**To Reproduce**

checkout source code with tag v0.13.1, run "make",build image

![image](https://github.com/rancher/system-upgrade-controller/assets/69490488/1d27e54e-dcc7-4802-8c84-d005498c411c)

**Expected behavior**

<img width="1301" alt="image" src="https://github.com/rancher/system-upgrade-controller/assets/69490488/346dd386-b283-4f68-91f0-522e03cc4f5f">

**Actual behavior**

<img width="1197" alt="image" src="https://github.com/rancher/system-upgrade-controller/assets/69490488/7934efd5-7f67-4dfb-8612-576146ba9ea8">

**Additional context**

**Comment by brandond** [comment]
In case it's not clear from the tag, you're building and running the e2e-test image, not the one for the controller. You probably want to run the actual release image?

**Comment by hchyue** [comment]
yes, i shoud choose rancher/system-upgrade-controller:dev
