### ISSUE TITLE
docker time out 

### ISSUE THREAD

**Issue by Virtuoso461** [rancher/rke2#6211]
**Environmental Info:**
RKE2 Version:  v1.28.10+rke2r1 (b0d0d687d98f4fa015e7b30aaf2807b50edcc5d7)

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

ERRO[0039] Error encountered while importing /var/lib/rancher/rke2/agent/images/cloud-controller-manager-image.txt: failed to pull images from /var/lib/rancher/rke2/agent/images/cloud-controller-manager-image.txt: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image "docker.io/rancher/rke2-cloud-provider:v1.29.3-build20240412": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/35/3525a3daa55c92783ca961cd9c84d71a6c74db945f2ad8ab8a9d7df2c28c1038/data?verify=1718615355-vEDAKVRFQ06XHuqcUi2lTw41%!F(MISSING)jI%!D(MISSING)": dial tcp 108.160.169.46:443: i/o timeout 

when i use "rke2 server", it want to pull the docker, but it failed, so i pull that images on my computer, but it can use the local images and always output failed to pull the docker images.
**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
You'll need to figure out why containerd on your node can't connect to the docker.io content delivery network. Do you need to use a local registry mirror?
