### ISSUE TITLE
Validate RHEL/Rocky/Oracle 9.4

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#6264]
**RKE2 Versions to be Validated**

v1.30.2+rke2r1
v1.29.6+rke2r1
v1.28.11+rke2r1
v1.27.15+rke2r1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

```yaml
# /etc/rancher/rke2/config.yaml
selinux: true
```

**Comment by rancher-max** [comment]
RHEL validations completed.

**Comment by ShylajaDevadiga** [comment]
Rocky 9.4 validations completed.

**Comment by VestigeJ** [comment]
I'm voting we push this issue out for Oracle 9.4 - I'm still getting very different behavior on installs that is difficult to pinpoint or create a new issue around for installs.

**Comment by VestigeJ** [comment]
https://github.com/rancher/rke2/issues/6451#issue-2443646392 seems it's a combination of selinux policies that weren't surfacing in the audit logs until I removed the database to expose all failures.

**Comment by VestigeJ** [comment]
https://github.com/rancher/rke2/issues/6451#issuecomment-2332578011
