### ISSUE TITLE
RKE2 set containerd root and state directory different

### ISSUE THREAD

**Issue by Davidffry** [rancher/rke2#6266]
**Is your feature request related to a problem? Please describe.**

The Issue is when I want to change the "defaults" directories path of root and state for the containerd I modify it into the **config.toml.tmpl** file (that I put into the directory */agent/etc/containerd/)
```
#extract of config.toml.tmpl
{{ template "base" . }}
root=/XYZ/
state=/dossofstate/
```
but when rke2 is started the containerd generate the config.toml correctly **but** the command of the containerd is : 
```
ps -aux | grep -i containerd
...
containerd -c /kubernetes/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /kubernetes/agent/containerd
...
```

as you can see the command overwrite the configuration file (focus on the directory of state and root)

**Describe the solution you'd like**

Either in the config.yaml of Rke2 define the containerd_root_path and containerd_state_path
or generate generic path in the containerd config.toml and overwrite it.

**Describe alternatives you've considered**

No alternative

**Additional context**

Context in Airgapped mode but seems not relevant.

**Comment by brandond** [comment]
Can you describe your use case for changing the root and state dirs from the default? I guess we could move to passing them via the config file instead of via the CLI, but I'm not sure what the original cause was for our passing them that way, so I'd be reluctant to make that change without good reason.

**Comment by tunicashashi** [comment]
Do I need to install k3s as well before running rke2 to get containerd in k3s/containerd/containerd.sock or can I use my own installed containerd?

**Comment by brandond** [comment]
You're welcome to provide your own container runtime, including your own standalone version of containerd. Just pass the socket address to rke2 via the --container-runtime-endpoint flag.

**Comment by Davidffry** [comment]
If i use my own standalone version of containerd I loose one of the main
advantage of rke2...I use the templating to set the different path but it
does not work, and if I provide the socket you are sure that rancher does
not use the default path? I need to test it.

Le ven. 9 août 2024, 22:16, Brad Davidson ***@***.***> a
écrit :

**Comment by brandond** [comment]
> if I provide the socket you are sure that rancher does not use the default path?

Are you asking if the rke2 --container-runtime-endpoint flag works? Or if you can configure a standalone containerd can actually be configured to use custom paths? If it's standalone, you can manage the configuration however you want without having to use a template.

**Comment by brandond** [comment]
You can already set --data-dir.... why do you want to put containerd separate from the rest of k3s?
