### ISSUE TITLE
RKE2 kubelet going down after the cluster is up

### ISSUE THREAD

**Issue by rajivml** [rancher/rke2#629]
Hi,

I have been trying to setup RKE2 in an airgap environment from last one week and am facing some or other issue. The issue that am facing now is, kubelet is going down once the cluster is up,

Environment: CentOS 7.9 
Cloud: Azure

Script I used to generate the bundle:
https://raw.githubusercontent.com/rajivml/argodemo/main/scripts/rancher_depend_centos7.sh

Script I used to install airgap bundle:
https://raw.githubusercontent.com/rajivml/argodemo/main/scripts/centos_install.sh

Now once the cluster is up, I have copied few other images (*.gz) to /var/lib/rancher/rke2/agent/images/ location with the intent that if I restart rke2-server, the containerd will pickup those images at the time of restart, but somehow the kubelet went down after this action, am not sure if kubelet going down is related to this event or not, I have noticed it going down randomly 

```
[root@rancher-centos7 sshuser]# netstat -tulpn | grep 10250
[root@rancher-centos7 sshuser]#
[root@rancher-centos7 sshuser]# netstat -tulpn | grep kubelet
[root@rancher-centos7 sshuser]# kubectl -n kube-system logs -f rke2-coredns-rke2-coredns-6f7676fdf7-79djm
Error from server: Get https://rancher-centos7:10250/containerLogs/kube-system/rke2-coredns-rke2-coredns-6f7676fdf7-79djm/coredns?follow=true: dial tcp xxx.17.17.5:10250: connect: connection refused
[root@rancher-centos7 sshuser]#

[root@rancher-centos7 sshuser]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G  9.9M   16G   1% /run
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda2       256G   23G  233G   9% /
/dev/sda1       494M   62M  433M  13% /boot
/dev/sda15      495M   12M  484M   3% /boot/efi
/dev/sdb1        63G  2.1G   58G   4% /mnt/resource
shm              64M     0   64M   0% 

journalctl --no-pager -u rke2-server
```
Logs Link:
https://raw.githubusercontent.com/rajivml/argodemo/main/logs/rancher.txt

**Comment by rajivml** [comment]
Even if if run , "systemctl restart rke2-server", I don't see kubelet coming back again

**Comment by rajivml** [comment]
logs for stopping and starting rke2-server,



Dec 20 06:34:29 rancher-centos7 systemd[1]: Stopping Rancher Kubernetes Engine v2 (server)...
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down /v1, Kind=Secret workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down /v1, Kind=Node workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down k3s.cattle.io/v1, Kind=Addon workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down helm.cattle.io/v1, Kind=HelmChart workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down batch/v1, Kind=Job workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down /v1, Kind=Service workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down /v1, Kind=Pod workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down /v1, Kind=Endpoints workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=info msg="Shutting down helm.cattle.io/v1, Kind=HelmChartConfig workers"
Dec 20 06:34:29 rancher-centos7 rke2[24411]: time="2020-12-20T06:34:29Z" level=fatal msg="server stopped: http: Server closed"
Dec 20 06:34:29 rancher-centos7 systemd[1]: rke2-server.service: main process exited, code=exited, status=1/FAILURE
Dec 20 06:34:29 rancher-centos7 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Dec 20 06:34:29 rancher-centos7 systemd[1]: Unit rke2-server.service entered failed state.
Dec 20 06:34:29 rancher-centos7 systemd[1]: rke2-server.service failed.
Dec 20 06:35:00 rancher-centos7 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Dec 20 06:35:00 rancher-centos7 systemd[1]: Started Rancher Kubernetes Engine v2 (server).
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=warning msg="not running in CIS 1.5 mode"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Runtime image \"index.docker.io/rancher/rke2-runtime:v1.18.13-rke2r1\" bin dir already exists at \"/var/lib/rancher/rke2/data/v1.18.13-rke2r1-68fd78b98e65/bin\"; skipping extract"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting rke2 v1.18.13+rke2r1 (328b72961434301ade71381ce94b23b178c40736)"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction,PodSecurityPolicy --encryption-provider-config=/var/lib/rancher/rke2/server/cred/encryption-config.json --etcd-cafile=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/rke2/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/rke2/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/rke2/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=rke2 --service-account-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.key"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Running kube-scheduler --address=127.0.0.1 --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig --port=10251 --profiling=false --secure-port=0"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --cluster-signing-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/rke2/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/rke2/server/tls/service.key --use-service-account-credentials=true"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Node token is available at /var/lib/rancher/rke2/server/token"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="To join node to cluster: rke2 agent -s https://172.17.17.5:9345 -t ${NODE_TOKEN}"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="etcd data store connection OK"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Wrote kubeconfig /etc/rancher/rke2/rke2.yaml"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Run: rke2 kubectl"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Waiting for API server to become available"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Module overlay was already loaded"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Module nf_conntrack was already loaded"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Module br_netfilter was already loaded"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Module iptable_nat was already loaded"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Applying Pod Security Policies"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Applying Cluster Role Bindings"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Kube API server is now running"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="rke2 is up and running"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="updating namespace: kube-system"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Setting Cluster RoleBinding: system:rke2-controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Pod Security Policies applied successfully"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Cluster-Http-Server 2020/12/20 06:35:01 http: TLS handshake error from 127.0.0.1:34768: remote error: tls: bad certificate"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Cluster-Http-Server 2020/12/20 06:35:01 http: TLS handshake error from 127.0.0.1:34774: remote error: tls: bad certificate"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="certificate CN=rancher-centos7 signed by CN=rke2-server-ca@1608434316: notBefore=2020-12-20 03:18:36 +0000 UTC notAfter=2021-12-20 06:35:01 +0000 UTC"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="certificate CN=system:node:rancher-centos7,O=system:nodes signed by CN=rke2-client-ca@1608434316: notBefore=2020-12-20 03:18:36 +0000 UTC notAfter=2021-12-20 06:35:01 +0000 UTC"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Logging containerd to /var/lib/rancher/rke2/agent/containerd/containerd.log"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Running containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/containerd"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: I1220 06:35:01.420415   24954 leaderelection.go:243] attempting to acquire leader lease  kube-system/rke2...
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting k3s.cattle.io/v1, Kind=Addon controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting /v1, Kind=Node controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Cluster dns configmap already exists"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: I1220 06:35:01.858806   24954 leaderelection.go:253] successfully acquired lease kube-system/rke2
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Cluster Role Bindings applied successfully"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChartConfig controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting /v1, Kind=Pod controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting /v1, Kind=Service controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting batch/v1, Kind=Job controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting /v1, Kind=Endpoints controller"
Dec 20 06:35:01 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:01Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChart controller"
Dec 20 06:35:02 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:02Z" level=info msg="Containerd is now running"
Dec 20 06:35:02 rancher-centos7 rke2[24954]: time="2020-12-20T06:35:02Z" level=info msg="Starting /v1, Kind=Secret controller"


[root@rancher-centos7 sshuser]# netstat -tulpn | grep kubelet

It's still down after the restart of rke2-server

**Comment by brandond** [comment]
It looks like etcd is crashing for some reason:
```

Dec 20 03:28:46 rancher-centos7 rke2[3590]: {"level":"warn","ts":"2020-12-20T03:28:46.636Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Dec 20 03:28:46 rancher-centos7 rke2[3590]: time="2020-12-20T03:28:46Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Dec 20 03:29:16 rancher-centos7 rke2[3590]: {"level":"warn","ts":"2020-12-20T03:29:16.636Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Dec 20 03:29:16 rancher-centos7 rke2[3590]: time="2020-12-20T03:29:16Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Dec 20 03:29:31 rancher-centos7 rke2[3590]: {"level":"warn","ts":"2020-12-20T03:29:31.636Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Dec 20 03:29:31 rancher-centos7 rke2[3590]: time="2020-12-20T03:29:31Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Dec 20 04:15:31 rancher-centos7 rke2[3590]: {"level":"warn","ts":"2020-12-20T04:15:31.636Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Dec 20 04:15:31 rancher-centos7 rke2[3590]: time="2020-12-20T04:15:31Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Dec 20 04:15:46 rancher-centos7 rke2[3590]: {"level":"warn","ts":"2020-12-20T04:15:46.636Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-d9413be6-a208-42c7-b9fc-df75a1721e68/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Dec 20 04:15:46 rancher-centos7 rke2[3590]: time="2020-12-20T04:15:46Z" level=error msg="Failed to get recorded learner progress from etcd: context deadline exceeded"
Dec 20 04:15:52 rancher-centos7 rke2[3590]: E1220 04:15:52.349720    3590 leaderelection.go:357] Failed to update lock: Put https://127.0.0.1:6443/api/v1/namespaces/kube-system/configmaps/rke2: context deadline exceeded
Dec 20 04:15:52 rancher-centos7 rke2[3590]: I1220 04:15:52.349866    3590 leaderelection.go:278] failed to renew lease kube-system/rke2: timed out waiting for the condition
Dec 20 04:15:52 rancher-centos7 rke2[3590]: E1220 04:15:52.349932    3590 leaderelection.go:297] Failed to release lock: resource name may not be empty
Dec 20 04:15:52 rancher-centos7 rke2[3590]: time="2020-12-20T04:15:52Z" level=fatal msg="leaderelection lost for rke2"
Dec 20 04:15:52 rancher-centos7 systemd[1]: rke2-server.service: main process exited, code=exited, status=1/FAILURE
```

Can you get the etcd pod logs?

```
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=/opt/rancher/rke2/bin:$PATH
crictl logs `crictl ps -q --label io.kubernetes.container.name=etcd` &> etcd.log
```

**Comment by rajivml** [comment]
I lost that server, but I just now replicated this issue on a fresh setup, as soon as I copy the images, the kubelet went down, 

![image](https://user-images.githubusercontent.com/46923567/102709309-5f54f980-42cf-11eb-83b7-0f09b6b590d8.png)

**Comment by rajivml** [comment]
[newserver.txt](https://github.com/rancher/rke2/files/5720710/newserver.txt)

[etcd.log](https://github.com/rancher/rke2/files/5720712/etcd.log)


PFA attached logs of both rke2 server and etcd logs

**Comment by rajivml** [comment]
looks like this time, it got recovered itself in couple of minutes, on couple of setups, I noticed it was not up for lot of time 

[etcd.log](https://github.com/rancher/rke2/files/5720716/etcd.log)
[rke2_server.log](https://github.com/rancher/rke2/files/5720717/rke2_server.log)

**Comment by brandond** [comment]
Your etcd server is performing poorly. Usually this is cause by insufficient CPU resources, or slow disk IO. Since this is occurring when you copy things into the images directory, and the logs are reporting 10+ second delays in disk `fsync` calls, I am suspecting slow disk IO. What sort of host is this on? How much CPU/memory does the VM have available? Are you using SSD or rotational storage?

```
{"level":"warn","ts":"2020-12-20T08:55:34.290Z","caller":"wal/wal.go:806","msg":"slow fdatasync","took":"11.295564539s","expected-duration":"1s"}
{"level":"warn","ts":"2020-12-20T08:55:37.873Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"14.878067745s","expected-
```

**Comment by rajivml** [comment]
the VM is hosted on Azure, 8 core 32GB machine, CentOS 8.2 and only RKE2 server is running on this machine nothing else and yeah we are using SSD , premium storage azure disks ... I can increase the disk size to 1 TB and give a try again because higher the disk size, higher the IOPS we get on cloud

**Comment by brandond** [comment]
Are both sda and sdb SSDs? Do you have other workloads sharing the disk that rke2 is on? You're need to identify what's causing those incredibly high fsync times. One extreme option would be to ensure that /var/lib/rancher/rke2/server/ is on a dedicated partition. This isn't generally necessary - I've never needed to do so - but if you have other IO-heavy workloads on the same disk, etcd is going to struggle.
