### ISSUE TITLE
`rke2-killall.sh` script does not work for user defined `data-dir`

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke2#6292]
**Environmental Info:**
RKE2 Version: `v1.29.6+rke2r1`

Node(s) CPU architecture, OS, and Version: N/A

Cluster Configuration: N/A

**Describe the bug:**

The `rke2-killall.sh` script hardcodes `/var/lib/rancher/rke2` when removing pod manifests and unmounting & removing the directory:
- https://github.com/rancher/rke2/blob/master/bundle/bin/rke2-killall.sh#L53
- https://github.com/rancher/rke2/blob/master/bundle/bin/rke2-killall.sh#L63
- https://github.com/rancher/rke2/blob/master/bundle/bin/rke2-killall.sh#L98
This can cause Rancher provisioned RKE2 clusters with a different `data-dir` to fail during an etcd resotre, as it runs the killall script.

**Steps To Reproduce:**

- Provision RKE2 cluster with custom `data-dir` through Rancher
- Perform etcd restore

**Expected behavior:**

`data-dir` assets are properly removed.

**Actual behavior:**

Attempts to remove non-existent assets in `/var/lib/rancher/rke2`

**Additional context / logs:**

**Comment by fmoral2** [comment]
## Validated on Version:
```console
-$  rke2 version v1.30.2+rke2r1 (f01072ab2b9cf1a529ce188e4a8d8645813d4620)


```
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
ubuntu 
AMD
 

*Cluster Configuration:*
-1 node server 

 
 
 

## Steps to validate the fix
1. Install rke2 with a custom data-dir
2. Run kill all 
3. Validate that image was removed from custom dir

 


 
 
## **Reproduction Issue:**
<details>

``` 

 v1.30.2+rke2r1


$ k get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-19-115   Ready    control-plane,etcd,master   76s   v1.30.2+rke2r1

~$ sudo RKE2_DATA_DIR=/var/fran/rke2 rke2-killall.sh

 

$ ls  /var/fran/rke2/agent/

client-ca.crt          client-kube-proxy.key  client-kubelet.key          client-rke2-controller.key  etc     kubelet.kubeconfig    logs           rke2controller.kubeconfig  serving-kubelet.crt
client-kube-proxy.crt  client-kubelet.crt     client-rke2-controller.crt  containerd                  images  kubeproxy.kubeconfig  pod-manifests  server-ca.crt              serving-kubelet.key


$ ls /var/fran/rke2/agent/pod-manifests/

 
cloud-controller-manager.yaml  etcd.yaml  kube-apiserver.yaml  kube-controller-manager.yaml  kube-proxy.yaml  kube-scheduler.yaml

```

 
## **Validation Results:**
<details>


``` 
  ~$ k get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-             Ready    control-plane,etcd,master   57s   v1.30.3+rke2r1


~$ sudo RKE2_DATA_DIR=/var/fran/rke2 rke2-killall.sh

~$ ls /var/fran/rke2/agent/pod-manifests/
 #  empty


 ```
