### ISSUE TITLE
Add RKE2_TOKEN to get.rke2.io script

### ISSUE THREAD

**Issue by clemenko** [rancher/rke2#634]
If you could set up a PSK with the curl statement it would greatly simplify the install process. 
Example : `curl -sfL https://get.rke2.io | RKE2_AGENT_TOKEN=clemenko sh - && systemctl enable rke2-server.service && systemctl start rke2-server.service`

then the agent install would be very similar
`curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" RKE2_AGENT_TOKEN=clemenko sh - && systemctl enable rke2-server.service && systemctl start rke2-server.service`

this would eliminate having to hit every node to create the `config.yaml` file.

**Comment by clemenko** [comment]
Here is my work around
```
  ssh $user@$server 'curl -sfL https://get.rke2.io |  sh - && systemctl enable rke2-server.service && systemctl start rke2-server.service' > /dev/null 2>&1

  sleep 10

  token=$(ssh $user@$server 'cat /var/lib/rancher/rke2/server/node-token')

  pdsh -l $user -w $worker_list 'curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh - && systemctl enable rke2-agent.service && mkdir -p /etc/rancher/rke2/ && echo "server: https://'$server':9345" > /etc/rancher/rke2/config.yaml && echo "token: '$token'" >> /etc/rancher/rke2/config.yaml && systemctl start rke2-agent.service'
```

**Comment by PatrickHuetter** [comment]
This would be a very nice feature for auto-provisioning scripts. It would be really useful if we could set a custom server and agent token (our own self generated one).

**Comment by brandond** [comment]
The RKE2 install script is intentionally simpler than the k3s install script. The recommended way to configure RKE2 is by writing to the config file before starting the service; this is why the install script does not start the service for you.
