### ISSUE TITLE
Specify CNI Interface

### ISSUE THREAD

**Issue by oxr463** [rancher/rke2#635]
> Currently in K3S, there exists the option "--flannel-iface", which let's a user specify the target interface for the network CNI, due to flannel being integrated into K3S.
>
> No such option exists currently for RKE2. For example, if I were to deploy RKE2 + Calico onto a machine with multiple NICs, I would need to create an rke2-canal-config.yml prior to deployment, as found in the docs here:
https://docs.rke2.io/install/network_options/#canal-options
>
> To improve feature parity, I would suggest that RKE2 has a "--canal-iface" flag very similar to the "--flannel-iface" behavior of K3S. This value should also be able to be set by the config.yml.

gz#14042

**Comment by nikkelma** [comment]
A related internal discussion about the same topic happened about a week ago, and the resolution is the following:

The `--flannel-iface` flag in k3s is a limitation, not a preference: flannel is bundled in the k3s binary, so there's no Helm chart step of deploying flannel, and therefore no ability to change that configuration through a HelmChartConfig.

Canal in RKE2 is installed through the HelmChart resources, so they should be configured through the more portable HelmChartConfig approach. Any CNI, bundled or not, can be configured this way (along with any other Helm-based components), making it the more portable approach.

**Comment by capta1nk1rk** [comment]
@nikkelma Ah, that makes sense.  Although the lack of cli flag parity between the two is a bit confusing, it's understandable considering the deployment of the CNI is completely different (Helm vs Binary).

@oxr463 Feel free to close this issue.
