### ISSUE TITLE
Static manifests changes are not persistent after restart

### ISSUE THREAD

**Issue by mhrznamn068** [rancher/rke2#6356]
**Environmental Info:**
RKE2 Version: 
v1.26.7+rke2r1

**Node(s) CPU architecture, OS, and Version:** 
Linux master-1 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Cluster Configuration:**
3 servers, 20 workers

**Describe the bug:**
Changing the static manifests in the **/var/lib/rancher/rke2/server/manifests** directory does not persist after restarting the rke2-server or rebooting the OS. We had added a few values in the manifests below and manually applied them using kubectl apply. However, after rebooting the OS, the manifests and resources revert to their default values.

**/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml**
```
controller.config.proxy-real-ip-cidr: '0.0.0.0/0'
controller.config.use-forwarded-headers: 'true'
```

**/var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml**
cpu resource limit changed to 300m from default 100m
```
resources.limits.cpu: 300m
```

**Expected behavior:**
The changes to the static manifests should persist after restart or any similar ways to set above values to the resource that will persist forever.

**Comment by brandond** [comment]
> Changing the static manifests in the /var/lib/rancher/rke2/server/manifests directory does not persist after restarting the rke2-server or rebooting the OS

No, they don't.

> We had added a few values in the manifests below and manually applied them using kubectl apply.

Don't do that. See the docs at https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig for how to customize values for the HelmCharts that come with RKE2.
