### ISSUE TITLE
[BUG] containerd_registry “rewrite”，Bug

### ISSUE THREAD

**Issue by xzxiaoshan** [rancher/rke2#6373]
官方文档  https://docs.rke2.io/zh/install/containerd_registry_configuration  所述的私服配置，其中 rewrite 不起作用，这是一个确定的BUG。

----------------

Official documents https://docs.rke2.io/zh/install/containerd_registry_configuration The private server configuration mentioned, where rewrite does not work, is a confirmed bug.

**Comment by brandond** [comment]
I am not understanding the question - what is a confirmed bug?
