### ISSUE TITLE
rancher/rke2-runtime Image cannot find tag v1.30.3-rc1-rke2r1

### ISSUE THREAD

**Issue by leganck** [rancher/rke2#6377]
**Environmental Info:**
RKE2 Version:  v1.30.3-rc1+rke2r1

![image](https://github.com/user-attachments/assets/899b1df4-377d-402a-bc0f-a73737c2f45
Node(s) CPU architecture, OS, and Version: 

`INFO[0000] Run: rke2 kubectl
INFO[0000] Waiting for cri connection: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: connection refused"
INFO[0000] Password verified locally for node km
INFO[0000] certificate CN=km signed by CN=rke2-server-ca@1721377179: notBefore=2024-07-19 08:19:39 +0000 UTC notAfter=2025-07-19 08:25:36 +0000 UTC
INFO[0001] certificate CN=system:node:km,O=system:nodes signed by CN=rke2-client-ca@1721377179: notBefore=2024-07-19 08:19:39 +0000 UTC notAfter=2025-07-19 08:25:37 +0000 UTC
INFO[0001] Module overlay was already loaded
INFO[0001] Module nf_conntrack was already loaded
INFO[0001] Module br_netfilter was already loaded
INFO[0001] Module iptable_nat was already loaded
INFO[0001] Module iptable_filter was already loaded
INFO[0001] Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1
WARN[0001] Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1: not found in any file in /var/lib/rancher/rke2/agent/images: image not found
INFO[0001] Checking local image archives in /var/lib/rancher/rke2/agent/images for index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1
WARN[0001] Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1 from tarball: no local image available for index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1: not found in any file in /var/lib/rancher/rke2/agent/images: image not found
INFO[0001] Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1
WARN[0002] Failed to get image from endpoint: GET https://index.docker.io/v2/rancher/rke2-runtime/manifests/v1.30.3-rc1-rke2r1: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v1.30.3-rc1-rke2r1
FATA[0002] failed to get runtime image index.docker.io/rancher/rke2-runtime:v1.30.3-rc1-rke2r1: all endpoints failed: GET https://index.docker.io/v2/rancher/rke2-runtime/manifests/v1.30.3-rc1-rke2r1: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v1.30.3-rc1-rke2r1`

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
It's an RC. Releases don't always go according to plan, thats why we do release candidates first. In this case, CI failed, so we've fixed that and released an RC2. In general I would suggest not opening issues against RCs and other non-GA releases.
