### ISSUE TITLE
how to fix this issue?

### ISSUE THREAD

**Issue by tscswcn** [rancher/rke2#638]
root@kuboard ~]# lsof -i:6443
[root@kuboard ~]# systemctl status rke2-server.service
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2020-12-23 21:38:33 CST; 1min 52s ago
     Docs: https://github.com/rancher/rke2#readme
  Process: 3151 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 3148 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 3154 (rke2)
    Tasks: 28
   Memory: 50.3M
   CGroup: /system.slice/rke2-server.service
           ├─3154 /usr/bin/rke2 server
           └─3168 containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib...

12月 23 21:39:43 kuboard rke2[3154]: time="2020-12-23T21:39:43+08:00" level=info msg="Failed to test data store connection: context deadline exceeded"
12月 23 21:39:58 kuboard rke2[3154]: {"level":"warn","ts":"2020-12-23T21:39:58.800+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker fa...
12月 23 21:39:58 kuboard rke2[3154]: time="2020-12-23T21:39:58+08:00" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
12月 23 21:39:58 kuboard rke2[3154]: {"level":"warn","ts":"2020-12-23T21:39:58.811+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker fa...
12月 23 21:39:58 kuboard rke2[3154]: time="2020-12-23T21:39:58+08:00" level=info msg="Failed to test data store connection: context deadline exceeded"
12月 23 21:40:03 kuboard rke2[3154]: time="2020-12-23T21:40:03+08:00" level=info msg="Waiting for etcd server to become available"
12月 23 21:40:13 kuboard rke2[3154]: {"level":"warn","ts":"2020-12-23T21:40:13.800+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker fa...
12月 23 21:40:13 kuboard rke2[3154]: time="2020-12-23T21:40:13+08:00" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
12月 23 21:40:13 kuboard rke2[3154]: {"level":"warn","ts":"2020-12-23T21:40:13.814+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker fa...
12月 23 21:40:13 kuboard rke2[3154]: time="2020-12-23T21:40:13+08:00" level=info msg="Failed to test data store connection: context deadline exceeded"
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by tscswcn** [comment]
Last login: Wed Dec 23 14:20:11 2020 from 106.38.48.37
root@aliyun:~# uname -a
Linux aliyun 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@aliyun:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@aliyun:~#

**Comment by kennychen101** [comment]
I have the same issue....

**Comment by mbrtsk** [comment]
Are these the informative errors reported on the initial bootstrap? Maybe: https://github.com/rancher/rke2/issues/470

I was testing with a vagrant earlier and it took about 15 minutes before the node reported ready.

**Comment by tscswcn** [comment]
> Are these the informative errors reported on the initial bootstrap? Maybe: #470
> 
> I was testing with a vagrant earlier and it took about 15 minutes before the node reported ready.

after logn time, it still  shown not ready

**Comment by tscswcn** [comment]
download package and images

rke2 server 



[root@node server]# kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pods --all-namespaces
NAMESPACE     NAME                                                 READY   STATUS             RESTARTS   AGE
kube-system   etcd-node-10-41-82-40                                1/1     Running            0          34m
kube-system   helm-install-rke2-canal-wj4fz                        0/1     Completed          0          35m
kube-system   helm-install-rke2-coredns-sg9hj                      0/1     Completed          0          35m
kube-system   helm-install-rke2-ingress-nginx-7tvv4                0/1     Completed          0          35m
kube-system   helm-install-rke2-kube-proxy-4qlb9                   0/1     Completed          0          35m
kube-system   helm-install-rke2-metrics-server-4lr2l               0/1     Completed          0          35m
kube-system   kube-apiserver-node-10-41-82-40                      1/1     Running            0          34m
kube-system   kube-controller-manager-node-10-41-82-40             1/1     Running            0          34m
kube-system   kube-proxy-5dgh9                                     1/1     Running            0          35m
kube-system   kube-scheduler-node-10-41-82-40                      1/1     Running            0          34m
kube-system   rke2-canal-rj9hb                                     2/2     Running            0          35m
kube-system   rke2-coredns-rke2-coredns-6975675896-fk68m           1/1     Running            0          35m
kube-system   rke2-ingress-nginx-controller-54946dd48f-qh55d       1/1     Running            0          34m
kube-system   rke2-ingress-nginx-default-backend-5795954f8-877p6   1/1     Running            0          34m
kube-system   rke2-metrics-server-68f9fb6485-2k8zv                 0/1     CrashLoopBackOff   11         34m
[root@node-10-41-82-40 server]# kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
NAME               STATUS   ROLES         AGE   VERSION
node-10-41-82-40   Ready    etcd,master   35m   v1.19.5+rke2r1
[root@node-10-41-82-40 server]#

**Comment by tscswcn** [comment]
close this issue

**Comment by jasonwitty** [comment]
this can happen if your IP address changes. After resolving the issue and restarting the service It was not resolved for me until i reran "rancherd reset-admin"; then it came back up.
