### ISSUE TITLE
Add docs for low-level debugging details and examples

### ISSUE THREAD

**Issue by nikkelma** [rancher/rke2#639]
RKE1 had the benefit of using the familiar `docker` CLI for accessing the low-level components of a cluster (etcd, API server, etc.), but RKE2's use of pure `containerd` puts many in unfamiliar water for similar tasks.

@brandond pointed me to prefer `crictl` and leverage existing docker-to-crictl docs (1) - a few concrete examples of using this tool along with a link to the upstream docs page would greatly help users (and staff) in these low-level debugging efforts. Specific use cases include when the k8s API server doesn't become healthy, or when logs can't be grabbed through `kubectl` due to DNS limitations.

**Main question**: in which section should these docs be located? Happy to contribute the content in a PR, want to make sure they're placed properly.

(1): <https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#mapping-from-docker-cli-to-crictl>

**Comment by cjellick** [comment]
reopening as a valid docs issue.
