### ISSUE TITLE
RKE2 new installation: pod networks issues with "502 Bad Gateway"

### ISSUE THREAD

**Issue by RogerSik** [rancher/rke2#6404]
Installing a new rke2 cluster on an ubuntu 22.04 / 24.04 (means both os tested) I have strange issue with the network.

Also tested this with: rke2 1.29.6 and 1.30.2.

It is a single node cluster.

My server has 2 network card (eth0 public and enp7s0 for internal)

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 96:00:03:8f:35:5d brd ff:ff:ff:ff:ff:ff
    inet 116.203.xxx.xxx/32 metric 100 scope global dynamic eth0

3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether 86:00:00:98:e5:5c brd ff:ff:ff:ff:ff:ff
    inet 10.128.196.2/32 brd 10.128.196.2 scope global dynamic enp7s0
```

**/var/lib/rancher/rke2/server/manifests/rke2-canal-network-config-value.yaml**
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      iface: 'enp7s0'
```

**/etc/rancher/rke2/config.yaml**
```
tls-san:
  - 10.128.196.2
  - vnc-kubernetes
  - 127.0.0.1
  - 127.0.0.1:9345
  - 116.203.113.130

node-ip: 10.128.196.2
node-name: vnc-kubernetes
node-external-ip: 116.203.113.130
bind-address: 10.128.196.2
advertise-address: 10.128.196.2

cluster-domain: cluster.local

etcd-snapshot-schedule-cron: "0 */2 * * *"
etcd-snapshot-retention: 7

disable: rke2-ingress-nginx

kube-apiserver-arg: "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
```

rke2-server is succesfull started. But if i want to do an kubectl logs (don't matter if on server or from remote to the public ip) I get following errors:
```
│ stream logs failed Get "https://10.128.196.2:10250/containerLogs/argocd/argocd-applicationset-controller-656b74445b-4llfd/applicationset-controller?follow=true&tai ││ lLines=100&timestamps=true": proxy error from 10.128.196.2:9345 while dialing 10.128.196.2:10250, code 502: 502 Bad Gateway for argocd/argocd-applicationset-contro ││ ller-656b74445b-4llfd (applicationset-controller)  
```

```
$k port-forward service/argocd-server 8080:80 -n argocd 
error: error upgrading connection: error dialing backend: proxy error from 10.128.196.2:9345 while dialing 10.128.196.2:10250, code 502: 502 Bad Gateway
```

Strange issue. Sometimes after a restart / reboot of the rke2-server or server it works for 1-2 minutes and than again happening these problems. Because it is a brand new cluster im  becoming desperating why is is not working. 

This setup is deployed on Hetzner Cloud.

PS. No need to mask the ip address is a throw away / test cluster.

**Comment by RogerSik** [comment]
It seems that my issue was:

**/etc/rancher/rke2/config.yaml**
```
bind-address: 10.128.196.2
```

without it. It works fine:

```
$ k port-forward service/argocd-server 8080:80 -n argocd (⎈|vnc-kubernetes/direct:default)
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

**Comment by RogerSik** [comment]
But i don't understand why i have here issues with it. On my other RKE2 Cluster with RKE2 1.28.10 there where no issue with same setup (2 network cards).

**Comment by brandond** [comment]
This is 
* https://github.com/k3s-io/k3s/issues/10444

Fixed in this month's releases.
