### ISSUE TITLE
Feature Request: RKE2 Support for Mixed Mode Registry

### ISSUE THREAD

**Issue by rajivml** [rancher/rke2#641]
HI,

w.r.t Airgapped installs, 

If Docker private registry is installed on the same RKE2 cluster where all your target applications are deployed, then the same registry cannot be configured via system-default-registry param and as a result we have to patch our helm templates at so many places using kustomize to make helm/kubectl aware of docker private registry
       
So, what we are trying to achieve here is we want to use default registry location (i.e /var/lib/rancher/rke2/agent/images) for bootstrapping the RKE2 cluster and once the cluster is up we want to setup docker private registry over there and use the same for rest of the helm/kubectl installs.

But if we set system-default-registry to the docker private registry IP, RKE2 will no longer look at the path "/var/lib/rancher/rke2/agent/images" where the images required to bootstrap the k8 cluster are located and as a result cluster can't boot up

Where as our expectation is RKE2 should look at both "/var/lib/rancher/rke2/agent/images" location as well as the registryIP that we have configured via system-default-registry property, so that we don't have to patch any of our helm-charts and it will make the life of the customers much easy.

In the absence of this support, customers has to resort to kustomize or use some other open source library like this, but the problem using these kind of open source plugins is lack of support and these plugins can get deprecated any time due to lack of committers 
https://github.com/phenixblue/imageswap-webhook

**Comment by rajivml** [comment]
More context about the request can be found here: https://rancher-users.slack.com/archives/C3ASABBD1/p1608958174187100

**Comment by rajivml** [comment]
I think it makes more sense to support this at the platform level , from last one week am just doing this one thing of patching our helm templates in different ways so that RKE2 is aware of those images.

If RKE2 supports this out of box i.e. look for images at  "/var/lib/rancher/rke2/agent/images" first followed by looking for images at the system-default-registry-ip configured before bailing out, then it will solve the issue for those customers who want to setup docker private registry on the same original cluster where all original workloads are deployed

**Comment by rajivml** [comment]
any chance of this getting picked up ? if there are doubts, please let me know , I can share further details

**Comment by brandond** [comment]
I believe #715 should address your concerns. You will still need to be careful with the manifests needed to bootstrap the in-cluster registry to ensure that the imagePullPolicy is set to IfNotPresent, but once that is merged you will be able to use an airgap tarball at the same time as --system-default-registry. Note that you will still probably want to use registries.yaml to redirect docker.io to your private registry to avoid having to update the manifests for everything else you're deploying.

**Comment by rajivml** [comment]
awesome, thanks @brandond that's a great news and will reduce the steps involved in an airgap install. Please update here once once it's merged, we will try asap and share feedback

**Comment by cjellick** [comment]
assign to 1.20.4 and brad, since his PR addresses this

**Comment by rancher-max** [comment]
#### Validated in v1.20.4-rc2+rke2r1

See notes from https://github.com/rancher/rke2/issues/683#issuecomment-790953975. I believe this has been addressed and solved now. I would follow Brad's recommendation from the previous comment to use all three options: registries.yaml (for the mirroring of your images as the cluster is used -- this is what will be most important for the helm/kubectl installs), tarball (to retrieve the bootstrapped images initially), and system-default-registry (to make it look like the system images come from the private registry as well).

I think you might not even need to use the system-default-registry for what you are looking for, as with the registries.yaml setup you should be able to perform any additional helm installs on the cluster, assuming your private registry contains all the images needed.

@rajivml I'm closing this out, but if the solution doesn't quite meet your needs, feel free to reopen and let us know what is missing.

**Comment by rajivml** [comment]
Thanks @rancher-max , I will try this next week and will share the feedback

**Comment by rajivml** [comment]
@rancher-max @brandond @nikkelma  I was under the impression that if we set system-default-registry to dockerPrivateRegistryIP, then every other image path that is part of deployment template get's prefixed with dockerPrivateRegistryIP but looks like that's not the case and is applicable only for rancher specific helm charts , can you plz confirm the same ?

For example if deployment template is ,
```
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: ngnix:latest
      restartPolicy: Never
```

and if registries.yaml is point to,

configs:
  "10.43.1.2":
    auth:
      username: xxxxxx # this is the registry username
      password: xxxxxx # this is the registry password
  "10.43.x.x":

Then I thought,  "10.43.1.2/ngnix:latest" will be tried first followed  "10.43.x.x/ngnix:latest" , so that we don't have to patch all our templates for airgap environment

**Comment by brandond** [comment]
system-default-registry is a chart value that is only supported by RKE2 and Rancher helm charts. If you want to pull from another registry for all images, even those from community charts, you're best off using the private registry configuration (registries.yaml).

**Comment by rajivml** [comment]
Thanks @brandond by configuring mirrors we were able to resolve the issue
