### ISSUE TITLE
[nit] v1.30.1+rke2r1 runc version listed as 1.1.

### ISSUE THREAD

**Issue by dweomer** [rancher/rke2#6410]
hey, super minor nit, just noticed this looking for latest cilium version we package:
![image](https://github.com/user-attachments/assets/fcbd00ef-dcb8-4d1c-9928-2fb395e2ff15)

**Comment by brandond** [comment]
* https://github.com/rancher/rke2/issues/5340#issuecomment-1975330600
* https://github.com/rancher/rke2/discussions/6145
* https://github.com/rancher/ecm-distro-tools/issues/361

**Comment by dweomer** [comment]
looks like this is covered by:
- https://github.com/rancher/ecm-distro-tools/issues/361
