### ISSUE TITLE
Modsecurity does not work in new releases (nginx-ingress-controller:v1.10.1)

### ISSUE THREAD

**Issue by kfkawalec** [rancher/rke2#6411]
**Environmental Info:**
RKE2 Version: 
v1.27.15+rke2r1

**Describe the bug:**
Unable to user ModSecurity in "nginx-ingress-controller:v1.10.1-hardened1", error:
```
dlopen() "/etc/nginx/modules/ngx_http_modsecurity_module.so" failed (liblua5.4.so.5: cannot open shared object file: No such file or directory)
```
Version "nginx-ingress-controller:v1.9.6-hardened1" works without any issue.

I tried to downgrade helm chart to 4.9.101 but the server automatically installed 4.10.101.
Maybe there is a way to do a permanent downgrade?

**Steps To Reproduce:**
Upgrade cluster to v1.27.15+rke2r1

**Comment by dereknola** [comment]
Can you give more information on your nginx config and setup. This will help me in reproducing this issue. I overhauled the base image that we ship with ingress-nginx to SLES 15.6 base and likely didn't include all the libraries from 1.9.6.

**Comment by kfkawalec** [comment]
I am using Ubuntu 22.04.3 LTS on the nodes.
I have installed liblua5:
```liblua5.4-0 is already the newest version (5.4.4-1)``` 

What other information is required?

**Comment by aganesh-suse** [comment]
Newer nginx controller bump: https://github.com/rancher/rke2-charts/pull/502/

**Comment by aganesh-suse** [comment]
Closing based on release-1.30 results: https://github.com/rancher/rke2/issues/6475
