### ISSUE TITLE
Security Vulnerability: Prometheus 2.48 <= 2.52 - End of Life Notification (EOL)

### ISSUE THREAD

**Issue by varunbondre** [rancher/rke2#6412]
**Is your feature request related to a problem? Please describe.**
We are consuming rancher/hardened-k8s-metrics-server container image for our project downloaded as part of the rke2 tarball . Recently we received a notification that the Prometheus versions 2.48 to 2.52 have reached end of life, please refer [here](https://endoflife.date/prometheus) or [here](https://prometheus.io/docs/introduction/release-cycle/). The aforementioned image is internally using the version v0.48.1 of Prometheus that is no longer supported. Prometheus v2.y.z releases are published with equivalent v0.y.z tags for Go library. Refer [here](https://github.com/prometheus/prometheus?tab=readme-ov-file#prometheus-code-base).

**Describe the solution you'd like**
We would like to request an upgrade to the supported version of Prometheus.

**Additional context**
I would just like to reiterate the importance of updating the EOL packages, if a version reaches End Of Life, there won’t be any security fixes done for these versions and also the vulnerabilities are not reported for these versions. This sounds like a security risk. I hope this request is taken on priority.

**Comment by brandond** [comment]
I'll paraphrase my response from https://github.com/rancher/rke2/issues/6403#issuecomment-2248817606:
> Hardened images are built directly from upstream project's source code without any patches. Any questions about library use by the core Kubernetes components should be directed to the upstream project.

The most recent release of metrics-server is 0.7.1 and uses the versions noted in your comment: https://github.com/kubernetes-sigs/metrics-server/blob/v0.7.1/go.mod#L9-L10
There is an automated PR open to bump that version: https://github.com/kubernetes-sigs/metrics-server/pull/1530

We've seen several issues from different users, using very similar language to request module version updates for 3rd party projects that we do not own. If you are all associated with the same organization, please communicate internally to ensure that you are following the correct process to get your desired changes made. You need to be working with the upstream projects, NOT filing a bunch of issues and vulnerability reports here with RKE2.
