### ISSUE TITLE
Rke2 server could not start on Ubuntu 22.04

### ISSUE THREAD

**Issue by yukuotec** [rancher/rke2#6416]
containerd not start, hence rke2 server not be able to start.
firewall and apparmor are disabled

**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.11+rke2r1 (6b12d7a783238b72da8450fa1b6ec587cebb79ed)
go version go1.21.11 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux rek2-1 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server only

**Describe the bug:**
server fail to start

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**
server can start successfully
[install.log](https://github.com/user-attachments/files/16387298/install.log)

**Actual behavior:**
server not start

**Additional context / logs:**
time="2024-07-26T14:07:15+08:00" level=debug msg="Supervisor proxy using supervisor=https://127.0.0.1:9345 apiserver=https://127.0.0.1:9345 lb=false"
W0726 14:07:15.942218    7512 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "/run/k3s/containerd/containerd.sock", ServerName: "%2Frun%2Fk3s%2Fcontainerd%2Fcontainerd.sock", }. Err: connection error: desc = "transport: Error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory"
time="2024-07-26T14:07:15+08:00" level=info msg="Waiting for cri connection: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""

**Comment by brandond** [comment]
I don't see the `rancher/rke2-runtime:v1.28.11-rke2r1` image pull ever complete. I do see that something seems to have interfered with RKE2's ability to create the data dir - it should have been created before the chmod attempted to change its permissions here:
`level=fatal msg="chmod /var/lib/rancher/rke2/data/v1.28.11-rke2r1-b8960a847dfd/bin: no such file or directory"`

You can try running `rm -rf /var/lib/rancher/rke2/data` and then restarting RKE2; assuming this node can pull the rke2-runtime image successfully it should recreate the missing directories. If you continue to get errors, ensure that you don't have anything else on this node (such as antivirus or anti-malware software) preventing RKE2 from creating files under /var/lib/rancher.

**Comment by tunicashashi** [comment]
I am also facing a similar issue with cri connection while installing rke2 latest i.e rancher/rke2-runtime:v1.30.3-rke2r1 on ubuntu 22.04
` connection error: desc = \"transport: Error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory`
I have containerd.sock available in /run/containerd/containerd.sock as it was installed using docker not k3s. Is k3s mandatory to be installed before running rke2 or how do I change default path for containerd.sock ?

If you want to point out from my attached log also error like " level=warning msg="Failed to load runtime image index.docker.io/rancher/rke2-runtime:v1.30.3-rke2r1"

Then I wanted to know why this error occur, I guess Contenerd.sock and and failed to load runtime image is somehow related. I tried to pull image using docker pull, I am able to pull fully.  (Note: my setup is behind proxy
[rke2_issue.log](https://github.com/user-attachments/files/16534249/rke2_issue.log)
)
