### ISSUE TITLE
[BUG] 快照 Snapshots 同步到 S3 问题

### ISSUE THREAD

**Issue by xzxiaoshan** [rancher/rke2#6417]
![image](https://github.com/user-attachments/assets/1d2c3bd4-1840-4d80-9c6c-cc742019882d)

![image](https://github.com/user-attachments/assets/2e01c795-1777-4d1f-a83e-d7803864d4dd)

**Comment by caroline-suse-rancher** [comment]
Can you please fill out our bug report template, [here](https://github.com/rancher/rke2/issues/new/choose)?
