### ISSUE TITLE
`enable-selinux: true` is incompatible with `disable-etcd: true` due to lack of SELinux policy setup

### ISSUE THREAD

**Issue by xyzzyz** [rancher/rke2#6428]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.27.15+rke2r1 (4014ef7e8fbfb47e6a1e2261a73ca50aef8ba7fb)
go version go1.21.11 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 
RHEL 8.8 on x86_64 arch

Cluster Configuration:
1 single server node, no agents

**Describe the bug:**
when you `enable-selinux: true` and `disable-etcd: true` at the same time, RKE2 fails to start due to SELinux issues

**Steps To Reproduce:**

- Installed RKE2: follow instructions here https://docs.rke2.io/install/quickstart
- set `enable-selinux: true` and `disable-etcd: true` in `/etc/rancher/rke2/config.yml`
- run `sudo rke2 server` (using `systemctl start rke2-server`  will not work due to unrelated issue 

**Expected behavior:**
RKE2 starts correctly

**Actual behavior:**
kube-apiserver never comes up. We get the following in journald logs:
```
Jul 30 15:59:32 rhel setroubleshoot[26043]: SELinux is preventing /usr/local/bin/kube-apiserver from write access on the sock_file kine.sock.
```

**Additional context / logs:**

**Comment by brandond** [comment]
This doesn't have anything to do with enabling or disabling etcd.

Ensure that you are installing RKE2 from RPM, and that you have the container-selinux and rke2-selinux packages installed. These are normally handled by the install script, as dependencies of the rke2-common package. It is possible that we've not tested kine support with selinux yet; I'd have to defer to QA for that.

> run `sudo rke2 server`

Don't do this. For general operation, should be run as a systemd unit, not as an interactive process via sudo. What is the "unrelated issue" that is causing you to be unable to use the systemd unit?

**Comment by xyzzyz** [comment]
The unrelated issue is https://github.com/rancher/rke2/issues/6427 .

> This doesn't have anything to do with enabling or disabling etcd.

This is not true: the file causing SELinux policy errors, `sock_file kine.sock`, only exists when RKE2 is configured to run with Kine, which is a replacement for etcd. You won't see this error when you use etcd, because nothing will then try to connect to `kine.sock`.

> Ensure that you are installing RKE2 from RPM, and that you have the container-selinux and rke2-selinux packages installed.

I did ensure that. Everything works fine with `selinux: true` if I don't disable etcd. When I disable `etcd,` I get these `kine.sock` errors. Adding the following additional rules fixes it:
```
module kube-apiserver-kine 1.0;

require {
        type container_runtime_t;
        type rke2_service_t;
        type container_var_lib_t;
        class sock_file write;
        class unix_stream_socket connectto;
}

#============= rke2_service_t ==============
allow rke2_service_t container_runtime_t:unix_stream_socket connectto;
allow rke2_service_t container_var_lib_t:sock_file write;
```

> It is possible that we've not tested kine support with selinux yet; I'd have to defer to QA for that.

Yes, I think that this is the case, and the point of this issue is to ensure that this is on someone's radar.

Thanks!

**Comment by vitorsavian** [comment]
@xyzzyz ty for the report, but we already tracked this issue, that is this one here -> https://github.com/rancher/rke2/issues/5924

**Comment by brandond** [comment]
Closing as duplicate of #5924
