### ISSUE TITLE
[Release-1.30] - `rke2-traefik` Image is missing from airgap tarball

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6440]
Backport fix for `rke2-traefik` Image is missing from airgap tarball

* #6438

**Comment by mdrahman-suse** [comment]
# Validation with RC v1.30.3-rc5+rke2r1

## Testing
- Create rke2 air-gapped cluster with flag `ingress-controller: traefik`

## Validation
```
v1.30.3-rc5+rke2r1
```
- Tested with Private Registry, System Default Registry and Tarball methods
- Verified cluster came up successfully

NOTE: 
For tarball installation, needed to additionally copy the traefik image as it is not part of the core image packaging 
- `rke2-images-traefik.linux-amd64.tar.gz`
