### ISSUE TITLE
RKE2 Airgapped Install Not Considering Image Pull secrets

### ISSUE THREAD

**Issue by rajivml** [rancher/rke2#647]
HI,

Rancher server is not injecting imagePullSecrets that I have passed via helm-chart into the helm-controller pods as a result image pull from docker private registry is failing

because of this what ever charts am enabling from Rancher UI, all those components are not getting installed as each install gets triggered as an helm job and the helm job doesn't have imagePullSecret section.

I don't see imagePullSecrets being passed from the code as well https://github.com/rancher/rancher/blob/2506427ba7bd31edf12f7110b7fdb8b2defe8eb3/pkg/catalogv2/helmop/operation.go#L711 

**Step 1)** Push and pull the images 
Release am using:
https://github.com/rancher/rancher/releases/tag/v2.5.3
I have pulled all the images through the shell scripts documented here and pushed the same to docker private registry 

**Step 2)** Installing Rancher via Helm Chart and use cert-manager for cert rotation 

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm fetch rancher-stable/rancher --version=v2.5.3
tar -xzvf rancher-2.5.3.tgz
helm template rancher . --namespace cattle-system --set hostname=xxx.northeurope.cloudapp.azure.com > all.yaml
kustomize build . > all_final.yaml
sed -i "s/DOCKER_REGISTRY_IP/xx.xx.31.128/g" all_final.yaml

**Artifacts:**
Here is the final zip for the reference and you can see both imagePullCredentials and systemDefaultRegistry configured under the helm chart
[all_final.zip](https://github.com/rancher/rke2/files/5758666/all_final.zip)

Now the deployment which are getting triggered they are considering docker registry IP but they are totally ignoring the imagePullSecret that has been configured . 
When am enabling the Monitoring and istio via Rancher UI then also it's the same issue imagePulls are failing with 401 UnAuthorized because imagePullSecret doesn't exist in any of those deployments created.

These are the logs when I enabled istio via Rancher, It's failing with 401 Un-Authorized because helm templates didn't considered imagePullSecret,

```
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  54m (x3001 over 154m)   kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Pulling    47m                     kubelet  Pulling image "10.43.31.128/prom/prometheus:v2.12.0"
  Warning  Failed     47m                     kubelet  Failed to pull image "10.43.31.128/prom/prometheus:v2.12.0": rpc error: code = Unknown desc = failed to pull and unpack image "10.43.31.128/prom/prometheus:v2.12.0": failed to resolve reference "10.43.31.128/prom/prometheus:v2.12.0": unexpected status code [manifests v2.12.0]: 401 Unauthorized
  Warning  Failed     47m                     kubelet  Error: ErrImagePull
  Normal   BackOff    47m                     kubelet  Back-off pulling image "10.43.31.128/prom/prometheus:v2.12.0"
  Warning  Failed     47m                     kubelet  Error: ImagePullBackOff
```

All these helm-operation pods have the same issue, imagePullSecret didn't exist, but rancher-server doesn't have that problem. The registry and pull secret that have been configured, they should get percolated for these deployments as well right ?

[root@rancher-federal-airgap rancher]# kubectl -n cattle-system get pods
NAME                      READY   STATUS             RESTARTS   AGE
helm-operation-2bt95      0/2     ImagePullBackOff   0          35m
helm-operation-2mdlz      0/2     ImagePullBackOff   0          7m15s
helm-operation-9dtlt      0/2     ImagePullBackOff   0          36m
helm-operation-clr6g      0/2     ImagePullBackOff   0          51m
helm-operation-cpmnq      0/2     ImagePullBackOff   0          6m15s
helm-operation-h9trr      0/2     ImagePullBackOff   0          5m15s
helm-operation-hnxfk      0/2     ImagePullBackOff   0          20m
helm-operation-s45zb      0/2     ErrImagePull       0          21m
helm-operation-s5xrp      0/2     ImagePullBackOff   0          37m
helm-operation-t4gsj      0/2     ImagePullBackOff   0          22m
helm-operation-v9blc      0/2     ImagePullBackOff   0          50m
helm-operation-wtfkv      0/2     ErrImagePull       0          52m
rancher-587547594-6m6fp   1/1     Running            2          3h17m

All these guys have the same issue 
![image](https://user-images.githubusercontent.com/46923567/103434420-066a5700-4c27-11eb-81d5-bfe10de2d47c.png)

Please refer to the yaml that I have attached which is the final yaml applied...also I have edited the rancher deployment and have this prop manually so that system charts are visible via rancher UI

        - name: CATTLE_SYSTEM_CATALOG
          value: bundled

Can you guys please look at the code and see if imagePullSecrets are getting percolated everywhere or not or else let me know what am doing wrong .

**Comment by rajivml** [comment]
I went through the code related to helm operation pods and I don't see imagePullSecrets being passed over there, 

https://github.com/rancher/rancher/blob/master/pkg/catalogv2/helmop/operation.go

**Comment by rajivml** [comment]
And am trying to add secret via UI to see if that helps by following this section, 

![image](https://user-images.githubusercontent.com/46923567/103435002-d0c96c00-4c2e-11eb-9834-dafde5b8e0e3.png)

I don't see a resource section either in global view or cluster view 

![image](https://user-images.githubusercontent.com/46923567/103435017-0a9a7280-4c2f-11eb-8792-515c7f8e4185.png)


![image](https://user-images.githubusercontent.com/46923567/103435031-2dc52200-4c2f-11eb-9376-ad11eedf685b.png)

**Comment by rajivml** [comment]
Some how in the setup I have done, there was no default project, I have created one and am able to see the Resources section and I have feeded the registry credentials over there and the secret got created now

grafana-project-monitoring-66b8884bd6-7sl6z
![image](https://user-images.githubusercontent.com/46923567/103444661-91cc0280-4c90-11eb-8d1e-f504510a8ec0.png)

Now I have enabled monitoring for this project and I can see that the secret is percolated to this namespace, but the monitoring deploying is still failing because the deployment is not using the secret that has been created that's why it's resulting in 401 un-authorized 

Can you please let me know if this is a bug from your side or there is some misconfiguration on my side ?

![image](https://user-images.githubusercontent.com/46923567/103444682-c6d85500-4c90-11eb-993f-dedd9c664fa8.png)

![image](https://user-images.githubusercontent.com/46923567/103444704-0a32c380-4c91-11eb-9c13-eb7337ff7b75.png)

**Comment by rajivml** [comment]
and these helm operation pods have almost made the system un-usable because of this issue where too many pods are getting spawned in an attempt to re-try but are failing, to bring back to state, I have to run otherwise with any new deployment I am getting "too many pods error"

kubectl -n cattle-system get pods| grep helm-operation | awk -F ' ' '{print $1}' | xargs -l1 -- sh -c 'kubectl -n cattle-system delete pod $0'

**Comment by cjellick** [comment]
@brandond can you have a look when you get a chance? is this covered by your airgap enhancements?

**Comment by brandond** [comment]
The helm job pods won't reference any image pull secrets, as we don't provide any way to reference those from the job pod specs. Putting registry credentials in registries.yaml should work though (and always should have worked).

**Comment by rajivml** [comment]
If we put registry credentials under registries.yaml , then how will helm operation pods authenticate with private registry when authentication is enabled ?

**Comment by rajivml** [comment]
I haven't configured the registry via registries.yaml because at the time of RKE2 cluster creation, the registry wouldn't even exist and we are setting up docker private registry on the same cluster.

So, in this scenario how do we make containerd aware of this registry that has been setup on the same RKE2 cluster ?

**Comment by brandond** [comment]
@rajivml 
> And the other fear that I have is, if we configure registry via registries.yaml, it will become the systemGlobalRegistry

registries.yaml has nothing to do with systemDefaultRegistry; it simply configures system-level registry endpoint and credentials configuration that is used by both containerd and the rke2 runtime image pull.


> and during machine boot, it will no longer look at /var/rancher/rk2/agent/images location

Images are imported from this location regardless of what's configured in systemDefaultRegistry or registries.yaml. There is no condition under which images are not loaded from tarballs.
