### ISSUE TITLE
Ingress-nginx-controller only allows ingress from first node

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#649]
I would expect the default install condition to allow ingress from all nodes, and only have to supply an additional HelmChartConfig if not desiring this functionality. 

Currently, it is deploying as a deployment and only allowing ingress from the first node. See annotations on the deployment:
```
field.cattle.io/publicEndpoints: '[{"nodeName":"c-zfpk8:machine-ffm6p","addresses":["<node 1 public ip redacted>"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-d4989f458-c87lw","allNodes":false},{"nodeName":"c-zfpk8:machine-ffm6p","addresses":["<node 1 public ip redacted>"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-d4989f458-c87lw","allNodes":false}]'
```

We might've chosen to use a deployment instead of a daemonset for this due to semver formatting. See https://github.com/rancher/rke2/issues/493 for more information.

**Comment by briandowns** [comment]
PR makes the necessary change to the chart: https://github.com/rancher/rke2-charts/pull/78

**Comment by rancher-max** [comment]
Validated this is working on v1.21.1-alpha4+rke2r1.

Waiting to close until validating v1.19 and v1.20 release branches when rc's are made available for those.

**Comment by rancher-max** [comment]
We actually don't want to backport this as it could have negative consequences on the other branches. Closing as validated in the expected milestone.
