### ISSUE TITLE
Unable to access Prometheus metrics of etcd component in single node RKE2 cluster

### ISSUE THREAD

**Issue by developer1622** [rancher/rke2#6492]
Hi Team, I am not sure, if this is bug or something wrong from my side to access the below info. Basically I am trying to access etcd prometheus metricd using Prometheus pod, but unable to access it though I have certificates access. Thank you

**Environmental Info:**

RKE2 Version: 

rke2 version v1.28.11+rke2r1 (6b12d7a783238b72da8450fa1b6ec587cebb79ed)
go version go1.21.11 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux myhostname 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single node cluster

**Describe the bug:**

I have followed below page to install single node RKE2 cluster

https://docs.rke2.io/install/quickstart

I have prometheus pod and it has access to hostNetwork, I am able to access the Prometheus metrics of kube-api server, kube-scheduler, kube-control-manager, coredns, kube-proxy, kubelet but not the **etcd**  Prometheus metrics, I have tried accessing locally on the node or inside the pod with various certificates from the below folder

``/var/lib/rancher/rke2/server/tls/etcd`` , I have tried 2379, 2380, 2381.

**Steps To Reproduce:**
- Installed RKE2 single node cluster: 

**Expected behavior:**
Able to access etcd Prometheus metrics on a port

**Actual behavior:**
throwing errors and unable to see the etcd Prometheus metrics, not able to find port and some cert errors.

**Additional context / logs:**
NA

**Comment by brandond** [comment]
Have you tried adding the etcd-expose-metrics flag to your RKE2 configuration?

https://docs.rke2.io/reference/server_config#database
