### ISSUE TITLE
Add 1.18 and 1.19 versions to channels

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#652]
Installing via RPM should be set now via https://github.com/rancher/rke2/issues/538

Now that we have a 1.19 release out for RKE2, we should adopt version specificity within [channels.yaml](https://github.com/rancher/rke2/blob/master/channels.yaml) Much like we do today already in [k3s](https://github.com/k3s-io/k3s/blob/master/channel.yaml#L20)

We should add 1.18 and 1.19 entries but not *-testing entries as we elected to stop doing that in K3s a while back as per that comment in k3s channel.yaml.

**Comment by Oats87** [comment]
This was already done by: https://github.com/rancher/rke2/pull/669

**Comment by ShylajaDevadiga** [comment]
Validated CHANNEL v1.18 and v1.19 on ubuntu and centos
```
$ curl -sfL https://get.rke2.io| sudo INSTALL_RKE2_CHANNEL=v1.18 sh -
$ rke2 -v
rke2 version v1.18.15+rke2r1 (44a0b3f1821709c882dcb0471f2eb8aa41e2206d)
go version go1.13.15b4
$ kubectl get nodes
NAME                                         STATUS   ROLES         AGE     VERSION
ip-172-31-1-118.us-east-2.compute.internal   Ready    etcd,master   3m36s   v1.18.15+rke2r1

$ curl -sfL https://get.rke2.io| sudo INSTALL_RKE2_CHANNEL=v1.19 sh -
$ rke2 -v
rke2 version v1.19.7+rke2r1 (d1430ad44dc162f15a54d093439c20ffb91f559b)
go version go1.15.5b5
$ kubectl get nodes
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-19-145   Ready    etcd,master   70s   v1.19.7+rke2r1
```
