### ISSUE TITLE
Helm Chart upgrade fails  after upgrade from rke2 v1.28.8+rke2r1 to v1.29.6+rke2r1

### ISSUE THREAD

**Issue by shindebshekhar** [rancher/rke2#6568]
**Environmental Info:**
RKE2 Version: v1.28.8+rke2r1

:~ # rke2 -v
rke2 version v1.28.8+rke2r1 (42cab2f61939504cb17073e47deaea0b29fe2c1b)
go version go1.21.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 

Linux hostname 5.3.18-150300.59.161-default #1 SMP Thu May 9 06:59:05 UTC 2024  x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 Master 3 Worker nodes

**Describe the bug:**

We are trying to upgrade rke2 from v1.28.8+rke2r1(fresh install) to v1.29.6+rke2r1

After first master upgrade rke2 service comes up but we see all the helm jobs fails for system components calico, coredns, ingress, metrics, vsphere, snapshot controller. Helm Jobs are retriggered in continuous loop(possibly trying to upgrade the above components)

```
kube-system       helm-install-rancher-vsphere-cpi                0/1           2s         2s
kube-system       helm-install-rancher-vsphere-csi                0/1           1s         1s
kube-system       helm-install-rke2-calico                        0/1           1s         1s
kube-system       helm-install-rke2-calico-crd                    0/1           1s         1s
kube-system       helm-install-rke2-coredns                       0/1           1s         1s
kube-system       helm-install-rke2-ingress-nginx                 0/1           1s         1s
kube-system       helm-install-rke2-metrics-server                0/1           0s         0s
kube-system       helm-install-rke2-snapshot-controller           0/1           10s        10s
kube-system       helm-install-rke2-snapshot-controller-crd       0/1           0s         0s
kube-system       helm-install-rke2-snapshot-validation-webhook   0/1           10s        10s

```
On further investigation, we found that the tigera opertor has below error:

```
{"level":"error","ts":"2024-08-14T15:30:00Z","msg":"
Could not wait for Cache to sync
","controller":"tigera-installation-controller","error":"
failed to wait for tigera-installation-controller caches to sync: failed to get informer from cache: no matches for kind \"ImageSet\
" in version \"operator.tigera.io/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:211\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:242\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/manager/runnable_group.go:219"}
{"level":"error","ts":"2024-08-14T15:30:00Z","msg":"error received after stop sequence was engaged","error":"failed to wait for tigera-installation-controller caches to sync: failed to get informer from cache: no matches for kind \"ImageSet\" in version \"operator.tigera.io/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/manager/internal.go:555"}
```
Also all the crds related to calico are deleted.
kubectl get crds | grep -i calico --> No result

**Comment by brandond** [comment]
Why are the helm install jobs failing?

**Comment by mugambika** [comment]
Logs from helm-install-rke2-calico-crd pod -

helm_v3 install --set-string global.clusterCIDR=x.x.xx/x --set-string global.clusterCIDRv4=x.x.x.x/x --set-string global.clusterDNS=x.x.x.x --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=x.x.x.x/x rke2-calico-crd /tmp/rke2-calico-crd.tgz
Error: INSTALLATION FAILED: cannot re-use a name that is still in use

**Comment by brandond** [comment]
Do they **all** say the same thing? I can't tell which of your job pods have succeeded and which have failed, you trimmed a bunch of stuff off the kubectl output.

**Comment by brandond** [comment]
The jobs and pods are all just seconds old, which suggests that something is thrashing the helmchart resources and causing them to be redeployed. Can you confirm that all of the servers in the cluster have been upgraded to the latest release, and are identically configured? Check the rke2-server logs on all the server nodes to see if they are perhaps stuck in a loop deploying conflicting versions of the HelmChart AddOns. You can also do `kubectl get event -A` and see if there are an excessive number of events from the addon deploy controller.

**Comment by mugambika** [comment]
Yes, all the servers are upgraded to latest release. Now we do not see the helm job getting re-deployed as earlier. But the issue with calico-crd and calico pods still remains.

**Comment by brandond** [comment]
Can you identify what was causing the thrashing? Had you left the cluster only partially upgraded?

It looks like the chart is stuck uninstalling due to the job pod getting killed partway through the process. I would probably try deleting the rke2-calico and rke2-calico-crd helm secrets from the kube-system namespace so that the chart can be successfully reinstalled.

**Comment by mugambika** [comment]
Yes, after first control-plane upgrade we observed that the helm charts were not updated and hence were troubleshooting on it.

After deleting the helm secrets for rke2-calico and rke2-calico-crd the helm jobs did run and some of them completed. But after that the calico-system namespace is in Terminating state.

**Comment by mugambika** [comment]
```shellSession
NAMESPACE                  NAME                                            COMPLETIONS   DURATION   AGE
cattle-gatekeeper-system   rancher-gatekeeper-crd-delete                   0/1           85m        85m
kube-system                helm-install-rancher-vsphere-cpi                1/1           10s        107m
kube-system                helm-install-rancher-vsphere-csi                1/1           13s        107m
kube-system                helm-install-rke2-calico                        1/1           72m        107m
kube-system                helm-install-rke2-calico-crd                    1/1           72m        107m
kube-system                helm-install-rke2-coredns                       1/1           12s        107m
kube-system                helm-install-rke2-ingress-nginx                 0/1           107m       107m
kube-system                helm-install-rke2-metrics-server                0/1           107m       107m
kube-system                helm-install-rke2-snapshot-controller           0/1           107m       107m
kube-system                helm-install-rke2-snapshot-controller-crd       0/1           107m       107m
kube-system                helm-install-rke2-snapshot-validation-webhook   0/1           107m       107m
kube-system                rke2-ingress-nginx-admission-create             1/1           5h38m      6h12m
tigera-operator            tigera-operator-uninstall                       0/1           6h12m      6h12m
```

```shellSession
NAME                          STATUS        AGE
calico-system                 Terminating   8h

```

**Comment by brandond** [comment]
> Yes, after first control-plane upgrade we observed that the helm charts were not updated and hence were troubleshooting on it.

Don't stop the upgrade partway through to poke at things. Some things may not complete the upgrade until all servers are on the new release. If you end up restarting any servers that are still down-level, they will redeploy older versions of the charts, and end up in a situation like this where they thrash the HelmChart resources back and forth between old and new versions.

**Comment by brandond** [comment]
You can try removing the finalizers from the namespace, so that it can finish deleting. Once that is done the helmchart should be able to recreate the namespace and any missing resources that were in it.
