### ISSUE TITLE
Add ctr to rke2 shell completion

### ISSUE THREAD

**Issue by vitorsavian** [rancher/rke2#6590]
**Is your feature request related to a problem? Please describe.**

- Rke2 does not have `ctr` in shell completion

**Describe the solution you'd like**

- Add a new cli flag to shell completion named `ctr` 

```bash
rke2 shell completion bash -i --ctr
```

**Additional context**

- https://github.com/rancher/rke2/issues/5488
- https://github.com/rancher/rke2/issues/5250

**Comment by endawkins** [comment]
See the following for validation:
- https://github.com/rancher/rke2/issues/6734
- https://github.com/rancher/rke2/issues/6735
- https://github.com/rancher/rke2/issues/6736
- https://github.com/rancher/rke2/issues/6737
