### ISSUE TITLE
Validate Amazon Linux 2023 

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#6593]
**K3s Versions to be Validated**

v1.30.2+rke2r1
v1.29.6+rke2r1
v1.28.11+rke2r1
v1.27.15+rke2r1

**Testing Considerations**

1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade
3. Install Rancher Manager
4. Validate snapshot restore via `cluster-reset-restore-path`

**Additional Information**

```yaml
# /etc/rancher/rke2/config.yaml
selinux: true
```

**Comment by aganesh-suse** [comment]
Validated rke2 tests mentioned in description with: 

v1.30.2+rke2r1
v1.29.6+rke2r1
v1.28.11+rke2r1
v1.27.15+rke2r1
