### ISSUE TITLE
Update to newer ingress-nginx v1.10.4

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#6594]
**Is your feature request related to a problem? Please describe.**
Current version of ingress-nginx is v1.10.1, release in April 2024. We need to move to a newer version

**Describe the solution you'd like**
Move to v1.10.4, released August 2024.

**Describe alternatives you've considered**
v1.11.1 is available, but we are not ready to move to the next minor release.

**Additional context**

**Comment by aganesh-suse** [comment]
Closing based on release-1.30 result: https://github.com/rancher/rke2/issues/6595
