### ISSUE TITLE
Fix Flannel helm chart with the right value to disable NFTables

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#6601]
The Flannel chart [v0.25.500](https://github.com/rancher/rke2-charts/tree/main/charts/rke2-flannel/rke2-flannel/v0.25.500) has a wrong configuration for the values `enableNFTables` so it will be enabled wrongly by default and Flannel starts with errors and `CrashLoopBackOff` status. The chart needs to be updated to a fixed version.

**Comment by mdrahman-suse** [comment]
Validated the fix on the release branches, Closing this issue. Thanks @rbrtbnfgl for the quick fix
