### ISSUE TITLE
Error from server: error dialing backend: dial tcp: lookup

### ISSUE THREAD

**Issue by mscbpi** [rancher/rke2#662]
We are encountering error when trying to `kubectl exec` or `kubectl log` or `kubectl port-forward`
```
    Error from server: error dialing backend: dial tcp: lookup <NODE_HOSTNAME_WHERE_POD_RUNS> on <DNS_SERVER>: server misbehaving
```
we tried to add NODE_HOSTNAME in  `/etc/hosts` of every node, as well as in the DNS Server, with correct `search dns_suffix` in `/etc/resolv.conf`. 

Hostname is resolved on hosts, it did not help with the error.

**Comment by briandowns** [comment]
Thanks for submitting this. Can you provide the full commands you're running, the version of RKE2, and any relevant log information?

**Comment by mscbpi** [comment]
version: 
`RKE Government v1.19.5+rke2r1`

command:
`kubectl exec -it <pod_name> -- bash`

We have rebooted the whole cluster. At first it won't come up at all, kubeapiserver /etcd not starting on any node.

We've then removed entries from hosts in the first one, and it finally came up, and the error for `kubectl exec` has disappeared.
😮

Being a 4-node cluster (3 master, 1 worker) the most atypical thing is that etcd and control-plane has started on the worker node as well after these operations. huh...
🙀

**Comment by grk-kulkarni** [comment]
We are getting same error in all logs (namely coredns, api server) with version RKE Government v1.19.7+rke2r1. the kube system pods are unable to lookup host from the upstream dns host. 

@mscbpi what were the changes that you had to do to resolve the issue ?

**Comment by mscbpi** [comment]
we just restarted the nodes with initial config. But we're now running 4 master nodes (while not having changed the config), not a normal and wanted situation. being a test cluster we have not investigated further. (we monitor rke2 in parallel of running rke1 in production).

**Comment by johnlinvc** [comment]
I got the same kind of issue.
Added following to `/etc/rancher/rke2/config.yaml` solved this issue.
```
kube-apiserver-arg: "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
```

Found the solution according to following SO answer.
https://stackoverflow.com/questions/50468354/kubedns-error-server-misbehaving
