### ISSUE TITLE
Remove deprecated `aws` cloud-provider helpers functions

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6626]
The code that sets the correct hostname based on the response from the IMDS is no longer used, due to removal of the in-tree AWS cloud provider in Kubernetes 1.27 and newer.

* https://github.com/rancher/rke2/blob/6f1feb7700087b16676f1a2c3277c3d45bd96348/pkg/rke2/rke2_linux.go#L97-L108
* https://github.com/rancher/rke2/blob/6f1feb7700087b16676f1a2c3277c3d45bd96348/pkg/rke2/rke2_linux.go#L504-L533

Attempts to use this code by starting RKE2 with `cloud-provider-name: aws` will cause the kubelet to fail to start:
```
E0822 22:35:03.230900     143 run.go:74] "command failed" err="failed to run Kubelet: unknown cloud provider \"aws\""
```

We should remove this dead code.

**Comment by brandond** [comment]
Didn't make it into October, moving out to next month.

**Comment by mdrahman-suse** [comment]
Unused code removed, no QA needed
