### ISSUE TITLE
When using KEDA for scaling with memory scaler receving reconciler error for HorizontalPodAutoscaler.autoscaling

### ISSUE THREAD

**Issue by anishsedhaii** [rancher/rke2#6627]
**Environmental Info:**
RKE2 Version:
v1.26.7+rke2r1

**Node(s) CPU architecture, OS, and Version:**
Linux master-1 5.4.0-189-generic https://github.com/rancher/rke2/pull/209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Cluster Configuration:**
3 servers, 20 workers>

**Describe the bug:**
When using KEDA version 2.14.1 and using the memory scaler the HPA could not be configured by KEDA, while describing scaled object this is the error **failed to ensure HPA is correctly created for ScaledObject** and from the KEDA operator logs there is this error 
```
ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"app","namespace":"app"}, "namespace": "app", "name": "app", "reconcileID": "037b82e6-e1a5-4640-a5a5-3bdbb215dbfa", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-app\" is invalid: spec.metrics[0].containerResource: Required value: must populate information for the given metric source (only allowed when HPAContainerMetrics feature is enabled)"}
```
The metrics server with image **registry.k8s.io/metrics-server/metrics-server:v0.6.4** is running on the kube-system namespace so there is no issue while running kubernetes basic HPA with :
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
```

**Steps To Reproduce:**
1. Install KEDA version 2.14.1
2. Deploy an application and apply below for scaling 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app
  namespace: app
spec:
  cooldownPeriod: 300
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    kind: Deployment
    name: app
  triggers:
    - metadata:
        containerName: app-app
        type: Utilization
        value: '60'
      type: memory
```
    
**Expected behavior:**
The Scaled Object must create a HPA which must be able to scale the pod as other scalers like prometheus and rabbitmq are working because they depend upon external data for scaling(scrape data from outside the cluster)

**Additional context / logs:**

KEDA operator log:
```
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
	```

kubectl describe describe scaledobjects.keda.sh app
Status:
  Conditions:
    Message:               failed to ensure HPA is correctly created for ScaledObject
    Reason:                ScaledObjectCheckFailed
    Status:                False
    Type:                  Ready
    Message:               ScaledObject check failed
    Reason:                UnknownState
    Status:                Unknown
    Type:                  Active
    Status:                Unknown
    Type:                  Fallback
    Status:                Unknown
    Type:                  Paused
  Original Replica Count:  1
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type     Reason                   Age                  From           Message
  ----     ------                   ----                 ----           -------
  Warning  ScaledObjectCheckFailed  6m9s (x22 over 78m)  keda-operator  failed to ensure HPA is correctly created for ScaledObject

**Comment by brandond** [comment]
I don't see anything here that indicates a problem with rke2. What is the underlying error that we are supposed to fix? Why did you open the issue here instead of in the keda project?

**Comment by brandond** [comment]
> `Required value: must populate information for the given metric source (only allowed when HPAContainerMetrics feature is enabled)`

You're running an EOL version of Kubernetes (1.26) where this feature gate is off by default. Upgrade to a newer version, or enable the feature gate.

Ref: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
