### ISSUE TITLE
Support kube-router

### ISSUE THREAD

**Issue by shane-davidson** [rancher/rke2#6632]
Adding a request here for kube-router as a supported CNI for RKE2 :)

**Comment by brandond** [comment]
Probably unlikely at the moment, given https://github.com/cloudnativelabs/kube-router/issues/1715

**Comment by aauren** [comment]
FWIW we're just trying to get some new blood into the project, not saying that kube-router won't be supported in the near future. We've already gotten several people that have reached out and are hopeful that kube-router will become even better supported in the next few months as those people begin ramping up.
