### ISSUE TITLE
Stable channel link https://update.rke2.io/v1-release/channels/stable returns pre-release v1.30.4+rke2r1

### ISSUE THREAD

**Issue by tsteine** [rancher/rke2#6657]
**Environmental Info:**
RKE2 Version: 

v1.28.12+rke2r1 / v1.30.4+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 Clusters:
3 hardware nodes, all control plane (Ceph)
5 hardware nodes, all control plane (Kubevirt)
6 virtual nodes, 3 control plane, 3 agents (rke2 workload virtual cluster)

**Describe the bug:**
I am using the rancher system upgrade controller, set to track channel https://update.rke2.io/v1-release/channels/stable
The stable channel link returns pre-release https://github.com/rancher/rke2/releases/tag/v1.30.4+rke2r1

As a consequence, the upgrade controller upgraded all my clusters from v1.28.12+rke2r1 to v1.30.4+rke2r1

**Steps To Reproduce:**

![image](https://github.com/user-attachments/assets/0da3719c-958f-4e92-b1b6-e088074fe4df)

**Expected behavior:**
I expected to get the latest stable release, which I think should still be v1.28.12+rke2r1

**Actual behavior:**
I got the latest pre-release of RKE2 v1.30.4+rke2r1

I should note, it's not clear to me whether this belongs as an issue in this project, the rke2-upgrade project, or the system-upgrade-controller. If this should be raised somewhere other than here, please advise.

**Comment by brandond** [comment]
It is stable. We're checking into why the step to publish release notes and clear the pre-release flag got skipped.

**Comment by tsteine** [comment]
Thank you for the prompt response. I was worried I had to restore from backup, to get back on stable track.

**Comment by ilbarone87** [comment]
@brandond is there any specific reason why the big jump from 1.28 to 1.30 for the stable channel?

**Comment by brandond** [comment]
Stable tracks patch releases on the newest minor that is supported by a stable release of Rancher. Rancher v2.8 only supported Kubernetes v1.28, but Rancher v2.9 now supports Kubernetes 1.30 so thats what we updated to.

If you want to stay within a particular minor version, or ensure that you are stepping through minors when upgrading, it's probably best to target a specific minor channel, instead of stable.

**Comment by ilbarone87** [comment]
@brandond thank you for the explanation.
