### ISSUE TITLE
Installation Failed on Ubuntu 18

### ISSUE THREAD

**Issue by hanjie0** [rancher/rke2#667]
Environment: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

I have installed rke2 by curl -sfL https://get.rke2.io | sh -
but Failed. 
When I setup DEBUG:  
I got :
...
+ curl -o /tmp/rke2-install.B0lD6qgaB5/rke2.tarball -fsSL https://github.com/rancher/rke2/releases/download/v1.19.5+rke2r1/rke2.linux-amd64.tar.gz
+ [ 0 -ne 0 ]
+ verify_tarball
+ info verifying installer
+ echo [INFO]  verifying installer
[INFO]  verifying installer
+ sha256sum /tmp/rke2-install.B0lD6qgaB5/rke2.tarball
+ awk {print $1}
+ CHECKSUM_ACTUAL=7c5ebd254cbe8987e739fb18f7f5212a675a3f9f77a90c22794a9b8a5296d3e3
+ [ 7c5ebd254cbe8987e739fb18f7f5212a675a3f9f77a90c22794a9b8a5296d3e3 != 7c5ebd254cbe8987e739fb18f7f5212a675a3f9f77a90c22794a9b8a5296d3e3 ]
+ unpack_tarball
+ info unpacking tarball file
+ echo [INFO]  unpacking tarball file
[INFO]  unpacking tarball file
+ mkdir -p /usr/local
+ tar xzf /tmp/rke2-install.B0lD6qgaB5/rke2.tarball -C /usr/local
+ exit 0

...
Is there any thing wrong on my environment? so that the tarball installation Failed?

**Comment by briandowns** [comment]
Was there nothing extracted to `/usr/local`?
