### ISSUE TITLE
Reasonable containerd/config.toml.tmpl UX

### ISSUE THREAD

**Issue by Patricol** [rancher/rke2#6678]
**Is your feature request related to a problem? Please describe.**
Any slight edit to `containerd`'s config is rather onerous, brittle and drift-prone.

**Describe the solution you'd like**
Ship a default `config.toml.tmpl` file somewhere with `rke2`, or even create it on the filesystem alongside `config.toml` if not already present. Requiring people to manually copy a portion of a [code file from GitHub](https://github.com/k3s-io/k3s/blob/master/pkg/agent/templates/templates_linux.go) to use as a base is not very ideal.

**Describe alternatives you've considered**
Letting people create a file that gets merged in, or even just `cat`-ed onto the end. Most will just want to add a line or two; it's fine if it's not perfect.

**Additional context**
Currently the path of least resistance is for users to make a nearly empty `tmpl` file; eventually causing extra support workload when people don't know why their settings (changed later after they forget about replacing the `tmpl`) don't work.

**Comment by brandond** [comment]
You can already do this.

https://docs.k3s.io/advanced#base-template
