### ISSUE TITLE
rke2-uninstall.sh does not remove etcd user

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#67]
Version:
version v0.0.1-alpha.6

Issue:
etcd user persists after running rke2-uninstall.sh, thus failing re-install of rke2 on the same node.

```
rke2 -v
-bash: /usr/local/bin/rke2: No such file or directory
cat /etc/passwd|grep etcd
etcd:x:997:997:ETCD Service User:/var/lib/rancher/rke2:/usr/sbin/nologin
```

**Comment by briandowns** [comment]
This was never discussed as an expectation. We should have a discussion on this to decide scope and intent before implementation if we decide to do so.

**Comment by briandowns** [comment]
@davidnuzik @cjellick Should the install script remove the etcd user?

**Comment by briandowns** [comment]
PR #69 remediates the issue. This can now be tested.

**Comment by ShylajaDevadiga** [comment]
Verified using rke2 version v0.0.1-alpha.7
