### ISSUE TITLE
Reduce logs dumps in GHA CI

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#6704]
**Is your feature request related to a problem? Please describe.**
When testing in GHA fails, the `dump-logs` function output around ~4000 lines of logs into the GHA GUI. This makes it incredibly difficult to determine the root cause of the failure. For example,  https://github.com/rancher/rke2/actions/runs/10606165104/job/29396373130, the failure reason is on line 727, but the logs of `[BASICS]` continue till line 4685.

**Describe the solution you'd like**

Instead of dumping logs to the GUI, use the GHA artifacts feature to simply upload the logs for further analysis as needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by aganesh-suse** [comment]
CI related. Closing as done.
