### ISSUE TITLE
FIPS Enabled Istio

### ISSUE THREAD

**Issue by ajureeruja** [rancher/rke2#671]
Not sure where this should go but since rke2 is focusing on FIPS compliance I'll put it here.  It would be nice to support a FIPS enabled deployment of Istio.  Are there any plans for Rancher to implement this?

**Comment by bsecker** [comment]
Commenting to keep this issue alive - is there any update on this?

**Comment by brandond** [comment]
We are not currently planning on bundling an Istio installation with RKE2; you might ask on rancher/rancher?
