### ISSUE TITLE
Remove kube-proxy-arg flag from RKE2 CLI and docs

### ISSUE THREAD

**Issue by rbkaspr** [rancher/rke2#677]
The documentation for rke2-server and -agent (and CLI arguments for same) list a `kube-proxy-arg` option which is apparently inherited from k3s but is not used in RKE2, which instead uses packaged Helm charts to deploy kube-proxy. Since the flag doesn't do anything, it should be removed from the docs and CLI help message.

It'd probably also be helpful to point out that kube-proxy needs to be configured via Helm overrides since it appears to be the only core Kubernetes component in RKE2 that this is the case for.

[Related Slack discussion](https://rancher-users.slack.com/archives/C3ASABBD1/p1611768011356900)

**Comment by rancher-max** [comment]
#### Validated using master build from commit `334a4a9`

```
$ ./bin/rke2 server --help | grep -i proxy
   --disable value                        (components) Do not deploy packaged components and delete any deployed components (valid items: rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-kube-proxy, rke2-metrics-server)

$ ./bin/rke2 agent --help | grep -i proxy
(no results)
```
- No results for `kube-proxy-arg` in both agent and server. 

I will leave this open to quickly validate in the next v1.20 RC. Note this will only be present in the v1.20 line.

**Comment by rancher-max** [comment]
Validated on v1.20.4-rc2+rke2r1 this is not seen.
