### ISSUE TITLE
version displayed in rancher gui is not up to date after rke2 upgrade?

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#679]
![2021-01-29-112337_357x379_scrot](https://user-images.githubusercontent.com/1146389/106263334-8551b000-6224-11eb-9058-62000810ebde.png)

The clusters are running v1.19.7+rke2r1 but the gui shows wrong version? If we edit cluster in gui and select new version it still shows the wrong one. 

They are installed with rpm packages on centos 8 machines and upgraded to v1.19.7+rke2r1 yesterday with yum. 

When we prevously ran rke on rancheros nodes this was always in sync.

**Comment by briandowns** [comment]
What are the versions reported when running via the CLI?

```sh
rke2 --version
```

**Comment by jonaz** [comment]
@briandowns 

kubectl version:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+rke2r1", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-20T01:50:52Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
```

`rke2 --version` : 
```
rke2 version v1.19.7+rke2r1 (d1430ad44dc162f15a54d093439c20ffb91f559b)
go version go1.15.5b5

```

**Comment by briandowns** [comment]
Glad to hear it's closer to correct. If you can provide any logs from the Rancher side around the time of the restarts that might yield some info, that'd be helpful. I'll link this issue over to the Rancher folks and see if there's anything they may know. Thank you for the update.

**Comment by brandond** [comment]
This probably should be moved to rancher/rancher - if the nodes actually have the correct version on them then something is probably going on with the rancher agent.

**Comment by briandowns** [comment]
That's what Im in the process of doing.

**Comment by jonaz** [comment]
We disabled selinux on rancher nodes and reboted them when it started working. So i think this is related to https://github.com/rancher/rancher/issues/26596#issuecomment-770641292 where we also added comments now.

**Comment by jonaz** [comment]
This was solved by https://github.com/rancher/rke2/issues/690
Verified in our 21 clusters.
