### ISSUE TITLE
Windows fails when `cni: none` is configured

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#6819]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

When `cni: none` is configured widows node does not start with a panic.

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by kenny2061** [comment]
Where can i set cni as calico or flannel when i run rke2 agent on windows server?

**Comment by brandond** [comment]
You don't. CNI is not set per node, it is set cluster-wide on the server when you first start the cluster. This is covered in the docs: https://docs.rke2.io/networking/basic_network_options

**Comment by VestigeJ** [comment]
https://github.com/rancher/rke2/issues/6829#issuecomment-2397521540
