### ISSUE TITLE
Avoid writing into /usr to support deploying on openSUSE/SUSE MicroOS

### ISSUE THREAD

**Issue by kailiu42** [rancher/rke2#682]
I was testing on openSUSE MicroOS and noticed that the api server just couldn't start since the begining. After checked into `/var/lib/rancher/rke2/agent/logs/kubelet.log` I saw a few repeating `mkdir` failures on `/usr/libexec/kubernetes/...` and `/usr/share/ca-certificate`, as the root(including /usr) is read only in MicroOS.

This seems is the reason of the failure, as deployment on a regular SLES 15 SP2 is OK. SLES 15 SP2 is almost the same as the MicroOS version I tested, except that the root is writable as most regular distros.

I have no problem deploying k3s on MicroOS as it seems k3s writes everything under `/var`, which is a writable separate btrfs. Can rke2 be adapted to support running on MicroOS too?

**Comment by thkukuk** [comment]
According to FHS RKE2 is not allowed to write to /usr on Linux, as this is purely for distributions. At least as long as RKE2 is not shipped as RPM.
RKE2 should use /opt as at least RKE1 is already doing for /opt/cni and /opt/containerd.
Certificates should never be modified or installed in /usr/share/ca-certificate, there is absolut no guarantee that this will lead to success. Linux has tools to import new certificates, which should work on every Linux distribution.

**Comment by brandond** [comment]
Unfortunately upstream has a bad habit of writing to /usr/libexec/kubernetes/, and daemonsets that want to modify stuff in /usr/share to modify CA bundles.

**Comment by ibuildthecloud** [comment]
@brandond I believe /usr/libexec/kubernetes/ has been removed upstream, is that true? Either way we should just disable flexvol support in k8s, it's an irrelevant feature at this point.  That will get rid of this issue with /usr/libexec.

Also regarding /usr/share/ca-certificates it is because of https://github.com/rancher/rke2/blob/master/pkg/podexecutor/staticpod.go#L122.  We should first iterate through that slice and see if the directory exists on the host before adding it to the pod spec.

**Comment by sdrahn** [comment]
@brandond and @ibuildthecloud : Question on this from my side would be if there is a workaround available until it is addressed in RKE2. Could you comment on that?

**Comment by The-Loeki** [comment]
Same problem on CoreOS / Flatcar /  rpm-ostree's; all mount /usr ro.

https://github.com/rancher/rke2/blob/master/pkg/podexecutor/staticpod.go#L34
Makes `/usr/share/ca-certificates` a `DirectoryOrCreate`
And ofc most of the dirs in that list are Debian-flavoured locations, so those directories won't exist and are created.

**Comment by davidnuzik** [comment]
To be done in master and backport to all other release branches.

**Comment by vbatts** [comment]
@ibuildthecloud 
> I believe /usr/libexec/kubernetes/ has been removed upstream, is that true?

correct. It was around k8s 1.19 that the removed this

**Comment by brandond** [comment]
@ibuildthecloud @vbatts as far as I can tell the default is still `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/` on 1.20.
https://github.com/kubernetes/kubernetes/blob/release-1.20/pkg/kubelet/apis/config/v1beta1/defaults.go#L37

We have some stuff like Calico that uses a flexvol driver to share a Unix socket with pods to enable secure communication between Felix and Dikastes for policy stuff.
https://docs.projectcalico.org/getting-started/kubernetes/hardway/istio-integration#install-flexvolume-driver

**Comment by rancher-max** [comment]
#### Validated using master build `0c589ac1`

- I am able to install on MicroOS where /usr has readonly access
- I am also still able to install on other OS's both when /usr has a different mount and in the standard writable use case.

This is a packaged approach and will have rke2 present in /opt/rke2 in tarball installs where /usr is not writable, with a helpful message suggesting adding that to PATH.

**Comment by brandond** [comment]
@davidnuzik do we still need backports to previous release branches? If so, which ones?

**Comment by davidnuzik** [comment]
Needs backports for 1.18 and 1.19

**Comment by davidnuzik** [comment]
@rancher-max moved back to test

**Comment by rancher-max** [comment]
#### Validated in v1.18.17-rc1 and v1.19.9-rc1 using MicroOS in VirtualBox

- Same helpful messages appear
- Rke2 installs successfully and am able to deploy workloads
