### ISSUE TITLE
Audit docs update

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#685]
Based on the docs https://docs.rke2.io/security/hardening_guide/#control-321, it mentioned that audit policies are not supported for rke2, this needs to be fixed since we support this by running with cis-1.5 profile.

**Comment by brandond** [comment]
I think that we just need a docs update - as per Max's comment on the issue that the text links to:
> There continues to be no audit logging by default when NOT in CIS mode
> When in CIS mode, this now passes the CIS Scored check (3.2.1 Ensure that a minimal audit policy is created (Scored)). This can be validated using /bin/ps -ef | grep kube-apiserver | grep audit-policy-file. Verified no regressions to CIS with the other audit parameters of: audit-log-path, audit-log-maxage, audit-log-maxbackup, and audit-log-maxsize
> The default audit-policy-file provides a level of None to all requests. Users have the ability to pass their own audit file with different levels. For example, to log all requests at the metadata level

So it works and enables auditing, but the default audit policy doesn't log anything. Users need to decide what events they want, and with how much detail.

**Comment by galal-hussein** [comment]
> I think that we just need a docs update - as per Max's comment on the issue that the text links to:
> 
> > There continues to be no audit logging by default when NOT in CIS mode
> > When in CIS mode, this now passes the CIS Scored check (3.2.1 Ensure that a minimal audit policy is created (Scored)). This can be validated using /bin/ps -ef | grep kube-apiserver | grep audit-policy-file. Verified no regressions to CIS with the other audit parameters of: audit-log-path, audit-log-maxage, audit-log-maxbackup, and audit-log-maxsize
> > The default audit-policy-file provides a level of None to all requests. Users have the ability to pass their own audit file with different levels. For example, to log all requests at the metadata level
> 
> So it works and enables auditing, but the default audit policy doesn't log anything. Users need to decide what events they want, and with how much detail.

sorry I misspoke in the issue description, I meant updating the docs

**Comment by bgulla** [comment]
@brandond , Do we have examples on how to configure the audit-logging functionality?

**Comment by brandond** [comment]
@bgulla not at the moment; that should be tracked as part of that. The tl;dr is
1. Start RKE2 in CIS mode
2. Edit the file at `/etc/rancher/rke2/audit-policy.yaml` to configure your desired policies, or provide a file in a different location specified by the `--audit-policy-file` option.

The policies themselves can get pretty complicated, documentation from upstream is at https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy

**Comment by davidnuzik** [comment]
Closing. Docs PR is merged.
