### ISSUE TITLE
Rancher "Error connecting to WebSocket" on login when using rke2 as local management cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#687]
rke2 Version:  v1.19.7+rke2r1, v1.19.7-beta1+rke2r2
rancher Version: 2.5.5, 2.5.6-rc4

Node OS: Ubuntu 20.04, SLES 15 SP2, CentOS 7.8 (Selinux Disabled)
During the first login or re-login, Unable to establish a Websocket error msg pops up. Screen Attached. 

Node OS: Centos 7.8, Selinux Enabled. 
Installation of rancher fails. rancher pod restart. See the logs

With Selinux Enabled on Centos
```
kubectl get pods -n cattle-system  --kubeconfig=rke2cbeta
NAME                       READY   STATUS             RESTARTS   AGE
helm-operation-4jzdm       0/2     Completed          0          24m
helm-operation-9bxqc       0/2     Completed          0          25m
rancher-65cb8bc8cd-62g8h   0/1     CrashLoopBackOff   8          28m
rancher-65cb8bc8cd-mkgdj   0/1     CrashLoopBackOff   8          28m
rancher-65cb8bc8cd-w27zz   0/1     Running            9          28m
```
Logs from rancher pod
```
2021/02/04 17:34:48 [ERROR] failed to call leader func: failed to add management data: error creating binary drop folder: mkdir ./management-state: permission denied
```
With Selinux Disabled on Centos
```
kubectl get pods -n cattle-system --kubeconfig=rke2cbetase
NAME                              READY   STATUS      RESTARTS   AGE
helm-operation-2dg2d              0/2     Completed   0          5m45s
helm-operation-5fq6b              0/2     Completed   0          5m3s
helm-operation-m9jdn              0/2     Completed   0          4m43s
helm-operation-qpkhf              0/2     Completed   0          80s
helm-operation-s9fbz              0/2     Completed   0          4m11s
helm-operation-v76dc              0/2     Completed   0          4m26s
helm-operation-wfstm              0/2     Completed   0          5m28s
rancher-65cb8bc8cd-4fzd7          1/1     Running     0          8m19s
rancher-65cb8bc8cd-8zjqf          1/1     Running     2          8m19s
rancher-65cb8bc8cd-bb4t7          1/1     Running     1          8m19s
rancher-webhook-b5b7b76c4-tkgg2   1/1     Running     0          4m31s
```
Logs
```
021/02/04 17:54:53 [ERROR] Failed to read API for groups map[gitjob.cattle.io/v1:the server could not find the requested resource]
2021/02/04 17:55:10 [ERROR] error syncing 'fleet-system/helm-operation-wfstm': handler helm-operation: an error on the server ("container not found (\"proxy\")") has prevented the request from succeeding (get pods helm-operation-wfstm), requeuing
```

This issue is not seen when rancher is installed on k3s.

![image](https://user-images.githubusercontent.com/56045581/106841658-63f32880-6657-11eb-98e3-8ba6f1df9674.png)

**Comment by metabsd** [comment]
I'm not using rancher at the moment but kubectl is working fine. 

I also see that error in my log :

`Feb 04 11:38:48 servername.domain rke2[13250]: time="2021-02-04T11:38:48-05:00" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"`

I also use the same version `1.19.7~rke2r1` on `RHEL8` with `SELINUX Disabled` and `FirewallD Disabled`

Any workaround to fix this ?

**Comment by brandond** [comment]
Note: this is an error in Rancher, but it may be related to the RKE2 ingress controller configuration. Any errors in RKE2 itself should NOT be reported on this issue.

**Comment by ShylajaDevadiga** [comment]
Created a separate Issue to track rancher pod restart when selinux is enabled #690

**Comment by davidnuzik** [comment]
Rancher chart for rancherd fixes this because they don’t use the nginx ingress or cert-manager. They just expose rancher directly via hostport. This issue is expected on vanilla RKE2.

**Comment by brandond** [comment]
@davidnuzik is this something that we should open an issue for in Rancher? It sounds like their Ingress resource needs an annotation to work properly with the nginx ingress controller.

**Comment by davidnuzik** [comment]
Looks like we should be all set with the issue above, https://github.com/rancher/rancher/issues/26596
