### ISSUE TITLE
Unable to download the install script from https://rancher-mirror.rancher.cn/rke2/install.sh

### ISSUE THREAD

**Issue by npcxiao** [rancher/rke2#6892]
**Describe the bug:**
Unable to download the install script from https://rancher-mirror.rancher.cn/rke2/install.sh

**Steps To Reproduce:**
$ curl -L https://rancher-mirror.rancher.cn/rke2/install.sh -o install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to rancher-mirror.rancher.cn port 443: Connection timed out

**Comment by brandond** [comment]
Please see https://github.com/rancher/rke2/issues/6210#issuecomment-2170474386
