### ISSUE TITLE
[Backport] With rke2 as local management cluster, rancher pod is in CrashLoop state when selinux is enabled

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#690]
rke2 Version: v1.19.7+rke2r1, v1.19.7-beta1+rke2r2
rancher Version: 2.5.5, 2.5.6-rc4

Node OS: Centos 7.8, Selinux Enabled.

Installation of rancher fails as rancher pods are in CrashLoopBackOff state. See the logs

**Steps to reproduce:**

- Create a 3 node rke2 cluster with selinux enabled
- Verify nodes are up and cluster is accessible.
- Install rancher.

**Expected Result:**
Rancher server should be deployed correctly.

**Actual Result:**
rancher pods are in CraashLoopBackOff state.

```
kubectl get pods -n cattle-system  --kubeconfig=rke2cbeta
NAME                       READY   STATUS             RESTARTS   AGE
helm-operation-4jzdm       0/2     Completed          0          24m
helm-operation-9bxqc       0/2     Completed          0          25m
rancher-65cb8bc8cd-62g8h   0/1     CrashLoopBackOff   8          28m
rancher-65cb8bc8cd-mkgdj   0/1     CrashLoopBackOff   8          28m
rancher-65cb8bc8cd-w27zz   0/1     Running            9          28m
```

Logs from rancher pod:
```
2021/02/04 17:34:48 [ERROR] failed to call leader func: failed to add management data: error creating binary drop folder: mkdir ./management-state: permission denied
```

**Comment by jonaz** [comment]
I did some comments and debugging of this here: https://github.com/rancher/rancher/issues/26596#issuecomment-770641292

**Comment by ShylajaDevadiga** [comment]
Thank you @jonaz I could validate rancher pods are running in 1.18.15 using rancher version 2.5.6-rc3

**Comment by cjellick** [comment]
@dweomer this seems like a legitimate regression. It could be that rke2 is behaving *more* correctly now and that is causing rancher to fail "properly", but it needs investigated and proven one way or another.

**Comment by dweomer** [comment]
I am unable to reproduce on centos/7 with this setup: https://github.com/dweomer/vagrantfiles/blob/6717ea55a2087d0b5071ed122ffa9351dc8eaa51/centos-7-rke2-rancher/Vagrantfile

I do see the issue on centos/8, however, using https://github.com/dweomer/vagrantfiles/blob/6717ea55a2087d0b5071ed122ffa9351dc8eaa51/centos-8-rke2-rancher/Vagrantfile

I suspect that a needed file transition isn't happening on centos/8. I will spin up each of the above clusters with SELinux in Permissive mode and compare the labels of the `management-state` directories for both installations to validate this working theory.

**Comment by davidnuzik** [comment]
Added Working label as this is actively in progress.

**Comment by dweomer** [comment]
Some Notes
---
I am able to reproduce this on centos 7/8 with v1.19.x of RKE2 but not v1.18.x. These RKE2 versions use different versions of containerd, v1.4.3 and v1.3.9 respectively. When I leverage a modified https://github.com/dweomer/vagrantfiles/blob/6717ea55a2087d0b5071ed122ffa9351dc8eaa51/centos-7-rke2-rancher/Vagrantfile that is parameterized with a custom `$RKE2_RUNTIME_IMAGE` that consists of default v1.19.7 rke2-runtime + upstream containerd v1.3.9 overlayed, the problem goes away. This speaks to a likely regression in volume relabeling in containerd from 1.3.x => 1.4.x

**Comment by dweomer** [comment]
More Notes
---
The underlying issues seems to be related to how image volumes get relabeled (containerd/cri by default creates implicit/shadow volumes for images that declare them which don't show up in kubernetes). I've come to this thesis by way of these observations:
- rke2 1.19 using containerd 1.3.9 will label the `management-state` directory under the `/var/lib/rancher` image volume as `container_file_t`
- rke2 1.19 using containerd 1.4.3 will label the `management-state` directory under the `/var/lib/rancher` image volume as `container_share_t`
- this issue does not present (in that there are no AVC denials in the audit log) when patching the rancher 2.5.5 chart to use an `emptyDir` volume for `/var/lib/rancher` (see https://github.com/dweomer/rke2-selinux/releases/download/v0.5-dev.3%2Brke2.690/rancher-2.5.5.tgz)

**Comment by cjellick** [comment]
Fix won't land in 1.19.8. Moving to 1.19.9

**Comment by ShylajaDevadiga** [comment]
Validated fix using rke2 version v1.19.8-alpha1+rke2r2, successfully deployed rancher v2.5.6 and the cluster is accessible on centos8 with selinux enabled.

```
$ rke2 -v
rke2 version v1.19.8-alpha1+rke2r2

$ kubectl get pods -n cattle-system |grep rancher
rancher-7589f87454-9q46q          1/1     Running     0          6m58s
rancher-7589f87454-gwx79          1/1     Running     0          6m58s
rancher-7589f87454-n94pn          1/1     Running     0          6m58s
rancher-webhook-b5b7b76c4-7ktrj   1/1     Running     0          3m17s
```

![image](https://user-images.githubusercontent.com/56045581/111430261-5a79c900-86b7-11eb-91a7-551e12c7ae09.png)

**Comment by ShylajaDevadiga** [comment]
Re-opening to test with rc.

**Comment by hectoralicea** [comment]
I have this exact same issue.
building my rke2 cluster using
https://github.com/rancherfederal/rke2-aws-tf

> Thank you @jonaz I could validate rancher pods are running in 1.18.15 using rancher version 2.5.6-rc3

I also moved to a pre- 1.19 build and everything seemed to work.  I think 1.19 introduced some security lock down issues which need to be fixed in the rancher helm chart.

**Comment by ShylajaDevadiga** [comment]
Validated on rke2 version v1.19.9-rc1+rke2r1, centos7.8 as well as centos 8.2, selinux enabled, rancher pods are deployed correctly.
```
Centos 7.8
[centos@ip-172-31-7-228 ~]$ rke2 -v
rke2 version v1.20.5-rc2+rke2r1 (2355feae77669ef3b60e8570c8a0fa22b7080185)
go version go1.15.8b5
[centos@ip-172-31-7-228 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[centos@ip-172-31-7-228 ~]$ sudo cat /var/lib/rancher/rke2/agent/etc/containerd/config.toml|grep selinux
  enable_selinux = true
[centos@ip-172-31-7-228 ~]$ kubectl get pods -A |grep rancher
cattle-system             rancher-7f4df87477-797q4                                             1/1     Running     2          8m3s
cattle-system             rancher-7f4df87477-f6wjb                                             1/1     Running     1          8m3s
cattle-system             rancher-7f4df87477-ngnrt                                             1/1     Running     2          8m3s
cattle-system             rancher-webhook-b5b7b76c4-ctmwh                                      1/1     Running     0          2m1s
rancher-operator-system   rancher-operator-5c795bd886-4dz78                                    1/1     Running     0          2m14s
[centos@ip-172-31-7-228 ~]$

Centos 8.2
[centos@ip-172-31-13-137 ~]$ rke2 -v
rke2 version v1.19.9-rc1+rke2r1 (f618405f29aaa03df638f6cd0d9e9091c21edd51)
go version go1.15.8b5
[centos@ip-172-31-13-137 ~]$ cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core) 
[centos@ip-172-31-13-137 ~]$ sudo cat /var/lib/rancher/rke2/agent/etc/containerd/config.toml|grep selinux
  enable_selinux = true
[centos@ip-172-31-13-137 ~]$ kubectl get pods -A |grep rancher
cattle-system             rancher-7f4df87477-6t8mq                                              1/1     Running     1          20m
cattle-system             rancher-7f4df87477-ktv2p                                              1/1     Running     0          20m
cattle-system             rancher-7f4df87477-pgh4q                                              1/1     Running     0          20m
cattle-system             rancher-webhook-b5b7b76c4-cbt97                                       1/1     Running     0          16m
rancher-operator-system   rancher-operator-5c795bd886-789hn                                     1/1     Running     0          3m54s
[centos@ip-172-31-13-137 ~]$ 
```
