### ISSUE TITLE
Ingress only accessible from first server node

### ISSUE THREAD

**Issue by fatihmete** [rancher/rke2#6925]
**Environmental Info:**
RKE2 Version: 
rke2 -v1.30.5+rke2r1

Node(s) CPU architecture, OS, and Version: 
Various nodes available (rhel7-rhel8)

Cluster Configuration:
3 server, 3 worker

**Describe the bug:**

After installation of RKE2, Ingress only available for first server node. nginx ingress controller deployed as DaemonSet and pods are running state.

**Steps To Reproduce:**
- fresh install RKE2.

**Expected behavior:**
Ingress ports 443 and 80 should be accessible from all nodes which ingress controller installed.

**Actual behavior:**
Ingress ports 443 and 80 only accessible from first server node.

**Additional context / logs:**
When I tried [https://docs.rke2.io/known_issues#ingress-in-cis-mode](https://docs.rke2.io/known_issues#ingress-in-cis-mode) this policy, I lost access from first server too.
nginx-ingress version: 4.10.402

**Comment by brandond** [comment]
Are you sure that you don't have a host firewall blocking access to those ports? There's nothing in the default configuration that would do what you're describing.

**Comment by fatihmete** [comment]
> Are you sure that you don't have a host firewall blocking access to those ports? There's nothing in the default configuration that would do what you're describing.

Firewall service is disabled. 
Interestingly, Ingress started working on one of the nodes after an unexpected reboot. Is there any service that could affect the functioning of Ingress?

**Comment by brandond** [comment]
Not that I'm aware of. Have you checked the pod status to make sure that everything's running where it should? What's the output of `kubectl get pod -o wide` ?
