### ISSUE TITLE
Bump wharfie 

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6929]
We should bump wharfie to latest
* Update go-containerregistry to remove old github.com/docker/cli
* Fix https://github.com/rancher/wharfie/issues/25#issuecomment-2289099654
  RKE2 uses wharfie to pull the rke2-runtime image.
  
Fix can be tested standalone, using same mirror/rewrite configuration described at https://github.com/rancher/rancher/issues/47379

**Comment by brandond** [comment]
Will be done alongside k3s bumps

**Comment by fmoral2** [comment]
validate here 
https://github.com/rancher/distros-test-framework/actions/runs/11344560991
