### ISSUE TITLE
Bump ingress-nginx certgen image

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6944]
We've been holding back the certgen helper image version used by ingress-nginx to generate the webhook cert. It's not in the critical path, but there are updates available.

We should upgrade from v1.4.1 -> v1.4.4

**Comment by fmoral2** [comment]
validated at
https://github.com/rancher/rke2/issues/6946#issuecomment-2407854821
https://github.com/rancher/rke2/issues/6948#issuecomment-2407855481
https://github.com/rancher/rke2/issues/6948#issuecomment-2407855481
https://github.com/rancher/rke2/issues/6949#issuecomment-2407853884
