### ISSUE TITLE
Bump CSI snapshot controller and webhook images

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6945]
We're still on v1.6.x of the CSI snapshot images; upstream is now v1.8.0. We should update.

**Comment by fmoral2** [comment]
validate here
https://github.com/rancher/rke2/issues/6950#issuecomment-2408079414
https://github.com/rancher/rke2/issues/6951#issuecomment-2408080639
https://github.com/rancher/rke2/issues/6952#issuecomment-2408081605

https://github.com/rancher/rke2/issues/6953#issuecomment-2408082516
