### ISSUE TITLE
Bump ingress-nginx images to v1.10.5

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#6985]
**Is your feature request related to a problem? Please describe.**

A new v1.10.5 ingress-nginx is now available. 
Additionally, a number of base OS (SLES 15.6) CVEs (SUSE-SU-2024:3470-1, SUSE-SU-2024:3501-1,SUSE-SU-2024:3470-1) have been addressed in the latest 15.6 tag

**Describe the solution you'd like**
Produce a new  ingress-nginx v1.10.5 hardened image

**Comment by fmoral2** [comment]
validated at
https://github.com/rancher/rke2/issues/6986#issuecomment-2407056390
https://github.com/rancher/rke2/issues/6987#issuecomment-2407805200
https://github.com/rancher/rke2/issues/6988#issuecomment-2407805738
https://github.com/rancher/rke2/issues/6989#issuecomment-2407806450
