### ISSUE TITLE
An health care use case feedback of RKE

### ISSUE THREAD

**Issue by leolb-aphp** [rancher/rke2#7]
Hello!

I'm excited about the future of RKE, though the current version does not yet fit into our use case.
I work at a french state hospital called APHP for "Assistance Publique - Hôpitaux de Paris".

We are a little lightweight on system administration and development resources, so the ease of use of RKE was a great fit to us. The support of Airgap installations which are also really important for us is there, so that's good too. We run behind an HTTP proxy for anything that goes outside and our base systems run CentOS FYI.

The current project is about making environments available for remote computation such as JupyterHub with strict confidentiality requirements.

We have users with different rights to a big data warehouse, so they must not step onto each other's permissions and access data they're not allowed to.

So we determined that Kubernetes orchestration mechanisms were great for resource management and fast to spin up and down as well but the isolation between users in their own pods is insufficient.

We could study that the Kubernetes eco-system is currently evolving towards better security mainly with efforts driven by Red Hat, Google and Intel/OpenStack.

- Red Hat is pushing unprivileged containers with podman, buildah, etc.
- Google is pushing gVisor.
- Intel/OpenStack is pushing Kata Containers.

And where's RKE in all this? Well RKE depends on Docker so it can't use gVisor, Kata Containers or any other custom runtime such as cri-o.

So here's me saying that I'd really love if RKE2 could support non-Docker deployments while keeping the ease of use!

Thanks a lot for the awesome work!

By the way I wish we could fund you in some way but the process that leads to such a thing is complicated, but if I have a working prototype it'll be easier for me to justify it to the people that can do it. But again, it's not your responsability to drive us to a working prototype, but know that with my rather limited knowledge of Golang (but I'm a fast learner), I'm happy to help in any way I can.

And by the way x2, I'm currently experimenting with k3s with multi master HA deployments with dqlite but it's not quite there yet. I could also get Kata Containers running with k3s so that's good!

Leo

**Comment by ibuildthecloud** [comment]
The fundamental reason to create RKE2 was to remove the dependency on Docker.  RKE2 will by default include and run on containerd but any CRI runtime will work. Security is a high priority in rke2. Things like CIS benchmark, FIPS, SELinux are all things that are important features of rke2. From a runtime perspective gVisor, kata containers or any other alternative runtime will be fine with rke2 out of the box.

**Comment by leolb-aphp** [comment]
@ibuildthecloud Awesome! I'm glad to hear that! Indeed, security and general regulatory compliance mechanisms are very interesting for us. Other things that are important for us is NVIDIA GPU support.

NVIDIA publishes a lot of information about it here: https://devblogs.nvidia.com/gpu-containers-runtime/

Also OpenShift-specific information here and I find their way of supporting it quite neat and also compatible with the security model: https://gitlab.com/opendatahub/opendatahub-operator/-/blob/v0.5.0/docs/enabling-gpu-aicoe-jupyterhub.adoc

**Comment by wzrdtales** [comment]
yay :)

**Comment by wzrdtales** [comment]
Since this in the early stage of design in the hope to influence a bit :) Just being able to choose a CRI is not the only meaningful thing. Hinting at for example https://github.com/atrioinc/multi-cri to allow multiple cris which it is not capable yet without adding code to allow multiple cris and is therefor just a blueprint. Maybe that might be something to step in and go a step further than just selecting.
It is useful when there are mixed environments on a single k8s cluster where you want containerd, gvisor and maybe kata containers side by side.

**Comment by leolb-aphp** [comment]
@wzrdtales You would certainly want to mix them yes. But I am thinking it might be wiser to create different kubernetes clusters for this. I don't feel like namespaces are sufficient layers of isolation.

**Comment by wzrdtales** [comment]
agreeing that namespace isolation is certainly not enough, but that is not the case at all in my setups. There are multiple isolation layers in place not just namespaces and I especially don't want multiple clusters in many scenarios, while moving some application in a more secure deployment than raw LXC/Docker. This must not even be 3rd party software (such as keycloak for example which is currently a prominent example across a lot of customers of me), it can be just an internal application with higher attack surface.

The fact is, I am doing this already and am using in rancher today already multiple CNIs, but rke being able to do that would make this a whole lot easier.

**Comment by cjellick** [comment]
Not sure there is anything actionable here so I am going to close this issue.
RKE2 will have containerd by default, but you can disable it and lay down your own CRI on each worker node.

**Comment by immanuelfodor** [comment]
FYI, Kubernetes is deprecating Dockershim and so Docker as runtime, containerd (and CRI-O) support is even more compelling from RKE2:
- https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/
- https://kubernetes.io/blog/2020/12/02/dockershim-faq/
