### ISSUE TITLE
Replace klipper-lb with busybox

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#7013]
**Is your feature request related to a problem? Please describe.**

Following on from k3s PR: https://github.com/k3s-io/k3s/pull/10954 we should do the same in RKE2

**Describe the solution you'd like**

Replace klipper-lb with busybox and start relying on kube-proxy for externalIPs

**Describe alternatives you've considered**

**Additional context**

**Comment by brandond** [comment]
Not doing this, the change was reverted from K3s.
