### ISSUE TITLE
Mount secret in api server

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#7043]
I am integrating  oidc with apiserver using config file as an argument below

```
kube-apiserver-arg:
  - --oidc-issuer-url=https://auth.jumphost.nip.io/
  - --oidc-client-id=oidc-auth-client
  - --oidc-ca-file=<Mount from secret>
  - --oidc-username-claim=email
  - --oidc-groups-claim=groups
```

Please let me know, how I can do (**Mount from secret  - --oidc-ca-file=/tmp/ca.crt**) that without modify apiserver manifest.

**Comment by brandond** [comment]
You can't. The apiserver is where secrets come from. How is the pod supposed to mount into the apiserver pod the content of something that isn't available until the apiserver is up?

It needs to be an actual file on disk on the node.
