### ISSUE TITLE
DNS seems to ignore domain-specific rules of systemd-resolve

### ISSUE THREAD

**Issue by LarsSven** [rancher/rke2#7044]
**Environmental Info:**
RKE2 Version: v1.30.3+rke2r1

Node(s) CPU architecture, OS, and Version: x86, Flatcar 3975.2.2

Cluster Configuration: 3 servers (4 cores, 8GB), 2 agents (4 cores, 8GB), running on OpenStack Nova 

**Describe the bug:**
On the OpenStack VMs we have 2 DNS servers configured, one is an internal DNS that only knows about very specific internal A records, while the other is a normal DNS that can be used to access the external internet. The internal DNS is essentially configured as:
```
[Resolve]
DNS=195.169.22.11
Domains=~digitallab.internal
```
The external DNS is simply retrieved using DHCP. Due to the `Domains` rule, the VM should only ever use the internal DNS for the `digitallab.internal` domain. However, When deploying an RKE2 cluster on top, the cluster seems to be using one of the two DNS servers at random and not considering the Domain-specific rules. I'm honestly a bit new to RKE2 so I'm not entirely sure how to confirm/debug it, but pods in the cluster roughly have a 50% failure rate on DNS lookups, while the VM has a 0% failure rate on DNS lookups.

**Expected behavior:**
RKE2 should ignore DNS servers that are configured for specific domains when it is trying to look up a domain that is not part of those specific domains

**Actual behavior:**
RKE2 seems to ignore domain-specific rules and approaches a random DNS server.

**Comment by brandond** [comment]
What is that configuration snippet from? That does not appear to be resolv.conf or coredns corefile syntax, or anything else that I would expect to be honored by RKE2 or Kubernetes in general.

The cluster dns service (coredns) doesn't use the local resolver on the nodes, as systemd-resolved only listens on the loopback address, which is not available within pods. It uses whatever the upstream resolver is configured on the node's resolv.conf, or if none can be found, falls back to using 8.8.8.8.
