### ISSUE TITLE
[WINDOWS] Cannot join Windows worker node to cluster

### ISSUE THREAD

**Issue by luisxkimo** [rancher/rke2#7075]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.30.5+rke2r1 (0c83bc82315cd61664880d0b52a7e070e9fbd623)
go version go1.22.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Windows Server 2022 21H2 Build 20348.2700

Cluster Configuration:
2 Managers and 2 workers in RHEL all of them

**Describe the bug:**
I'm trying to configure new Windows node in my cluster. This is the current config file:

```yaml
server: https://10.20.228.232:9345
token: "xxxx"
cni: calico
node-name: "windows-node1"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
node-taint:
  - csi-plugin=true:NoSchedule
  - os=windows:NoSchedule
debug: true
```

- Windows node are in the same subnet of the other cluster nodes (managers and workers) 
- Windows node have connectivity to the managers
> Invoke-WebRequest -Uri "https://10.20.228.232:9345/ping" -UseBasicParsing -SkipCertificateCheck

```pwsh
StatusCode        : 200
StatusDescription : OK
Content           : pong
```

**Steps To Reproduce:**
- Create a cluster with 2 managers and 2 workers in linux system
- Follow this instructions to run and configure worker in Windows: https://docs.rke2.io/install/quickstart#windows-agent-worker-node-installation

**Expected behavior:**
Windows node added to the cluster

**Actual behavior:**
rke2 Windows service throws some errors in Event viewer and node is not added to the cluster

**Additional context / logs:**

```
Starting rke2 agent v1.30.5+rke2r1 (0c83bc82315cd61664880d0b52a7e070e9fbd623)

Adding server to load balancer rke2-agent-load-balancer: 10.20.228.232:9345

Running load balancer rke2-agent-load-balancer 127.0.0.1:6444 -> [10.20.228.232:9345] [default: 10.20.228.232:9345]

Supervisor proxy using supervisor=https://127.0.0.1:6444 apiserver=https://127.0.0.1:6444 lb=true

failed to get CA certs: Get "https://127.0.0.1:6444/cacerts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Dial error from load balancer rke2-agent-load-balancer after 21.050524s: dial tcp 10.20.228.232:9345: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Incoming conn 127.0.0.1:52634, error dialing load balancer servers: context deadline exceeded 
```

**Comment by manuelbuil** [comment]
Do you see anything interesting in the logs of `10.20.228.232`? It seems like the supervisor is not responding correctly
