### ISSUE TITLE
How do I make the systemctl start rke2-server.service command run in the background

### ISSUE THREAD

**Issue by zzzhangqi** [rancher/rke2#7080]
**Environmental Info:**
RKE2 Version:  v1.29.7-rke2r1

Node(s) CPU architecture, OS, and Version:  amd64, Ubuntu 24.04

**Describe the bug:**

After executing the installation script `curl -sfL https://get.rke2.io | sh -`, Execute startup command `systemctl start rke2-server.service`, It will be stuck in the terminal for a long time. only a new terminal can be opened to observe the log and check the installation status.

How do I make the `systemctl start rke2-server.service` command run in the background

**Comment by brandond** [comment]
This is a systemd question, not RKE2. You should check the documentation on `systemctl` if you don't know how to use - but the short answer is to use `systemctl start --no-block rke2-server`. Or just hit control-c if you're impatient, it won't affect anything and you'll be dropped back to a shell.
