### ISSUE TITLE
Bump multus, cilium and flannel charts

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#7090]
**Is your feature request related to a problem? Please describe.**

Use the freshly release v1.6.0 of the upstream cni plugins

**Describe the solution you'd like**

Use the freshly release v1.6.0 of the upstream cni plugins

**Describe alternatives you've considered**

**Additional context**

**Comment by mdrahman-suse** [comment]
Validated all the backports on release branch commits
Flannel issue with Windows is tracked separately
