### ISSUE TITLE
--cluster-reset not mentioned in help

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#71]
Version:
(all)
latest validated on version v0.0.1-alpha.6

Issue:
There is no mention of `--cluster-reset` when using `rke2 server --help`

**Comment by briandowns** [comment]
This flag is deemed experiment and hidden in k3s which is why think it's not showing up. @ibuildthecloud is this something we want exposed or hidden in RKE2?

**Comment by briandowns** [comment]
Got an update from @cjellick that this is intended behavior for now but can be revisited.

**Comment by davidnuzik** [comment]
I took note of this for the future so we'll remember to revisit this later.
