### ISSUE TITLE
Ability to remove node labels/taints

### ISSUE THREAD

**Issue by jhoblitt** [rancher/rke2#7151]
**Is your feature request related to a problem? Please describe.**

I would like to be able to migrate labels between nodes. That is, add the label to new node(s) and be able to remove the label of existing nodes.  Currently, it is possible to set labels via `config.yaml` but there isn't a (documented) way to delete an existing label.

**Describe the solution you'd like**

For `rke2-{server,agent}` to either keep state as to which labels/taints were added via the config or for there to be a magic key value which would cause a label to be removed. E.g. `alice=null`.

**Comment by brandond** [comment]
See the discussion at https://github.com/rancher/rke2/issues/7152#issuecomment-2445144813

As mentioned there, the RKE2 options are passed through directly to the kubelet flags, and are only used to **add** values when the node is registered. RKE2 itself does not keep node labels or taints in sync with what is in the config file.
