### ISSUE TITLE
setting node-taint for enrolled nodes does nothing

### ISSUE THREAD

**Issue by jhoblitt** [rancher/rke2#7152]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.29.9+rke2r1 (429b6bbac506250ccc93e3c17967849223529c50)
go version go1.22.6 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

```
Linux XXX 5.14.0-427.37.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 24 17:44:03 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

5 servers, 13 agents

**Describe the bug:**

Adding 
```
node-taint:
- alice=bob:NoExecute
```
to the `config.yaml`, as showing in the [config example](https://docs.rke2.io/install/configuration#multiple-config-files). Has no effect. This works for `node-label` and my expectation is that setting taints would work similarly.

**Steps To Reproduce:**

- Installed RKE2: 
- started `rke2-agent`
- editing `config.yaml` to add `node-taint`
- restarted `rke2-agent`
- inspected node via `k get node foo -oyaml`

**Expected behavior:**

That a taint would appear in `node.spec.taints`.

**Actual behavior:**

Nothing happened.

**Additional context / logs:**

**Comment by jhoblitt** [comment]
Note that kubelet is not being run with a `--register-with-taints` flag and there doesn't appear to be a `KubeletConfiguration` file.

**Comment by brandond** [comment]
Yes, this is covered in the docs.
https://docs.rke2.io/advanced#node-labels-and-taints
> RKE2 agents can be configured with the options node-label and node-taint which adds a label and taint to the kubelet. The two options only add labels and/or taints at registration time, and can only be added once and not removed after that through rke2 commands.
>
> If you want to change node labels and taints after node registration you should use kubectl. Refer to the official Kubernetes documentation for details on how to add [taints](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) and [node labels](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node).
