### ISSUE TITLE
Error from server: error dialing backend: dial tcp: lookup

### ISSUE THREAD

**Issue by grk-pancham** [rancher/rke2#716]
We are getting dns lookup failures in all kube system logs (namely coredns, api server) with version RKE Government v1.19.7+rke2r1. 
the kube system pods are unable to lookup host from the upstream dns host.

Error:
Error from server: error dialing backend. dial tcp: lookup <hostname> on <dns host>:53: no such host

**Comment by brandond** [comment]
Duplicate of #662
