### ISSUE TITLE
[Maintenance] Ingress Nginx image version bump

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#7166]
This issue tracks bumping ingress-nginx image to version `1.10.5-hardened4`. 

Currently the `hardened3` image has two HIGH CVEs, [SUSE-SU-2024:3745-1](https://www.suse.com/support/update/announcement/2024/suse-su-20243745-1/). Producing a new image will use the latest SLES base-image with fixes for those CVEs.

**Comment by dereknola** [comment]
```
rancher/nginx-ingress-controller:v1.10.5-hardened4 (suse linux enterprise server 15.6)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by mdrahman-suse** [comment]
Validated on all the release backports
