### ISSUE TITLE
RKE2 ETCD snapshot created with 0B data due to missing snapshots in rke2-etcd-snapshots configmap

### ISSUE THREAD

**Issue by JacieChao** [rancher/rke2#7202]
**Environmental Info:**
RKE2 Version: v1.28.12+rke2r1

**Cluster Configuration:**

3 etcd/controlplane/worker provisioned by Rancher

**Describe the bug:**

The rke2 server won't sync the `rke2-etcd-snapshots` configmap after the snapshot file is created successfully which will cause the snapshot shown as 0B from Rancher UI.

**Steps To Reproduce:**

- Installed RKE2: Provisioned Custom RKE2 by Rancher
- The downstream RKE2 upgrade route is v1.26.8+rke2r1 -> v1.27.14+rke2r1 -> v1.28.10+rke2r1 -> v1.28.11+rke2r1 -> v1.28.12+rke2r1
- The hostname for the downstream cluster is `thisisatesthost209.jacietesta.com`
- Take a snapshot from Rancher UI. The snapshot shows 0B after the snapshot file is created successfully on the nodes.
![QQ_1730894232981](https://github.com/user-attachments/assets/14d48ac6-4d09-4757-bc1a-e1e6d69ea472)

**Expected behavior:**

The snapshot should create successfully.

**Actual behavior:**

The snapshot can be found in downstream cluster but doesn't exist in the `rke2-etcd-snapshots` configmap. The snapshot result shows 0B from Rancher UI.

**Additional context / logs:**

I found the issue https://github.com/rancher/rancher/issues/45141 here, but this issue is not the inconsistent issue for the `rke2` and `rke2-etcd` lease.

In my environment, the lease results show the same as below.
```
kubectl get lease -n kube-system rke2-etcd -o jsonpath='{.spec.holderIdentity}'
thisisatesthost209.jacietesta.com

kubectl get lease -n kube-system rke2 -o jsonpath='{.spec.holderIdentity}'
thisisatesthost209.jacietesta.com
```
The `etcdsnapshotfiles.k3s.cattle.io` CRD also exists on the downstream rke2 cluster.
```
kubectl get etcdsnapshotfiles.k3s.cattle.io | grep on-demand-thisisatesthost209.jacietesta.com-1730791109
local-on-demand-thisisatesthost209.jacietesta.com-1730791109-5bcb05        on-demand-thisisatesthost209.jacietesta.com-1730791109        thisisatesthost209.jacietesta.com    file:///var/lib/rancher/rke2/server/db/snapshots/on-demand-thisisatesthost209.jacietesta.com-1730791109        18427936   2024-11-05T07:18:29Z
```
This snapshot file exists on the rke2 cluster node.
```
root@thisisatesthost209:/var/lib/rancher/rke2/server/db/snapshots#ls -la | grep on-demand-thisisatesthost209.jacietesta.com-1730791109
-rw-------  1 root root 18427936 Nov  5 07:18 on-demand-thisisatesthost209.jacietesta.com-1730791109
```
This snapshot can be found by `rke2 etcd-snapshot list` command as below
```
rke2 etcd-snapshot list | grep on-demand-thisisatesthost209.jacietesta.com-1730791109

on-demand-thisisatesthost209.jacietesta.com-1730791109     file:///var/lib/rancher/rke2/server/db/snapshots/on-demand-thisisatesthost209.jacietesta.com-1730791109     18427936 2024-11-05T07:18:29Z
```
But this snapshot won't write to the rke2-etcd-snapshots configmap.
```
root@thisisatesthost209:/var/lib/rancher# kubectl -n kube-system get configmap rke2-etcd-snapshots -o yaml | grep on-demand-thisisatesthost209.jacietesta.com-1730791109
root@thisisatesthost209:/var/lib/rancher#
```
This results in the ETCDSnapshot status in Rancher showing 0B. Here is an example of an ETCDSnapshot CRD.
```
apiVersion: rke.cattle.io/v1
kind: ETCDSnapshot
metadata:
  annotations:
    etcdsnapshot.rke.io/snapshot-file-name: on-demand-thisisatesthost209.jacietesta.com-1730791109
    etcdsnapshot.rke.io/storage: local
  creationTimestamp: "2024-11-06T09:45:04Z"
  generation: 1
  labels:
    rke.cattle.io/cluster-name: ppspapprke
    rke.cattle.io/machine-id: 0883a1f5173a1a06325b57130a9718697bd42d9b7bec7e5c047b6e70ba1d9b9
  name: ppspapprke-on-demand-thisisatesthost209.jacietesta.com-17307-d4969
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Machine
    name: custom-9afdf4b98ee4
    uid: e78f42ac-4945-4d17-ba3f-cad7817bc2e8
  resourceVersion: "520632"
  uid: 133caccd-cf36-4ac2-b928-58c8741eeb1d
snapshotFile:
  location: file:///var/lib/rancher/rke2/server/db/snapshots/on-demand-thisisatesthost209.jacietesta.com-1730791109
  name: on-demand-thisisatesthost209.jacietesta.com-1730791109
  nodeName: thisisatesthost209.jacietesta.com
spec:
  clusterName: ppspapprke
status:
  missing: true
```

**Comment by JacieChao** [comment]
The snapshot won't be written to the configmap with empty metadata as https://github.com/k3s-io/k3s/issues/8834. 
This is the expected behavior in this issue.
```
apiVersion: k3s.cattle.io/v1
kind: ETCDSnapshotFile
metadata:
  creationTimestamp: "2024-11-05T07:51:45Z"
  finalizers:
  - wrangler.cattle.io/managed-etcd-snapshots-controller
  generation: 1
  labels:
    etcd.rke2.cattle.io/snapshot-storage-node: thisisatesthost209.jacietesta.com
  name: local-on-demand-thisisatesthost209.jacietesta.com-1730791109-5bcb05
  resourceVersion: "31839"
  uid: 39a4c638-8ecb-4a9d-be71-0bdcdf63e725
spec:
  location: file:///var/lib/rancher/rke2/server/db/snapshots/on-demand-thisisatesthost209.jacietesta.com-1730791109
  nodeName: thisisatesthost209.jacietesta.com
  snapshotName: on-demand-thisisatesthost209.jacietesta.com-1730791109
status:
  creationTime: "2024-11-05T07:18:29Z"
  readyToUse: true
  size: "18427936"
```

**Comment by JacieChao** [comment]
Hi @brandond as the https://github.com/k3s-io/k3s/issues/8834:
> The snapshot controller shouldn't create configmap entries for snapshots that have empty extra metadata; this confuses Rancher.

I think it still confuses Rancher as the 0B data result. The plan secret got this snapshot file and created ETCDSnapshot CRD. But the snapshot won't be an entry of the configmap without extra metadata. It's also not consistent with the `rke2 etcd-snapshot list` result which can confuse the user about whether the snapshot is successful or not.

So I'm confused about what would cause a successful snapshot to lose the extra metadata?

**Comment by brandond** [comment]
The snapshot won't be listed in the configmap under either of two conditions:
* There is no metadata present in the cluster at the time the snapshot is taken. Rancher is normally responsible for populating this metadata into the `rke2-etcd-snapshot-extra-metadata` configmap in the `kube-system` namespace in the downstream cluster.
* The configmap has grown too large to hold metadata for all snapshots, so some older snapshots are pruned from it to ensure that it does not grow too large to store.

**Comment by brandond** [comment]
Also, you didn't mention what Rancher version you're on, but I would recommend ensuring you're on the latest available patch of whatever minor you're on. If you're on a community release, make sure you're on the latest v2.9 patch.

**Comment by JacieChao** [comment]
@brandond Thanks for your quick reply. The Rancher version of my situation is v2.8.7. I will try to deep-dive the Rancher log with empty extra metadata reasons.

**Comment by brandond** [comment]
Search for messages from the snapshotbackpopulate controller
