### ISSUE TITLE
Node lose DNS after restart

### ISSUE THREAD

**Issue by didlawowo** [rancher/rke2#7226]
**Environmental Info:**
RKE2 Version: 1.31

Node(s) CPU architecture, OS, and Version: 
arm64 and amd64, debian / ubuntu
both impacted
cni cilium 

Cluster Configuration:
3 server 2 agent

**Describe the bug:**
when restart a node, the dns doesn't work anymore
reinstall the node using rke2 install fix the problem

**Steps To Reproduce:**
sudo reboot 

- Installed RKE2 config:
```
write-kubeconfig-mode: "0644"
tls-san:
  - "192.168.1.200"
  
# Make a etcd snapshot every 6 hours
etcd-snapshot-schedule-cron: "0 */6 * * *"
# Keep 56 etcd snapshorts (equals to 2 weeks with 6 a day)
etcd-snapshot-retention: 56
etcd-expose-metrics: true
cni:
  - none
disable:
  - rke2-ingress-nginx
disable-cloud-controller: true
disable-kube-proxy: true

```
```
CILIUM_VERSION="1.16.3"
helm repo add cilium https://helm.cilium.io/
helm upgrade --install cilium cilium/cilium --version=${CILIUM_VERSION} \
    --namespace kube-system \
    --create-namespace \
    --set kubeProxyReplacement=true \
    --set ingressController.enabled=false \
    --set ingressController.default=false \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.enabled=true \
    --set cluster.name="rke2" \
    --set localRedirectPolicy=true \
    --set cluster.id=1 \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set encryption.enabled=true \
    --set encryption.type=wireguard \
    --set l2announcements.enabled=true \
    --set l2announcements.leaseDuration="3s" \
    --set l2announcements.leaseRenewDeadline="1s" \
    --set l2announcements.leaseRetryPeriod="500ms" \
    --set externalIPs.enabled=true \
    --set k8sServiceHost="192.168.1.200" \
    --set k8sServicePort="6443" 
```

**Expected behavior:**
node restart and get dns working

**Actual behavior:**
dns not working (most timeout exception)

**Additional context / logs:**

**Comment by manuelbuil** [comment]
```
when restart a node, the dns doesn't work anymore
```
Can you show what you are trying and what you get? I wonder if dns resolution does not work in pods running at the node or in the node itself or both. Also not sure if you can't access the dns service or if it replies with a wrong answer

**Comment by didlawowo** [comment]
the dns resolution doesn"t work on pod for sure, on node i'm not sure.

i have several issue.
finally i have found maybe something on the leases side

**Comment by didlawowo** [comment]
a rollout restart of cilium daemonset fix the problem.
i think it's about endpoint.

**Comment by didlawowo** [comment]
this is a probleme with cilium l2 annoucement .
