### ISSUE TITLE
rke2 server -> changing cluster-cidr to i.e. "172.27.0.0/16" does NOT change podCidr: 10.42.0.0/16 for rke2-canal

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#723]
We have deployed RKE2 v1.19.7+rke2r1 with these settings in config.yaml:

```
cluster-cidr: "172.27.0.0/16"
service-cidr: "172.28.0.0/16"
```

But had to realize that the setup for canal is NOT adjusted and still sets the "wrong" default podCidr: 10.42.0.0/16.

We can see this in the logs of 

`kubectl -n kube-system logs rke2-canal-8mrtw kube-flannel`:

```
I0224 15:04:51.738121       1 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
I0224 15:04:51.738142       1 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
I0224 15:04:51.738616       1 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
I0224 15:04:51.738625       1 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 -j ACCEPT
I0224 15:04:51.738771       1 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0224 15:04:51.739207       1 iptables.go:167] Deleting iptables rule: -d 10.42.0.0/16 -j ACCEPT
I0224 15:04:51.739442       1 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.1.0/24 -j RETURN
I0224 15:04:51.740152       1 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 -j ACCEPT
I0224 15:04:51.740519       1 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully
I0224 15:04:51.741348       1 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
I0224 15:04:51.742006       1 iptables.go:155] Adding iptables rule: -d 10.42.0.0/16 -j ACCEPT
I0224 15:04:51.743213       1 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0224 15:04:51.744959       1 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.1.0/24 -j RETURN
I0224 15:04:51.746233       1 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully

```

Unfortunately this causes all PODs to be blocked for network communication because the iptables rules to not match the cluster CIDR.

Is this a bug in rke2 or is this just something we have overseen somewhere in the documentation?

**Comment by Martin-Weiss** [comment]
Just tried to work around this problem with this:

`/var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml`

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    podCidr: 172.27.0.0/16
```

--> here I see that kube-flannel sets the correct things after deleting the pods - but we still can not communicate between pods (can not use coredns). In case I leave the CIDRs on default - all seems to work.. but unfortunately the default is conflicting with other services networks in the environment..

Any idea how to fix this properly/workaround this problem?

**Comment by brandond** [comment]
Just to confirm a couple things:
* Cluster and service CIDRs should be set on first startup; if you change them after the fact things will not be reassigned as expected.
* If you change the service CIDR you must also change the CoreDNS service address and set this via `rke2 server --cluster-dns=X.X.X.X`

**Comment by Martin-Weiss** [comment]
> 
> 
> Just to confirm a couple things:
> 
>     * Cluster and service CIDRs should be set on first startup; if you change them after the fact things will not be reassigned as expected.
> 

Sure - and that is what I have done (via config.yaml)

But then I also had to realize the wrong config in rke2-canal that is not "automatically adjusted" when config.yaml is used to adjust cluster CIDR so had to do this for this deployment post mortem...

>     * If you change the service CIDR you must also change the CoreDNS service address and set this via `rke2 server --cluster-dns=X.X.X.X`

This is interesting - did not do this and I can see that my service automatically is running in the new cluster CIDR

`kube-system   rke2-coredns-rke2-coredns            ClusterIP   172.28.0.10    <none>        53/UDP,53/TCP   20h`

So why do I have to specify -cluster-dns=172.28.0.10 during deployment and did I oversee this in the RKE2 documentation ?

**Comment by dbason** [comment]
The `--cluster-dns option` is used by the kubelet processes to set the DNS address in the resolv.conf file inside the pods.  Without that the pods will be trying to use 10.43.0.10 as their resolver, hence the issues you are seeing.  The option is documented in the (rke2 server docs)[https://docs.rke2.io/install/install_options/server_config/] but I do agree the docs don't provide much guidance on changing the CIDR ranges inside the cluster.

**Comment by dbason** [comment]
I've just tested this now and it does seem that the `--cluster-dns` setting is inferred from the `service-cidr` config.  Everything else seems to work as expected with alternative CIDR settings.

**Comment by Martin-Weiss** [comment]
> 
> 
> I've just tested this now and it does seem that the `--cluster-dns` setting is inferred from the `service-cidr` config. Everything else seems to work as expected with alternative CIDR settings.

What do you mean with "everything"? I believe that at least the canal configuration seems to be wrong and needs the manual workaround / change when changing the cluster CIDR or what do you think?

I have even one more problem - maybe related or I might need to create an other issue.. - all my PODs in the cluster network (10.42) can not reach 10.43. - first I thought it is due to the changed CIDR for cluster and service network - but even with default settings a simple busybox in kube-system can not reach 10.43.0.10 to do DNS resolution... Any idea? Should I create an other issue for that?

**Comment by Martin-Weiss** [comment]
FYI - the POD to DNS communication problem seems to be related to the busybox image.. with SLE, Ubuntu and Atomic it works..
So for this issue here - I believe we just need to add handling of the changed CIDR in the canal deployment via adjusted values for the helm chart..

**Comment by briandowns** [comment]
It would appear to be an issue with NetworkManager trying to manage the Flannel device. Can you confirm Network Manager is disabled or explicitly ignoring this device?

**Comment by Martin-Weiss** [comment]
> 
> 
> It would appear to be an issue with NetworkManager trying to manage the Flannel device. Can you confirm Network Manager is disabled or explicitly ignoring this device?

We do not have NetworkManager.

The challenge is that rke2-server has this when changing CIRDs:
```
cluster-cidr: "172.27.0.0/16"
service-cidr: "172.28.0.0/16"
cluster-dns: "172.28.0.10"
```

but 

helm get values rke2-canal -n kube-system all

--> podCidr: 10.42.0.0/16

So I assume we have to adjust the podCidr for rke2-canal "manually" when changing the cluster-cidr via config.yaml.. and it would be great if rke2-server would take care of this setting automatically..

**Comment by Martin-Weiss** [comment]
FYI - there still seems to be something hard coded in canal forcing something to 10.42.. !

/etc/rancher/rke2/config.yaml

```
cluster-cidr: "172.27.0.0/16"
service-cidr: "172.28.0.0/16"
cluster-dns: "172.28.0.10"

```

And for the metrics server I see these IPtables

`iptables-save|grep -i metrics`

I see 10.42...: where I would expect 172...

```
-A KUBE-SEP-4C7CFOPWIRT7KGVW -s 172.27.2.7/32 -m comment --comment "kube-system/rke2-metrics-server" -j KUBE-MARK-MASQ
-A KUBE-SEP-4C7CFOPWIRT7KGVW -p tcp -m comment --comment "kube-system/rke2-metrics-server" -m tcp -j DNAT --to-destination 172.27.2.7:8443
-A KUBE-SEP-7XULAATHQLGMXNJM -s 172.27.2.5/32 -m comment --comment "kube-system/rke2-metrics-server" -j KUBE-MARK-MASQ
-A KUBE-SEP-7XULAATHQLGMXNJM -p tcp -m comment --comment "kube-system/rke2-metrics-server" -m tcp -j DNAT --to-destination 172.27.2.5:8443
-A KUBE-SEP-J3XXHVMWP4DPPEWS -s 172.27.2.6/32 -m comment --comment "kube-system/rke2-metrics-server" -j KUBE-MARK-MASQ
-A KUBE-SEP-J3XXHVMWP4DPPEWS -p tcp -m comment --comment "kube-system/rke2-metrics-server" -m tcp -j DNAT --to-destination 172.27.2.6:8443
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 172.28.76.203/32 -p tcp -m comment --comment "kube-system/rke2-metrics-server cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 172.28.76.203/32 -p tcp -m comment --comment "kube-system/rke2-metrics-server cluster IP" -m tcp --dport 443 -j KUBE-SVC-JOQCPDX2ATLAF3TL
-A KUBE-SVC-JOQCPDX2ATLAF3TL -m comment --comment "kube-system/rke2-metrics-server" -m statistic --mode random --probability 0.33333333349 -j KUBE-SEP-7XULAATHQLGMXNJM
-A KUBE-SVC-JOQCPDX2ATLAF3TL -m comment --comment "kube-system/rke2-metrics-server" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-J3XXHVMWP4DPPEWS
-A KUBE-SVC-JOQCPDX2ATLAF3TL -m comment --comment "kube-system/rke2-metrics-server" -j KUBE-SEP-4C7CFOPWIRT7KGVW
```

-> could it be that there is something in canal hard coded for 10.42?

**Comment by brandond** [comment]
With Flannel at least it's difficult to erase all references to the original CIDRs once any part of the cluster has come up with them. Are you still seeing references to 10.24.0.0/16 even on a clean cluster with the appropriate values in place from the start?

**Comment by Martin-Weiss** [comment]
> 
> 
> With Flannel at least it's difficult to erase all references to the original CIDRs once any part of the cluster has come up with them. I suspect Canal might be the same way. Are you still seeing references to 10.24.0.0/16 even on a clean cluster with the appropriate values in place from the start?

I am only testing with 100% fresh deployment and I can see this in iptables-save:

-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 172.28.76.203/32 -p tcp -m comment --comment "kube-system/rke2-metrics-server cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ

So the settings in config.yaml are not resulting in a proper change to 172.27. POD network.. Unfortunately I could not find where the reference to 10.42.0.0/16 is coming from - so assuming it might be hard coded in the canal/flannel or rke2 somewhere..

**Comment by brandond** [comment]
@wrkode and I determined this afternoon that it's coming from the rke2-kube-proxy helm chart. In addition to setting the podCird value for the rke2-canal chart, you also need to set the clusterCIDR value for the rke2-kube-proxy chart.

In general we need to do a better job of passing through values from the CLI into charts. We currently only pass through the system-default-registry value; it looks like we need to pass through cluster-cidr and kube-proxy-args as well.

**Comment by Martin-Weiss** [comment]
> 
> 
> @wrkode and I determined this afternoon that it's coming from the rke2-kube-proxy helm chart. In addition to setting the podCidr value for the rke2-canal chart, you also need to set the clusterCIDR value for the rke2-kube-proxy chart.
> 
> In general we need to do a better job of passing through values from the CLI into charts. We currently only pass through the system-default-registry value; we should probably pass through cluster-cidr and kube-proxy-args as well.
> 
> cc @cjellick

Great find! Thanks!

At least a valid workaround seems to exist with the following adjustment:

/var/lib/rancher/rke2/server/manifests/rke2-kube-proxy-config.yaml

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    clusterCIDR: 172.27.0.0/16
```

--> will give this a try, now.

**Comment by mstrent** [comment]
Thanks for the discussion, @Martin-Weiss & @brandond, it really helped. We also have to change the default subnets as they're already in use on our corporate LAN.

I've deployed the rke2-kube-proxy-config.yaml and rke2-canal-config.yaml workarounds, in addition to specifying config.yaml cluster-cidr & service-cidr per the docs.

Things do seem to be working, however I'm seeing events like this for all my services which indicates the default subnet is still lurking somewhere:
kube-system     2m54s       Warning   ClusterIPOutOfRange     service/rke2-coredns-rke2-coredns            Cluster IP 198.18.128.10 is not within the service CIDR 10.43.0.0/16; please recreate service
kube-system     2m49s       Warning   ClusterIPNotAllocated   service/rke2-coredns-rke2-coredns            Cluster IP 198.18.128.10 is not allocated; repairing
kube-system     2m54s       Warning   ClusterIPOutOfRange     service/rke2-ingress-nginx-default-backend   Cluster IP 198.18.245.203 is not within the service CIDR 10.43.0.0/16; please recreate service
kube-system     2m49s       Warning   ClusterIPNotAllocated   service/rke2-ingress-nginx-default-backend   Cluster IP 198.18.245.203 is not allocated; repairing

**Comment by mstrent** [comment]
Ok, looks like the above events are coming from kube-api.

**Comment by brandond** [comment]
I think you've forgotten to set the cluster-dns address to something within your new service cidr range?

> /etc/rancher/rke2/config.yaml
>```
>cluster-cidr: "172.27.0.0/16"
>service-cidr: "172.28.0.0/16"
>cluster-dns: "172.28.0.10"
>```

**Comment by jzuijlek** [comment]
I still have several issues with it using the 10.42 cidr some places. I've created the canal en kube-config manifests and used the cidr's and dns as described above uppon deployment.

`Warning  FailedCreatePodSandBox  6m     kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c0cdef817a0b6c6ef1a819350195a49918f7f112eaa0f09b24e3e21eaa3b6539": error getting ClusterInformation: Get "https://[172.28.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 10.60.5.62, 10.43.0.1, not 172.28.0.1`

Installing cert-manager with helm:
`Error: Internal error occurred: failed to allocate a serviceIP: the provided range does not match the current range`

**Comment by Martin-Weiss** [comment]
Did you re-deploy from scratch with the adjusted config.yaml and configs for canal and kube-proxy or did you change the settings "later"? It is strange to see a certificate valid for 10.43.0.1 in case you changed the CIRDs..

**Comment by jzuijlek** [comment]
I did do it later. I'll re-deploy from scratch again.

**Comment by jzuijlek** [comment]
Error is still present. New cluster from scratch with the CIDR specified in /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml and /var/lib/rancher/rke2/server/manifests/rke2-kube-proxy-config.yaml before starting the rke2-server service. 

Upon deploying cert-manager via helm:
`  Warning  FailedCreatePodSandBox  4s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1e155379733e979606747e3a68955e262ea5aa7a8925c75fbc0d2ab8ef2e3247": error getting ClusterInformation: Get "https://[172.28.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 10.60.5.63, 10.43.0.1, not 172.28.0.1
`

**Comment by Martin-Weiss** [comment]
Is is strange to see "x509: certificate is valid for 10.43.0.1, 127.0.0.1, 10.60.5.63, 10.43.0.1, not 172.28.0.1". 

I am not too deep in the details but I believe the kubernetes API should use the certificate in /var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt which should be build based on the settings in cluster.yaml.. When you re-deployed from scratch - did you wipe the server completely (especially delete /var/lib/rancher)? Did you use the rke2-uninstall.sh to clean up?

**Comment by jzuijlek** [comment]
Yes I used rke2-uninstall.sh to clean up and removed everything from /var/lib/rancher.

**Comment by brandond** [comment]
That looks more like an inter-node pod-to-service communications failure. Do you have firewalld/ufw active on your nodes?

**Comment by jzuijlek** [comment]
You are correct, vxlan is giving us issues with NXS firewall.

**Comment by belgaied2** [comment]
Is this issue resolved? It is a bug from Feb. What I mean is : are the command line arguments passed correctly to the Helm Chart now?

**Comment by brandond** [comment]
Yes, the command-line arguments are now propagated to the rke2-kube-proxy HelmChart configuration. Additionally, we are deprecating the Helm chart deployment in favor of running it as a static pod.

**Comment by mstrent** [comment]
@brandond Are you saying this workaround is no longer necessary, that the cluster-cidr config from config.yaml / rke2 command line will propagate through to either the (deprecated) kube-proxy Helm chart, or the new kube-proxy static pods? Or do we still need to separately pass cluster-cidr to kube-proxy via the new --kube-proxy-args?

**Comment by brandond** [comment]
The former.

**Comment by mstrent** [comment]
@brandond Awesome! Thank you!

Just to be sure: Would this also be true for Canal? The workaround podCidr Helm config would no longer be required?

**Comment by mstrent** [comment]
I've confirmed calico/flannel seem to be doing the right thing without the extra Helm chart config. @Martin-Weiss I think this issue can be closed.

**Comment by Martin-Weiss** [comment]
> 
> 
> I've confirmed calico/flannel seem to be doing the right thing without the extra Helm chart config. @Martin-Weiss I think this issue can be closed.

Thanks for the verification!

**Comment by vnjamat** [comment]
• **Tested for flannel CNI**
	• Login to primary master node
	• Backup current cluster 
	rke2 etcd-snapshot save --name current-snapshot
	• Copy the backup from /var/lib/rancher/rke2/server/db/snapshots
	• Copy node-token file from /var/lib/rancher/rke2/server/
	• Login to all nodes and backup the below files from /etc/rancher/rke2
		○ config.yaml
		○ registries.yaml
	• Scale down all the deployments
	• Stop and disable RKE2 service in all nodes except one secondary master node
	• Login to secondary master node
	• Remove all the nodes using kubectl except this secondary master
	• Backup current cluster 
	rke2 etcd-snapshot save --name pre-migrate-snapshot
	• Copy the backup from /var/lib/rancher/rke2/server/db/snapshots
	• Uninstall RKE2 in primary master node
	• Setup RKE2 in primary master node with cluster-cidr, don't Start RKE2 service
	• Restore cluster backup "pre-migrate-snapshot"
	rke2 server --cluster-reset --cluster-reset-restore-path=**<pre-migrate-snapshot backup file path>** --token=**<Token>**
	• Rotate certificates
	rke2 certificate rotate
	• Start RKE2 service
	• Remove secondary master node using kubectl
	• Update kube-flannel-cfg config map pod CIDR in kube-system namespace
	• Reboot Machine
	• Scale up rancher and rancher-webhook deployments
	• Cluster is ready with new pod CIDR
	• Backup current cluster 
	rke2 etcd-snapshot save --name post-migrate-snapshot
	• Uninstall RKE2 in other nodes and join again with cluster-cidr

**Comment by jvnvenu** [comment]
• **Tested for flannel CNI**
• Login to primary master node
• Backup current cluster 
rke2 etcd-snapshot save --name current-snapshot
• Copy the backup from /var/lib/rancher/rke2/server/db/snapshots
• Copy node-token file from /var/lib/rancher/rke2/server/
• Login to all nodes and backup the below files from /etc/rancher/rke2
	○ config.yaml
	○ registries.yaml
• Scale down all the deployments
• Stop and disable RKE2 service in all nodes except one secondary master node
• Login to secondary master node
• Remove all the nodes using kubectl except this secondary master
• Backup current cluster 
rke2 etcd-snapshot save --name pre-migrate-snapshot
• Copy the backup from /var/lib/rancher/rke2/server/db/snapshots
• Uninstall RKE2 in primary master node
• Setup RKE2 in primary master node with cluster-cidr, don't Start RKE2 service
• Restore cluster backup "pre-migrate-snapshot"
rke2 server --cluster-reset --cluster-reset-restore-path=<**pre-migrate-snapshot backup file path**> --token=<**Token**>
• Rotate certificates
rke2 certificate rotate
• Start RKE2 service
• Remove secondary master node using kubectl
• Update kube-flannel-cfg config map pod CIDR in kube-system namespace
• Reboot Machine
• Scale up rancher and rancher-webhook deployments
• Cluster is ready with new pod CIDR
• Backup current cluster 
rke2 etcd-snapshot save --name post-migrate-snapshot
• Uninstall RKE2 in other nodes and join again with cluster-cidr
