### ISSUE TITLE
traefik image not processed

### ISSUE THREAD

**Issue by vrbgtrhr** [rancher/rke2#7280]
i have placed rke2-images.linux-amd64.tar.zst and rke2-images-traefik.linux-arm64.tar.zst in /var/lib/rancher/rke2/agent/images/ but the traefik pod that spin up using the following config.yaml give ErrImagePull
```
ingress-controller: traefik
disable:
  - rke2-ingress-nginx
```

Version: v1.31.2+rke2r1

**Comment by dereknola** [comment]
>  rke2-images.linux-amd64.tar.zst and rke2-images-traefik.linux-arm64.tar.zst

You are using two different architectures for your images. Try it again with both `amd64`

**Comment by brandond** [comment]
The image tarballs need to be in `/var/lib/rancher/rke2/agent/images` when RKE2 starts. The install script doesn't do anything with them, they are processed by RKE2 when it starts. If you put the tarballs there **after** starting RKE2, they will not be imported.

Check to see what images you have imported:
`CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl image ls`
