### ISSUE TITLE
Packaged components don't come back when re-enabled

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#729]
#### Steps to reproduce

* Start RKE2 with `rke2 server --disable=rke2-coredns`
* Note lack of coredns on cluster
* Stop RKE2 and start with `rke2 server`
* Note that coredns does not come back since manifests are only extracted if the bin dir for this version is missing
* Upgrade RKE2 to a new version, or start RKE2 with `rke2 server --runtime-image=<IMAGE-FOR-DIFFERENT-VERSION>`
* Note that coredns comes back due to runtime image being extracted again

**Comment by rancher-max** [comment]
#### Validated using v1.20.4-rc3+rke2r1

-  Disabled all packaged components (rke2-canal, rke2-coredns, rke2-ingress-nginx, rke2-kube-proxy, rke2-metrics-server) and performed multiple stops/starts, enabling one at a time. 
- All services were disabled properly and re-enabled properly on a restart
