### ISSUE TITLE
external etcd path/prefix

### ISSUE THREAD

**Issue by SiimToo** [rancher/rke2#7311]
**Is your feature request related to a problem? Please describe.**
Path/prefix is needed for external centralised ETCD. It is for every cluster writes to different path. 
Example: /cluster1 /cluster2 etc   

**Describe the solution you'd like**
I would like a parameter like "--datastore-prefix" 

**Describe alternatives you've considered**

**Additional context**

**Comment by dereknola** [comment]
The etcd configuration in RKE2 is for the embedded etcd. If you want to run an external etcd, you can use the experimental Kine option if you want (docs are currently in review for this on the RKE2 docs site), but configuration is completely handled by via [standard etcd configuration docs](https://etcd.io/docs/v3.5/op-guide/configuration/).

**Comment by brandond** [comment]
It sounds like you're asking to have the `--etcd-prefix` flag respected for keys that RKE2 manages internally, such as the bootstrap key and apiserver endpoints key?

> --etcd-prefix string     Default: "/registry"
>  | The prefix to prepend to all resource paths in etcd.

This is NOT meant to be used to share a single etcd cluster over multiple Kubernetes clusters, and we do not intend to support use of a single external cluster for multiple RKE2 clusters.
