### ISSUE TITLE
`--cloud-provider-name=aws` is recommended by Rancher docs even when deploying out-of-tree aws cloud provider

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#7336]
We need to revert https://github.com/rancher/rke2/issues/6626 and leave this code in RKE2, as the Rancher docs are recommending users to deploy a hack whereby `--cloud-provider-name=aws` is set in the RKE2 config to get the hostname set properly, but `--cloud-provider=external` is set in all the Kubernetes component args to prevent them from crashing when the in-tree aws cloud provider is enabled:
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon#using-the-out-of-tree-aws-cloud-provider

This was discussed internally as a workaround for users trying to migrate to the out-of-tree cloud provider on RKE2 <= v1.27, it was NOT intended to be suggested as the correct way to deploy the out-of-tree AWS cloud provider following removal of the in-tree code.
    
We should:
1. revert the removal
2. add a new flag that opts into this special hostname-setting behavior, independent from setting the cloud provider name
3. add a warning that `--cloud-provider-name=aws` is deprecated, and (for now) wire up the new flag to that value.

**Comment by brandond** [comment]
This was a release blocker for the November patches; moved back into the correct milestone.

**Comment by fmoral2** [comment]
validated here
https://github.com/rancher/rke2/issues/7344#issuecomment-2515185383
https://github.com/rancher/rke2/issues/7345#issuecomment-2515185025

https://github.com/rancher/rke2/issues/7346#issuecomment-2515185191
