### ISSUE TITLE
kube-proxy tries to use nft binary that is not present in image

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#7337]
**Environmental Info:**
RKE2 Version: 1.31.2-rke2r1

Node(s) CPU architecture, OS, and Version:  Linux kub-a14 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 5 servers, 36 agets

**Describe the bug:**
`kube-proxy` prints at start:
```
2024-11-25T23:36:07.15370244+01:00 stderr F E1125 22:36:07.153557       1 proxier.go:734] "Error cleaning up nftables rules" err="could not find nftables binary: exec: \"nft\": executable file not found in $PATH"
2024-11-25T23:36:07.153741323+01:00 stderr F E1125 22:36:07.153641       1 proxier.go:734] "Error cleaning up nftables rules" err="could not find nftables binary: exec: \"nft\": executable file not found in $PATH"
```
the `nft` is not present in the `rancher/hardened-kubernetes:v1.31.2-rke2r1-build20241023` image.

**Steps To Reproduce:**

- Installed RKE2: 
```
server: https://xxx:9345
token:  xxx

cluster-cidr: 10.42.0.0/16,xxx:42cb:8:2::/96

service-cidr: 10.43.0.0/16,xxx:42cb:8:3::/112

kube-controller-manager-arg:
        - "feature-gates=InPlacePodVerticalScaling=true"
        - "node-cidr-mask-size-ipv6=108"


node-label:
  - "storage=local-ssd"

profile: cis

kube-scheduler-arg:
  - "feature-gates=InPlacePodVerticalScaling=true"

kubelet-arg:
  - "v=5"
  - 'config=/var/lib/rancher/rke2/agent/etc/kubelet.config'
  - "feature-gates=InPlacePodVerticalScaling=true,CloudDualStackNodeIPs=true"
  - "node-ip=10.16.62.19,xxx42cb:0:1:253:135"
  - "system-reserved=memory=8Gi"
  - "reserved-cpus=64-127"
  - "max-pods=160"
  - "kube-api-qps=100"
  - "kube-api-burst=100"
  - "cpu-manager-policy=static"
  - "topology-manager-policy=best-effort"

node-ip: '10.16.62.19,xxx:42cb:0:1:253:135'

control-plane-resource-requests: "kube-apiserver-memory=3G,etcd-memory=32G"
```

**Expected behavior:**

Do not complain about `nft` binary.

**Actual behavior:**
Error missing `nft` binary.

**Additional context / logs:**

n/a

**Comment by brandond** [comment]
This binary is not necessary unless you're running kube-proxy with `--proxy-mode=nftables`.

We may include the nft binary at some point, but it is not required and the messages are purely advisory (you have no nftables rules to clear because you're not running it in nftables mode).
