### ISSUE TITLE
ETCD Snapshot S3 (Minio) Upload not working

### ISSUE THREAD

**Issue by sass1997** [rancher/rke2#7383]
**Environmental Info:**
RKE2 Version: 1.30.06

Node(s) CPU architecture, OS, and Version: 
Linux 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 Servers 3 Nodes

**Describe the bug:**
After Upgrading cluster from 1.28 version to 1.29 and 1.30 the CronSchedule for ETCD Snapshots can't upload the snapshots anymore on s3 (minio). Trace Log of Minio. (Some Values are replaced by: xxx)
```
[REQUEST s3.NewMultipartUpload] [2024-12-04T17:19:21.699] [Client IP: xxx]
POST /xxx-etcd-backup/on-demand-xxx-m03-1733329161?uploads=
Proto: HTTP/1.1
Host: xxx
X-Amz-Date: 20241204T161921Z
X-Correlation-Id: 61dedc7e
X-Forwarded-Host: xxx
X-Forwarded-Port: 443
Content-Type: application/octet-stream
X-Forwarded-For: xxx
X-Amz-Meta-Rke2-Cluster-Id: 3d1174f3-6618-4bea-8fee-790504923c4f
X-Amz-Meta-Rke2-Token-Hash: 338a3a6d0c21
Accept-Encoding: gzip
Authorization: AWS4-HMAC-SHA256 Credential=4RYFVOVCF7ZX0Y5HRPWB/20241204/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-rke2-cluster-id;x-amz-meta-rke2-node-name;x-amz-meta-rke2-token-hash, Signature=9c5953c02ab1c1a88b70c0c2b6bac0755cd5e42e3ed385c2b5dacebcd78b1ff3
Content-Length: 0
Forwarded: for=xxx;proto=https;host=xxx
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
Https: on
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70
X-Forwarded-Proto: https
[RESPONSE] [2024-12-04T17:19:21.700] [ Duration 262µs TTFB 239.594µs ↑ 261 B  ↓ 454 B ]
400 Bad Request
X-Content-Type-Options: nosniff
X-Ratelimit-Remaining: 2132
X-Xss-Protection: 1; mode=block
Content-Length: 454
Content-Type: application/xml
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amz-Id-2: b675f5c02385af78c69266a96b22038bea3ecd7423814977a7267fd68ac2bbeb
X-Amz-Request-Id: 180E05B061F0F160
Accept-Ranges: bytes
Server: MinIO
Vary: Origin,Accept-Encoding
X-Ratelimit-Limit: 2132
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Key>on-demand-xxx-m03-1733329161</Key><BucketName>xxx-etcd-backup</BucketName><Resource>/xxx-etcd-backup/on-demand-xxx-m03-1733329161</Resource><RequestId>180E05B061F0F160</RequestId><HostId>b675f5c02385af78c69266a96b22038bea3ecd7423814977a7267fd68ac2bbeb</HostId></Error>
```

**Steps To Reproduce:**
Cluster >= 1.29
CronScheduleetcd Backup
Minio Version: Version: 2024-11-07T00:52:20Z

**Expected behavior:**
ETCD Snapshots Should be uploaded to S3

**Actual behavior:**
Upload isn't possible

**Additional context / logs:**
I've did a tracing of a cluster which is still on k8s version 1.28 as far as I can see there is newly the mulipartupload feature enabled in the s3 client since I only see the PUT Request in the old variant.

**Comment by brandond** [comment]
We're using minio/minio-go v7.0.70: https://github.com/rancher/rke2/blob/v1.30.6%2Brke2r1/go.mod#L293

I was unable to find anything in the repo with that specific error. The only thing I can find was a case where minio was behind nginx, and nginx was modifying the headers and breaking the signature: https://github.com/minio/minio-go/issues/1590

Can you confirm whether or not your minio instance is behind something that is modifying headers?

**Comment by sass1997** [comment]
Hi @brandond,

Could you confirm that the upload methods with the minio-go library was changed to multipart starting k8s 1.29? I'm not behind a nginx but there is a another proxy in front of which I can verify. The main concern of me is that upload with 1.28 was working like charm but starting 1.29 it's not working anymore.

Thank you for your answer

**Comment by brandond** [comment]
We update packages regularly for security and bug fixes. We have not changed anything specifically to enable multipart uploads, the client uses them automatically once the snapshot files are larger than a particular size - 5mb I think.

**Comment by sass1997** [comment]
I did the trace log on minio again on the 1.28 Version of RKE2 there I can see that the aws-sdk-go client is used
1.28
```
User-Agent: aws-sdk-go/1.42.10 (go1.19.8; linux; amd64)
```
1.30
```
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70
```

**Comment by brandond** [comment]
We have never used the AWS sdk for etcd snapshots. It has always been minio-go, back to the original implementation of S3 support in https://github.com/k3s-io/k3s/pull/2902/files

You're seeing traffic from something else.

**Comment by sass1997** [comment]
No it's exactly the request from the client which is uploading the etcd snapshots....I will try to setup an environment without f5 as next step.

**Comment by brandond** [comment]
I see the minio folks pointed out the same issue I did. Fix your F5.

**Comment by sass1997** [comment]
@brandond I will check to fix the header. Since I'm still very confused about the client information in the headers. We are doing the ETCD Snapshot Schedule Configuration etc via Rancher Manager. Could there be another behaviour in this case? I know this would be as well not your main focus in this project here still would be curious if you have a tip here

**Comment by brandond** [comment]
No. Rancher just configures the snapshot parameters, and executes the RKE2 CLI to interact with snapshots. It does not connect directly to S3 itself.
