### ISSUE TITLE
Migrating to custom CA certificates

### ISSUE THREAD

**Issue by manofftoday** [rancher/rke2#7384]
Although I had able to change the CA Certificates, it seems that its not working, since we created a cronjob and the cronjob was not able to change to running due to TLS error. So although apparently it works, the cluster is not able to create any object.

On master 1 node:
```shell
/bin/bash -c "DATA_DIR={{ rotate_certs_path }} PRODUCT=rke2 bash {{ rotate_certs_tls_path }}/generate-custom-ca-certs.sh
"rke2 certificate rotate-ca --force -path {{ rotate_certs_server_path }} -s {{ rke2_server }}
 rke2 certificate rotate
reboot
``` 

On the rest of the master nodes:
```shell
 rke2 certificate rotate
systemctl restart rke2-server
``` 

On the worker nodes:
```shell
systemctl restart rke2-agent
``` 

Then we update the kubeconfig TLS configuration with the new CA.
Nodes are join, I'm able to use kubectl but it seems that kube api is not being able to create or communicate correctly.

I'm missing something?
Thank you!

### Discussed in https://github.com/rancher/rke2/discussions/6533

<div type='discussions-op-text'>

<sup>Originally posted by **manofftoday** August 12, 2024</sup>
Hi there,

I need some help trying to figure out how to change the actual self-signed by rke2 CA certificates to custom CA certificates without re-deploying the cluster and trying to minimize the loss of service.
A fresh install worked flawlessly, but I can't figure out how to proceed on an already running cluster.

We have currently 3 master nodes and several worker nodes.
I'm following this procedure from official documentation.
This is the steps done:

1)
Created the intermediate CA and issued the crt and the key.
On the Master 1 which was the bootstrap, I created /opt/rke2/server/tls and placed into:

-  Custom intermediate-ca.pem
-  Custom intermediate-ca.key
-  Custom root-ca.pem
- A copy of /var/lib/rancher/rke2/server/tls/service.key

2)
Downloaded and run this script:

`curl -sL https://github.com/k3s-io/k3s/raw/master/contrib/util/generate-custom-ca-certs.sh | DATA_DIR=/opt/rke2 PRODUCT=rke2 bash -`

Now the certificates has been generated in /opt/rke2/server/tls on the master server.

If run the following command the certificates are not changing. A new token is either generated.

```
    rke2 certificate rotate-ca --path=/opt/rke2/server -s https://10.10.10.1:9345 --force
    certificates saved to datastore        

```

What should I do now? Any ideas? It's supposed this is supported according to the documentation... or at least is what I understand from this:

> If you used the --force option or changed the root CA, ensure that any nodes that were joined with a secure token are reconfigured to use the new token value, prior to being restarted. The token may be stored in a .env file, systemd unit, or config.yaml, depending on how the node was configured during initial installation.

I only found another old thread but I'm not sure if now it's supported or if changing the CA to custom in an already deployed environment is still unsupported...

#5613

Thank you!</div>

**Comment by brandond** [comment]
See https://docs.k3s.io/cli/certificate#using-the-example-script-1
> If the cluster has been started with default self-signed CA certificates, rotation will be disruptive. All nodes that were joined with a [secure token](https://docs.k3s.io/cli/token#secure) will need to be reconfigured to trust the new CA hash. If the new CA certificates are not cross-signed by the old CA certificates, you will need to use the --force option to bypass integrity checks, and pods will need to be restarted to trust the new root CA.

**Comment by manofftoday** [comment]
Thank you so much for your reply.
Yes, I read the documentation several times and still no clue how to do it.
I finally dealt with the issue following these steps, probably not the most efficient but:

1. Run the  generate-custom-ca-certs.sh script on the Master 1
2. Rotate CA Certificates with --force option on the Master 1
3. Restart rke2-server on Master 1
4. Rotate server certificate in the other etcd/control-plane nodes and restart rke2-server
5. Restart rke2-agent nodes
6. Replace TLS data on kubeconfig for kubectl
7. Get actual token value from file
8. Rotate token on Master 1:
`rke2 token rotate --data-dir /var/lib/rancher/rke2 --kubeconfig /etc/rancher/rke2/rke2.yaml --token {{ old_token}}`
9. Restart rke2-server on Master 1
10. Replace old token file with the new one in /var/lib/rancher/rke2/server/node-token for the rest of etcd/control-plane nodes
11. Restart rke2-server on the rest of etcd/control-plane servers
13. Replace old token file with the new one in /var/lib/rancher/rke2/agent/node-token for the workers nodes
14. Restart rke2-agent for the worker nodes
15. Delete all pods:
`kubectl delete pods --all -A`


Finally following this order seems to make it working.
I think documentation could be clearer here.
