### ISSUE TITLE
Unable to get image from private registry in http

### ISSUE THREAD

**Issue by PolarisPT** [rancher/rke2#7392]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.30.6+rke2r1 (2959cd2193af9ed18d0fc2912fc5c11d6462103d)
go version go1.22.8 X:boringcrypto
Rancher version : V2.9.2

Node(s) CPU architecture, OS, and Version: 
Linux rke2master 6.4.0-150600.23.25-default #1 SMP PREEMPT_DYNAMIC Tue Oct  1 10:54:01 UTC 2024 (ea7c56d) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node rke2

**Describe the bug:**
Unable to configure registry via Rancher gui to access private registry in http with auth

**Steps To Reproduce:**
This cluster was provisioned via Rancher (2.9.2) via "cluster management", "Custom".    

After configuring a deployment to access our private registry i get pod events :
"
Normal | BackOff (155) | 13 secs ago | Back-off pulling image "registry.ptinfra.com:30082/eureka-naming-server:1.1.1-250"
-- | -- | -- | --
Warning | Failed (6) | 33 mins ago | Error: ImagePullBackOff
Normal | Pulling (4) | 34 mins ago | Pulling image "registry.ptinfra.com:30082/eureka-naming-server:1.1.1-250"
Warning | Failed (4) | 34 mins ago | Failed to pull image "registry.ptinfra.com:30082/eureka-naming-server:1.1.1-250": failed to pull and unpack image "registry.ptinfra.com:30082/eureka-naming-server:1.1.1-250": failed to resolve reference "registry.ptinfra.com:30082/eureka-naming-server:1.1.1-250": failed to do request: Head "https://registry.ptinfra.com:30082/v2/eureka-naming-server/manifests/1.1.1-250": http: server gave HTTP response to HTTPS client
"
this is the registries.yaml generated based on the gui config i see in the node :  
"
rke2master:/var/lib/rancher/rke2/agent/etc/containerd # cat /etc/rancher/rke2/registries.yaml
{"configs":{"http://registry.ptinfra.com:30082":{"auth":{"username":"admin","password":"xxxxxxx","auth":"","identity_token":""},"tls":null}},"mirrors":null}
"

This is the the containerd generated config by rke2 :

"
rke2master:/var/lib/rancher/rke2/agent/etc/containerd # cat  /var/lib/rancher/rke2/agent/etc/containerd/config.toml
# File generated by rke2. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/rke2/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "index.docker.io/rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/var/lib/rancher/rke2/agent/etc/containerd/certs.d"

[plugins."io.containerd.grpc.v1.cri".registry.configs."http://registry.ptinfra.com:30082".auth]
  username = "admin"
  password = "xxxxxxx"
"

**Expected behavior:**
Expecting to be able to  download images from http private registry

**Actual behavior:**
Pod's unable to start because images cannot be downloaded

**Comment by brandond** [comment]
Please read the docs and set up your registry config properly. You seem to have registry URLs where you should have names, and do not have the endpoint set properly to use HTTP instead of HTTP.
Ref: https://docs.rke2.io/install/containerd_registry_configuration

What you probably want is:
```yaml
config:
  registry.ptinfra.com:30082:
    auth:
      username: "admin", 
      password: "xxxxxxx", 
mirrors:
  registry.ptinfra.com:30082:
    endpoint:
      - http://registry.ptinfra.com:30082
```
