### ISSUE TITLE
Uninstall process for calico cni is broken

### ISSUE THREAD

**Issue by ivansharamok** [rancher/rke2#7393]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.30.7+rke2r1 (fdbf8d58f402be2c83f8fd630d4e16203bbebc73)
go version go1.22.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux master1 6.8.0-1019-aws #21~22.04.1-Ubuntu SMP Thu Nov  7 17:33:30 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
The server was initialized with the following `/etc/rancher/rke2/config.yaml`:
```
cni: calico
disable:
  - rke2-ingress-nginx
kubernetes-helm:
  calico:
    valuesContent: |
      calicoctl:
        enabled: true
      calico:
        apiServer:
          enabled: true
```

When switching from managed cni (i.e. cni: calico) to unmanaged cni (i.e. cni: none), there are several jobs that get kicked off to clean up Calico related resources, such as: `tigera-operator-uninstall-*`, `helm-uninstall-rke2-calico-*`. The `tigera-operator-uninstall-*` job errors out and blocks removal of other calico related resources. The log has this output:
```
2024/12/10 01:21:22 [INFO] Version: v1.36.0
2024/12/10 01:21:22 [INFO] Go Version: go1.22.8 X:boringcrypto
2024/12/10 01:21:22 [INFO] Go OS/Arch: linux/amd64
2024/12/10 01:21:22 [INFO] preDelete hook exiting
2024/12/10 01:21:22 [ERROR] no matches for kind "APIServer" in version "operator.tigera.io/v1"Failed to complete pre-delete hook
```

**Steps To Reproduce:**

- Installed RKE2: 

```
sudo mkdir -p /etc/rancher/rke2
echo "cni: calico" | sudo tee /etc/rancher/rke2/config.yaml
sudo sed -i '$a disable\:\n  - rke2-ingress-nginx' /etc/rancher/rke2/config.yaml
sudo sed -i '$a kubernetes-helm:\n  calico:\n    valuesContent: |\n      calicoctl:\n        enabled: true\n      calico:\n        apiServer:\n          enabled: true' /etc/rancher/rke2/config.yaml
curl -sfL https://get.rke2.io | sudo sh -
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
```

- once all components got installed, I edited `/etc/rancher/rke2/config.yaml` file and restarted the `rke2-server.service`

```
echo "cni: none" | sudo tee /etc/rancher/rke2/config.yaml
sudo sed -i '$a disable\:\n  - rke2-ingress-nginx' /etc/rancher/rke2/config.yaml
sudo systemctl stop rke2-server.service
sudo systemctl start rke2-server.service
```

- the change triggered `tigera-operator-uninstall-*`, `helm-uninstall-rke2-calico-*` jobs to run but the ``tigera-operator-uninstall-*` job could never complain as it was complaining about not being able to find the APIServer version.

**Expected behavior:**
The expected behavior is that all uninstall related jobs would succeed successfully and remove managed calico cni from the cluster.

**Actual behavior:**
The actual behavior is that the ``tigera-operator-uninstall-*` job errors out and keeps retrying by creating more of similar jobs.

**Additional context / logs:**
N/A

**Comment by brandond** [comment]
> When switching from managed cni (i.e. cni: calico) to unmanaged cni (i.e. cni: none), there are several jobs that get kicked

We do not support changing CNI on a running cluster. An odd or unwanted behavior caused by doing so is not something we will address. If it breaks, you get to keep both pieces.
