### ISSUE TITLE
Update Calico and Flannel images on Canal and on Flannel

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#7401]
- Update Canal chart with updated images for Flannel (`v0.26.1-build20241211`)  and Calico (`v3.29.1-build20241211`).
- Update Flannel chart with latest image `v0.26.1-build20241211`

**Comment by fmoral2** [comment]
validate 
https://github.com/rancher/rke2/issues/7402#issuecomment-2538719412
https://github.com/rancher/rke2/issues/7403#issuecomment-2538722106
