### ISSUE TITLE
Support image registry path rewriting in containerd

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#741]
Support the ability to configure containerd in RKE2 for remapping the organization segment of an image repository to a specific "namespace" within an image registry. "Namespace" in this case is not a kubernetes namespace. It refers to a "section" of an image registry that has separate ACLs and is distinguished by a path segment in the registry URL.

So, the containerd configuration should allow for a mapping like this:
```
"docker.io/rancher": "https://my-reg.com/rancher-prod"
```
This would, for example, cause containerd to pull `rancher/hardened-kubernetes:v1.19.7-rke2r1` from `my-reg.com/rancher-prod/hardened-kubernetes:v1.19.7-rke2r1`. 

The supporting use case for this is when a single corporate registry serves multiple environments such as dev, test, staging, and prod. Each environment has its own namespace within the registry and the credentials configured for an environment can ONLY pull for its corresponding registry namespace. So, returning to our example, the RKE2 cluster for `prod` would have credentials that could ONLY pull from `https://my-reg.com/reancher-prod`.

We will need to extend this support to RKE2's pulling of the runtime image, which is not done through containerd, it is done the a separate library.

This configuration should support authentication. They existing behavior in RKE2 for specifying credentials either at the containerd configuration layer (aka in registries.yaml) or at the Kubernetes layer as image pull secret should continue to work.

For development and testing, quay.io is presumably a registry that supports this type of namespacing and requires remapping by the container runtime.

This does not need backported to older versions of RKE2. It can land in just the 1.20+ release train.

### Additional considerations
This is a feature that we will have to implement at the containerd/cri level. We do not want to maintain a fork of containerd for features in the long term. So, we'll have to work with upstream to see if they'll accept this as a feature. We have to reach out to the containerd team to see if they'd be willing to accept this work. If they aren't we need to take that back to @cloudnautique and figure out a more sustainable way forward.

**Comment by cjellick** [comment]
@cloudnautique I'd like you to "sign off" on the above description to ensure it captures everything that you are asking for.

**Comment by dweomer** [comment]
Based on this mostly working configuration https://github.com/containerd/containerd/issues/4358#issue-650141877 this may be easier than I had initially thought. What's more, if customers are fine forgoing the repo org re-write but instead leverage a top-level path, i.e. `docker.io/rancher` :arrow_right: `my-reg.com/rancher-prod/rancher` there may be no work to do (I need to test such a setup but indications are that it works).

**Comment by brandond** [comment]
@dweomer let me know when you figure out if/how this is supposed to work for containerd and I'll make sure it works with the go-containerregistry stuff for bootstrap.

**Comment by cjellick** [comment]
> What's more, if customers are fine forgoing the repo org re-write but instead leverage a top-level path, i.e. docker.io/rancher ➡️ my-reg.com/rancher-prod/rancher there may be no work to do (I need to test such a setup but indications are that it works).

I need @cloudnautique's input here. I think the requirement is to support a registry that cannot support two levels of netsing like that.

**Comment by cloudnautique** [comment]
@cjellick the initial write up lines up with the requirements, thanks.

@dweomer, a rewrite is needed vs. the prepend.

**Comment by cjellick** [comment]
Thanks @cloudnautique

**Comment by Martin-Weiss** [comment]
Just wanted to add some additional thoughts to the picture ;-)..

In case we can allow a mapping with registries.yaml for all external registries and pointing to different "paths/namespaces" on an internal registry (in a form like i.e. quay.io/x/y/ to on-premise-registry.local/abc/def/ - with or without wildcards) and if we can specify the "cluster registry access credentials" for the cluster to access the registry also in there (already possible) - we can keep the original image names and paths in all deployments / helm charts and do not even have to specify any registry credentials in Kubernetes.. This would eliminate the need for a "system-default-registry" to be specified.. 
Overriding the "default registry credentials" for a given namespace or deployment should still be possible with adding additional registry-credentials in Kubernetes and use them for a given deployment..

So beside registry mapping also registry path/namespace mapping would be a great value..

**Comment by dweomer** [comment]
@brandond my initial implementation https://github.com/containerd/containerd/pull/5171/files

**Comment by davidnuzik** [comment]
We initially planned for 1.20.6 but looks like this can make it in 1.20.5 so I have moved the milestone.

**Comment by rancher-max** [comment]
### Validated using v1.20.6-rc2+rke2r1


**Private Registry requiring authentication, using Namespaced & rewritten Images**
- rke2-images in my registry:
```
$ curl -ku "fakeuser:fakepass" "https://my.registry.com/v2/_catalog"
{"repositories":["testing/maxtest/hardened-calico","testing/maxtest/hardened-coredns","testing/maxtest/hardened-etcd","testing/maxtest/hardened-flannel","testing/maxtest/hardened-k8s-metrics-server","testing/maxtest/hardened-kube-proxy","testing/maxtest/hardened-kubernetes","testing/maxtest/klipper-helm","testing/maxtest/nginx-ingress-controller","testing/maxtest/nginx-ingress-controller-defaultbackend","testing/maxtest/pause","testing/maxtest/rke2-runtime"]}
```
- Place the following at /etc/rancher/rke2/registries.yaml:
```yaml
---
mirrors:
  docker.io:
    endpoint:
      - "https://my.registry.com"
    rewrite:
      "^rancher/(.*)": "testing/maxtest/$1"
configs:
  "my.registry.com":
    auth:
      username: fakeuser
      password: fakepass
    tls:
      ca_file: /etc/docker/certs.d/my.registry.com/ca.crt
```
- start rke2:
```
$ sudo rke2 server --write-kubeconfig-mode 644 2>&1 &
WARN[0000] not running in CIS mode                      
INFO[0000] Using registry config file at /etc/rancher/rke2/registries.yaml 
INFO[0000] Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.20.6-rc2-rke2r1 
INFO[0000] Extracting file charts/rke2-canal.yaml to /var/lib/rancher/rke2/data/v1.20.6-rc2-rke2r1-0e6e7ec3ff7c/charts/rke2-canal.yaml
...
$ kubectl get nodes,pods -A -o wide
NAME                    STATUS   ROLES                       AGE     VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-123-45-67-890   Ready    control-plane,etcd,master   4m18s   v1.20.6-rc2+rke2r1   123.45.67.890   <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   containerd://1.4.4-k3s1

NAMESPACE     NAME                                                     READY   STATUS      RESTARTS   AGE     IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   pod/etcd-ip-123-45-67-890                                1/1     Running     0          3m2s    123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/helm-install-rke2-canal-bzt9t                        0/1     Completed   0          3m44s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-bzkfp                      0/1     Completed   0          3m44s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-6tf27                0/1     Completed   0          3m44s   10.42.0.2       ip-123-45-67-890   <none>           <none>
kube-system   pod/helm-install-rke2-kube-proxy-rg7ws                   0/1     Completed   0          3m44s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-98vxq               0/1     Completed   0          3m44s   10.42.0.3       ip-123-45-67-890   <none>           <none>
kube-system   pod/kube-apiserver-ip-123-45-67-890                      1/1     Running     0          3m59s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/kube-controller-manager-ip-123-45-67-890             1/1     Running     0          3m59s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/kube-proxy-88gsd                                     1/1     Running     0          3m17s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/kube-scheduler-ip-123-45-67-890                      1/1     Running     0          3m59s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/rke2-canal-xjccd                                     2/2     Running     0          3m25s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-9d9bf756f-tb7p5            1/1     Running     0          3m17s   10.42.0.4       ip-123-45-67-890   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-54946dd48f-fx69t       1/1     Running     0          2m53s   123.45.67.890   ip-123-45-67-890   <none>           <none>
kube-system   pod/rke2-ingress-nginx-default-backend-5795954f8-788mw   1/1     Running     0          2m53s   10.42.0.6       ip-123-45-67-890   <none>           <none>
kube-system   pod/rke2-metrics-server-559dc47bd8-kwgdd                 1/1     Running     0          2m54s   10.42.0.5       ip-123-45-67-890   <none>           <none>
```

**Pull through private registry with TLS but no auth, using registry prefix**
- Setup my private registry to be a pullthrough using a prefix, without auth but with TLS:
```
$ mkdir -p certs && openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -x509 -days 365 -out certs/domain.crt -subj "/C=US/ST=AZ/O=Rancher QA/CN=my.otherregistry.com" -addext "subjectAltName = DNS:my.otherregistry.com"

$ sudo docker run -d --restart=always --name registry -v "$(pwd)"/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io -e REGISTRY_HTTP_PREFIX=/testing/ -p 443:443 registry:2.7.1
```

- Copied rke2 binary, domain.crt, and domain.key to airgapped node not running the registry, and ensured the cert was trusted by the OS: `$ sudo cp domain.crt /usr/local/share/ca-certificates/ && sudo update-ca-certificates`

- Started rke2 successfully by using the following at /etc/rancher/rke2/registries.yaml:
```yaml
---
mirrors:
  docker.io:
    endpoint:
      - "https://my.otherregistry.com/testing/v2/"
configs:
  "my.otherregistry.com":
    tls:
      cert_file: /home/ubuntu/domain.crt
      key_file: /home/ubuntu/domain.key
```

```
$ kubectl get nodes,pods -A -o wide
NAME                    STATUS   ROLES                       AGE     VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
node/ip-109-87-65-432   Ready    control-plane,etcd,master   6m17s   v1.20.6-rc2+rke2r1   109.87.65.432   <none>        Ubuntu 18.04.3 LTS   4.15.0-1051-aws   containerd://1.4.4-k3s1

NAMESPACE     NAME                                                     READY   STATUS      RESTARTS   AGE     IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   pod/etcd-ip-109-87-65-432                                1/1     Running     0          5m1s    109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/helm-install-rke2-canal-78d5s                        0/1     Completed   0          5m31s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-9fh52                      0/1     Completed   0          5m31s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-m2szx                0/1     Completed   0          5m31s   10.42.0.3       ip-109-87-65-432   <none>           <none>
kube-system   pod/helm-install-rke2-kube-proxy-6tg99                   0/1     Completed   0          5m31s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-dz8bv               0/1     Completed   0          5m31s   10.42.0.4       ip-109-87-65-432   <none>           <none>
kube-system   pod/kube-apiserver-ip-109-87-65-432                      1/1     Running     0          5m45s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/kube-controller-manager-ip-109-87-65-432             1/1     Running     0          5m45s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/kube-proxy-w59ns                                     1/1     Running     0          5m17s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/kube-scheduler-ip-109-87-65-432                      1/1     Running     0          5m45s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/rke2-canal-rr7tf                                     2/2     Running     0          5m16s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-9d9bf756f-sr95p            1/1     Running     0          5m17s   10.42.0.2       ip-109-87-65-432   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-54946dd48f-tq4z4       1/1     Running     0          4m43s   109.87.65.432   ip-109-87-65-432   <none>           <none>
kube-system   pod/rke2-ingress-nginx-default-backend-5795954f8-lwt8l   1/1     Running     0          4m43s   10.42.0.5       ip-109-87-65-432   <none>           <none>
kube-system   pod/rke2-metrics-server-559dc47bd8-k6nbw                 1/1     Running     0          4m41s   10.42.0.6       ip-109-87-65-432   <none>           <none>
```

**Ensured Installs without rewrites still continue to function properly**
