### ISSUE TITLE
Installation of rke2 v1.31 fails on Fedora 41

### ISSUE THREAD

**Issue by taotriad** [rancher/rke2#7429]
**Environmental Info:**
rke2 version v1.31.3+rke2r1 (f1db1f8266ab7315ff447c8acdaefa2ba16b87c0)
go version go1.22.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux fedora 6.11.11-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec  5 18:38:25 UTC 2024 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
Running the installation script fails due to dependency errors.

**Steps To Reproduce:**
Download and run install.sh on a Fedora 41 system.

**Expected behavior:**
Installation should complete successfully.

**Actual behavior:**
Installation fails.

**Additional context / logs:**
Modifying the baseurls in `/etc/yum.repos.d/rancher-rke2.repo` to point to centos/8 instead of centos/7 makes things work properly.

**Comment by brandond** [comment]
We don't support Fedora. You can find the list of supported distros at https://www.suse.com/suse-rke2/support-matrix/all-supported-versions/rke2-v1-31/

**Comment by taotriad** [comment]
From the installer:

`# set default distro to centos 7, for edge cases such as fedora`

Set that default to centos 8 instead of 7 and you'll fix installation (or better yet, provide a means to override it manually).
