### ISSUE TITLE
vxlan missing after Upgrade

### ISSUE THREAD

**Issue by SystemSpam** [rancher/rke2#7437]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.15+rke2r1 (96bb2a62fad8cb938a1761286b1d896623ac7014)
go version go1.22.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
X64 virtual Machines with RHEL9

Cluster Configuration:
1 rancher, 3 Linux Nodes Full, 3 Linux Nodes as Worker only, 3 Windows Nodes

**Describe the bug:**
On one Node with all Roles (etcd, Control Pane, Worker) the Network "Device" vxlan is missing.
The two other Nodes have the Network-Device.
All 3 Nodes have the Error in the Cluster Management "Calico is shutting down on this node:Resource is Ready"

The "Worker only" Nodes are not involved 

**Steps To Reproduce:**
I changed the Version in Rancher-Frontend at :
Cluster Management -> Choose cluster Menu "..." - > Edit Config -> Set Kubernetes Version to v1,28.15+rke2r1 (current)

I found some manuals about my problem, but I can't solve my Problem.

Every kubectl command I tried on the Node (with missing vxlan) answers with 
```
~]# kubectl get pods -A
E1217 10:18:18.063497   93377 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1217 10:18:18.064516   93377 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1217 10:18:18.065765   93377 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1217 10:18:18.066774   93377 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1217 10:18:18.067661   93377 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
of corse, bacouse the Network looks like
```
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever
2: ens192    inet 10.150.106.21/16 brd 10.150.255.255 scope global noprefixroute ens192\       valid_lft forever preferred_lft forever
3: cali6eaac1c9aed    inet6 fe80::ecee:eeff:feee:eeee/64 scope link \       valid_lft forever preferred_lft forever
4: calia857b68f030    inet6 fe80::ecee:eeff:feee:eeee/64 scope link \       valid_lft forever preferred_lft forever
5: cali26513aa7106    inet6 fe80::ecee:eeff:feee:eeee/64 scope link \       valid_lft forever preferred_lft forever
6: calibabdec4ee52    inet6 fe80::ecee:eeff:feee:eeee/64 scope link \       valid_lft forever preferred_lft forever
```

What are available steps to get back these setting (copied from anpther node as example)
```
...
16: vxlan.calico    inet 10.42.209.0/32 scope global vxlan.calico\       valid_lft forever preferred_lft forever
16: vxlan.calico    inet6 fe80::64c9:f9ff:fe9a:9b53/64 scope link \       valid_lft forever preferred_lft forever
...

```

Best regards
Robert

**Comment by rbrtbnfgl** [comment]
Is the calico pod failing on the nodes? Could you check the logs for the pods on the nodes where the vxlan is missing?
