### ISSUE TITLE
Kube-proxy 1.31.3 on ubuntu linux kernel 5.15.0-127-generic fails

### ISSUE THREAD

**Issue by erichevers** [rancher/rke2#7438]
After upgrading the OS today to the latest version and also upgraded RKE2 to 1.31.3 the kube-proxy pods keep crashing.
Downgrading the linux kernerl to 5.15.0.124 fixed the issue and another node with 5.15.0.126 didn't have the issue, so it seems like it is 5.15.0-127 specific

uname -srn
Linux nl1k8s097 5.15.0-127-generic

kube-proxy logs:
E1217 15:37:53.421766       1 proxier.go:734] "Error cleaning up nftables rules" err="could not find nftables binary: exec: \"nft\": executable file not found in $PATH"
E1217 15:37:53.421828       1 proxier.go:734] "Error cleaning up nftables rules" err="could not find nftables binary: exec: \"nft\": executable file not found in $PATH"
I1217 15:37:53.435690       1 server.go:677] "Successfully retrieved node IP(s)" IPs=["192.168.12.94"]
E1217 15:37:53.435974       1 server.go:234] "Kube-proxy configuration may be incomplete or incorrect" err="nodePortAddresses is unset; NodePort connections will be accepted on all local IPs. Consider using `--nodeport-addresses primary`"
I1217 15:37:53.470747       1 server.go:243] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
I1217 15:37:53.470947       1 server_linux.go:169] "Using iptables Proxier"
I1217 15:37:53.472139       1 proxier.go:255] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses" ipFamily="IPv4"
I1217 15:37:53.472589       1 server.go:483] "Version info" version="v1.31.3+rke2r1"
I1217 15:37:53.472613       1 server.go:485] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I1217 15:37:53.473836       1 config.go:199] "Starting service config controller"
I1217 15:37:53.473869       1 shared_informer.go:313] Waiting for caches to sync for service config
I1217 15:37:53.473973       1 config.go:105] "Starting endpoint slice config controller"
I1217 15:37:53.473985       1 shared_informer.go:313] Waiting for caches to sync for endpoint slice config
I1217 15:37:53.474419       1 config.go:328] "Starting node config controller"
I1217 15:37:53.474431       1 shared_informer.go:313] Waiting for caches to sync for node config
I1217 15:37:53.574315       1 shared_informer.go:320] Caches are synced for endpoint slice config
I1217 15:37:53.574480       1 shared_informer.go:320] Caches are synced for node config
I1217 15:37:53.574362       1 shared_informer.go:320] Caches are synced for service config
E1217 15:37:53.709945       1 proxier.go:1564] "Failed to execute iptables-restore" err=<
        exit status 2: Warning: Extension MARK revision 0 not supported, missing kernel module?
        ip6tables-restore v1.8.9 (nf_tables): unknown option "--xor-mark"
        Error occurred at line: 17
        Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
 > ipFamily="IPv6"
I1217 15:37:53.710050       1 proxier.go:833] "Sync failed" ipFamily="IPv6" retryingTime="30s"
E1217 15:38:23.765125       1 proxier.go:1564] "Failed to execute iptables-restore" err=<
        exit status 2: Warning: Extension MARK revision 0 not supported, missing kernel module?
        ip6tables-restore v1.8.9 (nf_tables): unknown option "--xor-mark"
        Error occurred at line: 17
        Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
 > ipFamily="IPv6"
I1217 15:38:23.765155       1 proxier.go:833] "Sync failed" ipFamily="IPv6" retryingTime="30s"

**Comment by ppomes** [comment]
Same issue for me.

**Comment by phuongvanle** [comment]
Same issue for me. 5.15.0-127-generic v1.30.6-rke2r1-build20241023

**Comment by brandond** [comment]
Kernel bug, see discussion at: https://github.com/k3s-io/k3s/issues/11175#issuecomment-2439630077

Upgrade or downgrade your kernel.

**Comment by paulrobu** [comment]
FYI, the kernel bug was fixed in the Linux package 5.15.0-130.140 released few hours ago, see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2091990

**Comment by erichevers** [comment]
Thanks for the quick fix. I've installed the 5.15.0-130.140 kernel on the DR k8s cluster nodes and can confirm this fixed the kube-proxy issue

**Comment by ColeSu-n** [comment]
Linux 5.15.0-127-generic x86_64

kube-proxy version: 1.26.0

同样也提示了ip6tables-restore v1.8.9 (nf_tables): unknown option "--xor-mark"
I want to know what version of my kernel needs to be downgraded. I encountered the problem that nodeport could not be used across nodes due to tx-checksum being turned on before, so I upgraded the kernel version.😂

**Comment by klauserber** [comment]
In my case I cannot confirm that 5.15.0-130 kernel completely solve the problem. I use Ubuntu 22.04 and have 5.15.0-130-generic installed. The kube-proxy do not crash anymore and all Services are working fine. But I cannot create new Services. I get this message:

```
fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Service hello-app2: Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Service \\\\\"hello-app2\\\\\" is invalid: spec.clusterIPs: Invalid value: []string{\\\\\"10.43.247.21\\\\\"}: failed to allocate IP 10.43.247.21: the provided IP (10.43.247.21) is not in the valid range. The range of valid IPs is 10.96.0.0/12\",\"reason\":\"Invalid\",\"details\":{\"name\":\"hello-app2\",\"kind\":\"Service\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: []string{\\\\\"10.43.247.21\\\\\"}: failed to allocate IP 10.43.247.21: the provided IP (10.43.247.21) is not in the valid range. The range of valid IPs is 10.96.0.0/12\",\"field\":\"spec.clusterIPs\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```
Switching back to an older kernel (e. g. 5.15.0-124-generic) solves this problem.

RKE2 version: v1.29.2+rke2r1

**Comment by domq** [comment]
This bug is present in Ubuntu Noble's 6.8.0-56-generic kernel.

**Comment by vnirocha** [comment]
I can confirm that this bug still appears on 6.8.0-56 kernel version.

**Comment by brandond** [comment]
If you'd like to get that fixed, it would probably be more productive to go comment on the Ubuntu issue tracker, not here.
