### ISSUE TITLE
CONTAINERD_* variables

### ISSUE THREAD

**Issue by julienbiau** [rancher/rke2#7447]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.30.5+rke2r1 (0c83bc82315cd61664880d0b52a7e070e9fbd623)
go version go1.22.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux rke6 5.14.21-150500.55.73-default #1 SMP PREEMPT_DYNAMIC Tue Aug 6 15:51:33 UTC 2024 (a0ede6a) x86_64 x86_64 x86_64 GNU/Linux
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

Cluster Configuration:
2 servers (10.41.0.36 10.41.0.37) + 2 agents (10.41.0.40 10.41.0.41) (all have the same node configuration explained above) http access is done through an http_proxy on 10.41.0.22 ip

**Describe the bug:**
Following this documentation : https://docs.rke2.io/advanced#configuring-an-http-proxy 
Even if i configure on my server the /etc/default/rke2-server file to set the HTTP_* and CONTAINERD_HTTP_* variables, i can get access to internet in my container. Rke2 is taking care of the HTTP_* variable beacause i can download docker image. 

**Steps To Reproduce:**

- Installed RKE2: 
https://docs.rke2.io/install/methods => tarball method
config.yaml :
disable-cloud-controller: true
kube-proxy-arg:
  - "iptables-localhost-nodeports=false"

**Expected behavior:**
I am expecting the HTTP_PROXY, HTTPS_PROXY and NO_PROXY variables to be set in my environnement variable of my container. Is it a misunderstanding from me ?

**Actual behavior:**
Variables are not set and if i use a curl command it failed. Using the command with the "--proxy http://10.41.0.22:8888" argument in the same container works.

**Additional context / logs:**

/etc/default/rke2-server:
HTTP_PROXY=http://10.41.0.22:8888
HTTPS_PROXY=http://10.41.0.22:8888
NO_PROXY=127.0.0.0/8,10.0.0.0/8,cattle-system.svc,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
CONTAINERD_HTTP_PROXY=http://10.41.0.22:8888
CONTAINERD_HTTPS_PROXY=http://10.41.0.22:8888
CONTAINERD_NO_PROXY=127.0.0.0/8,10.0.0.0/8,cattle-system.svc,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

I use curl command on an NGINX:ALPINE docker image.

**Comment by brandond** [comment]
That is not what the containerd env vars do. It only sets them for containerd, not for containers running in containerd.

There is no way to pass env vars from the host into containers. The only env vars in your containers will be those configured in your pod spec. You could look at using something like https://github.com/redhat-cop/podpreset-webhoo to inject them.

**Comment by julienbiau** [comment]
Thanks for the precision.
