### ISSUE TITLE
Spike: Windows Support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#747]
We may consider adding limited Windows support for agents (workers). The discussion is just starting and it will be necessary to research our options for potential limited Windows support.

**Comment by davidnuzik** [comment]
Closing. Complete.

**Comment by miketzian** [comment]
@davidnuzik - what was the outcome ?

**Comment by hazim1093** [comment]
@davidnuzik I would like to know about the outcome as well.  Wondering if we can use RKE2 for a hybrid setup with windows nodes as well or should we stick with RKE1 for now

**Comment by davidnuzik** [comment]
Windows support is being looked into at this stage. It's very early in development and we won't be formally supporting something until _possibly_ later this year (no promises). We anticipate RKE2 will be able to support agent nodes running on Windows. This would come out as experimental support initially (not to be used in production) and _perhaps_ later this year that support goes GA.

I don't have enough information at this time to give any better estimations. And I cannot promise on any of the above.
RKE1 (rancher/rke) isn't going anywhere any time soon - it will be around for quite a while. You could stick with RKE for now if you want @hazim1093 -- at a later time (_probably_ this year) we'll have a migration tool to move from RKE to RKE2. HOWEVER, I can't say at this time if it will support migrating windows nodes... These are still early days for Windows support.
The best suggestion I can offer at this point in time is to use RKE for now.
