### ISSUE TITLE
RKE2 kube-proxy should be a static pod, same as the other components

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#751]
We initially decided to deploy kube-proxy as a Helm Chart version of the Daemonset that kubeadm deploys. This mostly works fine, but has been the root cause for a growing list of issues:

https://github.com/rancher/rke2/issues/535#issuecomment-809580303 (data-dir needs to be the same across all nodes in the cluster)
#573 (kube-proxy daemonset pods aren't restarted when RKE2 agent changes on-disk config)
#645 (kube-proxy helm chart template error)
#678 (kube-proxy-args CLI flag is silently ignored)
#1080 (kube-proxy sysctls/module params cannot be set on docker, and cannot be overridden by supervisor code)

For better alignment with the deployment model that we use for the rest of the components, we should deploy kube-proxy as a static pod. This would allow users to use kube-proxy-args to alter configuration, and would resolve issues with the daemonset pods relying on config files that may be modified on RKE2 startup.

https://github.com/rancher/rke2/blob/master/pkg/podexecutor/staticpod.go#L81

**Comment by davidnuzik** [comment]
Blocking EIO team, to be worked on immediately after v1.21.1+rke2r1 release is done.

**Comment by brandond** [comment]
Tracking this in epic #1190
