### ISSUE TITLE
Support loading runtime image from compressed tarball

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#755]
We currently publish gzip-compressed tarballs in the release artifacts, but require the user to gunzip them before starting RKE2. Since the K3s image loading code already supports decompression, the RKE2 runtime bootstrap should support it too.

Publishing with a more advanced compression alg such as zstandard would also be nice.

**Comment by rancher-max** [comment]
I validated this in multiple airgap setups in v1.20.4-rc3 with the compressed tarballs from the release artifacts: gz, zst, and unpacking them to just a tar.
