### ISSUE TITLE
Install script needs to reload systemd if creating /usr/local/lib/systemd for the first time.

### ISSUE THREAD

**Issue by oskapt** [rancher/rke2#756]
Ubuntu 18.04 doesn't have `/usr/local/lib/systemd` by default, so when the RKE2 installer untars everything into `/usr/local` the service unit isn't picked up by systemd until after running `systemctl daemon-reload`.

If the script can run a check prior to install and set a flag if `tar` is going to create that directory, then it can fire off `daemon-reload`. Without it, the install docs don't actually work until the user figures it out and runs it themselves.

**Comment by caroline-suse-rancher** [comment]
Closing this due to age
