### ISSUE TITLE
system-default-registry with registry/namaspace causes startup failure with error "must be valid RFC 3986 URI authorities"

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#768]
Version v1.20.4+rke2r1

when using system-default-registry: registry.domain.local/rke-prod/docker.io the new released version of rke2-server fails to start with this error:

`
level=fatal msg="failed to parse system-default-registry: registries must be valid RFC 3986 URI authorities: registry.domain.local/rke-prod/docker.io"`

With the previous version  v1.19.7+rke2r1 this was working well.

-> could we adjust this check so that it allows "namespaced registries", again?

**Comment by brandond** [comment]
We did not ever intend to support namespace rewriting/prefixing with the system-default-registry feature; it was was only ever intended to accept a host:port, in line with containerd's support for registry endpoint overrides.

As of v1.20, RKE2 will honor the registries.yaml settings end-to-end, including the ability to configure authentication, certificates, etc. Previously it did not honor these settings when pulling the runtime image at startup.

Eventually we will add support for namespace rewriting/prefixing, but this needs to be supported in containerd first. The tracking issue for this is #741.

**Comment by Martin-Weiss** [comment]
Strange that it was working well in rke2 as also in rancher.. so for our deployments this change is basically a blocker, now.

When do you expect that we get namespace rewriting fixed / solved?

Am 11.03.2021 um 19:36 schrieb Brad Davidson ***@***.***>:

﻿

We did not ever intend to support namespace rewriting/prefixing with the system-default-registry feature; it was was only ever intended to accept a host:port, in line with containerd's support for registry endpoint overrides.

As of v1.20, RKE2 will honor the registries.yaml settings end-to-end, including the ability to configure authentication, certificates, etc. Previously it did not honor these settings when pulling the runtime image at startup.

Eventually we will add support for namespace rewriting/prefixing, but this needs to be supported in containerd first. The tracking issue for this is #741<https://github.com/rancher/rke2/issues/741>.

**Comment by brandond** [comment]
I believe the milestone on the linked issue should have a date associated with it.

**Comment by Martin-Weiss** [comment]
Just ran into one more issue with this "missing registry namespace mapping". During the upgrade of 1.19 to 1.20 using the tarball method - the images are not present on all other nodes in the cluster and pulling from namespaced registry does not work.. so i.e. helm-install-rke2 for canal etc. get stuck in ImagePullBackOff on "master-03" when upgrading "master-01"..

Or do we want to upgrade all masters at the same point in time?

**Comment by brandond** [comment]
In the case of a rolling upgrade (such as would be performed by the system upgrade controller), that issue should be temporary, and will resolve itself automatically once all nodes have been upgraded.

**Comment by Martin-Weiss** [comment]
> 
> 
> In the case of a rolling upgrade (such as would be performed by the system upgrade controller), that issue should be temporary, and will resolve itself automatically once all nodes have been upgraded.

Sure - but what if the rolling upgrade has an issue with one or the other machine or pod and gets stopped for a longer time?
(basically after each node upgrade you need to verify the "health ok" before going to the next machine - and if pods are in imagepull problems - IMO the operator should stop..)

So far I did not try out the system upgrade controller - just to be sure to be sure
 - the system upgrade controller will also work with namespaced registry mappings
 - in airgap scenarios with registry authentication 
 - will also update the local rke2 binary and other files from the tarball (or RPM)
 - adjust the config.yaml and other config files as needed
 - and all of this works on SLES 15 SP2 ?

**Comment by rancher-max** [comment]
Should be resolved per the same validations from https://github.com/rancher/rke2/issues/741#issuecomment-824252661
