### ISSUE TITLE
Can we merge the rke2-server and rke2-agent into one service and change "identity" with a parameter in the config.yaml?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#769]
During deployment it would be very nice if we could adjust the identity of a node with a setting in config.yaml instead of starting rke2-server or rke2-agent.. 

What do you think about such an enhancement for simplification?

**Comment by brandond** [comment]
We recently talked about making node roles a first-class concept, so that you only ever ran a single command - `rke2 node` for example. agent, control-plane, etcd would be roles selected via configuration, so that you could switch a node between server and agent behaviors based on configuration.

This was decided against, however. RKE2 and K3s will retain the CLI UX of dedicated server and agent entrypoints.

**Comment by Martin-Weiss** [comment]
Any idea what the reason for the decision for keeping two different services was?

Am 11.03.2021 um 18:55 schrieb Brad Davidson ***@***.***>:

﻿

We recently talked about making node roles a first-class concept, so that you only ever ran a single command - rke2 node for example. agent, control-plane, etcd would be roles selected via configuration, so that you could switch a node between server and agent behaviors based on configuration.

This was decided against, however. RKE2 and K3s will retain the CLI UX of dedicated server and agent entrypoints.

**Comment by brandond** [comment]
It was felt that it better encapsulated the two behaviors. This is why we also have different agent and server RPMs and systemd units, for example.

**Comment by Martin-Weiss** [comment]
As it is the same binary anyway I believe from a testing, maintenance and usage point of view going with a parameter in the config file or commandline would still be the better way - not sure what the added value of „encapsulated“ is - but I might just not be deep enough in the product ;-).

Am 11.03.2021 um 19:20 schrieb Brad Davidson ***@***.***>:

﻿

It was felt that it better encapsulated the two behaviors. This is why we also have different agent and server RPMs and systemd units, for example.
