### ISSUE TITLE
Install rke2 using commit id is broken

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#77]
Version:
Rke v0.0.1-alpha.7

Describe the bug:
Install rke2 using commit id.

INSTALL_RKE2_COMMIT=<Commit id> ./install.sh

```
# INSTALL_RKE2_COMMIT=4ccaa37d20b38e7d95a1ccd577894d4689b36a84 ./install.sh
[INFO]  using commit 4ccaa37d20b38e7d95a1ccd577894d4689b36a84 as release
[INFO]  downloading hash https://storage.googleapis.com/rke2-ci-builds/rke2-4ccaa37d20b38e7d95a1ccd577894d4689b36a84.sha256sum
# 
```

**Comment by briandowns** [comment]
This overall feature not working is captured in #62 . However since this ticket describes behavior preceding the actual use of the feature, we should update the title to describe the issue and I'll submit a PR shortly.

**Comment by davidnuzik** [comment]
Workaround for using commit id is to leverage git and make for now.

**Comment by briandowns** [comment]
This is captured in #62 . Does this ticket describe different behavior?

**Comment by davidnuzik** [comment]
It looks like a dupe to me.

**Comment by ShylajaDevadiga** [comment]
Oops yes. Closing issue

**Comment by davidnuzik** [comment]
Briefly reopening just to test something in zube / with zubebot.
