### ISSUE TITLE
systemctl restart rke2-server causes kubelet to restart forever 

### ISSUE THREAD

**Issue by Quantas** [rancher/rke2#782]
I just setup a testing cluster using RKE2 on friday, and I noticed a server systemctl service had been restarted for some reason or another, and in the events log in kubernetes, it keeps repeating that the kubelet has been restarted on that node until I eventually just reboot the server, then it comes up normally.  Is this expected? Anyone else notice this? Are there some logs you would like me to obtain? Thanks!

**Comment by Quantas** [comment]
Just a note, it is a 6 node cluster on CentOS 7, 3 are server and 3 are agent, using round robin DNS for the cluster url.

**Comment by brandond** [comment]
The journald logs from rke2-server or rke2-agent on the node in question would be a good start.

**Comment by Quantas** [comment]
Sounds good, I will grab those logs when I'm back at work on Monday. As an aside, I just tested a similar scenario at home with ubuntu without SELinux and didn't have any issues, my cluster at work has SELinux enabled. I will get those logs on Monday though :) Thanks!

**Comment by andrew-landsverk-win** [comment]
Here is what I've discovered, after doing `systemctl restart rke2-server` I get a message like the following:

> Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: F0315 08:00:52.262027    4635 server.go:162] listen tcp 0.0.0.0:10250: bind: address already in use
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: goroutine 859 [running]:
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/klog/v2.stacks(0xc0004c8d01, 0xc000290500, 0x64, 0x241)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/klog/v2.(*loggingT).output(0x6f76da0, 0xc000000003, 0x0, 0x0, 0xc000982310, 0x6e01433, 0x9, 0xa2, 0x410900)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/klog/v2.(*loggingT).printDepth(0x6f76da0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0003e5410, 0x1, 0x1)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/klog/v2.(*loggingT).print(...)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/klog/v2.Fatal(...)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/kubernetes/pkg/kubelet/server.ListenAndServeKubeletServer(0x5166fc0, 0xc000a09500, 0x5105240, 0xc0011a61c0, 0xc000c781a0, 0x10, 0x10, 0x280a, 0xc000806270, 0x50f64c0, ...)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/pkg/kubelet/server/server.go:162 +0x4fa
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).ListenAndServe(0xc000a09500, 0xc000c781a0, 0x10, 0x10, 0x280a, 0xc000806270, 0x50f64c0, 0xc000f72de0, 0xc001000100)
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/pkg/kubelet/kubelet.go:2222 +0xdb
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Mar 15 08:00:52 dev-rke2-master-1.dev.internal rke2[4618]: /go/src/kubernetes/cmd/kubelet/app/server.go:1187 +0x226

This is followed by a never ending stack trace in go. The only solution I have at that point is to restart the server entirely. I do not witness this behavior on Ubuntu, but I do on CentOS 7.

**Comment by brandond** [comment]
It's pretty difficult to tell what's going on from just a couple lines of the log as it's crashing. Can you grab the entire log (`journalctl -u rke2-server &>rke2-server.log`) and attach it to this issue?

**Comment by andrew-landsverk-win** [comment]
I have restarted the service and attached the log. Thanks!

[rke2-server.log](https://github.com/rancher/rke2/files/6143408/rke2-server.log)

**Comment by brandond** [comment]
RKE2 starts the kubelet as a child process, which should be terminated when the service is stopped or restarted. It looks like for some reason the kubelet on your node isn't getting terminated, so the old process is handing around and preventing the new kubelet from binding to the port:

```
Mar 15 12:44:07 dev-rke2-master-1.dev.internal rke2[22964]: F0315 12:44:07.293149   22983 server.go:162] listen tcp 0.0.0.0:10250: bind: address already in use
```

What Linux distribution are you running on this host? If you do `systemctl stop rke2-server` do you see a kubelet process still running?

**Comment by andrew-landsverk-win** [comment]
We are running on fully patched CentOS 7 (CentOS Linux release 7.9.2009 (Core)). 

- SELinux = Enforcing
- `systemctl stop rke2-server` still leaves kubelet process running. Here is the status output from systemd:

`
[root@dev-rke2-master-1 ~]# systemctl status rke2-server
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2021-03-15 13:15:43 CDT; 21s ago
     Docs: https://github.com/rancher/rke2#readme
  Process: 22964 ExecStart=/usr/bin/rke2 server (code=exited, status=1/FAILURE)
  Process: 22962 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 22960 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 22964 (code=exited, status=1/FAILURE)
    Tasks: 185
   Memory: 448.9M
`

**Comment by andrew-landsverk-win** [comment]
Thanks for the updates! :)

**Comment by rancher-max** [comment]
#### Validated on v1.20.5-rc1+rke2r1

- Restarting the server works successfully now
- This error does not happen on v1.19 or v1.18, so backports are not needed
- No panic produced, am able to use systemctl restart and systemctl stop followed by systemctl start both
- Cluster remains functional after restart completes

There is an error related to this when doing an upgrade via curl, so it has been called out separately: https://github.com/rancher/rke2/issues/828 
Note that upgrades via SUC still work correctly.
