### ISSUE TITLE
RKE2 Agent does not extract images with „system-default-registry“

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#784]
Agents try to download images from on-premise registry even though they are included in the images tar ball

```
# rke2 --version
rke2 version v1.20.4+rke2r1 (e0a5163fef9227fa6c19e5f597101d4939077793)
go version go1.15.8b5
```
In server and agent config.yaml:

`system-default-registry: registry.domain.de`

On servers `crictl images` shows this:

```
docker.io/rancher/pause                                           3.2                              e004ddc1b078f       686kB
registry.domain.de/rancher/pause                                     3.2                              e004ddc1b078f       686kB
docker.io/rancher/rke2-runtime                                    v1.20.4-rke2r1                   2f48f0df56b54       270MB
registry.domain.de/rancher/rke2-runtime                              v1.20.4-rke2r1                   2f48f0df56b54       270MB
registry.domain.de/rancher/hardened-kube-proxy                       v1.20.4-build20210302            fe40618686a2f       235MB
docker.io/rancher/hardened-kube-proxy                             v1.20.4-build20210302            fe40618686a2f       235MB
```

On agents `crictl images` shows this:

```
docker.io/rancher/pause                                           3.2                              e004ddc1b078f       686kB
docker.io/rancher/rke2-runtime                                    v1.20.4-rke2r1                   2f48f0df56b54       270MB
docker.io/rancher/hardened-kube-proxy                             v1.20.4-build20210302            fe40618686a2f       235MB
```

--> Due to that the agent tries to fetch the pause image registry.domain.de/rancher/pause:3.2 from the on premise registry which fails due to missing namespace mapping support.. 

Why do agents act different compared to servers for these images?
Is this a bug that can be fixed?

**Comment by brandond** [comment]
Yep, looks like this is a bug. As a workaround, until this is fixed, you should be able to add `airgap-extra-registry: registry.domain.de` to the config on the agent,

**Comment by Martin-Weiss** [comment]
> 
> 
> Yep, this looks like a bug.
> 
> As a workaround, until this is fixed, you should be able to add `airgap-extra-registry: registry.domain.de` to the config on the agent to get the images retagged properly.

Cool - thanks  - did not know that this parameter exists.. do you have some details about this parameter? I could not find it here.. https://docs.rke2.io/install/install_options/agent_config/

Our workaround for the moment was this:

`for img in $(crictl images |awk '{ print $1":"$2}' |grep -i docker.io); do ctr -a /run/k3s/containerd/containerd.sock -n k8s.io image tag $img $(echo $img|sed 's/^docker.io/registry.domain.de/g'); done`

**Comment by brandond** [comment]
That is a hidden flag inherited from K3s. It is intentionally undocumented. It does pretty much exactly what your shell script does - retags each image as it is loaded from the tarball.

**Comment by rancher-max** [comment]
#### Validated using commit id `a0665dfa8b47360a2a1c7e618e89cc3accfc512b`

On agent node, the images now show up:
```
$ sudo /var/lib/rancher/rke2/bin/crictl -r unix:///run/k3s/containerd/containerd.sock images
IMAGE                                                                TAG                              IMAGE ID            SIZE
docker.io/rancher/hardened-calico                                    v3.13.3-build20210223            736cae9d947ba       437MB
registry.domain.de/rancher/hardened-calico                           v3.13.3-build20210223            736cae9d947ba       437MB
...
```
Used simple config:
```
token: "secret"
system-default-registry: registry.domain.de
server: "https://<redacted>:9345"
```
