### ISSUE TITLE
Rancher rke2-cis-1.5-profile-permissive scan shows false failures on certificate permissions

### ISSUE THREAD

**Issue by bentastic27** [rancher/rke2#785]
I have found this being related to [1.1.20](https://docs.rke2.io/security/cis_self_assessment/#1120) and [4.1.7](https://docs.rke2.io/security/cis_self_assessment/#417). Both are calling for permissions being 644 or more restrictive, but if you set the perms to these you'll fail both:

```
# stat -c %n\ %a /var/lib/rancher/rke2/server/tls/*.crt
/var/lib/rancher/rke2/server/tls/client-admin.crt 644
/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt 644
/var/lib/rancher/rke2/server/tls/client-ca.crt 600
/var/lib/rancher/rke2/server/tls/client-cloud-controller.crt 644
/var/lib/rancher/rke2/server/tls/client-controller.crt 644
/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt 644
/var/lib/rancher/rke2/server/tls/client-kube-proxy.crt 644
/var/lib/rancher/rke2/server/tls/client-rke2-controller.crt 644
/var/lib/rancher/rke2/server/tls/client-scheduler.crt 644
/var/lib/rancher/rke2/server/tls/request-header-ca.crt 600
/var/lib/rancher/rke2/server/tls/server-ca.crt 600
/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt 644
```

However, setting these files with 600 perms back to 644 it passes. The calculation on the permissions seems to be incorrect.

gz#15644

**Comment by brandond** [comment]
I think @rancher-max had run into this as well?

The actual fixes need to go into a different repo:

https://github.com/rancher/security-scan/blob/master/package/cfg/rke2-cis-1.5-permissive/master.yaml#L305
https://github.com/rancher/security-scan/blob/master/package/cfg/rke2-cis-1.5-permissive/node.yaml#L170

**Comment by atsai1220** [comment]
As an additional note, agents fail on `4.1.7` for us because the file is not found. 

```
root@worker-0:/var/lib/rancher/rke2/server# stat -c %a /var/lib/rancher/rke2/server/tls/server-ca.crt
stat: cannot stat '/var/lib/rancher/rke2/server/tls/server-ca.crt': No such file or directory

atsai@worker-0:/var/lib/rancher/rke2/server$ ls
manifests
```

![Screen Shot 2021-03-16 at 9 04 30 AM](https://user-images.githubusercontent.com/14171643/111341380-b3554d00-8636-11eb-802d-87d190895b97.png)

**Comment by brandond** [comment]
The server checks shouldn't even run against an agent; does the test framework not handle that?

**Comment by fapatel1** [comment]
@briandowns to investigate further

**Comment by katran001** [comment]
@briandowns can I move this to the backlog or is it still under investigation?

**Comment by briandowns** [comment]
I believe this can be closed.
