### ISSUE TITLE
Active Directory based Authentication - Direct RKE2 kube API access

### ISSUE THREAD

**Issue by massep88** [rancher/rke2#792]
**What kind of request is this (question/bug/enhancement/feature request):**

This is a feature request.

**Description:**

We would like to directly access the RKE2 kube API with AD based authentication, without the need to deploy Rancher Server to act as an authentication proxy. In complement, this will enable us to setup RBAC using the existing AD configuration.

**Environment information**

- RKE2 : v1.19.7+rke2r1
- Installation option : HA 
- Infra : vSphere 6.7

**Comment by Martin-Weiss** [comment]
> I believe this is outside the scope of something we would bundle with RKE2. You should proably be looking at configuring an oauth2 provider backed by your AD domain:
> https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

I believe this what we can do with DEX + Gangway - true? 
So the question would be if we just could take what we have i.e. for CaaSP and use it on RKE2?

**Comment by massep88** [comment]
Yes agreed.
If a solution such as DEX + Gangway is pre-validated along RKE2 releases, then this feature request would be covered.
This request has been entered in the context of a complex migration of several hundreds of applications, all in production.
Everything that can simplify will help not only the move to RKE2 but also future operations.

**Comment by Martin-Weiss** [comment]
The other option might be to deploy and run rancher in each of these clusters. This would bring authentication and authorization, dashboard, monitoring etc.. the main challenge might be that "officially" running Rancher in a "workload cluster" is not supported.. but that is not much different to the DEX+Gangway solution that is also not supported officially at the moment..

**Comment by brandond** [comment]
Making the workload clusters Rancher downstream clusters (managed by a central Rancher instance) should get you what you're looking for, if you set up AD auth for Rancher. Can you clarify what you're saying about running Rancher in a workload cluster (what Rancher calls a downstream cluster) not being supported? Or were you suggesting running a full Rancher instance in each cluster?

**Comment by massep88** [comment]
=> Running a Rancher Server instance on downstream (managed) RKE2 cluster.
But, as Martin comments, I also understand that colocating Rancher and a downstream cluster is not recommended in production (or in other words "not supported").

**Comment by brandond** [comment]
No, thats why I was suggesting configuring them as downstream clusters. You would authenticate to AD by way of Rancher, and manage the downstream clusters via Rancher. Why would you install Rancher itself in the downstream clusters?

**Comment by massep88** [comment]
Ok so we are aligned.
This leads us back to the 2 options we have mentioned above :
- direct support in RKE2 
- or complementary components, such as Dex & Gangway, are pre-validated with RKE2

**Comment by brandond** [comment]
I don't understand what you mean by 'direct support'. Support for what, by what?

Any request to get new 3rd party components supported with RKE2 would need to go through product management.

**Comment by massep88** [comment]
I mean by "direct support" supporting the requested feature in a future release of RKE2.
Yes for sure : I have opened this ticket at product management request.

**Comment by brandond** [comment]
Kubernetes itself does not do AD or LDAP auth, so I'm not sure how we would even accommodate this ask in RKE2. You just need to pick an external auth provider to integrate into your cluster, whether that's Rancher or an oauth2 provider.

**Comment by massep88** [comment]
The request is not on Kubernetes but on RKE2 as a product. As you have mentioned, this is a request for product management.
For example, both Dex & Gangway were integrated in the past in CaaSP product.

For sure we could pick up an oauth2 provider and deploy our-selves on RKE2. But in this case, we would have to support it our-selves, managing patching and upgrades on this mission critical production environment. Something that, if possible, we would like to avoid.
About the use of a central Rancher Server : the good point is that support would be covered.
However we have not seen so far any other use in our environment than for AD AuthN.

Hence this feature request to have this delivered as a RKE2 product feature.

**Comment by brandond** [comment]
I'll defer to PM, but I don't think we're necessarily going to do anything just because CaaSP did it. The answer will probably be to just use Rancher.

**Comment by massep88** [comment]
Yes sure. Thank you very much @brandond

**Comment by massep88** [comment]
Hello @brandond 
Any feedbacks from PM ?
Thank you

**Comment by brandond** [comment]
I'm not the best person to represent this, perhaps @Martin-Weiss has brought it up?

**Comment by massep88** [comment]
I will directly follow up with PM. Github has been identified to me as the support channel to use for feature requests,
At the moment, we cannot use Rancher as central authentication proxy for RKE2 ( a feature I hope will be in Rancher 2.6).
