### ISSUE TITLE
Enhance install script to allow for installation using local tarball

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#795]
In order to support https://github.com/rancher/rancher/issues/31379 we need to enhance the install script to allow installation from a local tarball.

**Comment by rancher-max** [comment]
Validated this by copying artifacts to the node in a specific folder and then running the install with this variable pointed to that folder. Used both zst and gz, zst only, and gz only in three different installs on centos8 and ubuntu both. Also validated using this to join servers and agents to the initial node.
```
$ ls -l artifacts/
total 1392920
-rw-rw-r-- 1 ubuntu ubuntu 725923300 Apr  7 21:55 rke2-images.linux-amd64.tar.gz
-rw-rw-r-- 1 ubuntu ubuntu 504229972 Apr  7 21:55 rke2-images.linux-amd64.tar.zst
-rw-rw-r-- 1 ubuntu ubuntu       679 Apr  7 22:03 rke2-images.linux-amd64.txt
-rw-r--r-- 1 root   root   153383592 Apr  7 21:55 rke2.linux-amd64
-rw-r--r-- 1 root   root    42785534 Apr  7 21:55 rke2.linux-amd64.tar.gz
-rw-r--r-- 1 root   root         652 Apr  7 21:55 sha256sum-amd64.txt

$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_ARTIFACT_PATH=/home/ubuntu/artifacts sh -
[INFO]  staging local checksums from /home/ubuntu/artifacts/sha256sum-amd64.txt
[INFO]  staging zst airgap image tarball from /home/ubuntu/artifacts/rke2-images.linux-amd64.tar.zst
[INFO]  staging tarball from /home/ubuntu/artifacts/rke2.linux-amd64.tar.gz
[INFO]  verifying airgap tarball
grep: /tmp/rke2-install.KgkiyD8J6R/rke2-images.checksums: No such file or directory
[INFO]  installing airgap tarball to /var/lib/rancher/rke2/agent/images
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
```

Note this issue `grep: /tmp/rke2-install.KgkiyD8J6R/rke2-images.checksums: No such file or directory` that is not a blocker, but should be cleaned up at least in the output. Leaving this open to fix that.

**Comment by rancher-max** [comment]
Reopend (back in working) to address issue mentioned above

**Comment by davidnuzik** [comment]
@Oats87 there's no milestone for this... I put in v1.20.6

**Comment by davidnuzik** [comment]
@rancher-max could you create a new issue for the minor checksum issue?
Close this one then, and put that new issue in a 1.20.7 milestone assigned to Chris in Development project in Next up status.
Thanks :)
