### ISSUE TITLE
Error running CIS scan through rancher after upgrading rke2 version

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#798]
**Description:**
Running a CIS scan on an upgraded rke2 cluster in rancher fails to receive the results from worker nodes, and therefore the scan times out and shows a status of Error. Verified this error happens on both Centos8 and Ubuntu.

**Steps**

1. Deploy an rke2 cluster with 3 servers, 2 workers, and import to rancher (used v1.9.7+rke2r1)
2. Upgrade cluster through rancher to v1.19.8+rke2r1
3. Navigate to cluster dashboard, deploy CIS app from the marketplace, and run a scan

**Logs and Helpful Info:**
The scan never completes, even though the scan logs from all 5 running `sonobuoy-rancher-kube-bench-daemon-set` pods show it has completed: `level=info msg="Detected done file, transmitting result file" resultFile=/tmp/results/kb.tar.gz`. 

The `security-scan-runner-scan` pod shows that it never received an update from the worker pods:
```
time="2021-03-17T21:16:06Z" level=info msg="received aggregator request" client_cert=rancher-kube-bench node=server1 plugin_name=rancher-kube-bench
time="2021-03-17T21:16:06Z" level=info msg="received aggregator request" client_cert=rancher-kube-bench node=server2 plugin_name=rancher-kube-bench
time="2021-03-17T21:16:06Z" level=info msg="received aggregator request" client_cert=rancher-kube-bench node=server3 plugin_name=rancher-kube-bench
```

**Comment by brandond** [comment]
Is this in CIS mode? Wondering if we're battling network policy again.

**Comment by rancher-max** [comment]
Closing as this isn't relevant anymore
