### ISSUE TITLE
Remove two nodes will cause the master node fail when there are three server nodes

### ISSUE THREAD

**Issue by Jaorji** [rancher/rke2#812]
I have three server nodes, node1, node2 and node3

When I remove rke2 in node2 and node3, node1 will fail to connect API server 
`Mar 22 15:30:29 rke2-test-1 rke2[22077]: {"level":"warn","ts":"2021-03-22T15:30:29.077-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Mar 22 15:30:29 rke2-test-1 rke2[22077]: time="2021-03-22T15:30:29-04:00" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Mar 22 15:30:30 rke2-test-1 rke2[22077]: time="2021-03-22T15:30:30-04:00" level=info msg="Waiting for API server to become available"`
It keeps saying  " Waiting for API server to become available"

I don't have this issue when there are more than 3 server nodes

**Comment by brandond** [comment]
When you say removing two nodes, do you mean actually deleting two of them, or just stopping them? Keep in mind that you need to meet etcd quorum requirements, so in a 3 server cluster, at least 2 of the servers need to be up for etcd to function.

**Comment by Jaorji** [comment]
@brandond removing two nodes means uninstall rke2 in two nodes. Making a 3 server cluster into 1 server cluster

My purpose is to change 3 servers to only 1 server, so my step is :
1) install master node server - node1
2) install 2 additional master node- node2 and node3 join the same cluster with the master node server- node1
3) uninstall rke2 in node2 and node3

**Comment by brandond** [comment]
You can't just uninstall them, that will break cluster quorum because you'll be left with 1 of 3 nodes. If you're going to decommission them from the cluster, you should - ONE AT A TIME - delete the node from the cluster, stop the RKE2 service, then do what you will with the hosts.
