### ISSUE TITLE
Initial server URL host is not defined for load balancer

### ISSUE THREAD

**Issue by houshym** [rancher/rke2#813]
following https://docs.rke2.io/install/quickstart/ with 2 nodes ( 1 master and 1 worker). fresh install nodes. ubuntu 20.04. master works as expected but I am getting the following error on the agent
level=error msg="Remotedialer proxy error" error="dial tcp 10.0.2.15:9345: connect: connection refused"
10.0.2.15 is vagrant NAT adapter 

/etc/rancher/rke2/config.yaml is
server: https://192.168.10.100:9345
token: K1026.....

I tried the following command 
 rke2 agent --server 192.168.10.100 -c /etc/rancher/rke2/config.yaml
but I got following error

WARN[0000] not running in CIS 1.5 mode
INFO[0000] Runtime image "index.docker.io/rancher/rke2-runtime:v1.19.8-rke2r1" bin dir already exists at "/var/lib/rancher/rke2/data/v1.19.8-rke2r1-4c680a9974e2/bin"; skipping extract
INFO[0000] Starting rke2 agent v1.19.8+rke2r1 (77ad545580efc4ab64ce231d4a75fa2e493956a3)
INFO[0000] Module overlay was already loaded
INFO[0000] Module nf_conntrack was already loaded
INFO[0000] Module br_netfilter was already loaded
INFO[0000] Module iptable_nat was already loaded
WARN[0000] Error starting load balancer: Initial server URL host is not defined for load balancer
FATA[0000] Initial server URL host is not defined for load balancer

**Comment by brandond** [comment]
I have seen other reports of issues with Vagrant, due to it creating all the VMs with the same primary IP address (10.0.2.15).
