### ISSUE TITLE
Test and Certify SLES 15 SP1

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#815]
It's been requested to test SLES 15 SP1 as well on BOTH K3s and RKE2. We already previously tested SP2 but would like to include support for SP1 as well.

**Comment by davidnuzik** [comment]
Related to: https://github.com/rancher/rke2/issues/816

**Comment by davidnuzik** [comment]
Lower priority compared to all other issues to test in this milestone. These can be tested day after release even (if needed).

**Comment by ShylajaDevadiga** [comment]
Validated SLES 15 SP1 as per our support matrix on rke2 version v1.18.18, v1.19.10, v1.20.6

- Passed Conformance test
- Passed Functional test
- Passed upgrade using SUC
- Installation as management cluster and deploying rancher was successful
