### ISSUE TITLE
rke2 runtime image pull issues on Ubuntu 20.04

### ISSUE THREAD

**Issue by markthehipster** [rancher/rke2#819]
Hey there, 

So this is my second installation and the first one went totally fine, however I noticed the following issue: 
( I also created a third cluster, and I had the same issues there..)

Some precontext to all of this ; 
- We pre-build Ubuntu20.04 kvm images with docker installed
- these images have been stripped of `docker-ce`, `containerd.io`, `docker-ce-cli` via `apt purge` and manually installed `containerd` via `apt install` (pipeline wasnt changed yet for dockerless setup)
- rke2 was installed via an ansible playbook, it worked just fine on multiple re-installations of my test cluster.

```root@xxx-master1:~# systemctl status rke2-server.service 
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2021-03-26 13:09:48 UTC; 649ms ago
    Docs: https://github.com/rancher/rke2#readme
  Process: 10152 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 10160 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 10164 ExecStart=/usr/local/bin/rke2 server (code=exited, status=1/FAILURE)
  Main PID: 10164 (code=exited, status=1/FAILURE)
  ```
  
`  journalctl -u rke2-server`

```
Mar 26 12:36:18 xxx-master1 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 28.
Mar 26 12:36:18 xxx-master1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Mar 26 12:36:18 xxx-master1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Mar 26 12:36:18 xxx-master1 systemd[1]: Started Rancher Kubernetes Engine v2 (server).
Mar 26 12:36:19 xxx-master1 rke2[3219]: time="2021-03-26T12:36:19Z" level=warning msg="not running in CIS 1.5 mode"
Mar 26 12:36:19 xxx-master1 rke2[3219]: time="2021-03-26T12:36:19Z" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.20.4-rke2r1"
Mar 26 12:36:19 xxx-master1 rke2[3219]: time="2021-03-26T12:36:19Z" level=fatal msg="failed to get runtime image rancher/rke2-runtime:v1.20.4-rke2r1: .dockercfg: $HOME is not defined"
Mar 26 12:36:19 xxx-master1 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 12:36:19 xxx-master1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
```

^ this also happened on rke2-agent nodes
  
Solution was to run `rke2 server` or `rke2 agent` on masters/nodes so that it pulled the runtime image. 

`level=fatal msg="failed to get runtime image rancher/rke2-runtime:v1.20.4-rke2r1: .dockercfg: $HOME is not defined"`

My idea is that this happened because the `apt purge` of `docker` etc. but I'm also open to ideas on why could this be happening.

Thanks! 
Mark

**Comment by dweomer** [comment]
Hmm, it looks like the environment file for the unit is not being sourced. [This file](https://github.com/rancher/rke2/blob/master/bundle/lib/systemd/system/rke2-server.env) should be dropped in an appropriate location on your host during install and sourced from the service unit.

**Comment by markthehipster** [comment]
Ah damn, I completely forgot about that file, thank you so much @dweomer 
I'll go through my ansible script again and make sure it follows your rke2 install script properly.
