### ISSUE TITLE
Documentation for Cilium CNI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#827]
Related: https://github.com/rancher/rke2/issues/490

Add documentation entry for Cilium CNI to the https://github.com/rancher/rke2/blob/master/docs/install/network_options.md page.

**Comment by davidnuzik** [comment]
@manuelbuil @jcaamano I wasn't sure who to assign to this issue so I've assigned you both. We should work to get a PR in to update https://github.com/rancher/rke2/blob/master/docs/install/network_options.md to add Cilium CNI / chart details in.

**Comment by manuelbuil** [comment]
@davidnuzik the PR already exists ==> https://github.com/rancher/rke2/pull/691/files :)

**Comment by davidnuzik** [comment]
These are the PRs for charts we need to merge first: 
https://github.com/rancher/rke2-charts/pull/60
https://github.com/rancher/rke2-charts/pull/59

**Comment by davidnuzik** [comment]
The two rke2-charts PRs I mentioned in my last comment now have 2 LGTMs and I have merged them :)

**Comment by davidnuzik** [comment]
Documentation was reviewed and merged. Closing this issue out.
