### ISSUE TITLE
Rancher UI fails to load or loads slowly on Centos8 with selinux

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#833]
**Description:**
Rancher on Centos8 with selinux enforcing is not really functional. It IS functional on Centos7 with selinux enforcing. I believe the error is likely related to NetworkManager somehow since this appears on centos8 but not centos7, so possibly related to https://github.com/rancher/rke2/issues/798. 
With that said, technically rancher is no longer in a CrashLoopBackoff and isn’t reporting any real errors in its pod logs (meaning https://github.com/rancher/rke2/issues/690 is probably “resolved”), but again the rancher UI at least isn’t functional.
There are no rancher pod log errors.

This affects both v1.20.5-rc2+rke2r1 and v1.19.7-rc1+rke2r1. Used the default rancher version from rancher-latest helm chart, which right now is v2.5.7, but also verified this happens using v2.5.6 rancher.

**Steps to Reproduce:**
1. Bring up multinode server cluster on centos8 with selinux set to enforcing. Ensure TLS is setup for the cluster.
2. Install rancher using helm
3. After rancher reports that it is running, try to access the UI

Screenshot to show what it looks like after a long time of trying to load, and many refreshes.
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/55997940/113226889-21f4f600-9246-11eb-8d4c-669a7279ffca.png">

**Comment by rancher-max** [comment]
Confirmed when working with @Oats87 that this is very much relates to https://github.com/rancher/rke2/issues/786 as one of the nodes in an effected setup had the same networkmanager issue, and rebooting that node fixed these problems.

**Comment by bmdepesa** [comment]
We were not able to reproduce this so far with RKE1 and the following configurations:

Centos 8.2 + Docker 19.03 + SELinux (Docker & OS)
RHEL 8.2 + Docker 19.03 + SELinux (Docker & OS)

RKE1 local cluster (3 nodes all roles), k8s 1.20.4, Rancher Helm install v2.5.7, Canal CNI 

Rancher install / UI is working fine with no errors.
Downstream custom cluster provisioned with the same AMIs as local clusters -> CIS Scan passes

**Comment by rancher-max** [comment]
Closing as #786 covers this, and the workaround there fixes this issue.
