### ISSUE TITLE
Rancher Helm Chart installed Rancher UI not working in RKE2 built in AWS built using rke2-aws-tf Terraform project using the AWS cloud-enabled example

### ISSUE THREAD

**Issue by hectoralicea** [rancher/rke2#837]
I created an RKE2 cluster (v1.18.13+rke2r1) in AWS using this Terraform project (https://github.com/rancherfederal/rke2-aws-tf) using the cloud-enabled example for AWS.  The working terraform project was configured to build  3 autoscaling nodes and 1 server.

The RKE2 cluster appears to work just fine.  kubectl works great and  I’m able to deploy a highly customized Jenkins helm chart with no issues. ELB for service creates with no issues, etc.

Now I’m deploying the rancher helm chart into my RKE2 as follows:
```
helm upgrade rancher rancher-stable/rancher --install \
      --version v2.5.7 \
      --namespace cattle-system \
      --debug --wait --timeout 5m \
      --set hostname=rke-test.k8s.hla-associates.info \
      --set ingress.tls.source=rancher \
      --set ingress.enabled=true \
      --set tls=external
```

- Appears the built in ingress that rancher helm chart creates, terminates on port 80 of one of the VM nodes, rather than an AWS ALB.
- Appears the security group for the Node does not include port 80 or 443.
- I can reach port 22 and ssh in, but cannot reach ports 80 or 443, unless I manually add them.  Even when I do I get an 404 from the ingress.

Questions:

1. I would think that Rancher helm deploy to RKE2 on AWS would create an Ingress that would build up an AWS Load Balancer, rather than having to terminate at a Node VM.  What If I wanted to have ingress load balanced against more than 1 node. How would I get that to work that way?
2. I would think that Rancher should have added port 80 and 443 to the security group as part of provisioning the ingress.  How would get that to work that way?
3. Does RKE2 even support running the Rancher Management Console?

**Comment by brandond** [comment]
Yes, we definitely support running Rancher on RKE2. For the specific questions about the infra configured by the RFed TF project - those might best be asked on an issue on that project?

**Comment by hectoralicea** [comment]
> Yes, we definitely support running Rancher on RKE2. For specific questions about the infra configured by the RFed TF project - those might best be asked in an issue on that repo?

sounds good.  Will do that.  Thanks
