### ISSUE TITLE
Enable RKE2 built-in cloud provider if no cloud provider config is provided

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#839]
Request from @ibuildthecloud at https://rancher.slack.com/archives/CRF4B1J8H/p1616108701098200: 
> For the rke2 provisioning in rancher (using capi) I really need rke2 to set the providerID if no cloud provider is specified.  For k3s the providerID is always set to k3s://nodename, I need the same thing.

**Comment by rancher-max** [comment]
#### Validated on commitid `0a114cc67c3c8400ceed5e88699e99922f525e41` and v1.20.5+rke2r1

- All verification steps mentioned in the PR work. For "Verify that node external address is set when not using an in-tree cloud provider" this means that this should continue to set the external-ip when setting the `node-external-ip` flag. 
- Error still correctly occurs when trying to use `node-external-ip` with an in-tree cloud provider: `level=fatal msg="can't set node-external-ip while using cloud provider"`

Note this is actually present in v1.20.5 as well, so I made sure to back-validate there as well. Changing the milestone to reflect this.
