### ISSUE TITLE
[Documentation] CIS Hardening Guide

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#84]
Separated out from original issue https://github.com/rancher/rke2/issues/1

CIS Hardening is complete. Next step here is to create a guide with details.

**Comment by briandowns** [comment]
I believe we can use the current [Rancher 2.4 Hardening Guide](https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.4/?#) since it targets, describes, and provides guidance for CIS version 1.5.
