### ISSUE TITLE
Cut 1.21 (new minor) release

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#845]
Upstream: tbd

**Notice:**
Upstream plans to get the new minor release out by 4/8/2021. We will release by late April as it will take time to test the new minor version thoroughly with K3s and then RKE2. 
UPDATE: It is necessary for us to get additional work in to the 1.21 line for RKE2 in order to have a successful release. As such, we are going to forego a 1.21.0 release and opt for a 1.21.~1~2 release instead.

**Summary:**
Task covering release work.
Dev Complete: 6/11/2021

**List of required releases:**
_To release as soon as able for QA:_
- v1.21.2-rc1+rke2r1

_To release once have approval from QA:_
- v1.21.2+rke2r1 (Never release on a Friday unless specified otherwise)

**Prep work:**
- PM: Dev and QA team to be notified of the incoming releases - send calendar invite
- PM: Dev and QA team to be notified of the date we will mark the latest release as stable - send calendar invite
- QA: Review changes and understand testing efforts
- Release Captain KDM Work: Merge PR for rancher/kontainer-driver-metadata into the dev branches (we only need to update in 2.6 dev branch as only Rancher 2.6 will support 1.21.x)
- [x] Release Captain: Prepare release notes in our private release-notes repo (submit PR for changes taking care to carefully check links and the components, once merged, create the release in GitHub and mark as a draft and check the pre-release box, fill in title, set target release branch, leave tag version blank for now until we are ready to release)
- [x] PM: Create an issue to mark the latest release as stable (this is done typically not later than 1 days post release patch release, 7 days post new minor release) https://github.com/rancher/rke2/issues/846
- [x] QA: Validate and close out all issues in the release milestone.

**Vendor and release work:**
- [x] Release Captain: Tag and release any necessary RCs for QA to test KDM
- [x] Release Captain: Tag and release when have QA approval

**Post-Release work:**
- [x] Release Captain: Once release is fully complete (CI is all green and all release artifacts exist), edit the release, uncheck "Pre-release", and save.
~Release Captain: Prepare PRs as needed to update [KDM](https://github.com/rancher/kontainer-driver-metadata/) in the appropriate dev branches.~
- [x] PM: Close the milestone in GitHub.

**Comment by davidnuzik** [comment]
I've updated the issue body to v1.21.1 patch version
It is necessary for us to get additional work in to the 1.21 line for RKE2 in order to have a successful release. As such, we are going to forego a 1.21.0 release and opt for a 1.21.1 release instead.

**Comment by briandowns** [comment]
https://drone-publish.rancher.io/rancher/rke2/730
