### ISSUE TITLE
Can't turn off secrets encryption

### ISSUE THREAD

**Issue by mddamato** [rancher/rke2#850]
### Description

I can't seem to turn off the secrets encryption.

In the documentation, there is an option
```
--secrets-encryption                 (experimental) Enable Secret encryption at rest
```

Without setting it secrets in ETCD appear to be encrypted.

### Steps

Install RKE2 v1.20.5 from stable
```
yum install -y rke2-server
```

Turn off secrets-encryption
```
mkdir -p /etc/rancher/rke2
cat > /etc/rancher/rke2/config.yaml <<EOF
secrets-encryption: false
EOF
```

Start RKE2
```
systemctl start rke2-server
systemctl enable rke2-server
journalctl -u rke2-server -f
```

Create test secret
```
touch file && echo "hello my name is mike" > file
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n default \
create secret generic test --from-file ./file
```

Verify ETCD data
```
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml exec -it \
$(/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get po -l component=etcd -n kube-system \
-o jsonpath='{.items[0].metadata.name}') \
-n kube-system -- /bin/bash -c \
"ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 \
--cacert=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt \
--cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt \
--key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key \
get /registry/secrets/default/test --prefix"
```

I get something like:
```
/registry/secrets/default/test
k8s:enc:aescbc:v1:aescbckey:�zc��am��\y�}�6t�{ק�d�U�6�$t��N�?�NJ+1�q96S2T�"�CO$�O(�Z�X��>�h����j��@�V�P��fٕ��3?���G9����?K��h7Z�G�T�D���X�$^�t���8�!�C��{�g�؍3^Ź��:�"��!bm|
�=�Ro�z޷�]��/�)�z��χ�ܶ��2�M�!lhջƞ�ݝ��� �t�5"�������oɽR[�w�P��l�//MM7
```

### References

Found this PR that sets the flag by default: https://github.com/rancher/rke2/pull/32

**Comment by brandond** [comment]
You're correct, that is hard-coded enabled for compliance reasons. We should probably hide the flag so that we don't give the impression that it can be disabled.

**Comment by mddamato** [comment]
No current use case, actually. Just testing different security-related flags.

**Comment by rovandep** [comment]
We have a business use case; using a Kubernetes KMS provider plugin. 
We are not able to set a different encryption-provider-config than the one set by default and so at deployment or post deployment.

**Comment by brandond** [comment]
@rovandep you can pass your own configuration via `--kube-apiserver-arg=encryption-provider-config=/path/to/config`. This was validated in https://github.com/rancher/rke2/issues/1105
