### ISSUE TITLE
error: Unable to connect to the server: x509: certificate is valid for ...

### ISSUE THREAD

**Issue by renannprado** [rancher/rke2#852]
[Here](https://docs.rke2.io/cluster_access/#accessing-the-cluster-from-outside-with-kubectl) you say that all you have to do to access the cluster from outside is to copy the `rke2.yaml` file. However, the certificate generated is not using the `hostname` and therefore I face the below error:

> Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not [the hostname]

As a workaround, of course, I can use the `--insecure-skip-tls-verify` flag of `kubectl` to bypass the error. But I suppose there's a proper way of setting up `rke2` so that this issue doesn't happen.

**Comment by brandond** [comment]
you might check out the `--tls-san` option.

**Comment by renannprado** [comment]
@brandond thanks for the hint. I believe would be helpful to mention this part of the documentation as well.

One more question though: can I set this option **after** I already setup the cluster?

**Comment by brandond** [comment]
> @brandond thanks for the hint. I believe would be helpful to mention this part of the documentation as well.

It is listed in the CLI flags, as well as in the install docs: https://docs.rke2.io/install/ha/#2-launch-the-first-server-node

> One more question though: can I set this option **after** I already setup the cluster? if yes, how?
 Yes, just add it to the flags in the systemd unit or in your config file, and restart rke2-server.

**Comment by renannprado** [comment]
@brandond I missed this then as I don't want to setup HA - it's just a server at home. 

But I have changed the config accordingly and it didn't work.

`/etc/rancher/rke2/config.yaml`
```yaml
tls-san:
  - my-host
  - my-host.my-domain.com
```

I even deleted the `/etc/rancher/rke2/rke2.yaml` (which is the kubeconfig), but the new one that was generated still doesn't change the CA data.

Did I miss something?

**Comment by flybd5** [comment]
"Yes, just add it to the flags in the systemd unit or in your config file, and restart rke2-server."

This vague comment doesn't really help. There is no place in the systemd unit labeled as "flags" and this leaves it up to someone's imagination where the flags go. The second part is equally as cryptic. "restart rke2-server"? There is no such service or process in my installation. ??

**Comment by brandond** [comment]
@flybd5 It might not help you, but I believe it was helpful to the individual I was responding to as it seemed to answer their question.


> There is no place in the systemd unit labeled as "flags"
"flags" are the aforementioned RKE2 cli flags, this is everything following `rke2 server` on the ExecStart line in the systemd unit. You may also set CLI flags via the config file. You can find more info [in the documentation](https://docs.rke2.io/install/install_options/install_options.html#configuration-file).

> The second part is equally as cryptic. "restart rke2-server"

Yes, as in `systemctl restart rke2-server`. I would hope that restarting a Linux service is a familiar operation for anyone attempting to install and administer a Kubernetes cluster.

**Comment by flybd5** [comment]
> @flybd5 It might not help you, but I believe it was helpful to the individual I was responding to as it seemed to answer their question.
> 
> > There is no place in the systemd unit labeled as "flags"
> 
> "flags" are the aforementioned RKE2 cli flags, this is everything following `rke2 server` on the ExecStart line in the systemd unit. You may also set CLI flags via the config file. You can find more info [in the documentation](https://docs.rke2.io/install/install_options/install_options.html#configuration-file).
> 
> > The second part is equally as cryptic. "restart rke2-server"
> 
> Yes, as in `systemctl restart rke2-server`. I would hope that restarting a Linux service is a familiar operation for anyone attempting to install and administer a Kubernetes cluster.

Well that explains it. Apparently you are well behind the times. No rke2 here, it's the new rancherd service. One would hope that keeping up to date would be a familiar operation for anyone using Rancher. I guess not. :P

**Comment by brandond** [comment]
> Well that explains it. Apparently you are well behind the times. No rke2 here, it's the new rancherd service. One would hope that keeping up to date would be a familiar operation for anyone using Rancher. I guess not. :P

You're commenting in the RKE2 repo on a RKE2 issue. Rancherd is a downstream project that lives in a different repo: https://github.com/rancher/rancher/tree/master/cmd/rancherd

If you have rancherd questions, you should open them in the rancher/rancher repo.

**Comment by rgutierrez2004** [comment]
> You're commenting in the RKE2 repo on a RKE2 issue. Rancherd is an experimental downstream project that lives in a different repo:
The problem is rancherd by default setup an rke2 cluster, and most of the rke2 issues applies to rancherd deployments and viceversa.

**Comment by rancher-max** [comment]
As rancherd has been changed and removed and this issue appears stale, I'm going to close it out.

**Comment by watbulb** [comment]
This still happens even in 2026. What's the point of having "tls-san" as a flag, if any changes to its value necessitate an entire re-install of RKE2 or a cluster reset, because RKE cannot change the TLS SAN options once the cluster is already provisioned and installed. It should be reflected in the documentation that `--cluster-reset` is required between two different server boots in order to re-provision RKE2 to update the SAN configuration. Reproducing this is very easy, unbelievably easy it fails to reason why this hasn't been caught by developers. Have you ever moved a server from one location to another with different NICs and routes?

**Comment by renannprado** [comment]
@watbulb I know you didn't ask for it, but if you have the possibility, try k0s or Talos.

The first one works very well for me and their support in slack is really good. I haven't got the chance to try Talos, but it should be even easier to maintain.

**Comment by watbulb** [comment]
@renannprado Hey there! No problem, I really appreciate the pointers. I'll check those out. Thanks.
