### ISSUE TITLE
Update k3s Version and Add Etcd S3 Functionality

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#854]
K3s currently has the ability to save etcd snapshots to S3, and has a subcommand, `etcd-snapshot` to perform on-demand snapshots.

These features and bug fixes need to be pulled into RKE2 and documentation needs to be updated.

**Comment by briandowns** [comment]
PR #848 adds the required features.

**Comment by ekristen** [comment]
The documentation states that you should be able to pass the s3 options to the server command via CLI or yaml, presumably so that backups happen automatically to S3, however running the latest release seems to not understand these options.

**Comment by davidnuzik** [comment]
@briandowns is the issue ready for QA testing? I see this doesn't have a milestone and is in "To Triage" status.

**Comment by briandowns** [comment]
Yes. @ShylajaDevadiga was looking at it this morning having wrapped up k3s testing yesterday.

**Comment by davidnuzik** [comment]
Moved to test state.

**Comment by ShylajaDevadiga** [comment]
Validation etcd s3 functionality 

- Create snapshot and confirmed snapshot is stored locally as well as in s3
- Restore from snapshot on single node as well as multi node setup
- Restore from snapshot on a quorum loss scenario
- Validated etcd-snapshot-retention value is honored both locally as well in s3 bucket
- Validated scheduled snapshot
