### ISSUE TITLE
rke2-killall.sh does not clean up all network namespaces?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#855]
We had rke2 1.20.5 deployed on sles15sp2 and then did a rke2-killall.sh, deleted the installation and re-deployed (no reboot)

Even after the killall we can see this:

zrz-ux-vm11634:~ # ip netns
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
cni-3b14aef7-1868-f8cc-422c-df5a5c62084c (id: 0)
cni-5f7c07bc-67a0-cb4e-9f10-2e14eb312711 (id: 3)
cni-2b859e51-1be8-7cd8-bb9f-956c77698475 (id: 1)
Error: Peer netns reference is invalid.
cni-b61067e2-ec37-9b02-971c-166c54468ea4
Error: Peer netns reference is invalid.
cni-f4d1dab9-9124-c063-0b1a-7d3a78694ceb
Error: Peer netns reference is invalid.
cni-b0dbfb39-fe4b-9fb7-3f2e-f5416f230d0c

--> could it be that the killall does not clean up properly and is missing something on the cni side of things?

(Workaround was to reboot - but maybe we could get the deletion of the namespaces added to the rke2-killall, too?)

**Comment by brandond** [comment]
Probably just needs the equivalent of https://github.com/k3s-io/k3s/pull/2542

**Comment by Martin-Weiss** [comment]
> 
> 
> Probably just needs the equivalent of [k3s-io/k3s#2542](https://github.com/k3s-io/k3s/pull/2542)

Yeah - looks like.. how can we get this added in RKE2 uninstall?

**Comment by kmahyyg** [comment]
same problem here.

**Comment by mdrahman-suse** [comment]
### Validated on master branch with commit 81b04f085bd73d7a285f63087489600fb011a7a4
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
SUSE Linux Enterprise Server 15 SP4
```
  
*Cluster Configuration:*

```
1 server
```
  
*Config.yaml:*

```
write-kubeconfig-mode: 644
node-name: server
debug: true
```
  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2
 - For replication:`curl https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.26.2+rke2r1 sh -`
 - For validation: `curl https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=81b04f085bd73d7a285f63087489600fb011a7a4 sh -`
3. Enable and start service: `sudo systemctl enable rke2-server --now`
4. Ensure the cluster is up
5. Check network namespaces: `ip netns`
6. Kill rke2: `sudo rke2-killall.sh`
7. Check network namespaces, should see no errors
  
**Replication Results:**
- rke2 version used for replication:

```
rke2 version v1.26.2+rke2r1 (f92516c05d4bb33bdbdee902951fcf73d91466db)
go version go1.19.6 X:boringcrypto
```
 

- Before killall
```
~> ip netns
cni-8a8dc90f-3f17-0e0f-7f00-4d5b1c8d6a1a (id: 2)
cni-16cdcd3c-900d-5d83-04be-714de3afadf2 (id: 10)
cni-ca3f8a84-06d6-3a3e-b763-cadac5853ea1 (id: 8)
cni-a8ec073d-5c92-9734-7388-51b29d3ea6f0 (id: 7)
cni-5d51d076-8873-7d30-256a-952678e109d7 (id: 1)
cni-16c4fc1a-2745-0a9c-1594-130ce5cc2239 (id: 0)
```
- After killall
```
~> ip netns
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
cni-8a8dc90f-3f17-0e0f-7f00-4d5b1c8d6a1a
Error: Peer netns reference is invalid.
cni-16cdcd3c-900d-5d83-04be-714de3afadf2
Error: Peer netns reference is invalid.
cni-ca3f8a84-06d6-3a3e-b763-cadac5853ea1
Error: Peer netns reference is invalid.
cni-a8ec073d-5c92-9734-7388-51b29d3ea6f0
Error: Peer netns reference is invalid.
cni-5d51d076-8873-7d30-256a-952678e109d7
Error: Peer netns reference is invalid.
cni-16c4fc1a-2745-0a9c-1594-130ce5cc2239
```
 
**Validation Results:**
- rke2 version used for validation:

```
rke2 version v1.26.3+dev.81b04f08 (81b04f085bd73d7a285f63087489600fb011a7a4)
go version go1.19.7 X:boringcrypto
```
 

- Before killall
```
~> ip netns
cni-1bf46ee6-e0a1-a938-ae23-c7220916b4be (id: 5)
cni-d46afe89-b68b-cea0-b788-4e71c8907bf7 (id: 4)
cni-2a558639-a4cf-0b1b-58ff-6169520ab1c8 (id: 2)
cni-e61e820e-f862-4bfd-7320-a0cbf879c188 (id: 3)
cni-71e6cb8a-bf32-acaa-c99d-7f9f991f6303 (id: 1)
cni-7178975e-9dcd-8276-782d-4b1f4347f3a2 (id: 0)
```
- After killall
```
~> ip netns
~>
```
