### ISSUE TITLE
cluster reset not available

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#856]
#### Description
`cluster-reset` flag appears to not be available. It doesn't look like it is hidden: https://github.com/rancher/rke2/blob/9b3e44414d2a358cdfa795936eb09e67486c7150/pkg/cli/cmds/server.go#L38 
but I do not see it in the cli help, and even trying to use it does not reset the cluster quorum after it's been lost.

#### Effected Versions
All: v1.18.17+rke2r1, v1.19.9+rke2r1, v1.20.5+rke2r1

#### Steps to reproduce
In general, just run `rke2 server --help | grep cluster-reset` and only the restore-path flag is present. The impactful scenario is below:
1. Create a cluster with 3 server nodes
2. Stop 2 of the server nodes -- cluster will lose quorum
3. Attempt to reset the cluster using `rke2 server --cluster-reset` -- this does not work right now.

**Comment by briandowns** [comment]
The flag isn't showing in the help display is but is available for use. I'll take a look into why.

**Comment by briandowns** [comment]
Looks like the `cluster-reset` flag is set to hidden in k3s. I think removing the hidden attribute and updating RKE2 will resolve this.

**Comment by cjellick** [comment]
Is this a regression or did this always exist as a problem?
If it is a regression, I'd like to knonw where it was introduced.

**Comment by briandowns** [comment]
Always existed. THis is because of hidden flags in k3s.

**Comment by rancher-max** [comment]
@cjellick @briandowns I believe this is a regression because the flag was present in v1.18.16, v1.19.8, and v1.20.2-beta1. So it looks like this was introduced in the recent 1.18.17 and 1.19.9 releases, and a little while back in the 1.20.4 release.

**Comment by briandowns** [comment]
Interesting. I brought down 1.20 and didn't see it.

**Comment by brandond** [comment]
@galal-hussein do you remember why you hid these flags? https://github.com/k3s-io/k3s/commit/5749f66aa3c469b4c744caab1878c6967ac08041#diff-227294a471aa37485c65a92dded07953a1e93417274e4c889fa4a2c721bc17c4R13

**Comment by galal-hussein** [comment]
> @galal-hussein do you remember why you hid these flags? [k3s-io/k3s@5749f66#diff-227294a471aa37485c65a92dded07953a1e93417274e4c889fa4a2c721bc17c4R13](https://github.com/k3s-io/k3s/commit/5749f66aa3c469b4c744caab1878c6967ac08041#diff-227294a471aa37485c65a92dded07953a1e93417274e4c889fa4a2c721bc17c4R13)

These were mistakenly hidden along with disable flags during the backport

**Comment by rancher-max** [comment]
Was able to validate in versions v1.18.18-rc1+rke2r1 and v1.19.10-rc1+rke2r1 the `cluster-reset` flag exists now.

It still however appears to not be functional.
Logs during a reset look very similar to standard startup logs but then begin looping the same error:
```
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="Starting rke2 v1.18.18-rc1+rke2r1 (954e492bfe76e3643cfb933f7cc01d97d1948c9d)"
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="Pre-restore etcd database moved to /var/lib/rancher/rke2/server/db/etcd-old-1618965026"
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: {"level":"info","msg":"restoring snapshot","path":"/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-1618964040","wal-dir":"/var/lib/rancher/rke2/server/db/etcd/member/wal","data-dir":"/var/lib/rancher/rke2/server/db/etcd","snap-dir":"/var/lib/rancher/rke2/server/db/etcd/member/snap"}
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: {"level":"info","msg":"restored last compact revision","meta-bucket-name":"meta","meta-bucket-name-key":"finishedCompactRev","restored-compact-revision":3882}
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: {"level":"info","msg":"added member","cluster-id":"f96e6dcfe4f708f4","local-member-id":"0","added-peer-id":"dc3530dc84f86e0e","added-peer-peer-urls":["https://172.31.2.133:2380"]}
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: {"level":"info","msg":"restored snapshot","path":"/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-1618964040","wal-dir":"/var/lib/rancher/rke2/server/db/etcd/member/wal","data-dir":"/var/lib/rancher/rke2/server/db/etcd","snap-dir":"/var/lib/rancher/rke2/server/db/etcd/member/snap"}
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="Node token is available at /var/lib/rancher/rke2/server/token"
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="To join node to cluster: rke2 agent -s https://172.31.2.133:9345 -t ${NODE_TOKEN}"
Apr 21 00:30:26 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:26Z" level=info msg="Wrote kubeconfig /etc/rancher/rke2/rke2.yaml"

...

Apr 21 00:30:51 ip-172-31-2-133 rke2[20175]: {"level":"warn","ts":"2021-04-21T00:30:51.280Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Apr 21 00:30:51 ip-172-31-2-133 rke2[20175]: {"level":"warn","ts":"2021-04-21T00:30:51.368Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Apr 21 00:30:51 ip-172-31-2-133 rke2[20175]: time="2021-04-21T00:30:51Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Apr 21 00:30:51 ip-172-31-2-133 rke2[20175]: {"level":"warn","ts":"2021-04-21T00:30:51.370Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
```
I believe we expect the logs not to even look like the standard startup logs and instead give a message related to "cluster has been restored from a snapshot. Restart rke2 without the cluster-reset flag"

**Comment by rancher-max** [comment]
This is working. I didn't run the `rke2-killall.sh` script first. Running this script before running the cluster-reset resolves those errors.
