### ISSUE TITLE
Add support for Calico CNI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#860]
Add support for Calico. RKE2 clusters provisioned in (not yet released) Rancher 2.6 should default to Calico (to be tested via https://github.com/rancher/rancher/issues/32380).

**Comment by davidnuzik** [comment]
Note: May need to support pull secrets (in enterprise version) in a future Rancher 2.6.x release. Believe enterprise version is a flag to set in chart. @manuelbuil -- I believe you are looking into Calico CNI? If this is so please assign yourself to this issue and move it to Working state.

Regarding the enterprise version; if it's small effort we should expose this option.

**Comment by manuelbuil** [comment]
> Note: May need to support pull secrets (in enterprise version) in a future Rancher 2.6.x release. Believe enterprise version is a flag to set in chart. @manuelbuil -- I believe you are looking into Calico CNI? If this is so please assign yourself to this issue and move it to Working state.
> 
> Regarding the enterprise version; if it's small effort we should expose this option.

Calico is integrated into rke2 and working correctly. Agreed with Craig to delay the "calico as default for rke2" feature.

Can you provide me more information about the "pull secrets" requirement please? I am not aware of this

**Comment by davidnuzik** [comment]
For testing in Rancher 2.6 explicitly later: https://github.com/rancher/rancher/issues/32380

**Comment by rancher-max** [comment]
This appears to be working correctly using server param `cni: calico` in v1.21.1-alpha4+rke2r1. Open question I have before closing:
Is it supposed to build in its own namespaces? I see its building into `calico-system` and `tigera-operator`. This means that when I import the cluster into rancher, these namespaces don’t get added into the System project automatically. This could be something for Rancher to take care of, or we could possibly build these into the kube-system namespace instead with the rke2 chart, similar to how we do for cilium and canal.

**Comment by brandond** [comment]
I think the request from @ibuildthecloud was just that the charts themselves live in kube-system; the charts themselves are welcome to put things in whatever namespace they want.

Handling this (as well as adding support for selecting the CNI when provisioning the cluster) is something that Rancher will handle in 2.6
