### ISSUE TITLE
Failing to pull rke2-runtime image

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#871]
**Description:**
rke2-runtime is failing to pull when running v1.20.5-alpha1+rke2r2 via the systemd service file. Debug logs:
```
time="2021-04-12T14:03:53-07:00" level=debug msg="Transformed registry URL: 
https://index.docker.io/v2/ => https://index.docker.io/v2/"
time="2021-04-12T14:03:54-07:00" level=debug msg="Mirror config for auth.docker.io: templates.Mirror{Endpoints:[]string(nil), Rewrites:map[string]string(nil)}"
time="2021-04-12T14:03:54-07:00" level=debug msg="Mirror config for *: templates.Mirror{Endpoints:[]string(nil), Rewrites:map[string]string(nil)}"
time="2021-04-12T14:03:54-07:00" level=debug msg="Rewriting URL for host auth.docker.io: []string(nil) map[string]string(nil)"
time="2021-04-12T14:03:54-07:00" level=debug msg="Transformed registry URL: 
https://auth.docker.io/token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=registry.docker.io => https://auth.docker.io/v2//token?scope=repository%3Arancher%2Frke2-runtime%3Apull&service=registry.docker.io"
```

**Steps:**
1. `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.20.5-alpha1+rke2r2 sh -`
2. `sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service`
3. `journalctl -eu rke2-server` >> this will show the failure looping

**Comment by rancher-max** [comment]
This has been fixed on latest commit id `f38c8fbff2e1c62eb635d928458e66cd91220893` and default installs using that work properly.

**Comment by Martin-Weiss** [comment]
FYI - just tested with v1.20.6-rc2+rke2r1 and this issue seems to be solved! The runtime image seems to be pulled! Thanks a lot for fixing this!!

**Comment by rancher-max** [comment]
Yep this is resolved again in rc2
