### ISSUE TITLE
CIS 1.6 Hardening guide and Self assesment guide

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#876]
Create the two guides for RKE2 at https://docs.rke2.io/security/hardening_guide/

**Comment by davidnuzik** [comment]
Once complete, we should update the security page as well as indicated here: https://github.com/rancher/docs/issues/3185

**Comment by davidnuzik** [comment]
@rancher-max please skim over merged docs - double-check to ensure no significant issues.

**Comment by rancher-max** [comment]
@MonzElmasry @davidnuzik I think we should change the titles of both the 1.6 and 1.5 pages to include their versions for easier sidebar navigation. See what it looks like as it is now:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/55997940/119859879-a375a700-beca-11eb-9fb1-5f9484bc2a88.png">

Also, control 3.2.1 passes now in both CIS 1.5 and CIS 1.6. We should adjust our known issues and the docs here to reflect this. See: https://github.com/rancher/rke2/issues/410#issuecomment-722680342. Perhaps we should add a note in this edit saying that we don't actually log anything by default, but technically this control is a pass and we should document that.

**Comment by brandond** [comment]
Can we change them to just "CIS 1.5 Self-Assessment" and "CIS 1.6 Self-Assessment"?

**Comment by rancher-max** [comment]
This PR got closed and needs to be redone and merged. Reopened to address this.

**Comment by briandowns** [comment]
New PR #1150 has these changes now.
