### ISSUE TITLE
Can't file config.yaml in the default location

### ISSUE THREAD

**Issue by taragurung** [rancher/rke2#883]
The setup of cluster master and worker is fine but only problem is I can only find the **rke2.yaml** kubeconfig file in the default location /etc/rancher/rke2, server config.yaml is not available.

Any way to generate it?

**Comment by brandond** [comment]
It will be created in that file on servers during the startup process. Are you sure that this is a server and not an agent? If it's not there on a server, the best way to recreate it is to restart the rke2-server service.

**Comment by taragurung** [comment]
Yes, I didn't over-write it and also confirmed it's a server, not an agent. Hoping it to recreate on restart.

**Comment by brandond** [comment]
Oh I'm sorry, misread your question. rke2.yaml is the kubeconfig file that is generated on startup. config.yaml is something you create to pass configuration to RKE2; if it is deleted RKE2 will not recreate it for you.

**Comment by taragurung** [comment]
hmm but it should be there by default right? Just wondering why I didn't have that else all good.

**Comment by brandond** [comment]
No, that file is for user-provided configuration, as an alternative to configuring RKE2 via CLI flags or environment variables. What would you expect to find in that file if it was created by RKE2?

**Comment by taragurung** [comment]
As the config.yaml is not created. That is fine but suppose  I need to add 2 more master nodes. what I am confused about is. 

1. I created the first node successfully, which will have the token added to  /var/lib/rancher/rke2/server/token
2. Now, before creating another master node, do I have to add the bellow config.yaml in the first created server node then only repeat the installation process. 
As I am installing server nodes manually following this guide: https://docs.rke2.io/install/quickstart/

If I set up server node2 it will again have another token, how do I attach node1 and node2 quite confusing. 


config.yaml
```
server: https://my-kubernetes-domain.com:9345
token: my-shared-secret
tls-san:
  - my-kubernetes-domain.com
  - another-kubernetes-domain.com
 ```

**Comment by taragurung** [comment]
Yes, this file does not come pre-build, and We need it when we want to add new master nodes. So the steps to add new nodes and file is as follows.

1. follow the step 1 and step2 as in getting started documentation
2. Create a folder and config.yaml file before starting the rke2 service. (just see how it is done for worker nodes, same goes for the master nodes as well, which was not mentioned for master nodes in documentations)
3. Add the IP address of the master nodes created first and the token as well from the same node
4. start the rke2 service

Thanks @brandond
