### ISSUE TITLE
Bump nginx ingress version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#884]
Possibly related to https://github.com/rancher/rke2/pull/727

We have a request to bump the version used for the nginx chart 3.3.000 or newer. We will target for a 1.21.1 release in May.

**Comment by cjellick** [comment]
we are going to do v0.43.0

**Comment by ShylajaDevadiga** [comment]
Validated on v1.21.1-alpha4+rke2r1
```
kubectl describe pod -n kube-system rke2-ingress-nginx-v3-controller-gvtfx|grep -i image
    Image:         rancher/nginx-ingress-controller:nginx-0.46.0-rancher1
```
