### ISSUE TITLE
Add --cni flag as an option to RKE2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#887]
We agreed to add a new `--cni` flag to RKE2. Flag values would be supported CNI plugins: `{"calico", "canal", "cilium"}`. The current default value will be `canal`.
* HelmChart Manifests for all three plugins will be bundled by default.
* Any plugins NOT selected will be added to the `--disable` list, as `rke2-<NAME>`. For example, setting `--cni=calico` will add `rke2-canal,rke2-cilium` to the `--disable` list.
* Separate tarballs that include supporting images for each CNI (including the default CNI) will be produced. This will constitute a breaking change for airgap users, as they will need to load an additional tarball - one for the core images, another for the CNI images.

Notes: should we also silently handle CNI plugins with a `rke2-` prefix included? Might save some confusion due to the charts themselves having that prefix.

**Comment by manuelbuil** [comment]
@davidnuzik could you provide more context please? Where was this discussed? Is the current approach perceived as user-unfriendly?

**Comment by davidnuzik** [comment]
@manuelbuil this was discussed Thursday last week 4/15 in the afternoon rancher<->rke2 integration call. The current approach isn't necessarily unfriendly; the main concern was that we should have more control of the CNI charts by hosting everything within RKE2. This way we are not beholden to KDM in Rancher which could be more agnostic and could perhaps making fixing things in charts more difficult (at least this was my take of the discussion). The flag could also make it easier to integrate RKE2 with Rancher. If you have any further questions you can raise them in Slack with the team.

**Comment by jcaamano** [comment]
That is something that is very similar to the first integration proposal for cilium. I am going to link it here for reference:

https://github.com/rancher/rke2/pull/497

**Comment by rancher-max** [comment]
#### Validated in v1.21.0-alpha2+rke2r1
All 5 options of `none`, `canal`, `cilium`, `calico`, and just not using the flag appear to be working correctly. They use, respectively, "no cni", "rke2-canal", "rke2-cilium", and "rke2-calico".

They use the version of the chart built into rke2.
