### ISSUE TITLE
token CA hash does not match the server CA hash in 1.19

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#888]
I get this error in 1.19.7, 1.19.8 and 1.19.9 when using my own CA for /var/lib/rancher/rke2/server/tls/server-ca.crt and /var/lib/rancher/rke2/server/tls/server-ca.key:

`Apr 16 14:33:04 rke-test-master-01 rke2[19309]: time="2021-04-16T14:33:04+02:00" level=error msg="token CA hash does not match the server CA hash: a31dc5ddf16526a95135b3f8a8d284a59b00e8aaf47d9121896f8c8471bd845c != e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
`

This might be related to https://github.com/k3s-io/k3s/issues/2731 ?

--> is there any workaround or potential fix I can apply in 1.19?

P.S. with 1.20 I do not see this problem.

**Comment by brandond** [comment]
Yes, you've found the root cause for that error on 1.19. The issue was addressed in 1.20 and not backported to 1.19 since it involved some fairly significant rewrites of the agent join code. You'll need to run 1.20 or newer if you want to be able to use a cluster CA that is trusted by the host OS.

**Comment by Martin-Weiss** [comment]
> Yes, you've found the root cause for that error on 1.19. The issue was addressed in 1.20 and not backported to 1.19 since it involved some fairly significant rewrites of the agent join code. You'll need to run 1.20 or newer if you want to be able to use a cluster CA that is trusted by the host OS.

I do not want to use a "host OS trusted CA" - I just want to use a "custom CA". 
So do I get it right that using a "custom CA" in general not supported in 1.19?

Do you know if there is any workaround available to get a custom CA working in 1.19?

**Comment by brandond** [comment]
The error you're getting only occurs if the RKE2 server cert is trusted, which indicates that your custom CA has been included in the OS CA bundle. Can you share the steps you used to generate and install your custom CA certs?

**Comment by Martin-Weiss** [comment]
> The error you're getting only occurs if the RKE2 server cert is trusted, which indicates that your custom CA has been included in the OS CA bundle. 

Yes - this is the basic reason for using a custom CA - make sure it is already trusted everywhere.

> Can you share the steps you used to generate and install your custom CA certs?

Create server-ca.key and server-ca.crt with openssl commands.

The server-ca.crt is copied to /etc/pki/trust/anchors and update-ca-certificates is executed on all servers before deploying anything so this is part of the OS deployment process.

Then copy both files to /var/lib/rancher/rke2/server/tls/ before starting the rke2-server service the first time.

Now when starting rke2-server we see the error in journalctl -u rke2-server.

FYI - the token/agent-token we use are preconfigured in config.yaml with a custom string and not related to the CA..

**Comment by brandond** [comment]
OK - that's why I said you cannot use a "host OS trusted CA" with 1.19. It doesn't matter if this is a public CA, or a private CA that you have created for this purpose - it's not supported with 1.19. You can use your own CA just fine, but it cannot be present in the OS CA bundle.

**Comment by Martin-Weiss** [comment]
> OK - that's why I said you cannot use a "host OS trusted CA" as the cluster root CA for 1.19. It doesn't matter if this is a public CA, or a private CA that you have created for this purpose - it does not work with 1.19. You can use a "custom CA", but it cannot be present in the OS CA bundle.

Ok - this means we have no workaround to use a custom CA as the purpose of the custom CA is to have it "trusted everywhere internally already - which includes the OS / the host RKE2 will be deployed on".

> 
> If this is a critical feature for you and need the fixes backported to 1.19, please raise it internally with PM.

Will do - thanks!

**Comment by brandond** [comment]
I am curious though - why would you care if the host OS trusts the cluster CA? I haven't ever seen anyone deploy anything outside the cluster that needs to trust the cluster control plane. The kubectl file contains a trust root for interacting with the cluster, and that's generally sufficient.

**Comment by Martin-Weiss** [comment]
> I am curious though - why would you care if the host OS trusts the cluster CA? I haven't ever seen anyone deploy anything outside the cluster that needs to trust the cluster control plane. The kubectl file contains a trust anchor for interacting with the cluster, and that's generally sufficient.

It is the other way around  - customer already has a CA that is trusted everywhere and wants this CA to be used everywhere / by k8s so that all k8s clients already have the trusted CA.. - we also use that CA for cert-manager that creates new certificates within the cluster i.e. for ingress etc..
It would be really nice if we could use different intermediate CAs per cluster... or even better - use api calls against the customers CA infrastructure in case they have that.. (similar to letsencrypt or adcs..)
