### ISSUE TITLE
Test New Kubelet argument --protect-kernel-defaults

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#89]
A new argument has been added to kubelet that needs to be set to `true` to comply with CIS 1.5 requires. The work to accomplish this was done in rancher/rke2#87 .

To test

```sh
grep protect /var/lib/rancher/rke2//logs/kubelet.log 
```

This command should return a string with the argument and it being set to false.

**Comment by rancher-max** [comment]
#### Validated in `alpha21`

The command I used was: `grep -i protect /var/lib/rancher/rke2/agent/logs/kubelet.log`

Results:
```
$ grep -i protect /var/lib/rancher/rke2/agent/logs/kubelet.log 
I0727 18:47:06.694651    2231 container_manager_linux.go:271] Creating Container Manager object based on Node Config: {RuntimeCgroupsName:/systemd/system.slice SystemCgroupsName: KubeletCgroupsName:/systemd/system.slice ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:true NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s 
```

Notice the `ProtectKernelDefaults:true` which resolves this issue. This is present whether the node is the initial server node, a joined server node, or an agent node. When bringing up a cluster without CIS mode, this same command shows `ProtectKernelDefaults:false` as expected.
