### ISSUE TITLE
Server nodes do not start even though the service is enabled

### ISSUE THREAD

**Issue by wiryfuture** [rancher/rke2#890]
**Environmental Info:**
RKE2 Version: v1.20.5+rke2r1

Node(s) CPU architecture, OS, and Version: (Xen hypervisor)
![image](https://user-images.githubusercontent.com/50517631/115247337-9c66b680-a11e-11eb-887d-b5ebed5e7fd3.png)

Cluster Configuration:
3 servers and 3 agents, with a loadbalancer deployed in front of the servers for HA (and tls-san enabled with the LB ip)

**Describe the bug:**
On the server nodes, the rke2-server service does not start on boot, even though I have run `systemctl enable rke2-server` on all of them. There are no errors in the journalctl log, it simply does not start. If I run `systemctl start rke2-server`, the service start correctly immediately. This is odd, as only the server service has this issue, the agents do not have this issue, and the rke2-agent service starts fine on boot.

**Steps To Reproduce:**

- Installed RKE2: 
- Ran `systemctl enable  rke2-server && systemctl start rke2-server` on server node and authenticated
- Restarted node
- Checked journalctl and node health to see rke2-server hasn't started.

**Expected behavior:**
rke2-server starts on boot

**Actual behavior:**
rke2-server does not start on boot.

**Additional context / logs:**
None, there are no errors.

**Comment by brandond** [comment]
What does `systemctl status rke2-server` show after a reboot, when the service isn't started?

**Comment by wiryfuture** [comment]
This is it
![image](https://user-images.githubusercontent.com/50517631/115785543-8293d080-a3b7-11eb-8c1f-cc2ac3dd26cf.png)

I dug into the journalctl logs and found an error about my tls-san argument. This does not make sense, as the server starts fine manually and the config at /etc/rancher/rke2/config.yaml has tls-san as do all the other server nodes, and they always have, and it shouldn't even really make a difference anyway at this point of the installation (right?).
(*this has never been present when I have checked previously, may have been because I left the node alone after boot for a while*)
![image](https://user-images.githubusercontent.com/50517631/115785838-eae2b200-a3b7-11eb-914d-e532120b67eb.png)

On one of my agent nodes I just got this in the journalctl logs (again, a manual start launches it fine as well)
![image](https://user-images.githubusercontent.com/50517631/115786704-14500d80-a3b9-11eb-9dda-ae884cc6aa0a.png)

I'm starting to believe this issue has something to do with the servers in the cluster not being in quorum when the node is starting, leading to it having an absolute meltdown and not being able to connect to it at any point, even if the quorum is regained, without manual intervention. If I bring up my lab's nodes, the cluster won't reassemble itself on the nodes' boot.

**Comment by brandond** [comment]
Wait, do you have both rke2-agent and rke2-server installed on the same nodes?

**Comment by wiryfuture** [comment]
nonono!! This is just the same cluster and I'm noticing they both had errors on boot at  the same time

**Comment by brandond** [comment]
OK, so you have two errors? The agents have flags configured that they don't support, and also the servers don't start on boot?

**Comment by brandond** [comment]
In terms of cold start behavior - it is expected that the cluster won't come online until 2 out of the 3 servers are stared. Etcd will prevent the RKE2 service startup from completing until quorum is available.

**Comment by wiryfuture** [comment]
The agent doesn't have tls-san  in the config, I have no clue why it got that error just then, probably because the servers were down because:
The server service don't start when I bring up all the nodes unless I start them manually.

**Comment by brandond** [comment]
Can you check and confirm which services you have installed and enabled on each of the nodes? 
```bash
systemctl list-units --all 'rke2*'
```

**Comment by wiryfuture** [comment]
> In terms of cold start behavior - it is expected that the cluster won't come online until 2 out of the 3 servers are started. Etcd will prevent the RKE2 service startup from completing until quorum is available.

How does starting the rke2-server service manually differ from it starting on boot? That works but the service won't start on its own..

**Comment by wiryfuture** [comment]
> Can you check and confirm which services you have installed and enabled on each of the nodes?
> 
> ```shell
> systemctl list-units --all 'rke2*'
> ```
Everything looks fine except on agent1 (which had the error) even though rke2-server disabled; so I'm not sure what it tried to do, but I ran systemctl disable rke2-server on it just in case.
![image](https://user-images.githubusercontent.com/50517631/115789787-98a48f80-a3bd-11eb-8e15-252bc04c62a5.png)

**Comment by brandond** [comment]
Is it possible that you at one point started agent1 as a server, and the cluster is now looking for all 4 nodes for quorum?

**Comment by wiryfuture** [comment]
Hmmm. I'd think it seems like that too but agent1 was never registered as a control-plane or etcd with the cluster so I don''t think so.
