### ISSUE TITLE
Cilium CNI: cluster CIDR cannot be changed

### ISSUE THREAD

**Issue by susenguyen** [rancher/rke2#891]
**Environmental Info:**
RKE2 Version: v1.20.5%2Brke2r1

Node(s) CPU architecture, OS, and Version: 

SLES15 SP2

Cluster Configuration:

1 master, 2 workers

**Describe the bug:**

When deploying the Cilium CNI as described in https://docs.rke2.io/install/network_options/#using-cilium-instead-of-canal:
1) The cluster CIDR is not the default 10.42.0.0/16 as for Calico/Canal and described in https://docs.rke2.io/install/install_options/server_config, but 10.0.0.0/16
2) The value cannot be changed via the cluster-cidr flag in config.yaml; the CIDR remains 10.0.0.0/16.

**Comment by brandond** [comment]
The default CIDRs are 10.42.0.0/16 and 10.43.0.0/16, where are you seeing 10.0.0.0.0/16?

**Comment by brandond** [comment]
@jcaamano are there any downsides to doing that? I'm curious why it isn't the default, as that seems like it would be what most folks expect.

**Comment by manuelbuil** [comment]
> Documentation says:
> 
> ```
> The difference is that instead of Kubernetes assigning the per-node PodCIDRs
> via the Kubernetes v1.Node resource, the Cilium operator will manage the per-node
> PodCIDRs via the v2.CiliumNode resource. The advantage of this mode is that it does
> not depend on Kubernetes being configured to hand out per-node PodCIDRs.
> 
> This is useful if Kubernetes cannot be configured to hand out PodCIDRs or if more
> control is needed.
> ```
> 
> Ref: https://docs.cilium.io/en/v1.9/concepts/networking/ipam/cluster-pool/
> 
> I guess this advantage does not apply to RKE2.

Agree. I suggest changing the default to `ipam: kubernetes` instead of `ipam: cluster-pool`

**Comment by manuelbuil** [comment]
https://github.com/rancher/rke2-charts/pull/69

**Comment by manuelbuil** [comment]
@susenguyen before closing this issue, could you test again to verify it works in your env?

**Comment by susenguyen** [comment]
@manuelbuil , I successfully tested the "ipam: kubernetes" option as a helm option in the cilium helm chart and it's working fine. So we can close this request. Thanks a lot!
