### ISSUE TITLE
Pod Security Policies deprecation

### ISSUE THREAD

**Issue by bovy89** [rancher/rke2#892]
Hi,
now that PSP are officially deprecated, could be implemented an option to completely disable PSP in CIS/not-CIS mode (e.g. remove PodSecurityPolicy plugin and/or avoid psp configuration)? What are rke2 plans about PSP deprecation?

**Comment by brandond** [comment]
From the upstream documentation:

>Kubernetes 1.21 starts the deprecation process for PodSecurityPolicy. As with all feature deprecations, PodSecurityPolicy will continue to be fully functional for several more releases. The current plan is to remove PSP from Kubernetes in the 1.25 release.
>
>Until then, PSP is still PSP. There will be at least a year during which the newest Kubernetes releases will still support PSP, and nearly two years until PSP will pass fully out of all supported Kubernetes versions.

We're watching to see what replaces PSPs, and what the CIS Benchmark for Kubernetes recommends up to and after that replacement construct is available.

**Comment by bovy89** [comment]
Ok thanks. Maybe it might be useful, also in the [future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/#what-s-next), to let users decide if use or not PSP (or it's replacement). For example: OPA Gatekeeper seems to be a perfect (and more flexible) drop-in replacement and a lot of people already use it to enforce other policies: it would be great if we can use it on RKE2 (CIS/non-CIS mode) without PSP.
