### ISSUE TITLE
Add --no-psp flag (delete default PSP)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#898]
Add this flag to allow deletion of the default PSP for the Rancher 2.6 integration.

**Comment by Dmitry1987** [comment]
this might be what I'm looking for. the default PSP doesn't let custom stuff deployed in cluster to start: 
![image](https://user-images.githubusercontent.com/9369080/116948777-036b8b80-ac46-11eb-8ba5-ec722eb292c0.png)

what is the right way to make things work?  deleting the default PSP from namespace?

**Comment by davidnuzik** [comment]
Closing this. Future Rancher 2.6 will delete the PSP if necessary, as such this `--no-psp` feature is not required. Closing per Denise.
@Dmitry1987 sorry for missing you message -- might you be able to open a new issue if necessary? This issue was just for tracking some feature work for an upcoming Rancher release.
