### ISSUE TITLE
Test conf.d style config loading for config.yaml

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#899]
Previously tested in K3s https://github.com/k3s-io/k3s/issues/3205. Smoke test to ensure working correctly in RKE2 as well.

**Comment by rancher-max** [comment]
I do not believe this change is present yet on master of rke2. Moving back to Working.

**Comment by brandond** [comment]
@briandowns might be able to pull through a K3s update in #875

**Comment by davidnuzik** [comment]
Assigned the issue to @briandowns

**Comment by davidnuzik** [comment]
Moving to a v1.21.2 milestone

**Comment by brandond** [comment]
This made it in to RKE2 v1.21.1 via the k3s update in #971 - moving back into the milestone for testing.

**Comment by rancher-max** [comment]
#### Validated in v1.21.1-rc1+rke2r1

Performed the same steps as in https://github.com/k3s-io/k3s/issues/3205#issuecomment-822816740, without performing scenario 2 as that is k3s specific.
Install command was: 
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.21.1-rc1+rke2r1 sh -
sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
```
