### ISSUE TITLE
v1.20.6-rc2+rke2r1 with cilium first master -> node notReady and cilium does not get installed

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#911]
**Environmental Info:**
RKE2 Version:  v1.20.6-rc2+rke2r1

Node(s) CPU architecture, OS, and Version: 
Single / first master on SLES 15 SP2 with cilium instead of canal

Cluster Configuration:
1 master / first master / airgap with registry rewrite

**Describe the bug:**
Node Status does not get Ready -> stays on "not ready"

**Steps To Reproduce:**
- Installed RKE2: v1.20.6-rc2+rke2r1
- create single master with cilium instead of canal

describe node:
`Ready            False   Wed, 21 Apr 2021 14:52:58 +0200   Wed, 21 Apr 2021 13:26:17 +0200   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
`

kubectl get jobs -n kube-system
NAME                                           COMPLETIONS   DURATION   AGE
helm-install-rke2-cilium                       0/1           94m        94m
helm-install-rke2-coredns                      1/1           13s        95m
helm-install-rke2-ingress-nginx                0/1           94m        95m
helm-install-rke2-kube-proxy                   1/1           12s        95m
helm-install-rke2-metrics-server               0/1           94m        95m

-> cilium does not get installed

kubectl describe job -n kube-system helm-install-rke2-cilium

Pods Statuses:  0 Running / 0 Succeeded / 0 Failed

config.yaml

```
write-kubeconfig-mode: "0640"
cluster-cidr: "172.27.0.0/16"
service-cidr: "172.28.0.0/16"
cluster-dns: "172.28.0.10"
cloud-provider-name: vsphere
cloud-provider-config: /etc/rancher/rke2/vsphere.conf
private-registry: /etc/rancher/rke2/registries.yaml
agent-token: rke-test-token-asfebwadg
token: rke-test-token-asfebwadg
profile: cis-1.5
tls-san:
  - "rke-test.suse"
node-label:
  - "cluster=rke-test"
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
disable: rke2-canal

```

**Expected behavior:**
cilium gets installed and up/running and node gets ready

**Actual behavior:**
cilium does not get installed and node does not get ready

**Comment by Martin-Weiss** [comment]
For some reason the definition of parameters in the chart gets overwritten automatically when I copy the yaml to manifests and this ends up in this situation..

This is what I had in:

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  jobImage: %%REGISTRY%%/%%STAGE%%/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://%%CLUSTER%%.%%DOMAIN%%:9345/static/charts/rke2-cilium-1.9.402.tgz
  bootstrap: true
  set:
    global.rke2DataDir: /var/lib/rancher/rke2
    global.systemDefaultRegistry: "registry01.suse:5000/rke-test/docker.io"

But the file in manifests got changed by rke2 to global.systemDefaultRegistry: "" automatically..

**Comment by brandond** [comment]
The specific use case for system-default-registry is to pass the value into global.systemDefaultRegistry in helm charts for parity with the Rancher UI option. Additionally, system-default-registry should not include a path component.  If you need that behavior, use the registries.yaml endpoint and rewrite support instead of system-default-registry.

**Comment by Martin-Weiss** [comment]
> 
> 
> The specific use case for system-default-registry is to pass the value into global.systemDefaultRegistry in helm charts for parity with the Rancher UI option. Additionally, system-default-registry should not include a path component. If you need that behavior, use the registries.yaml endpoint and rewrite support instead of system-default-registry.

Seems that the challenge exists especially with the cilium chart as this is delivered "out of band".. and different rke2 versions need different handling, now as 1.20.6 supports registry rewrite but 1.19.* and 1.20.4/5 do not..

Is there any chance to get the registry rewrite also into 1.19.*? (have applications that do not support k8s 1.20 before September 2021 - maybe later...)

**Comment by Martin-Weiss** [comment]
> 
> 
> We are working on packaging alternative CNI plugins, which should resolve issues caused by alternative CNIs being more of a bring-your-own affair: #887
> 

Great

> That work currently takes precedence over backporting the trusted CA and registry rewrite stuff, so I would not expect to see those land on any older branches.

At least from the customers I am working with this would be a priority that does not fit to their needs. Most are happy with Canal (they just need something working) but they need 1.19 and they need custom CA and registry rewrite.. however - that needs to be handled and decided by PM..
