### ISSUE TITLE
unable to find a way to set cluster_name

### ISSUE THREAD

**Issue by hectoralicea** [rancher/rke2#912]
installed the latest version.

unable to find a way to set cluster_name in config.yaml or anywhere else.

anyone have any idea?

**Comment by brandond** [comment]
Clusters do not have names. You can set the name for it in your kubeconfig, but the cluster itself has no concept of a name that it stores internally.

**Comment by ianbuilds** [comment]
So, while `local` is the standard name for a local k3s cluster...all other clusters added tend to have names that show up here (see attached). 

- I can create a name via the Rancher GUI when a downstream cluster is created
- But...how can I establish the name of the rke2 cluster that was initially created via a `config.yaml`?

Also, rke (not rke2), installs pass the `cluster_name: <c-name>` in their configuration manifests, is there not a way to do this in rke2?

Just curious. Thanks.

**Comment by brandond** [comment]
Ad I said above, clusters don't know their name internally. You can give it a name in Rancher but the cluster itself does not have anywhere to store that information.
