### ISSUE TITLE
cis-1.6 profile breaks a lot of rancher installed helm charts with the default pod security policies specifically rancher-istio 1.8.300

### ISSUE THREAD

**Issue by mitchtys** [rancher/rke2#913]
**Environmental Info:**
RKE2 Version: 
```
# rke2 -v
rke2 version v1.20.5+rke2r1 (e3d8dc388a5a70b2b9e1355f4708dd8090ba8b05)
go version go1.15.8b5
```
Node(s) CPU architecture, OS, and Version:
 
not applicable really but sles 15 sp2 x86_64

Cluster Configuration:

3 servers, 3 agents, though its largely irrelevant to the bug

**Describe the bug:**

If you install an rke2 cluster with the cis-1.6 profile, like so:

```
tls-san:
  - ip
  - hostname
token: tokentokentoken
protect-kernel-defaults: true
profile: cis-1.6
```

Trying to install istio even with the workarounds documented at:
https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/configuration-reference/rke2/

This will fail due to the default pod security policy, its possible to work around it but this seems to be more pervasive in general than just the istio 1.8.300 helm chart.

If this is better directed to another repo let me know, but I'm starting here to raise the question of how the cis-1.x profiles are tested for all rancher helm charts. 

**Steps To Reproduce:**
The above should cover it. I tested specifically with this terraform configuration and libvirt+kvm:
https://github.com/mitchtys/sles-terraform/blob/rke2/rke2.tf

Mostly just this bunch of shell for the prime master, subsequent masters, and then agents later:
https://github.com/mitchtys/sles-terraform/blob/rke2/rke2.tf#L67-L92

Followed by this block to helm install the rancher ui and then pivot to installing the helm charts.
https://github.com/mitchtys/sles-terraform/blob/rke2/rke2.tf#L190-L209

**Expected behavior:**
I would expect rancher-istio to install without errors even on cis-1.6 hardened rke2 systems.

**Actual behavior:**
```
totally-rational-magpie:~ # kubectl get pods -n istio-system
NAME                       READY   STATUS                       RESTARTS   AGE
istioctl-installer-smhk7   0/1     CreateContainerConfigError   0          3m6s
kiali-854b4f884f-c9clj     1/1     Running                      0          3m8s
totally-rational-magpie:~ # kubectl describe pods -n istio-system istioctl-installer-smhk7 | tail -n 10
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m39s                 default-scheduler  Successfully assigned istio-system/istioctl-installer-smhk7 to conversely-superb-dove
  Normal   Pulling    3m39s                 kubelet            Pulling image "rancher/istio-installer:1.8.3-rancher1"
  Normal   Pulled     3m19s                 kubelet            Successfully pulled image "rancher/istio-installer:1.8.3-rancher1" in 20.260257464s
  Warning  Failed     64s (x12 over 3m19s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "istioctl-installer-smhk7_istio-system(48365bce-4607-44c9-bed9-b17df0093501)", container: istioctl-installer)
  Normal   Pulled     64s (x11 over 3m18s)  kubelet            Container image "rancher/istio-installer:1.8.3-rancher1" already present on machine
```

**Additional context / logs:**
On a less restrictive psp things are fine as expected

**Comment by mitchtys** [comment]
Possibly related to #909 or at least in the same general ballpark problem wise.

**Comment by cjellick** [comment]
There is an overall and ongoing effort to ensure all the rancher feature charts will work seemlessly when a cluster is hardened and PSPs are turned on. That effort lives with the rancher team. I don't know the status of it, but I can say it is a work in progress, so I can explicitly say the combination of these feature charts and rke2 in cis mode has not been validated.

It will be validated as part of that effort, but we need to sync with @deniseschannon and @cloudnautique to find out where that effort is.

**Comment by mitchtys** [comment]
Cool thanks @cjellick we can link that issue in here when we find out then, should help people find things at the very least in the interim how one should proceed until that is complete.

**Comment by mitchtys** [comment]
Since this isn't likely an issue with rke2 proper going to close this out in lieu of the rancher issue.
