### ISSUE TITLE
v1.20.5+rke2r1 failed to attach pvc again

### ISSUE THREAD

**Issue by rory-ye-nv** [rancher/rke2#914]
We have start a 3 server node rke2 cluster, and then deployed a longhorn for storage. the first start up of pod and pvc works fine, but when we delete the pod and start a new pod to attached to the PVC, or when longhorn has some resource problem that the pod failed, we delete the pod and start the pod again, the PVC can't be attached.

https://github.com/longhorn/longhorn/issues/2518

![image](https://user-images.githubusercontent.com/52643407/115648784-a5db6300-a358-11eb-8e13-072e2c4f2783.png)

**Environmental Info:**
RKE2 Version:  v1.20.5+rke2r1 

Node(s) CPU architecture, OS, and Version: 
2 CPU with 48 Cores totally 
Ubuntu 18.04 as host system

Cluster Configuration:
3 servers

**Steps To Reproduce:**
- Installed RKE2: 
- Install longhorn
- install service has pvc
- delete the service but not the pvc
- install the service again

**Expected behavior:**
the pvc can be reused

**Actual behavior:**
- the pvc will failed to attach some times.

**Comment by brandond** [comment]
It appears that the Node doesn't have access to the VolumeAttachments resource for this PV. RKE2 doesn't ship with the storage.k8s.io/VolumeAttachments CRD, so whatever it is that's providing that CRD (Longhorn?) is also responsible for creating the RBAC for it.

**Comment by ruruiye** [comment]
@brandond yes, we use longhorn. but when the pvc is created the first time, and the pod can mount it. is that doesn't require this CRD?

**Comment by shuo-wu** [comment]
Longhorn is responsible for neither creating storage.k8s.io/VolumeAttachments CRD, nor VolumeAttachments CRs during the volume attachment.

**Comment by ruruiye** [comment]
@brandond do you have any idea how to create this manually to fix this problem?

**Comment by brandond** [comment]
Hmm, not sure where that's coming from then. I found a similar report at https://github.com/ceph/ceph-csi/issues/734:

> If the kubelets starts with --enable-controller-attach-detach=false option, then I failed to attach.
> But if the kubelets starts with --enable-controller-attach-detach=true option, then it worked fine.

This flag is true by default, are you by any chance setting it to false with the --kubelet-arg flag?

**Comment by ruruiye** [comment]
@brandond I haven't set any flag on the kubelet-arg when I deploy RKE2

**Comment by mddamato** [comment]
I am having this same problem. It started with one node after I added a replacement server node. If I scale down the deployment and wait for longhorn to catch up, terminate the pod forcefully (it seems to hang), and then scale back up it will work for a while. I am not sure what causes it eventually fail and not be able to come back up.

**Comment by Oats87** [comment]
@ruruiye @mddamato When you are receiving the failure message, is the pod scheduled to a different node than it was originally running on?

**Comment by mddamato** [comment]
Yeah, in my case I only get the failure when the pod is scheduled to a particular node. The problem node is one I added after longhorn and the workloads were originally provisioned. The new node is a server node that replaced another server node that had some problems so it was ditched. Ever since I added the new node the storage has been unreliable and I can only seem to get it to bind some of the time.

**Comment by Oats87** [comment]
> Yeah, in my case I only get the failure when the pod is scheduled to a particular node. The problem node is one I added after longhorn and the workloads were originally provisioned. The new node is a server node that replaced another server node that had some problems so it was ditched. Ever since I added the new node the storage has been unreliable and I can only seem to get it to bind some of the time.

That's great info, thanks. Does your replacement node have a new node name/hostname?

**Comment by ruruiye** [comment]
@mddamato yes, you are right, I am not remove the previous node, but the previous pod is schedule on another node, and bind the pvc on that node. once I deleted the old pod, and reschedule it again, it will schedule to new node, then the pvc bind will failed.

**Comment by mddamato** [comment]
@Oats87 The new node did get a new IP/hostname. I booted a 4th server and once all 4 were healthy I shut down the problem server leaving me with 3 servers total.
