### ISSUE TITLE
vSphere CPI/CSI support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#916]
We agreed to add special behavior is that is triggered by setting `--cloud-provider-name=vsphere`.
* HelmChart Manifests for `rancher-charts/rancher-vsphere-cpi` and `rancher-charts/rancher-vsphere-csi` will be bundled by default, but included in the default `--disable` list.
* Setting `--cloud-provider-name=vsphere` will remove those two charts from the disable list so that they are installed, and fix up the actual cloudprovider name that is passed to the Kubernetes components.
* A separate tarball that includes supporting images for the vSphere CPI and CSI will be produced.

**Comment by rancher-max** [comment]
Used v1.21.0-alpha2+rke2r1 to validate. This isn't fully working, but all of the errors appear to be outside of rke2. See https://github.com/rancher/rancher/issues/32604 for more details. Manually fixing each of these (delete the clusterrole and clusterrolebinding, edit the nodeselector in the cpi daemonset, edit the nodeselector in the csi deployment) allows vsphere CPI/CSI to function correctly.

I will leave this opening pending decisions made on that issue.

**Comment by rancher-max** [comment]
RKE2 will not require any changes for this so closing this issue.
