### ISSUE TITLE
Move channels.yaml into its own repository and create "minor"-specific channels

### ISSUE THREAD

**Issue by Oats87** [rancher/rke2#919]
Today, `channels.yaml` is located in the main `rancher/rke2` repository. We should move `channels.yaml` out of the main `rancher/rke2` repository into its own repository, so that we do not need to run a full blown CI run in order to make simple channels changes. 

We should develop additional channels for the various minor releases, like:
`v1.18-latest`
`v1.18-stable`
`v1.19-latest`
`v1.19-stable`
`v1.20-latest`
`v1.20-stable`
`stable`
`latest`

so that we match our `rancher/rke2-packaging` release strategy and users have more granularity over the series of RKE2 they install, and do not inadvertently jump minor releases.

**Comment by davidnuzik** [comment]
Agreed to move out channels.yaml to its own repository.
- Same for K3S project as well.
- Document this in README.md for each project.
- Replace with single-line channels.yaml comment-ed out explaining where it has moved.

**Comment by caroline-suse-rancher** [comment]
channels.yaml now exists in KDM - closing due to staleness
