### ISSUE TITLE
Re-Test AWS, Azure in-tree cloud provider

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#926]
Related: https://github.com/rancher/rke2/issues/142#issuecomment-680984881

Test and prove that in-tree azure cloud provider works with RKE2.
After discussing with QA, it's been some time since we checked AWS as well. Ensure this is still working as expected.

**Comment by rancher-max** [comment]
#### Validated using v1.21.1-alpha5+rke2r1

Both Azure and AWS Cloud providers are still working correctly. No additional information to add as steps remain the same.
