### ISSUE TITLE
Move go-containerregistry wrapper code out to a library

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#928]
TODO: flesh out this issue
Move go-containerregistry stuff out to a library for use by https://github.com/rancher/system-agent/ (for supporting registries.yaml, unpacking files to disk, etc)

**Comment by brandond** [comment]
Implementation available, waiting for @Oats87 to let me know if he needs anything else.

**Comment by davidnuzik** [comment]
@Oats87 or @brandond can you linked to the merged PR here for QA? Must link the PR(changes) before moving an issue to test.

**Comment by Oats87** [comment]
@davidnuzik are you asking for the PR for RKE2 or `system-agent`? I did not do the `rke2` integration.

**Comment by brandond** [comment]
There isn't any ask here for QA - this is a tracking issue for creating the new project and moving code into it for Chris, and I'd left it in To Test to track his acceptance of the code for the agent. There are separate issues for having k3s and rke2 use the wharfie code.

**Comment by davidnuzik** [comment]
@Oats87 if you are satisfied with the new project please close this issue. Thanks
