### ISSUE TITLE
Add support for kubelet image credential providers

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#929]
TODO: flesh out this issue
Once #928 is done - add support for kubelet image credential provider plugins:  
https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/

**Comment by brandond** [comment]
ECR: https://github.com/kubernetes/cloud-provider-aws/tree/master/cmd/ecr-credential-provider
GCR: https://github.com/kubernetes/cloud-provider-gcp/tree/master/cmd/auth-provider-gcp
ACR: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/289

**Comment by brandond** [comment]
Implementation available, waiting for @Oats87 to let me know if he needs anything else.

**Comment by rancher-max** [comment]
This encounters the same errors as mentioned in https://github.com/k3s-io/k3s/issues/3280#issuecomment-843644882. Steps are the same. Tested in v1.21.1-alpha5+rke2r1

**Comment by davidnuzik** [comment]
Close in favor https://github.com/k3s-io/k3s/issues/3280
