### ISSUE TITLE
Dual-Stack clusters can be provisioned with Calico CNI plugin

### ISSUE THREAD

**Issue by janeczku** [rancher/rke2#937]
**User Story**

As a cluster admin, i want to be able to provision dual-stack RKE2 clusters using a Calico-managed network stack.

**Expected behavior**

**Given** that the compute nodes meet the [requirements for Kubernetes dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/) (e.g. have IPv6 host interface, etc.)
**When** providing a RKE2 configuration file that specifies IPv6 network assignments (`service-cidr`/`cluster-cidr`)  and selects Calico as `cni`
**Then** a fully functional IPv4/IPv6 dual-stack cluster is created that passes the [upstream validation steps](https://kubernetes.io/docs/tasks/network/validate-dual-stack/) for pod and service addressing.

**References**

- https://github.com/rancher/rke2/issues/860
- https://github.com/rancher/rke2/issues/870

**Comment by manuelbuil** [comment]
This should be already possible to do deploying version `v1.21.0-alpha-rke2r1` and using `--cni calico`. Note that the upstream documentation for the calico-helm is very limited. IPv6 is apparently enabled based on the IPPools provided in the installation resource (which is what can be modified in the values of the helm chart)

**Comment by janeczku** [comment]
Thanks for the info @manuelbuil, good to know that the required configuration options are exposed as Helm values.

**Comment by fbettag** [comment]
i tried to verify this, but after setting up with --cni calico, pod init of calico-node bugs out with that no CIDR is configured, even tho the same service-cidr/pod-cidr work with cilium.

**Comment by manuelbuil** [comment]
> i tried to verify this, but after setting up with --cni calico, pod init of calico-node bugs out with that no CIDR is configured, even tho the same service-cidr/pod-cidr work with cilium.

what version of rke2 are you using? Apart form `--cni calico`, did you choose other config options?

**Comment by fbettag** [comment]
> > i tried to verify this, but after setting up with --cni calico, pod init of calico-node bugs out with that no CIDR is configured, even tho the same service-cidr/pod-cidr work with cilium.
> 
> what version of rke2 are you using? Apart form `--cni calico`, did you choose other config options?

Rke2 alpha5 and standard calico that comes with cni specified

**Comment by manuelbuil** [comment]
> > > i tried to verify this, but after setting up with --cni calico, pod init of calico-node bugs out with that no CIDR is configured, even tho the same service-cidr/pod-cidr work with cilium.
> > 
> > 
> > what version of rke2 are you using? Apart form `--cni calico`, did you choose other config options?
> 
> Rke2 alpha5 and standard calico that comes with cni specified

Strange, I can't reproduce it. According to the code, it should get the value of kube-controller-manager `--cluster-cidr`. Can you post the output of `kubectl get ippools default-ipv4-ippool -o yaml` please?

**Comment by fbettag** [comment]
I switched to cilium as it works there 🤷‍♂️

**Comment by Mtze** [comment]
This would be very helpful!

**Comment by manuelbuil** [comment]
This works already! https://docs.rke2.io/install/network_options/#dual-stack-configuration

**Comment by Mtze** [comment]
Thanks for the hint!
