### ISSUE TITLE
klipper helm splitting on commas causing helm install failures

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#948]
**Environmental Info:**
RKE2 Version: 

v1.21.0-alpha2

Node(s) CPU architecture, OS, and Version: 

Ubuntu 20.04 LTS

Cluster Configuration:

1 server

**Describe the bug:**

When a helm chart has values such as:
```
set:
    global.clusterCIDR: '[192.168.0.1/16,2600:1f1c:ab4:ee48::/48]'
    global.serviceCIDR: '[192.168.0.2/16,2600:1f1c:ab4:ee49::/108]'
```
The resulting helm pod fails to install due to a split on the comma:
```
helm_v3 install --set-string 'global.clusterCIDR=[192.168.0.1/16' '2600:1f1c:ab4:ee48::/48]' --set-string 'global.serviceCIDR=[192.168.0.2/16' '2600:1f1c:ab4:ee49::/108]' rke2-coredns /rke2-coredns.tgz
Error: expected at most two arguments, unexpected arguments: rke2-coredns, /rke2-coredns.tgz
```

**Steps To Reproduce:**

- Install rke2 with dual stack cluster and/or service cidr.

**Expected behavior:**

helm pods should at least attempt the install without parsing errors

**Actual behavior:**

parsing errors in the helm pods due to:
`--set-string 'global.clusterCIDR=[192.168.0.1/16' '2600:1f1c:ab4:ee48::/48]'` should be:
`--set-string 'global.clusterCIDR=192.168.0.1/16,2600:1f1c:ab4:ee48::/48'`

**Additional context / logs:**

**Comment by brandond** [comment]
The version of urfave/cli we're using has a bug where accessing a StringSliceFlag as a StringSlice gives you back an improperly formatted string. You can see a minimal example here - https://play.golang.org/p/IPLb0LgsdkY - compare what happens with v1.22.2 vs v1.22.5.

The second part of this is going to need a fix to klipper-helm, as it appears that commas need to be backslash-escaped in --set/--set-string values: https://github.com/helm/helm/issues/1556

**Comment by rancher-max** [comment]
#### Validated in v1.21.1-rc1+rke2r1

- Using the same steps now succeeds on the helm jobs: `helm_v3 install --set-string 'global.clusterCIDR=10.42.0.0/16\,2001:db8:42::/56' --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string 'global.serviceCIDR=10.43.0.0/16\,2001:db8:42:1::/112' --set-string global.systemDefaultRegistry= rke2-cilium /rke2-cilium.tgz --values /config/values-10_HelmChartConfig.yaml`
- All nodes and pods become up and running successfully
