### ISSUE TITLE
Use rancher/wharfie code for bootstrap

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#958]
* Pull through work from k3s-io/k3s#3280.
* Remove code from RKE2 that has been moved to rancher/wharfie; use wharfie instead.
* Use `--image-credential-provider` flags to enable credential provider support when pulling bootstrap images.

**Comment by rancher-max** [comment]
This is validated on v1.21.1-alpha5+rke2r1

- All mirror private registry functionality still working as expected
- system-default-registry still working as expected
- Setting airgap-extra-registry still working as expected
- Airgap installs via tarball still working as expected

No new functionality to report here so steps remain the same and leaving them out here for brevity.

Note the `image-credential-provider` functionality encounters the same errors as noticed in the linked k3s issue. Closing this in favor of https://github.com/rancher/rke2/issues/929 for those.
