### ISSUE TITLE
Add support for deployment ordering to helm-controller

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#960]
In order to support deployment of an ordered set of CNI plugins along side multus, helm-controller needs to support some sort of time-delay sequencing or dependency injection.

For example, the rancher-sriov chart needs to be deployed after the rke2-multus and rke2-canal and charts the rancher-sriov chart waiting for some sort of infrastructure from the previous charts to be present and healthy (pods, services, etc) before continuing.

There are existing charts that also need this (for example, main charts that depend on -crd charts) but these currently work around the lack of sequencing by just retrying until the CRDs are present.

**Comment by fapatel1** [comment]
@brandond @manuelbuil to sync up with team to decide if this is a blocker

**Comment by manuelbuil** [comment]
> @brandond @manuelbuil to sync up with team to decide if this is a blocker

We decided to move the sriov helm chart to rancher to avoid this. Therefore, I don't think this is a blocker

**Comment by caroline-suse-rancher** [comment]
Closing, as this is no longer relevant
