### ISSUE TITLE
api server still have port open after sudo systemctl stop rke2-server.service

### ISSUE THREAD

**Issue by SebTardif** [rancher/rke2#963]
Using v1.20.6+rke2r1, the only command used to start/install is: sudo systemctl start rke2-server.service
That end-up starting the api.

So I would think the similar command to stop will disconnect it, but no, when I do: sudo systemctl stop rke2-server.service -> the api is still answering 401 when calling myip:6443

**Comment by brandond** [comment]
Stopping rke2 only stops the supervisor. All pods, including the static pods running the control-plane components, remain running. This is by design; if you want to kill all the pods you can run the rke2-killall.sh script.
