### ISSUE TITLE
Kube-Controller-Manager x509 to air-gapped EC2 endpoint

### ISSUE THREAD

**Issue by mvanhemert** [rancher/rke2#965]
**Environmental Info:**

RKE2 Version: 1.20.6

Node(s) CPU architecture, OS, and Version: 
Linux ip-x-x-x-x.[region].compute.internal 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Mar 25 14:36:04 EDT 2021 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Currently: 1 server. Desired: 3 servers, 32 agents

**Describe the bug:**

kube-controller-manager experiences an error initializing the cloud provider "aws" with an x509 certificate error from the EC2 service endpoint and falls into a CrashLoopBackOff cycle.

**Steps To Reproduce:**

- Configure STIG'd RHEL 8.3 host with tls-ca-bundle.pem from Alinux instance (per AWS Support direction) by placing file directly into /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
- Add `AWS_CA_BUNDLE` environment variable to `/etc/profile.d/sh.local` pointing to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`
- Install RKE2 following [these steps](https://susergs.com/installing-rke-government-in-airgap-environments/) with this [additional configuration](https://docs.rke2.io/advanced/#installation-on-classified-aws-regions-or-networks-with-custom-aws-api-endpoints).

**Expected behavior:**

kube-controller-manager runs successfully

**Actual behavior:**

kube-controller-manager fails to run successfully

**Additional context / logs:**

kube-controller-manager log (note: manually typed from air-gapped env, sorry for typos):
```
controllermanager.go:176] Version: v1.20.6+rke2r1
deprecated_insecure_serving.go:53] Serving insecurely on 127.0.0.1:10252
leaderelection.go:243] attempting to acquire leader lease kube-system/kube-controller-manager...
leaderelection.go:253] successfully acquired lease kube-system/kube-controller-manager
event.go:291] "Event occurred" object="kube-system/kube-controller-manager" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="ip-x-x-x-x.[region].compute.internal_b1040dfb-a36e-4306-b2d6-ebe266b75e5d became leader"
plugins.go:105] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
aws.go:1261] Building AWS cloudprovider
aws.go:1221] Zone not specified in configuration file; querying AWS metadata service
controllermanager.go:245] error building controller context: cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-xxxxxxxxxxxx: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post \\\"https://ec2.[region].[domain]/\\\": x509: certificate signed by unknown authority\""
```

RKE2 config.yaml:
```
bind-address: "x.x.x.x"
write-kubeconfig-mode: "0644"
selinux: true
profile: "cis-1.5"
cloud-provider-name: "aws"
cloud-provider-config: "/etc/rancher/rke2/cloud.conf"
protect-kernel-defaults: true
disable: "rke2-ingress-nginx"
```

cloud.conf:
```
[Global]
[ServiceOverride "ec2"]
  Service=ec2
  Region=[region]
  URL=https://ec2.[region].[domain]
  SigningRegion=[region]
[ServiceOverride "elasticloadbalancing"]
  Service=elasticloadbalancing
  Region=[region]
  URL=https://elasticloadbalancing.[region].[domain]
  SigningRegion=[region]
```

Other configuration:
- Instance is assigned a role with policies matching [these values](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/)
- AWS CLI works on the instance with only AWS_CA_BUNDLE defined and the role identified above 
- `openssl s_connect ec2.[region].[domain]:443 -debug -CAfile /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` is successful

**Comment by mvanhemert** [comment]
Labels from `kubectl get no --show-labels` (manually typed 😭) - both before and after the step from the previous comment:

```
beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.4xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=[region],failure-domain.beta.kubernetes.io/zon=[zone],kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-x-x-x-x.[region].compute.internal,kubernetes.io/os=linux,node=role.kubernetes.io/controle-plane=true,node=role.kubernetes.io/etcd=true,node-role.kubernetes.io/master=true,node.kubernetes.io/instance-type=m5.4xlarge,topology.kubernetes.io/region=pregion],topology.kubernetes.io/zone=[region]
```

**Comment by brandond** [comment]
QA validates use of the in-tree cloud provider (--cloud-provider=aws) on a regular basis, so I don't think the issue is on that side. The gap is probably with use of the AWS_CA_BUNDLE variable - RKE2 is not aware of this and will not use it nor pass it through to static pods. If you need to inject custom certs into the system trust store, you need to be sure you're placing them into whatever path is appropriate for the Linux distribution you're installing RKE2 on. Here are the distribution-specific PKI trust store paths we check:

https://github.com/rancher/rke2/blob/e8b3547bb9e01e5c99209a1b60ba22b4ff7efc45/pkg/podexecutor/staticpod.go#L30-L36

**Comment by brandond** [comment]
No, that wont work. That symlink will be broken within the pod because /etc/pki/ca-trust/ is not mounted.

**Comment by mvanhemert** [comment]
I placed the CA bundle into `/etc/ssl/certs` as `ca-bundle.crt` and separately `ca-bundle.pem` careful to restart the kube-controller-manager but it is still getting the x509 error.

**Comment by brandond** [comment]
Can you confirm that the cert is actually trusted according to your bundle? Something along the lines of:
`openssl s_client -verifyCApath /etc/ssl/certs -connect ec2.region.domain:443`

Note that other folks have been able to get RKE2 working in C2S environments: https://github.com/rancher/rke2/issues/814#issuecomment-818404130

**Comment by mvanhemert** [comment]
`openssl s_client -verifyCApath /etc/ssl/certs -connect ec2.region.domain:443` worked well.

I haven't read through 814 yet but will definitely review.

We `-it exec /bin/bash` into `kube-controller-manager` and `ls -lah /etc/ssl/certs` gives `permission denied`. Continuing down this path.

**Comment by mddamato** [comment]
The two certs directories (/etc/ssl/certs and /etc/pki/tls/certs, apparently symlinked together) appears to be blocked by SELinux in my testing 
```
type=AVC msg=audit(1620680325.183:179): avc:  denied  { read } for  pid=10290 comm="kube-controller" name="ca-bundle.crt" dev="nvme0n1p1" ino=353854 scontext=system_u:system_r:rke2_service_t:s0:c698,c870 tcontext=system_u:object_r:cert_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1620680325.192:180): avc:  denied  { read } for  pid=10290 comm="kube-controller" name="certs" dev="nvme0n1p1" ino=353853 scontext=system_u:system_r:rke2_service_t:s0:c698,c870 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=1
```

**Comment by dweomer** [comment]
@mddamato if you are able please try laying down the el8 rpm at https://github.com/rancher/rke2-selinux/releases/tag/v0.6.testing.1 prior to installing rke2 (which should satisfy the rke2-selinux dependency) and let me know if the same or similar denials are encountered

**Comment by mddamato** [comment]
I'd like to add that this may actually be a legitimate way to configure things, adding the certs to `/etc/pki/tls/certs/my_ca.pem` that is. The docs just specify otherwise and there might be other reasons to stick to the standard update-ca-trust process

**Comment by dweomer** [comment]
> @dweomer we added specific code to only mount SSL dirs if they already exist on the host, because DirectoryOrCreate was creating things and breaking on hosts with read-only root filesystems.
> 
> I think the correct fix is to just place the bundle into one of the supported SSL dirs, without all the extraneous symlinking.

I disagree. As mentioned in our Slack convo about this issue, symlinking happens. We can be somewhat permissive by rolling up to `/etc/pki` and `/etc/ssl` instead of the deeper paths to allow for heavily symlinked systems (it won't work for all but it will for most stock-ish systems). That said, what you propose is a reasonable workaround until we address it in our code. @mddamato I assume that this gives you a way forward at least?

**Comment by brandond** [comment]
A common concern about going up a level to `/etc/pki` is that this level would also end up mounting `/etc/pki/tls/private` which may contain other keys and confidential material that the control-plane components have no real need to access.

**Comment by rancher-max** [comment]
Validated all release channels: `testing`, `latest`, and `stable` to ensure they have the changes. Also validated install using these channels on rke2 versions v1.19.10, v1.20.6, and v1.21.1-alpha4 have the necessary rpm changes for selinux. Finally, validated the steps noted here https://github.com/rancher/rke2/issues/965#issuecomment-838893727 (ignoring step 1 now) and also see this working in an airgap, selinux, ca bundle aws system.
