### ISSUE TITLE
kubectl port-forward leads to "error: error upgrading connection: error dialing backend: dial tcp: lookup <NODENAME> on <DNSSERVER>:53: no such host"

### ISSUE THREAD

**Issue by Sicaine** [rancher/rke2#975]
**Environmental Info:**
RKE2 Version: rke2 version v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: amd, 16 core

Cluster Configuration: 3 controler 1 worker; all configured with internal ip in range of 10....

**Describe the bug:**
I just created a basic rke2 cluster out of 3 controller and one worker node. When i installed argocd and tried a port-forward with kubectl, the error message "error: error upgrading connection: error dialing backend: dial tcp: lookup <WORKER NODE> on <DNS SERVER>:53: no such host"

I found an old k8s bug where the workaround was to add the name of the worker node to the controller but i have to assume that this is some kind of bug or missconfiguration.
I did configure the node-ip with the local ips and kubectl get nodes -o wide shows those ips; its just not clear why the kubernetes proxy tries to resolve the node name and fails.

**Steps To Reproduce:**
i have 4 nodes all with internal ips;

This is the config:
write-kubeconfig-mode: "0644"
tls-san:
  - "loadbalancerurl"
advertise-address: {{ node_ip }}
node-ip: {{ node_ip }}
disable:
  - rke2-canal
cluster-cidr: 172.16.0.0/16
service-cidr: 192.168.0.0/18
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
node-label:
  - "foo=bar"
  - "something=amazing"

Network is cilium

Installation is through the curl step and enabling/starting the service

**Expected behavior:**
I would assume a port-forward just works

**Actual behavior:**
port-forward fails

**Additional context / logs:**

**Comment by Sicaine** [comment]
Apparently there was already a bug opened for this: https://github.com/rancher/rke2/issues/637

**Comment by Sicaine** [comment]
I would try to fix it as in #637 but would keep this open as a bug?

**Comment by brandond** [comment]
Kubernetes expects that node hostnames and IP addresses will be static for the life of the node. Are you saying that your nodes might have dynamic hostnames and/or IP addresses?

**Comment by brandond** [comment]
`kubectl port-forward` and `kubectl logs` are somewhat unique commands in that they both require the apiserver to initiate a connection to the node. In order to connect to the node, the apiserver has to be able to resolve its hostname to an address.

**Comment by Sicaine** [comment]
Sry to ask again but i still don't understand it:

How would any node know the ip address based on the other nodes hostname?

I'm only installing rke2 with the internal ips and there was no mentioning, in the installation guide, on keeping all hostnames and ip addresses on all nodes.

or does port-forward and logs don't work in rke2?

**Comment by brandond** [comment]
> How would any node know the ip address based on the other nodes hostname?

The same way any host finds another host on the internet - by asking a DNS server?

**Comment by Sicaine** [comment]
> > How would any node know the ip address based on the other nodes hostname?
> 
> The same way any host finds another host on the internet - by asking a DNS server?

If i understand you correctly, you assume that rke2 is always installed in an environment where all nodes use the same dns server/dhcp server which then is able to resolve all hostnames of all local nodes?

My previous setup with kubeadm did work in this environment without configuring DNS server though.

**Comment by brandond** [comment]
Yes, RKE2 is targeted for regulated corporate or governmental environments where functioning internal DNS can be assumed to exist. If you want something a little more lightweight, you might check out k3s, which manages node dns resolution internally.

**Comment by Sicaine** [comment]
I will recreate this issue and describe it more directly and collecting the k8s bug from for 4 years.

Tx i think i get now the issue on hand. Unfortunate i don't know what rke2 is doing differently than kubeadm
