### ISSUE TITLE
Need means to enable feature gates for api-server

### ISSUE THREAD

**Issue by AaronJaegerVA** [rancher/rke2#978]
I can find no way to enable feature gates for the api-server in a rke2 cluster. Did I miss something?

**Comment by brandond** [comment]
Have you seen https://docs.rke2.io/install/install_options/server_config/#:~:text=--kube-apiserver-arg 

`--kube-apiserver-arg=feature-gate=X-true`

**Comment by AaronJaegerVA** [comment]
I was looking on that page, but didn't put together how those options should be specified. Are you sure it isn't `feature_gates=` ? The [docs](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) here make it seem so. 

How would it work with the config file? I'm thinking:

```
kube-apiserver-arg: '--feature-gates=<feature>=true'
```

**Comment by brandond** [comment]
Yes, there was a typo. For the config file you can do something like this:

```yaml
kube-apiserver-arg:
  - feature-gates=X=true,Y=false
```

**Comment by AaronJaegerVA** [comment]
Great. I'll give it a go and report back.

**Comment by AaronJaegerVA** [comment]
It worked! Thank you @brandond
